
ANIMATE_PALETTE_FADE_WITH_RENDERING:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL02
	LDX #.LOWORD(-1)
	LDA @VIRTUAL02
	JSL PREPARE_PALETTE_FADE
	LDA #0
	STA @LOCAL00
	BRA @FADE_LOOP_CHECK
@FADE_STEP:
	JSL UPDATE_MAP_PALETTE_ANIMATION
	JSL OAM_CLEAR
	JSL RUN_ACTIONSCRIPT_FRAME
	JSL UPDATE_SCREEN
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA @LOCAL00
	INC
	STA @LOCAL00
@FADE_LOOP_CHECK:
	CMP @VIRTUAL02
	BCC @FADE_STEP
	JSL FINALIZE_PALETTE_FADE
	END_C_FUNCTION
