
ANIMATE_PALETTE_FADE_TO_MAP:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL02
	STA @VIRTUAL02
	PROMOTENEARPTR MAP_PALETTE_BACKUP, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	TXA
	JSL LOAD_PALETTE_TO_FADE_BUFFER
	LDY @LOCAL02
	TYX
	LDA @VIRTUAL02
	JSL PREPARE_PALETTE_FADE
	LDA @VIRTUAL02
	CMP #1
	BEQ @AFTER_FADE
	LDA #0
	STA @LOCAL01
	BRA @FADE_LOOP_CHECK
@FADE_STEP:
	JSL UPDATE_MAP_PALETTE_ANIMATION
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA @LOCAL01
	INC
	STA @LOCAL01
@FADE_LOOP_CHECK:
	CMP @VIRTUAL02
	BCC @FADE_STEP
@AFTER_FADE:
	JSL FINALIZE_PALETTE_FADE
	LDA #24
	JSL SET_PALETTE_UPLOAD_MODE
	END_C_FUNCTION
