
ANIMATE_MAP_PALETTE_CHANGE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TXY
	STY @LOCAL01
	TAX
	JSR LOAD_MAP_PALETTE_ANIMATION_FRAME
	LDY @LOCAL01
	TYA
	JSL INITIALIZE_MAP_PALETTE_FADE
	BRA @FADE_LOOP_CHECK
@CHECK_INPUT:
	LDA PAD_PRESS
	BEQ @UPDATE_FADE
	LDA #.LOWORD(-1)
	BRA @RETURN
@UPDATE_FADE:
	JSL UPDATE_MAP_PALETTE_FADE
	JSL WAIT_UNTIL_NEXT_FRAME
	LDY @LOCAL01
	DEY
	STY @LOCAL01
@FADE_LOOP_CHECK:
	LDY @LOCAL01
	BNE @CHECK_INPUT
	LOADPTR BUFFER + $7800, @LOCAL00
	LDX #BPP4PALETTE_SIZE * 6
	LDA #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 2
	JSL MEMCPY16
	LDA #0
@RETURN:
	END_C_FUNCTION
