
APPLY_PALETTE_BRIGHTNESS_ALL:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL02
	LDY #0
	STY @LOCAL00
	BRA @PALETTE_LOOP_CHECK
@PALETTE_LOOP_BODY:
	LDX @VIRTUAL02
	TYA
	JSR ADJUST_PALETTE_BRIGHTNESS
	LDY @LOCAL00
	INY
	STY @LOCAL00
@PALETTE_LOOP_CHECK:
	CPY #16
	BCC @PALETTE_LOOP_BODY
	SEP #PROC_FLAGS::ACCUM8
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
