
CLAMP_COLOR_CHANNEL:
	BEGIN_C_FUNCTION
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	CMP #$8000
	BLTEQ @NOT_NEGATIVE
	LDA #0
	BRA @RETURN
@NOT_NEGATIVE:
	CMP #31
	BLTEQ @NOT_OVER_MAX
	LDA #31
	BRA @RETURN
@NOT_OVER_MAX:
	AND #$001F
@RETURN:
	END_C_FUNCTION
