
FADE_TO_MAP_MUSIC_AT_LEADER:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA #$0001
	STA DO_MAP_MUSIC_FADE
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL RESOLVE_MAP_SECTOR_MUSIC
	LDA NEXT_MAP_MUSIC_TRACK
	CMP CURRENT_MAP_MUSIC_TRACK
	BEQ @DONE
	JSL WAIT_UNTIL_NEXT_FRAME
	JSL APPLY_NEXT_MAP_MUSIC
@DONE:
	STZ DO_MAP_MUSIC_FADE
	RTS
