
LOAD_PALETTE_TO_FADE_BUFFER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	STA @VIRTUAL02
	MOVE_INT @PARAM01, @VIRTUAL0A
	LOADPTR BUFFER, @VIRTUAL06
	LDY #0
	STY @LOCAL00
	BRA @LOOP_CHECK
@LOOP_BODY:
	LDA [@VIRTUAL0A]
	INC @VIRTUAL0A
	INC @VIRTUAL0A
	LDX @VIRTUAL02
	JSR FADE_PALETTE_COLOR
	STA [@VIRTUAL06]
	INC @VIRTUAL06
	INC @VIRTUAL06
	LDY @LOCAL00
	INY
	STY @LOCAL00
@LOOP_CHECK:
	CPY #256
	BCC @LOOP_BODY
	END_C_FUNCTION
