
LOAD_BG_PALETTE:
	ASL
	TAX
	LDA f:PALETTE_ANIM_BUFFER_PTR_TABLE,X
	TAX
	LDY #$0240
	LDA #$00BF
	MVN #$7E,#$7E
	SEP #PROC_FLAGS::ACCUM8
	LDA #PALETTE_UPLOAD::BG_ONLY
	STA PALETTE_UPLOAD_MODE
	REP #PROC_FLAGS::ACCUM8
	RTL
