
PREPARE_MAP_PALETTE_FADE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	LDY #.LOWORD(MAP_PALETTE_BACKUP)
	JSR PREPARE_PALETTE_FADE_SLOPES
	END_C_FUNCTION
