
PREPARE_PALETTE_FADE_SLOPES:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL08
	STX @LOCAL07
	STA @LOCAL06
	LOADPTR BUFFER, @VIRTUAL06
	LOADPTR BUFFER + $200, @LOCAL00
	LDX #$1000
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL MEMSET24
	STZ @LOCAL05
	JMP @OUTER_LOOP_CHECK
@PROCESS_GROUP:
	LDA @LOCAL05
	STA @LOCAL04
	JMP @INNER_LOOP_CHECK
@CALC_COLOR_SLOPES:
	.A16
	LDA @LOCAL07
	AND #$0001
	BEQ @READ_FROM_TARGET
	LDA @LOCAL04
	ASL
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	STA @VIRTUAL02
	BRA @CALC_SLOPES
@READ_FROM_TARGET:
	LDA @LOCAL04
	ASL
	STA @LOCAL03
	TAY
	LDA (@LOCAL08),Y
	STA @VIRTUAL02
	LDA @LOCAL03
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA @VIRTUAL02
	STA [@VIRTUAL0A]
@CALC_SLOPES:
	LDA @LOCAL04
	ASL
	STA @VIRTUAL04
	LDY @VIRTUAL04
	LDA (@LOCAL08),Y
	STA @LOCAL02
	LDY @LOCAL06
	LDA @VIRTUAL02
	AND #$001F
	TAX
	LDA @LOCAL02
	AND #$001F
	JSR GET_COLOUR_FADE_SLOPE
	.A16
	LDX @VIRTUAL04
	STA BUFFER + $200,X
	LDY @LOCAL06
	LDA @VIRTUAL02
	AND #$03E0
	LSR
	LSR
	LSR
	LSR
	LSR
	TAX
	LDA @LOCAL02
	AND #$03E0
	LSR
	LSR
	LSR
	LSR
	LSR
	JSR GET_COLOUR_FADE_SLOPE
	LDX @VIRTUAL04
	STA BUFFER + $400,X
	LDY @LOCAL06
	STY @LOCAL01
	LDY #$0400
	LDA @VIRTUAL02
	AND #$7C00
	JSL DIVISION16S_DIVISOR_POSITIVE
	TAX
	LDY #$0400
	LDA @LOCAL02
	AND #$7C00
	JSL DIVISION16S_DIVISOR_POSITIVE
	LDY @LOCAL01
	JSR GET_COLOUR_FADE_SLOPE
	LDX @VIRTUAL04
	STA BUFFER + $600,X
	INC @LOCAL04
@INNER_LOOP_CHECK:
	LDA @LOCAL05
	CLC
	ADC #16
	CMP @LOCAL04
	BGTL @CALC_COLOR_SLOPES
	LDA @LOCAL05
	STA @LOCAL03
	BRA @EXTRACT_LOOP_CHECK
@EXTRACT_CHANNELS:
	ASL
	STA @VIRTUAL02
	CLC
	ADC @LOCAL08
	TAX
	STX @LOCAL02
	LDA __BSS_START__,X
	AND #$001F
	XBA
	AND #$FF00
	LDX @VIRTUAL02
	STA BUFFER + $800,X
	LDX @LOCAL02
	LDA __BSS_START__,X
	AND #$03E0
	ASL
	ASL
	ASL
	LDX @VIRTUAL02
	STA BUFFER + $A00,X
	LDX @LOCAL02
	LDA __BSS_START__,X
	AND #$7C00
	LSR
	LSR
	LDX @VIRTUAL02
	STA BUFFER + $C00,X
	LDA @LOCAL03
	INC
	STA @LOCAL03
@EXTRACT_LOOP_CHECK:
	LDA @LOCAL05
	CLC
	ADC #16
	STA @VIRTUAL02
	LDA @LOCAL03
	CMP @VIRTUAL02
	BCC @EXTRACT_CHANNELS
	LDA @LOCAL07
	LSR
	STA @LOCAL07
	LDA @VIRTUAL02
	STA @LOCAL05
@OUTER_LOOP_CHECK:
	LDA @LOCAL05
	CMP #256
	BCCL @PROCESS_GROUP
	END_C_FUNCTION
