
PREPARE_PALETTE_FADE_FROM_CURRENT:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAY
	STY @LOCAL02
	PROMOTENEARPTR PALETTES, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDA #^PALETTES
	STA @LOCAL01+2
	MOVE_INT @LOCAL01, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #100
	JSL LOAD_PALETTE_TO_FADE_BUFFER
	LDX #.LOWORD(-1)
	LDY @LOCAL02
	TYA
	JSL PREPARE_PALETTE_FADE
	END_C_FUNCTION
