
RUN_FRAMES_UNTIL_FADE_DONE:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	BRA @CHECK_FADE
@FRAME_LOOP:
	JSL OAM_CLEAR
	JSL RUN_ACTIONSCRIPT_FRAME
	JSL UPDATE_SCREEN
	JSL WAIT_UNTIL_NEXT_FRAME
@CHECK_FADE:
	LDA FADE_PARAMETERS + fade_parameters::step
	AND #$00FF
	BNE @FRAME_LOOP
	RTS
