
SET_COLOR_MATH_FROM_TABLE:
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:COLOR_MATH_REGISTER_TABLE,X
	STA TM_MIRROR
	LDA f:COLOR_MATH_REGISTER_TABLE+11,X
	STA TD_MIRROR
	LDA f:COLOR_MATH_REGISTER_TABLE+21,X
	STA f:CGWSEL
	LDA f:COLOR_MATH_REGISTER_TABLE+31,X
	STA f:CGADSUB
	REP #PROC_FLAGS::ACCUM8
	RTL
