
SCROLL_MAP_TO_POSITION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @VIRTUAL04
	TAY
	STY @LOCAL01
	STY BG2_X_POS
	STY BG1_X_POS
	LDA @VIRTUAL04
	STA BG2_Y_POS
	LDA @VIRTUAL04
	STA BG1_Y_POS
	TYA
	AND #$8000
	BEQ @X_POSITIVE
	TYA
	LSR
	LSR
	LSR
	ORA #$E000
	STA @LOCAL00
	BRA @X_DIVIDED
@X_POSITIVE:
	TYA
	LSR
	LSR
	LSR
	STA @LOCAL00
@X_DIVIDED:
	LDA @VIRTUAL04
	AND #$8000
	BEQ @Y_POSITIVE
	LDA @VIRTUAL04
	LSR
	LSR
	LSR
	ORA #$E000
	STA @VIRTUAL02
	BRA @HSCROLL_DONE_CHECK
@Y_POSITIVE:
	LDA @VIRTUAL04
	LSR
	LSR
	LSR
	STA @VIRTUAL02
	BRA @HSCROLL_DONE_CHECK
@HSCROLL_CHECK_DIR:
	AND #$8000
	BEQ @HSCROLL_LEFT
	LDA SCREEN_LEFT_X
	INC
	STA SCREEN_LEFT_X
	LDX @VIRTUAL02
	CLC
	ADC #32
	JSR CLEAR_MAP_COLUMN_VRAM
	BRA @HSCROLL_DONE_CHECK
@HSCROLL_LEFT:
	LDA SCREEN_LEFT_X
	DEC
	STA SCREEN_LEFT_X
	LDX @VIRTUAL02
	DEC
	JSR CLEAR_MAP_COLUMN_VRAM
@HSCROLL_DONE_CHECK:
	LDA SCREEN_LEFT_X
	SEC
	SBC @LOCAL00
	BNE @HSCROLL_CHECK_DIR
	BRA @VSCROLL_DONE_CHECK
@VSCROLL_CHECK_DIR:
	AND #$8000
	BEQ @VSCROLL_UP
	LDA SCREEN_TOP_Y
	INC
	STA SCREEN_TOP_Y
	CLC
	ADC #28
	TAX
	LDA @LOCAL00
	JSR CLEAR_MAP_ROW_VRAM
	BRA @VSCROLL_DONE_CHECK
@VSCROLL_UP:
	LDX SCREEN_TOP_Y
	DEX
	STX SCREEN_TOP_Y
	DEX
	LDA @LOCAL00
	JSR CLEAR_MAP_ROW_VRAM
@VSCROLL_DONE_CHECK:
	LDA SCREEN_TOP_Y
	SEC
	SBC @VIRTUAL02
	BNE @VSCROLL_CHECK_DIR
	LDY @LOCAL01
	STY BG12_POSITION_X_COPY
	LDA @VIRTUAL04
	STA BG12_POSITION_Y_COPY
	END_C_FUNCTION
