
START_CAMERA_SHAKE:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA #$000C
	STA CAMERA_MODE_3_FRAMES_LEFT
	LDX #.LOWORD(GAME_STATE) + game_state::camera_mode
	LDA __BSS_START__,X
	STA CAMERA_MODE_BACKUP
	LDA #$0003
	STA __BSS_START__,X
	LDA #$0002
	JSL WRITE_APU_PORT1
	LDA #$0001
	STA OVERWORLD_STATUS_SUPPRESSION
	RTL
