
UPDATE_SPECIAL_CAMERA_MODE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX GAME_STATE+game_state::walking_style
	STX @LOCAL02
	CPX #WALKING_STYLE::STAIRS
	BEQ @USE_STAIRS_DIRECTION
	LDA GAME_STATE+game_state::leader_direction
	STA @LOCAL01
	BRA @DISPATCH_CAMERA_MODE
@USE_STAIRS_DIRECTION:
	LDA AUTO_MOVEMENT_DIRECTION
	STA @LOCAL01
@DISPATCH_CAMERA_MODE:
	LDA #.LOWORD(GAME_STATE) + game_state::camera_mode
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	AND #$00FF
	CMP #1
	BEQ @CAMERA_MODE_1
	CMP #2
	BEQL @CAMERA_MODE_2
	CMP #3
	BEQL @CAMERA_MODE_3
	JMP @RETURN
@CAMERA_MODE_1:
	LDY #.LOWORD(GAME_STATE) + game_state::leader_x_frac
	STY @LOCAL00
	LDA @LOCAL01
	OPTIMIZED_MULT @VIRTUAL04, 4
	STA @VIRTUAL04
	LDX @LOCAL02
	TXA
	OPTIMIZED_MULT @VIRTUAL04, 32
	CLC
	ADC @VIRTUAL04
	STA @LOCAL01
	CLC
	ADC #.LOWORD(HORIZONTAL_MOVEMENT_SPEEDS)
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL0A
	LDY @LOCAL00
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDY #.LOWORD(GAME_STATE) + game_state::leader_y_frac
	STY @LOCAL02
	LDA @LOCAL01
	CLC
	ADC #.LOWORD(VERTICAL_MOVEMENT_SPEEDS)
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL0A
	LDY @LOCAL02
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDX #.LOWORD(GAME_STATE) + game_state::auto_move_frames_left
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
	BNE @END_AUTO_MOVEMENT
	LDA #0
	LDX @VIRTUAL02
	STA __BSS_START__,X
	LDA GAME_STATE + game_state::auto_move_saved_walking_style
	STA GAME_STATE+game_state::walking_style
@END_AUTO_MOVEMENT:
	LDA #1
	STA GAME_STATE + game_state::leader_moved
	BRA @RETURN
@CAMERA_MODE_2:
	JSR SYNC_CAMERA_TO_ENTITY
	BRA @RETURN
@CAMERA_MODE_3:
	JSR UPDATE_CAMERA_MODE_3
@RETURN:
	END_C_FUNCTION
