
UPDATE_CAMERA_MODE_3:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX CAMERA_MODE_3_FRAMES_LEFT
	DEX
	STX CAMERA_MODE_3_FRAMES_LEFT
	BEQL @TIMER_EXPIRED
	LDA GAME_STATE+game_state::walking_style
	JSL MAP_INPUT_TO_DIRECTION
	STA @VIRTUAL04
	STA @LOCAL01
	LDA @VIRTUAL04
	CMP #.LOWORD(-1)
	BEQL @RETURN
	LDA #24
	STA @VIRTUAL02
	BRA @LOOP_CHECK
@LOOP_BODY:
	LDA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_SCRIPT_TABLE,X
	CMP #.LOWORD(-1)
	BEQ @NEXT_ENTITY
	TXA
	CLC
	ADC #.LOWORD(ENTITY_DIRECTIONS)
	TAY
	STY @LOCAL00
	LDA @LOCAL01
	STA @VIRTUAL04
	LDA __BSS_START__,Y
	CMP @VIRTUAL04
	BEQ @NEXT_ENTITY
	LDA ENTITY_SCRIPT_VAR1_TABLE,X
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	TAX
	STX CURRENT_PARTY_MEMBER_TICK
	LDA a:char_struct::position_index,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(player_position_buffer_entry)
	CLC
	ADC #.LOWORD(PLAYER_POSITION_BUFFER)
	TAX
	LDA a:player_position_buffer_entry::walking_style,X
	CMP #WALKING_STYLE::ROPE
	BEQ @NEXT_ENTITY
	CMP #WALKING_STYLE::LADDER
	BEQ @NEXT_ENTITY
	LDA @LOCAL01
	STA @VIRTUAL04
	LDY @LOCAL00
	STA __BSS_START__,Y
	LDA @VIRTUAL02
	JSL UPDATE_ENTITY_SPRITE
@NEXT_ENTITY:
	INC @VIRTUAL02
@LOOP_CHECK:
	LDA @VIRTUAL02
	CMP #29
	BLTEQ @LOOP_BODY
	LDA @LOCAL01
	STA @VIRTUAL04
	STA GAME_STATE+game_state::leader_direction
	BRA @RETURN
@TIMER_EXPIRED:
	JSL RESTORE_CAMERA_MODE
@RETURN:
	END_C_FUNCTION
