
MOVEMENT_CMD_APPLY_COLOR_MATH_FIXED:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	LDX #$0033
	DEC
	BNE @SUBTRACT_MODE
	LDX #$00B3
@SUBTRACT_MODE:
	PHX
	JSL MOVEMENT_DATA_READ8
	STY $94
	STA ACTIONSCRIPT_COLDATA_BLUE
	JSL MOVEMENT_DATA_READ8
	STY $94
	STA ACTIONSCRIPT_COLDATA_GREEN
	JSL MOVEMENT_DATA_READ8
	STY $94
	STA ACTIONSCRIPT_COLDATA_RED
	PLA
	JSL APPLY_COLOR_MATH_FIXED_COLOR
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	RTL
