.ENUM WINDOW
	COMMAND_MENU = $00
	TEXT_STANDARD = $01
	INVENTORY = $02
	INVENTORY_MENU = $03
	PSI_TARGET_COST = $04
	PHONE_MENU = $05
	EQUIP_MENU = $06
	EQUIP_MENU_ITEMLIST = $07
	STATUS_MENU = $08
	STATUS_STATS_PANEL = $09
	CARRIED_MONEY = $0A
	STATUS_EQUIPMENT_PANEL = $0B
	STORE_ITEM_LIST = $0C
	ESCARGO_EXPRESS_ITEM = $0D
	TEXT_BATTLE = $0E
	BATTLE_MENU = $0F
	BATTLE_PSI_CATEGORY = $10
	BATTLE_PSI_NAME = $11
	BATTLE_MENU_JEFF = $12
	FILE_SELECT_MAIN = $13
	FILE_SELECT_MENU = $14
	FILE_SELECT_COPY_MENU_TWO_FILES = $15
	FILE_SELECT_COPY_MENU_ONE_FILE = $16
	FILE_SELECT_DELETE_CONFIRMATION = $17
	FILE_SELECT_TEXT_SPEED = $18
	FILE_SELECT_MUSIC_MODE = $19
	FILE_SELECT_NAMING_NAME_BOX = $1A
	FILE_SELECT_NAMING_MESSAGE = $1B
	FILE_SELECT_NAMING_KEYBOARD = $1C
	FILE_SELECT_NAMING_CONFIRMATION_NESS = $1D
	FILE_SELECT_NAMING_CONFIRMATION_PAULA = $1E
	FILE_SELECT_NAMING_CONFIRMATION_JEFF = $1F
	FILE_SELECT_NAMING_CONFIRMATION_POO = $20
	FILE_SELECT_NAMING_CONFIRMATION_KING = $21
	FILE_SELECT_NAMING_CONFIRMATION_FOOD = $22
	FILE_SELECT_NAMING_CONFIRMATION_THING = $23
	FILE_SELECT_NAMING_CONFIRMATION_MESSAGE = $24
	STORE_PURCHASE_INFO = $25
	BATTLE_ACTION_NAME = $26
	NAMING_PROMPT = $27
	TARGETING_PROMPT = $28
	PSI_LEVEL_SHORT = $29
	PSI_LEVEL_MEDIUM = $2A
	PSI_LEVEL_WIDE = $2B
	OVERWORLD_CHAR_SELECT = $2C
	EQUIPMENT_STATS = $2D
	STATUS_PSI_CATEGORY = $2E
	PSI_DESCRIPTION = $2F
	BATTLE_MENU_FULL = $30
	BATTLE_TARGET_TEXT = $31
	FILE_SELECT_FLAVOUR_CHOICE = $32
	SINGLE_CHARACTER_SELECT = $33
	.IF .DEFINED(USA)
		DEBUG_MENU = $34
	.ENDIF
	MAX
.ENDENUM
