
DECOMPRESS_TITLE_DATA:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	BNE @DECOMPRESS_SECOND
	LOADPTR TITLE_SCREEN_BG1_DATA, @LOCAL00
	LOADPTR BUFFER, @LOCAL01
	JSL DECOMP
	BRA @DONE
@DECOMPRESS_SECOND:
	LOADPTR TITLE_SCREEN_BG2_DATA, @LOCAL00
	LOADPTR BUFFER, @LOCAL01
	JSL DECOMP
@DONE:
	END_C_FUNCTION
