
FILE_MENU_LOOP:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
.IF !.DEFINED(PROTOTYPE19950327)
	STACK_RESERVE_INT16
.ENDIF
	STACK_RESERVE_INT16 "LOCAL04"
	STACK_RESERVE_INT16 "LOCAL05"
	STACK_RESERVE_INT16 "LOCAL06"
	STACK_RESERVE_INT16 "LOCAL07"
	STACK_RESERVE_INT16 "LOCAL08"
	END_STACK_VARS
.IF .DEFINED(PROTOTYPE19950327)
	@LOCAL03T := @LOCAL04
	@LOCAL06ALT := @LOCAL08
	@LOCAL08ALT := @LOCAL05
	@LOCAL08ALT2 := @LOCAL06
.ELSE
	@LOCAL03T := @LOCAL03
	@LOCAL06ALT := @LOCAL06
	@LOCAL08ALT := @LOCAL08
	@LOCAL08ALT2 := @LOCAL08
.ENDIF
@FILE_SELECT_TOP:
	JSR SET_INSTANT_PRINTING
	LDA #0
	JSR FILE_SELECT_MENU
	TAX
	DEX
	LDA SAVE_FILES_PRESENT,X
	AND #$00FF
	BEQL @EMPTY_FILE_SELECTED
@VALID_FILE_SELECTED:
	JSR SHOW_FILE_SELECT_MENU
	CMP #0
	BEQ @MENU_B_PRESSED
	CMP #1
	BEQ @MENU_STARTGAME_SELECTED
	CMP #2
	BEQ @MENU_COPY_SELECTED
	CMP #3
	BEQ @MENU_DELETE_SELECTED
	CMP #4
	BEQ @MENU_SETUP_SELECTED
	BRA @MENU_OTHER_SELECTED
@MENU_B_PRESSED:
	JSR CLOSE_FOCUS_WINDOW
	BRA @FILE_SELECT_TOP
@MENU_STARTGAME_SELECTED:
	JSL RESET_QUEUED_INTERACTIONS
	JSL RELOAD_HOTSPOTS
	LDA GAME_STATE+game_state::leader_x_coord
	STA RESPAWN_X
	LDA GAME_STATE+game_state::leader_y_coord
	STA RESPAWN_Y
	JMP @FINALIZE_AND_START
@MENU_COPY_SELECTED:
	JSR SHOW_FILE_COPY_DIALOG
	CMP #0
	BEQ @VALID_FILE_SELECTED
	BRA @MENU_OTHER_SELECTED
@MENU_DELETE_SELECTED:
	JSR CONFIRM_FILE_DELETE
	CMP #0
	BEQ @VALID_FILE_SELECTED
	BRA @MENU_OTHER_SELECTED
@MENU_SETUP_SELECTED:
	JSL OPEN_TEXT_SPEED_MENU
@SETUP_TEXT_SPEED_SELECT:
	LDA #0
	JSL FILE_SELECT_TEXT_SPEED_MENU
	CMP #0
	BNE @MENU_SETUP_SELECTED2
	LDA #WINDOW::FILE_SELECT_TEXT_SPEED
	JSR CLOSE_WINDOW
	BRA @VALID_FILE_SELECTED
@MENU_SETUP_SELECTED2:
	JSR OPEN_SOUND_MENU
@SETUP_SOUND_SELECT:
	LDA #0
	JSR FILE_SELECT_SOUND_MODE_MENU
	CMP #0
	BNE @MENU_SETUP_SELECTED3
	LDA #WINDOW::FILE_SELECT_MUSIC_MODE
	JSR CLOSE_WINDOW
	BRA @SETUP_TEXT_SPEED_SELECT
@MENU_SETUP_SELECTED3:
	JSR OPEN_FLAVOUR_MENU
	CMP #0
	BNE @MENU_OTHER_SELECTED
	LDA #WINDOW::FILE_SELECT_FLAVOUR_CHOICE
	JSR CLOSE_WINDOW
	BRA @SETUP_SOUND_SELECT
@MENU_OTHER_SELECTED:
	JSR CLOSE_ALL_WINDOWS
	JMP @FILE_SELECT_TOP
@EMPTY_FILE_SELECTED:
	JSL OPEN_TEXT_SPEED_MENU
@NEW_GAME_TEXT_SPEED_SELECT:
	LDA #0
	JSL FILE_SELECT_TEXT_SPEED_MENU
	CMP #0
	BNE @NEW_GAME_OPEN_SOUND
	LDA #WINDOW::FILE_SELECT_TEXT_SPEED
	JSR CLOSE_WINDOW
	JMP @FILE_SELECT_TOP
@NEW_GAME_OPEN_SOUND:
	JSR OPEN_SOUND_MENU
@NEW_GAME_SOUND_SELECT:
	LDA #0
	JSR FILE_SELECT_SOUND_MODE_MENU
	CMP #0
	BNE @NEW_GAME_OPEN_FLAVOUR
	LDA #WINDOW::FILE_SELECT_MUSIC_MODE
	JSR CLOSE_WINDOW
	BRA @NEW_GAME_TEXT_SPEED_SELECT
@NEW_GAME_OPEN_FLAVOUR:
	JSR OPEN_FLAVOUR_MENU
	CMP #0
	BNE @CHANGE_TO_NAMING_SCREEN_MUSIC
	LDA #WINDOW::FILE_SELECT_FLAVOUR_CHOICE
	JSR CLOSE_WINDOW
	BRA @NEW_GAME_SOUND_SELECT
@CHANGE_TO_NAMING_SCREEN_MUSIC:
	LDA #MUSIC::NAMING_SCREEN
	JSL CHANGE_MUSIC
@START_NAMING:
	JSR CLOSE_ALL_WINDOWS
	LDA #0
	STA @VIRTUAL04
	STA @LOCAL08
	JMP @NAMING_CHECK_REMAINING
@NAMING_NEXT_CHARACTER:
	LDA @VIRTUAL04
	CMP #$FFFF
	BNE @DISPLAY_NAMING_SPRITE
	JSR CLOSE_ALL_WINDOWS
	LDA #1
	JSR FILE_SELECT_MENU
	LDA #1
	JSL FILE_SELECT_TEXT_SPEED_MENU
	LDA #1
	JSR FILE_SELECT_SOUND_MODE_MENU
	LDA #MUSIC::SETUP_SCREEN
	JSL CHANGE_MUSIC
	BRA @NEW_GAME_OPEN_FLAVOUR
@DISPLAY_NAMING_SPRITE:
	LDA @VIRTUAL04
	JSL DISPLAY_ANIMATED_NAMING_SPRITE
	LDA #FILE_MENU_NEW_GAME_NAME::DOG
	CLC
	SBC @VIRTUAL04
	BRANCHLTEQS @CHECK_DOG_NAME
	LOADPTR FILE_SELECT_TEXT_PLEASE_NAME_THEM_STRINGS, @VIRTUAL06
	LDA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, 40
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA #NAME_THEM_STRING_LENGTH
	STA @LOCAL01
	LDA @LOCAL08
	STA @VIRTUAL04
	LDY @VIRTUAL04
	STY @LOCAL07
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	TAX
	LDA #.SIZEOF(char_struct::name)
	LDY @LOCAL07
	JSR NAME_A_CHARACTER
	CMP #0
	BEQ @NAME_CANCELLED
	LDA #$FFFF
	STA @VIRTUAL02
	STA @LOCAL06
	JMP @NAMING_ADVANCE
@NAME_CANCELLED:
	LDA #1
	STA @VIRTUAL02
	STA @LOCAL06
	JMP @NAMING_ADVANCE
@CHECK_DOG_NAME:
	LDA @VIRTUAL04
	CMP #FILE_MENU_NEW_GAME_NAME::DOG
	BNE @CHECK_FOOD_NAME
	LOADPTR FILE_SELECT_TEXT_PLEASE_NAME_THEM_STRINGS, @VIRTUAL06
	LDA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, 40
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA #NAME_THEM_STRING_LENGTH
	STA @LOCAL01
	LDA @LOCAL08
	STA @VIRTUAL04
	LDY @VIRTUAL04
	LDX #.LOWORD(GAME_STATE) + game_state::pet_name
	LDA #.SIZEOF(game_state::pet_name)
	JSR NAME_A_CHARACTER
	CMP #0
	BEQ @DOG_NAME_CANCELLED
	LDA #$FFFF
	STA @VIRTUAL02
	STA @LOCAL06
	JMP @NAMING_ADVANCE
@DOG_NAME_CANCELLED:
	LDA #1
	STA @VIRTUAL02
	STA @LOCAL06
	JMP @NAMING_ADVANCE
@CHECK_FOOD_NAME:
	LDA @VIRTUAL04
	CMP #FILE_MENU_NEW_GAME_NAME::FAVORITE_FOOD
	BNE @CHECK_THING_NAME
	LOADPTR FILE_SELECT_TEXT_PLEASE_NAME_THEM_STRINGS, @VIRTUAL06
	LDA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, 40
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA #NAME_THEM_STRING_LENGTH
	STA @LOCAL01
	LDA @LOCAL08
	STA @VIRTUAL04
	LDY @VIRTUAL04
	LDX #.LOWORD(GAME_STATE) + game_state::favourite_food
	LDA #.SIZEOF(game_state::favourite_food)
	JSR NAME_A_CHARACTER
	CMP #0
	BEQ @FOOD_NAME_CANCELLED
	LDA #$FFFF
	STA @VIRTUAL02
	STA @LOCAL06
	BRA @NAMING_ADVANCE
@FOOD_NAME_CANCELLED:
	LDA #1
	STA @VIRTUAL02
	STA @LOCAL06
	BRA @NAMING_ADVANCE
@CHECK_THING_NAME:
	LDA @VIRTUAL04
	CMP #FILE_MENU_NEW_GAME_NAME::FAVORITE_THING
	BNE @NAMING_ADVANCE
	LOADPTR FILE_SELECT_TEXT_PLEASE_NAME_THEM_STRINGS, @VIRTUAL06
	LDA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, 40
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA #NAME_THEM_STRING_LENGTH
	STA @LOCAL01
	LDA @LOCAL08
	STA @VIRTUAL04
	LDY @VIRTUAL04
	LDX #.LOWORD(GAME_STATE) + game_state::favourite_thing + 4 ; part after 'PSI ' prefix
.IF .DEFINED(PROTOTYPE19950327) ;oops?
	LDA #.SIZEOF(game_state::favourite_thing) - 5
.ELSE
	LDA #.SIZEOF(game_state::favourite_thing) - 6
.ENDIF
	JSR NAME_A_CHARACTER
	CMP #0
	BEQ @THING_NAME_CANCELLED
	LDA #$FFFF
	STA @VIRTUAL02
	STA @LOCAL06
	BRA @NAMING_ADVANCE
@THING_NAME_CANCELLED:
	LDA #1
	STA @VIRTUAL02
	STA @LOCAL06
@NAMING_ADVANCE:
	LDA @VIRTUAL04
	JSL INIT_NAMING_SCREEN_EVENTS
	LDA @LOCAL06
	STA @VIRTUAL02
	LDA @VIRTUAL04
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL04
	STA @LOCAL08
@NAMING_CHECK_REMAINING:
	LDA #THINGS_NAMED_COUNT
	CLC
	SBC @VIRTUAL04
	JUMPGTS @NAMING_NEXT_CHARACTER
	JSR CLOSE_ALL_WINDOWS
	JSR SET_INSTANT_PRINTING
	LDX #0
	STX @LOCAL08
	BRA @CONFIRM_WINDOW_CHECK
@CREATE_CONFIRM_WINDOW:
	TXA
	CLC
	ADC #WINDOW::FILE_SELECT_NAMING_CONFIRMATION_NESS
	JSR CREATE_WINDOW
	LDX @LOCAL08
	INX
	STX @LOCAL08
	TXA
	JSR PRINT_CHARACTER_NAME
	LDX @LOCAL08
	STX @LOCAL08
@CONFIRM_WINDOW_CHECK:
	STX @VIRTUAL04
	LDA #PLAYER_CHAR_COUNT
	CLC
	SBC @VIRTUAL04
	BRANCHGTS @CREATE_CONFIRM_WINDOW
	CREATE_WINDOW_NEAR #WINDOW::FILE_SELECT_NAMING_CONFIRMATION_KING
	LDA #7
	JSR PRINT_CHARACTER_NAME
	LDA #WINDOW::FILE_SELECT_NAMING_CONFIRMATION_FOOD
	JSR CREATE_WINDOW
	LOADPTR FILE_SELECT_TEXT_FAVORITE_FOOD, @LOCAL00
	LDA #14
	JSR PRINT_STRING
	PROMOTENEARPTR GAME_STATE + game_state::favourite_food, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL STRLEN
	STA @LOCAL05
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #0
	LDA @LOCAL05
	JSL GET_TEXT_PIXEL_WIDTH
	TAX
	ASL
	PHP
	LSR
	LSR
	LSR
	LSR
	PLP
	BCC @FOOD_TEXT_NO_OVERFLOW
	ORA #$F000
@FOOD_TEXT_NO_OVERFLOW:
	STA @LOCAL08
	LDY #8
	TXA
	JSL MODULUS16S
	CMP #0
	BNE @FOOD_TEXT_ADJUST
	LDA @LOCAL08
	CMP #6
	BNE @FOOD_TEXT_PRINT
@FOOD_TEXT_ADJUST:
	LDA @LOCAL08
	INC
@FOOD_TEXT_PRINT:
	LDX #1
	STX @LOCAL04
	STA @VIRTUAL04
	LDA OPEN_WINDOW_TABLE + WINDOW::FILE_SELECT_NAMING_CONFIRMATION_FOOD * 2
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA WINDOW_STATS+window_stats::width,X
	SEC
	SBC @VIRTUAL04
	LDX @LOCAL04
	JSL SET_FOCUS_TEXT_CURSOR
	PROMOTENEARPTR GAME_STATE + game_state::favourite_food, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL STRLEN
	STA @LOCAL08
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @LOCAL08
	JSR PRINT_STRING
	LDA #WINDOW::FILE_SELECT_NAMING_CONFIRMATION_THING
	JSR CREATE_WINDOW
	LOADPTR FILE_SELECT_TEXT_COOLEST_THING, @LOCAL00
	LDA #14
	JSR PRINT_STRING
	PROMOTENEARPTR GAME_STATE + game_state::favourite_thing + 4, @VIRTUAL06 ; part after 'PSI ' prefix
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL STRLEN
	STA @LOCAL05
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #0
	LDA @LOCAL05
	JSL GET_TEXT_PIXEL_WIDTH
.IF !.DEFINED(PROTOTYPE19950327)
	TAX
.ENDIF
	ASL
	PHP
	LSR
	LSR
	LSR
	LSR
	PLP
	BCC @THING_TEXT_NO_OVERFLOW
	ORA #$F000
@THING_TEXT_NO_OVERFLOW:
	STA @LOCAL08
	LDY #8
.IF !.DEFINED(PROTOTYPE19950327)
	TXA
.ENDIF
	JSL MODULUS16S
	CMP #0
	BNE @THING_TEXT_ADJUST
	LDA @LOCAL08
	CMP #6
	BNE @THING_TEXT_PRINT
@THING_TEXT_ADJUST:
	LDA @LOCAL08
	INC
@THING_TEXT_PRINT:
	LDX #1
	STX @LOCAL07
	STA @VIRTUAL04
	LDA OPEN_WINDOW_TABLE + WINDOW::FILE_SELECT_NAMING_CONFIRMATION_THING * 2
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA WINDOW_STATS+window_stats::width,X
	SEC
	SBC @VIRTUAL04
	LDX @LOCAL07
	JSL SET_FOCUS_TEXT_CURSOR
	PROMOTENEARPTR GAME_STATE + game_state::favourite_thing + 4, @VIRTUAL06 ; part after 'PSI ' prefix
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL STRLEN
	STA @LOCAL08
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @LOCAL08
	JSR PRINT_STRING
	CREATE_WINDOW_NEAR #WINDOW::FILE_SELECT_NAMING_CONFIRMATION_MESSAGE
	LOADPTR FILE_SELECT_TEXT_ARE_YOU_SURE, @LOCAL00
	LDA #13
	JSR PRINT_STRING
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
	LOADPTR FILE_SELECT_TEXT_ARE_YOU_SURE_YEP, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDY #0
	LDX #14
	LDA #1
	JSR ADD_MENU_ITEM
	LOADPTR FILE_SELECT_TEXT_ARE_YOU_SURE_NOPE, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDY #0
	LDX #18
	TYA
	JSR ADD_MENU_ITEM
	JSR PRINT_MENU_ITEMS
	JSL CREATE_FILE_SELECT_PARTY_SPRITES
	LDA #$00FF
	STA ENABLE_WORD_WRAP
	LDA #1
	JSR SELECTION_MENU
	TAX
	BNE @EVERYTHING_OKAY
	JSL CLEAR_MAP_ENTITIES
	JMP @START_NAMING
@EVERYTHING_OKAY:
	LDA #MUSIC::NAME_CONFIRMATION
	JSL CHANGE_MUSIC
	JSL WINDOW_TICK
	LDX #0
	STX @LOCAL08ALT
	BRA @CONFIRM_WAIT_CHECK
@CONFIRM_WAIT_LOOP:
	JSL RENDER_FRAME_TICK
	LDX @LOCAL08ALT
	INX
	STX @LOCAL08ALT
@CONFIRM_WAIT_CHECK:
	STX @VIRTUAL02
	LDA #180
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @CONFIRM_WAIT_LOOP
	JSL CLEAR_MAP_ENTITIES
	STZ @LOCAL05
	JMP @INIT_CHARS_CHECK
@INIT_CHAR_STATS:
	LDA @LOCAL05
	STA @VIRTUAL04
	INC @VIRTUAL04
	LDA @VIRTUAL04
	STA @LOCAL08ALT2
	LOADPTR INITIAL_STATS, @VIRTUAL06
	LDA @LOCAL05
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(initial_stats)
	STA @VIRTUAL02
	LDY #0
	LDA @VIRTUAL02
	CLC
	ADC #initial_stats::level
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	TAX
	LDA @LOCAL08ALT2
	STA @VIRTUAL04
	JSR RESET_CHAR_LEVEL_ONE
	LDA @VIRTUAL02
	CLC
	ADC #initial_stats::exp
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	BEQ @AFTER_EXP_GAIN
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #0
	LDA @VIRTUAL04
	JSL GAIN_EXP
@AFTER_EXP_GAIN:
	LDA @LOCAL05
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAY
	STY @LOCAL03T
	LDA PARTY_CHARACTERS+char_struct::max_hp,Y
	STA PARTY_CHARACTERS+char_struct::current_hp,Y
	STA PARTY_CHARACTERS+char_struct::current_hp_target,Y
	LDA PARTY_CHARACTERS+char_struct::max_pp,Y
	STA PARTY_CHARACTERS+char_struct::current_pp,Y
	STA PARTY_CHARACTERS+char_struct::current_pp_target,Y
	TYX
	STZ PARTY_CHARACTERS+char_struct::current_pp_fraction,X
	TYX
	STZ PARTY_CHARACTERS+char_struct::current_hp_fraction,X
	TYA
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	STA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STZ_BADOPT @LOCAL00
	LDX #14
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
	JSL MEMSET16
	LOADPTR INITIAL_STATS, @VIRTUAL06
	LDA @LOCAL05
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(initial_stats)
	CLC
	ADC #initial_stats::items
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX #.SIZEOF(initial_stats::items)
	LDA @VIRTUAL02
	JSL MEMCPY16
	LDA #$0400
	LDY @LOCAL03T
	STA PARTY_CHARACTERS+char_struct::hp_pp_window_options,Y
	INC @LOCAL05
@INIT_CHARS_CHECK:
	LDA #PLAYER_CHAR_COUNT
	CLC
	SBC @LOCAL05
	JUMPGTS @INIT_CHAR_STATS
	LOADPTR INITIAL_STATS, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	LDY #initial_stats::money
	LDA [@VIRTUAL06],Y
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, GAME_STATE+game_state::money_carried
	MOVE_INT @LOCAL02, @VIRTUAL06
	LDY #initial_stats::unknown2
	LDA [@VIRTUAL06],Y
	ASL
	ASL
	ASL
	TAX
	LDA [@VIRTUAL06]
	ASL
	ASL
	ASL
	JSL PLACE_LEADER_AT_POSITION
	SEP #PROC_FLAGS::ACCUM8
	LDA #CHAR::P
	STA GAME_STATE+game_state::favourite_thing
	LDA #CHAR::S_
	STA GAME_STATE+game_state::favourite_thing+1
	LDA #CHAR::I
	STA GAME_STATE+game_state::favourite_thing+2
	LDA #CHAR::SPACE
	STA GAME_STATE+game_state::favourite_thing+3
.IF !.DEFINED(PROTOTYPE19950327)
	REP #PROC_FLAGS::ACCUM8
	LDA #4 ;Length of 'PSI ' string
	STA @LOCAL05
	BRA @PAD_THING_NAME_CHECK
@PAD_THING_NAME:
	LDA @LOCAL05
	CLC
	ADC #.LOWORD(GAME_STATE) + game_state::favourite_thing
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	BNE @THING_CHAR_NOT_NULL
	SEP #PROC_FLAGS::ACCUM8
	LDA #CHAR::SPACE
	STA __BSS_START__,X
	BRA @THING_NAME_PADDED
@THING_CHAR_NOT_NULL:
	LDA @LOCAL05
	INC
	STA @LOCAL05
@PAD_THING_NAME_CHECK:
	.A16
	STA @VIRTUAL02
	LDA #.SIZEOF(game_state::favourite_thing) - 1 ;Last byte should be \0
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @PAD_THING_NAME
@THING_NAME_PADDED:
	SEP #PROC_FLAGS::ACCUM8
.ENDIF
	LDA #1
	STA GAME_STATE + game_state::unknownC3
	REP #PROC_FLAGS::ACCUM8
	LDA GAME_STATE+game_state::leader_x_coord
	STA RESPAWN_X
	LDA GAME_STATE+game_state::leader_y_coord
	STA RESPAWN_Y
	JSL RESET_QUEUED_INTERACTIONS
	LDX #1768
	LDA #2112
	JSL PLACE_LEADER_AT_POSITION
	LOADPTR MSG_EVT_PROLOGUE_NEW, @LOCAL00
	JSL FREEZE_AND_QUEUE_TEXT_INTERACTION
	LDX #1
	LDA #EVENT_FLAG::FLG_SYS_MONSTER_OFF
	JSL SET_EVENT_FLAG
	LDA #1
	STA SHOW_NPC_FLAG
@FINALIZE_AND_START:
	JSR CLOSE_ALL_WINDOWS
	JSL INIT_ALL_ITEM_TRANSFORMATIONS
	LDA GAME_STATE+game_state::text_speed
	AND #$00FF
	STA @LOCAL06ALT
	TAX
	DEX
	LOADPTR HP_METER_SPEEDS, @VIRTUAL0A
	TXA
	ASL
	ASL
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, HP_METER_SPEED
	STX SELECTED_TEXT_SPEED
	LDA @LOCAL06ALT
	CMP #3
	BNE @TEXT_SPEED_NOT_SLOW
	LDA #0
	BRA @SET_TEXT_SPEED
@TEXT_SPEED_NOT_SLOW:
	OPTIMIZED_MULT @VIRTUAL04, 30
@SET_TEXT_SPEED:
	STA TEXT_SPEED_BASED_WAIT
	STZ UNREAD_7E5DBA
	DISPLAY_TEXT_PTR MSG_SYS_PRE_GAMESTART
	END_C_FUNCTION
