
FILE_SELECT_MENU:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STA @VIRTUAL04
	LDA #WINDOW::FILE_SELECT_MAIN
	JSR CREATE_WINDOW
	LDY #0
	STY @LOCAL03
	JMP @SLOT_LOOP_CHECK
@LOAD_SLOT:
	TYA
	JSL LOAD_GAME_SLOT
	LDA GAME_STATE + game_state::favourite_thing + 1
	AND #$00FF
	BEQL @EMPTY_SAVE_SLOT
	LDY @LOCAL03
	TYA
	SEP #PROC_FLAGS::ACCUM8
	CLC
	ADC #CHAR::ONE
	STA TEMPORARY_TEXT_BUFFER
	LDA #CHAR::COLON
	STA TEMPORARY_TEXT_BUFFER + 1
	LDA #CHAR::SPACE
	STA TEMPORARY_TEXT_BUFFER + 2
	LDX #0
	BRA @NAME_CHAR_LOOP_CHECK
@COPY_NAME_CHAR:
	SEP #PROC_FLAGS::ACCUM8
	STA TEMPORARY_TEXT_BUFFER + 3,X
	INX
@READ_NAME_CHAR:
	REP #PROC_FLAGS::ACCUM8
	LDA PARTY_CHARACTERS + char_struct::name,X
	AND #$00FF
	BEQ @PAD_NAME_CHAR
	CPX #.SIZEOF(char_struct::name)
	BCC @COPY_NAME_CHAR
@PAD_NAME_CHAR:
	SEP #PROC_FLAGS::ACCUM8
	LDA #CHAR::SPACE
	STA TEMPORARY_TEXT_BUFFER + 3,X
	INX
@NAME_CHAR_LOOP_CHECK:
	CPX #.SIZEOF(char_struct::name)
	BCC @READ_NAME_CHAR
@APPEND_LEVEL:
	REP #PROC_FLAGS::ACCUM8
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER + 7, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LOADPTR FILE_SELECT_TEXT_LEVEL, @LOCAL01
	LDA #FILE_SELECT_TEXT_LEVEL_LENGTH
	JSL MEMCPY24
	SEP #PROC_FLAGS::ACCUM8
	MOVE_INT832 .LOWORD(PARTY_CHARACTERS) + (PARTY_MEMBER::NESS - 1) * .SIZEOF(char_struct) + char_struct::level, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR NUMBER_TO_TEXT_BUFFER
	TAX
	CPX #1
	BNE @MULTI_DIGIT_LEVEL
	LDA #CHAR::SPACE
	BRA @AFTER_TENS_DIGIT
@MULTI_DIGIT_LEVEL:
	STX @VIRTUAL02
	LDA #7
	SEC
	SBC @VIRTUAL02
	TAX
	LDA NUMBER_TEXT_BUFFER,X
	AND #$00FF
	CLC
	ADC #CHAR::ZERO
@AFTER_TENS_DIGIT:
	SEP #PROC_FLAGS::ACCUM8
	STA TEMPORARY_TEXT_BUFFER + 12
	LDA NUMBER_TEXT_BUFFER + 6
	CLC
	ADC #CHAR::ZERO
	STA TEMPORARY_TEXT_BUFFER + 13
	REP #PROC_FLAGS::ACCUM8
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER + 14, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
@APPEND_TEXT_SPEED:
	LOADPTR FILE_SELECT_TEXT_TEXTSPEED, @LOCAL01
	LDA #FILE_SELECT_TEXT_TEXT_SPEED_LENGTH
	JSL MEMCPY24
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER + 20, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LOADPTR FILE_SELECT_TEXT_TEXTSPEED_STRINGS, @VIRTUAL06
	LDA GAME_STATE + game_state::text_speed
	AND #$00FF
	DEC
	OPTIMIZED_MULT @VIRTUAL04, TEXT_SPEED_STRING_LENGTH
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL01
	LDA @VIRTUAL06+2
	STA @LOCAL01+2
	LDA #TEXT_SPEED_STRING_LENGTH
	JSL MEMCPY24
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	LDY @LOCAL03
	STA SAVE_FILES_PRESENT,Y
	REP #PROC_FLAGS::ACCUM8
	LDA GAME_STATE + game_state::text_flavour
	AND #$00FF
	XBA
	AND #$FF00
	STA @LOCAL02
	BRA @ADD_SLOT_MENU_ITEM
@EMPTY_SAVE_SLOT:
	LDY @LOCAL03
	TYA
	SEP #PROC_FLAGS::ACCUM8
	CLC
	ADC #CHAR::ONE
	STA TEMPORARY_TEXT_BUFFER
	REP #PROC_FLAGS::ACCUM8
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER + 1, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LOADPTR FILE_SELECT_TEXT_START_NEW_GAME, @LOCAL01
	LDA #FILE_SELECT_TEXT_NEW_GAME_LENGTH
	JSL MEMCPY24
	SEP #PROC_FLAGS::ACCUM8
	STZ TEMPORARY_TEXT_BUFFER + 11
	LDY @LOCAL03
	TYX
	STZ SAVE_FILES_PRESENT,X
	REP #PROC_FLAGS::ACCUM8
	LDA #$100
	STA @LOCAL02
@ADD_SLOT_MENU_ITEM:
	STY @VIRTUAL02
	INC @VIRTUAL02
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDA @LOCAL02
	ORA @VIRTUAL02
	JSR ADD_MENU_ITEM_NO_POSITION
	LDY @VIRTUAL02
	STY @LOCAL03
@SLOT_LOOP_CHECK:
	CPY #3
	BCCL @LOAD_SLOT
	LDY #0
	TYX
	LDA #1
	JSR OPEN_WINDOW_AND_PRINT_MENU
	LDA @VIRTUAL04
	BEQL @FIRST_TIME_SELECT
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA WINDOW_STATS + WINDOW::PSI_LEVEL_WIDE,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	TAY
	STY @LOCAL02
	LDA CURRENT_SAVE_SLOT
	AND #$00FF
	TAX
	DEX
	BRA @ADVANCE_LOOP_CHECK
@ADVANCE_TO_SAVE:
	LDA __BSS_START__ + menu_option::next,Y
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	TAY
	STY @LOCAL02
	DEX
@ADVANCE_LOOP_CHECK:
	BNE @ADVANCE_TO_SAVE
	LDA #6
	JSR SET_WINDOW_PALETTE_INDEX
	LDY @LOCAL02
	LDA a:menu_option::text_y,Y
	TAX
	LDA a:menu_option::text_x,Y
	INC
	JSR SET_FOCUS_TEXT_CURSOR
	LDY @LOCAL02
	TYA
	CLC
	ADC #menu_option::label
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #$FFFF
	JSR PRINT_STRING
	LDA #0
	JSR SET_WINDOW_PALETTE_INDEX
	BRA @AFTER_SELECTION
@FIRST_TIME_SELECT:
	JSR CORRUPTION_CHECK
@WAIT_FADE:
	LDA FADE_PARAMETERS + fade_parameters::step
	AND #$00FF
	BNE @WAIT_FADE
	LDA #MUSIC::SETUP_SCREEN
	JSL CHANGE_MUSIC
	LOADPTR PREVIEW_WINDOW_FLAVOUR_HIBYTE, @LOCAL00
	JSR SET_CURSOR_MOVE_CALLBACK
	LDA #0
	JSR SELECTION_MENU
	SEP #PROC_FLAGS::ACCUM8
	STA CURRENT_SAVE_SLOT
	JSR CLEAR_CURSOR_MOVE_CALLBACK
@AFTER_SELECTION:
	.A16
	LDA CURRENT_SAVE_SLOT
	AND #$00FF
	DEC
	JSL LOAD_GAME_SLOT
	LDA CURRENT_SAVE_SLOT
	AND #$00FF
	END_C_FUNCTION
