
FILE_MENU_LOOP:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
@MAIN_LOOP:
	JSR SET_INSTANT_PRINTING
	LDA #0
	JSR FILE_SELECT_MENU
	TAX
	DEX
	LDA SAVE_FILES_PRESENT,X
	AND #$00FF
	BEQL @EMPTY_FILE_SELECTED
@VALID_FILE_SELECTED:
	JSR SHOW_FILE_SELECT_MENU
	CMP #0
	BEQ @MENU_B_PRESSED
	CMP #1
	BEQ @MENU_STARTGAME_SELECTED
	CMP #2
	BEQ @MENU_COPY_SELECTED
	CMP #3
	BEQ @MENU_DELETE_SELECTED
	CMP #4
	BEQ @MENU_SETUP_SELECTED
	BRA @MENU_OTHER_SELECTED
@MENU_B_PRESSED:
	JSR CLOSE_ALL_WINDOWS
	BRA @MAIN_LOOP
@MENU_STARTGAME_SELECTED:
	JSL RESET_QUEUED_INTERACTIONS
	JSL RELOAD_HOTSPOTS
	LDA GAME_STATE+game_state::leader_x_coord
	STA RESPAWN_X
	LDA GAME_STATE+game_state::leader_y_coord
	STA RESPAWN_Y
	JMP @START_GAME
@MENU_COPY_SELECTED:
	JSR SHOW_FILE_COPY_DIALOG
	CMP #0
	BEQ @VALID_FILE_SELECTED
	BRA @MENU_OTHER_SELECTED
@MENU_DELETE_SELECTED:
	JSR CONFIRM_FILE_DELETE
	CMP #0
	BEQ @VALID_FILE_SELECTED
	BRA @MENU_OTHER_SELECTED
@MENU_SETUP_SELECTED:
	LDA #0
	JSR OPEN_TEXT_SPEED_MENU
	CMP #0
	BNE @MENU_SETUP_SELECTED2
	LDA #WINDOW::FILE_SELECT_TEXT_SPEED
	JSR CLOSE_WINDOW
	BRA @VALID_FILE_SELECTED
@MENU_SETUP_SELECTED2:
	LDA #0
	JSR OPEN_SOUND_MENU
	CMP #0
	BNE @MENU_SETUP_SELECTED3
	LDA #WINDOW::FILE_SELECT_MUSIC_MODE
	JSR CLOSE_WINDOW
	BRA @MENU_SETUP_SELECTED
@MENU_SETUP_SELECTED3:
	JSR OPEN_FLAVOUR_MENU
	CMP #0
	BEQ @MENU_SETUP_SELECTED2
@MENU_OTHER_SELECTED:
	JSR CLOSE_ALL_WINDOWS
	JMP @MAIN_LOOP
@EMPTY_FILE_SELECTED:
	LDA #0
	JSR OPEN_TEXT_SPEED_MENU
	CMP #0
	BNE @NEW_SOUND_SETUP
	LDA #WINDOW::FILE_SELECT_TEXT_SPEED
	JSR CLOSE_WINDOW
	JMP @MAIN_LOOP
@NEW_SOUND_SETUP:
	LDA #0
	JSR OPEN_SOUND_MENU
	CMP #0
	BNE @NEW_FLAVOUR_SETUP
	LDA #WINDOW::FILE_SELECT_MUSIC_MODE
	JSR CLOSE_WINDOW
	BRA @EMPTY_FILE_SELECTED
@NEW_FLAVOUR_SETUP:
	JSR OPEN_FLAVOUR_MENU
	CMP #0
	BEQ @NEW_SOUND_SETUP
@CHANGE_TO_NAMING_SCREEN_MUSIC:
	LDA #MUSIC::NAMING_SCREEN
	JSL CHANGE_MUSIC
@BEGIN_NAMING:
	JSR CLOSE_ALL_WINDOWS
	LDA #0
	STA @VIRTUAL02
	JMP @NAMING_LOOP_CHECK
@NAMING_LOOP:
	LDA @VIRTUAL02
	CMP #$FFFF
	BNE @DO_NAME_ENTRY
	JSR CLOSE_ALL_WINDOWS
	LDA #1
	JSR FILE_SELECT_MENU
	LDA #1
	JSR OPEN_TEXT_SPEED_MENU
	LDA #1
	JSR OPEN_SOUND_MENU
	LDA #MUSIC::SETUP_SCREEN
	JSL CHANGE_MUSIC
	BRA @NEW_FLAVOUR_SETUP
@DO_NAME_ENTRY:
	LDA @VIRTUAL02
	JSL DISPLAY_ANIMATED_NAMING_SPRITE
	LDA #FILE_MENU_NEW_GAME_NAME::DOG
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @NAME_SPECIAL_ENTRY
	LOADPTR FILE_SELECT_TEXT_PLEASE_NAME_THEM_STRINGS, @VIRTUAL06
	LDA @VIRTUAL02
	OPTIMIZED_MULT @VIRTUAL04, 15
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA #NAME_THEM_STRING_LENGTH
	STA @LOCAL01
	LDY @VIRTUAL02
	STY @LOCAL09
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	TAX
	LDA #.SIZEOF(char_struct::name)
	LDY @LOCAL09
	JSR NAME_A_CHARACTER
	CMP #0
	BEQ @CHAR_NAME_BACK
	LDA #$FFFF
	STA @VIRTUAL04
	STA @LOCAL08
	JMP @ADVANCE_NAMING
@CHAR_NAME_BACK:
	LDA #1
	STA @VIRTUAL04
	STA @LOCAL08
	JMP @ADVANCE_NAMING
@NAME_SPECIAL_ENTRY:
	LDA @VIRTUAL02
	CMP #FILE_MENU_NEW_GAME_NAME::DOG
	BNE @NAME_FOOD_ENTRY
	LOADPTR FILE_SELECT_TEXT_PLEASE_NAME_THEM_STRINGS, @VIRTUAL06
	LDA @VIRTUAL02
	OPTIMIZED_MULT @VIRTUAL04, 15
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA #NAME_THEM_STRING_LENGTH
	STA @LOCAL01
	LDY @VIRTUAL02
	LDX #.LOWORD(GAME_STATE) + game_state::pet_name
	LDA #.SIZEOF(game_state::pet_name)
	JSR NAME_A_CHARACTER
	CMP #0
	BEQ @PET_NAME_BACK
	LDA #$FFFF
	STA @VIRTUAL04
	STA @LOCAL08
	JMP @ADVANCE_NAMING
@PET_NAME_BACK:
	LDA #1
	STA @VIRTUAL04
	STA @LOCAL08
	JMP @ADVANCE_NAMING
@NAME_FOOD_ENTRY:
	LDA @VIRTUAL02
	CMP #FILE_MENU_NEW_GAME_NAME::FAVORITE_FOOD
	BNE @NAME_THING_ENTRY
	LOADPTR FILE_SELECT_TEXT_PLEASE_NAME_THEM_STRINGS, @VIRTUAL06
	LDA @VIRTUAL02
	OPTIMIZED_MULT @VIRTUAL04, 15
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA #NAME_THEM_STRING_LENGTH
	STA @LOCAL01
	LDY @VIRTUAL02
	LDX #.LOWORD(GAME_STATE) + game_state::favourite_food
	LDA #.SIZEOF(game_state::favourite_food)
	JSR NAME_A_CHARACTER
	CMP #0
	BEQ @FOOD_NAME_BACK
	LDA #$FFFF
	STA @VIRTUAL04
	STA @LOCAL08
	BRA @ADVANCE_NAMING
@FOOD_NAME_BACK:
	LDA #1
	STA @VIRTUAL04
	STA @LOCAL08
	BRA @ADVANCE_NAMING
@NAME_THING_ENTRY:
	LDA @VIRTUAL02
	CMP #FILE_MENU_NEW_GAME_NAME::FAVORITE_THING
	BNE @ADVANCE_NAMING
	LOADPTR FILE_SELECT_TEXT_PLEASE_NAME_THEM_STRINGS, @VIRTUAL06
	LDA @VIRTUAL02
	OPTIMIZED_MULT @VIRTUAL04, 15
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA #NAME_THEM_STRING_LENGTH
	STA @LOCAL01
	LDY @VIRTUAL02
	LDX #.LOWORD(GAME_STATE) + game_state::favourite_thing + 2 ; part after 'PK ' prefix
	LDA #.SIZEOF(game_state::favourite_thing) - 3
	JSR NAME_A_CHARACTER
	CMP #0
	BEQ @THING_NAME_BACK
	LDA #$FFFF
	STA @VIRTUAL04
	STA @LOCAL08
	BRA @ADVANCE_NAMING
@THING_NAME_BACK:
	LDA #1
	STA @VIRTUAL04
	STA @LOCAL08
@ADVANCE_NAMING:
	LDA @VIRTUAL02
	JSL INIT_NAMING_SCREEN_EVENTS
	LDA @LOCAL08
	STA @VIRTUAL04
	LDA @VIRTUAL02
	CLC
	ADC @VIRTUAL04
	STA @VIRTUAL02
@NAMING_LOOP_CHECK:
	LDA #THINGS_NAMED_COUNT
	CLC
	SBC @VIRTUAL02
	JUMPGTS @NAMING_LOOP
	JSR CLOSE_ALL_WINDOWS
	JSR SET_INSTANT_PRINTING
	LDX #0
	STX @LOCAL07
	BRA @CONFIRM_NAME_LOOP_CHECK
@SHOW_CONFIRM_NAME:
	TXA
	CLC
	ADC #WINDOW::FILE_SELECT_NAMING_CONFIRMATION_NESS
	JSR CREATE_WINDOW
	LDX @LOCAL07
	INX
	STX @LOCAL06
	TXA
	JSR PRINT_CHARACTER_NAME
	LDX @LOCAL06
	STX @LOCAL07
@CONFIRM_NAME_LOOP_CHECK:
	STX @VIRTUAL02
	LDA #PLAYER_CHAR_COUNT
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @SHOW_CONFIRM_NAME
	CREATE_WINDOW_NEAR #WINDOW::FILE_SELECT_NAMING_CONFIRMATION_KING
	LDA #7
	JSR PRINT_CHARACTER_NAME
	LDA #WINDOW::FILE_SELECT_NAMING_CONFIRMATION_FOOD
	JSR CREATE_WINDOW
	LOADPTR FILE_SELECT_TEXT_FAVORITE_FOOD, @LOCAL00
	LDA #9
	JSR PRINT_STRING
	LDA #.LOWORD(WINDOW_STATS) + window_stats::width
	STA @VIRTUAL02
	STA @LOCAL07
	LDY #.LOWORD(GAME_STATE) + game_state::favourite_food
	STY @LOCAL06
	LDX #6
	TYA
	JSR COUNT_STRING_LENGTH
	LDX #1
	STX @LOCAL05
	PHA
	LDA OPEN_WINDOW_TABLE + WINDOW::FILE_SELECT_NAMING_CONFIRMATION_FOOD * 2
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	PLY
	STY @VIRTUAL02
	SEC
	SBC @VIRTUAL02
	LDX @LOCAL05
	JSR SET_FOCUS_TEXT_CURSOR
	LDY @LOCAL06
	TYA
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #6
	JSR PRINT_STRING
	LDA #WINDOW::FILE_SELECT_NAMING_CONFIRMATION_THING
	JSR CREATE_WINDOW
	LOADPTR FILE_SELECT_TEXT_COOLEST_THING, @LOCAL00
	LDA #11
	JSR PRINT_STRING
	LDY #.LOWORD(GAME_STATE) + game_state::favourite_thing + 2 ; part after 'PSI ' prefix
	STY @LOCAL04
	LDX #6
	TYA
	JSR COUNT_STRING_LENGTH
	LDX #1
	STX @LOCAL05
	PHA
	LDA @LOCAL07
	STA @VIRTUAL02
	LDA OPEN_WINDOW_TABLE + WINDOW::FILE_SELECT_NAMING_CONFIRMATION_THING * 2
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	PLY
	STY @VIRTUAL02
	SEC
	SBC @VIRTUAL02
	LDX @LOCAL05
	JSR SET_FOCUS_TEXT_CURSOR
	LDY @LOCAL04
	TYA
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #7
	JSR PRINT_STRING
	CREATE_WINDOW_NEAR #WINDOW::FILE_SELECT_NAMING_CONFIRMATION_MESSAGE
	LOADPTR FILE_SELECT_TEXT_ARE_YOU_SURE, @LOCAL00
	LDA #12
	JSR PRINT_STRING
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
	LOADPTR FILE_SELECT_TEXT_ARE_YOU_SURE_YEP, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDY #0
	LDX #13
	LDA #1
	JSR ADD_MENU_ITEM
	LOADPTR FILE_SELECT_TEXT_ARE_YOU_SURE_NOPE, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDY #0
	LDX #17
	TYA
	JSR ADD_MENU_ITEM
	JSR PRINT_MENU_ITEMS
	JSL CREATE_FILE_SELECT_PARTY_SPRITES
	LDA #1
	JSR SELECTION_MENU
	TAX
	BNE @EVERYTHING_OKAY
	JSL CLEAR_MAP_ENTITIES
	JMP @BEGIN_NAMING
@EVERYTHING_OKAY:
	LDA #MUSIC::NAME_CONFIRMATION
	JSL CHANGE_MUSIC
	JSL WINDOW_TICK
	LDX #0
	STX @LOCAL03
	BRA @CONFIRM_WAIT_CHECK
@CONFIRM_WAIT_TICK:
	JSL RENDER_FRAME_TICK
	LDX @LOCAL03
	INX
	STX @LOCAL03
@CONFIRM_WAIT_CHECK:
	STX @VIRTUAL02
	LDA #180
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @CONFIRM_WAIT_TICK
	JSL CLEAR_MAP_ENTITIES
	STZ @LOCAL03
	JMP @INIT_CHAR_LOOP_CHECK
@INIT_CHARACTER:
	LDA @LOCAL03
	STA @VIRTUAL04
	INC @VIRTUAL04
	LDA @VIRTUAL04
	STA @LOCAL07
	LOADPTR INITIAL_STATS, @VIRTUAL06
	LDA @LOCAL03
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(initial_stats)
	STA @VIRTUAL02
	LDY #0
	LDA @VIRTUAL02
	CLC
	ADC #initial_stats::level
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	TAX
	LDA @LOCAL07
	STA @VIRTUAL04
	JSR RESET_CHAR_LEVEL_ONE
	LDA @VIRTUAL02
	CLC
	ADC #initial_stats::exp
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	BEQ @AFTER_GAIN_EXP
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #0
	LDA @VIRTUAL04
	JSL GAIN_EXP
@AFTER_GAIN_EXP:
	LDA @LOCAL03
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA PARTY_CHARACTERS+char_struct::max_hp,X
	LDX @VIRTUAL02
	STA PARTY_CHARACTERS+char_struct::current_hp,X
	LDX @VIRTUAL02
	STA PARTY_CHARACTERS+char_struct::current_hp_target,X
	LDX @VIRTUAL02
	LDA PARTY_CHARACTERS+char_struct::max_pp,X
	LDX @VIRTUAL02
	STA PARTY_CHARACTERS+char_struct::current_pp,X
	LDX @VIRTUAL02
	STA PARTY_CHARACTERS+char_struct::current_pp_target,X
	LDX @VIRTUAL02
	STZ PARTY_CHARACTERS+char_struct::current_pp_fraction,X
	LDX @VIRTUAL02
	STZ PARTY_CHARACTERS+char_struct::current_hp_fraction,X
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	TAY
	STY @LOCAL07
	SEP #PROC_FLAGS::ACCUM8
	STZ_BADOPT @LOCAL00
	LDX #14
	REP #PROC_FLAGS::ACCUM8
	TYA
	JSL MEMSET16
	LOADPTR INITIAL_STATS, @VIRTUAL06
	LDA @LOCAL03
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(initial_stats)
	CLC
	ADC #initial_stats::items
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX #.SIZEOF(initial_stats::items)
	LDY @LOCAL07
	TYA
	JSL MEMCPY16
	LDA #$0400
	LDX @VIRTUAL02
	STA PARTY_CHARACTERS+char_struct::hp_pp_window_options,X
	INC @LOCAL03
@INIT_CHAR_LOOP_CHECK:
	LDA #PLAYER_CHAR_COUNT
	CLC
	SBC @LOCAL03
	JUMPGTS @INIT_CHARACTER
	LOADPTR INITIAL_STATS, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	LDY #initial_stats::money
	LDA [@VIRTUAL06],Y
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, GAME_STATE+game_state::money_carried
	MOVE_INT @LOCAL02, @VIRTUAL06
	LDY #initial_stats::unknown2
	LDA [@VIRTUAL06],Y
	OPTIMIZED_MULT @VIRTUAL04, 8
	TAX
	LDA [@VIRTUAL06]
	OPTIMIZED_MULT @VIRTUAL04, 8
	JSL PLACE_LEADER_AT_POSITION
	SEP #PROC_FLAGS::ACCUM8
	LDA #CHAR::P
	STA GAME_STATE+game_state::favourite_thing
	LDA #CHAR::K
	STA GAME_STATE+game_state::favourite_thing+1
	LDA #1
	STA GAME_STATE + game_state::unknownC3
	REP #PROC_FLAGS::ACCUM8
	LDA GAME_STATE+game_state::leader_x_coord
	STA RESPAWN_X
	LDA GAME_STATE+game_state::leader_y_coord
	STA RESPAWN_Y
	JSL RESET_QUEUED_INTERACTIONS
	LDX #1768
	LDA #2112
	JSL PLACE_LEADER_AT_POSITION
	LOADPTR MSG_EVT_PROLOGUE_NEW, @LOCAL00
	JSL FREEZE_AND_QUEUE_TEXT_INTERACTION
	LDX #1
	LDA #EVENT_FLAG::FLG_SYS_MONSTER_OFF
	JSL SET_EVENT_FLAG
	LDA #1
	STA SHOW_NPC_FLAG
@START_GAME:
	JSR CLOSE_ALL_WINDOWS
	JSL INIT_ALL_ITEM_TRANSFORMATIONS
	LDA GAME_STATE+game_state::text_speed
	AND #$00FF
	TAX
	DEC
	STA @LOCAL07
	LOADPTR HP_METER_SPEEDS, @VIRTUAL0A
	LDA @LOCAL07
	ASL
	ASL
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, HP_METER_SPEED
	LDA @LOCAL07
	STA SELECTED_TEXT_SPEED
	CPX #3
	BNE @NON_FAST_SPEED
	LDA #0
	BRA @SET_TEXT_SPEED_WAIT
@NON_FAST_SPEED:
	TXA
	OPTIMIZED_MULT @VIRTUAL04, 30
@SET_TEXT_SPEED_WAIT:
	STA TEXT_SPEED_BASED_WAIT
	STZ UNREAD_7E5DBA
	DISPLAY_TEXT_PTR MSG_SYS_PRE_GAMESTART
	END_C_FUNCTION
