
GAS_STATION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	JSL INIT_ENTITY_SYSTEM
	JSR GAS_STATION_LOAD
	LDX #11
	LDA #1
	JSL FADE_IN
	JSR RUN_GAS_STATION_CREDITS
	TAY
	STY @LOCAL02
	BEQ @CREDITS_FINISHED
	LDA #1
	BRA @EXIT
@CREDITS_FINISHED:
	LDX #0
	STX @LOCAL01
	BRA @CHECK_WAIT_TIMER
@WAIT_LOOP:
	LDA PAD_PRESS
	BEQ @NO_BUTTON_PRESS
	LDA #1
	BRA @EXIT
@NO_BUTTON_PRESS:
	JSL UPDATE_MAP_PALETTE_ANIMATION
	JSL WAIT_UNTIL_NEXT_FRAME
	LDX @LOCAL01
	INX
	STX @LOCAL01
@CHECK_WAIT_TIMER:
	CPX #330
	BCC @WAIT_LOOP
	SEP #PROC_FLAGS::ACCUM8
	STZ TM_MIRROR
	STZ_BADOPT @LOCAL00
	LDX #BPP4PALETTE_SIZE * 16
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(PALETTES)
	JSL MEMSET16
	SEP #PROC_FLAGS::ACCUM8
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
	LDY @LOCAL02
	BNE @AFTER_BLANK_SCREEN
	REP #PROC_FLAGS::ACCUM8
	LDA #30
	JSR WAIT_FRAMES_OR_UNTIL_PRESSED
@AFTER_BLANK_SCREEN:
	LDY @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	TYA
@EXIT:
	END_C_FUNCTION
