
INIT_NAMING_SCREEN_EVENTS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL02
	BRA @CHECK_ACTIONSCRIPT
@WAIT_ACTIONSCRIPT:
	JSL RENDER_FRAME_TICK
@CHECK_ACTIONSCRIPT:
	LDA WAIT_FOR_NAMING_SCREEN_ACTIONSCRIPT
	BNE @WAIT_ACTIONSCRIPT
	LOADPTR NAMING_SCREEN_ENTITIES + (7*4), @VIRTUAL0A
	LDA @LOCAL02
	ASL
	ASL
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	BRA @CHECK_ENTITY_LIST
@PROCESS_ENTITY:
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	INC @VIRTUAL0A
	INC @VIRTUAL0A
	JSL FIND_ENTITY_BY_SPRITE_ID
	TAX
	CPX #.LOWORD(-1)
	BEQ @ADVANCE_ENTITY_LIST
	LOADPTR EVENT_SCRIPT_POINTERS, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDA [@VIRTUAL0A]
	OPTIMIZED_MULT @VIRTUAL04, 3
	STA @LOCAL00
	INC
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	TAY
	LDA @LOCAL00
	PHA
	MOVE_INT @LOCAL01, @VIRTUAL06
	PLA
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	JSL REASSIGN_ENTITY_SCRIPT_FAR
@ADVANCE_ENTITY_LIST:
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	INC @VIRTUAL06
	INC @VIRTUAL06
@CHECK_ENTITY_LIST:
	LDA [@VIRTUAL06]
	BNE @PROCESS_ENTITY
@WAIT_ALL_SCRIPTS:
	LDY #.LOWORD(ENTITY_SCRIPT_TABLE)
	LDA #.LOWORD(-1)
	STA @LOCAL00
	LDX #0
	BRA @CHECK_SLOT_COUNT
@AND_SCRIPT_TABLE:
	LDA __BSS_START__,Y
	STA @VIRTUAL02
	LDA @LOCAL00
	AND @VIRTUAL02
	STA @LOCAL00
	INY
	INY
	INX
@CHECK_SLOT_COUNT:
	CPX #PARTY_LEADER_ENTITY_INDEX - 1
	BCC @AND_SCRIPT_TABLE
	JSL RENDER_FRAME_TICK
	LDA @LOCAL00
	CMP #.LOWORD(-1)
	BNE @WAIT_ALL_SCRIPTS
	END_C_FUNCTION
