
INIT_INTRO:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
.IF .DEFINED(JPN) || .DEFINED(PROTOTYPE19950327)
	STACK_RESERVE_INT16
.ENDIF
	END_STACK_VARS
.IF .DEFINED(JPN) || .DEFINED(PROTOTYPE19950327)
	.DEFINE _BEQL BEQ
	LDY #0
	STY @LOCAL01
.ELSE
	.DEFINE _BEQL BEQL ;the final build of earthbound introduced some code for the logo and title screens, so some cases need long branches
	LDA #0
	STA @VIRTUAL02
.ENDIF
	LDA #1
	STA DISABLED_TRANSITIONS
	LDA #2
	JSL WRITE_APU_PORT1
	JSL INIT_ENTITY_SYSTEM
	JSL INITIALIZE_BATTLE_UI_STATE
	JSL CLEAR_ALL_STATUS_EFFECTS
	LDA #1
	STA DISABLE_MUSIC_CHANGES
.IF .DEFINED(USA)
	STZ BG3_X_POS
	STZ BG3_Y_POS
	STZ BG2_Y_POS
	STZ BG2_X_POS
	STZ BG1_Y_POS
	STZ BG1_X_POS
	JSL UPDATE_SCREEN
	STZ BG3_X_POS
	STZ BG3_Y_POS
	STZ BG2_Y_POS
	STZ BG2_X_POS
	STZ BG1_Y_POS
	STZ BG1_X_POS
	JSL UPDATE_SCREEN
.ENDIF
@STATE_DISPATCH:
.IF .DEFINED(JPN) || .DEFINED(PROTOTYPE19950327)
	LDY @LOCAL01
	TYA
.ELSE
	LDA @VIRTUAL02
.ENDIF
	BEQ @STATE_LOGO_SCREEN
	CMP #1
	_BEQL @STATE_GAS_STATION
	CMP #2
	_BEQL @STATE_TITLE_SCREEN
	CMP #3
	_BEQL @STATE_ATTRACT_0
	CMP #4
	_BEQL @STATE_ATTRACT_2
	CMP #5
	_BEQL @STATE_ATTRACT_3
	CMP #6
	BEQL @STATE_ATTRACT_4
	CMP #7
	BEQL @STATE_ATTRACT_5
	CMP #8
	BEQL @STATE_ATTRACT_6
	CMP #9
	BEQL @STATE_ATTRACT_7
	CMP #10
	BEQL @STATE_ATTRACT_9
	JMP @STATE_DEFAULT_RESET
@STATE_LOGO_SCREEN:
	JSL LOGO_SCREEN
.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
	CMP #0
	BEQ @LOGO_NO_BUTTON
	LDA #2
	JSL WRITE_APU_PORT1
	LDA INIDISP_MIRROR
	AND #$00FF
	CMP #$80
	BEQ @LOGO_ALREADY_OFF
	LDY #0
	LDX #1
	LDA #4
	JSL FADE_OUT_WITH_MOSAIC
@LOGO_ALREADY_OFF:
	LDA #MUSIC::TITLE_SCREEN
	JSL CHANGE_MUSIC
	LDA #1
	JSL SHOW_TITLE_SCREEN
	TAX
	STX @LOCAL00
	LDA #2
	STA @VIRTUAL02
	JMP @ADVANCE_STATE
@LOGO_NO_BUTTON:
	LDX #0
.ELSE
	TAX
.ENDIF
	STX @LOCAL00
	JMP @ADVANCE_STATE
@STATE_GAS_STATION:
	LDA #MUSIC::GAS_STATION
	JSL CHANGE_MUSIC
	JSL GAS_STATION
.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
	CMP #0
	BEQ @GAS_NO_BUTTON
	LDA #2
	JSL WRITE_APU_PORT1
	LDA INIDISP_MIRROR
	AND #$00FF
	CMP #$80
	BEQ @GAS_ALREADY_OFF
	LDY #0
	LDX #1
	LDA #4
	JSL FADE_OUT_WITH_MOSAIC
@GAS_ALREADY_OFF:
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA f:CGADSUB
	STA f:CGWSEL
	LDA #1
	STA TM_MIRROR
	STZ TD_MIRROR
	REP #PROC_FLAGS::ACCUM8
	LDA #MUSIC::TITLE_SCREEN
	JSL CHANGE_MUSIC
	LDA #1
	JSL SHOW_TITLE_SCREEN
	TAX
	STX @LOCAL00
	INC @VIRTUAL02
	JMP @ADVANCE_STATE
@GAS_NO_BUTTON:
	LDX #0
.ELSE
	TAX
.ENDIF
	STX @LOCAL00
	JMP @ADVANCE_STATE
@STATE_TITLE_SCREEN:
	LDA #MUSIC::TITLE_SCREEN
	JSL CHANGE_MUSIC
	LDA #0
	JSL SHOW_TITLE_SCREEN
	TAX
	STX @LOCAL00
	BRA @ADVANCE_STATE
@STATE_ATTRACT_0:
	LDA #MUSIC::ATTRACT_MODE
	JSL CHANGE_MUSIC
	LDA #0
	JSL RUN_ATTRACT_MODE
	TAX
	STX @LOCAL00
	BRA @ADVANCE_STATE
@STATE_ATTRACT_2:
	LDA #2
	JSL RUN_ATTRACT_MODE
	TAX
	STX @LOCAL00
	BRA @ADVANCE_STATE
@STATE_ATTRACT_3:
	LDA #3
	JSL RUN_ATTRACT_MODE
	TAX
	STX @LOCAL00
	BRA @ADVANCE_STATE
@STATE_ATTRACT_4:
	LDA #4
	JSL RUN_ATTRACT_MODE
	TAX
	STX @LOCAL00
	BRA @ADVANCE_STATE
@STATE_ATTRACT_5:
	LDA #5
	JSL RUN_ATTRACT_MODE
	TAX
	STX @LOCAL00
	BRA @ADVANCE_STATE
@STATE_ATTRACT_6:
	LDA #6
	JSL RUN_ATTRACT_MODE
	TAX
	STX @LOCAL00
	BRA @ADVANCE_STATE
@STATE_ATTRACT_7:
	LDA #7
	JSL RUN_ATTRACT_MODE
	TAX
	STX @LOCAL00
	BRA @ADVANCE_STATE
@STATE_ATTRACT_9:
	LDA #9
	JSL RUN_ATTRACT_MODE
	TAX
	STX @LOCAL00
	BRA @ADVANCE_STATE
@STATE_DEFAULT_RESET:
.IF .DEFINED(JPN) || .DEFINED(PROTOTYPE19950327)
	LDY #1
	STY @LOCAL01
.ELSE
	LDA #1
	STA @VIRTUAL02
.ENDIF
@ADVANCE_STATE:
.IF .DEFINED(JPN) || .DEFINED(PROTOTYPE19950327)
	LDY @LOCAL01
	INY
	STY @LOCAL01
.ELSE
	INC @VIRTUAL02
.ENDIF
	LDX @LOCAL00
	BEQL @STATE_DISPATCH
	LDA #2
	JSL WRITE_APU_PORT1
.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
	SEP #PROC_FLAGS::ACCUM8
	STZ FADE_PARAMETERS + fade_parameters::step
	REP #PROC_FLAGS::ACCUM8
.ENDIF
	LDA INIDISP_MIRROR
	AND #$00FF
	CMP #$80
	BEQ @ALREADY_FADED_OUT
	LDY #0
	LDX #1
	LDA #4
	JSL FADE_OUT_WITH_MOSAIC
@ALREADY_FADED_OUT:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00
	STA f:CGADSUB
	STA f:CGWSEL
	LDA #$01
	STA TM_MIRROR
	STZ TD_MIRROR
	REP #PROC_FLAGS::ACCUM8
	STZ DISABLE_MUSIC_CHANGES
	END_C_FUNCTION
