
LOGO_SCREEN:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA #0
	JSR LOGO_SCREEN_LOAD
	LDY #0
	LDX #2
	LDA #1
	JSL FADE_IN_WITH_MOSAIC
	LDA DEBUG
	BEQ @NOT_DEBUG
	LDA #180
	JSR WAIT_FRAMES_OR_UNTIL_PRESSED
	BRA @FADE_OUT_NINTENDO
@NOT_DEBUG:
	LDX #0
	STX @LOCAL00
	BRA @WAIT_CHECK
@WAIT_LOOP:
	JSL WAIT_UNTIL_NEXT_FRAME
	LDX @LOCAL00
	INX
	STX @LOCAL00
@WAIT_CHECK:
	CPX #180
	BCC @WAIT_LOOP
@FADE_OUT_NINTENDO:
	LDY #0
	LDX #2
	LDA #1
	JSL FADE_OUT_WITH_MOSAIC
	LDA #1
	JSR LOGO_SCREEN_LOAD
	LDY #0
	LDX #2
	LDA #1
	JSL FADE_IN_WITH_MOSAIC
	LDA #120
	JSR WAIT_FRAMES_OR_UNTIL_PRESSED
	CMP #0
	BEQ @APE_NO_BUTTON
	LDY #0
	LDX #1
	LDA #2
	JSL FADE_OUT_WITH_MOSAIC
	LDA #1
	BRA @RETURN
@APE_NO_BUTTON:
	LDY #0
	LDX #2
	LDA #1
	JSL FADE_OUT_WITH_MOSAIC
	LDA #2
	JSR LOGO_SCREEN_LOAD
	LDY #0
	LDX #2
	LDA #1
	JSL FADE_IN_WITH_MOSAIC
	LDA #120
	JSR WAIT_FRAMES_OR_UNTIL_PRESSED
	CMP #0
	BEQ @HAL_NO_BUTTON
	LDY #0
	LDX #1
	LDA #2
	JSL FADE_OUT_WITH_MOSAIC
	LDA #1
	BRA @RETURN
@HAL_NO_BUTTON:
	LDY #0
	LDX #2
	LDA #1
	JSL FADE_OUT_WITH_MOSAIC
	LDA #0
@RETURN:
	END_C_FUNCTION
