
LOGO_SCREEN_LOAD:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL02
	LDA #1
	JSL SET_BGMODE
	LDY #$0000
	LDX #$4000
	TYA ;BG_TILEMAP_SIZE::NORMAL
	JSL SET_BG3_VRAM_LOCATION
	SEP #PROC_FLAGS::ACCUM8
	LDA #4
	STA TM_MIRROR
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
	BEQ @LOAD_NINTENDO
	CMP #1
	BEQ @LOAD_APE
	CMP #2
	BEQL @LOAD_HAL
	JMP @UPLOAD_TO_VRAM
@LOAD_NINTENDO:
	LOADPTR NINTENDO_GRAPHICS, @LOCAL00
	LOADPTR BUFFER, @LOCAL01
	JSL DECOMP
	LOADPTR NINTENDO_ARRANGEMENT, @LOCAL00
	LOADPTR INTRO_BG2_BUFFER, @LOCAL01
	JSL DECOMP
	LOADPTR NINTENDO_PALETTE, @LOCAL00
	PROMOTENEARPTR PALETTES, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DECOMP
	JMP @UPLOAD_TO_VRAM
@LOAD_APE:
	LOADPTR APE_GRAPHICS, @LOCAL00
	LOADPTR BUFFER, @LOCAL01
	JSL DECOMP
	LOADPTR APE_ARRANGEMENT, @LOCAL00
	LOADPTR INTRO_BG2_BUFFER, @LOCAL01
	JSL DECOMP
	LOADPTR APE_PALETTE, @LOCAL00
	PROMOTENEARPTR PALETTES, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DECOMP
	BRA @UPLOAD_TO_VRAM
@LOAD_HAL:
	LOADPTR HALKEN_GRAPHICS, @LOCAL00
	LOADPTR BUFFER, @LOCAL01
	JSL DECOMP
	LOADPTR HALKEN_ARRANGEMENT, @LOCAL00
	LOADPTR INTRO_BG2_BUFFER, @LOCAL01
	JSL DECOMP
	LOADPTR HALKEN_PALETTE, @LOCAL00
	PROMOTENEARPTR PALETTES, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DECOMP
@UPLOAD_TO_VRAM:
	COPY_TO_VRAM1 BUFFER, $0000, $8000, 0
	.A16
	COPY_TO_VRAM1 INTRO_BG2_BUFFER, $4000, $800, 0
	.A16
	SEP #PROC_FLAGS::ACCUM8
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
