
RECORD_DEMO_INPUT:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	LDA <DEMO_RECORDING_FLAGS + 0
	AND #DEMO_RECORDING_FLAG::RECORDING
	BEQ @DONE
	LDA <PAD_RAW +0
	ORA <PAD_RAW +2
	TAX
	CMP <DEMO_LAST_INPUT +0
	BNE @WRITE_INPUT
	INC <DEMO_SAME_INPUT_FRAMES
	LDA <DEMO_SAME_INPUT_FRAMES + 0
	CMP #$00FF
	BNE @DONE
@WRITE_INPUT:
	LDA <DEMO_SAME_INPUT_FRAMES + 0
	STA [<DEMO_WRITE_DESTINATION]
	INC <DEMO_WRITE_DESTINATION
	LDA <DEMO_LAST_INPUT + 0
	STA [<DEMO_WRITE_DESTINATION]
	INC <DEMO_WRITE_DESTINATION
	INC <DEMO_WRITE_DESTINATION
	STX <DEMO_LAST_INPUT
	STZ <DEMO_SAME_INPUT_FRAMES
	INC <DEMO_SAME_INPUT_FRAMES
	LDA #$0000
	STA [<DEMO_WRITE_DESTINATION]
	LDA <DEMO_WRITE_DESTINATION + 0
	BPL @DONE
	LDA <DEMO_RECORDING_FLAGS + 0
	AND #$FFFF ^ DEMO_RECORDING_FLAG::RECORDING
	STA <DEMO_RECORDING_FLAGS
@DONE:
	RTS
