
RENDER_PARTY_MEMBER_NAME:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	PROMOTENEARPTRA @VIRTUAL06
	LDX #0
	STX @LOCAL01
	BRA @CHAR_LOOP_CHECK
@RENDER_CHAR:
	INC @VIRTUAL06
	LDA @LOCAL00
	JSL RENDER_LARGE_FONT_CHARACTER
	LDX @LOCAL01
	INX
	STX @LOCAL01
@CHAR_LOOP_CHECK:
	CPX #5
	BCS @RETURN
	REP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	AND #$00FF
	STA @LOCAL00
	CLC
	SBC #79
	BRANCHGTS @RENDER_CHAR
@RETURN:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
