
RENDER_CHARACTER_NAME_DISPLAY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STA @LOCAL0D
	STZ @LOCAL0C
	STZ @LOCAL0B
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL0A
	STZ VWF_TILE
	STZ VWF_X
	SEP #PROC_FLAGS::ACCUM8
	LDA #<-1
	STA @LOCAL00
.IF .DEFINED(PROTOTYPE19950327)
	LDX #512
.ELSE
	LDX #1024
.ENDIF
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(VWF_BUFFER)
	JSL MEMSET16
	LDA #4
	STA @VIRTUAL04
	PROMOTENEARPTR PARTY_CHARACTERS + char_struct::name, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL STRLEN
	TAY
	STY @LOCAL09
.IF .DEFINED(PROTOTYPE19950327)
	CPY #6
	BNE @NAME_LENGTH_CLAMPED
	DEY
.ELSE
	CPY #5
	BLTEQ @NAME_LENGTH_CLAMPED
	LDY #5
.ENDIF
	STY @LOCAL09
@NAME_LENGTH_CLAMPED:
	LDA #6
	STA @LOCAL08
	PROMOTENEARPTR PARTY_CHARACTERS + char_struct::name, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	STZ @LOCAL07
	BRA @PREFIX_LOOP_CHECK
@PREFIX_LOOP_BODY:
	LDX @LOCAL07
	LDA f:LUMINE_HALL_TEXT,X
	AND #$00FF
	TAX
	LDA @LOCAL0D
	JSL RENDER_FONT_GLYPH
	INC @LOCAL07
@PREFIX_LOOP_CHECK:
	LDA @VIRTUAL04
	CLC
	SBC @LOCAL07
	BRANCHGTS @PREFIX_LOOP_BODY
	LDA #0
	STA @VIRTUAL04
	BRA @NAME_LOOP_CHECK
@NAME_LOOP_BODY:
	LDA [@VIRTUAL06]
	AND #$00FF
	TAX
	INC @VIRTUAL06
	LDA @LOCAL0D
	JSL RENDER_FONT_GLYPH
	INC @VIRTUAL04
@NAME_LOOP_CHECK:
	LDY @LOCAL09
	TYA
	CLC
	SBC @VIRTUAL04
	BRANCHGTS @NAME_LOOP_BODY
	LDY #0
	STY @LOCAL06
	BRA @SUFFIX_LOOP_CHECK
@SUFFIX_LOOP_BODY:
	TYX
	LDA f:LUMINE_HALL_TEXT+4,X
	AND #$00FF
	TAX
	LDA @LOCAL0D
	JSL RENDER_FONT_GLYPH
	LDY @LOCAL06
	INY
	STY @LOCAL06
@SUFFIX_LOOP_CHECK:
	STY @VIRTUAL04
	LDA @LOCAL08
	CLC
	SBC @VIRTUAL04
	BRANCHGTS @SUFFIX_LOOP_BODY
	LDA VWF_X
	CLC
	ADC @LOCAL0B
	STA @LOCAL08
	LDY #0
	STY @LOCAL09
	TYX
	STX @LOCAL05
	JMP @COPY_INITIAL_TILES_CHECK
@COPY_INITIAL_TILES_BODY:
	LOADPTR BUFFER, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL04
	PROMOTENEARPTR VWF_BUFFER, @VIRTUAL0A
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	TXA
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL01
	LDA @VIRTUAL06+2
	STA @LOCAL01+2
	LDA #16
	JSL MEMCPY24
	LDX @LOCAL05
	TXA
	CLC
	ADC #16
	TAX
	STX @LOCAL06
	LDA @VIRTUAL02
	CLC
	ADC #256
	MOVE_INTY @LOCAL04, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	TXA
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL01
	LDA @VIRTUAL06+2
	STA @LOCAL01+2
	LDA #16
	JSL MEMCPY24
	LDX @LOCAL06
	TXA
	CLC
	ADC #16
	TAX
	STX @LOCAL05
	LDA @VIRTUAL02
	CLC
	ADC #16
	STA @VIRTUAL02
	STA @LOCAL0A
	LDY @LOCAL09
	INY
	STY @LOCAL09
@COPY_INITIAL_TILES_CHECK:
	LDA VWF_X
	LSR
	LSR
	LSR
	STA @LOCAL06
	STA @VIRTUAL04
	TYA
	CMP @VIRTUAL04
	BCCL @COPY_INITIAL_TILES_BODY
	LDA #205
	STA @LOCAL0B
	PROMOTENEARPTR VWF_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @LOCAL06
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL01
	LDA @VIRTUAL06+2
	STA @LOCAL01+2
	LDA #32
	JSL MEMCPY24
	STZ VWF_TILE
	LDY #8
	LDA VWF_X
	JSL MODULUS16
	STA VWF_X
	LDA #0
	STA @VIRTUAL04
	JMP @RENDER_LUMINE_TEXT_CHECK
@RENDER_LUMINE_TEXT_BODY:
	LDA @LOCAL0C
	CLC
	SBC #16
	JUMPLTEQS @RENDER_LUMINE_GLYPH
	STZ @LOCAL0C
	LDA VWF_X
	CLC
	ADC @LOCAL08
	STA @LOCAL08
	LDY #0
	STY @LOCAL09
	TYX
	STX @LOCAL05
	JMP @COPY_LUMINE_TILES_CHECK
@COPY_LUMINE_TILES_BODY:
	LOADPTR BUFFER, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL04
	PROMOTENEARPTR VWF_BUFFER, @VIRTUAL0A
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL0A
	STA @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	TXA
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL01
	LDA @VIRTUAL06+2
	STA @LOCAL01+2
	LDA #16
	JSL MEMCPY24
	LDX @LOCAL05
	TXA
	CLC
	ADC #16
	TAX
	STX @LOCAL05
	LDA @VIRTUAL02
	CLC
	ADC #256
	MOVE_INTY @LOCAL04, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	TXA
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL01
	LDA @VIRTUAL06+2
	STA @LOCAL01+2
	LDA #16
	JSL MEMCPY24
	LDX @LOCAL05
	TXA
	CLC
	ADC #16
	TAX
	STX @LOCAL05
	LDA @VIRTUAL02
	CLC
	ADC #16
	STA @VIRTUAL02
	STA @LOCAL0A
	LDY #256
	LDA @VIRTUAL02
	JSL MODULUS16S
	CMP #0
	BNE @SKIP_BOUNDARY_ADJUST
	LDA @VIRTUAL02
	CLC
	ADC #256
	STA @VIRTUAL02
	STA @LOCAL0A
@SKIP_BOUNDARY_ADJUST:
	LDY @LOCAL09
	INY
	STY @LOCAL09
@COPY_LUMINE_TILES_CHECK:
	LDA VWF_X
	LSR
	LSR
	LSR
	STA @LOCAL07
	STA @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BCCL @COPY_LUMINE_TILES_BODY
	LDY #8
	LDA VWF_X
	JSL MODULUS16
	CMP #0
	BEQ @VWF_ALIGNED_RESET
	PROMOTENEARPTR VWF_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @LOCAL07
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL01
	LDA @VIRTUAL06+2
	STA @LOCAL01+2
	LDA #32
	JSL MEMCPY24
	SEP #PROC_FLAGS::ACCUM8
	LDA #<-1
	STA @LOCAL00
	LDX #480
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(VWF_BUFFER) + 32
	JSL MEMSET16
	STZ VWF_TILE
	LDY #8
	LDA VWF_X
	JSL MODULUS16
	STA VWF_X
	BRA @RENDER_LUMINE_GLYPH
@VWF_ALIGNED_RESET:
	STZ VWF_X
	STZ VWF_TILE
	SEP #PROC_FLAGS::ACCUM8
	LDA #<-1
	STA @LOCAL00
	LDX #512
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(VWF_BUFFER)
	JSL MEMSET16
@RENDER_LUMINE_GLYPH:
	LDX @VIRTUAL04
	LDA f:LUMINE_HALL_TEXT+10,X
	AND #$00FF
	TAX
	LDA @LOCAL0D
	JSL RENDER_FONT_GLYPH
	INC @LOCAL0C
	INC @VIRTUAL04
@RENDER_LUMINE_TEXT_CHECK:
	LDA @LOCAL0B
	CLC
	SBC @VIRTUAL04
	JUMPGTS @RENDER_LUMINE_TEXT_BODY
	LDA VWF_X
	CLC
	ADC @LOCAL08
	STA @VIRTUAL04
	LDY #0
	STY @LOCAL09
	TYX
	STX @LOCAL05
	JMP @COPY_FINAL_TILES_CHECK
@COPY_FINAL_TILES_BODY:
	LOADPTR BUFFER, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL03
	PROMOTENEARPTR VWF_BUFFER, @VIRTUAL0A
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL0A
	STA @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	TXA
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL01
	LDA @VIRTUAL06+2
	STA @LOCAL01+2
	LDA #16
	JSL MEMCPY24
	LDX @LOCAL05
	TXA
	CLC
	ADC #16
	TAX
	STX @LOCAL02
	LDA @VIRTUAL02
	CLC
	ADC #256
	MOVE_INTY @LOCAL03, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	TXA
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL01
	LDA @VIRTUAL06+2
	STA @LOCAL01+2
	LDA #16
	JSL MEMCPY24
	LDX @LOCAL02
	TXA
	CLC
	ADC #16
	TAX
	STX @LOCAL05
	LDA @VIRTUAL02
	CLC
	ADC #16
	STA @VIRTUAL02
	STA @LOCAL0A
	LDY #256
	LDA @VIRTUAL02
	JSL MODULUS16S
	CMP #0
	BNE @SKIP_FINAL_BOUNDARY
	LDA @VIRTUAL02
	CLC
	ADC #256
	STA @VIRTUAL02
	STA @LOCAL0A
@SKIP_FINAL_BOUNDARY:
	LDY @LOCAL09
	INY
	STY @LOCAL09
@COPY_FINAL_TILES_CHECK:
	LDA VWF_X
	LSR
	LSR
	LSR
.IF .DEFINED(PROTOTYPE19950327)
	STA @VIRTUAL02
	INC @VIRTUAL02
.ELSE
	CLC
	ADC #16
	STA @VIRTUAL02
.ENDIF
	TYA
	CMP @VIRTUAL02
	BCCL @COPY_FINAL_TILES_BODY
	LDA @VIRTUAL04
	ASL
	PHP
	LSR
	LSR
	LSR
	LSR
	PLP
	BCC @NO_SIGN_EXTEND
	ORA #$F000
@NO_SIGN_EXTEND:
	ASL
	ASL
	END_C_FUNCTION
