
RENDER_PARTY_MEMBER_NAME:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TXY
	STY @LOCAL01
	TAX
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	PROMOTENEARPTRA @VIRTUAL06
	LDX #4
	STX @LOCAL00
	BRA @CHAR_LOOP_CHECK
@RENDER_CHAR:
	.A16
	DEX
	STX @LOCAL00
	AND #$00FF
	SEC
	SBC #32
	TAX
	LDA f:JP_FONT_WIDTH_TABLE,X
	AND #$00FF
	CLC
	ADC #$8000
	INC @VIRTUAL06
	JSL RENDER_VWF_GLYPH
	LDY @LOCAL01
	TYA
	CLC
	ADC FLYOVER_VWF_X
	STA FLYOVER_VWF_X
@CHAR_LOOP_CHECK:
	REP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	AND #$00FF
	BEQ @RETURN
	LDX @LOCAL00
	BNE @RENDER_CHAR
@RETURN:
	END_C_FUNCTION
