
RUN_TITLE_SEQUENCE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA #0
	STA @VIRTUAL04
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	JSL INIT_ENTITY_SYSTEM
	JSL LOAD_TITLE_SCREEN_GRAPHICS
	SEP #PROC_FLAGS::ACCUM8
	LDA #$11
	STA TM_MIRROR
	JSL OAM_CLEAR
	.A16
	LDA #1
	STA TITLE_SCREEN_QUICK_MODE
	LDY #0
	TYX
.IF .DEFINED(JPN)
	LDA #EVENT_SCRIPT::TITLE_SCREEN_4
.ELSE
	LDA #EVENT_SCRIPT::TITLE_SCREEN_1
.ENDIF
	JSL INIT_ENTITY_WIPE
	STZ ACTIONSCRIPT_STATE
	JSL RENDER_FRAME_TICK
	LDX #1
	LDA #16
	JSL FADE_IN
	LDX #0
	STX @LOCAL00
	BRA @DELAY_LOOP_CHECK
@DELAY_LOOP_BODY:
	JSL RENDER_FRAME_TICK
	LDX @LOCAL00
	INX
	STX @LOCAL00
@DELAY_LOOP_CHECK:
	CPX #60
	BCC @DELAY_LOOP_BODY
	LDA #0
	STA @VIRTUAL02
	BRA @INPUT_LOOP_CHECK
@INPUT_LOOP_BODY:
	LDA @VIRTUAL04
	BNE @NO_BUTTON
	LDA PAD_PRESS
	AND #PAD::A_BUTTON
	BNE @BUTTON_PRESSED
	LDA PAD_PRESS
	AND #PAD::B_BUTTON
	BNE @BUTTON_PRESSED
	LDA PAD_PRESS
	AND #PAD::START_BUTTON
	BEQ @NO_BUTTON
@BUTTON_PRESSED:
	LDA #1
	STA @VIRTUAL02
	BRA @FADE_OUT
@NO_BUTTON:
	JSL RENDER_FRAME_TICK
@INPUT_LOOP_CHECK:
	LDA ACTIONSCRIPT_STATE
	BEQ @INPUT_LOOP_BODY
	LDA ACTIONSCRIPT_STATE
	CMP #2
	BEQ @INPUT_LOOP_BODY
@FADE_OUT:
	LDY #0
	LDX #4
	LDA #1
	JSL FADE_OUT_WITH_MOSAIC
	STZ ACTIONSCRIPT_STATE
	LDA #0
	JSL SETUP_ENTITY_COLOR_MATH
	JSL INIT_ENTITY_SYSTEM
	LDA @VIRTUAL02
	END_C_FUNCTION
