
SHOW_TITLE_SCREEN:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL02
	STA TITLE_SCREEN_QUICK_MODE
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	LDA @VIRTUAL02
	BNE @QUICK_MODE
	JSL INIT_ENTITY_SYSTEM
	BRA @AFTER_INIT
@QUICK_MODE:
	LDY #0
	LDX #1
	TXA
	JSL FADE_OUT_WITH_MOSAIC
	LDA #0
	STA @LOCAL02
	BRA @ENTITY_HIDE_LOOP_CHECK
@HIDE_ENTITY:
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #$8000
	STA __BSS_START__,X
	LDA @LOCAL02
	INC
	STA @LOCAL02
@ENTITY_HIDE_LOOP_CHECK:
	CMP #MAX_ENTITIES
	BCC @HIDE_ENTITY
@AFTER_INIT:
	LDA #9
	JSL SET_BGMODE
	LDA #1
	JSL SET_OAM_SIZE
	LDY #$0000
	LDX #$3800
	TYA ;BG_TILEMAP_SIZE::NORMAL
	JSL SET_BG1_VRAM_LOCATION
	LDY #$1000
	LDX #$3C00
	LDA #BG_TILEMAP_SIZE::NORMAL
	JSL SET_BG2_VRAM_LOCATION
	STZ BG3_X_POS
	STZ BG3_Y_POS
	STZ BG2_Y_POS
	STZ BG2_X_POS
	STZ BG1_Y_POS
	STZ BG1_X_POS
	JSL UPDATE_SCREEN
	JSL LOAD_TITLE_SCREEN_GRAPHICS
	LDA @VIRTUAL02
	BNE @TM_QUICK
	LDX #$10
	BRA @AFTER_TM
@TM_QUICK:
	LDX #$13
@AFTER_TM:
	TXA
	SEP #PROC_FLAGS::ACCUM8
	STA TM_MIRROR
	JSL BLANK_SCREEN_AND_WAIT_VBLANK
	JSL OAM_CLEAR
@SETUP_DISPLAY:
	.A16
	LDX #1
	TXA
	JSL FADE_IN
	LDY #0
	TYX
	LDA #EVENT_SCRIPT::TITLE_SCREEN_1
	JSL INIT_ENTITY_WIPE
	STZ ACTIONSCRIPT_STATE
	LDY #0
	STY @LOCAL01
	BRA @CHECK_SCRIPT
@MAIN_LOOP:
	LDA @VIRTUAL02
	BNE @WAIT_SCRIPT
	LDA PAD_PRESS
	AND #PAD::A_BUTTON
	BNE @BUTTON_PRESSED
	LDA PAD_PRESS
	AND #PAD::B_BUTTON
	BNE @BUTTON_PRESSED
	LDA PAD_PRESS
	AND #PAD::START_BUTTON
	BEQ @WAIT_SCRIPT
@BUTTON_PRESSED:
	LDY #1
	STY @LOCAL01
	BRA @FADE_OUT
@WAIT_SCRIPT:
	JSL RENDER_FRAME_TICK
@CHECK_SCRIPT:
	LDA ACTIONSCRIPT_STATE
	BEQ @MAIN_LOOP
@FADE_OUT:
	LDX #1
	TXA
	JSL FADE_OUT
	BRA @WAIT_FADE_CHECK
@WAIT_FADE_FRAME:
	JSL RENDER_FRAME_TICK
@WAIT_FADE_CHECK:
	LDA FADE_PARAMETERS + fade_parameters::step
	AND #$00FF
	BNE @WAIT_FADE_FRAME
	LDA @VIRTUAL02
	BNE @CLEANUP_ENTITIES
	STZ ACTIONSCRIPT_STATE
	LDA #0
	JSL SETUP_ENTITY_COLOR_MATH
	JSL INIT_ENTITY_SYSTEM
	LDY @LOCAL01
	TYA
	BRA @RETURN
@CLEANUP_ENTITIES:
	LDX #0
	STX @LOCAL00
	BRA @ENTITY_LOOP_CHECK
@PROCESS_ENTITY:
	TXA
	ASL
	TAX
	LDA ENTITY_SCRIPT_TABLE,X
	CMP #EVENT_SCRIPT::TITLE_SCREEN_1
	BCC @SKIP_DEACTIVATE
	CMP #EVENT_SCRIPT::TITLE_SCREEN_7
	BGT @SKIP_DEACTIVATE
	LDX @LOCAL00
	TXA
	JSL DEACTIVATE_ENTITY_FAR
@SKIP_DEACTIVATE:
	LDX @LOCAL00
	TXA
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAY
	LDA __BSS_START__,Y
	AND #$7FFF
	STA __BSS_START__,Y
	INX
	STX @LOCAL00
@ENTITY_LOOP_CHECK:
	CPX #MAX_ENTITIES
	BCC @PROCESS_ENTITY
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	JSL RELOAD_MAP
	JSL UNDRAW_FLYOVER_TEXT
	SEP #PROC_FLAGS::ACCUM8
	LDA #$17
	STA TM_MIRROR
	LDX #1
	REP #PROC_FLAGS::ACCUM8
	TXA
	JSL FADE_IN
@RETURN:
	END_C_FUNCTION
