
SHOW_TITLE_SCREEN:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL04
	STA TITLE_SCREEN_QUICK_MODE
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	LDA @VIRTUAL04
	BNE @T001
	JSL INIT_ENTITY_SYSTEM
	BRA @AFTER_INIT
@T001:
	LDY #0
	LDX #1
	TXA
	JSL FADE_OUT_WITH_MOSAIC
	LDA #0
	STA @LOCAL03
	BRA @T002
@HIDE_ENTITY:
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #$8000
	STA __BSS_START__,X
	LDA @LOCAL03
	INC
	STA @LOCAL03
@T002:
	CMP #MAX_ENTITIES
	BCC @HIDE_ENTITY
@AFTER_INIT:
	LDA #11
	JSL SET_BGMODE
	LDA #3
	JSL SET_OAM_SIZE
	LDY #$0000
	LDX #$5800
	TYA ;BG_TILEMAP_SIZE::NORMAL
	JSL SET_BG1_VRAM_LOCATION
	STZ BG3_X_POS
	STZ BG3_Y_POS
	STZ BG2_Y_POS
	STZ BG2_X_POS
	STZ BG1_Y_POS
	STZ BG1_X_POS
	JSL UPDATE_SCREEN
	STZ BG3_X_POS
	STZ BG3_Y_POS
	STZ BG2_Y_POS
	STZ BG2_X_POS
	STZ BG1_Y_POS
	STZ BG1_X_POS
	JSL UPDATE_SCREEN
	JSL LOAD_TITLE_SCREEN_GRAPHICS
	SEP #PROC_FLAGS::ACCUM8
	LDA #$11
	STA TM_MIRROR
	JSL OAM_CLEAR
	.A16
	LDY #0
	TYX
	LDA #EVENT_SCRIPT::TITLE_SCREEN_1
	JSL INIT_ENTITY_WIPE
	STZ ACTIONSCRIPT_STATE
@SETUP_DISPLAY:
	SEP #PROC_FLAGS::ACCUM8
	STZ @LOCAL00
	LDX #.LOWORD(PALETTES)
	REP #PROC_FLAGS::ACCUM8
	LDA #BPP4PALETTE_SIZE * 16
	JSL MEMSET16
	SEP #PROC_FLAGS::ACCUM8
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
	JSL BLANK_SCREEN_AND_WAIT_VBLANK
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0F
	STA INIDISP_MIRROR
	JSL WAIT_UNTIL_NEXT_FRAME
	SEP #PROC_FLAGS::ACCUM8
	STZ PALETTE_UPLOAD_MODE
	REP #PROC_FLAGS::ACCUM8
	LOADPTR TITLE_SCREEN_SPRITE_PALETTE, @LOCAL00
	PROMOTENEARPTR PALETTES, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	LDA #BPP4PALETTE_SIZE * 8
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL01
	LDA @VIRTUAL06+2
	STA @LOCAL01+2
	JSL DECOMP
	JSL COPY_FADE_BUFFER_TO_PALETTES
	SEP #PROC_FLAGS::ACCUM8
	STZ @LOCAL00
	LDX #.LOWORD(PALETTES)
	REP #PROC_FLAGS::ACCUM8
	LDA #BPP4PALETTE_SIZE * 16
	JSL MEMSET16
	LDX #$0100
	LDA #60
	JSL PREPARE_PALETTE_FADE
	SEP #PROC_FLAGS::ACCUM8
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
	LDX #0
	STX @LOCAL03
	BRA @FADE_IN_LOOP_CHECK
@FADE_IN_STEP:
	JSL UPDATE_MAP_PALETTE_ANIMATION
	JSL RENDER_FRAME_TICK
	LDX @LOCAL03
	INX
	STX @LOCAL03
@FADE_IN_LOOP_CHECK:
	STX @VIRTUAL02
	REP #PROC_FLAGS::ACCUM8
	LDA #60
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @FADE_IN_STEP
	LDA #0
@WAIT_FOR_SCRIPT:
	STA @VIRTUAL02
	BRA @T005
@T004:
	LDA @VIRTUAL04
	BNE @T006
	LDA PAD_PRESS
	AND #PAD::A_BUTTON
	BNE @T003
	LDA PAD_PRESS
	AND #PAD::B_BUTTON
	BNE @T003
	LDA PAD_PRESS
	AND #PAD::START_BUTTON
	BEQ @T006
@T003:
	LDA #1
	STA @VIRTUAL02
	BRA @T007
@T006:
	JSL RENDER_FRAME_TICK
@T005:
	LDA ACTIONSCRIPT_STATE
	BEQ @T004
@T007:
	LDY #0
	LDX #4
	LDA #1
	JSL FADE_OUT_WITH_MOSAIC
	LDA @VIRTUAL04
	BNE @CLEANUP_ENTITIES
	STZ ACTIONSCRIPT_STATE
	LDA #0
	JSL SETUP_ENTITY_COLOR_MATH
	JSL INIT_ENTITY_SYSTEM
	LDA @VIRTUAL02
	BRA @RETURN
@CLEANUP_ENTITIES:
	LDX #0
	STX @LOCAL02
	BRA @ENTITY_LOOP_CHECK
@PROCESS_ENTITY:
	TXA
	ASL
	TAX
	LDA ENTITY_SCRIPT_TABLE,X
	CMP #EVENT_SCRIPT::TITLE_SCREEN_1
	BCC @SKIP_DEACTIVATE
	CMP #EVENT_SCRIPT::TITLE_SCREEN_11
	BGT @SKIP_DEACTIVATE
	LDX @LOCAL02
	TXA
	JSL DEACTIVATE_ENTITY_FAR
@SKIP_DEACTIVATE:
	LDX @LOCAL02
	TXA
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAY
	LDA __BSS_START__,Y
	AND #$7FFF
	STA __BSS_START__,Y
	INX
	STX @LOCAL02
@ENTITY_LOOP_CHECK:
	CPX #MAX_ENTITIES
	BCC @PROCESS_ENTITY
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	JSL RELOAD_MAP
	JSL UNDRAW_FLYOVER_TEXT
	SEP #PROC_FLAGS::ACCUM8
	LDA #$17
	STA TM_MIRROR
	LDX #1
	REP #PROC_FLAGS::ACCUM8
	TXA
	JSL FADE_IN
@RETURN:
	END_C_FUNCTION
