
SHOW_TITLE_SCREEN:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	STX TITLE_SCREEN_QUICK_MODE
	LDA #0
	STA @VIRTUAL04
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	JSL INIT_ENTITY_SYSTEM
	BRA @SETUP_VIDEO
@HIDE_ENTITY_SPRITES:
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #$8000
	STA __BSS_START__,X
	LDA @LOCAL04
	INC
	STA @LOCAL04
	CMP #MAX_ENTITIES
	BCC @HIDE_ENTITY_SPRITES
@SETUP_VIDEO:
	LDA #11
	JSL SET_BGMODE
	LDA #3
	JSL SET_OAM_SIZE
	LDY #$0000
	LDX #$5800
	TYA ;BG_TILEMAP_SIZE::NORMAL
	JSL SET_BG1_VRAM_LOCATION
	STZ BG3_X_POS
	STZ BG3_Y_POS
	STZ BG2_Y_POS
	STZ BG2_X_POS
	STZ BG1_Y_POS
	STZ BG1_X_POS
	JSL UPDATE_SCREEN
	STZ BG3_X_POS
	STZ BG3_Y_POS
	STZ BG2_Y_POS
	STZ BG2_X_POS
	STZ BG1_Y_POS
	STZ BG1_X_POS
	JSL UPDATE_SCREEN
	JSL LOAD_TITLE_SCREEN_GRAPHICS
	SEP #PROC_FLAGS::ACCUM8
	LDA #$11
	STA TM_MIRROR
	JSL OAM_CLEAR
	.A16
	LDY #0
	TYX
	LDA #EVENT_SCRIPT::TITLE_SCREEN_1
	JSL INIT_ENTITY_WIPE
	STZ ACTIONSCRIPT_STATE
	LDA TITLE_SCREEN_QUICK_MODE
	BNEL @QUICK_MODE
	SEP #PROC_FLAGS::ACCUM8
	STZ @LOCAL00
	LDX #.LOWORD(PALETTES)
	REP #PROC_FLAGS::ACCUM8
	LDA #BPP4PALETTE_SIZE * 16
	JSL MEMSET16
	SEP #PROC_FLAGS::ACCUM8
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
	JSL BLANK_SCREEN_AND_WAIT_VBLANK
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0F
	STA INIDISP_MIRROR
	JSL WAIT_UNTIL_NEXT_FRAME
	SEP #PROC_FLAGS::ACCUM8
	STZ PALETTE_UPLOAD_MODE
	REP #PROC_FLAGS::ACCUM8
	LOADPTR TITLE_SCREEN_SPRITE_PALETTE, @LOCAL00
	PROMOTENEARPTR PALETTES, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	LDA #BPP4PALETTE_SIZE * 8
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL01
	LDA @VIRTUAL06+2
	STA @LOCAL01+2
	JSL DECOMP
	JSL COPY_FADE_BUFFER_TO_PALETTES
	SEP #PROC_FLAGS::ACCUM8
	STZ @LOCAL00
	LDX #.LOWORD(PALETTES)
	REP #PROC_FLAGS::ACCUM8
	LDA #BPP4PALETTE_SIZE * 16
	JSL MEMSET16
	LDX #$0100
	LDA #60
	JSL PREPARE_PALETTE_FADE
	SEP #PROC_FLAGS::ACCUM8
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
	LDX #0
	STX @LOCAL03
	BRA @PALETTE_FADE_CHECK
@PALETTE_FADE_LOOP:
	JSL UPDATE_MAP_PALETTE_ANIMATION
	JSL RENDER_FRAME_TICK
	LDX @LOCAL03
	INX
	STX @LOCAL03
@PALETTE_FADE_CHECK:
	STX @VIRTUAL02
	REP #PROC_FLAGS::ACCUM8
	LDA #60
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @PALETTE_FADE_LOOP
	BRA @MAIN_LOOP_INIT
@QUICK_MODE:
	LDX #1
	LDA #4
	JSL FADE_IN
	LDX #0
	STX @LOCAL04
	BRA @QUICK_WARMUP_CHECK
@QUICK_WARMUP_LOOP:
	JSL RENDER_FRAME_TICK
	LDX @LOCAL04
	INX
	STX @LOCAL04
@QUICK_WARMUP_CHECK:
	STX @VIRTUAL02
	LDA #60
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @QUICK_WARMUP_LOOP
@MAIN_LOOP_INIT:
	LDA #0
	STA @VIRTUAL02
	BRA @CHECK_ACTIONSCRIPT
@INPUT_LOOP:
	LDA @VIRTUAL04
	BNE @NO_BUTTON
	LDA PAD_PRESS
	AND #PAD::A_BUTTON
	BNE @BUTTON_PRESSED
	LDA PAD_PRESS
	AND #PAD::B_BUTTON
	BNE @BUTTON_PRESSED
	LDA PAD_PRESS
	AND #PAD::START_BUTTON
	BEQ @NO_BUTTON
@BUTTON_PRESSED:
	LDA #1
	STA @VIRTUAL02
	BRA @POST_INPUT_LOOP
@NO_BUTTON:
	JSL RENDER_FRAME_TICK
@CHECK_ACTIONSCRIPT:
	LDA ACTIONSCRIPT_STATE
	BEQ @INPUT_LOOP
	LDA ACTIONSCRIPT_STATE
	CMP #2
	BEQ @INPUT_LOOP
@POST_INPUT_LOOP:
	LDA TITLE_SCREEN_QUICK_MODE
	BNE @FADE_OUT
	LDA ACTIONSCRIPT_STATE
	BNE @FADE_OUT
	JSL RUN_TITLE_SEQUENCE
	STA @VIRTUAL02
@FADE_OUT:
	LDY #0
	LDX #4
	LDA #1
	JSL FADE_OUT_WITH_MOSAIC
	LDA @VIRTUAL04
	BNE @RETURN_TO_OVERWORLD
	STZ ACTIONSCRIPT_STATE
	LDA #0
	JSL SETUP_ENTITY_COLOR_MATH
	JSL INIT_ENTITY_SYSTEM
	LDA @VIRTUAL02
	BRA @RETURN
@RETURN_TO_OVERWORLD:
	LDY #0
	STY @LOCAL02
	BRA @DEACTIVATE_CHECK
@DEACTIVATE_LOOP:
	TYA
	ASL
	TAX
	LDA ENTITY_SCRIPT_TABLE,X
	CMP #EVENT_SCRIPT::TITLE_SCREEN_1
	BCC @SKIP_DEACTIVATE
	CMP #EVENT_SCRIPT::TITLE_SCREEN_11
	BGT @SKIP_DEACTIVATE
	TYA
	JSL DEACTIVATE_ENTITY_FAR
@SKIP_DEACTIVATE:
	LDY @LOCAL02
	TYA
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAX
	LDA __BSS_START__,X
	AND #$7FFF
	STA __BSS_START__,X
	INY
	STY @LOCAL02
@DEACTIVATE_CHECK:
	CPY #MAX_ENTITIES
	BCC @DEACTIVATE_LOOP
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	JSL RELOAD_MAP
	JSL UNDRAW_FLYOVER_TEXT
	SEP #PROC_FLAGS::ACCUM8
	LDA #$17
	STA TM_MIRROR
	LDX #1
	REP #PROC_FLAGS::ACCUM8
	TXA
	JSL FADE_IN
@RETURN:
	END_C_FUNCTION
