
START_DEMO_PLAYBACK_FAR:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	MOVE_INT @PARAM00, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL START_DEMO_PLAYBACK
	END_C_FUNCTION
