
CHANGE_VWF_2BPP_TO_3_COLOUR:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL04
	LDX #.LOWORD(VWF_BUFFER)
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL02
	JMP @BYTE_LOOP_CHECK
@PROCESS_BYTE:
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA @LOCAL01
	STA @VIRTUAL00
	LDA __BSS_START__,X
	STA @LOCAL00
	LDA __BSS_START__+1,X
	STA @VIRTUAL01
	LDY #0
	JMP @BIT_LOOP_CHECK
@PROCESS_BIT:
	LDA @VIRTUAL00
	ASL
	STA @VIRTUAL00
	LDA @LOCAL01
	ASL
	STA @LOCAL01
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	AND #$00FF
	AND #$0080
	BEQ @NOT_BOTH_SET
	LDA @VIRTUAL01
	AND #$00FF
	AND #$0080
	BEQ @NOT_BOTH_SET
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	AND #$00FE
	STA @VIRTUAL00
	LDA @LOCAL01
	AND #$00FE
	STA @LOCAL01
	BRA @NEXT_BIT
@NOT_BOTH_SET:
	.A16
	LDA @LOCAL00
	AND #$00FF
	AND #$0080
	BEQ @PLANE0_ZERO
	LDA #1
	BRA @AFTER_PLANE0_CHECK
@PLANE0_ZERO:
	LDA #0
@AFTER_PLANE0_CHECK:
	SEP #PROC_FLAGS::ACCUM8
	PHA
	LDA @VIRTUAL00
	STA TEMP_REGISTER
	PLA
	STA @VIRTUAL00
	LDA TEMP_REGISTER
	ORA @VIRTUAL00
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL01
	AND #$00FF
	AND #$0080
	BEQ @PLANE0_NOT_SET
	LDA #1
	BRA @PLANE1_NOT_SET
@PLANE0_NOT_SET:
	LDA #0
@PLANE1_NOT_SET:
	SEP #PROC_FLAGS::ACCUM8
	ORA @LOCAL01
	STA @LOCAL01
@NEXT_BIT:
	LDA @LOCAL00
	ASL
	STA @LOCAL00
	LDA @VIRTUAL01
	ASL
	STA @VIRTUAL01
	INY
@BIT_LOOP_CHECK:
	CPY #8
	BCCL @PROCESS_BIT
	LDA @LOCAL01
	STA __BSS_START__+1,X
	LDA @VIRTUAL00
	STA __BSS_START__,X
	INX
	INX
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL02
@BYTE_LOOP_CHECK:
	LDA @VIRTUAL04
	ASL
	ASL
	ASL
	ASL
	PHA
	LDA @VIRTUAL02
	PLY
	STY @VIRTUAL02
	CMP @VIRTUAL02
	BCCL @PROCESS_BYTE
	PLD
	RTL
