
CREDITS_SCROLL_FRAME:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA BG3_Y_POS
	CMP CREDITS_NEXT_CREDIT_POSITION
	BCS @PROCESS_CREDIT
	JMP @ROW_WIPE_CHECK
@PROCESS_CREDIT:
	LDA CREDITS_CURRENT_ROW
	STA @LOCAL07
	LDA CREDITS_CURRENT_ROW
	INC
	STA @LOCAL06
	LDA CREDITS_CURRENT_ROW
	INC
	INC
	AND #$000F
	STA CREDITS_CURRENT_ROW
	LDA BG3_Y_POS
	LSR
	LSR
	LSR
	CLC
	ADC #$001D
	AND #$001F
	STA @LOCAL05
	LDA #0
	STA @VIRTUAL04
	MOVE_INT CREDITS_SCRIPT_DATA, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL04
	LDA @LOCAL07
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #.LOWORD(BG2_BUFFER)
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL03
	LDA @LOCAL06
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #.LOWORD(BG2_BUFFER)
	PROMOTENEARPTRA @VIRTUAL0A
	REP #PROC_FLAGS::ACCUM8
	LDA [@LOCAL04]
	AND #$00FF
	STA @LOCAL02
	MOVE_INT @LOCAL04, @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL04
	LDA @LOCAL02
	CMP #1
	BEQ @CMD_SMALL_TEXT
	CMP #2
	BEQL @CMD_LARGE_TEXT
	CMP #3
	BEQL @CMD_SPACING
	CMP #4
	BEQL @CMD_PLAYER_NAME
	CMP #<-1
	BEQL @CMD_END
	JMP @ADVANCE_SCRIPT
@CMD_SMALL_TEXT:
	LDA CREDITS_NEXT_CREDIT_POSITION
	CLC
	ADC #8
	STA CREDITS_NEXT_CREDIT_POSITION
	BRA @SMALL_CHAR_LOOP_CHECK
@WRITE_SMALL_CHAR:
	AND #$00FF
	CLC
	ADC #$2000
	MOVE_INTX @LOCAL03, @VIRTUAL06
	STA [@VIRTUAL06]
	MOVE_INT @LOCAL04, @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL04
	MOVE_INT @LOCAL03, @VIRTUAL06
	INC @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL03
	INC @VIRTUAL04
@SMALL_CHAR_LOOP_CHECK:
	LDA [@LOCAL04]
	AND #$00FF
	BNE @WRITE_SMALL_CHAR
	LDA @VIRTUAL04
	LSR
	STA @VIRTUAL02
	LDA @LOCAL05
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #$6C10
	SEC
	SBC @VIRTUAL02
	STA @LOCAL02
	LDA @LOCAL07
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #.LOWORD(BG2_BUFFER)
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @LOCAL02
	TAY
	LDA @VIRTUAL04
	ASL
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL ENQUEUE_CREDITS_DMA
	JMP @ADVANCE_SCRIPT
@CMD_LARGE_TEXT:
	.A16
	LDA CREDITS_NEXT_CREDIT_POSITION
	CLC
	ADC #16
	STA CREDITS_NEXT_CREDIT_POSITION
	BRA @LARGE_CHAR_LOOP_CHECK
@WRITE_LARGE_CHAR:
	AND #$00FF
	CLC
	ADC #$2400
	MOVE_INTX @LOCAL03, @VIRTUAL06
	STA [@VIRTUAL06]
	INC @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL03
	LDA [@LOCAL04]
	AND #$00FF
	CLC
	ADC #$2410
	STA [@VIRTUAL0A]
	MOVE_INT @LOCAL04, @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL04
	INC @VIRTUAL0A
	INC @VIRTUAL0A
	INC @VIRTUAL04
@LARGE_CHAR_LOOP_CHECK:
	LDA [@LOCAL04]
	AND #$00FF
	BNE @WRITE_LARGE_CHAR
	LDA @VIRTUAL04
	LSR
	STA @VIRTUAL02
	LDA @LOCAL05
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #$6C10
	SEC
	SBC @VIRTUAL02
	STA @VIRTUAL02
	LDA @LOCAL07
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #.LOWORD(BG2_BUFFER)
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDY @VIRTUAL02
	LDA @VIRTUAL04
	ASL
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL ENQUEUE_CREDITS_DMA
	LDA @LOCAL05
	.A16
	CMP #31
	BEQ @LARGE_ROW_WRAP
	LDA @VIRTUAL02
	CLC
	ADC #32
	STA @LOCAL01
	BRA @DMA_SECOND_ROW
@LARGE_ROW_WRAP:
	LDA @VIRTUAL02
	SEC
	SBC #$03E0
	STA @LOCAL01
@DMA_SECOND_ROW:
	LDA @LOCAL06
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #.LOWORD(BG2_BUFFER)
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @LOCAL01
	TAY
	LDA @VIRTUAL04
	ASL
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL ENQUEUE_CREDITS_DMA
	JMP @ADVANCE_SCRIPT
@CMD_SPACING:
	.A16
	LDA [@LOCAL04]
	AND #$00FF
	ASL
	ASL
	ASL
	CLC
	ADC CREDITS_NEXT_CREDIT_POSITION
	STA CREDITS_NEXT_CREDIT_POSITION
	JMP @ADVANCE_SCRIPT
@CMD_PLAYER_NAME:
	LDX #.LOWORD(GAME_STATE) + game_state::earthbound_playername
	LDA __BSS_START__,X
	AND #$00FF
	BEQL @SKIP_NAME
	LDA CREDITS_NEXT_CREDIT_POSITION
	CLC
	ADC #16
	STA CREDITS_NEXT_CREDIT_POSITION
	LDY #0
	BRA @NAME_CHAR_LOOP_CHECK
@WRITE_NAME_CHAR:
	AND #$00FF
	STA @VIRTUAL02
	AND #$00F0
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #$2400
	PHA
	MOVE_INT @LOCAL03, @VIRTUAL06
	PLA
	STA [@VIRTUAL06]
	INC @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL03
	LDA __BSS_START__,X
	AND #$00FF
	STA @VIRTUAL02
	AND #$00F0
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #$2410
	STA [@VIRTUAL0A]
	INC @VIRTUAL0A
	INC @VIRTUAL0A
	INX
	INC @VIRTUAL04
	INY
@NAME_CHAR_LOOP_CHECK:
	LDA __BSS_START__,X
	AND #$00FF
	BEQ @NAME_CENTER_DMA
	CPY #24
	BCC @WRITE_NAME_CHAR
@NAME_CENTER_DMA:
	LDA @VIRTUAL04
	LSR
	STA @VIRTUAL02
	LDA @LOCAL05
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #$6C10
	SEC
	SBC @VIRTUAL02
	STA @VIRTUAL02
	LDA @LOCAL07
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #.LOWORD(BG2_BUFFER)
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDY @VIRTUAL02
	LDA @VIRTUAL04
	ASL
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL ENQUEUE_CREDITS_DMA
	.A16
	LDA @LOCAL05
	CMP #$001F
	BEQ @NAME_ROW_WRAP
	LDA @VIRTUAL02
	CLC
	ADC #32
	STA @LOCAL01
	BRA @NAME_DMA_SECOND_ROW
@NAME_ROW_WRAP:
	.A16
	LDA @VIRTUAL02
	SEC
	SBC #$03E0
	STA @LOCAL01
@NAME_DMA_SECOND_ROW:
	LDA @LOCAL06
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #.LOWORD(BG2_BUFFER)
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @LOCAL01
	TAY
	LDA @VIRTUAL04
	ASL
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL ENQUEUE_CREDITS_DMA
@SKIP_NAME:
	MOVE_INT @LOCAL04, @VIRTUAL06
	DEC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL04
	BRA @ADVANCE_SCRIPT
@CMD_END:
	.A16
	LDA #.LOWORD(-1)
	STA CREDITS_NEXT_CREDIT_POSITION
@ADVANCE_SCRIPT:
	MOVE_INT @LOCAL04, @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, CREDITS_SCRIPT_DATA
@ROW_WIPE_CHECK:
	LDA CREDITS_ROW_WIPE_THRESHOLD
	CMP BG3_Y_POS
	BCS @UPDATE_SCROLL
	LDA CREDITS_ROW_WIPE_THRESHOLD
	CLC
	ADC #8
	STA CREDITS_ROW_WIPE_THRESHOLD
	LOADPTR BLANK_TILE_DATA, @LOCAL00
	LDA BG3_Y_POS
	LSR
	LSR
	LSR
	DEC
	AND #$001F
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #$6C00
	TAY
	LDX #64
	SEP #PROC_FLAGS::ACCUM8
	LDA #3
	JSL ENQUEUE_CREDITS_DMA
@UPDATE_SCROLL:
	.A16
	MOVE_INT CREDITS_SCROLL_POSITION, @VIRTUAL06
	CLC
	LDA @VIRTUAL06 + fixed_point::fraction
	ADC #$4000
	STA @VIRTUAL06 + fixed_point::fraction
	BCC @AFTER_FRACTION
	INC @VIRTUAL06 + fixed_point::integer
@AFTER_FRACTION:
	MOVE_INT @VIRTUAL06, CREDITS_SCROLL_POSITION
	STA BG3_Y_POS
	JSR WRITE_BG3_Y_SCROLL
	END_C_FUNCTION
