
CREDITS_SCROLL_FRAME:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA BG3_Y_POS
	CMP CREDITS_NEXT_CREDIT_POSITION
	BGT @PROCESS_CREDIT
	JMP @ROW_WIPE_CHECK
@PROCESS_CREDIT:
	LDA CREDITS_CURRENT_ROW
	STA @LOCAL08
	LDA CREDITS_CURRENT_ROW
	INC
	STA @LOCAL07
	LDA CREDITS_CURRENT_ROW
	INC
	INC
	AND #$000F
	STA CREDITS_CURRENT_ROW
	LDA BG3_Y_POS
	LSR
	LSR
	LSR
	CLC
	ADC #29
	AND #$001F
	STA @VIRTUAL04
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL06
	MOVE_INT CREDITS_SCRIPT_DATA, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL05
	LDA @LOCAL08
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #.LOWORD(BG2_BUFFER)
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL04
	LDA @LOCAL07
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #.LOWORD(BG2_BUFFER)
	PROMOTENEARPTRA @VIRTUAL0A
	REP #PROC_FLAGS::ACCUM8
	LDA [@LOCAL05]
	AND #$00FF
	STA @LOCAL03
	MOVE_INT @LOCAL05, @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL05
	LDA @LOCAL03
	CMP #1
	BEQ @CMD_SMALL_TEXT
	CMP #2
	BEQL @CMD_LARGE_TEXT
	CMP #3
	BEQL @CMD_SPACING
	CMP #4
	BEQL @CMD_PLAYER_NAME
	CMP #<-1
	BEQL @CMD_END
	JMP @ADVANCE_SCRIPT
@CMD_SMALL_TEXT:
	LDA CREDITS_NEXT_CREDIT_POSITION
	CLC
	ADC #8
	STA CREDITS_NEXT_CREDIT_POSITION
	BRA @SMALL_CHAR_LOOP_CHECK
@WRITE_SMALL_CHAR:
	AND #$00FF
	CLC
	ADC #$2000
	MOVE_INTX @LOCAL04, @VIRTUAL06
	STA [@VIRTUAL06]
	MOVE_INT @LOCAL05, @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL05
	MOVE_INT @LOCAL04, @VIRTUAL06
	INC @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL04
	INC @VIRTUAL02
@SMALL_CHAR_LOOP_CHECK:
	LDA [@LOCAL05]
	AND #$00FF
	BNE @WRITE_SMALL_CHAR
	LDA @VIRTUAL02
	LSR
	PHA
	LDA @VIRTUAL04
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #$6C10
	PLY
	STY @VIRTUAL04
	SEC
	SBC @VIRTUAL04
	STA @LOCAL03
	LDA @LOCAL08
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #.LOWORD(BG2_BUFFER)
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @LOCAL03
	TAY
	LDA @VIRTUAL02
	ASL
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL ENQUEUE_CREDITS_DMA
	JMP @ADVANCE_SCRIPT
@CMD_LARGE_TEXT:
	.A16
	LDA CREDITS_NEXT_CREDIT_POSITION
	CLC
	ADC #16
	STA CREDITS_NEXT_CREDIT_POSITION
	BRA @LARGE_CHAR_LOOP_CHECK
@WRITE_LARGE_CHAR:
	AND #$00FF
	CLC
	ADC #$2400
	MOVE_INTX @LOCAL04, @VIRTUAL06
	STA [@VIRTUAL06]
	INC @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL04
	LDA [@LOCAL05]
	AND #$00FF
	CLC
	ADC #$2410
	STA [@VIRTUAL0A]
	MOVE_INT @LOCAL05, @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL05
	INC @VIRTUAL0A
	INC @VIRTUAL0A
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL06
@LARGE_CHAR_LOOP_CHECK:
	LDA [@LOCAL05]
	AND #$00FF
	BNE @WRITE_LARGE_CHAR
	LDA @VIRTUAL02
	LSR
	STA @VIRTUAL02
	LDA @VIRTUAL04
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #$6C10
	SEC
	SBC @VIRTUAL02
	STA @LOCAL02
	LDA @LOCAL08
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #.LOWORD(BG2_BUFFER)
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDY @LOCAL02
	LDA @LOCAL06
	STA @VIRTUAL02
	ASL
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL ENQUEUE_CREDITS_DMA
	LDA @VIRTUAL04
	.A16
	CMP #31
	BEQ @LARGE_ROW_WRAP
	LDA @LOCAL02
	CLC
	ADC #32
	STA @LOCAL08
	BRA @DMA_SECOND_ROW
@LARGE_ROW_WRAP:
	LDA @LOCAL02
	SEC
	SBC #$03E0
	STA @LOCAL08
@DMA_SECOND_ROW:
	LDA @LOCAL07
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #.LOWORD(BG2_BUFFER)
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @LOCAL08
	TAY
	LDA @VIRTUAL02
	ASL
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL ENQUEUE_CREDITS_DMA
	JMP @ADVANCE_SCRIPT
@CMD_SPACING:
	.A16
	LDA [@LOCAL05]
	AND #$00FF
	ASL
	ASL
	ASL
	CLC
	ADC CREDITS_NEXT_CREDIT_POSITION
	STA CREDITS_NEXT_CREDIT_POSITION
	JMP @ADVANCE_SCRIPT
@CMD_PLAYER_NAME:
	LDX #.LOWORD(GAME_STATE) + game_state::earthbound_playername
	STX @LOCAL03
	LDA __BSS_START__,X
	AND #$00FF
	BEQL @SKIP_NAME
	LDY #.LOWORD(CREDITS_PLAYER_NAME_BUFFER)
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA @LOCAL01
	JMP @CHAR_CONVERT_LOOP_CHECK
@CONVERT_EB_CHAR:
	.A16
	LDA @VIRTUAL00
	AND #$00FF
	STA @LOCAL02
	CMP #172
	BEQ @HANDLE_PIPE_CHAR
	CMP #174
	BEQ @HANDLE_TILDE_CHAR
	CMP #175
	BEQ @HANDLE_SPECIAL_CHAR
	BRA @CONVERT_STANDARD_CHAR
@HANDLE_PIPE_CHAR:
	.A16
	LDA @LOCAL01
	AND #$00FF
	STA @VIRTUAL02
	TYA
	CLC
	ADC @VIRTUAL02
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #124
	STA __BSS_START__,X
	BRA @NEXT_CHAR_CONVERT
@HANDLE_TILDE_CHAR:
	.A16
	LDA @LOCAL01
	AND #$00FF
	STA @VIRTUAL02
	TYA
	CLC
	ADC @VIRTUAL02
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #126
	STA __BSS_START__,X
	BRA @NEXT_CHAR_CONVERT
@HANDLE_SPECIAL_CHAR:
	.A16
	LDA @LOCAL01
	AND #$00FF
	STA @VIRTUAL02
	TYA
	CLC
	ADC @VIRTUAL02
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #127
	STA __BSS_START__,X
	BRA @NEXT_CHAR_CONVERT
@CONVERT_STANDARD_CHAR:
	.A16
	LDA @LOCAL02
	CLC
	SBC #144
	BRANCHLTEQS @LOWER_RANGE_OFFSET
	LDA @LOCAL02
	SEC
	SBC #80
	STA @LOCAL02
	BRA @STORE_CONVERTED
@LOWER_RANGE_OFFSET:
	LDA @LOCAL02
	SEC
	SBC #48
	STA @LOCAL02
@STORE_CONVERTED:
	LDA @LOCAL01
	AND #$00FF
	STA @VIRTUAL02
	TYA
	CLC
	ADC @VIRTUAL02
	TAX
	LDA @LOCAL02
	SEP #PROC_FLAGS::ACCUM8
	STA __BSS_START__,X
@NEXT_CHAR_CONVERT:
	LDX @LOCAL03
	INX
	STX @LOCAL03
	LDA @LOCAL01
	INC
	STA @LOCAL01
@CHAR_CONVERT_LOOP_CHECK:
	LDA __BSS_START__,X
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	AND #$00FF
	BNEL @CONVERT_EB_CHAR
	LDA CREDITS_NEXT_CREDIT_POSITION
	CLC
	ADC #16
	STA CREDITS_NEXT_CREDIT_POSITION
	LDX #0
	BRA @NAME_CHAR_LOOP_CHECK
@WRITE_NAME_CHAR:
	AND #$00FF
	STA @VIRTUAL02
	AND #$00F0
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #$2400
	PHA
	MOVE_INT @LOCAL04, @VIRTUAL06
	PLA
	STA [@VIRTUAL06]
	INC @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL04
	LDA __BSS_START__,Y
	AND #$00FF
	STA @VIRTUAL02
	AND #$00F0
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #$2410
	STA [@VIRTUAL0A]
	INC @VIRTUAL0A
	INC @VIRTUAL0A
	INY
	LDA @LOCAL06
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL06
	INX
@NAME_CHAR_LOOP_CHECK:
	LDA __BSS_START__,Y
	AND #$00FF
	BEQ @NAME_CENTER_DMA
	CPX #24
	BCC @WRITE_NAME_CHAR
@NAME_CENTER_DMA:
	LDA @LOCAL06
	STA @VIRTUAL02
	LSR
	STA @VIRTUAL02
	LDA @VIRTUAL04
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #$6C10
	SEC
	SBC @VIRTUAL02
	STA @LOCAL02
	LDA @LOCAL08
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #.LOWORD(BG2_BUFFER)
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDY @LOCAL02
	LDA @LOCAL06
	STA @VIRTUAL02
	ASL
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL ENQUEUE_CREDITS_DMA
	.A16
	LDA @VIRTUAL04
	CMP #31
	BEQ @NAME_ROW_WRAP
	LDA @LOCAL02
	CLC
	ADC #32
	STA @LOCAL08
	BRA @NAME_DMA_SECOND_ROW
@NAME_ROW_WRAP:
	.A16
	LDA @LOCAL02
	SEC
	SBC #$03E0
	STA @LOCAL08
@NAME_DMA_SECOND_ROW:
	LDA @LOCAL07
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #.LOWORD(BG2_BUFFER)
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @LOCAL08
	TAY
	LDA @VIRTUAL02
	ASL
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL ENQUEUE_CREDITS_DMA
@SKIP_NAME:
	MOVE_INT @LOCAL05, @VIRTUAL06
	DEC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL05
	BRA @ADVANCE_SCRIPT
@CMD_END:
	.A16
	LDA #.LOWORD(-1)
	STA CREDITS_NEXT_CREDIT_POSITION
@ADVANCE_SCRIPT:
	MOVE_INT @LOCAL05, @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, CREDITS_SCRIPT_DATA
@ROW_WIPE_CHECK:
	LDA CREDITS_ROW_WIPE_THRESHOLD
	CMP BG3_Y_POS
	BCS @UPDATE_SCROLL
	LDA CREDITS_ROW_WIPE_THRESHOLD
	CLC
	ADC #8
	STA CREDITS_ROW_WIPE_THRESHOLD
	LOADPTR BLANK_TILE_DATA, @LOCAL00
	LDA BG3_Y_POS
	LSR
	LSR
	LSR
	DEC
	AND #$001F
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #$6C00
	TAY
	LDX #64
	SEP #PROC_FLAGS::ACCUM8
	LDA #3
	JSL ENQUEUE_CREDITS_DMA
@UPDATE_SCROLL:
	.A16
	MOVE_INT CREDITS_SCROLL_POSITION, @VIRTUAL06
	CLC
	LDA @VIRTUAL06 + fixed_point::fraction
	ADC #$4000
	STA @VIRTUAL06 + fixed_point::fraction
	BCC @AFTER_FRACTION
	INC @VIRTUAL06 + fixed_point::integer
@AFTER_FRACTION:
	MOVE_INT @VIRTUAL06, CREDITS_SCROLL_POSITION
	STA BG3_Y_POS
	JSR WRITE_BG3_Y_SCROLL
	END_C_FUNCTION
