
PLAY_CREDITS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #1
	STA DISABLED_TRANSITIONS
	JSL INITIALIZE_CREDITS_SCENE
	JSL OAM_CLEAR
	LDX #2
	LDA #1
	JSL FADE_IN
	JSL COUNT_PHOTO_FLAGS
	CMP #0
	BEQ @NO_PHOTOS
	JSL COUNT_PHOTO_FLAGS
	TAY
	LDA #CREDITS_LENGTH
	JSL DIVISION16S_DIVISOR_POSITIVE
	BRA @AFTER_SPACING_CALC
@NO_PHOTOS:
	LDA #CREDITS_LENGTH
@AFTER_SPACING_CALC:
	STA @VIRTUAL04
	STA @VIRTUAL02
	LDA #.LOWORD(CREDITS_SCROLL_FRAME)
	JSL SET_IRQ_CALLBACK
	LDY #0
	STY @LOCAL02
	JMP @PHOTO_LOOP_CHECK
@PROCESS_PHOTO:
	TYA
	JSL TRY_RENDERING_PHOTOGRAPH
	CMP #0
	BEQL @NEXT_PHOTO
	LDX #$FFFF
	LDA #64
	JSL PREPARE_PALETTE_FADE
	.A16
	LDX #64
	STX @LOCAL01
	BRA @FADE_IN_LOOP_CHECK
@FADE_IN_FRAME:
	JSL UPDATE_MAP_PALETTE_ANIMATION
	JSL PROCESS_CREDITS_DMA_QUEUE
	JSL RENDER_FRAME_TICK
	LDX @LOCAL01
	DEX
	STX @LOCAL01
@FADE_IN_LOOP_CHECK:
	BNE @FADE_IN_FRAME
	JSL FINALIZE_PALETTE_FADE
	LDY @LOCAL02
	TYA
	JSL SLIDE_CREDITS_PHOTOGRAPH
	BRA @SLIDE_LOOP_CHECK
@SLIDE_WAIT_FRAME:
	JSL PROCESS_CREDITS_DMA_QUEUE
	JSL RENDER_FRAME_TICK
@SLIDE_LOOP_CHECK:
	LDA @VIRTUAL02
	CMP BG3_Y_POS
	BGT @SLIDE_WAIT_FRAME
	LOADPTR BUFFER+32, @LOCAL00
	LDX #480
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL MEMSET24
	.A16
	LDX #$FFFF
	LDA #64
	JSL PREPARE_PALETTE_FADE
	LDX #0
	STX @LOCAL01
	BRA @FADE_OUT_LOOP_CHECK
@FADE_OUT_FRAME:
	JSL UPDATE_MAP_PALETTE_ANIMATION
	JSL PROCESS_CREDITS_DMA_QUEUE
	JSL RENDER_FRAME_TICK
	LDX @LOCAL01
	INX
	STX @LOCAL01
@FADE_OUT_LOOP_CHECK:
	CPX #64
	BCC @FADE_OUT_FRAME
	SEP #PROC_FLAGS::ACCUM8
	STZ_BADOPT @LOCAL00
	LDX #480
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 1
	JSL MEMSET16
	LDA #24
	JSL SET_PALETTE_UPLOAD_MODE
	JSL PROCESS_CREDITS_DMA_QUEUE
	JSL RENDER_FRAME_TICK
	LDA @VIRTUAL02
	CLC
	ADC @VIRTUAL04
	STA @VIRTUAL02
@NEXT_PHOTO:
	LDY @LOCAL02
	INY
	STY @LOCAL02
@PHOTO_LOOP_CHECK:
	CPY #NUM_PHOTOS
	BCCL @PROCESS_PHOTO
	BRA @SCROLL_LOOP_CHECK
@SCROLL_WAIT_FRAME:
	JSL PROCESS_CREDITS_DMA_QUEUE
	JSL RENDER_FRAME_TICK
@SCROLL_LOOP_CHECK:
	LDA BG3_Y_POS
	CMP #CREDITS_LENGTH
	BCC @SCROLL_WAIT_FRAME
	JSL RESET_IRQ_CALLBACK
	LDX #0
	STX @LOCAL01
	BRA @END_WAIT_LOOP_CHECK
@END_WAIT_FRAME:
	JSL RENDER_FRAME_TICK
	LDX @LOCAL01
	INX
	STX @LOCAL01
@END_WAIT_LOOP_CHECK:
	CPX #2000
	BCC @END_WAIT_FRAME
	LDY #0
	LDX #2
	LDA #1
	JSL FADE_OUT_WITH_MOSAIC
	LDX #0
	LDA #$B3
	JSL SETUP_COLOR_MATH_WINDOW
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	JSL OVERWORLD_SETUP_VRAM
	JSL CLEAR_MAP_ENTITIES
	LDA #23
	STA ENTITY_ALLOCATION_MIN_SLOT
	LDA #24
	STA ENTITY_ALLOCATION_MAX_SLOT
	LDY #0
	TYX
	LDA #EVENT_SCRIPT::EVENT_001
	JSL INIT_ENTITY
	JSL RESET_PARTY_STATE
	JSL INITIALIZE_PARTY
	PROMOTENEARPTR BG2_BUFFER, @VIRTUAL06
	LDX #0
	BRA @CLEAR_BG2_LOOP_CHECK
@CLEAR_BG2_ENTRY:
	REP #PROC_FLAGS::ACCUM8
	LDA #0
	STA [@VIRTUAL06]
	INC @VIRTUAL06
	INC @VIRTUAL06
	INX
@CLEAR_BG2_LOOP_CHECK:
	CPX #512
	BCC @CLEAR_BG2_ENTRY
	JSL UNDRAW_FLYOVER_TEXT
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0017
	STA TM_MIRROR
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(PROCESS_OVERWORLD_TASKS)
	JSL SET_IRQ_CALLBACK
	STZ DISABLED_TRANSITIONS
	END_C_FUNCTION
