
PLAY_CAST_SCENE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	JSL LOAD_CAST_SCENE
	JSL OAM_CLEAR
	LDX #1
	TXA
	JSL FADE_IN
	LDY #0
	TYX
	LDA #EVENT_SCRIPT::EVENT_801
	JSL INIT_ENTITY_WIPE
	STZ ACTIONSCRIPT_STATE
	BRA @RENDER_LOOP_CHECK
@RENDER_LOOP:
	JSL RENDER_FRAME_TICK
	JSL UPDATE_BATTLE_SCREEN_EFFECTS
@RENDER_LOOP_CHECK:
	LDA ACTIONSCRIPT_STATE
	BEQ @RENDER_LOOP
	LDY #0
	LDX #1
	TXA
	JSL FADE_OUT_WITH_MOSAIC
	LDX #0
	STX @LOCAL00
	BRA @DEACTIVATE_LOOP_CHECK
@DEACTIVATE_ENTITY:
	TXA
	ASL
	TAX
	LDA ENTITY_SCRIPT_TABLE,X
	CMP #EVENT_SCRIPT::EVENT_801
	BNE @NEXT_ENTITY
	LDX @LOCAL00
	TXA
	JSL DEACTIVATE_ENTITY_FAR
@NEXT_ENTITY:
	LDX @LOCAL00
	INX
	STX @LOCAL00
@DEACTIVATE_LOOP_CHECK:
	CPX #MAX_ENTITIES
	BCC @DEACTIVATE_ENTITY
	LDA #23
	STA ENTITY_ALLOCATION_MIN_SLOT
	LDA #24
	STA ENTITY_ALLOCATION_MAX_SLOT
	LDY #0
	TYX
	LDA #EVENT_SCRIPT::EVENT_001
	JSL INIT_ENTITY
	JSL RESET_PARTY_STATE
	JSL INITIALIZE_PARTY
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	JSL UNDRAW_FLYOVER_TEXT
	SEP #PROC_FLAGS::ACCUM8
	LDA #$17
	STA TM_MIRROR
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
