
RENDER_CAST_NAME_TEXT:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL09
	STX @LOCAL08
	STA @VIRTUAL02
	LOADPTR FONT_PTR_TABLE, @LOCAL07
	STZ VWF_TILE
	STZ VWF_X
	SEP #PROC_FLAGS::ACCUM8
	LDA #<-1
	STA @LOCAL00
	LDX #32 * 26
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(VWF_BUFFER)
	JSL MEMSET16
	STZ TEXT_RENDER_STATE + 2
	STZ TEXT_RENDER_STATE
	LDA @VIRTUAL02
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX @LOCAL08
	LDA #.LOWORD(-1)
	JSL CENTER_VWF_FOR_STRING
	LDA #0
	STA @VIRTUAL04
	JMP @CHAR_LOOP_CHECK
@BLIT_CHAR:
	AND #$00FF
	SEC
	SBC #$50
	AND #$007F
	STA @LOCAL06
	MOVE_INT @LOCAL07, @VIRTUAL06
	LDY #4
	LDA [@VIRTUAL06],Y
	PHA
	INY
	INY
	LDA [@VIRTUAL06],Y
	STA @VIRTUAL0A+2
	PLA
	STA @VIRTUAL0A
	LDA @LOCAL06
	PHA
	LDY #8
	LDA [@LOCAL07],Y
	PLY
	JSL MULT16
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	MOVE_INT @LOCAL07, @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL06
	LDA @LOCAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	CLC
	ADC CHARACTER_PADDING
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAY
	STY @LOCAL05
	CPY #8
	BLTEQ @FINAL_BLIT
@WIDE_GLYPH_LOOP:
	MOVE_INT @LOCAL07, @VIRTUAL06
	LDA #10
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL04
	LDA @VIRTUAL06+2
	STA @LOCAL04+2
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	MOVE_INT @LOCAL04, @VIRTUAL06
	LDA [@VIRTUAL06]
	TAX
	TYA
	JSL BLIT_VWF_GLYPH
	LDY @LOCAL05
	TYA
	SEC
	SBC #8
	TAY
	STY @LOCAL05
	LDA [@VIRTUAL06]
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	CPY #8
	BGT @WIDE_GLYPH_LOOP
@FINAL_BLIT:
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDY #10
	LDA [@LOCAL07],Y
	TAX
	LDY @LOCAL05
	TYA
	JSL BLIT_VWF_GLYPH
	INC @VIRTUAL02
	INC @VIRTUAL04
@CHAR_LOOP_CHECK:
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	AND #$00FF
	BNEL @BLIT_CHAR
	LDA @LOCAL08
	JSL CHANGE_VWF_2BPP_TO_3_COLOUR
	LDA @LOCAL09
	ASL
	ASL
	ASL
	STA @VIRTUAL04
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL03
	JMP @TILE_LOOP_CHECK
@COPY_TILE:
	LDA @LOCAL09
	AND #$000F
	STA @VIRTUAL02
	LDA @LOCAL09
	AND #$03F0
	ASL
	CLC
	ADC @VIRTUAL02
	ASL
	ASL
	ASL
	ASL
	TAY
	STY @LOCAL02
	LOADPTR BUFFER, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL04
	LDA @LOCAL03
	STA @VIRTUAL02
	ASL
	ASL
	ASL
	ASL
	ASL
	TAX
	STX @LOCAL06
	TYA
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	TXA
	CLC
	ADC #.LOWORD(VWF_BUFFER)
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDA #16
	JSL MEMCPY24
	LDY @LOCAL02
	TYA
	CLC
	ADC #256
	MOVE_INTX @LOCAL04, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX @LOCAL06
	TXA
	CLC
	ADC #.LOWORD(VWF_BUFFER) + 16
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDA #16
	JSL MEMCPY24
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL03
	LDA @VIRTUAL04
	CLC
	ADC #8
	STA @VIRTUAL04
	INC @LOCAL09
@TILE_LOOP_CHECK:
	LDA @VIRTUAL02
	CMP @LOCAL08
	BCCL @COPY_TILE
	END_C_FUNCTION
