
DEBUG_Y_BUTTON_FLAG:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX #EVENT_FLAG::FLG_TEMP_0
	STX @VIRTUAL02
@DISPLAY_FLAG:
	JSR SET_INSTANT_PRINTING
	CREATE_WINDOW_NEAR #WINDOW::FILE_SELECT_MENU
	LDA #3
	JSR SET_WINDOW_NUMBER_PADDING
	MOVE_INT1632 @VIRTUAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR PRINT_NUMBER
	LDA #$0020
.IF .DEFINED(JPN)
	JSR PRINT_LETTER
.ELSE
	JSL PRINT_CHAR_WITH_SOUND
	JSL ADVANCE_VWF_TILE
.ENDIF
	LDA @VIRTUAL02
	JSL GET_EVENT_FLAG
	CMP #0
	BEQ @FLAG_IS_OFF
	LOADPTR DEBUG_ON_TEXT, @VIRTUAL06
	BRA @SHOW_FLAG_STATUS
@FLAG_IS_OFF:
	LOADPTR DEBUG_OFF_TEXT, @VIRTUAL06
@SHOW_FLAG_STATUS:
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #$0100
	JSR PRINT_STRING
	JSR CLEAR_INSTANT_PRINTING
	JSL WINDOW_TICK
	LDY @VIRTUAL02
	STY @LOCAL01
@WAIT_INPUT:
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA PAD_HELD
	AND #PAD::UP
	BEQ @CHECK_DOWN
	LDY @LOCAL01
	INY
	STY @LOCAL01
	BRA @VALIDATE_INDEX
@CHECK_DOWN:
	LDA PAD_HELD
	AND #PAD::DOWN
	BEQ @CHECK_RIGHT
	LDY @LOCAL01
	DEY
	STY @LOCAL01
	BRA @VALIDATE_INDEX
@CHECK_RIGHT:
	LDA PAD_HELD
	AND #PAD::RIGHT
	BEQ @CHECK_LEFT
	LDY @LOCAL01
	TYA
	CLC
	ADC #10
	TAY
	STY @LOCAL01
	BRA @VALIDATE_INDEX
@CHECK_LEFT:
	LDA PAD_HELD
	AND #PAD::LEFT
	BEQ @CHECK_TOGGLE
	LDY @LOCAL01
	TYA
	SEC
	SBC #10
	TAY
	STY @LOCAL01
	BRA @VALIDATE_INDEX
@CHECK_TOGGLE:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON | PAD::L_BUTTON
	BEQ @CHECK_EXIT
	LDA @VIRTUAL02
	JSL GET_EVENT_FLAG
	CMP #0
	BEQ @FLAG_OFF
	LDX #0
	BRA @SET_FLAG
@FLAG_OFF:
	LDX #1
@SET_FLAG:
	LDA @VIRTUAL02
	JSL SET_EVENT_FLAG
	BRA @VALIDATE_INDEX
@CHECK_EXIT:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON
	BEQ @WAIT_INPUT
	LDA #WINDOW::FILE_SELECT_MENU
	JSR CLOSE_WINDOW
	BRA @EXIT
@VALIDATE_INDEX:
	LDY @LOCAL01
	CPY #2000
	BCC @CHECK_ZERO
	JMP @DISPLAY_FLAG
@CHECK_ZERO:
	CPY #0
	BEQL @DISPLAY_FLAG
	STY @VIRTUAL02
	JMP @DISPLAY_FLAG
@EXIT:
	END_C_FUNCTION
