
DEBUG_Y_BUTTON_GOODS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX #0
	STX @VIRTUAL04
@DISPLAY_ITEM:
	JSR SET_INSTANT_PRINTING
	CREATE_WINDOW_NEAR #WINDOW::FILE_SELECT_MENU
	LDA #2
	JSR SET_WINDOW_NUMBER_PADDING
.IF .DEFINED(USA)
	LDA #130
	JSR SET_WINDOW_NUMBER_PADDING
	LDX #0
	TXA
	JSL SET_FOCUS_TEXT_CURSOR
.ENDIF
	MOVE_INT1632 @VIRTUAL04, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR PRINT_NUMBER
.IF .DEFINED(USA)
	LDX #0
	LDA #3
	JSL SET_FOCUS_TEXT_CURSOR
.ENDIF
	LDA @VIRTUAL04
	JSR PRINT_ITEM_TYPE
	JSR CLEAR_INSTANT_PRINTING
	JSL WINDOW_TICK
	LDA @VIRTUAL04
	STA @VIRTUAL02
@WAIT_INPUT:
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA PAD_HELD
	AND #PAD::UP
	BEQ @CHECK_DOWN
	INC @VIRTUAL02
	JMP @VALIDATE_INDEX
@CHECK_DOWN:
	LDA PAD_HELD
	AND #PAD::DOWN
	BEQ @CHECK_RIGHT
	LDA @VIRTUAL02
	DEC
	STA @VIRTUAL02
	JMP @VALIDATE_INDEX
@CHECK_RIGHT:
	LDA PAD_HELD
	AND #PAD::RIGHT
	BEQ @CHECK_LEFT
	LDA @VIRTUAL02
	CLC
	ADC #10
	STA @VIRTUAL02
	JMP @VALIDATE_INDEX
@CHECK_LEFT:
	LDA PAD_HELD
	AND #PAD::LEFT
	BEQ @CHECK_GIVE
	LDA @VIRTUAL02
	SEC
	SBC #10
	STA @VIRTUAL02
	BRA @VALIDATE_INDEX
@CHECK_GIVE:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON | PAD::L_BUTTON
	BEQ @CHECK_EXIT
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDX #1
	TXA
	JSR CHAR_SELECT_PROMPT
	TAY
	STY @LOCAL02
	BEQ @VALIDATE_INDEX
	TYA
	JSL FIND_INVENTORY_SPACE2
	CMP #0
	BEQ @VALIDATE_INDEX
	LDX @VIRTUAL04
	LDY @LOCAL02
	TYA
	JSL GIVE_ITEM_TO_CHARACTER
	LDX @VIRTUAL04
	LDY @LOCAL02
	TYA
	JSL CHECK_ITEM_USABLE_BY
	CMP #0
	BEQ @EXIT
	LDA @VIRTUAL04
	JSR GET_ITEM_TYPE
	CMP #2
	BNE @EXIT
	LDY @LOCAL02
	TYA
	JSL FIND_EMPTY_INVENTORY_SLOT
	TAX
	LDY @LOCAL02
	TYA
	JSR EQUIP_ITEM
	BRA @EXIT
@CHECK_EXIT:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON
	BNE @EXIT
	JMP @WAIT_INPUT
@VALIDATE_INDEX:
	LDA @VIRTUAL02
	CMP #$0100
	BCC @UPDATE_INDEX
	JMP @DISPLAY_ITEM
@UPDATE_INDEX:
	LDA @VIRTUAL02
	STA @VIRTUAL04
	JMP @DISPLAY_ITEM
@EXIT:
	LDA #WINDOW::FILE_SELECT_MENU
	JSR CLOSE_WINDOW
	END_C_FUNCTION
