
CHECK_DEBUG_EXIT_BUTTON:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA #0
	STA @LOCAL00
	LDA DEBUG_MODE_NUMBER
	CMP #2
	BNE @CHECK_Y_BUTTON
	BRA @CHECK_B_BUTTON
@WAIT_FOR_B_BUTTON:
	JSL WAIT_UNTIL_NEXT_FRAME
@CHECK_B_BUTTON:
	LDA PAD_STATE
	AND #PAD::B_BUTTON
	BEQ @WAIT_FOR_B_BUTTON
	STZ BATTLE_MODE
	LDA #.LOWORD(-1)
	STA @LOCAL00
	BRA @RETURN
@CHECK_Y_BUTTON:
	LDA PAD_STATE
	AND #PAD::Y_BUTTON
	BEQ @RETURN
	LDA #.LOWORD(-1)
	STA @LOCAL00
@RETURN:
	LDA @LOCAL00
	END_C_FUNCTION
