
CHECK_DEBUG_ENEMIES_ENABLED:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA DEBUG_MODE_NUMBER
	CMP #2
	BNE @NOT_ENABLED
	LDA DEBUG_ENEMIES_ENABLED_FLAG
	BEQ @NOT_ENABLED
	LDA #.LOWORD(-1)
	BRA @NOT_MODE_1
@NOT_ENABLED:
	LDA #0
@NOT_MODE_1:
	END_C_FUNCTION
