
CHECK_DEBUG_MODE_1:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA DEBUG_MODE_NUMBER
	CMP #1
	BNE @RETURN
	LDA #0
	BRA @STORE_RESULT
@RETURN:
	LDA #.LOWORD(-1)
@STORE_RESULT:
	END_C_FUNCTION
