
DEBUG_CHECK_VIEW_CHARACTER_MODE:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA DEBUG_MODE_NUMBER
	CMP #$0002
	BNE @NOT_VIEW_MODE
	LDA #$0000
	BRA @RETURN
@NOT_VIEW_MODE:
	LDA #$0001
@RETURN:
	RTL
