
CLAMP_TO_DEBUG_MAX:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STA @LOCAL00
	LDA DEBUG_MODE_NUMBER
	CMP #1
	BNE @NOT_MODE_1
	LDA @LOCAL00
	CMP #10
	BLTEQ @NOT_MODE_1
	LDA #10
	STA @LOCAL00
@NOT_MODE_1:
	LDA @LOCAL00
	END_C_FUNCTION
