
; unused function, possibly for debugging
DEBUG_MAP_SCROLL_HANDLER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDY #0
	TYA
	STA @LOCAL01
	LDX PAD_STATE
	LDA PAD_PRESS
	STA @VIRTUAL02
	AND #PAD::START_BUTTON
	BEQ @CHECK_DPAD_DOWN
	LDA DEBUG_MAP_SCROLL_MODE
	EOR #$0001
	STA DEBUG_MAP_SCROLL_MODE
@CHECK_DPAD_DOWN:
	TXA
	AND #PAD::DOWN
	BEQ @CHECK_DPAD_UP
	LDY #1
	BRA @CHECK_DPAD_LEFT
@CHECK_DPAD_UP:
	TXA
	AND #PAD::UP
	BEQ @CHECK_DPAD_LEFT
	LDY #.LOWORD(-1)
@CHECK_DPAD_LEFT:
	TXA
	AND #PAD::LEFT
	BEQ @CHECK_DPAD_RIGHT
	LDA #.LOWORD(-1)
	STA @LOCAL01
	BRA @CHECK_L_BUTTON
@CHECK_DPAD_RIGHT:
	TXA
	AND #PAD::RIGHT
	BEQ @CHECK_L_BUTTON
	LDA #1
	STA @LOCAL01
@CHECK_L_BUTTON:
	TXA
	AND #PAD::L_BUTTON
	BEQ @CHECK_R_BUTTON
	LDA @LOCAL01
	ASL
	ASL
	STA @LOCAL01
	TYA
	ASL
	ASL
	TAY
@CHECK_R_BUTTON:
	TXA
	AND #PAD::R_BUTTON
	BEQ @CHECK_X_BUTTON
	LDA @LOCAL01
	ASL
	STA @LOCAL01
	TYA
	ASL
	TAY
@CHECK_X_BUTTON:
	TXA
	AND #PAD::X_BUTTON
	BEQ @CHECK_Y_BUTTON
	LDA @LOCAL01
	ASL
	STA @LOCAL01
	TYA
	ASL
	TAY
@CHECK_Y_BUTTON:
	TXA
	AND #PAD::Y_BUTTON
	BNE @APPLY_SCROLL
	LDA @LOCAL00
	STA @VIRTUAL04
	AND #$0080
	BEQ @APPLY_SCROLL
	LDY #0
	TYA
	STA @LOCAL01
@APPLY_SCROLL:
	LDA @LOCAL01
	CLC
	ADC SCREEN_X_PIXELS
	TAX
	STX SCREEN_X_PIXELS
	TYA
	CLC
	ADC SCREEN_Y_PIXELS
	STA @LOCAL01
	STA SCREEN_Y_PIXELS
	CPX SCREEN_X_PIXELS_COPY
	BNE @POSITION_CHANGED
	CMP SCREEN_Y_PIXELS_COPY
	BEQ @NO_POSITION_CHANGE
@POSITION_CHANGED:
	LDA SCREEN_Y_PIXELS
	SEC
	SBC #112
	TAX
	LDA SCREEN_X_PIXELS
	SEC
	SBC #128
	JSR REFRESH_MAP_AT_POSITION
	BRA @SAVE_SCREEN_COPY
@NO_POSITION_CHANGE:
	LDA @VIRTUAL02
	AND #$0080
	BEQ @SAVE_SCREEN_COPY
	LDA #.LOWORD(-1)
	STA LOADED_MAP_PALETTE
	STA LOADED_MAP_TILE_COMBO
	TXA
	AND #$FFF8
	STA SCREEN_X_PIXELS
	LDA @LOCAL01
	AND #$FFF8
	STA SCREEN_Y_PIXELS
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	LDA SCREEN_Y_PIXELS
	LSR
	LSR
	LSR
	TAX
	LDA SCREEN_X_PIXELS
	LSR
	LSR
	LSR
	JSL LOAD_MAP_AT_POSITION
	JSL BLANK_SCREEN_AND_WAIT_VBLANK
@SAVE_SCREEN_COPY:
	LDA SCREEN_X_PIXELS
	STA SCREEN_X_PIXELS_COPY
	LDA SCREEN_Y_PIXELS
	STA SCREEN_Y_PIXELS_COPY
	END_C_FUNCTION
