
DEBUG_HANDLE_CURSOR_MOVEMENT:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA PAD_HELD
	STA @LOCAL00
	AND #PAD::UP
	BEQ @CHECK_DOWN
	LDA DEBUG_MENU_CURSOR_POSITION
	BEQ @WRAP_TO_BOTTOM
	DEC DEBUG_MENU_CURSOR_POSITION
	BRA @CHECK_DOWN
@WRAP_TO_BOTTOM:
	LDA #6
	STA DEBUG_MENU_CURSOR_POSITION
@CHECK_DOWN:
	LDA @LOCAL00
	AND #PAD::DOWN
	BEQ @CHECK_DOWN_DONE
	LDA DEBUG_MENU_CURSOR_POSITION
	CMP #6
	BEQ @WRAP_TO_TOP
	INC DEBUG_MENU_CURSOR_POSITION
	BRA @CHECK_DOWN_DONE
@WRAP_TO_TOP:
	STZ DEBUG_MENU_CURSOR_POSITION
@CHECK_DOWN_DONE:
	LDA DEBUG_CURSOR_ENTITY
	ASL
	TAX
	LDA DEBUG_MENU_CURSOR_POSITION
	OPTIMIZED_MULT @VIRTUAL04, 3 * 8
	CLC
	ADC #26 * 2
	STA ENTITY_ABS_Y_TABLE,X
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::START_BUTTON | PAD::A_BUTTON | PAD::L_BUTTON
	STA DEBUG_MENU_BUTTONS_PRESSED
	END_C_FUNCTION
