
INIT_DEBUG_MODE_DISPLAY:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	LDA DEBUG_MODE_NUMBER
	BEQ @MODE_ZERO
	JSL LOAD_DEBUG_MODE_GRAPHICS
	BRA @DONE
@MODE_ZERO:
	JSL LOAD_CHARACTER_WINDOW_PALETTE
@DONE:
	END_C_FUNCTION
