
INTEGER_TO_BINARY_DEBUG_TILES:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int value8
	END_STACK_VARS
	TAY
	STY @LOCAL02
	LDA #16
	JSL SBRK
	STA @VIRTUAL02
	LDX #0
	STX @LOCAL01
	BRA @BIT_LOOP_CHECK
@PROCESS_BIT:
	LDY @LOCAL02
	TYA
	AND #$0080
	BEQ @BIT_ZERO
	LDA #$2031 ;1 tile, priority
	STA @LOCAL00
	BRA @STORE_TILE
@BIT_ZERO:
	LDA #$2030 ;0 tile, priority
	STA @LOCAL00
@STORE_TILE:
	TXA
	ASL
	STA @VIRTUAL04
	LDA @VIRTUAL02
	CLC
	ADC @VIRTUAL04
	TAX
	LDA @LOCAL00
	STA __BSS_START__,X
	TYA
	ASL
	TAY
	STY @LOCAL02
	LDX @LOCAL01
	INX
	STX @LOCAL01
@BIT_LOOP_CHECK:
	CPX #8
	BCC @PROCESS_BIT
	LDA @VIRTUAL02
	END_C_FUNCTION
