
LOAD_DEBUG_MODE_GRAPHICS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LOADPTR BUFFER, @VIRTUAL06
	JSL INITIALIZE_BATTLE_UI_STATE
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA DEBUG_MODE_NUMBER
	CMP #1
	BNE @NOT_MODE_1
	JSL LOAD_WINDOW_GFX
.IF .DEFINED(JPN)
	COPY_TO_VRAM1P @VIRTUAL06, VRAM::TEXT_LAYER_TILES, 14336, 0
.ELSE
	LDA #1
	JSL UPLOAD_TEXT_TILES_TO_VRAM
.ENDIF
	JSL LOAD_CHARACTER_WINDOW_PALETTE
	BRA @UPLOAD_PALETTE
@NOT_MODE_1:
	COPY_TO_VRAM1 DEBUG_MENU_FONT, VRAM::TEXT_LAYER_TILES + $100, 4096, 0
	LDA #0
	STA [@VIRTUAL06]
	COPY_TO_VRAM1P @VIRTUAL06, VRAM::TEXT_LAYER_TILEMAP, 2048, 3
	LDA DEBUG_MODE_NUMBER
	CMP #3
	BEQ @MODE_3_PALETTE
	LDA #.LOWORD(-1)
	STA PALETTES+4
	BRA @UPLOAD_PALETTE
@MODE_3_PALETTE:
	LOADPTR DEBUG_FONT_PALETTE, @LOCAL00
	LDX #BPP2PALETTE_SIZE * 3
	LDA #.LOWORD(PALETTES)
	JSL MEMCPY16
@UPLOAD_PALETTE:
	SEP #PROC_FLAGS::ACCUM8
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
