
DEBUG_PROCESS_COMMAND_SELECTION:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA DEBUG_MENU_BUTTONS_PRESSED
	BEQL @RETURN
	LDA DEBUG_MENU_CURSOR_POSITION
	BEQ @CMD_GAME_START
	CMP #$0001
	BEQ @CMD_NPC_TEST
	CMP #$0002
	BEQ @CMD_ENEMY_TEST
	CMP #$0003
	BEQ @CMD_OVERWORLD_3
	CMP #$0004
	BEQ @CMD_BATTLE_TEST
	CMP #$0005
	BEQ @CMD_OVERWORLD_5
	CMP #$0006
	BEQ @CMD_SOUND_TEST
	BRA @AFTER_COMMAND
@CMD_GAME_START:
	LDY #$0000
	LDX #$0001
	LDA #$0004
	JSL FADE_OUT_WITH_MOSAIC
	JSL MAIN_LOOP
	BRA @AFTER_COMMAND
@CMD_NPC_TEST:
	LDA #$0001
	STA DEBUG_MODE_NUMBER
	LDA #$FFFF
	STA NPC_SPAWNS_ENABLED
	JSR RUN_DEBUG_OVERWORLD_MODE
	BRA @AFTER_COMMAND
@CMD_ENEMY_TEST:
	LDA #$0002
	STA DEBUG_MODE_NUMBER
	LDA #$000A
	STA OVERWORLD_ENEMY_MAXIMUM
	LDA #$FFFF
	STA ENEMY_SPAWNS_ENABLED
	JSR RUN_DEBUG_OVERWORLD_MODE
	BRA @AFTER_COMMAND
@CMD_OVERWORLD_3:
	LDA #$0003
	STA DEBUG_MODE_NUMBER
	JSR RUN_DEBUG_OVERWORLD_MODE
	BRA @AFTER_COMMAND
@CMD_BATTLE_TEST:
	LDA #$0004
	STA DEBUG_MODE_NUMBER
	JSL BATTLE_ROUTINE
	BRA @AFTER_COMMAND
@CMD_OVERWORLD_5:
	LDA #$0005
	STA DEBUG_MODE_NUMBER
	JSR RUN_DEBUG_OVERWORLD_MODE
	BRA @AFTER_COMMAND
@CMD_SOUND_TEST:
	LDA #$0006
	STA DEBUG_MODE_NUMBER
	LDA DEBUG_CURSOR_ENTITY
	JSL RUN_DEBUG_SOUND_TEST
@AFTER_COMMAND:
	JSL DISABLE_HDMA_AND_INIT_WINDOW
	STZ DEBUG_MENU_BUTTONS_PRESSED
	STZ DEBUG_MODE_NUMBER
	JSL INIT_ENTITY_SYSTEM
	JSR INIT_DEBUG_MENU_SCREEN
	JSR DEBUG_DISPLAY_MENU_OPTIONS
	LDX #$0001
	TXA
	JSL FADE_IN
@RETURN:
	RTS
