
RUN_DEBUG_SOUND_TEST:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL04
	LDA #0
	STA @VIRTUAL02
	LDX CURRENT_MUSIC_TRACK
	STX DEBUG_SOUND_MENU_INITIAL_BGM
	STX DEBUG_SOUND_MENU_SELECTED_BGM
	LDA #2
	STA DEBUG_SOUND_MENU_SELECTED_EFFECT
	LDA @VIRTUAL04
	JSR SETUP_DEBUG_SOUND_MENU
@MAIN_LOOP:
	JSL UPDATE_SCREEN
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA PAD_PRESS
	AND #PAD::Y_BUTTON
	BEQ @DELAY_FRAME
	JSR RUN_DEBUG_OVERWORLD_MODE
	LDA @VIRTUAL04
	JSR SETUP_DEBUG_SOUND_MENU
@DELAY_FRAME:
	JSL OAM_CLEAR
	JSL RUN_ACTIONSCRIPT_FRAME
	LDY DEBUG_SOUND_MENU_SELECTED_BGM
	LDX #10
	LDA #18
	JSR DRAW_HEX_BYTE_TO_VRAM
	LDY DEBUG_SOUND_MENU_SELECTED_SE
	LDX #12
	LDA #18
	JSR DRAW_HEX_BYTE_TO_VRAM
	LDY DEBUG_SOUND_MENU_SELECTED_EFFECT
	LDX #14
	LDA #18
	JSR DRAW_HEX_BYTE_TO_VRAM
	LDA PAD_PRESS
	CMP #PAD::SELECT_BUTTON | PAD::START_BUTTON
	BEQL @EXIT
	LDA PAD_HELD
	AND #PAD::UP
	BEQ @SKIP_UP
	LDA @VIRTUAL02
	DEC
	STA @VIRTUAL02
@SKIP_UP:
	LDA PAD_HELD
	AND #PAD::DOWN
	BEQ @SKIP_DOWN
	INC @VIRTUAL02
@SKIP_DOWN:
	LDA @VIRTUAL02
	CMP #.LOWORD(-1)
	BNE @WRAP_CURSOR_LOW
	LDA #2
	STA @VIRTUAL02
@WRAP_CURSOR_LOW:
	LDA @VIRTUAL02
	CMP #3
	BNE @WRAP_CURSOR_HIGH
	LDA #0
	STA @VIRTUAL02
@WRAP_CURSOR_HIGH:
	LDA PAD_PRESS
	AND #PAD::L_BUTTON
	BEQ @SKIP_L_BUTTON
	LDA DEBUG_SOUND_MENU_SELECTED_BGM
	STA DEBUG_SOUND_MENU_INITIAL_BGM
	LDA #46
	STA DEBUG_SOUND_MENU_SELECTED_BGM
@SKIP_L_BUTTON:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON
	BNE @RESTORE_BGM
	LDA PAD_PRESS
	AND #PAD::R_BUTTON
	BEQ @DISPATCH_ROW
@RESTORE_BGM:
	LDA DEBUG_SOUND_MENU_INITIAL_BGM
	STA DEBUG_SOUND_MENU_SELECTED_BGM
@DISPATCH_ROW:
	LDA @VIRTUAL02
	BEQ @HANDLE_BGM_ROW
	CMP #1
	BEQ @HANDLE_SE_ROW
	CMP #2
	BEQL @HANDLE_EFFECT_ROW
	JMP @CHECK_STOP_BUTTON
@HANDLE_BGM_ROW:
	LDA PAD_HELD
	AND #PAD::LEFT
	BEQ @SKIP_BGM_LEFT
	DEC DEBUG_SOUND_MENU_SELECTED_BGM
@SKIP_BGM_LEFT:
	LDA PAD_HELD
	AND #PAD::RIGHT
	BEQ @SKIP_BGM_RIGHT
	INC DEBUG_SOUND_MENU_SELECTED_BGM
@SKIP_BGM_RIGHT:
	LDA DEBUG_SOUND_MENU_SELECTED_BGM
	CMP #.LOWORD(-1)
	BNE @WRAP_BGM_LOW
	LDA #191
	STA DEBUG_SOUND_MENU_SELECTED_BGM
@WRAP_BGM_LOW:
	LDA DEBUG_SOUND_MENU_SELECTED_BGM
	CMP #192
	BNE @WRAP_BGM_HIGH
	LDA #1
	STA DEBUG_SOUND_MENU_SELECTED_BGM
@WRAP_BGM_HIGH:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON
	BEQL @CHECK_STOP_BUTTON
	JSL STOP_MUSIC
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA CURRENT_MUSIC_TRACK
	JSL READ_APU_IO0
	LDA DEBUG_SOUND_MENU_SELECTED_BGM
	JSL CHANGE_MUSIC
	JMP @CHECK_STOP_BUTTON
@HANDLE_SE_ROW:
	LDA PAD_HELD
	AND #PAD::LEFT
	BEQ @SKIP_SE_LEFT
	DEC DEBUG_SOUND_MENU_SELECTED_SE
@SKIP_SE_LEFT:
	LDA PAD_HELD
	AND #PAD::RIGHT
	BEQ @SKIP_SE_RIGHT
	INC DEBUG_SOUND_MENU_SELECTED_SE
@SKIP_SE_RIGHT:
	LDA DEBUG_SOUND_MENU_SELECTED_SE
	CMP #.LOWORD(-1)
	BNE @WRAP_SE_LOW
	LDA #127
	STA DEBUG_SOUND_MENU_SELECTED_SE
@WRAP_SE_LOW:
	LDA DEBUG_SOUND_MENU_SELECTED_SE
	CMP #128
	BNE @WRAP_SE_HIGH
	LDA #1
	STA DEBUG_SOUND_MENU_SELECTED_SE
@WRAP_SE_HIGH:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON
	BEQ @CHECK_STOP_BUTTON
	LDA DEBUG_SOUND_MENU_SELECTED_SE
	JSL PLAY_SOUND
	BRA @CHECK_STOP_BUTTON
@HANDLE_EFFECT_ROW:
	LDA PAD_HELD
	AND #PAD::LEFT
	BEQ @SKIP_EFFECT_LEFT
	DEC DEBUG_SOUND_MENU_SELECTED_EFFECT
@SKIP_EFFECT_LEFT:
	LDA PAD_HELD
	AND #PAD::RIGHT
	BEQ @SKIP_EFFECT_RIGHT
	INC DEBUG_SOUND_MENU_SELECTED_EFFECT
@SKIP_EFFECT_RIGHT:
	LDA DEBUG_SOUND_MENU_SELECTED_EFFECT
	CMP #.LOWORD(-1)
	BNE @WRAP_EFFECT_LOW
	LDA #32
	STA DEBUG_SOUND_MENU_SELECTED_EFFECT
@WRAP_EFFECT_LOW:
	LDA DEBUG_SOUND_MENU_SELECTED_EFFECT
	CMP #33
	BNE @WRAP_EFFECT_HIGH
	LDA #1
	STA DEBUG_SOUND_MENU_SELECTED_EFFECT
@WRAP_EFFECT_HIGH:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON
	BEQ @CHECK_STOP_BUTTON
	LDA DEBUG_SOUND_MENU_SELECTED_EFFECT
	JSL WRITE_APU_PORT1
@CHECK_STOP_BUTTON:
	LDA PAD_PRESS
	AND #PAD::X_BUTTON
	BEQ @SKIP_STOP
	JSL STOP_MUSIC
	JSL STOP_SOUND_EFFECT
@SKIP_STOP:
	LDA @VIRTUAL04
	ASL
	TAX
	LDA @VIRTUAL02
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #84
	STA ENTITY_ABS_Y_TABLE,X
	JMP @MAIN_LOOP
@EXIT:
	END_C_FUNCTION
