
RUN_DEBUG_OVERWORLD_MODE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LOADPTR BUFFER, @VIRTUAL06
	LDA #0
	STA [@VIRTUAL06]
	LDA DEBUG_START_POSITION_X
	STA @VIRTUAL04
	LDA DEBUG_START_POSITION_Y
	STA @VIRTUAL02
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	JSL INIT_ENTITY_SYSTEM
	JSL CLEAR_OVERWORLD_SPRITEMAPS
	LDX #0
	LDA #$8000
	JSL ALLOC_SPRITE_MEM
	JSL INITIALIZE_MISC_OBJECT_DATA
	LDA DEBUG_VIEW_CHARACTER_SPRITE
	STA @LOCAL07
	LDA #23
	STA ENTITY_ALLOCATION_MIN_SLOT
	LDA #24
	STA ENTITY_ALLOCATION_MAX_SLOT
	LDA #3
	STA NEW_ENTITY_PRIORITY
	LDA @VIRTUAL04
	STA GAME_STATE+game_state::leader_x_coord
	LDA @VIRTUAL02
	STA GAME_STATE+game_state::leader_y_coord
	LDY #0
	TYX
	LDA #EVENT_SCRIPT::EVENT_001
	JSL INIT_ENTITY
	JSL RESET_PARTY_STATE
	LDA #0
	STA @LOCAL06
	BRA @CLEAR_PARTY_CHECK
@CLEAR_PARTY_BODY:
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ a:game_state::party_members,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL06
	INC
	STA @LOCAL06
@CLEAR_PARTY_CHECK:
	CMP #6
	BCC @CLEAR_PARTY_BODY
	LDA #CHARACTER_PAULA
	JSL ADD_CHAR_TO_PARTY
	LDA DEBUG_MODE_NUMBER
	CMP #5
	BEQ @SKIP_EXTRA_PARTY
	LDA DEBUG_MODE_NUMBER
	CMP #3
	BEQ @SKIP_EXTRA_PARTY
	LDA #CHARACTER_JEFF
	JSL ADD_CHAR_TO_PARTY
	LDA #CHARACTER_POO
	JSL ADD_CHAR_TO_PARTY
@SKIP_EXTRA_PARTY:
	LDA #<-1
	JSL ENABLE_CHARACTER_MOVEMENT
	LDX #128
	STX ENTITY_SCREEN_X_TABLE + (PARTY_LEADER_ENTITY_INDEX * 2)
	LDX #112
	STX ENTITY_SCREEN_Y_TABLE + (PARTY_LEADER_ENTITY_INDEX * 2)
	LDA DEBUG_MODE_NUMBER
	CMP #2
	BNE @SKIP_ENTITY_CREATE
	LDA #32
	STA @LOCAL00
	STA @LOCAL01
	LDY #.LOWORD(-1)
	LDX #EVENT_SCRIPT::EVENT_004
	LDA @LOCAL07
	JSL CREATE_ENTITY
	STA @LOCAL05
	ASL
	STA @LOCAL06
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA __BSS_START__,X
	LDA @LOCAL06
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #$8000
	STA __BSS_START__,X
@SKIP_ENTITY_CREATE:
	SEP #PROC_FLAGS::ACCUM8
	STZ_BADOPT @LOCAL00
	LDX #BPP4PALETTE_SIZE * 16
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(PALETTES)
	JSL MEMSET16
	JSL OVERWORLD_INITIALIZE
	LDX @VIRTUAL02
	LDA @VIRTUAL04
	JSL LOAD_MAP_AT_POSITION
	LDY #4
	LDX @VIRTUAL02
	LDA @VIRTUAL04
	JSL SET_LEADER_POSITION_AND_LOAD_PARTY
	JSL LOAD_DEBUG_MODE_GRAPHICS
	LDA DEBUG_MODE_NUMBER
	CMP #3
	BNE @SKIP_MODE3_SETUP
	SEP #PROC_FLAGS::ACCUM8
	LDA #$13
	STA TM_MIRROR
	LDA #$04
	STA TD_MIRROR
	LDA #$02
	STA f:CGWSEL
	LDA #$47
	STA f:CGADSUB
	REP #PROC_FLAGS::ACCUM8
	LDA #3
	STA DEBUG_MODE_NUMBER
@SKIP_MODE3_SETUP:
	LDA DEBUG_MODE_NUMBER
	CMP #5
	BNE @SKIP_POSITION_SETUP
	JSL SETUP_DEBUG_CHECK_POSITION_WINDOW
@SKIP_POSITION_SETUP:
	LDA #.LOWORD(PROCESS_OVERWORLD_TASKS)
	JSL SET_IRQ_CALLBACK
	JSL BLANK_SCREEN_AND_WAIT_VBLANK
	LDX #1
	TXA
	JSL FADE_IN
@MAIN_LOOP:
	JSL OAM_CLEAR
	LDA DEBUG_MODE_NUMBER
	CMP #2
	BEQ @MODE2_OVERLAY
	CMP #5
	BEQ @MODE5_OVERLAY
	BRA @AFTER_OVERLAY
@MODE2_OVERLAY:
	JSR DISPLAY_VIEW_CHARACTER_DEBUG_OVERLAY
	BRA @AFTER_OVERLAY
@MODE5_OVERLAY:
	JSR DISPLAY_CHECK_POSITION_DEBUG_OVERLAY
@AFTER_OVERLAY:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON
	BEQL @AFTER_RELOAD
	STZ BATTLE_SWIRL_COUNTDOWN
	LDA PAD_STATE
	AND #PAD::X_BUTTON
	BEQ @ENABLE_ENEMIES
	LDA #.LOWORD(-1)
	STA DEBUG_ENEMIES_ENABLED_FLAG
@ENABLE_ENEMIES:
	LDA #.LOWORD(-1)
	STA LOADED_MAP_PALETTE
	STA LOADED_MAP_TILE_COMBO
	LDA SCREEN_X_PIXELS
	AND #$FFF8
	STA SCREEN_X_PIXELS
	LDA SCREEN_Y_PIXELS
	AND #$FFF8
	STA SCREEN_Y_PIXELS
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	LDA #.LOWORD(GAME_STATE)+game_state::leader_x_coord
	STA @VIRTUAL04
	LDA #.LOWORD(GAME_STATE)+game_state::leader_y_coord
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	TAX
	STX @LOCAL04
	LDX @VIRTUAL04
	LDA __BSS_START__,X
	LDX @LOCAL04
	JSL LOAD_MAP_AT_POSITION
	LDY GAME_STATE+game_state::leader_direction
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	TAX
	STX @LOCAL04
	LDX @VIRTUAL04
	LDA __BSS_START__,X
	LDX @LOCAL04
	JSL SET_LEADER_POSITION_AND_LOAD_PARTY
	JSL LOAD_DEBUG_MODE_GRAPHICS
	STZ DEBUG_ENEMIES_ENABLED_FLAG
	LDA DEBUG_MODE_NUMBER
	CMP #5
	BNE @SKIP_POSITION_WINDOW
	JSL SETUP_DEBUG_CHECK_POSITION_WINDOW
@SKIP_POSITION_WINDOW:
	JSL BLANK_SCREEN_AND_WAIT_VBLANK
	LDY #0
	LDX #1
	LDA #4
	JSL FADE_IN_WITH_MOSAIC
@AFTER_RELOAD:
	LDA DEBUG_MODE_NUMBER
	CMP #2
	BNEL @AFTER_MODE2_INPUT
	LDY @LOCAL07
	LDA PAD_HELD + 2
	STA @LOCAL03
	AND #PAD::UP
	BEQ @CHECK_DOWN
	LDA @LOCAL07
	CMP #333
	BEQ @WRAP_SPRITE_MAX
	INC @LOCAL07
	BRA @AFTER_SPRITE_CHANGE
@WRAP_SPRITE_MAX:
	STZ @LOCAL07
	BRA @AFTER_SPRITE_CHANGE
@CHECK_DOWN:
	LDA @LOCAL03
	AND #PAD::DOWN
	BEQ @AFTER_SPRITE_CHANGE
	LDA @LOCAL07
	BEQ @WRAP_SPRITE_MIN
	DEC @LOCAL07
	BRA @AFTER_SPRITE_CHANGE
@WRAP_SPRITE_MIN:
	LDA #324
	STA @LOCAL07
@AFTER_SPRITE_CHANGE:
	LDA PAD_PRESS + 2
	AND #PAD::X_BUTTON
	BEQ @SKIP_FREEZE
	LDA @LOCAL05
	ASL
	STA @LOCAL06
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA __BSS_START__,X
	LDA @LOCAL06
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #$8000
	STA __BSS_START__,X
@SKIP_FREEZE:
	LDA PAD_PRESS + 2
	AND #PAD::Y_BUTTON
	BEQ @SKIP_UNFREEZE
	LDA @LOCAL05
	ASL
	STA @LOCAL06
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	AND #$FFFF ^ (OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED)
	STA __BSS_START__,X
	LDA @LOCAL06
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAX
	LDA __BSS_START__,X
	AND #$7FFF
	STA __BSS_START__,X
@SKIP_UNFREEZE:
	CPY @LOCAL07
	BEQ @SKIP_RECREATE
	LDA @LOCAL05
	JSL REMOVE_ENTITY
	LDA #32
	STA @LOCAL00
	STA @LOCAL01
	LDY @LOCAL05
	LDX #EVENT_SCRIPT::EVENT_004
	LDA @LOCAL07
	JSL CREATE_ENTITY
	ASL
	TAX
	STZ ENTITY_NPC_IDS,X
@SKIP_RECREATE:
	LDA PAD_PRESS + 2
	AND #PAD::A_BUTTON
	BEQ @SKIP_SPAWN
	LDA @LOCAL05
	ASL
	TAX
	LDA ENTITY_TICK_CALLBACK_HIGH,X
	AND #OBJECT_TICK_DISABLED
	BNE @SKIP_SPAWN
	LDA BG1_X_POS
	CLC
	ADC #32
	TAX
	LDA BG1_Y_POS
	CLC
	ADC #32
	STX @LOCAL00
	STA @LOCAL01
	LDY #.LOWORD(-1)
	LDX #EVENT_SCRIPT::EVENT_006
	LDA @LOCAL07
	JSL CREATE_ENTITY
	ASL
	TAX
	STZ ENTITY_NPC_IDS,X
@SKIP_SPAWN:
	LDA PAD_PRESS + 2
	AND #PAD::B_BUTTON
	BEQ @AFTER_MODE2_INPUT
	LDA BG1_X_POS
	STA @LOCAL02
	LDY BG1_Y_POS
	LDA #0
	STA @VIRTUAL02
	BRA @PATHFIND_LOOP_CHECK
@PATHFIND_LOOP_BODY:
	LDA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_SCRIPT_TABLE,X
	CMP #.LOWORD(-1)
	BEQ @SKIP_PATHFIND_CLEAR
	STZ ENTITY_PATHFINDING_STATES,X
@SKIP_PATHFIND_CLEAR:
	INC @VIRTUAL02
@PATHFIND_LOOP_CHECK:
	LDA @VIRTUAL02
	CMP #MAX_ENTITIES
	BNE @PATHFIND_LOOP_BODY
	LDA @LOCAL02
	STA @LOCAL00
	STY @LOCAL01
	LDY #.LOWORD(-1)
	LDX #EVENT_SCRIPT::EVENT_499
	LDA #OVERWORLD_SPRITE::GIRL_IN_STRIPED_APRON
	JSL CREATE_ENTITY
	ASL
	TAX
	LDA #.LOWORD(-1)
	STA ENTITY_PATHFINDING_STATES,X
	JSL PATHFIND_TO_PARTY_LEADER
@AFTER_MODE2_INPUT:
	JSL RUN_ACTIONSCRIPT_FRAME
	LDA PAD_STATE
	AND #PAD::START_BUTTON | PAD::SELECT_BUTTON
	CMP #PAD::START_BUTTON | PAD::SELECT_BUTTON
	BNE @CHECK_Y_MENU
	LDA ENTITY_ABS_X_TABLE + (PARTY_LEADER_ENTITY_INDEX * 2)
	STA DEBUG_START_POSITION_X
	LDA ENTITY_ABS_Y_TABLE + (PARTY_LEADER_ENTITY_INDEX * 2)
	STA DEBUG_START_POSITION_Y
	LDA @LOCAL07
	STA DEBUG_VIEW_CHARACTER_SPRITE
	BRA @EXIT
@CHECK_Y_MENU:
	LDA PAD_PRESS
	AND #PAD::Y_BUTTON
	BEQ @SKIP_Y_MENU
	JSL DEBUG_Y_BUTTON_MENU
@SKIP_Y_MENU:
	LDA DEBUG_MODE_NUMBER
	CMP #3
	BNE @SKIP_COLLISION_OVERLAY
	LDA BG1_X_POS
	STA BG3_X_POS
	LDA BG1_Y_POS
	STA BG3_Y_POS
	LDA PAD_PRESS
	AND #PAD::SELECT_BUTTON
	BEQ @SKIP_COLLISION_OVERLAY
	LDX VIEW_ATTRIBUTE_MODE
	INX
	STX VIEW_ATTRIBUTE_MODE
	CPX #4
	BNE @SKIP_COLLISION_UPDATE
	STZ VIEW_ATTRIBUTE_MODE
@SKIP_COLLISION_UPDATE:
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSR UPDATE_DEBUG_COLLISION_DISPLAY
@SKIP_COLLISION_OVERLAY:
	LDA DEBUG_MODE_NUMBER
	CMP #1
	BNE @SKIP_OPEN_MENU
	LDA PAD_PRESS
	AND #PAD::B_BUTTON
	BEQ @SKIP_OPEN_MENU
	JSL OPEN_MENU_BUTTON
@SKIP_OPEN_MENU:
	LDA CURRENT_QUEUED_INTERACTION
	SEC
	SBC NEXT_QUEUED_INTERACTION
	BEQ @SKIP_INTERACTIONS
	JSL PROCESS_QUEUED_INTERACTIONS
@SKIP_INTERACTIONS:
	JSL UPDATE_SCREEN
	JSL WAIT_UNTIL_NEXT_FRAME
	JSL INIT_BATTLE_OVERWORLD
	JMP @MAIN_LOOP
@EXIT:
	END_C_FUNCTION
