
SETUP_DEBUG_SOUND_MENU:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL02
	LDY #0
	LDX #1
	LDA #4
	JSL FADE_OUT_WITH_MOSAIC
	JSL INIT_ENTITY_SYSTEM
	JSR INIT_DEBUG_MENU_SCREEN
	LOADPTR DEBUG_SOUND_MODE_MENU_TEXT, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #5
	LDA #10
	JSR DRAW_DEBUG_MENU_TEXT_ROW
	LDA #14
	MOVE_INTX @LOCAL01, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX #10
	TXA
	JSR DRAW_DEBUG_MENU_TEXT_ROW
	LDA #28
	MOVE_INTX @LOCAL01, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX #12
	LDA #10
	JSR DRAW_DEBUG_MENU_TEXT_ROW
	LDA #42
	MOVE_INTX @LOCAL01, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX #14
	LDA #10
	JSR DRAW_DEBUG_MENU_TEXT_ROW
	LDA #56
	MOVE_INTX @LOCAL01, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX #20
	LDA #9
	JSR DRAW_DEBUG_MENU_TEXT_ROW
	LDA #70
	MOVE_INTX @LOCAL01, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX #22
	LDA #10
	JSR DRAW_DEBUG_MENU_TEXT_ROW
	LDA @VIRTUAL02
	ASL
	TAX
	LDA #64
	STA ENTITY_ABS_X_TABLE,X
	LDA #80
	STA ENTITY_ABS_Y_TABLE,X
	LDY #0
	LDX #1
	LDA #4
	JSL FADE_IN_WITH_MOSAIC
	END_C_FUNCTION
