
DEBUG_Y_BUTTON_MENU:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
.IF .DEFINED(USA)
	STACK_RESERVE_INT32
.ENDIF
	END_STACK_VARS
.IF .DEFINED(JPN)
	@DEBUGSTRINGLENGTH = 9
.ELSE
	@DEBUGSTRINGLENGTH = 10
.ENDIF
	JSL DISABLE_ALL_ENTITIES
	LDA #SFX::CURSOR1
	JSL PLAY_SOUND
	JSR SHOW_HPPP_WINDOWS
@DISPLAY_MENU:
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
.IF !.DEFINED(JPN)
	MOVE_INT @VIRTUAL06, @LOCAL04
.ENDIF
	CREATE_WINDOW_NEAR #WINDOW::PHONE_MENU
	LDA #0
	STA @LOCAL03
	BRA @MENU_ITEM_LOOP_CHECK
@ADD_MENU_ITEM:
.IF .DEFINED(JPN)
	MOVE_INT @VIRTUAL0A, @LOCAL00
.ELSE
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
.ENDIF
	MOVE_INT_CONSTANT NULL, @LOCAL01
	JSR ADD_MENU_OPTION
	LDA @LOCAL03
	INC
	STA @LOCAL03
@MENU_ITEM_LOOP_CHECK:
	LOADPTR DEBUG_MENU_TEXT, @VIRTUAL0A
	LDA @LOCAL03
	OPTIMIZED_MULT @VIRTUAL04, @DEBUGSTRINGLENGTH
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	BNE @ADD_MENU_ITEM
	LDY #0
	TYX
	LDA #1
	JSR OPEN_WINDOW_AND_PRINT_MENU
	LDA #1
	JSR SELECTION_MENU
	CMP #1
	BEQL @CMD_FLAGS
	CMP #2
	BEQL @CMD_GOODS
	CMP #3
	BEQL @CMD_SAVE
	CMP #4
	BEQL @CMD_MSG_00
	CMP #5
	BEQL @CMD_MSG_01
	CMP #6
	BEQL @CMD_MSG_02
	CMP #7
	BEQL @CMD_MSG_UNKNOWN
	CMP #8
	BEQL @CMD_WARP
	CMP #9
	BEQL @CMD_COFFEE_TEA
	CMP #10
	BEQL @CMD_PSI_1
	CMP #11
	BEQL @CMD_PSI_2
	CMP #12
	BEQL @CMD_PSI_3_4
	CMP #13
	BEQL @CMD_NAME_0
	CMP #14
	BEQL @CMD_NAME_1
	CMP #15
	BEQL @CMD_TOWN_MAP
	CMP #16
	BEQL @CMD_GUIDE
	CMP #17
	BEQL @CMD_CAST
	CMP #18
	BEQL @CMD_SOUND_STONE
	CMP #19
	BEQL @CMD_CREDITS
	CMP #20
	BEQL @CMD_FLIPOUT
	CMP #21
	BEQL @CMD_REPLAY
	CMP #22
	BEQL @CMD_MSG_BTL
	CMP #23
	BEQL @CMD_TO_BE_CONTINUED
	JMP @CMD_DISABLE_REPLAY
@CMD_FLAGS:
	JSL DEBUG_Y_BUTTON_FLAG
	JMP @AFTER_COMMAND
@CMD_GOODS:
	JSL DEBUG_Y_BUTTON_GOODS
	JMP @AFTER_COMMAND
@CMD_SAVE:
	JSL SAVE_CURRENT_GAME
	LDA GAME_STATE+game_state::leader_x_coord
	STA RESPAWN_X
	LDA GAME_STATE+game_state::leader_y_coord
	STA RESPAWN_Y
	JMP @AFTER_COMMAND
@CMD_MSG_00:
	LOADPTR MSG_DEBUG_00, @VIRTUAL06
.IF !.DEFINED(JPN)
	MOVE_INT @VIRTUAL06, @LOCAL04
.ENDIF
	JMP @AFTER_COMMAND
@CMD_MSG_01:
	LOADPTR MSG_DEBUG_01, @VIRTUAL06
.IF !.DEFINED(JPN)
	MOVE_INT @VIRTUAL06, @LOCAL04
.ENDIF
	JMP @AFTER_COMMAND
@CMD_MSG_02:
	LOADPTR MSG_DEBUG_02, @VIRTUAL06
.IF !.DEFINED(JPN)
	MOVE_INT @VIRTUAL06, @LOCAL04
.ENDIF
	JMP @AFTER_COMMAND
@CMD_MSG_UNKNOWN:
	LOADPTR TEXT_DEBUG_UNKNOWN_MENU_2, @VIRTUAL06
.IF !.DEFINED(JPN)
	MOVE_INT @VIRTUAL06, @LOCAL04
.ENDIF
	JMP @AFTER_COMMAND
@CMD_WARP:
	LDX #0
	STX @LOCAL02
	BRA @WARP_HPPP_CHECK
@WARP_HPPP_LOOP:
	LDA #0
	JSL UNDRAW_HP_PP_WINDOW
	JSL UPDATE_HPPP_METER_AND_RENDER
	JSL UPDATE_HPPP_METER_AND_RENDER
	LDA #0
	JSL DRAW_AND_MARK_HPPP_WINDOW
	JSL UPDATE_HPPP_METER_AND_RENDER
	JSL UPDATE_HPPP_METER_AND_RENDER
	LDX @LOCAL02
	INX
	STX @LOCAL02
@WARP_HPPP_CHECK:
	CPX #30
	BCC @WARP_HPPP_LOOP
	LDA #7696
	STA @VIRTUAL04
	LDA #2280
	STA @VIRTUAL02
	LDX #1
	TXA
	JSL FADE_OUT
	LDX @VIRTUAL02
	LDA @VIRTUAL04
	JSL LOAD_MAP_AT_POSITION
	LDY #0
	LDX @VIRTUAL02
	LDA @VIRTUAL04
	JSL SET_LEADER_POSITION_AND_LOAD_PARTY
	LDX #1
	TXA
	JSL FADE_IN
	JMP @AFTER_COMMAND
@CMD_COFFEE_TEA:
	JSL RAND
	AND #$0001
	JSL COFFEETEA_SCENE
	JMP @AFTER_COMMAND
@CMD_PSI_1:
	LDA #1
	JSL LEARN_SPECIAL_PSI
	JMP @AFTER_COMMAND
@CMD_PSI_2:
	LDA #2
	JSL LEARN_SPECIAL_PSI
	JMP @AFTER_COMMAND
@CMD_PSI_3_4:
	LDA #3
	JSL LEARN_SPECIAL_PSI
	LDA #4
	JSL LEARN_SPECIAL_PSI
	JMP @AFTER_COMMAND
@CMD_NAME_0:
	LDA #0
	JSL ENTER_YOUR_NAME_PLEASE
	JMP @AFTER_COMMAND
@CMD_NAME_1:
	LDA #1
	JSL ENTER_YOUR_NAME_PLEASE
.IF .DEFINED(JPN)
	BRA @AFTER_COMMAND
.ELSE
	JMP @AFTER_COMMAND
.ENDIF
@CMD_TOWN_MAP:
	JSL RUN_TOWN_MAP_MENU
	BRA @AFTER_COMMAND
@CMD_GUIDE:
	JSL DEBUG_Y_BUTTON_GUIDE
	BRA @AFTER_COMMAND
@CMD_CAST:
	JSL PLAY_CAST_SCENE
	LDA #1
	JSR TELEPORT
	BRA @AFTER_COMMAND
@CMD_SOUND_STONE:
	LDA #1
	JSL USE_SOUND_STONE
	BRA @AFTER_COMMAND
@CMD_CREDITS:
	JSL PLAY_CREDITS
	LDA #1
	JSR TELEPORT
	BRA @AFTER_COMMAND
@CMD_FLIPOUT:
	LDX #0
	LDA HPPP_METER_FLIPOUT_MODE
	BNE @FLIPOUT_OFF
	LDX #1
@FLIPOUT_OFF:
	TXA
	JSR TOGGLE_HPPP_FLIPOUT_MODE
	BRA @AFTER_COMMAND
@CMD_REPLAY:
	JSL START_REPLAY_MODE
	BRA @CLEANUP
@CMD_MSG_BTL:
	LOADPTR MSG_BTL_INORU_BACK_TO_PC_9, @VIRTUAL06
.IF !.DEFINED(JPN)
	MOVE_INT @VIRTUAL06, @LOCAL04
.ENDIF
	BRA @AFTER_COMMAND
@CMD_TO_BE_CONTINUED:
	LOADPTR MSG_EVT_TO_BE_CONTINUED, @VIRTUAL06
	JSR CLOSE_ALL_WINDOWS
	JSR HIDE_HPPP_WINDOWS
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
	BRA @CLEANUP
@CMD_DISABLE_REPLAY:
	JSL DISABLE_REPLAY_MODE
	BRA @CLEANUP
@AFTER_COMMAND:
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
.IF !.DEFINED(JPN)
	MOVE_INT @LOCAL04, @VIRTUAL06
	CMP @VIRTUAL0A+2
	BNE @HAS_MESSAGE
	LDA @VIRTUAL06
	CMP @VIRTUAL0A
@HAS_MESSAGE:
.ELSE
	CMP32 @VIRTUAL06, @VIRTUAL0A
.ENDIF
	BEQL @DISPLAY_MENU
	JSR CLOSE_FOCUS_WINDOW
	CREATE_WINDOW_NEAR #WINDOW::TEXT_STANDARD
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
@CLEANUP:
	JSR CLOSE_ALL_WINDOWS
	JSR HIDE_HPPP_WINDOWS
@WAIT_FADE:
	JSL WINDOW_TICK
	LDA ENTITY_FADE_ENTITY
	CMP #.LOWORD(-1)
	BNE @WAIT_FADE
	JSL ENABLE_ALL_ENTITIES
	END_C_FUNCTION
