
LOAD_MAP_ROW_AT_SCROLL_POS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TAY
	STY @LOCAL00
	TYX
	LDA BG1_X_POS
	LSR
	LSR
	LSR
	JSL LOAD_MAP_ROW_TO_VRAM_LONG
	LDY @LOCAL00
	TYA
	END_C_FUNCTION
