
LOAD_MAP_COLUMN_TO_VRAM:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TXY
	STY @LOCAL08
	STA @VIRTUAL04
	LDA DEBUG
	BEQ @AFTER_DEBUG
	TYX
	LDA @VIRTUAL04
	JSL UPDATE_DEBUG_COLLISION_COLUMN
@AFTER_DEBUG:
	LDA #128
	JSL SBRK
	STA @LOCAL07
	CLC
	ADC #64
	STA @LOCAL06
	LDY @LOCAL08
	TYA
	DEC
	STA @LOCAL08
	LDA @VIRTUAL04
	LSR
	LSR
	AND #$000F
	ASL
	CLC
	ADC #.LOWORD(LOADED_MAP_BLOCKS)
	STA @LOCAL05
	LDA @VIRTUAL04
	AND #$0003
	PHA
	LDA @LOCAL08
	AND #$0003
	OPTIMIZED_MULT @VIRTUAL02, 4
	STA @VIRTUAL02
	LDA @LOCAL08
	LSR
	LSR
	AND #$000F
	OPTIMIZED_MULT @VIRTUAL02, 32
	TAY
	LDA (@LOCAL05),Y
	OPTIMIZED_MULT @VIRTUAL02, 16
	CLC
	ADC @VIRTUAL02
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	TAY
	STY @LOCAL04
	LDA @LOCAL08
	AND #$001F
	TAX
	STX @LOCAL03
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL02
	BRA @TILE_LOOP_CHECK
@PROCESS_TILE:
	LDA @LOCAL08
	AND #$0003
	BNE @READ_TILE
	LDA @VIRTUAL04
	AND #$0003
	STA @VIRTUAL02
	LDA @LOCAL08
	LSR
	LSR
	AND #$000F
	OPTIMIZED_MULT @VIRTUAL02, 32
	TAY
	LDA (@LOCAL05),Y
	OPTIMIZED_MULT @VIRTUAL02, 16
	CLC
	ADC @VIRTUAL02
	TAY
	STY @LOCAL04
@READ_TILE:
	TYA
	ASL
	TAX
	LDA BUFFER + $8000,X
	STA @LOCAL01
	LDX @LOCAL03
	TXA
	ASL
	TAY
	LDA @LOCAL01
	STA (@LOCAL07),Y
	LDA @LOCAL01
	AND #$03FF
	CMP #384
	BCS @TILE_OUT_OF_RANGE
	LDA @LOCAL01
	ORA #$2000
	STA @LOCAL01
	BRA @STORE_LAYER2_TILE
@TILE_OUT_OF_RANGE:
	STZ @LOCAL01
@STORE_LAYER2_TILE:
	TXA
	ASL
	TAY
	LDA @LOCAL01
	STA (@LOCAL06),Y
	LDY @LOCAL04
	INY
	INY
	INY
	INY
	STY @LOCAL04
	INX
	TXA
	AND #$001F
	TAX
	STX @LOCAL03
	LDA @LOCAL08
	INC
	STA @LOCAL08
	LDA @LOCAL02
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL02
@TILE_LOOP_CHECK:
	LDA @VIRTUAL02
	CMP #MAP_RESOLUTION_HEIGHT
	BCCL @PROCESS_TILE
	LDA @VIRTUAL04
	AND #$003F
	STA @VIRTUAL02
	CMP #31
	BGT @SECOND_TILEMAP_HALF
	LDA @LOCAL07
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	COPY_TO_VRAM1OFFSET @VIRTUAL06, @VIRTUAL02, 64, VRAM::OVERWORLD_LAYER_1_TILEMAP, 27
	LDA @LOCAL06
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	COPY_TO_VRAM1OFFSET @VIRTUAL06, @VIRTUAL02, 64, VRAM::OVERWORLD_LAYER_2_TILEMAP, 27
	BRA @RETURN
@SECOND_TILEMAP_HALF:
	LDA @VIRTUAL02
	AND #$001F
	STA @VIRTUAL02
	LDA @LOCAL07
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	COPY_TO_VRAM1OFFSET @VIRTUAL06, @VIRTUAL02, 64, VRAM::OVERWORLD_LAYER_1_TILEMAP + TILEMAP_SIZE, 27
	LDA @LOCAL06
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	COPY_TO_VRAM1OFFSET @VIRTUAL06, @VIRTUAL02, 64, VRAM::OVERWORLD_LAYER_2_TILEMAP + TILEMAP_SIZE, 27
@RETURN:
	END_C_FUNCTION
