
LOAD_INITIAL_MAP_DATA:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX #0
	BRA @INVALIDATE_CHECK
@INVALIDATE_ENTRY:
	SEP #PROC_FLAGS::ACCUM8
	LDA #>-1
	STA LOADED_COLUMNS_Y,X
	STA LOADED_COLUMNS_X,X
	STA LOADED_ROWS_Y,X
	STA LOADED_ROWS_X,X
	INX
@INVALIDATE_CHECK:
	CPX #16
	BCC @INVALIDATE_ENTRY
	REP #PROC_FLAGS::ACCUM8
	LDA BG1_X_POS
	SEC
	SBC #128
	LSR
	LSR
	LSR
	STA @VIRTUAL04
	LDA BG1_Y_POS
	SEC
	SBC #128
	LSR
	LSR
	LSR
	STA @VIRTUAL02
	STA @LOCAL01
	LDY #0
	STY @LOCAL00
	BRA @MAP_ROW_CHECK
@LOAD_MAP_ROW:
	LDA @LOCAL01
	STA @VIRTUAL02
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	TAX
	LDA @VIRTUAL04
	JSR LOAD_MAP_ROW
	LDY @LOCAL00
	INY
	STY @LOCAL00
@MAP_ROW_CHECK:
	CPY #60
	BCC @LOAD_MAP_ROW
	LDY #0
	STY @LOCAL00
	BRA @COLLISION_ROW_CHECK
@LOAD_COLLISION_ROW:
	LDA @LOCAL01
	STA @VIRTUAL02
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	TAX
	LDA @VIRTUAL04
	JSR LOAD_COLLISION_ROW
	LDY @LOCAL00
	INY
	STY @LOCAL00
@COLLISION_ROW_CHECK:
	CPY #60
	BCC @LOAD_COLLISION_ROW
	END_C_FUNCTION
