
RENDER_TOWN_MAP_ICONS:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL03
	STZ CURRENT_SPRITE_DRAWING_PRIORITY
	LOADPTR TOWN_MAP_ICON_SPRITEMAP_PTR_TABLE, @LOCAL00
	JSL SWAP_SPRITEMAP_BANK
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	LOADPTR TOWN_MAP_ICON_PLACEMENT_PTR_TABLE, @VIRTUAL0A
	LDX @LOCAL03
	TXA
	ASL
	ASL
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	JMP @ICON_LOOP_CHECK
@PROCESS_ICON:
	LDY #1
	STY @LOCAL02
	SEP #PROC_FLAGS::ACCUM8
	LDY #2
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
	LDA f:TOWN_MAP_ICON_ANIMATION_FLAGS,X
	AND #$00FF
	BEQ @CHECK_VISIBILITY
	LDA TOWN_MAP_ANIMATION_FRAME
	CMP #10
	BCS @CHECK_VISIBILITY
	LDY #0
	STY @LOCAL02
@CHECK_VISIBILITY:
	LDX #0
	STX @LOCAL01
	LDY #3
	LDA [@VIRTUAL06],Y
	CMP #$8000
	BCC @CHECK_EVENT_FLAG
	LDX #1
	STX @LOCAL01
@CHECK_EVENT_FLAG:
	LDY #3
	LDA [@VIRTUAL06],Y
	AND #$7FFF
	JSL GET_EVENT_FLAG
	LDX @LOCAL01
	STX @VIRTUAL04
	CMP @VIRTUAL04
	BEQ @DRAW_CHECK
	LDY #0
	STY @LOCAL02
@DRAW_CHECK:
	LDY @LOCAL02
	BEQ @NEXT_ICON
	SEP #PROC_FLAGS::ACCUM8
	LDY #1
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAY
	STY @LOCAL03
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	TAX
	STX @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	LDY #2
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	ASL
	TAX
	LDA f:TOWN_MAP_ICON_SPRITEMAP_PTR_TABLE,X
	LDY @LOCAL03
	LDX @LOCAL01
	JSL REDIRECT_C08C58
@NEXT_ICON:
	LDA #5
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
@ICON_LOOP_CHECK:
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	CMP #<-1
	BNEL @PROCESS_ICON
	JSR UPDATE_TOWN_MAP_PLAYER_ICON
	LDX TOWN_MAP_ANIMATION_FRAME
	DEX
	STX TOWN_MAP_ANIMATION_FRAME
	BNE @RESET_ANIMATION
	LDA #60
	STA TOWN_MAP_ANIMATION_FRAME
@RESET_ANIMATION:
	LDA @VIRTUAL02
	JSL SWAP_SPRITEMAP_BANK
	JSR CYCLE_MAP_ICON_PALETTE
	END_C_FUNCTION
