
ADVANCE_TILEMAP_ANIMATION_FRAME:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	STA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR1_TABLE,X
	STA @LOCAL01
	AND #$0001
	BEQ @USE_LOWER_BUFFER
	LDA @LOCAL01
	LSR
	ASL
	ASL
	ASL
	ASL
	STORE_INT1632 @VIRTUAL06
	CLC
	VAR_ADD_CONST_INT_ASSIGN BUFFER + $4000, @VIRTUAL06
	BRA @BUFFER_SELECTED
@USE_LOWER_BUFFER:
	LDA @LOCAL01
	LSR
	ASL
	ASL
	ASL
	ASL
	STORE_INT1632 @VIRTUAL06
	CLC
	VAR_ADD_CONST_INT_ASSIGN BUFFER + $1000, @VIRTUAL06
@BUFFER_SELECTED:
	LOADPTR BUFFER+2, @VIRTUAL0A
	LDY #0
	BRA @ROW_CHECK
@ROW_LOOP:
	LDX #0
	BRA @COLUMN_CHECK
@COLUMN_LOOP:
	LDA [@VIRTUAL06]
	STA [@VIRTUAL0A]
	INC @VIRTUAL0A
	INC @VIRTUAL0A
	LDA #16
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	INX
@COLUMN_CHECK:
	CPX #30
	BCC @COLUMN_LOOP
	LDA #478
	EOR #$FFFF
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	INY
@ROW_CHECK:
	CPY #8
	BCC @ROW_LOOP
	LOADPTR BUFFER, @LOCAL00
	LDX #588
	LDA #808
	JSL UPDATE_TILEMAP_REGION
	LDA @VIRTUAL02
	ASL
	TAY
	CLC
	ADC #.LOWORD(ENTITY_SCRIPT_VAR1_TABLE)
	TAX
	LDA __BSS_START__,X
	INC
	STA __BSS_START__,X
	LDX #0
	CMP ENTITY_SCRIPT_VAR0_TABLE,Y
	BLTEQ @RETURN
	LDX #1
@RETURN:
	TXA
	END_C_FUNCTION
