
ALLOC_BG2_TILEMAP_ENTRY:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	LDY #$0008
	LDA #$FFFF
	BRA @CHECK_WORD
@NEXT_WORD:
	INY
	INY
	CPY #$0040
	BNE @CHECK_WORD
	JSL HIDE_HPPP_WINDOWS_LONG
	JSL CLOSE_ALL_WINDOWS_FAR
	JSL ENABLE_ALL_ENTITIES
	LDA #.LOWORD(JMP_BUF2)
	JSL LONGJMP
@CHECK_WORD:
	CMP USED_BG2_TILE_MAP,Y
	BEQ @NEXT_WORD
	LDX #$001E
	LDA USED_BG2_TILE_MAP,Y
	BRA @TEST_BIT
@FIND_FREE_BIT:
	DEX
	DEX
	ASL
@TEST_BIT:
	BMI @FIND_FREE_BIT
	LDA USED_BG2_TILE_MAP,Y
	ORA f:POWERS_OF_TWO_16BIT,X
	STA USED_BG2_TILE_MAP,Y
	STX USED_BG2_TILEMAP_FIRST_FREE_BIT
	LSR USED_BG2_TILEMAP_FIRST_FREE_BIT
	TYA
	ASL
	ASL
	ASL
	CLC
	ADC USED_BG2_TILEMAP_FIRST_FREE_BIT
	RTS
