
INIT_USED_BG2_TILE_MAP:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #0
	STA @LOCAL00
	BRA @LOOP_CHECK
@LOOP_BODY:
	ASL
	TAX
	LDA f:USED_BG2_TILE_MAP_DEFAULTS,X
	STA USED_BG2_TILE_MAP,X
	LDA @LOCAL00
	INC
	STA @LOCAL00
@LOOP_CHECK:
	CMP #32
	BCC @LOOP_BODY
	END_C_FUNCTION
