
SET_BUFFER_TILEMAP_PRIORITY:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	END_STACK_VARS
	LOADPTR BUFFER, @VIRTUAL0A
	LDX #0
	BRA @TILE_LOOP_CHECK
@SET_PRIORITY:
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	LDA [@VIRTUAL06]
	ORA #$2000
	STA [@VIRTUAL06]
	INC @VIRTUAL0A
	INC @VIRTUAL0A
	INX
@TILE_LOOP_CHECK:
	CPX #1024
	BCC @SET_PRIORITY
	END_C_FUNCTION
