
DISPLAY_EQUIPMENT_MENU:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	DEC
	STA @VIRTUAL02
	STA @LOCAL05
	JSR SET_INSTANT_PRINTING
	CREATE_WINDOW_NEAR #WINDOW::EQUIP_MENU
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	CMP #1
	BEQ @AFTER_PAGINATION
	LDA #6
	STA PAGINATION_WINDOW
@AFTER_PAGINATION:
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #.SIZEOF(char_struct::name)
	LDA #6
	JSL SET_WINDOW_TITLE
	LDY #0
	STY @LOCAL04
	JMP @EQUIP_SLOT_LOOP_CHECK
@PROCESS_EQUIP_SLOT:
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_10, @VIRTUAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 4
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	MOVE_INT_CONSTANT NULL, @LOCAL01
	TYX
	LDA #0
	JSR ADD_POSITIONED_MENU_OPTION
	LDY @LOCAL04
	TYA
	BEQ @SLOT_WEAPON
	CMP #1
	BEQ @SLOT_BODY
	CMP #2
	BEQ @SLOT_ARMS
	CMP #3
	BEQ @SLOT_OTHER
	BRA @AFTER_SLOT_LOAD
@SLOT_WEAPON:
	LDA @LOCAL05
	STA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::WEAPON,X
	AND #$00FF
	STA @VIRTUAL04
	STA @LOCAL03
	BRA @AFTER_SLOT_LOAD
@SLOT_BODY:
	LDA @LOCAL05
	STA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	STA @VIRTUAL04
	STA @LOCAL03
	BRA @AFTER_SLOT_LOAD
@SLOT_ARMS:
	LDA @LOCAL05
	STA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::ARMS,X
	AND #$00FF
	STA @VIRTUAL04
	STA @LOCAL03
	BRA @AFTER_SLOT_LOAD
@SLOT_OTHER:
	LDA @LOCAL05
	STA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	STA @VIRTUAL04
	STA @LOCAL03
@AFTER_SLOT_LOAD:
	LDA @LOCAL03
	STA @VIRTUAL04
	BEQL @NO_ITEM_EQUIPPED
	LDA @VIRTUAL04
	DEC
	PHA
	LDA @LOCAL05
	STA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	STA @LOCAL02
	LOADPTR ITEM_CONFIGURATION_TABLE, @VIRTUAL06
	LDA @LOCAL02
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX #.SIZEOF(item::name)
	LDA #.LOWORD(TEMPORARY_TEXT_BUFFER)
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	STZ TEMPORARY_TEXT_BUFFER + 10
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA @VIRTUAL04
	LDX @VIRTUAL04
	LDA @LOCAL05
	STA @VIRTUAL02
	INC
	JSL CHECK_ITEM_EQUIPPED
	CMP #0
	BEQ @AFTER_ITEM_NAME
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL STRLEN
	TAX
@APPEND_EQUIP_MARKER:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$22
	STA TEMPORARY_TEXT_BUFFER,X
	STZ TEMPORARY_TEXT_BUFFER + 1,X
	BRA @AFTER_ITEM_NAME
@NO_ITEM_EQUIPPED:
	.A16
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_12, @LOCAL00
	LDX #4
	LDA #.LOWORD(TEMPORARY_TEXT_BUFFER)
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	STZ TEMPORARY_TEXT_BUFFER+4
@AFTER_ITEM_NAME:
	LDY @LOCAL04
	TYX
	REP #PROC_FLAGS::ACCUM8
	LDA #4
	JSR SET_FOCUS_TEXT_CURSOR
	LDA #CHAR::COLON
	JSR PRINT_LETTER
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #10
	JSR PRINT_STRING
	LDY @LOCAL04
	INY
	STY @LOCAL04
@EQUIP_SLOT_LOOP_CHECK:
	STY @VIRTUAL02
	LDA #PLAYER_CHAR_COUNT
	CLC
	SBC @VIRTUAL02
	JUMPGTS @PROCESS_EQUIP_SLOT
	JSR PRINT_MENU_ITEMS
	JSR CLEAR_INSTANT_PRINTING
	END_C_FUNCTION
