
DISPLAY_CHARACTER_EQUIPMENT_STATS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	TXY
	DEY
	STY @LOCAL03
	JSR SET_INSTANT_PRINTING
	CREATE_WINDOW_NEAR #WINDOW::EQUIPMENT_STATS
	LDA #2
	JSR SET_WINDOW_NUMBER_PADDING
	LDX #0
	LDA #1
	JSR SET_FOCUS_TEXT_CURSOR
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_8, @LOCAL00
	LDA #6
	JSR PRINT_STRING
	LDY @LOCAL03
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::base_offense,X
	AND #$00FF
	STA @LOCAL02
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::WEAPON,X
	AND #$00FF
	BEQ @AFTER_WEAPON_OFFENSE
	LDA #0
	STA @VIRTUAL02
	LDY @LOCAL03
	CPY #3
	BNE @POO_WEAPON_OFFSET
	LDA #1
	STA @VIRTUAL02
@POO_WEAPON_OFFSET:
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::WEAPON,X
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TXA
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL02
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL02
	STA @LOCAL02
@AFTER_WEAPON_OFFENSE:
	LDA @LOCAL02
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @OFFENSE_NOT_ZERO
	LDA #0
	BRA @PRINT_OFFENSE
@OFFENSE_NOT_ZERO:
	LDA @LOCAL02
	CLC
	SBC #$00FF
	BRANCHLTEQS @OFFENSE_IN_RANGE
	LDX #$00FF
	BRA @OFFENSE_CLAMPED
@OFFENSE_IN_RANGE:
	LDA @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
@OFFENSE_CLAMPED:
	TXA
@PRINT_OFFENSE:
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR PRINT_NUMBER
	LDX #1
	LDA #0
	JSR SET_FOCUS_TEXT_CURSOR
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_9, @LOCAL00
	LDA #7
	JSR PRINT_STRING
	LDY @LOCAL03
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::base_defense,X
	AND #$00FF
	STA @LOCAL02
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	BEQ @AFTER_BODY_DEFENSE
	LDA #0
	STA @VIRTUAL02
	LDY @LOCAL03
	CPY #3
	BNE @POO_BODY_OFFSET
	LDA #1
	STA @VIRTUAL02
@POO_BODY_OFFSET:
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TXA
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL02
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL02
	STA @LOCAL02
@AFTER_BODY_DEFENSE:
	LDY @LOCAL03
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::ARMS,X
	AND #$00FF
	BEQ @AFTER_ARMS_DEFENSE
	LDA #0
	STA @VIRTUAL02
	LDY @LOCAL03
	CPY #3
	BNE @POO_ARMS_OFFSET
	LDA #1
	STA @VIRTUAL02
@POO_ARMS_OFFSET:
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::ARMS,X
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TXA
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL02
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL02
	STA @LOCAL02
@AFTER_ARMS_DEFENSE:
	LDY @LOCAL03
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	BEQ @AFTER_OTHER_DEFENSE
	LDA #0
	STA @VIRTUAL02
	LDY @LOCAL03
	CPY #3
	BNE @POO_OTHER_OFFSET
	LDA #1
	STA @VIRTUAL02
@POO_OTHER_OFFSET:
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TXA
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL02
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL02
	STA @LOCAL02
@AFTER_OTHER_DEFENSE:
	LDA @LOCAL02
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @DEFENSE_NOT_ZERO
	LDA #0
	BRA @PRINT_DEFENSE
@DEFENSE_NOT_ZERO:
	LDA @LOCAL02
	CLC
	SBC #$00FF
	BRANCHLTEQS @DEFENSE_IN_RANGE
	LDX #$00FF
	BRA @DEFENSE_CLAMPED
@DEFENSE_IN_RANGE:
	LDA @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
@DEFENSE_CLAMPED:
	TXA
@PRINT_DEFENSE:
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR PRINT_NUMBER
	LDA COMPARE_EQUIPMENT_MODE
	BEQL @RETURN
	LDX #0
	LDA #10
	JSR SET_FOCUS_TEXT_CURSOR
	LDA #1
	JSR SET_WINDOW_PALETTE_INDEX
	LDA #$014E
	JSR PRINT_LETTER
	LDA #0
	JSR SET_WINDOW_PALETTE_INDEX
	LDY @LOCAL03
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::base_offense,X
	AND #$00FF
	STA @LOCAL02
	LDA TEMPORARY_WEAPON
	AND #$00FF
	BEQ @AFTER_PREVIEW_WEAPON
	LDX #0
	STX @LOCAL01
	LDY @LOCAL03
	CPY #3
	BNE @POO_PREVIEW_WEAPON_OFFSET
	LDX #1
	STX @LOCAL01
@POO_PREVIEW_WEAPON_OFFSET:
	LDA TEMPORARY_WEAPON
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	LDX @LOCAL01
	STX @VIRTUAL04
	CLC
	ADC @VIRTUAL04
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL02
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL02
	STA @LOCAL02
@AFTER_PREVIEW_WEAPON:
	LDA @LOCAL02
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @PREVIEW_OFF_NOT_ZERO
	LDA #0
	BRA @PRINT_PREVIEW_OFFENSE
@PREVIEW_OFF_NOT_ZERO:
	LDA @LOCAL02
	CLC
	SBC #$00FF
	BRANCHLTEQS @PREVIEW_OFF_IN_RANGE
	LDX #$00FF
	BRA @PREVIEW_OFF_CLAMPED
@PREVIEW_OFF_IN_RANGE:
	LDA @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
@PREVIEW_OFF_CLAMPED:
	TXA
@PRINT_PREVIEW_OFFENSE:
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR PRINT_NUMBER
	LDX #1
	LDA #10
	JSR SET_FOCUS_TEXT_CURSOR
	LDA #1
	JSR SET_WINDOW_PALETTE_INDEX
	LDA #$014E
	JSR PRINT_LETTER
	LDA #0
	JSR SET_WINDOW_PALETTE_INDEX
	LDY @LOCAL03
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::base_defense,X
	AND #$00FF
	STA @LOCAL02
	LDA TEMPORARY_BODY_GEAR
	AND #$00FF
	BEQ @AFTER_PREVIEW_BODY
	LDX #0
	STX @LOCAL01
	LDY @LOCAL03
	CPY #3
	BNE @POO_PREVIEW_BODY_OFFSET
	LDX #1
	STX @LOCAL01
@POO_PREVIEW_BODY_OFFSET:
	LDA TEMPORARY_BODY_GEAR
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	LDX @LOCAL01
	STX @VIRTUAL04
	CLC
	ADC @VIRTUAL04
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL02
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL02
	STA @LOCAL02
@AFTER_PREVIEW_BODY:
	LDA TEMPORARY_ARMS_GEAR
	AND #$00FF
	BEQ @AFTER_PREVIEW_ARMS
	LDX #0
	STX @LOCAL01
	LDY @LOCAL03
	CPY #3
	BNE @POO_PREVIEW_ARMS_OFFSET
	LDX #1
	STX @LOCAL01
@POO_PREVIEW_ARMS_OFFSET:
	LDA TEMPORARY_ARMS_GEAR
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	LDX @LOCAL01
	STX @VIRTUAL04
	CLC
	ADC @VIRTUAL04
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL02
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL02
	STA @LOCAL02
@AFTER_PREVIEW_ARMS:
	LDA TEMPORARY_OTHER_GEAR
	AND #$00FF
	BEQ @AFTER_PREVIEW_OTHER
	LDX #0
	STX @LOCAL01
	LDY @LOCAL03
	CPY #3
	BNE @POO_PREVIEW_OTHER_OFFSET
	LDX #1
	STX @LOCAL01
@POO_PREVIEW_OTHER_OFFSET:
	LDA TEMPORARY_OTHER_GEAR
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	LDX @LOCAL01
	STX @VIRTUAL04
	CLC
	ADC @VIRTUAL04
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL02
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL02
	STA @LOCAL02
@AFTER_PREVIEW_OTHER:
	LDA @LOCAL02
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @PREVIEW_DEF_NOT_ZERO
	LDA #0
	BRA @PRINT_PREVIEW_DEFENSE
@PREVIEW_DEF_NOT_ZERO:
	LDA @LOCAL02
	CLC
	SBC #$00FF
	BRANCHLTEQS @PREVIEW_DEF_IN_RANGE
	LDX #$00FF
	BRA @PREVIEW_DEF_CLAMPED
@PREVIEW_DEF_IN_RANGE:
	LDA @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
@PREVIEW_DEF_CLAMPED:
	TXA
@PRINT_PREVIEW_DEFENSE:
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR PRINT_NUMBER
@RETURN:
	JSR CLEAR_INSTANT_PRINTING
	END_C_FUNCTION
