
DISPLAY_EQUIPMENT_MENU:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	DEC
	STA @LOCAL05
	CREATE_WINDOW_NEAR #WINDOW::EQUIP_MENU
	JSL WINDOW_TICK_WITHOUT_INSTANT_PRINTING
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	CMP #1
	BEQ @AFTER_PAGINATION
	LDA #6
	STA PAGINATION_WINDOW
@AFTER_PAGINATION:
	LDA @LOCAL05
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #.SIZEOF(char_struct::name)
	LDA #6
	JSL SET_WINDOW_TITLE
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL04
	JMP @EQUIP_SLOT_LOOP_CHECK
@PROCESS_EQUIP_SLOT:
	LDA #1
	STA FORCE_LEFT_TEXT_ALIGNMENT
	LDA @VIRTUAL02
	BEQ @SLOT_WEAPON
	CMP #1
	BEQ @SLOT_BODY
	CMP #2
	BEQL @SLOT_ARMS
	CMP #3
	BEQL @SLOT_OTHER
	JMP @AFTER_SLOT_LOAD
@SLOT_WEAPON:
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_10, @VIRTUAL06
	LDA @VIRTUAL02
	OPTIMIZED_MULT @VIRTUAL04, 11
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDX @VIRTUAL02
	LDA #0
	JSR ADD_POSITIONED_MENU_OPTION
	LDA @LOCAL05
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::WEAPON,X
	AND #$00FF
	STA @VIRTUAL04
	STA @LOCAL03
	JMP @AFTER_SLOT_LOAD
@SLOT_BODY:
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_10, @VIRTUAL06
	LDA @VIRTUAL02
	OPTIMIZED_MULT @VIRTUAL04, 11
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDX @VIRTUAL02
	LDA #0
	JSR ADD_POSITIONED_MENU_OPTION
	LDA @LOCAL05
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	STA @VIRTUAL04
	STA @LOCAL03
	JMP @AFTER_SLOT_LOAD
@SLOT_ARMS:
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_10, @VIRTUAL06
	LDA @VIRTUAL02
	OPTIMIZED_MULT @VIRTUAL04, 11
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDX @VIRTUAL02
	LDA #0
	JSR ADD_POSITIONED_MENU_OPTION
	LDA @LOCAL05
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::ARMS,X
	AND #$00FF
	STA @VIRTUAL04
	STA @LOCAL03
	BRA @AFTER_SLOT_LOAD
@SLOT_OTHER:
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_10, @VIRTUAL06
	LDA @VIRTUAL02
	OPTIMIZED_MULT @VIRTUAL04, 11
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDX @VIRTUAL02
	LDA #0
	JSR ADD_POSITIONED_MENU_OPTION
	LDA @LOCAL05
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	STA @VIRTUAL04
	STA @LOCAL03
@AFTER_SLOT_LOAD:
	LDA @LOCAL03
	STA @VIRTUAL04
	BEQL @NO_ITEM_EQUIPPED
	LDA @VIRTUAL04
	DEC
	STA @VIRTUAL02
	LDA @LOCAL05
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	TAY
	STY @LOCAL02
	LDX @VIRTUAL04
	LDA @LOCAL05
	INC
	JSL CHECK_ITEM_EQUIPPED
	CMP #0
	BEQ @NOT_EQUIPPED
	SEP #PROC_FLAGS::ACCUM8
	LDA #34
	STA TEMPORARY_TEXT_BUFFER
	REP #PROC_FLAGS::ACCUM8
	LOADPTR ITEM_CONFIGURATION_TABLE, @VIRTUAL06
	LDY @LOCAL02
	TYA
	LDY #.SIZEOF(item)
	JSL MULT168
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX #.SIZEOF(item::name)
	LDA #.LOWORD(TEMPORARY_TEXT_BUFFER)+1
	JSL MEMCPY16
	BRA @AFTER_EQUIP_MARKER
@NOT_EQUIPPED:
	LOADPTR ITEM_CONFIGURATION_TABLE, @VIRTUAL06
	LDY @LOCAL02
	TYA
	LDY #.SIZEOF(item)
	JSL MULT168
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX #.SIZEOF(item::name)
	LDA #.LOWORD(TEMPORARY_TEXT_BUFFER)
	JSL MEMCPY16
@AFTER_EQUIP_MARKER:
	SEP #PROC_FLAGS::ACCUM8
	STZ TEMPORARY_TEXT_BUFFER+.SIZEOF(item::name)
	BRA @AFTER_ITEM_NAME
@NO_ITEM_EQUIPPED:
	.A16
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_12, @LOCAL00
	LDX #10
	LDA #.LOWORD(TEMPORARY_TEXT_BUFFER)
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	STZ TEMPORARY_TEXT_BUFFER+10
@AFTER_ITEM_NAME:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL04
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA #6
	JSL SET_FOCUS_TEXT_CURSOR
	LDA #CHAR::COLON
	JSR PRINT_LETTER
	LDA #CHAR::SPACE
	JSR PRINT_LETTER
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #49
	JSR PRINT_STRING
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL04
@EQUIP_SLOT_LOOP_CHECK:
	LDA #PLAYER_CHAR_COUNT
	CLC
	SBC @VIRTUAL02
	JUMPGTS @PROCESS_EQUIP_SLOT
	JSR PRINT_MENU_ITEMS
	STZ FORCE_LEFT_TEXT_ALIGNMENT
	JSL CLEAR_INSTANT_PRINTING
	END_C_FUNCTION
