
EQUIPMENT_CHANGE_MENU:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	DEC
	STA @LOCAL07
	LDA #1
	STA @LOCAL06
@SELECT_SLOT_TYPE:
	LDA #4
	JSR DISPLAY_MENU_HEADER_TEXT
	LDA #6
	JSR SET_WINDOW_FOCUS
	LDA @LOCAL06
	DEC
	JSR PRINT_MENU_AT_SELECTION
	LDA #1
	JSR SELECTION_MENU
	STA @LOCAL06
	JSR CLOSE_MENU_HEADER_WINDOW
	LDA @LOCAL06
	BEQL @RETURN
	CREATE_WINDOW_NEAR #WINDOW::EQUIP_MENU_ITEMLIST
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_11, @VIRTUAL06
	LDA @LOCAL06
	DEC
	ASL
	ASL
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX #4
	LDA #7
	JSL SET_WINDOW_TITLE
	LDA #0
	STA @VIRTUAL04
	STA @LOCAL05
	LDA #.LOWORD(-1)
	STA @LOCAL04
	LDA #0
	STA @VIRTUAL02
	JMP @ITEM_LOOP_CHECK
@CHECK_ITEM:
	LDA @LOCAL07
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	STA @LOCAL03
	BEQL @NEXT_ITEM
	LDA @LOCAL03
	JSR GET_ITEM_TYPE
	CMP #2
	BNEL @NEXT_ITEM
	LDA @LOCAL03
	JSL GET_ITEM_SUBTYPE
	CMP @LOCAL06
	BNEL @NEXT_ITEM
	LDY @LOCAL07
	INY
	STY @LOCAL02
	LDX @LOCAL03
	TYA
	JSL CHECK_ITEM_USABLE_BY
	CMP #0
	BEQL @NEXT_ITEM
	LOADPTR ITEM_CONFIGURATION_TABLE, @VIRTUAL06
	LDA @LOCAL03
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX #.SIZEOF(item::name)
	LDA #.LOWORD(TEMPORARY_TEXT_BUFFER)
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	STZ TEMPORARY_TEXT_BUFFER+.SIZEOF(item::name)
	LDX @VIRTUAL02
	INX
	LDY @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	TYA
	JSL CHECK_ITEM_EQUIPPED
	CMP #0
	BEQ @ADD_ITEM_ENTRY
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL STRLEN
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #34
	STA TEMPORARY_TEXT_BUFFER,X
	STZ TEMPORARY_TEXT_BUFFER+1,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL05
	STA @VIRTUAL04
	STA @LOCAL04
@ADD_ITEM_ENTRY:
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDA @VIRTUAL02
	INC
	JSR ADD_MENU_ITEM_NO_POSITION
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #115
	STA __BSS_START__+14,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL05
	STA @VIRTUAL04
	INC @VIRTUAL04
	LDA @VIRTUAL04
	STA @LOCAL05
@NEXT_ITEM:
	INC @VIRTUAL02
@ITEM_LOOP_CHECK:
	LDA @VIRTUAL02
	CMP #14
	BCCL @CHECK_ITEM
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_13, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDA #.LOWORD(-1)
	JSR ADD_MENU_ITEM_NO_POSITION
	LDY @LOCAL04
	LDX #0
	LDA #1
	JSR LAYOUT_AND_PRINT_MENU_AT_SELECTION
	LDA @LOCAL07
	SEP #PROC_FLAGS::ACCUM8
	INC
	STA CHARACTER_FOR_EQUIP_MENU
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL06
	CMP #1
	BEQ @SET_WEAPON_CALLBACK
	CMP #2
	BEQ @SET_BODY_CALLBACK
	CMP #3
	BEQ @SET_ARMS_CALLBACK
	CMP #4
	BEQ @SET_OTHER_CALLBACK
	BRA @AFTER_CALLBACK
@SET_WEAPON_CALLBACK:
	LOADPTR PREVIEW_WEAPON_EQUIP_STATS, @LOCAL00
	JSR SET_CURSOR_MOVE_CALLBACK
	BRA @AFTER_CALLBACK
@SET_BODY_CALLBACK:
	LOADPTR PREVIEW_BODY_EQUIP_STATS, @LOCAL00
	JSR SET_CURSOR_MOVE_CALLBACK
	BRA @AFTER_CALLBACK
@SET_ARMS_CALLBACK:
	LOADPTR PREVIEW_ARMS_EQUIP_STATS, @LOCAL00
	JSR SET_CURSOR_MOVE_CALLBACK
	BRA @AFTER_CALLBACK
@SET_OTHER_CALLBACK:
	LOADPTR PREVIEW_OTHER_EQUIP_STATS, @LOCAL00
	JSR SET_CURSOR_MOVE_CALLBACK
@AFTER_CALLBACK:
	LDA #1
	STA COMPARE_EQUIPMENT_MODE
	JSR DISPLAY_MENU_HEADER_TEXT
	LDA #1
	JSR SELECTION_MENU
	TAX
	STX @LOCAL04
	JSR CLOSE_MENU_HEADER_WINDOW
	JSR CLEAR_CURSOR_MOVE_CALLBACK
	LDX @LOCAL04
	CPX #.LOWORD(-1)
	BNE @EQUIP_SELECTED
	LDA @LOCAL06
	CMP #1
	BEQ @UNEQUIP_WEAPON
	CMP #2
	BEQ @UNEQUIP_BODY
	CMP #3
	BEQ @UNEQUIP_ARMS
	CMP #4
	BEQ @UNEQUIP_OTHER
	BRA @CLOSE_AND_REFRESH
@UNEQUIP_WEAPON:
	LDX #0
	LDA @LOCAL07
	INC
	JSL CHANGE_EQUIPPED_WEAPON
	BRA @CLOSE_AND_REFRESH
@UNEQUIP_BODY:
	LDX #0
	LDA @LOCAL07
	INC
	JSL CHANGE_EQUIPPED_BODY
	BRA @CLOSE_AND_REFRESH
@UNEQUIP_ARMS:
	LDX #0
	LDA @LOCAL07
	INC
	JSL CHANGE_EQUIPPED_ARMS
	BRA @CLOSE_AND_REFRESH
@UNEQUIP_OTHER:
	LDX #0
	LDA @LOCAL07
	INC
	JSL CHANGE_EQUIPPED_OTHER
	BRA @CLOSE_AND_REFRESH
@EQUIP_SELECTED:
	CPX #0
	BEQ @CLOSE_AND_REFRESH
	LDA @LOCAL07
	INC
	JSR EQUIP_ITEM
@CLOSE_AND_REFRESH:
	LDA #WINDOW::EQUIP_MENU_ITEMLIST
	JSR CLOSE_WINDOW
	LDA @LOCAL07
	INC
	JSL SHOW_EQUIPMENT_AND_STATS
	JMP @SELECT_SLOT_TYPE
@RETURN:
	END_C_FUNCTION
