
OPEN_EQUIPMENT_MENU:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
	JSL SAVE_WINDOW_TEXT_ATTRIBUTES
	LDA GAME_STATE + game_state::party_members
	AND #$00FF
	TAX
	STX @LOCAL02
@SHOW_EQUIPMENT:
	LDX @LOCAL02
	TXA
	JSL SHOW_EQUIPMENT_AND_STATS
	LDA GAME_STATE + game_state::player_controlled_party_count
	AND #$00FF
	CMP #1
	BEQ @SINGLE_MEMBER
	LDA #0
	JSR DISPLAY_MENU_HEADER_TEXT
	LOADPTR SHOW_EQUIPMENT_AND_STATS, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDX #1
	LDA #0
	JSR CHAR_SELECT_PROMPT
	TAX
	STX @LOCAL02
	JSR CLOSE_MENU_HEADER_WINDOW
	BRA @CHECK_RESULT
@SINGLE_MEMBER:
	LDA GAME_STATE + game_state::party_members
	AND #$00FF
	TAX
	STX @LOCAL02
	LDA #0
	JSR SELECT_BATTLE_MENU_CHARACTER
@CHECK_RESULT:
	LDX @LOCAL02
	BEQ @CLOSE_WINDOWS
	TXA
	JSR EQUIPMENT_CHANGE_MENU
	LDA GAME_STATE + game_state::player_controlled_party_count
	AND #$00FF
	CMP #1
	BNE @SHOW_EQUIPMENT
@CLOSE_WINDOWS:
	LDA #WINDOW::EQUIPMENT_STATS
	JSR CLOSE_WINDOW
	LDA #WINDOW::EQUIP_MENU
	JSR CLOSE_WINDOW
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
	JSL RESTORE_WINDOW_TEXT_ATTRIBUTES
	LDX @LOCAL02
	TXA
	END_C_FUNCTION
