
BTLACT_BASH:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LDA #0
	JSR MISS_CALC
	CMP #0
	BNE @DONE
	JSR SMAAAASH
	CMP #0
	BNE @DONE
	JSR DETERMINE_DODGE
	CMP #0
	BNE @DODGED
	JSR BTLACT_LEVEL_2_ATK
	JSR HEAL_STRANGENESS
	BRA @DONE
@DODGED:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_TATAKU_YOKETA
@DONE:
	END_C_FUNCTION
