
BOMB_COMMON:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int
	END_STACK_VARS
	STA @LOCAL06
	STZ @LOCAL05
	LDA #0
	STA @VIRTUAL04
	LDA @LOCAL06
	JSR FIFTY_PERCENT_VARIANCE
	LDX #$00FF
	JSR CALC_RESIST_DAMAGE
	LDX CURRENT_TARGET
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
.IF .DEFINED(JPN)
	BNEL @ENEMY_PATH
	LDA #0
	STA @LOCAL04
.ELSE
	BNE @ENEMY_PATH
	LDX #0
	STX @LOCAL04
.ENDIF
	BRA @FIND_SLOT_CHECK
@FIND_SLOT_BODY:
	LDX CURRENT_TARGET
	LDA __BSS_START__,X
	STA @VIRTUAL02
.IF .DEFINED(JPN)
	LDA @LOCAL04
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
.ELSE
	LDX @LOCAL04
	LDA GAME_STATE + game_state::party_members,X
.ENDIF
	AND #$00FF
	CMP @VIRTUAL02
	BEQ @FOUND_SLOT
.IF .DEFINED(JPN)
	LDA @LOCAL04
	INC
	STA @LOCAL04
.ELSE
	INX
	STX @LOCAL04
.ENDIF
@FIND_SLOT_CHECK:
.IF .DEFINED(JPN)
	CMP #6
	BCC @FIND_SLOT_BODY
.ELSE
	CPX #6
	BCC @FIND_SLOT_BODY
.ENDIF
@FOUND_SLOT:
.IF .DEFINED(JPN)
	LDA @LOCAL04
.ELSE
	CPX #0
.ENDIF
	BEQ @CHECK_RIGHT_NEIGHBOR
.IF .DEFINED(JPN)
	DEC
.ELSE
	TXA
	DEC
.ENDIF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(battler)
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	STA @VIRTUAL04
@CHECK_RIGHT_NEIGHBOR:
.IF .DEFINED(JPN)
	LDA @LOCAL04
	TAX
.ENDIF
	LDA GAME_STATE + game_state::party_members + 1,X
	AND #$00FF
.IF .DEFINED(JPN)
	TAX
	STX @VIRTUAL02
.ELSE
	STA @LOCAL03
	STA @VIRTUAL02
.ENDIF
	LDA #1
	CLC
	SBC @VIRTUAL02
	JUMPGTS @APPLY_SPLASH
.IF .DEFINED(JPN)
	TXA
.ELSE
	LDA @LOCAL03
.ENDIF
	CLC
	SBC #4
	JUMPGTS @APPLY_SPLASH
.IF .DEFINED(JPN)
	LDA @LOCAL04
.ELSE
	TXA
.ENDIF
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE) + .SIZEOF(battler)
	STA @LOCAL05
	JMP @APPLY_SPLASH
@ENEMY_PATH:
	LDA #8
	STA @VIRTUAL02
	STA @LOCAL03
	JMP @ENEMY_LOOP_CHECK
@ENEMY_LOOP_BODY:
	LDA @VIRTUAL02
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	STX @LOCAL02
	TXA
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	TAY
	STY @LOCAL01
	CPY CURRENT_TARGET
	BEQL @ENEMY_NEXT
	LDA BATTLERS_TABLE+battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BNEL @ENEMY_NEXT
	SEP #PROC_FLAGS::ACCUM8
	LDA BATTLERS_TABLE + battler::row,X
	LDX CURRENT_TARGET
	CMP a:battler::row,X
	BNEL @ENEMY_NEXT
	LDX @LOCAL02
	LDA BATTLERS_TABLE+battler::sprite_x,X
	STA @VIRTUAL01
	LDX CURRENT_TARGET
	LDA a:battler::sprite_x,X
	STA @VIRTUAL00
	LDA @VIRTUAL01
	CMP @VIRTUAL00
	BCS @NEIGHBOR_RIGHT
	LDX CURRENT_TARGET
	REP #PROC_FLAGS::ACCUM8
	LDA a:battler::sprite,X
	JSR GET_BATTLE_SPRITE_WIDTH
	STA @LOCAL00
	LDX @LOCAL02
	LDA BATTLERS_TABLE+battler::sprite,X
	JSR GET_BATTLE_SPRITE_WIDTH
	CLC
	ADC @LOCAL00
	ASL
	ASL
	CLC
	ADC #8
	STA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	SEC
	SBC @VIRTUAL01
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	CMP @VIRTUAL02
	BGT @ENEMY_NEXT
	LDY @LOCAL01
	STY @VIRTUAL04
	BRA @ENEMY_NEXT
@NEIGHBOR_RIGHT:
	LDX CURRENT_TARGET
	REP #PROC_FLAGS::ACCUM8
	LDA a:battler::sprite,X
	JSR GET_BATTLE_SPRITE_WIDTH
	STA @LOCAL00
	LDX @LOCAL02
	LDA BATTLERS_TABLE+battler::sprite,X
	JSR GET_BATTLE_SPRITE_WIDTH
	CLC
	ADC @LOCAL00
	ASL
	ASL
	CLC
	ADC #8
	STA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL01
	SEC
	SBC @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	CMP @VIRTUAL02
	BGT @ENEMY_NEXT
	LDY @LOCAL01
	STY @LOCAL05
@ENEMY_NEXT:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL03
@ENEMY_LOOP_CHECK:
	LDA @VIRTUAL02
	CMP #BATTLER_COUNT
	BCCL @ENEMY_LOOP_BODY
@APPLY_SPLASH:
	LDY CURRENT_TARGET
	STY @LOCAL03
	LDA @VIRTUAL04
	BEQ @CHECK_RIGHT_SPLASH
	LDA @VIRTUAL04
	STA CURRENT_TARGET
	JSL FIX_TARGET_NAME
	LDA @LOCAL06
	LSR
	JSR FIFTY_PERCENT_VARIANCE
	LDX #$00FF
	JSR CALC_RESIST_DAMAGE
@CHECK_RIGHT_SPLASH:
	LDA @LOCAL05
	BEQ @RESTORE_TARGET
	LDA @LOCAL05
	STA CURRENT_TARGET
	JSL FIX_TARGET_NAME
	LDA @LOCAL06
	LSR
	JSR FIFTY_PERCENT_VARIANCE
	LDX #$00FF
	JSR CALC_RESIST_DAMAGE
@RESTORE_TARGET:
	LDY @LOCAL03
	STY CURRENT_TARGET
	JSL FIX_TARGET_NAME
	END_C_FUNCTION
