
BOTTLE_ROCKET_COMMON:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int
	END_STACK_VARS
	STA @VIRTUAL02
	LDY #0
	STY @LOCAL02
	TYX
	STX @LOCAL01
	BRA @LOOP_CHECK
@CHECK_HIT:
	LDA #100
	JSR SUCCESS_SPEED
	CMP #0
	BEQ @NEXT_TARGET
	LDY @LOCAL02
	INY
	STY @LOCAL02
@NEXT_TARGET:
	LDX @LOCAL01
	INX
	STX @LOCAL01
@LOOP_CHECK:
	TXA
	CMP @VIRTUAL02
	BCC @CHECK_HIT
	LDY @LOCAL02
	BEQ @ALL_MISSED
	TYA
	LDY #120
	JSL MULT168
	JSR TWENTY_FIVE_PERCENT_VARIANCE
	LDX #$00FF
	JSR CALC_RESIST_DAMAGE
	BRA @DONE
@ALL_MISSED:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
@DONE:
	END_C_FUNCTION
