
BTLACT_DISTRACT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	JSR FAIL_ATTACK_ON_NPCS
	CMP #0
	BNE @DONE
	JSR SUCCESS_LUCK40
	CMP #0
	BEQ @NO_EFFECT
	LDX CURRENT_TARGET
	SEP #PROC_FLAGS::ACCUM8
	LDA a:battler::paralysis_resist,X
	JSR SUCCESS_255
	.A16
	CMP #0
	BEQ @NO_EFFECT
	LDA CURRENT_TARGET
	CLC
	ADC #battler::afflictions + STATUS_GROUP::CONCENTRATION
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	BNE @NO_EFFECT
	SEP #PROC_FLAGS::ACCUM8
	LDA #STATUS_4::CANT_CONCENTRATE4
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_FUUIN_ON
	BRA @DONE
@NO_EFFECT:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
@DONE:
	END_C_FUNCTION
