
BTLACT_GIYGAS_PRAYER_9:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	JSL RESET_HPPP_ROLLING
	LOADPTR MSG_BTL_INORU_BACK_TO_PC_9, @LOCAL00
	LDA #MUSIC::GIYGAS_WEAKENED2
	JSR PLAY_GIYGAS_WEAKENED_SEQUENCE
	LDA #GIYGAS_PRAYER_DAMAGE_7
	JSR GIYGAS_HURT_PRAYER
	LOADPTR MSG_BTL_INORU_BACK_TO_PC_F_1, @LOCAL00
	LDA #MUSIC::GIYGAS_WEAKENED2
	JSR PLAY_GIYGAS_WEAKENED_SEQUENCE
	LDA #GIYGAS_PRAYER_DAMAGE_8
	JSR GIYGAS_HURT_PRAYER
	LOADPTR MSG_BTL_INORU_BACK_TO_PC_F_2, @LOCAL00
	LDA #MUSIC::GIYGAS_WEAKENED2
	JSR PLAY_GIYGAS_WEAKENED_SEQUENCE
	LDA #GIYGAS_PRAYER_DAMAGE_9
	JSR GIYGAS_HURT_PRAYER
	LOADPTR MSG_BTL_INORU_BACK_TO_PC_F_3, @LOCAL00
	LDA #MUSIC::GIYGAS_WEAKENED2
	JSR PLAY_GIYGAS_WEAKENED_SEQUENCE
	LDA #GIYGAS_PRAYER_DAMAGE_10
	JSR GIYGAS_HURT_PRAYER
	JSL REDIRECT_CLOSE_FOCUS_WINDOW
	STZ BATTLE_MODE_FLAG
	JSL REDIRECT_HIDE_HPPP_WINDOWS
	LDA #1
	STA BATTLE_MODE_FLAG
	JSL WINDOW_TICK
	LDA #GIYGAS_PHASES::DEFEATED
	STA GIYGAS_PHASE
	LDA #MUSIC::GIYGAS_DEATH
	JSL CHANGE_MUSIC
	LDY #0
	STY @LOCAL04
@PRAYER_NOISE_LOOP:
	LOADPTR FINAL_GIYGAS_PRAYER_NOISE_TABLE, @VIRTUAL06
	LDY @LOCAL04
	TYA
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	TAX
	INY
	STY @LOCAL04
	TXA
	JSL PLAY_SOUND
	LDY @LOCAL04
	TYA
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	TAX
	BEQ @PRAYER_NOISE_DONE
	INY
	STY @LOCAL04
	TXA
	JSR WAIT
	BRA @PRAYER_NOISE_LOOP
@PRAYER_NOISE_DONE:
	LDA #MUSIC::GIYGAS_DEATH2
	JSL CHANGE_MUSIC
	STZ GIYGAS_PHASE
	LDA #8*SECONDS
	JSR WAIT
	LDX #.LOWORD(BATTLERS_TABLE) + 9 * .SIZEOF(battler) + battler::consciousness
	STX @LOCAL03
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA __BSS_START__,X
	JSL RENDER_ALL_BATTLE_SPRITES
	.A16
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_POKEY_RUN_AWAY
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	LDX @LOCAL03
	STA __BSS_START__,X
	JSL RENDER_ALL_BATTLE_SPRITES
	.A16
	LDA #1*SECOND
	JSR WAIT
	.A16
	LDY #2
	STY @LOCAL02
	TYA
	STA @VIRTUAL04
	LDA #45
	STA @VIRTUAL02
	LDA #1*SECOND
	STA VERTICAL_SHAKE_DURATION
	LDX #0
	STX @LOCAL01
	BRA @STATIC_TRANSITION_CHECK
@STATIC_TRANSITION_BODY:
	.A16
	LDA #0
	STA @LOCAL04
	BRA @FRAME_DELAY_CHECK
@DELAY_TICK:
	JSL WINDOW_TICK
	.A16
	LDA @VIRTUAL04
	BEQ @NEXT_FRAME
	LDA @VIRTUAL02
	DEC
	STA @VIRTUAL02
	BNE @NEXT_FRAME
	LDA @VIRTUAL04
	DEC
	STA @VIRTUAL04
	LDA #45
	STA @VIRTUAL02
	LDA #1*SECOND
	STA VERTICAL_SHAKE_DURATION
@NEXT_FRAME:
	LDA @LOCAL04
	INC
	STA @LOCAL04
@FRAME_DELAY_CHECK:
	LDX @LOCAL01
	TXA
	ASL
	TAX
	LDA @LOCAL04
	CMP f:GIYGAS_DEATH_STATIC_TRANSITION_DELAYS,X
	BCC @DELAY_TICK
	JSL ROTATE_BG_DISTORTION
	LDY @LOCAL02
	TYA
	JSL WRITE_APU_PORT2
	LDY @LOCAL02
	CPY #2
	BNE @SET_TOGGLE_2
	LDY #1
	STY @LOCAL02
	BRA @NEXT_STATIC_TRANSITION
@SET_TOGGLE_2:
	LDY #2
	STY @LOCAL02
@NEXT_STATIC_TRANSITION:
	LDX @LOCAL01
	INX
	STX @LOCAL01
@STATIC_TRANSITION_CHECK:
	TXA
	ASL
	TAX
	LDA f:GIYGAS_DEATH_STATIC_TRANSITION_DELAYS,X
	BNE @STATIC_TRANSITION_BODY
	LDA #MUSIC::GIYGAS_STATIC
	JSL CHANGE_MUSIC
	.A16
	LDA #10*SECONDS
	JSR WAIT
	LDA #SFX::PSI_THUNDER_DAMAGE
	JSL PLAY_SOUND
	JSL STOP_MUSIC
	LDY #5
	LDX #0
	TYA
	JSL START_BATTLE_SWIRL
	BRA @SWIRL_CHECK
@SWIRL_TICK:
	JSL WINDOW_TICK
@SWIRL_CHECK:
	JSL IS_BATTLE_SWIRL_ACTIVE
	CMP #0
	BNE @SWIRL_TICK
	JSL STOP_MUSIC
	LDX #MUSIC::NONE
	LDA #ENEMY_GROUP::BOSS_GIYGAS_PHASE_FINAL
	JSR LOAD_BATTLE_SCENE
	LDA #8*SECONDS
	JSR WAIT
	LDA #3
	STA SPECIAL_DEFEAT
	END_C_FUNCTION
