
BTLACT_HEALING_A:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LDA CURRENT_TARGET
	CLC
	ADC #battler::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	CMP #STATUS_0::COLD
	BEQ @CURE_COLD
	CMP #STATUS_0::SUNSTROKE
	BEQ @CURE_SUNSTROKE
	BRA @CHECK_TEMPORARY
@CURE_COLD:
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KAZE_OFF
	BRA @DONE
@CURE_SUNSTROKE:
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_NISSYA_OFF
	BRA @DONE
@CHECK_TEMPORARY:
	LDA CURRENT_TARGET
	CLC
	ADC #battler::afflictions + STATUS_GROUP::TEMPORARY
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	CMP #STATUS_2::ASLEEP
	BNE @NO_EFFECT
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_NEMURI_OFF
	BRA @DONE
@NO_EFFECT:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_HEAL_NG
@DONE:
	END_C_FUNCTION
