
BTLACT_HEALING_O:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	LDX CURRENT_TARGET
	LDA a:battler::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BNE @NOT_UNCONSCIOUS
	LDX CURRENT_TARGET
	LDA a:battler::hp_max,X
	TAX
	LDA CURRENT_TARGET
	JSR REVIVE_TARGET
	BRA @DONE
@NOT_UNCONSCIOUS:
	JSL BTLACT_HEALING_G
@DONE:
	END_C_FUNCTION
