
BTLACT_HEALING_G:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LDA CURRENT_TARGET
	CLC
	ADC #battler::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	CMP #STATUS_0::PARALYZED
	BEQ @CURE_PARALYSIS
	CMP #STATUS_0::DIAMONDIZED
	BEQ @CURE_DIAMONDIZE
	CMP #STATUS_0::UNCONSCIOUS
	BEQ @REVIVE_UNCONSCIOUS
	BRA @FALLBACK_HEALING_B
@CURE_PARALYSIS:
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_SHIBIRE_OFF
	BRA @DONE
@CURE_DIAMONDIZE:
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_DAIYA_OFF
	BRA @DONE
@REVIVE_UNCONSCIOUS:
	SEP #PROC_FLAGS::ACCUM8
	LDA #192
	JSR SUCCESS_255
	.A16
	CMP #0
	BEQ @REVIVE_FAILED
	LDX CURRENT_TARGET
	LDA a:battler::hp_max,X
	LSR
	LSR
	TAX
	LDA CURRENT_TARGET
	JSR REVIVE_TARGET
	BRA @DONE
@REVIVE_FAILED:
	.A16
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_IKIKAERI_F
	BRA @DONE
@FALLBACK_HEALING_B:
	JSL BTLACT_HEALING_B
@DONE:
	END_C_FUNCTION
