
BTLACT_HEALING_B:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LDA CURRENT_TARGET
	CLC
	ADC #battler::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	CMP #STATUS_0::POISONED
	BEQ @CURE_POISON
	CMP #STATUS_0::NAUSEOUS
	BEQ @CURE_NAUSEA
	BRA @CHECK_TEMPORARY
@CURE_POISON:
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_MODOKU_OFF
	BRA @DONE
@CURE_NAUSEA:
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIMOCHI_OFF
	BRA @DONE
@CHECK_TEMPORARY:
	LDA CURRENT_TARGET
	CLC
	ADC #battler::afflictions + STATUS_GROUP::TEMPORARY
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	CMP #STATUS_2::CRYING
	BNE @CHECK_STRANGENESS
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_NAMIDA_OFF
	BRA @DONE
@CHECK_STRANGENESS:
	LDA CURRENT_TARGET
	CLC
	ADC #battler::afflictions + STATUS_GROUP::STRANGENESS
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	CMP #STATUS_3::STRANGE
	BNE @FALLBACK_HEALING_A
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_HEN_OFF
	BRA @DONE
@FALLBACK_HEALING_A:
	JSL BTLACT_HEALING_A
@DONE:
	END_C_FUNCTION
