
BTLACT_HP_RECOVERY_10000:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	LDX CURRENT_TARGET
	LDA a:battler::id,X
	CMP #PARTY_MEMBER::POO
	BNE @NOT_POO
	LDX #10000
	LDA CURRENT_TARGET
	JSR RECOVER_HP
	BRA @DONE
@NOT_POO:
	JSL BTLACT_HP_RECOVERY_1D4
@DONE:
	END_C_FUNCTION
