
BTLACT_HP_SUCKER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	JSR SUCCESS_LUCK80
	CMP #0
	BEQL @NO_EFFECT
	LDX CURRENT_ATTACKER
	LDA a:battler::hp_target,X
	BEQ @NO_EFFECT
	LDA CURRENT_TARGET
	CMP CURRENT_ATTACKER
	BNE @DRAIN_TARGET
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_HPSUCK_ME
	BRA @DONE
@DRAIN_TARGET:
	LDX CURRENT_TARGET
	LDA a:battler::hp_max,X
	JSR FIFTY_PERCENT_VARIANCE
	LSR
	LSR
	LSR
	TAY
	STY @LOCAL02
	TYX
	LDA CURRENT_TARGET
	JSR REDUCE_HP
	LOADPTR MSG_BTL_HPSUCK_ON, @LOCAL00
	LDY @LOCAL02
	TYA
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	LDX CURRENT_ATTACKER
	LDY @LOCAL02
	TYA
	CLC
	ADC a:battler::hp,X
	TAX
	LDA CURRENT_ATTACKER
	JSR SET_HP
	LDX CURRENT_TARGET
	LDA a:battler::hp,X
	BNE @DONE
	LDA CURRENT_TARGET
	JSL KO_TARGET
	BRA @DONE
@NO_EFFECT:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
@DONE:
	END_C_FUNCTION
