
BTLACT_HYPNOSIS_A:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	JSR FAIL_ATTACK_ON_NPCS
	CMP #0
	BNE @DONE
	LDX CURRENT_TARGET
	SEP #PROC_FLAGS::ACCUM8
	LDA a:battler::hypnosis_resist,X
	JSR SUCCESS_255
	.A16
	CMP #0
	BEQ @NO_EFFECT
	LDY #STATUS_2::ASLEEP
	LDX #STATUS_GROUP::TEMPORARY
	LDA CURRENT_TARGET
	JSR INFLICT_STATUS_BATTLE
	.A16
	CMP #0
	BEQ @NO_EFFECT
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_NEMURI_ON
	BRA @DONE
@NO_EFFECT:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
@DONE:
	END_C_FUNCTION
