
BTLACT_LEVEL_4_ATK:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #0
	JSR MISS_CALC
	CMP #0
	BNE @DONE
	JSR SMAAAASH
	CMP #0
	BNE @DONE
	JSR DETERMINE_DODGE
	CMP #0
	BNE @DODGED
	LDX CURRENT_ATTACKER
	LDA a:battler::offense,X
	OPTIMIZED_MULT @VIRTUAL04, 4
	LDX CURRENT_TARGET
	SEC
	SBC a:battler::defense,X
	STA @LOCAL01
	CLC
	SBC #0
	BRANCHLTEQS @APPLY_VARIANCE
	LDA @LOCAL01
	JSR TWENTY_FIVE_PERCENT_VARIANCE
	STA @LOCAL01
@APPLY_VARIANCE:
	LDA @LOCAL01
	CLC
	SBC #0
	BRANCHGTS @APPLY_DAMAGE
	LDA #1
	STA @LOCAL01
@APPLY_DAMAGE:
	LDX #$00FF
	LDA @LOCAL01
	JSR CALC_RESIST_DAMAGE
	JSR HEAL_STRANGENESS
	BRA @DONE
@DODGED:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_TATAKU_YOKETA
@DONE:
	END_C_FUNCTION
