
BTLACT_LEVEL_2_ATK_POISON:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	JSR FAIL_ATTACK_ON_NPCS
	CMP #0
	BNE @DONE
	LDA #0
	JSR MISS_CALC
	CMP #0
	BNE @DONE
	JSR SMAAAASH
	CMP #0
	BNE @DONE
	JSR DETERMINE_DODGE
	CMP #0
	BNE @DODGED
	JSR BTLACT_LEVEL_2_ATK
	JSR HEAL_STRANGENESS
	LDY #STATUS_0::POISONED
	LDX #STATUS_GROUP::PERSISTENT_EASYHEAL
	LDA CURRENT_TARGET
	JSR INFLICT_STATUS_BATTLE
	CMP #0
	BEQ @DONE
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_MODOKU_ON
	BRA @DONE
@DODGED:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_TATAKU_YOKETA
@DONE:
	END_C_FUNCTION
