
BTLACT_MAGNET_O:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	LDX CURRENT_TARGET
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @DO_MAGNET
	LDX CURRENT_TARGET
	LDA a:battler::id,X
	CMP #PARTY_MEMBER::JEFF
	BEQ @DONE
@DO_MAGNET:
	JSL BTLACT_MAGNET_A
@DONE:
	END_C_FUNCTION
