
BTLACT_MASTERBARFDEATH:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CURRENT_ATTACKER
	STA @VIRTUAL04
	LDA CURRENT_TARGET
	STA @VIRTUAL02
	STA @LOCAL03
	JSL REDIRECT_HIDE_HPPP_WINDOWS
	LDA #PARTY_MEMBER::POO
	JSL ADD_CHAR_TO_PARTY
	LDA #0
	STA @LOCAL02
	BRA @FIND_BATTLER_LOOP_CHECK
@FIND_EMPTY_BATTLER:
	LDA @LOCAL02
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BNE @NEXT_BATTLER
	TXA
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	TAY
	STY @LOCAL02
	TYX
	LDA #PARTY_MEMBER::POO
	JSL BATTLE_INIT_PLAYER_STATS
	LDY @LOCAL02
	STY CURRENT_ATTACKER
	JSL REDIRECT_SHOW_HPPP_WINDOWS
.IF .DEFINED(JPN)
	LDA #0
	STA @LOCAL02
.ELSE
	LDX #0
.ENDIF
	BRA @PARTY_LOOP_CHECK
@CHECK_PARTY_MEMBER:
.IF .DEFINED(JPN)
	LDA @LOCAL02
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
.ELSE
	LDA GAME_STATE + game_state::party_members,X
.ENDIF
	AND #$00FF
	CMP #PARTY_MEMBER::POO
	BNE @NEXT_PARTY_MEMBER
.IF .DEFINED(JPN)
	LDA @LOCAL02
.ELSE
	TXA
.ENDIF
	JSL SELECT_BATTLE_MENU_CHARACTER_FAR
	BRA @STARSTORM_ATTACK
@NEXT_PARTY_MEMBER:
.IF .DEFINED(JPN)
	LDA @LOCAL02
	INC
	STA @LOCAL02
.ELSE
	INX
.ENDIF
@PARTY_LOOP_CHECK:
.IF .DEFINED(JPN)
	STA @VIRTUAL02
.ELSE
	STX @VIRTUAL02
.ENDIF
	LDA #TOTAL_PARTY_COUNT
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @CHECK_PARTY_MEMBER
	BRA @STARSTORM_ATTACK
@NEXT_BATTLER:
	LDA @LOCAL02
	INC
	STA @LOCAL02
@FIND_BATTLER_LOOP_CHECK:
	STA @VIRTUAL02
	LDA #BATTLER_COUNT
	CLC
	SBC @VIRTUAL02
.IF .DEFINED(JPN)
	JUMPGTS @FIND_EMPTY_BATTLER
.ELSE
	BRANCHGTS @FIND_EMPTY_BATTLER
.ENDIF
@STARSTORM_ATTACK:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_POO_BREAK_IN_2
	LDA #0
	JSL FIX_ATTACKER_NAME
	SEP #PROC_FLAGS::ACCUM8
	LDA #PSI::STARSTORM_ALPHA
	JSL SET_CURRENT_ITEM_FAR
	MOVE_INT f:BATTLE_ACTION_TABLE+364, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_IN_BATTLE_TEXT
	LDY #0
	STY @LOCAL01
	BRA @DAMAGE_LOOP_CHECK
@DAMAGE_ENEMY:
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	.A16
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @NEXT_ENEMY
	LDA BATTLERS_TABLE+battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BNE @NEXT_ENEMY
	TXA
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	STA CURRENT_TARGET
	JSL FIX_TARGET_NAME
	LDA #$0168
	JSR TWENTY_FIVE_PERCENT_VARIANCE
	TAX
	LDA CURRENT_TARGET
	JSR CALC_DAMAGE
@NEXT_ENEMY:
	LDY @LOCAL01
	INY
	STY @LOCAL01
@DAMAGE_LOOP_CHECK:
	STY @VIRTUAL02
	LDA #BATTLER_COUNT
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @DAMAGE_ENEMY
	LDA @VIRTUAL04
	STA CURRENT_ATTACKER
	LDA @LOCAL03
	STA @VIRTUAL02
	STA CURRENT_TARGET
	LDA #0
	JSL FIX_ATTACKER_NAME
	JSL FIX_TARGET_NAME
	END_C_FUNCTION
