
BTLACT_MUMMY_WRAP:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	JSR FAIL_ATTACK_ON_NPCS
	CMP #0
	BNE @DONE
	LDA #250
	JSR SUCCESS_SPEED
	CMP #0
	BEQ @NO_EFFECT
	LDX CURRENT_TARGET
	LDA #MUMMY_WRAP_BASE_DAMAGE
	SEC
	SBC a:battler::defense,X
	STA @LOCAL01
	CLC
	SBC #0
	BRANCHLTEQS @NO_EFFECT
	LDX #$00FF
	LDA @LOCAL01
	JSR CALC_RESIST_DAMAGE
	LDY #STATUS_2::SOLIDIFIED
	LDX #STATUS_GROUP::TEMPORARY
	LDA CURRENT_TARGET
	JSR INFLICT_STATUS_BATTLE
	CMP #0
	BEQ @DONE
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KOORI_ON
	BRA @DONE
@NO_EFFECT:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
@DONE:
	END_C_FUNCTION
