
BTLACT_PARALYZE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	JSR FAIL_ATTACK_ON_NPCS
	CMP #0
	BNE @DONE
	JSR SUCCESS_LUCK80
	CMP #0
	BEQ @NO_EFFECT
	LDX CURRENT_TARGET
	SEP #PROC_FLAGS::ACCUM8
	LDA a:battler::paralysis_resist,X
	JSR SUCCESS_255
	.A16
	CMP #0
	BEQ @NO_EFFECT
	LDY #STATUS_0::PARALYZED
	LDX #STATUS_GROUP::PERSISTENT_EASYHEAL
	LDA CURRENT_TARGET
	JSR INFLICT_STATUS_BATTLE
	.A16
	CMP #0
	BEQ @NO_EFFECT
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_SHIBIRE_ON
	BRA @DONE
@NO_EFFECT:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
@DONE:
	END_C_FUNCTION
