
BTLACT_POKEY_SPEECH_2:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #GIYGAS_PHASES::START_PRAYING
	STA GIYGAS_PHASE
	LDA #2*SECONDS
	JSR WAIT
	LDX #.LOWORD(BATTLERS_TABLE) + .SIZEOF(battler) * 9 + battler::consciousness
	STX @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA __BSS_START__,X
	JSL RENDER_ALL_BATTLE_SPRITES
	.A16
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_MECHPOKEY_2_TALK_2
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	LDX @LOCAL01
	STA __BSS_START__,X
	JSL RENDER_ALL_BATTLE_SPRITES
	.A16
	LDA #1*SECOND
	JSR WAIT
	LDA #ENEMY::GIYGAS_5
	JSR REPLACE_BOSS_BATTLER
	LDX #MUSIC::GIYGAS_PHASE3
	LDA #ENEMY_GROUP::BOSS_GIYGAS_PHASE_DURING_PRAYER_1
	JSR LOAD_BATTLE_SCENE
	LDA #1
	STA SKIP_DEATH_TEXT_AND_CLEANUP
	END_C_FUNCTION
