
BTLACT_PRAY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
.IF .DEFINED(JPN)
	@PRAYERTEXTPTR := @VIRTUAL06
	@PRAYERTEXTPTRTMP := @VIRTUAL0A
.ELSE
	@PRAYERTEXTPTR := @VIRTUAL0A
	@PRAYERTEXTPTRTMP := @VIRTUAL06
.ENDIF
	LDA #16
	JSR RAND_LIMIT
	TAX
	LDA f:PRAYER_LIST,X
	AND #$00FF
	STA @LOCAL02
	LOADPTR PRAYER_TEXT_PTRS, @PRAYERTEXTPTR
	LDA @LOCAL02
	ASL
	ASL
	CLC
	ADC @PRAYERTEXTPTR
	STA @PRAYERTEXTPTR
	DEREFERENCE_PTR_TO @PRAYERTEXTPTR, @PRAYERTEXTPTRTMP
	MOVE_INT @PRAYERTEXTPTRTMP, @LOCAL00
	JSL DISPLAY_IN_BATTLE_TEXT
	LDA @LOCAL02
	BEQ @PRAYER_SUBTLE
	CMP #1
	BEQ @PRAYER_WARM
	CMP #2
	BEQ @PRAYER_MYSTERIOUS
	CMP #3
	BEQL @PRAYER_GOLDEN
	CMP #4
	BEQL @PRAYER_ROCKIN
	CMP #5
	BEQL @PRAYER_FLASH
	CMP #6
	BEQL @PRAYER_RAINBOW
	CMP #7
	BEQL @PRAYER_AROMA
	CMP #8
	BEQL @PRAYER_RENDING_SOUND
	CMP #9
	BEQL @PRAYER_DEFENSE_DOWN
	JMP @APPLY_PRAYER
@PRAYER_SUBTLE:
	JSL TARGET_ALLIES
	JSL REMOVE_NPC_TARGETTING
	LOADPTR BTLACT_PRAY_SUBTLE, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JMP @APPLY_PRAYER
@PRAYER_WARM:
	JSL TARGET_ALLIES
	JSL REMOVE_NPC_TARGETTING
	LOADPTR BTLACT_PRAY_WARM, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JMP @APPLY_PRAYER
@PRAYER_MYSTERIOUS:
	JSL TARGET_ALLIES
	JSL REMOVE_NPC_TARGETTING
	LOADPTR BTLACT_PRAY_MYSTERIOUS, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JMP @APPLY_PRAYER
@PRAYER_GOLDEN:
	JSL TARGET_ALLIES
	JSL REMOVE_NPC_TARGETTING
	JSR REMOVE_DEAD_TARGETTING
	MOVE_INT BATTLER_TARGET_FLAGS, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL RANDOM_TARGETTING
	MOVE_INT @VIRTUAL06, BATTLER_TARGET_FLAGS
	LOADPTR BTLACT_PRAY_GOLDEN, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JMP @APPLY_PRAYER
@PRAYER_ROCKIN:
	JSL TARGET_ALL_ENEMIES
	JSL REMOVE_NPC_TARGETTING
	JSR REMOVE_DEAD_TARGETTING
	MOVE_INT BATTLER_TARGET_FLAGS, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL RANDOM_TARGETTING
	MOVE_INT @VIRTUAL06, BATTLER_TARGET_FLAGS
	LOADPTR BTLACT_PSI_ROCKIN_B, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	BRA @APPLY_PRAYER
@PRAYER_FLASH:
	JSL TARGET_ALL
	LOADPTR BTLACT_PSI_FLASH_A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	BRA @APPLY_PRAYER
@PRAYER_RAINBOW:
	JSL TARGET_ALL
	LOADPTR BTLACT_PRAY_RAINBOW, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	BRA @APPLY_PRAYER
@PRAYER_AROMA:
	JSL TARGET_ALL
	LOADPTR BTLACT_PRAY_AROMA, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	BRA @APPLY_PRAYER
@PRAYER_RENDING_SOUND:
	JSL TARGET_ALL
	LOADPTR BTLACT_PRAY_RENDING_SOUND, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	BRA @APPLY_PRAYER
@PRAYER_DEFENSE_DOWN:
	JSL TARGET_ALL
	LOADPTR BTLACT_DEFENSE_DOWN_A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
@APPLY_PRAYER:
	LDA @LOCAL02
	CMP #6
	BEQ @SKIP_REMOVE_DEAD
	JSR REMOVE_DEAD_TARGETTING
@SKIP_REMOVE_DEAD:
	MOVE_INT @LOCAL01, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL APPLY_ACTION_TO_TARGETS
	MOVE_INT_CONSTANT 0, BATTLER_TARGET_FLAGS
	END_C_FUNCTION
