
BTLACT_PRAY_RAINBOW:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	LDX CURRENT_TARGET
	LDA a:battler::afflictions+STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BNE @DONE
	LDX CURRENT_TARGET
	LDA a:battler::hp_max,X
	TAX
	LDA CURRENT_TARGET
	JSR REVIVE_TARGET
@DONE:
	END_C_FUNCTION
