
BTLACT_PSI_FLASH_A:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	JSR FAIL_ATTACK_ON_NPCS
	CMP #0
	BNE @DONE
	JSR FLASH_IMMUNITY_TEST
	CMP #0
	BEQ @WEAKEN_SHIELD
	JSL RAND
	AND #$0007
	BNE @INFLICT_CRYING
	JSR FLASH_INFLICT_FEELING_STRANGE
	BRA @WEAKEN_SHIELD
@INFLICT_CRYING:
	JSR FLASH_INFLICT_CRYING
@WEAKEN_SHIELD:
	JSR WEAKEN_SHIELD
@DONE:
	END_C_FUNCTION
