
PSI_THUNDER_COMMON:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @LOCAL04
	STA @VIRTUAL04
	LDY #0
	STY @LOCAL03
	TYX
	STX @LOCAL02
	BRA @COUNT_CHECK
@COUNT_BODY:
	TXA
	JSL IS_CHAR_TARGETTED
	CMP #0
	BEQ @COUNT_NEXT
	LDY @LOCAL03
	INY
	STY @LOCAL03
@COUNT_NEXT:
	LDX @LOCAL02
	INX
	STX @LOCAL02
@COUNT_CHECK:
	CPX #BATTLER_COUNT
	BCC @COUNT_BODY
	LDY @LOCAL03
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 64
	STA @VIRTUAL02
	CMP #256
	BCC @CLAMP_DONE
	LDA #255
	STA @VIRTUAL02
@CLAMP_DONE:
	MOVE_INT BATTLER_TARGET_FLAGS, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDY #0
	STY @LOCAL03
	JMP @HIT_CHECK
@HIT_BODY:
	MOVE_INT @LOCAL01, @VIRTUAL06
	MOVE_INT @VIRTUAL06, BATTLER_TARGET_FLAGS
	JSL REMOVE_STATUS_UNTARGETTABLE_TARGETS
	LDA #0
	STA @VIRTUAL06
	LDA #0
	STA @VIRTUAL06+2
	MOVE_INT BATTLER_TARGET_FLAGS, @VIRTUAL0A
	CMP @VIRTUAL06+2
	BNE @TARGETS_REMAIN
	LDA @VIRTUAL0A
	CMP @VIRTUAL06
@TARGETS_REMAIN:
	BEQL @DONE
.IF .DEFINED(JPN)
	MOVE_INT BATTLER_TARGET_FLAGS, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @LOCAL00
.ELSE
	MOVE_INT BATTLER_TARGET_FLAGS, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
.ENDIF
	JSL RANDOM_TARGETTING
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, BATTLER_TARGET_FLAGS
	LDX #0
	STX @LOCAL02
	BRA @FIND_TARGET_CHECK
@FIND_TARGET_BODY:
	TXA
	JSL IS_CHAR_TARGETTED
	CMP #0
	BNE @FOUND_TARGET
	LDX @LOCAL02
	INX
	STX @LOCAL02
@FIND_TARGET_CHECK:
	CPX #BATTLER_COUNT
	BCC @FIND_TARGET_BODY
@FOUND_TARGET:
	LDX @LOCAL02
	TXA
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	STA CURRENT_TARGET
	JSL FIX_TARGET_NAME
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	JSR SUCCESS_255
	.A16
	CMP #0
	BEQL @MISS
	.A16
	LDA @VIRTUAL04
	CMP #120
	BNE @LARGE_THUNDER
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_THUNDER_SMALL
	BRA @WAIT_ANIMATION
@LARGE_THUNDER:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_THUNDER_LARGE
	BRA @WAIT_ANIMATION
@ANIMATION_TICK:
	JSL WINDOW_TICK
@WAIT_ANIMATION:
	JSL IS_PSI_ANIMATION_ACTIVE
	CMP #0
	BNE @ANIMATION_TICK
	LDX CURRENT_TARGET
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::use_alt_spritemap,X
	LDX CURRENT_TARGET
	REP #PROC_FLAGS::ACCUM8
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @CHECK_SHIELD
	LDX #1
	STX @LOCAL02
	LDX CURRENT_TARGET
	LDA a:battler::row,X
	AND #$00FF
	INC
	LDX @LOCAL02
	JSL FIND_ITEM_IN_INVENTORY2
	CMP #0
	BEQ @CHECK_SHIELD
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_FRANKLIN_TURN
	LDA #1
	STA DAMAGE_IS_REFLECTED
	JSR SWAP_ATTACKER_WITH_TARGET
@CHECK_SHIELD:
	LDX CURRENT_TARGET
	LDA a:battler::afflictions + STATUS_GROUP::SHIELD,X
	AND #$00FF
	TAX
	CPX #1
	BEQ @SET_SHIELD_HP
	CPX #2
	BNE @PSI_SHIELD_CHECK
@SET_SHIELD_HP:
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	LDX CURRENT_TARGET
	STA a:battler::shield_hp,X
@PSI_SHIELD_CHECK:
	JSR PSI_SHIELD_NULLIFY
	.A16
	CMP #0
	BNE @WEAKEN_SHIELD
	LDA @VIRTUAL04
	JSR FIFTY_PERCENT_VARIANCE
	LDX #$00FF
	JSR CALC_RESIST_DAMAGE
@WEAKEN_SHIELD:
	JSR WEAKEN_SHIELD
	BRA @CHECK_SIDES
@MISS:
	.A16
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_THUNDER_MISS_SE
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KAMINARI_HAZURE
@CHECK_SIDES:
	LDA #0
	JSL COUNT_CHARS
	CMP #0
	BEQ @DONE
	LDA #1
	JSL COUNT_CHARS
	CMP #0
	BEQ @DONE
	LDY @LOCAL03
	INY
	STY @LOCAL03
@HIT_CHECK:
	CPY @LOCAL04
	BCCL @HIT_BODY
@DONE:
	MOVE_INT_CONSTANT 0, BATTLER_TARGET_FLAGS
	END_C_FUNCTION
