
BTLACT_PSI_FLASH_G:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	JSR FAIL_ATTACK_ON_NPCS
	CMP #0
	BNE @DONE
	JSR FLASH_IMMUNITY_TEST
	CMP #0
	BEQ @WEAKEN_SHIELD
	JSL RAND
	AND #$0007
	BEQ @INFLICT_KO
	CMP #1
	BEQ @INFLICT_KO
	CMP #2
	BEQ @INFLICT_PARALYSIS
	CMP #3
	BEQ @INFLICT_FEELING_STRANGE
	BRA @INFLICT_CRYING
@INFLICT_KO:
	LDA CURRENT_TARGET
	JSL KO_TARGET
	BRA @WEAKEN_SHIELD
@INFLICT_PARALYSIS:
	JSR FLASH_INFLICT_PARALYSIS
	BRA @WEAKEN_SHIELD
@INFLICT_FEELING_STRANGE:
	JSR FLASH_INFLICT_FEELING_STRANGE
	BRA @WEAKEN_SHIELD
@INFLICT_CRYING:
	JSR FLASH_INFLICT_CRYING
@WEAKEN_SHIELD:
	JSR WEAKEN_SHIELD
@DONE:
	END_C_FUNCTION
