
FLASH_IMMUNITY_TEST:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	JSR PSI_SHIELD_NULLIFY
	CMP #0
	BEQ @NOT_NULLIFIED
	LDA #0
	BRA @RETURN
@NOT_NULLIFIED:
	LDX CURRENT_TARGET
	SEP #PROC_FLAGS::ACCUM8
	LDA a:battler::flash_resist,X
	JSR SUCCESS_255
	.A16
	CMP #0
	BEQ @NO_EFFECT
	LDA #1
	BRA @RETURN
@NO_EFFECT:
	.A16
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
	LDA #0
@RETURN:
	END_C_FUNCTION
