
BTLACT_PSI_SHIELD_B:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LDX #STATUS_6::PSI_SHIELD_POWER
	LDA CURRENT_TARGET
	JSR SHIELDS_COMMON
	CMP #0
	BEQ @ALREADY_ACTIVE
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_PSYPOWER_ADD
	BRA @DONE
@ALREADY_ACTIVE:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_PSYPOWER_ON
@DONE:
	END_C_FUNCTION
