
BTLACT_RANDOM_STAT_UP_1D4:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #7
	JSR RAND_LIMIT
	CMP #0
	BEQ @BOOST_DEFENSE
	CMP #1
	BEQ @BOOST_OFFENSE
	CMP #2
	BEQL @BOOST_SPEED
	CMP #3
	BEQL @BOOST_GUTS
	CMP #4
	BEQL @BOOST_VITALITY
	CMP #5
	BEQL @BOOST_IQ
	CMP #6
	BEQL @BOOST_LUCK
	JMP @DONE
@BOOST_DEFENSE:
	LDA #4
	JSR RAND_LIMIT
	INC
	STA @LOCAL02
	LDA CURRENT_TARGET
	CLC
	ADC #battler::defense
	TAX
	LDA @LOCAL02
	STA @VIRTUAL02
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL02
	STA __BSS_START__,X
	LOADPTR MSG_BTL_DEFENSE_UP, @LOCAL00
	MOVE_INT1632S @LOCAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	BRA @DONE
@BOOST_OFFENSE:
	LDA #4
	JSR RAND_LIMIT
	INC
	STA @LOCAL02
	LDA CURRENT_TARGET
	CLC
	ADC #battler::offense
	TAX
	LDA @LOCAL02
	STA @VIRTUAL02
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL02
	STA __BSS_START__,X
	LOADPTR MSG_BTL_OFFENSE_UP, @LOCAL00
	MOVE_INT1632S @LOCAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	BRA @DONE
@BOOST_SPEED:
	JSL BTLACT_SPEED_UP_1D4
	BRA @DONE
@BOOST_GUTS:
	JSL BTLACT_GUTS_UP_1D4
	BRA @DONE
@BOOST_VITALITY:
	JSL BTLACT_VITALITY_UP_1D4
	BRA @DONE
@BOOST_IQ:
	JSL BTLACT_IQ_UP_1D4
	BRA @DONE
@BOOST_LUCK:
	JSL BTLACT_LUCK_UP_1D4
@DONE:
	END_C_FUNCTION
