
BTLACT_REDUCEPP:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX CURRENT_TARGET
	LDA a:battler::pp_target,X
	BNE @HAS_PP
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_PPSUCK_ZERO
	BRA @DONE
@HAS_PP:
	LDX CURRENT_TARGET
	LDA a:battler::pp_max,X
	LSR
	LSR
	LSR
	LSR
	BEQ @NO_EFFECT
	JSR FIFTY_PERCENT_VARIANCE
	TAY
	STY @LOCAL02
	TYX
	LDA CURRENT_TARGET
	JSR REDUCE_PP
	LOADPTR MSG_BTL_PPSUCK_OBJ, @LOCAL00
	LDY @LOCAL02
	TYA
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	BRA @DONE
@NO_EFFECT:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
@DONE:
	END_C_FUNCTION
