
BTLACT_SHIELD_KILLER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	JSR SUCCESS_LUCK80
	CMP #0
	BEQ @NO_EFFECT
	LDA CURRENT_TARGET
	CLC
	ADC #battler::afflictions + STATUS_GROUP::SHIELD
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	BEQ @NO_EFFECT
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_SHIELD_OFF
	BRA @DONE
@NO_EFFECT:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
@DONE:
	END_C_FUNCTION
