
BTLACT_SHOOT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LDA #1
	JSR MISS_CALC
	CMP #0
	BNE @DONE
	JSR DETERMINE_DODGE
	CMP #0
	BNE @DODGED
	JSR BTLACT_LEVEL_2_ATK
	BRA @DONE
@DODGED:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_UTU_YOKETA
@DONE:
	END_C_FUNCTION
