
BTLACT_SPY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	END_STACK_VARS
	LOADPTR MSG_BTL_CHECK_OFFENSE, @LOCAL00
	LDX CURRENT_TARGET
	LDA a:battler::offense,X
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	LOADPTR MSG_BTL_CHECK_DEFENSE, @LOCAL00
	LDX CURRENT_TARGET
	LDA a:battler::defense,X
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	LDX CURRENT_TARGET
	LDA a:battler::fire_resist,X
	AND #$00FF
	CMP #$00FF
	BNE @CHECK_FREEZE_RESIST
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_CHECK_ANTI_FIRE
@CHECK_FREEZE_RESIST:
	LDX CURRENT_TARGET
	LDA a:battler::freeze_resist,X
	AND #$00FF
	CMP #$00FF
	BNE @CHECK_FLASH_RESIST
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_CHECK_ANTI_FREEZE
@CHECK_FLASH_RESIST:
	LDX CURRENT_TARGET
	LDA a:battler::flash_resist,X
	AND #$00FF
	CMP #$00FF
	BNE @CHECK_PARALYSIS_RESIST
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_CHECK_ANTI_FLASH
@CHECK_PARALYSIS_RESIST:
	LDX CURRENT_TARGET
	LDA a:battler::paralysis_resist,X
	AND #$00FF
	CMP #$00FF
	BNE @CHECK_HYPNOSIS_RESIST
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_CHECK_ANTI_PARALYSIS
@CHECK_HYPNOSIS_RESIST:
	LDX CURRENT_TARGET
	LDA a:battler::hypnosis_resist,X
	AND #$00FF
	CMP #$00FF
	BNE @CHECK_BRAINSHOCK_RESIST
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_CHECK_BRAIN_LEVEL_0
@CHECK_BRAINSHOCK_RESIST:
	LDX CURRENT_TARGET
	LDA a:battler::brainshock_resist,X
	AND #$00FF
	CMP #$00FF
	BNE @CHECK_ITEM_DROP
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_CHECK_BRAIN_LEVEL_3
@CHECK_ITEM_DROP:
	LDX CURRENT_TARGET
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BNE @DONE
	LDA #3
	JSL FIND_INVENTORY_SPACE2
	CMP #0
	BEQ @DONE
	LDA ITEM_DROPPED
	BEQ @DONE
	SEP #PROC_FLAGS::ACCUM8
	LDA ITEM_DROPPED
	JSL SET_CURRENT_ITEM_FAR
	.A16
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_CHECK_PRESENT_GET
	STZ ITEM_DROPPED
@DONE:
	END_C_FUNCTION
