
BTLACT_STEAL:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	LDX CURRENT_TARGET
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BEQ @DONE
	LDX CURRENT_TARGET
	LDA a:battler::npc_id,X
	AND #$00FF
	BNE @DONE
	LDA MIRROR_ENEMY
	BEQ @TRY_STEAL
	LDX CURRENT_ATTACKER
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @TRY_STEAL
	LDX CURRENT_ATTACKER
	LDA __BSS_START__,X
	CMP #4
	BEQ @DONE
@TRY_STEAL:
	LDX CURRENT_ATTACKER
	LDA a:battler::current_action_argument,X
	AND #$00FF
	BEQ @DONE
	AND #$00FF
	TAX
	LDA #$00FF
	JSL TAKE_ITEM_FROM_CHARACTER
@DONE:
	END_C_FUNCTION
