
BTLACT_SUDDEN_GUTS_PILL:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	END_STACK_VARS
	JSR FAIL_ATTACK_ON_NPCS
	CMP #0
	BNE @RETURN
	LDX CURRENT_TARGET
	LDA a:battler::guts,X
	ASL
	CMP #$00FF
	BCC @CLAMP_MAX
	LDA #$00FF
@CLAMP_MAX:
	LDX CURRENT_TARGET
	STA a:battler::guts,X
	LOADPTR MSG_BTL_2GUTS_UP, @LOCAL00
	LDX CURRENT_TARGET
	LDA a:battler::guts,X
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
@RETURN:
	END_C_FUNCTION
