
BUILD_COMMAND_MENU:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT8
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA SKIP_ADDING_COMMAND_TEXT
	AND #$00FF
	BNEL @AFTER_MENU_BUILD
	LDA #1
	STA @VIRTUAL02
	JMP @COMMAND_LOOP_CHECK
@PROCESS_COMMAND:
	LDA @VIRTUAL02
	CMP #3
	BNE @CHECK_AUTO_SELECT
	JSR FIND_FIRST_CHARACTER_WITH_PSI
	CMP #0
	BEQL @NEXT_COMMAND
@CHECK_AUTO_SELECT:
	LDA @VIRTUAL02
	CMP #1
	BEQ @SET_AUTO_SELECT
	LDA @VIRTUAL02
	CMP #5
	BEQ @SET_AUTO_SELECT
	LDA @VIRTUAL02
	CMP #2
	BNE @SET_NORMAL_SELECT
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	CMP #1
	BNE @SET_NORMAL_SELECT
	LDX #1
	LDA GAME_STATE + game_state::party_members
	AND #$00FF
	JSL GET_CHARACTER_ITEM
	CMP #0
	BNE @SET_NORMAL_SELECT
@SET_AUTO_SELECT:
	LDY #1
	BRA @ADD_COMMAND
@SET_NORMAL_SELECT:
	LDY #27
@ADD_COMMAND:
	LDA @VIRTUAL02
	DEC
	STA @LOCAL04
	LOADPTR DEBUG_MENU_ELEMENT_SPACING_DATA, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL03
	LDA @LOCAL04
	ASL
	TAX
	LOADPTR CMD_WINDOW_TEXT, @VIRTUAL06
	LDA @LOCAL04
	OPTIMIZED_MULT @VIRTUAL04, 10
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	MOVE_INT_CONSTANT NULL, @LOCAL01
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	TXA
	INC
	MOVE_INTY @LOCAL03, @VIRTUAL06
	MOVE_INTY @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	TAY
	TXA
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	TAX
	LDA @VIRTUAL02
	JSR ADD_MENU_ITEM_WITH_SOUND
@NEXT_COMMAND:
	INC @VIRTUAL02
@COMMAND_LOOP_CHECK:
	LDA @VIRTUAL02
	CMP #7
	BCCL @PROCESS_COMMAND
@AFTER_MENU_BUILD:
	SEP #PROC_FLAGS::ACCUM8
	STZ SKIP_ADDING_COMMAND_TEXT
	JSR PRINT_MENU_ITEMS
	END_C_FUNCTION
