
CC_GATHER_MENU_OPTION_TEXT:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXA
	CMP #1
	BEQ @END_MARKER_WITH_CALLBACK
	CMP #2
	BEQ @END_MARKER_NO_CALLBACK
	BRA @STORE_CHARACTER
@END_MARKER_WITH_CALLBACK:
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	SEP #PROC_FLAGS::ACCUM8
	STZ TEXT_NEW_MENU_OPTION_BUFFER,X
	REP #PROC_FLAGS::ACCUM8
	STZ CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_ADD_MENU_OPTION_WITH_CALLBACK)
	BRA @RETURN
@END_MARKER_NO_CALLBACK:
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	SEP #PROC_FLAGS::ACCUM8
	STZ TEXT_NEW_MENU_OPTION_BUFFER,X
	REP #PROC_FLAGS::ACCUM8
	PROMOTENEARPTR TEXT_NEW_MENU_OPTION_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	JSR ADD_MENU_OPTION
	LDA #NULL
	BRA @RETURN
@STORE_CHARACTER:
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA TEXT_NEW_MENU_OPTION_BUFFER,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_GATHER_MENU_OPTION_TEXT)
@RETURN:
	END_C_FUNCTION
