
COUNT_MENU_OPTION_CHAIN:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	CMP #.LOWORD(-1)
	BNE @START_COUNTING
	LDA #0
	BRA @DONE
@START_COUNTING:
	LDX #1
	STX @LOCAL00
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	BRA @CHECK_NEXT
@NEXT_LINK:
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	LDX @LOCAL00
	INX
	STX @LOCAL00
@CHECK_NEXT:
	TAX
	LDA a:menu_option::next,X
	CMP #.LOWORD(-1)
	BNE @NEXT_LINK
	LDX @LOCAL00
	TXA
@DONE:
	END_C_FUNCTION
