
FIND_FIRST_EMPTY_MENU_OPTION:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA #0
	STA @LOCAL00
	BRA @LOOP_CHECK
@CHECK_OPTION:
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	TAX
	LDA MENU_OPTIONS,X
	BNE @NEXT_OPTION
	LDA @LOCAL00
	BRA @DONE
@NEXT_OPTION:
	LDA @LOCAL00
	INC
	STA @LOCAL00
@LOOP_CHECK:
	CMP #NUM_MENU_OPTIONS
	BNE @CHECK_OPTION
	LDA #.LOWORD(-1)
@DONE:
	END_C_FUNCTION
