
LAYOUT_MENU_OPTIONS:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL0D
	TXY
	STY @LOCAL0C
	STA @VIRTUAL02
	STA @LOCAL0B
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	STA @LOCAL0A
	CLC
	ADC #window_stats::current_option
	TAX
	LDA __BSS_START__,X
	CMP #.LOWORD(-1)
	BEQL @DONE
	LDA @VIRTUAL02
	LDY #window_stats::unknown49
	STA (@LOCAL0A),Y
	LDA __BSS_START__,X
	STA @LOCAL09
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	STA @VIRTUAL04
	LDY @LOCAL0C
	LDA @VIRTUAL02
	DEC
	JSL MULT16
	LDY #window_stats::width
	CLC
	ADC (@LOCAL0A),Y
	LDY @VIRTUAL02
	JSL DIVISION16S_DIVISOR_POSITIVE
	STA @LOCAL08
@CALC_PAGE_SIZE:
	LDY #window_stats::height
	LDA (@LOCAL0A),Y
	LSR
	TAX
	STX @LOCAL07
	LDA @LOCAL09
	JSR COUNT_MENU_OPTION_CHAIN
	LDX @LOCAL07
	LDY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	DEC
	JSL DIVISION16S_DIVISOR_POSITIVE
	STX @VIRTUAL02
	CMP @VIRTUAL02
	BLTEQ @PAGE_SIZE_READY
	DEX
	DEX
@PAGE_SIZE_READY:
	STX @LOCAL09
	STZ @LOCAL06
	LDA #1
	STA @LOCAL05
@PAGE_LOOP:
	LDY #window_stats::text_y
	LDA (@LOCAL0A),Y
	STA @LOCAL07
	LDA @LOCAL09
	STA @LOCAL04
	BRA @ROW_CHECK
@ROW_LOOP:
	LDA @LOCAL0B
	STA @VIRTUAL02
	LDY @VIRTUAL02
	STY @LOCAL03
	BRA @COLUMN_CHECK
@COLUMN_LOOP:
	LDA @LOCAL0D
	BEQ @NO_CENTER
	LDX #30
	LDA @VIRTUAL04
	CLC
	ADC #menu_option::label
	JSR COUNT_STRING_LENGTH
	STA @VIRTUAL02
	LDA @LOCAL08
	SEC
	SBC @VIRTUAL02
	LSR
	BRA @SET_POSITION
@NO_CENTER:
	LDA #0
@SET_POSITION:
	CLC
	ADC @LOCAL06
	LDX @VIRTUAL04
	STA a:menu_option::text_x,X
	LDA @LOCAL07
	LDX @VIRTUAL04
	STA a:menu_option::text_y,X
	LDA @LOCAL05
	LDX @VIRTUAL04
	STA a:menu_option::page,X
	LDX @VIRTUAL04
	LDA a:menu_option::next,X
	STA @LOCAL02
	CMP #.LOWORD(-1)
	BEQ @END_OF_OPTIONS
	LDA @LOCAL06
	CLC
	ADC @LOCAL08
	STA @LOCAL06
	LDA @LOCAL02
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	STA @VIRTUAL04
@NEXT_COLUMN:
	LDY @LOCAL03
	DEY
	STY @LOCAL03
@COLUMN_CHECK:
	BNE @COLUMN_LOOP
	STZ @LOCAL06
	INC @LOCAL07
	DEC @LOCAL04
@ROW_CHECK:
	LDA @LOCAL04
	BNE @ROW_LOOP
	INC @LOCAL05
	JMP @PAGE_LOOP
@END_OF_OPTIONS:
	LDA @LOCAL0A
	CLC
	ADC #window_stats::current_option
	TAX
	STX @LOCAL0D
	LDA __BSS_START__,X
	JSR COUNT_MENU_OPTION_CHAIN
	STA @LOCAL05
	LDY #window_stats::height
	LDA (@LOCAL0A),Y
	LSR
	STA @VIRTUAL04
	LDA @LOCAL0B
	STA @VIRTUAL02
	LDY @VIRTUAL02
	LDA @LOCAL05
	CLC
	ADC @VIRTUAL02
	DEC
	JSL DIVISION16S_DIVISOR_POSITIVE
	CMP @VIRTUAL04
	BLTEQ @DONE
	LDX @LOCAL0D
	LDA __BSS_START__,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	LDX @VIRTUAL02
	DEX
	STX @LOCAL03
	BRA @SCROLL_CHECK
@SCROLL_FIND_PREV:
	DEX
	STX @LOCAL03
	TAX
	LDA a:menu_option::next,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
@SCROLL_CHECK:
	LDX @LOCAL03
	BNE @SCROLL_FIND_PREV
	LOADPTR MENU_OVERFLOW_TEXT, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDY #window_stats::height
	LDA (@LOCAL0A),Y
	LSR
	TAY
	DEY
	LDX #0
	TXA
	JSR ADD_MENU_ITEM
	LDY #window_stats::option_count
	LDA (@LOCAL0A),Y
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	TAX
	STZ MENU_OPTIONS + menu_option::page,X
@DONE:
	END_C_FUNCTION
