
LAYOUT_MENU_OPTIONS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL0D
	STX @LOCAL0C
	STA @LOCAL0B
	LDA #0
	STA @VIRTUAL04
	STA @VIRTUAL02
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	STA @LOCAL0A
	CLC
	ADC #window_stats::current_option
	TAX
	LDA __BSS_START__,X
	CMP #.LOWORD(-1)
	BEQL @DONE
	LDA @LOCAL0B
	LDY #window_stats::unknown49
	STA (@LOCAL0A),Y
	LDA __BSS_START__,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	TAY
	STY @LOCAL09
	SEP #PROC_FLAGS::ACCUM8
	STZ @LOCAL00
	LDX #4
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(MENU_OPTION_LABEL_LENGTHS)
	JSL MEMSET16
	SEP #PROC_FLAGS::ACCUM8
	LDA #<-1
	STA @LOCAL00
	LDX #4
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(MENU_OPTION_COLUMN_WIDTHS)
	JSL MEMSET16
	LDA @LOCAL0D
	BEQL @FIXED_WIDTH_SETUP
@MEASURE_LABEL_LOOP:
	LDY @LOCAL09
	TYA
	CLC
	ADC #menu_option::label
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #30
	JSL GET_STRING_PIXEL_WIDTH
	SEP #PROC_FLAGS::ACCUM8
	CLC
	ADC #8
	LDX @VIRTUAL04
	STA MENU_OPTION_LABEL_LENGTHS,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	PHA
	LDA @VIRTUAL02
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL02
	LDY @LOCAL09
	LDA menu_option::next,Y
	CMP #.LOWORD(-1)
	BEQ @COMPUTE_SCALE_FACTOR
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	TAY
	STY @LOCAL09
	INC @VIRTUAL04
	BRA @MEASURE_LABEL_LOOP
@COMPUTE_SCALE_FACTOR:
	LDY #window_stats::width
	LDA (@LOCAL0A),Y
	LDY #$0800
	JSL MULT16
	LDY @VIRTUAL02
	JSL DIVISION16S_DIVISOR_POSITIVE
	STA @LOCAL08
	BRA @COMPUTE_SCALED_WIDTHS_CHECK
@COMPUTE_SCALED_WIDTHS_BODY:
	LDX @VIRTUAL04
	LDA MENU_OPTION_LABEL_LENGTHS,X
	AND #$00FF
	TAY
	LDA @LOCAL08
	JSL MULT16
	XBA
	AND #$00FF
	SEP #PROC_FLAGS::ACCUM8
	LDX @VIRTUAL04
	STA MENU_OPTION_COLUMN_WIDTHS,X
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	DEC
	STA @VIRTUAL04
@COMPUTE_SCALED_WIDTHS_CHECK:
	LDA @VIRTUAL04
	CMP #.LOWORD(-1)
	BNE @COMPUTE_SCALED_WIDTHS_BODY
	LDY #window_stats::current_option
	LDA (@LOCAL0A),Y
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	TAY
	STY @LOCAL09
	LDA #0
	STA @VIRTUAL04
	BRA @COMPUTE_ROW_COUNT
@FIXED_WIDTH_SETUP:
	LDY @LOCAL0C
	LDA @LOCAL0B
	DEC
	JSL MULT16
	LDY #window_stats::width
	CLC
	ADC (@LOCAL0A),Y
	LDY @LOCAL0B
	JSL DIVISION16S_DIVISOR_POSITIVE
	STA @LOCAL07
@COMPUTE_ROW_COUNT:
	LDY #window_stats::height
	LDA (@LOCAL0A),Y
	LSR
	TAX
	STX @LOCAL06
	LDY #window_stats::current_option
	LDA (@LOCAL0A),Y
	JSL COUNT_MENU_OPTION_CHAIN_FAR
	LDX @LOCAL06
	STX @VIRTUAL02
	LDY @LOCAL0B
	CLC
	ADC @LOCAL0B
	DEC
	JSL DIVISION16S_DIVISOR_POSITIVE
	CMP @VIRTUAL02
	BLTEQ @ROW_COUNT_READY
	DEX
	DEX
@ROW_COUNT_READY:
	STX @LOCAL06
	LDA #0
	STA @LOCAL08
	LDA #1
	STA @LOCAL05
@PAGE_LOOP:
	LDY #window_stats::text_y
	LDA (@LOCAL0A),Y
	STA @VIRTUAL02
	STA @LOCAL04
	LDA @LOCAL06
	STA @LOCAL0C
	JMP @ROW_LOOP_CHECK
@ROW_LOOP_INIT:
	LDX @LOCAL0B
	STX @LOCAL03
	JMP @COLUMN_LOOP_CHECK
@POSITION_OPTION:
	LDA @LOCAL0D
	BEQL @FIXED_WIDTH_POSITION
	LDA @VIRTUAL04
	CLC
	ADC #.LOWORD(MENU_OPTION_COLUMN_WIDTHS)
	STA @LOCAL02
	LDX @VIRTUAL04
	SEP #PROC_FLAGS::ACCUM8
	LDA (@LOCAL02)
	SEC
	SBC MENU_OPTION_LABEL_LENGTHS,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	PHA
	ASL
	PLA
	ROR
	ASL
	PHP
	LSR
	LSR
	LSR
	LSR
	PLP
	BCC @SKIP_SIGN_EXTEND_OFFSET
	ORA #$F000
@SKIP_SIGN_EXTEND_OFFSET:
	STA @VIRTUAL02
	LDA @LOCAL08
	CLC
	ADC @VIRTUAL02
	LDY @LOCAL09
	STA a:menu_option::text_x,Y
	LDA @LOCAL04
	STA @VIRTUAL02
	STA a:menu_option::text_y,Y
	LDA @LOCAL05
	STA a:menu_option::page,Y
	LDA a:menu_option::next,Y
	TAY
	CPY #.LOWORD(-1)
	BEQL @OPTIONS_EXHAUSTED
	LDA (@LOCAL02)
	AND #$00FF
	CLC
	ADC #7
	ASL
	PHP
	LSR
	LSR
	LSR
	LSR
	PLP
	BCC @SKIP_SIGN_EXTEND_ADVANCE
	ORA #$F000
@SKIP_SIGN_EXTEND_ADVANCE:
	STA @VIRTUAL02
	LDA @LOCAL08
	CLC
	ADC @VIRTUAL02
	STA @LOCAL08
	INC @VIRTUAL04
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	TAY
	STY @LOCAL09
	BRA @NEXT_COLUMN
@FIXED_WIDTH_POSITION:
	LDA @LOCAL08
	LDY @LOCAL09
	STA __BSS_START__+8,Y
	LDA @LOCAL04
	STA @VIRTUAL02
	STA __BSS_START__+10,Y
	LDA @LOCAL05
	STA __BSS_START__+6,Y
	LDA __BSS_START__+2,Y
	TAY
	CPY #.LOWORD(-1)
	BEQ @OPTIONS_EXHAUSTED
	LDA @LOCAL08
	CLC
	ADC @LOCAL07
	STA @LOCAL08
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	TAY
	STY @LOCAL09
@NEXT_COLUMN:
	LDX @LOCAL03
	DEX
	STX @LOCAL03
@COLUMN_LOOP_CHECK:
	BNEL @POSITION_OPTION
	LDA #0
	STA @LOCAL08
	LDA @LOCAL04
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL04
	DEC @LOCAL0C
@ROW_LOOP_CHECK:
	LDA @LOCAL0C
	BNEL @ROW_LOOP_INIT
	INC @LOCAL05
	JMP @PAGE_LOOP
@OPTIONS_EXHAUSTED:
	LDA @LOCAL0A
	CLC
	ADC #window_stats::current_option
	TAX
	STX @LOCAL07
	LDA __BSS_START__,X
	JSL COUNT_MENU_OPTION_CHAIN_FAR
	STA @LOCAL0D
	LDY #window_stats::height
	LDA (@LOCAL0A),Y
	LSR
	STA @VIRTUAL02
	LDY @LOCAL0B
	LDA @LOCAL0D
	CLC
	ADC @LOCAL0B
	DEC
	JSL DIVISION16S_DIVISOR_POSITIVE
	CMP @VIRTUAL02
	BLTEQ @DONE
	LDX @LOCAL07
	LDA __BSS_START__,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	TAX
	LDY @LOCAL0B
	DEY
	STY @LOCAL07
	BRA @FIND_LAST_PAGE_CHECK
@FIND_LAST_PAGE_BODY:
	DEY
	STY @LOCAL07
	LDA a:menu_option::next,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	TAX
@FIND_LAST_PAGE_CHECK:
	LDY @LOCAL07
	BNE @FIND_LAST_PAGE_BODY
	LOADPTR MENU_OVERFLOW_TEXT, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDY #window_stats::height
	LDA (@LOCAL0A),Y
	LSR
	TAY
	DEY
	LDX #0
	TXA
	JSL ADD_MENU_ITEM_FAR
	LDY #window_stats::option_count ; also .SIZEOF(menu_option) for the following multiplication
	LDA (@LOCAL0A),Y
	JSL MULT168
	TAX
	STZ MENU_OPTIONS + menu_option::page,X
@DONE:
	END_C_FUNCTION
