
OPEN_STATUS_MENU:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
@RESET_ALIGNMENT:
	LDA #1
	STA FORCE_LEFT_TEXT_ALIGNMENT
@CHAR_SELECT_LOOP:
	LOADPTR DISPLAY_STATUS_WINDOW, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDX #1
	LDA #0
	JSR CHAR_SELECT_PROMPT
	TAX
	BEQL @EXIT
	CPX #3
	BEQ @RESET_ALIGNMENT
	LDA #0
	STA @VIRTUAL02
	CREATE_WINDOW_NEAR #WINDOW::STATUS_PSI_CATEGORY
	LDA #0
	STA @LOCAL04
	BRA @CATEGORY_CHECK
@BUILD_CATEGORY_MENU:
	TAX
	INX
	STX @LOCAL03
	LOADPTR PSI_CATEGORIES, @VIRTUAL06
	LDA @LOCAL04
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	MOVE_INT_CONSTANT NULL, @LOCAL01
	TXA
	JSR ADD_MENU_ITEM_NO_POSITION
	LDX @LOCAL03
	TXA
	STA @LOCAL04
@CATEGORY_CHECK:
	CMP #4
	BCC @BUILD_CATEGORY_MENU
	LDY #0
	TYX
	LDA #1
	JSR OPEN_WINDOW_AND_PRINT_MENU
@CATEGORY_MENU_LOOP:
	LDA #WINDOW::STATUS_PSI_CATEGORY
	JSR SET_WINDOW_FOCUS
	LDA @VIRTUAL02
	BNE @SKIP_REPRINT
	JSR PRINT_MENU_ITEMS
	JSL WINDOW_TICK_WITHOUT_INSTANT_PRINTING
	INC @VIRTUAL02
@SKIP_REPRINT:
	CREATE_WINDOW_NEAR #WINDOW::STATUS_MENU
	LDA #WINDOW::STATUS_PSI_CATEGORY
	STA CURRENT_FOCUS_WINDOW
	STZ FORCE_LEFT_TEXT_ALIGNMENT
	LOADPTR GENERATE_BATTLE_PSI_LIST, @LOCAL00
	JSR SET_CURSOR_MOVE_CALLBACK
	LDA #1
	JSR SELECTION_MENU
	TAX
	STX @LOCAL02
	JSR CLEAR_CURSOR_MOVE_CALLBACK
	LDX @LOCAL02
	BEQ @CLOSE_CATEGORY
	LDA #1
	JSR GET_WINDOW_MENU_OPTION_COUNT
	CMP #0
	BEQ @CATEGORY_MENU_LOOP
	LDA #1
	JSR SET_WINDOW_FOCUS
	LDA #$00FF
	STA LAST_SELECTED_PSI_DESCRIPTION
	LOADPTR DISPLAY_PSI_DESCRIPTION, @LOCAL00
	JSR SET_CURSOR_MOVE_CALLBACK
@PSI_DESCRIPTION_LOOP:
	LDA #1
	JSR SELECTION_MENU
	CMP #0
	BNE @PSI_DESCRIPTION_LOOP
	JSR CLEAR_CURSOR_MOVE_CALLBACK
	LDA #WINDOW::PSI_TARGET_COST
	JSL CLOSE_WINDOW
	LDA #WINDOW::PSI_DESCRIPTION
	JSL CLOSE_WINDOW
	LDA #$00FF
	STA LAST_SELECTED_PSI_DESCRIPTION
	JMP @CATEGORY_MENU_LOOP
@CLOSE_CATEGORY:
	LDA #WINDOW::STATUS_PSI_CATEGORY
	JSL CLOSE_WINDOW
	LDA #WINDOW::TEXT_STANDARD
	JSL CLOSE_WINDOW
	LDA #WINDOW::STATUS_MENU
	STA CURRENT_FOCUS_WINDOW
	LDA #1
	STA FORCE_LEFT_TEXT_ALIGNMENT
	LDX @LOCAL02
	BEQL @CHAR_SELECT_LOOP
@EXIT:
	LDA #WINDOW::STATUS_MENU
	JSL CLOSE_WINDOW
	PLD
	RTS
