
OPEN_STATUS_MENU:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
@TOP_OF_LOOP:
@CHAR_SELECT_LOOP:
	LOADPTR DISPLAY_STATUS_WINDOW, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDX #1
	LDA #0
	JSR CHAR_SELECT_PROMPT
	TAX
	BEQL @EXIT
	CPX #3
	BEQ @CHAR_SELECT_LOOP
	CREATE_WINDOW_NEAR #WINDOW::STATUS_PSI_CATEGORY
	LDA #0
	STA @LOCAL03
	BRA @CATEGORY_CHECK
@BUILD_CATEGORY_ITEM:
	TAX
	INX
	STX @LOCAL02
	LOADPTR PSI_CATEGORIES, @VIRTUAL06
	LDA @LOCAL03
	OPTIMIZED_MULT @VIRTUAL04, 5
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	MOVE_INT_CONSTANT NULL, @LOCAL01
	TXA
	JSR ADD_MENU_ITEM_NO_POSITION
	LDX @LOCAL02
	TXA
	STA @LOCAL03
@CATEGORY_CHECK:
	CMP #4
	BCC @BUILD_CATEGORY_ITEM
	LDY #0
	TYX
	LDA #1
	JSR OPEN_WINDOW_AND_PRINT_MENU
@CATEGORY_MENU_LOOP:
	LDA #WINDOW::STATUS_PSI_CATEGORY
	JSR SET_WINDOW_FOCUS
	JSR PRINT_MENU_ITEMS
	LOADPTR GENERATE_BATTLE_PSI_LIST, @LOCAL00
	JSR SET_CURSOR_MOVE_CALLBACK
	LDA #1
	JSR SELECTION_MENU
	TAX
	STX @LOCAL02
	JSR CLEAR_CURSOR_MOVE_CALLBACK
	LDX @LOCAL02
	BEQ @CLOSE_CATEGORY
	LDA #1
	JSR GET_WINDOW_MENU_OPTION_COUNT
	CMP #0
	BEQ @CATEGORY_MENU_LOOP
	LDA #1
	JSR SET_WINDOW_FOCUS
	LOADPTR DISPLAY_PSI_DESCRIPTION, @LOCAL00
	JSR SET_CURSOR_MOVE_CALLBACK
@PSI_DESCRIPTION_LOOP:
	LDA #1
	JSR SELECTION_MENU
	CMP #0
	BNE @PSI_DESCRIPTION_LOOP
	JSR CLEAR_CURSOR_MOVE_CALLBACK
	LDA #WINDOW::PSI_TARGET_COST
	JSR CLOSE_WINDOW
	LDA #WINDOW::PSI_DESCRIPTION
	JSR CLOSE_WINDOW
	BRA @CATEGORY_MENU_LOOP
@CLOSE_CATEGORY:
	LDA #WINDOW::STATUS_PSI_CATEGORY
	JSR CLOSE_WINDOW
	LDA #WINDOW::TEXT_STANDARD
	JSR CLOSE_WINDOW
	LDX @LOCAL02
	BEQL @CHAR_SELECT_LOOP
@EXIT:
	LDA #WINDOW::STATUS_MENU
	JSR CLOSE_WINDOW
	END_C_FUNCTION
