
OPEN_TELEPHONE_MENU:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA #0
	STA @VIRTUAL02
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
	JSL SAVE_WINDOW_TEXT_ATTRIBUTES
	CREATE_WINDOW_NEAR #WINDOW::EQUIP_MENU_ITEMLIST
	LOADPTR PHONE_CALL_TEXT, @LOCAL00
	LDX #.SIZEOF(char_struct::name)
	LDA #7
	JSL SET_WINDOW_TITLE
	LDY #1
	STY @LOCAL03
	BRA @CONTACT_LOOP_CHECK
@PROCESS_CONTACT:
	LDA @LOCAL02
	CLC
	ADC #telephone_contact::event_flag
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	JSL GET_EVENT_FLAG
	CMP #0
	BEQ @NEXT_CONTACT
.IF .DEFINED(JPN)
	MOVE_INT @VIRTUAL0A, @LOCAL00
.ELSE
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
.ENDIF
	LDX #.SIZEOF(telephone_contact::label)
	LDA #.LOWORD(TEMPORARY_TEXT_BUFFER)
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	STZ TEMPORARY_TEXT_BUFFER + .SIZEOF(telephone_contact::label)
	REP #PROC_FLAGS::ACCUM8
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDY @LOCAL03
	TYA
	JSR ADD_MENU_ITEM_NO_POSITION
@NEXT_CONTACT:
	LDY @LOCAL03
	INY
	STY @LOCAL03
@CONTACT_LOOP_CHECK:
	LOADPTR TELEPHONE_CONTACTS_TABLE, @VIRTUAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(telephone_contact)
	STA @LOCAL02
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	BNEL @PROCESS_CONTACT
	LDA #0
	JSR GET_WINDOW_MENU_OPTION_COUNT
	CMP #0
	BEQ @CLOSE_MENU
	LDY #1
	LDX #0
	TYA
	JSR OPEN_WINDOW_AND_PRINT_MENU
	LDA #1
	JSR SELECTION_MENU
	STA @VIRTUAL02
@CLOSE_MENU:
	JSR CLOSE_FOCUS_WINDOW
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
	JSL RESTORE_WINDOW_TEXT_ATTRIBUTES
	LDA @VIRTUAL02
	END_C_FUNCTION
