
OVERWORLD_PSI_MENU:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FF
	STA @VIRTUAL01
	LDY #0
	STY @LOCAL09
	STZ ONLY_ONE_CHARACTER_WITH_PSI
@CHARACTER_SELECT:
	JSR COUNT_CHARACTERS_WITH_PSI
	.A16
	CMP #1
	BNE @MULTI_CHARACTER
	LDA @VIRTUAL01
	AND #$00FF
	BEQL @AFTER_CHAR_SELECT6
	JSR FIND_FIRST_CHARACTER_WITH_PSI
	TAX
	DEX
	SEP #PROC_FLAGS::ACCUM8
	LDA GAME_STATE + game_state::party_members,X
	STA @LOCAL08
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL08
	AND #$00FF
	JSL DISPLAY_CHARACTER_PSI_LIST
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA ONLY_ONE_CHARACTER_WITH_PSI
	BRA @AFTER_CHAR_SELECT
@MULTI_CHARACTER:
	.A16
	LDA #0
	JSR DISPLAY_MENU_HEADER_TEXT
	LOADPTR DISPLAY_CHARACTER_PSI_LIST, @LOCAL00
	LOADPTR CHECK_CHARACTER_PSI_AVAILABILITY_FAR, @LOCAL01
	LDX #1
	LDA #0
	JSR CHAR_SELECT_PROMPT
	SEP #PROC_FLAGS::ACCUM8
	STA @LOCAL08
	JSR CLOSE_MENU_HEADER_WINDOW
@AFTER_CHAR_SELECT:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL08
	AND #$00FF
	STA OVERWORLD_SELECTED_PSI_USER
	LDA @LOCAL08
	AND #$00FF
	BEQL @AFTER_CHAR_SELECT6
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FF
	STA @VIRTUAL01
@PSI_ABILITY_LOOP:
	REP #PROC_FLAGS::ACCUM8
	LDA #1
	JSR SET_WINDOW_FOCUS
	LDA @VIRTUAL01
	AND #$00FF
	CMP #$00FF
	BEQ @SKIP_REDISPLAY
	LDX #0
	JSR DISPLAY_PSI_ABILITY_DETAILS
	JSR PRINT_MENU_ITEMS
@SKIP_REDISPLAY:
	LOADPTR DISPLAY_PSI_TARGET_AND_COST, @LOCAL00
	JSR SET_CURSOR_MOVE_CALLBACK
	LDA #1
	JSR SELECTION_MENU
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL01
	JSR CLEAR_CURSOR_MOVE_CALLBACK
	.A16
	LDA @VIRTUAL01
	AND #$00FF
	BEQL @CANCELLED
	.A16
	LDA ONLY_ONE_CHARACTER_WITH_PSI
	AND #$00FF
	BNE @CHECK_PP_COST
	LDX #6
	LDA @VIRTUAL01
	AND #$00FF
	JSR DISPLAY_PSI_ABILITY_DETAILS
@CHECK_PP_COST:
	.A16
	LOADPTR PSI_ABILITY_TABLE, @VIRTUAL06
	LDA @VIRTUAL01
	AND #$00FF
	STA @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	STA @LOCAL07
	INC
	INC
	INC
	INC
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	STA @VIRTUAL02
	LDA @LOCAL08
	AND #$00FF
	TAX
	STX @LOCAL06
	TXA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	.A16
	PHA
	LDA @VIRTUAL02
	STA @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	ASL
	ASL
	TAX
	INX
	INX
	INX
	LDA f:BATTLE_ACTION_TABLE,X
	AND #$00FF
	PLX
	CMP PARTY_CHARACTERS+char_struct::current_pp,X
	BLTEQ @HAS_ENOUGH_PP
	CREATE_WINDOW_NEAR #WINDOW::TEXT_BATTLE
	.A16
	DISPLAY_TEXT_PTR MSG_BTL_PSI_CANNOT_MENU
	JSR CLOSE_FOCUS_WINDOW
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA @VIRTUAL00
	JMP @HANDLE_RESULT
@HAS_ENOUGH_PP:
	.A16
	LDA @LOCAL07
	INC
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	CMP #8
	BNE @NOT_TELEPORT
	LDA GAME_STATE+game_state::party_npc_1
	AND #$00FF
	CMP #PARTY_MEMBER::DUNGEON_MAN
	BEQ @TELEPORT_BLOCKED
	LDA GAME_STATE+game_state::party_npc_2
	AND #$00FF
	CMP #PARTY_MEMBER::DUNGEON_MAN
	BEQ @TELEPORT_BLOCKED
	LDA #EVENT_FLAG::FLG_SYS_DISTLPT
	JSL GET_EVENT_FLAG
	CMP #0
	BNE @TELEPORT_BLOCKED
	LDX GAME_STATE+game_state::walking_style
	CPX #WALKING_STYLE::LADDER
	BEQ @TELEPORT_BLOCKED
	CPX #WALKING_STYLE::ROPE
	BEQ @TELEPORT_BLOCKED
	CPX #WALKING_STYLE::ESCALATOR
	BEQ @TELEPORT_BLOCKED
	CPX #WALKING_STYLE::STAIRS
	BEQ @TELEPORT_BLOCKED
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL LOAD_SECTOR_ATTRS
	AND #MAP_SECTOR_CONFIG::CANNOT_TELEPORT
	BNE @TELEPORT_BLOCKED
	JSR OPEN_TELEPORT_DESTINATION_MENU
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	BRA @HANDLE_RESULT
@TELEPORT_BLOCKED:
	.A16
	CREATE_WINDOW_NEAR #WINDOW::TEXT_BATTLE
	DISPLAY_TEXT_PTR MSG_SYS_TLPT_NG
	JSR CLOSE_FOCUS_WINDOW
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA @VIRTUAL00
	BRA @HANDLE_RESULT
@NOT_TELEPORT:
	LDX @LOCAL06
	LDA @VIRTUAL02
	JSR DETERMINE_TARGETTING
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	BRA @HANDLE_RESULT
@CANCELLED:
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA @VIRTUAL00
@HANDLE_RESULT:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	AND #$00FF
	BEQL @PSI_ABILITY_LOOP
	LDA #WINDOW::PSI_TARGET_COST
	JSL CLOSE_WINDOW
	LDA @VIRTUAL01
	AND #$00FF
	BEQL @CHARACTER_SELECT
	LDA @LOCAL08
	AND #$00FF
	STA @VIRTUAL04
	STA @LOCAL09
	LOADPTR PSI_ABILITY_TABLE, @VIRTUAL06
	LDA @VIRTUAL01
	AND #$00FF
	STA @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	STA @VIRTUAL02
	LDY #1
	LDA @VIRTUAL02
	INC
	INC
	INC
	INC
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	STA @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	ASL
	ASL
	TAX
	INX
	INX
	INX
	LDA f:BATTLE_ACTION_TABLE,X
	AND #$00FF
	TAX
	LDA @LOCAL09
	STA @VIRTUAL04
	JSL REDUCE_PP_TARGET
	LDA @VIRTUAL02
	INC
	INC
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	CMP #8
	BNE @NOT_TELEPORT_ACTION
	LDA @VIRTUAL02
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	STA @LOCAL00
	LDA @VIRTUAL00
	JSL SET_TELEPORT_STATE
	JMP @EXECUTE_ACTION
@NOT_TELEPORT_ACTION:
	.A16
	LDA #.LOWORD(BATTLERS_TABLE)
	STA CURRENT_ATTACKER
	TAX
	LDA @VIRTUAL04
	JSL BATTLE_INIT_PLAYER_STATS
	LDX #.SIZEOF(char_struct::name)
	LDA @VIRTUAL04
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	JSR SET_BATTLE_ATTACKER_NAME
	LDA @VIRTUAL00
	AND #$00FF
	TAY
	CPY #$00FF
	BEQ @SKIP_TARGET_NAME
	LDX #5
	TYA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	JSR SET_BATTLE_TARGET_NAME
@SKIP_TARGET_NAME:
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL01
	JSR SET_CURRENT_ITEM
	.A16
	CREATE_WINDOW_NEAR #WINDOW::TEXT_STANDARD
	LOADPTR BATTLE_ACTION_TABLE, @VIRTUAL0A
	LDA @VIRTUAL01
	AND #$00FF
	STA @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	TAX
	INX
	INX
	INX
	INX
	LDA f:PSI_ABILITY_TABLE,X
	STA @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	ASL
	ASL
	INC
	INC
	INC
	INC
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
@EXECUTE_ACTION:
	.A16
	LOADPTR BATTLE_ACTION_TABLE, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL05
	LOADPTR PSI_ABILITY_TABLE, @VIRTUAL0A
	LDA @VIRTUAL01
	AND #$00FF
	STA @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	INC
	INC
	INC
	INC
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	STA @LOCAL04
	LDA @VIRTUAL0A+2
	STA @LOCAL04+2
	LDA [@VIRTUAL0A]
	STA @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	ASL
	ASL
	CLC
	ADC #8
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL06
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BEQL @AFTER_CHAR_SELECT5
	LDX #.LOWORD(BATTLERS_TABLE) + .SIZEOF(battler) * 1
	STX CURRENT_TARGET
	LDA @VIRTUAL00
	AND #$00FF
	TAY
	CPY #$00FF
	BNEL @AFTER_CHAR_SELECT0
	LDY #0
	STY @LOCAL06
	JMP @MULTI_CHARACTER7
@MULTI_CHARACTER2:
	TYA
	CLC
	ADC #.LOWORD(GAME_STATE) + game_state::party_members
	STA @VIRTUAL02
	LDX #5
	STX @LOCAL03
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	AND #$00FF
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	.A16
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	LDX @LOCAL03
	JSR SET_BATTLE_TARGET_NAME
	LDX #.LOWORD(BATTLERS_TABLE) + .SIZEOF(battler) * 1
	STX @LOCAL03
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	AND #$00FF
	LDX @LOCAL03
	JSL BATTLE_INIT_PLAYER_STATS
	LOADPTR BATTLE_ACTION_TABLE, @VIRTUAL0A
	LDA @VIRTUAL01
	AND #$00FF
	STA @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	TAX
	INX
	INX
	INX
	INX
	LDA f:PSI_ABILITY_TABLE,X
	STA @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	ASL
	ASL
	CLC
	ADC #8
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	PHA
	MOVE_INT @VIRTUAL06, TEMP_FUNCTION_POINTER
	PLA
	JSL JUMP_TEMP_FUNCTION_POINTER
	LDA #0
	STA @LOCAL02
	BRA @MULTI_CHARACTER4
@MULTI_CHARACTER3:
	LDA @LOCAL02
	STA @VIRTUAL02
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::afflictions
	CLC
	ADC @VIRTUAL02
	PHA
	LDA @LOCAL02
	CLC
	ADC CURRENT_TARGET
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__+29,X
	PLX
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	INC
	STA @LOCAL02
@MULTI_CHARACTER4:
	STA @VIRTUAL02
	LDA #7
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @MULTI_CHARACTER3
	LDY @LOCAL06
	INY
	STY @LOCAL06
@MULTI_CHARACTER7:
	STY @VIRTUAL02
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	CLC
	SBC @VIRTUAL02
	JUMPGTS @MULTI_CHARACTER2
	JMP @AFTER_CHAR_SELECT4
@AFTER_CHAR_SELECT0:
	TYA
	JSL BATTLE_INIT_PLAYER_STATS
	MOVE_INT @LOCAL04, @VIRTUAL0A
	LDA [@VIRTUAL0A]
	STA @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	ASL
	ASL
	CLC
	ADC #8
	MOVE_INTX @LOCAL05, @VIRTUAL06
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	PHA
	MOVE_INT @VIRTUAL06, TEMP_FUNCTION_POINTER
	PLA
	JSL JUMP_TEMP_FUNCTION_POINTER
	LDA #0
	STA @LOCAL06
	BRA @AFTER_CHAR_SELECT2
@AFTER_CHAR_SELECT1:
	LDA @LOCAL06
	STA @VIRTUAL02
	LDA @VIRTUAL00
	AND #$00FF
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::afflictions
	CLC
	ADC @VIRTUAL02
	PHA
	LDA @LOCAL06
	CLC
	ADC CURRENT_TARGET
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__+29,X
	PLX
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL06
	INC
	STA @LOCAL06
@AFTER_CHAR_SELECT2:
	STA @VIRTUAL02
	LDA #7
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @AFTER_CHAR_SELECT1
@AFTER_CHAR_SELECT4:
	JSL RENDER_AND_DISABLE_ENTITIES
@AFTER_CHAR_SELECT5:
	LDY #1
	STY @LOCAL09
@AFTER_CHAR_SELECT6:
	LDA #WINDOW::TEXT_STANDARD
	JSL CLOSE_WINDOW
	LDY @LOCAL09
	TYA
	END_C_FUNCTION
