
PRINT_MENU_AT_SELECTION:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
.IF .DEFINED(USA)
	STACK_RESERVE_INT16
.ENDIF
	STACK_RESERVE_INT16 "LOCAL01"
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL01
	CMP #.LOWORD(-1)
	BEQ @PRINT
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	TAY
.IF .DEFINED(USA)
	STY @LOCAL00
.ENDIF
	LDA @LOCAL01
	STA a:window_stats::selected_option,Y
	LDA a:window_stats::current_option,Y
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	TAX
	BRA @CHECK_SELECTION
@WALK_OPTIONS:
	DEC
	STA @LOCAL01
	LDA a:menu_option::next,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	TAX
@CHECK_SELECTION:
	LDA @LOCAL01
	BNE @WALK_OPTIONS
	LDA a:menu_option::page,X
.IF .DEFINED(USA)
	LDY @LOCAL00
.ENDIF
	STA a:window_stats::menu_page_number,Y
@PRINT:
	JSR PRINT_MENU_ITEMS
	END_C_FUNCTION
