
RUN_TOWN_MAP_MENU:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX #0
	STX @LOCAL01
	TXY
	STY @LOCAL00
	LDA #60
	STA TOWN_MAP_ANIMATION_FRAME
	LDA #20
	STA TOWN_MAP_PLAYER_ICON_ANIMATION_FRAME
	LDA #12
	STA FRAMES_UNTIL_MAP_ICON_PALETTE_UPDATE
	TXA
	JSR LOAD_TOWN_MAP_DATA
@MAIN_LOOP:
	JSL WAIT_UNTIL_NEXT_FRAME
	JSL OAM_CLEAR
	LDA PAD_PRESS
	AND #PAD::UP
	BEQ @CHECK_DOWN
	LDX @LOCAL01
	DEX
	STX @LOCAL01
@CHECK_DOWN:
	LDA PAD_PRESS
	AND #PAD::DOWN
	BEQ @WRAP_UNDERFLOW
	LDX @LOCAL01
	INX
	STX @LOCAL01
@WRAP_UNDERFLOW:
	LDX @LOCAL01
	CPX #.LOWORD(-1)
	BNE @WRAP_OVERFLOW
	LDX #5
	STX @LOCAL01
@WRAP_OVERFLOW:
	CPX #6
	BNE @CHECK_MAP_CHANGE
	LDX #0
	STX @LOCAL01
@CHECK_MAP_CHANGE:
	STX @VIRTUAL02
	LDY @LOCAL00
	TYA
	CMP @VIRTUAL02
	BEQ @RENDER
	TXA
	JSR LOAD_TOWN_MAP_DATA
	LDX @LOCAL01
	TXY
	STY @LOCAL00
@RENDER:
	TXA
	JSR RENDER_TOWN_MAP_ICONS
	LDA PAD_PRESS
	AND #PAD::A_BUTTON
	BNE @EXIT
	JSL UPDATE_SCREEN
	BRA @MAIN_LOOP
@EXIT:
	JSL UNDRAW_FLYOVER_TEXT
	JSL RELOAD_MAP
	SEP #PROC_FLAGS::ACCUM8
	LDA #$17
	STA TM_MIRROR
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
