
SELECTION_MENU_WITH_FOCUS:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXY
	STY @LOCAL01
	TAX
	STX @LOCAL00
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
	JSL SAVE_WINDOW_TEXT_ATTRIBUTES
	LDX @LOCAL00
	TXA
	JSR SET_WINDOW_FOCUS
	LDY @LOCAL01
	TYA
	JSR SELECTION_MENU
	TAX
	STX @LOCAL00
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
	JSL RESTORE_WINDOW_TEXT_ATTRIBUTES
	LDX @LOCAL00
	TXA
	END_C_FUNCTION
