
ADJUST_PARTY_MEMBER_VISIBILITY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @LOCAL00
	STX @VIRTUAL02
	TAX
	LDA @PARAM03
	STA @VIRTUAL04
	TXA
	JSL GET_DISTANCE_TO_PARTY_MEMBER
	CMP @VIRTUAL02
	BNE @DISTANCE_TOO_FAR
	LDY @LOCAL00
	INY
	STY @LOCAL00
	LDA CURRENT_ENTITY_SLOT
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SCRIPT_VAR7_TABLE)
	TAX
	LDA __BSS_START__,X
	AND #$FFFF ^ SPRITE_TABLE_10_FLAGS::SPACING_HIDE
	STA __BSS_START__,X
	BRA @FINISH
@DISTANCE_TOO_FAR:
	CMP @VIRTUAL02
	BLTEQ @FINISH
	LDY @LOCAL00
	TYA
	CLC
	ADC @VIRTUAL04
	TAY
	STY @LOCAL00
	LDA CURRENT_ENTITY_SLOT
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SCRIPT_VAR7_TABLE)
	TAX
	LDA __BSS_START__,X
	ORA #SPRITE_TABLE_10_FLAGS::SPACING_HIDE
	STA __BSS_START__,X
@FINISH:
	LDY @LOCAL00
	TYA
	END_C_FUNCTION
