
CHECK_FOLLOWER_VERTICAL_DISTANCE:
	.A16
	LDX $88
	LDA ENTITY_SCREEN_X_TABLE,Y
	EOR ENTITY_SCREEN_X_TABLE,X
	BNE @RETURN
	LDA ENTITY_ABS_Y_TABLE,Y
	SEC
	SBC ENTITY_ABS_Y_TABLE,X
	BPL @ABS_Y_DONE
	EOR #$FFFF
	INC
@ABS_Y_DONE:
	LDY ENTITY_SCRIPT_VAR5_TABLE,X
	TYX
	SEC
	SBC f:FOLLOWER_SPACING_THRESHOLDS,X
	BPL @ABS_EXCESS_DONE
	EOR #$FFFF
	INC
@ABS_EXCESS_DONE:
	BEQ @RETURN
	DEC
@RETURN:
	RTS
