
CLEAR_PARTY_SPRITE_HIDE_FLAGS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA PLAYER_INTANGIBILITY_FRAMES
	BEQ @RETURN
	LDA #24
	STA @LOCAL00
	BRA @CHECK_SLOT
@CLEAR_HIDE_BIT:
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAX
	LDA __BSS_START__,X
	AND #$7FFF
	STA __BSS_START__,X
	LDA @LOCAL00
	INC
	STA @LOCAL00
@CHECK_SLOT:
	CMP #MAX_ENTITIES
	BCC @CLEAR_HIDE_BIT
@RETURN:
	END_C_FUNCTION
