
GET_DISTANCE_TO_PARTY_MEMBER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	JSR GET_PREVIOUS_POSITION_INDEX
	STA @LOCAL00
	LDX CURRENT_PARTY_MEMBER_TICK
	LDA a:char_struct::position_index,X
	STA @VIRTUAL02
	LDA @LOCAL00
	CMP @VIRTUAL02
	BCS @WRAP_AROUND
	CLC
	ADC #256
@WRAP_AROUND:
	SEC
	SBC @VIRTUAL02
	END_C_FUNCTION
