
GET_PREVIOUS_PARTY_POSITION:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL00
	LDX #0
	BRA @COMPARE_PARTY_ORDER
@NEXT_INDEX:
	INX
@COMPARE_PARTY_ORDER:
	LDA @LOCAL00
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA GAME_STATE + game_state::party_order,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @NEXT_INDEX
	CPX #0
	BNE @GET_PREVIOUS
	LDA #.LOWORD(-1)
	BRA @RETURN
@GET_PREVIOUS:
	DEX
	LDA GAME_STATE + game_state::party_order,X
	AND #$00FF
@RETURN:
	END_C_FUNCTION
