
GET_PARTY_MEMBER_SPRITE_ID:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @VIRTUAL04
	STX @LOCAL02
	STA @LOCAL01
	LDY #0
	LDA MOVING_PARTY_MEMBER_ENTITY_ID
	STA @VIRTUAL02
	LDA @LOCAL01
	BNE @CLEAR_OVERLAY
	LDA DISABLED_TRANSITIONS
	BNE @CLEAR_OVERLAY
	LDA PAJAMA_FLAG
	BEQ @CLEAR_OVERLAY
	LDA #OVERWORLD_SPRITE::NESS_IN_PJS
	JMP @RETURN
@CLEAR_OVERLAY:
	LDA @VIRTUAL02
	CMP #.LOWORD(-1)
	BEQ @CHECK_PARTY_STATUS
	LDA @VIRTUAL02
	ASL
	TAX
	STZ ENTITY_OVERLAY_FLAGS,X
@CHECK_PARTY_STATUS:
	LDA GAME_STATE + game_state::party_status
	AND #$00FF
	CMP #1
	BNE @CHECK_AFFLICTIONS
	LDA GAME_STATE + game_state::character_mode
	CMP #3
	BEQ @STATUS1_SMALL_MODE
	LDA #13
	JMP @RETURN
@STATUS1_SMALL_MODE:
	LDA #37
	JMP @RETURN
@CHECK_AFFLICTIONS:
	LDX @VIRTUAL04
	LDA a:char_struct::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BEQ @SET_UNCONSCIOUS
	CMP #STATUS_0::DIAMONDIZED
	BEQ @DIAMONDIZED
	CMP #STATUS_0::NAUSEOUS
	BEQ @NAUSEOUS
	BRA @CHECK_HARDHEAL
@SET_UNCONSCIOUS:
	LDY #1
	BRA @CHECK_HARDHEAL
@DIAMONDIZED:
	LDA GAME_STATE + game_state::character_mode
	CMP #3
	BEQ @DIAMONDIZED_SMALL_MODE
	LDA #12
	JMP @RETURN
@DIAMONDIZED_SMALL_MODE:
	LDA #36
	JMP @RETURN
@NAUSEOUS:
	LDA @VIRTUAL02
	CMP #.LOWORD(-1)
	BEQ @CHECK_HARDHEAL
	LDA @VIRTUAL02
	ASL
	CLC
	ADC #.LOWORD(ENTITY_OVERLAY_FLAGS)
	TAX
	LDA __BSS_START__,X
	ORA #$8000
	STA __BSS_START__,X
@CHECK_HARDHEAL:
	LDX @VIRTUAL04
	LDA a:char_struct::afflictions + STATUS_GROUP::PERSISTENT_HARDHEAL,X
	AND #$00FF
	CMP #STATUS_1::MUSHROOMIZED
	BEQ @MUSHROOMIZED
	CMP #STATUS_1::POSSESSED
	BEQ @POSSESSED
	BRA @CHECK_BICYCLE
@MUSHROOMIZED:
	LDA @VIRTUAL02
	CMP #.LOWORD(-1)
	BEQ @CHECK_BICYCLE
	LDA @VIRTUAL02
	ASL
	CLC
	ADC #.LOWORD(ENTITY_OVERLAY_FLAGS)
	TAX
	LDA __BSS_START__,X
	ORA #$4000
	STA __BSS_START__,X
	BRA @CHECK_BICYCLE
@POSSESSED:
	INC POSSESSED_PLAYER_COUNT
@CHECK_BICYCLE:
	LDA GAME_STATE + game_state::character_mode
	CMP #6
	BEQ @MODE_BICYCLE
	CMP #4
	BEQ @MODE_GHOST
	BRA @DETERMINE_CHAR_COLUMN
@MODE_BICYCLE:
	LDA #7
	JMP @RETURN
@MODE_GHOST:
	LDX @VIRTUAL04
	LDA a:char_struct::unknown53,X
	BNE @DETERMINE_CHAR_COLUMN
	LDA #6
	JMP @RETURN
@DETERMINE_CHAR_COLUMN:
	CPY #0
	BNE @APPLY_MODE_OFFSET
	LDA @LOCAL02
	BEQ @CHAR_NESS
	CMP #12
	BEQ @CHAR_NESS
	CMP #13
	BEQ @CHAR_NESS
	CMP #4
	BEQ @CHAR_PAULA
	CMP #7
	BEQ @CHAR_JEFF
	CMP #8
	BEQ @CHAR_POO
	BRA @APPLY_MODE_OFFSET
@CHAR_NESS:
	LDY #0
	BRA @APPLY_MODE_OFFSET
@CHAR_PAULA:
	LDY #1
	BRA @APPLY_MODE_OFFSET
@CHAR_JEFF:
	LDY #2
	BRA @APPLY_MODE_OFFSET
@CHAR_POO:
	LDY #3
@APPLY_MODE_OFFSET:
	LDX GAME_STATE + game_state::character_mode
	CPX #3
	BNE @CHECK_ROBOT_MODE
	INY
	INY
	INY
	INY
	LDA @VIRTUAL02
	ASL
	TAX
	STZ ENTITY_OVERLAY_FLAGS,X
	BRA @SET_WALK_SPEED
@CHECK_ROBOT_MODE:
	CPX #5
	BNE @SET_WALK_SPEED
	CPY #0
	BNE @SET_WALK_SPEED
	TYA
	CLC
	ADC #6
	TAY
@SET_WALK_SPEED:
	LDA GAME_STATE + game_state::party_status
	AND #$00FF
	CMP #3
	BNE @CHECK_UNCONSCIOUS_SPEED
	LDA @VIRTUAL02
	ASL
	TAX
	LDA #5
	STA ENTITY_SCRIPT_VAR3_TABLE,X
	BRA @CHECK_PARALYZED
@CHECK_UNCONSCIOUS_SPEED:
	LDX @VIRTUAL04
	LDA a:char_struct::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BNE @CHECK_SURFACE_FLAGS
	LDA @VIRTUAL02
	ASL
	TAX
	LDA #16
	STA ENTITY_SCRIPT_VAR3_TABLE,X
	BRA @CHECK_PARALYZED
@CHECK_SURFACE_FLAGS:
	LDA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_SURFACE_FLAGS,X
	STA @LOCAL00
	AND #$000C
	CMP #12
	BNE @CHECK_SHALLOW_WATER
	LDA #24
	STA ENTITY_SCRIPT_VAR3_TABLE,X
	BRA @CHECK_PARALYZED
@CHECK_SHALLOW_WATER:
	LDA @LOCAL00
	AND #$0008
	CMP #8
	BNE @SPEED_NORMAL
	LDA #16
	STA ENTITY_SCRIPT_VAR3_TABLE,X
	BRA @CHECK_PARALYZED
@SPEED_NORMAL:
	LDA #8
	STA ENTITY_SCRIPT_VAR3_TABLE,X
@CHECK_PARALYZED:
	LDX @VIRTUAL04
	LDA a:char_struct::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	CMP #STATUS_0::PARALYZED
	BNE @LOOKUP_SPRITE
	LDA @VIRTUAL02
	ASL
	TAX
	LDA #56
	STA ENTITY_SCRIPT_VAR3_TABLE,X
@LOOKUP_SPRITE:
	TYA
	ASL
	STA @VIRTUAL02
	LDA @LOCAL01
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL02
	TAX
	LDA f:PLAYABLE_CHAR_GFX_TABLE,X
@RETURN:
	PLD
	RTL
