
INITIALIZE_PARTY_MEMBER_ANIMATIONS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	SEP #PROC_FLAGS::ACCUM8
	STZ GAME_STATE + game_state::party_status
	REP #PROC_FLAGS::ACCUM8
	LDA #24
	STA @LOCAL00
	BRA @LOOP_CHECK
@LOOP_BODY:
	ASL
	TAX
	LDA #8
	STA ENTITY_SCRIPT_VAR3_TABLE,X
	LDA @LOCAL00
	INC
	STA @LOCAL00
@LOOP_CHECK:
	CMP #29
	BLTEQ @LOOP_BODY
	END_C_FUNCTION
