
LOAD_PARTY_AT_MAP_POSITION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
.IF .DEFINED(JPN)
	STACK_RESERVE_INT16 "LOCALM2"
.ENDIF
	STACK_RESERVE_INT16 "LOCAL05"
	STACK_RESERVE_INT16 "LOCAL06"
	STACK_RESERVE_INT16 "LOCAL07"
	STACK_RESERVE_INT16 "LOCAL08"
	STACK_RESERVE_INT16 "LOCAL09"
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
.IF .DEFINED(JPN)
	@LOCAL07ALT := @LOCALM2
	@LOCAL08ALT := @LOCAL07
.ELSE
	@LOCAL07ALT := @LOCAL07
	@LOCAL08ALT := @LOCAL08
.ENDIF
	STA @LOCAL09
	LDA CURRENT_TELEPORT_DESTINATION_X
	ORA CURRENT_TELEPORT_DESTINATION_Y
	BEQ @USE_LEADER_COORDS
	LDA CURRENT_TELEPORT_DESTINATION_X
	OPTIMIZED_MULT @VIRTUAL04, 8
	STA @LOCAL08
	LDA CURRENT_TELEPORT_DESTINATION_Y
	OPTIMIZED_MULT @VIRTUAL04, 8
	TAX
	BRA @LOAD_SECTOR
@USE_LEADER_COORDS:
	LDA GAME_STATE+game_state::leader_x_coord
	STA @LOCAL08
	LDX GAME_STATE+game_state::leader_y_coord
@LOAD_SECTOR:
	LDA @LOCAL08
	JSL LOAD_SECTOR_ATTRS
	AND #$0007
	STA @LOCAL07
	STA GAME_STATE+game_state::character_mode
	ASL
	STA FOOTSTEP_SOUND_ID
	STZ FOOTSTEP_SOUND_ID_OVERRIDE
	LDA @LOCAL07
	CMP #3
	BEQ @SMALL_PARTY_MODE
	STZ GAME_STATE+game_state::walking_style
	BRA @BEGIN_ENTITY_LOOP
@SMALL_PARTY_MODE:
	LDA #WALKING_STYLE::SLOWEST
	STA GAME_STATE+game_state::walking_style
@BEGIN_ENTITY_LOOP:
	LDA CURRENT_ENTITY_SLOT
	STA @LOCAL06
	LDA #.LOWORD(-1)
	STA CURRENT_ENTITY_SLOT
	STZ @LOCAL05
	JMP @CHECK_PARTY_INDEX
@ENTITY_LOOP_BODY:
.IF .DEFINED(JPN)
	LDA @LOCAL05
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_order,X
.ELSE
	LDY #.LOWORD(GAME_STATE) + game_state::party_order
	LDA (@LOCAL05),Y
.ENDIF
	AND #$00FF
	TAX
	BEQL @NEXT_PARTY_MEMBER
	TXA
	DEC
	STA @VIRTUAL04
	LDA @LOCAL05
	ASL
.IF .DEFINED(JPN)
	STA @LOCALM2
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_entity_slots,X
.ELSE
	TAY
	LDA GAME_STATE + game_state::party_entity_slots,Y
.ENDIF
	STA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR0_TABLE,X
	STA NEW_ENTITY_VAR0
	LDA ENTITY_SCRIPT_VAR1_TABLE,X
	STA NEW_ENTITY_VAR1
.IF .DEFINED(JPN)
	LDA @LOCALM2
	STA NEW_ENTITY_VAR5
.ELSE
	STY NEW_ENTITY_VAR5
.ENDIF
	LDA ENTITY_SPRITEMAP_POINTER_HIGH,X
	STA @LOCAL03
	LDA ENTITY_TICK_CALLBACK_HIGH,X
	STA @LOCAL07ALT
	LDA @VIRTUAL02
	JSL REMOVE_ENTITY
	LDA @VIRTUAL02
	STA MOVING_PARTY_MEMBER_ENTITY_ID
	LDA GAME_STATE+game_state::character_mode
	CMP #3
	BEQ @SMALL_MODE_SPRITE
	LDA @LOCAL05
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	TAY
	LDX #0
	LDA @VIRTUAL04
	JSL GET_PARTY_MEMBER_SPRITE_ID
	STA @LOCAL08ALT
	LDA GAME_STATE+game_state::leader_x_coord
	STA @LOCAL00
	LDA GAME_STATE+game_state::leader_y_coord
	STA @LOCAL01
	LDY @VIRTUAL02
	LDA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(character_initial_entity_entry)
	TAX
	INX
	INX
	INX
	INX
	LDA f:CHARACTER_INITIAL_ENTITY_DATA,X ;character_initial_entity_entry::actionscript_id
	TAX
	LDA @LOCAL08ALT
	JSL CREATE_ENTITY
	STA @LOCAL02
	BRA @RESTORE_ENTITY_STATE
@SMALL_MODE_SPRITE:
	LDA @LOCAL05
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	TAY
	LDX #10
	LDA @VIRTUAL04
	JSL GET_PARTY_MEMBER_SPRITE_ID
	STA @LOCAL08ALT
	LDA GAME_STATE+game_state::leader_x_coord
	STA @LOCAL00
	LDA GAME_STATE+game_state::leader_y_coord
	STA @LOCAL01
	LDY @VIRTUAL02
	LDA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(character_initial_entity_entry)
	TAX
	INX
	INX
	INX
	INX
	LDA f:CHARACTER_INITIAL_ENTITY_DATA,X ;character_initial_entity_entry::actionscript_id
	TAX
	LDA @LOCAL08ALT
	JSL CREATE_ENTITY
	STA @LOCAL02
@RESTORE_ENTITY_STATE:
	ASL
	TAX
	LDA @LOCAL03
	STA ENTITY_SPRITEMAP_POINTER_HIGH,X
	LDA @LOCAL07ALT
	STA ENTITY_TICK_CALLBACK_HIGH,X
	LDA @LOCAL09
	STA ENTITY_DIRECTIONS,X
	STZ ENTITY_ANIMATION_FRAME,X
	LDA @LOCAL02
	JSL UPDATE_ENTITY_SPRITE
@NEXT_PARTY_MEMBER:
	INC @LOCAL05
@CHECK_PARTY_INDEX:
	LDA @LOCAL05
	CMP #6
	BCCL @ENTITY_LOOP_BODY
	LDA @LOCAL06
	STA CURRENT_ENTITY_SLOT
	JSL SNAP_PARTY_TO_LEADER
	LDA #.LOWORD(-1)
	STA LADDER_STAIRS_TILE_X
	LDA PENDING_INTERACTIONS
	STA @VIRTUAL02
	STZ PENDING_INTERACTIONS
	LDA #4
	STA @LOCAL00
	LDY GAME_STATE+game_state::current_party_members
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL CHECK_DIRECTIONAL_COLLISION
	LDA @VIRTUAL02
	STA PENDING_INTERACTIONS
	LDA LADDER_STAIRS_TILE_X
	CMP #.LOWORD(-1)
	BEQ @DONE
	LDX LADDER_STAIRS_TILE_Y
	LDA LADDER_STAIRS_TILE_X
	JSL PROCESS_DOOR_AT_TILE
@DONE:
	PLD
	RTL
