
SCHEDULE_PARTY_ANIMATION_RESET:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAY
	LDX #.LOWORD(GAME_STATE) + game_state::party_status
	LDA __BSS_START__,X
	AND #$00FF
	CMP #3
	BEQ @ALREADY_DONE
	SEP #PROC_FLAGS::ACCUM8
	LDA #3
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA #24
	STA @LOCAL01
	BRA @LOOP_CHECK
@LOOP_BODY:
	ASL
	TAX
	LDA #5
	STA ENTITY_SCRIPT_VAR3_TABLE,X
	LDA @LOCAL01
	INC
	STA @LOCAL01
@LOOP_CHECK:
	CMP #29
	BLTEQ @LOOP_BODY
	LOADPTR INITIALIZE_PARTY_MEMBER_ANIMATIONS, @LOCAL00
	TYA
	JSL SCHEDULE_OVERWORLD_TASK
@ALREADY_DONE:
	END_C_FUNCTION
