
SET_LEADER_POSITION_AND_LOAD_PARTY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @VIRTUAL02
	STA @LOCAL00
	STA GAME_STATE+game_state::leader_x_coord
	STX GAME_STATE+game_state::leader_y_coord
	LDA @VIRTUAL02
	STA GAME_STATE+game_state::leader_direction
	LDY GAME_STATE+game_state::current_party_members
	LDA @LOCAL00
	JSL LOOKUP_SURFACE_FLAGS
	STA GAME_STATE+game_state::trodden_tile_type
	LDA @VIRTUAL02
	JSL LOAD_PARTY_AT_MAP_POSITION
	JSL INIT_PARTY_POSITION_BUFFER
	LDA #0
	STA @LOCAL00
	BRA @CHECK_FINGERPRINT_INDEX
@CLEAR_FINGERPRINT:
	ASL
	TAX
	LDA #.LOWORD(-1)
	STA ENTITY_ANIMATION_FINGERPRINTS + 24 * 2,X
	LDA @LOCAL00
	INC
	STA @LOCAL00
@CHECK_FINGERPRINT_INDEX:
	CMP #TOTAL_PARTY_COUNT
	BCC @CLEAR_FINGERPRINT
	LDA #.LOWORD(-1)
	STA MINI_GHOST_ENTITY_ID
	STZ CURRENT_TELEPORT_DESTINATION_Y
	STZ CURRENT_TELEPORT_DESTINATION_X
	LDA f:NESS_PAJAMA_FLAG
	JSL GET_EVENT_FLAG
	STA PAJAMA_FLAG
	JSL REFRESH_PARTY_ENTITIES
	END_C_FUNCTION
