
SNAP_PARTY_TO_LEADER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDY #0
	STY @LOCAL01
	BRA @LOOP_CHECK
@PROCESS_MEMBER:
.IF .DEFINED(JPN)
	TYA
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_order,X
.ELSE
	LDA GAME_STATE+game_state::party_order,Y
.ENDIF
	AND #$00FF
	BEQ @NEXT_MEMBER
	TYA
	ASL
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_entity_slots,X
.ELSE
	TAX
	LDA GAME_STATE+game_state::party_entity_slots,X
.ENDIF
	STA @LOCAL00
	ASL
	TAX
	LDA GAME_STATE+game_state::leader_x_coord
	STA ENTITY_ABS_X_TABLE,X
	LDA GAME_STATE+game_state::leader_y_coord
	STA ENTITY_ABS_Y_TABLE,X
	LDA @LOCAL00
	JSL ENTITY_SCREEN_COORDS_BY_ID
@NEXT_MEMBER:
	LDY @LOCAL01
	INY
	STY @LOCAL01
@LOOP_CHECK:
	CPY #6
	BCC @PROCESS_MEMBER
	END_C_FUNCTION
