
UPDATE_PARTY_SPRITE_POSITION:
	.A8
	LDX $88
	CPX CURRENT_LEADING_PARTY_MEMBER_ENTITY
	BEQ @USE_ABSOLUTE_POSITION
	LDA ENTITY_SCRIPT_VAR7_TABLE,X
	AND #$0000
	CLC
	BNE @USE_ABSOLUTE_POSITION
	LDA NOT_MOVING_IN_SAME_DIRECTION_FACED
	BNE @USE_ABSOLUTE_POSITION
	LDA ENTITY_DIRECTIONS,X
	CMP CURRENT_LEADER_DIRECTION
	BNE @USE_ABSOLUTE_POSITION
	ASL
	TAX
	LDY CURRENT_LEADING_PARTY_MEMBER_ENTITY
	JSR (.LOWORD(FOLLOWER_DISTANCE_CHECK_TABLE),X)
	ASL
	BEQ @DONE
@USE_ABSOLUTE_POSITION:
	LDX $88
	LDA ENTITY_ABS_X_TABLE,X
	SEC
	SBC BG1_X_POS
	STA ENTITY_SCREEN_X_TABLE,X
	LDA ENTITY_ABS_Y_TABLE,X
	SEC
	SBC BG1_Y_POS
	STA ENTITY_SCREEN_Y_TABLE,X
@DONE:
	LDX $88
	RTS
