
UPDATE_NPC_PARTY_LINEUP:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT8
	END_STACK_VARS
	LDY #0
	BRA @CHECK_MEMBER
@NEXT_MEMBER:
	INY
@CHECK_MEMBER:
	TYA
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
	AND #$00FF
	BEQ @FOUND_PLAYER_COUNT
	AND #$00FF
	STA @VIRTUAL02
	LDA #5
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @NEXT_MEMBER
@FOUND_PLAYER_COUNT:
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA GAME_STATE+game_state::player_controlled_party_count
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(GAME_STATE)+game_state::party_npc_1
	STA @VIRTUAL04
	LDX @VIRTUAL04
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL04
	REP #PROC_FLAGS::ACCUM8
	TYA
	CLC
	ADC #.LOWORD(GAME_STATE)
	CLC
	ADC #game_state::party_members
	STA @LOCAL03
	SEP #PROC_FLAGS::ACCUM8
	LDA (@LOCAL03)
	STA @VIRTUAL00
	LDA @LOCAL04
	CMP @VIRTUAL00
	BEQL @NPC1_MATCHES
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(GAME_STATE)+game_state::party_npc_2
	STA @VIRTUAL02
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @VIRTUAL01
	CMP @VIRTUAL00
	BNE @NPC2_MISMATCH
	LDA @VIRTUAL01
	LDX @VIRTUAL04
	STA __BSS_START__,X
	LDX #.LOWORD(GAME_STATE)+game_state::party_npc_2_hp
	STX @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA GAME_STATE+game_state::party_npc_1_hp
	SEP #PROC_FLAGS::ACCUM8
	LDA GAME_STATE + game_state::party_members + 1,Y
	LDX @VIRTUAL02
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	ASL
	TAX
	INX
	LDA f:NPC_AI_TABLE,X
	AND #$00FF
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::hp
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	LDX @LOCAL02
	STA __BSS_START__,X
	JMP @DONE
@NPC2_MISMATCH:
	LDA @LOCAL04
	CMP GAME_STATE + game_state::party_members + 1,Y
	BNE @REASSIGN_BOTH_NPCS
	LDX @VIRTUAL02
	STA __BSS_START__,X
	LDX #.LOWORD(GAME_STATE)+game_state::party_npc_1_hp
	STX @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA GAME_STATE+game_state::party_npc_2_hp
	SEP #PROC_FLAGS::ACCUM8
	LDA (@LOCAL03)
	LDX @VIRTUAL04
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	ASL
	TAX
	INX
	LDA f:NPC_AI_TABLE,X
	AND #$00FF
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::hp
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	LDX @LOCAL02
	STA __BSS_START__,X
	JMP @DONE
@REASSIGN_BOTH_NPCS:
	LDA @VIRTUAL00
	LDX @VIRTUAL04
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	TYA
	INC
	STA @LOCAL02
	LOADPTR ENEMY_CONFIGURATION_TABLE, @VIRTUAL0A
	LOADPTR NPC_AI_TABLE, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDA @VIRTUAL00
	AND #$00FF
	ASL
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::hp
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	STA GAME_STATE+game_state::party_npc_1_hp
	LDA @LOCAL02
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA a:game_state::party_members,X
	STA @LOCAL00
	STA @VIRTUAL00
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	CMP @VIRTUAL00
	BEQL @DONE
	LDA @LOCAL00
	LDX @VIRTUAL02
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	ASL
	INC
	MOVE_INTX @LOCAL01, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::hp
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	STA GAME_STATE+game_state::party_npc_2_hp
	BRA @DONE
@NPC1_MATCHES:
	REP #PROC_FLAGS::ACCUM8
	TYA
	INC
	LDX #.LOWORD(GAME_STATE) + game_state::party_npc_2
	STX @LOCAL02
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA a:game_state::party_members,X
	STA @LOCAL00
	STA @VIRTUAL00
	LDX @LOCAL02
	LDA __BSS_START__,X
	CMP @VIRTUAL00
	BEQ @DONE
	LDA @LOCAL00
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	ASL
	TAX
	INX
	LDA f:NPC_AI_TABLE,X
	AND #$00FF
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::hp
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	STA GAME_STATE+game_state::party_npc_2_hp
@DONE:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
