
ALLOC_SPRITE_MEM:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TXY
	STA @LOCAL00
	LDX #0
	BRA @LOOP_CHECK
@CHECK_ENTRY:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	ORA #$0080
	STA @VIRTUAL02
	LDA SPRITE_VRAM_TABLE,X
	AND #$00FF
	CMP @VIRTUAL02
	BEQ @WRITE_ENTRY
	LDA @LOCAL00
	CMP #$8000
	BNE @NEXT_ENTRY
@WRITE_ENTRY:
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA SPRITE_VRAM_TABLE,X
@NEXT_ENTRY:
	INX
@LOOP_CHECK:
	CPX #88
	BCC @CHECK_ENTRY
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
