
ANIMATE_PALETTE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA OVERWORLD_PALETTE_ANIM + overworld_palette_anim::timer
	DEC
	STA OVERWORLD_PALETTE_ANIM + overworld_palette_anim::timer
	BNE @DONE
	LDX #.LOWORD(OVERWORLD_PALETTE_ANIM) + overworld_palette_anim::index
	STX @LOCAL00
	LDA __BSS_START__,X
	ASL
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(OVERWORLD_PALETTE_ANIM)
	TAX
	LDA a:overworld_palette_anim::delays,X
.ELSE
	TAX
	LDA OVERWORLD_PALETTE_ANIM + overworld_palette_anim::delays,X
.ENDIF
	BNE @LOAD_PALETTE_FRAME
	LDA #0
	LDX @LOCAL00
	STA __BSS_START__,X
@LOAD_PALETTE_FRAME:
	LDX #.LOWORD(OVERWORLD_PALETTE_ANIM) + overworld_palette_anim::index
	STX @LOCAL00
	LDA __BSS_START__,X
	ASL
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(OVERWORLD_PALETTE_ANIM)
	TAX
	LDA a:overworld_palette_anim::delays,X
.ELSE
	TAX
	LDA OVERWORLD_PALETTE_ANIM + overworld_palette_anim::delays,X
.ENDIF
	STA OVERWORLD_PALETTE_ANIM + overworld_palette_anim::timer
	LDX @LOCAL00
	LDA __BSS_START__,X
	JSL LOAD_BG_PALETTE
	LDX @LOCAL00
	LDA __BSS_START__,X
	INC
	STA __BSS_START__,X
@DONE:
	END_C_FUNCTION
