
CHECK_HARDWARE:
	.IF DEBUG_BUILD
		LDA #$0000
	.ELSE
		SEP #PROC_FLAGS::ACCUM8
		LDA #$30
		STA f:ANTIPIRACY_SCRATCH_SPACE
		INC
		STA f:ANTIPIRACY_MIRROR_TEST
		CMP f:ANTIPIRACY_SCRATCH_SPACE
		BEQ @MIRROR_TEST_PASSED
		REP #PROC_FLAGS::ACCUM8
		PLA
		TSC
		SBC #$0100
		TCD
		JMP f:DISPLAY_ANTI_PIRACY_SCREEN
	@MIRROR_TEST_PASSED:
		.A8
		LDA f:STAT78
		AND #$10
		BEQ @HARDWARE_OK
		REP #PROC_FLAGS::ACCUM8
		PLA
		TSC
		SBC #$0100
		TCD
		JMP f:DISPLAY_FAULTY_GAMEPAK_SCREEN
	@HARDWARE_OK:
		REP #PROC_FLAGS::ACCUM8
	.ENDIF
	RTL
