
FADE_OUT_WITH_MOSAIC:
	PHP
	REP #PROC_FLAGS::ACCUM8
	PHD
	PHA
	TDC
	SEC
	SBC #$0006
	TCD
	PLA
	STZ FADE_PARAMETERS
	STA $00
	STX $02
	STY $04
@FADE_STEP:
	SEP #PROC_FLAGS::ACCUM8
	STZ MOSAIC_MIRROR
	LDA INIDISP_MIRROR
.IF .DEFINED(PROTOTYPE19950327) || .DEFINED(JPN)
.ELSE
	BMI @FADE_DONE
.ENDIF
	SEC
	SBC $00
	REP #PROC_FLAGS::ACCUM8
	BMI @FADE_DONE
	JSR SET_INIDISP
	LDA $04
	BEQ @SKIP_MOSAIC
	JSR UPDATE_MOSAIC_FROM_BRIGHTNESS
@SKIP_MOSAIC:
	LDA $02
	JSL WAIT_FRAMES
	BRA @FADE_STEP
@FADE_DONE:
.IF .DEFINED(PROTOTYPE19950327) || .DEFINED(JPN)
.ELSE
	REP #PROC_FLAGS::ACCUM8
.ENDIF
	LDA #$0080
	JSR SET_INIDISP
	SEP #PROC_FLAGS::ACCUM8
	STZ HDMAEN_MIRROR
	STZ NEW_FRAME_STARTED
@WAIT_VBLANK:
	LDA NEW_FRAME_STARTED
	BEQ @WAIT_VBLANK
	LDA #$0000
	STA f:HDMAEN
	REP #PROC_FLAGS::ACCUM8
	PLD
	PLP
	RTL
