
INIT_ERROR_SCREEN:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	JSL STOP_MUSIC
	LDA #$0001
	JSL SET_BGMODE
	LDY #VRAM::ERROR_SCREEN_TILES
	LDX #VRAM::ERROR_SCREEN_TILEMAP
	TYA ;BG_TILEMAP_SIZE::NORMAL
	JSL SET_BG3_VRAM_LOCATION
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0004
	STA TM_MIRROR
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	RTL
