
IRQ:
	PHP
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	PHA
	PHX
	PHY
	PHD
	PEA __BSS_START__
	PLD
	PHB
	PEA __BSS_START__
	PLB
	PLB
	SEP #PROC_FLAGS::ACCUM8
	LDA TIMEUP
	BMI IRQ_ENABLED
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	PLB
	PLD
	PLY
	PLX
	PLA
	PLP
	RTI
NMI:
	PHP
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	PHA
	PHX
	PHY
	PHD
	PEA __BSS_START__
	PLD
	PHB
	PEA __BSS_START__
	PLB
	PLB
	SEP #PROC_FLAGS::ACCUM8
IRQ_ENABLED:
	LDA RDNMI
	STZ HDMAEN
	LDA #$0080
	STA INIDISP
	INC <NEW_FRAME_STARTED + 0
	INC <FRAME_COUNTER + 0
	REP #PROC_FLAGS::ACCUM8
	SEP #PROC_FLAGS::INDEX8
	LDX <NEXT_FRAME_DISPLAY_ID + 0
	BEQ @AFTER_OAM_DMA
;Bank 0
	LDY #$0000
	STZ OAMADDL
	STY DMAP0
	STY A1B0
	LDY #$0004
	STY BBAD0
	LDA #.LOWORD(OAM1)
	LDX <NEXT_FRAME_DISPLAY_ID + 0
	DEX
	BEQ @OAM_BUF1
	LDA #.LOWORD(OAM2)
@OAM_BUF1:
	STA A1T0L
	LDA #$0220
	STA DAS0L
	LDY #DMA_CHANNELS::CHANNEL_0
	STY MDMAEN
	CLC
	ADC <DMA_BYTES_COPIED + 0
	STA <DMA_BYTES_COPIED + 0
@AFTER_OAM_DMA:
	LDX PALETTE_UPLOAD_MODE
	BEQ @AFTER_PALETTE_DMA
	LDA PALETTE_DMA_PARAMETERS - 4,X
	STA A1T0L
	LDY PALETTE_DMA_PARAMETERS - 2,X
	STY CGADD
	LDA #$2200
	STA DMAP0
	LDY #$0000
	STY A1B0
	STY PALETTE_UPLOAD_MODE
	LDA PALETTE_DMA_PARAMETERS - 6,X
	STA DAS0L
	LDY #DMA_CHANNELS::CHANNEL_0
	STY MDMAEN
	CLC
	ADC <DMA_BYTES_COPIED + 0
	STA <DMA_BYTES_COPIED + 0
@AFTER_PALETTE_DMA:
	SEP #PROC_FLAGS::ACCUM8
	LDA <FADE_PARAMETERS + fade_parameters::step
	BEQ @AFTER_FADE
	DEC <FADE_DELAY_FRAMES_LEFT + 0
	BPL @AFTER_FADE
	LDA <FADE_PARAMETERS + fade_parameters::delay
	STA <FADE_DELAY_FRAMES_LEFT + 0
	LDA <INIDISP_MIRROR + 0
	AND #$000F
	CLC
	ADC <FADE_PARAMETERS + fade_parameters::step
	BPL @FADE_NOT_DARK
	STZ HDMAEN_MIRROR
	LDA #$0080
	BRA @FADE_COMPLETE
@FADE_NOT_DARK:
	CMP #$0010
	BCC @FADE_STORE
	LDA #$000F
@FADE_COMPLETE:
	STZ <FADE_PARAMETERS + fade_parameters::step
@FADE_STORE:
	STA <INIDISP_MIRROR + 0
@AFTER_FADE:
	REP #PROC_FLAGS::INDEX8
	LDA <INIDISP_MIRROR + 0
	STA INIDISP
	LDA <MOSAIC_MIRROR + 0
	STA MOSAIC
	LDY <BG12NBA_MIRROR + 0
	STY BG12NBA
	LDY <WH2_MIRROR + 0
	LDY #$00FF
	STY WH2
	REP #PROC_FLAGS::ACCUM8
	SEP #PROC_FLAGS::INDEX8
	LDX <LAST_COMPLETED_DMA_INDEX + 0
	BRA @DMA_LOOP_CHECK
@PROCESS_DMA:
	LDY DMA_QUEUE + queued_dma::mode,X
	LDA DMA_TABLE,Y
	STA DMAP0
	LDA DMA_TABLE + 2,Y
	STA VMAIN
	LDA DMA_QUEUE + queued_dma::size,X
	STA DAS0L
	LDA DMA_QUEUE + queued_dma::src,X
	STA A1T0L
	LDY DMA_QUEUE + queued_dma::src + 2,X
	STY A1B0
	LDA DMA_QUEUE + queued_dma::dest,X
	STA VMADDL
	TXA
	CLC
	ADC #.SIZEOF(queued_dma)
	TAX
	LDY #DMA_CHANNELS::CHANNEL_0
	STY MDMAEN
@DMA_LOOP_CHECK:
	CPX <DMA_QUEUE_INDEX + 0
	BNE @PROCESS_DMA
	STX <LAST_COMPLETED_DMA_INDEX + 0
	SEP #PROC_FLAGS::ACCUM8
	LDA <NEXT_FRAME_DISPLAY_ID + 0
	BEQL @AFTER_BG_SCROLL
	DEC
	BNE @BG_SCROLL_BUF2
; Note: The + 0 is for suppressing a spurious 'suspicious address warning'
	LDA <BG1_X_POS_BUF + 0
	STA BG1HOFS
	LDA <BG1_X_POS_BUF + 1
	STA BG1HOFS
	LDA <BG1_Y_POS_BUF + 0
	STA BG1VOFS
	LDA <BG1_Y_POS_BUF + 1
	STA BG1VOFS
	LDA <BG2_X_POS_BUF + 0
	STA BG2HOFS
	LDA <BG2_X_POS_BUF + 1
	STA BG2HOFS
	LDA <BG2_Y_POS_BUF + 0
	STA BG2VOFS
	LDA <BG2_Y_POS_BUF + 1
	STA BG2VOFS
	LDA <BG3_X_POS_BUF + 0
	STA BG3HOFS
	LDA <BG3_X_POS_BUF + 1
	STA BG3HOFS
	LDA <BG3_Y_POS_BUF + 0
	STA BG3VOFS
	LDA <BG3_Y_POS_BUF + 1
	STA BG3VOFS
	LDA <BG4_X_POS_BUF + 0
	STA BG4HOFS
	LDA <BG4_X_POS_BUF + 1
	STA BG4HOFS
	LDA <BG4_Y_POS_BUF + 0
	STA BG4VOFS
	LDA <BG4_Y_POS_BUF + 1
	STA BG4VOFS
	BRA @AFTER_BG_SCROLL
@BG_SCROLL_BUF2:
	LDA <BG1_X_POS_BUF + 2
	STA BG1HOFS
	LDA <BG1_X_POS_BUF + 3
	STA BG1HOFS
	LDA <BG1_Y_POS_BUF + 2
	STA BG1VOFS
	LDA <BG1_Y_POS_BUF + 3
	STA BG1VOFS
	LDA <BG2_X_POS_BUF + 2
	STA BG2HOFS
	LDA <BG2_X_POS_BUF + 3
	STA BG2HOFS
	LDA <BG2_Y_POS_BUF + 2
	STA BG2VOFS
	LDA <BG2_Y_POS_BUF + 3
	STA BG2VOFS
	LDA <BG3_X_POS_BUF + 2
	STA BG3HOFS
	LDA <BG3_X_POS_BUF + 3
	STA BG3HOFS
	LDA <BG3_Y_POS_BUF + 2
	STA BG3VOFS
	LDA <BG3_Y_POS_BUF + 3
	STA BG3VOFS
	LDA <BG4_X_POS_BUF + 2
	STA BG4HOFS
	LDA <BG4_X_POS_BUF + 3
	STA BG4HOFS
	LDA <BG4_Y_POS_BUF + 2
	STA BG4VOFS
	LDA <BG4_Y_POS_BUF + 3
	STA BG4VOFS
	REP #PROC_FLAGS::ACCUM8
	LDA BG1_X_POS
	STA EVEN_BG1_X_POSITION
	LDA BG1_Y_POS
	STA EVEN_BG1_Y_POSITION
@AFTER_BG_SCROLL:
	LDY #$0000
	STY <NEXT_FRAME_DISPLAY_ID + 0
	LDX <INIDISP_MIRROR + 0
	BMI @AFTER_DISPLAY_SETUP
	LDX <TM_MIRROR + 0
	STX TM
	LDX <TD_MIRROR + 0
	STX TD
	LDX <HDMAEN_MIRROR + 0
	STX HDMAEN
@AFTER_DISPLAY_SETUP:
	JSR PROCESS_SFX_QUEUE
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	STZ <DMA_BYTES_COPIED + 0
	LDA IN_IRQ_CALLBACK
	BNE @AFTER_IRQ_CALLBACK
	INC IN_IRQ_CALLBACK
	PHB
	PEA $7E7E
	PLB
	PLB
	PHD
	PEA $0200
	PLD
	JSR EXECUTE_IRQ_CALLBACK
	PLD
	PLB
	STZ IN_IRQ_CALLBACK
@AFTER_IRQ_CALLBACK:
	LDA #.LOWORD(HEAP)
	CMP <BASE_HEAP_ADDRESS + 0
	BNE @SWAP_HEAP
	LDA #.LOWORD(HEAP_ALT)
@SWAP_HEAP:
	STA <BASE_HEAP_ADDRESS + 0
	STA <CURRENT_HEAP_ADDRESS + 0
	LDA #$0000
	STA f:DMA_TRANSFER_FLAG
	STZ <UNREAD_7E00AB + 0
	INC <TIMER + 0
	BNE @RETURN
	INC <TIMER + 2
@RETURN:
	PLB
	PLD
	PLY
	PLX
	PLA
	PLP
	RTI
