
LOAD_WINDOW_GFX:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	END_STACK_VARS
	LOADPTR TEXT_WINDOW_GFX, @LOCAL00
	LOADPTR BUFFER, @LOCAL01
	JSL DECOMP
	LOADPTR BUFFER + $3200, @LOCAL00
	LDX #$0600
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL MEMSET24
	.A16
	LDA GAME_STATE+game_state::text_flavour
	AND #$00FF
	DEC
	OPTIMIZED_MULT @VIRTUAL04, 3
	TAX
	INX
	INX
	LDA f:TEXT_WINDOW_PROPERTIES,X
	AND #$00FF
	BEQ @AFTER_FLAVOUR_DECOMP
	LOADPTR FLAVOURED_TEXT_GFX, @LOCAL00
	LOADPTR BUFFER + $100, @LOCAL01
	JSL DECOMP
	.A16
@AFTER_FLAVOUR_DECOMP:
	LOADPTR BUFFER + $2A00, @LOCAL07
	LDA #0
	STA @LOCAL06
	JMP @PARTY_MEMBER_LOOP_CHECK
@PROCESS_PARTY_MEMBER:
@LOAD_CHAR_NAME:
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL05
	LDY #0
	STY @LOCAL04
	JMP @NAME_CHAR_LOOP_CHECK
@PROCESS_NAME_CHAR:
	LDA [@LOCAL05]
	AND #$00FF
	TAX
	STX @VIRTUAL02
	TXA
	AND #$00F0
	CLC
	ADC @VIRTUAL02
	ASL
	ASL
	ASL
	ASL
	STORE_INT1632 @VIRTUAL0A
	CLC
	VAR_ADD_CONST_INT_ASSIGN BUFFER, @VIRTUAL0A
	LOADPTR BUFFER + $70, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL03
	LDX #0
	BRA @PIXEL_COL_LOOP_CHECK
@COMPOSITE_PIXEL_COL:
	LDA [@VIRTUAL0A]
	STA @VIRTUAL02
	XBA
	AND #$00FF
	EOR #$00FF
	PHA
	LDA [@VIRTUAL06]
	AND #$00FF
	STA @VIRTUAL04
	LDA @VIRTUAL02
	AND #$FF00
	ORA @VIRTUAL04
	PLY
	STY @VIRTUAL02
	ORA @VIRTUAL02
	STA [@LOCAL07]
	LDY #256
	LDA [@VIRTUAL0A],Y
	STA @VIRTUAL02
	XBA
	AND #$00FF
	EOR #$00FF
	PHA
	LDA [@VIRTUAL06],Y
	AND #$00FF
	STA @VIRTUAL04
	LDA @VIRTUAL02
	AND #$FF00
	ORA @VIRTUAL04
	PLY
	STY @VIRTUAL02
	ORA @VIRTUAL02
	LDY #256
	STA [@LOCAL07],Y
	MOVE_INT @LOCAL07, @VIRTUAL06
	INC @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL07
	INC @VIRTUAL0A
	INC @VIRTUAL0A
	MOVE_INT @LOCAL03, @VIRTUAL06
	INC @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL03
	INX
@PIXEL_COL_LOOP_CHECK:
	CPX #8
	BCCL @COMPOSITE_PIXEL_COL
	MOVE_INT @LOCAL05, @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL05
	LDY @LOCAL04
	INY
	STY @LOCAL04
@NAME_CHAR_LOOP_CHECK:
	CPY #4
	BCCL @PROCESS_NAME_CHAR
	LDA @LOCAL06
	INC
	STA @LOCAL06
@PARTY_MEMBER_LOOP_CHECK:
	CMP #4
	BCCL @PROCESS_PARTY_MEMBER
	LOADPTR BUFFER + $2C00, @LOCAL05
	LOADPTR STATUS_EQUIP_WINDOW_TEXT_2, @LOCAL07
	JMP @MENU_CHAR_LOOP_CHECK
@PROCESS_MENU_CHAR:
	CMP #32
	BEQL @ADVANCE_STRING_PTR
	STA @VIRTUAL02
	AND #$FFF0
	CLC
	ADC @VIRTUAL02
	ASL
	ASL
	ASL
	ASL
	STORE_INT1632 @VIRTUAL0A
	CLC
	VAR_ADD_CONST_INT_ASSIGN BUFFER, @VIRTUAL0A
	LOADPTR BUFFER + $70, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL03
	LDX #0
	BRA @MENU_PIXEL_LOOP_CHECK
@COMPOSITE_MENU_PIXEL:
	LDA [@VIRTUAL0A]
	STA @LOCAL02
	XBA
	AND #$00FF
	EOR #$00FF
	STA @VIRTUAL02
	LDA [@VIRTUAL06]
	AND #$00FF
	STA @VIRTUAL04
	LDA @LOCAL02
	AND #$FF00
	ORA @VIRTUAL04
	ORA @VIRTUAL02
	STA [@LOCAL05]
	LDY #256
	LDA [@VIRTUAL0A],Y
	STA @LOCAL02
	XBA
	AND #$00FF
	EOR #$00FF
	STA @VIRTUAL02
	LDA [@VIRTUAL06],Y
	AND #$00FF
	STA @VIRTUAL04
	LDA @LOCAL02
	AND #$FF00
	ORA @VIRTUAL04
	ORA @VIRTUAL02
	STA [@LOCAL05],Y
	MOVE_INT @LOCAL05, @VIRTUAL06
	INC @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL05
	INC @VIRTUAL0A
	INC @VIRTUAL0A
	MOVE_INT @LOCAL03, @VIRTUAL06
	INC @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL03
	INX
@MENU_PIXEL_LOOP_CHECK:
	CPX #8
	BCC @COMPOSITE_MENU_PIXEL
@ADVANCE_STRING_PTR:
	MOVE_INT @LOCAL07, @VIRTUAL06
	INC @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL07
@MENU_CHAR_LOOP_CHECK:
	LDA [@LOCAL07]
	BNEL @PROCESS_MENU_CHAR
	END_C_FUNCTION
