
MAIN_LOOP:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	JSL INIT_CHOSEN_FOUR_POINTERS
	LDA #.LOWORD(JMP_BUF1)
	JSL SETJMP
	JSL INIT_INTRO
	JSR FILE_SELECT_INIT
	JSR INITIALIZE_OVERWORLD_STATE
	JSL OAM_CLEAR
	JSL RUN_ACTIONSCRIPT_FRAME
	LDX #1
	TXA
	JSL FADE_IN
	JSL UPDATE_SCREEN
.IF .DEFINED(USA)
	LDA #.LOWORD(JMP_BUF2)
	JSL SETJMP
	JSL INIT_USED_BG2_TILE_MAP
.ENDIF
@LOOP_BEGIN:
	JSL OAM_CLEAR
	JSL RUN_ACTIONSCRIPT_FRAME
	JSL UPDATE_SCREEN
	JSL UPDATE_SWIRL_EFFECT
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA CURRENT_QUEUED_INTERACTION
	SEC
	SBC NEXT_QUEUED_INTERACTION
	BEQ @SKIP_INTERACTIONS
	LDA BATTLE_SWIRL_COUNTDOWN
	BNE @SKIP_INTERACTIONS
	LDA ENEMY_HAS_BEEN_TOUCHED
	BNE @SKIP_INTERACTIONS
	LDA BATTLE_MODE
	BNE @SKIP_INTERACTIONS
	JSL PROCESS_QUEUED_INTERACTIONS
	INC INPUT_DISABLE_FRAME_COUNTER
	JMP @LOOP_END
@SKIP_INTERACTIONS:
	LDA GAME_STATE + game_state::camera_mode
	CMP #2
	BEQL @LOOP_END
	LDX GAME_STATE+game_state::walking_style
	CPX #WALKING_STYLE::ESCALATOR
	BEQL @LOOP_END
	LDA BATTLE_SWIRL_COUNTDOWN
	BNEL @LOOP_END
	LDA BATTLE_MODE
	BEQ @CHECK_BICYCLE_DISMOUNT
	JSL INIT_BATTLE_OVERWORLD
	INC INPUT_DISABLE_FRAME_COUNTER
	BRA @CHECK_DEBUG
@CHECK_BICYCLE_DISMOUNT:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON | PAD::L_BUTTON
	BEQ @CHECK_DEBUG
	CPX #3
	BNE @CHECK_DEBUG
	JSL DISABLE_ALL_ENTITIES
	JSL GET_OFF_BICYCLE
	JSL ENABLE_ALL_ENTITIES
	JMP @LOOP_BEGIN
@CHECK_DEBUG:
	LDA DEBUG
	BEQ @NO_DEBUG
	LDA PAD_STATE
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON
	BEQ @DEBUG_PAD2_B_HELD
	LDA PAD_PRESS
	AND #PAD::R_BUTTON
	BEQ @DEBUG_PAD2_B_HELD
	JSL DEBUG_Y_BUTTON_MENU
	JMP @LOOP_BEGIN
@DEBUG_PAD2_B_HELD:
	LDA PAD_PRESS + 2
	AND #PAD::A_BUTTON
	BEQ @DEBUG_PAD2_A_HELD
	JSL GET_DISTANCE_TO_MAGIC_TRUFFLE
@DEBUG_PAD2_A_HELD:
	LDA PAD_PRESS + 2
	AND #PAD::B_BUTTON
	BEQ @NO_DEBUG
	JSL TEST_YOUR_SANCTUARY_DISPLAY
@NO_DEBUG:
	LDA BATTLE_SWIRL_COUNTDOWN
	BNEL @LOOP_BEGIN
	LDA ENEMY_HAS_BEEN_TOUCHED
	BNEL @LOOP_BEGIN
	LDA INPUT_DISABLE_FRAME_COUNTER
	BNE @DECREMENT_INPUT_DISABLE
	LDA PENDING_INTERACTIONS
	BNE @CHECK_PSI_TELEPORT
	LDA PAD_PRESS
	AND #PAD::A_BUTTON
	BEQ @NO_OPEN_MENU
	JSL OPEN_MENU_BUTTON
	BRA @CHECK_PSI_TELEPORT
@NO_OPEN_MENU:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON
	BEQ @NO_OPEN_HPPP_DISPLAY
	LDA GAME_STATE+game_state::walking_style
	CMP #WALKING_STYLE::BICYCLE
	BEQ @NO_OPEN_HPPP_DISPLAY
	JSL OPEN_HPPP_DISPLAY
	BRA @CHECK_PSI_TELEPORT
@NO_OPEN_HPPP_DISPLAY:
	LDA PAD_PRESS
	AND #PAD::X_BUTTON
	BEQ @NO_OPEN_TOWN_MAP
	JSL SHOW_TOWN_MAP
	BRA @CHECK_PSI_TELEPORT
@NO_OPEN_TOWN_MAP:
	LDA PAD_PRESS
	AND #PAD::L_BUTTON
	BEQ @CHECK_PSI_TELEPORT
	JSL OPEN_MENU_BUTTON_CHECKTALK
	BRA @CHECK_PSI_TELEPORT
@DECREMENT_INPUT_DISABLE:
	DEC INPUT_DISABLE_FRAME_COUNTER
@CHECK_PSI_TELEPORT:
	LDA PSI_TELEPORT_DESTINATION
	BEQ @CHECK_DEBUG_HEAL
	JSL TELEPORT_MAINLOOP
@CHECK_DEBUG_HEAL:
	LDA DEBUG
	BEQ @LOOP_END
	LDA PAD_PRESS + 2
	AND #PAD::B_BUTTON
	BEQ @LOOP_END
	LDA #0
	STA @LOCAL00
	BRA @DEBUG_HEAL_CHECK
@DEBUG_HEAL_LOOP:
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::max_hp,X
	STA PARTY_CHARACTERS+char_struct::current_hp_target,X
	LDA PARTY_CHARACTERS+char_struct::max_pp,X
	STA PARTY_CHARACTERS+char_struct::current_pp_target,X
	LDA @LOCAL00
	INC
	STA @LOCAL00
@DEBUG_HEAL_CHECK:
	CMP #TOTAL_PARTY_COUNT
	BCC @DEBUG_HEAL_LOOP
@LOOP_END:
	JSL UPDATE_OVERWORLD_DAMAGE
	CMP #0
	BNE @CHECK_DEBUG_EXIT
	JSL SPAWN
	CMP #0
	BEQ @CHECK_DEBUG_EXIT
	LDX #0
	LDA #.LOWORD(JMP_BUF1)
	JSL LONGJMP
@CHECK_DEBUG_EXIT:
	LDA DEBUG
	BEQL @LOOP_BEGIN
	LDA PAD_STATE
	AND #PAD::START_BUTTON
	BEQL @LOOP_BEGIN
	LDA PAD_STATE
	AND #PAD::SELECT_BUTTON
	BEQL @LOOP_BEGIN
	END_C_FUNCTION
