
READ_JOYPAD:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	LDA <DEMO_RECORDING_FLAGS + 0
	BEQ @READ_HARDWARE
	AND #$4000
	BEQ @READ_HARDWARE
	DEC <DEMO_FRAMES_LEFT
	BNE @DONE
	INC <DEMO_READ_SOURCE
	INC <DEMO_READ_SOURCE
	INC <DEMO_READ_SOURCE
	LDA [<DEMO_READ_SOURCE]
	AND #$00FF
	BEQ @DEMO_END
	STA <DEMO_FRAMES_LEFT
	LDY #$0001
	LDA [<DEMO_READ_SOURCE],Y
	STA <PAD_RAW
	STA <PAD_RAW + 2
	BRA @DONE
@DEMO_END:
	LDA <DEMO_RECORDING_FLAGS + 0
	AND #$FFFF ^ DEMO_RECORDING_FLAG::PLAYBACK
	STA <DEMO_RECORDING_FLAGS
@READ_HARDWARE:
	LDA JOYPAD_2_DATA
	STA <PAD_RAW + 2
	LDA JOYPAD_1_DATA
	STA <PAD_RAW
@DONE:
	RTS
