
RENDER_FRAME_TICK:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	LDA RENDER_HPPP_WINDOWS
	AND #$00FF
	BEQ @SKIP_PALETTE
	JSR UPDATE_TEXT_WINDOW_PALETTE
@SKIP_PALETTE:
	LDA BATTLE_MODE_FLAG
	BEQ @OVERWORLD
	JSL WAIT_AND_UPDATE_BATTLE_EFFECTS_FAR
	BRA @DONE
@OVERWORLD:
	JSL OAM_CLEAR
	JSL RUN_ACTIONSCRIPT_FRAME
	JSL UPDATE_SCREEN
	JSL WAIT_UNTIL_NEXT_FRAME
@DONE:
	END_C_FUNCTION
