
SBRK:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	TAY
@TRY_ALLOCATE:
	TYA
	CLC
	ADC CURRENT_HEAP_ADDRESS
	SEC
	SBC #HEAPSIZE
	CMP BASE_HEAP_ADDRESS
	BCS @WAIT_FOR_FRAME
	ADC #HEAPSIZE
	LDY CURRENT_HEAP_ADDRESS
	STA CURRENT_HEAP_ADDRESS
	TYA
	RTL
@WAIT_FOR_FRAME:
	LDA NEW_FRAME_STARTED
	BEQ @WAIT_FOR_FRAME
	STZ NEW_FRAME_STARTED
	BRA @TRY_ALLOCATE
	PHP
	SEP #PROC_FLAGS::ACCUM8
	LDA NMITIMEN_MIRROR
	AND #$007F
	STA NMITIMEN_MIRROR
	STA f:NMITIMEN
	PLP
	RTL
