
STRCAT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT32 "DESTINATION" ;FAR char*
	STACK_RESERVE_PARAM_INT32 "SOURCE" ;FAR const char*
	STACK_RESERVE_RETURN_INT32 ;FAR char*
	END_STACK_VARS
	MOVE_INT @SOURCE, @VIRTUAL0A
	MOVE_INT @DESTINATION, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL04
	MOVE_INT @LOCAL04, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL03
	BRA @CHECK_NULL_TERMINATOR
@ADVANCE_POINTER:
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL03
@CHECK_NULL_TERMINATOR:
	LDA [@VIRTUAL06]
	AND #$00FF
	BNE @ADVANCE_POINTER
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL STRLEN
	STA @LOCAL02
	MOVE_INT @LOCAL03, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDA @LOCAL02
	INC
	JSL MEMCPY24
	MOVE_INT @LOCAL04, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @RETURNVAL
	END_C_FUNCTION
