
TRANSFER_TO_VRAM:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	STA DMA_COPY_MODE
@WAIT_DMA_READY:
	LDA DMA_BYTES_COPIED
	BNE @WAIT_DMA_READY
	MOVE_INT $0E, DMA_COPY_RAM_SRC
	STY DMA_COPY_VRAM_DEST
	CPX #$1201
	BCC @FINAL_CHUNK
	LDA #$1200
	STA DMA_COPY_SIZE
@CHECK_SIZE:
	CPX #$1201
	BCC @FINAL_CHUNK
@WAIT_CHUNK_COMPLETE:
	LDA DMA_BYTES_COPIED
	BNE @WAIT_CHUNK_COMPLETE
	PHX
	JSL PREPARE_VRAM_COPY_COMMON
	.A16
	LDA DMA_COPY_RAM_SRC
	CLC
	ADC #$1200
	STA DMA_COPY_RAM_SRC
	LDA DMA_COPY_VRAM_DEST
	CLC
	ADC #$0900
	STA DMA_COPY_VRAM_DEST
	PLA
	SEC
	SBC #$1200
	TAX
	BRA @CHECK_SIZE
@FINAL_CHUNK:
	STX DMA_COPY_SIZE
@WAIT_FINAL_DMA:
	LDA DMA_BYTES_COPIED
	BNE @WAIT_FINAL_DMA
	JSL PREPARE_VRAM_COPY_COMMON
	.A16
@WAIT_RETURN:
	LDA DMA_BYTES_COPIED
	BNE @WAIT_RETURN
	RTL
