
WAIT_UNTIL_NEXT_FRAME:
	SEP #PROC_FLAGS::ACCUM8
	LDA NMITIMEN_MIRROR
	AND #$00B0
	BEQ @WAITFORNOTVBLANK
@WAIT_FOR_NMI:
	LDA NEW_FRAME_STARTED
	BEQ @WAIT_FOR_NMI
	STZ NEW_FRAME_STARTED
	BRA @VBLANK_REACHED
@WAITFORNOTVBLANK:
	LDA f:HVBJOY
	BMI @WAITFORNOTVBLANK
@WAITFORVBLANK:
	LDA f:HVBJOY
	BPL @WAITFORVBLANK
@VBLANK_REACHED:
	STZ NEW_FRAME_STARTED
	PHD
	PEA $0000
	PLD
	PHB
	PEA $0000
	PLB
	PLB
	JSR UPDATE_JOYPAD_STATE
	PLB
	PLD
	REP #PROC_FLAGS::ACCUM8
	RTL
