; Do nothing for some number of frames
WAIT:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int frames
	END_STACK_VARS
	TAX
	STX @LOCAL00
	BRA @LOOP_CHECK
@TICK:
	JSL WINDOW_TICK
@LOOP_CHECK:
	LDX @LOCAL00
	TXA
	DEX
	STX @LOCAL00
	CMP #0
	BNE @TICK
	END_C_FUNCTION
