
OPEN_FLAVOUR_MENU:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	.IF .DEFINED(JPN)
		@FLAVOURSTARTLINE := 1
		@FLAVOURDESCLENGTH := 10
	.ELSE
		@FLAVOURSTARTLINE := 2
		@FLAVOURDESCLENGTH := 37
	.ENDIF
	CREATE_WINDOW_NEAR #WINDOW::FILE_SELECT_FLAVOUR_CHOICE
	JSR SET_INSTANT_PRINTING
	LOADPTR FILE_SELECT_TEXT_WHICH_STYLE, @LOCAL00
	LDA #@FLAVOURDESCLENGTH
	JSR PRINT_STRING
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
	LOADPTR FILE_SELECT_TEXT_FLAVOR_PLAIN, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDX #@FLAVOURSTARTLINE
	LDA #0
	JSR ADD_POSITIONED_MENU_OPTION
	LOADPTR FILE_SELECT_TEXT_FLAVOR_MINT, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDX #@FLAVOURSTARTLINE+1
	LDA #0
	JSR ADD_POSITIONED_MENU_OPTION
	LOADPTR FILE_SELECT_TEXT_FLAVOR_STRAWBERRY, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDX #@FLAVOURSTARTLINE+2
	LDA #0
	JSR ADD_POSITIONED_MENU_OPTION
	LOADPTR FILE_SELECT_TEXT_FLAVOR_BANANA, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDX #@FLAVOURSTARTLINE+3
	LDA #0
	JSR ADD_POSITIONED_MENU_OPTION
	LOADPTR FILE_SELECT_TEXT_FLAVOR_PEANUT, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDX #@FLAVOURSTARTLINE+4
	LDA #0
	JSR ADD_POSITIONED_MENU_OPTION
	LDX #.LOWORD(GAME_STATE) + game_state::text_flavour
	LDA __BSS_START__,X
	AND #$00FF
	BNE @FLAVOUR_SET
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA __BSS_START__,X
@FLAVOUR_SET:
	LDX #.LOWORD(GAME_STATE) + game_state::text_flavour
	STX @LOCAL03
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	AND #$00FF
	DEC
	JSR PRINT_MENU_AT_SELECTION
	LOADPTR PREVIEW_WINDOW_FLAVOUR, @LOCAL00
	JSR SET_CURSOR_MOVE_CALLBACK
	LDA #1
	JSR SELECTION_MENU
	TAY
	STY @LOCAL02
	BEQ @SELECTION_CANCELLED
	TYA
	SEP #PROC_FLAGS::ACCUM8
	LDX @LOCAL03
	STA __BSS_START__,X
	BRA @SAVE_AND_RETURN
@SELECTION_CANCELLED:
	.A16
	LDX @LOCAL03
	LDA __BSS_START__,X
	AND #$00FF
	BEQ @USE_DEFAULT_FLAVOUR
	AND #$00FF
	TAX
	BRA @PREVIEW_CURRENT
@USE_DEFAULT_FLAVOUR:
	LDX #1
@PREVIEW_CURRENT:
	TXA
	JSL PREVIEW_WINDOW_FLAVOUR
@SAVE_AND_RETURN:
	REP #PROC_FLAGS::ACCUM8
.IF .DEFINED(JPN)
	LDA #WINDOW::FILE_SELECT_FLAVOUR_CHOICE
	JSR CLOSE_WINDOW
.ENDIF
	LDA CURRENT_SAVE_SLOT
	AND #$00FF
	DEC
	JSL SAVE_GAME_SLOT
	LDY @LOCAL02
	TYA
	END_C_FUNCTION
