
SHOW_FILE_SELECT_MENU:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	CREATE_WINDOW_NEAR #WINDOW::FILE_SELECT_MENU
	LOADPTR FILE_SELECT_TEXT_CONTINUE, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDY #0
	TYX
	LDA #1
	JSR ADD_MENU_ITEM
	LDX #0
	BRA @SLOT_LOOP_CHECK
@CHECK_SAVE_SLOT:
	LDA CURRENT_SAVE_SLOT
	AND #$00FF
	DEC
	STA @VIRTUAL02
	TXA
	CMP @VIRTUAL02
	BEQ @NEXT_SLOT
	LDA SAVE_FILES_PRESENT,X
	AND #$00FF
	BNE @NEXT_SLOT
	LOADPTR FILE_SELECT_TEXT_COPY, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDY #0
	LDX #5
	LDA #2
	JSR ADD_MENU_ITEM
	BRA @ADD_DELETE_SETUP
@NEXT_SLOT:
	INX
@SLOT_LOOP_CHECK:
	STX @VIRTUAL02
	LDA #3
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @CHECK_SAVE_SLOT
@ADD_DELETE_SETUP:
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
	LOADPTR FILE_SELECT_TEXT_DELETE, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDY #0
	LDX #10
	LDA #3
	JSR ADD_MENU_ITEM
	LOADPTR FILE_SELECT_TEXT_SET_UP, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDY #0
	LDX #14
	LDA #4
	JSR ADD_MENU_ITEM
	JSR PRINT_MENU_ITEMS
	LDA #1
	JSR SELECTION_MENU
	END_C_FUNCTION
