
BLIT_FONT_TO_VWF_BUFFER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	STY @LOCAL05
	STA @LOCAL04
	MOVE_INT @PARAM03, @VIRTUAL0A
	LDY #8
	LDA FLYOVER_PIXEL_OFFSET
	JSL MODULUS16
	STA @LOCAL03
	LDA FLYOVER_BYTE_OFFSET
	CLC
	ADC @LOCAL05
	STA @VIRTUAL02
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	LDA @VIRTUAL02
	STA @LOCAL02
	LDA #0
	STA @VIRTUAL04
	BRA @HALF_LOOP_CHECK
@PROCESS_HALF:
	LDY #0
	STY @LOCAL01
	BRA @ROW_LOOP_CHECK
@BLIT_ROW:
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	EOR #$00FF
	LDY @LOCAL03
	SEP #PROC_FLAGS::INDEX8
	JSL ASR8_POSITIVE
	EOR #$00FF
	REP #PROC_FLAGS::INDEX8
	LDX @VIRTUAL02
	INX
	STA @VIRTUAL00
	LDA __BSS_START__,X
	AND @VIRTUAL00
	STA __BSS_START__,X
	LDX @VIRTUAL02
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL02
	INC @VIRTUAL02
	LDY @LOCAL01
	INY
	STY @LOCAL01
	INC @VIRTUAL06
@ROW_LOOP_CHECK:
	CPY #8
	BCC @BLIT_ROW
	LDA @LOCAL02
	CLC
	ADC #416
	STA @VIRTUAL02
	INC @VIRTUAL04
@HALF_LOOP_CHECK:
	LDA #2
	CLC
	SBC @VIRTUAL04
	BRANCHGTS @PROCESS_HALF
	LDA FLYOVER_PIXEL_OFFSET
	CLC
	ADC @LOCAL04
	STA FLYOVER_PIXEL_OFFSET
	LSR
	LSR
	LSR
	CMP FLYOVER_BYTE_OFFSET
	BEQL @RETURN
	ASL
	ASL
	ASL
	ASL
	STA @LOCAL04
	STA FLYOVER_BYTE_OFFSET
	LDA #8
	SEC
	SBC @LOCAL03
	STA @LOCAL02
	LDA @LOCAL04
	CLC
	ADC @LOCAL05
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	STA @LOCAL03
	STA @VIRTUAL02
	LDA #0
	STA @VIRTUAL04
	BRA @OVERLAP_HALF_LOOP_CHECK
@PROCESS_OVERLAP_HALF:
	LDY #0
	STY @LOCAL00
	BRA @OVERLAP_ROW_LOOP_CHECK
@BLIT_OVERLAP_ROW:
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	EOR #$00FF
	LDY @LOCAL02
	SEP #PROC_FLAGS::INDEX8
	JSL ASL16_ENTRY2
	EOR #$00FF
	REP #PROC_FLAGS::INDEX8
	LDX @VIRTUAL02
	INX
	STA @VIRTUAL00
	LDA __BSS_START__,X
	AND @VIRTUAL00
	STA __BSS_START__,X
	LDX @VIRTUAL02
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL02
	INC @VIRTUAL02
	LDY @LOCAL00
	INY
	STY @LOCAL00
	INC @VIRTUAL06
@OVERLAP_ROW_LOOP_CHECK:
	CPY #8
	BCC @BLIT_OVERLAP_ROW
	LDA @LOCAL03
	CLC
	ADC #416
	STA @VIRTUAL02
	INC @VIRTUAL04
@OVERLAP_HALF_LOOP_CHECK:
	LDA #2
	CLC
	SBC @VIRTUAL04
	BRANCHGTS @PROCESS_OVERLAP_HALF
@RETURN:
	END_C_FUNCTION
