
FLUSH_VWF_TILES_TO_VRAM:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #.LOWORD(TEXT_RENDER_STATE)
	STA @LOCAL03
	LDA VWF_X
	LSR
	LSR
	LSR
	STA @LOCAL02
	LDA (@LOCAL03) ;text_renderer_state::pixels_rendered
	LSR
	LSR
	LSR
	STA @VIRTUAL02
	LDY #text_renderer_state::upper_vram_position
	LDA (@LOCAL03),Y
	STA @LOCAL01
	BEQ @NO_EXISTING_TILE
	LDY #text_renderer_state::lower_vram_position
	LDA (@LOCAL03),Y
	TAY
	LDA @LOCAL01
	TAX
	LDA @VIRTUAL02
	JSR UPLOAD_VWF_TILE_TO_VRAM
	BRA @TILE_LOOP_CHECK
@NO_EXISTING_TILE:
	LDA @VIRTUAL02
	DEC
	STA @VIRTUAL02
	BRA @TILE_LOOP_CHECK
@ALLOC_AND_UPLOAD:
	JSR ALLOC_BG2_TILEMAP_ENTRY
	STA @LOCAL00
	LDY #text_renderer_state::upper_vram_position
	STA (@LOCAL03),Y
	JSR ALLOC_BG2_TILEMAP_ENTRY
	STA @VIRTUAL04
	LDY #text_renderer_state::lower_vram_position
	STA (@LOCAL03),Y
	LDX @VIRTUAL02
	INX
	CPX #52
	BNE @NO_WRAP
	LDX #0
@NO_WRAP:
	STX @VIRTUAL02
	LDY @VIRTUAL04
	LDX @LOCAL00
	LDA @VIRTUAL02
	JSR UPLOAD_VWF_TILE_TO_VRAM
	LDX @VIRTUAL04
	LDA @LOCAL00
	JSR WRITE_CHAR_TO_WINDOW
@TILE_LOOP_CHECK:
	LDA @VIRTUAL02
	CMP @LOCAL02
	BNE @ALLOC_AND_UPLOAD
	LDA VWF_X
	STA (@LOCAL03)
	END_C_FUNCTION
