
INITIALIZE_EXISTING_NAME_VWF:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @VIRTUAL04
	STA @VIRTUAL02
	LDY #0
	STY @LOCAL01
	BRA @CHECK_CHAR_LOOP
@PROCESS_CHAR:
	LDA @VIRTUAL00
	AND #$00FF
	SEC
	SBC #$50
	AND #$007F
	STA @LOCAL00
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	STA KEYBOARD_INPUT_CHARACTERS,Y
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	SEP #PROC_FLAGS::ACCUM8
	STA KEYBOARD_INPUT_CHARACTER_OFFSETS,Y
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT FONT_PTR_TABLE, @VIRTUAL06
	LDA @LOCAL00
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	TAX
	SEP #PROC_FLAGS::ACCUM8
	CLC
	ADC CHARACTER_PADDING
	STA KEYBOARD_INPUT_CHARACTER_WIDTHS,Y
	LDX @VIRTUAL02
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	AND #$00FF
	TAX
	LDA #0
	JSL RENDER_VWF_CHARACTER
	LDY @LOCAL01
	INY
	STY @LOCAL01
	INC @VIRTUAL02
@CHECK_CHAR_LOOP:
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	AND #$00FF
	BEQ @AFTER_CHARS
	TYA
	CMP @VIRTUAL04
	BNE @PROCESS_CHAR
@AFTER_CHARS:
	STY NEXT_KEYBOARD_INPUT_INDEX
	TYA
	CMP @VIRTUAL04
	BCS @RETURN
	SEP #PROC_FLAGS::ACCUM8
	LDA #32
	STA KEYBOARD_INPUT_CHARACTER_OFFSETS,Y
	LDX #112
	REP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL RENDER_VWF_CHARACTER
	LDY @LOCAL01
	TYX
	SEP #PROC_FLAGS::ACCUM8
	STZ KEYBOARD_INPUT_CHARACTERS,X
	STY @VIRTUAL02
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL02
	LDA @VIRTUAL04
	SEC
	SBC @VIRTUAL02
	TAY
	STY @LOCAL01
	TYA
	CLC
	SBC #0
	BRANCHLTEQS @RETURN
	BRA @CHECK_DASH_LOOP
@ADD_DASH:
	SEP #PROC_FLAGS::ACCUM8
	LDA #3
	LDX @VIRTUAL02
	STA KEYBOARD_INPUT_CHARACTER_OFFSETS,X
	LDX #83
	REP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL RENDER_VWF_CHARACTER
	LDY @LOCAL01
	DEY
	STY @LOCAL01
	INC @VIRTUAL02
@CHECK_DASH_LOOP:
	CPY #0
	BNE @ADD_DASH
@RETURN:
	END_C_FUNCTION
