
INITIALIZE_EXISTING_NAME_VWF:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @VIRTUAL04
	STA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STZ @LOCAL00
	LDX #24
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(KEYBOARD_INPUT_CHARACTER_WIDTHS)
	JSL MEMSET16
	LDY #0
	STY @LOCAL02
	BRA @CHECK_CHAR_LOOP
@PROCESS_CHAR:
	LDA @LOCAL01
	AND #$00FF
	SEC
	SBC #$50
	AND #$007F
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	STA KEYBOARD_INPUT_CHARACTERS,Y
	REP #PROC_FLAGS::ACCUM8
	TXA
	SEP #PROC_FLAGS::ACCUM8
	STA KEYBOARD_INPUT_CHARACTER_OFFSETS,Y
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT FONT_PTR_TABLE, @VIRTUAL06
	TXA
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	TAX
	SEP #PROC_FLAGS::ACCUM8
	CLC
	ADC CHARACTER_PADDING
	STA KEYBOARD_INPUT_CHARACTER_WIDTHS,Y
	LDX @VIRTUAL02
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	AND #$00FF
	TAX
	LDA #0
	JSL RENDER_VWF_CHARACTER
	LDY @LOCAL02
	INY
	STY @LOCAL02
	INC @VIRTUAL02
@CHECK_CHAR_LOOP:
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL01
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQ @AFTER_CHARS
	TYA
	CMP @VIRTUAL04
	BNE @PROCESS_CHAR
@AFTER_CHARS:
	STY NEXT_KEYBOARD_INPUT_INDEX
	TYA
	CMP @VIRTUAL04
	BCS @DONE
	SEP #PROC_FLAGS::ACCUM8
	LDA #32
	STA KEYBOARD_INPUT_CHARACTER_OFFSETS,Y
	LDA #6
	STA KEYBOARD_INPUT_CHARACTER_WIDTHS,Y
	LDX #112
	REP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL RENDER_VWF_CHARACTER
	LDY @LOCAL02
	TYX
	SEP #PROC_FLAGS::ACCUM8
	STZ KEYBOARD_INPUT_CHARACTERS,X
	INY
	STY @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	STY @VIRTUAL04
	SEC
	SBC @VIRTUAL04
	STA @VIRTUAL02
	CLC
	SBC #0
	BRANCHLTEQS @DONE
	BRA @CHECK_DASH_LOOP
@ADD_DASH:
	SEP #PROC_FLAGS::ACCUM8
	LDA #3
	STA KEYBOARD_INPUT_CHARACTER_OFFSETS,Y
	LDX #83
	REP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL RENDER_VWF_CHARACTER
	SEP #PROC_FLAGS::ACCUM8
	LDA #3
	LDY @LOCAL02
	STA KEYBOARD_INPUT_CHARACTER_WIDTHS,Y
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
	DEC
	STA @VIRTUAL02
	INY
	STY @LOCAL02
@CHECK_DASH_LOOP:
	LDA @VIRTUAL02
	BNE @ADD_DASH
@DONE:
	PLD
	RTL
