
RENDER_TINY_FONT_STRING:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;NEAR char*
	STACK_RESERVE_PARAM_INT16 ;NEAR void*
	END_STACK_VARS
	STX @LOCAL05
	STA @VIRTUAL02
	JSL ADVANCE_VWF_TILE
	LDA VWF_TILE
	STA @LOCAL04
	LOADPTR FONT_PTR_TABLE, @VIRTUAL06
	LDY #.SIZEOF(font_table_entry) * FONT::TINY + font_table_entry::height
	LDA [@VIRTUAL06],Y
	STA @LOCAL03
	LDY #.SIZEOF(font_table_entry) * FONT::TINY + font_table_entry::width
	LDA [@VIRTUAL06],Y
	STA @LOCAL02
	LDA #6
	STA @LOCAL01
	LDA @VIRTUAL02
	PROMOTENEARPTRA @VIRTUAL0A
	REP #PROC_FLAGS::ACCUM8
	LDA #0
	STA @VIRTUAL04
	BRA @RENDER_CHAR_CHECK
@RENDER_CHAR_LOOP:
	AND #$00FF
	INC @VIRTUAL02
	SEC
	SBC #CHAR::SPACE
	AND #$007F
	TAY
	MOVE_INT FONT_PTR_TABLE + .SIZEOF(font_table_entry) * FONT::TINY + font_table_entry::graphics, @VIRTUAL06
	LDA @LOCAL03
	JSL MULT16
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX @LOCAL02
	LDA @LOCAL01
	JSL BLIT_VWF_GLYPH
	INC @VIRTUAL04
@RENDER_CHAR_CHECK:
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	AND #$00FF
	BNE @RENDER_CHAR_LOOP
	LDA @LOCAL04
	STA @VIRTUAL02
	BRA @UPLOAD_LOOP_CHECK
@UPLOAD_TILE:
	LDA @VIRTUAL02
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #.LOWORD(VWF_BUFFER)
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDY @LOCAL05
	LDX #16
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	.A16
	LDA @LOCAL05
	CLC
	ADC #8
	STA @LOCAL05
	LDA @VIRTUAL02
	CMP #51
	BNE @NO_WRAP
	LDA #.LOWORD(-1)
	STA @VIRTUAL02
@NO_WRAP:
	INC @VIRTUAL02
@UPLOAD_LOOP_CHECK:
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL0A]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL0A
	AND #$00FF
	BNE @UPLOAD_TILE
	JSL WAIT_UNTIL_NEXT_FRAME
	JSL WAIT_UNTIL_NEXT_FRAME
	END_C_FUNCTION
