
RENDER_CAST_NAME_VWF_JP:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @VIRTUAL04
	STA @LOCAL07
	LDA @VIRTUAL04
	ASL
	INC
	INC
	CLC
	ADC CAST_TEXT_ROW
	CMP #256
	BLTEQ @AFTER_VRAM_CHECK
	STZ CAST_TEXT_ROW
@AFTER_VRAM_CHECK:
	LDA CAST_TEXT_ROW
	STA @LOCAL06
	LOADPTR BUFFER + $4000, @VIRTUAL06
	LDA @LOCAL07
	ASL
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL04
	LDA @VIRTUAL06+2
	STA @LOCAL05
	LDA [@VIRTUAL06]
	AND #$03FF
	STA @LOCAL03
	LDA @VIRTUAL04
	AND #$0001
	BEQL @EVEN_WIDTH_PATH
	LDA @VIRTUAL04
	ASL
	STA @LOCAL02
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA @LOCAL02
	STA @VIRTUAL02
	LDA #2
	SEC
	SBC @VIRTUAL02
	EOR #$FFFF
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	STA [@VIRTUAL0A]
	LDA @LOCAL02
	CLC
	ADC #64
	STA @LOCAL02
	MOVE_INTX @LOCAL04, @VIRTUAL06
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA @LOCAL02
	STA @VIRTUAL02
	LDA #2
	SEC
	SBC @VIRTUAL02
	EOR #$FFFF
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	STA [@VIRTUAL0A]
	INC @VIRTUAL04
	LDA #4
	STA @LOCAL02
	STA @LOCAL00
	LDY @VIRTUAL04
	TAX
	LDA #64
	JSL BLIT_SHIFTED_FONT_TILE_JP
	STA @LOCAL07
	STA @VIRTUAL02
	MOVE_INT @LOCAL04, @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$1C00
	ORA @VIRTUAL02
	STA [@VIRTUAL06]
	LDA #64
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA @LOCAL07
	CLC
	ADC @VIRTUAL04
	STA @VIRTUAL02
	LDA [@VIRTUAL0A]
	AND #$1C00
	ORA @VIRTUAL02
	STA [@VIRTUAL0A]
	INC @VIRTUAL06
	INC @VIRTUAL06
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL01
	BRA @ODD_TILE_LOOP_CHECK
@BLIT_ODD_TILE:
	LDA @LOCAL02
	STA @LOCAL00
	LDY @VIRTUAL04
	LDX #8
	LDA @LOCAL03
	JSL BLIT_SHIFTED_FONT_TILE_JP
	TAX
	LDA [@VIRTUAL06]
	STA @LOCAL07
	AND #$03FF
	STA @LOCAL03
	STX @VIRTUAL02
	LDA @LOCAL07
	AND #$1C00
	ORA @VIRTUAL02
	STA [@VIRTUAL06]
	LDA #64
	MOVE_INTY @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	TXA
	CLC
	ADC @VIRTUAL04
	STA @VIRTUAL02
	LDA [@VIRTUAL0A]
	AND #$1C00
	ORA @VIRTUAL02
	STA [@VIRTUAL0A]
	INC @VIRTUAL06
	INC @VIRTUAL06
	LDA @LOCAL01
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL01
@ODD_TILE_LOOP_CHECK:
	LDA @VIRTUAL04
	DEC
	PHA
	LDA @VIRTUAL02
	PLY
	STY @VIRTUAL02
	CMP @VIRTUAL02
	BCC @BLIT_ODD_TILE
	BRA @UPLOAD_TILES
@EVEN_WIDTH_PATH:
	STZ @LOCAL02
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL01
	BRA @EVEN_TILE_LOOP_CHECK
@BLIT_EVEN_TILE:
	LDA @LOCAL02
	STA @LOCAL00
	LDY @VIRTUAL04
	LDX #8
	LDA @LOCAL03
	JSL BLIT_SHIFTED_FONT_TILE_JP
	DEC
	STA @LOCAL07
	STA @VIRTUAL02
	LDA [@VIRTUAL06]
	AND #$1C00
	ORA @VIRTUAL02
	STA [@VIRTUAL06]
	LDA #64
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA @LOCAL07
	CLC
	ADC @VIRTUAL04
	STA @VIRTUAL02
	LDA [@VIRTUAL0A]
	AND #$1C00
	ORA @VIRTUAL02
	STA [@VIRTUAL0A]
	INC @VIRTUAL06
	INC @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$03FF
	STA @LOCAL03
	LDA @LOCAL01
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL01
@EVEN_TILE_LOOP_CHECK:
	LDA @VIRTUAL02
	CMP @VIRTUAL04
	BCC @BLIT_EVEN_TILE
@UPLOAD_TILES:
	LDA @VIRTUAL04
	INC
	CLC
	ADC CAST_TEXT_ROW
	STA CAST_TEXT_ROW
	LDA @VIRTUAL04
	ASL
	ASL
	ASL
	ASL
	STA @VIRTUAL02
	LOADPTR BUFFER + $2000, @VIRTUAL06
	LDA @LOCAL06
	ASL
	ASL
	ASL
	ASL
	STORE_INT1632 @VIRTUAL0A
	CLC
	ADD_INT_ASSIGN @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL0A, @LOCAL00
	LDA @LOCAL06
	ASL
	ASL
	ASL
	CLC
	ADC #$7000
	TAY
	LDX @VIRTUAL02
	SEP #%00100000
	LDA #0
	JSL PREPARE_VRAM_COPY
	LDA @VIRTUAL04
	CLC
	ADC @LOCAL06
	STA @LOCAL06
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	ASL
	ASL
	ASL
	ASL
	STORE_INT1632 @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @LOCAL06
	ASL
	ASL
	ASL
	CLC
	.A16
	ADC #$7000
	TAY
	LDX @VIRTUAL02
	SEP #%00100000
	LDA #0
	JSL PREPARE_VRAM_COPY
	END_C_FUNCTION
