
RENDER_VWF_CHARACTER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	TXY
	STY @LOCAL05
	STA @VIRTUAL02
	LDA CURRENT_FOCUS_WINDOW
	CMP #.LOWORD(-1)
	BEQL @DONE
	CPY #$2F
	BEQ @PRINT_SPECIAL
	CPY #CHAR::EQUIPPED
	BEQ @PRINT_SPECIAL
	CPY #$20
	BNE @NORMAL_CHAR
@PRINT_SPECIAL:
	TYA
	JSL PRINT_CHAR_WITH_SOUND
	JSL ADVANCE_VWF_TILE
	JMP @DONE
@NORMAL_CHAR:
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	TAX
	LDY @LOCAL05
	CPY #CHAR::SPACE
	BNE @CHECK_INDENT
	LDA VWF_INDENT_NEW_LINE
	AND #$00FF
	BNEL @DONE
	BRA @SETUP_GLYPH
@CHECK_INDENT:
	LDA VWF_INDENT_NEW_LINE
	AND #$00FF
	BEQ @SETUP_GLYPH
	STZ a:window_stats::text_x,X
	CPY #CHAR::BULLET
	BEQ @CLEAR_INDENT
	LDA a:window_stats::text_y,X
	TAX
	LDA #6
	JSL SET_TEXT_PIXEL_POSITION
@CLEAR_INDENT:
	SEP #PROC_FLAGS::ACCUM8
	STZ VWF_INDENT_NEW_LINE
@SETUP_GLYPH:
	LDY @LOCAL05
	REP #PROC_FLAGS::ACCUM8
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA LAST_PRINTED_CHARACTER
	REP #PROC_FLAGS::ACCUM8
	TYA
	SEC
	SBC #$50
	AND #$007F
	STA @LOCAL04
	LOADPTR FONT_PTR_TABLE, @VIRTUAL0A
	LDA @VIRTUAL02
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(font_table_entry)
	TAY
	STY @LOCAL03
	TYA
	CLC
	ADC #font_table_entry::height
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	TAX
	TYA
	INC
	INC
	INC
	INC
	MOVE_INTY @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL06
	LDA @LOCAL04
	TAY
	TXA
	JSL MULT16
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL02
	LDA @VIRTUAL06+2
	STA @LOCAL02+2
	LDY @LOCAL03
	TYA
	CLC
	ADC #font_table_entry::width
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	STA @VIRTUAL02
	TYA
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL0A
	LDA @LOCAL04
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	STA @LOCAL04
	LDA CHARACTER_PADDING
	AND #$00FF
	STA @VIRTUAL04
	LDA @LOCAL04
	CLC
	ADC @VIRTUAL04
	TAY
	STY @LOCAL01
	CPY #8
	BLTEQ @BLIT_FINAL
@BLIT_LARGE_LOOP:
	MOVE_INT @LOCAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX @VIRTUAL02
	LDA #8
	JSL BLIT_VWF_GLYPH
	LDY @LOCAL01
	TYA
	SEC
	SBC #8
	TAY
	STY @LOCAL01
	LDA @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL02
	LDA @VIRTUAL06+2
	STA @LOCAL02+2
	CPY #8
	BGT @BLIT_LARGE_LOOP
@BLIT_FINAL:
	MOVE_INT @LOCAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX @VIRTUAL02
	TYA
	JSL BLIT_VWF_GLYPH
	JSL FLUSH_VWF_TILES_TO_VRAM
@DONE:
	END_C_FUNCTION
