
; unused in EB
RENDER_VWF_TEXT_TILE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	DEC
	STA @LOCAL02
	LDA VWF_UPLOAD_START
	DEC
	STA @LOCAL01
@NEXT_TILE:
	INC @LOCAL02
	LDA @LOCAL02
.IF .DEFINED(JPN)
	CMP #3
.ELSE
	CMP #7
.ENDIF
	BLTEQ @CHECK_ROW_WRAP
	STZ @LOCAL02
@CHECK_ROW_WRAP:
	INC @LOCAL01
	LDA @LOCAL01
	CMP #48
	BCC @COMPUTE_VRAM_ADDR
	STZ @LOCAL01
@COMPUTE_VRAM_ADDR:
	LDA @LOCAL01
	AND #$000F
	ASL
	ASL
	ASL
	STA @VIRTUAL02
	LDA @LOCAL01
	AND #$00F0
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #VRAM::TEXT_LAYER_TILES + $1900
	STA @VIRTUAL04
	LDA @LOCAL02
	ASL
	ASL
	ASL
	ASL
	ASL
	STA @VIRTUAL02
	CLC
	ADC #.LOWORD(VWF_TILE_BUFFER)
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDY @VIRTUAL04
	LDX #16
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	.A16
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(VWF_TILE_BUFFER) + 16
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	COPY_TO_VRAM1OFFSET @VIRTUAL06, @VIRTUAL04, 16, 128, 0
	.A16
	LDA VWF_TILE
	CMP @LOCAL02
	BNEL @NEXT_TILE
	LDA @LOCAL01
	STA VWF_UPLOAD_START
	LDA #1
	STA DMA_TRANSFER_FLAG
	END_C_FUNCTION
