
RESET_VWF_TEXT_STATE:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
@WAIT_DMA:
	LDA DMA_TRANSFER_FLAG
	BNE @WAIT_DMA
	LDX #0
	BRA @FILL_CHECK
@FILL_BYTE:
	SEP #PROC_FLAGS::ACCUM8
	LDA #<-1
	STA VWF_TILE_BUFFER,X
	INX
@FILL_CHECK:
	CPX #32
	BCC @FILL_BYTE
	REP #PROC_FLAGS::ACCUM8
	STZ VWF_TILE
	STZ VWF_X
	LDX VWF_UPLOAD_START
	INX
	STX VWF_UPLOAD_START
	CPX #48
	BCC @DONE
	STZ VWF_UPLOAD_START
@DONE:
	STZ VWF_ACTIVE
.IF .DEFINED(USA)
	JSL CLEAR_TEXT_RENDER_STATE
.ENDIF
	END_C_FUNCTION
