
UPLOAD_VWF_BUFFER_TO_VRAM:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;unused
	END_STACK_VARS
	JSR INVERT_VWF_BUFFER
	LDY #$01A0
	LDA FLYOVER_SCREEN_OFFSET
	JSL MULT16
	STA @LOCAL02
	CLC
	ADC #$04E0
	CMP #$3400
	BGT @HANDLE_WRAP
	JMP @NO_WRAP
@HANDLE_WRAP:
	LDA @LOCAL02
	STA @VIRTUAL02
	LDA #$3400
	SEC
	SBC @VIRTUAL02
	STA @LOCAL01
	BEQ @UPLOAD_WRAPPED_PORTION
	PROMOTENEARPTR VWF_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA FLYOVER_SCREEN_OFFSET
	LDY #208
	JSL MULT168
	CLC
	ADC #VRAM::TEXT_LAYER_TILES + $150
	TAY
	LDA @LOCAL01
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
@UPLOAD_WRAPPED_PORTION:
	LDY #$01A0
	LDA FLYOVER_SCREEN_OFFSET
	JSL MULT16
	.A16
	STA @LOCAL02
	CLC
	ADC #$04E0
	SEC
	SBC #$3400
	TAX
	BEQ @AFTER_UPLOAD
	LDA @LOCAL02
	STA @VIRTUAL02
	LDA #VRAM::TEXT_LAYER_TILES + $892 ;an upper limit on tile size
	SEC
	SBC @VIRTUAL02
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDY #VRAM::TEXT_LAYER_TILES + $150
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	BRA @AFTER_UPLOAD
@NO_WRAP:
	.A16
	PROMOTENEARPTR VWF_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA FLYOVER_SCREEN_OFFSET
	LDY #208
	JSL MULT168
	CLC
	ADC #VRAM::TEXT_LAYER_TILES + $150
	TAY
	LDX #$04E0
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
@AFTER_UPLOAD:
	.A16
	LDA #.LOWORD(-1)
	STA FLYOVER_DIRTY_MIN
	STZ FLYOVER_DIRTY_MAX
	JSL WAIT_UNTIL_NEXT_FRAME
	END_C_FUNCTION
