
ANIMATE_WINDOW_BORDER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #3
	JSR SET_WINDOW_PALETTE_INDEX
	LOADPTR WINDOW_BORDER_ANIM_TILES_ROW1, @VIRTUAL06
	BRA @NEXT_TILE
@PROCESS_TILE:
	INC @VIRTUAL06
	INC @VIRTUAL06
	JSR SET_TILE_ATTRIBUTE_AND_REDRAW
	LDX #1
	STX @LOCAL00
	BRA @TICK_CHECK
@TICK_LOOP:
	JSL WINDOW_TICK
@TICK_CHECK:
	LDX @LOCAL00
	TXA
	DEX
	STX @LOCAL00
	CMP #0
	BNE @TICK_LOOP
@NEXT_TILE:
	LDA [@VIRTUAL06]
	BNE @PROCESS_TILE
	LDA #0
	JSR SET_WINDOW_PALETTE_INDEX
	END_C_FUNCTION
