
APPLY_WINDOW_TEXT_ATTRIBUTES:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	TAX
	STX @LOCAL02
	LDA a:window_stats::curr_tile_attributes,X
	STA @LOCAL01
	LDA a:window_stats::width,X
	STA @VIRTUAL04
	LDY @VIRTUAL04
	LDA a:window_stats::text_y,X
	JSL MULT16
	ASL
	ASL
	CLC
	ADC a:window_stats::tilemap_address,X
	TAY
	LDA @VIRTUAL04
	DEC
	STA @VIRTUAL02
	STA @LOCAL00
	BRA @CHECK_EMPTY
@FIND_LAST_CHAR:
	LDA @LOCAL00
	STA @VIRTUAL02
	DEC
	STA @VIRTUAL02
	STA @LOCAL00
@CHECK_EMPTY:
	LDA @VIRTUAL02
	ASL
	STA @VIRTUAL02
	TYA
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	CMP #64
	BEQ @FIND_LAST_CHAR
	LDX @LOCAL02
	LDA a:window_stats::text_x,X
	STA @LOCAL02
	ASL
	STA @VIRTUAL02
	TYA
	CLC
	ADC @VIRTUAL02
	TAX
	LDA @LOCAL02
	STA @LOCAL02
	BRA @APPLY_LOOP_CHECK
@APPLY_LOOP_BODY:
	LDA __BSS_START__,X
	AND #$03FF
	ORA @LOCAL01
	STA __BSS_START__,X
	LDA @VIRTUAL04
	ASL
	STA @VIRTUAL02
	TXA
	CLC
	ADC @VIRTUAL02
	TAY
	LDA __BSS_START__,Y
	AND #$03FF
	ORA @LOCAL01
	STA __BSS_START__,Y
	INX
	INX
	LDA @LOCAL02
	INC
	STA @LOCAL02
@APPLY_LOOP_CHECK:
	LDY @LOCAL00
	STY @VIRTUAL02
	INC @VIRTUAL02
	CMP @VIRTUAL02
	BCC @APPLY_LOOP_BODY
	END_C_FUNCTION
