
CLEAR_WINDOW_CONTENT:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
.IF .DEFINED(JPN)
	@TMP00 := @LOCAL00
	@TMP01 := @LOCAL01
.ELSE
	@TMP00 := @VIRTUAL02
	@TMP01 := @LOCAL00
.ENDIF
	CMP #.LOWORD(-1)
	BEQ @DONE
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	TAX
.IF .DEFINED(USA)
	STX @LOCAL01
.ENDIF
	LDY a:window_stats::tilemap_address,X
	STY @TMP01
	LDY a:window_stats::height,X
	LDA a:window_stats::width,X
	JSL MULT16
	STA @TMP00
	BRA @LOOP_CHECK
@CLEAR_TILE_LOOP:
.IF .DEFINED(USA)
	LDY @LOCAL00
	LDA __BSS_START__,Y
	BEQ @SKIP_FREE_TILE
	JSL FREE_TILE_SAFE
.ENDIF
@SKIP_FREE_TILE:
	LDA #64
	LDY @TMP01
	STA __BSS_START__,Y
	INY
	INY
	STY @TMP01
	LDA @TMP00
	DEC
	STA @TMP00
@LOOP_CHECK:
.IF .DEFINED(JPN)
	CMP #0
	BNE @CLEAR_TILE_LOOP
.ELSE
	LDA @TMP00
	BNE @CLEAR_TILE_LOOP
	JSL RESET_VWF_TEXT_STATE
	LDX @LOCAL01
.ENDIF
	STZ a:window_stats::text_y,X
	STZ a:window_stats::text_x,X
@DONE:
	END_C_FUNCTION
