
DISPLAY_MONEY_WINDOW:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
	JSL SAVE_WINDOW_TEXT_ATTRIBUTES
	CREATE_WINDOW_NEAR #WINDOW::CARRIED_MONEY
	LDA #5
	JSR SET_WINDOW_NUMBER_PADDING
	JSL SET_INSTANT_PRINTING
	JSR CLEAR_FOCUS_WINDOW_CONTENT
	MOVE_INT GAME_STATE + game_state::money_carried, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL PRINT_MONEY_IN_WINDOW
	JSL CLEAR_INSTANT_PRINTING
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
	JSL RESTORE_WINDOW_TEXT_ATTRIBUTES
	END_C_FUNCTION
