
DISPATCH_WINDOW_BORDER_ANIMATION:
	BEGIN_C_FUNCTION
	END_STACK_VARS
	CMP #1
	BEQ @ANIMATE_BORDER
	CMP #2
	BEQ @ANIMATE_BORDER_HPPP
	BRA @DONE
@ANIMATE_BORDER:
	JSL ANIMATE_WINDOW_BORDER
	BRA @DONE
@ANIMATE_BORDER_HPPP:
	JSL ANIMATE_WINDOW_BORDER_WITH_HPPP
@DONE:
	END_C_FUNCTION
