
GET_WINDOW_MENU_OPTION_COUNT:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	CMP #$0000
	BNE @HAS_WINDOW_ID
	LDA CURRENT_FOCUS_WINDOW
@HAS_WINDOW_ID:
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA WINDOW_STATS+window_stats::current_option,X
	JSR COUNT_MENU_OPTION_CHAIN
	RTS
