
PREVIEW_WINDOW_FLAVOUR:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL01
	LDX #.LOWORD(GAME_STATE)+game_state::text_flavour
	STX @LOCAL00
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	STA __BSS_START__,X
	JSL LOAD_WINDOW_GFX
	.A16
	LDA #2
	JSL UPLOAD_TEXT_TILES_TO_VRAM
	JSL LOAD_CHARACTER_WINDOW_PALETTE
	SEP #PROC_FLAGS::ACCUM8
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
	LDA @VIRTUAL00
	LDX @LOCAL00
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
