
RENDER_WINDOW_FRAME:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL08
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	STA @LOCAL07
	TAX
	LDA WINDOW_STATS + window_stats::tilemap_address,X
	STA @LOCAL06
	LDA @LOCAL07
	TAX
	LDA WINDOW_STATS + window_stats::window_x,X
	ASL
	STA @VIRTUAL02
	LDA @LOCAL07
	TAX
	LDA WINDOW_STATS + window_stats::window_y,X
	OPTIMIZED_MULT @VIRTUAL04, 64
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #.LOWORD(BG2_BUFFER)
	TAX
	STX @LOCAL05
	LDA @LOCAL07
	TAX
	LDY WINDOW_STATS + window_stats::width,X
	STY @LOCAL04
	STY @LOCAL03
	TAX
	LDA WINDOW_STATS + window_stats::height,X
	STA @LOCAL02
	LDX @LOCAL05
	LDA __BSS_START__,X
	BEQ @TOPLEFT_NORMAL
	CMP #$3C10
	BNE @TOPLEFT_OVERLAP
@TOPLEFT_NORMAL:
	LDA #$3C10
	STA __BSS_START__,X
	STX @VIRTUAL02
	INC @VIRTUAL02
	INC @VIRTUAL02
	BRA @CHECK_TITLE
@TOPLEFT_OVERLAP:
	LDA #$3C13
	STA __BSS_START__,X
	STX @VIRTUAL02
	INC @VIRTUAL02
	INC @VIRTUAL02
@CHECK_TITLE:
	LDA @LOCAL08
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA WINDOW_STATS + window_stats::unknown59,X
	STA @LOCAL01
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQ @AFTER_TITLE
	TXA
	CLC
	ADC #.LOWORD(WINDOW_STATS) + window_stats::title
	STA @VIRTUAL04
	LDA @LOCAL01
	AND #$00FF
	DEC
	OPTIMIZED_MULT @VIRTUAL04, 16
	CLC
	ADC #$02E0
	STA @LOCAL00
	LDA #$3C16
	LDX @VIRTUAL02
	STA __BSS_START__,X
	LDX @VIRTUAL02
	INX
	INX
	STX @LOCAL05
	LDY @LOCAL04
	DEY
	BRA @TITLE_LOOP_CHECK
@WRITE_TITLE_TILE:
	LDA @LOCAL00
	CLC
	ADC #$2000
	LDX @LOCAL05
	STA __BSS_START__,X
	LDA @LOCAL00
	INC
	STA @LOCAL00
	INX
	INX
	STX @LOCAL05
	DEY
	INC @VIRTUAL04
@TITLE_LOOP_CHECK:
	LDX @VIRTUAL04
	LDA __BSS_START__,X
	AND #$00FF
	BNE @WRITE_TITLE_TILE
	LDA #$7C16
	LDX @LOCAL05
	STA __BSS_START__,X
	STX @VIRTUAL02
	INC @VIRTUAL02
	INC @VIRTUAL02
	DEY
	STY @LOCAL04
@AFTER_TITLE:
	LDA @LOCAL08
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA WINDOW_STATS + window_stats::id,X
	CMP PAGINATION_WINDOW
	BNE @AFTER_PAGINATION_CHECK
	LDA PAGINATION_ANIMATION_FRAME
	CMP #.LOWORD(-1)
	BEQ @AFTER_PAGINATION_CHECK
	LDY @LOCAL04
	TYA
	SEC
	SBC #4
	TAY
	STY @LOCAL04
@AFTER_PAGINATION_CHECK:
	LDY @LOCAL04
	TYX
	STX @LOCAL05
	BRA @TOP_EDGE_LOOP_CHECK
@WRITE_TOP_EDGE:
	LDA #$3C11
	LDX @VIRTUAL02
	STA __BSS_START__,X
	INC @VIRTUAL02
	INC @VIRTUAL02
	LDX @LOCAL05
	DEX
	STX @LOCAL05
@TOP_EDGE_LOOP_CHECK:
	BNE @WRITE_TOP_EDGE
	LDA @LOCAL08
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA WINDOW_STATS + window_stats::id,X
	CMP PAGINATION_WINDOW
	BNE @AFTER_PAGINATION
	LDA PAGINATION_ANIMATION_FRAME
	CMP #.LOWORD(-1)
	BEQ @AFTER_PAGINATION
	LOADPTR PAGINATION_ANIM_TILES_PTR_TABLE, @VIRTUAL0A
	LDA PAGINATION_ANIMATION_FRAME
	ASL
	ASL
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	LDX #0
	STX @LOCAL00
	BRA @PAGINATION_LOOP_CHECK
@WRITE_PAGINATION_TILE:
	LDA [@VIRTUAL06]
	LDX @VIRTUAL02
	STA __BSS_START__,X
	INC @VIRTUAL06
	INC @VIRTUAL06
	INC @VIRTUAL02
	INC @VIRTUAL02
	LDX @LOCAL00
	INX
	STX @LOCAL00
@PAGINATION_LOOP_CHECK:
	CPX #4
	BCC @WRITE_PAGINATION_TILE
@AFTER_PAGINATION:
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	BEQ @TOPRIGHT_NORMAL
	CMP #$7C10
	BNE @TOPRIGHT_OVERLAP
@TOPRIGHT_NORMAL:
	LDA #$7C10
	LDX @VIRTUAL02
	STA __BSS_START__,X
	LDA @VIRTUAL02
	INC
	INC
	STA @LOCAL08
	BRA @AFTER_TOPRIGHT
@TOPRIGHT_OVERLAP:
	LDA #$7C13
	LDX @VIRTUAL02
	STA __BSS_START__,X
	LDA @VIRTUAL02
	INC
	INC
	STA @LOCAL08
@AFTER_TOPRIGHT:
	LDA #32
	SEC
	SBC @LOCAL03
	DEC
	DEC
	ASL
	STA @VIRTUAL02
	LDA @LOCAL08
	CLC
	ADC @VIRTUAL02
	TAX
	LDY @LOCAL02
	BRA @ROW_LOOP_CHECK
@WRITE_ROW:
	LDA #$3C12
	STA __BSS_START__,X
	INX
	INX
	LDA @LOCAL03
	STA @LOCAL00
	BRA @BODY_TILE_LOOP_CHECK
@WRITE_BODY_TILE:
	LDA (@LOCAL06)
	CLC
	ADC #$2000
	STA __BSS_START__,X
	INC @LOCAL06
	INC @LOCAL06
	INX
	INX
	LDA @LOCAL00
	DEC
	STA @LOCAL00
@BODY_TILE_LOOP_CHECK:
	BNE @WRITE_BODY_TILE
	LDA #$7C12
	STA __BSS_START__,X
	TXA
	INC
	INC
	STA @LOCAL02
	LDA #32
	SEC
	SBC @LOCAL03
	DEC
	DEC
	ASL
	STA @VIRTUAL02
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL02
	TAX
	DEY
@ROW_LOOP_CHECK:
	BNE @WRITE_ROW
	LDA __BSS_START__,X
	BEQ @BOTTOMLEFT_NORMAL
	CMP #$BC10
	BNE @BOTTOMLEFT_OVERLAP
@BOTTOMLEFT_NORMAL:
	LDA #$BC10
	STA __BSS_START__,X
	TXY
	INY
	INY
	BRA @AFTER_BOTTOMLEFT
@BOTTOMLEFT_OVERLAP:
	LDA #$BC13
	STA __BSS_START__,X
	TXY
	INY
	INY
@AFTER_BOTTOMLEFT:
	LDX @LOCAL03
	BRA @BOTTOM_EDGE_LOOP_CHECK
@WRITE_BOTTOM_EDGE:
	LDA #$BC11
	STA __BSS_START__,Y
	INY
	INY
	DEX
@BOTTOM_EDGE_LOOP_CHECK:
	BNE @WRITE_BOTTOM_EDGE
	LDA __BSS_START__,Y
	BEQ @BOTTOMRIGHT_NORMAL
	CMP #$FC10
	BNE @BOTTOMRIGHT_OVERLAP
@BOTTOMRIGHT_NORMAL:
	LDA #$FC10
	STA __BSS_START__,Y
	BRA @RETURN
@BOTTOMRIGHT_OVERLAP:
	LDA #$FC13
	STA __BSS_START__,Y
@RETURN:
	END_C_FUNCTION
