
RENDER_WINDOW_FRAME:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL08
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAY
	LDA WINDOW_STATS + window_stats::tilemap_address,Y
	STA @LOCAL07
	LDA WINDOW_STATS + window_stats::window_x,Y
	ASL
	STA @VIRTUAL02
	LDA WINDOW_STATS + window_stats::window_y,Y
	OPTIMIZED_MULT @VIRTUAL04, 64
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #.LOWORD(BG2_BUFFER)
	TAX
	LDA WINDOW_STATS + window_stats::width,Y
	STA @VIRTUAL04
	STA @LOCAL06
	LDA WINDOW_STATS + window_stats::height,Y
	STA @LOCAL05
	LDA __BSS_START__,X
	BEQ @TOPLEFT_NORMAL
	CMP #$3C10
	BNE @TOPLEFT_OVERLAP
@TOPLEFT_NORMAL:
	LDA #$3C10
	STA __BSS_START__,X
	TXY
	INY
	INY
	STY @LOCAL04
	BRA @CHECK_TITLE
@TOPLEFT_OVERLAP:
	LDA #$3C13
	STA __BSS_START__,X
	TXY
	INY
	INY
	STY @LOCAL04
@CHECK_TITLE:
	LDA @LOCAL08
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	STA @LOCAL03
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA WINDOW_STATS + window_stats::unknown59,X
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	AND #$00FF
	BEQL @AFTER_TITLE
	LDA @LOCAL03
	CLC
	ADC #.LOWORD(WINDOW_STATS) + window_stats::title
	STA @LOCAL02
	LDA @VIRTUAL00
	AND #$00FF
	DEC
	OPTIMIZED_MULT @VIRTUAL04, 16
	CLC
	ADC #$02E0
	STA @VIRTUAL02
	LDA #$3C16
	LDY @LOCAL04
	STA __BSS_START__,Y
	TYX
	INX
	INX
	STX @LOCAL04
	LDA @VIRTUAL04
	DEC
	STA @VIRTUAL04
	STA @LOCAL01
	LDA @LOCAL02
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL STRLEN
	STA @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	ASL
	CLC
	ADC #7
	LSR
	LSR
	LSR
	STA @LOCAL02
	BRA @TITLE_LOOP_CHECK
@WRITE_TITLE_TILE:
	LDA @VIRTUAL02
	CLC
	ADC #$2000
	LDX @LOCAL04
	STA __BSS_START__,X
	INC @VIRTUAL02
	INX
	INX
	STX @LOCAL04
	LDA @LOCAL01
	STA @VIRTUAL04
	DEC
	STA @VIRTUAL04
	STA @LOCAL01
	LDA @LOCAL02
	DEC
	STA @LOCAL02
@TITLE_LOOP_CHECK:
	BNE @WRITE_TITLE_TILE
	LDA #$7C16
	LDX @LOCAL04
	STA __BSS_START__,X
	TXY
	INY
	INY
	STY @LOCAL04
	LDA @LOCAL01
	STA @VIRTUAL04
	DEC
	STA @VIRTUAL04
@AFTER_TITLE:
	LDA @LOCAL08
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA WINDOW_STATS+window_stats::id,X
	CMP PAGINATION_WINDOW
	BNE @AFTER_PAGINATION_CHECK
	LDA PAGINATION_ANIMATION_FRAME
	CMP #$FFFF
	BEQ @AFTER_PAGINATION_CHECK
	LDA @VIRTUAL04
	SEC
	SBC #4
	STA @VIRTUAL04
@AFTER_PAGINATION_CHECK:
	LDX @VIRTUAL04
	BRA @TOP_EDGE_LOOP_CHECK
@WRITE_TOP_EDGE:
	LDA #$3C11
	LDY @LOCAL04
	STA __BSS_START__,Y
	INY
	INY
	STY @LOCAL04
	DEX
@TOP_EDGE_LOOP_CHECK:
	BNE @WRITE_TOP_EDGE
	LDA @LOCAL08
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA WINDOW_STATS+window_stats::id,X
	CMP PAGINATION_WINDOW
	BNE @AFTER_PAGINATION
	LDA PAGINATION_ANIMATION_FRAME
	CMP #.LOWORD(-1)
	BEQ @AFTER_PAGINATION
	LOADPTR PAGINATION_ANIM_TILES_PTR_TABLE, @VIRTUAL0A
	LDA PAGINATION_ANIMATION_FRAME
	ASL
	ASL
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	LDX #0
	BRA @PAGINATION_LOOP_CHECK
@WRITE_PAGINATION_TILE:
	LDA [@VIRTUAL06]
	LDY @LOCAL04
	STA __BSS_START__,Y
	INC @VIRTUAL06
	INC @VIRTUAL06
	INY
	INY
	STY @LOCAL04
	INX
@PAGINATION_LOOP_CHECK:
	CPX #4
	BCC @WRITE_PAGINATION_TILE
@AFTER_PAGINATION:
	LDY @LOCAL04
	LDA __BSS_START__,Y
	BEQ @TOPRIGHT_NORMAL
	CMP #$7C10
	BNE @TOPRIGHT_OVERLAP
@TOPRIGHT_NORMAL:
	LDA #$7C10
	STA __BSS_START__,Y
	TYA
	INC
	INC
	STA @LOCAL08
	BRA @AFTER_TOPRIGHT
@TOPRIGHT_OVERLAP:
	LDA #$7C13
	STA __BSS_START__,Y
	TYA
	INC
	INC
	STA @LOCAL08
@AFTER_TOPRIGHT:
	LDA #32
	SEC
	SBC @LOCAL06
	DEC
	DEC
	ASL
	STA @VIRTUAL02
	LDA @LOCAL08
	CLC
	ADC @VIRTUAL02
	TAX
	LDY @LOCAL05
	BRA @ROW_LOOP_CHECK
@WRITE_ROW:
	LDA #$3C12
	STA __BSS_START__,X
	INX
	INX
	LDA @LOCAL06
	STA @LOCAL04
	BRA @BODY_TILE_LOOP_CHECK
@WRITE_BODY_TILE:
	LDA (@LOCAL07)
	CLC
	ADC #$2000
	STA __BSS_START__,X
	INC @LOCAL07
	INC @LOCAL07
	INX
	INX
	LDA @LOCAL04
	DEC
	STA @LOCAL04
@BODY_TILE_LOOP_CHECK:
	BNE @WRITE_BODY_TILE
	LDA #$7C12
	STA __BSS_START__,X
	TXA
	INC
	INC
	STA @LOCAL03
	LDA #32
	SEC
	SBC @LOCAL06
	DEC
	DEC
	ASL
	STA @VIRTUAL02
	LDA @LOCAL03
	CLC
	ADC @VIRTUAL02
	TAX
	DEY
@ROW_LOOP_CHECK:
	BNE @WRITE_ROW
	LDA __BSS_START__,X
	BEQ @BOTTOMLEFT_NORMAL
	CMP #$BC10
	BNE @BOTTOMLEFT_OVERLAP
@BOTTOMLEFT_NORMAL:
	LDA #$BC10
	STA __BSS_START__,X
	TXY
	INY
	INY
	BRA @AFTER_BOTTOMLEFT
@BOTTOMLEFT_OVERLAP:
	LDA #$BC13
	STA __BSS_START__,X
	TXY
	INY
	INY
@AFTER_BOTTOMLEFT:
	LDX @LOCAL06
	BRA @BOTTOM_EDGE_LOOP_CHECK
@WRITE_BOTTOM_EDGE:
	LDA #$BC11
	STA __BSS_START__,Y
	INY
	INY
	DEX
@BOTTOM_EDGE_LOOP_CHECK:
	BNE @WRITE_BOTTOM_EDGE
	LDA __BSS_START__,Y
	BEQ @BOTTOMRIGHT_NORMAL
	CMP #$FC10
	BNE @BOTTOMRIGHT_OVERLAP
@BOTTOMRIGHT_NORMAL:
	LDA #$FC10
	STA __BSS_START__,Y
	BRA @RETURN
@BOTTOMRIGHT_OVERLAP:
	LDA #$FC13
	STA __BSS_START__,Y
@RETURN:
	END_C_FUNCTION
