
SET_WINDOW_TILE_ATTRIBUTE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL00
	LDA CURRENT_FOCUS_WINDOW
	CMP #.LOWORD(-1)
	BEQ @RETURN
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDY WINDOW_STATS + window_stats::curr_tile_attributes,X
	LDX @LOCAL00
	LDA CURRENT_FOCUS_WINDOW
	JSR WRITE_TILE_TO_WINDOW
@RETURN:
	END_C_FUNCTION
