
WRITE_CHAR_TO_WINDOW:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @LOCAL05
	STA @LOCAL04
	LDA CURRENT_FOCUS_WINDOW
	CMP #.LOWORD(-1)
	BEQL @DONE
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	CMP #.LOWORD(-1)
	BEQL @DONE
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	STA @VIRTUAL02
	STA @LOCAL03
	LDX @VIRTUAL02
	LDA a:window_stats::text_x,X
	STA @VIRTUAL04
	LDX @VIRTUAL02
	LDA a:window_stats::text_y,X
	STA @LOCAL02
	LDX @VIRTUAL02
	LDA a:window_stats::curr_tile_attributes,X
	STA @LOCAL01
	LDX @VIRTUAL02
	LDA @VIRTUAL04
	CMP a:window_stats::width,X
	BNE @CALC_TILE_POSITION
	LDA #0
	STA @VIRTUAL04
	LDX @VIRTUAL02
	LDA a:window_stats::height,X
	LSR
	DEC
	CMP @LOCAL02
	BEQ @AT_BOTTOM
	INC @LOCAL02
	BRA @CHECK_WORD_WRAP_INDENT
@AT_BOTTOM:
	LDA f:ALLOW_TEXT_OVERFLOW
	AND #$00FF
	BNEL @UPDATE_CURSOR
	LDA CURRENT_FOCUS_WINDOW
	JSL SCROLL_WINDOW_UP_FAR
@CHECK_WORD_WRAP_INDENT:
	LDA ENABLE_WORD_WRAP
	BEQ @CALC_TILE_POSITION
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA VWF_INDENT_NEW_LINE
@CALC_TILE_POSITION:
	REP #PROC_FLAGS::ACCUM8
	LDA BLINKING_TRIANGLE_FLAG
	BEQ @COMPUTE_TILEMAP_OFFSET
	LDA @VIRTUAL04
	BNE @COMPUTE_TILEMAP_OFFSET
	LDA @LOCAL04
	CMP #$20
	BEQ @CHECK_TRIANGLE_MODE
	LDA @LOCAL04
	CMP #CHAR::BULLET
	BNE @COMPUTE_TILEMAP_OFFSET
@CHECK_TRIANGLE_MODE:
	LDA BLINKING_TRIANGLE_FLAG
	CMP #1
	BEQL @UPDATE_CURSOR
	CMP #2
	BNE @COMPUTE_TILEMAP_OFFSET
	LDA #$20
	STA @LOCAL04
@COMPUTE_TILEMAP_OFFSET:
	LDA @VIRTUAL04
	ASL
	PHA
	LDX @VIRTUAL02
	LDY a:window_stats::width,X
	LDA @LOCAL02
	JSL MULT16
	ASL
	ASL
	LDX @VIRTUAL02
	CLC
	ADC a:window_stats::tilemap_address,X
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	TAY
	STY @LOCAL00
	LDA __BSS_START__,Y
	BEQ @CHECK_UPPER_EQUIPPED
	JSL FREE_TILE_SAFE
@CHECK_UPPER_EQUIPPED:
	LDA @LOCAL04
	CMP #CHAR::EQUIPPED
	BNE @UPPER_NORMAL_ATTR
	LDX #$0C00
	BRA @STORE_UPPER_TILE
@UPPER_NORMAL_ATTR:
	LDX @LOCAL01
@STORE_UPPER_TILE:
	TXA
	CLC
	ADC @LOCAL04
	LDY @LOCAL00
	STA __BSS_START__,Y
	LDA @LOCAL03
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA a:window_stats::width,X
	ASL
	STA @VIRTUAL02
	TYA
	CLC
	ADC @VIRTUAL02
	TAY
	STY @LOCAL04
	LDA __BSS_START__,Y
	BEQ @CHECK_LOWER_EQUIPPED
	JSL FREE_TILE_SAFE
@CHECK_LOWER_EQUIPPED:
	LDA @LOCAL05
	CMP #CHAR::EQUIPPED
	BNE @LOWER_NORMAL_ATTR
	LDX #$0C00
	BRA @STORE_LOWER_TILE
@LOWER_NORMAL_ATTR:
	LDX @LOCAL01
@STORE_LOWER_TILE:
	TXA
	CLC
	ADC @LOCAL05
	LDY @LOCAL04
	STA __BSS_START__,Y
	INC @VIRTUAL04
@UPDATE_CURSOR:
	LDA @VIRTUAL04
	LDX @LOCAL03
	STX @VIRTUAL02
	STA a:window_stats::text_x,X
	LDA @LOCAL02
	LDX @VIRTUAL02
	STA a:window_stats::text_y,X
@DONE:
	END_C_FUNCTION
