
;unused
UNUSED_UPDATE_TILEMAP_REGION_4X4:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LOADPTR DEBUG_TILEMAP_DATA, @LOCAL00
	LDX #31
	LDA #926
	JSL UPDATE_TILEMAP_REGION
	END_C_FUNCTION
