
CLEAR_BATTLE_VISUAL_EFFECTS:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	STZ GREEN_FLASH_DURATION
	STZ RED_FLASH_DURATION
	SEP #PROC_FLAGS::ACCUM8
	STZ FRAMES_UNTIL_NEXT_SWIRL_UPDATE
	REP #PROC_FLAGS::ACCUM8
	LDA HP_PP_BOX_BLINK_DURATION
	BEQ @SKIP_BLINK_REDRAW
	LDA HP_PP_BOX_BLINK_TARGET
	JSL DRAW_AND_MARK_HPPP_WINDOW
	STZ HP_PP_BOX_BLINK_DURATION
@SKIP_BLINK_REDRAW:
	LDY #0
	TYX
	TYA
	JSL SET_COLDATA
	LDA #1
	JSL SET_COLOR_MATH_FROM_TABLE
	END_C_FUNCTION
