
GET_EFFECTIVE_HPPP_METER_SPEED:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_RETURN_INT32
	END_STACK_VARS
	LDA HALF_HPPP_METER_SPEED
	AND #$00FF
	BEQ @FULL_SPEED
	SEP #PROC_FLAGS::INDEX8
	LDY #1
	MOVE_INT HP_METER_SPEED, @VIRTUAL06
	JSL ASR32
	MOVE_INT @VIRTUAL06, @RETURNVAL
	BRA @RETURN
@FULL_SPEED:
	MOVE_INT HP_METER_SPEED, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @RETURNVAL
@RETURN:
	REP #PROC_FLAGS::INDEX8
	END_C_FUNCTION
