
INTERPOLATE_BG_PALETTE_COLORS:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL04
	LDA LOADED_BG_DATA_LAYER1 + loaded_bg_data::bitdepth
	AND #$00FF
	CMP #4
	BNE @MODE_2BPP
	LDA #1
	STA @VIRTUAL02
	BRA @4BPP_LOOP_CHECK
@INTERPOLATE_4BPP:
	LDY @VIRTUAL02
	LDX @VIRTUAL04
	LDA #.LOWORD(LOADED_BG_DATA_LAYER1)
	JSR INTERPOLATE_BG_PALETTE_COLOR
	INC @VIRTUAL02
@4BPP_LOOP_CHECK:
	LDA @VIRTUAL02
	CMP #16
	BCC @INTERPOLATE_4BPP
	BRA @RETURN
@MODE_2BPP:
	LDA #1
	STA @VIRTUAL02
	BRA @2BPP_LOOP_CHECK
@INTERPOLATE_2BPP:
	LDY @VIRTUAL02
	LDX @VIRTUAL04
	LDA #.LOWORD(LOADED_BG_DATA_LAYER1)
	JSR INTERPOLATE_BG_PALETTE_COLOR
	LDY @VIRTUAL02
	LDX @VIRTUAL04
	LDA #.LOWORD(LOADED_BG_DATA_LAYER2)
	JSR INTERPOLATE_BG_PALETTE_COLOR
	INC @VIRTUAL02
@2BPP_LOOP_CHECK:
	LDA @VIRTUAL02
	CMP #4
	BCC @INTERPOLATE_2BPP
@RETURN:
	END_C_FUNCTION
