
LOAD_ATTACK_PALETTE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int attackType
	END_STACK_VARS
	TAX
	TXY
	TXA
	DEC
	STA @LOCAL01
	CPY #0
	BEQ @NO_ATTACK_TYPE
	LOADPTR ATTACK_TYPE_PALETTES, @VIRTUAL06
	LDA @LOCAL01
	OPTIMIZED_MULT @VIRTUAL04, BPP4PALETTE_SIZE
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX #BPP4PALETTE_SIZE
	LDA #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 12
	JSL MEMCPY16
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #BPP4PALETTE_SIZE
	LDA #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 13
	JSL MEMCPY16
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #BPP4PALETTE_SIZE
	LDA #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 14
	JSL MEMCPY16
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #BPP4PALETTE_SIZE
	LDA #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 15
	JSL MEMCPY16
	LDA #16
	JSL SET_PALETTE_UPLOAD_MODE
	BRA @RETURN
@NO_ATTACK_TYPE:
	LDA #BPP4PALETTE_SIZE * 4
	STA @LOCAL01
	BRA @DARKEN_LOOP_CHECK
@DARKEN_ENTRY:
	ASL
	TAX
	LDA PALETTES,X
	LSR
	LSR ;divide entire colour by two. normally, this would cause the lower two bits of each channel to bleed into the next, but...
	AND #(7 << 10) +(7 << 5) + 7 ;we keep only the bottom 3 bits of each colour channel. combined, this just darkens the colour.
	STA PALETTES + (BPP4PALETTE_SIZE * 4),X
	LDA @LOCAL01
	INC
	STA @LOCAL01
@DARKEN_LOOP_CHECK:
	CMP #BPP4PALETTE_SIZE * 6
	BCC @DARKEN_ENTRY
	LDA #16
	JSL SET_PALETTE_UPLOAD_MODE
@RETURN:
	END_C_FUNCTION
