
REVERSE_BATTLE_SPRITE_PALETTE_EFFECT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TXY
	TAX
	STX BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	TYA
	ASL
	TAX
	LDA BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	STA BATTLE_SPRITE_PALETTE_EFFECT_FRAMES_LEFT,X
	LDX #0
	STX @LOCAL01
	BRA @LOOP_CHECK
@LOOP_BODY:
	STX @VIRTUAL02
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 48
	CLC
	ADC @VIRTUAL02
	ASL
	STA @LOCAL00
	CLC
	ADC #.LOWORD(BATTLE_SPRITE_PALETTE_EFFECT_DELTAS)
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	EOR #$FFFF
	INC
	LDX @VIRTUAL02
	STA __BSS_START__,X
	LDA @LOCAL00
	TAX
	STZ BATTLE_SPRITE_PALETTE_EFFECT_COUNTERS,X
	LDX @LOCAL01
	INX
	STX @LOCAL01
@LOOP_CHECK:
	CPX #48
	BCC @LOOP_BODY
	END_C_FUNCTION
