
SETUP_BATTLE_SPRITE_PALETTE_EFFECT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL06
	STX @VIRTUAL04
	STX @LOCAL05
	STA @LOCAL04
	LDX @PARAM03
	STX @LOCAL03
	LSR
	LSR
	LSR
	LSR
	ASL
	TAX
	LDA BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	STA BATTLE_SPRITE_PALETTE_EFFECT_FRAMES_LEFT,X
	LDA @LOCAL04
	ASL
	TAX
	LDA PALETTES + 12 * BPP4PALETTE_SIZE,X
	STA @LOCAL02
	AND #$001F
	STA @VIRTUAL02
	LDA @LOCAL02
	LSR
	LSR
	LSR
	LSR
	LSR
	AND #$001F
	TAX
	STX @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	LDA #10
	SEP #PROC_FLAGS::INDEX8
	TAY
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	JSL ASR8_POSITIVE
	AND #$001F
	STA @LOCAL00
	LDA @VIRTUAL04
	CMP @VIRTUAL02
	BLTEQ @RED_EQUAL
	LDA @LOCAL04
	OPTIMIZED_MULT @VIRTUAL04, 6
	STA @LOCAL02
	LDA @LOCAL05
	STA @VIRTUAL04
	SEC
	SBC @VIRTUAL02
	REP #PROC_FLAGS::INDEX8
	LDY #.LOWORD(BATTLE_SPRITE_PALETTE_EFFECT_STEPS)
	STA (@LOCAL02),Y
	LDA #1
	LDY #.LOWORD(BATTLE_SPRITE_PALETTE_EFFECT_DELTAS)
	STA (@LOCAL02),Y
	BRA @SETUP_GREEN
@RED_EQUAL:
	LDA @VIRTUAL04
	CMP @VIRTUAL02
	BNE @RED_DECREASE
	LDA @LOCAL04
	OPTIMIZED_MULT @VIRTUAL04, 6
	REP #PROC_FLAGS::INDEX8
	TAX
	STZ BATTLE_SPRITE_PALETTE_EFFECT_DELTAS,X
	BRA @SETUP_GREEN
@RED_DECREASE:
	LDA @LOCAL04
	OPTIMIZED_MULT @VIRTUAL04, 6
	STA @LOCAL02
	LDA @LOCAL05
	STA @VIRTUAL04
	LDA @VIRTUAL02
	SEC
	SBC @VIRTUAL04
	REP #PROC_FLAGS::INDEX8
	LDY #.LOWORD(BATTLE_SPRITE_PALETTE_EFFECT_STEPS)
	STA (@LOCAL02),Y
	LDA #$FFFF
	LDY #.LOWORD(BATTLE_SPRITE_PALETTE_EFFECT_DELTAS)
	STA (@LOCAL02),Y
@SETUP_GREEN:
	LDX @LOCAL01
	STX @VIRTUAL02
	LDY @LOCAL06
	TYA
	CMP @VIRTUAL02
	BLTEQ @GREEN_EQUAL
	LDA @LOCAL04
	OPTIMIZED_MULT @VIRTUAL04, 6
	STA @VIRTUAL02
	STX @VIRTUAL04
	TYA
	SEC
	SBC @VIRTUAL04
	LDX @VIRTUAL02
	STA BATTLE_SPRITE_PALETTE_EFFECT_STEPS + 2,X
	LDA #32
	LDX @VIRTUAL02
	STA BATTLE_SPRITE_PALETTE_EFFECT_DELTAS + 2,X
	BRA @SETUP_BLUE
@GREEN_EQUAL:
	STX @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BNE @GREEN_DECREASE
	LDA @LOCAL04
	OPTIMIZED_MULT @VIRTUAL04, 6
	TAX
	STZ BATTLE_SPRITE_PALETTE_EFFECT_DELTAS + 2,X
	BRA @SETUP_BLUE
@GREEN_DECREASE:
	LDA @LOCAL04
	OPTIMIZED_MULT @VIRTUAL04, 6
	STA @VIRTUAL02
	STY @VIRTUAL04
	TXA
	SEC
	SBC @VIRTUAL04
	LDX @VIRTUAL02
	STA BATTLE_SPRITE_PALETTE_EFFECT_STEPS + 2,X
	LDA #$FFE0
	LDX @VIRTUAL02
	STA BATTLE_SPRITE_PALETTE_EFFECT_DELTAS + 2,X
@SETUP_BLUE:
	LDA @LOCAL03
	CMP @LOCAL00
	BLTEQ @BLUE_EQUAL
	LDA @LOCAL04
	OPTIMIZED_MULT @VIRTUAL04, 6
	TAX
	LDA @LOCAL03
	SEC
	SBC @LOCAL00
	STA BATTLE_SPRITE_PALETTE_EFFECT_STEPS + 4,X
	LDA #$0400
	STA BATTLE_SPRITE_PALETTE_EFFECT_DELTAS + 4,X
	BRA @CLEAR_COUNTERS
@BLUE_EQUAL:
	LDA @LOCAL03
	CMP @LOCAL00
	BNE @BLUE_DECREASE
	LDA @LOCAL04
	OPTIMIZED_MULT @VIRTUAL04, 6
	TAX
	STZ BATTLE_SPRITE_PALETTE_EFFECT_DELTAS + 4,X
	BRA @CLEAR_COUNTERS
@BLUE_DECREASE:
	LDA @LOCAL04
	OPTIMIZED_MULT @VIRTUAL04, 6
	TAX
	LDA @LOCAL00
	SEC
	SBC @LOCAL03
	STA BATTLE_SPRITE_PALETTE_EFFECT_STEPS + 4,X
	LDA #$FC00
	STA BATTLE_SPRITE_PALETTE_EFFECT_DELTAS + 4,X
@CLEAR_COUNTERS:
	LDA @LOCAL04
	OPTIMIZED_MULT @VIRTUAL04, 6
	TAX
	STZ BATTLE_SPRITE_PALETTE_EFFECT_COUNTERS + 4,X
	STZ BATTLE_SPRITE_PALETTE_EFFECT_COUNTERS + 2,X
	STZ BATTLE_SPRITE_PALETTE_EFFECT_COUNTERS,X
	END_C_FUNCTION
