
UPDATE_BATTLE_SCREEN_EFFECTS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	END_STACK_VARS
	LDA ENABLE_BACKGROUND_DARKENING
	BEQ @AFTER_DARKEN
	LDA BACKGROUND_BRIGHTNESS
	SEC
	SBC #$0555
	STA BACKGROUND_BRIGHTNESS
	STORE_INT1632 @VIRTUAL0A
	MOVE_INT_CONSTANT $00006000, @VIRTUAL06
	CLC
	CMP32ALT @VIRTUAL06, @VIRTUAL0A
	BRANCHLTEQS @APPLY_DARKEN
	LDA #$6000
	STA BACKGROUND_BRIGHTNESS
	STZ ENABLE_BACKGROUND_DARKENING
@APPLY_DARKEN:
	SEP #PROC_FLAGS::INDEX8
	LDY #$0008
	LDA BACKGROUND_BRIGHTNESS
	JSL ASR8_POSITIVE
	JSR INTERPOLATE_BG_PALETTE_COLORS
@AFTER_DARKEN:
	LDA REFLECT_FLASH_DURATION
	BEQ @AFTER_REFLECT_FLASH
	LDA REFLECT_FLASH_DURATION
	DEC
	STA REFLECT_FLASH_DURATION
	AND #$0002
	BEQ @REFLECT_FLASH_DIM
	LDA #$FFFF
	JSR INTERPOLATE_BG_PALETTE_COLORS
	BRA @AFTER_REFLECT_FLASH
@REFLECT_FLASH_DIM:
	LDA #$0100
	JSR INTERPOLATE_BG_PALETTE_COLORS
@AFTER_REFLECT_FLASH:
	LDA GREEN_BACKGROUND_FLASH_DURATION
	BEQ @AFTER_GREEN_BG_FLASH
	STZ PALETTES
	LDA GREEN_BACKGROUND_FLASH_DURATION
	CMP #3
	BEQ @GREEN_BG_FLASH_PHASE3
	CMP #2
	BEQ @GREEN_BG_FLASH_PHASE2
	BRA @GREEN_BG_FLASH_TICK
@GREEN_BG_FLASH_PHASE3:
	LDA #$03E0
	STA PALETTES
@GREEN_BG_FLASH_PHASE2:
	LDA #$0018
	JSL SET_PALETTE_UPLOAD_MODE
@GREEN_BG_FLASH_TICK:
	LDA GREEN_BACKGROUND_FLASH_DURATION
	DEC
	STA GREEN_BACKGROUND_FLASH_DURATION
	AND #$0002
	BEQ @GREEN_BG_FLASH_DIM
	LDA #0
	JSR INTERPOLATE_BG_PALETTE_COLORS
	BRA @AFTER_GREEN_BG_FLASH
@GREEN_BG_FLASH_DIM:
	LDA #$0100
	JSR INTERPOLATE_BG_PALETTE_COLORS
@AFTER_GREEN_BG_FLASH:
	LDA VERTICAL_SHAKE_DURATION
	BNE @APPLY_VERTICAL_SHAKE
	STZ SCREEN_EFFECT_VERTICAL_OFFSET
	BRA @AFTER_VERTICAL_SHAKE
@APPLY_VERTICAL_SHAKE:
	LDA #1*SECOND
	SEC
	SBC VERTICAL_SHAKE_DURATION
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:VERTICAL_SHAKE_AMPLITUDE_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA SCREEN_EFFECT_VERTICAL_OFFSET
	LDX VERTICAL_SHAKE_DURATION
	DEX
	STX VERTICAL_SHAKE_DURATION
	BNE @AFTER_VERTICAL_SHAKE
	LDA VERTICAL_SHAKE_HOLD_DURATION
	BEQ @AFTER_VERTICAL_SHAKE
	DEC VERTICAL_SHAKE_HOLD_DURATION
	LDA #1*SIXTH_OF_A_SECOND
	STA VERTICAL_SHAKE_DURATION
@AFTER_VERTICAL_SHAKE:
	.I16
	STZ SCREEN_EFFECT_HORIZONTAL_OFFSET
	LDA WOBBLE_DURATION
	BEQ @AFTER_WOBBLE
	LDY #6*FIFTHS_OF_A_SECOND
	LDA WOBBLE_DURATION
	JSL MODULUS16
	DEC WOBBLE_DURATION
	LDY #72
	XBA
	AND #$FF00
	JSL DIVISION16S_DIVISOR_POSITIVE
	.I16
	TAX
	LDY #$0100
	SEP #PROC_FLAGS::ACCUM8
	LDA f:SINE_LOOKUP_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	JSL DIVISION16
	STA SCREEN_EFFECT_HORIZONTAL_OFFSET
@AFTER_WOBBLE:
	LDA SHAKE_DURATION
	BEQ @AFTER_SHAKE
	LDA SHAKE_DURATION
	AND #$0003
	DEC SHAKE_DURATION
	CMP #0
	BEQ @SHAKE_CENTER
	CMP #2
	BEQ @SHAKE_CENTER
	CMP #1
	BEQ @SHAKE_RIGHT
	CMP #3
	BEQ @SHAKE_LEFT
	BRA @AFTER_SHAKE
@SHAKE_CENTER:
	STZ SCREEN_EFFECT_HORIZONTAL_OFFSET
	BRA @AFTER_SHAKE
@SHAKE_RIGHT:
	LDA #2
	STA SCREEN_EFFECT_HORIZONTAL_OFFSET
	BRA @AFTER_SHAKE
@SHAKE_LEFT:
	LDA #$FFFE
	STA SCREEN_EFFECT_HORIZONTAL_OFFSET
@AFTER_SHAKE:
	LDA LOADED_BG_DATA_LAYER1 + loaded_bg_data::bitdepth
	AND #$00FF
	CMP #2
	BNE @SET_BG3_OFFSET
	LDA SCREEN_EFFECT_HORIZONTAL_OFFSET
	STA BG1_X_POS
	LDA SCREEN_EFFECT_VERTICAL_OFFSET
	STA BG1_Y_POS
	BRA @AFTER_BG_OFFSET
@SET_BG3_OFFSET:
	LDA BATTLE_MODE_FLAG
	BEQ @AFTER_BG_OFFSET
	LDA SCREEN_EFFECT_HORIZONTAL_OFFSET
	STA BG3_X_POS
	LDA SCREEN_EFFECT_VERTICAL_OFFSET
	STA BG3_Y_POS
@AFTER_BG_OFFSET:
	LDA SCREEN_EFFECT_MINIMUM_WAIT_FRAMES
	BEQ @AFTER_MIN_WAIT
	DEC SCREEN_EFFECT_MINIMUM_WAIT_FRAMES
@AFTER_MIN_WAIT:
	LDA BATTLE_MODE_FLAG
	BEQ @GENERATE_BG_FRAMES
	JSL RENDER_ALL_BATTLE_SPRITES
@GENERATE_BG_FRAMES:
	LDX #0
	LDA #.LOWORD(LOADED_BG_DATA_LAYER1)
	JSL GENERATE_BATTLEBG_FRAME
	LDY #.LOWORD(LOADED_BG_DATA_LAYER2)
	LDA __BSS_START__,Y
	AND #$00FF
	BEQ @AFTER_BG_FRAME
	LDX #1
	TYA
	JSL GENERATE_BATTLEBG_FRAME
@AFTER_BG_FRAME:
	JSL UPDATE_PSI_ANIMATION
	LDA RED_FLASH_DURATION
	BEQ @AFTER_RED_FLASH
	LDA RED_FLASH_DURATION
	DEC
	STA RED_FLASH_DURATION
	LDY #12
	JSL DIVISION16S_DIVISOR_POSITIVE
	AND #$0001
	BEQ @RED_FLASH_RESTORE
	LDY #4
	LDX #0
	LDA #31
	JSL SET_COLDATA
	LDX #$003F
	LDA #0
	JSL SET_COLOUR_ADDSUB_MODE
	BRA @AFTER_RED_FLASH
@RED_FLASH_RESTORE:
	LDY #0
	TYX
	TYA
	JSL SET_COLDATA
	LDA CURRENT_LAYER_CONFIG
	JSL SET_COLOR_MATH_FROM_TABLE
@AFTER_RED_FLASH:
	LDA GREEN_FLASH_DURATION
	BEQ @AFTER_GREEN_FLASH
	LDA GREEN_FLASH_DURATION
	DEC
	STA GREEN_FLASH_DURATION
	LDY #12
	JSL DIVISION16S_DIVISOR_POSITIVE
	AND #$0001
	BEQ @GREEN_FLASH_RESTORE
	LDY #4
	LDX #31
	LDA #0
	JSL SET_COLDATA
	LDX #$003F
	LDA #0
	JSL SET_COLOUR_ADDSUB_MODE
	BRA @AFTER_GREEN_FLASH
@GREEN_FLASH_RESTORE:
	LDY #0
	TYX
	TYA
	JSL SET_COLDATA
	LDA CURRENT_LAYER_CONFIG
	JSL SET_COLOR_MATH_FROM_TABLE
@AFTER_GREEN_FLASH:
	LDA HP_PP_BOX_BLINK_DURATION
	BEQ @AFTER_HPPP_BLINK
	LDA HP_PP_BOX_BLINK_DURATION
	DEC
	STA HP_PP_BOX_BLINK_DURATION
	LDY #3
	JSL DIVISION16S_DIVISOR_POSITIVE
	AND #$0001
	BEQ @HPPP_BLINK_SHOW
	LDA HP_PP_BOX_BLINK_TARGET
	JSL UNDRAW_HP_PP_WINDOW
	BRA @AFTER_HPPP_BLINK
@HPPP_BLINK_SHOW:
	LDA HP_PP_BOX_BLINK_TARGET
	JSL DRAW_AND_MARK_HPPP_WINDOW
@AFTER_HPPP_BLINK:
	JSL UPDATE_SWIRL_EFFECT
	JSL UPDATE_BATTLE_SPRITE_PALETTE_ANIM
	LDA LETTERBOX_EFFECT_ENDING
	BEQ @RETURN
	LDA LETTERBOX_TOP_END
	BEQ @RETURN
	LDA LETTERBOX_EFFECT_ENDING_TOP
	CMP #$03BB
	BCS @SHRINK_LETTERBOX
	STZ LETTERBOX_EFFECT_ENDING_TOP
	LDA #224
	STA LETTERBOX_EFFECT_ENDING_BOTTOM
	STZ LETTERBOX_EFFECT_ENDING
	BRA @UPDATE_LETTERBOX_BOUNDS
@SHRINK_LETTERBOX:
	LDA LETTERBOX_EFFECT_ENDING_TOP
	SEC
	SBC #$03BB
	STA LETTERBOX_EFFECT_ENDING_TOP
	LDA LETTERBOX_EFFECT_ENDING_BOTTOM
	CLC
	ADC #$03BB
	STA LETTERBOX_EFFECT_ENDING_BOTTOM
@UPDATE_LETTERBOX_BOUNDS:
	SEP #PROC_FLAGS::INDEX8
	LDY #8
	LDA LETTERBOX_EFFECT_ENDING_TOP
	JSL ASR8_POSITIVE
	CMP LETTERBOX_TOP_END
	BCS @CHECK_LETTERBOX_BOTTOM
	STA LETTERBOX_TOP_END
@CHECK_LETTERBOX_BOTTOM:
	LDY #8
	LDA LETTERBOX_EFFECT_ENDING_BOTTOM
	JSL ASR8_POSITIVE
	CMP LETTERBOX_BOTTOM_START
	BLTEQ @REBUILD_LETTERBOX_TABLE
	STA LETTERBOX_BOTTOM_START
@REBUILD_LETTERBOX_TABLE:
	JSL BUILD_LETTERBOX_HDMA_TABLE
@RETURN:
	END_C_FUNCTION
