
UPDATE_BATTLE_SPRITE_PALETTE_ANIM:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #0
	STA @VIRTUAL04
	STA @LOCAL05
	JMP @GROUP_CHECK
@GROUP_BODY:
	LDA @VIRTUAL04
	ASL
	CLC
	ADC #.LOWORD(BATTLE_SPRITE_PALETTE_EFFECT_FRAMES_LEFT)
	TAX
	LDA __BSS_START__,X
	BEQL @GROUP_NEXT
	DEC
	STA __BSS_START__,X
	LDA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, 96
	STA @LOCAL04
	CLC
	ADC #.LOWORD(BATTLE_SPRITE_PALETTE_EFFECT_DELTAS) + 6
	TAY
	LDA @LOCAL04
	CLC
	ADC #.LOWORD(BATTLE_SPRITE_PALETTE_EFFECT_COUNTERS) + 6
	TAX
	STX @LOCAL03
	LDA @LOCAL04
	CLC
	ADC #.LOWORD(BATTLE_SPRITE_PALETTE_EFFECT_STEPS) + 6
	STA @LOCAL02
	LDA @LOCAL05
	STA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, BPP4PALETTE_SIZE
	CLC
	ADC #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 12 + 1 * COLOUR_SIZE
	STA @VIRTUAL02
	LDA #1
	STA @LOCAL01
	JMP @COLOR_CHECK
@PROCESS_RED:
	LDA __BSS_START__,Y
	BEQ @PROCESS_GREEN
	STX @LOCAL04
	LDA @LOCAL02
	TAX
	LDA __BSS_START__,X
	CLC
	ADC (@LOCAL04)
	STA (@LOCAL04)
	BRA @RED_THRESHOLD
@RED_APPLY:
	STX @LOCAL04
	LDA @LOCAL00
	SEC
	SBC BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	STA (@LOCAL04)
	LDA @VIRTUAL02
	STA @LOCAL04
	LDA __BSS_START__,Y
	CLC
	ADC (@LOCAL04)
	STA (@LOCAL04)
@RED_THRESHOLD:
	LDX @LOCAL03
	LDA __BSS_START__,X
	STA @LOCAL00
	LDA BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	CMP @LOCAL00
	BLTEQ @RED_APPLY
@PROCESS_GREEN:
	INY
	INY
	INX
	INX
	STX @LOCAL04
	LDA @LOCAL02
	INC
	INC
	STA @LOCAL03
	LDA __BSS_START__,Y
	BEQ @PROCESS_BLUE
	STX @LOCAL02
	LDA @LOCAL03
	TAX
	LDA __BSS_START__,X
	CLC
	ADC (@LOCAL02)
	STA (@LOCAL02)
	BRA @GREEN_THRESHOLD
@GREEN_APPLY:
	STX @LOCAL02
	LDA @LOCAL00
	SEC
	SBC BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	STA (@LOCAL02)
	LDA @VIRTUAL02
	STA @LOCAL02
	LDA __BSS_START__,Y
	CLC
	ADC (@LOCAL02)
	STA (@LOCAL02)
@GREEN_THRESHOLD:
	LDX @LOCAL04
	LDA __BSS_START__,X
	STA @LOCAL00
	LDA BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	CMP @LOCAL00
	BLTEQ @GREEN_APPLY
@PROCESS_BLUE:
	INY
	INY
	INX
	INX
	STX @LOCAL04
	LDA @LOCAL03
	INC
	INC
	STA @LOCAL02
	LDA __BSS_START__,Y
	BEQ @ADVANCE_COLOR
	STX @LOCAL03
	LDA @LOCAL02
	TAX
	LDA __BSS_START__,X
	CLC
	ADC (@LOCAL03)
	STA (@LOCAL03)
	BRA @BLUE_THRESHOLD
@BLUE_APPLY:
	STX @LOCAL03
	LDA @LOCAL00
	SEC
	SBC BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	STA (@LOCAL03)
	LDA @VIRTUAL02
	STA @LOCAL03
	LDA __BSS_START__,Y
	CLC
	ADC (@LOCAL03)
	STA (@LOCAL03)
@BLUE_THRESHOLD:
	LDX @LOCAL04
	LDA __BSS_START__,X
	STA @LOCAL00
	LDA BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	CMP @LOCAL00
	BLTEQ @BLUE_APPLY
@ADVANCE_COLOR:
	INY
	INY
	INX
	INX
	STX @LOCAL03
	LDA @LOCAL02
	INC
	INC
	STA @LOCAL02
	INC @VIRTUAL02
	INC @VIRTUAL02
	INC @LOCAL01
@COLOR_CHECK:
	LDA @LOCAL01
	CMP #16
	BCCL @PROCESS_RED
	LDA #16
	JSL SET_PALETTE_UPLOAD_MODE
@GROUP_NEXT:
	INC @VIRTUAL04
	LDA @VIRTUAL04
	STA @LOCAL05
@GROUP_CHECK:
	LDA @VIRTUAL04
	CMP #4
	BCCL @GROUP_BODY
	END_C_FUNCTION
