
CHECK_BATTLE_ACTION_TARGETABLE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @VIRTUAL02
	TAX
	CPX #1
	BNE @TARGETABLE
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(battle_action)
	TAX
	INX
	INX
	LDA f:BATTLE_ACTION_TABLE + battle_action::direction,X
	AND #$00FF
	CMP #1
	BNE @TARGETABLE
	LDA @VIRTUAL02
	JSL IS_ROW_VALID
	CMP #0
	BNE @TARGETABLE
	LDA #0
	BRA @DONE
@TARGETABLE:
	LDA #1
@DONE:
	END_C_FUNCTION
