
DETERMINE_BATTLE_ITEM_TARGET:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAY
	STY @LOCAL03
	LDA #$00FF
	STA @VIRTUAL02
	LDA __BSS_START__+1,Y
	AND #$00FF
	TAX
	LDA __BSS_START__,Y
	AND #$00FF
	JSL GET_CHARACTER_ITEM
	STA @LOCAL02
	LOADPTR ITEM_CONFIGURATION_TABLE, @VIRTUAL06
	LDA @LOCAL02
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDY @LOCAL03
	STY @VIRTUAL04
	INC @VIRTUAL04
	INC @VIRTUAL04
	LDA #2
	LDX @VIRTUAL04
	STA __BSS_START__,X
	TYA
	INC
	INC
	INC
	INC
	STA @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA (@LOCAL01)
	REP #PROC_FLAGS::ACCUM8
	TYA
	CLC
	ADC #5
	STA @LOCAL00
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,Y
	STA (@LOCAL00)
	LDY #item::type
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @LOCAL02
	AND #$0030
	CMP #1 << 4
	BEQ @OFFENSIVE_OR_SUPPORT
	CMP #2 << 4
	BEQ @OFFENSIVE_OR_SUPPORT
	CMP #3 << 4
	BEQ @TYPE_EQUIPMENT
	JMP @SET_DEFAULT_ACTION
@OFFENSIVE_OR_SUPPORT:
	LDA #item::effect
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDY @LOCAL03
	LDA __BSS_START__,Y
	AND #$00FF
	TAX
	LDA [@VIRTUAL06]
	JSR DETERMINE_TARGETTING
	STA @VIRTUAL02
	AND #$00FF
	BNE @STORE_TARGETING
	LDA #0
	JMP @RETURN
@STORE_TARGETING:
	LDA [@VIRTUAL06]
	LDX @VIRTUAL04
	STA __BSS_START__,X
	SEP #PROC_FLAGS::INDEX8
	LDY #8
	LDA @VIRTUAL02
	JSL ASR8_POSITIVE
	SEP #PROC_FLAGS::ACCUM8
	STA (@LOCAL01)
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STA (@LOCAL00)
	BRA @SET_DEFAULT_ACTION
@TYPE_EQUIPMENT:
	.A16
	.I16
	LDA @LOCAL02
	AND #$000C
	BEQ @CHECK_USABLE
	CMP #4
	BNE @SET_DEFAULT_ACTION
@CHECK_USABLE:
	LDY @LOCAL03
	LDA __BSS_START__,Y
	AND #$00FF
	TAX
	STX @LOCAL02
	DEX
	SEP #PROC_FLAGS::ACCUM8
	LDY #item::flags
	LDA [@VIRTUAL06],Y
	AND f:ITEM_USABLE_FLAGS,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQ @NOT_USABLE
	LDA #item::effect
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDX @LOCAL02
	LDA [@VIRTUAL06]
	JSR DETERMINE_TARGETTING
	STA @VIRTUAL02
	AND #$00FF
	BNE @STORE_EQUIP_TARGETING
	LDA #0
	BRA @RETURN
@STORE_EQUIP_TARGETING:
	LDA [@VIRTUAL06]
	LDX @VIRTUAL04
	STA __BSS_START__,X
	SEP #PROC_FLAGS::INDEX8
	LDY #8
	LDA @VIRTUAL02
	JSL ASR8_POSITIVE
	SEP #PROC_FLAGS::ACCUM8
	STA (@LOCAL01)
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STA (@LOCAL00)
	BRA @SET_DEFAULT_ACTION
@NOT_USABLE:
	.A16
	.I16
	LDA #3
	LDX @VIRTUAL04
	STA __BSS_START__,X
@SET_DEFAULT_ACTION:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
@RETURN:
	REP #PROC_FLAGS::INDEX8
	END_C_FUNCTION
