
FIND_PREV_BATTLER_IN_ROW:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @LOCAL03
	STX @LOCAL02
	STA @LOCAL01
	BNE @BACK_ROW
	LDX NUM_BATTLERS_IN_FRONT_ROW
	TXA
	DEC
	CLC
	ADC #.LOWORD(BATTLER_FRONT_ROW_X_POSITIONS)
	STA @VIRTUAL04
	BRA @SEARCH_LOOP_INIT
@BACK_ROW:
	LDX NUM_BATTLERS_IN_BACK_ROW
	TXA
	DEC
	CLC
	ADC #.LOWORD(BATTLER_BACK_ROW_X_POSITIONS)
	STA @VIRTUAL04
@SEARCH_LOOP_INIT:
	TXA
	DEC
	STA @VIRTUAL02
	BRA @LOOP_CHECK
@CHECK_BATTLER:
	LDX @VIRTUAL04
	LDA __BSS_START__,X
	AND #$00FF
	STA @LOCAL00
	LDA @VIRTUAL04
	DEC
	STA @VIRTUAL04
	LDA @LOCAL00
	CMP @LOCAL02
	BCS @PREV_BATTLER
	LDY @LOCAL03
	LDX @VIRTUAL02
	LDA @LOCAL01
	JSR CHECK_BATTLE_ACTION_TARGETABLE
	CMP #0
	BEQ @PREV_BATTLER
	LDA @VIRTUAL02
	BRA @RETURN
@PREV_BATTLER:
	LDA @VIRTUAL02
	DEC
	STA @VIRTUAL02
@LOOP_CHECK:
	LDA @VIRTUAL02
	INC
	BNE @CHECK_BATTLER
	LDA #.LOWORD(-1)
@RETURN:
	END_C_FUNCTION
