
FIND_NEXT_BATTLER_IN_ROW:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @LOCAL03
	STX @LOCAL02
	STA @LOCAL01
	BNE @BACK_ROW
	LDA NUM_BATTLERS_IN_FRONT_ROW
	STA @LOCAL00
	LDA #.LOWORD(BATTLER_FRONT_ROW_X_POSITIONS)
	STA @VIRTUAL04
	BRA @SEARCH_LOOP_INIT
@BACK_ROW:
	LDA NUM_BATTLERS_IN_BACK_ROW
	STA @LOCAL00
	LDA #.LOWORD(BATTLER_BACK_ROW_X_POSITIONS)
	STA @VIRTUAL04
@SEARCH_LOOP_INIT:
	LDA #0
	STA @VIRTUAL02
	BRA @LOOP_CHECK
@CHECK_BATTLER:
	LDX @VIRTUAL04
	LDA __BSS_START__,X
	AND #$00FF
	INC @VIRTUAL04
	CMP @LOCAL02
	BLTEQ @NEXT_BATTLER
	LDY @LOCAL03
	LDX @VIRTUAL02
	LDA @LOCAL01
	JSR CHECK_BATTLE_ACTION_TARGETABLE
	CMP #0
	BEQ @NEXT_BATTLER
	LDA @VIRTUAL02
	BRA @RETURN
@NEXT_BATTLER:
	INC @VIRTUAL02
@LOOP_CHECK:
	LDA @VIRTUAL02
	CMP @LOCAL00
	BCC @CHECK_BATTLER
	LDA #.LOWORD(-1)
@RETURN:
	END_C_FUNCTION
