
GET_BATTLER_ROW_X_POSITION:
	BEGIN_C_FUNCTION
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXY
	TAX
	BNE @BACK_ROW
	SEP #PROC_FLAGS::ACCUM8
	LDA BATTLER_FRONT_ROW_X_POSITIONS,Y
	BRA @EXTEND_TO_16BIT
@BACK_ROW:
	SEP #PROC_FLAGS::ACCUM8
	LDA BATTLER_BACK_ROW_X_POSITIONS,Y
@EXTEND_TO_16BIT:
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	END_C_FUNCTION
