
SELECT_BATTLE_TARGET:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
.IF .DEFINED(USA)
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
.ENDIF
	STACK_RESERVE_INT16 "LOCAL05"
	STACK_RESERVE_INT16 "LOCAL06"
	STACK_RESERVE_INT16 "LOCAL07"
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @LOCAL07
	STA @LOCAL06
	STZ @LOCAL05
.IF .DEFINED(USA)
	STZ @LOCAL04
.ENDIF
	LDA NUM_BATTLERS_IN_FRONT_ROW
	BEQ @NO_FRONT_ROW
	LDX #0
	BRA @STORE_ROW
@NO_FRONT_ROW:
	LDX #1
@STORE_ROW:
	STX @VIRTUAL04
	LDA GIYGAS_PHASE
	BEQ @UPDATE_TARGET_DISPLAY
	LDA #1
	STA @VIRTUAL04
@UPDATE_TARGET_DISPLAY:
	LDX @LOCAL05
	LDA @VIRTUAL04
	JSR GET_BATTLER_ROW_X_POSITION
	STA @LOCAL02
	LDX @LOCAL05
	LDA @VIRTUAL04
	JSR ENEMY_FLASHING_ON
	LDX @LOCAL05
	LDA @VIRTUAL04
	JSR DISPLAY_BATTLE_TARGET_TEXT
	JSL WINDOW_TICK
@INPUT_LOOP:
	JSL UPDATE_HPPP_METER_AND_RENDER
	LDA PAD_PRESS
	AND #PAD::UP
	BEQ @CHECK_DOWN
	LDA @VIRTUAL04
	BNE @CHECK_DOWN
	LDA NUM_BATTLERS_IN_BACK_ROW
	BNEL @SWITCH_ROW
@CHECK_DOWN:
	LDA PAD_PRESS
	AND #PAD::DOWN
	BEQ @CHECK_LEFT
	LDA @VIRTUAL04
	CMP #1
	BNE @CHECK_LEFT
	LDA NUM_BATTLERS_IN_FRONT_ROW
	BNEL @SWITCH_ROW
@CHECK_LEFT:
	LDA #SFX::CURSOR2
	STA @LOCAL01
	LDA PAD_PRESS
	AND #PAD::LEFT
	BEQ @CHECK_RIGHT
	LDA @VIRTUAL04
	STA @VIRTUAL02
	LDY @LOCAL07
	LDX @LOCAL02
	LDA @VIRTUAL02
	JSR FIND_PREV_BATTLER_IN_ROW
	TAX
	CPX #.LOWORD(-1)
	BNEL @APPLY_SELECTION
	LDA @VIRTUAL04
	EOR #$0001
	STA @VIRTUAL02
	LDY @LOCAL07
	LDX @LOCAL02
	LDA @VIRTUAL02
	JSR FIND_PREV_BATTLER_IN_ROW
	TAX
	CPX #.LOWORD(-1)
	BEQL @UPDATE_TARGET_DISPLAY
	JMP @APPLY_SELECTION
@CHECK_RIGHT:
	LDA PAD_PRESS
	AND #PAD::RIGHT
	BEQ @CHECK_CONFIRM
	LDA @VIRTUAL04
	STA @VIRTUAL02
	LDY @LOCAL07
	LDX @LOCAL02
	LDA @VIRTUAL02
	JSR FIND_NEXT_BATTLER_IN_ROW
	TAX
	CPX #.LOWORD(-1)
	BNEL @APPLY_SELECTION
	LDA @VIRTUAL04
	EOR #$0001
	STA @VIRTUAL02
	LDY @LOCAL07
	LDX @LOCAL02
	LDA @VIRTUAL02
	JSR FIND_NEXT_BATTLER_IN_ROW
	TAX
	CPX #.LOWORD(-1)
	BEQL @UPDATE_TARGET_DISPLAY
	JMP @APPLY_SELECTION
@CHECK_CONFIRM:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON | PAD::L_BUTTON
	BEQ @CHECK_CANCEL
	JSR ENEMY_FLASHING_OFF
	LDY NUM_BATTLERS_IN_FRONT_ROW
	LDA @VIRTUAL04
	JSL MULT16
	CLC
	ADC @LOCAL05
	TAX
	INX
	STX @LOCAL00
	LDA #SFX::CURSOR1
	JSL PLAY_SOUND
	BRA @RETURN
@CHECK_CANCEL:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON
	BEQL @INPUT_LOOP
	LDA @LOCAL06
	CMP #1
	BNEL @INPUT_LOOP
	JSR ENEMY_FLASHING_OFF
	LDX #0
	STX @LOCAL00
	LDA #SFX::CURSOR2
	JSL PLAY_SOUND
	BRA @RETURN
@SWITCH_ROW:
	LDA #SFX::CURSOR3
	STA @LOCAL01
	LDA @VIRTUAL04
	EOR #$0001
	STA @VIRTUAL02
	LDY @LOCAL07
	LDX @LOCAL02
	DEX
	LDA @VIRTUAL02
	JSR FIND_NEXT_BATTLER_IN_ROW
	TAX
	CPX #.LOWORD(-1)
	BNE @APPLY_SELECTION
	LDY @LOCAL07
	LDX @LOCAL02
	INX
	LDA @VIRTUAL02
	JSR FIND_PREV_BATTLER_IN_ROW
	TAX
	CPX #.LOWORD(-1)
	BEQL @UPDATE_TARGET_DISPLAY
@APPLY_SELECTION:
.IF .DEFINED(USA)
	STZ @LOCAL05
	JSL CLEAR_INSTANT_PRINTING
	CREATE_WINDOW_NEAR #WINDOW::BATTLE_TARGET_TEXT
	JSL WINDOW_TICK
	JSL SET_INSTANT_PRINTING
	LDX @LOCAL01
.ENDIF
	STX @LOCAL05
	LDA @VIRTUAL02
	STA @VIRTUAL04
	LDA @LOCAL01
	JSL PLAY_SOUND
	JMP @UPDATE_TARGET_DISPLAY
@RETURN:
	JSR CLOSE_FOCUS_WINDOW
	LDX @LOCAL00
	TXA
	END_C_FUNCTION
