
SELECT_BATTLE_ROW:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STA @VIRTUAL02
	LDA NUM_BATTLERS_IN_FRONT_ROW
	BEQ @START_BACK_ROW
	LDX #0
	BRA @AFTER_INITIAL_ROW
@START_BACK_ROW:
	LDX #1
@AFTER_INITIAL_ROW:
	TXY
	STY @LOCAL02
@DISPLAY_ROW:
	LDY @LOCAL02
	TYA
	JSR SET_BATTLER_FLASHING
	JSR CLEAR_INSTANT_PRINTING
	LDX #.LOWORD(-1)
	LDY @LOCAL02
	TYA
	JSR DISPLAY_BATTLE_TARGET_TEXT
	JSL WINDOW_TICK
@INPUT_LOOP:
	JSL UPDATE_HPPP_METER_AND_RENDER
	LDA PAD_PRESS
	AND #PAD::UP
	BEQ @CHECK_DOWN
	LDX #1
	STX @LOCAL01
	LDA #SFX::CURSOR3
	STA @LOCAL00
	BRA @VALIDATE_ROW_CHANGE
@CHECK_DOWN:
	LDA PAD_PRESS
	AND #PAD::DOWN
	BEQ @CHECK_CONFIRM
	LDX #0
	STX @LOCAL01
	LDA #SFX::CURSOR3
	STA @LOCAL00
	BRA @VALIDATE_ROW_CHANGE
@CHECK_CONFIRM:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON | PAD::L_BUTTON
	BEQ @CHECK_CANCEL
	JSR CLEAR_BATTLER_FLASHING
	LDY @LOCAL02
	TYX
	INX
	STX @LOCAL01
	LDA #SFX::CURSOR1
	JSL PLAY_SOUND
	BRA @RETURN
@CHECK_CANCEL:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON
	BEQ @INPUT_LOOP
	LDA @VIRTUAL02
	CMP #1
	BNE @INPUT_LOOP
	JSR CLEAR_BATTLER_FLASHING
	LDX #0
	STX @LOCAL01
	LDA #SFX::CURSOR2
	JSL PLAY_SOUND
	BRA @RETURN
@VALIDATE_ROW_CHANGE:
	CPX #0
	BNE @CHECK_BACK_ROW
	LDA NUM_BATTLERS_IN_FRONT_ROW
	BNE @APPLY_ROW_CHANGE
@CHECK_BACK_ROW:
	CPX #0
	BEQL @DISPLAY_ROW
	LDA NUM_BATTLERS_IN_BACK_ROW
	BEQL @DISPLAY_ROW
@APPLY_ROW_CHANGE:
	LDA @LOCAL00
	JSL PLAY_SOUND
	LDX @LOCAL01
	TXY
	STY @LOCAL02
	JMP @DISPLAY_ROW
@RETURN:
	JSR CLOSE_FOCUS_WINDOW
	LDX @LOCAL01
	TXA
	END_C_FUNCTION
