
SELECT_BATTLE_TARGET_DISPATCH:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @VIRTUAL02
	TXY
	TAX
	BEQ @SELECT_SINGLE_TARGET
	TYA
	JSR SELECT_BATTLE_ROW
	BRA @RETURN
@SELECT_SINGLE_TARGET:
	LDX @VIRTUAL02
	TYA
	JSR SELECT_BATTLE_TARGET
@RETURN:
	END_C_FUNCTION
