
FIFTY_PERCENT_VARIANCE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int value
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	STA @VIRTUAL04
	JSR RAND_LONG
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
	STX @LOCAL02
	JSR RAND_LONG
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @LOCAL01
	LDX @LOCAL02
	TXA
	SEC
	SBC #$0080
	STA @LOCAL00
	STA @VIRTUAL02
	LDA #$0000
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @ABS_RAND1_NEGATIVE
	LDA @LOCAL00
	EOR #$FFFF
	INC
	BRA @ABS_RAND1_DONE
@ABS_RAND1_NEGATIVE:
	LDA @LOCAL00
@ABS_RAND1_DONE:
	TAY
	LDA @LOCAL01
	SEC
	SBC #$0080
	STA @LOCAL00
	STA @VIRTUAL02
	LDA #$0000
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @ABS_RAND2_NEGATIVE
	LDA @LOCAL00
	EOR #$FFFF
	INC
	BRA @ABS_RAND2_DONE
@ABS_RAND2_NEGATIVE:
	LDA @LOCAL00
@ABS_RAND2_DONE:
	STA @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BLTEQ @USE_SMALLER
	LDX @LOCAL01
	LDY @VIRTUAL02
@USE_SMALLER:
	STX @VIRTUAL02
	LDA #$0080
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @APPLY_POSITIVE
	LDX @VIRTUAL04
	TYA
	SEP #PROC_FLAGS::ACCUM8
	JSR TRUNCATE_16_TO_8
	STA @VIRTUAL02
	LDA @VIRTUAL04
	SEC
	SBC @VIRTUAL02
	STA @VIRTUAL04
	BRA @DONE
@APPLY_POSITIVE:
	.A16
	TXA
	CLC
	SBC #$0080
	BRANCHLTEQS @DONE
	LDX @VIRTUAL04
	TYA
	SEP #PROC_FLAGS::ACCUM8
	JSR TRUNCATE_16_TO_8
	STA @VIRTUAL02
	LDA @VIRTUAL04
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL04
@DONE:
	LDA @VIRTUAL04
	END_C_FUNCTION
