
APPLY_ACTION_TO_TARGETS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	MOVE_INT @PARAM00, @VIRTUAL06
	BRA @WAIT_PSI_CHECK
@WAIT_PSI_TICK:
	JSL WINDOW_TICK
@WAIT_PSI_CHECK:
	JSL IS_PSI_ANIMATION_ACTIVE
	CMP #0
	BNE @WAIT_PSI_TICK
	LDA #.LOWORD(BATTLERS_TABLE) + (.SIZEOF(battler) * 8)
	STA CURRENT_TARGET
	LDX #8
	STX @LOCAL00
	BRA @ENEMY_LOOP_CHECK
@ENEMY_LOOP_BODY:
	TXA
	JSL IS_CHAR_TARGETTED
	CMP #0
	BEQ @ENEMY_NEXT
	JSL FIX_TARGET_NAME
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BEQ @ENEMY_NEXT
	PHA
	MOVE_INT @VIRTUAL06, TEMP_FUNCTION_POINTER
	PLA
	JSL JUMP_TEMP_FUNCTION_POINTER
@ENEMY_NEXT:
	LDA CURRENT_TARGET
	CLC
	ADC #.SIZEOF(battler)
	STA CURRENT_TARGET
	LDX @LOCAL00
	INX
	STX @LOCAL00
@ENEMY_LOOP_CHECK:
	CPX #BATTLER_COUNT
	BCC @ENEMY_LOOP_BODY
	LDA #.LOWORD(BATTLERS_TABLE)
	STA CURRENT_TARGET
	LDX #0
	STX @LOCAL00
	BRA @PARTY_LOOP_CHECK
@PARTY_LOOP_BODY:
	TXA
	JSL IS_CHAR_TARGETTED
	CMP #0
	BEQ @PARTY_NEXT
	JSL FIX_TARGET_NAME
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BEQ @PARTY_NEXT
	PHA
	MOVE_INT @VIRTUAL06, TEMP_FUNCTION_POINTER
	PLA
	JSL JUMP_TEMP_FUNCTION_POINTER
@PARTY_NEXT:
	LDA CURRENT_TARGET
	CLC
	ADC #.SIZEOF(battler)
	STA CURRENT_TARGET
	LDX @LOCAL00
	INX
	STX @LOCAL00
@PARTY_LOOP_CHECK:
	CPX #8
	BCC @PARTY_LOOP_BODY
	END_C_FUNCTION
