
APPLY_CONDIMENT:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT32 ;const ItemParameters*
	END_STACK_VARS
	LDX CURRENT_ATTACKER
	LDA a:battler::current_action_argument,X
	AND #$00FF
	STA @VIRTUAL04
	STA @LOCAL04
	LDA @VIRTUAL04
	SEP #PROC_FLAGS::ACCUM8
	JSL FIND_CONDIMENT
	.A16
	STA @VIRTUAL02
	CMP #$0000
	BEQL @NO_CONDIMENT
	LDX @VIRTUAL02
	STX @LOCAL03
	LDX CURRENT_ATTACKER
	LDA a:battler::id,X
	LDX @LOCAL03
	JSL TAKE_ITEM_FROM_CHARACTER
	LDY #$0000
	STY @LOCAL02
	BRA @SEARCH_CONDIMENT_TABLE
@CHECK_CONDIMENT_MATCH:
	PHA
	LDA @LOCAL04
	STA @VIRTUAL04
	PLA
	AND #$00FF
	CMP @VIRTUAL04
	BNE @NEXT_CONDIMENT_ENTRY
	TXA
	INC
	MOVE_INTY @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	CMP @VIRTUAL02
	BEQ @CONDIMENT_MATCH
	TXA
	INC
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	CMP @VIRTUAL02
	BNE @CONDIMENT_NO_MATCH
@CONDIMENT_MATCH:
	.A16
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_EAT_SPICE_ATARI
	LOADPTR CONDIMENT_TABLE, @VIRTUAL06
	LDY @LOCAL02
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 7
	INC
	INC
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @RETURNVAL
	LDA @VIRTUAL08
	STA @RETURNVAL+2
	BRA @RETURN
@NEXT_CONDIMENT_ENTRY:
	INY
	STY @LOCAL02
@SEARCH_CONDIMENT_TABLE:
	LOADPTR CONDIMENT_TABLE, @VIRTUAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 7
	TAX
	PHA
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	PLA
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	BNEL @CHECK_CONDIMENT_MATCH
@CONDIMENT_NO_MATCH:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_EAT_SPICE_HAZURE
@NO_CONDIMENT:
	LOADPTR ITEM_CONFIGURATION_TABLE, @VIRTUAL06
	LDA @LOCAL04
	STA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @RETURNVAL
	LDA @VIRTUAL08
	STA @RETURNVAL+2
@RETURN:
	END_C_FUNCTION
