
APPLY_NEUTRALIZE_TO_ALL:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA MIRROR_ENEMY
	BEQ @APPLY_TO_ALL
	LDX #.LOWORD(BATTLERS_TABLE)
	STX @LOCAL02
	LDY #0
	BRA @MIRROR_LOOP_CHECK
@MIRROR_LOOP_BODY:
	LDA a:battler::consciousness,X
	AND #$00FF
	BEQ @MIRROR_NEXT
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @MIRROR_NEXT
	LDA a:battler::id,X
	CMP #4
	BNE @MIRROR_NEXT
	STZ MIRROR_ENEMY
	TXA
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	PROMOTENEARPTR MIRROR_BATTLER_BACKUP, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL COPY_MIRROR_DATA
	LDX @LOCAL02
	STZ a:battler::current_action,X
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_NEUTRALIZE_METAMORPH
	BRA @APPLY_TO_ALL
@MIRROR_NEXT:
	TXA
	CLC
	ADC #.SIZEOF(battler)
	TAX
	STX @LOCAL02
	INY
@MIRROR_LOOP_CHECK:
	CPY #BATTLER_COUNT
	BCC @MIRROR_LOOP_BODY
@APPLY_TO_ALL:
	JSL TARGET_ALL
	JSR REMOVE_DEAD_TARGETTING
	LOADPTR BTLACT_NEUTRALIZE, @LOCAL00
	JSL APPLY_ACTION_TO_TARGETS
	MOVE_INT_CONSTANT 0, BATTLER_TARGET_FLAGS
	END_C_FUNCTION
