
APPLY_PSI_BATTLE_EFFECT:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL02
	CMP #35
	BCS @CHECK_ENEMY_PSI
	LDA @VIRTUAL02
	JSL SHOW_PSI_ANIMATION
	JMP @DONE
@CHECK_ENEMY_PSI:
	LDA @VIRTUAL02
	CMP #46
	BCS @CHECK_SCREEN_EFFECTS
	JSL DARKEN_BG_PALETTES
	LOADPTR ENEMY_PSI_COLOURS, @VIRTUAL06
	LDA @VIRTUAL02
	SEC
	SBC #35
	OPTIMIZED_MULT @VIRTUAL04, 3
	STA @LOCAL01
	INC
	INC
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	TAY
	LDA @LOCAL01
	INC
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	TAX
	LDA @LOCAL01
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	JSL SET_COLDATA
	LDX #$3F
	LDA #$10
	JSL SET_COLOUR_ADDSUB_MODE
	LDX #7
	LDA #5
	JSL INIT_SWIRL_EFFECT
	JMP @DONE
@CHECK_SCREEN_EFFECTS:
	LDA @VIRTUAL02
	CMP #49
	BCS @CHECK_MISC_SWIRL
	LDA @VIRTUAL02
	INC
	CMP #47
	BEQ @SET_WOBBLE
	CMP #48
	BEQ @SET_SHAKE
	CMP #49
	BEQL @DONE
	JMP @DONE
@SET_WOBBLE:
	LDA #144
	STA WOBBLE_DURATION
	JMP @DONE
@SET_SHAKE:
	LDA #300
	STA SHAKE_DURATION
	JMP @DONE
@CHECK_MISC_SWIRL:
	LDA @VIRTUAL02
	CMP #54
	BCC @APPLY_MISC_SWIRL
	JMP @DONE
@APPLY_MISC_SWIRL:
	JSL DARKEN_BG_PALETTES
	LOADPTR MISC_SWIRL_COLOURS, @VIRTUAL06
	LDA @VIRTUAL02
	SEC
	SBC #49
	STA @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	STA @LOCAL00
	INC
	INC
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	TAY
	LDA @LOCAL00
	INC
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	TAX
	LDA @LOCAL00
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	JSL SET_COLDATA
	LDX #$3F
	LDA #$10
	JSL SET_COLOUR_ADDSUB_MODE
	LDA @VIRTUAL02
	CMP #53
	BCS @SLOW_SWIRL
	LDX #5
	LDA #4
	JSL INIT_SWIRL_EFFECT
	BRA @DONE
@SLOW_SWIRL:
	LDX #4
	LDA #2
	JSL INIT_SWIRL_EFFECT
@DONE:
	END_C_FUNCTION
