
AUTOHEALING:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int statusGroup
	STACK_RESERVE_PARAM_INT16 ;int statusID
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	STX @LOCAL04
	STA @LOCAL03
	LDA #9999
	STA @LOCAL02
	LDA #$0000
	STA @VIRTUAL04
	STA @VIRTUAL02
	BRA @LOOP_CHECK
@CHECK_MEMBER:
.IF .DEFINED(JPN)
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
.ELSE
	LDX @VIRTUAL02
	LDA GAME_STATE + game_state::party_members,X
.ENDIF
	AND #$00FF
	TAY
	STY @LOCAL01
	CPY #PARTY_MEMBER::NESS
	BCC @NEXT_MEMBER
	CPY #PARTY_MEMBER::POO
	BGT @NEXT_MEMBER
	TYA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	STX @LOCAL00
	LDA PARTY_CHARACTERS+char_struct::unknown94,X
	AND #$00FF
	BNE @NEXT_MEMBER
	TXA
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::afflictions
	CLC
	ADC @LOCAL03
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	CMP @LOCAL04
	BNE @NEXT_MEMBER
	LDX @LOCAL00
	LDA PARTY_CHARACTERS+char_struct::current_hp_target,X
	CMP @LOCAL02
	BCS @NEXT_MEMBER
	STA @LOCAL02
	LDY @LOCAL01
	STY @VIRTUAL04
@NEXT_MEMBER:
	INC @VIRTUAL02
@LOOP_CHECK:
	LDA @VIRTUAL02
	CMP #TOTAL_PARTY_COUNT
	BCC @CHECK_MEMBER
	LDA @VIRTUAL04
	BEQ @DONE
	LDA @VIRTUAL04
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #$01
	STA PARTY_CHARACTERS+char_struct::unknown94,X
@DONE:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	END_C_FUNCTION
