
; A: battle_menu_selection*
BATTLE_PSI_MENU:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
.IF .DEFINED(USA)
	@LOCAL04_2 := @LOCAL05
	STACK_RESERVE_INT16 "LOCALEB"
.ELSE
	@LOCAL04_2 := @LOCAL04
.ENDIF
	STACK_RESERVE_INT16 "LOCAL06"
	STACK_RESERVE_PARAM_INT16 ;NEAR A97DStruct*
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	STA @VIRTUAL04
	STA @LOCAL06
.IF .DEFINED(USA)
	STZ @LOCALEB
.ENDIF
@OPEN_CATEGORY_WINDOW:
	CREATE_WINDOW_NEAR #WINDOW::BATTLE_PSI_CATEGORY
	LDA #$0000
	STA @LOCAL05
	BRA @CATEGORY_LOOP_CHECK
@ADD_CATEGORY:
	TAX
	INX
	STX @LOCAL04
	LOADPTR PSI_CATEGORIES, @VIRTUAL06
	LDA @LOCAL05
	OPTIMIZED_MULT @VIRTUAL04, PSI_CATEGORY_NAME_SIZE
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	MOVE_INT_CONSTANT NULL, @LOCAL01
	TXA
	JSR ADD_MENU_ITEM_NO_POSITION
	LDX @LOCAL04
	TXA
	STA @LOCAL05
@CATEGORY_LOOP_CHECK:
	CMP #$0003
	BCC @ADD_CATEGORY
	LDY #$0000
	TYX
	LDA #$0001
	JSR OPEN_WINDOW_AND_PRINT_MENU
@CATEGORY_SELECTION:
	LDA #$0010
	JSR SET_WINDOW_FOCUS
.IF .DEFINED(USA)
	LDA @LOCALEB
	BNE @SKIP_PRINT
.ENDIF
	JSR PRINT_MENU_ITEMS
.IF .DEFINED(USA)
@SKIP_PRINT:
	INC @LOCALEB
.ENDIF
	LOADPTR GENERATE_BATTLE_PSI_LIST, @LOCAL00
	JSR SET_CURSOR_MOVE_CALLBACK
	LDA #$0001
	JSR SELECTION_MENU
	STA @VIRTUAL02
	JSR CLEAR_CURSOR_MOVE_CALLBACK
	LDA @VIRTUAL02
	BEQL @CLOSE_AND_RETURN
	LDA @LOCAL06
	STA @VIRTUAL04
	LDX @VIRTUAL04
	LDA a:battle_menu_selection::user,X
	AND #$00FF
	TAX
	LDA @VIRTUAL02
	JSR CHECK_PSI_CATEGORY_AVAILABLE
	CMP #$0000
	BEQ @CATEGORY_SELECTION
@OPEN_PSI_LIST:
	CREATE_WINDOW_NEAR #WINDOW::TEXT_STANDARD
	LDA @VIRTUAL02
	JSL GENERATE_BATTLE_PSI_LIST
	LOADPTR DISPLAY_PSI_TARGET_AND_COST, @LOCAL00
	JSR SET_CURSOR_MOVE_CALLBACK
	LDA #$0001
	JSR SELECTION_MENU
	TAY
	STY @LOCAL04_2
	JSR CLEAR_CURSOR_MOVE_CALLBACK
	LDY @LOCAL04_2
	BEQL @PSI_CANCELLED
.IF .DEFINED(PROTOTYPE19950327) || .DEFINED(JPN)
	LDX #$0006
	TYA
	JSR DISPLAY_PSI_ABILITY_DETAILS
.ENDIF
	LOADPTR BATTLE_ACTION_TABLE, @VIRTUAL06
.IF .DEFINED(PROTOTYPE19950327) || .DEFINED(JPN)
	LDY @LOCAL04_2
.ENDIF
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 15
	TAX
	INX
	INX
	INX
	INX
	LDA f:PSI_ABILITY_TABLE,X
	OPTIMIZED_MULT @VIRTUAL04, 12
	STA @LOCAL03
	LDA @LOCAL06
	STA @VIRTUAL04
	LDX @VIRTUAL04
	LDA a:battle_menu_selection::user,X
	AND #$00FF
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA @LOCAL03
	INC
	INC
	INC
	MOVE_INTY @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	CMP PARTY_CHARACTERS+char_struct::current_pp_target,X
	BLTEQ @CHECK_PP_COST
	CREATE_WINDOW_NEAR #WINDOW::TEXT_BATTLE
	LDA #$0002
	JSR ENABLE_BLINKING_TRIANGLE
	DISPLAY_TEXT_PTR MSG_BTL_PSI_CANNOT_MENU
	JSR CLEAR_BLINKING_PROMPT
	JSR CLOSE_FOCUS_WINDOW
	LDX #$0000
	STX @LOCAL02
	JMP @CHECK_RESULT
@CHECK_PP_COST:
	LDA @LOCAL03
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	TAX
	CPX #$0001
	BEQ @CHECK_SINGLE_TARGET
	CPX #$0003
	BNE @DETERMINE_TARGET
@CHECK_SINGLE_TARGET:
	LDY @LOCAL04_2
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 15
	TAX
	INX
	INX
	INX
	INX
	LDA f:PSI_ABILITY_TABLE,X
	OPTIMIZED_MULT @VIRTUAL04, 12
	TAX
	LDA f:BATTLE_ACTION_TABLE,X
	AND #$00FF
	BNE @DETERMINE_TARGET
	LDA #$0010
	JSR CLOSE_WINDOW
	LDA #$0004
	JSR CLOSE_WINDOW
	LDA #$0001
	JSR CLOSE_WINDOW
	CREATE_WINDOW_NEAR #WINDOW::BATTLE_ACTION_NAME
	JSR SET_INSTANT_PRINTING
	LDA #$0006
	JSR SET_WINDOW_PALETTE_INDEX
	LDY @LOCAL04_2
	TYA
	JSR PRINT_PSI_ABILITY_NAME
	LDA #$0000
	JSR SET_WINDOW_PALETTE_INDEX
@DETERMINE_TARGET:
	LOADPTR PSI_ABILITY_TABLE, @VIRTUAL06
	LDY @LOCAL04_2
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 15
	INC
	INC
	INC
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA @LOCAL06
	STA @VIRTUAL04
	LDX @VIRTUAL04
	LDA a:battle_menu_selection::user,X
	AND #$00FF
	TAX
	LDA [@VIRTUAL06]
	JSR DETERMINE_TARGETTING
	TAX
	STX @LOCAL02
	LDA [@VIRTUAL06]
	OPTIMIZED_MULT @VIRTUAL04, 12
	TAX
	LDA f:BATTLE_ACTION_TABLE,X
	AND #$00FF
	BNE @CLOSE_STANDARD_WINDOWS
	LDA #$0026
	JSR CLOSE_WINDOW
	BRA @AFTER_CLOSE
@CLOSE_STANDARD_WINDOWS:
	LDA #$0010
	JSR CLOSE_WINDOW
	LDA #$0004
	JSR CLOSE_WINDOW
	LDA #$0001
	JSR CLOSE_WINDOW
@AFTER_CLOSE:
	LDX @LOCAL02
	TXA
	AND #$00FF
	BEQL @OPEN_CATEGORY_WINDOW
	BRA @CHECK_RESULT
@PSI_CANCELLED:
	LDX #$0001
	STX @LOCAL02
@CHECK_RESULT:
	CPX #$0000
	BEQL @OPEN_PSI_LIST
	LDA #$0004
	JSR CLOSE_WINDOW
	LDY @LOCAL04_2
	BEQL @CATEGORY_SELECTION
	TYA
	SEP #PROC_FLAGS::ACCUM8
	LDX @LOCAL06
	STX @VIRTUAL04
	STA a:battle_menu_selection::param1,X
	REP #PROC_FLAGS::ACCUM8
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 15
	TAX
	INX
	INX
	INX
	INX
	LDA f:PSI_ABILITY_TABLE,X
	LDX @LOCAL06
	STX @VIRTUAL04
	STA a:battle_menu_selection::selected_action,X
	SEP #PROC_FLAGS::ACCUM8
	LDA #$08
	PHA
	LDX @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	TXA
	SEP #PROC_FLAGS::INDEX8
	PLY
	JSL ASR8_POSITIVE
	SEP #PROC_FLAGS::ACCUM8
	REP #PROC_FLAGS::INDEX8
	LDX @VIRTUAL04
	STA a:battle_menu_selection::targetting,X
	LDX @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	TXA
	SEP #PROC_FLAGS::ACCUM8
	LDX @VIRTUAL04
	STA a:battle_menu_selection::selected_target,X
	REP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA @VIRTUAL02
@CLOSE_AND_RETURN:
	LDA #$0001
	JSR CLOSE_WINDOW
	LDA #$0010
	JSR CLOSE_WINDOW
	LDA @VIRTUAL02
	END_C_FUNCTION
