
;A: current target
CALC_DAMAGE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_PARAM_INT16 ;NEAR battler*
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
.IF .DEFINED(JPN)
	STACK_RESERVE_INT16
.ENDIF
	STACK_RESERVE_INT16 "LOCAL03"
	STACK_RESERVE_INT16 "LOCAL04"
	STACK_RESERVE_INT16 "LOCAL05"
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	STX @VIRTUAL04
	TAY
	STY @LOCAL05
	STZ @LOCAL04
	LDA @VIRTUAL04
	BNE @CHECK_GIYGAS_REDIRECT
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
	LDA #0
	JMP @RETURN
@CHECK_GIYGAS_REDIRECT:
	LDA __BSS_START__ + battler::ally_or_enemy,Y
	AND #$00FF
	CMP #1
	BNE @STORE_PRE_DAMAGE_HP
	LDA __BSS_START__ + battler::id,Y
	CMP #ENEMY::GIYGAS_2
	BNE @STORE_PRE_DAMAGE_HP
	LDA #$0001
	STA @LOCAL04
	LDA CURRENT_TARGET
	STA @LOCAL03
@GIYGAS_FIND_RANDOM_TARGET:
	JSL RAND
	AND #$0003
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	TAX
	STX CURRENT_TARGET
	LDA __BSS_START__ + battler::consciousness,X
	AND #$00FF
	BEQ @GIYGAS_FIND_RANDOM_TARGET
	LDA __BSS_START__ + battler::npc_id,X
	AND #$00FF
	BNE @GIYGAS_FIND_RANDOM_TARGET
	LDA __BSS_START__ + battler::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	TAX
	CPX #STATUS_0::UNCONSCIOUS
	BEQ @GIYGAS_FIND_RANDOM_TARGET
	CPX #STATUS_0::DIAMONDIZED
	BEQ @GIYGAS_FIND_RANDOM_TARGET
	JSL FIX_TARGET_NAME
	LDY CURRENT_TARGET
	STY @LOCAL05
	LDA #$0010
	STA REFLECT_FLASH_DURATION
	LDA #SFX::REFLECT_DAMAGE
	JSL PLAY_SOUND
	LDA #1*HALF_OF_A_SECOND
	JSR WAIT
@STORE_PRE_DAMAGE_HP:
	LDY @LOCAL05
	LDA __BSS_START__ + battler::hp_target,Y
	STA @VIRTUAL02
	LDA __BSS_START__ + battler::ally_or_enemy,Y
	AND #$00FF
	BEQ @SKIP_BOSS_HP_REDUCTION
	LDA __BSS_START__ + battler::id,Y
	CMP #ENEMY::MASTER_BELCH_1
	BEQ @CHECK_GUTS_SAVE
	CMP #ENEMY::MASTER_BELCH_3
	BEQ @CHECK_GUTS_SAVE
	CMP #ENEMY::GIYGAS_2
	BEQ @CHECK_GUTS_SAVE
	CMP #ENEMY::GIYGAS_3
	BEQ @CHECK_GUTS_SAVE
	CMP #ENEMY::GIYGAS_5
	BEQ @CHECK_GUTS_SAVE
	CMP #ENEMY::GIYGAS_6
	BEQ @CHECK_GUTS_SAVE
@SKIP_BOSS_HP_REDUCTION:
	LDX @VIRTUAL04
	TYA
	JSR REDUCE_HP
@CHECK_GUTS_SAVE:
	LDY @LOCAL05
	LDA __BSS_START__ + battler::ally_or_enemy,Y
	AND #$00FF
	BNE @DISPLAY_DAMAGE_TEXT
	LDA __BSS_START__ + battler::hp_target,Y
	BNE @CHECK_FINAL_ATTACK_SURVIVAL
	LDA @VIRTUAL02
	CMP #$0001
	BLTEQ @CHECK_FINAL_ATTACK_SURVIVAL
	LDX CURRENT_ATTACKER
	LDA __BSS_START__ + battler::guts,X
	CMP #GUTS_FLOOR_FOR_SMAAAASH_CHANCE
	BCS @USE_RAW_GUTS
	LDX #GUTS_FLOOR_FOR_SMAAAASH_CHANCE
	BRA @DO_GUTS_ROLL
@USE_RAW_GUTS:
	TAX
@DO_GUTS_ROLL:
	TXA
	JSR SUCCESS_500
	CMP #$0000
	BEQ @CHECK_FINAL_ATTACK_SURVIVAL
	LDX #$0001
	LDY @LOCAL05
	TYA
	JSR SET_HP
@CHECK_FINAL_ATTACK_SURVIVAL:
	LDA ENEMY_PERFORMING_FINAL_ATTACK
	BEQ @DISPLAY_DAMAGE_TEXT
	LDA #$0001
	JSL COUNT_CHARS
	CMP #$0001
	BNE @DISPLAY_DAMAGE_TEXT
	LDA #$0000
	JSL COUNT_CHARS
	CMP #$0001
	BNE @DISPLAY_DAMAGE_TEXT
	LDX #$0001
	LDY @LOCAL05
	TYA
	JSR SET_HP
@DISPLAY_DAMAGE_TEXT:
	LDY @LOCAL05
	LDA __BSS_START__ + battler::ally_or_enemy,Y
	AND #$00FF
	CMP #$0001
	BNE @PARTY_TARGET_DAMAGE
	LDA __BSS_START__ + battler::id,Y
	CMP #ENEMY::GIYGAS_3
	BEQ @CHECK_GIYGAS_GREEN_FLASH
	CMP #ENEMY::GIYGAS_4
	BEQ @CHECK_GIYGAS_GREEN_FLASH
	CMP #ENEMY::GIYGAS_5
	BEQ @CHECK_GIYGAS_GREEN_FLASH
	CMP #ENEMY::GIYGAS_6
	BNE @SET_GIYGAS_FLASH
@CHECK_GIYGAS_GREEN_FLASH:
	LDA #$0010
	STA GREEN_BACKGROUND_FLASH_DURATION
@SET_GIYGAS_FLASH:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0015
	STA __BSS_START__ + 72,Y
	REP #PROC_FLAGS::ACCUM8
	LDA IS_SMAAAAASH_ATTACK
	BEQ @ENEMY_SMASH_TEXT
	LOADPTR MSG_BTL_DAMAGE_SMASH_M, @LOCAL00
	MOVE_INT1632 @VIRTUAL04, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	STZ IS_SMAAAAASH_ATTACK
	JMP @SET_SCREEN_EFFECT_WAIT
@ENEMY_SMASH_TEXT:
	LOADPTR MSG_BTL_DAMAGE_M, @LOCAL00
	MOVE_INT1632 @VIRTUAL04, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	JMP @SET_SCREEN_EFFECT_WAIT
@PARTY_TARGET_DAMAGE:
	LDA __BSS_START__ + battler::npc_id,Y
	AND #$00FF
	BNE @DISPLAY_PARTY_DAMAGE_TEXT
	LDA HP_PP_BOX_BLINK_DURATION
	BNE @DISPLAY_PARTY_DAMAGE_TEXT
	LDA #$0015
	STA HP_PP_BOX_BLINK_DURATION
.IF .DEFINED(JPN)
	LDA #$0000
	STA @LOCAL02
.ELSE
	LDX #$0000
.ENDIF
	BRA @NEXT_PARTY_SLOT
@FIND_PARTY_SLOT:
	LDA __BSS_START__ + battler::id,Y
	STA @VIRTUAL02
.IF .DEFINED(JPN)
	LDA @LOCAL02
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @PARTY_SLOT_MISMATCH
	LDA @LOCAL02
	STA HP_PP_BOX_BLINK_TARGET
.ELSE
	LDA GAME_STATE + game_state::party_members,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @PARTY_SLOT_MISMATCH
	STX HP_PP_BOX_BLINK_TARGET
.ENDIF
	BRA @DISPLAY_PARTY_DAMAGE_TEXT
@PARTY_SLOT_MISMATCH:
.IF .DEFINED(JPN)
	LDA @LOCAL02
	INC
	STA @LOCAL02
.ELSE
	INX
.ENDIF
@NEXT_PARTY_SLOT:
.IF .DEFINED(JPN)
	CMP #TOTAL_PARTY_COUNT
.ELSE
	CPX #TOTAL_PARTY_COUNT
.ENDIF
	BCC @FIND_PARTY_SLOT
@DISPLAY_PARTY_DAMAGE_TEXT:
	LDA __BSS_START__ + battler::hp_target,Y
	BNE @TARGET_SURVIVED
	LDA #DAMAGE_TAKEN_SCREEN_SHAKE_DURATION_MORTAL
	STA VERTICAL_SHAKE_DURATION
	LDA #DAMAGE_TAKEN_SCREEN_SHAKE_DURATION_MORTAL_HOLD
	STA VERTICAL_SHAKE_HOLD_DURATION
	LOADPTR MSG_BTL_DAMAGE_TO_DEATH, @LOCAL00
	MOVE_INT1632 @VIRTUAL04, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	BRA @NORMAL_DAMAGE_TEXT
@TARGET_SURVIVED:
	LDA IS_SMAAAAASH_ATTACK
	BEQ @SMASH_SURVIVED_TEXT
	LDA #DAMAGE_TAKEN_SCREEN_SHAKE_DURATION_REGULAR
	STA VERTICAL_SHAKE_DURATION
	LOADPTR MSG_BTL_DAMAGE_SMASH, @LOCAL00
	MOVE_INT1632 @VIRTUAL04, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	STZ VERTICAL_SHAKE_HOLD_DURATION
	STZ IS_SMAAAAASH_ATTACK
	BRA @NORMAL_DAMAGE_TEXT
@SMASH_SURVIVED_TEXT:
	LDA #DAMAGE_TAKEN_SCREEN_SHAKE_DURATION_NORMAL
	STA VERTICAL_SHAKE_DURATION
	LOADPTR MSG_BTL_DAMAGE, @LOCAL00
	MOVE_INT1632 @VIRTUAL04, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	STZ VERTICAL_SHAKE_HOLD_DURATION
@NORMAL_DAMAGE_TEXT:
	LDA #$0028
	STA SCREEN_EFFECT_MINIMUM_WAIT_FRAMES
@SET_SCREEN_EFFECT_WAIT:
	LDA @LOCAL04
	BEQ @RESTORE_GIYGAS_TARGET
	LDA @LOCAL03
	STA CURRENT_TARGET
	JSL FIX_TARGET_NAME
@RESTORE_GIYGAS_TARGET:
	LDA #$0001
@RETURN:
	END_C_FUNCTION
