
CALC_RESIST_DAMAGE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXY
	STA @VIRTUAL02
	LDA #$0000
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @APPLY_RESIST
	LDA #0
	STA @VIRTUAL02
@APPLY_RESIST:
	CPY #$00FF
	BCS @CHECK_CONSCIOUSNESS
	LDX @VIRTUAL02
	TYA
	SEP #PROC_FLAGS::ACCUM8
	JSR TRUNCATE_16_TO_8
	STA @VIRTUAL02
@CHECK_CONSCIOUSNESS:
	.A16
	LDX CURRENT_TARGET
	LDA a:battler::consciousness,X
	AND #$00FF
	CMP #1
	BNEL @DONE
	LDX CURRENT_TARGET
	LDA a:battler::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BEQL @DONE
	LDX CURRENT_TARGET
	LDA a:battler::guarding,X
	AND #$00FF
	CMP #1
	BNE @CHECK_GUARD_HALVE
	LDX CURRENT_ATTACKER
	LDA a:battler::current_action,X
	JSR GET_BATTLE_ACTION_TYPE
	CMP #ACTION_TYPE::PHYSICAL
	BNE @CHECK_GUARD_HALVE
	SEP #PROC_FLAGS::INDEX8
	LDY #1
	LDA @VIRTUAL02
	JSL ASR16
	STA @VIRTUAL02
@CHECK_GUARD_HALVE:
	REP #PROC_FLAGS::INDEX8
	LDX CURRENT_ATTACKER
	LDA a:battler::current_action,X
	JSR GET_BATTLE_ACTION_TYPE
	CMP #ACTION_TYPE::PHYSICAL
	BNE @FLOOR_DAMAGE
	LDX CURRENT_TARGET
	LDA a:battler::afflictions + STATUS_GROUP::SHIELD,X
	AND #$00FF
	CMP #STATUS_6::SHIELD_POWER
	BEQ @SHIELD_HALVE_DAMAGE
	CMP #STATUS_6::SHIELD
	BNE @FLOOR_DAMAGE
@SHIELD_HALVE_DAMAGE:
	SEP #PROC_FLAGS::INDEX8
	LDY #1
	LDA @VIRTUAL02
	JSL ASR16
	STA @VIRTUAL02
@FLOOR_DAMAGE:
	LDA @VIRTUAL02
	BNE @APPLY_DAMAGE
	LDA #1
	STA @VIRTUAL02
@APPLY_DAMAGE:
	REP #PROC_FLAGS::INDEX8
	LDX @VIRTUAL02
	LDA CURRENT_TARGET
	JSR CALC_DAMAGE
	CMP #0
	BEQ @POST_DAMAGE_FLOOR
	LDX CURRENT_TARGET
	LDA a:battler::hp,X
	BNE @POST_DAMAGE_FLOOR
	LDA CURRENT_TARGET
	JSL KO_TARGET
@POST_DAMAGE_FLOOR:
	LDA @VIRTUAL02
	BNE @CHECK_SHIELD_NULLIFIED
	LDA #1
	STA @VIRTUAL02
@CHECK_SHIELD_NULLIFIED:
	LDA SHIELD_HAS_NULLIFIED_DAMAGE
	BNEL @SHIELDS_DONE
	LDX CURRENT_TARGET
	LDA a:battler::afflictions + STATUS_GROUP::SHIELD,X
	AND #$00FF
	CMP #STATUS_6::SHIELD_POWER
	BEQ @SHIELD_POWER_REFLECT
	CMP #STATUS_6::SHIELD
	BEQ @WEAKEN_SHIELD
	BRA @SHIELDS_DONE
@SHIELD_POWER_REFLECT:
	LDA ENEMY_PERFORMING_FINAL_ATTACK
	BNE @WEAKEN_SHIELD
	SEP #PROC_FLAGS::INDEX8
	LDY #1
	LDA @VIRTUAL02
	JSL ASR16
	STA @VIRTUAL02
	CMP #0
	BNE @DAMAGE_ABOVE_ZERO_AFTER_SHIELD
	LDA #1
	STA @VIRTUAL02
@DAMAGE_ABOVE_ZERO_AFTER_SHIELD:
	.A16
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_POWER_TURN
	JSR SWAP_ATTACKER_WITH_TARGET
	LDX @VIRTUAL02
	LDA CURRENT_TARGET
	JSR CALC_DAMAGE
	LDX CURRENT_TARGET
	LDA a:battler::hp,X
	BNE @STILL_HAS_HP_AFTER_REFLECT
	LDA CURRENT_TARGET
	JSL KO_TARGET
@STILL_HAS_HP_AFTER_REFLECT:
	JSR SWAP_ATTACKER_WITH_TARGET
@WEAKEN_SHIELD:
	LDA CURRENT_TARGET
	CLC
	ADC #battler::shield_hp
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNE @SHIELDS_DONE
	LDX CURRENT_TARGET
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::afflictions + STATUS_GROUP::SHIELD,X
	REP #PROC_FLAGS::ACCUM8
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_SHIELD_OFF
@SHIELDS_DONE:
	.I16
	LDX CURRENT_TARGET
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @CHECK_SLEEP_WAKE
	LDX CURRENT_TARGET
	LDA a:battler::npc_id,X
	AND #$00FF
	BNE @CHECK_SLEEP_WAKE
	LDX CURRENT_TARGET
	LDA a:battler::row,X
	AND #$00FF
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::current_hp,X
	BEQ @DONE
@CHECK_SLEEP_WAKE:
	LDX CURRENT_TARGET
	LDA a:battler::afflictions + STATUS_GROUP::TEMPORARY,X
	AND #$00FF
	CMP #STATUS_2::ASLEEP
	BNE @DONE
	SEP #PROC_FLAGS::ACCUM8
	LDA #CHANCE_OF_WAKING_UP_WHEN_ATTACKED
	JSR SUCCESS_255
	.A16
	CMP #$0000
	BEQ @DONE
	LDX CURRENT_TARGET
	STZ a:battler::current_action,X
	LDX CURRENT_TARGET
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::afflictions + STATUS_GROUP::TEMPORARY,X
	REP #PROC_FLAGS::ACCUM8
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_NEMURI_OFF
@DONE:
	LDA @VIRTUAL02
	END_C_FUNCTION
