
CALC_RESISTANCES:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16 ;int characterID
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	TAX
	DEX
	STX @LOCAL02
	TXA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL01
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	TAY
	BEQ @NO_BODY_FIRE
	TYA
	DEC
	STA @VIRTUAL02
	LDA @LOCAL01
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::special
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	AND #$0003
	BRA @CHECK_OTHER_FIRE
@NO_BODY_FIRE:
	LDA #$0000
@CHECK_OTHER_FIRE:
	STA @LOCAL00
	LDX @LOCAL02
	TXA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	TAY
	BEQ @CLAMP_FIRE
	TYA
	DEC
	STA @VIRTUAL04
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::special
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	AND #$0003
	STA @VIRTUAL02
	LDA @LOCAL00
	CLC
	ADC @VIRTUAL02
	STA @LOCAL00
@CLAMP_FIRE:
	LDA @LOCAL00
	CLC
	SBC #$0003
	BRANCHLTEQS @FIRE_IN_RANGE
	LDY #$0003
	STY @LOCAL01
	BRA @STORE_FIRE
@FIRE_IN_RANGE:
	LDA @LOCAL00
	TAY
	STY @LOCAL01
@STORE_FIRE:
	LDX @LOCAL02
	TXA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL00
	TAX
	LDY @LOCAL01
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA PARTY_CHARACTERS+char_struct::fire_resist,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	TAY
	BEQ @NO_BODY_FREEZE
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0002
	PHA
	REP #PROC_FLAGS::ACCUM8
	TYA
	DEC
	STA @VIRTUAL02
	LDA @LOCAL00
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::special
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	AND #$000C
	SEP #PROC_FLAGS::INDEX8
	PLY
	JSL ASR16
	BRA @NO_OTHER_FREEZE
@NO_BODY_FREEZE:
	LDA #$0000
@NO_OTHER_FREEZE:
	STA @LOCAL00
	REP #PROC_FLAGS::INDEX8
	LDX @LOCAL02
	TXA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	TAY
	BEQ @CLAMP_FREEZE
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0002
	PHA
	REP #PROC_FLAGS::ACCUM8
	TYA
	DEC
	STA @VIRTUAL04
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::special
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	AND #$000C
	SEP #PROC_FLAGS::INDEX8
	PLY
	JSL ASR16
	STA @VIRTUAL02
	LDA @LOCAL00
	CLC
	ADC @VIRTUAL02
	STA @LOCAL00
@CLAMP_FREEZE:
	LDA @LOCAL00
	CLC
	SBC #$0003
	BRANCHLTEQS @FREEZE_IN_RANGE
	REP #PROC_FLAGS::INDEX8
	LDY #$0003
	STY @LOCAL01
	BRA @STORE_FREEZE
@FREEZE_IN_RANGE:
	LDA @LOCAL00
	REP #PROC_FLAGS::INDEX8
	TAY
	STY @LOCAL01
@STORE_FREEZE:
	LDX @LOCAL02
	TXA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL00
	TAX
	LDY @LOCAL01
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA PARTY_CHARACTERS+char_struct::freeze_resist,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	TAY
	BEQ @NO_BODY_FLASH
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0004
	PHA
	REP #PROC_FLAGS::ACCUM8
	TYA
	DEC
	STA @VIRTUAL02
	LDA @LOCAL00
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::special
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	AND #$0030
	SEP #PROC_FLAGS::INDEX8
	PLY
	JSL ASR16
	BRA @NO_OTHER_FLASH
@NO_BODY_FLASH:
	LDA #$0000
@NO_OTHER_FLASH:
	STA @LOCAL00
	REP #PROC_FLAGS::INDEX8
	LDX @LOCAL02
	TXA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	TAY
	BEQ @CLAMP_FLASH
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0004
	PHA
	REP #PROC_FLAGS::ACCUM8
	TYA
	DEC
	STA @VIRTUAL04
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::special
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	AND #$0030
	SEP #PROC_FLAGS::INDEX8
	PLY
	JSL ASR16
	STA @VIRTUAL02
	LDA @LOCAL00
	CLC
	ADC @VIRTUAL02
	STA @LOCAL00
@CLAMP_FLASH:
	LDA @LOCAL00
	CLC
	SBC #$0003
	BRANCHLTEQS @FLASH_IN_RANGE
	REP #PROC_FLAGS::INDEX8
	LDY #$0003
	STY @LOCAL01
	BRA @STORE_FLASH
@FLASH_IN_RANGE:
	LDA @LOCAL00
	REP #PROC_FLAGS::INDEX8
	TAY
	STY @LOCAL01
@STORE_FLASH:
	LDX @LOCAL02
	TXA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL00
	TAX
	LDY @LOCAL01
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA PARTY_CHARACTERS+char_struct::flash_resist,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	TAY
	BEQ @NO_BODY_PARALYSIS
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0006
	PHA
	REP #PROC_FLAGS::ACCUM8
	TYA
	DEC
	STA @VIRTUAL02
	LDA @LOCAL00
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::special
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	AND #$00C0
	SEP #PROC_FLAGS::INDEX8
	PLY
	JSL ASR16
	BRA @NO_OTHER_PARALYSIS
@NO_BODY_PARALYSIS:
	LDA #$0000
@NO_OTHER_PARALYSIS:
	STA @LOCAL00
	REP #PROC_FLAGS::INDEX8
	LDX @LOCAL02
	TXA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	TAY
	BEQ @CLAMP_PARALYSIS
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0006
	PHA
	REP #PROC_FLAGS::ACCUM8
	TYA
	DEC
	STA @VIRTUAL04
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::special
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	AND #$00C0
	SEP #PROC_FLAGS::INDEX8
	PLY
	JSL ASR16
	STA @VIRTUAL02
	LDA @LOCAL00
	CLC
	ADC @VIRTUAL02
	STA @LOCAL00
@CLAMP_PARALYSIS:
	LDA @LOCAL00
	CLC
	SBC #$0003
	BRANCHLTEQS @PARALYSIS_IN_RANGE
	REP #PROC_FLAGS::INDEX8
	LDY #$0003
	STY @LOCAL01
	BRA @STORE_PARALYSIS
@PARALYSIS_IN_RANGE:
	LDA @LOCAL00
	REP #PROC_FLAGS::INDEX8
	TAY
	STY @LOCAL01
@STORE_PARALYSIS:
	LDX @LOCAL02
	TXA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL00
	TAX
	LDY @LOCAL01
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA PARTY_CHARACTERS+char_struct::paralysis_resist,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::ARMS,X
	AND #$00FF
	TAY
	BEQ @NO_ARMS_HYPNOSIS
	TYA
	DEC
	STA @VIRTUAL02
	LDA @LOCAL00
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::special
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @LOCAL01
	BRA @STORE_HYPNOSIS
@NO_ARMS_HYPNOSIS:
	LDA #$0000
	STA @LOCAL01
@STORE_HYPNOSIS:
	LDX @LOCAL02
	TXA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	STA PARTY_CHARACTERS+char_struct::hypnosis_brainshock_resist,X
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
