
CALCULATE_BATTLER_ROW_WIDTH:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	LDA #0
	STA @VIRTUAL02
	LDX #.LOWORD(BATTLERS_TABLE) + .SIZEOF(battler) * 8
	STX @LOCAL01
	LDY #8
	STY @LOCAL00
	BRA @LOOP_CHECK
@LOOP_BODY:
	LDA a:battler::consciousness,X
	AND #$00FF
	CMP #1
	BNE @NEXT_BATTLER
	LDA a:battler::sprite,X
	JSR GET_BATTLE_SPRITE_WIDTH
	STA @VIRTUAL04
	LDA @VIRTUAL02
	CLC
	ADC @VIRTUAL04
	STA @VIRTUAL02
@NEXT_BATTLER:
	LDX @LOCAL01
	TXA
	CLC
	ADC #.SIZEOF(battler)
	TAX
	STX @LOCAL01
	LDY @LOCAL00
	INY
	STY @LOCAL00
@LOOP_CHECK:
	CPY #BATTLER_COUNT
	BCC @LOOP_BODY
	LDA @VIRTUAL02
	END_C_FUNCTION
