
CALC_PSI_DMG_MODIFIERS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_PARAM_INT16 ;int resistLevel
	END_STACK_VARS
	AND #$00FF
	BEQ @RESIST_NONE
	CMP #1
	BEQ @RESIST_LOW
	CMP #2
	BEQ @RESIST_MED
	CMP #3
	BEQ @RESIST_HIGH
	BRA @RETURN
@RESIST_NONE:
	SEP #PROC_FLAGS::ACCUM8
	LDA #255
	BRA @RETURN
@RESIST_LOW:
	SEP #PROC_FLAGS::ACCUM8
	LDA #179
	BRA @RETURN
@RESIST_MED:
	SEP #PROC_FLAGS::ACCUM8
	LDA #102
	BRA @RETURN
@RESIST_HIGH:
	SEP #PROC_FLAGS::ACCUM8
	LDA #13
@RETURN:
	SEP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
