
CALL_FOR_HELP_COMMON:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	STA @LOCAL0C
	LDX CURRENT_ATTACKER
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BEQ @HELP_FAILED
	LDX CURRENT_ATTACKER
	LDA a:battler::current_action_argument,X
	AND #$00FF
	STA @LOCAL0B
	LOADPTR BTL_ENTRY_PTR_TABLE, @VIRTUAL0A
	LDA CURRENT_BATTLE_GROUP
	OPTIMIZED_MULT @VIRTUAL04, 8
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	BRA @GROUP_SCAN_CHECK
@SCAN_GROUP_ENTRY:
	LDY #$0001
	LDA [@VIRTUAL06],Y
	CMP @LOCAL0B
	BEQ @FOUND_ENEMY
	LDA #$0003
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
@GROUP_SCAN_CHECK:
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	CMP #$00FF
	BNE @SCAN_GROUP_ENTRY
@HELP_FAILED:
	LDA @LOCAL0C
	BEQ @HELP_FAILED_TANE
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_TANEMAKI_NO
	JMP @RETURN
@HELP_FAILED_TANE:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_NAKAMA_NO
	JMP @RETURN
@FOUND_ENEMY:
	LDX #.LOWORD(BATTLERS_TABLE)
	LDA #$0000
	STA @LOCAL0A
	LDY #$0008
	BRA @COUNT_LOOP_CHECK
@COUNT_EXISTING:
	LDA a:battler::consciousness,X
	AND #$00FF
	CMP #$0001
	BNE @NEXT_BATTLER_COUNT
	LDA a:battler::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BEQ @NEXT_BATTLER_COUNT
	LDA a:battler::enemy_type_id,X
	CMP @LOCAL0B
	BNE @NEXT_BATTLER_COUNT
	LDA @LOCAL0A
	INC
	STA @LOCAL0A
@NEXT_BATTLER_COUNT:
	TXA
	CLC
	ADC #.SIZEOF(battler)
	TAX
	INY
@COUNT_LOOP_CHECK:
	CPY #$0020
	BCC @COUNT_EXISTING
	LOADPTR ENEMY_CONFIGURATION_TABLE, @VIRTUAL06
	LDA @LOCAL0B
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	TAX
	STX @LOCAL09
	TXA
	CLC
	ADC #enemy_data::max_called
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	TAY
	STY @LOCAL08
	LDA @LOCAL0A
	STA @VIRTUAL02
	TYA
	SEC
	SBC @VIRTUAL02
	LDY #$00CD
	JSL MULT168
	LDY @LOCAL08
	JSL DIVISION16S_DIVISOR_POSITIVE
	SEP #PROC_FLAGS::ACCUM8
	JSR SUCCESS_255
	.A16
	CMP #$0000
	BEQL @HELP_FAILED
	LDX @LOCAL09
	TXA
	CLC
	ADC #enemy_data::battle_sprite
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	STA @LOCAL08
	JSR GET_BATTLE_SPRITE_WIDTH
	OPTIMIZED_MULT @VIRTUAL04, 8
	CLC
	ADC #$0010
	STA @LOCAL07
	LDX @LOCAL09
	TXA
	CLC
	ADC #enemy_data::row
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	STA @LOCAL06
	JSR CALCULATE_BATTLER_ROW_WIDTH
	TAX
	STX @LOCAL05
	LDA @LOCAL08
	JSR GET_BATTLE_SPRITE_WIDTH
	STA @VIRTUAL02
	LDX @LOCAL05
	TXA
	CLC
	ADC @VIRTUAL02
	CMP #$0020
	BGTL @NO_SPACE
	LDA #$0080
	STA @LOCAL05
	STA @LOCAL04
	STA @VIRTUAL04
	LDY @VIRTUAL04
	STY @LOCAL03
	LDX #.LOWORD(BATTLERS_TABLE) + (.SIZEOF(battler) * 8)
	STX @LOCAL02
	LDA #$0008
	STA @LOCAL09
	BRA @POSITION_SCAN_CHECK
@SCAN_POSITIONS:
	LDA a:battler::consciousness,X
	AND #$00FF
	BEQ @NEXT_POSITION_BATTLER
	LDA a:battler::sprite,X
	JSR GET_BATTLE_SPRITE_WIDTH
	OPTIMIZED_MULT @VIRTUAL04, 8
	LSR
	STA @VIRTUAL02
	STA @LOCAL01
	LDX @LOCAL02
	LDA a:battler::row,X
	AND #$00FF
	CMP @LOCAL06
	BNE @CHECK_OTHER_ROW
	LDA a:battler::sprite_x,X
	AND #$00FF
	SEC
	SBC @VIRTUAL02
	LDY @LOCAL03
	STY @VIRTUAL02
	CMP @VIRTUAL02
	BCS @UPDATE_LEFT_BOUND
	TAY
	STY @LOCAL03
@UPDATE_LEFT_BOUND:
	LDA @LOCAL01
	STA @VIRTUAL02
	LDA a:battler::sprite_x,X
	AND #$00FF
	CLC
	ADC @VIRTUAL02
	CMP @VIRTUAL04
	BLTEQ @NEXT_POSITION_BATTLER
	STA @VIRTUAL04
	BRA @NEXT_POSITION_BATTLER
@CHECK_OTHER_ROW:
	LDA a:battler::sprite_x,X
	AND #$00FF
	SEC
	SBC @VIRTUAL02
	CMP @LOCAL04
	BCS @UPDATE_OTHER_LEFT
	STA @LOCAL04
@UPDATE_OTHER_LEFT:
	LDA a:battler::sprite_x,X
	AND #$00FF
	CLC
	ADC @VIRTUAL02
	CMP @LOCAL05
	BLTEQ @NEXT_POSITION_BATTLER
	STA @LOCAL05
@NEXT_POSITION_BATTLER:
	TXA
	CLC
	ADC #.SIZEOF(battler)
	TAX
	STX @LOCAL02
	INC @LOCAL09
@POSITION_SCAN_CHECK:
	LDA @LOCAL09
	CMP #$0020
	BCCL @SCAN_POSITIONS
	LDA @VIRTUAL04
	SEC
	SBC #$0080
	PHA
	LDY @LOCAL03
	STY @VIRTUAL02
	LDA #$0080
	SEC
	SBC @VIRTUAL02
	PLX
	STX @VIRTUAL02
	CMP @VIRTUAL02
	BCS @TRY_LEFT_SAME_ROW
	CPY @LOCAL07
	BLTEQ @TRY_SWAP_ROW
	LDA @LOCAL07
	LSR
	STA @VIRTUAL02
	TYA
	SEC
	SBC @VIRTUAL02
	TAY
	STY @LOCAL0A
	JMP @PLACE_NEW_ENEMY
@TRY_LEFT_SAME_ROW:
	.A16
	LDA @VIRTUAL04
	CLC
	ADC @LOCAL07
	CMP #$0100
	BCS @TRY_SWAP_ROW
	LDA @LOCAL07
	LSR
	STA @VIRTUAL02
	LDA @VIRTUAL04
	CLC
	ADC @VIRTUAL02
	TAY
	STY @LOCAL0A
	JMP @PLACE_NEW_ENEMY
@TRY_SWAP_ROW:
	LDA #$0001
	SEC
	SBC @LOCAL06
	STA @LOCAL06
	LDA @LOCAL05
	SEC
	SBC #$0080
	STA @VIRTUAL02
	LDA #$0080
	SEC
	SBC @LOCAL04
	CMP @VIRTUAL02
	BCS @TRY_LEFT_OTHER_ROW
	LDA @LOCAL04
	CMP @LOCAL07
	BLTEQ @NO_SPACE
	LDA @LOCAL07
	LSR
	STA @VIRTUAL02
	LDA @LOCAL04
	SEC
	SBC @VIRTUAL02
	TAY
	STY @LOCAL0A
	JMP @PLACE_NEW_ENEMY
@TRY_LEFT_OTHER_ROW:
	LDA @LOCAL05
	CLC
	ADC @LOCAL07
	CMP #$0100
	BCS @NO_SPACE
	LDA @LOCAL07
	LSR
	CLC
	ADC @LOCAL05
	TAY
	STY @LOCAL0A
	JMP @PLACE_NEW_ENEMY
@NO_SPACE:
	LDX #.LOWORD(BATTLERS_TABLE) + (.SIZEOF(battler) * 8)
	STX @LOCAL01
	LDA #$0008
	STA @VIRTUAL02
	BRA @DEAD_CHECK_LOOP
@FIND_DEAD_BATTLER:
	TXA
	CLC
	ADC #battler::consciousness
	TAY
	STY @LOCAL02
	LDA __BSS_START__,Y
	AND #$00FF
	CMP #$0001
	BNE @NEXT_DEAD_CHECK
	LDA a:battler::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BNE @NEXT_DEAD_CHECK
	LDA @LOCAL08
	JSR GET_BATTLE_SPRITE_WIDTH
	STA @VIRTUAL04
	LDX @LOCAL01
	LDA a:battler::sprite,X
	JSR GET_BATTLE_SPRITE_WIDTH
	PHA
	LDA @VIRTUAL04
	PLY
	STY @VIRTUAL04
	CMP @VIRTUAL04
	BNE @NEXT_DEAD_CHECK
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	LDY @LOCAL02 ;battler::consciousness
	STA __BSS_START__,Y
	LDX @LOCAL01
	REP #PROC_FLAGS::ACCUM8
	LDA a:battler::sprite_x,X
	AND #$00FF
	TAY
	STY @LOCAL0A
	LDA a:battler::row,X
	AND #$00FF
	STA @LOCAL06
	BRA @PLACE_NEW_ENEMY
@NEXT_DEAD_CHECK:
	LDX @LOCAL01
	TXA
	CLC
	ADC #.SIZEOF(battler)
	TAX
	STX @LOCAL01
	INC @VIRTUAL02
@DEAD_CHECK_LOOP:
	LDA @VIRTUAL02
	CMP #BATTLER_COUNT
	BCC @FIND_DEAD_BATTLER
	JMP @HELP_FAILED
@PLACE_NEW_ENEMY:
	JSR CALCULATE_BATTLER_ROW_WIDTH
	TAX
	STX @LOCAL09
	LDA @LOCAL08
	JSR GET_BATTLE_SPRITE_WIDTH
	STA @VIRTUAL02
	LDX @LOCAL09
	TXA
	CLC
	ADC @VIRTUAL02
	CMP #$0020
	BGTL @HELP_FAILED
	LDA #.LOWORD(BATTLERS_TABLE) + (.SIZEOF(battler) * 8)
	STA @LOCAL09
	LDX #$0008
	STX @LOCAL08
	BRA @FIND_EMPTY_CHECK
@FIND_EMPTY_SLOT:
	TAX
	LDA a:battler::consciousness,X
	AND #$00FF
	BEQ @INIT_NEW_BATTLER
	LDA @LOCAL09
	CLC
	ADC #.SIZEOF(battler)
	STA @LOCAL09
	LDX @LOCAL08
	INX
	STX @LOCAL08
@FIND_EMPTY_CHECK:
	CPX #$0020
	BCC @FIND_EMPTY_SLOT
@INIT_NEW_BATTLER:
	LDA @LOCAL09
	STA CURRENT_TARGET
	LDX CURRENT_TARGET
	LDA @LOCAL0B
	JSL BATTLE_INIT_ENEMY_STATS
	LDY @LOCAL0A
	TYA
	SEP #PROC_FLAGS::ACCUM8
	LDX CURRENT_TARGET
	STA a:battler::sprite_x,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL06
	SEP #PROC_FLAGS::ACCUM8
	LDX CURRENT_TARGET
	STA a:battler::row,X
	LDX CURRENT_TARGET
	REP #PROC_FLAGS::ACCUM8
	LDA a:battler::row,X
	AND #$00FF
	BEQ @SET_BACK_ROW_Y
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0080
	LDX CURRENT_TARGET
	STA a:battler::sprite_y,X
	BRA @SET_SPRITE
@SET_BACK_ROW_Y:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0090
	LDX CURRENT_TARGET
	STA a:battler::sprite_y,X
@SET_SPRITE:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL0B
	JSR FIND_BATTLE_SPRITE_FOR_ENEMY
	SEP #PROC_FLAGS::ACCUM8
	LDX CURRENT_TARGET
	STA a:battler::vram_sprite_index,X
	LDA #$0001
	LDX CURRENT_TARGET
	STA a:battler::has_taken_turn,X
	JSL FIX_TARGET_NAME
	.A16
	LDA @LOCAL0C
	BEQ @DISPLAY_TANE_TEXT
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_TANEMAKI_HAETA
	BRA @RETURN
@DISPLAY_TANE_TEXT:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_NAKAMA_KITA
@RETURN:
	END_C_FUNCTION
