
CHECK_DEAD_PLAYERS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #$0000
	STA @VIRTUAL04
	JMP @PARTY_LOOP_CHECK
@CHECK_BATTLER:
	LDA @VIRTUAL04
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAY
	STY @LOCAL03
	LDA BATTLERS_TABLE+battler::consciousness,Y
	AND #$00FF
	BEQL @NEXT_BATTLER
	LDA BATTLERS_TABLE+battler::ally_or_enemy,Y
	AND #$00FF
	BNEL @NEXT_BATTLER
	LDA BATTLERS_TABLE+battler::npc_id,Y
	AND #$00FF
	BNEL @NEXT_BATTLER
	LDA BATTLERS_TABLE+battler::row,Y
	AND #$00FF
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	STA @VIRTUAL02
	STA @LOCAL02
	LDY @LOCAL03
	TYA
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)+battler::hp
	TAX
	STX @LOCAL01
	LDX @VIRTUAL02
	LDA a:char_struct::current_hp,X
	LDX @LOCAL01
	STA __BSS_START__,X
	LDX @VIRTUAL02
	LDA a:char_struct::current_pp,X
	STA BATTLERS_TABLE+battler::pp,Y
	LDX @LOCAL01
	LDA __BSS_START__,X
	BNE @SYNC_AFFLICTIONS
	LDA BATTLERS_TABLE+battler::afflictions,Y
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BEQ @SYNC_AFFLICTIONS
	TYA
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	STA CURRENT_TARGET
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #STATUS_0::UNCONSCIOUS
	STA a:battler::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	LDX CURRENT_TARGET
	STZ a:battler::afflictions + STATUS_GROUP::SHIELD,X
	LDX CURRENT_TARGET
	STZ a:battler::afflictions + STATUS_GROUP::HOMESICKNESS,X
	LDX CURRENT_TARGET
	STZ a:battler::afflictions + STATUS_GROUP::CONCENTRATION,X
	LDX CURRENT_TARGET
	STZ a:battler::afflictions + STATUS_GROUP::STRANGENESS,X
	LDX CURRENT_TARGET
	STZ a:battler::afflictions + STATUS_GROUP:: TEMPORARY,X
	LDX CURRENT_TARGET
	STZ a:battler::afflictions + STATUS_GROUP::PERSISTENT_HARDHEAL,X
	JSL FIX_TARGET_NAME
	.A16
	LDX OPEN_WINDOW_TABLE + WINDOW::TEXT_BATTLE * 2
	STX @LOCAL03
	CREATE_WINDOW_FAR #WINDOW::TEXT_BATTLE
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIZETU_ON
	LDX @LOCAL03
	CPX #$FFFF
	BNE @SYNC_AFFLICTIONS
	JSL REDIRECT_CLOSE_FOCUS_WINDOW
@SYNC_AFFLICTIONS:
	LDX #$0000
	STX @LOCAL01
	BRA @AFFLICTION_LOOP_CHECK
@COPY_AFFLICTION:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	STA @VIRTUAL02
	STX @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	PHA
	STX @VIRTUAL02
	LDA @VIRTUAL04
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)+battler::afflictions
	CLC
	ADC @VIRTUAL02
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	PLX
	STA a:char_struct::afflictions,X
	LDX @LOCAL01
	INX
	STX @LOCAL01
@AFFLICTION_LOOP_CHECK:
	CPX #.SIZEOF(char_struct::afflictions)
	BCC @COPY_AFFLICTION
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	STA @VIRTUAL02
	CLC
	ADC #char_struct::afflictions + 4
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	BEQ @CLAMP_HOMESICKNESS
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA __BSS_START__,X
@CLAMP_HOMESICKNESS:
	JSL UPDATE_PARTY
@NEXT_BATTLER:
	INC @VIRTUAL04
@PARTY_LOOP_CHECK:
	.A16
	LDA @VIRTUAL04
	CMP #TOTAL_PARTY_COUNT
	BCCL @CHECK_BATTLER
	END_C_FUNCTION
