
CHECK_BATTLE_TARGET_TYPE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	TXY
	TAX
	STX @LOCAL00
	LDX CURRENT_TARGET
	LDA a:battler::npc_id,X
	AND #$00FF
	CMP #ENEMY::TINY_LIL_GHOST
	BNE @NOT_GHOST
	LDA #TRUE
	BRA @RETURN
@NOT_GHOST:
	LDX CURRENT_TARGET
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @IS_ENEMY
	LDX @LOCAL00
	TXA
	JSR APPLY_PSI_BATTLE_EFFECT
	LDA #FALSE
	BRA @RETURN
@IS_ENEMY:
	TYA
	JSR APPLY_PSI_BATTLE_EFFECT
	LDA #TRUE
@RETURN:
	END_C_FUNCTION
