CHOOSE_TARGET:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;NEAR battler*
	END_STACK_VARS
	STA $02
	LDX #$0000
	STX $0E
	BRA @FRONT_ROW_CHECK
@SCAN_FRONT_ROW:
	LDA FRONT_ROW_BATTLERS,X
	AND #$00FF
	JSL CHECK_IF_VALID_TARGET
	CMP #$0000
	BNE @AFTER_ROW_CHECK
	LDX $0E
	INX
	STX $0E
@FRONT_ROW_CHECK:
	CPX NUM_BATTLERS_IN_FRONT_ROW
	BCC @SCAN_FRONT_ROW
	LDX #$0000
	STX $0E
	BRA @BACK_ROW_CHECK
@SCAN_BACK_ROW:
	LDA BACK_ROW_BATTLERS,X
	AND #$00FF
	JSL CHECK_IF_VALID_TARGET
	CMP #$0000
	BNE @AFTER_ROW_CHECK
	LDX $0E
	INX
	STX $0E
@BACK_ROW_CHECK:
	CPX NUM_BATTLERS_IN_BACK_ROW
	BCC @SCAN_BACK_ROW
	JSL SORT_BATTLERS_INTO_ROWS
@AFTER_ROW_CHECK:
	LDX $02
	LDA a:battler::current_action,X
	OPTIMIZED_MULT $04, 12
	TAX
	LDA f:BATTLE_ACTION_TABLE,X
	AND #$00FF
	BNE @TARGET_HAS_TYPE
	LDX $02
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #$0001
	BNE @ENEMY_DEFAULT_TARGET
	LDX $02
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::action_targetting,X
	BRA @CHECK_TARGET_TYPE
@ENEMY_DEFAULT_TARGET:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0010
	LDX $02
	STA a:battler::action_targetting,X
	BRA @CHECK_TARGET_TYPE
@TARGET_HAS_TYPE:
	.A16
	LDX $02
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #$0001
	BNE @PLAYER_DEFAULT_TARGET
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0010
	LDX $02
	STA a:battler::action_targetting,X
	BRA @CHECK_TARGET_TYPE
@PLAYER_DEFAULT_TARGET:
	LDX $02
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::action_targetting,X
@CHECK_TARGET_TYPE:
	REP #PROC_FLAGS::ACCUM8
	LOADPTR BATTLE_ACTION_TABLE, $06
	LDX $02
	INX
	INX
	INX
	INX
	STX $0E
	LDA __BSS_START__,X ;battler.current_action
	OPTIMIZED_MULT $04, 12
	INC
	MOVE_INTX $06, $0A
	CLC
	ADC $0A
	STA $0A
	LDA [$0A]
	AND #$00FF
	BEQ @TARGET_TYPE_SELF
	CMP #$0001
	BEQ @TARGET_TYPE_SINGLE
	CMP #$0002
	BEQ @TARGET_TYPE_SINGLE
	CMP #$0003
	BEQL @TARGET_TYPE_ROW
	CMP #$0004
	BEQL @TARGET_TYPE_ALL
	JMP @RETURN
@TARGET_TYPE_SELF:
	LDA $02
	CLC
	ADC #battler::action_targetting
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	ORA #$0001
	STA __BSS_START__,X
	LDX $02
	REP #PROC_FLAGS::ACCUM8
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #$0001
	BNE @SELF_ENEMY
	LDY #.SIZEOF(battler)
	LDA $02
	SEC
	SBC #.LOWORD(BATTLERS_TABLE)
	JSL DIVISION16S_DIVISOR_POSITIVE
	TAX
	LDA $02
	JSL SET_BATTLER_TARGET
	JMP @RETURN
@SELF_ENEMY:
	LDY #.SIZEOF(battler)
	LDA $02
	SEC
	SBC #.LOWORD(BATTLERS_TABLE)
	JSL DIVISION16S_DIVISOR_POSITIVE
	SEP #PROC_FLAGS::ACCUM8
	INC
	LDX $02
	STA a:battler::current_target,X
	JMP @RETURN
@TARGET_TYPE_SINGLE:
	.A16
	LDA $02
	CLC
	ADC #battler::action_targetting
	TAY
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,Y
	ORA #$0001
	STA __BSS_START__,Y
	LDX $02
	REP #PROC_FLAGS::ACCUM8
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #$0001
	BNE @ENEMY_SINGLE_TARGET
	LDX $0E
	LDA __BSS_START__,X ;battler.current_action
	OPTIMIZED_MULT $04, 12
	CLC
	ADC $06
	STA $06
	LDA [$06]
	AND #$00FF
	BNE @PICK_RANDOM_FOR_PLAYER
	JSL FIND_TARGETTABLE_NPC
	SEP #PROC_FLAGS::ACCUM8
	LDX $02
	STA a:battler::current_target,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @RETURN
@PICK_RANDOM_PLAYER:
	JSL RAND
	SEP #PROC_FLAGS::ACCUM8
	AND #$0007
	INC
	LDX $02
	STA a:battler::current_target,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	DEC
	JSL CHECK_IF_VALID_TARGET
	CMP #$0000
	BNEL @RETURN
	BRA @PICK_RANDOM_PLAYER
@PICK_RANDOM_FOR_PLAYER:
	LDA $02
	JSL PICK_RANDOM_ENEMY_TARGET
	TAX
	JSL CHECK_IF_VALID_TARGET
	CMP #$0000
	BNEL @RETURN
	BRA @PICK_RANDOM_FOR_PLAYER
@ENEMY_SINGLE_TARGET:
	LDX $0E
	LDA __BSS_START__,X ;battler.current_action
	OPTIMIZED_MULT $04, 12
	CLC
	ADC $06
	STA $06
	LDA [$06]
	AND #$00FF
	BNE @PLAYER_PICK_RANDOM
@ENEMY_PICK_RANDOM:
	LDA $02
	JSL PICK_RANDOM_ENEMY_TARGET
	TAX
	JSL CHECK_IF_VALID_TARGET
	CMP #$0000
	BNEL @RETURN
	BRA @ENEMY_PICK_RANDOM
@PLAYER_PICK_RANDOM:
	JSL RAND
	SEP #PROC_FLAGS::ACCUM8
	AND #$0007
	INC
	LDX $02
	STA a:battler::current_target,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	DEC
	JSL CHECK_IF_VALID_TARGET
	CMP #$0000
	BEQ @PLAYER_PICK_RANDOM
	BRA @RETURN
@TARGET_TYPE_ROW:
	LDA $02
	CLC
	ADC #battler::action_targetting
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	ORA #$0002
	STA __BSS_START__,X
	LDX $02
	REP #PROC_FLAGS::ACCUM8
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #$0001
	BNE @ROW_NO_FRONT
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	LDX $02
	STA a:battler::current_target,X
	BRA @RETURN
@ROW_NO_FRONT:
	LDA NUM_BATTLERS_IN_FRONT_ROW
	BNE @ROW_NO_BACK
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0002
	LDX $02
	STA a:battler::current_target,X
	BRA @RETURN
@ROW_NO_BACK:
	LDA NUM_BATTLERS_IN_BACK_ROW
	BNE @ROW_RANDOM
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	LDX $02
	STA a:battler::current_target,X
	BRA @RETURN
@ROW_RANDOM:
	JSL RAND
	SEP #PROC_FLAGS::ACCUM8
	AND #$0001
	INC
	LDX $02
	STA a:battler::current_target,X
	BRA @RETURN
@TARGET_TYPE_ALL:
	.A16
	LDA $02
	CLC
	ADC #battler::action_targetting
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	ORA #$0004
	STA __BSS_START__,X
	LDA #$0001
	LDX $02
	STA a:battler::current_target,X
@RETURN:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
