
CLAMP_ENEMIES_TO_SCREEN_WIDTH:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDY #0
	STY @LOCAL01
	TYX
	STX @LOCAL00
	BRA @LOOP_CHECK
@LOOP_BODY:
	TXA
	ASL
	TAX
	LDA ENEMIES_IN_BATTLE_IDS,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::battle_sprite
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	JSR GET_BATTLE_SPRITE_WIDTH
	STA @VIRTUAL02
	LDY @LOCAL01
	TYA
	CLC
	ADC @VIRTUAL02
	TAY
	STY @LOCAL01
	CPY #32
	BLTEQ @NEXT_ENEMY
	LDX @LOCAL00
	STX ENEMIES_IN_BATTLE
	BRA @DONE
@NEXT_ENEMY:
	LDX @LOCAL00
	INX
	STX @LOCAL00
@LOOP_CHECK:
	CPX ENEMIES_IN_BATTLE
	BCC @LOOP_BODY
@DONE:
	END_C_FUNCTION
