
CLEAR_HPPP_WINDOW_HEADER:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	LDY #.LOWORD(BG2_BUFFER) + ((ACTIVE_HPPP_WINDOW_Y_OFFSET * 32) - 6) * 2
	LDX #0
	BRA @LOOP_CHECK
@CLEAR_TILE:
	LDA #0
	STA __BSS_START__,Y
	INY
	INY
	INX
@LOOP_CHECK:
	CPX #4
	BCC @CLEAR_TILE
	END_C_FUNCTION
