
CLEAR_BATTLER_FLASHING:
.IF .DEFINED(JPN)
	BEGIN_C_FUNCTION
.ELSE
	BEGIN_C_FUNCTION_FAR
.ENDIF
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CURRENT_FLASHING_ROW
	CMP #.LOWORD(-1)
	BEQ @DONE
	LDA CURRENT_FLASHING_ROW
	BEQ @USE_FRONT_ROW
	LDX NUM_BATTLERS_IN_BACK_ROW
	BRA @ROW_COUNT_SET
@USE_FRONT_ROW:
	LDX NUM_BATTLERS_IN_FRONT_ROW
@ROW_COUNT_SET:
	STX @VIRTUAL02
	LDX #0
	STX @LOCAL00
	BRA @LOOP_CHECK
@LOOP_BODY:
	LDA CURRENT_FLASHING_ROW
	BEQ @CLEAR_FRONT_ROW
	LDA BACK_ROW_BATTLERS,X
	AND #$00FF
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ BATTLERS_TABLE + battler::is_flash_target,X
	BRA @NEXT_BATTLER
@CLEAR_FRONT_ROW:
	.A16
	LDA FRONT_ROW_BATTLERS,X
	AND #$00FF
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ BATTLERS_TABLE + battler::is_flash_target,X
@NEXT_BATTLER:
	LDX @LOCAL00
	INX
	STX @LOCAL00
@LOOP_CHECK:
	REP #PROC_FLAGS::ACCUM8
	TXA
	CMP @VIRTUAL02
	BCC @LOOP_BODY
	STZ ENEMY_TARGETTING_FLASHING
	LDA #.LOWORD(-1)
	STA CURRENT_FLASHING_ROW
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA REDRAW_ALL_WINDOWS
@DONE:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
