
CLEANUP_WINDOW_TILES:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	CMP #$FFFF
	BNE @DONE
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	TAX
	STX @LOCAL01
	LDY a:window_stats::tilemap_address,X
	STY @LOCAL00
	LDY a:window_stats::height,X
	LDA a:window_stats::width,X
	JSL MULT16
	STA @VIRTUAL02
	BRA @CHECK_REMAINING
@FREE_TILE_LOOP:
	LDY @LOCAL00
	LDA __BSS_START__,Y
	BEQ @TILE_ALREADY_FREE
	JSL FREE_TILE_SAFE
@TILE_ALREADY_FREE:
	LDA #64
	LDY @LOCAL00
	STA __BSS_START__,Y
	INY
	INY
	STY @LOCAL00
	LDA @VIRTUAL02
	DEC
	STA @VIRTUAL02
@CHECK_REMAINING:
	LDA @VIRTUAL02
	BNE @FREE_TILE_LOOP
	LDX @LOCAL01
	LDA a:window_stats::unknown59,X
	AND #$00FF
	BEQ @CLEAR_TITLE_FLAGS
	AND #$00FF
	DEC
	ASL
	TAX
	LDA #$FFFF
	STA TITLED_WINDOWS,X
@CLEAR_TITLE_FLAGS:
	LDX @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	STZ a:window_stats::title,X
	STZ a:window_stats::unknown59,X
	LDA #1
	STA REDRAW_ALL_WINDOWS
	JSL CLEAR_PARTY_SPRITE_HIDE_FLAGS
@DONE:
	END_C_FUNCTION
