
CLOSE_OVAL_WINDOW:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	LDX #0
	TXA
	JSL INIT_SWIRL_EFFECT
	SEP #PROC_FLAGS::ACCUM8
	LDA #19
	STA SWIRL_MASK_SETTINGS
	REP #PROC_FLAGS::ACCUM8
	LDA ACTIVE_OVAL_WINDOW
	AND #$00FF
	BEQ @STANDARD_CLOSE
	MOVE_INT_CONSTANT OVAL_WINDOW_VARIANT_CLOSE, LOADED_OVAL_WINDOW
	BRA @RETURN
@STANDARD_CLOSE:
	MOVE_INT_CONSTANT OVAL_WINDOW_STANDARD_CLOSE, LOADED_OVAL_WINDOW
@RETURN:
	END_C_FUNCTION
