
COUNT_CHARS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16 ;int side
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	STA @VIRTUAL04
	LDA #$0000
	STA @VIRTUAL02
	LDX #.LOWORD(BATTLERS_TABLE)
	TAY
	BRA @LOOP_CHECK
@LOOP_BODY:
	LDA a:battler::consciousness,X
	AND #$00FF
	BEQ @NEXT
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP @VIRTUAL04
	BNE @NEXT
	LDA a:battler::npc_id,X
	AND #$00FF
	BNE @NEXT
	LDA a:battler::afflictions,X
	AND #$00FF
	CMP #$0001
	BEQ @NEXT
	CMP #$0002
	BEQ @NEXT
	INC @VIRTUAL02
@NEXT:
	TXA
	CLC
	ADC #.SIZEOF(battler)
	TAX
	INY
@LOOP_CHECK:
	CPY #$0020
	BCC @LOOP_BODY
	LDA @VIRTUAL02
	END_C_FUNCTION
