
HEXADECIMATE_OFFENSE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;NEAR battler*
	END_STACK_VARS
	STA @VIRTUAL02
	CLC
	ADC #battler::offense
	TAY
	LDA __BSS_START__,Y
	LSR
	LSR
	LSR
	LSR
	BEQ @CLAMP_MIN
	TAX
	BRA @APPLY_DECREASE
@CLAMP_MIN:
	LDX #1
@APPLY_DECREASE:
	STX @VIRTUAL04
	LDA __BSS_START__,Y
	SEC
	SBC @VIRTUAL04
	STA __BSS_START__,Y
	LDA @VIRTUAL02
	CLC
	ADC #battler::offense
	TAX
	STX @LOCAL01
	LDX @VIRTUAL02
	LDA a:battler::base_offense,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, 3
	LSR
	LSR
	STA @LOCAL00
	STA @VIRTUAL02
	LDX @LOCAL01
	LDA __BSS_START__,X
	CMP @VIRTUAL02
	BCS @DONE
	LDA @LOCAL00
	STA __BSS_START__,X
@DONE:
	END_C_FUNCTION
