
DETERMINE_DODGE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	LDX CURRENT_TARGET
	LDA a:battler::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	CMP #STATUS_0::PARALYZED
	BNE @CHECK_ASLEEP
	LDA #0
	BRA @RETURN
@CHECK_ASLEEP:
	LDX CURRENT_TARGET
	LDA a:battler::afflictions + STATUS_GROUP::TEMPORARY,X
	AND #$00FF
	CMP #STATUS_2::ASLEEP
	BNE @CHECK_IMMOBILIZED
	LDA #0
	BRA @RETURN
@CHECK_IMMOBILIZED:
	CMP #STATUS_2::IMMOBILIZED
	BNE @CHECK_SOLIDIFIED
	LDA #0
	BRA @RETURN
@CHECK_SOLIDIFIED:
	CMP #STATUS_2::SOLIDIFIED
	BNE @CALC_SPEED
	LDA #0
	BRA @RETURN
@CALC_SPEED:
	LDX CURRENT_TARGET
	LDA a:battler::speed,X
	ASL
	LDX CURRENT_ATTACKER
	SEC
	SBC a:battler::speed,X
	STA @LOCAL00
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @NO_DODGE
	LDA @LOCAL00
	JSR SUCCESS_500
	CMP #0
	BNE @DODGED
@NO_DODGE:
	LDA #0
	BRA @RETURN
@DODGED:
	LDA #1
@RETURN:
	END_C_FUNCTION
