
DISPLAY_BATTLE_CUTSCENE_TEXT:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int group
	STACK_RESERVE_PARAM_INT16 ;int music
	STACK_RESERVE_PARAM_INT32 "SCRIPT"; const char* script
	END_STACK_VARS
	STX @VIRTUAL02
	TAY
	STY @LOCAL01
	MOVE_INT @SCRIPT, @VIRTUAL06
	LDX #4
	LDA #1
	JSL FADE_OUT
	JSR WAIT_FOR_FADE_WITH_TICK
	STZ BATTLE_MODE_FLAG
	STZ CURRENT_MAP_MUSIC_TRACK
	JSL CLOSE_ALL_WINDOWS_AND_HIDE_HPPP
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_IN_BATTLE_TEXT
	LDX #2
	LDA #1
	JSL FADE_OUT
	JSR WAIT_FOR_FADE_WITH_TICK
	LDX @VIRTUAL02
	LDY @LOCAL01
	TYA
	JSR LOAD_BATTLE_SCENE
	LDA #1
	STA BATTLE_MODE_FLAG
	JSL REDIRECT_SHOW_HPPP_WINDOWS
	CREATE_WINDOW_FAR #WINDOW::TEXT_BATTLE
	LDA #1*SECOND
	JSR WAIT
	END_C_FUNCTION
