
EAT_FOOD:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16 "LOCAL02"
.IF .DEFINED(USA)
	STACK_RESERVE_INT32 "LOCALEB"
	@TEXTTMP := @VIRTUAL06
.ELSE
	@TEXTTMP := @VIRTUAL0A
.ENDIF
	STACK_RESERVE_INT16 "LOCAL03"
	END_STACK_VARS
	LDX CURRENT_TARGET
	LDA a:battler::id,X
	TAX
	STX @LOCAL03
	TXA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::afflictions,X
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BNE @NOT_UNCONSCIOUS
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
	JMP @RETURN
@NOT_UNCONSCIOUS:
	JSR APPLY_CONDIMENT
.IF .DEFINED(USA)
	MOVE_INT @VIRTUAL06, @LOCALEB
.ENDIF
	LDX @LOCAL03
	CPX #4
	BNE @NOT_POO
	LDA #2
	BRA @APPLY_FOOD_EFFECT
@NOT_POO:
	LDA #1
@APPLY_FOOD_EFFECT:
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	TAY
	STY @LOCAL02
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	BEQ @CASE_HP_RECOVERY
	CMP #1
	BEQ @CASE_PP_RECOVERY
	CMP #2
	BEQL @CASE_HP_PP_RECOVERY
	CMP #3
	BEQL @CASE_RANDOM_STAT
	CMP #4
	BEQL @BOOST_IQ
	CMP #5
	BEQL @BOOST_GUTS
	CMP #6
	BEQL @BOOST_SPEED
	CMP #7
	BEQL @BOOST_VITALITY
	CMP #8
	BEQL @BOOST_LUCK
	CMP #9
	BEQL @CASE_HEAL_STATUS
	CMP #10
	BEQL @CASE_CURE_POISON
	JMP @CHECK_CONDIMENT_SPECIAL
@CASE_HP_RECOVERY:
	CPY #0
	BEQ @HP_FULL_RECOVERY
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 6
	JSR TWENTY_FIVE_PERCENT_VARIANCE
	TAX
	BRA @DO_HP_RECOVERY
@HP_FULL_RECOVERY:
	LDX #30000
@DO_HP_RECOVERY:
	LDA CURRENT_TARGET
	JSR RECOVER_HP
	JMP @CHECK_CONDIMENT_SPECIAL
@CASE_PP_RECOVERY:
	CPY #0
	BEQ @PP_FULL_RECOVERY
	TYA
	JSR TWENTY_FIVE_PERCENT_VARIANCE
	TAX
	BRA @DO_PP_RECOVERY
@PP_FULL_RECOVERY:
	LDX #30000
@DO_PP_RECOVERY:
	LDA CURRENT_TARGET
	JSR RECOVER_PP
	JMP @CHECK_CONDIMENT_SPECIAL
@CASE_HP_PP_RECOVERY:
	CPY #0
	BEQ @HP_FULL_PART
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 6
	JSR TWENTY_FIVE_PERCENT_VARIANCE
	TAX
	BRA @DO_HP_PART
@HP_FULL_PART:
	LDX #30000
@DO_HP_PART:
	LDA CURRENT_TARGET
	JSR RECOVER_HP
	LDY @LOCAL02
	BEQ @PP_FULL_PART
	TYA
	JSR TWENTY_FIVE_PERCENT_VARIANCE
	TAX
	BRA @DO_PP_PART
@PP_FULL_PART:
	LDX #$7530
@DO_PP_PART:
	LDA CURRENT_TARGET
	JSR RECOVER_PP
	JMP @CHECK_CONDIMENT_SPECIAL
@CASE_RANDOM_STAT:
	LDA #$0004
	JSR RAND_LIMIT
	CMP #0
	BEQ @BOOST_IQ
	CMP #1
	BEQL @BOOST_GUTS
	CMP #2
	BEQL @BOOST_SPEED
	CMP #3
	BEQL @BOOST_VITALITY
	CMP #4
	BEQL @BOOST_LUCK
	JMP @CHECK_CONDIMENT_SPECIAL
@BOOST_IQ:
	LDA CURRENT_TARGET
	CLC
	ADC #battler::iq
	LDY @LOCAL02
	SEP #PROC_FLAGS::INDEX8
	STY @VIRTUAL00
	PHA
	REP #PROC_FLAGS::INDEX8
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL00
	PLX
	STA __BSS_START__,X
	LDX @LOCAL03
	REP #PROC_FLAGS::ACCUM8
	TXA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::boosted_iq
	PHA
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL00
	PLX
	STA __BSS_START__,X
	LDX @LOCAL03
	REP #PROC_FLAGS::ACCUM8
	TXA
	JSL RECALC_CHARACTER_POSTMATH_IQ
	REP #PROC_FLAGS::ACCUM8
	LOADPTR MSG_BTL_IQ_UP, @LOCAL00
	LDY @LOCAL02
	TYA
	STORE_INT1632 @TEXTTMP
	MOVE_INT @TEXTTMP, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	JMP @CHECK_CONDIMENT_SPECIAL
@BOOST_GUTS:
	LDA CURRENT_TARGET
	CLC
	ADC #battler::guts
	PHA
	LDY @LOCAL02
	STY @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL02
	PLX
	STA __BSS_START__,X
	LDX @LOCAL03
	TXA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::boosted_guts
	PHA
	LDY @LOCAL02
	SEP #PROC_FLAGS::INDEX8
	STY @VIRTUAL00
	REP #PROC_FLAGS::INDEX8
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL00
	PLX
	STA __BSS_START__,X
	LDX @LOCAL03
	REP #PROC_FLAGS::ACCUM8
	TXA
	JSL RECALC_CHARACTER_POSTMATH_GUTS
	REP #PROC_FLAGS::ACCUM8
	LOADPTR MSG_BTL_GUTS_UP, @LOCAL00
	LDY @LOCAL02
	TYA
	STORE_INT1632 @TEXTTMP
	MOVE_INT @TEXTTMP, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	JMP @CHECK_CONDIMENT_SPECIAL
@BOOST_SPEED:
	LDA CURRENT_TARGET
	CLC
	ADC #battler::speed
	PHA
	LDY @LOCAL02
	STY @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL02
	PLX
	STA __BSS_START__,X
	LDX @LOCAL03
	TXA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::boosted_speed
	PHA
	LDY @LOCAL02
	SEP #PROC_FLAGS::INDEX8
	STY @VIRTUAL00
	REP #PROC_FLAGS::INDEX8
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL00
	PLX
	STA __BSS_START__,X
	LDX @LOCAL03
	REP #PROC_FLAGS::ACCUM8
	TXA
	JSL RECALC_CHARACTER_POSTMATH_SPEED
	REP #PROC_FLAGS::ACCUM8
	LOADPTR MSG_BTL_SPEED_UP, @LOCAL00
	LDY @LOCAL02
	TYA
	STORE_INT1632 @TEXTTMP
	MOVE_INT @TEXTTMP, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	JMP @CHECK_CONDIMENT_SPECIAL
@BOOST_VITALITY:
	LDA CURRENT_TARGET
	CLC
	ADC #battler::vitality
	LDY @LOCAL02
	SEP #PROC_FLAGS::INDEX8
	STY @VIRTUAL00
	PHA
	REP #PROC_FLAGS::INDEX8
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL00
	PLX
	STA __BSS_START__,X
	LDX @LOCAL03
	REP #PROC_FLAGS::ACCUM8
	TXA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::boosted_vitality
	PHA
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL00
	PLX
	STA __BSS_START__,X
	LDX @LOCAL03
	REP #PROC_FLAGS::ACCUM8
	TXA
	JSL RECALC_CHARACTER_POSTMATH_VITALITY
	REP #PROC_FLAGS::ACCUM8
	LOADPTR MSG_BTL_VITA_UP, @LOCAL00
	LDY @LOCAL02
	TYA
	STORE_INT1632 @TEXTTMP
	MOVE_INT @TEXTTMP, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	BRA @CHECK_CONDIMENT_SPECIAL
@BOOST_LUCK:
	LDA CURRENT_TARGET
	CLC
	ADC #battler::luck
	PHA
	LDY @LOCAL02
	STY @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL02
	PLX
	STA __BSS_START__,X
	LDX @LOCAL03
	TXA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::boosted_luck
	PHA
	LDY @LOCAL02
	SEP #PROC_FLAGS::INDEX8
	STY @VIRTUAL00
	REP #PROC_FLAGS::INDEX8
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL00
	PLX
	STA __BSS_START__,X
	LDX @LOCAL03
	REP #PROC_FLAGS::ACCUM8
	TXA
	JSL RECALC_CHARACTER_POSTMATH_LUCK
	REP #PROC_FLAGS::ACCUM8
	LOADPTR MSG_BTL_LUCK_UP, @LOCAL00
	LDY @LOCAL02
	TYA
	STORE_INT1632 @TEXTTMP
	MOVE_INT @TEXTTMP, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	BRA @CHECK_CONDIMENT_SPECIAL
@CASE_HEAL_STATUS:
	JSL BTLACT_HEALING_A
	BRA @CHECK_CONDIMENT_SPECIAL
@CASE_CURE_POISON:
	JSL HEAL_POISON
@CHECK_CONDIMENT_SPECIAL:
.IF .DEFINED(USA)
	MOVE_INT @LOCALEB, @VIRTUAL06
.ENDIF
	SEP #PROC_FLAGS::ACCUM8
	LDY #item_parameters::special
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQ @RETURN
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, 6
	JSL SCHEDULE_PARTY_ANIMATION_RESET
@RETURN:
	END_C_FUNCTION
