
ENEMY_FLASHING_ON:
.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
	BEGIN_C_FUNCTION_FAR
.ELSE
	BEGIN_C_FUNCTION
.ENDIF
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int enemy
	STACK_RESERVE_PARAM_INT16 ;int row
	END_STACK_VARS
	STX @LOCAL01
	STA @LOCAL00
	LDA CURRENT_FLASHING_ENEMY
	CMP #$FFFF
	BEQ @NO_PREVIOUS_FLASH
.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
	JSL ENEMY_FLASHING_OFF
.ELSE
	JSR ENEMY_FLASHING_OFF
.ENDIF
@NO_PREVIOUS_FLASH:
	LDX @LOCAL01
	STX CURRENT_FLASHING_ENEMY
	LDA @LOCAL00
	STA CURRENT_FLASHING_ENEMY_ROW
	BEQ @FRONT_ROW
	LDX CURRENT_FLASHING_ENEMY
	LDA BACK_ROW_BATTLERS,X
	AND #$00FF
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA BATTLERS_TABLE+battler::is_flash_target,X
	BRA @SET_FLASH_STATE
@FRONT_ROW:
	.A16
	LDX CURRENT_FLASHING_ENEMY
	LDA FRONT_ROW_BATTLERS,X
	AND #$00FF
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA BATTLERS_TABLE+battler::is_flash_target,X
@SET_FLASH_STATE:
	REP #PROC_FLAGS::ACCUM8
	LDA #1
	STA ENEMY_TARGETTING_FLASHING
	SEP #PROC_FLAGS::ACCUM8
	STA REDRAW_ALL_WINDOWS
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
