
ENEMY_SELECT_MODE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	STA @VIRTUAL04
	STA @LOCAL0A
	LDA @VIRTUAL04
	STA @LOCAL09
	JSR SET_INSTANT_PRINTING
	CREATE_WINDOW_NEAR #WINDOW::TEXT_BATTLE
	LDA OPEN_WINDOW_TABLE + WINDOW::TEXT_BATTLE * 2
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	TAX
	LDA a:window_stats::text_x,X
	STA @LOCAL08
	LDA a:window_stats::text_y,X
	STA @LOCAL07
	LDA #1
	STA @LOCAL06
	STA @LOCAL05
@REDRAW_NUMBER:
	JSR SET_INSTANT_PRINTING
	LDX @LOCAL07
	LDA @LOCAL08
	JSR SET_FOCUS_TEXT_CURSOR
	LDA @LOCAL0A
	STA @VIRTUAL04
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR NUMBER_TO_TEXT_BUFFER
	STA @VIRTUAL02
	LDA #7
	SEC
	SBC @VIRTUAL02
	CLC
	ADC #.LOWORD(NUMBER_TEXT_BUFFER)
	TAY
	STY @LOCAL04
	LDX #3
	STX @LOCAL03
	BRA @LEADING_ZERO_CHECK
@PRINT_LEADING_ZEROS:
	CPX @LOCAL06
	BNE @NORMAL_ZERO
.IF CLEAN_ROM
	LDA #CHAR::JZERO_UNDERLINED
.ELSE
	LDA #CHAR::ZERO
.ENDIF
	BRA @PRINT_ZERO
@NORMAL_ZERO:
.IF CLEAN_ROM
	LDA #CHAR::JZERO
.ELSE
	LDA #CHAR::ZERO
.ENDIF
@PRINT_ZERO:
	JSR PRINT_LETTER
	LDX @LOCAL03
	DEX
	STX @LOCAL03
@LEADING_ZERO_CHECK:
	TXA
	CMP @VIRTUAL02
	BGT @PRINT_LEADING_ZEROS
	BRA @DIGIT_LOOP_CHECK
@PRINT_DIGIT_ENTRY:
	CPX @LOCAL06
	BNE @DIGIT_NORMAL_ZERO
.IF CLEAN_ROM
	LDA #CHAR::JZERO_UNDERLINED
.ELSE
	LDA #CHAR::ZERO
.ENDIF
	BRA @PRINT_DIGIT_WITH_OFFSET
@DIGIT_NORMAL_ZERO:
.IF CLEAN_ROM
	LDA #CHAR::JZERO
.ELSE
	LDA #CHAR::ZERO
.ENDIF
@PRINT_DIGIT_WITH_OFFSET:
	STA @VIRTUAL02
	LDY @LOCAL04
	LDA __BSS_START__,Y
	AND #$00FF
	CLC
	ADC @VIRTUAL02
	INY
	STY @LOCAL04
	JSR PRINT_LETTER
	LDX @LOCAL03
	DEX
	STX @LOCAL03
@DIGIT_LOOP_CHECK:
	CPX #0
	BNE @PRINT_DIGIT_ENTRY
	JSR CLEAR_INSTANT_PRINTING
	JSL WINDOW_TICK
@INPUT_LOOP:
	JSL WINDOW_TICK
	LDA PAD_PRESS
	AND #PAD::LEFT
	BEQ @CHECK_RIGHT
	LDA @LOCAL06
	CMP #3
	BCS @CHECK_RIGHT
	INC @LOCAL06
	LDA @LOCAL05
	OPTIMIZED_MULT @VIRTUAL04, 10
	STA @LOCAL05
	JMP @REDRAW_NUMBER
@CHECK_RIGHT:
	LDA PAD_PRESS
	AND #PAD::RIGHT
	BEQ @CHECK_UP
	LDA @LOCAL06
	CMP #1
	BLTEQ @CHECK_UP
	DEC @LOCAL06
	MOVE_INT_CONSTANT 10, @VIRTUAL0A
	MOVE_INT1632 @LOCAL05, @VIRTUAL06
	JSL DIVISION32
	LDA @VIRTUAL06
	STA @LOCAL05
	JMP @REDRAW_NUMBER
@CHECK_UP:
	LDA PAD_HELD
	AND #PAD::UP
	BEQ @CHECK_DOWN
	MOVE_INT_CONSTANT 10, @VIRTUAL0A
	LDY @LOCAL05
	LDA @VIRTUAL04
	JSL DIVISION16S_DIVISOR_POSITIVE
	STORE_INT1632 @VIRTUAL06
	JSL MODULUS32S
	MOVE_INT_CONSTANT 9, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BEQ @UP_WRAP
	LDA @VIRTUAL04
	CLC
	ADC @LOCAL05
	STA @VIRTUAL04
	STA @LOCAL0A
	JMP @VALIDATE_NUMBER
@UP_WRAP:
	LDA @LOCAL05
	OPTIMIZED_MULT @VIRTUAL04, 9
	STA @VIRTUAL02
	LDA @LOCAL0A
	STA @VIRTUAL04
	SEC
	SBC @VIRTUAL02
	STA @VIRTUAL04
	STA @LOCAL0A
	JMP @VALIDATE_NUMBER
@CHECK_DOWN:
	LDA PAD_HELD
	AND #PAD::DOWN
	BEQ @CHECK_A
	MOVE_INT_CONSTANT 10, @VIRTUAL0A
	LDY @LOCAL05
	LDA @VIRTUAL04
	JSL DIVISION16S_DIVISOR_POSITIVE
	STORE_INT1632 @VIRTUAL06
	JSL MODULUS32S
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BEQ @DOWN_WRAP
	LDA @VIRTUAL04
	SEC
	SBC @LOCAL05
	STA @VIRTUAL04
	STA @LOCAL0A
	BRA @VALIDATE_NUMBER
@DOWN_WRAP:
	LDA @LOCAL05
	OPTIMIZED_MULT @VIRTUAL04, 9
	STA @VIRTUAL02
	LDA @LOCAL0A
	STA @VIRTUAL04
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL04
	STA @LOCAL0A
	BRA @VALIDATE_NUMBER
@CHECK_A:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON | PAD::L_BUTTON
	BEQ @CHECK_B
	LDX @VIRTUAL04
	STX @LOCAL03
	JMP @CLOSE_AND_RETURN
@CHECK_B:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON
	BEQL @INPUT_LOOP
	LDX @LOCAL09
	STX @LOCAL03
	JMP @CLOSE_AND_RETURN
@VALIDATE_NUMBER:
	LDA @VIRTUAL04
	BEQL @REDRAW_NUMBER
	LDA @VIRTUAL04
	CMP #ENEMY_GROUP::MINI_BARF
	BLTEQ @LOAD_ENEMY_GROUP
	LDA #ENEMY_GROUP::MINI_BARF
	STA @VIRTUAL04
	STA @LOCAL0A
@LOAD_ENEMY_GROUP:
	LDA @VIRTUAL04
	STA CURRENT_BATTLE_GROUP
	LOADPTR BTL_ENTRY_PTR_TABLE, @VIRTUAL0A
	LDA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, 8
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDY #battle_entry_ptr_entry::pointer+2
	LDA [@VIRTUAL0A],Y
	TAY
	LDA [@VIRTUAL0A]
	STA @VIRTUAL06
	STY @VIRTUAL06+2
	STZ ENEMIES_IN_BATTLE
	BRA @GROUP_LOOP_CHECK
@PARSE_GROUP_ENTRY:
	LDA ENEMIES_IN_BATTLE
	ASL
	TAX
	LDY #battle_group_entry::id
	LDA [@VIRTUAL06],Y
	STA ENEMIES_IN_BATTLE_IDS,X
	INC ENEMIES_IN_BATTLE
@NEXT_GROUP_ENTRY:
	LDX @LOCAL02
	TXY
	DEX
	STX @LOCAL02
	CPY #0
	BNE @PARSE_GROUP_ENTRY
	LDA #.SIZEOF(battle_group_entry)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
@GROUP_LOOP_CHECK:
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	TAX
	STX @LOCAL02
	CPX #$00FF
	BNE @NEXT_GROUP_ENTRY
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	JSL SETUP_BATTLE_ENEMY_SPRITES
	LDY #8
	STY @LOCAL03
	BRA @CLEAR_BATTLER_CHECK
@CLEAR_BATTLER:
	SEP #PROC_FLAGS::ACCUM8
	STZ_BADOPT @LOCAL00
	LDX #.SIZEOF(battler)
	REP #PROC_FLAGS::ACCUM8
	TYA
	TXY
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	JSL MEMSET16
	LDY @LOCAL03
	INY
	STY @LOCAL03
@CLEAR_BATTLER_CHECK:
	CPY #BATTLER_COUNT
	BCC @CLEAR_BATTLER
	LDY #0
	STY @LOCAL04
	BRA @INIT_ENEMY_CHECK
@INIT_ENEMY_BATTLER:
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE) + (.SIZEOF(battler) * 8)
	TAX
	STX @LOCAL01
	LDY @LOCAL04
	TYA
	ASL
	TAX
	LDA ENEMIES_IN_BATTLE_IDS,X
	LDX @LOCAL01
	JSL BATTLE_INIT_ENEMY_STATS
	LDY @LOCAL04
	INY
	STY @LOCAL04
@INIT_ENEMY_CHECK:
	CPY ENEMIES_IN_BATTLE
	BCC @INIT_ENEMY_BATTLER
	JSL LAYOUT_ENEMY_BATTLE_POSITIONS
	LDA #24
	JSL SET_PALETTE_UPLOAD_MODE
	JSL BLANK_SCREEN_AND_WAIT_VBLANK
	LDX #1
	TXA
	JSL FADE_IN
	JMP @REDRAW_NUMBER
@CLOSE_AND_RETURN:
	LDA #WINDOW::TEXT_BATTLE
	JSR SET_WINDOW_FOCUS
	JSR CLOSE_FOCUS_WINDOW
	LDX @LOCAL03
	TXA
	END_C_FUNCTION
