
FAIL_ATTACK_ON_NPCS:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	LDX CURRENT_TARGET
	LDA a:battler::npc_id,X
	AND #$00FF
	BEQ @NOT_NPC
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIKANAI
	LDA #1
	BRA @RETURN
@NOT_NPC:
	LDA #0
@RETURN:
	END_C_FUNCTION
