
FEELING_STRANGE_RETARGETTING:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	MOVE_INT_CONSTANT 0, BATTLER_TARGET_FLAGS
	LDX CURRENT_ATTACKER
	LDA a:battler::action_targetting,X
	AND #$00FF
	AND #$0007
	CMP #ACTION_TARGET::ONE
	BEQ @TARGET_ONE
	CMP #ACTION_TARGET::RANDOM
	BEQ @TARGET_RANDOM
	CMP #ACTION_TARGET::ALL
	BEQ @TARGET_ALL
	BRA @DONE
@TARGET_ONE:
	JSL TARGET_ALL
	MOVE_INT BATTLER_TARGET_FLAGS, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL RANDOM_TARGETTING
	MOVE_INT @VIRTUAL06, BATTLER_TARGET_FLAGS
	BRA @DONE
@TARGET_RANDOM:
	JSL RAND
	LDY #3
	JSL MODULUS16
	JSL TARGET_ROW
	BRA @DONE
@TARGET_ALL:
	JSL RAND
	AND #$0001
	BEQ @TARGET_ENEMIES
	JSL TARGET_ALLIES
	BRA @CHECK_SHIELD
@TARGET_ENEMIES:
	JSL TARGET_ALL_ENEMIES
@CHECK_SHIELD:
	LDX CURRENT_ATTACKER
	LDA a:battler::current_action,X
	JSL GET_SHIELD_TARGETTING
	CMP #0
	BNE @DONE
	LDX CURRENT_ATTACKER
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @DONE
	JSL REMOVE_NPC_TARGETTING
@DONE:
	END_C_FUNCTION
