
FIND_STEALABLE_ITEMS:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
.IF .DEFINED(JPN)
	STACK_RESERVE_INT16 "LOCALM2"
.ENDIF
	STACK_RESERVE_INT16 "LOCAL00"
	STACK_RESERVE_INT16 "LOCAL01"
	STACK_RESERVE_INT16 "LOCAL02"
	STACK_RESERVE_INT16 "LOCAL03"
	STACK_RESERVE_INT16 "LOCAL04"
	STACK_RESERVE_INT16 "LOCAL05"
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STZ @LOCAL05
	STZ @LOCAL04
	JMP @PARTY_LOOP_CHECK
@PROCESS_PARTY_MEMBER:
.IF .DEFINED(JPN)
	LDA @LOCAL04
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
.ELSE
	LDY #.LOWORD(GAME_STATE) + game_state::party_members
	LDA (@LOCAL04),Y
.ENDIF
	AND #$00FF
	STA @LOCAL03
	CMP #$0001
	BCCL @NEXT_PARTY_MEMBER
	LDA @LOCAL03
	CMP #$0004
	BGTL @NEXT_PARTY_MEMBER
	LDA #$0000
	STA @LOCAL02
	BRA @FIND_BATTLER_CHECK
@FIND_BATTLER_BODY:
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @NEXT_BATTLER
	LDA BATTLERS_TABLE,X
	CMP @LOCAL03
	BNE @NEXT_BATTLER
	LDA BATTLERS_TABLE+battler::npc_id,X
	AND #$00FF
	BNE @NEXT_BATTLER
	LDA BATTLERS_TABLE+battler::action_item_slot,X
	AND #$00FF
	STA @LOCAL01
@NEXT_BATTLER:
	LDA @LOCAL02
	INC
	STA @LOCAL02
@FIND_BATTLER_CHECK:
	CMP #TOTAL_PARTY_COUNT
	BCC @FIND_BATTLER_BODY
	STZ @LOCAL00
	JMP @SLOT_LOOP_CHECK
@CHECK_ITEM_SLOT:
	LDA @LOCAL00
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	CMP @LOCAL01
	BEQL @NEXT_SLOT
	LDA @LOCAL03
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAY
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @LOCAL00
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	STA @VIRTUAL04
	STA @LOCALM2
	LDA @VIRTUAL04
.ELSE
	STY @LOCAL02
	TYA
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @LOCAL00
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	STA @VIRTUAL04
.ENDIF
	BEQL @NEXT_SLOT
	LOADPTR ITEM_CONFIGURATION_TABLE, @VIRTUAL06
	LDA @VIRTUAL04
.IF .DEFINED(JPN)
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	TAX
	CLC
	ADC #item::cost
	PHA
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	PLA
.ELSE
	LDY #.SIZEOF(item)
	JSL MULT168
	TAX
	CLC
	ADC #item::cost
	MOVE_INTY @VIRTUAL06, @VIRTUAL0A
.ENDIF
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	BEQ @NEXT_SLOT
	CMP #290
	BCS @NEXT_SLOT
	TXA
	CLC
	ADC #item::type
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	AND #$0030
	CMP #$0020
	BNE @NEXT_SLOT
.IF .DEFINED(USA)
	LDY @LOCAL02
.ENDIF
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::WEAPON,Y
	AND #$00FF
	CMP @VIRTUAL02
	BEQ @NEXT_SLOT
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,Y
	AND #$00FF
	CMP @VIRTUAL02
	BEQ @NEXT_SLOT
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::ARMS,Y
	AND #$00FF
	CMP @VIRTUAL02
	BEQ @NEXT_SLOT
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,Y
	AND #$00FF
	CMP @VIRTUAL02
	BEQ @NEXT_SLOT
.IF .DEFINED(JPN)
	LDA @LOCALM2
	STA @VIRTUAL04
.ELSE
	LDA @VIRTUAL04
.ENDIF
	SEP #PROC_FLAGS::ACCUM8
	LDY #.LOWORD(STEALABLE_ITEM_CANDIDATES)
	STA (@LOCAL05),Y
	REP #PROC_FLAGS::ACCUM8
	INC @LOCAL05
@NEXT_SLOT:
	INC @LOCAL00
@SLOT_LOOP_CHECK:
	LDA @LOCAL00
	CMP #.SIZEOF(char_struct::items)
	BCCL @CHECK_ITEM_SLOT
@NEXT_PARTY_MEMBER:
	INC @LOCAL04
@PARTY_LOOP_CHECK:
	LDA @LOCAL04
	CMP #TOTAL_PARTY_COUNT
	BCCL @PROCESS_PARTY_MEMBER
	LDA @LOCAL05
	END_C_FUNCTION

