
FIND_NEXT_MENU_OPTION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @VIRTUAL04
	STX @LOCAL06
	STA @LOCAL05
	LDX @PARAM04
	STX @LOCAL04
	LDY @PARAM03
	STY @LOCAL03
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	STA @LOCAL02
	LDA @LOCAL05
	STA @VIRTUAL02
	STA @LOCAL01
	LDY @LOCAL06
	STY @LOCAL00
	LDA @VIRTUAL04
	BEQL @HSEARCH_START
	TYA
	CLC
	ADC @VIRTUAL04
	TAY
	STY @LOCAL00
	BRA @VSEARCH_SAME_COL_CHECK
@VSEARCH_SAME_COL:
	TYX
	LDA @LOCAL01
	STA @VIRTUAL02
	JSL GET_MENU_TILE_AT_POSITION
	CMP #$002F
	BEQL @FOUND
	LDY @LOCAL00
	TYA
	CLC
	ADC @VIRTUAL04
	TAY
	STY @LOCAL00
@VSEARCH_SAME_COL_CHECK:
	LDY #window_stats::height
	LDA (@LOCAL02),Y
	LSR
	STA @VIRTUAL02
	LDY @LOCAL00
	TYA
	CMP @VIRTUAL02
	BCC @VSEARCH_SAME_COL
	LDA @VIRTUAL04
	CLC
	ADC @LOCAL06
	TAY
	STY @LOCAL00
	BRA @VSEARCH_LEFT_ROW_CHECK
@VSEARCH_LEFT_OUTER:
	LDA @LOCAL01
	STA @VIRTUAL02
	DEC
	STA @VIRTUAL02
	BRA @VSEARCH_LEFT_CHECK
@VSEARCH_LEFT:
	LDY @LOCAL00
	TYX
	LDA @VIRTUAL02
	JSL GET_MENU_TILE_AT_POSITION
	CMP #$002F
	BEQL @FOUND
	LDA @VIRTUAL02
	DEC
	STA @VIRTUAL02
@VSEARCH_LEFT_CHECK:
	LDY #window_stats::width
	LDA @VIRTUAL02
	CMP (@LOCAL02),Y
	BCC @VSEARCH_LEFT
	LDA @LOCAL05
	STA @VIRTUAL02
	STA @LOCAL01
	LDY @LOCAL00
	TYA
	CLC
	ADC @VIRTUAL04
	TAY
	STY @LOCAL00
@VSEARCH_LEFT_ROW_CHECK:
	LDY #window_stats::height
	LDA (@LOCAL02),Y
	LSR
	STA @VIRTUAL02
	LDY @LOCAL00
	TYA
	CMP @VIRTUAL02
	BCC @VSEARCH_LEFT_OUTER
	LDX @LOCAL05
	LDA @VIRTUAL04
	CLC
	ADC @LOCAL06
	TAY
	STY @LOCAL00
	BRA @VSEARCH_RIGHT_ROW_CHECK
@VSEARCH_RIGHT_OUTER:
	STX @VIRTUAL02
	INC @VIRTUAL02
	BRA @VSEARCH_RIGHT_CHECK
@VSEARCH_RIGHT:
	LDY @LOCAL00
	TYX
	LDA @VIRTUAL02
	JSL GET_MENU_TILE_AT_POSITION
	CMP #$002F
	BEQL @FOUND
	INC @VIRTUAL02
@VSEARCH_RIGHT_CHECK:
	LDY #window_stats::width
	LDA @VIRTUAL02
	CMP (@LOCAL02),Y
	BCC @VSEARCH_RIGHT
	LDX @LOCAL05
	LDY @LOCAL00
	TYA
	CLC
	ADC @VIRTUAL04
	TAY
	STY @LOCAL00
@VSEARCH_RIGHT_ROW_CHECK:
	LDY #window_stats::height
	LDA (@LOCAL02),Y
	LSR
	STA @VIRTUAL02
	LDY @LOCAL00
	TYA
	CMP @VIRTUAL02
	BCC @VSEARCH_RIGHT_OUTER
	JMP @NOT_FOUND
@HSEARCH_START:
	LDA @VIRTUAL02
	CLC
	ADC @LOCAL03
	STA @VIRTUAL02
	BRA @HSEARCH_SAME_ROW_CHECK
@HSEARCH_SAME_ROW:
	LDY @LOCAL00
	TYX
	LDA @VIRTUAL02
	JSL GET_MENU_TILE_AT_POSITION
	CMP #$002F
	BEQL @FOUND
	LDA @VIRTUAL02
	CLC
	ADC @LOCAL03
	STA @VIRTUAL02
@HSEARCH_SAME_ROW_CHECK:
	LDY #window_stats::width
	LDA @VIRTUAL02
	CMP (@LOCAL02),Y
	BCC @HSEARCH_SAME_ROW
	LDA @LOCAL05
	CLC
	ADC @LOCAL03
	STA @VIRTUAL02
	BRA @HSEARCH_UP_COL_CHECK
@HSEARCH_UP_OUTER:
	LDY @LOCAL00
	DEY
	STY @LOCAL00
	BRA @HSEARCH_UP_CHECK
@HSEARCH_UP:
	TYX
	LDA @VIRTUAL02
	JSL GET_MENU_TILE_AT_POSITION
	CMP #$002F
	BEQ @FOUND
	LDY @LOCAL00
	DEY
	STY @LOCAL00
@HSEARCH_UP_CHECK:
	LDY #window_stats::height
	LDA (@LOCAL02),Y
	LSR
	STA @VIRTUAL04
	LDY @LOCAL00
	TYA
	CMP @VIRTUAL04
	BCC @HSEARCH_UP
	LDY @LOCAL06
	STY @LOCAL00
	LDA @VIRTUAL02
	CLC
	ADC @LOCAL03
	STA @VIRTUAL02
@HSEARCH_UP_COL_CHECK:
	LDY #window_stats::width
	LDA @VIRTUAL02
	CMP (@LOCAL02),Y
	BCC @HSEARCH_UP_OUTER
	LDX @LOCAL06
	LDA @LOCAL05
	CLC
	ADC @LOCAL03
	STA @VIRTUAL02
	BRA @HSEARCH_DOWN_COL_CHECK
@HSEARCH_DOWN_OUTER:
	TXY
	INY
	STY @LOCAL00
	BRA @HSEARCH_DOWN_CHECK
@HSEARCH_DOWN:
	TYX
	LDA @VIRTUAL02
	JSL GET_MENU_TILE_AT_POSITION
	CMP #$002F
	BEQ @FOUND
	LDY @LOCAL00
	INY
	STY @LOCAL00
@HSEARCH_DOWN_CHECK:
	LDY #window_stats::height
	LDA (@LOCAL02),Y
	LSR
	STA @VIRTUAL04
	LDY @LOCAL00
	TYA
	CMP @VIRTUAL04
	BCC @HSEARCH_DOWN
	LDX @LOCAL06
	LDA @VIRTUAL02
	CLC
	ADC @LOCAL03
	STA @VIRTUAL02
@HSEARCH_DOWN_COL_CHECK:
	LDY #window_stats::width
	LDA @VIRTUAL02
	CMP (@LOCAL02),Y
	BCC @HSEARCH_DOWN_OUTER
@NOT_FOUND:
	LDA #$FFFF
	BRA @RETURN
@FOUND:
	LDA @LOCAL04
	CMP #$FFFF
	BEQ @PLAY_SOUND
	LDA @LOCAL04
	JSL PLAY_SOUND
@PLAY_SOUND:
	LDY @LOCAL00
	TYA
	XBA
	AND #$FF00
	CLC
	ADC @VIRTUAL02
@RETURN:
	END_C_FUNCTION
