
FIND_FIRST_UNCONSCIOUS_PARTY_SLOT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA #0
	STA @LOCAL00
	BRA @LOOP_CHECK
@CHECK_MEMBER:
	INC
	STA @LOCAL00
@LOOP_CHECK:
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_order,X
.ELSE
	TAX
	LDA GAME_STATE + game_state::party_order,X
.ENDIF
	AND #$00FF
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::afflictions,X
	AND #$00FF
	CMP #1
	BEQ @DONE
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	STA @VIRTUAL02
	LDA @LOCAL00
	CMP @VIRTUAL02
	BCC @CHECK_MEMBER
@DONE:
	LDA @LOCAL00
	END_C_FUNCTION
