
FIND_FIRST_ALIVE_PARTY_MEMBER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDY #0
	STY @LOCAL01
	BRA @LOOP_CHECK
@CHECK_MEMBER:
.IF .DEFINED(JPN)
	TYA
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_order,X
.ELSE
	LDA GAME_STATE + game_state::party_order,Y
.ENDIF
	AND #$00FF
	STA @LOCAL00
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::afflictions,X
	AND #$00FF
	TAX
	CPX #1
	BEQ @IS_DEAD
	CPX #2
	BEQ @IS_DEAD
	LDA @LOCAL00
	BRA @RETURN
@IS_DEAD:
	LDY @LOCAL01
	INY
	STY @LOCAL01
@LOOP_CHECK:
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	STA @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BCC @CHECK_MEMBER
	LDA #0
@RETURN:
	END_C_FUNCTION
