
FIND_NEXT_ENEMY_LETTER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int
	END_STACK_VARS
	TAY
	STY @LOCAL02
	SEP #PROC_FLAGS::ACCUM8
	STZ_BADOPT @LOCAL00
	LDX #26
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(USED_ENEMY_LETTERS)
	JSL MEMSET16
	LDA #0
	STA @LOCAL01
	BRA @LOOP_CHECK
@LOOP_BODY:
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE + battler::consciousness,X
	AND #$00FF
	BEQ @NEXT_BATTLER
	LDA BATTLERS_TABLE + battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BNE @NEXT_BATTLER
	LDY @LOCAL02
	TYA
	CMP BATTLERS_TABLE + battler::enemy_type_id,X
	BNE @NEXT_BATTLER
	LDA BATTLERS_TABLE + battler::the_flag,X
	AND #$00FF
	TAX
	DEX
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA USED_ENEMY_LETTERS,X
@NEXT_BATTLER:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	INC
	STA @LOCAL01
@LOOP_CHECK:
	CMP #BATTLER_COUNT
	BCC @LOOP_BODY
	LDX #0
	BRA @FIND_CHECK
@CHECK_LETTER:
	LDA USED_ENEMY_LETTERS,X
	AND #$00FF
	BNE @FIND_NEXT
	TXA
	SEP #PROC_FLAGS::ACCUM8
	INC
	BRA @RETURN
@FIND_NEXT:
	INX
@FIND_CHECK:
	CPX #26
	BCC @CHECK_LETTER
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
@RETURN:
	END_C_FUNCTION
