
FIND_TARGETTABLE_NPC:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	JSL RAND
	AND #$0003
	BNE @SEARCH_START
	LDA #$0000
	BRA @RETURN
@SEARCH_START:
	LDA #$0000
	STA @LOCAL01
	BRA @LOOP_PARTY_CHECK
@CHECK_PARTY_MEMBER:
	LDA_STRUCT_MEMBER GAME_STATE, game_state::party_members
	AND #$00FF
	TAY
	STY @LOCAL00
	CPY #PARTY_MEMBER::POKEY
	BCC @INVALID_PARTY_TARGET
	TYA
	ASL
	TAX
	LDA f:NPC_AI_TABLE,X
	AND #$00FF
	AND #NPC_FLAGS::UNTARGETTABLE
	BEQ @INVALID_PARTY_TARGET
	LDA #$0000
	STA @LOCAL01
	BRA @LOOP_BATTLERS_CHECK
@CHECK_BATTLER:
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @NEXT_BATTLER
	LDY @LOCAL00
	STY $02
	LDA BATTLERS_TABLE+battler::npc_id,X
	AND #$00FF
	CMP $02
	BNE @NEXT_BATTLER
	LDA @LOCAL01
	INC
	BRA @RETURN
@NEXT_BATTLER:
	LDA @LOCAL01
	INC
	STA @LOCAL01
@LOOP_BATTLERS_CHECK:
	CMP #.SIZEOF(game_state::party_members)
	BCC @CHECK_BATTLER
@INVALID_PARTY_TARGET:
	LDA @LOCAL01
	INC
	STA @LOCAL01
@LOOP_PARTY_CHECK:
	CMP #.SIZEOF(game_state::party_members)
	BCC @CHECK_PARTY_MEMBER
	LDA #$0000
@RETURN:
	END_C_FUNCTION
