
GET_EQUIP_WINDOW_TEXT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;NEAR char*
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	STX @VIRTUAL02
	TAY
	LDA __BSS_START__,Y
	AND #$00FF
	BEQ @CHECK_OFFSET_3
	LDA #0
	STA @LOCAL00
	BRA @FOUND_SLOT
@CHECK_OFFSET_3:
	TYX
	INX
	INX
	INX
	LDA __BSS_START__,X
	AND #$00FF
	BEQ @SCAN_REMAINING
	TXY
	LDA #3
	STA @LOCAL00
	BRA @FOUND_SLOT
@SCAN_REMAINING:
	INY
	LDA #1
	STA @LOCAL00
	BRA @CHECK_SCAN_LIMIT
@CHECK_SCAN_BODY:
	LDA __BSS_START__,Y
	AND #$00FF
	BNE @FOUND_SLOT
	LDA @LOCAL00
	INC
	STA @LOCAL00
	INY
@CHECK_SCAN_LIMIT:
	CMP #7
	BCC @CHECK_SCAN_BODY
	LDA @VIRTUAL02
	BEQ @RETURN_NONE
	LDA #7
	BRA @RETURN
@RETURN_NONE:
	LDA #32
	BRA @RETURN
@FOUND_SLOT:
	LDA @VIRTUAL02
	BEQ @LOOKUP_TABLE_2
	LDA __BSS_START__,Y
	AND #$00FF
	DEC
	ASL
	STA @VIRTUAL02
	LDA @LOCAL00
	OPTIMIZED_MULT @VIRTUAL04, 14
	CLC
	ADC @VIRTUAL02
	TAX
	LDA f:STATUS_EQUIP_WINDOW_TEXT,X
	BRA @RETURN
@LOOKUP_TABLE_2:
	LDA __BSS_START__,Y
	AND #$00FF
	DEC
	ASL
	STA @VIRTUAL02
	LDA @LOCAL00
	OPTIMIZED_MULT @VIRTUAL04, 14
	CLC
	ADC @VIRTUAL02
	TAX
	LDA f:STATUS_EQUIP_WINDOW_TEXT_2,X
@RETURN:
	END_C_FUNCTION
