
HEAL_CHARACTER_HP:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @VIRTUAL02
	TAX
	BEQL @RETURN
	TXA
	DEC
	STA @VIRTUAL04
	CPY #0
	BNE @APPLY_HEAL
	MOVE_INT1632 @VIRTUAL02, @VIRTUAL0A
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::max_hp,X
	STORE_INT1632 @VIRTUAL06
	JSL MULT32
	MOVE_INT_CONSTANT 100, @VIRTUAL0A
	JSL DIVISION32
	LDA @VIRTUAL06
	STA @VIRTUAL02
@APPLY_HEAL:
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::current_hp_target
	TAX
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL02
	STA __BSS_START__,X
	LDA @LOCAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::current_hp
	TAX
	LDA __BSS_START__,X
	BNE @CLAMP_TO_MAX
	LDA #1
	STA __BSS_START__,X
@CLAMP_TO_MAX:
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL01
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::current_hp_target
	TAX
	STX @LOCAL00
	LDA @LOCAL01
	TAX
	LDA PARTY_CHARACTERS+char_struct::max_hp,X
	STA @LOCAL02
	STA @VIRTUAL02
	LDX @LOCAL00
	LDA __BSS_START__,X
	CMP @VIRTUAL02
	BLTEQ @RETURN
	LDA @LOCAL02
	STA __BSS_START__,X
@RETURN:
	END_C_FUNCTION
