
INFLICT_STATUS_BATTLE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;NEAR battler* target
	STACK_RESERVE_PARAM_INT16 ;int statusGroup
	STACK_RESERVE_PARAM_INT16 ;int status
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	STX @VIRTUAL02
	TAX
	STX @LOCAL00
	LDA a:battler::npc_id,X
	AND #$00FF
	BEQ @NOT_NPC
	LDA #0
	BRA @RETURN
@NOT_NPC:
	TXA
	CLC
	ADC @VIRTUAL02
	TAX
	LDA a:battler::afflictions,X
	AND #$00FF
	BEQ @APPLY_STATUS
	STY @VIRTUAL04
	CMP @VIRTUAL04
	BLTEQ @ALREADY_ACTIVE
@APPLY_STATUS:
	LDX @LOCAL00
	TXA
	CLC
	ADC @VIRTUAL02
	TAX
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA a:battler::afflictions,X
	REP #PROC_FLAGS::ACCUM8
	LDA #1
	BRA @RETURN
@ALREADY_ACTIVE:
	LDA #0
@RETURN:
	END_C_FUNCTION
