
INIT_OVAL_WINDOW:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAY
	STY @LOCAL00
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA ACTIVE_OVAL_WINDOW
	LDX #0
	REP #PROC_FLAGS::ACCUM8
	TXA
	JSL INIT_SWIRL_EFFECT
	SEP #PROC_FLAGS::ACCUM8
	LDA #19
	STA SWIRL_MASK_SETTINGS
	LDY @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	TYA
	CMP #2
	BEQ @BATTLE_VARIANT
	CMP #1
	BEQ @VARIANT_OPEN
	BRA @STANDARD_OPEN
@BATTLE_VARIANT:
	MOVE_INT_CONSTANT OVAL_WINDOW_BATTLE_VARIANT, LOADED_OVAL_WINDOW
	BRA @RETURN
@VARIANT_OPEN:
	MOVE_INT_CONSTANT OVAL_WINDOW_VARIANT_OPEN, LOADED_OVAL_WINDOW
	BRA @RETURN
@STANDARD_OPEN:
	MOVE_INT_CONSTANT OVAL_WINDOW_STANDARD_OPEN, LOADED_OVAL_WINDOW
@RETURN:
	END_C_FUNCTION
