
INIT_BATTLE_SCRIPTED:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int character
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STA @LOCAL01
	STA CURRENT_BATTLE_GROUP
	LOADPTR BTL_ENTRY_PTR_TABLE, @VIRTUAL0A
	LDA @LOCAL01
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	STZ ENEMIES_IN_BATTLE
	BRA @READ_ENTRY
@READ_ENEMY:
	LDA ENEMIES_IN_BATTLE
	ASL
	TAX
	LDY #1
	LDA [@VIRTUAL06],Y
	STA ENEMIES_IN_BATTLE_IDS,X
	INC ENEMIES_IN_BATTLE
@DECREMENT_COUNT:
	LDA @LOCAL00
	TAX
	DEC
	STA @LOCAL00
	CPX #0
	BNE @READ_ENEMY
	LDA #3
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
@READ_ENTRY:
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	STA @LOCAL00
	CMP #$00FF
	BNE @DECREMENT_COUNT
	LDA #$FFFF
	STA BATTLE_MODE
	JSL BATTLE_SWIRL_SEQUENCE
	BRA @CHECK_SWIRL
@WAIT_SWIRL:
	JSL WAIT_UNTIL_NEXT_FRAME
	JSL UPDATE_SWIRL_EFFECT
@CHECK_SWIRL:
	JSL IS_BATTLE_SWIRL_ACTIVE
	CMP #0
	BNE @WAIT_SWIRL
	JSL INIT_BATTLE_COMMON
	TAX
	STX @LOCAL01
	LDA PSI_TELEPORT_DESTINATION
	BNE @TELEPORT
	CPX #0
	BEQ @RELOAD_MAP
	LDA #1
	BRA @RETURN
@RELOAD_MAP:
	JSL RELOAD_MAP
	LDX #1
	TXA
	JSL FADE_IN
	BRA @POST_BATTLE
@TELEPORT:
	JSL TELEPORT_MAINLOOP
	LDX @LOCAL01
	BEQ @POST_BATTLE
	LDA #1
	BRA @RETURN
@POST_BATTLE:
	JSL RENDER_AND_DISABLE_ENTITIES
	LDA CURRENT_BATTLE_GROUP
	CMP #ENEMY_GROUP::BOSS_START
	BCS @SET_RESULT
	LDA #120
	STA PLAYER_INTANGIBILITY_FRAMES
@SET_RESULT:
	LDA #0
@RETURN:
	END_C_FUNCTION
