
INIT_BATTLE_OVERWORLD:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA BATTLE_MODE
	BEQL @DONE
	LDA DEBUG
	BEQ @CHECK_INSTANT_WIN
	JSL CHECK_DEBUG_EXIT_BUTTON
	CMP #$FFFF
	BEQ @RESET_ENTITIES
@CHECK_INSTANT_WIN:
	JSL INSTANT_WIN_CHECK
	CMP #0
	BEQ @INIT_COMMON
	JSL INSTANT_WIN_HANDLER
	STZ BATTLE_MODE
	BRA @RESET_ENTITIES
@INIT_COMMON:
	JSL INIT_BATTLE_COMMON
	TAX
	STX @LOCAL01
	JSL REFRESH_PARTY_ENTITIES
	STZ OVERWORLD_STATUS_SUPPRESSION
	LDA PSI_TELEPORT_DESTINATION
	BNE @TELEPORT
	LDX @LOCAL01
	BEQ @RELOAD_MAP
	LDA DEBUG
	BEQ @DONE
	JSL DEBUG_CHECK_VIEW_CHARACTER_MODE
	CMP #0
	BNE @DONE
@RELOAD_MAP:
	JSL RELOAD_MAP
	LDX #1
	TXA
	JSL FADE_IN
	BRA @RESET_ENTITIES
@TELEPORT:
	JSL TELEPORT_MAINLOOP
@RESET_ENTITIES:
	LDA #0
	STA @LOCAL00
	BRA @RESET_ENTITY_LOOP_CHECK
@RESET_ENTITY:
	ASL
	TAX
	LDA #ENTITY_COLLISION_NO_OBJECT
	STA ENTITY_COLLIDED_OBJECTS,X
	STZ ENTITY_PATHFINDING_STATES,X
	TXA
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAX
	LDA __BSS_START__,X
	AND #$7FFF
	STA __BSS_START__,X
	LDA @LOCAL00
	INC
	STA @LOCAL00
@RESET_ENTITY_LOOP_CHECK:
	CMP #23
	BNE @RESET_ENTITY
	STZ OVERWORLD_STATUS_SUPPRESSION
	JSL ENABLE_ALL_ENTITIES
	LDA #120
	STA PLAYER_INTANGIBILITY_FRAMES
	LDA #$FFFF
	STA TOUCHED_ENEMY
@DONE:
	END_C_FUNCTION
