
INSTANT_WIN_CHECK:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA BATTLE_INITIATIVE
	CMP #INITIATIVE::ENEMIES_FIRST
	BNE @NOT_ENEMIES_FIRST
	LDA #0
	JMP @RETURN
@NOT_ENEMIES_FIRST:
	STZ @LOCAL09
	STZ @LOCAL08
	LDA #$FFFF
	STA @VIRTUAL02
	STA @LOCAL07
	LDA @VIRTUAL02
	STA @VIRTUAL04
	LDY #0
	STY @LOCAL06
	JMP @PARTY_LOOP_CHECK
@SCAN_PARTY_MEMBER:
.IF .DEFINED(JPN)
	TYA
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
.ELSE
	LDA GAME_STATE + game_state::party_members,Y
.ENDIF
	AND #$00FF
	TAX
	STX @LOCAL05
	CPX #1
	BCCL @NEXT_PARTY_MEMBER
	CPX #4
	BGTL @NEXT_PARTY_MEMBER
	TXA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::speed,X
	AND #$00FF
	CMP @VIRTUAL04
	BCS @CHECK_OFFENSE
	STA @VIRTUAL04
@CHECK_OFFENSE:
	LDX @LOCAL05
	TXA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::offense,X
	AND #$00FF
	CMP @VIRTUAL02
	BCS @CHECK_AFFLICTIONS
	STA @VIRTUAL02
	STA @LOCAL07
@CHECK_AFFLICTIONS:
	LDX @LOCAL05
	TXA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL04
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::afflictions
	TAX
	LDA a:STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	STA @LOCAL03
	CMP #STATUS_0::UNCONSCIOUS
	BEQ @NEXT_PARTY_MEMBER
	LDA @LOCAL03
	CMP #STATUS_0::DIAMONDIZED
	BEQ @NEXT_PARTY_MEMBER
	LDA @LOCAL03
	CMP #STATUS_0::PARALYZED
	BEQ @NEXT_PARTY_MEMBER
	LDA @LOCAL03
	CMP #STATUS_0::NAUSEOUS
	BEQ @NEXT_PARTY_MEMBER
	LDA @LOCAL03
	CMP #STATUS_0::POISONED
	BEQ @NEXT_PARTY_MEMBER
	LDA @LOCAL03
	CMP #STATUS_0::SUNSTROKE
	BEQ @NEXT_PARTY_MEMBER
	LDA @LOCAL03
	CMP #STATUS_0::COLD
	BEQ @NEXT_PARTY_MEMBER
	LDA a:STATUS_GROUP::PERSISTENT_HARDHEAL,X
	AND #$00FF
	TAX
	CPX #STATUS_1::MUSHROOMIZED
	BEQ @NEXT_PARTY_MEMBER
	CPX #STATUS_1::POSSESSED
	BEQ @NEXT_PARTY_MEMBER
	LDA @LOCAL08
	ASL
	PHA
	LDA @LOCAL04
	TAX
	LDA PARTY_CHARACTERS+char_struct::offense,X
	AND #$00FF
	PLX
	STA INSTANT_WIN_SORTED_OFFENSE,X
	INC @LOCAL08
@NEXT_PARTY_MEMBER:
	LDY @LOCAL06
	INY
	STY @LOCAL06
@PARTY_LOOP_CHECK:
	CPY #6
	BCCL @SCAN_PARTY_MEMBER
	LDA ENEMIES_IN_BATTLE
	CMP @LOCAL08
	BLTEQ @ENOUGH_MEMBERS
	LDA #0
	JMP @RETURN
@ENOUGH_MEMBERS:
	LDA BATTLE_INITIATIVE
	BNEL @PARTY_FIRST_PATH
	LDA #0
	STA @LOCAL05
	BRA @ENEMY_SPEED_CHECK
@SCAN_ENEMY_SPEED:
	ASL
	TAX
	LDA ENEMIES_IN_BATTLE_IDS,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::speed
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	AND #$00FF
	TAX
	CPX @LOCAL09
	BLTEQ @NEXT_ENEMY_SPEED
	STX @LOCAL09
@NEXT_ENEMY_SPEED:
	LDA @LOCAL05
	INC
	STA @LOCAL05
@ENEMY_SPEED_CHECK:
	CMP ENEMIES_IN_BATTLE
	BCC @SCAN_ENEMY_SPEED
	LDA @VIRTUAL04
	CMP @LOCAL09
	BCS @SPEED_CHECK_PASSED
	LDA #0
	JMP @RETURN
@SPEED_CHECK_PASSED:
	LDA #0
	STA @LOCAL03
	BRA @NORMAL_ENEMY_CHECK
@CHECK_OFFENSE_VS_ENEMY:
	LOADPTR ENEMY_CONFIGURATION_TABLE, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	LDA @LOCAL03
	ASL
	TAX
	LDA ENEMIES_IN_BATTLE_IDS,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	TAX
	CLC
	ADC #enemy_data::defense
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	STA @VIRTUAL02
	TXA
	CLC
	ADC #enemy_data::hp
	MOVE_INTX @LOCAL02, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL04
	LDA @LOCAL07
	STA @VIRTUAL02
	ASL
	CMP @VIRTUAL04
	BCS @NEXT_NORMAL_ENEMY
	LDA #0
	JMP @RETURN
@NEXT_NORMAL_ENEMY:
	LDA @LOCAL03
	INC
	STA @LOCAL03
@NORMAL_ENEMY_CHECK:
	CMP ENEMIES_IN_BATTLE
	BCC @CHECK_OFFENSE_VS_ENEMY
	LDA #1
	JMP @RETURN
@PARTY_FIRST_PATH:
	LDA #0
	STA @LOCAL03
	BRA @COLLECT_ENEMY_CHECK
@COLLECT_ENEMY_STATS:
	ASL
	TAY
	STY @LOCAL05
	LOADPTR ENEMY_CONFIGURATION_TABLE, @VIRTUAL06
	TYA
	CLC
	ADC #.LOWORD(ENEMIES_IN_BATTLE_IDS)
	TAX
	LDA __BSS_START__,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::hp
	MOVE_INTY @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	LDY @LOCAL05
	STA INSTANT_WIN_SORTED_HP,Y
	LDA __BSS_START__,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::defense
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	LDY @LOCAL05
	STA INSTANT_WIN_SORTED_DEFENSE,Y
	LDA @LOCAL03
	INC
	STA @LOCAL03
@COLLECT_ENEMY_CHECK:
	CMP ENEMIES_IN_BATTLE
	BCC @COLLECT_ENEMY_STATS
@START_SORT_OFFENSE:
	LDY #1
	LDX #0
	STX @LOCAL09
	BRA @SORT_OFFENSE_OUTER_CHECK
@SORT_OFFENSE_OUTER:
	TXA
	INC
	STA @LOCAL06
	BRA @SORT_OFFENSE_INNER_CHECK
@SORT_OFFENSE_INNER:
	LDX @LOCAL09
	TXA
	ASL
	CLC
	ADC #.LOWORD(INSTANT_WIN_SORTED_OFFENSE)
	STA @LOCAL07
	LDA (@LOCAL07)
	STA @LOCAL01
	LDA @LOCAL06
	ASL
	CLC
	ADC #.LOWORD(INSTANT_WIN_SORTED_OFFENSE)
	STA @VIRTUAL04
	LDX @VIRTUAL04
	LDA __BSS_START__,X
	STA @VIRTUAL02
	CMP @LOCAL01
	BLTEQ @SORT_OFFENSE_NEXT
	LDY #0
	LDA @VIRTUAL02
	STA (@LOCAL07)
	LDA @LOCAL01
	LDX @VIRTUAL04
	STA __BSS_START__,X
@SORT_OFFENSE_NEXT:
	LDA @LOCAL06
	INC
	STA @LOCAL06
@SORT_OFFENSE_INNER_CHECK:
	CMP @LOCAL08
	BCC @SORT_OFFENSE_INNER
	LDX @LOCAL09
	INX
	STX @LOCAL09
@SORT_OFFENSE_OUTER_CHECK:
	LDA @LOCAL08
	DEC
	STA @VIRTUAL02
	TXA
	CMP @VIRTUAL02
	BCC @SORT_OFFENSE_OUTER
	CPY #0
	BEQ @START_SORT_OFFENSE
@START_SORT_ENEMIES:
	LDA #1
	STA @LOCAL07
	LDA #0
	STA @VIRTUAL02
	BRA @SORT_ENEMIES_OUTER_CHECK
@SORT_ENEMIES_OUTER:
	LDY @VIRTUAL02
	INY
	BRA @SORT_ENEMIES_INNER_CHECK
@SORT_ENEMIES_INNER:
	LDA @VIRTUAL02
	ASL
	TAX
	CLC
	ADC #.LOWORD(INSTANT_WIN_SORTED_HP)
	STA @LOCAL05
	LDA (@LOCAL05)
	STA @LOCAL00
	TYA
	ASL
	STA @LOCAL09
	CLC
	ADC #.LOWORD(INSTANT_WIN_SORTED_HP)
	STA @LOCAL03
	LDA (@LOCAL03)
	STA @VIRTUAL04
	CMP @LOCAL00
	BLTEQ @SORT_ENEMIES_NEXT
	STZ @LOCAL07
	LDA @VIRTUAL04
	STA (@LOCAL05)
	LDA @LOCAL00
	STA (@LOCAL03)
	TXA
	CLC
	ADC #.LOWORD(INSTANT_WIN_SORTED_DEFENSE)
	STA @LOCAL05
	LDA (@LOCAL05)
	STA @VIRTUAL04
	LDA @LOCAL09
	CLC
	ADC #.LOWORD(INSTANT_WIN_SORTED_DEFENSE)
	TAX
	LDA __BSS_START__,X
	STA (@LOCAL05)
	LDA @VIRTUAL04
	STA __BSS_START__,X
@SORT_ENEMIES_NEXT:
	INY
@SORT_ENEMIES_INNER_CHECK:
	CPY ENEMIES_IN_BATTLE
	BCC @SORT_ENEMIES_INNER
	INC @VIRTUAL02
@SORT_ENEMIES_OUTER_CHECK:
	LDA ENEMIES_IN_BATTLE
	DEC
	STA @VIRTUAL04
	LDA @VIRTUAL02
	CMP @VIRTUAL04
	BCC @SORT_ENEMIES_OUTER
	LDA @LOCAL07
	BEQ @START_SORT_ENEMIES
	LDX #0
	STX @LOCAL09
	TXA
	STA @LOCAL06
	BRA @ATTACK_SIM_CHECK
@SIMULATE_ATTACKS:
	ASL
	TAX
	LDA INSTANT_WIN_SORTED_OFFENSE,X
	ASL
	STA @VIRTUAL04
	LDX @LOCAL09
	TXA
	ASL
	STA @LOCAL05
	CLC
	ADC #.LOWORD(INSTANT_WIN_SORTED_HP)
	STA @VIRTUAL02
	STA @LOCAL03
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	TAY
	STY @LOCAL04
	LDY #.LOWORD(INSTANT_WIN_SORTED_DEFENSE)
	LDA (@LOCAL05),Y
	STA @LOCAL05
	LDY @LOCAL04
	TYA
	CLC
	ADC @LOCAL05
	STA @VIRTUAL02
	LDA @VIRTUAL04
	CMP @VIRTUAL02
	BCS @ATTACK_SUFFICIENT
	LDA @VIRTUAL04
	SEC
	SBC @LOCAL05
	STA @VIRTUAL02
	TYA
	SEC
	SBC @VIRTUAL02
	LDX @LOCAL03
	STX @VIRTUAL02
	STA __BSS_START__,X
	BRA @NEXT_ATTACK_SIM
@ATTACK_SUFFICIENT:
	LDX @LOCAL09
	INX
	STX @LOCAL09
	CPX ENEMIES_IN_BATTLE
	BCC @NEXT_ATTACK_SIM
	LDA #1
	BRA @RETURN
@NEXT_ATTACK_SIM:
	LDA @LOCAL06
	INC
	STA @LOCAL06
@ATTACK_SIM_CHECK:
	CMP @LOCAL08
	BCC @SIMULATE_ATTACKS
	LDA #0
@RETURN:
	END_C_FUNCTION
