
INSTANT_WIN_PP_RECOVERY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #SFX::RECOVER_HP
	JSL PLAY_SOUND
	LDY #0
	STY @LOCAL05
	BRA @FLASH_LOOP_CHECK
@FLASH_ITERATION:
	LOADPTR BUFFER, @LOCAL00
	PROMOTENEARPTR PALETTES, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDA #.LOWORD(PALETTES)
	JSL MEMCPY24
	LDA #0
	STA @LOCAL04
	BRA @FILL_LOOP_CHECK
@FILL_PURPLE:
	ASL
	TAX
	LDA #$5D70 ; RGB (16, 11, 23), a kind of purple
	STA PALETTES,X
	LDA @LOCAL04
	INC
	STA @LOCAL04
@FILL_LOOP_CHECK:
	CMP #$0100
	BCC @FILL_PURPLE
	LDX #$FFFF
	LDA #12
	JSL PREPARE_PALETTE_FADE
	LDX #0
	STX @LOCAL04
	BRA @FADE_CHECK
@FADE_TICK:
	JSL UPDATE_MAP_PALETTE_ANIMATION
	JSL WAIT_UNTIL_NEXT_FRAME
	LDX @LOCAL04
	INX
	STX @LOCAL04
@FADE_CHECK:
	CPX #12
	BCC @FADE_TICK
	JSL FINALIZE_PALETTE_FADE
	LDY @LOCAL05
	INY
	STY @LOCAL05
@FLASH_LOOP_CHECK:
	CPY #2
	BCC @FLASH_ITERATION
	LDA #0
	STA @VIRTUAL02
	BRA @PARTY_LOOP_CHECK
@SCAN_PARTY_MEMBER:
.IF .DEFINED(JPN)
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
.ELSE
	LDX @VIRTUAL02
	LDA GAME_STATE + game_state::party_members,X
.ENDIF
	AND #$00FF
	TAX
	CPX #1
	BEQ @RECOVER_PP
	CPX #2
	BEQ @RECOVER_PP
	CPX #4
	BNE @NEXT_PARTY_MEMBER
@RECOVER_PP:
	TXA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL03
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::current_pp_target
	TAY
	LDA __BSS_START__,Y
	CLC
	ADC #20
	TAX
	STX @LOCAL02
	TXA
	STA __BSS_START__,Y
	LDA @LOCAL03
	TAX
	LDA PARTY_CHARACTERS+char_struct::max_pp,X
	STA @LOCAL03
	STA @VIRTUAL04
	LDX @LOCAL02
	TXA
	CMP @VIRTUAL04
	BLTEQ @NEXT_PARTY_MEMBER
	LDA @LOCAL03
	STA __BSS_START__,Y
@NEXT_PARTY_MEMBER:
	INC @VIRTUAL02
@PARTY_LOOP_CHECK:
	LDA @VIRTUAL02
	CMP #6
	BCC @SCAN_PARTY_MEMBER
	END_C_FUNCTION