
INSTANT_WIN_HANDLER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
.IF .DEFINED(JPN) ;what is this...?
	@LOCAL02ALT := @LOCAL03
	@LOCAL02ALT2 := @LOCAL04
	@LOCAL04ALT := @LOCAL02
.ELSE
	@LOCAL02ALT := @LOCAL02
	@LOCAL02ALT2 := @LOCAL02
	@LOCAL04ALT := @LOCAL04
.ENDIF
	STZ BATTLE_INITIATIVE
	LDA #MUSIC::SUDDEN_VICTORY
	JSL CHANGE_MUSIC
	JSL STOP_BATTLE_SWIRL
	LDX #0
	STX @LOCAL04
	BRA @FLASH_LOOP_CHECK
@FLASH_COLORS:
	LDA #$03E0
	JSR FILL_PALETTES_WITH_COLOR
	LDA #$001F
	JSR FILL_PALETTES_WITH_COLOR
	LDA #$7C00
	JSR FILL_PALETTES_WITH_COLOR
	LDX @LOCAL04
	INX
	STX @LOCAL04
@FLASH_LOOP_CHECK:
	CPX #2
	BCC @FLASH_COLORS
	LDA #0
	JSR FILL_PALETTES_WITH_COLOR
	LOADPTR BUFFER, @LOCAL00
	LOADPTR BUFFER + $2000, @LOCAL01
	LDA #$0200
	JSL MEMCPY24
	LDX #$FFFF
	LDA #6
	JSL PREPARE_PALETTE_FADE
	LDX #0
	STX @LOCAL03
	BRA @FADE_LOOP_CHECK
@FADE_STEP:
	JSL UPDATE_MAP_PALETTE_ANIMATION
	JSL WAIT_UNTIL_NEXT_FRAME
	LDX @LOCAL03
	INX
	STX @LOCAL03
@FADE_LOOP_CHECK:
	CPX #6
	BCC @FADE_STEP
	JSL FINALIZE_PALETTE_FADE
	JSL DISABLE_ALL_ENTITIES
	CREATE_WINDOW_FAR #WINDOW::TEXT_BATTLE
	STZ BATTLE_MONEY_SCRATCH
	LDA #0
	STA @LOCAL03
	BRA @MONEY_LOOP_CHECK
@SUM_ENEMY_MONEY:
	ASL
	TAX
	LDA ENEMIES_IN_BATTLE_IDS,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::money
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	CLC
	ADC BATTLE_MONEY_SCRATCH
	STA BATTLE_MONEY_SCRATCH
	LDA @LOCAL03
	INC
	STA @LOCAL03
@MONEY_LOOP_CHECK:
	CMP ENEMIES_IN_BATTLE
	BCC @SUM_ENEMY_MONEY
	LDY #.LOWORD(GAME_STATE) + game_state::unknownC4
	STY @LOCAL02ALT
	LDA BATTLE_MONEY_SCRATCH
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00 ;@LOCAL00 = @VIRTUAL06
	JSL DEPOSIT_INTO_ATM
	MOVE_INT @VIRTUAL06, @VIRTUAL0A ;@VIRTUAL0A = @VIRTUAL06
	LDY @LOCAL02ALT
	MOVE_INT_YPTRSRC 0, @VIRTUAL06 ;@VIRTUAL06 = game_state.unknownC4
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A ;@VIRTUAL06 += @VIRTUAL0A
	MOVE_INT_YPTRDEST @VIRTUAL06, 0 ;game_state.unknownC4 = @VIRTUAL06
	LDY #0
	STY @LOCAL03
	BRA @CLEAR_BATTLER_CHECK
@CLEAR_BATTLER:
	SEP #PROC_FLAGS::ACCUM8
	STZ_BADOPT @LOCAL00
	LDX #.SIZEOF(battler)
	REP #PROC_FLAGS::ACCUM8
	TYA
	TXY
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	JSL MEMSET16
	LDY @LOCAL03
	INY
	STY @LOCAL03
@CLEAR_BATTLER_CHECK:
	CPY #BATTLER_COUNT
	BCC @CLEAR_BATTLER
	LDY #0
	STY @LOCAL02ALT2
	BRA @PLAYER_INIT_CHECK
@INIT_PLAYER_BATTLER:
.IF .DEFINED(JPN)
	TYA
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
.ELSE
	LDA GAME_STATE + game_state::party_members,Y
.ENDIF
	AND #$00FF
	STA @LOCAL03
	BEQ @NEXT_PLAYER
	CMP #4
	BGT @NEXT_PLAYER
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	TAX
	LDA @LOCAL03
	JSL BATTLE_INIT_PLAYER_STATS
@NEXT_PLAYER:
	LDY @LOCAL02ALT2
	INY
	STY @LOCAL02ALT2
@PLAYER_INIT_CHECK:
	CPY #TOTAL_PARTY_COUNT
	BCC @INIT_PLAYER_BATTLER
	MOVE_INT_CONSTANT 0, BATTLE_EXP_SCRATCH
	LDA #0
	STA @LOCAL03
	BRA @EXP_LOOP_CHECK
@SUM_ENEMY_EXP:
	LOADPTR ENEMY_CONFIGURATION_TABLE, @VIRTUAL06
	LDA @LOCAL03
	ASL
	TAX
	LDA ENEMIES_IN_BATTLE_IDS,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::exp
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL0A
	MOVE_INT BATTLE_EXP_SCRATCH, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, BATTLE_EXP_SCRATCH
	LDA @LOCAL03
	INC
	STA @LOCAL03
@EXP_LOOP_CHECK:
	CMP ENEMIES_IN_BATTLE
	BCC @SUM_ENEMY_EXP
	LDA #0
	JSL COUNT_CHARS
	DEC
	STORE_INT1632 @VIRTUAL0A
	MOVE_INT BATTLE_EXP_SCRATCH, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, BATTLE_EXP_SCRATCH
	LDA #0
	JSL COUNT_CHARS
	STORE_INT1632 @VIRTUAL0A
	JSL DIVISION32
	MOVE_INT @VIRTUAL06, BATTLE_EXP_SCRATCH
	LOADPTR MSG_BTL_PLAYER_WIN_FORCE, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	LDY #.LOWORD(BATTLERS_TABLE)
	STY @LOCAL04ALT
	LDA #0
	STA @VIRTUAL02
	BRA @EXP_AWARD_CHECK
@AWARD_EXP:
	LDA a:battler::consciousness,Y
	AND #$00FF
	BEQ @NEXT_BATTLER_EXP
	LDA a:battler::ally_or_enemy,Y
	AND #$00FF
	BNE @NEXT_BATTLER_EXP
	LDA a:battler::npc_id,Y
	AND #$00FF
	BNE @NEXT_BATTLER_EXP
	LDA a:battler::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,Y
	AND #$00FF
	TAX
	CPX #STATUS_0::UNCONSCIOUS
	BEQ @NEXT_BATTLER_EXP
	CPX #STATUS_0::DIAMONDIZED
	BEQ @NEXT_BATTLER_EXP
	MOVE_INT BATTLE_EXP_SCRATCH, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #1
	LDA __BSS_START__,Y
	JSL GAIN_EXP
@NEXT_BATTLER_EXP:
	LDY @LOCAL04ALT
	TYA
	CLC
	ADC #.SIZEOF(battler)
	TAY
	STY @LOCAL04ALT
	INC @VIRTUAL02
@EXP_AWARD_CHECK:
	LDA @VIRTUAL02
	CMP #BATTLER_COUNT
	BCC @AWARD_EXP
	LDA ENEMIES_IN_BATTLE
	JSR RAND_LIMIT
	ASL
	TAX
	LDA ENEMIES_IN_BATTLE_IDS,X
	STA @LOCAL02ALT2
	LOADPTR ENEMY_CONFIGURATION_TABLE, @VIRTUAL06
	LDA @LOCAL02ALT2
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	STA @LOCAL03
	CLC
	ADC #enemy_data::item_dropped
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	STA ITEM_DROPPED
	LDA @LOCAL03
	CLC
	ADC #enemy_data::item_drop_rate
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	BEQ @DROP_RATE_0
	CMP #1
	BEQ @DROP_RATE_1
	CMP #2
	BEQ @DROP_RATE_2
	CMP #3
	BEQ @DROP_RATE_3
	CMP #4
	BEQ @DROP_RATE_4
	CMP #5
	BEQ @DROP_RATE_5
	CMP #6
	BEQ @DROP_RATE_6
	BRA @CHECK_DROPPED_ITEM
@DROP_RATE_0:
	JSL RAND
	AND #ITEM_RARITY_0
	BEQ @CHECK_DROPPED_ITEM
	STZ ITEM_DROPPED
	BRA @CHECK_DROPPED_ITEM
@DROP_RATE_1:
	JSL RAND
	AND #ITEM_RARITY_1
	BEQ @CHECK_DROPPED_ITEM
	STZ ITEM_DROPPED
	BRA @CHECK_DROPPED_ITEM
@DROP_RATE_2:
	JSL RAND
	AND #ITEM_RARITY_2
	BEQ @CHECK_DROPPED_ITEM
	STZ ITEM_DROPPED
	BRA @CHECK_DROPPED_ITEM
@DROP_RATE_3:
	JSL RAND
	AND #ITEM_RARITY_3
	BEQ @CHECK_DROPPED_ITEM
	STZ ITEM_DROPPED
	BRA @CHECK_DROPPED_ITEM
@DROP_RATE_4:
	JSL RAND
	AND #ITEM_RARITY_4
	BEQ @CHECK_DROPPED_ITEM
	STZ ITEM_DROPPED
	BRA @CHECK_DROPPED_ITEM
@DROP_RATE_5:
	JSL RAND
	AND #ITEM_RARITY_5
	BEQ @CHECK_DROPPED_ITEM
	STZ ITEM_DROPPED
	BRA @CHECK_DROPPED_ITEM
@DROP_RATE_6:
	JSL RAND
	AND #ITEM_RARITY_6
	BEQ @CHECK_DROPPED_ITEM
	STZ ITEM_DROPPED
@CHECK_DROPPED_ITEM:
	LDA ITEM_DROPPED
	BEQ @RESTORE_MUSIC
	SEP #PROC_FLAGS::ACCUM8
	LDA ITEM_DROPPED
	JSL SET_CURRENT_ITEM_FAR
	.A16
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_PRESENT
@RESTORE_MUSIC:
	JSL CLOSE_ALL_WINDOWS_AND_HIDE_HPPP
	LDA GAME_STATE+game_state::walking_style
	CMP #WALKING_STYLE::BICYCLE
	BNE @NOT_BICYCLE
	LDA #MUSIC::BICYCLE
	JSL CHANGE_MUSIC
	BRA @DONE
@NOT_BICYCLE:
	JSL UPDATE_MAP_MUSIC_AT_LEADER
@DONE:
	JSL ENABLE_ALL_ENTITIES
	END_C_FUNCTION
