
IS_ATTACKER_ENEMY:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDX CURRENT_ATTACKER
	LDA __BSS_START__+14,X
	AND #$00FF
	BNE @IS_ENEMY
	LDA #$0000
	BRA @RETURN
@IS_ENEMY:
	LDA #$0001
@RETURN:
	RTL
