
IS_BATTLE_SWIRL_ACTIVE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	LDA FRAMES_UNTIL_NEXT_SWIRL_UPDATE
	AND #$00FF
	BEQ @NOT_ACTIVE
	LDA SWIRL_LENGTH_PADDING
	AND #$00FF
	CLC
	SBC #4
	BRANCHLTEQS @NOT_ACTIVE
	LDA #1
	BRA @RETURN
@NOT_ACTIVE:
	LDA #0
@RETURN:
	END_C_FUNCTION
