
IS_ITEM_STEALABLE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int item
	END_STACK_VARS
	STA @VIRTUAL04
	JSR FIND_STEALABLE_ITEMS
	STA @VIRTUAL02
	LDA #0
	STA @LOCAL00
	BRA @LOOP_CHECK
@CHECK_ITEM:
	TAX
	LDA STEALABLE_ITEM_CANDIDATES,X
	AND #$00FF
	CMP @VIRTUAL04
	BNE @NEXT_ITEM
	LDA #1
	BRA @RETURN
@NEXT_ITEM:
	LDA @LOCAL00
	INC
	STA @LOCAL00
@LOOP_CHECK:
	CMP @VIRTUAL02
	BCC @CHECK_ITEM
	LDA #0
@RETURN:
	END_C_FUNCTION
