
IS_PSI_ANIMATION_ACTIVE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	LDA PSI_ANIMATION_STATE + psi_animation_state::time_until_next_frame
	AND #$00FF
	BNE @ACTIVE
	LDA FRAMES_UNTIL_NEXT_SWIRL_UPDATE
	AND #$00FF
	BEQ @NOT_ACTIVE
@ACTIVE:
	LDA #1
	BRA @RETURN
@NOT_ACTIVE:
	LDA #0
@RETURN:
	END_C_FUNCTION
