
KO_TARGET:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
.IF .DEFINED(JPN)
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
.ELSE
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
.ENDIF
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;NEAR battler* target
	END_STACK_VARS
	STA @VIRTUAL02
	STZ SKIP_DEATH_TEXT_AND_CLEANUP
	LDX @VIRTUAL02
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNEL @HANDLE_ENEMY_KO
	LDX @VIRTUAL02
	LDA a:battler::afflictions + STATUS_GROUP::PERSISTENT_HARDHEAL,X
	AND #$00FF
	CMP #STATUS_1::POSSESSED
	BNEL @SET_UNCONSCIOUS
	LDY #0
	STY @LOCAL07
	JMP @POSSESSION_CHECK
@CHECK_POSSESSION_LOOP:
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	STA @LOCAL06
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQL @POSSESSION_NEXT
	LDA @LOCAL06
	TAX
	LDA BATTLERS_TABLE+battler::npc_id,X
	AND #$00FF
	BNEL @POSSESSION_NEXT
	LDA @LOCAL06
	CLC
	ADC #.LOWORD(BATTLERS_TABLE) + battler::afflictions
	TAX
	LDA a:STATUS_GROUP::PERSISTENT_HARDHEAL,X
	AND #$00FF
	CMP #STATUS_1::POSSESSED
	BNE @POSSESSION_NEXT
	LDA @LOCAL06
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	STA @VIRTUAL04
	LDA @VIRTUAL02
	CMP @VIRTUAL04
	BNE @SET_UNCONSCIOUS
	LDA BATTLERS_TABLE+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)+battler::npc_id
	AND #$00FF
	CMP #ENEMY::TINY_LIL_GHOST
	BNE @SET_UNCONSCIOUS
	SEP #PROC_FLAGS::ACCUM8
	STZ BATTLERS_TABLE+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)+battler::consciousness
	BRA @SPAWN_GHOST_CHECK
@SPAWN_GHOST_LOOP:
	REP #PROC_FLAGS::ACCUM8
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @SPAWN_GHOST_NEXT
	LDA BATTLERS_TABLE+battler::npc_id,X
	AND #$00FF
	BNE @SPAWN_GHOST_NEXT
	TXA
	CLC
	ADC #.LOWORD(BATTLERS_TABLE) + battler::afflictions
	TAX
	LDA a:STATUS_GROUP::PERSISTENT_HARDHEAL,X
	AND #$00FF
	CMP #STATUS_1::POSSESSED
	BNE @SPAWN_GHOST_NEXT
	LDX #.LOWORD(BATTLERS_TABLE) + (.SIZEOF(battler) * 6)
	LDA #ENEMY::TINY_LIL_GHOST
	JSL BATTLE_INIT_ENEMY_STATS
	SEP #PROC_FLAGS::ACCUM8
	LDA #ENEMY::TINY_LIL_GHOST
	STA BATTLERS_TABLE+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)+battler::npc_id
	LDA #1
	STA BATTLERS_TABLE+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)+13
@SPAWN_GHOST_NEXT:
	LDY @LOCAL07
	INY
	STY @LOCAL07
@SPAWN_GHOST_CHECK:
	LDY @LOCAL07
	CPY #6
	BCC @SPAWN_GHOST_LOOP
	BRA @SET_UNCONSCIOUS
@POSSESSION_NEXT:
	LDY @LOCAL07
	INY
	STY @LOCAL07
@POSSESSION_CHECK:
	CPY #6
	BCCL @CHECK_POSSESSION_LOOP
@SET_UNCONSCIOUS:
	SEP #PROC_FLAGS::ACCUM8
	LDA #STATUS_0::UNCONSCIOUS
	LDX @VIRTUAL02
	STA a:battler::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	LDX @VIRTUAL02
	STZ a:battler::afflictions + STATUS_GROUP::SHIELD,X
	LDX @VIRTUAL02
	STZ a:battler::afflictions + STATUS_GROUP::HOMESICKNESS,X
	LDX @VIRTUAL02
	STZ a:battler::afflictions + STATUS_GROUP::CONCENTRATION,X
	LDX @VIRTUAL02
	STZ a:battler::afflictions + STATUS_GROUP::STRANGENESS,X
	LDX @VIRTUAL02
	STZ a:battler::afflictions + STATUS_GROUP::TEMPORARY,X
	LDX @VIRTUAL02
	STZ a:battler::afflictions + STATUS_GROUP::PERSISTENT_HARDHEAL,X
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
	CLC
	ADC #battler::npc_id
	TAX
	STX @LOCAL07
	LDA __BSS_START__,X
	AND #$00FF
	BEQL @HANDLE_CHAR_KO
	LOADPTR ENEMY_CONFIGURATION_TABLE, @VIRTUAL0A
	LDX @VIRTUAL02
	LDA a:battler::id,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::death_text_ptr
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_IN_BATTLE_TEXT
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::consciousness,X
	LDX @LOCAL07
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X ;battler::npc_id
	AND #$00FF
	TAX
	CPX #PARTY_MEMBER::TEDDY_BEAR
	BEQ @IS_TEDDY_BEAR
	CPX #PARTY_MEMBER::PLUSH_TEDDY_BEAR
	BNE @REASSIGN_FRONT_ROW
@IS_TEDDY_BEAR:
	LDA @VIRTUAL02
	CLC
	ADC #battler::row
	TAX
	STX @LOCAL05
	LDA __BSS_START__,X
	AND #$00FF
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_npc_1,X
.ELSE
	TAX
	LDA GAME_STATE+game_state::party_npc_1,X
.ENDIF
	AND #$00FF
	BEQL @DONE
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	LDX @VIRTUAL02
	STA a:battler::consciousness,X
	LDX @VIRTUAL02
	STZ a:battler::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	LDX @LOCAL05
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	AND #$00FF
	ASL
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_npc_1_hp,X
.ELSE
	TAX
	LDA GAME_STATE+game_state::party_npc_1_hp,X
.ENDIF
	LDX @VIRTUAL02
	STA a:battler::hp_target,X
	LDX @VIRTUAL02
	STA a:battler::hp,X
	LDX @LOCAL05
	LDA __BSS_START__,X
	AND #$00FF
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA a:game_state::party_npc_1,X
.ELSE
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA GAME_STATE+game_state::party_npc_1,X
.ENDIF
	LDX @VIRTUAL02
	STA a:battler::npc_id,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	ASL
	TAX
	INX
	LDA f:NPC_AI_TABLE,X
	AND #$00FF
	LDX @VIRTUAL02
	STA a:battler::id,X
	JMP @DONE
@REASSIGN_FRONT_ROW:
	LDA GAME_STATE+game_state::party_npc_1
	AND #$00FF
	BEQL @DONE
	LDX #.LOWORD(BATTLERS_TABLE)
	LDY #0
	BRA @FIND_FRONT_ROW_CHECK
@FIND_FRONT_ROW_LOOP:
	LDA a:battler::consciousness,X
	AND #$00FF
	BEQ @FIND_FRONT_ROW_NEXT
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @FIND_FRONT_ROW_NEXT
	SEP #PROC_FLAGS::ACCUM8
	LDA a:battler::npc_id,X
	CMP GAME_STATE+game_state::party_npc_1
	BNE @FIND_FRONT_ROW_NEXT
	STZ a:battler::row,X
	JMP @DONE
@FIND_FRONT_ROW_NEXT:
	REP #PROC_FLAGS::ACCUM8
	TXA
	CLC
	ADC #.SIZEOF(battler)
	TAX
	INY
@FIND_FRONT_ROW_CHECK:
	STY @VIRTUAL02
	LDA #BATTLER_COUNT
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @FIND_FRONT_ROW_LOOP
	JMP @DONE
@HANDLE_CHAR_KO:
	LDX @VIRTUAL02
	STZ a:battler::hp_target,X
	LDA @VIRTUAL02
	CLC
	ADC #battler::row
	TAX
	STX @LOCAL04
	LDA __BSS_START__,X
	AND #$00FF
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	STZ PARTY_CHARACTERS+char_struct::current_hp_target,X
	LDX @LOCAL04
	LDA __BSS_START__,X
	AND #$00FF
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA #1
	STA PARTY_CHARACTERS+char_struct::current_hp,X
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KIZETU_ON
	JMP @DONE
@HANDLE_ENEMY_KO:
	LDX @VIRTUAL02
	LDA a:battler::id,X
	CMP #ENEMY::GIYGAS_2
	BEQL @DONE
	CMP #ENEMY::GIYGAS_3
	BEQL @DONE
	CMP #ENEMY::GIYGAS_5
	BEQL @DONE
	CMP #ENEMY::GIYGAS_6
	BEQL @DONE
	LDA #1
	JSL COUNT_CHARS
	CMP #1
	BNEL @ACCUMULATE_REWARDS
	JSL RESET_HPPP_ROLLING
	LDA #0
	STA @LOCAL07
	BRA @ENSURE_HP_CHECK
@ENSURE_HP_LOOP:
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	STX @LOCAL05
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @ENSURE_HP_NEXT
	LDA BATTLERS_TABLE+battler::ally_or_enemy,X
	AND #$00FF
	BNE @ENSURE_HP_NEXT
	LDA BATTLERS_TABLE+battler::afflictions,X
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BEQ @ENSURE_HP_NEXT
	LDA BATTLERS_TABLE+battler::npc_id,X
	AND #$00FF
	BNE @ENSURE_HP_NEXT
	TXA
	CLC
	ADC #.LOWORD(BATTLERS_TABLE) + battler::row
	TAY
	STY @LOCAL06
	LDA __BSS_START__,Y
	AND #$00FF
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::current_hp,X
	BNE @ENSURE_HP_NEXT
	LDA #1
	LDX @LOCAL05
	STA BATTLERS_TABLE+battler::hp_target,X
	LDY @LOCAL06
	LDA __BSS_START__,Y
	AND #$00FF
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA #1
	STA PARTY_CHARACTERS+char_struct::current_hp_target,X
@ENSURE_HP_NEXT:
	LDA @LOCAL07
	INC
	STA @LOCAL07
@ENSURE_HP_CHECK:
	CMP #TOTAL_PARTY_COUNT
	BCC @ENSURE_HP_LOOP
@ACCUMULATE_REWARDS:
	LDA @VIRTUAL02
	CLC
	ADC #battler::exp
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL0A
	MOVE_INT BATTLE_EXP_SCRATCH, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, BATTLE_EXP_SCRATCH
	LDX @VIRTUAL02
	LDA a:battler::money,X
	CLC
	ADC BATTLE_MONEY_SCRATCH
	STA BATTLE_MONEY_SCRATCH
.IF .DEFINED(JPN)
	LOADPTR ENEMY_CONFIGURATION_TABLE, @VIRTUAL0A
.ELSE
	LOADPTR ENEMY_CONFIGURATION_TABLE, @LOCAL03
.ENDIF
	LDX @VIRTUAL02
	LDA a:battler::id,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::final_action
.IF .DEFINED(JPN)
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	BEQL @SHOW_DEATH_TEXT
	LDA #1
	STA ENEMY_PERFORMING_FINAL_ATTACK
	LDY CURRENT_ATTACKER
	STY @LOCAL03
	LDX CURRENT_TARGET
	STX @LOCAL05
	MOVE_INT BATTLER_TARGET_FLAGS, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	LDA @VIRTUAL02
	STA CURRENT_ATTACKER
	LDX @VIRTUAL02
	LDA a:battler::id,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::final_action
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
.ELSE
	TAY
	LDA [@LOCAL03],Y
	BEQL @SHOW_DEATH_TEXT
	LDA #1
	STA ENEMY_PERFORMING_FINAL_ATTACK
	LDX CURRENT_ATTACKER
	STX @LOCAL05
	LDY CURRENT_TARGET
	STY @LOCAL02
	MOVE_INT BATTLER_TARGET_FLAGS, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDA @VIRTUAL02
	STA CURRENT_ATTACKER
	LDX @VIRTUAL02
	LDA a:battler::id,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::final_action
	TAY
	LDA [@LOCAL03],Y
.ENDIF
	LDX @VIRTUAL02
	STA a:battler::current_action,X
	LDX @VIRTUAL02
	LDA a:battler::id,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::final_action_arg
.IF .DEFINED(JPN)
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
.ELSE
	TAY
	SEP #PROC_FLAGS::ACCUM8
	LDA [@LOCAL03],Y
.ENDIF
	LDX @VIRTUAL02
	STA a:battler::current_action_argument,X
	REP #PROC_FLAGS::ACCUM8
	LDA CURRENT_ATTACKER
	JSL CHOOSE_TARGET
	LDA CURRENT_ATTACKER
	JSL SET_BATTLER_TARGETS_BY_ACTION
	LDA #0
	JSL FIX_ATTACKER_NAME
	JSL SET_TARGET_IF_TARGETED
.IF .DEFINED(JPN)
	LOADPTR BATTLE_ACTION_TABLE, @LOCAL01
.ELSE
	LOADPTR BATTLE_ACTION_TABLE, @VIRTUAL0A
.ENDIF
	LDX @VIRTUAL02
	LDA a:battler::id,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::final_action
.IF .DEFINED(JPN)
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
.ELSE
	TAY
	LDA [@LOCAL03],Y
.ENDIF
	OPTIMIZED_MULT @VIRTUAL04, 12
	INC
	INC
	INC
	INC
.IF .DEFINED(JPN)
	PHA
	MOVE_INT @LOCAL01, @VIRTUAL06
	PLA
.ELSE
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
.ENDIF
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_IN_BATTLE_TEXT
	LDX @VIRTUAL02
	LDA a:battler::id,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::final_action
.IF .DEFINED(JPN)
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
.ELSE
	TAY
	LDA [@LOCAL03],Y
.ENDIF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(battle_action)
	CLC
	ADC #battle_action::battle_function_pointer
.IF .DEFINED(JPN)
	PHA
	MOVE_INT @LOCAL01, @VIRTUAL06
	PLA
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @LOCAL00
.ELSE
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
.ENDIF
	JSL APPLY_ACTION_TO_TARGETS
	STZ ENEMY_PERFORMING_FINAL_ATTACK
.IF .DEFINED(JPN)
	LDY @LOCAL03
	STY CURRENT_ATTACKER
	LDX @LOCAL05
	STX CURRENT_TARGET
	MOVE_INT @LOCAL02, @VIRTUAL06
.ELSE
	LDX @LOCAL05
	STX CURRENT_ATTACKER
	LDY @LOCAL02
	STY CURRENT_TARGET
	MOVE_INT @LOCAL01, @VIRTUAL06
.ENDIF
	MOVE_INT @VIRTUAL06, BATTLER_TARGET_FLAGS
	LDA #0
	JSL FIX_ATTACKER_NAME
	JSL FIX_TARGET_NAME
	LDA SPECIAL_DEFEAT
	BNEL @DONE
@SHOW_DEATH_TEXT:
	LDA SKIP_DEATH_TEXT_AND_CLEANUP
	BNEL @DONE
	LOADPTR ENEMY_CONFIGURATION_TABLE, @VIRTUAL0A
	LDX @VIRTUAL02
	LDA a:battler::id,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::death_text_ptr
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_IN_BATTLE_TEXT
	LDA #.LOWORD(BATTLERS_TABLE)
	LDX #0
	STX @LOCAL07
	BRA @CLEAR_ALT_SPRITEMAP_CHECK
@CLEAR_ALT_SPRITEMAP_LOOP:
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::use_alt_spritemap,X
	CLC
	REP #PROC_FLAGS::ACCUM8
	ADC #.SIZEOF(battler)
	LDX @LOCAL07
	INX
	STX @LOCAL07
@CLEAR_ALT_SPRITEMAP_CHECK:
	CPX #BATTLER_COUNT
	BCC @CLEAR_ALT_SPRITEMAP_LOOP
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	LDX @VIRTUAL02
	STA a:battler::use_alt_spritemap,X
	REP #PROC_FLAGS::ACCUM8
	LDA #10
	JSL SET_BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	LDA #1
	STA @VIRTUAL04
	BRA @FADE_WHITE_CHECK
@FADE_WHITE_LOOP:
	LDA #31
	STA @LOCAL00
	TAY
	TAX
	STX @LOCAL05
	LDX @VIRTUAL02
	LDA a:battler::vram_sprite_index,X
	AND #$00FF
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL04
	LDX @LOCAL05
	JSL SETUP_BATTLE_SPRITE_PALETTE_EFFECT
	INC @VIRTUAL04
@FADE_WHITE_CHECK:
	LDA @VIRTUAL04
	CMP #16
	BCC @FADE_WHITE_LOOP
	LDA #SIXTH_OF_A_SECOND
	JSR WAIT
	LDA #20
	JSL SET_BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	LDA #1
	STA @VIRTUAL04
	BRA @FADE_BLACK_CHECK
@FADE_BLACK_LOOP:
	STZ_BADOPT @LOCAL00
.IF .DEFINED(JPN)
	TAY
	TAX
.ELSE
	LDY #0
	TYX
.ENDIF
	STX @LOCAL05
	LDX @VIRTUAL02
	LDA a:battler::vram_sprite_index,X
	AND #$00FF
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL04
	LDX @LOCAL05
	JSL SETUP_BATTLE_SPRITE_PALETTE_EFFECT
	INC @VIRTUAL04
@FADE_BLACK_CHECK:
	LDA @VIRTUAL04
	CMP #16
	BCC @FADE_BLACK_LOOP
	LDA #THIRD_OF_A_SECOND
	JSR WAIT
	SEP #PROC_FLAGS::ACCUM8
	LDA #STATUS_0::UNCONSCIOUS
	LDX @VIRTUAL02
	STA a:battler::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	LDX @VIRTUAL02
	STZ a:battler::afflictions + STATUS_GROUP::SHIELD,X
	LDX @VIRTUAL02
	STZ a:battler::afflictions + STATUS_GROUP::HOMESICKNESS,X
	LDX @VIRTUAL02
	STZ a:battler::afflictions + STATUS_GROUP::CONCENTRATION,X
	LDX @VIRTUAL02
	STZ a:battler::afflictions + STATUS_GROUP::STRANGENESS,X
	LDX @VIRTUAL02
	STZ a:battler::afflictions + STATUS_GROUP::TEMPORARY,X
	LDX @VIRTUAL02
	STZ a:battler::afflictions + STATUS_GROUP::PERSISTENT_HARDHEAL,X
	LDX @VIRTUAL02
	REP #PROC_FLAGS::ACCUM8
	STZ a:battler::hp_target,X
	LDX @VIRTUAL02
	LDA a:battler::id,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::death_type
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	AND #$00FF
	BEQL @CHECK_TINY_LIL_GHOST
	LDX #.LOWORD(BATTLERS_TABLE) + (.SIZEOF(battler) * (FIRST_ENEMY_INDEX))
	LDY #FIRST_ENEMY_INDEX
	BRA @SET_ENEMY_ALT_SPRITE_CHECK
@SET_ENEMY_ALT_SPRITE_LOOP:
	LDA a:battler::consciousness,X
	AND #$00FF
	BEQ @SET_ENEMY_ALT_SPRITE_NEXT
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA a:battler::use_alt_spritemap,X
@SET_ENEMY_ALT_SPRITE_NEXT:
	REP #PROC_FLAGS::ACCUM8
	TXA
	CLC
	ADC #.SIZEOF(battler)
	TAX
	INY
@SET_ENEMY_ALT_SPRITE_CHECK:
	CPY #BATTLER_COUNT
	BCC @SET_ENEMY_ALT_SPRITE_LOOP
	LDA #SFX::ENEMY_DEFEATED
	JSL PLAY_SOUND
	LDA #10
	JSL SET_BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	LDA #1
	STA @VIRTUAL04
	BRA @GROUP_FLASH_WHITE_CHECK
@GROUP_FLASH_WHITE_LOOP:
	LDA @VIRTUAL04
	AND #15
	BEQ @GROUP_FLASH_WHITE_SKIP
	LDA #31
	STA @LOCAL00
	TAY
	TAX
	LDA @VIRTUAL04
	JSL SETUP_BATTLE_SPRITE_PALETTE_EFFECT
@GROUP_FLASH_WHITE_SKIP:
	INC @VIRTUAL04
@GROUP_FLASH_WHITE_CHECK:
	LDA @VIRTUAL04
	CMP #64
	BCC @GROUP_FLASH_WHITE_LOOP
	LDA #SIXTH_OF_A_SECOND
	JSR WAIT
	LDA #20
	JSL SET_BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	LDA #1
	STA @VIRTUAL04
	BRA @GROUP_FADE_BLACK_CHECK
@GROUP_FADE_BLACK_LOOP:
	LDA @VIRTUAL04
	AND #15
	BEQ @GROUP_FADE_BLACK_SKIP
	STZ_BADOPT @LOCAL00
.IF .DEFINED(JPN)
	TAY
	TAX
.ELSE
	LDY #0
	TYX
.ENDIF
	LDA @VIRTUAL04
	JSL SETUP_BATTLE_SPRITE_PALETTE_EFFECT
@GROUP_FADE_BLACK_SKIP:
	INC @VIRTUAL04
@GROUP_FADE_BLACK_CHECK:
	LDA @VIRTUAL04
	CMP #64
	BCC @GROUP_FADE_BLACK_LOOP
	LDA #20
	JSR WAIT
	LDX #.LOWORD(BATTLERS_TABLE) + (.SIZEOF(battler) * 8)
	LDY #8
	BRA @KO_ALL_ENEMIES_CHECK
@KO_ALL_ENEMIES_LOOP:
	LDA a:battler::consciousness,X
	AND #$00FF
	BEQ @KO_ALL_ENEMIES_NEXT
	SEP #PROC_FLAGS::ACCUM8
	LDA #STATUS_0::UNCONSCIOUS
	STA a:battler::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
@KO_ALL_ENEMIES_NEXT:
	REP #PROC_FLAGS::ACCUM8
	TXA
	CLC
	ADC #.SIZEOF(battler)
	TAX
	INY
@KO_ALL_ENEMIES_CHECK:
	CPY #BATTLER_COUNT
	BCC @KO_ALL_ENEMIES_LOOP
	JSL RENDER_ALL_BATTLE_SPRITES
	LDA #2
	STA SPECIAL_DEFEAT
@CHECK_TINY_LIL_GHOST:
	LDX @VIRTUAL02
	LDA a:battler::npc_id,X
	AND #$00FF
	CMP #ENEMY::TINY_LIL_GHOST
	BNEL @DONE
	LDY #0
	STY @LOCAL07
	BRA @CURE_POSSESSION_CHECK
@CURE_POSSESSION_LOOP:
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @CURE_POSSESSION_NEXT
	LDA BATTLERS_TABLE+battler::npc_id,X
	AND #$00FF
	BNE @CURE_POSSESSION_NEXT
	TXA
	CLC
	ADC #.LOWORD(BATTLERS_TABLE) + battler::afflictions
	TAX
	INX
	LDA __BSS_START__,X ; STATUS_GROUP::PERSISTENT_HARDHEAL
	AND #$00FF
	CMP #2
	BNE @CURE_POSSESSION_NEXT
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA __BSS_START__,X
	BRA @RESPAWN_GHOST_CHECK
@CURE_POSSESSION_NEXT:
	LDY @LOCAL07
	INY
	STY @LOCAL07
@CURE_POSSESSION_CHECK:
	CPY #TOTAL_PARTY_COUNT
	BCC @CURE_POSSESSION_LOOP
	BRA @RESPAWN_GHOST_CHECK
@RESPAWN_GHOST_LOOP:
	REP #PROC_FLAGS::ACCUM8
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @RESPAWN_GHOST_NEXT
	LDA BATTLERS_TABLE+battler::npc_id,X
	AND #$00FF
	BNE @RESPAWN_GHOST_NEXT
	TXA
	CLC
	ADC #.LOWORD(BATTLERS_TABLE) + battler::afflictions
	TAX
	LDA a:STATUS_GROUP::PERSISTENT_HARDHEAL,X
	AND #$00FF
	CMP #STATUS_1::POSSESSED
	BNE @RESPAWN_GHOST_NEXT
	LDX #.LOWORD(BATTLERS_TABLE) + (.SIZEOF(battler) * 6)
	LDA #ENEMY::TINY_LIL_GHOST
	JSL BATTLE_INIT_ENEMY_STATS
	SEP #PROC_FLAGS::ACCUM8
	LDA #ENEMY::TINY_LIL_GHOST
	STA BATTLERS_TABLE+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)+battler::npc_id
	LDA #1
	STA BATTLERS_TABLE+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)+battler::has_taken_turn
@RESPAWN_GHOST_NEXT:
	LDY @LOCAL07
	INY
	STY @LOCAL07
@RESPAWN_GHOST_CHECK:
	LDY @LOCAL07
	CPY #TOTAL_PARTY_COUNT
	BCC @RESPAWN_GHOST_LOOP
@DONE:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
