
LAYOUT_ENEMY_BATTLE_POSITIONS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
.IF .DEFINED(USA)
	STACK_RESERVE_INT16 "LOCALEB"
.ENDIF
	STACK_RESERVE_INT8 "LOCAL03"
	STACK_RESERVE_INT16 "LOCAL04"
	STACK_RESERVE_INT16 "LOCAL05"
	STACK_RESERVE_INT16 "LOCAL06"
	STACK_RESERVE_INT16 "LOCAL07"
	STACK_RESERVE_INT16 "LOCAL08"
	STACK_RESERVE_INT16 "LOCAL09"
	STACK_RESERVE_INT16 "LOCAL0A"
	STACK_RESERVE_INT16 "LOCAL0B"
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
.IF .DEFINED(JPN) ;wonder why the allocation is so different here?
	@LOCALEB_1 := @LOCAL04
	@LOCALEB_2 := @LOCAL05
	@LOCAL04ALT := @LOCAL09
	@LOCAL04ALT2 := @LOCAL0A
	@LOCAL05ALT := @LOCAL01
	@LOCAL05ALT2 := @LOCAL04
	@LOCAL0AALT := @LOCAL07
.ELSE
	@LOCALEB_1 := @LOCALEB
	@LOCALEB_2 := @LOCALEB
	@LOCAL04ALT := @LOCAL04
	@LOCAL04ALT2 := @LOCAL04
	@LOCAL05ALT := @LOCAL05
	@LOCAL05ALT2 := @LOCAL05
	@LOCAL0AALT := @LOCAL0A
.ENDIF
	STZ BATTLE_SPRITE_ROW_WIDTH+2
	STZ BATTLE_SPRITE_ROW_WIDTH
	LDX #8
	STX @LOCAL0B
	JMP @ROW_ASSIGN_CHECK
@ROW_ASSIGN_LOOP:
	TXA
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAY
	STY @LOCAL0A
	LDA BATTLERS_TABLE+battler::consciousness,Y
	AND #$00FF
	BEQL @ROW_ASSIGN_NEXT
	LDA BATTLERS_TABLE+battler::ally_or_enemy,Y
	AND #$00FF
	CMP #1
	BNEL @ROW_ASSIGN_NEXT
	LDA BATTLERS_TABLE,Y
	JSR FIND_BATTLE_SPRITE_FOR_ENEMY
	SEP #PROC_FLAGS::ACCUM8
	LDY @LOCAL0A
	STA BATTLERS_TABLE+battler::vram_sprite_index,Y
	REP #PROC_FLAGS::ACCUM8
	LDA BATTLERS_TABLE+battler::row,Y
	AND #$00FF
	STA @LOCAL09
	LDA BATTLERS_TABLE+battler::sprite,Y
	JSR GET_BATTLE_SPRITE_WIDTH
	STA @VIRTUAL02
	LDA @LOCAL09
	ASL
	TAX
	LDA BATTLE_SPRITE_ROW_WIDTH,X
	BEQ @AFTER_ROW_SPACING
	INC @VIRTUAL02
@AFTER_ROW_SPACING:
	LDA @LOCAL09
	ASL
	CLC
	ADC #.LOWORD(BATTLE_SPRITE_ROW_WIDTH)
	TAY
	LDA __BSS_START__,Y
	CLC
	ADC @VIRTUAL02
	CMP #30
	BGT @ROW_OVERFLOW
	STA __BSS_START__,Y
	BRA @ROW_ASSIGN_NEXT
@ROW_OVERFLOW:
	LDA #1
	SEC
	SBC @LOCAL09
	STA @LOCAL0A
	LDX @LOCAL0B
	TXA
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::sprite,X
	JSR GET_BATTLE_SPRITE_WIDTH
	STA @VIRTUAL02
	LDA @LOCAL0A
	ASL
	TAX
	LDA BATTLE_SPRITE_ROW_WIDTH,X
	BEQ @AFTER_ALT_ROW_SPACING
	INC @VIRTUAL02
@AFTER_ALT_ROW_SPACING:
	LDA @LOCAL0A
	ASL
	CLC
	ADC #.LOWORD(BATTLE_SPRITE_ROW_WIDTH)
	TAY
	STY @LOCAL08
	LDA __BSS_START__,Y
	CLC
	ADC @VIRTUAL02
	CMP #30
	BGT @LAYOUT_FAILED
	LDX @LOCAL0B
	TXA
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA @LOCAL0A
	SEP #PROC_FLAGS::ACCUM8
	STA BATTLERS_TABLE+battler::row,X
	LDY @LOCAL08
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,Y
	CLC
	ADC @VIRTUAL02
	STA __BSS_START__,Y
	BRA @ROW_ASSIGN_NEXT
@LAYOUT_FAILED:
	LDA #0
	JMP @RETURN
@ROW_ASSIGN_NEXT:
	LDX @LOCAL0B
	INX
	STX @LOCAL0B
@ROW_ASSIGN_CHECK:
	CPX #BATTLER_COUNT
	BCCL @ROW_ASSIGN_LOOP
	;TODO: why 8?
	LDA BATTLERS_TABLE+8*.SIZEOF(battler)+16
	AND #$00FF
	STA @LOCAL0A
	LDA #32
	STA @LOCAL07
	STA @LOCAL06
	LDX #8
	STX @LOCAL08
	JMP @XPOS_GROUP1_CHECK
@XPOS_GROUP1_LOOP:
	TXA
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAY
	STY @LOCAL09
	LDA BATTLERS_TABLE+battler::consciousness,Y
	AND #$00FF
	BEQL @XPOS_GROUP1_NEXT
	LDA BATTLERS_TABLE+battler::ally_or_enemy,Y
	AND #$00FF
	CMP #1
	BNEL @XPOS_GROUP1_NEXT
	LDA BATTLERS_TABLE+16,Y
	AND #$00FF
	CMP @LOCAL0A
	BNEL @XPOS_GROUP1_NEXT
	LDA BATTLERS_TABLE+battler::sprite,Y
	JSR GET_BATTLE_SPRITE_WIDTH
	LSR
	STA @LOCAL05
	LDA @LOCAL06
	CMP @LOCAL07
	BNE @COMPARE_SIDES
	LDA @LOCAL06
	SEP #PROC_FLAGS::ACCUM8
	LDY @LOCAL09
	STA BATTLERS_TABLE+battler::sprite_x,Y
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL06
	SEC
	SBC @LOCAL05
	STA @LOCAL06
	LDA @LOCAL07
	CLC
	ADC @LOCAL05
	STA @LOCAL07
	JSR RAND_LONG
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	AND #$0001
	BEQ @RANDOM_RIGHT_SIDE
	LDA @LOCAL06
	STA @VIRTUAL04
	STA @LOCAL04
	JMP @XPOS_GROUP1_NEXT
@RANDOM_RIGHT_SIDE:
	LDA @LOCAL07
	STA @VIRTUAL04
	STA @LOCAL04
	JMP @XPOS_GROUP1_NEXT
@COMPARE_SIDES:
	LDA #32
	SEC
	SBC @LOCAL06
	STA @LOCAL09
	LDA @LOCAL07
	SEC
	SBC #32
	STA @VIRTUAL02
	LDA @LOCAL09
	CMP @VIRTUAL02
	BCC @PLACE_LEFT
	CMP @VIRTUAL02
	BNE @PLACE_RIGHT
	JSR RAND_LONG
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	AND #$0001
	BEQ @PLACE_RIGHT
@PLACE_LEFT:
	LDA @LOCAL05
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL06
	SEP #PROC_FLAGS::ACCUM8
	SEC
	SBC @VIRTUAL00
	DEC
	STA @LOCAL03
	LDX @LOCAL08
	REP #PROC_FLAGS::ACCUM8
	TXA
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA BATTLERS_TABLE+battler::sprite_x,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	SEC
	SBC @LOCAL05
	STA @LOCAL06
	BRA @XPOS_GROUP1_NEXT
@PLACE_RIGHT:
	LDA @LOCAL05
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	SEP #PROC_FLAGS::ACCUM8
	CLC
	ADC @VIRTUAL00
	INC
	STA @LOCAL03
	LDX @LOCAL08
	REP #PROC_FLAGS::ACCUM8
	TXA
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA BATTLERS_TABLE+battler::sprite_x,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	CLC
	ADC @LOCAL05
	STA @LOCAL07
@XPOS_GROUP1_NEXT:
	LDX @LOCAL08
	INX
	STX @LOCAL08
@XPOS_GROUP1_CHECK:
	CPX #32
	BCCL @XPOS_GROUP1_LOOP
	LDA @LOCAL04
	STA @VIRTUAL04
	LDY @VIRTUAL04
	STY @LOCAL0B
	TYX
	STX @LOCALEB_1
	LDA #8
	STA @VIRTUAL02
	STA @LOCAL08
	JMP @XPOS_OTHER_CHECK
@XPOS_OTHER_LOOP:
	LDA @VIRTUAL02
	LDY #.SIZEOF(battler)
	JSL MULT168
	STA @VIRTUAL04
	LDX @VIRTUAL04
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQL @XPOS_OTHER_NEXT
	LDX @VIRTUAL04
	LDA BATTLERS_TABLE+battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BNEL @XPOS_OTHER_NEXT
	LDX @VIRTUAL04
	LDA BATTLERS_TABLE+16,X
	AND #$00FF
	CMP @LOCAL0A
	BEQL @XPOS_OTHER_NEXT
	LDX @VIRTUAL04
	LDA BATTLERS_TABLE+battler::sprite,X
	JSR GET_BATTLE_SPRITE_WIDTH
	LSR
	STA @LOCAL01
	LDY @LOCAL0B
	STY @VIRTUAL02
	LDX @LOCALEB_1
	TXA
	CMP @VIRTUAL02
	BNE @COMPARE_SIDES_OTHER
	TXA
	SEP #PROC_FLAGS::ACCUM8
	LDX @VIRTUAL04
	STA BATTLERS_TABLE+battler::sprite_x,X
	LDX @LOCALEB_1
	REP #PROC_FLAGS::ACCUM8
	TXA
	SEC
	SBC @LOCAL01
	TAX
	STX @LOCALEB_1
	TYA
	CLC
	ADC @LOCAL01
	TAY
	STY @LOCAL0B
	JMP @XPOS_OTHER_NEXT
@COMPARE_SIDES_OTHER:
	CPY #32
	BLTEQ @PLACE_RIGHT_OTHER
	CPX #32
	BGT @PLACE_LEFT_OTHER
	STX @VIRTUAL04
	LDA #32
	SEC
	SBC @VIRTUAL04
	STA @LOCAL04ALT
	TYA
	SEC
	SBC #32
	STA @VIRTUAL04
	LDA @LOCAL04ALT
	CMP @VIRTUAL04
	BCC @PLACE_LEFT_OTHER
	CMP @VIRTUAL04
	BNE @PLACE_RIGHT_OTHER
	JSR RAND_LONG
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	AND #$0001
	BEQ @PLACE_RIGHT_OTHER
@PLACE_LEFT_OTHER:
	LDA @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	LDX @LOCALEB_1
	REP #PROC_FLAGS::ACCUM8
	TXA
	SEP #PROC_FLAGS::ACCUM8
	SEC
	SBC @VIRTUAL00
	DEC
	STA @LOCAL03
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL08
	STA @VIRTUAL02
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA BATTLERS_TABLE+battler::sprite_x,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	SEC
	SBC @LOCAL01
	TAX
	STX @LOCALEB_1
	BRA @XPOS_OTHER_NEXT
@PLACE_RIGHT_OTHER:
	LDA @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	LDY @LOCAL0B
	REP #PROC_FLAGS::ACCUM8
	TYA
	SEP #PROC_FLAGS::ACCUM8
	CLC
	ADC @VIRTUAL00
	INC
	STA @LOCAL03
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL08
	STA @VIRTUAL02
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA BATTLERS_TABLE+battler::sprite_x,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	CLC
	ADC @LOCAL01
	TAY
	STY @LOCAL0B
@XPOS_OTHER_NEXT:
	LDA @LOCAL08
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL08
@XPOS_OTHER_CHECK:
	LDA @VIRTUAL02
	CMP #32
	BCCL @XPOS_OTHER_LOOP
	LDA @LOCAL0A
	CMP #1
	BNE @AFTER_SINGLE_ROW_FIX
	LDY @LOCAL0B
	STY @VIRTUAL02
	LDX @LOCALEB_1
	TXA
	CMP @VIRTUAL02
	BNE @AFTER_SINGLE_ROW_FIX
	LDA #8
	STA @VIRTUAL02
	BRA @CLEAR_ROWS_CHECK
@CLEAR_ROWS_LOOP:
	LDA @VIRTUAL02
	LDY #.SIZEOF(battler)
	JSL MULT168
	STA @LOCAL04ALT2
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @CLEAR_ROWS_NEXT
	LDA @LOCAL04ALT2
	TAX
	LDA BATTLERS_TABLE+battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BNE @CLEAR_ROWS_NEXT
	LDA @LOCAL04ALT2
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ BATTLERS_TABLE+battler::row,X
@CLEAR_ROWS_NEXT:
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL02
@CLEAR_ROWS_CHECK:
	LDA @VIRTUAL02
	CMP #32
	BCC @CLEAR_ROWS_LOOP
@AFTER_SINGLE_ROW_FIX:
	LDX @LOCALEB_1
	CPX @LOCAL06
	BCS @CLAMP_MAX
	STX @LOCAL06
@CLAMP_MAX:
	LDY @LOCAL0B
	CPY @LOCAL07
	BLTEQ @CALC_CENTER_OFFSET
	STY @LOCAL07
@CALC_CENTER_OFFSET:
	LDA @LOCAL06
	CLC
	ADC @LOCAL07
	LSR
	STA @VIRTUAL02
	LDA #32
	SEC
	SBC @VIRTUAL02
	SEC
	SBC #16
	TAY
	STY @LOCAL06
	LDA #8
	STA @LOCALEB_2
	BRA @FINAL_POS_CHECK
@FINAL_POS_LOOP:
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	STX @LOCAL05ALT
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @FINAL_POS_NEXT
	LDA BATTLERS_TABLE+battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BNE @FINAL_POS_NEXT
	TXA
	CLC
	ADC #.LOWORD(BATTLERS_TABLE) + battler::sprite_x
	STA @VIRTUAL02
	LDY @LOCAL06
	SEP #PROC_FLAGS::INDEX8
	STY @VIRTUAL00
	REP #PROC_FLAGS::INDEX8
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL00
	ASL
	ASL
	ASL
	LDX @VIRTUAL02
	STA __BSS_START__,X
	LDX @LOCAL05ALT
	REP #PROC_FLAGS::ACCUM8
	LDA BATTLERS_TABLE+battler::row,X
	AND #$00FF
	BEQ @SET_Y_FRONT_ROW
	SEP #PROC_FLAGS::ACCUM8
	LDA #128
	STA BATTLERS_TABLE+69,X
	BRA @FINAL_POS_NEXT
@SET_Y_FRONT_ROW:
	SEP #PROC_FLAGS::ACCUM8
	LDA #144
	STA BATTLERS_TABLE+69,X
@FINAL_POS_NEXT:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCALEB_2
	INC
	STA @LOCALEB_2
@FINAL_POS_CHECK:
	CMP #BATTLER_COUNT
	BCC @FINAL_POS_LOOP
	LDA CURRENT_BATTLE_GROUP
	CMP #ENEMY_GROUP::UNKNOWN_475
	BNE @AFTER_SPECIAL_GROUP
	SEP #PROC_FLAGS::ACCUM8
	LDA #128
	STA BATTLERS_TABLE+8*.SIZEOF(battler)+battler::sprite_x
	STA BATTLERS_TABLE+8*.SIZEOF(battler)+69
	LDA #200
	STA BATTLERS_TABLE+9*.SIZEOF(battler)+battler::sprite_x
	LDA #144
	STA BATTLERS_TABLE+9*.SIZEOF(battler)+69
@AFTER_SPECIAL_GROUP:
	REP #PROC_FLAGS::ACCUM8
	STZ @LOCAL09
	LDA #0
	STA @VIRTUAL04
	JMP @SORT_OUTER_CHECK
@SORT_OUTER_LOOP:
	.I16
	LDA @VIRTUAL04
.IF .DEFINED(USA)
	REP #PROC_FLAGS::INDEX8
.ENDIF
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE) + (.SIZEOF(battler) * 8)
	TAY
	STY @LOCAL05ALT2
	LDA @VIRTUAL04
	INC
	STA @LOCAL06
	JMP @SORT_INNER_CHECK
@SORT_INNER_LOOP:
	.I16
	LDA @LOCAL06
.IF .DEFINED(USA)
	REP #PROC_FLAGS::INDEX8
.ENDIF
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)+8*.SIZEOF(battler)
	STA @LOCAL0AALT
	LDY @LOCAL05ALT2
	LDA __BSS_START__,Y
	CMP (@LOCAL0AALT)
	BNEL @SORT_INNER_NEXT
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__+11,Y
	LDY #11
	CMP (@LOCAL0AALT),Y
	BCS @COMPARE_ROW
	LDY @LOCAL05ALT2
	LDA __BSS_START__+69,Y
	STA @VIRTUAL00
	LDY #69
	LDA (@LOCAL0AALT),Y
	STA @LOCAL03
	STA @VIRTUAL01
	LDA @VIRTUAL00
	CMP @VIRTUAL01
	BCC @SWAP_BATTLERS
	LDA @LOCAL03
	PHA
	LDA @VIRTUAL00
	SEP #PROC_FLAGS::INDEX8
	PLX
	STX @VIRTUAL00
	CMP @VIRTUAL00
	BNE @COMPARE_ROW
	REP #PROC_FLAGS::INDEX8
	LDY @LOCAL05ALT2
	LDA __BSS_START__+68,Y
	LDY #68
	CMP (@LOCAL0AALT),Y
	BGT @SWAP_BATTLERS
@COMPARE_ROW:
	REP #PROC_FLAGS::INDEX8
	LDY @LOCAL05ALT2
	LDA __BSS_START__+11,Y
	LDY #11
	CMP (@LOCAL0AALT),Y
.IF .DEFINED(JPN)
	BCS @COMPARE_Y_POS
.ELSE
	BGT @COMPARE_Y_POS
.ENDIF
	JMP @SORT_INNER_NEXT
@COMPARE_Y_POS:
	LDY @LOCAL05ALT2
	LDA __BSS_START__+69,Y
	STA @VIRTUAL00
	LDY #69
	LDA (@LOCAL0AALT),Y
	STA @LOCAL03
	STA @VIRTUAL01
	LDA @VIRTUAL00
	CMP @VIRTUAL01
	BGT @SWAP_BATTLERS
	LDA @LOCAL03
	PHA
	LDA @VIRTUAL00
	SEP #PROC_FLAGS::INDEX8
	PLX
	STX @VIRTUAL00
	CMP @VIRTUAL00
	BNEL @SORT_INNER_NEXT
	REP #PROC_FLAGS::INDEX8
	LDY @LOCAL05ALT2
	LDA a:battler::sprite_x,Y
	LDY #68
	CMP (@LOCAL0AALT),Y
	BCC @SWAP_BATTLERS
	JMP @SORT_INNER_NEXT
@SWAP_BATTLERS:
	REP #PROC_FLAGS::ACCUM8
	LDA #1
	STA @LOCAL09
	LDY @LOCAL05ALT2
	TYA
	CLC
	ADC #11
	TAX
	STX @LOCALEB_2
	LDA __BSS_START__,X
	AND #$00FF
	STA @LOCAL01
	LDA @LOCAL0AALT
	CLC
	ADC #11
	STA @VIRTUAL02
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	LDX @LOCALEB_2
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	LDX @VIRTUAL02
	STA __BSS_START__,X
	STA @VIRTUAL00
	LDX @LOCALEB_2
	LDA __BSS_START__,X
	CMP @VIRTUAL00
	BLTEQ @SORT_INNER_NEXT
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(BATTLERS_TABLE) + ((BATTLER_COUNT - 1) * .SIZEOF(battler))
	STA @VIRTUAL02
	TYA
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #.SIZEOF(battler)
	LDA @VIRTUAL02
	JSL MEMCPY16
	LDA @LOCAL0AALT
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #.SIZEOF(battler)
	LDY @LOCAL05ALT2
	TYA
	JSL MEMCPY16
	LDA @VIRTUAL02
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #.SIZEOF(battler)
	LDA @LOCAL0AALT
	JSL MEMCPY16
@SORT_INNER_NEXT:
	REP #PROC_FLAGS::ACCUM8
	INC @LOCAL06
@SORT_INNER_CHECK:
	LDA ENEMIES_IN_BATTLE
	CMP @LOCAL06
	BGTL @SORT_INNER_LOOP
	INC @VIRTUAL04
@SORT_OUTER_CHECK:
	LDA ENEMIES_IN_BATTLE
	DEC
	STA @VIRTUAL02
	LDA @VIRTUAL04
	CMP @VIRTUAL02
	BCCL @SORT_OUTER_LOOP
	LDA @LOCAL09
	BNEL @AFTER_SPECIAL_GROUP
	SEP #PROC_FLAGS::ACCUM8
	STZ_BADOPT @LOCAL00
	REP #PROC_FLAGS::INDEX8
	LDX #.SIZEOF(battler)
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(BATTLERS_TABLE) + 31 * .SIZEOF(battler)
	JSL MEMSET16
	LDA #0
@RETURN:
	END_C_FUNCTION
