
LOAD_BATTLE_SCENE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
.IF .DEFINED(JPN)
	STACK_RESERVE_INT32 "LOCALM2"
	STACK_RESERVE_INT16 "LOCALM22"
.ENDIF
	STACK_RESERVE_INT16 "LOCAL00"
	STACK_RESERVE_INT16 "LOCAL01"
	STACK_RESERVE_INT16 "LOCAL02"
	STACK_RESERVE_INT16 "LOCAL03"
	STACK_RESERVE_PARAM_INT16 ;int battleGroup
	STACK_RESERVE_PARAM_INT16 ;int
	END_STACK_VARS
	STX @LOCAL03
	STA @LOCAL02
	STZ @LOCAL01
	LDA BATTLE_MODE_FLAG
	BEQ @SKIP_SWIRL
	LDA @LOCAL02
	CMP #ENEMY_GROUP::BOSS_GIYGAS_PHASE_FINAL
	BNE @CHECK_SKIP_SWIRL
@SKIP_SWIRL:
	LDA #1
	STA @LOCAL01
@CHECK_SKIP_SWIRL:
	LDA @LOCAL01
	BNE @AFTER_SWIRL_IN
	LDY #30
	LDX #1
	LDA #6
	JSL START_BATTLE_SWIRL
	BRA @SWIRL_IN_CHECK
@SWIRL_IN_TICK:
	JSL WINDOW_TICK
@SWIRL_IN_CHECK:
	JSL IS_BATTLE_SWIRL_ACTIVE
	CMP #0
	BNE @SWIRL_IN_TICK
@AFTER_SWIRL_IN:
	LDA @LOCAL02
	STA CURRENT_BATTLE_GROUP
	LOADPTR BTL_ENTRY_BG_TABLE, @VIRTUAL06
	LDA CURRENT_BATTLE_GROUP
	ASL
	ASL
	STA @LOCAL00
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
.IF .DEFINED(JPN)
	STA @LOCALM22
	LDA @LOCAL00
.ELSE
	STA @VIRTUAL04
	LDA @LOCAL00
.ENDIF
	INC
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
.IF .DEFINED(JPN)
	STA @VIRTUAL04
.ELSE
	STA @VIRTUAL02
.ENDIF
	LDA CURRENT_BATTLE_GROUP
	ASL
	ASL
	ASL
	CLC
	ADC #battle_entry_ptr_entry::letterbox_style
	TAX
	LDA f:BTL_ENTRY_PTR_TABLE,X
	AND #$00FF
.IF .DEFINED(JPN)
	STA @VIRTUAL02
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	JSL LOAD_ENEMY_BATTLE_SPRITES
	JSL LOAD_WINDOW_GFX
	COPY_TO_VRAM1 BUFFER, $6000, $3800, 0
	LDY @VIRTUAL02
	LDX @VIRTUAL04
	LDA @LOCALM22
	.A16
.ELSE
	TAX
	STX @LOCAL00
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	JSL LOAD_ENEMY_BATTLE_SPRITES
	JSL LOAD_WINDOW_GFX
	LDA #1
	JSL UPLOAD_TEXT_TILES_TO_VRAM
	LDX @LOCAL00
	TXY
	LDX @VIRTUAL02
	LDA @VIRTUAL04
.ENDIF
	JSL LOAD_BATTLE_BG
	JSL SETUP_BATTLE_ENEMY_SPRITES
	LDA #24
	JSL SET_PALETTE_UPLOAD_MODE
	JSL RENDER_ALL_BATTLE_SPRITES
	LDA #1
	STA BATTLE_MODE_FLAG
	LDA @LOCAL03
	BEQ @PLAY_MUSIC
	LDA @LOCAL03
	JSL CHANGE_MUSIC
@PLAY_MUSIC:
	JSL BLANK_SCREEN_AND_WAIT_VBLANK
	LDA @LOCAL01
	BEQ @FADE_WITH_SWIRL
	LDX #4
	LDA #1
	JSL FADE_IN
	JSR WAIT_FOR_FADE_WITH_TICK
	BRA @RETURN
@FADE_WITH_SWIRL:
	LDX #1
	LDA #15
	JSL FADE_IN
	LDA @LOCAL02
	CMP #ENEMY_GROUP::BOSS_GIYGAS_PHASE_FINAL
	BEQ @RETURN
	LDY #5
	LDX #0
	LDA #6
	JSL START_BATTLE_SWIRL
	BRA @SWIRL_OUT_CHECK
@SWIRL_OUT_TICK:
	JSL WINDOW_TICK
@SWIRL_OUT_CHECK:
	JSL IS_BATTLE_SWIRL_ACTIVE
	CMP #0
	BNE @SWIRL_OUT_TICK
@RETURN:
	END_C_FUNCTION
