
BATTLE_ROUTINE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	LDA BATTLE_MODE
	BNE @INIT_GIYGAS
	LDA #1
	STA @LOCAL12
	STA @LOCAL11
	SEP #PROC_FLAGS::ACCUM8
	STA GAME_STATE+game_state::player_controlled_party_count
.IF .DEFINED(JPN)
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(GAME_STATE) + game_state::party_members
	STA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
.ELSE
	LDY #.LOWORD(GAME_STATE) + game_state::party_members
	STY @LOCAL10
.ENDIF
	STZ_BADOPT @LOCAL00
	LDX #6
	REP #PROC_FLAGS::ACCUM8
.IF .DEFINED(JPN)
	LDA @VIRTUAL02
.ELSE
	TYA
.ENDIF
	JSL MEMSET16
.IF .DEFINED(JPN)
	LDY #.LOWORD(GAME_STATE) + game_state::party_order
	STY @LOCAL10
.ELSE
	LDA #.LOWORD(GAME_STATE) + game_state::party_order
	STA @VIRTUAL02
.ENDIF
	SEP #PROC_FLAGS::ACCUM8
	STZ_BADOPT @LOCAL00
	LDX #6
	REP #PROC_FLAGS::ACCUM8
.IF .DEFINED(JPN)
	TYA
.ELSE
	LDA @VIRTUAL02
.ENDIF
	JSL MEMSET16
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
.IF .DEFINED(JPN) ;reversed order?
	LDX @VIRTUAL02
	STA __BSS_START__,X
	LDY @LOCAL10
	STA __BSS_START__,Y
.ELSE
	LDY @LOCAL10
	STA __BSS_START__,Y
	LDX @VIRTUAL02
	STA __BSS_START__,X
.ENDIF
	REP #PROC_FLAGS::ACCUM8
	LDA #1
	STA ENEMIES_IN_BATTLE
	STA CURRENT_BATTLE_GROUP
	MOVE_INT f:BTL_ENTRY_PTR_TABLE+.SIZEOF(battle_entry_ptr_entry)+battle_entry_ptr_entry::pointer, @VIRTUAL06
	LDY #1
	LDA [@VIRTUAL06],Y
	STA ENEMIES_IN_BATTLE_IDS
@INIT_GIYGAS:
	STZ GIYGAS_PHASE
	LDA CURRENT_BATTLE_GROUP
	CMP #ENEMY_GROUP::UNKNOWN_475
	BNE @LOAD_BG_TABLE
	LDA #GIYGAS_PHASES::BATTLE_STARTED
	STA GIYGAS_PHASE
@LOAD_BG_TABLE:
	LOADPTR BTL_ENTRY_BG_TABLE, @VIRTUAL06
	LDA CURRENT_BATTLE_GROUP
	ASL
	ASL
	STA @LOCAL0F
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	STA @LOCAL0E
	LDA @LOCAL0F
	INC
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
.IF .DEFINED(JPN)
	STA @LOCAL0F
.ELSE
	STA @LOCAL0D
.ENDIF
	LDA CURRENT_BATTLE_GROUP
	ASL
	ASL
	ASL
	CLC
	ADC #battle_entry_ptr_entry::letterbox_style
	TAX
	LDA f:BTL_ENTRY_PTR_TABLE,X
	AND #$00FF
.IF .DEFINED(JPN)
	STA @LOCAL0D
.ELSE
	STA @LOCAL0C
.ENDIF
@REINIT_BATTLE:
.IF .DEFINED(USA)
	REP #PROC_FLAGS::ACCUM8
.ENDIF
	STZ MIRROR_ENEMY
.IF .DEFINED(JPN)
	STZ @LOCAL0C
	SEP #PROC_FLAGS::ACCUM8
	STZ BATTLE_ITEM_USED ;huh... usually mother 2 optimizes this worse
	REP #PROC_FLAGS::ACCUM8
	STZ @LOCAL0B
.ELSE
	STZ @LOCAL0B
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA BATTLE_ITEM_USED
	REP #PROC_FLAGS::ACCUM8
	STZ @LOCAL0A
.ENDIF
	STZ BATTLE_MONEY_SCRATCH
	MOVE_INT_CONSTANT 0, BATTLE_EXP_SCRATCH
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	JSL CLEAR_BATTLE_VISUAL_EFFECTS
	JSL LOAD_ENEMY_BATTLE_SPRITES
	JSL LOAD_WINDOW_GFX
.IF .DEFINED(JPN)
	COPY_TO_VRAM1 BUFFER, $6000, $3800, $00
	LDY @LOCAL0D
	LDX @LOCAL0F
.ELSE
	LDA #1
	JSL UPLOAD_TEXT_TILES_TO_VRAM
	LDY @LOCAL0C
	LDX @LOCAL0D
.ENDIF
	LDA @LOCAL0E
	JSL LOAD_BATTLE_BG
	JSL SETUP_BATTLE_ENEMY_SPRITES
	LDY #0
.IF .DEFINED(JPN)
	STY @LOCAL0A
.ELSE
	STY @LOCAL10
.ENDIF
	BRA @CLEAR_BATTLER_CHECK
@CLEAR_BATTLER_LOOP:
	SEP #PROC_FLAGS::ACCUM8
	STZ_BADOPT @LOCAL00
	LDX #.SIZEOF(battler)
	REP #PROC_FLAGS::ACCUM8
	TYA
	TXY
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	JSL MEMSET16
.IF .DEFINED(JPN)
	LDY @LOCAL0A
	INY
	STY @LOCAL0A
.ELSE
	LDY @LOCAL10
	INY
	STY @LOCAL10
.ENDIF
@CLEAR_BATTLER_CHECK:
	CPY #BATTLER_COUNT
	BCC @CLEAR_BATTLER_LOOP
	STZ HIGHEST_ENEMY_LEVEL_IN_BATTLE
	LDY #0
	STY @LOCAL09
	STZ @LOCAL10
	JMP @INIT_PARTY_CHECK
@INIT_PARTY_MEMBER:
.IF .DEFINED(JPN)
	LDA @LOCAL10
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
.ELSE
	LDY #.LOWORD(GAME_STATE) + game_state::party_members
	LDA (@LOCAL10),Y
.ENDIF
	AND #$00FF
	STA @VIRTUAL04
	STA @LOCAL08
	LDA @VIRTUAL04
	BEQ @INIT_NPC_PARTY_MEMBER
	LDA @VIRTUAL04
	CMP #4
	BGT @INIT_NPC_PARTY_MEMBER
	LDA @LOCAL10
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	TAX
	LDA @VIRTUAL04
	JSL BATTLE_INIT_PLAYER_STATS
	BRA @NEXT_PARTY_INIT
@INIT_NPC_PARTY_MEMBER:
	LDA @VIRTUAL04
	CMP #5
	BCC @NEXT_PARTY_INIT
	LDA @LOCAL10
	LDY #.SIZEOF(battler)
	JSL MULT168
	STA @VIRTUAL02
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	TAX
	STX @LOCAL07
	LDA @VIRTUAL04
	ASL
	TAX
	INX
	LDA f:NPC_AI_TABLE,X
	AND #$00FF
	LDX @LOCAL07
	JSL BATTLE_INIT_ENEMY_STATS
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STZ BATTLERS_TABLE+battler::ally_or_enemy,X
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	SEP #PROC_FLAGS::ACCUM8
	LDX @VIRTUAL02
	STA BATTLERS_TABLE+battler::npc_id,X
	LDY @LOCAL09
	REP #PROC_FLAGS::ACCUM8
	TYA
	SEP #PROC_FLAGS::ACCUM8
	LDX @VIRTUAL02
	STA BATTLERS_TABLE+16,X
	REP #PROC_FLAGS::ACCUM8
	TYA
	ASL
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_npc_1_hp,X
.ELSE
	TAX
	LDA GAME_STATE+game_state::party_npc_1_hp,X
.ENDIF
	LDX @VIRTUAL02
	STA BATTLERS_TABLE+battler::hp_target,X
	LDX @VIRTUAL02
	STA BATTLERS_TABLE+battler::hp,X
	INY
	STY @LOCAL09
	LDX @VIRTUAL02
	STZ BATTLERS_TABLE+battler::pp_target,X
	LDX @VIRTUAL02
	STZ BATTLERS_TABLE+battler::pp,X
@NEXT_PARTY_INIT:
	INC @LOCAL10
@INIT_PARTY_CHECK:
	LDA @LOCAL10
	CMP #6
	BCCL @INIT_PARTY_MEMBER
	JSL CLAMP_ENEMIES_TO_SCREEN_WIDTH
	LDY #0
	STY @LOCAL10
	BRA @INIT_ENEMY_CHECK
@INIT_ENEMY_LOOP:
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE) + (.SIZEOF(battler) * 8)
	TAX
	STX @LOCAL07
	LDY @LOCAL10
	TYA
	ASL
	TAX
	LDA ENEMIES_IN_BATTLE_IDS,X
	LDX @LOCAL07
	JSL BATTLE_INIT_ENEMY_STATS
	LDY @LOCAL10
	INY
	STY @LOCAL10
@INIT_ENEMY_CHECK:
	CPY ENEMIES_IN_BATTLE
	BCC @INIT_ENEMY_LOOP
	JSL LAYOUT_ENEMY_BATTLE_POSITIONS
	JSL RENDER_ALL_BATTLE_SPRITES
	JSL LOAD_CHARACTER_WINDOW_PALETTE
	LDA #24
	JSL SET_PALETTE_UPLOAD_MODE
	LDA #1
	STA BATTLE_MODE_FLAG
	LDA ENEMIES_IN_BATTLE_IDS
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::music
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	AND #$00FF
	JSL CHANGE_MUSIC
	JSL BLANK_SCREEN_AND_WAIT_VBLANK
	LDX #1
	TXA
	JSL FADE_IN
	LDA BATTLE_MODE
	BNEL @CHECK_BUZZ_BUZZ
	LDA @LOCAL12
	JSL INITIALIZE_BATTLE_PARTY
	LDA #0
	STA @VIRTUAL02
	TAY
	STY @LOCAL10
	JMP @REINIT_PARTY_CHECK
@REINIT_PARTY_MEMBER:
	REP #PROC_FLAGS::ACCUM8
.IF .DEFINED(JPN)
	TYA
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
.ELSE
	LDA GAME_STATE + game_state::party_members,Y
.ENDIF
	AND #$00FF
	STA @VIRTUAL04
	STA @LOCAL08
	LDA @VIRTUAL04
	BEQ @REINIT_NPC_MEMBER
	LDA @VIRTUAL04
	CMP #4
	BGT @REINIT_NPC_MEMBER
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	TAX
	LDA @VIRTUAL04
	JSL BATTLE_INIT_PLAYER_STATS
	JMP @REINIT_NEXT_MEMBER
@REINIT_NPC_MEMBER:
	LDA @VIRTUAL04
	CMP #5
	BCCL @REINIT_NEXT_MEMBER
	LOADPTR NPC_AI_TABLE, @VIRTUAL06
	LDA @VIRTUAL04
	ASL
.IF .DEFINED(JPN)
	STA @LOCAL09
.ELSE
	STA @LOCAL06
.ENDIF
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	AND #$0001
	BEQ @REINIT_NEXT_MEMBER
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
.IF .DEFINED(JPN)
	STA @LOCAL06
.ELSE
	STA @LOCAL09
.ENDIF
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	TAX
.IF .DEFINED(JPN)
	LDA @LOCAL09
.ELSE
	LDA @LOCAL06
.ENDIF
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	JSL BATTLE_INIT_ENEMY_STATS
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDY #.LOWORD(BATTLERS_TABLE) + battler::row
.IF .DEFINED(JPN)
	STA (@LOCAL06),Y
.ELSE
	STA (@LOCAL09),Y
.ENDIF
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
	ASL
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_npc_1_hp,X
	LDY #.LOWORD(BATTLERS_TABLE) + battler::hp_target
	STA (@LOCAL06),Y
	LDY #.LOWORD(BATTLERS_TABLE) + battler::hp
	STA (@LOCAL06),Y
	INC @VIRTUAL02
	LDX @LOCAL06
	STZ BATTLERS_TABLE+battler::pp_target,X
	LDX @LOCAL06
	STZ BATTLERS_TABLE+battler::pp,X
	LDX @LOCAL06
.ELSE
	TAX
	LDA GAME_STATE+game_state::party_npc_1_hp,X
	LDY #.LOWORD(BATTLERS_TABLE) + battler::hp_target
	STA (@LOCAL09),Y
	LDY #.LOWORD(BATTLERS_TABLE) + battler::hp
	STA (@LOCAL09),Y
	INC @VIRTUAL02
	LDX @LOCAL09
	STZ BATTLERS_TABLE+battler::pp_target,X
	LDX @LOCAL09
	STZ BATTLERS_TABLE+battler::pp,X
	LDX @LOCAL09
.ENDIF
	SEP #PROC_FLAGS::ACCUM8
	STZ BATTLERS_TABLE+battler::ally_or_enemy,X
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	SEP #PROC_FLAGS::ACCUM8
	LDY #.LOWORD(BATTLERS_TABLE) + battler::npc_id
.IF .DEFINED(JPN)
	STA (@LOCAL06),Y
.ELSE
	STA (@LOCAL09),Y
.ENDIF
@REINIT_NEXT_MEMBER:
	LDY @LOCAL10
	INY
	STY @LOCAL10
@REINIT_PARTY_CHECK:
	CPY #6
	BCCL @REINIT_PARTY_MEMBER
	JSL REDIRECT_SHOW_HPPP_WINDOWS
	JSL WINDOW_TICK
@DEBUG_BATTLE_LOOP:
	.A16
	JSL WAIT_UNTIL_NEXT_FRAME
	JSL UPDATE_BATTLE_SCREEN_EFFECTS
	LDA PAD_PRESS
	AND #PAD::START_BUTTON
	BNEL @START_BATTLE_MUSIC
	LDA PAD_PRESS
	AND #PAD::SELECT_BUTTON
	BEQ @DEBUG_CHECK_RIGHT
	LDA CURRENT_BATTLE_GROUP
	JSL ENEMY_SELECT_MODE
	STA @LOCAL10
	STA CURRENT_BATTLE_GROUP
	LOADPTR BTL_ENTRY_BG_TABLE, @VIRTUAL06
	LDA @LOCAL10
	ASL
	ASL
	TAX
	MOVE_INTY @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	STA @LOCAL0E
	TXA
	INC
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
.IF .DEFINED(JPN)
	STA @LOCAL0F
.ELSE
	STA @LOCAL0D
.ENDIF
	LDA @LOCAL10
	ASL
	ASL
	ASL
	CLC
	ADC #battle_entry_ptr_entry::letterbox_style
	TAX
	LDA f:BTL_ENTRY_PTR_TABLE,X
	AND #$00FF
.IF .DEFINED(JPN)
	STA @LOCAL0D
.ELSE
	STA @LOCAL0C
.ENDIF
	JMP @APPLY_DEBUG_PARTY
@DEBUG_CHECK_RIGHT:
	LDA PAD_HELD
	AND #PAD::RIGHT
	BEQ @DEBUG_CHECK_LEFT
	LDA @LOCAL11
	CMP #15
	BCS @DEBUG_CHECK_DOWN
	INC @LOCAL11
	JMP @APPLY_DEBUG_PARTY
@DEBUG_CHECK_LEFT:
	LDA PAD_HELD
	AND #PAD::LEFT
	BEQ @DEBUG_CHECK_DOWN
	LDA @LOCAL11
	CMP #1
	BLTEQ @DEBUG_CHECK_DOWN
	DEC @LOCAL11
	JMP @APPLY_DEBUG_PARTY
@DEBUG_CHECK_DOWN:
	LDA PAD_HELD
	AND #PAD::DOWN
	BEQ @DEBUG_CHECK_UP
	LDA @LOCAL12
	CMP #1
	BLTEQ @DEBUG_CHECK_X
	DEC @LOCAL12
	BRA @APPLY_DEBUG_PARTY
@DEBUG_CHECK_UP:
	LDA PAD_HELD
	AND #PAD::UP
	BEQ @DEBUG_CHECK_X
	LDA @LOCAL12
	CMP #MAX_LEVEL
	BCS @DEBUG_CHECK_X
	INC @LOCAL12
	BRA @APPLY_DEBUG_PARTY
@DEBUG_CHECK_X:
	LDA PAD_PRESS
	AND #PAD::X_BUTTON
	BEQ @DEBUG_CHECK_A
	LDA HIGHEST_ENEMY_LEVEL_IN_BATTLE
	STA @LOCAL12
	BRA @APPLY_DEBUG_PARTY
@DEBUG_CHECK_A:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON
	BEQ @DEBUG_CHECK_B
	LDA DEBUGGING_CURRENT_PSI_ANIMATION
	JSL SHOW_PSI_ANIMATION
	LDX DEBUGGING_CURRENT_PSI_ANIMATION
	INX
	STX DEBUGGING_CURRENT_PSI_ANIMATION
	CPX #34
	BNE @DEBUG_CHECK_B
	STZ DEBUGGING_CURRENT_PSI_ANIMATION
@DEBUG_CHECK_B:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON
	BEQL @DEBUG_BATTLE_LOOP
	LDX DEBUGGING_CURRENT_SWIRL_FLAGS
	LDA DEBUGGING_CURRENT_SWIRL
	JSL INIT_SWIRL_EFFECT
	LDX DEBUGGING_CURRENT_SWIRL
	INX
	STX DEBUGGING_CURRENT_SWIRL
	CPX #8
	BNEL @DEBUG_BATTLE_LOOP
	STZ DEBUGGING_CURRENT_SWIRL
	LDA DEBUGGING_CURRENT_SWIRL_FLAGS
	INC
	AND #$0003
	STA DEBUGGING_CURRENT_SWIRL_FLAGS
	JMP @DEBUG_BATTLE_LOOP
@APPLY_DEBUG_PARTY:
.IF .DEFINED(JPN)
	LDA #0
	STA @LOCAL0B
.ELSE
	LDX #0
.ENDIF
	LDA @LOCAL11
	AND #$0001
	BEQ @ADD_NESS
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA GAME_STATE + game_state::party_members
.IF .DEFINED(JPN)
	REP #PROC_FLAGS::ACCUM8
	LDA #1
	STA @LOCAL0B
.ELSE
	LDX #1
.ENDIF
@ADD_NESS:
.IF .DEFINED(JPN)
	LDA @LOCAL11
	AND #$0002
	BEQ @ADD_PAULA
	LDA @LOCAL0B
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #2
	STA a:game_state::party_members,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL0B
	INC
	STA @LOCAL0B
.ELSE
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL11
	AND #$0002
	BEQ @ADD_PAULA
	SEP #PROC_FLAGS::ACCUM8
	LDA #2
	STA GAME_STATE + game_state::party_members,X
	INX
.ENDIF
@ADD_PAULA:
.IF .DEFINED(JPN)
	LDA @LOCAL11
	AND #$0004
	BEQ @ADD_JEFF
	LDA @LOCAL0B
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #3
	STA a:game_state::party_members,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL0B
	INC
	STA @LOCAL0B
.ELSE
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL11
	AND #$0004
	BEQ @ADD_JEFF
	SEP #PROC_FLAGS::ACCUM8
	LDA #3
	STA GAME_STATE + game_state::party_members,X
	INX
.ENDIF
@ADD_JEFF:
.IF .DEFINED(JPN)
	LDA @LOCAL11
	AND #$0008
	BEQ @ADD_POO
	LDA @LOCAL0B
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #4
	STA a:game_state::party_members,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL0B
	INC
	STA @LOCAL0B
.ELSE
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL11
	AND #$0008
	BEQ @ADD_POO
	SEP #PROC_FLAGS::ACCUM8
	LDA #4
	STA GAME_STATE + game_state::party_members,X
	INX
.ENDIF
@ADD_POO:
.IF .DEFINED(JPN)
	LDA @LOCAL0B
.ELSE
	REP #PROC_FLAGS::ACCUM8
	TXA
.ENDIF
	SEP #PROC_FLAGS::ACCUM8
	STA GAME_STATE+game_state::player_controlled_party_count
	BRA @CLEAR_SLOTS_CHECK
@CLEAR_REMAINING_SLOTS:
	.A16
.IF .DEFINED(JPN) ;wow
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ a:game_state::party_members,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL0B
	INC
	STA @LOCAL0B
.ELSE
	STZ GAME_STATE + game_state::party_members,X
	INX
.ENDIF
@CLEAR_SLOTS_CHECK:
.IF .DEFINED(JPN)
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL0B
	CMP #$0006
.ELSE
	CPX #6
.ENDIF
	BCC @CLEAR_REMAINING_SLOTS
	JMP @REINIT_BATTLE
@START_BATTLE_MUSIC:
	LDA ENEMIES_IN_BATTLE_IDS
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	.A16
	CLC
	ADC #enemy_data::music
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	AND #$00FF
	JSL CHANGE_MUSIC
@CHECK_BUZZ_BUZZ:
	LDA #EVENT_FLAG::FLG_BUNBUN
	JSL GET_EVENT_FLAG
	CMP #0
	BEQ @CHECK_POSSESSED
	LDX #.LOWORD(BATTLERS_TABLE)+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)
	LDA #ENEMY::BUZZ_BUZZ
	JSL BATTLE_INIT_ENEMY_STATS
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA BATTLERS_TABLE+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)+16
	STZ BATTLERS_TABLE+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)+battler::ally_or_enemy
	LDA #ENEMY::BUZZ_BUZZ
	STA BATTLERS_TABLE+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)+battler::npc_id
@CHECK_POSSESSED:
.IF .DEFINED(JPN)
	REP #PROC_FLAGS::ACCUM8
	LDA #0
	STA @LOCAL07
.ELSE
	LDX #0
	STX @LOCAL07
.ENDIF
	BRA @POSSESSED_LOOP_ENTRY
@CHECK_POSSESSED_LOOP:
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
.ELSE
	REP #PROC_FLAGS::ACCUM8
	LDA GAME_STATE + game_state::party_members,X
.ENDIF
	AND #$00FF
	STA @VIRTUAL04
	STA @LOCAL08
	LDA @VIRTUAL04
	BEQ @NEXT_POSSESSED_CHECK
	LDA @VIRTUAL04
	CMP #4
	BGT @NEXT_POSSESSED_CHECK
	LDA @VIRTUAL04
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::afflictions
	TAX
	LDA a:STATUS_GROUP::PERSISTENT_HARDHEAL,X
	AND #$00FF
	CMP #STATUS_1::POSSESSED
	BNE @NEXT_POSSESSED_CHECK
	LDX #.LOWORD(BATTLERS_TABLE)+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)
	LDA #ENEMY::TINY_LIL_GHOST
	JSL BATTLE_INIT_ENEMY_STATS
	SEP #PROC_FLAGS::ACCUM8
	LDA #ENEMY::TINY_LIL_GHOST
	STA BATTLERS_TABLE+(TOTAL_PARTY_COUNT)*.SIZEOF(battler)+battler::npc_id
	BRA @SETUP_ITEM_DROP
@NEXT_POSSESSED_CHECK:
.IF .DEFINED(JPN)
	LDA @LOCAL07
	INC
	STA @LOCAL07
.ELSE
	LDX @LOCAL07
	INX
	STX @LOCAL07
.ENDIF
@POSSESSED_LOOP_ENTRY:
	.A16
.IF .DEFINED(JPN)
	CMP #TOTAL_PARTY_COUNT
.ELSE
	CPX #TOTAL_PARTY_COUNT
.ENDIF
	BCC @CHECK_POSSESSED_LOOP
@SETUP_ITEM_DROP:
	JSL REDIRECT_SHOW_HPPP_WINDOWS
	LDA ENEMIES_IN_BATTLE
	JSR RAND_LIMIT
	.A16
	ASL
	TAX
	LDA ENEMIES_IN_BATTLE_IDS,X
.IF .DEFINED(JPN)
	STA @LOCAL0A
.ELSE
	STA @LOCAL0F
.ENDIF
	LOADPTR ENEMY_CONFIGURATION_TABLE, @VIRTUAL06
.IF .DEFINED(JPN)
	LDA @LOCAL0A
.ELSE
	LDA @LOCAL0F
.ENDIF
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	.A16
.IF .DEFINED(JPN)
	STA @LOCAL0A
.ELSE
	STA @LOCAL0F
.ENDIF
	CLC
	ADC #enemy_data::item_dropped
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	STA ITEM_DROPPED
.IF .DEFINED(JPN)
	LDA @LOCAL0A
.ELSE
	LDA @LOCAL0F
.ENDIF
	CLC
	ADC #enemy_data::item_drop_rate
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	BEQ @RARITY_ZERO
	CMP #1
	BEQ @RARITY_ONE
	CMP #2
	BEQ @RARITY_TWO
	CMP #3
	BEQ @RARITY_THREE
	CMP #4
	BEQ @RARITY_FOUR
	CMP #5
	BEQ @RARITY_FIVE
	CMP #6
	BEQ @RARITY_SIX
	BRA @RARITY_SEVEN
@RARITY_ZERO:
	JSL RAND
	AND #$007F ;1/2
	BEQ @RARITY_SEVEN
	STZ ITEM_DROPPED
	BRA @RARITY_SEVEN
@RARITY_ONE:
	JSL RAND
	AND #$003F ;1/4
	BEQ @RARITY_SEVEN
	STZ ITEM_DROPPED
	BRA @RARITY_SEVEN
@RARITY_TWO:
	JSL RAND
	AND #$001F ;1/8
	BEQ @RARITY_SEVEN
	STZ ITEM_DROPPED
	BRA @RARITY_SEVEN
@RARITY_THREE:
	JSL RAND
	AND #$000F ;1/16
	BEQ @RARITY_SEVEN
	STZ ITEM_DROPPED
	BRA @RARITY_SEVEN
@RARITY_FOUR:
	JSL RAND
	AND #$0007 ;1/32
	BEQ @RARITY_SEVEN
	STZ ITEM_DROPPED
	BRA @RARITY_SEVEN
@RARITY_FIVE:
	JSL RAND
	AND #$0003 ;1/64
	BEQ @RARITY_SEVEN
	STZ ITEM_DROPPED
	BRA @RARITY_SEVEN
@RARITY_SIX:
	JSL RAND
	AND #$0001 ;1/128
	BEQ @RARITY_SEVEN
	STZ ITEM_DROPPED
@RARITY_SEVEN: ;Item dropped or 0% chance of drop occurring
	LDA ITEM_DROPPED
	BNEL @END_ITEM_DROP
	LDX #0
	STX @LOCAL10
	BRA @CONSOLATION_OUTER_LOOP_ENTRY
@CONSOLATION_OUTER_LOOP_BEGIN:
	LDY #8
.IF .DEFINED(JPN)
	STY @LOCAL0A
.ELSE
	STY @LOCAL0F
.ENDIF
	BRA @CONSOLATION_INNER_LOOP_ENTRY
@CONSOLATION_INNER_LOOP_BEGIN:
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	.A16
	STA @LOCAL09
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @ENEMY_NOT_IN_CONSOLATION_TABLE
	LOADPTR CONSOLATION_ITEM_TABLE, @VIRTUAL06
	LDX @LOCAL10
	TXA
	OPTIMIZED_MULT @VIRTUAL04, 9
	STA @VIRTUAL02
	LDA @LOCAL09
	TAX
	LDA @VIRTUAL02
	MOVE_INTY @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	CMP BATTLERS_TABLE + battler::id,X
	BNE @ENEMY_NOT_IN_CONSOLATION_TABLE
	LDA #7
	JSR RAND_LIMIT
	PHA
	LDA @VIRTUAL02
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	STA ITEM_DROPPED
@ENEMY_NOT_IN_CONSOLATION_TABLE:
.IF .DEFINED(JPN)
	LDY @LOCAL0A
	INY
	STY @LOCAL0A
.ELSE
	LDY @LOCAL0F
	INY
	STY @LOCAL0F
.ENDIF
@CONSOLATION_INNER_LOOP_ENTRY:
	CPY #BATTLER_COUNT
	BCC @CONSOLATION_INNER_LOOP_BEGIN
	LDX @LOCAL10
	INX
	STX @LOCAL10
@CONSOLATION_OUTER_LOOP_ENTRY:
	CPX #2
	BCCL @CONSOLATION_OUTER_LOOP_BEGIN
@END_ITEM_DROP:
.IF .DEFINED(JPN)
	STZ @LOCAL09
.ELSE
	STZ @LOCAL06
.ENDIF
	LDA BATTLE_INITIATIVE
	BEQ @AFTER_INITIATIVE
	CMP #1
	BEQ @INITIATIVE_PARTY_FIRST
	CMP #2
	BEQ @INITIATIVE_ENEMIES_FIRST
	BRA @AFTER_INITIATIVE
@INITIATIVE_PARTY_FIRST:
	LDA #INITIATIVE::PARTY_FIRST
.IF .DEFINED(JPN)
	STA @LOCAL09
.ELSE
	STA @LOCAL06
.ENDIF
	BRA @AFTER_INITIATIVE
@INITIATIVE_ENEMIES_FIRST:
	LDA #INITIATIVE::ENEMIES_FIRST
.IF .DEFINED(JPN)
	STA @LOCAL09
.ELSE
	STA @LOCAL06
.ENDIF
@AFTER_INITIATIVE:
	STZ BATTLE_INITIATIVE
	CREATE_WINDOW_FAR #WINDOW::TEXT_BATTLE
	;TODO: why 8?
	LDA #.LOWORD(BATTLERS_TABLE)+8*.SIZEOF(battler)
	STA CURRENT_ATTACKER
	LDA #1
	JSL FIX_ATTACKER_NAME
	LOADPTR ENEMY_CONFIGURATION_TABLE, @VIRTUAL0A
	LDA ENEMIES_IN_BATTLE_IDS
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::encounter_text_ptr
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_IN_BATTLE_TEXT
.IF .DEFINED(JPN)
	LDA @LOCAL09
.ELSE
	LDA @LOCAL06
.ENDIF
	CMP #INITIATIVE::PARTY_FIRST
	BNE @ANNOUNCE_PARTY_FIRST
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_SENSEI_PC
@ANNOUNCE_PARTY_FIRST:
	LDA #0
	STA @LOCAL10
	BRA @ENEMY_STATUS_CHECK
@ANNOUNCE_ENEMY_STATUS:
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)+8*.SIZEOF(battler)
	STA CURRENT_TARGET
	JSL FIX_TARGET_NAME
	LDX CURRENT_TARGET
	LDA a:battler::afflictions+2,X
	AND #$00FF
	CMP #STATUS_2::ASLEEP
	BNE @CHECK_ENEMY_SEALED
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_AT_START_NEMURI
@CHECK_ENEMY_SEALED:
	LDX CURRENT_TARGET
	LDA a:battler::afflictions+4,X
	AND #$00FF
	BEQ @CHECK_ENEMY_STRANGE
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_AT_START_FUUIN
@CHECK_ENEMY_STRANGE:
	LDX CURRENT_TARGET
	LDA a:battler::afflictions+3,X
	AND #$00FF
	CMP #STATUS_3::STRANGE
	BNE @NEXT_ENEMY_STATUS
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_AT_START_HEN
@NEXT_ENEMY_STATUS:
	LDA @LOCAL10
	INC
	STA @LOCAL10
@ENEMY_STATUS_CHECK:
	CMP ENEMIES_IN_BATTLE
	BCC @ANNOUNCE_ENEMY_STATUS
	JSL REDIRECT_CLOSE_FOCUS_WINDOW
.IF .DEFINED(JPN)
	STZ @LOCAL06
	LDA @LOCAL06
.ELSE
	STZ @LOCAL09
	LDA @LOCAL09
.ENDIF
	STA SPECIAL_DEFEAT
	JMP @CHECK_NEW_TURN
@START_TURN:
.IF .DEFINED(JPN)
	INC @LOCAL0B
.ELSE
	INC @LOCAL0A
.ENDIF
	JSL SORT_BATTLERS_INTO_ROWS
	LDY #.LOWORD(BATTLERS_TABLE)
	STY @LOCAL10
	LDX #0
	STX @LOCAL05
	BRA @INITIATIVE_CALC_CHECK
@CALC_INITIATIVE_LOOP:
	TYX
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::has_taken_turn,X
	REP #PROC_FLAGS::ACCUM8
	LDA a:battler::consciousness,Y
	AND #$00FF
	BEQ @NEXT_INITIATIVE_CALC
	TYA
	CLC
	ADC #battler::initiative
	STA @VIRTUAL02
	LDA a:battler::speed,Y
	JSR FIFTY_PERCENT_VARIANCE
	LDX @VIRTUAL02
	STA __BSS_START__,X
	CMP #0
	BNE @NEXT_INITIATIVE_CALC
	LDA #1
	LDX @VIRTUAL02
	STA __BSS_START__,X
@NEXT_INITIATIVE_CALC:
	LDY @LOCAL10
	TYA
	CLC
	ADC #.SIZEOF(battler)
	TAY
	STY @LOCAL10
	LDX @LOCAL05
	INX
	STX @LOCAL05
@INITIATIVE_CALC_CHECK:
	CPX #BATTLER_COUNT
	BCC @CALC_INITIATIVE_LOOP
	LDA #0
	STA @LOCAL10
	BRA @CLEAR_CHAR_UNK94_CHECK
@CLEAR_CHAR_UNK94_LOOP:
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ PARTY_CHARACTERS + char_struct::unknown94,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL10
	INC
	STA @LOCAL10
@CLEAR_CHAR_UNK94_CHECK:
	CMP #4
	BCC @CLEAR_CHAR_UNK94_LOOP
	LDY #0
	STY @LOCAL04
	TYA
	STA @VIRTUAL02
	JMP @PLAYER_MENU_CHECK
@PLAYER_MENU_OUTER:
	JSL CHECK_DEAD_PLAYERS
	LDA #0
	JSL COUNT_CHARS
	CMP #0
	BNE @CHECK_PARTY_MEMBER
	CREATE_WINDOW_FAR #WINDOW::TEXT_BATTLE
	JMP @CHECK_BATTLE_END
@CHECK_PARTY_MEMBER:
.IF .DEFINED(JPN)
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
.ELSE
	LDX @VIRTUAL02
	LDA GAME_STATE + game_state::party_members,X
.ENDIF
	AND #$00FF
	STA @VIRTUAL04
	STA @LOCAL08
	LDA @VIRTUAL04
	BEQL @NEXT_PLAYER_MENU
	LDA @VIRTUAL04
	CMP #4
	BGTL @NEXT_PLAYER_MENU
.IF .DEFINED(JPN)
	LDA @LOCAL09
.ELSE
	LDA @LOCAL06
.ENDIF
	CMP #2
	BEQ @SKIP_MENU
.IF .DEFINED(JPN)
	LDA @LOCAL09
.ELSE
	LDA @LOCAL06
.ENDIF
	CMP #3
	BEQ @SKIP_MENU
.IF .DEFINED(JPN)
	LDA @LOCAL09
.ELSE
	LDA @LOCAL06
.ENDIF
	CMP #4
	BEQ @SKIP_MENU
	LDA @VIRTUAL04
	CMP #4
	BNE @CHECK_INCAPACITATED
	LDA MIRROR_ENEMY
	BNE @SKIP_MENU
@CHECK_INCAPACITATED:
	LDA @VIRTUAL04
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::afflictions
	TAX
	LDA a:STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BEQ @SKIP_MENU
	CMP #STATUS_0::DIAMONDIZED
	BEQ @SKIP_MENU
	LDA a:STATUS_GROUP::TEMPORARY,X
	AND #$00FF
	TAX
	CPX #STATUS_2::ASLEEP
	BEQ @SKIP_MENU
	CPX #STATUS_2::SOLIDIFIED
	BNE @OPEN_BATTLE_MENU
@SKIP_MENU:
	LDA #BATTLE_ACTIONS::NO_EFFECT
	STA @LOCAL07
	SEP #PROC_FLAGS::ACCUM8
	STZ BATTLE_ITEM_USED
	JMP @FIND_BATTLER_SLOT
@OPEN_BATTLE_MENU:
	LDA @VIRTUAL02
	JSL SELECT_BATTLE_MENU_CHARACTER_FAR
	LDY @LOCAL04
	TYX
	LDA @VIRTUAL04
	JSL BATTLE_SELECTION_MENU
	.A16
	STA @LOCAL07
	JSL CLEAR_BATTLE_MENU_CHARACTER_INDICATOR_FAR
	JSL REDIRECT_CLOSE_FOCUS_WINDOW
	LDA BATTLE_MODE
	BEQ @AFTER_BATTLE_MENU
	LDA @LOCAL07
	CMP #$FFFF
	BNE @AFTER_BATTLE_MENU
	STZ @LOCAL03
	JMP @BATTLE_ENDING
@AFTER_BATTLE_MENU:
	LDA @LOCAL07
	CMP #BATTLE_ACTIONS::RUN_AWAY
	BNE @CHECK_MENU_RESULT
	LDA #BATTLE_ACTIONS::USE_NO_EFFECT
	STA @LOCAL07
.IF .DEFINED(JPN)
	LDA @LOCAL09
.ELSE
	LDA @LOCAL06
.ENDIF
	CMP #1
	BNE @RUN_AWAY_NORMAL
	LDA #4
.IF .DEFINED(JPN)
	STA @LOCAL09
.ELSE
	STA @LOCAL06
.ENDIF
	BRA @AFTER_RUN_TYPE
@RUN_AWAY_NORMAL:
	LDA #3
.IF .DEFINED(JPN)
	STA @LOCAL09
.ELSE
	STA @LOCAL06
.ENDIF
@AFTER_RUN_TYPE:
	LDA #1
.IF .DEFINED(JPN)
	STA @LOCAL0C
.ELSE
	STA @LOCAL0B
.ENDIF
@CHECK_MENU_RESULT:
	LDA @LOCAL07
	CMP #$FFFF
	BEQL @REINIT_BATTLE
	CMP #0
	BNE @STORE_ACTION
	LDY @LOCAL04
	BEQL @PLAYER_MENU_OUTER
	DEY
	STY @LOCAL04
	TYA
	ASL
	TAX
	LDA PARTY_MEMBERS_WITH_SELECTED_ACTIONS,X
	STA @VIRTUAL02
	JMP @PLAYER_MENU_OUTER
@STORE_ACTION:
	LDY @LOCAL04
	TYA
	ASL
	TAX
	LDA @VIRTUAL02
	STA PARTY_MEMBERS_WITH_SELECTED_ACTIONS,X
	INY
	STY @LOCAL04
	LDA @LOCAL07
	CMP #1
	BNE @FIND_BATTLER_SLOT
	LDA #0
	STA @LOCAL07
@FIND_BATTLER_SLOT:
	REP #PROC_FLAGS::ACCUM8
	STZ @LOCAL05
	JMP @FIND_SLOT_CHECK
@FIND_SLOT_LOOP:
	LDA @LOCAL05
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQL @NEXT_SLOT
	LDA BATTLERS_TABLE+battler::ally_or_enemy,X
	AND #$00FF
	BNEL @NEXT_SLOT
	LDA @VIRTUAL04
	CMP BATTLERS_TABLE + battler::id,X
	BNEL @NEXT_SLOT
	LDA @LOCAL07
	STA BATTLERS_TABLE+battler::current_action,X
	LDA BATTLE_ITEM_USED
	AND #$00FF
	BEQ @NO_ITEM_USED
	SEP #PROC_FLAGS::ACCUM8
	LDA BATTLE_MENU_SELECTION + battle_menu_selection::param1
	STA BATTLERS_TABLE+7,X
	LDA BATTLE_ITEM_USED
	STA BATTLERS_TABLE+battler::current_action_argument,X
	BRA @AFTER_ITEM_STORE
@NO_ITEM_USED:
	SEP #PROC_FLAGS::ACCUM8
	STZ BATTLERS_TABLE+7,X
	LDA BATTLE_MENU_SELECTION + battle_menu_selection::param1
	STA BATTLERS_TABLE+battler::current_action_argument,X
@AFTER_ITEM_STORE:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL05
	LDY #.SIZEOF(battler)
	JSL MULT168
.IF .DEFINED(JPN)
	TAX
	STX @LOCAL0A
	LDA #.LOWORD(BATTLE_MENU_SELECTION) + battle_menu_selection::targetting
	STA @LOCAL07
	TAX
.ELSE
	STA @LOCAL07
	LDX #.LOWORD(BATTLE_MENU_SELECTION) + battle_menu_selection::targetting
	STX @LOCAL0F
	PHA
.ENDIF
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
.IF .DEFINED(JPN)
	LDX @LOCAL0A
.ELSE
	PLX
.ENDIF
	STA BATTLERS_TABLE + battler::action_targetting,X
.IF .DEFINED(USA)
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	TAX
	SEP #PROC_FLAGS::ACCUM8
.ENDIF
	LDA BATTLE_MENU_SELECTION + battle_menu_selection::selected_target
	STA BATTLERS_TABLE + battler::current_target,X
.IF .DEFINED(JPN)
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	TAX
.ELSE
	LDX @LOCAL0F
	REP #PROC_FLAGS::ACCUM8
.ENDIF
	LDA __BSS_START__,X
	AND #$00FF
	CMP #1
	BNE @AFTER_TARGET
	LDA #0
.IF .DEFINED(JPN)
	STA @LOCAL0A
.ELSE
	STA @LOCAL0F
.ENDIF
	BRA @TARGET_SEARCH_CHECK
@FIND_TARGET_LOOP:
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @NEXT_TARGET_SEARCH
	LDA BATTLERS_TABLE+battler::npc_id,X
	AND #$00FF
	BNE @NEXT_TARGET_SEARCH
	LDA BATTLE_MENU_SELECTION + battle_menu_selection::selected_target
	AND #$00FF
	CMP BATTLERS_TABLE+battler::id,X
	BNE @NEXT_TARGET_SEARCH
	LDA @LOCAL05
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
.IF .DEFINED(JPN)
	LDA @LOCAL0A
.ELSE
	LDA @LOCAL0F
.ENDIF
	SEP #PROC_FLAGS::ACCUM8
	INC
	STA BATTLERS_TABLE+battler::current_target,X
	BRA @AFTER_TARGET
@NEXT_TARGET_SEARCH:
.IF .DEFINED(JPN)
	LDA @LOCAL0A
	INC
	STA @LOCAL0A
.ELSE
	LDA @LOCAL0F
	INC
	STA @LOCAL0F
.ENDIF
@TARGET_SEARCH_CHECK:
	.A16
	CMP #6
	BCC @FIND_TARGET_LOOP
@AFTER_TARGET:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL05
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::current_action,X
	CMP #BATTLE_ACTIONS::GUARD
	BNE @NOT_GUARDING
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA BATTLERS_TABLE+battler::guarding,X
	BRA @NEXT_PLAYER_MENU
@NOT_GUARDING:
	SEP #PROC_FLAGS::ACCUM8
	STZ BATTLERS_TABLE+battler::guarding,X
	BRA @NEXT_PLAYER_MENU
@NEXT_SLOT:
	INC @LOCAL05
@FIND_SLOT_CHECK:
	.A16
	LDA @LOCAL05
	CMP #BATTLER_COUNT
	BCCL @FIND_SLOT_LOOP
@NEXT_PLAYER_MENU:
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL02
@PLAYER_MENU_CHECK:
	LDA @VIRTUAL02
	CMP #6
	BCCL @PLAYER_MENU_OUTER
	LDA #.LOWORD(BATTLERS_TABLE)
.IF .DEFINED(USA)
	STA @VIRTUAL02
.ENDIF
	STA @LOCAL04
	LDY #0
.IF .DEFINED(JPN)
	STY @LOCAL05
.ELSE
	STY @LOCAL07
.ENDIF
	JMP @SELECT_ACTION_CHECK
@SELECT_BATTLER_ACTION:
.IF .DEFINED(JPN)
	LDY #battler::consciousness
	LDA (@LOCAL04),Y
	AND #$00FF
	BEQ @CHECK_POO_MIRROR
	LDY #battler::ally_or_enemy
	LDA (@LOCAL04),Y
.ELSE
	LDX @VIRTUAL02
	LDA a:battler::consciousness,X
	AND #$00FF
	BEQ @CHECK_POO_MIRROR
	LDX @VIRTUAL02
	LDA a:battler::ally_or_enemy,X
.ENDIF
	AND #$00FF
	CMP #1
	BEQ @CHECK_INITIATIVE_SKIP
@CHECK_POO_MIRROR:
.IF .DEFINED(JPN)
	LDY #battler::npc_id
	LDA (@LOCAL04),Y
	AND #$00FF
	BNE @CHECK_INITIATIVE_SKIP
	LDA (@LOCAL04)
.ELSE
	LDX @VIRTUAL02
	LDA a:battler::npc_id,X
	AND #$00FF
	BNE @CHECK_INITIATIVE_SKIP
	LDX @VIRTUAL02
	LDA a:battler::id,X
.ENDIF
	CMP #PARTY_MEMBER::POO
	BNEL @NEXT_BATTLER_ACTION
	LDA MIRROR_ENEMY
	BEQL @NEXT_BATTLER_ACTION
@CHECK_INITIATIVE_SKIP:
.IF .DEFINED(JPN)
	LDA @LOCAL09
.ELSE
	LDA @LOCAL06
.ENDIF
	CMP #1
	BEQ @ENEMY_FIRST_SKIP
.IF .DEFINED(JPN)
	LDA @LOCAL09
.ELSE
	LDA @LOCAL06
.ENDIF
	CMP #4
	BNE @CHECK_PARTY_FIRST_SKIP
@ENEMY_FIRST_SKIP:
.IF .DEFINED(JPN)
	LDY #battler::ally_or_enemy
	LDA (@LOCAL04),Y
	AND #$00FF
	CMP #1
	BNE @CHECK_PARTY_FIRST_SKIP
	LDX @LOCAL04
.ELSE
	LDX @VIRTUAL02
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BNE @CHECK_PARTY_FIRST_SKIP
	LDX @VIRTUAL02
.ENDIF
	STZ a:battler::current_action,X
	JMP @NEXT_BATTLER_ACTION
@CHECK_PARTY_FIRST_SKIP:
.IF .DEFINED(JPN)
	LDA @LOCAL09
	CMP #$0002
	BNE @CHECK_POO_MIRROR_ENEMY
	LDY #battler::ally_or_enemy
	LDA (@LOCAL04),Y
	AND #$00FF
	BNE @CHECK_POO_MIRROR_ENEMY
	LDX @LOCAL04
.ELSE
	LDA @LOCAL06
	CMP #2
	BNE @CHECK_POO_MIRROR_ENEMY
	LDX @VIRTUAL02
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @CHECK_POO_MIRROR_ENEMY
	LDX @VIRTUAL02
.ENDIF
	STZ a:battler::current_action,X
	JMP @NEXT_BATTLER_ACTION
@CHECK_POO_MIRROR_ENEMY:
.IF .DEFINED(JPN)
	LDY #battler::ally_or_enemy
	LDA (@LOCAL04),Y
	AND #$00FF
	BNE @LOAD_ENEMY_CONFIG
	LDA (@LOCAL04)
.ELSE
	LDX @VIRTUAL02
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @LOAD_ENEMY_CONFIG
	LDX @VIRTUAL02
	LDA a:battler::id,X
.ENDIF
	CMP #PARTY_MEMBER::POO
	BNE @LOAD_ENEMY_CONFIG
	LOADPTR ENEMY_CONFIGURATION_TABLE, @VIRTUAL06
	LDA MIRROR_ENEMY
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	BRA @SELECT_ACTION_PATTERN
@LOAD_ENEMY_CONFIG:
	LOADPTR ENEMY_CONFIGURATION_TABLE, @VIRTUAL06
.IF .DEFINED(JPN)
	LDA (@LOCAL04)
.ELSE
	LDX @VIRTUAL02
	LDA a:battler::id,X
.ENDIF
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
@SELECT_ACTION_PATTERN:
	SEP #PROC_FLAGS::ACCUM8
	LDY #enemy_data::action_order
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQ @ACTION_PATTERN_1
	CMP #1
	BEQ @ACTION_PATTERN_2
	CMP #2
	BEQ @ACTION_PATTERN_3
	CMP #3
	BEQ @ACTION_PATTERN_4
	JMP @APPLY_SELECTED_ACTION
@ACTION_PATTERN_1:
	JSL RAND
	AND #$0003
	STA @VIRTUAL04
	STA @LOCAL08
	JMP @APPLY_SELECTED_ACTION
@ACTION_PATTERN_2:
	JSL RAND
	AND #$0007
	BEQ @ACTION_PATTERN_2_4TH
	CMP #1
	BEQ @ACTION_PATTERN_2_3RD
	CMP #2
	BEQ @ACTION_PATTERN_2_2ND
	CMP #3
	BEQ @ACTION_PATTERN_2_2ND
	BRA @ACTION_PATTERN_2_1ST
@ACTION_PATTERN_2_4TH:
	LDA #3
	STA @VIRTUAL04
	STA @LOCAL08
	BRA @APPLY_SELECTED_ACTION
@ACTION_PATTERN_2_3RD:
	LDA #2
	STA @VIRTUAL04
	STA @LOCAL08
	BRA @APPLY_SELECTED_ACTION
@ACTION_PATTERN_2_2ND:
	LDA #1
	STA @VIRTUAL04
	STA @LOCAL08
	BRA @APPLY_SELECTED_ACTION
@ACTION_PATTERN_2_1ST:
	LDA #0
	STA @VIRTUAL04
	STA @LOCAL08
	BRA @APPLY_SELECTED_ACTION
@ACTION_PATTERN_3:
.IF .DEFINED(JPN)
	LDA @LOCAL04
.ELSE
	LDA @VIRTUAL02
.ENDIF
	CLC
	ADC #battler::action_order_var
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL04
	STA @LOCAL08
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	INC
	AND #$0003
	STA __BSS_START__,X
	BRA @APPLY_SELECTED_ACTION
@ACTION_PATTERN_4:
	.A16
.IF .DEFINED(JPN)
	LDA @LOCAL04
.ELSE
	LDA @VIRTUAL02
.ENDIF
	CLC
	ADC #battler::action_order_var
	TAX
	STX @LOCAL10
	LDA __BSS_START__,X
	AND #$00FF
	ASL
.IF .DEFINED(JPN)
	STA @LOCAL0A
.ELSE
	STA @LOCAL0F
.ENDIF
	JSL RAND
.IF .DEFINED(JPN)
	STA @VIRTUAL02
.ELSE
	STA @VIRTUAL04
.ENDIF
	AND #$0001
	STA @VIRTUAL02
.IF .DEFINED(JPN)
	LDA @LOCAL0A
.ELSE
	LDA @LOCAL0F
.ENDIF
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL04
	STA @LOCAL08
	LDX @LOCAL10
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	INC
	AND #$0001
	STA __BSS_START__,X
@APPLY_SELECTED_ACTION:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL04
.IF .DEFINED(USA)
	STA @VIRTUAL02
.ENDIF
	INC
	INC
	INC
	INC
.IF .DEFINED(JPN)
	STA @LOCAL0A
.ELSE
	STA @LOCAL0F
.ENDIF
	TAX
	LDA @LOCAL08
	STA @VIRTUAL04
	ASL
	CLC
	ADC #enemy_data::actions
	MOVE_INTY @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	STA __BSS_START__,X
.IF .DEFINED(JPN)
	LDA @LOCAL04
.ELSE
	LDA @VIRTUAL02
.ENDIF
	CLC
	ADC #8
	TAX
	STX @LOCAL10
	LDA @VIRTUAL04
	CLC
	ADC #enemy_data::action_args
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	STA @VIRTUAL00
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
.IF .DEFINED(JPN)
	LDA @LOCAL0A
.ELSE
	LDA @LOCAL0F
.ENDIF
	TAX
	LDA __BSS_START__,X
	CMP #BATTLE_ACTIONS::ENEMY_EXTENDER
	BNE @CHECK_STEAL_ACTION
.IF .DEFINED(JPN)
	LDY #battler::ally_or_enemy
	LDA (@LOCAL04),Y
.ELSE
	LDX @VIRTUAL02
	LDA a:battler::ally_or_enemy,X
.ENDIF
	AND #$00FF
	BNE @EXTENDER_SET_ID
.IF .DEFINED(JPN)
	LDA (@LOCAL04)
.ELSE
	LDX @VIRTUAL02
	LDA a:battler::id,X
.ENDIF
	CMP #PARTY_MEMBER::POO
	BNE @EXTENDER_SET_ID
	LDA @VIRTUAL00
	AND #$00FF
	STA MIRROR_ENEMY
	JMP @CHECK_POO_MIRROR_ENEMY
@EXTENDER_SET_ID:
.IF .DEFINED(JPN)
	LDY #battler::current_action_argument
	LDA (@LOCAL04),Y
.ELSE
	LDX @VIRTUAL02
	LDA a:battler::current_action_argument,X
.ENDIF
	AND #$00FF
.IF .DEFINED(JPN)
	STA (@LOCAL04)
.ELSE
	LDX @VIRTUAL02
	STA a:battler::id,X
.ENDIF
	JMP @CHECK_POO_MIRROR_ENEMY
@CHECK_STEAL_ACTION:
	CMP #BATTLE_ACTIONS::STEAL
	BNE @CHECK_ON_GUARD
	JSL SELECT_STEALABLE_ITEM
	SEP #PROC_FLAGS::ACCUM8
	LDX @LOCAL10
	STA __BSS_START__,X
.IF .DEFINED(JPN)
	LDX @LOCAL04
.ELSE
	LDX @VIRTUAL02
.ENDIF
	REP #PROC_FLAGS::ACCUM8
	STZ a:battler::initiative,X
@CHECK_ON_GUARD:
.IF .DEFINED(JPN)
	LDY #battler::current_action
	LDA (@LOCAL04),Y
.ELSE
	LDX @VIRTUAL02
	LDA a:battler::current_action,X
.ENDIF
	CMP #BATTLE_ACTIONS::ON_GUARD
	BNE @NOT_DEFENDING
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
.IF .DEFINED(JPN)
	LDY #battler::guarding
	STA (@LOCAL04),Y
.ELSE
	LDX @VIRTUAL02
	STA a:battler::guarding,X
.ENDIF
	BRA @AFTER_GUARD_CHECK
@NOT_DEFENDING:
.IF .DEFINED(JPN)
	LDX @LOCAL04
.ELSE
	LDX @VIRTUAL02
.ENDIF
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::guarding,X
@AFTER_GUARD_CHECK:
	REP #PROC_FLAGS::ACCUM8
.IF .DEFINED(JPN)
	LDA @LOCAL04
.ELSE
	LDA @VIRTUAL02
.ENDIF
	JSL CHOOSE_TARGET
@NEXT_BATTLER_ACTION:
.IF .DEFINED(JPN)
	LDA @LOCAL04
.ELSE
	LDA @VIRTUAL02
.ENDIF
	CLC
	ADC #.SIZEOF(battler)
.IF .DEFINED(USA)
	STA @VIRTUAL02
.ENDIF
	STA @LOCAL04
.IF .DEFINED(JPN)
	LDY @LOCAL05
	INY
	STY @LOCAL05
.ELSE
	LDY @LOCAL07
	INY
	STY @LOCAL07
.ENDIF
@SELECT_ACTION_CHECK:
	CPY #BATTLER_COUNT
	BCCL @SELECT_BATTLER_ACTION
	CREATE_WINDOW_FAR #WINDOW::TEXT_BATTLE
.IF .DEFINED(JPN)
	LDA @LOCAL09
.ELSE
	LDA @LOCAL06
.ENDIF
	CMP #INITIATIVE::ENEMIES_FIRST
	BNE @ANNOUNCE_ENEMY_FIRST
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_SENSEI_MON
@ANNOUNCE_ENEMY_FIRST:
.IF .DEFINED(JPN)
	LDA @LOCAL0C
.ELSE
	LDA @LOCAL0B
.ENDIF
	BEQL @AFTER_RUN_CHECK
	LDY #.LOWORD(BATTLERS_TABLE)
.IF .DEFINED(JPN)
	STY @LOCAL0C
.ELSE
	STY @LOCAL0F
.ENDIF
	STZ @LOCAL05
	LDA #0
	STA @VIRTUAL04
	STA @LOCAL08
	STA @VIRTUAL02
	JMP @RUN_CHECK_ENTRY
@RUN_CHECK_LOOP:
	LDA a:battler::consciousness,Y
	AND #$00FF
	BEQ @NEXT_RUN_CHECK
	LDA a:battler::npc_id,Y
	AND #$00FF
	BNE @NEXT_RUN_CHECK
	LDA a:battler::ally_or_enemy,Y
	AND #$00FF
	CMP #1
	BNE @PLAYER_SPEED_CHECK
	LDA a:battler::id,Y
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::boss
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	AND #$00FF
	BNEL @RUN_FAILED
.IF .DEFINED(JPN)
	LDY @LOCAL0C
.ELSE
	LDY @LOCAL0F
.ENDIF
	LDA a:battler::afflictions,Y
	AND #$00FF
	TAX
	CPX #1
	BEQ @NEXT_RUN_CHECK
	CPX #2
	BEQ @NEXT_RUN_CHECK
	CPX #3
	BEQ @NEXT_RUN_CHECK
	LDA a:battler::afflictions+2,Y
	AND #$00FF
	TAX
	CPX #1
	BEQ @NEXT_RUN_CHECK
	CPX #3
	BEQ @NEXT_RUN_CHECK
	CPX #4
	BEQ @NEXT_RUN_CHECK
	LDA a:battler::speed,Y
	CMP @VIRTUAL04
	BLTEQ @NEXT_RUN_CHECK
	STA @VIRTUAL04
	STA @LOCAL08
	BRA @NEXT_RUN_CHECK
@PLAYER_SPEED_CHECK:
	LDA a:battler::speed,Y
	CMP @LOCAL05
	BLTEQ @NEXT_RUN_CHECK
	STA @LOCAL05
@NEXT_RUN_CHECK:
	TYA
	CLC
	ADC #.SIZEOF(battler)
	TAY
.IF .DEFINED(JPN)
	STY @LOCAL0C
.ELSE
	STY @LOCAL0F
.ENDIF
	INC @VIRTUAL02
@RUN_CHECK_ENTRY:
	LDA @VIRTUAL02
	CMP #BATTLER_COUNT
	BCCL @RUN_CHECK_LOOP
	LDA @VIRTUAL04
	BEQ @RUN_SUCCESS
.IF .DEFINED(JPN)
	LDA @LOCAL09
.ELSE
	LDA @LOCAL06
.ENDIF
	CMP #4
	BEQ @RUN_SUCCESS
.IF .DEFINED(JPN)
	LDA @LOCAL0B
.ELSE
	LDA @LOCAL0A
.ENDIF
	OPTIMIZED_MULT @VIRTUAL04, 10
	CLC
	ADC @LOCAL05
	TAX
.IF .DEFINED(JPN)
	STX @LOCAL0C
.ELSE
	STX @LOCAL0F
.ENDIF
	LDA @LOCAL08
	STA @VIRTUAL04
	TXA
	CMP @VIRTUAL04
	BCC @RUN_FAILED
	LDA #100
	JSR RAND_LIMIT
.IF .DEFINED(JPN)
	STA @LOCAL0A
	LDX @LOCAL0C
.ELSE
	STA @LOCAL0B
	LDX @LOCAL0F
.ENDIF
	TXA
	SEC
	SBC @VIRTUAL04
	STA @VIRTUAL02
.IF .DEFINED(JPN)
	LDA @LOCAL0A
.ELSE
	LDA @LOCAL0B
.ENDIF
	CMP @VIRTUAL02
	BCS @RUN_FAILED
@RUN_SUCCESS:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_PLAYER_FLEE
	STZ @LOCAL03
	JMP @BATTLE_ENDING
@RUN_FAILED:
.IF .DEFINED(JPN)
	STZ @LOCAL0C
.ELSE
	STZ @LOCAL0B
.ENDIF
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_PLAYER_FLEE_NG
@AFTER_RUN_CHECK:
.IF .DEFINED(JPN)
	STZ @LOCAL09
.ELSE
	STZ @LOCAL06
.ENDIF
	JMP @CHECK_TURN_CONTINUE
@EXECUTE_TURNS:
	JSL CHECK_DEAD_PLAYERS
	LDA #0
	JSL COUNT_CHARS
	CMP #0
	BEQL @CHECK_BATTLE_END
	LDA #1
	JSL COUNT_CHARS
	CMP #0
	BEQL @CHECK_BATTLE_END
	LDA #$FFFF
	STA @VIRTUAL04
	STA @LOCAL08
.IF .DEFINED(JPN)
	LDY #$0000
	STY @LOCAL05
	TYA
.ELSE
	LDX #0
	TXA
.ENDIF
	STA @LOCAL10
	BRA @ATTACKER_SEARCH_CHECK
@FIND_ATTACKER_LOOP:
	LDY #.SIZEOF(battler)
	JSL MULT168
.IF .DEFINED(JPN)
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @NEXT_ATTACKER_SEARCH
	LDA BATTLERS_TABLE+13,X
	AND #$00FF
	BNE @NEXT_ATTACKER_SEARCH
	LDA BATTLERS_TABLE+70,X
	TAX
	LDY @LOCAL05
	STY @VIRTUAL02
	TXA
.ELSE
	TAY
	LDA BATTLERS_TABLE+battler::consciousness,Y
	AND #$00FF
	BEQ @NEXT_ATTACKER_SEARCH
	LDA BATTLERS_TABLE+13,Y
	AND #$00FF
	BNE @NEXT_ATTACKER_SEARCH
	LDA BATTLERS_TABLE+70,Y
	TAY
	STX @VIRTUAL02
	TYA
.ENDIF
	CMP @VIRTUAL02
	BCC @NEXT_ATTACKER_SEARCH
	LDA @LOCAL10
	STA @VIRTUAL04
	STA @LOCAL08
.IF .DEFINED(JPN)
	TXY
	STY @LOCAL05
.ELSE
	TYX
.ENDIF
@NEXT_ATTACKER_SEARCH:
	LDA @LOCAL10
	INC
	STA @LOCAL10
@ATTACKER_SEARCH_CHECK:
	CMP #BATTLER_COUNT
	BCC @FIND_ATTACKER_LOOP
	LDA @VIRTUAL04
	CMP #$FFFF
	BEQL @CLOSE_BATTLE_WINDOW
	JSL CLEAR_FOCUS_WINDOW_CONTENT_FAR
	LDA @VIRTUAL04
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	TAX
	STX CURRENT_ATTACKER
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA a:battler::has_taken_turn,X
	LDX CURRENT_ATTACKER
	REP #PROC_FLAGS::ACCUM8
	LDA a:battler::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	TAX
	CPX #STATUS_0::UNCONSCIOUS
	BEQL @CHECK_TURN_CONTINUE
	CPX #STATUS_0::DIAMONDIZED
	BEQL @CHECK_TURN_CONTINUE
	CPX #STATUS_0::PARALYZED
	BEQ @PARALYZED_OR_IMMOBILIZED
	LDX CURRENT_ATTACKER
	LDA a:battler::afflictions + STATUS_GROUP::TEMPORARY,X
	AND #$00FF
	CMP #STATUS_2::IMMOBILIZED
	BNEL @CHECK_ASLEEP
@PARALYZED_OR_IMMOBILIZED:
	LDX CURRENT_ATTACKER
	INX
	INX
	INX
	INX
.IF .DEFINED(JPN)
	STX @LOCAL0A
.ELSE
	STX @LOCAL0F
.ENDIF
	LDA __BSS_START__,X
	STA @LOCAL10
	OPTIMIZED_MULT @VIRTUAL04, 12
	TAX
	INX
	INX
	LDA f:BATTLE_ACTION_TABLE,X
	AND #$00FF
	CMP #ACTION_TYPE::PSI
	BEQ @CHECK_ASLEEP
	LDA @LOCAL10
	CMP #BATTLE_ACTIONS::PRAY
	BEQ @CHECK_ASLEEP
	CMP #BATTLE_ACTIONS::FINAL_PRAYER_1
	BEQ @CHECK_ASLEEP
	CMP #BATTLE_ACTIONS::FINAL_PRAYER_2
	BEQ @CHECK_ASLEEP
	CMP #BATTLE_ACTIONS::FINAL_PRAYER_3
	BEQ @CHECK_ASLEEP
	CMP #BATTLE_ACTIONS::FINAL_PRAYER_4
	BEQ @CHECK_ASLEEP
	CMP #BATTLE_ACTIONS::FINAL_PRAYER_5
	BEQ @CHECK_ASLEEP
	CMP #BATTLE_ACTIONS::FINAL_PRAYER_6
	BEQ @CHECK_ASLEEP
	CMP #BATTLE_ACTIONS::FINAL_PRAYER_7
	BEQ @CHECK_ASLEEP
	CMP #BATTLE_ACTIONS::FINAL_PRAYER_8
	BEQ @CHECK_ASLEEP
	CMP #BATTLE_ACTIONS::FINAL_PRAYER_9
	BEQ @CHECK_ASLEEP
	CMP #BATTLE_ACTIONS::SPY
	BEQ @CHECK_ASLEEP
	CMP #BATTLE_ACTIONS::MIRROR
	BEQ @CHECK_ASLEEP
	CMP #BATTLE_ACTIONS::NO_EFFECT
	BEQ @CHECK_ASLEEP
	LDX CURRENT_ATTACKER
	LDA a:battler::afflictions+STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	CMP #STATUS_0::PARALYZED
	BNE @SET_PARALYZED_ACTION
	LDA #BATTLE_ACTIONS::ACTION_252
.IF .DEFINED(JPN)
	LDX @LOCAL0A
.ELSE
	LDX @LOCAL0F
.ENDIF
	STA __BSS_START__,X ;battler::current_action
	BRA @CLEAR_ACTION_ITEM
@SET_PARALYZED_ACTION:
	LDA #BATTLE_ACTIONS::ACTION_254
.IF .DEFINED(JPN)
	LDX @LOCAL0A
.ELSE
	LDX @LOCAL0F
.ENDIF
	STA __BSS_START__,X ;battler::current_action
@CLEAR_ACTION_ITEM:
	LDX CURRENT_ATTACKER
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::action_item_slot,X
@CHECK_ASLEEP:
	LDX CURRENT_ATTACKER
	REP #PROC_FLAGS::ACCUM8
	LDA a:battler::afflictions + STATUS_GROUP::TEMPORARY,X
	AND #$00FF
	CMP #STATUS_2::ASLEEP
	BNE @CHECK_SOLIDIFIED
	LDX CURRENT_ATTACKER
	INX
	INX
	INX
	INX
	LDA __BSS_START__,X ;battler::current_action
	BEQ @CHECK_SOLIDIFIED
	LDA #BATTLE_ACTIONS::ACTION_253
	STA __BSS_START__,X ;battler::current_action
	LDX CURRENT_ATTACKER
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::action_item_slot,X
@CHECK_SOLIDIFIED:
	LDX CURRENT_ATTACKER
	REP #PROC_FLAGS::ACCUM8
	LDA a:battler::afflictions + STATUS_GROUP::TEMPORARY,X
	AND #$00FF
	CMP #STATUS_2::SOLIDIFIED
	BNE @CHECK_CONCENTRATION
	LDX CURRENT_ATTACKER
	INX
	INX
	INX
	INX
	LDA __BSS_START__,X ;battler::current_action
	BEQ @CHECK_CONCENTRATION
	LDA #BATTLE_ACTIONS::ACTION_255
	STA __BSS_START__,X ;battler::current_action
	LDX CURRENT_ATTACKER
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::afflictions+STATUS_GROUP::TEMPORARY,X
	LDX CURRENT_ATTACKER
	STZ a:battler::action_item_slot,X
@CHECK_CONCENTRATION:
	LDX CURRENT_ATTACKER
	REP #PROC_FLAGS::ACCUM8
	LDA a:battler::afflictions+STATUS_GROUP::CONCENTRATION,X
	AND #$00FF
	BEQ @CHECK_HOMESICK
	LDX CURRENT_ATTACKER
	INX
	INX
	INX
	INX
.IF .DEFINED(JPN)
	STX @LOCAL0A
.ELSE
	STX @LOCAL0F
.ENDIF
	LDA __BSS_START__,X ;battler::current_action
	STA @LOCAL10
	OPTIMIZED_MULT @VIRTUAL04, 12
	TAX
	INX
	INX
	LDA f:BATTLE_ACTION_TABLE,X
	AND #$00FF
	CMP #ACTION_TYPE::PSI
	BNE @CHECK_HOMESICK
	LDA @LOCAL10
	BEQ @CHECK_HOMESICK
	LDA #BATTLE_ACTIONS::ACTION_256
.IF .DEFINED(JPN)
	LDX @LOCAL0A
.ELSE
	LDX @LOCAL0F
.ENDIF
	STA __BSS_START__,X ;battler::current_action
@CHECK_HOMESICK:
	LDX CURRENT_ATTACKER
	LDA a:battler::afflictions+STATUS_GROUP::HOMESICKNESS,X
	AND #$00FF
	CMP #STATUS_5::HOMESICK
	BNE @LOOKUP_ACTION
	LDX CURRENT_ATTACKER
	LDA a:battler::current_action,X
	BEQ @LOOKUP_ACTION
	JSL RAND
	AND #$0007
	BNE @LOOKUP_ACTION
	LDA #BATTLE_ACTIONS::ACTION_251
	LDX CURRENT_ATTACKER
	STA a:battler::current_action,X
	LDX CURRENT_ATTACKER
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::action_item_slot,X
@LOOKUP_ACTION:
	REP #PROC_FLAGS::ACCUM8
	LOADPTR BATTLE_ACTION_TABLE, @VIRTUAL06
	LDX CURRENT_ATTACKER
	LDA a:battler::current_action,X
	OPTIMIZED_MULT @VIRTUAL04, 12
.IF .DEFINED(JPN)
	STA @LOCAL0A
.ELSE
	STA @LOCAL0F
.ENDIF
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	CMP #1
	BNE @AFTER_SELF_TARGET
.IF .DEFINED(JPN)
	LDA @LOCAL0A
.ELSE
	LDA @LOCAL0F
.ENDIF
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	BNE @AFTER_SELF_TARGET
	LDX CURRENT_ATTACKER
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @SET_ENEMY_SELF_TARGET
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	LDX CURRENT_ATTACKER
	STA a:battler::action_targetting,X
	LDY #.SIZEOF(battler)
	REP #PROC_FLAGS::ACCUM8
	LDA CURRENT_ATTACKER
	SEC
	SBC #.LOWORD(BATTLERS_TABLE)
	JSL DIVISION16S_DIVISOR_POSITIVE
	SEP #PROC_FLAGS::ACCUM8
	INC
	LDX CURRENT_ATTACKER
	STA a:battler::current_target,X
	BRA @AFTER_SELF_TARGET
@SET_ENEMY_SELF_TARGET:
	SEP #PROC_FLAGS::ACCUM8
	LDA #17
	LDX CURRENT_ATTACKER
	STA a:battler::action_targetting,X
	LDY #.SIZEOF(battler)
	REP #PROC_FLAGS::ACCUM8
	LDA CURRENT_ATTACKER
	SEC
	SBC #.LOWORD(BATTLERS_TABLE)
	JSL DIVISION16S_DIVISOR_POSITIVE
	TAX
	LDA CURRENT_ATTACKER
	JSL SET_BATTLER_TARGET
@AFTER_SELF_TARGET:
	LDX #0
.IF .DEFINED(JPN)
	STX @LOCAL10
.ELSE
	STX @LOCAL0F
.ENDIF
	REP #PROC_FLAGS::ACCUM8
	LDA CURRENT_ATTACKER
	STA CURRENT_TARGET
	TXA
	JSL FIX_ATTACKER_NAME
	JSL FIX_TARGET_NAME
	LDX CURRENT_ATTACKER
	LDA a:battler::afflictions+STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	CMP #STATUS_0::NAUSEOUS
	BEQ @NAUSEOUS_DAMAGE
	CMP #STATUS_0::POISONED
	BEQ @POISONED_DAMAGE
	CMP #STATUS_0::SUNSTROKE
	BEQ @SUNSTROKE_DAMAGE
	CMP #STATUS_0::COLD
	BEQ @COLD_DAMAGE
	JMP @APPLY_STATUS_DAMAGE
@NAUSEOUS_DAMAGE:
	LDA #20
	JSR TWENTY_FIVE_PERCENT_VARIANCE
	TAX
.IF .DEFINED(JPN)
	STX @LOCAL10
.ELSE
	STX @LOCAL0F
.ENDIF
	LOADPTR MSG_BTL_KIMOCHI_DAMAGE, @LOCAL00
	TXA
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	BRA @APPLY_STATUS_DAMAGE
@POISONED_DAMAGE:
	LDA #20
	JSR TWENTY_FIVE_PERCENT_VARIANCE
	TAX
.IF .DEFINED(JPN)
	STX @LOCAL10
.ELSE
	STX @LOCAL0F
.ENDIF
	LOADPTR MSG_BTL_MODOKU_DAMAGE, @LOCAL00
	TXA
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	BRA @APPLY_STATUS_DAMAGE
@SUNSTROKE_DAMAGE:
	LDA #4
	JSR TWENTY_FIVE_PERCENT_VARIANCE
	TAX
.IF .DEFINED(JPN)
	STX @LOCAL10
.ELSE
	STX @LOCAL0F
.ENDIF
	LOADPTR MSG_BTL_NISSHA_DAMAGE, @LOCAL00
	TXA
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	BRA @APPLY_STATUS_DAMAGE
@COLD_DAMAGE:
	LDA #4
	JSR TWENTY_FIVE_PERCENT_VARIANCE
	TAX
.IF .DEFINED(JPN)
	STX @LOCAL10
.ELSE
	STX @LOCAL0F
.ENDIF
	LOADPTR MSG_BTL_KAZE_DAMAGE, @LOCAL00
	TXA
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
@APPLY_STATUS_DAMAGE:
.IF .DEFINED(JPN)
	LDX @LOCAL10
.ELSE
	LDX @LOCAL0F
.ENDIF
	LDA CURRENT_ATTACKER
	JSL LOSE_HP_STATUS
	LDX CURRENT_ATTACKER
	LDA a:battler::hp,X
	BNE @ATTACKER_ALIVE
	LDA CURRENT_ATTACKER
	JSL KO_TARGET
	LDA #0
	JSL COUNT_CHARS
	CMP #0
	BEQL @CHECK_BATTLE_END
	LDA #1
	JSL COUNT_CHARS
	CMP #0
	BNEL @CHECK_TURN_CONTINUE
	JMP @CHECK_BATTLE_END
@ATTACKER_ALIVE:
	LDX CURRENT_ATTACKER
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BNE @SET_ACTION_TARGETS
	LDA CURRENT_ATTACKER
	JSL CHOOSE_TARGET
	LDX CURRENT_ATTACKER
	LDA a:battler::current_action,X
	CMP #BATTLE_ACTIONS::STEAL
	BNE @SET_ACTION_TARGETS
	JSL SELECT_STEALABLE_ITEM
	SEP #PROC_FLAGS::ACCUM8
	LDX CURRENT_ATTACKER
	STA a:battler::current_action_argument,X
@SET_ACTION_TARGETS:
	REP #PROC_FLAGS::ACCUM8
	LDA CURRENT_ATTACKER
	JSL SET_BATTLER_TARGETS_BY_ACTION
	LDX CURRENT_ATTACKER
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @CHECK_MUSHROOMIZED
	LDX CURRENT_ATTACKER
	LDA a:battler::current_action,X
	OPTIMIZED_MULT @VIRTUAL04, 12
	TAX
	LDA f:BATTLE_ACTION_TABLE,X
	AND #$00FF
	BNE @CHECK_MUSHROOMIZED
	JSL REMOVE_STATUS_UNTARGETTABLE_TARGETS
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	MOVE_INT BATTLER_TARGET_FLAGS, @VIRTUAL06
	CMP @VIRTUAL0A+2
	BNE @CHECK_NULL_TARGETS
	LDA @VIRTUAL06
	CMP @VIRTUAL0A
@CHECK_NULL_TARGETS:
	BNE @CHECK_MUSHROOMIZED
	LDA CURRENT_ATTACKER
	JSL CHOOSE_TARGET
	LDA CURRENT_ATTACKER
	JSL SET_BATTLER_TARGETS_BY_ACTION
	JSL REMOVE_STATUS_UNTARGETTABLE_TARGETS
@CHECK_MUSHROOMIZED:
	LDY #0
	STY @LOCAL10
	LDX CURRENT_ATTACKER
	LDA a:battler::afflictions+STATUS_GROUP::PERSISTENT_HARDHEAL,X
	AND #$00FF
	CMP #STATUS_1::MUSHROOMIZED
	BNE @CHECK_STRANGE_STATUS
	LDA #100
	JSR RAND_LIMIT
	CMP #MUSHROOMIZED_TARGET_CHANGE_CHANCE
	BCC @STRANGE_RETARGET
@CHECK_STRANGE_STATUS:
	LDX CURRENT_ATTACKER
	LDA a:battler::afflictions+STATUS_GROUP::STRANGENESS,X
	AND #$00FF
	CMP #STATUS_3::STRANGE
	BNE @CHECK_STEAL_VALIDITY
@STRANGE_RETARGET:
	LDX CURRENT_ATTACKER
	LDA a:battler::current_action,X
	OPTIMIZED_MULT @VIRTUAL04, 12
	TAX
	INX
	LDA f:BATTLE_ACTION_TABLE,X
	AND #$00FF
	BEQ @CHECK_STEAL_VALIDITY
	LDY #1
	STY @LOCAL10
@RETARGET_LOOP:
	JSR FEELING_STRANGE_RETARGETTING
	JSL REMOVE_STATUS_UNTARGETTABLE_TARGETS
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	MOVE_INT BATTLER_TARGET_FLAGS, @VIRTUAL06
	CMP @VIRTUAL0A+2
	BNE @CHECK_RETARGET_NULL
	LDA @VIRTUAL06
	CMP @VIRTUAL0A
@CHECK_RETARGET_NULL:
	BEQ @RETARGET_LOOP
@CHECK_STEAL_VALIDITY:
	LDX CURRENT_ATTACKER
	LDA a:battler::current_action,X
	CMP #BATTLE_ACTIONS::STEAL
	BNE @PREPARE_ACTION
	LDX CURRENT_ATTACKER
	LDA a:battler::current_action_argument,X
	AND #$00FF
	JSL IS_ITEM_STEALABLE
	CMP #0
	BNE @PREPARE_ACTION
	LDX CURRENT_ATTACKER
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::current_action_argument,X
@PREPARE_ACTION:
	REP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL FIX_ATTACKER_NAME
	LDX CURRENT_ATTACKER
	SEP #PROC_FLAGS::ACCUM8
	LDA a:battler::current_action_argument,X
	JSL SET_CURRENT_ITEM_FAR
	JSL SET_TARGET_IF_TARGETED
	.A16
	LDX CURRENT_ATTACKER
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @CHECK_PP_COST
	LDX CURRENT_ATTACKER
	LDA a:battler::id,X
	CMP #PLAYER_CHAR_COUNT
	BGT @CHECK_PP_COST
.IF .DEFINED(JPN)
	LDA #$0000
	STA @LOCAL0A
.ELSE
	LDX #0
	STX @LOCAL0F
.ENDIF
	BRA @PARTY_SLOT_CHECK
@FIND_PARTY_SLOT_LOOP:
	LDX CURRENT_ATTACKER
	LDA a:battler::id,X
	STA @VIRTUAL02
.IF .DEFINED(JPN)
	LDA @LOCAL0A
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
.ELSE
	LDX @LOCAL0F
	LDA GAME_STATE + game_state::party_members,X
.ENDIF
	AND #$00FF
	CMP @VIRTUAL02
	BNE @NEXT_PARTY_SLOT
.IF .DEFINED(JPN)
	LDA @LOCAL0A
.ELSE
	TXA
.ENDIF
	JSL SELECT_BATTLE_MENU_CHARACTER_FAR
	BRA @CHECK_PP_COST
@NEXT_PARTY_SLOT:
.IF .DEFINED(JPN)
	LDA @LOCAL0A
	INC
	STA @LOCAL0A
.ELSE
	INX
	STX @LOCAL0F
.ENDIF
@PARTY_SLOT_CHECK:
.IF .DEFINED(JPN)
	CMP #$0006
.ELSE
	CPX #6
.ENDIF
	BCC @FIND_PARTY_SLOT_LOOP
@CHECK_PP_COST:
	.A16
	LDX CURRENT_ATTACKER
	LDA a:battler::current_action,X
	OPTIMIZED_MULT @VIRTUAL04, 12
	TAX
	INX
	INX
	INX
	LDA f:BATTLE_ACTION_TABLE,X
	AND #$00FF
	BEQ @CHECK_ENEMY_PALETTE
	AND #$00FF
	LDX CURRENT_ATTACKER
	CMP a:battler::pp_target,X
	BLTEQ @DEDUCT_PP
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_PSI_CANNOT
	JMP @AFTER_ACTION
@DEDUCT_PP:
	TAX
	LDA CURRENT_ATTACKER
	JSL SET_BATTLER_PP_FROM_TARGET
@CHECK_ENEMY_PALETTE:
	LDX CURRENT_ATTACKER
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BNE @CHECK_STATUS_TEXT
	LDX CURRENT_ATTACKER
	LDA a:battler::current_action,X
	BEQ @CHECK_STATUS_TEXT
	OPTIMIZED_MULT @VIRTUAL04, 12
	TAX
	INX
	INX
	LDA f:BATTLE_ACTION_TABLE,X ;battle_action::type
	AND #$00FF
	CMP #ACTION_TYPE::PHYSICAL
	BEQ @PALETTE_PHYSICAL
	CMP #ACTION_TYPE::PIERCING_PHYSICAL
	BEQ @PALETTE_PHYSICAL
	CMP #ACTION_TYPE::PSI
	BEQ @PALETTE_PSI
	CMP #ACTION_TYPE::OTHER
	BEQ @PALETTE_OTHER
	BRA @ANIMATE_ATTACKER
@PALETTE_PHYSICAL:
	LDA #1
	JSL LOAD_ATTACK_PALETTE
	BRA @ANIMATE_ATTACKER
@PALETTE_PSI:
	LDA #2
	JSL LOAD_ATTACK_PALETTE
	BRA @ANIMATE_ATTACKER
@PALETTE_OTHER:
	LDA #3
	JSL LOAD_ATTACK_PALETTE
@ANIMATE_ATTACKER:
	SEP #PROC_FLAGS::ACCUM8
	LDA #12
	LDX CURRENT_ATTACKER
	STA a:battler::shake_timer,X
	LDX #0
	STX @LOCAL07
	BRA @ANIMATE_WAIT_CHECK
@ANIMATE_WAIT_LOOP:
	JSL WINDOW_TICK
	LDX @LOCAL07
	INX
	STX @LOCAL07
@ANIMATE_WAIT_CHECK:
	CPX #12
	BCC @ANIMATE_WAIT_LOOP
@CHECK_STATUS_TEXT:
	LDY @LOCAL10
	BEQ @DISPLAY_ACTION_TEXT
	LDX CURRENT_ATTACKER
	REP #PROC_FLAGS::ACCUM8
	LDA a:battler::afflictions+STATUS_GROUP::STRANGENESS,X
	AND #$00FF
	CMP #STATUS_3::STRANGE
	BNE @CHECK_MUSHROOM_TEXT
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_RND_ACT_HEN
@CHECK_MUSHROOM_TEXT:
	LDX CURRENT_ATTACKER
	LDA a:battler::afflictions+STATUS_GROUP::PERSISTENT_HARDHEAL,X
	AND #$00FF
	CMP #STATUS_1::MUSHROOMIZED
	BNE @DISPLAY_ACTION_TEXT
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_RND_ACT_KINOKO
@DISPLAY_ACTION_TEXT:
	REP #PROC_FLAGS::ACCUM8
	LOADPTR BATTLE_ACTION_TABLE, @VIRTUAL0A
	LDX CURRENT_ATTACKER
	LDA a:battler::current_action,X
	OPTIMIZED_MULT @VIRTUAL04, 12
	INC
	INC
	INC
	INC
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT_WITH_PROMPT
	LDX CURRENT_ATTACKER
	LDA a:battler::current_action,X
	BEQL @AFTER_ACTION
	BRA @CHECK_PSI_DONE
@WAIT_PSI_ANIMATION:
	JSL WINDOW_TICK
@CHECK_PSI_DONE:
	JSL IS_PSI_ANIMATION_ACTIVE
	CMP #0
	BNE @WAIT_PSI_ANIMATION
	LDY #0
	STY @LOCAL05
	JMP @TARGET_LOOP_CHECK
@APPLY_TO_TARGET:
	TYA
	JSL IS_CHAR_TARGETTED
	CMP #0
	BEQL @NEXT_TARGET
	LDY @LOCAL05
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	STA CURRENT_TARGET
	JSL FIX_TARGET_NAME
	LDX CURRENT_TARGET
	LDA a:battler::afflictions+STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BNE @EXECUTE_ACTION_CALLBACK
.IF .DEFINED(JPN)
	LDX #$0000
	STX @LOCAL10
.ELSE
	LDA #0
	STA @LOCAL0F
.ENDIF
	BRA @DEAD_TARGET_ACTION_CHECK
@CHECK_DEAD_TARGET_ACTION:
.IF .DEFINED(USA)
	TXA
.ENDIF
	LDX CURRENT_ATTACKER
	CMP a:battler::current_action,X
	BEQ @EXECUTE_ACTION_CALLBACK
.IF .DEFINED(JPN)
	LDX @LOCAL10
	INX
	STX @LOCAL10
.ELSE
	LDA @LOCAL0F
	INC
	STA @LOCAL0F
.ENDIF
@DEAD_TARGET_ACTION_CHECK:
.IF .DEFINED(JPN)
	TXA
	ASL
	TAX
	LDA f:DEAD_TARGETTABLE_ACTIONS,X
.ELSE
	ASL
	TAX
	LDA f:DEAD_TARGETTABLE_ACTIONS,X
	TAX
.ENDIF
	BNE @CHECK_DEAD_TARGET_ACTION
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_NOT_EXIST
	JMP @NEXT_TARGET
@EXECUTE_ACTION_CALLBACK:
	LOADPTR BATTLE_ACTION_TABLE, @VIRTUAL0A
	LDX CURRENT_ATTACKER
	LDA a:battler::current_action,X
	OPTIMIZED_MULT @VIRTUAL04, 12
	CLC
	ADC #8
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BEQ @NEXT_TARGET
	PHA
	MOVE_INT @VIRTUAL06, TEMP_FUNCTION_POINTER
	PLA
	JSL JUMP_TEMP_FUNCTION_POINTER
	JSL CHECK_DEAD_PLAYERS
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA REDRAW_ALL_WINDOWS
	REP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL COUNT_CHARS
	CMP #0
	BEQ @ALL_PARTY_DEAD
	LDA #1
	JSL COUNT_CHARS
	CMP #0
	BNE @CHECK_SPECIAL_DEFEAT
@ALL_PARTY_DEAD:
	JSL CONSUME_USED_BATTLE_ITEM
	JMP @CHECK_BATTLE_END
@CHECK_SPECIAL_DEFEAT:
	LDA SPECIAL_DEFEAT
	CMP #3
	BEQ @SPECIAL_DEFEAT_FLEE
	CMP #2
	BEQ @SPECIAL_DEFEAT_ENEMIES
	CMP #1
	BEQ @SPECIAL_DEFEAT_CODE2
	BRA @CHECK_SCREEN_EFFECT
@SPECIAL_DEFEAT_FLEE:
	STZ @LOCAL03
	JMP @BATTLE_ENDING
@SPECIAL_DEFEAT_ENEMIES:
	JSL CONSUME_USED_BATTLE_ITEM
	JMP @ENEMIES_ARE_DEAD
@SPECIAL_DEFEAT_CODE2:
	LDA #2
	STA @LOCAL03
	JMP @BATTLE_ENDING
@WAIT_SCREEN_EFFECT:
	JSL WINDOW_TICK
@CHECK_SCREEN_EFFECT:
	LDA SCREEN_EFFECT_MINIMUM_WAIT_FRAMES
	BNE @WAIT_SCREEN_EFFECT
@NEXT_TARGET:
	LDY @LOCAL05
	INY
	STY @LOCAL05
@TARGET_LOOP_CHECK:
	CPY #BATTLER_COUNT
	BCCL @APPLY_TO_TARGET
@AFTER_ACTION:
	LDX CURRENT_ATTACKER
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @POST_ACTION_STATUS
	JSL CONSUME_USED_BATTLE_ITEM
	LDA MIRROR_ENEMY
	BEQ @CLEAR_MENU_INDICATOR
	LDX CURRENT_ATTACKER
	LDA a:battler::id,X
	CMP #PARTY_MEMBER::POO
	BNE @CLEAR_MENU_INDICATOR
	LDX MIRROR_TURN_TIMER
	DEX
	STX MIRROR_TURN_TIMER
	BNE @CLEAR_MENU_INDICATOR
	STZ MIRROR_ENEMY
	LDA CURRENT_ATTACKER
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	PROMOTENEARPTR MIRROR_BATTLER_BACKUP, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL COPY_MIRROR_DATA
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_NEUTRALIZE_METAMORPH
@CLEAR_MENU_INDICATOR:
	JSL CLEAR_BATTLE_MENU_CHARACTER_INDICATOR_FAR
@POST_ACTION_STATUS:
	JSL CHECK_DEAD_PLAYERS
	LDA CURRENT_ATTACKER
	STA CURRENT_TARGET
	JSL FIX_TARGET_NAME
	LDX CURRENT_ATTACKER
	LDA a:battler::afflictions+STATUS_GROUP::TEMPORARY,X
	AND #$00FF
	CMP #STATUS_2::ASLEEP
	BEQ @CHECK_WAKE_UP
	CMP #STATUS_2::IMMOBILIZED
	BEQ @CHECK_IMMOBILIZED_END
	CMP #STATUS_2::SOLIDIFIED
	BEQ @CHECK_SOLIDIFIED_END
	BRA @CHECK_CONCENTRATION_END
@CHECK_WAKE_UP:
	JSL RAND
	AND #$0003
	BNE @CHECK_CONCENTRATION_END
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_NEMURI_OFF
	LDX CURRENT_ATTACKER
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::afflictions+STATUS_GROUP::TEMPORARY,X
	BRA @CHECK_CONCENTRATION_END
@CHECK_IMMOBILIZED_END:
	.A16
	LDA #100
	JSR RAND_LIMIT
	CMP #100-CHANCE_OF_BODY_MOVING_AGAIN
	BCS @CHECK_CONCENTRATION_END
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_SHIBARA_OFF
	LDX CURRENT_ATTACKER
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::afflictions+STATUS_GROUP::TEMPORARY,X
	BRA @CHECK_CONCENTRATION_END
@CHECK_SOLIDIFIED_END:
	.A16
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KOORI_STAT
	LDX CURRENT_ATTACKER
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::afflictions+STATUS_GROUP::TEMPORARY,X
@CHECK_CONCENTRATION_END:
	REP #PROC_FLAGS::ACCUM8
	LDA CURRENT_ATTACKER
	CLC
	ADC #battler::afflictions+STATUS_GROUP::CONCENTRATION
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQ @CLEAR_ALT_SPRITEMAPS
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	DEC
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNE @CLEAR_ALT_SPRITEMAPS
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_FUUIN_OFF
@CLEAR_ALT_SPRITEMAPS:
	LDA #.LOWORD(BATTLERS_TABLE)
	LDX #0
	STX @LOCAL10
	BRA @CLEAR_SPRITEMAP_CHECK
@CLEAR_SPRITEMAP_LOOP:
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::use_alt_spritemap,X
	CLC
	REP #PROC_FLAGS::ACCUM8
	ADC #.SIZEOF(battler)
	LDX @LOCAL10
	INX
	STX @LOCAL10
@CLEAR_SPRITEMAP_CHECK:
	CPX #BATTLER_COUNT
	BCC @CLEAR_SPRITEMAP_LOOP
	JSL CHECK_DEAD_PLAYERS
	JSL REDIRECT_SHOW_HPPP_WINDOWS
@CHECK_BATTLE_END:
	LDA #0
	JSL COUNT_CHARS
	CMP #0
	BNE @ALLIES_ARE_ALIVE
	LDA #1
	STA @LOCAL03
	JSL RESET_HPPP_ROLLING
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_MONSTER_WIN
	LDA #1
.IF .DEFINED(JPN)
	STA @LOCAL06
.ELSE
	STA @LOCAL09
.ENDIF
@ALLIES_ARE_ALIVE:
	LDA #1
	JSL COUNT_CHARS
	CMP #0
	BNEL @CHECK_TURN_CONTINUE
@ENEMIES_ARE_DEAD:
	STZ @LOCAL03
	JSL RESET_HPPP_ROLLING
	LDA #1
	STA LETTERBOX_EFFECT_ENDING
	STA ENABLE_BACKGROUND_DARKENING
	LDY #.LOWORD(GAME_STATE) + game_state::unknownC4
.IF .DEFINED(JPN)
	STY @LOCAL0A
.ELSE
	STY @LOCAL0F
.ENDIF
	LDA BATTLE_MONEY_SCRATCH
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DEPOSIT_INTO_ATM
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
.IF .DEFINED(JPN)
	LDY @LOCAL0A
.ELSE
	LDY @LOCAL0F
.ENDIF
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDA #0
	JSL COUNT_CHARS
	DEC
	STORE_INT1632 @VIRTUAL0A
	MOVE_INT BATTLE_EXP_SCRATCH, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, BATTLE_EXP_SCRATCH
	LDA #0
	JSL COUNT_CHARS
	STORE_INT1632 @VIRTUAL0A
	JSL DIVISION32
	MOVE_INT @VIRTUAL06, BATTLE_EXP_SCRATCH
	LDA CURRENT_BATTLE_GROUP
	CMP #$01C0
	BCC @NOT_BOSS_BATTLE
	LOADPTR MSG_BTL_PLAYER_WIN_BOSS, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	BRA @SKIP_NOT_BOSS_BATTLE
@NOT_BOSS_BATTLE:
	LOADPTR MSG_BTL_PLAYER_WIN, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
@SKIP_NOT_BOSS_BATTLE:
	LDA ITEM_DROPPED
	BEQ @DISTRIBUTE_EXP_SETUP
	SEP #PROC_FLAGS::ACCUM8
	LDA ITEM_DROPPED
	JSL SET_CURRENT_ITEM_FAR
	.A16
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_PRESENT
@DISTRIBUTE_EXP_SETUP:
	LDY #.LOWORD(BATTLERS_TABLE)
	STY @LOCAL10
	LDA #0
	STA @VIRTUAL02
	BRA @EXP_LOOP_CHECK
@DISTRIBUTE_EXP_LOOP:
	LDA a:battler::consciousness,Y
	AND #$00FF
	BEQ @NEXT_EXP_BATTLER
	LDA a:battler::ally_or_enemy,Y
	AND #$00FF
	BNE @NEXT_EXP_BATTLER
	LDA a:battler::npc_id,Y
	AND #$00FF
	BNE @NEXT_EXP_BATTLER
	LDA a:battler::afflictions,Y
	AND #$00FF
	TAX
	CPX #STATUS_0::UNCONSCIOUS
	BEQ @NEXT_EXP_BATTLER
	CPX #STATUS_0::DIAMONDIZED
	BEQ @NEXT_EXP_BATTLER
	MOVE_INT BATTLE_EXP_SCRATCH, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #1
	LDA a:battler::id,Y
	JSL GAIN_EXP
@NEXT_EXP_BATTLER:
	LDY @LOCAL10
	TYA
	CLC
	ADC #.SIZEOF(battler)
	TAY
	STY @LOCAL10
	INC @VIRTUAL02
@EXP_LOOP_CHECK:
	LDA @VIRTUAL02
	CMP #BATTLER_COUNT
	BCC @DISTRIBUTE_EXP_LOOP
	LDA #1
.IF .DEFINED(JPN)
	STA @LOCAL06
.ELSE
	STA @LOCAL09
.ENDIF
@CHECK_TURN_CONTINUE:
.IF .DEFINED(JPN)
	LDA @LOCAL06
.ELSE
	LDA @LOCAL09
.ENDIF
	BEQL @EXECUTE_TURNS
@CLOSE_BATTLE_WINDOW:
	JSL REDIRECT_CLOSE_FOCUS_WINDOW
@CHECK_NEW_TURN:
.IF .DEFINED(JPN)
	LDA @LOCAL06
.ELSE
	LDA @LOCAL09
.ENDIF
	BEQL @START_TURN
@BATTLE_ENDING:
	JSL RESET_HPPP_ROLLING
@WAIT_HPPP_STABLE:
	JSL WINDOW_TICK
	JSL RESET_HPPP_METER_SPEED_IF_STABLE
	CMP #0
	BEQ @WAIT_HPPP_STABLE
	LDA MIRROR_ENEMY
	BEQL @BATTLE_CLEANUP
	LDA #.LOWORD(BATTLERS_TABLE)
.IF .DEFINED(JPN)
	STA @LOCAL0B
	LDX #0
	STX @LOCAL0C
.ELSE
	STA @LOCAL0F
	LDX #0
	STX @LOCAL0A
.ENDIF
	JMP @MIRROR_RESTORE_CHECK
@RESTORE_MIRROR_LOOP:
	TAX
	LDA a:battler::consciousness,X
	AND #$00FF
	BEQ @NEXT_MIRROR_BATTLER
.IF .DEFINED(JPN)
	LDA @LOCAL0B
.ELSE
	LDA @LOCAL0F
.ENDIF
	TAX
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @NEXT_MIRROR_BATTLER
.IF .DEFINED(JPN)
	LDA @LOCAL0B
.ELSE
	LDA @LOCAL0F
.ENDIF
	TAX
	LDA a:battler::id,X
	CMP #PARTY_MEMBER::POO
	BNE @NEXT_MIRROR_BATTLER
	STZ MIRROR_ENEMY
.IF .DEFINED(JPN)
	LDA @LOCAL0B
.ELSE
	LDA @LOCAL0F
.ENDIF
	CLC
	ADC #battler::afflictions
	TAX
.IF .DEFINED(JPN)
	STX @LOCAL0C
.ELSE
	STX @LOCAL0A
.ENDIF
	LDA a:STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	STA @VIRTUAL04
	STA @LOCAL08
.IF .DEFINED(JPN)
	LDA @LOCAL0B
.ELSE
	LDA @LOCAL0F
.ENDIF
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	PROMOTENEARPTR MIRROR_BATTLER_BACKUP, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL COPY_MIRROR_DATA
	LDA @VIRTUAL04
	SEP #PROC_FLAGS::ACCUM8
.IF .DEFINED(JPN)
	LDX @LOCAL0C
.ELSE
	LDX @LOCAL0A
.ENDIF
	STA a:STATUS_GROUP::PERSISTENT_EASYHEAL,X
	JSL CHECK_DEAD_PLAYERS
	BRA @BATTLE_CLEANUP
@NEXT_MIRROR_BATTLER:
	.A16
.IF .DEFINED(JPN)
	LDA @LOCAL0B
.ELSE
	LDA @LOCAL0F
.ENDIF
	CLC
	ADC #.SIZEOF(battler)
.IF .DEFINED(JPN)
	STA @LOCAL0B
	LDX @LOCAL0C
	INX
	STX @LOCAL0C
.ELSE
	STA @LOCAL0F
	LDX @LOCAL0A
	INX
	STX @LOCAL0A
.ENDIF
@MIRROR_RESTORE_CHECK:
	CPX #BATTLER_COUNT
	BCCL @RESTORE_MIRROR_LOOP
@BATTLE_CLEANUP:
	JSL RESET_POST_BATTLE_STATS
	SEP #PROC_FLAGS::ACCUM8
	STZ GAME_STATE+game_state::auto_fight_enable
	REP #PROC_FLAGS::ACCUM8
	STZ BATTLE_MODE_FLAG
	LDA BATTLE_MODE
	BEQL @REINIT_BATTLE
	LDX #1
	TXA
	JSL FADE_OUT
	BRA @FADE_OUT_CHECK
@FADE_OUT_LOOP:
	JSL WAIT_UNTIL_NEXT_FRAME
	JSL UPDATE_BATTLE_SCREEN_EFFECTS
@FADE_OUT_CHECK:
	LDA FADE_PARAMETERS + fade_parameters::step
	AND #$00FF
	BNE @FADE_OUT_LOOP
	JSL CLEAR_HPPP_WINDOW_HEADER
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	JSL CLOSE_ALL_WINDOWS_AND_HIDE_HPPP
	JSL CLEAR_BATTLE_VISUAL_EFFECTS
	LDA @LOCAL03
	END_C_FUNCTION
