
BATTLE_SELECTION_MENU:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @LOCAL09
	STA @LOCAL08
	LDA #0
	JSL LOAD_ATTACK_PALETTE
	LDA @LOCAL08
	DEC
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(char_struct)
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	STA @VIRTUAL04
	STA @LOCAL07
	LDX @VIRTUAL04
	LDA a:char_struct::afflictions,X
	AND #$00FF
	CMP #STATUS_0::PARALYZED
	BEQ @PARALYZED
	LDX @VIRTUAL04
	LDA a:char_struct::afflictions+2,X
	AND #$00FF
	CMP #STATUS_2::IMMOBILIZED
	BNE @CHECK_WEAPON_TYPE
@PARALYZED:
	LDA #2
	STA @LOCAL06
	BRA @AFTER_WEAPON_CHECK
@CHECK_WEAPON_TYPE:
	LDX @VIRTUAL04
	LDA a:char_struct::equipment+EQUIPMENT_SLOT::WEAPON,X
	AND #$00FF
	BEQ @CHECK_WEAPON_ITEM
	DEC
	STA @VIRTUAL02
	LDA @VIRTUAL04
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__ + char_struct::items,X
	AND #$00FF
@CHECK_WEAPON_ITEM:
	CMP #0
	BEQ @NO_WEAPON
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::type
	TAX
	LDA f:ITEM_CONFIGURATION_TABLE,X
	AND #$00FF
	AND #$0003
	CMP #1
	BNE @NO_WEAPON
	LDA #1
	STA @LOCAL06
	BRA @AFTER_WEAPON_CHECK
@NO_WEAPON:
	STZ @LOCAL06
@AFTER_WEAPON_CHECK:
	LDA GAME_STATE+game_state::auto_fight_enable
	AND #$00FF
	BEQL @MANUAL_MENU_SETUP
	LDA @LOCAL07
	STA @VIRTUAL04
	LDX @VIRTUAL04
	LDA a:char_struct::afflictions+4,X
	AND #$00FF
	BNEL @AUTO_FIGHT_ATTACK
	LDX @VIRTUAL04
	LDA a:char_struct::afflictions+3,X
	AND #$00FF
	CMP #STATUS_3::STRANGE
	BEQL @AUTO_FIGHT_ATTACK
	LDX @VIRTUAL04
	LDA a:char_struct::afflictions+1,X
	AND #$00FF
	CMP #STATUS_1::MUSHROOMIZED
	BEQL @AUTO_FIGHT_ATTACK
	LDA @LOCAL08
	CMP #PARTY_MEMBER::NESS
	BEQ @AUTO_FIGHT_PSI_CHECK
	LDA @LOCAL08
	CMP #PARTY_MEMBER::POO
	BNEL @AUTO_FIGHT_ATTACK
@AUTO_FIGHT_PSI_CHECK:
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA BATTLE_MENU_SELECTION + battle_menu_selection::targetting
	LDA #26
	STA BATTLE_MENU_SELECTION + battle_menu_selection::param1
	REP #PROC_FLAGS::ACCUM8
	LDA #35
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_action
	LDX #26
	LDA @LOCAL08
	JSL CHECK_IF_PSI_KNOWN
	CMP #0
	BEQ @TRY_LIFEUP_GAMMA
	LDX @VIRTUAL04
	LDA f:BATTLE_ACTION_TABLE + (.SIZEOF(battle_action) * BATTLE_ACTIONS::PSI_LIFEUP_OMEGA) + battle_action::pp_cost
	AND #$00FF
	CMP a:char_struct::current_pp_target,X
	BGT @TRY_LIFEUP_GAMMA
	LDA #0
	JSL COUNT_CHARS
	CMP #2
	BCC @TRY_LIFEUP_GAMMA
	LDA #0
	STA @LOCAL05
	BRA @CHECK_PARTY_LOOP
@CHECK_PARTY_MEMBER_HP:
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
	AND #$00FF
	TAX
	CPX #1
	BCC @NEXT_PARTY_MEMBER
	CPX #4
	BGT @NEXT_PARTY_MEMBER
	TXA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::max_hp,X
	LSR
	LSR
	CMP PARTY_CHARACTERS+char_struct::current_hp_target,X
	BLTEQ @TRY_LIFEUP_GAMMA
@NEXT_PARTY_MEMBER:
	LDA @LOCAL05
	INC
	STA @LOCAL05
@CHECK_PARTY_LOOP:
	CMP #6
	BCC @CHECK_PARTY_MEMBER_HP
	SEP #PROC_FLAGS::ACCUM8
	LDA #4
	STA BATTLE_MENU_SELECTION + battle_menu_selection::targetting
	JMP @AUTO_FIGHT_RETURN
@TRY_LIFEUP_GAMMA:
	SEP #PROC_FLAGS::ACCUM8
	LDA #25
	STA BATTLE_MENU_SELECTION + battle_menu_selection::param1
	REP #PROC_FLAGS::ACCUM8
	LDA #34
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_action
	LDX #25
	LDA @LOCAL08
	JSL CHECK_IF_PSI_KNOWN
	CMP #0
	BEQ @TRY_LIFEUP_BETA
	LDX @VIRTUAL04
	LDA f:BATTLE_ACTION_TABLE + (.SIZEOF(battle_action) * BATTLE_ACTIONS::PSI_LIFEUP_GAMMA) + battle_action::pp_cost
	AND #$00FF
	CMP a:char_struct::current_pp_target,X
	BGT @TRY_LIFEUP_BETA
	JSL AUTOLIFEUP
	SEP #PROC_FLAGS::ACCUM8
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_target
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @AUTO_FIGHT_RETURN
@TRY_LIFEUP_BETA:
	SEP #PROC_FLAGS::ACCUM8
	LDA #24
	STA BATTLE_MENU_SELECTION + battle_menu_selection::param1
	REP #PROC_FLAGS::ACCUM8
	LDA #33
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_action
	LDX #24
	LDA @LOCAL08
	JSL CHECK_IF_PSI_KNOWN
	CMP #0
	BEQ @TRY_LIFEUP_ALPHA
	LDX @VIRTUAL04
	LDA f:BATTLE_ACTION_TABLE + (.SIZEOF(battle_action) * BATTLE_ACTIONS::PSI_LIFEUP_BETA) + battle_action::pp_cost
	AND #$00FF
	CMP a:char_struct::current_pp_target,X
	BGT @TRY_LIFEUP_ALPHA
	JSL AUTOLIFEUP
	SEP #PROC_FLAGS::ACCUM8
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_target
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNE @AUTO_FIGHT_RETURN
@TRY_LIFEUP_ALPHA:
	SEP #PROC_FLAGS::ACCUM8
	LDA #23
	STA BATTLE_MENU_SELECTION + battle_menu_selection::param1
	REP #PROC_FLAGS::ACCUM8
	LDA #32
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_action
	LDX #23
	LDA @LOCAL08
	JSL CHECK_IF_PSI_KNOWN
	CMP #0
	BEQ @TRY_HEALING_OMEGA
	LDX @VIRTUAL04
	LDA f:BATTLE_ACTION_TABLE + (.SIZEOF(battle_action) * BATTLE_ACTIONS::PSI_LIFEUP_ALPHA) + battle_action::pp_cost
	AND #$00FF
	CMP a:char_struct::current_pp_target,X
	BGT @TRY_HEALING_OMEGA
	JSL AUTOLIFEUP
	SEP #PROC_FLAGS::ACCUM8
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_target
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQ @TRY_HEALING_OMEGA
@AUTO_FIGHT_RETURN:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL08
	SEP #PROC_FLAGS::ACCUM8
	STA BATTLE_MENU_SELECTION
	REP #PROC_FLAGS::ACCUM8
	LDA BATTLE_MENU_SELECTION + battle_menu_selection::selected_action
	JMP @RETURN
@TRY_HEALING_OMEGA:
	SEP #PROC_FLAGS::ACCUM8
	LDA #30
	STA BATTLE_MENU_SELECTION + battle_menu_selection::param1
	REP #PROC_FLAGS::ACCUM8
	LDA #39
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_action
	LDX #30
	LDA @LOCAL08
	JSL CHECK_IF_PSI_KNOWN
	CMP #0
	BEQ @TRY_HEALING_GAMMA
	LDX @VIRTUAL04
	LDA f:BATTLE_ACTION_TABLE + (.SIZEOF(battle_action) * BATTLE_ACTIONS::PSI_HEALING_OMEGA) + battle_action::pp_cost
	AND #$00FF
	CMP a:char_struct::current_pp_target,X
	BGT @TRY_HEALING_GAMMA
	LDX #1
	LDA #0
	JSL AUTOHEALING
	SEP #PROC_FLAGS::ACCUM8
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_target
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNE @AUTO_FIGHT_RETURN
@TRY_HEALING_GAMMA:
	SEP #PROC_FLAGS::ACCUM8
	LDA #29
	STA BATTLE_MENU_SELECTION + battle_menu_selection::param1
	REP #PROC_FLAGS::ACCUM8
	LDA #38
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_action
	LDX #29
	LDA @LOCAL08
	JSL CHECK_IF_PSI_KNOWN
	CMP #0
	BEQ @TRY_HEALING_BETA
	LDX @VIRTUAL04
	LDA f:BATTLE_ACTION_TABLE + (.SIZEOF(battle_action) * BATTLE_ACTIONS::PSI_HEALING_GAMMA) + battle_action::pp_cost
	AND #$00FF
	CMP a:char_struct::current_pp_target,X
	BGT @TRY_HEALING_BETA
	LDX #3
	LDA #0
	JSL AUTOHEALING
	SEP #PROC_FLAGS::ACCUM8
	LDY #.LOWORD(BATTLE_MENU_SELECTION) + battle_menu_selection::selected_target
	STY @LOCAL04
	STA __BSS_START__,Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @AUTO_FIGHT_RETURN
	LDX #2
	LDA #0
	JSL AUTOHEALING
	SEP #PROC_FLAGS::ACCUM8
	LDY @LOCAL04
	STA __BSS_START__,Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @AUTO_FIGHT_RETURN
	LDX #1
	LDA #0
	JSL AUTOHEALING
	SEP #PROC_FLAGS::ACCUM8
	LDY @LOCAL04
	STA __BSS_START__,Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @AUTO_FIGHT_RETURN
@TRY_HEALING_BETA:
	SEP #PROC_FLAGS::ACCUM8
	LDA #28
	STA BATTLE_MENU_SELECTION + battle_menu_selection::param1
	REP #PROC_FLAGS::ACCUM8
	LDA #37
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_action
	LDX #28
	LDA @LOCAL08
	JSL CHECK_IF_PSI_KNOWN
	CMP #0
	BEQL @TRY_HEALING_ALPHA
	LDX @VIRTUAL04
	LDA f:BATTLE_ACTION_TABLE + (.SIZEOF(battle_action) * BATTLE_ACTIONS::PSI_HEALING_BETA) + battle_action::pp_cost
	AND #$00FF
	CMP a:char_struct::current_pp_target,X
	BGT @TRY_HEALING_ALPHA
	LDX #5
	LDA #0
	JSL AUTOHEALING
	SEP #PROC_FLAGS::ACCUM8
	LDY #.LOWORD(BATTLE_MENU_SELECTION) + battle_menu_selection::selected_target
	STY @LOCAL09
	STA __BSS_START__,Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @AUTO_FIGHT_RETURN
	LDX #4
	LDA #0
	JSL AUTOHEALING
	SEP #PROC_FLAGS::ACCUM8
	LDY @LOCAL09
	STA __BSS_START__,Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @AUTO_FIGHT_RETURN
	LDX #2
	TXA
	JSL AUTOHEALING
	SEP #PROC_FLAGS::ACCUM8
	LDY @LOCAL09
	STA __BSS_START__,Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @AUTO_FIGHT_RETURN
	LDX #1
	LDA #3
	JSL AUTOHEALING
	SEP #PROC_FLAGS::ACCUM8
	LDY @LOCAL09
	STA __BSS_START__,Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @AUTO_FIGHT_RETURN
@TRY_HEALING_ALPHA:
	SEP #PROC_FLAGS::ACCUM8
	LDA #27
	STA BATTLE_MENU_SELECTION + battle_menu_selection::param1
	REP #PROC_FLAGS::ACCUM8
	LDA #36
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_action
	LDX #27
	LDA @LOCAL08
	JSL CHECK_IF_PSI_KNOWN
	CMP #0
	BEQ @AUTO_FIGHT_ATTACK
	LDX @VIRTUAL04
	LDA f:BATTLE_ACTION_TABLE + (.SIZEOF(battle_action) * BATTLE_ACTIONS::PSI_HEALING_ALPHA) + battle_action::pp_cost
	AND #$00FF
	CMP a:char_struct::current_pp_target,X
	BGT @AUTO_FIGHT_ATTACK
	LDX #7
	LDA #0
	JSL AUTOHEALING
	SEP #PROC_FLAGS::ACCUM8
	LDY #.LOWORD(BATTLE_MENU_SELECTION) + battle_menu_selection::selected_target
	STY @LOCAL04
	STA __BSS_START__,Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @AUTO_FIGHT_RETURN
	LDX #6
	LDA #0
	JSL AUTOHEALING
	SEP #PROC_FLAGS::ACCUM8
	LDY @LOCAL04
	STA __BSS_START__,Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @AUTO_FIGHT_RETURN
	LDX #1
	LDA #2
	JSL AUTOHEALING
	SEP #PROC_FLAGS::ACCUM8
	LDY @LOCAL04
	STA __BSS_START__,Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @AUTO_FIGHT_RETURN
@AUTO_FIGHT_ATTACK:
	LDA @LOCAL06
	BEQ @AUTO_ATTACK_BASH
	CMP #1
	BEQ @AUTO_ATTACK_SHOOT
	CMP #2
	BEQ @AUTO_ATTACK_DO_NOTHING
	BRA @AUTO_ATTACK_SELECT_TARGET
@AUTO_ATTACK_BASH:
	LDA #4
	STA @LOCAL03
	BRA @AUTO_ATTACK_SELECT_TARGET
@AUTO_ATTACK_SHOOT:
	LDA #5
	STA @LOCAL03
	BRA @AUTO_ATTACK_SELECT_TARGET
@AUTO_ATTACK_DO_NOTHING:
	LDA #1
	JMP @RETURN
@AUTO_ATTACK_SELECT_TARGET:
	LDA @LOCAL08
	SEP #PROC_FLAGS::ACCUM8
	STA BATTLE_MENU_SELECTION
	STZ BATTLE_MENU_SELECTION + battle_menu_selection::param1
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_action
	SEP #PROC_FLAGS::ACCUM8
	LDA #17
	STA BATTLE_MENU_SELECTION + battle_menu_selection::targetting
	REP #PROC_FLAGS::ACCUM8
	LDA NUM_BATTLERS_IN_FRONT_ROW
	CLC
	ADC NUM_BATTLERS_IN_BACK_ROW
	JSR RAND_LIMIT
	SEP #PROC_FLAGS::ACCUM8
	INC
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_target
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	JMP @RETURN
@MANUAL_MENU_SETUP:
	JSL SET_HALF_HPPP_METER_SPEED
	LDA @LOCAL08
	CMP #PARTY_MEMBER::PAULA
	BEQ @HAS_PSI
	LDA @LOCAL08
	CMP #PARTY_MEMBER::POO
	BNE @NO_PSI
@HAS_PSI:
	LDA #1
	STA @LOCAL03
	BRA @AFTER_PSI_CHECK
@NO_PSI:
	STZ @LOCAL03
@AFTER_PSI_CHECK:
	LDA @LOCAL09
	BNE @AFTER_FIRST_TIME_CHECK
	INC @LOCAL03
@AFTER_FIRST_TIME_CHECK:
	LOADPTR BATTLE_WINDOW_SIZES, @VIRTUAL06
	LDA @LOCAL03
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	JSL REDIRECT_CREATE_WINDOW
	LDA @LOCAL08
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	PROMOTENEARPTRA @VIRTUAL0A
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL0A, @LOCAL00
	LDX #4
	LDA [@VIRTUAL06]
	AND #$00FF
	JSL SET_WINDOW_TITLE
	LDA @LOCAL06
	BEQ @SETUP_BASH_OPTION
	CMP #1
	BEQ @SETUP_SHOOT_OPTION
	CMP #2
	BEQ @SETUP_DO_NOTHING_OPTION
	BRA @AFTER_ATTACK_OPTION
@SETUP_BASH_OPTION:
	LOADPTR BATTLE_MENU_TEXT_BASH, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDY #0
	TYX
	LDA #1
	JSL SELECTION_MENU_ITEM_SETUP
	BRA @AFTER_ATTACK_OPTION
@SETUP_SHOOT_OPTION:
	LOADPTR BATTLE_MENU_TEXT_SHOOT, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDY #0
	TYX
	LDA #1
	JSL SELECTION_MENU_ITEM_SETUP
	BRA @AFTER_ATTACK_OPTION
@SETUP_DO_NOTHING_OPTION:
	LOADPTR BATTLE_MENU_TEXT_DO_NOTHING, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDY #0
	TYX
	LDA #1
	JSL SELECTION_MENU_ITEM_SETUP
@AFTER_ATTACK_OPTION:
	LDA @LOCAL06
	CMP #2
	BEQ @AFTER_GOODS_AUTOFIGHT
@SETUP_GOODS_AUTOFIGHT:
	LOADPTR BATTLE_MENU_TEXT, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	LDA #5
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	MOVE_INT @VIRTUAL0A, @LOCAL01
	LDY #0
	LDX #5
	LDA #2
	JSL SELECTION_MENU_ITEM_SETUP
	LDA #20
	MOVE_INTX @LOCAL02, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	MOVE_INT @VIRTUAL0A, @LOCAL01
	LDY #1
	LDX #5
	TXA
	JSL SELECTION_MENU_ITEM_SETUP
@AFTER_GOODS_AUTOFIGHT:
	LDA @LOCAL09
	BNEL @AFTER_DEFEND_RUN
	LDA @LOCAL03
	CMP #2
	BNE @MENU_OFFSET_DEFAULT
	LDX #15
	BRA @STORE_MENU_OFFSET
@MENU_OFFSET_DEFAULT:
	LDX #10
@STORE_MENU_OFFSET:
	STX @LOCAL09
	LOADPTR BATTLE_MENU_TEXT, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	LDA #10
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	MOVE_INT @VIRTUAL0A, @LOCAL01
	LDY #0
	LDX @LOCAL09
	LDA #3
	JSL SELECTION_MENU_ITEM_SETUP
	LDA #40
	MOVE_INTX @LOCAL02, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	MOVE_INT @VIRTUAL0A, @LOCAL01
	LDY #1
	LDX @LOCAL09
	LDA #6
	JSL SELECTION_MENU_ITEM_SETUP
@AFTER_DEFEND_RUN:
	LDA @LOCAL08
	CMP #PARTY_MEMBER::JEFF
	BNE @CHECK_PSI_AFFLICTION
	LOADPTR BATTLE_MENU_TEXT_SPY, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDY #1
	LDX #0
	LDA #4
	JSL SELECTION_MENU_ITEM_SETUP
	BRA @AFTER_PSI_OPTION
@CHECK_PSI_AFFLICTION:
	LDA @LOCAL07
	STA @VIRTUAL04
	LDX @VIRTUAL04
	LDA a:char_struct::afflictions+4,X
	AND #$00FF
	BNE @AFTER_PSI_OPTION
	LOADPTR BATTLE_MENU_TEXT_PSI, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDY #1
	LDX #0
	LDA #4
	JSL SELECTION_MENU_ITEM_SETUP
@AFTER_PSI_OPTION:
	LDA @LOCAL08
	CMP #PARTY_MEMBER::PAULA
	BNE @CHECK_POO
	LOADPTR BATTLE_MENU_TEXT_PRAY, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDY #0
	LDX #10
	LDA #7
	JSL SELECTION_MENU_ITEM_SETUP
@CHECK_POO:
	LDA @LOCAL08
	CMP #PARTY_MEMBER::POO
	BNE @MENU_SELECTION_LOOP
	LOADPTR BATTLE_MENU_TEXT_MIRROR, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDY #0
	LDX #10
	LDA #7
	JSL SELECTION_MENU_ITEM_SETUP
@MENU_SELECTION_LOOP:
	LDX @LOCAL03
	LDA f:BATTLE_WINDOW_SIZES,X
	AND #$00FF
	JSL REDIRECT_SET_WINDOW_FOCUS
	JSL REDIRECT_PRINT_MENU_ITEMS
	LDA #1
	JSL REDIRECT_SELECTION_MENU
	CMP #0
	BNEL @PROCESS_SELECTION
	LDA DEBUG
	BEQ @CHECK_BATTLE_MODE
	LDA PAD_STATE
	AND #PAD::SELECT_BUTTON | PAD::START_BUTTON
	CMP #PAD::SELECT_BUTTON | PAD::START_BUTTON
	BNE @CHECK_R_BUTTON
	JSL RESUME_MUSIC
	LDA #$FFFF
	JMP @RETURN
@CHECK_R_BUTTON:
	LDA PAD_STATE
	AND #PAD::R_BUTTON
	BEQ @CHECK_BATTLE_MODE
	JSL CYCLE_BATTLE_TARGET
	BRA @MENU_SELECTION_LOOP
@CHECK_BATTLE_MODE:
	LDA BATTLE_MODE
	BNE @CANCEL_MENU
	LDA PAD_STATE
	AND #PAD::L_BUTTON
	BEQ @CHECK_SELECT_DEBUG
	JSL DEBUG_SET_CHAR_LEVEL
	LDY #0
	STY @LOCAL09
	BRA @DEBUG_LEVEL_CHECK
@DEBUG_LEVEL_UP_LOOP:
	TYA
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
	AND #$00FF
	STA @LOCAL07
	BEQ @DEBUG_NEXT_MEMBER
	CMP #4
	BGT @DEBUG_NEXT_MEMBER
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	TAX
	LDA @LOCAL07
	JSL BATTLE_INIT_PLAYER_STATS
@DEBUG_NEXT_MEMBER:
	LDY @LOCAL09
	INY
	STY @LOCAL09
@DEBUG_LEVEL_CHECK:
	CPY #6
	BCC @DEBUG_LEVEL_UP_LOOP
	JMP @MENU_SELECTION_LOOP
@CHECK_SELECT_DEBUG:
	LDA PAD_STATE
	AND #PAD::SELECT_BUTTON
	BEQ @CANCEL_MENU
	JSL DEBUG_Y_BUTTON_GOODS
	JMP @MENU_SELECTION_LOOP
@CANCEL_MENU:
	JSL RESUME_MUSIC
	LDA #0
	JMP @RETURN
@PROCESS_SELECTION:
	SEP #PROC_FLAGS::ACCUM8
	STZ BATTLE_ITEM_USED
	REP #PROC_FLAGS::ACCUM8
	CMP #1
	BEQ @ACTION_BASH_SHOOT
	CMP #2
	BEQL @ACTION_GOODS
	CMP #3
	BEQL @ACTION_AUTO_FIGHT
	CMP #4
	BEQL @ACTION_PSI_SPY
	CMP #5
	BEQL @ACTION_GUARD
	CMP #6
	BEQL @ACTION_RUN_AWAY
	CMP #7
	BEQL @ACTION_PRAY_MIRROR
	JMP @CLOSE_MENU
@ACTION_BASH_SHOOT:
	LDA @LOCAL06
	BEQ @SET_BASH
	CMP #1
	BEQ @SET_SHOOT
	CMP #2
	BEQ @SET_DO_NOTHING
	BRA @BASH_SHOOT_TARGET
@SET_BASH:
	LDA #BATTLE_ACTIONS::BASH
	STA @VIRTUAL02
	STA @LOCAL04
	BRA @BASH_SHOOT_TARGET
@SET_SHOOT:
	LDA #BATTLE_ACTIONS::SHOOT
	STA @VIRTUAL02
	STA @LOCAL04
	BRA @BASH_SHOOT_TARGET
@SET_DO_NOTHING:
	LDA #BATTLE_ACTIONS::USE_NO_EFFECT
	STA @VIRTUAL02
	STA @LOCAL04
@BASH_SHOOT_TARGET:
	LDA @LOCAL04
	STA @VIRTUAL02
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_action
	SEP #PROC_FLAGS::ACCUM8
	LDA #17
	STA BATTLE_MENU_SELECTION + battle_menu_selection::targetting
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL06
	CMP #2
	BEQL @CLOSE_MENU
	LDY @VIRTUAL02
	LDX #1
	LDA #0
	JSL SELECT_BATTLE_TARGET_DISPATCH_FAR
	SEP #PROC_FLAGS::ACCUM8
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_target
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQL @MENU_SELECTION_LOOP
	JMP @CLOSE_MENU
@ACTION_GOODS:
	LDA @LOCAL08
	SEP #PROC_FLAGS::ACCUM8
	STA BATTLE_MENU_SELECTION
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(BATTLE_MENU_SELECTION)
	JSL BATTLE_ITEM_MENU_FAR
	TAX
	BEQL @MENU_SELECTION_LOOP
	LDA BATTLE_MENU_SELECTION + battle_menu_selection::param1
	AND #$00FF
	TAX
	LDA @LOCAL08
	JSL GET_CHARACTER_ITEM
	SEP #PROC_FLAGS::ACCUM8
	STA BATTLE_ITEM_USED
	REP #PROC_FLAGS::ACCUM8
	LDA BATTLE_MENU_SELECTION + battle_menu_selection::selected_action
	STA @VIRTUAL02
	STA @LOCAL04
	JMP @CLOSE_MENU
@ACTION_AUTO_FIGHT:
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA GAME_STATE+game_state::auto_fight_enable
	JSL RENDER_HPPP_WINDOW_HEADER
	.A16
	LDA #BATTLE_ACTIONS::NO_EFFECT
	STA @VIRTUAL02
	STA @LOCAL04
	JMP @CLOSE_MENU
@ACTION_PSI_SPY:
	LDA @LOCAL08
	CMP #PARTY_MEMBER::JEFF
	BNE @ACTION_PSI_MENU
	LDA #BATTLE_ACTIONS::SPY
	STA @VIRTUAL02
	STA @LOCAL04
	LDA @VIRTUAL02
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_action
	SEP #PROC_FLAGS::ACCUM8
	LDA #17
	STA BATTLE_MENU_SELECTION + battle_menu_selection::targetting
	LDY @VIRTUAL02
	LDX #1
	REP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL SELECT_BATTLE_TARGET_DISPATCH_FAR
	SEP #PROC_FLAGS::ACCUM8
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_target
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQL @MENU_SELECTION_LOOP
	JMP @CLOSE_MENU
@ACTION_PSI_MENU:
	LDA @LOCAL08
	SEP #PROC_FLAGS::ACCUM8
	STA BATTLE_MENU_SELECTION
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(BATTLE_MENU_SELECTION)
	JSL REDIRECT_BATTLE_PSI_MENU
	TAX
	BEQL @MENU_SELECTION_LOOP
	SEP #PROC_FLAGS::ACCUM8
	STZ BATTLE_ITEM_USED
	REP #PROC_FLAGS::ACCUM8
	LDA BATTLE_MENU_SELECTION + battle_menu_selection::selected_action
	STA @VIRTUAL02
	STA @LOCAL04
	JMP @CLOSE_MENU
@ACTION_GUARD:
	LDA #BATTLE_ACTIONS::GUARD
	STA @VIRTUAL02
	STA @LOCAL04
	LDA @VIRTUAL02
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_action
	SEP #PROC_FLAGS::ACCUM8
	STZ BATTLE_MENU_SELECTION + battle_menu_selection::targetting
	JMP @CLOSE_MENU
@ACTION_RUN_AWAY:
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA BATTLE_MENU_SELECTION + battle_menu_selection::targetting
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL08
	SEP #PROC_FLAGS::ACCUM8
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_target
	REP #PROC_FLAGS::ACCUM8
	LDA #BATTLE_ACTIONS::RUN_AWAY
	STA @VIRTUAL02
	STA @LOCAL04
	LDA @VIRTUAL02
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_action
	JMP @CLOSE_MENU
@ACTION_PRAY_MIRROR:
	LDX #.LOWORD(BATTLE_MENU_SELECTION) + battle_menu_selection::targetting
	STX @LOCAL09
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(BATTLE_MENU_SELECTION) + battle_menu_selection::selected_target
	STA @VIRTUAL04
	LDA @LOCAL08
	SEP #PROC_FLAGS::ACCUM8
	LDX @VIRTUAL04
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL08
	CMP #PARTY_MEMBER::PAULA
	BEQ @PAULA_PRAY
	CMP #PARTY_MEMBER::POO
	BEQL @POO_MIRROR
	JMP @CLOSE_MENU
@PAULA_PRAY:
	LDA GIYGAS_PHASE
	CMP #GIYGAS_PHASES::START_PRAYING
	BEQ @PRAYER_PHASE_1
	CMP #GIYGAS_PHASES::PRAYER_1_USED
	BEQ @PRAYER_PHASE_2
	CMP #GIYGAS_PHASES::PRAYER_2_USED
	BEQ @PRAYER_PHASE_3
	CMP #GIYGAS_PHASES::PRAYER_3_USED
	BEQ @PRAYER_PHASE_4
	CMP #GIYGAS_PHASES::PRAYER_4_USED
	BEQ @PRAYER_PHASE_5
	CMP #GIYGAS_PHASES::PRAYER_5_USED
	BEQ @PRAYER_PHASE_6
	CMP #GIYGAS_PHASES::PRAYER_6_USED
	BEQ @PRAYER_PHASE_7
	CMP #GIYGAS_PHASES::PRAYER_7_USED
	BEQ @PRAYER_PHASE_8
	CMP #GIYGAS_PHASES::PRAYER_8_USED
	BEQ @PRAYER_PHASE_9
	BRA @PRAYER_DEFAULT
@PRAYER_PHASE_1:
	LDA #BATTLE_ACTIONS::FINAL_PRAYER_1
	STA @VIRTUAL02
	STA @LOCAL04
	BRA @SET_PRAY_ACTION
@PRAYER_PHASE_2:
	LDA #BATTLE_ACTIONS::FINAL_PRAYER_2
	STA @VIRTUAL02
	STA @LOCAL04
	BRA @SET_PRAY_ACTION
@PRAYER_PHASE_3:
	LDA #BATTLE_ACTIONS::FINAL_PRAYER_3
	STA @VIRTUAL02
	STA @LOCAL04
	BRA @SET_PRAY_ACTION
@PRAYER_PHASE_4:
	LDA #BATTLE_ACTIONS::FINAL_PRAYER_4
	STA @VIRTUAL02
	STA @LOCAL04
	BRA @SET_PRAY_ACTION
@PRAYER_PHASE_5:
	LDA #BATTLE_ACTIONS::FINAL_PRAYER_5
	STA @VIRTUAL02
	STA @LOCAL04
	BRA @SET_PRAY_ACTION
@PRAYER_PHASE_6:
	LDA #BATTLE_ACTIONS::FINAL_PRAYER_6
	STA @VIRTUAL02
	STA @LOCAL04
	BRA @SET_PRAY_ACTION
@PRAYER_PHASE_7:
	LDA #BATTLE_ACTIONS::FINAL_PRAYER_7
	STA @VIRTUAL02
	STA @LOCAL04
	BRA @SET_PRAY_ACTION
@PRAYER_PHASE_8:
	LDA #BATTLE_ACTIONS::FINAL_PRAYER_8
	STA @VIRTUAL02
	STA @LOCAL04
	BRA @SET_PRAY_ACTION
@PRAYER_PHASE_9:
	LDA #BATTLE_ACTIONS::FINAL_PRAYER_9
	STA @VIRTUAL02
	STA @LOCAL04
	BRA @SET_PRAY_ACTION
@PRAYER_DEFAULT:
	LDA #BATTLE_ACTIONS::PRAY
	STA @VIRTUAL02
	STA @LOCAL04
@SET_PRAY_ACTION:
	LDA @VIRTUAL02
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_action
	BRA @CLOSE_MENU
@POO_MIRROR:
	LDA #BATTLE_ACTIONS::MIRROR
	STA @VIRTUAL02
	STA @LOCAL04
	LDA @VIRTUAL02
	STA BATTLE_MENU_SELECTION + battle_menu_selection::selected_action
	SEP #PROC_FLAGS::ACCUM8
	LDA #17
	LDX @LOCAL09
	STA __BSS_START__,X
	LDY @VIRTUAL02
	LDX #1
	REP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL SELECT_BATTLE_TARGET_DISPATCH_FAR
	SEP #PROC_FLAGS::ACCUM8
	LDX @VIRTUAL04
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQL @MENU_SELECTION_LOOP
@CLOSE_MENU:
	LDX @LOCAL03
	REP #PROC_FLAGS::ACCUM8
	LDA f:BATTLE_WINDOW_SIZES,X
	AND #$00FF
	JSL REDIRECT_SET_WINDOW_FOCUS
	JSL RESUME_MUSIC
	LDA @LOCAL04
	STA @VIRTUAL02
@RETURN:
	END_C_FUNCTION
