
MISS_CALC:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16 "MISS_CHANCE"
	STACK_RESERVE_INT16 "MISS_MESSAGE"
	STACK_RESERVE_PARAM_INT16 ;int missMessage
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	TAY
	STY @MISS_MESSAGE
	LDX CURRENT_ATTACKER
	LDA __BSS_START__+14,X
	AND #$00FF
	BNEL @ENEMY_MISS_RATE
	LDX CURRENT_ATTACKER
	LDA __BSS_START__+15,X
	AND #$00FF
	BNEL @ENEMY_MISS_RATE
	LDX CURRENT_ATTACKER
	LDA __BSS_START__+16,X
	AND #$00FF
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::WEAPON,X
	AND #$00FF
	BEQ @NO_WEAPON
	DEC
	STA @VIRTUAL02
	TXA
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::special
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	TAX
	STX @MISS_CHANCE
	BRA @CHECK_STATUS_PENALTY
@NO_WEAPON:
	LDX #1
	STX @MISS_CHANCE
@CHECK_STATUS_PENALTY:
	LDX CURRENT_ATTACKER
	LDA __BSS_START__ + battler::afflictions + STATUS_GROUP::TEMPORARY,X
	AND #$00FF
	CMP #STATUS_2::CRYING
	BEQ @APPLY_STATUS_PENALTY
	LDX CURRENT_ATTACKER
	LDA __BSS_START__ + battler::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	CMP #STATUS_0::NAUSEOUS
	BNE @PERFORM_ROLL
@APPLY_STATUS_PENALTY:
	LDX @MISS_CHANCE
	TXA
	CLC
	ADC #8 ;miss chance + 1/2
	TAX
	STX @MISS_CHANCE
	BRA @PERFORM_ROLL
@ENEMY_MISS_RATE:
	LDX CURRENT_ATTACKER
	LDA __BSS_START__,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::miss_rate
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	AND #$00FF
	TAX
	STX @MISS_CHANCE
@PERFORM_ROLL:
	LDX @MISS_CHANCE
	BEQ @HIT
	LDA #16
	JSR RAND_LIMIT
	STA @VIRTUAL02
	LDX @MISS_CHANCE
	TXA
	DEC
	CMP @VIRTUAL02
	BCC @HIT
	LDY @MISS_MESSAGE
	BEQ @PHYSICAL_MISS_TEXT
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KARABURI_UTSU
	BRA @MISS
@PHYSICAL_MISS_TEXT:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_KARABURI
@MISS:
	LDA #1
	BRA @RETURN
@HIT:
	LDA #0
@RETURN:
	END_C_FUNCTION
