
PREVIEW_ARMS_EQUIP_STATS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL01
	LDA CHARACTER_FOR_EQUIP_MENU
	AND #$00FF
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::WEAPON,X
	STA TEMPORARY_WEAPON
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	STA TEMPORARY_BODY_GEAR
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	CMP #$FFFF
	BNE @USE_ITEM
	LDX #0
	BRA @STORE_ARMS
@USE_ITEM:
	TAX
@STORE_ARMS:
	TXA
	SEP #PROC_FLAGS::ACCUM8
	STA TEMPORARY_ARMS_GEAR
	REP #PROC_FLAGS::ACCUM8
	LDA CHARACTER_FOR_EQUIP_MENU
	AND #$00FF
	TAX
	STX @LOCAL00
	TXA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	STA TEMPORARY_OTHER_GEAR
	LDX @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	TXA
	JSL DISPLAY_CHARACTER_EQUIPMENT_STATS
	END_C_FUNCTION
