
PRINT_ENEMY_ARTICLE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	BNE @TARGET_BRANCH
	LDA ATTACKER_ENEMY_ID
	CMP #.LOWORD(-1)
	BNE @ATTACKER_VALID
	SEP #PROC_FLAGS::ACCUM8
	STZ PRINT_ATTACKER_ARTICLE
	BRA @RETURN
@ATTACKER_VALID:
	.A16
	LDA PRINT_ATTACKER_ARTICLE
	AND #$00FF
	BNE @RETURN
	LDA ATTACKER_ENEMY_ID
	BRA @LOOKUP_AND_PRINT
@TARGET_BRANCH:
	.A16
	LDA TARGET_ENEMY_ID
	CMP #.LOWORD(-1)
	BNE @TARGET_VALID
	SEP #PROC_FLAGS::ACCUM8
	STZ PRINT_TARGET_ARTICLE
	BRA @RETURN
@TARGET_VALID:
	.A16
	LDA PRINT_TARGET_ARTICLE
	AND #$00FF
	BNE @RETURN
	LDA TARGET_ENEMY_ID
@LOOKUP_AND_PRINT:
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(enemy_data)
	.A16
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	AND #$00FF
	BEQ @RETURN
	LDA LAST_PRINTED_CHARACTER
	AND #$00FF
	CMP #CHAR::BULLET
	BNE @LOWERCASE_THE
	LOADPTR THETHE, @LOCAL00
	LDA #4
	JSL PRINT_STRING_WITH_WORDWRAP
	BRA @RETURN
@LOWERCASE_THE:
	LOADPTR THETHE+4, @LOCAL00
	LDA #4
	JSL PRINT_STRING_WITH_WORDWRAP
@RETURN:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
