
PSI_ANIMATION_FILL_DATA:
	.BYTE $30, $00, $00
UPDATE_PSI_ANIMATION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT8
	END_STACK_VARS
.IF .DEFINED(JPN) ;wonder why these got swapped?
	@VIRTUALTMP01 := @VIRTUAL04
	@VIRTUALTMP02 := @VIRTUAL02
.ELSE
	@VIRTUALTMP01 := @VIRTUAL02
	@VIRTUALTMP02 := @VIRTUAL04
.ENDIF
	LDA PSI_ANIMATION_STATE + psi_animation_state::time_until_next_frame
	AND #$00FF
	BEQL @CHECK_ENEMY_COLOR_CHANGE
	LDX #.LOWORD(PSI_ANIMATION_STATE) + psi_animation_state::time_until_next_frame
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	DEC
	STA PSI_ANIMATION_STATE + psi_animation_state::time_until_next_frame
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @CHECK_PALETTE_ANIMATION
	LDA #.LOWORD(PSI_ANIMATION_STATE) + psi_animation_state::total_frames
	STA @VIRTUAL04
	LDX @VIRTUAL04
	LDA __BSS_START__,X
	AND #$00FF
	BEQ @ALL_FRAMES_DONE
	SEP #PROC_FLAGS::ACCUM8
	LDA PSI_ANIMATION_STATE + psi_animation_state::frame_hold_frames
	STA PSI_ANIMATION_STATE + psi_animation_state::time_until_next_frame
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(PSI_ANIMATION_STATE) + psi_animation_state::frame_data
	STA @VIRTUAL02
	LDY @VIRTUAL02
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	COPY_TO_VRAM1P @VIRTUAL06, $5800, $400, $06
	.A16
	COPY_TO_VRAM1 PSI_ANIMATION_FILL_DATA, $5800, $400, $0F
	.A16
	LDY @VIRTUAL02
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDA #$0400
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDY @VIRTUAL02
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDX @VIRTUAL04
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	DEC
	LDX @VIRTUAL04
	STA __BSS_START__,X
	BRA @CHECK_PALETTE_ANIMATION
@ALL_FRAMES_DONE:
	.A16
	COPY_TO_VRAM1 PSI_ANIMATION_FILL_DATA+1, $5800, $800, $03
	JSL RESTORE_BG_PALETTE_BACKUPS
@CHECK_PALETTE_ANIMATION:
	LDX #.LOWORD(PSI_ANIMATION_STATE) + psi_animation_state::palette_animation_time_until_next_frame
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL06
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQL @CHECK_ENEMY_COLOR_CHANGE
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL06
	DEC
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @CHECK_ENEMY_COLOR_CHANGE
	SEP #PROC_FLAGS::ACCUM8
	LDA PSI_ANIMATION_STATE + psi_animation_state::palette_animation_frames
	STA __BSS_START__,X
	LDA PSI_ANIMATION_STATE + psi_animation_state::palette_animation_upper_index
	SEC
	SBC PSI_ANIMATION_STATE + psi_animation_state::palette_animation_lower_index
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDX #0
	STX @LOCAL05
	BRA @PALETTE_LOOP_CHECK
@ROTATE_PALETTE_ENTRY:
	LDA PSI_ANIMATION_STATE + psi_animation_state::palette_animation_current_index
	AND #$00FF
	STA @VIRTUAL04
	TXA
	CMP @VIRTUAL04
	BCS @INDEX_NO_WRAP
	TXA
	CLC
	ADC @VIRTUAL02
	SEC
	SBC @VIRTUAL04
	STA @VIRTUAL04
	STA @LOCAL04
	BRA @STORE_PALETTE_ENTRY
@INDEX_NO_WRAP:
	TXA
	SEC
	SBC @VIRTUAL04
	STA @VIRTUAL04
	STA @LOCAL04
@STORE_PALETTE_ENTRY:
	LDA PSI_ANIMATION_STATE + psi_animation_state::palette_animation_lower_index
	AND #$00FF
	STA @LOCAL03
	STX @VIRTUAL04
	CLC
	ADC @VIRTUAL04
	ASL
	CLC
	ADC PSI_ANIMATION_STATE + psi_animation_state::displayed_palette
	PHA
	LDA @LOCAL04
	STA @VIRTUAL04
	LDA @LOCAL03
	CLC
	ADC @VIRTUAL04
	ASL
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(PSI_ANIMATION_STATE)
	TAX
	LDA a:psi_animation_state::palette,X
.ELSE
	TAX
	LDA PSI_ANIMATION_STATE + psi_animation_state::palette,X
.ENDIF
	PLX
	STA __BSS_START__,X
	LDX @LOCAL05
	INX
	STX @LOCAL05
@PALETTE_LOOP_CHECK:
	TXA
	CMP @VIRTUAL02
	BCC @ROTATE_PALETTE_ENTRY
	LDX #.LOWORD(PSI_ANIMATION_STATE) + psi_animation_state::palette_animation_current_index
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	INC
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	CMP @VIRTUAL02
	BCC @WRAP_INDEX
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA __BSS_START__,X
@WRAP_INDEX:
	REP #PROC_FLAGS::ACCUM8
	LDA #24
	JSL SET_PALETTE_UPLOAD_MODE
@CHECK_ENEMY_COLOR_CHANGE:
	LDX #.LOWORD(PSI_ANIMATION_STATE) + psi_animation_state::enemy_colour_change_start_frames_left
	LDA __BSS_START__,X
	BEQ @CHECK_COLOR_RESTORE
	DEC
	STA __BSS_START__,X
	BNE @CHECK_COLOR_RESTORE
	LDA #20
	JSL SET_BATTLE_SPRITE_PALETTE_EFFECT_SPEED
	LDA #0
	STA @VIRTUALTMP01
	BRA @ENEMY_SPRITE_CHECK
@SCAN_ENEMY_SPRITE:
	LDA @VIRTUALTMP01
	ASL
	TAX
	LDA PSI_ANIMATION_ENEMY_TARGETS,X
	BEQ @NEXT_ENEMY_SPRITE
	LDA #1
	STA @VIRTUALTMP02
	BRA @COLOR_EFFECT_CHECK
@APPLY_COLOR_EFFECT:
	LDA PSI_ANIMATION_STATE + psi_animation_state::enemy_colour_change_blue
	STA @LOCAL00
	LDY PSI_ANIMATION_STATE + psi_animation_state::enemy_colour_change_green
	LDX PSI_ANIMATION_STATE + psi_animation_state::enemy_colour_change_red
	LDA @VIRTUALTMP01
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUALTMP02
	JSL SETUP_BATTLE_SPRITE_PALETTE_EFFECT
	INC @VIRTUALTMP02
@COLOR_EFFECT_CHECK:
	LDA @VIRTUALTMP02
	CMP #16
	BCC @APPLY_COLOR_EFFECT
@NEXT_ENEMY_SPRITE:
	INC @VIRTUALTMP01
@ENEMY_SPRITE_CHECK:
	LDA @VIRTUALTMP01
	CMP #4
	BCC @SCAN_ENEMY_SPRITE
@CHECK_COLOR_RESTORE:
	LDX #.LOWORD(PSI_ANIMATION_STATE + psi_animation_state::enemy_colour_change_frames_left)
	LDA __BSS_START__,X
	BEQ @RETURN
	DEC
	STA __BSS_START__,X
	BNE @RETURN
	LDY #0
	STY @LOCAL02
	BRA @RESTORE_LOOP_CHECK
@RESTORE_ENEMY_COLOR:
	TYA
	ASL
	TAX
	LDA PSI_ANIMATION_ENEMY_TARGETS,X
	BEQ @NEXT_RESTORE_ENEMY
	TYX
	LDA #20
	JSL REVERSE_BATTLE_SPRITE_PALETTE_EFFECT
@NEXT_RESTORE_ENEMY:
	LDY @LOCAL02
	INY
	STY @LOCAL02
@RESTORE_LOOP_CHECK:
	CPY #4
	BCC @RESTORE_ENEMY_COLOR
@RETURN:
	END_C_FUNCTION
