
RECOVER_PP:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @VIRTUAL04
	STA @VIRTUAL02
	STA @LOCAL04
	LDX @VIRTUAL02
	LDA a:battler::consciousness,X
	AND #$00FF
	CMP #1
	BNE @RETURN
	LDX @VIRTUAL02
	LDA a:battler::afflictions,X
	AND #$00FF
	CMP #1
	BEQ @RETURN
	LDX @VIRTUAL02
	LDY a:battler::pp_target,X
	LDX @VIRTUAL02
	LDA a:battler::pp_max,X
	STA @LOCAL03
	STA @VIRTUAL02
	TYA
	CLC
	ADC @VIRTUAL04
	CMP @VIRTUAL02
	BCC @WITHIN_MAX
	STY @VIRTUAL02
	LDA @LOCAL03
	SEC
	SBC @VIRTUAL02
	BRA @STORE_RECOVERY
@WITHIN_MAX:
	LDA @VIRTUAL04
@STORE_RECOVERY:
	TAY
	STY @LOCAL02
	LDA @LOCAL04
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA @VIRTUAL04
	CLC
	ADC a:battler::pp_target,X
	TAX
	LDA @VIRTUAL02
	JSR SET_PP
	LOADPTR MSG_BTL_PP_KAIFUKU, @LOCAL00
	LDY @LOCAL02
	TYA
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
@RETURN:
	END_C_FUNCTION
