
RECOVER_HP:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @LOCAL02
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA a:battler::consciousness,X
	AND #$00FF
	CMP #1
	BNE @RETURN
	LDX @VIRTUAL02
	LDA a:battler::afflictions,X
	AND #$00FF
	CMP #1
	BEQ @HEAL_BLOCKED
	LDX @LOCAL02
	STX @VIRTUAL04
	TXA
	LDX @VIRTUAL02
	CLC
	ADC a:battler::hp_target,X
	TAY
	STY @LOCAL02
	TYX
	LDA @VIRTUAL02
	JSR SET_HP
	LDX @VIRTUAL02
	LDY @LOCAL02
	TYA
	CMP a:battler::hp_max,X
	BCC @NOT_MAX_HP
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_HPMAX_KAIFUKU
	BRA @RETURN
@NOT_MAX_HP:
	LOADPTR MSG_BTL_HP_KAIFUKU, @LOCAL00
	MOVE_INT1632 @VIRTUAL04, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DISPLAY_TEXT_WAIT
	BRA @RETURN
@HEAL_BLOCKED:
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_HEAL_NG
@RETURN:
	END_C_FUNCTION
