
REDUCE_HP:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @VIRTUAL02
	TAY
	LDA a:battler::hp_target,Y
	STA @LOCAL00
	STA @VIRTUAL04
	LDA @VIRTUAL02
	CMP @VIRTUAL04
	BLTEQ @SUBTRACT_HP
	LDA #0
	BRA @APPLY_HP
@SUBTRACT_HP:
	LDA @LOCAL00
	SEC
	SBC @VIRTUAL02
@APPLY_HP:
	TAX
	TYA
	JSR SET_HP
	END_C_FUNCTION
