
REMOVE_STATUS_UNTARGETTABLE_TARGETS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX #0
	STX @LOCAL00
	BRA @LOOP_ACTIONS_CHECK
@CHECK_ACTION:
	LDX CURRENT_ATTACKER
	CMP a:battler::current_action,X
	BEQ @DONE
	LDX @LOCAL00
	INX
	STX @LOCAL00
@LOOP_ACTIONS_CHECK:
	TXA
	ASL
	TAX
	LDA f:DEAD_TARGETTABLE_ACTIONS,X
	BNE @CHECK_ACTION
	LDY #0
	STY @LOCAL00
	BRA @LOOP_BATTLERS_CHECK
@CHECK_BATTLER:
	TYA
	JSL IS_CHAR_TARGETTED
	CMP #0
	BEQ @NEXT_BATTLER
	LDY @LOCAL00
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @REMOVE_TARGET
	LDA BATTLERS_TABLE+battler::afflictions,X
	AND #$00FF
	TAX
	CPX #STATUS_0::UNCONSCIOUS
	BEQ @REMOVE_TARGET
	CPX #STATUS_0::DIAMONDIZED
	BNE @NEXT_BATTLER
@REMOVE_TARGET:
	LDY @LOCAL00
	TYA
	JSL REMOVE_TARGET
@NEXT_BATTLER:
	LDY @LOCAL00
	INY
	STY @LOCAL00
@LOOP_BATTLERS_CHECK:
	CPY #BATTLER_COUNT
	BCC @CHECK_BATTLER
@DONE:
	END_C_FUNCTION
