
REMOVE_DEAD_TARGETTING:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX #0
	STX @LOCAL00
	BRA @LOOP_CHECK
@LOOP_BODY:
	TXA
	JSL IS_CHAR_TARGETTED
	CMP #0
	BEQ @NEXT_BATTLER
	LDX @LOCAL00
	TXA
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::afflictions,X
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BNE @NEXT_BATTLER
	LDX @LOCAL00
	TXA
	JSL REMOVE_TARGET
@NEXT_BATTLER:
	LDX @LOCAL00
	INX
	STX @LOCAL00
@LOOP_CHECK:
	CPX #BATTLER_COUNT
	BCC @LOOP_BODY
	END_C_FUNCTION
