
RENDER_ALL_WINDOWS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA RENDER_HPPP_WINDOWS
	AND #$00FF
	BEQ @SKIP_HPPP
	JSR DRAW_ACTIVE_HPPP_WINDOWS
@SKIP_HPPP:
	LDA WINDOW_HEAD
	CMP #$FFFF
	BEQ @DONE
	LDY WINDOW_HEAD
	STY @LOCAL00
@RENDER_LOOP:
	TYA
	JSL RENDER_WINDOW_FRAME
	LDY @LOCAL00
	TYA
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDY WINDOW_STATS+window_stats::next,X
	STY @LOCAL00
	CPY #$FFFF
	BNE @RENDER_LOOP
@DONE:
	END_C_FUNCTION
