
RENDER_AND_DISABLE_ENTITIES:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	JSL UPDATE_PARTY
	JSL REFRESH_PARTY_ENTITIES
	JSL RENDER_FRAME_TICK
	JSL DISABLE_ALL_ENTITIES
	LDA ENTITY_FADE_ENTITY
	CMP #.LOWORD(-1)
	BEQ @DONE
	LDA ENTITY_FADE_ENTITY
	ASL
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	AND #$FFFF ^ (OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED)
	STA __BSS_START__,X
@DONE:
	END_C_FUNCTION
