
RENDER_HPPP_WINDOW_HEADER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	END_STACK_VARS
	LDY #.LOWORD(BG2_BUFFER) + ((ACTIVE_HPPP_WINDOW_Y_OFFSET * 32) - 6) * 2
	LOADPTR HPPP_WINDOW_HEADER_TILES, @VIRTUAL06
	LDX #0
	BRA @LOOP_CHECK
@COPY_TILE:
	LDA [@VIRTUAL06]
	STA __BSS_START__,Y
	INC @VIRTUAL06
	INC @VIRTUAL06
	INY
	INY
	INX
@LOOP_CHECK:
	CPX #4
	BCC @COPY_TILE
	END_C_FUNCTION
