
RENDER_ALL_BATTLE_SPRITES:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	LDA #$007E
	JSL SWAP_SPRITEMAP_BANK
	JSL OAM_CLEAR
	LDA #0
	JSR RENDER_BATTLE_SPRITE_ROW
	LDA #1
	JSR RENDER_BATTLE_SPRITE_ROW
	JSL UPDATE_SCREEN
	END_C_FUNCTION
