
RENDER_BATTLE_SPRITE_ROW:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL04
	LDA #.LOWORD(BATTLERS_TABLE) + .SIZEOF(battler) * 8
	STA @VIRTUAL02
	LDA #8
	STA @VIRTUAL04
	STA @LOCAL03
	JMP @BATTLER_LOOP_CHECK
@BATTLER_LOOP_BODY:
	LDX @VIRTUAL02
	LDA a:battler::consciousness,X
	AND #$00FF
	BEQL @NEXT_BATTLER
	LDX @VIRTUAL02
	LDA a:battler::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	CMP #1
	BEQL @NEXT_BATTLER
	LDX @VIRTUAL02
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BNEL @NEXT_BATTLER
	LDX @VIRTUAL02
	LDA a:battler::row,X
	AND #$00FF
	CMP @LOCAL04
	BNEL @NEXT_BATTLER
	LDX @VIRTUAL02
	LDA a:battler::sprite,X
	BEQL @NEXT_BATTLER
	LDA @VIRTUAL02
	CLC
	ADC #battler::blink_timer
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	BEQ @CHECK_SHAKE
	SEP #PROC_FLAGS::ACCUM8
	DEC
	STA __BSS_START__,X
	LDY #3
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	JSL DIVISION16
	AND #$0001
	BNEL @NEXT_BATTLER
@CHECK_SHAKE:
	LDA @VIRTUAL02
	CLC
	ADC #battler::shake_timer
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	BEQ @CHECK_ALT_SPRITEMAP
	SEP #PROC_FLAGS::ACCUM8
	DEC
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	AND #$0004
	BNE @CHECK_ALT_SPRITEMAP
	LDX @VIRTUAL02
	LDA a:battler::sprite_y,X
	AND #$00FF
	SEC
	SBC SCREEN_EFFECT_VERTICAL_OFFSET
	TAY
	LDX @VIRTUAL02
	LDA a:battler::sprite_x,X
	AND #$00FF
	SEC
	SBC SCREEN_EFFECT_HORIZONTAL_OFFSET
	TAX
	STX @LOCAL02
	LDX @VIRTUAL02
	LDA a:battler::vram_sprite_index,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, 80
	CLC
	ADC #.LOWORD(ALT_BATTLE_SPRITEMAPS)
	LDX @LOCAL02
	JSL WRITE_SPRITEMAP_TO_OAM
	JMP @NEXT_BATTLER
@CHECK_ALT_SPRITEMAP:
	LDX @VIRTUAL02
	LDA a:battler::use_alt_spritemap,X
	AND #$00FF
	BEQ @CHECK_TARGET_FLASH
	LDX @VIRTUAL02
	LDA a:battler::sprite_y,X
	AND #$00FF
	SEC
	SBC SCREEN_EFFECT_VERTICAL_OFFSET
	TAY
	LDX @VIRTUAL02
	LDA a:battler::sprite_x,X
	AND #$00FF
	SEC
	SBC SCREEN_EFFECT_HORIZONTAL_OFFSET
	TAX
	STX @LOCAL01
	LDX @VIRTUAL02
	LDA a:battler::vram_sprite_index,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, 80
	CLC
	ADC #.LOWORD(ALT_BATTLE_SPRITEMAPS)
	LDX @LOCAL01
	JSL WRITE_SPRITEMAP_TO_OAM
	JMP @NEXT_BATTLER
@CHECK_TARGET_FLASH:
	LDA ENEMY_TARGETTING_FLASHING
	BEQ @DRAW_NORMAL_SPRITE
	LDX @VIRTUAL02
	LDA a:battler::is_flash_target,X
	AND #$00FF
	BEQ @DRAW_FLASH_SPRITE
	LDA FRAME_COUNTER
	AND #$00FF
	AND #$0008
	BEQ @DRAW_NORMAL_SPRITE
@DRAW_FLASH_SPRITE:
	LDX @VIRTUAL02
	LDA a:battler::sprite_y,X
	AND #$00FF
	SEC
	SBC SCREEN_EFFECT_VERTICAL_OFFSET
	TAY
	LDX @VIRTUAL02
	LDA a:battler::sprite_x,X
	AND #$00FF
	SEC
	SBC SCREEN_EFFECT_HORIZONTAL_OFFSET
	TAX
	STX @LOCAL02
	LDX @VIRTUAL02
	LDA a:battler::vram_sprite_index,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, 80
	CLC
	ADC #.LOWORD(ALT_BATTLE_SPRITEMAPS)
	LDX @LOCAL02
	JSL WRITE_SPRITEMAP_TO_OAM
	BRA @NEXT_BATTLER
@DRAW_NORMAL_SPRITE:
	LDX @VIRTUAL02
	LDA a:battler::sprite_y,X
	AND #$00FF
	SEC
	SBC SCREEN_EFFECT_VERTICAL_OFFSET
	TAY
	LDX @VIRTUAL02
	LDA a:battler::sprite_x,X
	AND #$00FF
	SEC
	SBC SCREEN_EFFECT_HORIZONTAL_OFFSET
	TAX
	STX @LOCAL00
	LDX @VIRTUAL02
	LDA a:battler::vram_sprite_index,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, 80
	CLC
	ADC #.LOWORD(BATTLE_SPRITEMAPS)
	LDX @LOCAL00
	JSL WRITE_SPRITEMAP_TO_OAM
@NEXT_BATTLER:
	LDA @VIRTUAL02
	CLC
	ADC #.SIZEOF(battler)
	STA @VIRTUAL02
	LDA @LOCAL03
	STA @VIRTUAL04
	INC @VIRTUAL04
	LDA @VIRTUAL04
	STA @LOCAL03
@BATTLER_LOOP_CHECK:
	LDA @VIRTUAL04
	CMP #BATTLER_COUNT
	BCCL @BATTLER_LOOP_BODY
	END_C_FUNCTION
