
RESET_HPPP_METER_SPEED_IF_STABLE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	JSL CHECK_ALL_HPPP_METERS_STABLE
	CMP #0
	BEQ @DONE
	SEP #PROC_FLAGS::ACCUM8
	STZ FASTEST_HPPP_METER_SPEED
@DONE:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
