
SELECT_STEALABLE_ITEM:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	JSR FIND_STEALABLE_ITEMS
	TAX
	STX @LOCAL00
	BNE @HAS_ITEMS
	LDA #0
	BRA @RETURN
@HAS_ITEMS:
	JSL RAND
	AND #$0080
	BEQ @SELECT_ITEM
	LDA #0
	BRA @RETURN
@SELECT_ITEM:
	LDX @LOCAL00
	TXA
	JSR RAND_LIMIT
	TAX
	LDA STEALABLE_ITEM_CANDIDATES,X
	AND #$00FF
@RETURN:
	END_C_FUNCTION
