
SET_TARGET_IF_TARGETED:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	MOVE_INT BATTLER_TARGET_FLAGS, @VIRTUAL06
	CMP @VIRTUAL0A+2
	BNE @CHECK_HIGH_WORD
	LDA @VIRTUAL06
	CMP @VIRTUAL0A
@CHECK_HIGH_WORD:
	BEQ @DONE
	LDX #0
	STX @LOCAL00
	BRA @LOOP_CHECK
@CHECK_BATTLER:
	TXA
	JSL IS_CHAR_TARGETTED
	CMP #0
	BNE @FOUND_TARGET
	LDX @LOCAL00
	INX
	STX @LOCAL00
@LOOP_CHECK:
	CPX #BATTLER_COUNT
	BCC @CHECK_BATTLER
@FOUND_TARGET:
	LDX @LOCAL00
	TXA
	LDY #.SIZEOF(battler)
	JSL MULT168
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	STA CURRENT_TARGET
	JSL FIX_TARGET_NAME
@DONE:
	END_C_FUNCTION
