
SET_BATTLER_TARGETS_BY_ACTION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL00
	MOVE_INT_CONSTANT 0, BATTLER_TARGET_FLAGS
	LDA a:battler::action_targetting,X
	AND #$00FF
	CMP #1
	BEQ @TARGET_ONE
	CMP #2
	BEQ @TARGET_ALLIES
	CMP #4
	BEQ @TARGET_ALLIES
	CMP #17
	BEQ @TARGET_BY_ROW_POSITION
	CMP #18
	BEQL @TARGET_ROW
	CMP #20
	BEQL @TARGET_ALL_ENEMIES
	JMP @DONE
@TARGET_ONE:
	LDA a:battler::current_target,X
	AND #$00FF
	DEC
	JSL TARGET_BATTLER
	JMP @DONE
@TARGET_ALLIES:
	JSL TARGET_ALLIES
	LDX @LOCAL00
	LDA a:battler::current_action,X
	JSL GET_SHIELD_TARGETTING
	CMP #0
	BNE @REMOVE_DEAD_ALLIES
	LDX @LOCAL00
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @REMOVE_DEAD_ALLIES
	JSL REMOVE_NPC_TARGETTING
@REMOVE_DEAD_ALLIES:
	JSL REMOVE_STATUS_UNTARGETTABLE_TARGETS
	JMP @DONE
@TARGET_BY_ROW_POSITION:
	LDA a:battler::current_target,X
	AND #$00FF
	CMP NUM_BATTLERS_IN_FRONT_ROW
	BLTEQ @FRONT_ROW
	SEC
	SBC NUM_BATTLERS_IN_FRONT_ROW
	TAX
	DEX
	LDA BACK_ROW_BATTLERS,X
	AND #$00FF
	JSL TARGET_BATTLER
	BRA @CHECK_HEALING_OMEGA
@FRONT_ROW:
	TAX
	DEX
	LDA FRONT_ROW_BATTLERS,X
	AND #$00FF
	JSL TARGET_BATTLER
@CHECK_HEALING_OMEGA:
	LDX @LOCAL00
	LDA a:battler::current_action,X
	CMP #BATTLE_ACTIONS::PSI_HEALING_OMEGA
	BNE @DONE
	LDA #8
	STA @LOCAL00
	BRA @SCAN_UNCONSCIOUS_CHECK
@SCAN_UNCONSCIOUS_BODY:
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @SCAN_NEXT
	LDA BATTLERS_TABLE+battler::afflictions,X
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BNE @SCAN_NEXT
	MOVE_INT_CONSTANT 0, BATTLER_TARGET_FLAGS
	LDA @LOCAL00
	JSL TARGET_BATTLER
	BRA @DONE
@SCAN_NEXT:
	LDA @LOCAL00
	INC
	STA @LOCAL00
@SCAN_UNCONSCIOUS_CHECK:
	CMP #BATTLER_COUNT
	BCC @SCAN_UNCONSCIOUS_BODY
	BRA @DONE
@TARGET_ROW:
	LDA a:battler::current_target,X
	AND #$00FF
	JSL TARGET_ROW
	JSL REMOVE_NPC_TARGETTING
	JSL REMOVE_STATUS_UNTARGETTABLE_TARGETS
	BRA @DONE
@TARGET_ALL_ENEMIES:
	JSL TARGET_ALL_ENEMIES
	LDX @LOCAL00
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNE @REMOVE_DEAD_ENEMIES
	JSL REMOVE_NPC_TARGETTING
@REMOVE_DEAD_ENEMIES:
	JSL REMOVE_STATUS_UNTARGETTABLE_TARGETS
@DONE:
	END_C_FUNCTION
