SET_BATTLER_PP_FROM_TARGET:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;NEAR battler* target
	STACK_RESERVE_PARAM_INT16 ;
	END_STACK_VARS
	STX @VIRTUAL02
	TAY
	LDA a:battler::pp_target,Y
	STA @LOCAL00
	STA @VIRTUAL04
	LDA @VIRTUAL02
	CMP @VIRTUAL04
	BLTEQ @SUBTRACT
	LDA #0
	BRA @APPLY
@SUBTRACT:
	LDA @LOCAL00
	SEC
	SBC @VIRTUAL02
@APPLY:
	TAX
	TYA
	JSR SET_PP
	END_C_FUNCTION
