
SET_BATTLER_FLASHING:
.IF .DEFINED(JPN)
	BEGIN_C_FUNCTION
.ELSE
	BEGIN_C_FUNCTION_FAR
.ENDIF
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL00
	LDA CURRENT_FLASHING_ROW
	CMP #.LOWORD(-1)
	BEQ @AFTER_CLEAR
.IF .DEFINED(JPN)
	JSR CLEAR_BATTLER_FLASHING
.ELSE
	JSL CLEAR_BATTLER_FLASHING
.ENDIF
@AFTER_CLEAR:
	LDX @LOCAL00
	STX CURRENT_FLASHING_ROW
	LDA CURRENT_FLASHING_ROW
	BEQ @USE_FRONT_ROW
	LDA NUM_BATTLERS_IN_BACK_ROW
	BRA @ROW_COUNT_SET
@USE_FRONT_ROW:
	LDA NUM_BATTLERS_IN_FRONT_ROW
@ROW_COUNT_SET:
	STA @VIRTUAL02
	LDX #0
	STX @LOCAL00
	BRA @LOOP_CHECK
@LOOP_BODY:
	LDA CURRENT_FLASHING_ROW
	BEQ @SET_FRONT_ROW
	LDA BACK_ROW_BATTLERS,X
	AND #$00FF
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA BATTLERS_TABLE + battler::is_flash_target,X
	BRA @NEXT_BATTLER
@SET_FRONT_ROW:
	.A16
	LDA FRONT_ROW_BATTLERS,X
	AND #$00FF
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA BATTLERS_TABLE + battler::is_flash_target,X
@NEXT_BATTLER:
	LDX @LOCAL00
	INX
	STX @LOCAL00
@LOOP_CHECK:
	REP #PROC_FLAGS::ACCUM8
	TXA
	CMP @VIRTUAL02
	BCC @LOOP_BODY
	LDA #1
	STA ENEMY_TARGETTING_FLASHING
	SEP #PROC_FLAGS::ACCUM8
	STA REDRAW_ALL_WINDOWS
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
