
SET_TARGET_NAME_WITH_ARTICLE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
.IF .DEFINED(JPN)
	@TMP := @LOCAL01
.ELSE
	@TMP := @LOCAL02
.ENDIF
	TAY
	STY @LOCAL02
	SEP #PROC_FLAGS::ACCUM8
.IF .DEFINED(USA)
	STZ PRINT_ATTACKER_ARTICLE
.ENDIF
	STZ_BADOPT @LOCAL00
	LDX #.SIZEOF(enemy_data::name) + 2
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(TARGET_NAME_BUFFER)
	JSL MEMSET16
	LDY @LOCAL02
	CPY NUM_BATTLERS_IN_FRONT_ROW
	BLTEQ @FRONT_ROW
	TYA
	SEC
	SBC NUM_BATTLERS_IN_FRONT_ROW
	TAX
	DEX
	LDA BACK_ROW_BATTLERS,X
	AND #$00FF
	STA @VIRTUAL02
	BRA @LOOKUP_BATTLER
@FRONT_ROW:
	TYX
	DEX
	LDA FRONT_ROW_BATTLERS,X
	AND #$00FF
	STA @VIRTUAL02
@LOOKUP_BATTLER:
	LDA @VIRTUAL02
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAY
	STY @LOCAL02
	LOADPTR ENEMY_CONFIGURATION_TABLE, @VIRTUAL06
	LDA BATTLERS_TABLE + battler::id,Y
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	OPTIMIZED_ADD enemy_data::name
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX #.SIZEOF(enemy_data::name)
	LDA #.LOWORD(TARGET_NAME_BUFFER)
	JSR COPY_ENEMY_NAME
	TAX
	STX @LOCAL01
	LDY @LOCAL02
	LDA BATTLERS_TABLE+battler::the_flag,Y
	AND #$00FF
	CMP #1
	BNE @APPEND_LETTER
	LDA BATTLERS_TABLE + battler::enemy_type_id,Y
	JSL FIND_NEXT_ENEMY_LETTER
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	CMP #2
	BEQ @SKIP_LETTER
@APPEND_LETTER:
.IF .DEFINED(USA)
	SEP #PROC_FLAGS::ACCUM8
	LDA #CHAR::SPACE
	LDX @LOCAL01
	STA __BSS_START__,X
	INX
	STX @LOCAL02
	REP #PROC_FLAGS::ACCUM8
.ENDIF
	LDA @VIRTUAL02
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA BATTLERS_TABLE+battler::the_flag,X
	CLC
	ADC #CHAR::A_ - 1
	LDX @TMP
	STA __BSS_START__,X
.IF .DEFINED(USA)
	LDA #1
	STA PRINT_ATTACKER_ARTICLE
.ENDIF
@SKIP_LETTER:
	LDX #.SIZEOF(enemy_data::name) + 1
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(TARGET_NAME_BUFFER)
	JSL SET_BATTLE_ATTACKER_NAME_FAR
.IF .DEFINED(USA)
	LDA @VIRTUAL02
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE + battler::id,X
	STA ATTACKER_ENEMY_ID
.ENDIF
	END_C_FUNCTION
