
SET_BATTLER_TARGET:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16 ;battler*
	STACK_RESERVE_PARAM_INT16 ;int
	END_STACK_VARS
	STX @VIRTUAL02
	TAY
	LDX #0
	BRA @FRONT_ROW_CHECK
@FRONT_ROW_LOOP:
	LDA FRONT_ROW_BATTLERS,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @FRONT_ROW_NEXT
	TXA
	SEP #PROC_FLAGS::ACCUM8
	INC
	STA a:battler::current_target,Y
	BRA @DONE
@FRONT_ROW_NEXT:
	INX
@FRONT_ROW_CHECK:
	CPX NUM_BATTLERS_IN_FRONT_ROW
	BCC @FRONT_ROW_LOOP
	LDX #0
	BRA @BACK_ROW_CHECK
@BACK_ROW_LOOP:
	.A16
	LDA BACK_ROW_BATTLERS,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @BACK_ROW_NEXT
	TXA
	SEP #PROC_FLAGS::ACCUM8
	CLC
	ADC NUM_BATTLERS_IN_FRONT_ROW
	INC
	STA a:battler::current_target,Y
	BRA @DONE
@BACK_ROW_NEXT:
	INX
@BACK_ROW_CHECK:
	CPX NUM_BATTLERS_IN_BACK_ROW
	BCC @BACK_ROW_LOOP
@DONE:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
