
SORT_BATTLERS_INTO_ROWS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	STZ NUM_BATTLERS_IN_BACK_ROW
	STZ NUM_BATTLERS_IN_FRONT_ROW
	LDA #8
	STA @LOCAL02
	BRA @COUNT_LOOP_CHECK
@COUNT_BATTLER:
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @NEXT_COUNT_BATTLER
	LDA BATTLERS_TABLE+battler::afflictions,X
	AND #$00FF
	CMP #1
	BEQ @NEXT_COUNT_BATTLER
	LDA BATTLERS_TABLE+battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BNE @NEXT_COUNT_BATTLER
	LDA BATTLERS_TABLE+battler::row,X
	AND #$00FF
	BEQ @IS_FRONT_ROW
	INC NUM_BATTLERS_IN_BACK_ROW
	BRA @NEXT_COUNT_BATTLER
@IS_FRONT_ROW:
	INC NUM_BATTLERS_IN_FRONT_ROW
@NEXT_COUNT_BATTLER:
	LDA @LOCAL02
	INC
	STA @LOCAL02
@COUNT_LOOP_CHECK:
	CMP #32
	BCC @COUNT_BATTLER
	STZ @LOCAL01
	LDA #0
	STA @VIRTUAL02
	JMP @SORT_FRONT_LOOP_CHECK
@SORT_FRONT_ROW_BODY:
	LDA #$FFFF
	STA @VIRTUAL04
	LDY #8
	STY @LOCAL02
	BRA @FRONT_CANDIDATE_CHECK
@CHECK_FRONT_CANDIDATE:
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @NEXT_FRONT_CANDIDATE
	LDA BATTLERS_TABLE+battler::afflictions,X
	AND #$00FF
	CMP #1
	BEQ @NEXT_FRONT_CANDIDATE
	LDA BATTLERS_TABLE+battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BNE @NEXT_FRONT_CANDIDATE
	LDA BATTLERS_TABLE+battler::row,X
	AND #$00FF
	BNE @NEXT_FRONT_CANDIDATE
	LDA BATTLERS_TABLE+battler::sprite_x,X
	AND #$00FF
	CMP @LOCAL01
	BLTEQ @NEXT_FRONT_CANDIDATE
	CMP @VIRTUAL04
	BGT @NEXT_FRONT_CANDIDATE
	LDY @LOCAL02
	STY @LOCAL00
	STA @VIRTUAL04
@NEXT_FRONT_CANDIDATE:
	LDY @LOCAL02
	INY
	STY @LOCAL02
@FRONT_CANDIDATE_CHECK:
	CPY #32
	BCC @CHECK_FRONT_CANDIDATE
	LDA @LOCAL00
	SEP #PROC_FLAGS::ACCUM8
	LDX @VIRTUAL02
	STA FRONT_ROW_BATTLERS,X
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	LSR
	LSR
	LSR
	SEP #PROC_FLAGS::ACCUM8
	LDX @VIRTUAL02
	STA BATTLER_FRONT_ROW_X_POSITIONS,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::sprite,X
	JSR GET_BATTLE_SPRITE_HEIGHT
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	LDA #18
	SEC
	SBC @VIRTUAL00
	LDX @VIRTUAL02
	STA BATTLER_FRONT_ROW_Y_POSITIONS,X
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	STA @LOCAL01
	INC @VIRTUAL02
@SORT_FRONT_LOOP_CHECK:
	LDA @VIRTUAL02
	CMP NUM_BATTLERS_IN_FRONT_ROW
	BCCL @SORT_FRONT_ROW_BODY
	STZ @LOCAL01
	LDA #0
	STA @VIRTUAL02
	JMP @SORT_BACK_LOOP_CHECK
@SORT_BACK_ROW_BODY:
	LDA #$FFFF
	STA @VIRTUAL04
	LDY #8
	STY @LOCAL02
	BRA @BACK_CANDIDATE_CHECK
@CHECK_BACK_CANDIDATE:
	TYA
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::consciousness,X
	AND #$00FF
	BEQ @NEXT_BACK_CANDIDATE
	LDA BATTLERS_TABLE+battler::afflictions,X
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BEQ @NEXT_BACK_CANDIDATE
	LDA BATTLERS_TABLE+battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BNE @NEXT_BACK_CANDIDATE
	LDA BATTLERS_TABLE+battler::row,X
	AND #$00FF
	BEQ @NEXT_BACK_CANDIDATE
	LDA BATTLERS_TABLE+battler::sprite_x,X
	AND #$00FF
	CMP @LOCAL01
	BLTEQ @NEXT_BACK_CANDIDATE
	CMP @VIRTUAL04
	BGT @NEXT_BACK_CANDIDATE
	LDY @LOCAL02
	STY @LOCAL00
	STA @VIRTUAL04
@NEXT_BACK_CANDIDATE:
	LDY @LOCAL02
	INY
	STY @LOCAL02
@BACK_CANDIDATE_CHECK:
	CPY #32
	BCC @CHECK_BACK_CANDIDATE
	LDA @LOCAL00
	SEP #PROC_FLAGS::ACCUM8
	LDX @VIRTUAL02
	STA BACK_ROW_BATTLERS,X
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	LSR
	LSR
	LSR
	SEP #PROC_FLAGS::ACCUM8
	LDX @VIRTUAL02
	STA BATTLER_BACK_ROW_X_POSITIONS,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	LDY #.SIZEOF(battler)
	JSL MULT168
	TAX
	LDA BATTLERS_TABLE+battler::sprite,X
	JSR GET_BATTLE_SPRITE_HEIGHT
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	LDA #16
	SEC
	SBC @VIRTUAL00
	LDX @VIRTUAL02
	STA BATTLER_BACK_ROW_Y_POSITIONS,X
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	STA @LOCAL01
	INC @VIRTUAL02
@SORT_BACK_LOOP_CHECK:
	LDA @VIRTUAL02
	CMP NUM_BATTLERS_IN_BACK_ROW
	BCCL @SORT_BACK_ROW_BODY
	END_C_FUNCTION
