
START_BATTLE_SWIRL:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @VIRTUAL02
	TAY
	JSL INIT_SWIRL_EFFECT
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STA SWIRL_LENGTH_PADDING
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
