
SUCCESS_255:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	JSR RAND_LONG
	CMP @VIRTUAL00
	BCS @FAIL
	REP #PROC_FLAGS::ACCUM8
	LDA #1
	BRA @RETURN
@FAIL:
	REP #PROC_FLAGS::ACCUM8
	LDA #0
@RETURN:
	END_C_FUNCTION
