
SWAP_ITEM_INTO_EQUIPMENT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL07
	STA @VIRTUAL02
	STA @LOCAL06
	TXA
	DEC
	STA @VIRTUAL04
	TYA
	DEC
	STA @VIRTUAL02
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	TAX
	STX @LOCAL05
	LDY @LOCAL07
	TYA
	STA @LOCAL04
	BRA @COMPACT_LOOP_CHECK
@SHIFT_ITEM_DOWN:
	LDA @LOCAL04
	TAY
	DEY
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	STA (@LOCAL03),Y
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL04
	INC
	STA @LOCAL04
@COMPACT_LOOP_CHECK:
	CMP #$000E
	BCS @AFTER_COMPACT
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	STA @LOCAL03
	LDA @LOCAL04
	TAY
	SEP #PROC_FLAGS::ACCUM8
	LDA (@LOCAL03),Y
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	AND #$00FF
	BNE @SHIFT_ITEM_DOWN
@AFTER_COMPACT:
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL02
	LDA @LOCAL04
	DEC
	STA @VIRTUAL02
	LDA @LOCAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	STA __BSS_START__,X
	LDX @LOCAL05
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL06
	STA @VIRTUAL02
	JSL GIVE_ITEM_TO_CHARACTER
	LDA @VIRTUAL04
	INC
	STA @LOCAL03
	PHA
	LDA @VIRTUAL02
	PLY
	STY @VIRTUAL02
	CMP @VIRTUAL02
	BNEL @DIFFERENT_CHARACTER
	LDA @LOCAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::equipment+EQUIPMENT_SLOT::WEAPON
	STA @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	LDA (@LOCAL01)
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @LOCAL05
	LDY @LOCAL07
	CPY @LOCAL05
	BNEL @CHECK_BODY_EQUIP
	LDA @LOCAL06
	STA @VIRTUAL02
	JSL FIND_EMPTY_INVENTORY_SLOT
	SEP #PROC_FLAGS::ACCUM8
	STA (@LOCAL01)
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::equipment + EQUIPMENT_SLOT::BODY
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BCS @WEAPON_AFTER_ADJUST_BODY
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	DEC
	STA __BSS_START__,X
@WEAPON_AFTER_ADJUST_BODY:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::equipment+EQUIPMENT_SLOT::ARMS
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BCS @WEAPON_AFTER_ADJUST_ARMS
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	DEC
	STA __BSS_START__,X
@WEAPON_AFTER_ADJUST_ARMS:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::equipment+EQUIPMENT_SLOT::OTHER
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BCC @WEAPON_DEC_OTHER
	JMP @RETURN
@WEAPON_DEC_OTHER:
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	DEC
	STA __BSS_START__,X
	JMP @RETURN
@CHECK_BODY_EQUIP:
	.A16
	LDA @LOCAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::equipment + EQUIPMENT_SLOT::BODY
	TAX
	STX @LOCAL03
	LDA __BSS_START__,X
	AND #$00FF
	STA @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BNEL @CHECK_ARMS_EQUIP
	LDA @LOCAL06
	STA @VIRTUAL02
	JSL FIND_EMPTY_INVENTORY_SLOT
	SEP #PROC_FLAGS::ACCUM8
	LDX @LOCAL03
	STA __BSS_START__,X
	LDA (@LOCAL01)
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BCS @BODY_AFTER_ADJUST_WEAPON
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	DEC
	STA (@LOCAL01)
@BODY_AFTER_ADJUST_WEAPON:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::equipment+EQUIPMENT_SLOT::ARMS
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BCS @BODY_AFTER_ADJUST_ARMS
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	DEC
	STA __BSS_START__,X
@BODY_AFTER_ADJUST_ARMS:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::equipment+EQUIPMENT_SLOT::OTHER
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BCC @BODY_DEC_OTHER
	JMP @RETURN
@BODY_DEC_OTHER:
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	DEC
	STA __BSS_START__,X
	JMP @RETURN
@CHECK_ARMS_EQUIP:
	.A16
	LDA @LOCAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::equipment + EQUIPMENT_SLOT::ARMS
	TAX
	STX @LOCAL03
	LDA __BSS_START__,X
	AND #$00FF
	STA @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BNEL @CHECK_OTHER_EQUIP
	LDA @LOCAL06
	STA @VIRTUAL02
	JSL FIND_EMPTY_INVENTORY_SLOT
	SEP #PROC_FLAGS::ACCUM8
	LDX @LOCAL03
	STA __BSS_START__,X
	LDA (@LOCAL01)
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BCS @ARMS_AFTER_ADJUST_WEAPON
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	DEC
	STA (@LOCAL01)
@ARMS_AFTER_ADJUST_WEAPON:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::equipment+EQUIPMENT_SLOT::BODY
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BCS @ARMS_AFTER_ADJUST_BODY
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	DEC
	STA __BSS_START__,X
@ARMS_AFTER_ADJUST_BODY:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::equipment+EQUIPMENT_SLOT::OTHER
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BCC @ARMS_DEC_OTHER
	JMP @RETURN
@ARMS_DEC_OTHER:
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	DEC
	STA __BSS_START__,X
	JMP @RETURN
@CHECK_OTHER_EQUIP:
	.A16
	LDA @LOCAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::equipment + EQUIPMENT_SLOT::OTHER
	TAX
	STX @LOCAL03
	LDA __BSS_START__,X
	AND #$00FF
	STA @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BNEL @NO_EQUIP_MATCH
	LDA @LOCAL06
	STA @VIRTUAL02
	JSL FIND_EMPTY_INVENTORY_SLOT
	SEP #PROC_FLAGS::ACCUM8
	LDX @LOCAL03
	STA __BSS_START__,X
	LDA (@LOCAL01)
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BCS @OTHER_AFTER_ADJUST_WEAPON
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	DEC
	STA (@LOCAL01)
@OTHER_AFTER_ADJUST_WEAPON:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::equipment+EQUIPMENT_SLOT::BODY
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BCS @OTHER_AFTER_ADJUST_BODY
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	DEC
	STA __BSS_START__,X
@OTHER_AFTER_ADJUST_BODY:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::equipment+EQUIPMENT_SLOT::ARMS
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BCC @OTHER_DEC_ARMS
	JMP @RETURN
@OTHER_DEC_ARMS:
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	DEC
	STA __BSS_START__,X
	JMP @RETURN
@NO_EQUIP_MATCH:
	CPY @LOCAL05
	BCS @NOEQ_AFTER_ADJUST_WEAPON
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	DEC
	STA (@LOCAL01)
@NOEQ_AFTER_ADJUST_WEAPON:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::equipment+EQUIPMENT_SLOT::BODY
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BCS @NOEQ_AFTER_ADJUST_BODY
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	DEC
	STA __BSS_START__,X
@NOEQ_AFTER_ADJUST_BODY:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::equipment+EQUIPMENT_SLOT::ARMS
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BCS @NOEQ_AFTER_ADJUST_ARMS
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	DEC
	STA __BSS_START__,X
@NOEQ_AFTER_ADJUST_ARMS:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::equipment+EQUIPMENT_SLOT::OTHER
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BCC @NOEQ_DEC_OTHER
	JMP @RETURN
@NOEQ_DEC_OTHER:
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	DEC
	STA __BSS_START__,X
	JMP @RETURN
@DIFFERENT_CHARACTER:
	.A16
	LDY #.LOWORD(PARTY_CHARACTERS) + char_struct::equipment + EQUIPMENT_SLOT::WEAPON
	LDA (@LOCAL02),Y
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BNE @CHECK_TARGET_BODY
	LDX #$0000
	LDA @LOCAL03
	JSL CHANGE_EQUIPPED_WEAPON
	BRA @AFTER_EQUIP_CHANGE
@CHECK_TARGET_BODY:
	.A16
	LDY #.LOWORD(PARTY_CHARACTERS) + char_struct::equipment + EQUIPMENT_SLOT::BODY
	LDA (@LOCAL02),Y
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BNE @CHECK_TARGET_ARMS
	LDX #$0000
	LDA @LOCAL03
	JSL CHANGE_EQUIPPED_BODY
	BRA @AFTER_EQUIP_CHANGE
@CHECK_TARGET_ARMS:
	LDY #.LOWORD(PARTY_CHARACTERS) + char_struct::equipment + EQUIPMENT_SLOT::ARMS
	LDA (@LOCAL02),Y
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BNE @CHECK_TARGET_OTHER
	LDX #$0000
	LDA @LOCAL03
	JSL CHANGE_EQUIPPED_ARMS
	BRA @AFTER_EQUIP_CHANGE
@CHECK_TARGET_OTHER:
	LDY #.LOWORD(PARTY_CHARACTERS) + char_struct::equipment + EQUIPMENT_SLOT::OTHER
	LDA (@LOCAL02),Y
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BNE @AFTER_EQUIP_CHANGE
	LDX #$0000
	LDA @LOCAL03
	JSL CHANGE_EQUIPPED_OTHER
@AFTER_EQUIP_CHANGE:
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	.A16
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::equipment+EQUIPMENT_SLOT::WEAPON
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BCS @AFTER_ADJUST_WEAPON_POST
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	DEC
	STA __BSS_START__,X
@AFTER_ADJUST_WEAPON_POST:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::equipment+EQUIPMENT_SLOT::BODY
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BCS @AFTER_ADJUST_BODY_POST
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	DEC
	STA __BSS_START__,X
@AFTER_ADJUST_BODY_POST:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::equipment+EQUIPMENT_SLOT::ARMS
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BCS @AFTER_ADJUST_ARMS_POST
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	DEC
	STA __BSS_START__,X
@AFTER_ADJUST_ARMS_POST:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::equipment+EQUIPMENT_SLOT::OTHER
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CMP @VIRTUAL02
	BCS @RETURN
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	DEC
	STA __BSS_START__,X
@RETURN:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
