
TARGET_ROW:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAY
	STY @LOCAL01
	MOVE_INT_CONSTANT 0, BATTLER_TARGET_FLAGS
	LDX #.LOWORD(BATTLERS_TABLE)
	LDA #0
	STA @LOCAL00
	JMP @LOOP_CHECK
@CHECK_BATTLER:
	LDA a:battler::consciousness,X
	AND #$00FF
	BEQL @NEXT_BATTLER
	LDY @LOCAL01
	TYA
	BEQ @TARGET_ALLIES
	CMP #1
	BEQ @TARGET_ENEMY_ROW
	CMP #2
	BEQ @TARGET_ENEMY_ROW
	JMP @NEXT_BATTLER
@TARGET_ALLIES:
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BNEL @NEXT_BATTLER
	LOADPTR POWERS_OF_TWO_32BIT, @VIRTUAL06
	LDA @LOCAL00
	ASL
	ASL
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL0A
	MOVE_INT BATTLER_TARGET_FLAGS, @VIRTUAL06
	OR_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, BATTLER_TARGET_FLAGS
	BRA @NEXT_BATTLER
@TARGET_ENEMY_ROW:
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	CMP #1
	BNE @NEXT_BATTLER
	TYA
	DEC
	STA @VIRTUAL02
	LDA a:battler::row,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @NEXT_BATTLER
	LOADPTR POWERS_OF_TWO_32BIT, @VIRTUAL06
	LDA @LOCAL00
	ASL
	ASL
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL0A
	MOVE_INT BATTLER_TARGET_FLAGS, @VIRTUAL06
	OR_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, BATTLER_TARGET_FLAGS
@NEXT_BATTLER:
	TXA
	CLC
	ADC #.SIZEOF(battler)
	TAX
	LDA @LOCAL00
	INC
	STA @LOCAL00
@LOOP_CHECK:
	CMP #BATTLER_COUNT
	BCCL @CHECK_BATTLER
	END_C_FUNCTION
