
TARGET_ALLIES:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	MOVE_INT_CONSTANT 0, BATTLER_TARGET_FLAGS
	LDX #.LOWORD(BATTLERS_TABLE)
	LDA #0
	STA @LOCAL00
	BRA @LOOP_CHECK
@LOOP_BODY:
	LDA a:battler::consciousness,X
	AND #$00FF
	BEQ @NEXT_BATTLER
	LDA a:battler::ally_or_enemy,X
	AND #$00FF
	BEQ @TARGET_THIS
	LDA a:battler::npc_id,X
	AND #$00FF
	BEQ @NEXT_BATTLER
@TARGET_THIS:
	LOADPTR POWERS_OF_TWO_32BIT, @VIRTUAL06
	LDA @LOCAL00
	ASL
	ASL
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL0A
	MOVE_INT BATTLER_TARGET_FLAGS, @VIRTUAL06
	OR_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, BATTLER_TARGET_FLAGS
@NEXT_BATTLER:
	TXA
	CLC
	ADC #.SIZEOF(battler)
	TAX
	LDA @LOCAL00
	INC
	STA @LOCAL00
@LOOP_CHECK:
	CMP #BATTLER_COUNT
	BCC @LOOP_BODY
	END_C_FUNCTION
