
UPDATE_TEDDY_BEAR_PARTY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT8
	STACK_RESERVE_INT8
	END_STACK_VARS
	SEP #PROC_FLAGS::ACCUM8
	STZ @LOCAL05
	STZ @LOCAL04
	JMP @PARTY_LOOP_TEST
@CHECK_PARTY_MEMBER:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL04
	AND #$00FF
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
.ELSE
	TAX
	LDA GAME_STATE + game_state::party_members,X
.ENDIF
	AND #$00FF
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	TAX
	STX @LOCAL03
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA @VIRTUAL01
	JMP @ITEM_LOOP_TEST
@CHECK_ITEM_TYPE:
	.A16
	LOADPTR ITEM_CONFIGURATION_TABLE, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	LDA @VIRTUAL00
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	STA @LOCAL01
	CLC
	ADC #item::type
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	CMP #4
	BNE @NEXT_ITEM
	LDA @LOCAL05
	AND #$00FF
	BEQ @UPDATE_BEST
	LDA @LOCAL01
	CLC
	ADC #item::params + item_parameters::ep
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL05
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::ep
	MOVE_INTX @LOCAL02, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	CLC
	SBC @VIRTUAL00
	BRANCHLTEQS @NEXT_ITEM
@UPDATE_BEST:
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	STA @VIRTUAL00
	STA @LOCAL05
@NEXT_ITEM:
	SEP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL01
@ITEM_LOOP_TEST:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL01
	AND #$00FF
	STA @VIRTUAL02
	LDA #14
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @NEXT_PARTY_MEMBER
	LDX @LOCAL03
	TXA
	CLC
	ADC @VIRTUAL02
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA a:char_struct::items,X
	STA @VIRTUAL00
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	AND #$00FF
	BNEL @CHECK_ITEM_TYPE
@NEXT_PARTY_MEMBER:
	SEP #PROC_FLAGS::ACCUM8
	INC @LOCAL04
@PARTY_LOOP_TEST:
	LDA GAME_STATE+game_state::player_controlled_party_count
	CMP @LOCAL04
	BGTL @CHECK_PARTY_MEMBER
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL05
	AND #$00FF
	BEQ @NO_TEDDY_BEAR
	LOADPTR ITEM_CONFIGURATION_TABLE, @VIRTUAL06
	LDA @LOCAL05
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::params + item_parameters::strength
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	JSL CHECK_CHARACTER_IN_PARTY
	CMP #$0000
	BNE @RETURN
	LDA #PARTY_MEMBER::TEDDY_BEAR
	JSL REMOVE_CHAR_FROM_PARTY
	LDA #PARTY_MEMBER::PLUSH_TEDDY_BEAR
	JSL REMOVE_CHAR_FROM_PARTY
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	JSL ADD_CHAR_TO_PARTY
	BRA @RETURN
@NO_TEDDY_BEAR:
	LDA #PARTY_MEMBER::TEDDY_BEAR
	JSL REMOVE_CHAR_FROM_PARTY
	LDA #PARTY_MEMBER::PLUSH_TEDDY_BEAR
	JSL REMOVE_CHAR_FROM_PARTY
@RETURN:
	END_C_FUNCTION
