
UPDATE_TILEMAP_COLUMN:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA TILEMAP_UPDATE_TILE_HEIGHT
	ASL
	STA @VIRTUAL04
	LDA #0
	STA @VIRTUAL02
	BRA @LOOP_CHECK
@LOOP_BODY:
	LDA TILEMAP_UPDATE_TILE_Y
	OPTIMIZED_MULT @VIRTUAL04, 32
	CLC
	ADC TILEMAP_UPDATE_BASE_ADDRESS
	CLC
	ADC TILEMAP_UPDATE_TILE_X
	STA @LOCAL01
	INC TILEMAP_UPDATE_TILE_X
	MOVE_INT TILEMAP_UPDATE_REMAINING_TILES, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @LOCAL01
	TAY
	LDX @VIRTUAL04
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	.A16
	MOVE_INT TILEMAP_UPDATE_REMAINING_TILES, @VIRTUAL06
	LDA TILEMAP_UPDATE_TILE_WIDTH
	ASL
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA TILEMAP_UPDATE_REMAINING_TILES
	LDA @VIRTUAL06+2
	STA TILEMAP_UPDATE_REMAINING_TILES+2
	LDA TILEMAP_UPDATE_TILE_X
	CMP #32
	BEQ @WRAP_BASE_ADDRESS
	LDA TILEMAP_UPDATE_TILE_X
	CMP #64
	BNE @SKIP_WRAP
@WRAP_BASE_ADDRESS:
	LDA TILEMAP_UPDATE_BASE_ADDRESS
	EOR #$0400
	STA TILEMAP_UPDATE_BASE_ADDRESS
@SKIP_WRAP:
	INC @VIRTUAL02
@LOOP_CHECK:
	LDA @VIRTUAL02
	CMP TILEMAP_UPDATE_TILE_COUNT
	BCC @LOOP_BODY
	END_C_FUNCTION
