
UPLOAD_BATTLE_SCREEN_TO_VRAM:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	COPY_TO_VRAM2 BG2_BUFFER, $7C00, $700, $00
	.A16
	COPY_TO_VRAM1 BLANK_TILE_DATA, $7F80, $40, $00
	END_C_FUNCTION
