
WEAKEN_SHIELD:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	STZ SHIELD_HAS_NULLIFIED_DAMAGE
	LDA DAMAGE_IS_REFLECTED
	BEQ @DONE
	JSR SWAP_ATTACKER_WITH_TARGET
	LDA CURRENT_TARGET
	CLC
	ADC #battler::shield_hp
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNE @SHIELD_STILL_ACTIVE
	LDX CURRENT_TARGET
	SEP #PROC_FLAGS::ACCUM8
	STZ a:battler::afflictions + STATUS_GROUP::SHIELD,X
	REP #PROC_FLAGS::ACCUM8
	DISPLAY_BATTLE_TEXT_PTR MSG_BTL_SHIELD_OFF
@SHIELD_STILL_ACTIVE:
	STZ DAMAGE_IS_REFLECTED
@DONE:
	END_C_FUNCTION
