
CHECK_ALL_BLOCKS_SIGNATURE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX #0
	STX @LOCAL00
	BRA @LOOP_CHECK
@CHECK_NEXT_BLOCK:
	TXA
	JSR CHECK_BLOCK_SIGNATURE
	LDX @LOCAL00
	INX
	STX @LOCAL00
@LOOP_CHECK:
	CPX #SAVE_COUNT*SAVE_COPY_COUNT
	BCC @CHECK_NEXT_BLOCK
	END_C_FUNCTION
