
CHECK_SAVE_CORRUPTION:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int slot
	END_STACK_VARS
	TAY
	STY @LOCAL01
	TYA
	ASL
	STA @VIRTUAL02
	JSR VALIDATE_SAVE_BLOCK_CHECKSUMS
	CMP #FALSE
	BEQ @CHECK_BACKUP_BLOCK
	LDA @VIRTUAL02
	JSR ERASE_SAVE_BLOCK
	LDX @VIRTUAL02
	INX
	STX @LOCAL00
	TXA
	JSR VALIDATE_SAVE_BLOCK_CHECKSUMS
	CMP #FALSE
	BEQ @RESTORE_FROM_BACKUP
	LDX @LOCAL00
	TXA
	JSR ERASE_SAVE_BLOCK
	LDY @LOCAL01
	TYX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:SAVE_SLOT_BIT_FLAGS,X
	ORA CORRUPTION_CHECK_RESULTS
	STA CORRUPTION_CHECK_RESULTS
	BRA @DONE
@RESTORE_FROM_BACKUP:
	LDX @LOCAL00
	LDA @VIRTUAL02
	JSR COPY_SAVE_BLOCK
@CHECK_BACKUP_BLOCK:
	LDY @VIRTUAL02
	INY
	STY @LOCAL01
	TYA
	JSR VALIDATE_SAVE_BLOCK_CHECKSUMS
	.A16
	CMP #FALSE
	BEQ @DONE
	LDY @LOCAL01
	TYA
	JSR ERASE_SAVE_BLOCK
	LDX @VIRTUAL02
	LDY @LOCAL01
	TYA
	JSR COPY_SAVE_BLOCK
@DONE:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
