
UPDATE_REPLAY_SAVE_SLOT:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	JSL TEST_SRAM_SIZE
	CMP #0
	BEQ @RETURN ;insufficient SRAM
	LDA REPLAY_MODE_ACTIVE
	BEQ @USE_RANDOM_SPRITE
	JSL LOAD_REPLAY_SAVE_SLOT
	LDA GAME_STATE+game_state::leader_x_coord
	STA UNUSED_7EB569
	LDA GAME_STATE+game_state::leader_y_coord
	STA UNUSED_7EB56B
	BRA @RETURN
@USE_RANDOM_SPRITE:
	JSL SAVE_REPLAY_SAVE_SLOT
@RETURN:
	END_C_FUNCTION
