
ADVANCE_FLYOVER_PIXEL_OFFSET:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, 24
	PHP
	LSR
	LSR
	LSR
	PLP
	BCC @APPLY_SIGN_EXTENSION
	ORA #$C000
@APPLY_SIGN_EXTENSION:
	STA @VIRTUAL02
	LDA #104
	SEC
	SBC @VIRTUAL02
	STA FLYOVER_VWF_X
	END_C_FUNCTION
