
CALCULATE_MOVEMENT_PATH_STEPS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @LOCAL06
	STX @VIRTUAL02
	TAX
	LDY @PARAM03
	STY @LOCAL05
	LDA #0
	STA @VIRTUAL04
	STX @LOCAL01 + fixed_point::integer
	LDA @VIRTUAL02
	STA @LOCAL02 + fixed_point::integer
@STEP_LOOP:
	LDA @LOCAL01 + fixed_point::integer
	SEC
	SBC @LOCAL06
	STA @LOCAL04
	LDA @LOCAL02 + fixed_point::integer
	SEC
	SBC @LOCAL05
	STA @VIRTUAL02
	STA @LOCAL03
	LDA @LOCAL04
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @X_DIFF_POSITIVE
	LDA @LOCAL04
	EOR #$FFFF
	INC
	BRA @X_ABS_DONE
@X_DIFF_POSITIVE:
	LDA @LOCAL04
@X_ABS_DONE:
	CLC
	SBC #1
	BRANCHGTS @NOT_ARRIVED
	LDA @LOCAL03
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @Y_DIFF_POSITIVE
	LDA @VIRTUAL02
	EOR #$FFFF
	INC
	BRA @Y_ABS_DONE
@Y_DIFF_POSITIVE:
	LDA @VIRTUAL02
@Y_ABS_DONE:
	CLC
	SBC #1
	JUMPLTEQS @ARRIVED
@NOT_ARRIVED:
	LDA @LOCAL05
	STA @LOCAL00
	LDY @LOCAL06
	LDX @LOCAL02 + fixed_point::integer
	LDA @LOCAL01 + fixed_point::integer
	JSL CALCULATE_DIRECTION_FROM_POSITIONS
	LDY #$2000
	CLC
	ADC #$1000
	JSL DIVISION16S_DIVISOR_POSITIVE
	TAX
	STX @LOCAL04
	TXA
	ASL
	TAX
	LDA f:AUTO_MOVEMENT_DIRECTION_TABLE,X
	JSL RECORD_AUTO_MOVEMENT_STEP
	LDX @LOCAL04
	TXA
	ASL
	ASL
	STA @LOCAL04
	CLC
	ADC #.LOWORD(HORIZONTAL_MOVEMENT_SPEEDS)
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL0A
	MOVE_INT @LOCAL01, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDA @LOCAL04
	CLC
	ADC #.LOWORD(VERTICAL_MOVEMENT_SPEEDS)
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL0A
	MOVE_INT @LOCAL02, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, @LOCAL02
	INC @VIRTUAL04
	JMP @STEP_LOOP
@ARRIVED:
	LDA @VIRTUAL04
	END_C_FUNCTION
