
CHECK_DOOR_NEAR_LEADER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
.IF .DEFINED(JPN) ;why were these swapped?
	@TMP1 := @VIRTUAL02
	@TMP2 := @VIRTUAL04
.ELSE
	@TMP1 := @VIRTUAL04
	@TMP2 := @VIRTUAL02
.ENDIF
	STA @TMP2
	ASL
	TAX
	LDA GAME_STATE+game_state::leader_x_coord
	LSR
	LSR
	LSR
	CLC
	ADC DIRECTION_X_OFFSET_TABLE,X
	STA @LOCAL01
	LDA @TMP2
	CMP #4
	BNE @NOT_FACING_DOWN
	LDA GAME_STATE+game_state::leader_y_coord
	INC
	LSR
	LSR
	LSR
	CLC
	ADC DIRECTION_Y_OFFSET_TABLE,X
	STA @TMP1
	BRA @Y_CALCULATED
@NOT_FACING_DOWN:
	LDA GAME_STATE+game_state::leader_y_coord
	LSR
	LSR
	LSR
	CLC
	ADC DIRECTION_Y_OFFSET_TABLE,X
	STA @TMP1
@Y_CALCULATED:
	LDA @TMP2
	STA @LOCAL00
	LDY GAME_STATE+game_state::current_party_members
	LDA @TMP1
	ASL
	ASL
	ASL
	TAX
	LDA @LOCAL01
	ASL
	ASL
	ASL
	JSL CHECK_ENTITY_COLLISION
	AND #$0082
	CMP #$0082
	BNE @FIND_DOOR
	LDA @TMP2
	ASL
	TAX
	LDA DIRECTION_X_OFFSET_TABLE,X
	CLC
	ADC @LOCAL01
	STA @LOCAL01
	LDA @TMP1
	CLC
	ADC DIRECTION_Y_OFFSET_TABLE,X
	STA @TMP1
@FIND_DOOR:
	LDX @TMP1
	LDA @LOCAL01
	JSL FIND_DOOR_AT_POSITION
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
	CPX #<-1
	BNE @CHECK_AFTER_RIGHT
	LDX @TMP1
	LDA @LOCAL01
	INC
	JSL FIND_DOOR_AT_POSITION
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
@CHECK_AFTER_RIGHT:
	CPX #<-1
	BNE @CHECK_DOOR_TYPE
	LDX @TMP1
	LDA @LOCAL01
	DEC
	JSL FIND_DOOR_AT_POSITION
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
@CHECK_DOOR_TYPE:
	CPX #<-1
	BEQ @DONE
	CPX #5
	BNE @DONE
	LOADPTR DOOR_DATA&$FF0000, @VIRTUAL06
	LDA DOOR_FOUND
	AND #$7FFF
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA DOOR_FOUND_TYPE
	STA UNREAD_7E5DDC
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, MAP_OBJECT_TEXT
	LDA #.LOWORD(-2)
	STA INTERACTING_NPC_ID
@DONE:
	END_C_FUNCTION
