
CHECK_IF_PSI_KNOWN:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	STA @LOCAL02
	CMP #PARTY_MEMBER::NESS
	BEQ @GET_NESS_LEVEL
	CMP #PARTY_MEMBER::PAULA
	BEQ @GET_PAULA_LEVEL
	CMP #PARTY_MEMBER::POO
	BEQ @GET_POO_LEVEL
	BRA @CHECK_LEARN_LEVEL
@GET_NESS_LEVEL:
	TXA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(psi_ability)
	CLC
	ADC #psi_ability::ness_level
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:PSI_ABILITY_TABLE,X
	STA @VIRTUAL00
	STA @LOCAL01
	BRA @CHECK_LEARN_LEVEL
@GET_PAULA_LEVEL:
	.A16
	TXA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(psi_ability)
	CLC
	ADC #psi_ability::paula_level
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:PSI_ABILITY_TABLE,X
	STA @VIRTUAL00
	STA @LOCAL01
	BRA @CHECK_LEARN_LEVEL
@GET_POO_LEVEL:
	.A16
	TXA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(psi_ability)
	CLC
	ADC #psi_ability::poo_level
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:PSI_ABILITY_TABLE,X
	STA @VIRTUAL00
	STA @LOCAL01
@CHECK_LEARN_LEVEL:
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	AND #$00FF
	BEQ @NOT_LEARNABLE
	LDX #0
	STX @LOCAL00
	LDA @LOCAL02
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	CMP PARTY_CHARACTERS+char_struct::level,X
	BGT @CHECK_RESULT
	LDX #1
	STX @LOCAL00
@CHECK_RESULT:
	LDX @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	TXA
	BRA @RETURN
@NOT_LEARNABLE:
	LDA #0
@RETURN:
	END_C_FUNCTION
