; A = character ID (starting at 1), X = item slot
CHECK_ITEM_EQUIPPED:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @VIRTUAL02
	TAX
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::WEAPON,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @CHECK_BODY
	LDA #$0001
	BRA @RETURN
@CHECK_BODY:
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @CHECK_ARMS
	LDA #$0001
	BRA @RETURN
@CHECK_ARMS:
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::ARMS,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @CHECK_OTHER
	LDA #$0001
	BRA @RETURN
@CHECK_OTHER:
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @NOT_EQUIPPED
	LDA #$0001
	BRA @RETURN
@NOT_EQUIPPED:
	LDA #$0000
@RETURN:
	PLD
	RTL
