
CLEAR_ALL_STATUS_EFFECTS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #0
	STA @LOCAL01
	BRA @CHECK_ENTITY_INDEX
@CLEAR_SURFACE_FLAGS:
	ASL
	TAX
	STZ ENTITY_SURFACE_FLAGS,X
	LDA @LOCAL01
	INC
	STA @LOCAL01
@CHECK_ENTITY_INDEX:
	CMP #MAX_ENTITIES
	BCC @CLEAR_SURFACE_FLAGS
	LDX #0
	STX @LOCAL00
	BRA @CHECK_MEMBER_INDEX
@MEMBER_LOOP:
	LDA #0
	STA @LOCAL01
	BRA @CHECK_GROUP_INDEX
@CLEAR_AFFLICTION:
	STA @VIRTUAL02
	LDX @LOCAL00
	TXA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::afflictions
	CLC
	ADC @VIRTUAL02
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	INC
	STA @LOCAL01
@CHECK_GROUP_INDEX:
	CMP #7
	BCC @CLEAR_AFFLICTION
	LDX @LOCAL00
	INX
	STX @LOCAL00
@CHECK_MEMBER_INDEX:
	CPX #6
	BCC @MEMBER_LOOP
	SEP #PROC_FLAGS::ACCUM8
	STZ GAME_STATE + game_state::party_status
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
