
CLEAR_BUFFER_RANGE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STORE_INT1632 @VIRTUAL06
	CLC
	VAR_ADD_CONST_INT_ASSIGN BUFFER, @VIRTUAL06
	BRA @BYTE_LOOP_CHECK
@CLEAR_BYTE:
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
	DEX
@BYTE_LOOP_CHECK:
	CPX #0
	BNE @CLEAR_BYTE
	END_C_FUNCTION
