
CLEAR_AUTO_MOVEMENT_BUFFER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	STZ AUTO_MOVEMENT_DEMO_INDEX
	LDA #0
	STA @LOCAL00
	BRA @CLEAR_LOOP_CHECK
@CLEAR_LOOP_BODY:
	OPTIMIZED_MULT @VIRTUAL04, 3
	TAX
	STZ AUTO_MOVEMENT_DEMO_BUFFER+1,X
	SEP #PROC_FLAGS::ACCUM8
	STZ AUTO_MOVEMENT_DEMO_BUFFER,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	INC
	STA @LOCAL00
@CLEAR_LOOP_CHECK:
	CMP #64
	BCC @CLEAR_LOOP_BODY
	END_C_FUNCTION
