
CYCLE_BATTLE_TARGET:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDY #1
	STY @LOCAL02
	LDX #0
	STX @LOCAL01
	BRA @CHECK_CONSCIOUS
@ADVANCE:
	LDY @LOCAL02
	STY @VIRTUAL02
	LDX @LOCAL01
	TXA
	CLC
	ADC @VIRTUAL02
	TAX
	STX @LOCAL01
	STX @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @WRAP_LOW
	LDX #BATTLER_COUNT - 1
	STX @LOCAL01
@WRAP_LOW:
	STX @VIRTUAL02
	LDA #BATTLER_COUNT
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @CHECK_CONSCIOUS
	LDX #0
	STX @LOCAL01
@CHECK_CONSCIOUS:
	LDX @LOCAL01
	TXA
	LDY #.SIZEOF(battler)
	JSL MULT168
	STA @LOCAL00
	TAX
	LDA BATTLERS_TABLE + battler::consciousness,X
	AND #$00FF
	BEQ @ADVANCE
	LDA @LOCAL00
	CLC
	ADC #.LOWORD(BATTLERS_TABLE)
	JSL NULL_C1E1A2
	JSL WINDOW_TICK
@POLL_INPUT:
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA PAD_HELD
	AND #PAD::RIGHT
	BEQ @CHECK_LEFT
	LDY #1
	STY @LOCAL02
	BRA @CYCLE_NEXT
@CHECK_LEFT:
	LDA PAD_HELD
	AND #PAD::LEFT
	BEQ @CHECK_CONFIRM
	LDY #.LOWORD(-1)
	STY @LOCAL02
	BRA @CYCLE_NEXT
@CHECK_CONFIRM:
	LDA PAD_PRESS
	BEQ @POLL_INPUT
	JSL REDIRECT_CLOSE_FOCUS_WINDOW
	BRA @RETURN
@CYCLE_NEXT:
	STY @VIRTUAL02
	LDX @LOCAL01
	TXA
	CLC
	ADC @VIRTUAL02
	TAX
	STX @LOCAL01
	STX @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @CYCLE_WRAP_LOW
	LDX #BATTLER_COUNT - 1
	STX @LOCAL01
@CYCLE_WRAP_LOW:
	STX @VIRTUAL02
	LDA #BATTLER_COUNT
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @CYCLE_WRAP_HIGH
	LDX #0
	STX @LOCAL01
@CYCLE_WRAP_HIGH:
	JSL REDIRECT_CLOSE_FOCUS_WINDOW
	JMP @CHECK_CONSCIOUS
@RETURN:
	END_C_FUNCTION
