
DECREASE_WALLET_BALANCE:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	MOVE_INT @PARAM00, $06
	LDY #.LOWORD(GAME_STATE)+game_state::money_carried
	MOVE_INT $06, $0A
	MOVE_INT_YPTRSRC __BSS_START__, $06
	SEC
	SUB_INT_ASSIGN $06, $0A
	MOVE_INT_CONSTANT NULL, $0A
	CLC
	LDA $0A
	SBC $06
	LDA $0C
	SBC $08
	BRANCHLTEQS @BALANCE_SUFFICIENT
	LDA #$0001
	BRA @RETURN
@BALANCE_SUFFICIENT:
	MOVE_INT_YPTRDEST $06, __BSS_START__
	LDA #$0000
@RETURN:
	PLD
	RTL
