
ENABLE_CHARACTER_MOVEMENT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	CMP #<-1
	BEQ @ALL_CHARACTERS
	SEP #PROC_FLAGS::ACCUM8
	JSL FIND_ENTITY_FOR_CHARACTER
	.A16
	CMP #.LOWORD(-1)
	BEQ @DONE
	ASL
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	AND #$FFFF ^ (OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED)
	STA __BSS_START__,X
	BRA @DONE
@ALL_CHARACTERS:
	LDX #.LOWORD(ENTITY_TICK_CALLBACK_HIGH) + 23 * 2
	LDA __BSS_START__,X
	AND #$FFFF ^ (OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED)
	STA __BSS_START__,X
	LDA #0
	STA @LOCAL00
	BRA @PARTY_LOOP_CHECK
@ENABLE_PARTY_MEMBER:
	ASL
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_entity_slots,X
.ELSE
	TAX
	LDA GAME_STATE + game_state::party_entity_slots,X
.ENDIF
	ASL
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	AND #$FFFF ^ (OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED)
	STA __BSS_START__,X
	LDA @LOCAL00
	INC
	STA @LOCAL00
@PARTY_LOOP_CHECK:
	LDA GAME_STATE+game_state::party_count
	AND #$00FF
	STA @VIRTUAL02
	LDA @LOCAL00
	CMP @VIRTUAL02
	BCC @ENABLE_PARTY_MEMBER
@DONE:
	END_C_FUNCTION
