
ENABLE_PARTY_MOVEMENT_AND_SHOW:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA GAME_STATE + game_state::party_entity_slots
	ASL
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	AND #$FFFF ^ (OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED)
	STA __BSS_START__,X
	LDA #1
	STA @LOCAL00
	BRA @LOOP_CHECK
@LOOP_BODY:
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_order,X
.ELSE
	TAX
	LDA GAME_STATE + game_state::party_order,X
.ENDIF
	AND #$00FF
	CMP #9
	BEQ @NEXT_MEMBER
	LDA @LOCAL00
	ASL
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_entity_slots,X
.ELSE
	TAX
	LDA GAME_STATE + game_state::party_entity_slots,X
.ENDIF
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAX
	LDA __BSS_START__,X
	AND #$FFFF ^ (SPRITEMAP_FLAGS::DRAW_DISABLED)
	STA __BSS_START__,X
@NEXT_MEMBER:
	LDA @LOCAL00
	INC
	STA @LOCAL00
@LOOP_CHECK:
	LDA GAME_STATE+game_state::party_count
	AND #$00FF
	STA @VIRTUAL02
	LDA @LOCAL00
	CMP @VIRTUAL02
	BCC @LOOP_BODY
	END_C_FUNCTION
