
ENABLE_TESSIE_LEAVES_ENTITIES:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #0
	STA @LOCAL00
	BRA @LOOP_CHECK
@LOOP_BODY:
	ASL
	TAX
	LDA ENTITY_SPRITE_IDS,X
	CMP #OVERWORLD_SPRITE::LEAVES_FOR_TESSIE_SCENE
	BNE @NEXT_ENTITY
	TXA
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	AND #$FFFF ^ (OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED)
	STA __BSS_START__,X
@NEXT_ENTITY:
	LDA @LOCAL00
	INC
	STA @LOCAL00
@LOOP_CHECK:
	CMP #MAX_ENTITIES
	BCC @LOOP_BODY
	END_C_FUNCTION
