
FIND_CONDIMENT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int item
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::type
	TAX
	LDA f:ITEM_CONFIGURATION_TABLE,X
	AND #$00FF
	AND #$003C
	CMP #$0020
	BNE @NOT_FOUND
	LDX CURRENT_ATTACKER
	LDA __BSS_START__,X
	TAY
	DEY
	STY @LOCAL02
	LDX #0
	STX @LOCAL01
	BRA @ITEM_LOOP_TEST
@CHECK_CONDIMENT_TYPE:
	AND #$00FF
	STA @LOCAL00
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::type
	TAX
	LDA f:ITEM_CONFIGURATION_TABLE,X
	AND #$00FF
	AND #$003C
	CMP #$0028
	BNE @NEXT_ITEM
	LDA @LOCAL00
	BRA @RETURN
@NEXT_ITEM:
	LDX @LOCAL01
	INX
	STX @LOCAL01
@ITEM_LOOP_TEST:
	CPX #.SIZEOF(char_struct::items)
	BCS @NOT_FOUND
	STX @VIRTUAL02
	LDY @LOCAL02
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	BNE @CHECK_CONDIMENT_TYPE
@NOT_FOUND:
	LDA #FALSE
@RETURN:
	END_C_FUNCTION
