
FIND_INVENTORY_SPACE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	DEC
	STA @LOCAL00
	LDA #0
	STA @VIRTUAL02
	BRA @LOOP_CHECK
@CHECK_SLOT:
	LDA @LOCAL00
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	BNE @NEXT_SLOT
	LDA @LOCAL00
	INC
	BRA @RETURN
@NEXT_SLOT:
	INC @VIRTUAL02
@LOOP_CHECK:
	LDA #.SIZEOF(char_struct::items)
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @CHECK_SLOT
	LDA #FALSE
@RETURN:
	END_C_FUNCTION
