
FIND_INVENTORY_SPACE2:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	CMP #$00FF
	BNE @SINGLE_CHARACTER
	LDY #0
	STY @LOCAL01
	BRA @PARTY_LOOP_CHECK
@CHECK_PARTY_MEMBER:
	TYA
	CLC
.IF .DEFINED(JPN)
	ADC #.LOWORD(GAME_STATE)
	CLC
	ADC #game_state::party_members
.ELSE
	ADC #.LOWORD(GAME_STATE) + game_state::party_members
.ENDIF
	TAX
	STX @LOCAL00
	LDA __BSS_START__,X
	AND #$00FF
	JSR FIND_INVENTORY_SPACE
	CMP #$0000
	BEQ @NEXT_MEMBER
	LDX @LOCAL00
	LDA __BSS_START__,X
	AND #$00FF
	BRA @RETURN
@NEXT_MEMBER:
	LDY @LOCAL01
	INY
	STY @LOCAL01
@PARTY_LOOP_CHECK:
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	STA @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BCC @CHECK_PARTY_MEMBER
	LDA #0
	BRA @RETURN
@SINGLE_CHARACTER:
	JSR FIND_INVENTORY_SPACE
@RETURN:
	END_C_FUNCTION
