
FIND_ITEM_IN_INVENTORY2:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	STX @VIRTUAL04
	CMP #$00FF
	BNE @SINGLE_CHAR
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL01
	BRA @MEMBER_LOOP_TEST
@SEARCH_MEMBER:
	LDA @LOCAL01
	STA @VIRTUAL02
	CLC
.IF .DEFINED(JPN)
	ADC #.LOWORD(GAME_STATE)
	CLC
	ADC #game_state::party_members
.ELSE
	ADC #.LOWORD(GAME_STATE) + game_state::party_members
.ENDIF
	TAY
	STY @LOCAL00
	LDX @VIRTUAL04
	LDA __BSS_START__,Y
	AND #$00FF
	JSR FIND_ITEM_IN_INVENTORY
	CMP #0
	BEQ @NEXT_MEMBER
	LDY @LOCAL00
	LDA __BSS_START__,Y
	AND #$00FF
	BRA @RETURN
@NEXT_MEMBER:
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL01
@MEMBER_LOOP_TEST:
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	PHA
	LDA @VIRTUAL02
	PLY
	STY @VIRTUAL02
	CMP @VIRTUAL02
	BCC @SEARCH_MEMBER
	LDA #0
	BRA @RETURN
@SINGLE_CHAR:
	LDX @VIRTUAL04
	JSR FIND_ITEM_IN_INVENTORY
@RETURN:
	END_C_FUNCTION
