
GET_ITEM_TYPE:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
.IF .DEFINED(JPN)
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
.ENDIF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::type
	TAX
	LDA f:ITEM_CONFIGURATION_TABLE,X
	AND #$00FF
	AND #$0030
	BEQ @TYPE_00
	CMP #$0010
	BEQ @TYPE_10
	CMP #$0020
	BEQ @TYPE_20
	CMP #$0030
	BEQ @TYPE_30
	BRA @TYPE_OTHER
@TYPE_00:
	LDA #$0001
	BRA @RETURN
@TYPE_10:
	LDA #$0002
	BRA @RETURN
@TYPE_20:
	LDA #$0003
	BRA @RETURN
@TYPE_30:
	LDA #$0004
	BRA @RETURN
@TYPE_OTHER:
	LDA #$0000
@RETURN:
.IF .DEFINED(JPN)
	PLD
.ENDIF
	RTS
