
GET_LEADER_DIRECTION_OFFSET:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA GAME_STATE+game_state::leader_direction
	ASL
	TAX
	LDA f:DIRECTION_TO_DIAGONAL_TABLE,X
	END_C_FUNCTION
