
GIVE_ITEM_TO_SPECIFIC_CHARACTER:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
.IF .DEFINED(JPN)
	STACK_RESERVE_INT16
.ENDIF
	STACK_RESERVE_INT16 "LOCAL01"
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	TXY
	STY @LOCAL01
	TAX
	DEC
	STA @VIRTUAL04
.IF .DEFINED(JPN)
	STA @LOCAL00
.ENDIF
	LDA #0
	STA @VIRTUAL02
	BRA @SLOT_LOOP_TEST
@CHECK_SLOT:
	LDA @VIRTUAL04
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	BNE @SLOT_OCCUPIED
	LDY @LOCAL01
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::type
	TAX
	LDA f:ITEM_CONFIGURATION_TABLE,X
	AND #$00FF
	CMP #ITEM_TYPE::TEDDY_BEAR
	BNE @NOT_TEDDY_BEAR
	JSL UPDATE_TEDDY_BEAR_PARTY
@NOT_TEDDY_BEAR:
	LDY @LOCAL01
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::flags
	TAX
	LDA f:ITEM_CONFIGURATION_TABLE,X
	AND #$00FF
	AND #ITEM_FLAGS::TRANSFORM
	BEQ @NO_TRANSFORM
.IF !.DEFINED(JPN)
	LDY @LOCAL01
.ENDIF
	TYA
	SEP #PROC_FLAGS::ACCUM8
	JSL START_ITEM_TRANSFORMATION
@NO_TRANSFORM:
.IF .DEFINED(JPN)
	LDA @LOCAL00
	STA @VIRTUAL04
.ELSE
	LDA @VIRTUAL04
.ENDIF
	INC
	BRA @RETURN
@SLOT_OCCUPIED:
	INC @VIRTUAL02
@SLOT_LOOP_TEST:
	.A16
	LDA #.SIZEOF(char_struct::items)
	CLC
	SBC @VIRTUAL02
	JUMPGTS @CHECK_SLOT
	LDA #0
@RETURN:
	END_C_FUNCTION
