
HP_PP_ROLLER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA DISABLE_HPPP_ROLLING
	AND #$00FF
	BNEL @EXIT
	LDA FRAME_COUNTER
	AND #$00FF
	AND #$0003
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
.ELSE
	TAX
	LDA GAME_STATE + game_state::party_members,X
.ENDIF
	AND #$00FF
	BEQL @EXIT
	AND #$00FF
	STA @LOCAL02
	CLC
	SBC #4
	JUMPGTS @EXIT
	LDA @LOCAL02
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	STA @LOCAL01
	LDA HPPP_METER_FLIPOUT_MODE
	BNE @HP_ROLLING_ACTIVE
	LDA @LOCAL01
	CLC
	ADC #char_struct::current_hp_fraction
	TAX
	STX @LOCAL00
	LDA __BSS_START__,X
	AND #$0001
	BEQL @HP_CHECK_NEEDS_START
@HP_ROLLING_ACTIVE:
	LDA @LOCAL01
	TAX
	LDY a:char_struct::current_hp,X
	TAX
	LDA a:char_struct::current_hp_target,X
	STA @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BCS @HP_CHECK_REACHED_TARGET
	LDA @LOCAL01
	CLC
	ADC #char_struct::current_hp_fraction
	TAX
	TXY
	STY @LOCAL00
	LDA FASTEST_HPPP_METER_SPEED
	AND #$00FF
	BNE @HP_INC_USE_FAST_SPEED
	LDA HPPP_METER_FLIPOUT_MODE
	BEQ @HP_INC_NORMAL_SPEED
@HP_INC_USE_FAST_SPEED:
	MOVE_INT_CONSTANT $00064000, @VIRTUAL06
	BRA @HP_INC_APPLY_SPEED
@HP_INC_NORMAL_SPEED:
	JSR GET_EFFECTIVE_HPPP_METER_SPEED
@HP_INC_APPLY_SPEED:
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	LDY @LOCAL00
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDA @LOCAL01
	CLC
	ADC #char_struct::current_hp
	TAX
	LDA __BSS_START__,X
	CMP @VIRTUAL02
	BCCL @PP_SECTION
	LDA @VIRTUAL02
	STA __BSS_START__,X
	LDA @LOCAL01
	TAX
	LDA #1
	STA a:char_struct::current_hp_fraction,X
	JMP @PP_SECTION
@HP_CHECK_REACHED_TARGET:
	TYA
	CMP @VIRTUAL02
	BNE @HP_DECREASING
	LDA @LOCAL01
	CLC
	ADC #char_struct::current_hp_fraction
	TAX
	LDA __BSS_START__,X
	CMP #1
	BNE @HP_DECREASING
	LDA #0
	STA __BSS_START__,X
	JMP @PP_SECTION
@HP_DECREASING:
	LDA @LOCAL01
	CLC
	ADC #char_struct::current_hp_fraction
	TAX
	TXY
	STY @LOCAL00
	LDA HPPP_METER_FLIPOUT_MODE
	BEQ @HP_DEC_NORMAL_SPEED
	MOVE_INT_CONSTANT $00064000, @VIRTUAL06
	BRA @HP_DEC_APPLY_SPEED
@HP_DEC_NORMAL_SPEED:
	JSR GET_EFFECTIVE_HPPP_METER_SPEED
@HP_DEC_APPLY_SPEED:
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	LDY @LOCAL00
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	SEC
	SUB_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDA @LOCAL01
	TAX
	LDY a:char_struct::current_hp,X
	TYA
	CMP @VIRTUAL02
	BCC @HP_DEC_CLAMP
	CPY #1000
	BLTEQ @PP_SECTION
@HP_DEC_CLAMP:
	LDA @LOCAL01
	TAX
	LDA @VIRTUAL02
	STA a:char_struct::current_hp,X
	LDA @LOCAL01
	TAX
	LDA #1
	STA a:char_struct::current_hp_fraction,X
	BRA @PP_SECTION
@HP_CHECK_NEEDS_START:
	LDA @LOCAL01
	PHA
	TAX
	LDA a:char_struct::current_hp,X
	PLX
	CMP a:char_struct::current_hp_target,X
	BEQ @PP_SECTION
	LDA #1
	LDX @LOCAL00
	STA __BSS_START__,X
@PP_SECTION:
	LDA HPPP_METER_FLIPOUT_MODE
	BNE @PP_ROLLING_ACTIVE
	LDA @LOCAL01
	CLC
	ADC #char_struct::current_pp_fraction
	TAX
	STX @LOCAL00
	LDA __BSS_START__,X
	AND #$0001
	BEQL @PP_CHECK_NEEDS_START
@PP_ROLLING_ACTIVE:
	LDA @LOCAL01
	TAX
	LDY a:char_struct::current_pp,X
	TAX
	LDA a:char_struct::current_pp_target,X
	STA @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BCS @PP_CHECK_REACHED_TARGET
	LDA @LOCAL01
	CLC
	ADC #char_struct::current_pp_fraction
	TAX
	TXY
	LDA HPPP_METER_FLIPOUT_MODE
	BEQ @PP_INC_NORMAL_SPEED
	MOVE_INT_CONSTANT $00064000, @VIRTUAL06
	BRA @PP_INC_APPLY_SPEED
@PP_INC_NORMAL_SPEED:
	MOVE_INT_CONSTANT $00019000, @VIRTUAL06
@PP_INC_APPLY_SPEED:
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDA @LOCAL01
	CLC
	ADC #char_struct::current_pp
	TAX
	LDA __BSS_START__,X
	CMP @VIRTUAL02
	BCCL @CHECK_FLIPOUT
	LDA @VIRTUAL02
	STA __BSS_START__,X
	LDA @LOCAL01
	TAX
	LDA #1
	STA __BSS_START__ + char_struct::current_pp_fraction,X
	JMP @CHECK_FLIPOUT
@PP_CHECK_REACHED_TARGET:
	TYA
	CMP @VIRTUAL02
	BNE @PP_DECREASING
	LDA @LOCAL01
	CLC
	ADC #char_struct::current_pp_fraction
	TAX
	LDA __BSS_START__,X
	CMP #1
	BNE @PP_DECREASING
	LDA #0
	STA __BSS_START__,X
	JMP @CHECK_FLIPOUT
@PP_DECREASING:
	LDA @LOCAL01
	CLC
	ADC #char_struct::current_pp_fraction
	TAX
	TXY
	LDA HPPP_METER_FLIPOUT_MODE
	BEQ @PP_DEC_NORMAL_SPEED
	MOVE_INT_CONSTANT $00064000, @VIRTUAL06
	BRA @PP_DEC_APPLY_SPEED
@PP_DEC_NORMAL_SPEED:
	MOVE_INT_CONSTANT $00019000, @VIRTUAL06
@PP_DEC_APPLY_SPEED:
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	SEC
	SUB_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDA @LOCAL01
	TAX
	LDY a:char_struct::current_pp,X
	TYA
	CMP @VIRTUAL02
	BCC @PP_DEC_CLAMP
	CPY #1000
	BLTEQ @CHECK_FLIPOUT
@PP_DEC_CLAMP:
	LDA @LOCAL01
	TAX
	LDA @VIRTUAL02
	STA a:char_struct::current_pp,X
	LDA @LOCAL01
	TAX
	LDA #1
	STA __BSS_START__ + char_struct::current_pp_fraction,X
	BRA @CHECK_FLIPOUT
@PP_CHECK_NEEDS_START:
	LDA @LOCAL01
	PHA
	TAX
	LDA a:char_struct::current_pp,X
	PLX
	CMP a:char_struct::current_pp_target,X
	BEQ @CHECK_FLIPOUT
	LDA #1
	LDX @LOCAL00
	STA __BSS_START__,X
@CHECK_FLIPOUT:
	LDA HPPP_METER_FLIPOUT_MODE
	BEQ @EXIT
	LDA @LOCAL01
	TAX
	LDY a:char_struct::current_hp,X
	CPY #999
	BNE @HP_NOT_AT_MAX
	TAX
	LDA #1
	STA a:char_struct::current_hp_target,X
	BRA @CHECK_PP_FLIPOUT
@HP_NOT_AT_MAX:
	CPY #1
	BNE @CHECK_PP_FLIPOUT
	TAX
	LDA #999
	STA a:char_struct::current_hp_target,X
@CHECK_PP_FLIPOUT:
	LDA @LOCAL01
	TAX
	LDY a:char_struct::current_pp,X
	CPY #999
	BNE @PP_NOT_AT_MAX
	TAX
	STZ a:char_struct::current_pp_target,X
	BRA @EXIT
@PP_NOT_AT_MAX:
	CPY #0
	BNE @EXIT
	TAX
	LDA #999
	STA a:char_struct::current_pp_target,X
@EXIT:
	END_C_FUNCTION
