
INFLICT_STATUS_NONBATTLE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	STY @VIRTUAL02
	PHA
	LDA @VIRTUAL02
	STA @LOCAL02
	PLA
	TXY
	STY @LOCAL01
	TAX
	STX @LOCAL00
	CPY #8
	BNE @NOT_PARTY_STATUS
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	DEC
	STA GAME_STATE + game_state::party_status
	REP #PROC_FLAGS::ACCUM8
	TXA
	BRA @RETURN
@NOT_PARTY_STATUS:
	TXA
	JSL CHECK_CHARACTER_IN_PARTY
	CMP #0
	BEQ @FAILURE
	LDY @LOCAL01
	TYA
	DEC
	STA @VIRTUAL02
	LDX @LOCAL00
	TXA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::afflictions
	CLC
	ADC @VIRTUAL02
	TAX
	LDA @LOCAL02
	STA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	DEC
	STA __BSS_START__,X
	JSL RENDER_AND_DISABLE_ENTITIES
	LDX @LOCAL00
	TXA
	BRA @RETURN
@FAILURE:
	.A16
	LDA #0
@RETURN:
	END_C_FUNCTION
