
INIT_TRANSITION_SCROLL_VELOCITY:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	STZ TRANSITION_X_VELOCITY_FRAC
	STZ TRANSITION_BACKGROUND_X_VELOCITY
	STZ TRANSITION_Y_VELOCITY_FRAC
	STZ TRANSITION_BACKGROUND_Y_VELOCITY
	TAY
	TXA
	CLC
	ADC #$0080
	AND #$00FF
	TAX
	PHX
	TYA
	JSL COSINE_SINE
	STA TRANSITION_X_VELOCITY_FRAC + 1
	LDA TRANSITION_X_VELOCITY_FRAC + 1
	BPL @X_POSITIVE
	LDA #$FF00
	ORA TRANSITION_BACKGROUND_X_VELOCITY
	STA TRANSITION_BACKGROUND_X_VELOCITY
@X_POSITIVE:
	PLX
	TYA
	JSL COSINE
	STA TRANSITION_Y_VELOCITY_FRAC + 1
	LDA TRANSITION_Y_VELOCITY_FRAC + 1
	BPL @Y_POSITIVE
	LDA #$FF00
	ORA TRANSITION_BACKGROUND_Y_VELOCITY
	STA TRANSITION_BACKGROUND_Y_VELOCITY
@Y_POSITIVE:
	LDA BG1_X_POS
	STA TRANSITION_BACKGROUND_X
	LDA BG1_Y_POS
	STA TRANSITION_BACKGROUND_Y
	STZ TRANSITION_X_POSITION_FRAC
	STZ TRANSITION_Y_POSITION_FRAC
	RTL
