
INIT_SWIRL_EFFECT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	@OPTIONS := @VIRTUAL02
	STX @OPTIONS
	STA @VIRTUAL04
	LDA @OPTIONS
	AND #$0002
	BEQ @NO_INVERT
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA SWIRL_INVERT_ENABLED
	BRA @CHECK_REVERSED
@NO_INVERT:
	SEP #PROC_FLAGS::ACCUM8
	STZ SWIRL_INVERT_ENABLED
@CHECK_REVERSED:
	REP #PROC_FLAGS::ACCUM8
	LDA @OPTIONS
	AND #$0001
	BEQ @NOT_REVERSED
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA SWIRL_REVERSED
	BRA @CHECK_MASK
@NOT_REVERSED:
	SEP #PROC_FLAGS::ACCUM8
	STZ SWIRL_REVERSED
@CHECK_MASK:
	REP #PROC_FLAGS::ACCUM8
	LDA @OPTIONS
	AND #$0004
	BEQ @STANDARD_MASK
	SEP #PROC_FLAGS::ACCUM8
	LDA #32
	STA SWIRL_MASK_SETTINGS
	BRA @LOAD_TABLE
@STANDARD_MASK:
	SEP #PROC_FLAGS::ACCUM8
	LDA #31
	STA SWIRL_MASK_SETTINGS
@LOAD_TABLE:
	LDA #1
	STA FRAMES_UNTIL_NEXT_SWIRL_UPDATE
	REP #PROC_FLAGS::ACCUM8
	LOADPTR SWIRL_PRIMARY_TABLE, @VIRTUAL06
	LDA @VIRTUAL04
	ASL
	ASL
	STA @LOCAL01
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL0A]
	STA FRAMES_UNTIL_NEXT_SWIRL_FRAME
	LDY #.LOWORD(SWIRL_FRAMES_LEFT)
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	INC
	INC
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL0A]
	STA __BSS_START__,Y
	LDX #.LOWORD(SWIRL_HDMA_TABLE_ID)
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	STA @LOCAL00
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA SWIRL_REVERSED
	AND #$00FF
	BEQ @AFTER_REVERSED_ADJUST
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,Y
	STA @VIRTUAL00
	LDA @LOCAL00
	CLC
	ADC @VIRTUAL00
	STA __BSS_START__,X
@AFTER_REVERSED_ADJUST:
	LDY #.LOWORD(LOADED_OVAL_WINDOW)
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDA @VIRTUAL04
	BNE @INIT_STATE
	LOADPTR OVAL_WINDOW_STANDARD_OPEN, @VIRTUAL06
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
@INIT_STATE:
	SEP #PROC_FLAGS::ACCUM8
	STZ SWIRL_HDMA_CHANNEL_OFFSET
	STZ SWIRL_LENGTH_PADDING
	LDA #1
	STA SWIRL_AUTO_RESTORE
	REP #PROC_FLAGS::ACCUM8
	LDA @OPTIONS
	AND #$0080
	BEQ @NO_REPEATING
	LDA @VIRTUAL04
	SEP #PROC_FLAGS::ACCUM8
	STA SWIRL_NEXT_SWIRL
	LDA #4
	STA FRAMES_UNTIL_NEXT_SWIRL_FRAME
	STZ SWIRL_REPEAT_SPEED
	LDA #8
	STA SWIRL_REPEATS_UNTIL_SPEED_UP
	BRA @DONE
@NO_REPEATING:
	SEP #PROC_FLAGS::ACCUM8
	STZ SWIRL_NEXT_SWIRL
@DONE:
	JSL DISABLE_WINDOWS
	END_C_FUNCTION
