
INITIALIZE_GAME_OVER_SCREEN:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
.IF .DEFINED(JPN)
	@TMP := @VIRTUAL0A
.ELSE
	@TMP := @VIRTUAL06
.ENDIF
	LDA PARTY_MEMBERS_ALIVE_OVERWORLD
	BNE @AFTER_MUSIC
	LDA #MUSIC::YOU_LOSE
	JSL CHANGE_MUSIC
	LDY #$0000
	LDX #$0001
	TXA
	JSL FADE_OUT_WITH_MOSAIC
@AFTER_MUSIC:
	STZ LOADED_ANIMATED_TILE_COUNT
	STZ MAP_PALETTE_ANIMATION_LOADED
	STZ ITEM_TRANSFORMATIONS_LOADED
	LDA #$0009
	JSL SET_BGMODE
	LDY #VRAM::GAME_OVER_LAYER_1_TILES
	LDX #VRAM::GAME_OVER_LAYER_1_TILEMAP
	TYA ;BG_TILEMAP_SIZE::NORMAL
	JSL SET_BG1_VRAM_LOCATION
	LDY #VRAM::GAME_OVER_LAYER_2_TILES
	LDX #VRAM::GAME_OVER_LAYER_2_TILEMAP
	LDA #BG_TILEMAP_SIZE::NORMAL
	JSL SET_BG3_VRAM_LOCATION
	LOADPTR BUFFER, $06
	LOADPTR GAME_OVER_GRAPHICS, @LOCAL00
	MOVE_INT $06, @LOCAL01
	JSL DECOMP
	LDA GAME_STATE + game_state::party_members
	AND #$00FF
	CMP #$0003
	BEQ @USE_GFX_OFFSET
	COPY_TO_VRAM1P $06, VRAM::GAME_OVER_LAYER_1_TILES, 32768, $00
	BRA @AFTER_GFX_LOAD
@USE_GFX_OFFSET:
	.A16
	COPY_TO_VRAM1 BUFFER + $8000, VRAM::GAME_OVER_LAYER_1_TILES, 32768, $00
@AFTER_GFX_LOAD:
	.A16
	LOADPTR BUFFER, $06
	LOADPTR GAME_OVER_ARRANGEMENT, @LOCAL00
	MOVE_INT $06, @LOCAL01
	JSL DECOMP
	COPY_TO_VRAM1P $06, VRAM::GAME_OVER_LAYER_1_TILEMAP, 2048, $00
	.A16
	PROMOTENEARPTR $0200, @TMP
	REP #PROC_FLAGS::ACCUM8
	LOADPTR GAME_OVER_PALETTE, @LOCAL00
	MOVE_INT @TMP, @LOCAL01
	JSL DECOMP
	LDY #$02E0
	STY @LOCAL02
	MOVE_INT @TMP, @LOCAL00
	LDX #$0020
	TYA
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	STZ_BADOPT @LOCAL00
	LDX #$00C0
	REP #PROC_FLAGS::ACCUM8
	LDA #$0220
	JSL MEMSET16
	LDY @LOCAL02
	TYA
	PROMOTENEARPTRA @TMP
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @TMP, @LOCAL00
	LDX #$0020
	LDA #$0240
	JSL MEMCPY16
	JSL INITIALIZE_BATTLE_UI_STATE
	JSL LOAD_WINDOW_GFX
.IF .DEFINED(JPN)
	COPY_TO_VRAM1P $06, VRAM::GAME_OVER_LAYER_2_TILES, $3800, $00
.ELSE
	LDA #$0001
	JSL UPLOAD_TEXT_TILES_TO_VRAM
.ENDIF
	JSL LOAD_CHARACTER_WINDOW_PALETTE
	LDA #$0018
	JSL SET_PALETTE_UPLOAD_MODE
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0005
	STA TM_MIRROR
	REP #PROC_FLAGS::ACCUM8
	STZ PARTY_MEMBERS_ALIVE_OVERWORLD
	STZ BG2_Y_POS
	STZ BG2_X_POS
	STZ BG1_X_POS
	STZ BG1_X_POS
	LDX #$0001
	TXA
	JSL FADE_IN
	JSL WAIT_FOR_FADE_COMPLETE
	END_C_FUNCTION
