
INIT_PATH_MATRIX_BORDERS:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	END_STACK_VARS
	LDX #0
	BRA @ROW_LOOP_CHECK
@SET_ROW_BORDERS:
	SEP #PROC_FLAGS::ACCUM8
	LDA #253
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA PATH_MATRIX_COLUMNS
	DEC
	STA @VIRTUAL02
	LDY PATH_MATRIX_COLUMNS
	TXA
	JSL MULT16
	CLC
	ADC @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDY PATH_MATRIX_COLUMNS
	TXA
	JSL MULT16
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	STA [@VIRTUAL06]
	INX
@ROW_LOOP_CHECK:
	CPX PATH_MATRIX_ROWS
	BCC @SET_ROW_BORDERS
	LDX #0
	BRA @COL_LOOP_CHECK
@SET_COL_BORDERS:
	SEP #PROC_FLAGS::ACCUM8
	LDA #253
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	STX @VIRTUAL02
	LDY PATH_MATRIX_COLUMNS
	LDA PATH_MATRIX_ROWS
	DEC
	JSL MULT16
	CLC
	ADC @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	TXA
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	STA [@VIRTUAL06]
	INX
@COL_LOOP_CHECK:
	CPX PATH_MATRIX_COLUMNS
	BCC @SET_COL_BORDERS
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
