
INIT_CHOSEN_FOUR_POINTERS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #0
	STA @LOCAL00
	BRA @LOOP_CHECK
@LOOP_BODY:
	ASL
	TAX
	LDA @LOCAL00
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	STA CHOSEN_FOUR_PTRS,X
	LDA @LOCAL00
	INC
	STA @LOCAL00
@LOOP_CHECK:
	CMP #6
	BCC @LOOP_BODY
	END_C_FUNCTION
