
IS_PLAYER_BUSY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA WINDOW_HEAD
	CMP #.LOWORD(-1)
	BEQ @CHECK_WINDOW_HEAD
@FADING:
	LDA #1
	BRA @RETURN
@CHECK_WINDOW_HEAD:
@CHECK_ENTITY_FADE:
	LDA ENTITY_FADE_ENTITY
	CMP #.LOWORD(-1)
	BEQ @CHECK_SUPPRESSION
	LDA #1
	BRA @RETURN
@CHECK_SUPPRESSION:
	LDA OVERWORLD_STATUS_SUPPRESSION
	BEQ @CHECK_SPRITEMAP
	LDA #1
	BRA @RETURN
@CHECK_SPRITEMAP:
	LDA GAME_STATE+game_state::current_party_members
	ASL
	TAX
	LDA ENTITY_SPRITEMAP_POINTER_HIGH,X
	AND #$8000
	BEQ @CHECK_TICK_FLAGS
	LDA #1
	BRA @RETURN
@CHECK_TICK_FLAGS:
	LDA ENTITY_TICK_CALLBACK_HIGH+46
	AND #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	BEQ @CHECK_PENDING
	LDA #0
	BRA @CHECK_WALKING_STYLE
@CHECK_PENDING:
	LDA PENDING_INTERACTIONS
@CHECK_WALKING_STYLE:
	LDX GAME_STATE + game_state::walking_style
	CPX #WALKING_STYLE::LADDER
	BEQ @SPECIAL_WALKING_STYLE
	CPX #WALKING_STYLE::ROPE
	BEQ @SPECIAL_WALKING_STYLE
	CPX #WALKING_STYLE::ESCALATOR
	BEQ @SPECIAL_WALKING_STYLE
	CPX #WALKING_STYLE::STAIRS
	BNE @RETURN
@SPECIAL_WALKING_STYLE:
	LDA #1
@RETURN:
	END_C_FUNCTION
