
LEVEL_UP_CHAR:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @LOCAL07
	TAX
	TXY
	DEY
	STY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL05
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::level
	STA @VIRTUAL02
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL04
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL04
	STA @LOCAL03
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL04
	INC
	LDX @VIRTUAL02
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	BEQ @CALC_OFFENSE
	LDA #1
	JSR ENABLE_BLINKING_TRIANGLE
	LDX #4
	LDA @LOCAL05
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	JSR SET_BATTLE_TARGET_NAME
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STORE_INT832 @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_CNUM
	DISPLAY_TEXT_PTR MSG_BTL_LEVEL_UP
	LDA #2
	JSR ENABLE_BLINKING_TRIANGLE
@CALC_OFFENSE:
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::base_offense
	STA @VIRTUAL02
	LDY @LOCAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 7
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:STATS_GROWTH_VARS,X
	STA @LOCAL00
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	STA @LOCAL00+1
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA @VIRTUAL04
	JSR CALCULATE_STAT_GAIN
	TAX
	STX @LOCAL05
	TXA
	CLC
	SBC #0
	BRANCHLTEQS @CALC_DEFENSE
	SEP #PROC_FLAGS::INDEX8
	STX @VIRTUAL00
	REP #PROC_FLAGS::INDEX8
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL00
	LDX @VIRTUAL02
	STA __BSS_START__,X
	LDY @LOCAL06
	REP #PROC_FLAGS::ACCUM8
	TYA
	INC
	JSL RECALC_CHARACTER_POSTMATH_OFFENSE
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	BEQ @CALC_DEFENSE
	LDX @LOCAL05
	TXA
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_CNUM
	DISPLAY_TEXT_PTR MSG_BTL_LV_OFFENSE_UP
@CALC_DEFENSE:
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::base_defense
	STA @VIRTUAL02
	LDY @LOCAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 7
	TAX
	INX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:STATS_GROWTH_VARS,X
	STA @LOCAL00
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	STA @LOCAL00+1
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA @VIRTUAL04
	JSR CALCULATE_STAT_GAIN
	TAX
	STX @LOCAL05
	TXA
	CLC
	SBC #0
	BRANCHLTEQS @CALC_SPEED
	SEP #PROC_FLAGS::INDEX8
	STX @VIRTUAL00
	REP #PROC_FLAGS::INDEX8
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL00
	LDX @VIRTUAL02
	STA __BSS_START__,X
	LDY @LOCAL06
	REP #PROC_FLAGS::ACCUM8
	TYA
	INC
	JSL RECALC_CHARACTER_POSTMATH_DEFENSE
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	BEQ @CALC_SPEED
	LDX @LOCAL05
	TXA
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_CNUM
	DISPLAY_TEXT_PTR MSG_BTL_LV_DEFENSE_UP
@CALC_SPEED:
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::base_speed
	STA @VIRTUAL02
	LDY @LOCAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 7
	TAX
	INX
	INX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:STATS_GROWTH_VARS,X
	STA @LOCAL00
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	STA @LOCAL00+1
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA @VIRTUAL04
	JSR CALCULATE_STAT_GAIN
	TAX
	STX @LOCAL05
	TXA
	CLC
	SBC #0
	BRANCHLTEQS @CALC_GUTS
	SEP #PROC_FLAGS::INDEX8
	STX @VIRTUAL00
	REP #PROC_FLAGS::INDEX8
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL00
	LDX @VIRTUAL02
	STA __BSS_START__,X
	LDY @LOCAL06
	REP #PROC_FLAGS::ACCUM8
	TYA
	INC
	JSL RECALC_CHARACTER_POSTMATH_SPEED
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	BEQ @CALC_GUTS
	LDX @LOCAL05
	TXA
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_CNUM
	DISPLAY_TEXT_PTR MSG_BTL_LV_SPEED_UP
@CALC_GUTS:
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::base_guts
	STA @VIRTUAL02
	LDY @LOCAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 7
	TAX
	INX
	INX
	INX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:STATS_GROWTH_VARS,X
	STA @LOCAL00
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	STA @LOCAL00+1
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA @VIRTUAL04
	JSR CALCULATE_STAT_GAIN
	TAX
	STX @LOCAL05
	TXA
	CLC
	SBC #0
	BRANCHLTEQS @CALC_VITALITY
	SEP #PROC_FLAGS::INDEX8
	STX @VIRTUAL00
	REP #PROC_FLAGS::INDEX8
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL00
	LDX @VIRTUAL02
	STA __BSS_START__,X
	LDY @LOCAL06
	REP #PROC_FLAGS::ACCUM8
	TYA
	INC
	JSL RECALC_CHARACTER_POSTMATH_GUTS
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	BEQ @CALC_VITALITY
	LDX @LOCAL05
	TXA
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_CNUM
	DISPLAY_TEXT_PTR MSG_BTL_LV_GUTS_UP
@CALC_VITALITY:
	LDA #10
	CLC
	SBC @VIRTUAL04
	BRANCHLTEQS @VITALITY_HIGH_LEVEL
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::base_vitality,X
	AND #$00FF
	DEC
	DEC
	OPTIMIZED_MULT @VIRTUAL04, 10
	STA @VIRTUAL02
	LDY @LOCAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 7
	TAX
	INX
	INX
	INX
	INX
	LDA f:STATS_GROWTH_VARS,X
	AND #$00FF
	TAY
	LDA @LOCAL03
	STA @VIRTUAL04
	JSL MULT16
	SEC
	SBC @VIRTUAL02
	LDY #10
	JSL DIVISION16
	BRA @APPLY_VITALITY
@VITALITY_HIGH_LEVEL:
	LDY @LOCAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 7
	TAX
	INX
	INX
	INX
	INX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:STATS_GROWTH_VARS,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA PARTY_CHARACTERS+char_struct::base_vitality,X
	STA @LOCAL00+1
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA @VIRTUAL04
	JSR CALCULATE_STAT_GAIN
@APPLY_VITALITY:
	STA @VIRTUAL02
	CLC
	SBC #0
	BRANCHLTEQS @CALC_IQ
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::base_vitality
	TAX
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL00
	STA __BSS_START__,X
	LDY @LOCAL06
	REP #PROC_FLAGS::ACCUM8
	TYA
	INC
	JSL RECALC_CHARACTER_POSTMATH_VITALITY
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	BEQ @CALC_IQ
	MOVE_INT1632S @VIRTUAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_CNUM
	DISPLAY_TEXT_PTR MSG_BTL_LV_VITA_UP
@CALC_IQ:
	LDA #10
	CLC
	SBC @VIRTUAL04
	BRANCHLTEQS @IQ_HIGH_LEVEL
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::base_iq,X
	AND #$00FF
	DEC
	DEC
	OPTIMIZED_MULT @VIRTUAL04, 10
	STA @VIRTUAL02
	LDY @LOCAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 7
	CLC
	ADC #5
	TAX
	LDA f:STATS_GROWTH_VARS,X
	AND #$00FF
	TAY
	LDA @LOCAL03
	STA @VIRTUAL04
	JSL MULT16
	SEC
	SBC @VIRTUAL02
	LDY #10
	JSL DIVISION16
	BRA @APPLY_IQ
@IQ_HIGH_LEVEL:
	LDY @LOCAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 7
	CLC
	ADC #5
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:STATS_GROWTH_VARS,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA PARTY_CHARACTERS+char_struct::base_iq,X
	STA @LOCAL00+1
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA @VIRTUAL04
	JSR CALCULATE_STAT_GAIN
@APPLY_IQ:
	STA @VIRTUAL02
	CLC
	SBC #0
	BRANCHLTEQS @CALC_LUCK
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::base_iq
	TAX
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL00
	STA __BSS_START__,X
	LDY @LOCAL06
	REP #PROC_FLAGS::ACCUM8
	TYA
	INC
	JSL RECALC_CHARACTER_POSTMATH_IQ
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	BEQ @CALC_LUCK
	MOVE_INT1632S @VIRTUAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_CNUM
	DISPLAY_TEXT_PTR MSG_BTL_LV_IQ_UP
@CALC_LUCK:
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::base_luck
	STA @VIRTUAL02
	LDY @LOCAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 7
	CLC
	ADC #6
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:STATS_GROWTH_VARS,X
	STA @LOCAL00
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	STA @LOCAL00+1
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA @VIRTUAL04
	JSR CALCULATE_STAT_GAIN
	TAX
	STX @LOCAL05
	TXA
	CLC
	SBC #0
	BRANCHLTEQS @CALC_MAX_HP
	SEP #PROC_FLAGS::INDEX8
	STX @VIRTUAL00
	REP #PROC_FLAGS::INDEX8
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL00
	LDX @VIRTUAL02
	STA __BSS_START__,X
	LDY @LOCAL06
	REP #PROC_FLAGS::ACCUM8
	TYA
	INC
	JSL RECALC_CHARACTER_POSTMATH_LUCK
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	BEQ @CALC_MAX_HP
	LDX @LOCAL05
	TXA
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_CNUM
	DISPLAY_TEXT_PTR MSG_BTL_LV_LUCK_UP
@CALC_MAX_HP:
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::vitality,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, 15
	SEC
	SBC PARTY_CHARACTERS+char_struct::max_hp,X
	STA @LOCAL02
	CLC
	SBC #1
	BRANCHLTEQS @HP_RANDOM_FLOOR
	LDA @LOCAL02
	TAX
	BRA @APPLY_MAX_HP
@HP_RANDOM_FLOOR:
	LDA #2
	JSL RAND_MOD
	TAX
	INX
@APPLY_MAX_HP:
	STX @VIRTUAL02
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::max_hp
	TAX
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL02
	STA __BSS_START__,X
	LDA @LOCAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::current_hp_target
	TAX
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL02
	STA __BSS_START__,X
	LDA @LOCAL07
	BEQ @CALC_MAX_PP
	MOVE_INT1632S @VIRTUAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_CNUM
	DISPLAY_TEXT_PTR MSG_BTL_LV_MAXHP_UP
@CALC_MAX_PP:
	LDY @LOCAL06
	CPY #2
	BEQL @FINISH
	CPY #0
	BNE @PP_NORMAL_IQ
	LDA #EVENT_FLAG::FLG_WIN_OSCAR
	JSL GET_EVENT_FLAG
	CMP #0
	BEQ @PP_NORMAL_IQ
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::iq,X
	AND #$00FF
	ASL
	BRA @PP_CALC_POTENTIAL
@PP_NORMAL_IQ:
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::iq,X
	AND #$00FF
@PP_CALC_POTENTIAL:
	STA @LOCAL01
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA @LOCAL01
	OPTIMIZED_MULT @VIRTUAL04, 5
	SEC
	SBC PARTY_CHARACTERS+char_struct::max_pp,X
	STA @LOCAL02
	CLC
	SBC #1
	BRANCHLTEQS @PP_RANDOM_FLOOR
	LDA @LOCAL02
	TAX
	BRA @PP_APPLY
@PP_RANDOM_FLOOR:
	LDA #2
	JSL RAND_MOD
	TAX
@PP_APPLY:
	TXA
	STA @LOCAL01
	BEQ @CHECK_PSI_LEARNING
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @VIRTUAL02
	STA @LOCAL02
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::max_pp
	TAX
	LDA @LOCAL01
	STA @VIRTUAL02
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL02
	STA __BSS_START__,X
	LDA @LOCAL02
	STA @VIRTUAL02
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::current_pp_target
	TAX
	LDA @LOCAL01
	STA @VIRTUAL02
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL02
	STA __BSS_START__,X
	LDA @LOCAL07
	BEQ @CHECK_PSI_LEARNING
	MOVE_INT1632S @LOCAL01, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_CNUM
	DISPLAY_TEXT_PTR MSG_BTL_LV_MAXPP_UP
@CHECK_PSI_LEARNING:
	LDA @LOCAL07
	BEQL @FINISH
	LDA @LOCAL03
	STA @VIRTUAL04
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDY @LOCAL06
	TYA
	BEQ @PSI_CHECK_NESS
	CMP #1
	BEQ @PSI_CHECK_PAULA
	CMP #3
	BEQL @PSI_CHECK_POO
	JMP @FINISH
@PSI_CHECK_NESS:
	LDX #1
	STX @LOCAL06
	BRA @PSI_NESS_LOOP_HEAD
@PSI_NESS_LOOP_BODY:
	LDA @LOCAL03
	CLC
	ADC #6
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	CMP @VIRTUAL02
	BNE @PSI_NESS_NEXT
	TXA
	SEP #PROC_FLAGS::ACCUM8
	JSR SET_CURRENT_ITEM
	.A16
	DISPLAY_TEXT_PTR MSG_BTL_LEARN_PSI
@PSI_NESS_NEXT:
	.A8
	LDX @LOCAL06
	INX
	STX @LOCAL06
@PSI_NESS_LOOP_HEAD:
	.A16
	LOADPTR PSI_ABILITY_TABLE, @VIRTUAL06
	TXA
	OPTIMIZED_MULT @VIRTUAL04, 15
	STA @LOCAL03
	MOVE_INTY @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	BNE @PSI_NESS_LOOP_BODY
	JMP @FINISH
@PSI_CHECK_PAULA:
	LDX #1
	STX @LOCAL06
	BRA @PSI_PAULA_LOOP_HEAD
@PSI_PAULA_LOOP_BODY:
	.A16
	LDA @LOCAL03
	CLC
	ADC #7
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	CMP @VIRTUAL02
	BNE @PSI_PAULA_NEXT
	TXA
	SEP #PROC_FLAGS::ACCUM8
	JSR SET_CURRENT_ITEM
	.A16
	DISPLAY_TEXT_PTR MSG_BTL_LEARN_PSI
@PSI_PAULA_NEXT:
	.A8
	LDX @LOCAL06
	INX
	STX @LOCAL06
@PSI_PAULA_LOOP_HEAD:
	.A16
	LOADPTR PSI_ABILITY_TABLE, @VIRTUAL06
	TXA
	OPTIMIZED_MULT @VIRTUAL04, 15
	STA @LOCAL03
	MOVE_INTY @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	BNE @PSI_PAULA_LOOP_BODY
	BRA @FINISH
@PSI_CHECK_POO:
	LDX #1
	STX @LOCAL06
	BRA @PSI_POO_LOOP_HEAD
@PSI_POO_LOOP_BODY:
	.A16
	LDA @LOCAL03
	CLC
	ADC #8
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	CMP @VIRTUAL02
	BNE @PSI_POO_NEXT
	TXA
	SEP #PROC_FLAGS::ACCUM8
	JSR SET_CURRENT_ITEM
	.A16
	DISPLAY_TEXT_PTR MSG_BTL_LEARN_PSI
@PSI_POO_NEXT:
	.A8
	LDX @LOCAL06
	INX
	STX @LOCAL06
@PSI_POO_LOOP_HEAD:
	.A16
	LOADPTR PSI_ABILITY_TABLE, @VIRTUAL06
	TXA
	OPTIMIZED_MULT @VIRTUAL04, 15
	STA @LOCAL03
	MOVE_INTY @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	BNE @PSI_POO_LOOP_BODY
@FINISH:
	LDA @LOCAL07
	BEQ @RETURN
	JSR CLEAR_BLINKING_PROMPT
@RETURN:
	END_C_FUNCTION
