
LOAD_CHARACTER_PORTRAIT_SCREEN:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	END_STACK_VARS
	LDA #0
	JSL RENDER_CHARACTER_NAME_DISPLAY
	TAY
	LOADPTR BUFFER + $4000, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL07
	LDX #0
	BRA @CLEAR_TILE_BUFFER_CHECK
@CLEAR_TILE_BUFFER_ROW:
	LDA #0
	STA @LOCAL06
	BRA @CLEAR_TILE_WORD_CHECK
@CLEAR_TILE_WORD:
	LDA #0
	STA [@VIRTUAL06]
	INC @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL07
	LDA @LOCAL06
	INC
	STA @LOCAL06
@CLEAR_TILE_WORD_CHECK:
	CMP #8
	BCC @CLEAR_TILE_WORD
	INX
@CLEAR_TILE_BUFFER_CHECK:
	CPX #29
	BCC @CLEAR_TILE_BUFFER_ROW
	TYA
	CLC
	ADC #30
	STA @VIRTUAL04
	LDX #0
	STX @LOCAL05
	TXA
	STA @VIRTUAL02
	STA @LOCAL04
	BRA @DECODE_PORTRAIT_HEADER_CHECK
@DECODE_PORTRAIT_HEADER:
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @VIRTUAL02
	JSL DECODE_PLANAR_TILEMAP
	MOVE_INT @VIRTUAL06, @LOCAL07
	LDX @LOCAL05
	INX
	STX @LOCAL05
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL04
@DECODE_PORTRAIT_HEADER_CHECK:
	CPX #4
	BCC @DECODE_PORTRAIT_HEADER
	PROMOTENEARPTR PARTY_CHARACTERS + char_struct::name, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL STRLEN
	TAY
	STY @LOCAL03
	CPY #6
	BNE @NAME_LENGTH_OK
	DEY
	STY @LOCAL03
@NAME_LENGTH_OK:
	LDX #0
	STX @LOCAL05
	BRA @DECODE_NAME_TILES_CHECK
@DECODE_NAME_TILE:
	MOVE_INT @LOCAL07, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @LOCAL04
	STA @VIRTUAL02
	JSL DECODE_PLANAR_TILEMAP
	MOVE_INT @VIRTUAL06, @LOCAL07
	LDX @LOCAL05
	INX
	STX @LOCAL05
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL04
@DECODE_NAME_TILES_CHECK:
	LDY @LOCAL03
	STY @VIRTUAL02
	TXA
	CMP @VIRTUAL02
	BCC @DECODE_NAME_TILE
	LDX #0
	STX @LOCAL05
	BRA @DECODE_STATS_TILES_CHECK
@DECODE_STATS_TILE:
	MOVE_INT @LOCAL07, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @LOCAL04
	STA @VIRTUAL02
	JSL DECODE_PLANAR_TILEMAP
	MOVE_INT @VIRTUAL06, @LOCAL07
	LDX @LOCAL05
	INX
	STX @LOCAL05
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL04
@DECODE_STATS_TILES_CHECK:
	CPX #6
	BCC @DECODE_STATS_TILE
	LDX #0
	STX @LOCAL05
	BRA @DECODE_PORTRAIT_BODY_CHECK
@DECODE_PORTRAIT_BODY:
	MOVE_INT @LOCAL07, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @LOCAL04
	STA @VIRTUAL02
	JSL DECODE_PLANAR_TILEMAP
	MOVE_INT @VIRTUAL06, @LOCAL07
	LDX @LOCAL05
	INX
	STX @LOCAL05
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL04
@DECODE_PORTRAIT_BODY_CHECK:
	CPX #205
	BCC @DECODE_PORTRAIT_BODY
	LDX #0
	BRA @CLEAR_TRAILING_BUFFER_CHECK
@CLEAR_TRAILING_ROW:
	LDA #0
	STA @LOCAL06
	BRA @CLEAR_TRAILING_WORD_CHECK
@CLEAR_TRAILING_WORD:
	LDA #0
	MOVE_INTY @LOCAL07, @VIRTUAL06
	STA [@VIRTUAL06]
	INC @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL07
	LDA @LOCAL06
	INC
	STA @LOCAL06
@CLEAR_TRAILING_WORD_CHECK:
	CMP #8
	BCC @CLEAR_TRAILING_WORD
	INX
@CLEAR_TRAILING_BUFFER_CHECK:
	CPX #30
	BCC @CLEAR_TRAILING_ROW
	LOADPTR BUFFER + $1000, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	LOADPTR BUFFER + $4000, @VIRTUAL0A
	LDA #0
	STA @LOCAL06
	BRA @INIT_TILEMAP_ROW_CHECK
@INIT_TILEMAP_ENTRY:
	LDA #$0C10
	STA [@VIRTUAL06]
	INC @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	LDA @LOCAL06
	INC
	STA @LOCAL06
@INIT_TILEMAP_ROW_CHECK:
	CMP #8
	BCC @INIT_TILEMAP_ENTRY
	LDA #0
	STA @LOCAL04
	BRA @INTERLEAVE_ROW_CHECK
@INTERLEAVE_ROW:
	LDX #0
	BRA @INTERLEAVE_COL_CHECK
@INTERLEAVE_COLUMN:
	LDY #16
	LDA [@VIRTUAL0A],Y
	LSR
	AND #$0005
	STA @VIRTUAL02
	LDA [@VIRTUAL0A]
	ASL
	AND #$000A
	ORA @VIRTUAL02
	TAY
	STA [@VIRTUAL06]
	MOVE_INT @VIRTUAL06, @LOCAL01
	TYA
	CLC
	ADC #$0C10
	STA [@LOCAL01]
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDA [@LOCAL01]
	CLC
	ADC #$0C10
	STA [@LOCAL01]
	MOVE_INT @LOCAL02, @VIRTUAL06
	INC @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	INC @VIRTUAL0A
	INC @VIRTUAL0A
	INX
@INTERLEAVE_COL_CHECK:
	CPX #8
	BCC @INTERLEAVE_COLUMN
	LDA @LOCAL04
	INC
	STA @LOCAL04
@INTERLEAVE_ROW_CHECK:
	LDA @VIRTUAL04
	CLC
	ADC #30
	STA @VIRTUAL02
	LDA @LOCAL04
	CMP @VIRTUAL02
	BCC @INTERLEAVE_ROW
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA @VIRTUAL04
	ASL
	STA ENTITY_SCRIPT_VAR0_TABLE,X
	SEP #PROC_FLAGS::ACCUM8
	LDA #8
	STA BUFFER
	LDA #30
	STA BUFFER+1
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
