
LOAD_CHARACTER_PORTRAIT_SCREEN:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDY #0
	STY @LOCAL07
	LOADPTR TEXT_WINDOW_GFX, @LOCAL00
	LOADPTR BUFFER, @LOCAL01
	JSL DECOMP
	LOADPTR BUFFER + $4000, @VIRTUAL0A
	LDX #0
	BRA @CLEAR_ROW_LOOP_CHECK
@CLEAR_ROW:
	LDA #0
	STA @LOCAL06
	BRA @CLEAR_WORD_LOOP_CHECK
@CLEAR_WORD:
	LDA #0
	STA [@VIRTUAL0A]
	INC @VIRTUAL0A
	INC @VIRTUAL0A
	LDA @LOCAL06
	INC
	STA @LOCAL06
@CLEAR_WORD_LOOP_CHECK:
	CMP #8
	BCC @CLEAR_WORD
	INX
@CLEAR_ROW_LOOP_CHECK:
	CPX #29
	BCC @CLEAR_ROW
	LDY @LOCAL07
	TYA
	CLC
	ADC #30
	TAY
	STY @LOCAL07
	LDX #0
	STX @LOCAL05
	BRA @HEADER_CHAR_LOOP_CHECK
@DECODE_HEADER_CHAR:
	MOVE_INT @VIRTUAL0A, @LOCAL00
	LDA f:LUMINE_HALL_TEXT,X
	AND #$00FF
	JSL DECODE_PLANAR_TILEMAP
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	LDY @LOCAL07
	INY
	INY
	INY
	INY
	STY @LOCAL07
	LDX @LOCAL05
	INX
	STX @LOCAL05
@HEADER_CHAR_LOOP_CHECK:
	CPX #3
	BCC @DECODE_HEADER_CHAR
	LDX #4
	STX @LOCAL05
	PROMOTENEARPTR PARTY_CHARACTERS + char_struct::name, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL04
	BRA @NAME_CHAR_LOOP_CHECK
@DECODE_NAME_CHAR:
	DEX
	STX @LOCAL05
	AND #$00FF
	STA @LOCAL03
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL04
	MOVE_INT @VIRTUAL0A, @LOCAL00
	LDA @LOCAL03
	JSL DECODE_PLANAR_TILEMAP
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	LDY @LOCAL07
	INY
	INY
	INY
	INY
	STY @LOCAL07
@NAME_CHAR_LOOP_CHECK:
	MOVE_INT @LOCAL04, @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	BEQ @AFTER_NAME
	LDX @LOCAL05
	BNE @DECODE_NAME_CHAR
@AFTER_NAME:
	LDX #0
	STX @LOCAL05
	BRA @SUBTITLE_LOOP_CHECK
@DECODE_SUBTITLE_CHAR:
	MOVE_INT @VIRTUAL0A, @LOCAL00
	LDA f:LUMINE_HALL_TEXT+3,X
	AND #$00FF
	JSL DECODE_PLANAR_TILEMAP
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	LDY @LOCAL07
	INY
	INY
	INY
	INY
	STY @LOCAL07
	LDX @LOCAL05
	INX
	STX @LOCAL05
@SUBTITLE_LOOP_CHECK:
	CPX #97
	BCC @DECODE_SUBTITLE_CHAR
	LDX #0
	BRA @TRAILING_BLANK_LOOP_CHECK
@TRAILING_BLANK_SECTION:
@CLEAR_TRAILING_TILES:
@CLEAR_TRAILING_TILE:
	LDA #0
	STA @LOCAL06
	BRA @TRAILING_BLANK_WORD_CHECK
@WRITE_TRAILING_BLANK:
	LDA #0
	STA [@VIRTUAL0A]
	INC @VIRTUAL0A
	INC @VIRTUAL0A
	LDA @LOCAL06
	INC
	STA @LOCAL06
@TRAILING_BLANK_WORD_CHECK:
	CMP #8
	BCC @WRITE_TRAILING_BLANK
	INX
@TRAILING_BLANK_LOOP_CHECK:
	CPX #30
	BCC @CLEAR_TRAILING_TILE
	LOADPTR BUFFER + $2000, @VIRTUAL0A
	LOADPTR BUFFER + $4000, @LOCAL02
	LDA #0
	STA @LOCAL06
	BRA @HEADER_LOOP_CHECK
@WRITE_HEADER_TILE:
	LDA #$0C10
	STA [@VIRTUAL0A]
	INC @VIRTUAL0A
	INC @VIRTUAL0A
	LDA @LOCAL06
	INC
	STA @LOCAL06
@HEADER_LOOP_CHECK:
	CMP #8
	BCC @WRITE_HEADER_TILE
	LDA #0
	STA @LOCAL06
	BRA @TILE_ROW_LOOP_CHECK
@PROCESS_TILE_ROW:
	LDX #0
	BRA @PIXEL_COL_LOOP_CHECK
@DECODE_PIXEL:
	LDY #16
	LDA [@LOCAL02],Y
	LSR
	AND #$0005
	STA @VIRTUAL04
	LDA [@LOCAL02]
	ASL
	AND #$000A
	ORA @VIRTUAL04
	STA @VIRTUAL02
	STA [@VIRTUAL0A]
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	LDA @VIRTUAL02
	CLC
	ADC #$0C10
	STA [@VIRTUAL06]
	MOVE_INT @LOCAL02, @VIRTUAL06
	LDA [@VIRTUAL06]
	CLC
	ADC #$0C10
	STA [@VIRTUAL06]
	INC @VIRTUAL0A
	INC @VIRTUAL0A
	MOVE_INT @LOCAL02, @VIRTUAL06
	INC @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	INX
@PIXEL_COL_LOOP_CHECK:
	CPX #8
	BCC @DECODE_PIXEL
	LDA @LOCAL06
	INC
	STA @LOCAL06
@TILE_ROW_LOOP_CHECK:
	LDY @LOCAL07
	TYA
	CLC
	ADC #30
	STA @VIRTUAL02
	LDA @LOCAL06
	CMP @VIRTUAL02
	BCC @PROCESS_TILE_ROW
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	TYA
	ASL
	STA ENTITY_SCRIPT_VAR0_TABLE,X
	SEP #PROC_FLAGS::ACCUM8
	LDA #8
	STA BUFFER
	LDA #30
	STA BUFFER+1
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
