
REMOVE_CHAR_FROM_PARTY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int character
	END_STACK_VARS
	TAY
	STY @LOCAL00
	LDX #0
	BRA @SEARCH_LOOP_CHECK
@CHECK_MEMBER:
	STY @VIRTUAL02
	LDA GAME_STATE + game_state::party_members,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @NEXT_MEMBER
	BRA @SHIFT_LOOP_CHECK
@SHIFT_MEMBER:
	SEP #PROC_FLAGS::ACCUM8
	LDA GAME_STATE + game_state::party_members + 1,X
	STA GAME_STATE + game_state::party_members,X
	INX
@SHIFT_LOOP_CHECK:
	STX @VIRTUAL02
	REP #PROC_FLAGS::ACCUM8
	LDA #6
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @SHIFT_MEMBER
	DEX
	SEP #PROC_FLAGS::ACCUM8
	STZ GAME_STATE + game_state::party_members,X
	REP #PROC_FLAGS::ACCUM8
	TYA
	JSL REMOVE_PARTY_MEMBER
	LDY @LOCAL00
	CPY #4
	BGT @RETURN
	JSL UPDATE_TEDDY_BEAR_PARTY
	JSL INIT_ALL_ITEM_TRANSFORMATIONS
	BRA @RETURN
@NEXT_MEMBER:
	INX
@SEARCH_LOOP_CHECK:
	STX @VIRTUAL02
	LDA GAME_STATE+game_state::party_count
	AND #$00FF
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @CHECK_MEMBER
@RETURN:
	END_C_FUNCTION
