
ADD_CHAR_TO_PARTY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int character
	END_STACK_VARS
	TAY
	STY @LOCAL02
	LDA #0
	STA @VIRTUAL02
	JMP @SEARCH_LOOP_CHECK
@CHECK_SLOT:
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA a:game_state::party_members,X
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	AND #$00FF
	STY @VIRTUAL04
	CMP @VIRTUAL04
	BEQL @RETURN
	STY @VIRTUAL04
	CMP @VIRTUAL04
	BGT @FOUND_INSERT_POINT
	LDA @VIRTUAL00
	AND #$00FF
	BNEL @NEXT_SLOT
@FOUND_INSERT_POINT:
	LDX @VIRTUAL02
	STX @LOCAL01
	BRA @FIND_END_LOOP_CHECK
@FIND_END:
	LDX @LOCAL01
	STX @VIRTUAL04
	LDA #6
	CLC
	SBC @VIRTUAL04
	JUMPLTEQS @RETURN
	INX
	STX @LOCAL01
@FIND_END_LOOP_CHECK:
	TXA
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
	AND #$00FF
	BNE @FIND_END
	BRA @SHIFT_LOOP_CHECK
@SHIFT_UP:
	TXA
	DEC
	STA @LOCAL00
	TXA
	CLC
	ADC #.LOWORD(GAME_STATE)
	PHA
	LDA @LOCAL00
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA a:game_state::party_members,X
	PLX
	STA a:game_state::party_members,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	TAX
	STX @LOCAL01
@SHIFT_LOOP_CHECK:
	LDX @LOCAL01
	TXA
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @SHIFT_UP
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA a:game_state::party_members,X
	REP #PROC_FLAGS::ACCUM8
	TYA
	JSL ADD_PARTY_MEMBER
	ASL
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA __BSS_START__,X
	LDY @LOCAL02
	CPY #4
	BGT @RETURN
	JSL UPDATE_TEDDY_BEAR_PARTY
	JSL INIT_ALL_ITEM_TRANSFORMATIONS
	BRA @RETURN
@NEXT_SLOT:
	INC @VIRTUAL02
@SEARCH_LOOP_CHECK:
	LDA #6
	CLC
	SBC @VIRTUAL02
	JUMPGTS @CHECK_SLOT
@RETURN:
	END_C_FUNCTION
