
ADD_CHAR_TO_PARTY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int character
	END_STACK_VARS
	STA @VIRTUAL04
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL00
	JMP @SCAN_LOOP_HEAD
@CHECK_SLOT:
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA GAME_STATE + game_state::party_members,X
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	AND #$00FF
	CMP @VIRTUAL04
	BEQL @RETURN
	CMP @VIRTUAL04
	BGT @FOUND_INSERT_POINT
	LDA @VIRTUAL00
	AND #$00FF
	BNE @ADVANCE_INSERT_POS
@FOUND_INSERT_POINT:
	LDY @VIRTUAL02
	BRA @FIND_EMPTY_SLOT
@CHECK_SLOT_EMPTY:
	STY @VIRTUAL02
	LDA #6
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @RETURN
	INY
@FIND_EMPTY_SLOT:
	LDA GAME_STATE + game_state::party_members,Y
	AND #$00FF
	BNE @CHECK_SLOT_EMPTY
	BRA @SHIFT_LOOP_HEAD
@SHIFT_MEMBER_DOWN:
	TYX
	DEX
	SEP #PROC_FLAGS::ACCUM8
	LDA GAME_STATE + game_state::party_members,X
	STA GAME_STATE + game_state::party_members,Y
	TXY
@SHIFT_LOOP_HEAD:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	STA @VIRTUAL02
	TYA
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @SHIFT_MEMBER_DOWN
	LDA @VIRTUAL04
	SEP #PROC_FLAGS::ACCUM8
	LDX @VIRTUAL02
	STA GAME_STATE + game_state::party_members,X
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	JSL ADD_PARTY_MEMBER
	ASL
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA __BSS_START__,X
	LDA @VIRTUAL04
	CMP #4
	BGT @RETURN
	JSL UPDATE_TEDDY_BEAR_PARTY
	JSL INIT_ALL_ITEM_TRANSFORMATIONS
	BRA @RETURN
@ADVANCE_INSERT_POS:
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL00
@SCAN_LOOP_HEAD:
	LDA #6
	CLC
	SBC @VIRTUAL02
	JUMPGTS @CHECK_SLOT
@RETURN:
	END_C_FUNCTION
