
REMOVE_CHAR_FROM_PARTY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int character
	END_STACK_VARS
	TAX
	STX @LOCAL01
	LDA #0
	STA @LOCAL00
	BRA @SEARCH_LOOP_CHECK
@CHECK_MEMBER:
	LDX @LOCAL01
	STX @VIRTUAL02
	LDA @LOCAL00
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @NEXT_MEMBER
	BRA @SHIFT_LOOP_CHECK
@SHIFT_DOWN:
	LDA @LOCAL00
	CLC
	ADC #.LOWORD(GAME_STATE)
	PHA
	LDA @LOCAL00
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA GAME_STATE + game_state::party_members + 1,X
	PLX
	STA a:game_state::party_members,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	INC
	STA @LOCAL00
@SHIFT_LOOP_CHECK:
	LDA @LOCAL00
	STA @VIRTUAL02
	LDA #6
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @SHIFT_DOWN
	LDA @LOCAL00
	DEC
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ a:game_state::party_members,X
	LDX @LOCAL01
	REP #PROC_FLAGS::ACCUM8
	TXA
	JSL REMOVE_PARTY_MEMBER
	LDX @LOCAL01
	CPX #4
	BGT @RETURN
	JSL UPDATE_TEDDY_BEAR_PARTY
	JSL INIT_ALL_ITEM_TRANSFORMATIONS
	BRA @RETURN
@NEXT_MEMBER:
	LDA @LOCAL00
	INC
	STA @LOCAL00
@SEARCH_LOOP_CHECK:
	STA @VIRTUAL02
	LDA GAME_STATE+game_state::party_count
	AND #$00FF
	CLC
	SBC @VIRTUAL02
	JUMPGTS @CHECK_MEMBER
@RETURN:
	END_C_FUNCTION
