
PLAY_COMEBACK_SEQUENCE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	LDA #60
	JSR SKIPPABLE_PAUSE
	DISPLAY_TEXT_PTR MSG_SYS_COMEBACK
	JSL CLOSE_ALL_WINDOWS_AND_HIDE_HPPP
	LDA EVENT_FLAG_NOCONTINUE_SELECTED
	JSL GET_EVENT_FLAG
	CMP #0
	BNE @NO_CONTINUE
	LDA #60
	JSR SKIPPABLE_PAUSE
	LDA #.LOWORD(-1)
	JMP @RETURN
@NO_CONTINUE:
	LDA #60
	JSR SKIPPABLE_PAUSE
	CMP #0
	BEQ @FADE_PHASE_1
	LDA #0
	JMP @RETURN
@FADE_PHASE_1:
	LDX #90
	LDA #1
	JSR ANIMATE_MAP_PALETTE_CHANGE
	CMP #0
	BEQ @PAUSE_AFTER_PHASE_1
	LDA #0
	BRA @RETURN
@PAUSE_AFTER_PHASE_1:
	LDA #1
	JSR SKIPPABLE_PAUSE
	CMP #0
	BEQ @FADE_PHASE_2
	LDA #0
	BRA @RETURN
@FADE_PHASE_2:
	LDX #90
	LDA #2
	JSR ANIMATE_MAP_PALETTE_CHANGE
	CMP #0
	BEQ @PAUSE_AFTER_PHASE_2
	LDA #0
	BRA @RETURN
@PAUSE_AFTER_PHASE_2:
	LDA #1
	JSR SKIPPABLE_PAUSE
	CMP #0
	BEQ @FADE_PHASE_3
	LDA #0
	BRA @RETURN
@FADE_PHASE_3:
	LDX #90
	LDA #3
	JSR ANIMATE_MAP_PALETTE_CHANGE
	CMP #0
	BEQ @PAUSE_AFTER_PHASE_3
	LDA #0
	BRA @RETURN
@PAUSE_AFTER_PHASE_3:
	LDA #1
	JSR SKIPPABLE_PAUSE
	CMP #0
	BEQ @FADE_PHASE_4
	LDA #0
	BRA @RETURN
@FADE_PHASE_4:
	LDX #8
	LDA #4
	JSR ANIMATE_MAP_PALETTE_CHANGE
	CMP #0
	BEQ @FADE_COMPLETE
	LDA #0
	BRA @RETURN
@FADE_COMPLETE:
	LDA #0
@RETURN:
	END_C_FUNCTION
