
; parses flyover script
; void PLAY_FLYOVER_SCRIPT(short id)
PLAY_FLYOVER_SCRIPT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL00
	LDX #.LOWORD(ENTITY_TICK_CALLBACK_HIGH) + (23 * 2)
	LDA __BSS_START__,X
	STA @VIRTUAL02
	ORA #$C000
	STA __BSS_START__,X
	JSL INIT_FLYOVER_TEXT_SCREEN
	LOADPTR FLYOVER_TEXT_POINTERS, @VIRTUAL0A
	LDA @LOCAL00
	ASL
	ASL
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
@SCRIPT_PARSE_BEGIN:
	LDA [@VIRTUAL06]
	AND #$00FF
	STA @LOCAL00
	INC @VIRTUAL06
	CMP #$00
	BEQ @END_OF_SCRIPT
	CMP #$02
	BEQ @PARSE_02
	CMP #$09
	BEQ @PARSE_09
	CMP #$01
	BEQ @PARSE_01
	CMP #$08
	BEQ @PARSE_08
	BRA @PRINT_TEXT
@PARSE_02:
	LDA [@VIRTUAL06]
	AND #$00FF
	STA FLYOVER_SCREEN_OFFSET
	INC @VIRTUAL06
	BRA @SCRIPT_PARSE_BEGIN
@PARSE_09:
	LDA #18
	JSL UPLOAD_VWF_BUFFER_TO_VRAM
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA #18
	JSL SCROLL_FLYOVER_TEXT
	BRA @SCRIPT_PARSE_BEGIN
@PARSE_01:
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
	JSL ADVANCE_FLYOVER_PIXEL_OFFSET
	BRA @SCRIPT_PARSE_BEGIN
@PARSE_08:
	LDA [@VIRTUAL06]
	AND #$00FF
	TAY
	INC @VIRTUAL06
	LDX #12
	TYA
	JSL RENDER_PARTY_MEMBER_NAME
	BRA @SCRIPT_PARSE_BEGIN
@PRINT_TEXT:
	LDA [@VIRTUAL06]
	AND #$00FF
	TAX
	INC @VIRTUAL06
	LDY #12
	LDA @LOCAL00
	JSL RENDER_FLYOVER_TEXT_CHARACTER
	BRA @SCRIPT_PARSE_BEGIN
@END_OF_SCRIPT:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$04
	STA TM_MIRROR
	LDY #0
	LDX #3
	REP #PROC_FLAGS::ACCUM8
	LDA #1
	JSL FADE_IN_WITH_MOSAIC
	LDX #$0000
	STX @LOCAL00
	BRA @DISPLAY_LOOP_CHECK
@WAIT_FRAME:
	JSL WAIT_UNTIL_NEXT_FRAME
	LDX @LOCAL00
	INX
	STX @LOCAL00
@DISPLAY_LOOP_CHECK:
	CPX #180
	BCC @WAIT_FRAME
	LDY #0
	LDX #3
	LDA #1
	JSL FADE_OUT_WITH_MOSAIC
	SEP #PROC_FLAGS::ACCUM8
	LDA #$17
	STA TM_MIRROR
	LDY #.LOWORD(BG2_BUFFER)
	LDX #$0380
	BRA @CLEAR_BG2_LOOP_CHECK
@CLEAR_BG2_ENTRY:
	REP #PROC_FLAGS::ACCUM8
	LDA #0
	STA __BSS_START__,Y
	INY
	INY
	DEX
@CLEAR_BG2_LOOP_CHECK:
	BNE @CLEAR_BG2_ENTRY
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	JSL UNDRAW_FLYOVER_TEXT
	LDA @VIRTUAL02
	STA ENTITY_TICK_CALLBACK_HIGH+46
	JSL BLANK_SCREEN_AND_WAIT_VBLANK
	END_C_FUNCTION
