
POPULATE_PATH_MATRIX:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @LOCAL04
	STA @VIRTUAL04
	LDA #0
	STA @LOCAL03
	BRA @CLEAR_CELL_CHECK
@CLEAR_CELL_BODY:
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @LOCAL03
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	CMP #<-3
	BEQ @CLEAR_CELL_SKIP
	LDA #<-2
	STA [@VIRTUAL06]
@CLEAR_CELL_SKIP:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	INC
	STA @LOCAL03
@CLEAR_CELL_CHECK:
	CMP PATH_MATRIX_SIZE
	BCC @CLEAR_CELL_BODY
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL02
	JMP @ENTITY_LOOP_CHECK
@ENTITY_LOOP_BODY:
	LDA @VIRTUAL02
	ASL
	TAY
	LDA (@LOCAL04),Y
	TAY
	STY @LOCAL01
	LDA __BSS_START__,Y
	BNE @MARK_ENTITY_AREA
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA a:pathfinder::origin + pathfinder_coords::y_coord,Y
	LDY PATH_MATRIX_COLUMNS
	JSL MULT16
	LDY @LOCAL01
	CLC
	ADC a:pathfinder::origin + pathfinder_coords::x_coord,Y
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	CMP #<-3
	BEQL @NEXT_ENTITY
	LDA #<-1
	STA [@VIRTUAL06]
	JMP @NEXT_ENTITY
@MARK_ENTITY_AREA:
	.A16
	LDA #0
	STA @LOCAL00
	BRA @TOP_BORDER_ROW_CHECK
@TOP_BORDER_ROW_BODY:
	LDX #0
	BRA @TOP_BORDER_COL_CHECK
@TOP_BORDER_MARK_CELL:
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	STX @VIRTUAL02
	LDY PATH_MATRIX_COLUMNS
	LDA @LOCAL00
	JSL MULT16
	CLC
	ADC @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	CMP #<-3
	BEQ @TOP_BORDER_SKIP_WALL
	LDA #<-1
	STA [@VIRTUAL06]
@TOP_BORDER_SKIP_WALL:
	INX
@TOP_BORDER_COL_CHECK:
	CPX PATH_MATRIX_COLUMNS
	BCC @TOP_BORDER_MARK_CELL
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	INC
	STA @LOCAL00
@TOP_BORDER_ROW_CHECK:
	CMP PATH_MATRIX_BORDER
	BCC @TOP_BORDER_ROW_BODY
	LDA PATH_MATRIX_ROWS
	SEC
	SBC PATH_MATRIX_BORDER
	STA @LOCAL00
	BRA @BOTTOM_BORDER_ROW_CHECK
@BOTTOM_BORDER_ROW_BODY:
	LDX #0
	BRA @BOTTOM_BORDER_COL_CHECK
@BOTTOM_BORDER_MARK_CELL:
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	STX @VIRTUAL02
	LDY PATH_MATRIX_COLUMNS
	LDA @LOCAL00
	JSL MULT16
	CLC
	ADC @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	CMP #<-3
	BEQ @BOTTOM_BORDER_SKIP_WALL
	LDA #<-1
	STA [@VIRTUAL06]
@BOTTOM_BORDER_SKIP_WALL:
	INX
@BOTTOM_BORDER_COL_CHECK:
	CPX PATH_MATRIX_COLUMNS
	BCC @BOTTOM_BORDER_MARK_CELL
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	INC
	STA @LOCAL00
@BOTTOM_BORDER_ROW_CHECK:
	CMP PATH_MATRIX_ROWS
	BCC @BOTTOM_BORDER_ROW_BODY
	LDX #0
	BRA @LEFT_BORDER_COL_CHECK
@LEFT_BORDER_COL_BODY:
	LDA #0
	STA @LOCAL03
	BRA @LEFT_BORDER_ROW_CHECK
@LEFT_BORDER_MARK_CELL:
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	STX @VIRTUAL02
	LDY PATH_MATRIX_COLUMNS
	LDA @LOCAL03
	JSL MULT16
	CLC
	ADC @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	CMP #<-3
	BEQ @LEFT_BORDER_SKIP_WALL
	LDA #<-1
	STA [@VIRTUAL06]
@LEFT_BORDER_SKIP_WALL:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	INC
	STA @LOCAL03
@LEFT_BORDER_ROW_CHECK:
	CMP PATH_MATRIX_ROWS
	BCC @LEFT_BORDER_MARK_CELL
	INX
@LEFT_BORDER_COL_CHECK:
	CPX PATH_MATRIX_BORDER
	BCC @LEFT_BORDER_COL_BODY
	LDA PATH_MATRIX_COLUMNS
	SEC
	SBC PATH_MATRIX_BORDER
	TAX
	BRA @RIGHT_BORDER_COL_CHECK
@RIGHT_BORDER_COL_BODY:
	LDA #0
	STA @LOCAL03
	BRA @RIGHT_BORDER_ROW_CHECK
@RIGHT_BORDER_MARK_CELL:
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	STX @VIRTUAL02
	LDY PATH_MATRIX_COLUMNS
	LDA @LOCAL03
	JSL MULT16
	CLC
	ADC @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	CMP #<-3
	BEQ @RIGHT_BORDER_SKIP_WALL
	LDA #<-1
	STA [@VIRTUAL06]
@RIGHT_BORDER_SKIP_WALL:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	INC
	STA @LOCAL03
@RIGHT_BORDER_ROW_CHECK:
	CMP PATH_MATRIX_ROWS
	BCC @RIGHT_BORDER_MARK_CELL
	INX
@RIGHT_BORDER_COL_CHECK:
	CPX PATH_MATRIX_COLUMNS
	BCC @RIGHT_BORDER_COL_BODY
	LDY @LOCAL01
	TYX
	STZ a:pathfinder::origin + pathfinder_coords::y_coord,X
	TYX
	STZ a:pathfinder::origin + pathfinder_coords::x_coord,X
@NEXT_ENTITY:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL02
@ENTITY_LOOP_CHECK:
	LDA @VIRTUAL02
	CMP @VIRTUAL04
	BCCL @ENTITY_LOOP_BODY
	END_C_FUNCTION
