
QUANTIZE_DIRECTION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDY #$2000
	CLC
	ADC #$1000
	JSL DIVISION16S_DIVISOR_POSITIVE
	ASL
	TAX
	LDA f:QUANTIZED_ANGLE_TO_DIRECTION_TABLE,X
	END_C_FUNCTION
