
RECALC_CHARACTER_POSTMATH_DEFENSE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;NEAR int character
	END_STACK_VARS
	TAX
	DEC
	STA @VIRTUAL02
	STA @LOCAL03
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::base_defense,X
	AND #$00FF
	TAY
	STY @LOCAL02
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	TAX
	BEQ @CHECK_ARMS
	LDA #0
	STA @LOCAL01
	LDA @VIRTUAL02
	CMP #PARTY_MEMBER::POO - 1
	BNE @NOT_POO_BODY
	LDA #1
	STA @LOCAL01
@NOT_POO_BODY:
	LDA @LOCAL01
	PHA
	TXA
	DEC
.IF .DEFINED(JPN)
	STA @VIRTUAL04
.ELSE
	PHA
.ENDIF
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
.IF .DEFINED(JPN)
	CLC
	ADC @VIRTUAL04
.ELSE
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
.ENDIF
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL04
	LDY @LOCAL02
	TYA
	CLC
	ADC @VIRTUAL04
	TAY
	STY @LOCAL02
@CHECK_ARMS:
	LDA @LOCAL03
	STA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::ARMS,X
	AND #$00FF
	TAX
	BEQ @CHECK_OTHER
	LDA #0
	STA @LOCAL01
	LDA @VIRTUAL02
	CMP #PARTY_MEMBER::POO - 1
	BNE @NOT_POO_ARMS
	LDA #1
	STA @LOCAL01
@NOT_POO_ARMS:
	LDA @LOCAL01
	PHA
	TXA
	DEC
.IF .DEFINED(JPN)
	STA @VIRTUAL04
.ELSE
	PHA
.ENDIF
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
.IF .DEFINED(JPN)
	CLC
	ADC @VIRTUAL04
.ELSE
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
.ENDIF
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL04
	LDY @LOCAL02
	TYA
	CLC
	ADC @VIRTUAL04
	TAY
	STY @LOCAL02
@CHECK_OTHER:
	LDA @LOCAL03
	STA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	TAX
	BEQ @CLAMP
	LDA #0
	STA @LOCAL01
	LDA @VIRTUAL02
	CMP #PARTY_MEMBER::POO - 1
	BNE @NOT_POO_OTHER
	LDA #1
	STA @LOCAL01
@NOT_POO_OTHER:
	LDA @LOCAL01
	PHA
	TXA
	DEC
.IF .DEFINED(JPN)
	STA @VIRTUAL04
.ELSE
	PHA
.ENDIF
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
.IF .DEFINED(JPN)
	CLC
	ADC @VIRTUAL04
.ELSE
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
.ENDIF
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	STA @VIRTUAL04
	LDY @LOCAL02
	TYA
	CLC
	ADC @VIRTUAL04
	TAY
	STY @LOCAL02
@CLAMP:
	LDY @LOCAL02
	STY @VIRTUAL04
	LDA #0
	CLC
	SBC @VIRTUAL04
	BRANCHLTEQS @CHECK_UPPER_BOUND
	LDA #0
	BRA @STORE_RESULT
@CHECK_UPPER_BOUND:
	TYA
	CLC
	SBC #$00FF
	BRANCHLTEQS @IN_RANGE
	LDA #$00FF
	BRA @STORE_RESULT
@IN_RANGE:
	TYA
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
@STORE_RESULT:
	SEP #PROC_FLAGS::ACCUM8
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	STA PARTY_CHARACTERS+char_struct::defense,X
	END_C_FUNCTION
