
RECORD_REPEATED_AUTO_MOVEMENT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @LOCAL01
	TAY
	STY @LOCAL00
	BRA @RECORD_CHECK
@RECORD_LOOP:
	LDY @LOCAL00
	TYA
	ASL
	TAX
	LDA f:AUTO_MOVEMENT_DIRECTION_TABLE,X
	JSL RECORD_AUTO_MOVEMENT_STEP
	LDX @LOCAL01
	DEX
	STX @LOCAL01
@RECORD_CHECK:
	CPX #0
	BNE @RECORD_LOOP
	END_C_FUNCTION
