
REDUCE_HP_AMTPERCENT:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL02
	STX @VIRTUAL04
	CMP #$00FF
	BNE @SINGLE_CHARACTER
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL01
	BRA @CHECK_LOOP
@REDUCE_MEMBER:
	LDY @LOCAL02
	LDX @VIRTUAL04
	STX @LOCAL00
	LDA @LOCAL01
	STA @VIRTUAL02
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
.ELSE
	LDX @VIRTUAL02
	LDA GAME_STATE + game_state::party_members,X
.ENDIF
	AND #$00FF
	LDX @LOCAL00
	JSL REDUCE_HP_TARGET
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL01
@CHECK_LOOP:
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	PHA
	LDA @VIRTUAL02
	PLY
	STY @VIRTUAL02
	CMP @VIRTUAL02
	BCC @REDUCE_MEMBER
	BRA @RETURN
@SINGLE_CHARACTER:
	LDY @LOCAL02
	LDX @VIRTUAL04
	JSL REDUCE_HP_TARGET
@RETURN:
	END_C_FUNCTION
