
REMOVE_ITEM_FROM_INVENTORY:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXY
	STY @LOCAL03
	TAX
	DEC
	STA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::WEAPON,X
	AND #$00FF
	STA @VIRTUAL04
	LDY @LOCAL03
	TYA
	CMP @VIRTUAL04
	BNE @CHECK_BODY
	LDX #0
	LDA @VIRTUAL02
	INC
	JSL CHANGE_EQUIPPED_WEAPON
	BRA @DONE_UNEQUIP
@CHECK_BODY:
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	STA @VIRTUAL04
	TYA
	CMP @VIRTUAL04
	BNE @CHECK_ARMS
	LDX #0
	LDA @VIRTUAL02
	INC
	JSL CHANGE_EQUIPPED_BODY
	BRA @DONE_UNEQUIP
@CHECK_ARMS:
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::ARMS,X
	AND #$00FF
	STA @VIRTUAL04
	TYA
	CMP @VIRTUAL04
	BNE @CHECK_OTHER
	LDX #0
	LDA @VIRTUAL02
	INC
	JSL CHANGE_EQUIPPED_ARMS
	BRA @DONE_UNEQUIP
@CHECK_OTHER:
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	STA @VIRTUAL04
	TYA
	CMP @VIRTUAL04
	BNE @DONE_UNEQUIP
	LDX #0
	LDA @VIRTUAL02
	INC
	JSL CHANGE_EQUIPPED_OTHER
@DONE_UNEQUIP:
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::equipment+EQUIPMENT_SLOT::WEAPON
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL04
	LDY @LOCAL03
	TYA
	CMP @VIRTUAL04
	BCS @ADJUST_BODY
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	DEC
	STA __BSS_START__,X
@ADJUST_BODY:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::equipment+EQUIPMENT_SLOT::BODY
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL04
	LDY @LOCAL03
	TYA
	CMP @VIRTUAL04
	BCS @ADJUST_ARMS
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	DEC
	STA __BSS_START__,X
@ADJUST_ARMS:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::equipment+EQUIPMENT_SLOT::ARMS
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL04
	LDY @LOCAL03
	TYA
	CMP @VIRTUAL04
	BCS @ADJUST_OTHER
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	DEC
	STA __BSS_START__,X
@ADJUST_OTHER:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::equipment+EQUIPMENT_SLOT::OTHER
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL04
	LDY @LOCAL03
	TYA
	CMP @VIRTUAL04
	BCS @SAVE_REMOVED_ITEM
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	DEC
	STA __BSS_START__,X
@SAVE_REMOVED_ITEM:
	REP #PROC_FLAGS::ACCUM8
	TYA
	DEC
	STA @VIRTUAL04
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @VIRTUAL00
	BRA @SHIFT_LOOP_TEST
@SHIFT_ITEM:
	TYA
	DEC
	STA @VIRTUAL04
	LDX @LOCAL01
	TXA
	CLC
	ADC @VIRTUAL04
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	STA __BSS_START__,X
	INY
	STY @LOCAL03
@SHIFT_LOOP_TEST:
	LDY @LOCAL03
	CPY #14
	BCS @CLEAR_LAST_SLOT
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	TAX
	STX @LOCAL01
	LDY @LOCAL03
	STY @VIRTUAL04
	TXA
	CLC
	ADC @VIRTUAL04
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNE @SHIFT_ITEM
@CLEAR_LAST_SLOT:
	REP #PROC_FLAGS::ACCUM8
	TYA
	DEC
	STA @VIRTUAL04
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LOADPTR ITEM_CONFIGURATION_TABLE, @VIRTUAL06
	LDA @VIRTUAL00
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	STA @LOCAL03
	CLC
	ADC #item::type
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	CMP #ITEM_TYPE::TEDDY_BEAR
	BNE @NOT_TEDDY_BEAR
	LDA @LOCAL03
	CLC
	ADC #item::params + item_parameters::strength
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	JSL REMOVE_CHAR_FROM_PARTY
	JSL UPDATE_TEDDY_BEAR_PARTY
@NOT_TEDDY_BEAR:
	LDA @VIRTUAL00
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::flags
	TAX
	LDA f:ITEM_CONFIGURATION_TABLE,X
	AND #$00FF
	AND #ITEM_FLAGS::TRANSFORM
	BEQ @NO_TRANSFORM
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	JSL START_TIMED_ITEM_TRANSFORMATION
@NO_TRANSFORM:
	LDA @VIRTUAL02
	INC
	END_C_FUNCTION
