
REMOVE_ASSOCIATED_ENTITIES:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	CMP #.LOWORD(-1)
	BEQ @RETURN
	ORA #$C000
	STA @VIRTUAL02
	LDY #0
	STY @LOCAL00
	BRA @CHECK_LOOP_BOUND
@CHECK_ENTITY:
	TYA
	ASL
	CLC
	ADC #.LOWORD(ENTITY_DRAW_PRIORITY)
	TAX
	LDA __BSS_START__,X
	CMP @VIRTUAL02
	BNE @NEXT_ENTITY
	LDA #0
	STA __BSS_START__,X
	TYA
	JSL REMOVE_ENTITY
@NEXT_ENTITY:
	LDY @LOCAL00
	INY
	STY @LOCAL00
@CHECK_LOOP_BOUND:
	CPY #MAX_ENTITIES
	BCC @CHECK_ENTITY
@RETURN:
	END_C_FUNCTION
