
RENDER_KEYBOARD_INPUT_CHARACTER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	STY @LOCAL06
	STX @LOCAL05
	JSL WAIT_UNTIL_NEXT_FRAME
	STZ VWF_TILE
	STZ VWF_X
	SEP #PROC_FLAGS::ACCUM8
	LDA #<-1
	STA @LOCAL00
	LDX #32 * 26
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(VWF_BUFFER)
	JSL MEMSET16
	STZ TEXT_RENDER_STATE + 2
	STZ TEXT_RENDER_STATE
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	STA @LOCAL04
	LDA @LOCAL06
	CMP #.LOWORD(-1)
	BNE @INSERT_CHAR
	LDA NEXT_KEYBOARD_INPUT_INDEX
	BNE @BACKSPACE_NOT_EMPTY
	LDA #TRUE
	JMP @RETURN
@BACKSPACE_NOT_EMPTY:
	LDA NEXT_KEYBOARD_INPUT_INDEX
	CMP @LOCAL05
	BCS @BACKSPACE_DO
	LDA #83
	JSR REGISTER_KEYBOARD_INPUT_CHARACTER
@BACKSPACE_DO:
	DEC NEXT_KEYBOARD_INPUT_INDEX
	LDA #112
	JSR REGISTER_KEYBOARD_INPUT_CHARACTER
	BRA @RENDER_VWF
@INSERT_CHAR:
	LDA @LOCAL05
	DEC
	CMP NEXT_KEYBOARD_INPUT_INDEX
	BCS @INSERT_DO
	LDA #FALSE
	JMP @RETURN
@INSERT_DO:
	LDA @LOCAL06
	JSR REGISTER_KEYBOARD_INPUT_CHARACTER
	LDA NEXT_KEYBOARD_INPUT_INDEX
	INC
	STA NEXT_KEYBOARD_INPUT_INDEX
	CMP @LOCAL05
	BCS @RENDER_VWF
	LDA #112
	JSR REGISTER_KEYBOARD_INPUT_CHARACTER
@RENDER_VWF:
	LOADPTR FONT_PTR_TABLE, @VIRTUAL06
	LDY #font_table_entry::width
	LDA [@VIRTUAL06],Y
	STA @VIRTUAL04
	LDX @LOCAL04
	STZ a:window_stats::text_x,X
	LDY #font_table_entry::height
	LDA [@VIRTUAL06],Y
	STA @LOCAL03
	LDA #0
	STA @VIRTUAL02
	BRA @CHECK_GLYPH_LOOP
@BLIT_GLYPH:
	MOVE_INT FONT_PTR_TABLE + font_table_entry::graphics, @VIRTUAL06
	LDX @VIRTUAL02
	LDA KEYBOARD_INPUT_CHARACTER_OFFSETS,X
	AND #$00FF
	TAY
	LDA @LOCAL03
	JSL MULT16
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDX @VIRTUAL02
	LDA KEYBOARD_INPUT_CHARACTER_WIDTHS,X
	AND #$00FF
	TAY
	STY @LOCAL02
	BRA @CHECK_WIDTH_REMAINING
@BLIT_8PX_COLUMN:
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX @VIRTUAL04
	LDA #8
	JSL BLIT_VWF_GLYPH
	LDY @LOCAL02
	TYA
	SEC
	SBC #8
	TAY
	STY @LOCAL02
	LDA @VIRTUAL04
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
@CHECK_WIDTH_REMAINING:
	CPY #8
	BCS @BLIT_8PX_COLUMN
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX @VIRTUAL04
	TYA
	JSL BLIT_VWF_GLYPH
	INC @VIRTUAL02
@CHECK_GLYPH_LOOP:
	LDA @VIRTUAL02
	CMP @LOCAL05
	BCC @BLIT_GLYPH
	LDX @LOCAL04
	STZ a:window_stats::text_x,X
	LDA #VRAM::TEXT_LAYER_TILES + $1700
	STA @VIRTUAL04
	LDY #window_stats::width
	LDA (@LOCAL04),Y
	STA @LOCAL01
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL02
	BRA @CHECK_TILE_LOOP
@UPLOAD_TILE:
	LDA @LOCAL02
	STA @VIRTUAL02
	ASL
	ASL
	ASL
	ASL
	ASL
	STA @LOCAL04
	CLC
	ADC #.LOWORD(VWF_BUFFER)
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDY @VIRTUAL04
	LDX #16
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	.A16
	LDA @LOCAL04
	CLC
	ADC #.LOWORD(VWF_BUFFER) + 16
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	COPY_TO_VRAM1OFFSET @VIRTUAL06, @VIRTUAL04, 16, 8, 0
	.A16
	LDA @VIRTUAL04
	CLC
	ADC #16
	STA @VIRTUAL04
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL02
@CHECK_TILE_LOOP:
	LDA @VIRTUAL02
	PHA
	LDA @LOCAL01
	STA @VIRTUAL02
	INC @VIRTUAL02
	PLA
	CMP @VIRTUAL02
	BCCL @UPLOAD_TILE
	LDA #1
	STA DMA_TRANSFER_FLAG
	LDY #0
	STY @LOCAL05
	BRA @CHECK_CHAR_LOOP
@WRITE_CHAR_TO_TILEMAP:
	TYA
	ASL
	CLC
	ADC #$02E0
	TAX
	INX
	JSR WRITE_CHAR_TO_WINDOW
	LDY @LOCAL05
	INY
	STY @LOCAL05
@CHECK_CHAR_LOOP:
	LDA @LOCAL01
	STA @VIRTUAL02
	INC @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BCC @WRITE_CHAR_TO_TILEMAP
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	CMP WINDOW_TAIL
	BEQ @CHECK_TEXT_SOUND
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA REDRAW_ALL_WINDOWS
@CHECK_TEXT_SOUND:
	REP #PROC_FLAGS::ACCUM8
	LDA TEXT_SOUND_MODE
	CMP #2
	BNE @CHECK_SOUND_MODE_3
	LDX #1
	BRA @PLAY_TEXT_SFX
@CHECK_SOUND_MODE_3:
	LDA TEXT_SOUND_MODE
	CMP #3
	BNE @CHECK_BLINKING_TRIANGLE
	LDX #0
	BRA @PLAY_TEXT_SFX
@CHECK_BLINKING_TRIANGLE:
	LDX #0
	LDA BLINKING_TRIANGLE_FLAG
	BNE @PLAY_TEXT_SFX
	LDX #1
@PLAY_TEXT_SFX:
	CPX #0
	BEQ @WAIT_TEXT_SPEED
	LDA INSTANT_PRINTING
	AND #$00FF
	BNE @WAIT_TEXT_SPEED
	LDA @LOCAL06
	CMP #32
	BEQ @WAIT_TEXT_SPEED
	LDA #SFX::TEXT_PRINT
	JSL PLAY_SOUND
@WAIT_TEXT_SPEED:
	LDX SELECTED_TEXT_SPEED
	INX
	STX @LOCAL06
	BRA @CHECK_SPEED_DELAY
@SPEED_DELAY_TICK:
	JSL WINDOW_TICK
	LDX @LOCAL06
	DEX
	STX @LOCAL06
@CHECK_SPEED_DELAY:
	BNE @SPEED_DELAY_TICK
	LDA #FALSE
@RETURN:
	END_C_FUNCTION
