
RESTORE_OVERWORLD_STATE:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	STZ PENDING_INTERACTIONS
	LDA #EVENT_FLAG::FLG_WIN_GIEGU
	JSL GET_EVENT_FLAG
	STA OVERWORLD_STATUS_SUPPRESSION
	LDA GAME_STATE+game_state::walking_style
	CMP #WALKING_STYLE::BICYCLE
	BNE @NOT_REPLAY
	LDA #MUSIC::BICYCLE
	JSL CHANGE_MUSIC
	BRA @DONE
@NOT_REPLAY:
	JSL UPDATE_MAP_MUSIC_AT_LEADER
@DONE:
	END_C_FUNCTION
