
RUN_ATTRACT_MODE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STA @VIRTUAL02
	JSL INIT_ENTITY_SYSTEM
	JSL CLEAR_OVERWORLD_SPRITEMAPS
	LDX #0
	LDA #$8000
	JSL ALLOC_SPRITE_MEM
	JSL INITIALIZE_MISC_OBJECT_DATA
	LDA #1
	STA NPC_SPAWNS_ENABLED
	STZ ENEMY_SPAWNS_ENABLED
	LDA #0
	JSL SET_AUTO_SECTOR_MUSIC_CHANGES
	LDA #23
	STA ENTITY_ALLOCATION_MIN_SLOT
	LDA #24
	STA ENTITY_ALLOCATION_MAX_SLOT
	LDY #0
	TYX
	LDA #1
	JSL INIT_ENTITY
	JSL RESET_PARTY_STATE
	LDA #0
	STA @LOCAL02
	BRA @PARTY_LOOP_CHECK
@CLEAR_PARTY_MEMBER:
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ a:game_state::party_members,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	INC
	STA @LOCAL02
@PARTY_LOOP_CHECK:
	CMP #.SIZEOF(game_state::party_members)
	BCC @CLEAR_PARTY_MEMBER
	LDX #2824
	LDA #7520
	JSL PLACE_LEADER_AT_POSITION
	JSL INITIALIZE_PARTY
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA @LOCAL00
	LDX #BPP4PALETTE_SIZE * 16
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(PALETTES)
	JSL MEMSET16
	JSL OVERWORLD_INITIALIZE
	SEP #PROC_FLAGS::ACCUM8
	STZ TM_MIRROR
	REP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL INIT_OVAL_WINDOW
	JSL UPDATE_SWIRL_EFFECT
	STZ ACTIONSCRIPT_STATE
	LDX #0
	STX @LOCAL02
	TXY
	STY @LOCAL01
	LOADPTR ATTRACT_MODE_TXT, @VIRTUAL0A
	LDA @VIRTUAL02
	ASL
	ASL
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
	BRA @SCRIPT_LOOP_CHECK
@MAIN_LOOP:
	JSL UPDATE_SWIRL_EFFECT
	LDA PAD_PRESS
	AND #PAD::A_BUTTON
	BNE @BUTTON_PRESSED
	LDA PAD_PRESS
	AND #PAD::B_BUTTON
	BNE @BUTTON_PRESSED
	LDA PAD_PRESS
	AND #PAD::START_BUTTON
	BEQ @NO_BUTTON
@BUTTON_PRESSED:
	LDY #1
	STY @LOCAL01
	BRA @AFTER_SCRIPT
@NO_BUTTON:
	JSL RENDER_FRAME_TICK
	LDX @LOCAL02
	BEQ @SET_TM_MIRROR
	CPX #1
	BNE @AFTER_TM_MIRROR
@SET_TM_MIRROR:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$13
	STA TM_MIRROR
@AFTER_TM_MIRROR:
	INX
	STX @LOCAL02
@SCRIPT_LOOP_CHECK:
	REP #PROC_FLAGS::ACCUM8
	LDA ACTIONSCRIPT_STATE
	BEQ @MAIN_LOOP
@AFTER_SCRIPT:
	JSL CLOSE_OVAL_WINDOW
	BRA @CHECK_PSI_ANIMATION
@WAIT_PSI_ANIMATION:
	JSL RENDER_FRAME_TICK
	JSL UPDATE_SWIRL_EFFECT
@CHECK_PSI_ANIMATION:
	JSL IS_PSI_ANIMATION_ACTIVE
	CMP #0
	BNE @WAIT_PSI_ANIMATION
	LDX #1
	TXA
	JSL FADE_OUT
	BRA @FADE_OUT_LOOP_CHECK
@WAIT_FADE_OUT:
	JSL RENDER_FRAME_TICK
@FADE_OUT_LOOP_CHECK:
	LDA FADE_PARAMETERS + fade_parameters::step
	AND #$00FF
	BNE @WAIT_FADE_OUT
	JSL STOP_OVAL_WINDOW
	STZ ACTIONSCRIPT_STATE
	JSL CLEAR_MAP_ENTITIES
	LDY @LOCAL01
	TYA
	END_C_FUNCTION
