
SAVE_PHOTO_STATE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	DEC
	STA @VIRTUAL02
	LOADINT32 3600, @VIRTUAL0A
	LOADPTRPTR TIMER, @VIRTUAL06
	JSL DIVISION32
	LOADINT32 60000, @VIRTUAL0A
	CLC
	LDA @VIRTUAL0A
	SBC @VIRTUAL06
	LDA @VIRTUAL0A+2
	SBC @VIRTUAL06+2
	BRANCHLTEQS @TIME_OVERFLOW
	LDA @VIRTUAL06
	STA @LOCAL02
	BRA @TIME_DONE
@TIME_OVERFLOW:
	LDA #59999
	STA @LOCAL02
@TIME_DONE:
	LDA @VIRTUAL02
	ASL
	ASL
	ASL
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA @LOCAL02
	STA a:game_state::saved_photo_states,X
.ELSE
	TAX
	LDA @LOCAL02
	STA GAME_STATE + game_state::saved_photo_states,X
.ENDIF
	LDY #0
	STY @LOCAL01
	JMP @PARTY_LOOP_CHECK
@PARTY_LOOP_BODY:
	REP #PROC_FLAGS::ACCUM8
	TYA
	CLC
	ADC #.LOWORD(GAME_STATE)
	STA @LOCAL02
	CLC
	ADC #game_state::party_order
	TAX
	STX @LOCAL00
	LDA __BSS_START__,X
	AND #$00FF
	BNE @PARTY_MEMBER_PRESENT
	STY @VIRTUAL04
	LDA @VIRTUAL02
	ASL
	ASL
	ASL
	CLC
.IF .DEFINED(JPN)
	ADC #.LOWORD(GAME_STATE)
	CLC
	ADC @VIRTUAL04
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ a:game_state::saved_photo_states + photo_state::party,X
	JMP @NEXT_PARTY_MEMBER
.ELSE
	ADC @VIRTUAL04
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ GAME_STATE + game_state::saved_photo_states + photo_state::party,X
	BRA @NEXT_PARTY_MEMBER
.ENDIF
@PARTY_MEMBER_PRESENT:
	.A16
	LDA @LOCAL02
	TAX
	LDA __BSS_START__+game_state::player_controlled_party_members,X
	AND #$00FF
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	STA @LOCAL02
	STA CURRENT_PARTY_MEMBER_TICK
	LDX @LOCAL00
	LDA __BSS_START__,X
	AND #$00FF
	TAX
	STX @LOCAL00
	LDA @LOCAL02
	TAX
	LDA a:char_struct::afflictions,X
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BNE @CHECK_DIAMONDIZED
	LDX @LOCAL00
	TXA
	ORA #$0020
	TAX
	STX @LOCAL00
	BRA @CHECK_MUSHROOMIZED
@CHECK_DIAMONDIZED:
	CMP #STATUS_0::DIAMONDIZED
	BNE @CHECK_MUSHROOMIZED
	LDX @LOCAL00
	TXA
	ORA #$0040
	TAX
	STX @LOCAL00
@CHECK_MUSHROOMIZED:
	LDX CURRENT_PARTY_MEMBER_TICK
	LDA a:char_struct::afflictions+STATUS_GROUP::PERSISTENT_HARDHEAL,X
	AND #$00FF
	CMP #STATUS_1::MUSHROOMIZED
	BNE @STORE_PARTY_STATUS
	LDX @LOCAL00
	TXA
	ORA #$0080
	TAX
	STX @LOCAL00
@STORE_PARTY_STATUS:
	LDY @LOCAL01
	STY @VIRTUAL04
	LDA @VIRTUAL02
	ASL
	ASL
	ASL
	CLC
.IF .DEFINED(JPN)
	ADC #.LOWORD(GAME_STATE)
	CLC
	ADC @VIRTUAL04
	PHA
	LDX @LOCAL00
	TXA
	SEP #PROC_FLAGS::ACCUM8
	PLX
	STA a:game_state::saved_photo_states + photo_state::party,X
.ELSE
	ADC @VIRTUAL04
	PHA
	LDX @LOCAL00
	TXA
	SEP #PROC_FLAGS::ACCUM8
	PLX
	STA GAME_STATE + game_state::saved_photo_states + photo_state::party,X
.ENDIF
@NEXT_PARTY_MEMBER:
	INY
	STY @LOCAL01
@PARTY_LOOP_CHECK:
	CPY #6
	BCCL @PARTY_LOOP_BODY
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
