
SET_ALL_PARTY_DIRECTIONS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL02
	LDY #0
	STY @LOCAL01
	BRA @LOOP_CHECK
@LOOP_BODY:
.IF .DEFINED(JPN)
	TYA
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_order,X
.ELSE
	LDA GAME_STATE + game_state::party_order,Y
.ENDIF
	AND #$00FF
	STA @VIRTUAL04
	LDA #16
	CLC
	SBC @VIRTUAL04
	BRANCHLTEQS @NEXT_MEMBER
	TYA
	ASL
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_entity_slots,X
.ELSE
	TAX
	LDA GAME_STATE + game_state::party_entity_slots,X
.ENDIF
	STA @LOCAL00
	ASL
	CLC
	ADC #.LOWORD(ENTITY_DIRECTIONS)
	TAX
	LDA __BSS_START__,X
	CMP @VIRTUAL02
	BEQ @NEXT_MEMBER
	LDA @VIRTUAL02
	STA __BSS_START__,X
	LDA @LOCAL00
	JSL UPDATE_ENTITY_SPRITE
@NEXT_MEMBER:
	LDY @LOCAL01
	INY
	STY @LOCAL01
@LOOP_CHECK:
	LDA GAME_STATE+game_state::party_count
	AND #$00FF
	STA @VIRTUAL04
	TYA
	CMP @VIRTUAL04
	BCC @LOOP_BODY
	END_C_FUNCTION
