
SORT_PATH_NODES:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL08
	STA @LOCAL07
	DEC
	STA @LOCAL06
	LDA #0
	STA @LOCAL05
	BRA @INIT_CHECK
@INIT_ENTRY:
	ASL
	TAY
	LDA @LOCAL05
	OPTIMIZED_MULT @VIRTUAL04, 18
	STA @VIRTUAL02
	TXA
	CLC
	ADC @VIRTUAL02
	STA (@LOCAL08),Y
	LDA @LOCAL05
	INC
	STA @LOCAL05
@INIT_CHECK:
	CMP @LOCAL07
	BCC @INIT_ENTRY
	LDA @LOCAL07
	CMP #1
	BGT @OUTER_LOOP_CHECK
	JMP @DONE
@OUTER_LOOP_CHECK:
	LDA #0
	STA @VIRTUAL04
	BRA @OUTER_LOOP_COND
@OUTER_LOOP_BODY:
	LDA #.LOWORD(-1)
	STA @LOCAL04
	STA @LOCAL03
	LDY @VIRTUAL04
	STY @LOCAL02
	BRA @INNER_LOOP_COND
@COMPARE_ENTRY:
	TYA
	ASL
	TAY
	LDA (@LOCAL08),Y
	TAX
	LDA __BSS_START__+2,X
	STA @LOCAL01
	LDA __BSS_START__+4,X
	STA @VIRTUAL02
	LDA @LOCAL01
	CMP @LOCAL04
	BEQ @COMPARE_SECONDARY
	LDX #0
	CMP @LOCAL04
	BCS @CHECK_IS_LESS
	LDX #1
	BRA @CHECK_IS_LESS
@COMPARE_SECONDARY:
	LDX #0
	LDA @VIRTUAL02
	CMP @LOCAL03
	BCS @CHECK_IS_LESS
	LDX #1
@CHECK_IS_LESS:
	CPX #0
	BEQ @ADVANCE_INNER
	LDA @LOCAL01
	STA @LOCAL04
	LDA @VIRTUAL02
	STA @LOCAL03
	LDY @LOCAL02
	STY @LOCAL00
@ADVANCE_INNER:
	LDY @LOCAL02
	INY
	STY @LOCAL02
@INNER_LOOP_COND:
	CPY @LOCAL07
	BCC @COMPARE_ENTRY
	LDA @VIRTUAL04
	ASL
	CLC
	ADC @LOCAL08
	TAY
	LDA __BSS_START__,Y
	STA @LOCAL05
	LDA @LOCAL00
	ASL
	CLC
	ADC @LOCAL08
	TAX
	LDA __BSS_START__,X
	STA __BSS_START__,Y
	LDA @LOCAL05
	STA __BSS_START__,X
	INC @VIRTUAL04
@OUTER_LOOP_COND:
	LDA @VIRTUAL04
	CMP @LOCAL06
	BCCL @OUTER_LOOP_BODY
@DONE:
	END_C_FUNCTION
