
SORT_PATH_NODES:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL05
	STA @LOCAL04
	DEC
	STA @LOCAL03
	LDA #0
	STA @LOCAL02
	BRA @INIT_LOOP_CHECK
@INIT_NODE:
	ASL
	TAY
	LDA @LOCAL02
	OPTIMIZED_MULT @VIRTUAL04, 18
	STA @VIRTUAL02
	TXA
	CLC
	ADC @VIRTUAL02
	STA (@LOCAL05),Y
	LDA @LOCAL02
	INC
	STA @LOCAL02
@INIT_LOOP_CHECK:
	CMP @LOCAL04
	BCC @INIT_NODE
	LDA @LOCAL04
	CMP #1
	BLTEQ @RETURN
@SELECTION_SORT_PASS:
	LDA #0
	STA @VIRTUAL04
	BRA @OUTER_LOOP_CHECK
@FIND_MIN_NODE:
	LDA #.LOWORD(-1)
	STA @VIRTUAL02
	STA @LOCAL01
	LDX @VIRTUAL04
	BRA @INNER_LOOP_CHECK
@COMPARE_NODE:
	TXA
	ASL
	TAY
	LDA (@LOCAL05),Y
	TAY
	LDA __BSS_START__+2,Y
	STA @LOCAL02
	LDA __BSS_START__+4,Y
	TAY
	LDA @LOCAL02
	CMP @VIRTUAL02
	BEQ @CHECK_SECONDARY_KEY
	CMP @VIRTUAL02
	BCS @SKIP_UPDATE
	BRA @UPDATE_MIN
@CHECK_SECONDARY_KEY:
	CPY @LOCAL01
	BCS @SKIP_UPDATE
@UPDATE_MIN:
	STA @VIRTUAL02
	STY @LOCAL01
	STX @LOCAL00
@SKIP_UPDATE:
	INX
@INNER_LOOP_CHECK:
	CPX @LOCAL04
	BCC @COMPARE_NODE
	LDA @VIRTUAL04
	ASL
	CLC
	ADC @LOCAL05
	TAY
	LDA __BSS_START__,Y
	STA @LOCAL02
	LDA @LOCAL00
	ASL
	CLC
	ADC @LOCAL05
	TAX
	LDA __BSS_START__,X
	STA __BSS_START__,Y
	LDA @LOCAL02
	STA __BSS_START__,X
	INC @VIRTUAL04
@OUTER_LOOP_CHECK:
	LDA @VIRTUAL04
	CMP @LOCAL03
	BCC @FIND_MIN_NODE
@RETURN:
	END_C_FUNCTION
