
TELEPORT_MAINLOOP:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	END_STACK_VARS
	JSL STOP_MUSIC
	JSL WAIT_UNTIL_NEXT_FRAME
	JSR TELEPORT_FREEZEOBJECTS
	LDA #1
	STA UNREAD_7E5DBA
	MOVE_INT_CONSTANT 0, PSI_TELEPORT_SPEED
	STZ PSI_TELEPORT_STATE
	JSL CLEAR_PARTY_SPRITE_HIDE_FLAGS
	JSR INIT_PSI_TELEPORT_BETA
	LDA PSI_TELEPORT_STYLE
	CMP #TELEPORT_STYLE::PSI_ALPHA
	BEQ @STYLE_1_OR_5
	CMP #TELEPORT_STYLE::STAR_MASTER
	BEQ @STYLE_1_OR_5
	CMP #TELEPORT_STYLE::PSI_BETA
	BEQ @STYLE_2
	CMP #TELEPORT_STYLE::INSTANT
	BEQ @STYLE_3
	CMP #TELEPORT_STYLE::PSI_BETTER
	BEQ @STYLE_4
	BRA @STYLE_OTHER
@STYLE_1_OR_5:
	LOADPTR PSI_TELEPORT_ALPHA_TICK, @LOCAL00
	LOADPTR UPDATE_PARTY_ENTITY_FROM_BUFFER, @LOCAL01
	LDA #23
	JSL SET_PARTY_TICK_CALLBACKS
	BRA @STYLE_OTHER
@STYLE_2:
	LOADPTR PSI_TELEPORT_BETA_TICK, @LOCAL00
	LOADPTR UPDATE_PARTY_ENTITY_FROM_BUFFER, @LOCAL01
	LDA #23
	JSL SET_PARTY_TICK_CALLBACKS
	BRA @STYLE_OTHER
@STYLE_3:
	LDA #1
	STA PSI_TELEPORT_STATE
	BRA @STYLE_OTHER
@STYLE_4:
	LOADPTR PSI_TELEPORT_BETA_TICK, @LOCAL00
	LOADPTR UPDATE_PARTY_ENTITY_FROM_BUFFER, @LOCAL01
	LDA #23
	JSL SET_PARTY_TICK_CALLBACKS
@STYLE_OTHER:
	LDA PSI_TELEPORT_STYLE
	CMP #TELEPORT_STYLE::INSTANT
	BEQ @TELEPORT_LOOP_CHECK
	LDA #MUSIC::TELEPORT_OUT
	JSL CHANGE_MUSIC
	BRA @TELEPORT_LOOP_CHECK
@TELEPORT_LOOP_BODY:
	JSL OAM_CLEAR
	JSL RUN_ACTIONSCRIPT_FRAME
	JSR TELEPORT_FREEZEOBJECTS2
	JSL UPDATE_SCREEN
	JSL WAIT_UNTIL_NEXT_FRAME
@TELEPORT_LOOP_CHECK:
	LDA PSI_TELEPORT_STATE
	BEQ @TELEPORT_LOOP_BODY
	LDA PSI_TELEPORT_STATE
	CMP #1
	BEQ @STATE_ARRIVED
	CMP #2
	BEQ @STATE_FAILED
	BRA @CLEANUP
@STATE_ARRIVED:
	JSR INIT_TELEPORT_ARRIVAL
	JSL LOAD_TELEPORT_DESTINATION
	JSR INIT_TELEPORT_DEPARTURE
	LDA PSI_TELEPORT_STYLE
	CMP #TELEPORT_STYLE::STAR_MASTER
	BNE @CLEANUP
	LOADPTR MSG_EVT_MASTER_TLPT, @LOCAL00
	JSL FREEZE_AND_QUEUE_TEXT_INTERACTION
	BRA @CLEANUP
@STATE_FAILED:
	JSR RUN_TELEPORT_FAILURE_SEQUENCE
	LDA #10
	JSL WAIT_FRAMES_WITH_UPDATES
@CLEANUP:
	LOADPTR UPDATE_OVERWORLD_FRAME, @LOCAL00
	LOADPTR UPDATE_FOLLOWER_STATE, @LOCAL01
	LDA #23
	JSL SET_PARTY_TICK_CALLBACKS
	JSR RESET_ENTITIES_AFTER_TELEPORT
	JSL ENABLE_ALL_ENTITIES
	STZ UNREAD_7E5DBA
	MOVE_INT_CONSTANT NULL, PSI_TELEPORT_SPEED
	STZ PLAYER_INTANGIBILITY_FRAMES
	STZ PSI_TELEPORT_DESTINATION
	END_C_FUNCTION
