
TELEPORT_FREEZEOBJECTS:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #0
	STA @LOCAL00
	BRA @CHECK_LOOP
@FREEZE_ENTITY:
	ASL
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA __BSS_START__,X
	LDA @LOCAL00
	INC
	STA @LOCAL00
@CHECK_LOOP:
	CMP #23
	BCC @FREEZE_ENTITY
	END_C_FUNCTION
