
TELEPORT_FREEZEOBJECTS2:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDY #0
	BRA @CHECK_LOOP
@FREEZE_ENTITY:
	TYA
	ASL
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	STA @LOCAL00
	AND #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	CMP #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	BEQ @ALREADY_FROZEN
	LDA @LOCAL00
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA __BSS_START__,X
@ALREADY_FROZEN:
	INY
@CHECK_LOOP:
	CPY #23
	BCC @FREEZE_ENTITY
	END_C_FUNCTION
