
TRACE_PATH_ROUTE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @LOCAL0F
	STX @LOCAL0E
	TAX
	LDA __BSS_START__,X
	STA @LOCAL0D
	LDA __BSS_START__+2,X
	STA @LOCAL0C
	LDY #0
	STY @LOCAL0B
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDY PATH_MATRIX_COLUMNS
	LDA @LOCAL0D
	JSL MULT16
	CLC
	ADC @LOCAL0C
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	STA @VIRTUAL00
	CMP #<-5
	BLTEQ @CHECK_MAX_STEPS
	REP #PROC_FLAGS::ACCUM8
	LDA #0
	JMP @RETURN
@CHECK_MAX_STEPS:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL0E
	BNE @STORE_START_WAYPOINT
	LDA #0
	JMP @RETURN
@STORE_START_WAYPOINT:
	LDX @LOCAL0F
	LDA @LOCAL0D
	STA __BSS_START__,X
	LDA @LOCAL0C
	STA __BSS_START__+2,X
	LDA #1
	STA @LOCAL0A
	JMP @BACKTRACK_COND
@BACKTRACK_STEP:
	LDA #666
	STA @LOCAL09
	STA @LOCAL08
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	DEC
	STA @VIRTUAL00
	LDY @LOCAL0B
	STY @VIRTUAL02
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
	STA @LOCAL07
	STZ @LOCAL0B
	JMP @CARDINAL_LOOP_COND
@CHECK_CARDINAL:
	LDA @VIRTUAL02
	ASL
	ASL
	TAY
	LDA PATH_CARDINAL_INDEX + pathfinder_coords::y_coord,Y
	CLC
	ADC @LOCAL0D
	TAX
	LDA PATH_CARDINAL_INDEX + pathfinder_coords::x_coord,Y
	CLC
	ADC @LOCAL0C
	STA @LOCAL06
	LDA @VIRTUAL02
	INC
	AND #$0003
	STA @VIRTUAL04
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @LOCAL06
	STA @VIRTUAL02
	LDY PATH_MATRIX_COLUMNS
	TXA
	JSL MULT16
	CLC
	ADC @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	CMP @VIRTUAL00
	BNEL @CARDINAL_NO_MATCH
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL09
	CMP #666
	BNE @CHECK_DIAGONAL
	LDA @LOCAL07
	STA @VIRTUAL02
	STA @LOCAL09
	STX @LOCAL00
	LDA @LOCAL06
	STA @LOCAL01
@CHECK_DIAGONAL:
	LDA @LOCAL07
	STA @VIRTUAL02
	ASL
	ASL
	TAX
	LDA PATH_DIAGONAL_INDEX + pathfinder_coords::y_coord,X
	CLC
	ADC @LOCAL0D
	STA @LOCAL05
	LDA PATH_DIAGONAL_INDEX + pathfinder_coords::x_coord,X
	CLC
	ADC @LOCAL0C
	TAY
	STY @LOCAL04
	LDA @VIRTUAL00
	AND #$00FF
	DEC
	PHA
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	STY @VIRTUAL02
	LDY PATH_MATRIX_COLUMNS
	LDA @LOCAL05
	JSL MULT16
	CLC
	ADC @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	PLY
	STY @VIRTUAL02
	CMP @VIRTUAL02
	BNE @CARDINAL_NO_MATCH
	LDA @VIRTUAL04
	ASL
	ASL
	TAX
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA PATH_CARDINAL_INDEX + pathfinder_coords::x_coord,X
	CLC
	ADC @LOCAL0C
	STA @VIRTUAL02
	LDY PATH_MATRIX_COLUMNS
	LDA PATH_CARDINAL_INDEX + pathfinder_coords::y_coord,X
	CLC
	ADC @LOCAL0D
	JSL MULT16
	CLC
	ADC @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	CMP @VIRTUAL00
	BNE @CARDINAL_NO_MATCH
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	STA @VIRTUAL02
	STA @LOCAL08
	LDA @LOCAL05
	STA @LOCAL02
	LDY @LOCAL04
	STY @LOCAL03
	BRA @AFTER_DIRECTION_SCAN
@CARDINAL_NO_MATCH:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	STA @VIRTUAL02
	STA @LOCAL07
	INC @LOCAL0B
@CARDINAL_LOOP_COND:
	LDA @LOCAL0B
	CMP #4
	BCCL @CHECK_CARDINAL
@AFTER_DIRECTION_SCAN:
	LDA @LOCAL08
	CMP #666
	BEQ @NO_DIAGONAL_FOUND
	LDA @LOCAL02
	STA @LOCAL0D
	LDA @LOCAL03
	STA @LOCAL0C
	LDY @LOCAL08
	STY @LOCAL0B
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	DEC
	STA @VIRTUAL00
	BRA @CHECK_BUFFER_FULL
@NO_DIAGONAL_FOUND:
	.A16
	LDA @LOCAL09
	CMP #666
	BEQ @PATH_COMPLETE
	LDA @LOCAL00
	STA @LOCAL0D
	LDA @LOCAL01
	STA @LOCAL0C
	LDY @LOCAL09
	STY @LOCAL0B
@CHECK_BUFFER_FULL:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL0E
	CMP @LOCAL0A
	BNE @STORE_WAYPOINT
	LDA @LOCAL0A
	BRA @RETURN
@STORE_WAYPOINT:
	LDA @LOCAL0A
	ASL
	ASL
	CLC
	ADC @LOCAL0F
	TAX
	LDA @LOCAL0D
	STA __BSS_START__,X
	LDA @LOCAL0C
	STA __BSS_START__+2,X
	INC @LOCAL0A
@BACKTRACK_COND:
	LDA @VIRTUAL00
	AND #$00FF
	BNEL @BACKTRACK_STEP
@PATH_COMPLETE:
	LDA @LOCAL0A
@RETURN:
	END_C_FUNCTION
