
TRANSLITERATE_CONSONANT_VOWEL:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 "BUFFER" ;NEAR char*
	STACK_RESERVE_PARAM_INT16 ;int - consonant letter ($41 - $5A = 'A' - 'Z')
	STACK_RESERVE_PARAM_INT16 ;int - vowel index (0=a, 1=i, 2=u, 3=e, 4=o)
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STA @VIRTUAL02
	LOADPTR CONSONANT_VOWEL_TRANSLITERATION_PAIRS, @VIRTUAL06
	TYA
	ASL
	PHA
	TXA
	SEC
	SBC #$41
	OPTIMIZED_MULT @VIRTUAL04, 10
	PLY
	STY @VIRTUAL04
	CLC
	ADC @VIRTUAL04
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDX #2
	STX @LOCAL00
	BRA @LOOP_CHECK
@COPY_BYTE:
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
	INC @VIRTUAL02
	LDX @LOCAL00
	DEX
	STX @LOCAL00
@LOOP_CHECK:
	BEQ @DONE
	LDA [@VIRTUAL06]
	AND #$00FF
	BNE @COPY_BYTE
@DONE:
	LDA @VIRTUAL02
	END_C_FUNCTION
