
UPDATE_SWIRL_EFFECT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA FRAMES_UNTIL_NEXT_SWIRL_UPDATE
	AND #$00FF
	BEQL @RETURN
	LDY #.LOWORD(LOADED_OVAL_WINDOW)
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL0A
	CMP @VIRTUAL06+2
	BNE @CHECK_OVAL_NULL
	LDA @VIRTUAL0A
	CMP @VIRTUAL06
@CHECK_OVAL_NULL:
	BEQL @SWIRL_FRAME_UPDATE
	LDX #.LOWORD(FRAMES_UNTIL_NEXT_SWIRL_UPDATE)
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	DEC
	STA FRAMES_UNTIL_NEXT_SWIRL_UPDATE
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @APPLY_VELOCITIES
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL0A
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL0A]
	STA FRAMES_UNTIL_NEXT_SWIRL_UPDATE
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNE @LOAD_OVAL_PARAMS
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	JMP @RETURN
@LOAD_OVAL_PARAMS:
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDY #oval_window::centre_x
	LDA [@VIRTUAL06],Y
	CMP #$8000
	BEQ @SKIP_CENTRE_X
	STA LOADED_OVAL_WINDOW_CENTRE_X
@SKIP_CENTRE_X:
	MOVE_INT LOADED_OVAL_WINDOW, @VIRTUAL06
	LDY #oval_window::centre_y
	LDA [@VIRTUAL06],Y
	CMP #$8000
	BEQ @SKIP_CENTRE_Y
	STA LOADED_OVAL_WINDOW_CENTRE_Y
@SKIP_CENTRE_Y:
	MOVE_INT LOADED_OVAL_WINDOW, @VIRTUAL06
	LDY #oval_window::initial_width
	LDA [@VIRTUAL06],Y
	CMP #$8000
	BEQ @SKIP_WIDTH
	STA LOADED_OVAL_WINDOW_WIDTH
@SKIP_WIDTH:
	MOVE_INT LOADED_OVAL_WINDOW, @VIRTUAL06
	LDY #oval_window::initial_height
	LDA [@VIRTUAL06],Y
	CMP #$8000
	BEQ @SKIP_HEIGHT
	STA LOADED_OVAL_WINDOW_HEIGHT
@SKIP_HEIGHT:
	LDY #.LOWORD(LOADED_OVAL_WINDOW)
	STY @LOCAL03
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDY #oval_window::centre_x_add
	LDA [@VIRTUAL06],Y
	STA LOADED_OVAL_WINDOW_CENTRE_X_ADD
	LDY @LOCAL03
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDY #oval_window::centre_y_add
	LDA [@VIRTUAL06],Y
	STA LOADED_OVAL_WINDOW_CENTRE_Y_ADD
	LDY @LOCAL03
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDY #oval_window::width_velocity
	LDA [@VIRTUAL06],Y
	STA LOADED_OVAL_WINDOW_WIDTH_VELOCITY
	LDY @LOCAL03
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDY #oval_window::height_velocity
	LDA [@VIRTUAL06],Y
	STA LOADED_OVAL_WINDOW_HEIGHT_VELOCITY
	LDY @LOCAL03
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDY #oval_window::width_acceleration
	LDA [@VIRTUAL06],Y
	STA LOADED_OVAL_WINDOW_WIDTH_ACCELERATION
	LDY @LOCAL03
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDY #oval_window::height_acceleration
	LDA [@VIRTUAL06],Y
	STA LOADED_OVAL_WINDOW_HEIGHT_ACCELERATION
	LDY @LOCAL03
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDA #.SIZEOF(oval_window)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA __BSS_START__,Y
	LDA @VIRTUAL06+2
	STA __BSS_START__+2,Y
@APPLY_VELOCITIES:
	LDX #.LOWORD(LOADED_OVAL_WINDOW_CENTRE_X)
	LDA __BSS_START__,X
	CLC
	ADC LOADED_OVAL_WINDOW_CENTRE_X_ADD
	STA __BSS_START__,X
	LDX #.LOWORD(LOADED_OVAL_WINDOW_CENTRE_Y)
	LDA __BSS_START__,X
	CLC
	ADC LOADED_OVAL_WINDOW_CENTRE_Y_ADD
	STA __BSS_START__,X
	LDX #.LOWORD(LOADED_OVAL_WINDOW_WIDTH_VELOCITY)
	LDA __BSS_START__,X
	CLC
	ADC LOADED_OVAL_WINDOW_WIDTH_ACCELERATION
	STA __BSS_START__,X
	LDY #.LOWORD(LOADED_OVAL_WINDOW_HEIGHT_VELOCITY)
	LDA __BSS_START__,Y
	CLC
	ADC LOADED_OVAL_WINDOW_HEIGHT_ACCELERATION
	STA __BSS_START__,Y
	LDA __BSS_START__,X
	STA @LOCAL03
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @ADD_WIDTH_VELOCITY
	LDX #.LOWORD(LOADED_OVAL_WINDOW_WIDTH)
	LDA @LOCAL03
	EOR #$FFFF
	INC
	STA @VIRTUAL02
	LDA __BSS_START__,X
	CMP @VIRTUAL02
	BCS @ADD_WIDTH_VELOCITY
	LDA #0
	STA __BSS_START__,X
	BRA @UPDATE_HEIGHT
@ADD_WIDTH_VELOCITY:
	LDX #.LOWORD(LOADED_OVAL_WINDOW_WIDTH)
	LDA __BSS_START__,X
	CLC
	ADC LOADED_OVAL_WINDOW_WIDTH_VELOCITY
	STA __BSS_START__,X
@UPDATE_HEIGHT:
	LDA LOADED_OVAL_WINDOW_HEIGHT_VELOCITY
	STA @LOCAL03
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @ADD_HEIGHT_VELOCITY
	LDX #.LOWORD(LOADED_OVAL_WINDOW_HEIGHT)
	LDA @LOCAL03
	EOR #$FFFF
	INC
	STA @VIRTUAL02
	LDA __BSS_START__,X
	CMP @VIRTUAL02
	BCS @ADD_HEIGHT_VELOCITY
	LDA #0
	STA __BSS_START__,X
	BRA @CHECK_OVAL_COLLAPSED
@ADD_HEIGHT_VELOCITY:
	LDX #.LOWORD(LOADED_OVAL_WINDOW_HEIGHT)
	LDA __BSS_START__,X
	CLC
	ADC LOADED_OVAL_WINDOW_HEIGHT_VELOCITY
	STA __BSS_START__,X
@CHECK_OVAL_COLLAPSED:
	LDA LOADED_OVAL_WINDOW_WIDTH
	BNE @RENDER_OVAL
	LDA LOADED_OVAL_WINDOW_HEIGHT
	BNE @RENDER_OVAL
	SEP #PROC_FLAGS::ACCUM8
	STZ FRAMES_UNTIL_NEXT_SWIRL_UPDATE
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT_CONSTANT NULL, LOADED_OVAL_WINDOW
	JMP @RETURN
@RENDER_OVAL:
	LDA LOADED_OVAL_WINDOW_HEIGHT
	XBA
	AND #$00FF
	STA @LOCAL00
	LDA LOADED_OVAL_WINDOW_WIDTH
	XBA
	AND #$00FF
	TAY
	LDX LOADED_OVAL_WINDOW_CENTRE_Y
	LDA LOADED_OVAL_WINDOW_CENTRE_X
	JSL GENERATE_OVAL_WINDOW_DATA
	LDX #65
	LDA #3
	JSL SETUP_SWIRL_WINDOW_HDMA
	LDA SWIRL_INVERT_ENABLED
	AND #$00FF
	TAX
	LDA SWIRL_MASK_SETTINGS
	AND #$00FF
	JSL SET_WINDOW_MASK
	JMP @RETURN
@SWIRL_FRAME_UPDATE:
	LDX #.LOWORD(FRAMES_UNTIL_NEXT_SWIRL_UPDATE)
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	DEC
	STA FRAMES_UNTIL_NEXT_SWIRL_UPDATE
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @RETURN
@PROCESS_SWIRL_FRAME:
	LDX #.LOWORD(SWIRL_FRAMES_LEFT)
	STX @LOCAL03
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	AND #$00FF
	BEQL @NO_FRAMES_LEFT
	SEP #PROC_FLAGS::ACCUM8
	LDA FRAMES_UNTIL_NEXT_SWIRL_FRAME
	STA FRAMES_UNTIL_NEXT_SWIRL_UPDATE
	LDY #.LOWORD(SWIRL_HDMA_CHANNEL_OFFSET)
	STY @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,Y
	AND #$00FF
	INC
	INC
	INC
	JSL MASK_HDMA_CHANNEL
	LDY @LOCAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,Y
	INC
	STA __BSS_START__,Y
	AND #$0001
	STA __BSS_START__,Y
	REP #PROC_FLAGS::ACCUM8
	LDA SWIRL_REVERSED
	AND #$00FF
	BNE @REVERSED_SWIRL
	LDX #.LOWORD(SWIRL_HDMA_TABLE_ID)
	STX @LOCAL03
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL01
	REP #PROC_FLAGS::ACCUM8
	LOADPTR SWIRL_DATA & $FF0000, @VIRTUAL06
	LDA @LOCAL01
	AND #$00FF
	ASL
	TAX
	LDA f:SWIRL_POINTER_TABLE,X
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	INC
	LDX @LOCAL03
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA __BSS_START__,Y
	AND #$00FF
	INC
	INC
	INC
	JSL SETUP_HDMA_CHANNEL
	BRA @APPLY_WINDOW_MASK
@REVERSED_SWIRL:
	LDX #.LOWORD(SWIRL_HDMA_TABLE_ID)
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	DEC
	STA @LOCAL01
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LOADPTR SWIRL_DATA & $FF0000, @VIRTUAL06
	LDA @LOCAL01
	AND #$00FF
	ASL
	TAX
	LDA f:SWIRL_POINTER_TABLE,X
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA __BSS_START__,Y
	AND #$00FF
	INC
	INC
	INC
	JSL SETUP_HDMA_CHANNEL
@APPLY_WINDOW_MASK:
	LDA SWIRL_INVERT_ENABLED
	AND #$00FF
	TAX
	LDA SWIRL_MASK_SETTINGS
	AND #$00FF
	JSL SET_WINDOW_MASK
	LDX #.LOWORD(SWIRL_FRAMES_LEFT)
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
	JMP @RETURN
@NO_FRAMES_LEFT:
	.A16
	LDA #.LOWORD(SWIRL_NEXT_SWIRL)
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	AND #$00FF
	BEQL @NO_NEXT_SWIRL
	LDY #.LOWORD(SWIRL_REPEATS_UNTIL_SPEED_UP)
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,Y
	DEC
	STA __BSS_START__,Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQ @SPEED_UP
	LOADPTR SWIRL_PRIMARY_TABLE, @VIRTUAL06
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	AND #$00FF
	ASL
	ASL
	INC
	INC
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL0A]
	LDX @LOCAL03
	STA __BSS_START__,X
	LDY #.LOWORD(SWIRL_HDMA_TABLE_ID)
	LDX @VIRTUAL02
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	AND #$00FF
	ASL
	ASL
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	STA @LOCAL01
	STA __BSS_START__,Y
	REP #PROC_FLAGS::ACCUM8
	LDA SWIRL_REVERSED
	AND #$00FF
	BEQL @PROCESS_SWIRL_FRAME
	LDX @LOCAL03
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @VIRTUAL00
	LDA @LOCAL01
	CLC
	ADC @VIRTUAL00
	STA __BSS_START__,Y
	JMP @PROCESS_SWIRL_FRAME
@SPEED_UP:
	LDX #.LOWORD(SWIRL_REPEAT_SPEED)
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	INC
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	CMP #1
	BEQ @SPEED_LEVEL_1
	CMP #2
	BEQ @SPEED_LEVEL_2
	CMP #3
	BEQ @SPEED_LEVEL_3
	BRA @AFTER_SPEED_SET
@SPEED_LEVEL_1:
	SEP #PROC_FLAGS::ACCUM8
	LDA #4
	STA __BSS_START__,Y
	LDA #3
	STA FRAMES_UNTIL_NEXT_SWIRL_FRAME
	BRA @AFTER_SPEED_SET
@SPEED_LEVEL_2:
	SEP #PROC_FLAGS::ACCUM8
	LDA #6
	STA __BSS_START__,Y
	LDA #2
	STA FRAMES_UNTIL_NEXT_SWIRL_FRAME
	BRA @AFTER_SPEED_SET
@SPEED_LEVEL_3:
	SEP #PROC_FLAGS::ACCUM8
	LDA #12
	STA __BSS_START__,Y
	LDA #1
	STA FRAMES_UNTIL_NEXT_SWIRL_FRAME
@AFTER_SPEED_SET:
	REP #PROC_FLAGS::ACCUM8
	LDA SWIRL_REPEATS_UNTIL_SPEED_UP
	AND #$00FF
	BNEL @PROCESS_SWIRL_FRAME
@NO_NEXT_SWIRL:
	LDX #.LOWORD(SWIRL_LENGTH_PADDING)
	LDA __BSS_START__,X
	AND #$00FF
	BEQ @CHECK_AUTO_RESTORE
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA FRAMES_UNTIL_NEXT_SWIRL_UPDATE
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
	BRA @RETURN
@CHECK_AUTO_RESTORE:
	.A16
	LDA SWIRL_AUTO_RESTORE
	AND #$00FF
	BEQ @RETURN
	LDA SWIRL_HDMA_CHANNEL_OFFSET
	AND #$00FF
	INC
	INC
	INC
	JSL MASK_HDMA_CHANNEL
	LDX #0
	TXA
	JSL SET_WINDOW_MASK
	JSL RESTORE_BG_PALETTE_BACKUPS
	LDY #0
	TYX
	TYA
	JSL SET_COLDATA
	LDA CURRENT_LAYER_CONFIG
	JSL SET_COLOR_MATH_FROM_TABLE
@RETURN:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
