
UPDATE_TRANSITION_SCROLL:
	LDA TRANSITION_X_VELOCITY_FRAC
	CLC
	ADC TRANSITION_X_POSITION_FRAC
	STA TRANSITION_X_POSITION_FRAC
	LDA TRANSITION_BACKGROUND_X_VELOCITY
	ADC TRANSITION_BACKGROUND_X
	STA TRANSITION_BACKGROUND_X
	STA BG1_X_POS
	STA BG2_X_POS
	LDA TRANSITION_Y_VELOCITY_FRAC
	CLC
	ADC TRANSITION_Y_POSITION_FRAC
	STA TRANSITION_Y_POSITION_FRAC
	LDA TRANSITION_BACKGROUND_Y_VELOCITY
	ADC TRANSITION_BACKGROUND_Y
	STA TRANSITION_BACKGROUND_Y
	STA BG1_Y_POS
	STA BG2_Y_POS
	LDA BG1_X_POS
	LDX BG1_Y_POS
	JSL SCROLL_MAP_TO_POSITION
	RTL
