
UPDATE_BUBBLE_MONKEY_MODE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL01
	LDA BUBBLE_MONKEY_MODE
	CMP #3
	BEQ @RETURNING_OR_DISTRACTED
	LDA BUBBLE_MONKEY_MODE
	CMP #1
	BNE @CHECK_DISTANCE
@RETURNING_OR_DISTRACTED:
	LDA #2
	STA BUBBLE_MONKEY_MODE
	BRA @SET_TIMER
@CHECK_DISTANCE:
	LDA @LOCAL01
	JSL GET_DISTANCE_TO_PARTY_MEMBER
	CMP #40
	BLTEQ @SET_RANDOM_MODE
	LDA #2
	STA BUBBLE_MONKEY_MODE
	BRA @SET_TIMER
@SET_RANDOM_MODE:
	JSL RAND
	AND #$0003
	TAX
	STX @LOCAL00
	STX BUBBLE_MONKEY_MODE
@SET_TIMER:
	LDX @LOCAL00
	TXA
	AND #$0003
	OPTIMIZED_MULT @VIRTUAL04, 3
	INC
	INC
	INC
	INC
	STA BUBBLE_MONKEY_MOVEMENT_CHANGE_TIMER
	END_C_FUNCTION
