
UPDATE_PARTY_FOLLOWER_MOVEMENT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	STA @LOCAL05
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR1_TABLE,X
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	TAY
	STY CURRENT_PARTY_MEMBER_TICK
	LDA a:char_struct::position_index,Y
	STA @VIRTUAL02
	STA @VIRTUAL04
	STA @LOCAL04
	LDA @VIRTUAL02
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(player_position_buffer_entry)
	CLC
	ADC #.LOWORD(PLAYER_POSITION_BUFFER)
	STA @LOCAL03
	LDA ENTITY_SCRIPT_VAR0_TABLE,X
	STA @LOCAL02
	LDA (@LOCAL03) ;player_position_buffer_entry::x_coord
	STA ENTITY_ABS_X_TABLE,X
	LDY #player_position_buffer_entry::y_coord
	LDA (@LOCAL03),Y
	STA ENTITY_ABS_Y_TABLE,X
	LDY #player_position_buffer_entry::walking_style
	LDA (@LOCAL03),Y
	BEQ @WALKING_STYLE_ZERO
	LDY CURRENT_ENTITY_SLOT
	TAX
	LDA @LOCAL02
	JSL UPDATE_PARTY_ENTITY_GRAPHICS
	LDA #2
	STA @LOCAL00
	LDY @VIRTUAL02
	LDX #30
	LDA @LOCAL02
	JSL ADJUST_PARTY_MEMBER_VISIBILITY
	AND #$00FF
	LDX CURRENT_PARTY_MEMBER_TICK
	STA a:char_struct::position_index,X
	JMP @DONE
@WALKING_STYLE_ZERO:
	LDA BUBBLE_MONKEY_MODE
	BEQ @ADJUST_VISIBILITY
	CMP #2
	BEQ @ADJUST_VISIBILITY
	CMP #1
	BEQL @HIDE_MODE
	CMP #3
	BEQL @DISTRACTED_MODE
	JMP @UPDATE_TIMER
@ADJUST_VISIBILITY:
	LDA #2
	STA @LOCAL00
	LDY @VIRTUAL02
	LDX #12
	LDA @LOCAL02
	JSL ADJUST_PARTY_MEMBER_VISIBILITY
	STA @VIRTUAL02
	AND #$00FF
	LDX CURRENT_PARTY_MEMBER_TICK
	STA a:char_struct::position_index,X
	LDA @LOCAL04
	STA @VIRTUAL04
	CMP @VIRTUAL02
	BEQ @POSITION_CLOSE
	LDA @VIRTUAL04
	INC
	CMP @VIRTUAL02
	BNE @POSITION_CHANGED
@POSITION_CLOSE:
	LDY CURRENT_ENTITY_SLOT
	STY @LOCAL01
	LDY #player_position_buffer_entry::walking_style
	LDA (@LOCAL03),Y
	TAX
	LDA @LOCAL02
	LDY @LOCAL01
	JSL UPDATE_PARTY_ENTITY_GRAPHICS
	LDA GAME_STATE + game_state::leader_moved
	BEQL @UPDATE_TIMER
	BRA @UPDATE_DIRECTION
@POSITION_CHANGED:
	LDY CURRENT_ENTITY_SLOT
	LDX #14
	LDA @LOCAL02
	JSL UPDATE_PARTY_ENTITY_GRAPHICS
@UPDATE_DIRECTION:
	LDA @LOCAL05
	ASL
	STA @LOCAL04
	TAX
	LDY #player_position_buffer_entry::direction
	LDA (@LOCAL03),Y
	STA ENTITY_DIRECTIONS,X
	LDA @LOCAL04
	CLC
	ADC #.LOWORD(ENTITY_SCRIPT_VAR7_TABLE)
	TAX
	LDA __BSS_START__,X
	AND #$1FFF
	STA __BSS_START__,X
	BRA @UPDATE_TIMER
@HIDE_MODE:
	TXA
	CLC
	ADC #.LOWORD(ENTITY_SCRIPT_VAR7_TABLE)
	TAX
	LDA __BSS_START__,X
	ORA #$7000
	STA __BSS_START__,X
	BRA @UPDATE_TIMER
@DISTRACTED_MODE:
	TXA
	CLC
	ADC #.LOWORD(ENTITY_SCRIPT_VAR7_TABLE)
	TAX
	LDA __BSS_START__,X
	ORA #SPRITE_TABLE_10_FLAGS::STATIC_POSE | SPRITE_TABLE_10_FLAGS::FORCE_STATIC_ANIM | SPRITE_TABLE_10_FLAGS::SPACING_HIDE
	STA __BSS_START__,X
	LDX #.LOWORD(BUBBLE_MONKEY_DISTRACTED_NEXT_DIRECTION_CHANGE_TIME)
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
	BNE @UPDATE_TIMER
	LDY #.LOWORD(BUBBLE_MONKEY_DISTRACTED_DIRECTION_CHANGES_LEFT)
	LDA __BSS_START__,Y
	DEC
	STA __BSS_START__,Y
	BNE @RANDOMIZE_DIRECTION
	LDA #15
	STA BUBBLE_MONKEY_MOVEMENT_CHANGE_TIMER
	LDA #.LOWORD(-1)
	STA __BSS_START__,X
@RANDOMIZE_DIRECTION:
	JSL RAND
	ASL
	ASL
	AND #$000F
	INC
	INC
	INC
	INC
	STA BUBBLE_MONKEY_DISTRACTED_NEXT_DIRECTION_CHANGE_TIME
	LDA BUBBLE_MONKEY_DISTRACTED_NEXT_DIRECTION
	EOR #$0004
	STA @LOCAL04
	STA BUBBLE_MONKEY_DISTRACTED_NEXT_DIRECTION
	LDA @LOCAL05
	ASL
	TAX
	LDA @LOCAL04
	STA ENTITY_DIRECTIONS,X
@UPDATE_TIMER:
	LDA @LOCAL05
	ASL
	TAX
	LDA #4
	STA ENTITY_SCRIPT_VAR3_TABLE,X
	LDX BUBBLE_MONKEY_MOVEMENT_CHANGE_TIMER
	DEX
	STX BUBBLE_MONKEY_MOVEMENT_CHANGE_TIMER
	BNE @UPDATE_SURFACE_FLAGS
	LDA @LOCAL02
	JSR UPDATE_BUBBLE_MONKEY_MODE
	LDA BUBBLE_MONKEY_MODE
	CMP #3
	BNE @SET_NORMAL_TIMER
	LDA #4
	STA BUBBLE_MONKEY_DISTRACTED_DIRECTION_CHANGES_LEFT
	LDA #6
	STA BUBBLE_MONKEY_DISTRACTED_NEXT_DIRECTION
	LDA #15
	STA BUBBLE_MONKEY_DISTRACTED_NEXT_DIRECTION_CHANGE_TIME
	LDA #.LOWORD(-1)
	STA BUBBLE_MONKEY_MOVEMENT_CHANGE_TIMER
	BRA @UPDATE_SURFACE_FLAGS
@SET_NORMAL_TIMER:
	LDA #60
	STA BUBBLE_MONKEY_MOVEMENT_CHANGE_TIMER
@UPDATE_SURFACE_FLAGS:
	LDA @LOCAL05
	ASL
	TAX
	LDY #player_position_buffer_entry::tile_flags
	LDA (@LOCAL03),Y
	STA ENTITY_SURFACE_FLAGS,X
@DONE:
	END_C_FUNCTION
