
DO_BATTLEBG_DMA:
	PHY
	TAY
	LDA f:DMA_TARGET_REGISTERS,X
	PHA
	TYA
	ASL
	ASL
	ASL
	ASL
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #^__BSS_START__
	STA f:A1B0,X
	STA f:DASB0,X
	PLA
	STA f:BBAD0,X
	PLA
	LDA #$42
	STA f:DMAP0,X
	REP #PROC_FLAGS::ACCUM8
	PLA
	PHX
	BNE @SETUP_LAYER2
	LDX #$0006
@COPY_LAYER1_TABLE:
	LDA f:BATTLEBG_LAYER1_HDMA_TABLE,X
	STA ANIMATED_BACKGROUND_LAYER_1_HDMA_TABLE,X
	DEX
	DEX
	BPL @COPY_LAYER1_TABLE
	LDA #.LOWORD(ANIMATED_BACKGROUND_LAYER_1_HDMA_TABLE)
	BRA @SET_HDMA_SOURCE
@SETUP_LAYER2:
	LDX #6
@COPY_LAYER2_TABLE:
	LDA f:BATTLEBG_LAYER2_HDMA_TABLE,X
	STA ANIMATED_BACKGROUND_LAYER_2_HDMA_TABLE,X
	DEX
	DEX
	BPL @COPY_LAYER2_TABLE
	LDA #.LOWORD(ANIMATED_BACKGROUND_LAYER_2_HDMA_TABLE)
@SET_HDMA_SOURCE:
	PLX
	STA f:A1T0L,X
	SEP #PROC_FLAGS::ACCUM8
	TYX
	LDA HDMAEN_MIRROR
	ORA f:DMA_FLAGS,X
	STA HDMAEN_MIRROR
	REP #PROC_FLAGS::ACCUM8
	RTL
