
ADD_PARTY_MEMBER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TAY
	STY @LOCAL06
	LDX #0
	STX @LOCAL05
	CPY #5
	BCC @FIND_SLOT_LOW
@FIND_SLOT_HIGH:
	LDA GAME_STATE + game_state::party_order,X
	AND #$00FF
	BEQ @INSERT_POINT_FOUND
	AND #$00FF
	STA @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BLTEQ @INSERT_POINT_FOUND
	INX
	STX @LOCAL05
	BRA @FIND_SLOT_HIGH
@FIND_SLOT_LOW:
	LDA GAME_STATE + game_state::party_order,X
	AND #$00FF
	BEQ @INSERT_POINT_FOUND
	AND #$00FF
	STA @LOCAL04
	STA @VIRTUAL02
	LDA #5
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @INSERT_POINT_FOUND
	LDY @LOCAL06
	STY @VIRTUAL02
	LDA @LOCAL04
	CMP @VIRTUAL02
	BGT @INSERT_POINT_FOUND
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR1_TABLE,X
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::afflictions,X
	AND #$00FF
	CMP #1
	BEQ @INSERT_POINT_FOUND
	LDX @LOCAL05
	INX
	STX @LOCAL05
	BRA @FIND_SLOT_LOW
@INSERT_POINT_FOUND:
	LDX @LOCAL05
	LDA GAME_STATE + game_state::party_order,X
	AND #$00FF
	BEQ @STORE_NEW_MEMBER
	LDA #5
	STA @LOCAL03
	BRA @SHIFT_LOOP_CHECK
@SHIFT_ENTRY:
	CLC
	ADC #.LOWORD(GAME_STATE)
	STA @LOCAL02
	LDA @LOCAL03
	DEC
	STA @VIRTUAL04
	CLC
	ADC #.LOWORD(GAME_STATE)
	STA @VIRTUAL02
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__ + game_state::party_order,X
	LDY #game_state::party_order
	STA (@LOCAL02),Y
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	ASL
	PHA
	LDA @VIRTUAL04
	ASL
	TAX
	LDA GAME_STATE + game_state::party_entity_slots,X
	PLX
	STA GAME_STATE + game_state::party_entity_slots,X
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__+game_state::player_controlled_party_members,X
	LDY #game_state::player_controlled_party_members
	STA (@LOCAL02),Y
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	STA @LOCAL03
@SHIFT_LOOP_CHECK:
	LDX @LOCAL05
	TXA
	DEC
	STA @VIRTUAL02
	LDA @LOCAL03
	CMP @VIRTUAL02
	BNE @SHIFT_ENTRY
@STORE_NEW_MEMBER:
	LDY @LOCAL06
	TYA
	SEP #PROC_FLAGS::ACCUM8
	STA GAME_STATE + game_state::party_order,X
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(GAME_STATE) + game_state::party_count
	PHA
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	INC
	PLX
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	TYA
	DEC
	STA @LOCAL02
	STA NEW_ENTITY_VAR0
	LDA @LOCAL02
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(character_initial_entity_entry)
	CLC
	ADC #character_initial_entity_entry::unknown6
	TAX
	LDA f:CHARACTER_INITIAL_ENTITY_DATA,X
	STA @LOCAL06
	ASL
	TAX
	LDA ENTITY_SCRIPT_TABLE,X
	CMP #.LOWORD(-1)
	BEQ @ENTITY_SLOT_VALID
	INC @LOCAL06
@ENTITY_SLOT_VALID:
	LDX @LOCAL05
	TXA
	ASL
	TAX
	LDA @LOCAL06
	STA GAME_STATE + game_state::party_entity_slots,X
	LDA @LOCAL06
	STA NEW_ENTITY_VAR1
	SEC
	SBC #24
	STA NEW_ENTITY_VAR1
	SEP #PROC_FLAGS::ACCUM8
	LDA NEW_ENTITY_VAR1
	LDX @LOCAL05
	STA GAME_STATE+game_state::player_controlled_party_members,X
	REP #PROC_FLAGS::ACCUM8
	LDA GAME_STATE+game_state::party_count
	AND #$00FF
	CMP #1
	BNE @NOT_FIRST_MEMBER
	LDA NEW_ENTITY_VAR1
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA GAME_STATE + game_state::unknown88
	STA PARTY_CHARACTERS+char_struct::position_index,X
	BRA @AFTER_POSITION_INDEX
@NOT_FIRST_MEMBER:
	CPX #0
	BNE @GET_PREV_POSITION
	LDA GAME_STATE + game_state::unknown88
	STA @LOCAL04
	BRA @SET_POSITION_INDEX
@GET_PREV_POSITION:
	TXA
	DEC
	ASL
	TAX
	LDA GAME_STATE + game_state::party_entity_slots,X
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR1_TABLE,X
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::position_index,X
	STA @LOCAL04
@SET_POSITION_INDEX:
	LDA NEW_ENTITY_VAR1
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA @LOCAL04
	STA PARTY_CHARACTERS+char_struct::position_index,X
@AFTER_POSITION_INDEX:
	LDA NEW_ENTITY_VAR1
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::position_index,X
	BEQ @POSITION_ZERO
	TAX
	DEX
	BRA @AFTER_POSITION_WRAP
@POSITION_ZERO:
	LDX #$00FF
@AFTER_POSITION_WRAP:
	TXA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(player_position_buffer_entry)
	TAX
	LDA PLAYER_POSITION_BUFFER + player_position_buffer_entry::x_coord,X
	STA @VIRTUAL04
	LDA PLAYER_POSITION_BUFFER + player_position_buffer_entry::y_coord,X
	STA @VIRTUAL02
	LDA GAME_STATE + game_state::character_mode
	CMP #3
	BEQ @SMALL_MODE_SPRITE
	LDA @LOCAL02
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(character_initial_entity_entry)
	TAX
	LDA f:CHARACTER_INITIAL_ENTITY_DATA,X ;character_initial_entity_entry::overworld_sprite
	STA @LOCAL05
	BRA @AFTER_SPRITE_SELECT
@SMALL_MODE_SPRITE:
	LDA @LOCAL02
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(character_initial_entity_entry)
	TAX
	INX
	INX
	LDA f:CHARACTER_INITIAL_ENTITY_DATA,X ;character_initial_entity_entry::lost_underworld_sprite
	STA @LOCAL05
@AFTER_SPRITE_SELECT:
	LOADPTR CHARACTER_INITIAL_ENTITY_DATA, @VIRTUAL06
	LDA @VIRTUAL04
	STA @LOCAL00
	LDA @VIRTUAL02
	STA @LOCAL01
	LDY @LOCAL06
	LDA @LOCAL02
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(character_initial_entity_entry)
	INC
	INC
	INC
	INC
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A] ;character_initial_entity_entry::actionscript_id
	TAX
	LDA @LOCAL05
	JSL CREATE_ENTITY
	LDA @LOCAL06
	ASL
	TAX
	STX @LOCAL03
	LDA @VIRTUAL04
	SEC
	SBC BG1_X_POS
	STA ENTITY_SCREEN_X_TABLE,X
	LDA @VIRTUAL02
	SEC
	SBC BG1_Y_POS
	STA ENTITY_SCREEN_Y_TABLE,X
	LDY #.LOWORD(GAME_STATE) + game_state::current_party_members
	STY @LOCAL05
	LDA GAME_STATE + game_state::party_order
	AND #$00FF
	DEC
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(character_initial_entity_entry)
	CLC
	ADC #character_initial_entity_entry::unknown6
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	STA __BSS_START__,Y
	JSL REBUILD_ENTITY_FREE_LIST
	JSL UPDATE_NPC_PARTY_LINEUP
	LDA GAME_STATE + game_state::party_entity_slots
	LDY @LOCAL05
	STA __BSS_START__,Y
	JSL UPDATE_PARTY
	LDA @VIRTUAL04
	STA ENTITY_PREPARED_X_COORDINATE
	LDA @VIRTUAL02
	STA ENTITY_PREPARED_Y_COORDINATE
	LDX @LOCAL03
	LDA ENTITY_DIRECTIONS,X
	STA ENTITY_PREPARED_DIRECTION
	LDA @LOCAL06
	END_C_FUNCTION
