
ALLOCATE_ENTITY_SLOT:
	LDA LAST_ALLOCATED_SCRIPT
	BMI @FAIL
	LDY #.LOWORD(-1)
	LDA LAST_ENTITY
	BMI @FAIL
@SEARCH_LOOP:
	TAX
	CPX ENTITY_ALLOCATION_MIN_SLOT
	BCC @ADVANCE
	CPX ENTITY_ALLOCATION_MAX_SLOT
	BCC @FOUND
@ADVANCE:
	TXY
	LDA ENTITY_NEXT_ENTITY_TABLE,X
	BPL @SEARCH_LOOP
@FAIL:
	SEC
	RTS
@FOUND:
	TYA
	BPL @UNLINK_MIDDLE
	LDA ENTITY_NEXT_ENTITY_TABLE,X
	STA LAST_ENTITY
	CLC
	RTS
@UNLINK_MIDDLE:
	LDA ENTITY_NEXT_ENTITY_TABLE,X
	STA ENTITY_NEXT_ENTITY_TABLE,Y
	CLC
	RTS
