
APPLY_POSSESSION_OVERLAY_FLAG:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL00
	TXA
	AND #$0080
	BEQ @NOT_POSSESSED
	LDA @LOCAL00
	ASL
	CLC
	ADC #.LOWORD(ENTITY_OVERLAY_FLAGS)
	TAX
	LDA __BSS_START__,X
	ORA #$4000
	STA __BSS_START__,X
@NOT_POSSESSED:
	END_C_FUNCTION
