
ATTEMPT_ENEMY_SPAWN:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL0E
	STX @LOCAL0D
	STA @LOCAL0C
	LDA DEBUG
	BEQ @CHECK_SPAWN_COUNTER
	JSL CHECK_DEBUG_ENEMIES_ENABLED
	CMP #0
	BEQ @CHECK_SPAWN_COUNTER
	JSL RAND
	CMP #16
	BCS @CHECK_SPAWN_COUNTER
	STZ @LOCAL0B
	LOADPTR ENEMY_BATTLE_GROUPS_TABLE, @VIRTUAL0A
	JMP @READ_GROUP_ENTRY_COUNT
@CHECK_SPAWN_COUNTER:
	LDA ENEMY_SPAWN_COUNTER
	INC
	STA ENEMY_SPAWN_COUNTER
	AND #$000F
	BNEL @SELECT_ENEMY_GROUP
	LDA @LOCAL0C
	OPTIMIZED_MULT @VIRTUAL04, 8
	LSR
	LSR
	LSR
	LSR
	LSR
	ASL
	STA @VIRTUAL04
	LDA @LOCAL0D
	OPTIMIZED_MULT @VIRTUAL04, 8
	LSR
	LSR
	LSR
	LSR
	OPTIMIZED_MULT @VIRTUAL04, 64
	CLC
	ADC @VIRTUAL04
	TAX
	LDA f:MAP_DATA_PER_SECTOR_ATTRIBUTES_TABLE,X
	AND #$0007
	BEQ @RATE_CASE_0
	CMP #1
	BEQ @RATE_CASE_1
	CMP #2
	BEQ @RATE_CASE_2
	CMP #3
	BEQ @RATE_CASE_3
	CMP #4
	BEQ @RATE_CASE_4
	CMP #5
	BEQ @RATE_CASE_5
	BRA @ROLL_SPAWN_CHANCE
@RATE_CASE_0:
	LDA #2
	STA @VIRTUAL02
	STA @LOCAL0A
	BRA @ROLL_SPAWN_CHANCE
@RATE_CASE_1:
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL0A
	BRA @ROLL_SPAWN_CHANCE
@RATE_CASE_2:
	LDA #1
	STA @VIRTUAL02
	STA @LOCAL0A
	BRA @ROLL_SPAWN_CHANCE
@RATE_CASE_3:
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL0A
	BRA @ROLL_SPAWN_CHANCE
@RATE_CASE_4:
	LDA #5
	STA @VIRTUAL02
	STA @LOCAL0A
	BRA @ROLL_SPAWN_CHANCE
@RATE_CASE_5:
	LDA #1
	STA @VIRTUAL02
	STA @LOCAL0A
@ROLL_SPAWN_CHANCE:
	JSL RAND
	LDX @LOCAL0A
	STX @VIRTUAL02
	LDY #100
	JSL MODULUS16
	CMP @VIRTUAL02
	BCC @SPAWN_MAGIC_BUTTERFLY
	JMP @RETURN
@SPAWN_MAGIC_BUTTERFLY:
	LDA #MAGIC_BUTTERFLY_BATTLEGROUP
	STA @LOCAL0B
	STA SPAWNING_ENEMY_GROUP
	MOVE_INT f:BTL_ENTRY_PTR_TABLE +.SIZEOF(battle_entry_ptr_entry) * MAGIC_BUTTERFLY_BATTLEGROUP + battle_entry_ptr_entry::pointer, @VIRTUAL0A
	JMP @READ_GROUP_ENTRY_COUNT
@SELECT_ENEMY_GROUP:
	LDY @LOCAL0E
	BEQL @RETURN
	LDA @LOCAL0C
	OPTIMIZED_MULT @VIRTUAL04, 8
	LSR
	LSR
	LSR
	LSR
	LSR
	STA @VIRTUAL02
	LDA @LOCAL0D
	OPTIMIZED_MULT @VIRTUAL04, 8
	LSR
	LSR
	LSR
	LSR
	OPTIMIZED_MULT @VIRTUAL04, 32
	CLC
	ADC @VIRTUAL02
	TAX
	LDA f:GLOBAL_MAP_TILESETPALETTE_DATA,X
	AND #$00FF
	LSR
	LSR
	LSR
	CMP LOADED_MAP_TILE_COMBO
	BNEL @RETURN
	STY ENEMY_SPAWN_ENCOUNTER_ID
	LOADPTR ENEMY_PLACEMENT_GROUPS_PTR_TABLE, @VIRTUAL06
	TYA
	ASL
	ASL
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	LDA [@VIRTUAL06]
	STA @LOCAL09
	LDA #enemy_placement::groups
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL08
	LDA @VIRTUAL06+2
	STA @LOCAL08+2
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	INC @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL07
	LDA [@LOCAL07] ;enemy_placement::spawn_chance
	AND #$00FF
	STA ENEMY_SPAWN_CHANCE
	LDX #0
	STX @LOCAL06
	LDA @LOCAL09
	BEQ @CHECK_PIRACY_FLAG
	JSL GET_EVENT_FLAG
	CMP #0
	BEQ @CHECK_PIRACY_FLAG
	SEP #PROC_FLAGS::ACCUM8
	LDY #enemy_placement::spawn_chance_alt
	LDA [@VIRTUAL0A],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA ENEMY_SPAWN_CHANCE
	LDA [@LOCAL07]
	AND #$00FF
	BEQ @CHECK_PIRACY_FLAG
	LDX #8
	STX @LOCAL06
@CHECK_PIRACY_FLAG:
	LDY ENEMY_SPAWN_CHANCE
	STY @LOCAL09
	LDA PIRACY_FLAG
	BNE @PICK_RANDOM_SLOT
	JSL RAND
	LDY @LOCAL09
	STY @VIRTUAL02
	LDY #100
	JSL MULT168
	XBA
	AND #$00FF
	CMP @VIRTUAL02
	BCC @PICK_RANDOM_SLOT
	JMP @RETURN
@PICK_RANDOM_SLOT:
	JSL RAND
	AND #$0007
	STA @VIRTUAL02
	LDX @LOCAL06
	TXA
	CLC
	ADC @VIRTUAL02
	STA @LOCAL05
	LDX #0
@FIND_GROUP_FOR_SLOT:
	MOVE_INT @LOCAL08, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	LDA [@VIRTUAL0A] ;enemy_group::slots
	AND #$00FF
	STA @VIRTUAL02
	TXA
	CLC
	ADC @VIRTUAL02
	TAX
	STX @VIRTUAL02
	LDA @LOCAL05
	CMP @VIRTUAL02
	BCC @GROUP_FOUND
	LDA #.SIZEOF(enemy_group)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL08
	LDA @VIRTUAL06+2
	STA @LOCAL08+2
	BRA @FIND_GROUP_FOR_SLOT
@GROUP_FOUND:
	LDY #enemy_group::group
	LDA [@VIRTUAL06],Y
	STA @LOCAL0B
	STA SPAWNING_ENEMY_GROUP
	LOADPTR BTL_ENTRY_PTR_TABLE, @VIRTUAL06
	LDA @LOCAL0B
	OPTIMIZED_MULT @VIRTUAL04, 8
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL0A
	LDA @LOCAL0D
	OPTIMIZED_MULT @VIRTUAL04, 128
	CLC
	ADC @LOCAL0C
	STA @LOCAL06
	LDY #0
	BRA @CHECK_ENTITY_INDEX
@CHECK_EXISTING_ENTITY:
	TYA
	ASL
	TAX
	LDA ENTITY_SCRIPT_TABLE,X
	CMP #.LOWORD(-1)
	BEQ @NEXT_ENTITY
	LDA @LOCAL0B
	CLC
	ADC #$8000
	CMP ENTITY_NPC_IDS,X
	BNE @NEXT_ENTITY
	LDA @LOCAL06
	CMP ENTITY_ENEMY_SPAWN_TILES,X
	BEQL @RETURN
@NEXT_ENTITY:
	INY
@CHECK_ENTITY_INDEX:
	CPY #23
	BNE @CHECK_EXISTING_ENTITY
	JMP @READ_GROUP_ENTRY_COUNT
@LOAD_ENEMY_CONFIG:
	LDY #battle_group_entry::id
	LDA [@VIRTUAL0A],Y
	STA @LOCAL04
	LOADPTR ENEMY_CONFIGURATION_TABLE, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL08
	LDA @LOCAL04
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	STA @LOCAL03
.IF .DEFINED(USA)
	INC
.ENDIF
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	STA SPAWNING_ENEMY_NAME
	LDA @LOCAL03
	CLC
	ADC #enemy_data::overworld_sprite
	MOVE_INTX @LOCAL08, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	STA @LOCAL09
	STA SPAWNING_ENEMY_SPRITE
	LDA @LOCAL03
	CLC
	ADC #enemy_data::event_script
	MOVE_INTX @LOCAL08, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	STA @LOCAL03
	BNEL @NEXT_ENEMY
	LDA #DEFAULT_ENEMY_MOVEMENT_STYLE
	STA @LOCAL03
	JMP @NEXT_ENEMY
@CHECK_BUTTERFLY_ALREADY_SPAWNED:
	LDA @LOCAL04
	CMP #ENEMY::MAGIC_BUTTERFLY
	BNE @CHECK_ENEMY_COUNT_LIMIT
	LDA MAGIC_BUTTERFLY_SPAWNED
	BNEL @NEXT_ENEMY
@CHECK_ENEMY_COUNT_LIMIT:
	LDA OVERWORLD_ENEMY_COUNT
	CMP OVERWORLD_ENEMY_MAXIMUM
	BNE @CREATE_ENEMY_ENTITY
	INC ENEMY_SPAWN_TOO_MANY_ENEMIES_FAILURE_COUNT
	JMP @NEXT_ENEMY
@CREATE_ENEMY_ENTITY:
	STZ ENEMY_SPAWN_TOO_MANY_ENEMIES_FAILURE_COUNT
	STZ_BADOPT @LOCAL00
.IF .DEFINED(USA)
	STZ @LOCAL00+2
.ELSE
	STA @LOCAL00+2
.ENDIF
	LDY #.LOWORD(-1)
	LDX @LOCAL03
	LDA @LOCAL09
	JSL CREATE_ENTITY
	STA @LOCAL02
	STZ @LOCAL06
	BRA @CHECK_POSITION_ATTEMPTS
@TRY_RANDOM_POSITION:
	JSL RAND
	LDY ENEMY_SPAWN_RANGE_WIDTH
	JSL MODULUS16
	STA @VIRTUAL02
	LDA @LOCAL0C
	OPTIMIZED_MULT @VIRTUAL04, 8
	CLC
	ADC @VIRTUAL02
	OPTIMIZED_MULT @VIRTUAL04, 8
	STA @VIRTUAL04
	JSL RAND
	LDY ENEMY_SPAWN_RANGE_HEIGHT
	JSL MODULUS16
	STA @VIRTUAL02
	LDA @LOCAL0D
	OPTIMIZED_MULT @VIRTUAL04, 8
	CLC
	ADC @VIRTUAL02
	OPTIMIZED_MULT @VIRTUAL04, 8
	STA @VIRTUAL02
	LDY @LOCAL02
	LDX @VIRTUAL02
	LDA @VIRTUAL04
	JSL LOOKUP_SURFACE_FLAGS
	STA @LOCAL01
	AND #$00D0
	BNE @POSITION_INVALID
	LDY @LOCAL04
	LDX @LOCAL02
	LDA @LOCAL01
	JSL CAN_ENEMY_RUN_IN_DIRECTION
	CMP #0
	BEQ @POSITION_VALID
@POSITION_INVALID:
	INC @LOCAL06
@CHECK_POSITION_ATTEMPTS:
	LDA @LOCAL06
	CMP #20
	BNE @TRY_RANDOM_POSITION
	LDA @LOCAL02
	JSL REMOVE_ENTITY
	BRA @NEXT_ENEMY
@POSITION_VALID:
	LDA @LOCAL02
	ASL
	TAX
	STX @LOCAL06
	LDA @VIRTUAL04
	STA ENTITY_ABS_X_TABLE,X
	LDA @VIRTUAL02
	STA ENTITY_ABS_Y_TABLE,X
	LDA @LOCAL0B
	CLC
	ADC #$8000
	STA ENTITY_NPC_IDS,X
	LDA @LOCAL04
	STA ENTITY_ENEMY_IDS,X
	LDA @LOCAL0D
	OPTIMIZED_MULT @VIRTUAL04, 128
	CLC
	ADC @LOCAL0C
	STA ENTITY_ENEMY_SPAWN_TILES,X
	STZ ENTITY_PATHFINDING_STATES,X
	JSL RAND
	LDX @LOCAL06
	STA ENTITY_WEAK_ENEMY_VALUE,X
	INC OVERWORLD_ENEMY_COUNT
	LDA @LOCAL04
	CMP #ENEMY::MAGIC_BUTTERFLY
	BNE @NEXT_ENEMY
	LDA #1
	STA MAGIC_BUTTERFLY_SPAWNED
@NEXT_ENEMY:
	LDX ENEMY_SPAWN_REMAINING_ENEMY_COUNT
	DEC ENEMY_SPAWN_REMAINING_ENEMY_COUNT
	CPX #0
	BNEL @CHECK_BUTTERFLY_ALREADY_SPAWNED
	LDA #3
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
@READ_GROUP_ENTRY_COUNT:
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	LDA [@VIRTUAL06] ;battle_group_entry::count
	AND #$00FF
	TAX
	STX ENEMY_SPAWN_REMAINING_ENEMY_COUNT
	CPX #>-1
	BNEL @LOAD_ENEMY_CONFIG
@RETURN:
	END_C_FUNCTION
