
ATTEMPT_HOMESICKNESS:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA PARTY_CHARACTERS+char_struct::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BEQ @FAILED
	LDX #0
	LDA #15
	STA @LOCAL00
	BRA @LEVEL_LOOP_CHECK
@CHECK_BRACKET:
	LDA @LOCAL00
	STA @VIRTUAL02
	LDA PARTY_CHARACTERS+char_struct::level
	AND #$00FF
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @NEXT_BRACKET
	LDA f:HOMESICKNESS_PROBABILITY,X
	AND #$00FF
	BEQ @NOT_HOMESICK
	AND #$00FF
	JSL RAND_MOD
	CMP #0
	BNE @NOT_HOMESICK
	LDY #STATUS_5::HOMESICK + 1
	LDX #STATUS_GROUP::HOMESICKNESS + 1
	LDA #PARTY_MEMBER::NESS
	JSL INFLICT_STATUS_NONBATTLE
	BRA @RETURN
@NOT_HOMESICK:
	LDA #0
	BRA @RETURN
@NEXT_BRACKET:
	INX
	LDA @LOCAL00
	CLC
	ADC #15
	STA @LOCAL00
@LEVEL_LOOP_CHECK:
	STX @VIRTUAL02
	LDA #100 / 15
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @CHECK_BRACKET
@FAILED:
	LDA #0
@RETURN:
	END_C_FUNCTION
