
BATTLE_SWIRL_SEQUENCE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16 "SWIRL_MUSIC"
	STACK_RESERVE_INT16 "SWIRL_BLUE"
	STACK_RESERVE_INT16 "SWIRL_RED"
	STACK_RESERVE_INT16
	END_STACK_VARS
	@SWIRL_GREEN := @VIRTUAL04
	LDA #$0001
	STA $16
	LDA #$0004
	STA @SWIRL_RED
	STA @SWIRL_GREEN
	LDY #$0000
	STY @SWIRL_BLUE
	LDA BATTLE_INITIATIVE
	BEQ @INITIATIVE_NORMAL
	CMP #INITIATIVE::PARTY_FIRST
	BEQ @INITIATIVE_PARTY_FIRST
	CMP #INITIATIVE::ENEMIES_FIRST
	BEQ @INITIATIVE_ENEMIES_FIRST
	BRA @CHECK_BOSS
@INITIATIVE_NORMAL:
	LDX #MUSIC::BATTLE_SWIRL4
	STX @SWIRL_MUSIC
	LDA #$000E
	STA $02
	STA $0E
	BRA @CHECK_BOSS
@INITIATIVE_PARTY_FIRST:
	LDX #MUSIC::BATTLE_SWIRL4
	STX @SWIRL_MUSIC
	LDA #$001C
	STA @SWIRL_RED
	LDA #$0005
	STA @SWIRL_GREEN
	LDY #$000C
	STY @SWIRL_BLUE
	LDA #$0006
	STA $02
	STA $0E
	BRA @CHECK_BOSS
@INITIATIVE_ENEMIES_FIRST:
	LDX #MUSIC::BATTLE_SWIRL2
	STX @SWIRL_MUSIC
	STZ @SWIRL_RED
	LDA #$001F
	STA @SWIRL_GREEN
	TAY
	STY @SWIRL_BLUE
	LDA #$0006
	STA $02
	STA $0E
@CHECK_BOSS:
	LDA CURRENT_BATTLE_GROUP
	CMP #ENEMY_GROUP::BOSS_FRANK
	BCC @PLAY_MUSIC
	LDA #$0003
	STA $16
	LDA #$000E
	STA $02
	STA $0E
	LDX #MUSIC::BATTLE_SWIRL1
	STX @SWIRL_MUSIC
@PLAY_MUSIC:
	LDX @SWIRL_MUSIC
	TXA
	JSL CHANGE_MUSIC
	JSL RESTORE_BG_PALETTE_AND_ENABLE_DISPLAY
	LDA $0E
	STA $02
	AND #$0004
	BEQ @START_SWIRL
	LDY @SWIRL_BLUE
	LDX @SWIRL_GREEN
	LDA @SWIRL_RED
	JSL SET_COLDATA
	LDA $02
	AND #$0008
	BEQ @COLOUR_MATH_NO_DIV2
	LDX #CGADSUB_BITS::COLOUR_MATH_ADDSUB | CGADSUB_BITS::COLOUR_MATH_DIV2 | CGADSUB_BITS::COLOUR_MATH_MAINISBACKDROP | CGADSUB_BITS::COLOUR_MATH_MAINISOBJ47 | CGADSUB_BITS::COLOUR_MATH_MAINISBG4 | CGADSUB_BITS::COLOUR_MATH_MAINISBG3 | CGADSUB_BITS::COLOUR_MATH_MAINISBG2 | CGADSUB_BITS::COLOUR_MATH_MAINISBG1
	LDA #CGWSEL_BITS::COLOUR_MATH_ENABLE_MATHWIN | CGWSEL_BITS::MAIN_SCREEN_BLACK_NEVER | CGWSEL_BITS::SUBSCREEN_BGOBJ_DISABLE | CGWSEL_BITS::USE_PALETTE
	JSL SET_COLOUR_ADDSUB_MODE
	BRA @START_SWIRL
@COLOUR_MATH_NO_DIV2:
	LDX #CGADSUB_BITS::COLOUR_MATH_ADDSUB | CGADSUB_BITS::COLOUR_MATH_MAINISBACKDROP | CGADSUB_BITS::COLOUR_MATH_MAINISOBJ47 | CGADSUB_BITS::COLOUR_MATH_MAINISBG4 | CGADSUB_BITS::COLOUR_MATH_MAINISBG3 | CGADSUB_BITS::COLOUR_MATH_MAINISBG2 | CGADSUB_BITS::COLOUR_MATH_MAINISBG1
	LDA #CGWSEL_BITS::COLOUR_MATH_ENABLE_MATHWIN | CGWSEL_BITS::MAIN_SCREEN_BLACK_NEVER | CGWSEL_BITS::SUBSCREEN_BGOBJ_DISABLE | CGWSEL_BITS::USE_PALETTE
	JSL SET_COLOUR_ADDSUB_MODE
@START_SWIRL:
	LDY #$001E
	LDX $02
	LDA $16
	JSL START_BATTLE_SWIRL
	LDA $02
	AND #$0004
	BEQ @SWIRL_MASK_FULL
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0020
	STA SWIRL_MASK_SETTINGS
	BRA @DONE
@SWIRL_MASK_FULL:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$000F
	STA SWIRL_MASK_SETTINGS
@DONE:
	STZ SWIRL_AUTO_RESTORE
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
