
BLANK_SCREEN_AND_WAIT_VBLANK:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0080
	STA INIDISP_MIRROR
	STZ NEW_FRAME_STARTED
@WAIT_LOOP:
	LDA NEW_FRAME_STARTED
	BEQ @WAIT_LOOP
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	RTL
