
CALCULATE_PROSPECTIVE_POSITION:
	LDX CURRENT_ENTITY_OFFSET
	BRA CALCULATE_PROSPECTIVE_POSITION_COMPUTE
	LDX $88
	BRA CALCULATE_PROSPECTIVE_POSITION_COMPUTE
CALCULATE_PROSPECTIVE_POSITION_ENTRY2:
	ASL
	TAX
CALCULATE_PROSPECTIVE_POSITION_COMPUTE:
	LDY #$0000
	LDA ENTITY_ABS_X_FRACTION_TABLE,X
	CLC
	ADC ENTITY_DELTA_X_FRACTION_TABLE,X
	LDA ENTITY_ABS_X_TABLE,X
	ADC ENTITY_DELTA_X_TABLE,X
	STA ENTITY_MOVEMENT_PROSPECTIVE_X
	CMP ENTITY_ABS_X_TABLE,X
	BEQ CALCULATE_PROSPECTIVE_POSITION_CHECK_Y
	INY
CALCULATE_PROSPECTIVE_POSITION_CHECK_Y:
	LDA ENTITY_ABS_Y_FRACTION_TABLE,X
	CLC
	ADC ENTITY_DELTA_Y_FRACTION_TABLE,X
	LDA ENTITY_ABS_Y_TABLE,X
	ADC ENTITY_DELTA_Y_TABLE,X
	STA ENTITY_MOVEMENT_PROSPECTIVE_Y
	CMP ENTITY_ABS_Y_TABLE,X
	BEQ CALCULATE_PROSPECTIVE_POSITION_DONE
	INY
CALCULATE_PROSPECTIVE_POSITION_DONE:
	TYA
	RTL
