
CALCULATE_TRAVEL_FRAMES:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL03
	LDX CURRENT_ENTITY_SLOT
	TXA
	ASL
	TAX
	LDA ENTITY_DELTA_X_TABLE,X
	STA @LOCAL00 + fixed_point::integer
	LDA ENTITY_DELTA_X_FRACTION_TABLE,X
	STA @LOCAL00 + fixed_point::fraction
	LDA ENTITY_DELTA_Y_TABLE,X
	STA @LOCAL01 + fixed_point::integer
	LDA ENTITY_DELTA_Y_FRACTION_TABLE,X
	STA @LOCAL01
	STA @VIRTUAL0A
	LDA @LOCAL01+2
	STA @VIRTUAL0A+2
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
	CLC
	LDA @VIRTUAL06
	SBC @VIRTUAL0A
	LDA @VIRTUAL06+2
	SBC @VIRTUAL0A+2
	BRANCHLTEQS @DY_POSITIVE
	MOVE_INT @LOCAL01, @VIRTUAL06
	SEC
	NEGATE_INT_ASSIGN @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	BRA @ABS_DY_DONE
@DY_POSITIVE:
	MOVE_INT @LOCAL01, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
@ABS_DY_DONE:
	MOVE_INT @LOCAL00, @VIRTUAL06
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CLC
	LDA @VIRTUAL0A
	SBC @VIRTUAL06
	LDA @VIRTUAL0A+2
	SBC @VIRTUAL06+2
	BRANCHLTEQS @DX_POSITIVE
	MOVE_INT @LOCAL00, @VIRTUAL0A
	SEC
	NEGATE_INT_ASSIGN @VIRTUAL0A
	BRA @ABS_DX_DONE
@DX_POSITIVE:
	MOVE_INT @LOCAL00, @VIRTUAL0A
@ABS_DX_DONE:
	MOVE_INT @LOCAL02, @VIRTUAL06
	CLC
	LDA @VIRTUAL0A
	SBC @VIRTUAL06
	LDA @VIRTUAL0A+2
	SBC @VIRTUAL06+2
	BRANCHLTEQS @USE_DY
	MOVE_INT @LOCAL00, @VIRTUAL0A
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
	CLC
	LDA @VIRTUAL06
	SBC @VIRTUAL0A
	LDA @VIRTUAL06+2
	SBC @VIRTUAL0A+2
	BRANCHLTEQS @DX_ABS
	MOVE_INT @LOCAL00, @VIRTUAL0A
	SEC
	NEGATE_INT_ASSIGN @VIRTUAL0A
	BRA @DO_DIVISION
@DX_ABS:
	MOVE_INT @LOCAL00, @VIRTUAL0A
	BRA @DO_DIVISION
@USE_DY:
	MOVE_INT @LOCAL01, @VIRTUAL0A
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
	CLC
	LDA @VIRTUAL06
	SBC @VIRTUAL0A
	LDA @VIRTUAL06+2
	SBC @VIRTUAL0A+2
	BRANCHLTEQS @DY_ABS
	MOVE_INT @LOCAL01, @VIRTUAL0A
	SEC
	NEGATE_INT_ASSIGN @VIRTUAL0A
	BRA @DO_DIVISION
@DY_ABS:
	MOVE_INT @LOCAL01, @VIRTUAL0A
@DO_DIVISION:
	LDA CURRENT_SCRIPT_SLOT
	ASL
	PHA
	SEP #PROC_FLAGS::ACCUM8
	LDA #16
	SEP #PROC_FLAGS::INDEX8
	TAY
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT1632 @LOCAL03, @VIRTUAL06
	JSL ASL32_ENTRY2
	REP #PROC_FLAGS::INDEX8
	JSL DIVISION32
	LDA @VIRTUAL06
	PLX
	STA ENTITY_SCRIPT_SLEEP_FRAMES,X
	END_C_FUNCTION
