
CAN_ENEMY_RUN_IN_DIRECTION:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDX #$0000
	AND #$000C
	BEQ @DIR_UP
	CMP #$0004
	BEQ @DIR_RIGHT
	CMP #$0008
	BEQ @DIR_DOWN_OR_LEFT
	CMP #$000C
	BEQ @DIR_DOWN_OR_LEFT
	BRA @CHECK_RUN_FLAG
@DIR_UP:
	LDX #$0004
	BRA @CHECK_RUN_FLAG
@DIR_RIGHT:
	LDX #$0002
	BRA @CHECK_RUN_FLAG
@DIR_DOWN_OR_LEFT:
	LDX #$0001
@CHECK_RUN_FLAG:
	STX @VIRTUAL02
	TYA
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::run_flag
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	AND #$00FF
	AND @VIRTUAL02
	BEQ @CAN_RUN
	LDA #$0000
	BRA @RETURN
@CAN_RUN:
	LDA #$0080
@RETURN:
	PLD
	RTL
