
CHECK_HOTSPOT_EXIT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL04
	STA @LOCAL02
	LDA NEXT_QUEUED_INTERACTION
	EOR NEXT_QUEUED_INTERACTION
	BNEL @RETURN
	LDA PSI_TELEPORT_DESTINATION
	BNEL @RETURN
	LDA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(active_hotspot)
	CLC
	ADC #.LOWORD(ACTIVE_HOTSPOTS)
	TAY
	LDA a:active_hotspot::mode,Y
	STA @LOCAL01
	LDX GAME_STATE+game_state::leader_x_coord
	LDA GAME_STATE+game_state::leader_y_coord
	STA @VIRTUAL02
	LDA @LOCAL01
	CMP #1
	BNE @MODE_OUTSIDE_CHECK
	TXA
	CMP a:active_hotspot::x1,Y
	BCC @DEACTIVATE_HOTSPOT
	TXA
	CMP a:active_hotspot::x2,Y
	BGT @DEACTIVATE_HOTSPOT
	LDA @VIRTUAL02
	CMP a:active_hotspot::y1,Y
	BCC @DEACTIVATE_HOTSPOT
	LDA @VIRTUAL02
	CMP a:active_hotspot::y2,Y
	BGT @DEACTIVATE_HOTSPOT
	BRA @RETURN
@MODE_OUTSIDE_CHECK:
	TXA
	CMP a:active_hotspot::x1,Y
	BLTEQ @RETURN
	TXA
	CMP a:active_hotspot::x2,Y
	BCS @RETURN
	LDA @VIRTUAL02
	CMP a:active_hotspot::y1,Y
	BLTEQ @RETURN
	LDA @VIRTUAL02
	CMP a:active_hotspot::y2,Y
	BCS @RETURN
@DEACTIVATE_HOTSPOT:
	LDA #0
	STA a:active_hotspot::mode,Y
	TYA
	CLC
	ADC #active_hotspot::pointer
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #9
	JSL QUEUE_INTERACTION
	LDA @LOCAL02
	STA @VIRTUAL04
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ a:game_state::active_hotspot_modes,X
.ELSE
	LDX @VIRTUAL04
	SEP #PROC_FLAGS::ACCUM8
	STZ GAME_STATE + game_state::active_hotspot_modes,X
.ENDIF
@RETURN:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
