
CHECK_LOW_HP_ALERT:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAY
	STY @LOCAL01
.IF .DEFINED(JPN)
	TYA
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::player_controlled_party_members,X
.ELSE
	LDA GAME_STATE+game_state::player_controlled_party_members,Y
.ENDIF
	AND #$00FF
	ASL
	TAX
	LDA CHOSEN_FOUR_PTRS,X
	TAX
	STX @LOCAL00
	LDY #100
	LDA a:char_struct::max_hp,X
	OPTIMIZED_MULT @VIRTUAL04, 20
	JSL DIVISION16S_DIVISOR_POSITIVE
	CMP a:char_struct::current_hp,X
	BLTEQ @HP_NOT_LOW
	LDY @LOCAL01
	TYA
	ASL
	TAX
	LDA HP_ALERT_SHOWN,X
	BNE @MARK_SHOWN
	LDX @LOCAL00
	LDA a:char_struct::unknown53,X
	INC
	JSL SHOW_HP_ALERT
@MARK_SHOWN:
	LDY @LOCAL01
	TYA
	ASL
	TAX
	LDA #1
	STA HP_ALERT_SHOWN,X
	BRA @RETURN
@HP_NOT_LOW:
	LDY @LOCAL01
	TYA
	ASL
	TAX
	STZ HP_ALERT_SHOWN,X
@RETURN:
	END_C_FUNCTION
