
CHECK_ENEMY_SHOULD_FLEE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_NPC_IDS,X
	AND #$7FFF
	STA @LOCAL02
	LOADPTR BTL_ENTRY_PTR_TABLE, @VIRTUAL06
	LDA @LOCAL02
	ASL
	ASL
	ASL
	TAX
	STX @LOCAL01
	TXA
	OPTIMIZED_ADD battle_entry_ptr_entry::run_away_flag
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	BEQ @CHECK_LEVEL_THRESHOLD
	JSL GET_EVENT_FLAG
	STA @LOCAL00
	LDX @LOCAL01
	TXA
	CLC
	ADC #battle_entry_ptr_entry::run_away_flag_state
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	STA @VIRTUAL02
	LDA @LOCAL00
	CMP @VIRTUAL02
	BNE @CHECK_LEVEL_THRESHOLD
	LDA #1
	JMP @RETURN
@CHECK_LEVEL_THRESHOLD:
	JSL SUM_ALIVE_PARTY_LEVELS
	TAY
	STY @LOCAL00
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	STX @LOCAL02
	LDA ENTITY_ENEMY_IDS,X
	LDY #.SIZEOF(enemy_data)
	JSL MULT168
	CLC
	ADC #enemy_data::level
	TAX
	LDA f:ENEMY_CONFIGURATION_TABLE,X
	AND #$00FF
	STA @LOCAL01
	OPTIMIZED_MULT @VIRTUAL04, 10
	STA @VIRTUAL02
	LDY @LOCAL00
	TYA
	CMP @VIRTUAL02
	BLTEQ @CHECK_LEVEL_X8
	LDA #1
	BRA @RETURN
@CHECK_LEVEL_X8:
	LDA @LOCAL01
	ASL
	ASL
	ASL
	STA @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BLTEQ @CHECK_LEVEL_X6
	LDX @LOCAL02
	LDA ENTITY_WEAK_ENEMY_VALUE,X
	CMP #192
	BCS @CHECK_LEVEL_X6
	LDA #1
	BRA @RETURN
@CHECK_LEVEL_X6:
	LDA @LOCAL01
	STA @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	ASL
	STA @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BLTEQ @NO_FLEE
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_WEAK_ENEMY_VALUE,X
	CMP #128
	BCS @NO_FLEE
	LDA #1
	BRA @RETURN
@NO_FLEE:
	LDA #0
@RETURN:
	END_C_FUNCTION
