
CLEAR_ALL_ENEMIES:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	STZ MAGIC_BUTTERFLY_SPAWNED
	STZ ENEMY_SPAWN_TOO_MANY_ENEMIES_FAILURE_COUNT
	STZ OVERWORLD_ENEMY_COUNT
	LDX #0
	STX @LOCAL01
	BRA @REMOVE_LOOP_CHECK
@CHECK_ENTITY_TYPE:
	TXA
	ASL
	TAX
	LDA ENTITY_SCRIPT_TABLE,X
	INC
	CMP #6
	BLTEQ @SKIP_PARTY_MEMBER
	LDX @LOCAL01
	TXA
	JSL REMOVE_ENTITY
@SKIP_PARTY_MEMBER:
	LDX @LOCAL01
	INX
	STX @LOCAL01
@REMOVE_LOOP_CHECK:
	CPX #MAX_ENTITIES
	BNE @CHECK_ENTITY_TYPE
	LDA #0
	STA @LOCAL00
	BRA @CLEAR_LOOP_CHECK
@CLEAR_COLLISION:
	ASL
	TAX
	LDA #ENTITY_COLLISION_NO_OBJECT
	STA ENTITY_COLLIDED_OBJECTS,X
	LDA @LOCAL00
	INC
	STA @LOCAL00
@CLEAR_LOOP_CHECK:
	CMP #MAX_ENTITIES
	BCC @CLEAR_COLLISION
	END_C_FUNCTION
