
DEACTIVATE_ENTITIES_BY_SCRIPT_ID:
	JSR SCRIPT_READ_WORD
	STY $94
	LDX FIRST_ENTITY
@LOOP:
	LDY ENTITY_NEXT_ENTITY_TABLE,X
	STY $96
	CMP ENTITY_SCRIPT_TABLE,X
	BNE @NEXT_ENTITY
	CPX $88
	BEQ @NEXT_ENTITY
	STA $98
	JSR DEACTIVATE_ENTITY
	LDA $98
@NEXT_ENTITY:
	LDX $96
	BPL @LOOP
	RTL
