
DEACTIVATE_ENTITY:
	PHA
	LDA ENTITY_SCRIPT_TABLE,X
	BMI @ALREADY_INACTIVE
	PHY
	LDA #$FFFF
	STA ENTITY_SCRIPT_TABLE,X
	JSR CLEAR_SPRITE_TICK_CALLBACK
	JSR FREE_ENTITY_SCRIPTS
	JSR UNLINK_ENTITY_FROM_LIST
	JSR APPEND_ENTITY_TO_LIST
	PLY
@ALREADY_INACTIVE:
	PLA
	RTS
