
DECREMENT_DELIVERY_TIMER:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR0_TABLE,X
	ASL
	CLC
	ADC #.LOWORD(DELIVERY_TIMERS)
	TAX
	LDA __BSS_START__,X
	BEQ @TIMER_NOT_ZERO
	DEC
	STA __BSS_START__,X
@TIMER_NOT_ZERO:
	END_C_FUNCTION
