
DOOR_TRANSITION:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	MOVE_INT @PARAM00, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @LOCAL03
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL06
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BEQ @SKIP_TEXT
	MOVE_INT @VIRTUAL06, @LOCAL00 ;door_data::text
	JSL DISPLAY_TEXT_AND_WAIT_FOR_FADE
@SKIP_TEXT:
	STZ LADDER_STAIRS_TILE_Y
	STZ LADDER_STAIRS_TILE_X
	LDA #door_data::event_flag
	MOVE_INTX @LOCAL03, @VIRTUAL0A
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	BEQ @FLAG_CHECK_PASSED
	AND #$7FFF
	JSL GET_EVENT_FLAG
	STA @LOCAL02
	LDX #0
	LDA [@VIRTUAL06]
	CMP #EVENT_FLAG_UNSET
	BLTEQ @STORE_EXPECTED_FLAG
	LDX #1
@STORE_EXPECTED_FLAG:
	STX @VIRTUAL02
	LDA @LOCAL02
	CMP @VIRTUAL02
	BEQ @FLAG_CHECK_PASSED
	STZ USING_DOOR
	JMP @EXIT
@FLAG_CHECK_PASSED:
	LDY #1
	STY @LOCAL01
	BRA @CLEAR_FLAG_LOOP_CHECK
@CLEAR_FLAG_LOOP_BODY:
	LDX #0
	TYA
	JSL SET_EVENT_FLAG
	LDY @LOCAL01
	INY
	STY @LOCAL01
@CLEAR_FLAG_LOOP_CHECK:
	CPY #10
	BLTEQ @CLEAR_FLAG_LOOP_BODY
	JSL PROCESS_DOOR_INTERACTIONS
	JSL CLEAR_PARTY_SPRITE_HIDE_FLAGS
	LDA #$FFFF
	STA ENTITY_FADE_ENTITY
	STZ PLAYER_INTANGIBILITY_FRAMES
	LDA #door_data::unknown10
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDX #1
	LDA [@VIRTUAL06]
	AND #$00FF
	JSL GET_SCREEN_TRANSITION_SOUND_EFFECT
	JSL PLAY_SOUND
	LDA DISABLED_TRANSITIONS
	BEQ @NORMAL_TRANSITION_OUT
	LDX #1
	TXA
	JSL FADE_OUT
	BRA @AFTER_TRANSITION_OUT
@NORMAL_TRANSITION_OUT:
	LDX #1
	LDA [@VIRTUAL06]
	AND #$00FF
	JSL SCREEN_TRANSITION
@AFTER_TRANSITION_OUT:
	LDY #door_data::unknown8
	LDA [@VIRTUAL0A],Y
	ASL
	ASL
	ASL
	STA @VIRTUAL02
	LDY #door_data::unknown6
	LDA [@VIRTUAL0A],Y
	STA @LOCAL02
	AND #$3FFF
	ASL
	ASL
	ASL
	STA @VIRTUAL04
	SEP #PROC_FLAGS::ACCUM8
	LDA #14
	SEP #PROC_FLAGS::INDEX8
	TAY
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	JSL ASR8_POSITIVE
	ASL
	REP #PROC_FLAGS::INDEX8
	TAX
	LDA f:DOOR_ENTRY_DIRECTION_TABLE,X
	CMP #2
	BEQ @SKIP_Y_ADJUST
	LDA @VIRTUAL02
	CLC
	ADC #8
	STA @VIRTUAL02
@SKIP_Y_ADJUST:
	LDA DEBUG
	BEQ @NOT_DEBUG
	LDA DEBUG_MODE_NUMBER
	CMP #6
	BEQ @SKIP_MUSIC_RESOLVE
	LDX @VIRTUAL04
	LDA @VIRTUAL02
	JSL RESOLVE_MAP_SECTOR_MUSIC
@SKIP_MUSIC_RESOLVE:
	LDA REPLAY_MODE_ACTIVE
	BNE @LOAD_DESTINATION_MAP
	SEP #PROC_FLAGS::ACCUM8
	LDY #door_data::unknown10
	LDA [@VIRTUAL0A],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	JSL BACKUP_RNG_IF_BAD_SRAM
	BRA @LOAD_DESTINATION_MAP
@NOT_DEBUG:
	LDX @VIRTUAL04
	LDA @VIRTUAL02
	JSL RESOLVE_MAP_SECTOR_MUSIC
@LOAD_DESTINATION_MAP:
	LDX @VIRTUAL04
	LDA @VIRTUAL02
	JSL LOAD_MAP_AT_POSITION
	STZ PLAYER_HAS_MOVED_SINCE_MAP_LOAD
	STZ GAME_STATE+game_state::walking_style
	SEP #PROC_FLAGS::ACCUM8
	LDA #14
	PHA
	REP #PROC_FLAGS::ACCUM8
	LDY #door_data::unknown6
	LDA [@VIRTUAL0A],Y
	SEP #PROC_FLAGS::INDEX8
	PLY
	JSL ASR8_POSITIVE
	ASL
	REP #PROC_FLAGS::INDEX8
	TAX
	LDA f:DOOR_ENTRY_DIRECTION_TABLE,X
	TAY
	LDX @VIRTUAL04
	LDA @VIRTUAL02
	JSL SET_LEADER_POSITION_AND_LOAD_PARTY
	LDA DEBUG
	BEQ @AFTER_REPLAY_SAVE
	LDA REPLAY_MODE_ACTIVE
	BNE @AFTER_REPLAY_SAVE
	JSL SAVE_REPLAY_SAVE_SLOT
@AFTER_REPLAY_SAVE:
	JSL APPLY_NEXT_MAP_MUSIC
	JSL FLUSH_ENTITY_CREATION_QUEUE
	LDA #door_data::unknown10
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDX #0
	LDA [@VIRTUAL06]
	AND #$00FF
	JSL GET_SCREEN_TRANSITION_SOUND_EFFECT
	JSL PLAY_SOUND
	LDA DISABLED_TRANSITIONS
	BEQ @NORMAL_TRANSITION_IN
	LDX #1
	TXA
	JSL FADE_IN
	BRA @AFTER_TRANSITION_IN
@NORMAL_TRANSITION_IN:
	LDX #0
	LDA [@VIRTUAL06]
	AND #$00FF
	JSL SCREEN_TRANSITION
@AFTER_TRANSITION_IN:
	LDA #$FFFF
	STA STAIRS_DIRECTION
	STZ PLAYER_HAS_DONE_SOMETHING_THIS_FRAME
	JSL SPAWN_BUZZ_BUZZ
	STZ USING_DOOR
@EXIT:
	END_C_FUNCTION
