
ENABLE_ALL_ENTITIES:
	LDX FIRST_ENTITY
	BMI @DONE
@LOOP:
	LDA ENTITY_TICK_CALLBACK_HIGH,X
	AND #$FFFF ^ (OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED)
	STA ENTITY_TICK_CALLBACK_HIGH,X
	LDA ENTITY_NEXT_ENTITY_TABLE,X
	TAX
	BPL @LOOP
@DONE:
	RTL
