
EXECUTE_MOVEMENT_SCRIPT:
	LDX $8A
	LDA ENTITY_SCRIPT_SLEEP_FRAMES,X
	BNE @RETURN
	LDY ENTITY_SCRIPT_PROGRAM_COUNTERS,X
	LDA ENTITY_SCRIPT_PROGRAM_COUNTER_BANKS,X
	STA $82
	TXA
	ASL
	ASL
	ASL
	ADC #.LOWORD(ENTITY_SCRIPT_STACKS)
	STA $84
@FETCH_OPCODE:
	LDA [$80],Y
	INY
	AND #$00FF
	CMP #$0070
	BCS @DIRECTION_OPCODE
	ASL
	TAX
	JSR (.LOWORD(MOVEMENT_CTRL_CODES_PTR_TABLE),X)
	BRA @CHECK_SLEEP
@DIRECTION_OPCODE:
	STA $90
	AND #$000F
	STA ENTITY_SCRIPT_SLEEP_FRAMES,X
	LDA $90
	AND #$0070
	LSR
	LSR
	LSR
	TAX
	JSR (.LOWORD(MOVEMENT_CTRL_CODES_PTR_TABLE)+138,X)
@CHECK_SLEEP:
	LDX $8A
	LDA ENTITY_SCRIPT_SLEEP_FRAMES,X
	BEQ @FETCH_OPCODE
	TYA
	STA ENTITY_SCRIPT_PROGRAM_COUNTERS,X
	LDA $82
	STA ENTITY_SCRIPT_PROGRAM_COUNTER_BANKS,X
@RETURN:
	DEC ENTITY_SCRIPT_SLEEP_FRAMES,X
	RTS
