
FIND_FREE_7E4682:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	STA @VIRTUAL02
	LDX #0
	STX @LOCAL01
	LDA @VIRTUAL02
	STA UNREAD_7E4A6A
	BRA @SCAN_LOOP
@CHECK_ENTRY:
	LDA OVERWORLD_SPRITEMAPS + spritemap::special_flags,X
	AND #$00FF
	CMP #<-1
	BEQ @FOUND_FREE
	TXA
	CLC
	ADC #.SIZEOF(spritemap)
	TAX
	STX @LOCAL01
@SCAN_LOOP:
	CPX #$0380
	BCC @CHECK_ENTRY
	LDA #.LOWORD(-255)
	BRA @RETURN
@FOUND_FREE:
	TXA
	CLC
	ADC @VIRTUAL02
	CMP #$0380
	BCS @NO_SPACE
	TXA
	STA @LOCAL00
	BRA @VERIFY_LOOP
@VERIFY_ENTRY:
	TAX
	LDA OVERWORLD_SPRITEMAPS + spritemap::special_flags,X
	AND #$00FF
	CMP #<-1
	BEQ @ADVANCE_VERIFY
	LDA @LOCAL00
	CLC
	ADC #.SIZEOF(spritemap)
	TAX
	STX @LOCAL01
	BRA @SCAN_LOOP
@ADVANCE_VERIFY:
	LDA @LOCAL00
	CLC
	ADC #.SIZEOF(spritemap)
	STA @LOCAL00
@VERIFY_LOOP:
	LDX @LOCAL01
	TXA
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL04
	LDA @LOCAL00
	CMP @VIRTUAL04
	BCC @VERIFY_ENTRY
	TXA
	BRA @RETURN
@NO_SPACE:
	LDA #.LOWORD(-254)
@RETURN:
	END_C_FUNCTION
