
FORCE_BLANK_AND_WAIT_VBLANK:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0080
	STA INIDISP_MIRROR
	STZ HDMAEN_MIRROR
.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
	STZ FADE_PARAMETERS + fade_parameters::step
.ENDIF
	STZ NEW_FRAME_STARTED
@WAIT_LOOP:
	LDA NEW_FRAME_STARTED
	BEQ @WAIT_LOOP
	LDA #$0000
	STA f:HDMAEN
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	RTL
