
FREE_ENTITY_SCRIPTS:
	LDA ENTITY_SCRIPT_INDEX_TABLE,X
	BMI @DONE
	PHX
	LDA LAST_ALLOCATED_SCRIPT
	PHA
	LDA ENTITY_SCRIPT_INDEX_TABLE,X
	STA LAST_ALLOCATED_SCRIPT
@FIND_LAST:
	TAX
	LDA ENTITY_SCRIPT_NEXT_SCRIPTS,X
	BPL @FIND_LAST
	PLA
	STA ENTITY_SCRIPT_NEXT_SCRIPTS,X
	PLX
@DONE:
	RTS
