
GET_MAP_ENEMY_PLACEMENT:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	CMP #MAP_WIDTH_TILES
	BCS @OUT_OF_BOUNDS
	CPX #MAP_HEIGHT_TILES
	BCS @OUT_OF_BOUNDS
	ASL
	STA @VIRTUAL02
	TXA
	XBA
	AND #$FF00
	CLC
	ADC @VIRTUAL02
	TAX
	LDA f:MAP_ENEMY_PLACEMENT,X
	BRA @RETURN
@OUT_OF_BOUNDS:
	LDA #$0000
@RETURN:
	PLD
	RTL
