
GET_PREVIOUS_POSITION_INDEX:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL01
	LDA #0
	STA @LOCAL00
	BRA @COMPARE_PARTY_ORDER
@NEXT_INDEX:
	LDA @LOCAL00
	INC
	STA @LOCAL00
@COMPARE_PARTY_ORDER:
	LDX @LOCAL01
	STX @VIRTUAL02
	INC @VIRTUAL02
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_order,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @NEXT_INDEX
	LDA @LOCAL00
	BNE @GET_PREVIOUS
	LDA #.LOWORD(-1)
	BRA @RETURN
@GET_PREVIOUS:
	DEC
	ASL
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_entity_slots,X
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR1_TABLE,X
	ASL
	TAX
	LDA CHOSEN_FOUR_PTRS,X
	TAX
	LDA a:char_struct::position_index,X
@RETURN:
	END_C_FUNCTION
