
GET_DISTANCE_TO_MAGIC_TRUFFLE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	LDA #OVERWORLD_SPRITE::MAGIC_TRUFFLE
	JSL FIND_ENTITY_BY_SPRITE_ID
	STA @VIRTUAL04
	CMP #.LOWORD(-1)
	BNE @TRUFFLE_FOUND
	LDA #0
	JMP @RETURN
@TRUFFLE_FOUND:
	LDA @VIRTUAL04
	ASL
	TAX
	LDA ENTITY_ABS_X_TABLE,X
	STA @LOCAL02
	LDY GAME_STATE+game_state::leader_x_coord
	TYA
	SEC
	SBC #64
	STA @VIRTUAL02
	LDA @LOCAL02
	CMP @VIRTUAL02
	BCC @OUT_OF_RANGE
	TYA
	CLC
	ADC #64
	STA @VIRTUAL02
	LDA @LOCAL02
	CMP @VIRTUAL02
	BGT @OUT_OF_RANGE
	LDY ENTITY_ABS_Y_TABLE,X
	LDA GAME_STATE+game_state::leader_y_coord
	STA @LOCAL02
	SEC
	SBC #64
	STA @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BCC @OUT_OF_RANGE
	LDA @LOCAL02
	CLC
	ADC #64
	STA @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BLTEQ @COMPUTE_DISTANCE
@OUT_OF_RANGE:
	LDA #1
	JMP @RETURN
@COMPUTE_DISTANCE:
	LDA @LOCAL02
	STA @VIRTUAL02
	TYA
	SEC
	SBC @VIRTUAL02
	STA @LOCAL02
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @DY_POSITIVE
	LDA @LOCAL02
	EOR #$FFFF
	INC
	STA @VIRTUAL02
	STA @LOCAL01
	BRA @COMPUTE_DX
@DY_POSITIVE:
	LDA @LOCAL02
	STA @VIRTUAL02
	STA @LOCAL01
@COMPUTE_DX:
	LDA @VIRTUAL04
	ASL
	TAX
	LDA ENTITY_ABS_X_TABLE,X
	SEC
	SBC GAME_STATE+game_state::leader_x_coord
	STA @LOCAL02
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @DX_POSITIVE
	LDA @LOCAL02
	EOR #$FFFF
	INC
	BRA @SUM_DISTANCES
@DX_POSITIVE:
	LDA @LOCAL02
@SUM_DISTANCES:
	LDX @LOCAL01
	STX @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL02
	LDA #16
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @CALC_DIRECTION
	LDA #10
	BRA @RETURN
@CALC_DIRECTION:
	LDA @VIRTUAL04
	ASL
	TAX
	LDA ENTITY_ABS_Y_TABLE,X
	STA @LOCAL00
	LDY ENTITY_ABS_X_TABLE,X
	LDX GAME_STATE + game_state::leader_y_coord
	LDA GAME_STATE + game_state::leader_x_coord
	JSL CALCULATE_DIRECTION_FROM_POSITIONS
	LDY #$2000
	CLC
	ADC #$1000
	JSL DIVISION16S_DIVISOR_POSITIVE
	INC
	INC
@RETURN:
	END_C_FUNCTION
