
GET_DIRECTION_TO:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int x1
	STACK_RESERVE_PARAM_INT16 ;int y1
	STACK_RESERVE_PARAM_INT16 ;int x2
	STACK_RESERVE_PARAM_INT16 ;int y2
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	STX @VIRTUAL04
	STA @VIRTUAL02
	LDX @PARAM03
	TXA
	STA @LOCAL01
	TYA
	SEC
	SBC @VIRTUAL02
	TAX
	LDA @LOCAL01
	SEC
	SBC @VIRTUAL04
	STA @LOCAL00
	STX @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @DY_NON_NEGATIVE
	LDX #0
	BRA @CLASSIFY_DX
@DY_NON_NEGATIVE:
	CPX #0
	BNE @DY_POSITIVE
	LDX #1
	BRA @CLASSIFY_DX
@DY_POSITIVE:
	LDX #2
@CLASSIFY_DX:
	LDA @LOCAL00
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @DX_NON_NEGATIVE
	LDA #0
	STA @LOCAL01
	BRA @LOOKUP_DIRECTION
@DX_NON_NEGATIVE:
	LDA @LOCAL00
	BNE @DX_POSITIVE
	LDA #1
	STA @LOCAL01
	BRA @LOOKUP_DIRECTION
@DX_POSITIVE:
	LDA #2
	STA @LOCAL01
@LOOKUP_DIRECTION:
	TXA
	ASL
	STA @VIRTUAL02
	LDA @LOCAL01
	OPTIMIZED_MULT @VIRTUAL04, 6
	CLC
	ADC @VIRTUAL02
	TAX
	LDA f:DIRECTION_MATRIX,X
	END_C_FUNCTION
