
GET_POSITION_OF_PARTY_MEMBER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	LDY CURRENT_ENTITY_SLOT
	STY @LOCAL02
	CPX #<-2
	BNE @FIND_BY_CHARACTER
	LDA GAME_STATE+game_state::party_count
	AND #$00FF
	TAX
	STX @LOCAL01
	TXA
	DEC
	ASL
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_entity_slots,X
.ELSE
	TAX
	LDA GAME_STATE + game_state::party_entity_slots,X
.ENDIF
	STA @LOCAL00
	ASL
	TAX
	LDA ENTITY_ABS_X_TABLE,X
	BNE @COPY_POSITION
	LDX @LOCAL01
	TXA
	DEC
	DEC
	ASL
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_entity_slots,X
.ELSE
	TAX
	LDA GAME_STATE + game_state::party_entity_slots,X
.ENDIF
	STA @LOCAL00
	BRA @COPY_POSITION
@FIND_BY_CHARACTER:
	TXA
	SEP #PROC_FLAGS::ACCUM8
	JSL FIND_ENTITY_FOR_CHARACTER
	STA @LOCAL00
@COPY_POSITION:
	LDY @LOCAL02
	TYA
	ASL
	TAY
	LDA @LOCAL00
	ASL
	TAX
	LDA ENTITY_ABS_X_TABLE,X
	STA ENTITY_SCRIPT_VAR6_TABLE,Y
	LDA ENTITY_ABS_Y_TABLE,X
	STA ENTITY_SCRIPT_VAR7_TABLE,Y
	END_C_FUNCTION
