
GET_PREVIOUS_POSITION_INDEX:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL00
	LDX #0
	BRA @CHECK_PARTY_ORDER
@NEXT_MEMBER:
	INX
@CHECK_PARTY_ORDER:
	LDA @LOCAL00
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA GAME_STATE + game_state::party_order,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @NEXT_MEMBER
	CPX #0
	BNE @FOUND_PREDECESSOR
	LDA #.LOWORD(-1)
	BRA @RETURN
@FOUND_PREDECESSOR:
	TXA
	DEC
	ASL
	TAX
	LDA GAME_STATE + game_state::party_entity_slots,X
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR1_TABLE,X
	ASL
	TAX
	LDA CHOSEN_FOUR_PTRS,X
	TAX
	LDA a:char_struct::position_index,X
@RETURN:
	END_C_FUNCTION
