
HANDLE_ENEMY_CONTACT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA BATTLE_MODE
	BEQ @NOT_IN_BATTLE
	LDA #0
	JMP @RETURN
@NOT_IN_BATTLE:
	LDA USING_DOOR
	BEQ @NOT_USING_DOOR
	LDA #0
	JMP @RETURN
@NOT_USING_DOOR:
	LDA CURRENT_ENTITY_SLOT
	STA @VIRTUAL02
	LDA BATTLE_SWIRL_COUNTDOWN
	BEQ @CHECK_CAMERA_MODE
	LDA @VIRTUAL02
	CMP TOUCHED_ENEMY
	BEQ @COLLISION_DETECTED
@CHECK_CAMERA_MODE:
	LDA GAME_STATE + game_state::camera_mode
	CMP #2
	BNE @CAMERA_OK
	LDA #0
	JMP @RETURN
@CAMERA_OK:
	LDA PLAYER_MOVEMENT_FLAGS
	AND #02
	BEQ @MOVEMENT_OK
	LDA #0
	JMP @RETURN
@MOVEMENT_OK:
	LDA GAME_STATE+game_state::walking_style
	CMP #WALKING_STYLE::ESCALATOR
	BNE @NOT_ON_ESCALATOR
	LDA #0
	JMP @RETURN
@NOT_ON_ESCALATOR:
	LDA PLAYER_INTANGIBILITY_FRAMES
	BEQ @NOT_INTANGIBLE
	LDA #0
	JMP @RETURN
@NOT_INTANGIBLE:
	LDA BATTLE_SWIRL_COUNTDOWN
	BEQ @CHECK_COLLISION
	LDA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_PATH_POINT_COUNTS,X
	BEQ @COLLISION_DETECTED
@CHECK_COLLISION:
	JSL CHECK_ENTITY_ENEMY_COLLISION
	CMP #0
	BNE @COLLISION_DETECTED
	LDA #0
	JMP @RETURN
@COLLISION_DETECTED:
	LDA BATTLE_SWIRL_COUNTDOWN
	BNE @START_ENCOUNTER
	LDA ENEMY_HAS_BEEN_TOUCHED
	BNE @START_ENCOUNTER
	LDA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_ENEMY_IDS,X
	CMP #ENEMY::MAGIC_BUTTERFLY
	BNE @START_ENCOUNTER
	LDA #1
	JMP @RETURN
@START_ENCOUNTER:
	LDA BATTLE_SWIRL_COUNTDOWN
	BNE @SWIRL_ACTIVE
	LDA ENEMY_HAS_BEEN_TOUCHED
	BNE @SWIRL_ACTIVE
	LDA #1
	STA ENEMY_HAS_BEEN_TOUCHED
	JSL DESATURATE_PALETTES
	LDA @VIRTUAL02
	CMP ENTITY_COLLIDED_OBJECTS+46
	BNE @GET_COLLIDED_ENTITY
	LDA #24
	STA ENEMY_PATHFINDING_TARGET_ENTITY
	BRA @STORE_TOUCHED_ENEMY
@GET_COLLIDED_ENTITY:
	LDA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_COLLIDED_OBJECTS,X
	STA ENEMY_PATHFINDING_TARGET_ENTITY
@STORE_TOUCHED_ENEMY:
	LDA @VIRTUAL02
	STA TOUCHED_ENEMY
	LDA #0
	STA @LOCAL03
	BRA @DISABLE_ENTITY_CHECK
@DISABLE_ENTITY_LOOP:
	CMP #23
	BEQ @NEXT_ENTITY
	ASL
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA __BSS_START__,X
@NEXT_ENTITY:
	LDA @LOCAL03
	INC
	STA @LOCAL03
@DISABLE_ENTITY_CHECK:
	CMP #MAX_ENTITIES
	BCC @DISABLE_ENTITY_LOOP
	JSL START_CAMERA_SHAKE
	LDA #1
	JMP @RETURN
@SWIRL_ACTIVE:
	LDA @VIRTUAL02
	ASL
	TAX
	LDA #ENTITY_COLLISION_DISABLED
	STA ENTITY_COLLIDED_OBJECTS,X
	STZ @LOCAL02
	LDA BATTLE_SWIRL_COUNTDOWN
	BEQL @CHECK_RESULT
	LDA @VIRTUAL02
	CMP TOUCHED_ENEMY
	BNE @CHECK_PATHFINDING_ENEMIES
	TXA
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA __BSS_START__,X
	LDA #1
	STA @LOCAL02
	JMP @CHECK_RESULT
@CHECK_PATHFINDING_ENEMIES:
	LDA ENTITY_ENEMY_IDS,X
	STA @VIRTUAL04
	LDY #0
	STZ @LOCAL02
	TYA
	STA @LOCAL01
	BRA @PATHFINDING_LOOP_CHECK
@COMPARE_ENEMY_ID:
	ASL
	TAX
	LDA @VIRTUAL04
	CMP PATHFINDING_ENEMY_IDS,X
	BNE @NEXT_PATHFINDING_SLOT
	TXA
	CLC
	ADC #.LOWORD(PATHFINDING_ENEMY_COUNTS)
	TAX
	LDA __BSS_START__,X
	STA @LOCAL00
	BEQ @NEXT_PATHFINDING_SLOT
	LDA @LOCAL00
	DEC
	STA __BSS_START__,X
	LDA #1
	STA @LOCAL02
	LDA @VIRTUAL02
	ASL
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA __BSS_START__,X
	LDA ENEMIES_IN_BATTLE
	ASL
	TAX
	LDA @VIRTUAL04
	STA ENEMIES_IN_BATTLE_IDS,X
	INC ENEMIES_IN_BATTLE
@NEXT_PATHFINDING_SLOT:
	LDA @LOCAL01
	ASL
	TAX
	TYA
	CLC
	ADC PATHFINDING_ENEMY_COUNTS,X
	TAY
	LDA @LOCAL01
	INC
	STA @LOCAL01
@PATHFINDING_LOOP_CHECK:
	CMP #4
	BNE @COMPARE_ENEMY_ID
	CPY #0
	BNE @CHECK_RESULT
	JSL IS_BATTLE_SWIRL_ACTIVE
	CMP #0
	BNE @CHECK_RESULT
	LDA #0
	STA @LOCAL03
	BRA @DISABLE_ALL_CHECK
@DISABLE_ALL_ENTITIES_LOOP:
	CMP #23
	BEQ @NEXT_ENTITY_2
	ASL
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA __BSS_START__,X
@NEXT_ENTITY_2:
	LDA @LOCAL03
	INC
	STA @LOCAL03
@DISABLE_ALL_CHECK:
	CMP #MAX_ENTITIES
	BCC @DISABLE_ALL_ENTITIES_LOOP
	LDA #1
	STA BATTLE_SWIRL_COUNTDOWN
@CHECK_RESULT:
	LDA @LOCAL02
@RETURN:
	END_C_FUNCTION
