
INFLICT_SUNSTROKE_CHECK:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA OVERWORLD_STATUS_SUPPRESSION
	BNEL @RETURN
	LDA GAME_STATE+game_state::trodden_tile_type
	AND #$000C
	CMP #4
	BNEL @RETURN
	LDX #0
	STX @LOCAL01
	JMP @CHECK_LOOP
@LOOP_PARTY_MEMBER:
	REP #PROC_FLAGS::ACCUM8
	TXA
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAY
	LDA __BSS_START__ + game_state::party_order,Y
	AND #$00FF
	BEQL @RETURN
	AND #$00FF
	CLC
	SBC #4
	BRANCHGTS @RETURN
	LDA __BSS_START__+game_state::player_controlled_party_members,Y
	AND #$00FF
	ASL
	TAX
	LDY CHOSEN_FOUR_PTRS,X
	STY CURRENT_PARTY_MEMBER_TICK
	LDA a:char_struct::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,Y
	AND #$00FF
	TAY
	BEQ @NO_CONFLICTING_STATUS
	CPY #STATUS_0::COLD
	BNE @NEXT_MEMBER
@NO_CONFLICTING_STATUS:
	LDX CURRENT_PARTY_MEMBER_TICK
	LDA a:char_struct::guts,X
	AND #$00FF
	STA @VIRTUAL02
	LDA #30
	SEC
	SBC @VIRTUAL02
	CMP #$8000
	BLTEQ @CALC_CHANCE
	LDA #1
@CALC_CHANCE:
	LDY #100
	XBA
	AND #$FF00
	JSL DIVISION16S_DIVISOR_POSITIVE
	STA @LOCAL00
	JSL RAND
	TAY
	LDA @LOCAL00
	STA @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BGT @NEXT_MEMBER
	SEP #PROC_FLAGS::ACCUM8
	LDA #STATUS_0::SUNSTROKE
	LDX CURRENT_PARTY_MEMBER_TICK
	STA a:char_struct::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
@NEXT_MEMBER:
	LDX @LOCAL01
	INX
	STX @LOCAL01
@CHECK_LOOP:
	CPX #6
	BCCL @LOOP_PARTY_MEMBER
@RETURN:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
