
INIT_ENTITY_SYSTEM:
	LDA #.LOWORD(BUILD_ENTITY_DRAW_LIST)
	STA CURRENT_ENTITY_DRAW_CALLBACK
	LDX #.LOWORD(-1)
	STX FIRST_ENTITY
	STX ENTITY_NEXT_ENTITY_TABLE+58
	STX ENTITY_SCRIPT_NEXT_SCRIPTS+138
	INX
	STX LAST_ENTITY
	STX LAST_ALLOCATED_SCRIPT
	CLC
	LDX #56
@BUILD_ENTITY_LIST:
	TXA
	ADC #2
	STA ENTITY_NEXT_ENTITY_TABLE,X
	DEX
	DEX
	BPL @BUILD_ENTITY_LIST
	LDX #136
@BUILD_SCRIPT_LIST:
	TXA
	ADC #2
	STA ENTITY_SCRIPT_NEXT_SCRIPTS,X
	DEX
	DEX
	BPL @BUILD_SCRIPT_LIST
	LDX #58
	LDA #.LOWORD(-1)
@CLEAR_SCRIPT_TABLE:
	STA ENTITY_SCRIPT_TABLE,X
	DEX
	DEX
	BPL @CLEAR_SCRIPT_TABLE
	LDX #58
@CLEAR_SPRITE_CALLBACKS:
	STZ ENTITY_SPRITEMAP_POINTER_HIGH,X
	STZ ENTITY_TICK_CALLBACK_HIGH,X
	DEX
	DEX
	BPL @CLEAR_SPRITE_CALLBACKS
	LDX #6
@CLEAR_BG_OFFSETS:
	STZ ENTITY_BG_HORIZONTAL_OFFSET_HIGH,X
	STZ ENTITY_BG_VERTICAL_OFFSET_HIGH,X
	STZ ENTITY_BG_HORIZONTAL_VELOCITY_LOW,X
	STZ ENTITY_BG_HORIZONTAL_VELOCITY_HIGH,X
	STZ ENTITY_BG_VERTICAL_VELOCITY_LOW,X
	STZ ENTITY_BG_VERTICAL_VELOCITY_HIGH,X
	STZ ENTITY_BG_HORIZONTAL_OFFSET_LOW,X
	STZ ENTITY_BG_VERTICAL_OFFSET_LOW,X
	STZ ENTITY_DRAW_PRIORITY,X
	DEX
	DEX
	BPL @CLEAR_BG_OFFSETS
	JSR CLEAR_ENTITY_DRAW_SORTING_TABLE
	STZ DISABLE_ACTIONSCRIPT
	RTL
