
INITIATE_ENEMY_ENCOUNTER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA TOUCHED_ENEMY
	STA @LOCAL09
	STZ ENEMY_HAS_BEEN_TOUCHED
	LDA @LOCAL09
	ASL
	STA @LOCAL08
	CLC
	ADC #.LOWORD(ENTITY_MOVING_DIRECTIONS)
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	CMP #8
	BNE @CALC_DIRECTION
	LDY #0
	LDX #1
	BRA @DETERMINE_INITIATIVE
@CALC_DIRECTION:
	LDA ENEMY_PATHFINDING_TARGET_ENTITY
	ASL
	TAX
	LDA ENTITY_ABS_Y_TABLE,X
	STA @LOCAL00
	LDY ENTITY_ABS_X_TABLE,X
	LDA @LOCAL08
	TAX
	LDA ENTITY_ABS_Y_TABLE,X
	TAX
	STX @LOCAL07
	LDA @LOCAL08
	TAX
	LDA ENTITY_ABS_X_TABLE,X
	LDX @LOCAL07
	JSL CALCULATE_DIRECTION_FROM_POSITIONS
	LDY #$2000
	CLC
	ADC #$1000
	JSL DIVISION16S_DIVISOR_POSITIVE
	STA @VIRTUAL04
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	SEC
	SBC @VIRTUAL04
	AND #$0007
	BEQ @ENEMY_BEHIND_PLAYER
	CMP #1
	BEQ @ENEMY_BEHIND_PLAYER
	CMP #7
	BNE @ENEMY_NOT_BEHIND
@ENEMY_BEHIND_PLAYER:
	LDY #1
	BRA @CHECK_PLAYER_FACING
@ENEMY_NOT_BEHIND:
	LDY #0
@CHECK_PLAYER_FACING:
	LDA GAME_STATE+game_state::leader_direction
	SEC
	SBC @VIRTUAL04
	AND #$0007
	BEQ @PLAYER_FACING_ENEMY
	CMP #1
	BEQ @PLAYER_FACING_ENEMY
	CMP #7
	BNE @PLAYER_NOT_FACING
@PLAYER_FACING_ENEMY:
	LDX #0
	BRA @DETERMINE_INITIATIVE
@PLAYER_NOT_FACING:
	LDX #1
@DETERMINE_INITIATIVE:
	STZ BATTLE_INITIATIVE
	CPX #1
	BNE @CHECK_ENEMIES_FIRST
	CPY #0
	BNE @CHECK_ENEMIES_FIRST
	LDA #INITIATIVE::PARTY_FIRST
	STA BATTLE_INITIATIVE
@CHECK_ENEMIES_FIRST:
	CPY #1
	BNE @SETUP_BATTLE_GROUP
	CPX #0
	BNE @SETUP_BATTLE_GROUP
	LDA #INITIATIVE::ENEMIES_FIRST
	STA BATTLE_INITIATIVE
@SETUP_BATTLE_GROUP:
	LDA #120
	STA BATTLE_SWIRL_COUNTDOWN
	LDA @LOCAL09
	ASL
	TAX
	LDA ENTITY_NPC_IDS,X
	AND #$7FFF
	STA @LOCAL06
	STA CURRENT_BATTLE_GROUP
	LOADPTR BTL_ENTRY_PTR_TABLE, @VIRTUAL0A
	LDA @LOCAL06
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	JSL BATTLE_SWIRL_SEQUENCE
	LDA #0
	STA @VIRTUAL04
	JMP @MARK_ENEMIES_LOOP_COND
@MARK_ENEMIES_LOOP_BODY:
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	STA @VIRTUAL02
	CMP #$00FF
	BEQ @ENTRY_END_MARKER
	LDY #0
	LDA @VIRTUAL02
	STA @LOCAL06
	BEQ @ADVANCE_GROUP_PTR
	LDY #1
	LDA [@VIRTUAL06],Y
	TAY
	LDA @LOCAL09
	ASL
	TAX
	TYA
	CMP ENTITY_ENEMY_IDS,X
	BNE @CHECK_REMAINING_COUNT
	LDA #.LOWORD(-1)
	STA ENTITY_PATHFINDING_STATES,X
	LDA @LOCAL06
	DEC
	STA @LOCAL06
@CHECK_REMAINING_COUNT:
	LDA @LOCAL06
	BEQ @ADVANCE_GROUP_PTR
	LDA #0
	STA @LOCAL05
	BRA @SCAN_ENTITIES_COND
@SCAN_ENTITIES_BODY:
	ASL
	TAX
	LDA ENTITY_SCRIPT_TABLE,X
	CMP #.LOWORD(-1)
	BEQ @NEXT_ENTITY
	TYA
	CMP ENTITY_ENEMY_IDS,X
	BNE @NEXT_ENTITY
	LDA #.LOWORD(-1)
	STA ENTITY_PATHFINDING_STATES,X
@NEXT_ENTITY:
	LDA @LOCAL05
	INC
	STA @LOCAL05
@SCAN_ENTITIES_COND:
	CMP #23
	BNE @SCAN_ENTITIES_BODY
@ADVANCE_GROUP_PTR:
	LDA #3
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	BRA @STORE_ENTRY_RESULTS
@ENTRY_END_MARKER:
	LDY #0
	TYA
	STA @VIRTUAL02
@STORE_ENTRY_RESULTS:
	LDA @VIRTUAL04
	ASL
	TAX
	TYA
	STA PATHFINDING_ENEMY_IDS,X
	LDA @VIRTUAL02
	STA PATHFINDING_ENEMY_COUNTS,X
	INC @VIRTUAL04
@MARK_ENEMIES_LOOP_COND:
	LDA @VIRTUAL04
	CMP #4
	BNEL @MARK_ENEMIES_LOOP_BODY
	STZ ENEMIES_IN_BATTLE
	LDY #64
	TYX
	LDA GAME_STATE+game_state::party_count
	AND #$00FF
	JSL FIND_PATH_TO_PARTY
	LDA #.LOWORD(PATHFINDING_STATE)
	STA @LOCAL04
	LOADPTR BTL_ENTRY_PTR_TABLE, @VIRTUAL0A
	LDA CURRENT_BATTLE_GROUP
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	STZ @LOCAL08
	JMP @CLEANUP_LOOP_COND
@CLEANUP_LOOP_BODY:
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	TAX
	STX @LOCAL03
	CPX #$00FF
	BEQL @NEXT_GROUP_ENTRY
	CPX #0
	BEQL @ADVANCE_CLEANUP_PTR
	LDY #1
	LDA [@VIRTUAL06],Y
	STA @LOCAL06
	CPX #0
	BEQL @ADVANCE_CLEANUP_PTR
	LDA #0
	STA @LOCAL05
	TAY
	STY @LOCAL02
	BRA @COUNT_PATHFINDERS_COND
@COUNT_PATHFINDERS_BODY:
	LDY @LOCAL02
	TYA
	STA @VIRTUAL04
	ASL
	ASL
	ASL
	ADC @VIRTUAL04
	ASL
	CLC
	ADC @LOCAL04
	TAX
	LDA a:pathfinding::pathfinders + pathfinder::object_index,X
	ASL
	TAX
	LDA ENTITY_ENEMY_IDS,X
	CMP @LOCAL06
	BNE @NEXT_PATHFINDER
	LDA @LOCAL05
	INC
	STA @LOCAL05
@NEXT_PATHFINDER:
	INY
	STY @LOCAL02
@COUNT_PATHFINDERS_COND:
	TYA
	LDY #pathfinding::pathfinder_count
	CMP (@LOCAL04),Y
	BCC @COUNT_PATHFINDERS_BODY
	LDX @LOCAL03
	STX @VIRTUAL02
	LDA @LOCAL05
	CMP @VIRTUAL02
	BCS @REMOVE_EXCESS_ENEMIES
	JMP @ADVANCE_CLEANUP_PTR
@REMOVE_EXCESS_ENEMIES:
	STX @VIRTUAL02
	SEC
	SBC @VIRTUAL02
	STA @VIRTUAL04
	STA @LOCAL02
	JMP @REMOVE_LOOP_COND
@FIND_BEST_TO_REMOVE:
	LDA #.LOWORD(-1)
	STA @VIRTUAL02
	STA @LOCAL01
	LDY #0
	STY @LOCAL03
	TYA
	STA @LOCAL05
	BRA @FIND_BEST_SCAN_COND
@FIND_BEST_SCAN_BODY:
	OPTIMIZED_MULT @VIRTUAL04, 18
	CLC
	ADC @LOCAL04
	TAX
	STX @LOCAL07
	LDA a:pathfinding::pathfinders + pathfinder::object_index,X
	ASL
	TAX
	LDA ENTITY_ENEMY_IDS,X
	CMP @LOCAL06
	BNE @NEXT_PATHFINDER_SCAN
	LDX @LOCAL07
	LDA a:pathfinding::pathfinders + pathfinder::unknown14,X
	TAX
	LDY @LOCAL03
	STY @VIRTUAL02
	TXA
	CMP @VIRTUAL02
	BLTEQ @NEXT_PATHFINDER_SCAN
	LDA @LOCAL05
	STA @VIRTUAL02
	STA @LOCAL01
	TXY
	STY @LOCAL03
@NEXT_PATHFINDER_SCAN:
	LDA @LOCAL05
	INC
	STA @LOCAL05
@FIND_BEST_SCAN_COND:
	LDY #pathfinding::pathfinder_count
	CMP (@LOCAL04),Y
	BCC @FIND_BEST_SCAN_BODY
	LDA @LOCAL01
	STA @VIRTUAL02
	OPTIMIZED_MULT @VIRTUAL04, 18
	CLC
	ADC @LOCAL04
	STA @LOCAL03
	CLC
	ADC #pathfinding::pathfinders + pathfinder::object_index
	TAX
	STX @LOCAL05
	LDA __BSS_START__,X
	CMP @LOCAL09
	BEQ @REMOVE_LOOP_COND
	LDA @LOCAL03
	TAX
	STZ a:pathfinding::pathfinders + pathfinder::unknown14,X
	LDX @LOCAL05
	LDA __BSS_START__,X
	ASL
	TAX
	STZ ENTITY_PATHFINDING_STATES,X
@REMOVE_LOOP_COND:
	LDA @LOCAL02
	STA @VIRTUAL04
	LDX @VIRTUAL04
	LDA @VIRTUAL04
	DEC
	STA @VIRTUAL04
	STA @LOCAL02
	CPX #0
	BNEL @FIND_BEST_TO_REMOVE
@ADVANCE_CLEANUP_PTR:
	LDA #3
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
@NEXT_GROUP_ENTRY:
	INC @LOCAL08
@CLEANUP_LOOP_COND:
	LDA @LOCAL08
	CMP #4
	BNEL @CLEANUP_LOOP_BODY
	LDA #0
	STA @LOCAL05
	BRA @ENTITY_STATE_LOOP_COND
@ENTITY_STATE_LOOP_BODY:
	CMP @LOCAL09
	BEQ @NEXT_ENTITY_STATE
	ASL
	TAX
	LDA ENTITY_PATHFINDING_STATES,X
	CMP #.LOWORD(-1)
	BNE @HIDE_ENTITY_SPRITE
	TXA
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	AND #$FFFF ^ (OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED)
	STA __BSS_START__,X
	BRA @NEXT_ENTITY_STATE
@HIDE_ENTITY_SPRITE:
	TXA
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #$8000
	STA __BSS_START__,X
@NEXT_ENTITY_STATE:
	LDA @LOCAL05
	INC
	STA @LOCAL05
@ENTITY_STATE_LOOP_COND:
	CMP #23
	BNE @ENTITY_STATE_LOOP_BODY
	LDA @LOCAL09
	ASL
	TAX
	STZ ENTITY_PATHFINDING_STATES,X
	LDA ENEMIES_IN_BATTLE
	ASL
	PHA
	LDA ENTITY_ENEMY_IDS,X
	PLX
	STA ENEMIES_IN_BATTLE_IDS,X
	INC ENEMIES_IN_BATTLE
	PLD
	RTL
