
;  Initializes an entity along with other entity vars
; A = actipn script, X,Y = coordinates
INIT_ENTITY_WIPE:
	PHA
	STZ NEW_ENTITY_POS_Z
	STZ NEW_ENTITY_VAR0
	STZ NEW_ENTITY_VAR1
	STZ NEW_ENTITY_VAR2
	STZ NEW_ENTITY_VAR3
	STZ NEW_ENTITY_VAR4
	STZ NEW_ENTITY_VAR5
	STZ NEW_ENTITY_VAR6
	STZ NEW_ENTITY_VAR7
	STZ NEW_ENTITY_PRIORITY
	LDA #$0000
	STA ENTITY_ALLOCATION_MIN_SLOT
	LDA #$001E
	STA ENTITY_ALLOCATION_MAX_SLOT
	PLA
; Initializes an entity
;A = action script, X,Y = coordinates
INIT_ENTITY:
	PHA
	PHY
	PHX
	LDA ENTITY_ALLOCATION_MIN_SLOT
	ASL
	STA ENTITY_ALLOCATION_MIN_SLOT
	LDA ENTITY_ALLOCATION_MAX_SLOT
	ASL
	STA ENTITY_ALLOCATION_MAX_SLOT
	JSR ALLOCATE_ENTITY_SLOT
	BCC @ALLOC_SUCCESS
	PLA
	PLA
	PLA
	LDA #$0000
	RTL
@ALLOC_SUCCESS:
	JSR ALLOCATE_ENTITY_SCRIPT_SLOT
	TYA
	STA ENTITY_SCRIPT_INDEX_TABLE,X
	LDA #$FFFF
	STA ENTITY_SCRIPT_NEXT_SCRIPTS,Y
	LDA #.LOWORD(APPLY_ENTITY_DELTA_POSITION_ENTRY2)
	STA ENTITY_MOVE_CALLBACK,X
	LDA #.LOWORD(ENTITY_SCREEN_COORDS_BG1)
	STA ENTITY_SCREEN_POSITION_CALLBACK,X
	LDA #.LOWORD(DRAW_ENTITY_SPRITE)
	STA ENTITY_DRAW_CALLBACK,X
	LDA NEW_ENTITY_VAR0
	STA ENTITY_SCRIPT_VAR0_TABLE,X
	LDA NEW_ENTITY_VAR1
	STA ENTITY_SCRIPT_VAR1_TABLE,X
	LDA NEW_ENTITY_VAR2
	STA ENTITY_SCRIPT_VAR2_TABLE,X
	LDA NEW_ENTITY_VAR3
	STA ENTITY_SCRIPT_VAR3_TABLE,X
	LDA NEW_ENTITY_VAR4
	STA ENTITY_SCRIPT_VAR4_TABLE,X
	LDA NEW_ENTITY_VAR5
	STA ENTITY_SCRIPT_VAR5_TABLE,X
	LDA NEW_ENTITY_VAR6
	STA ENTITY_SCRIPT_VAR6_TABLE,X
	LDA NEW_ENTITY_VAR7
	STA ENTITY_SCRIPT_VAR7_TABLE,X
	LDA NEW_ENTITY_PRIORITY
	STA ENTITY_DRAW_PRIORITY,X
	LDA #$8000
	STA ENTITY_ABS_X_FRACTION_TABLE,X
	STA ENTITY_ABS_Y_FRACTION_TABLE,X
	STA ENTITY_ABS_Z_FRACTION_TABLE,X
	PLA
	STA ENTITY_ABS_X_TABLE,X
	STA ENTITY_SCREEN_X_TABLE,X
	PLA
	STA ENTITY_ABS_Y_TABLE,X
	STA ENTITY_SCREEN_Y_TABLE,X
	LDA NEW_ENTITY_POS_Z
	STA ENTITY_ABS_Z_TABLE,X
	JSR LINK_ENTITY_TO_LIST
	PLA
	BRA @INIT_SCRIPT_PC
	PHA
	JSR FREE_ENTITY_SCRIPTS
	JSR ALLOCATE_ENTITY_SCRIPT_SLOT
	TYA
	STA ENTITY_SCRIPT_INDEX_TABLE,X
	LDA #$FFFF
	STA ENTITY_SCRIPT_NEXT_SCRIPTS,Y
	PLA
@INIT_SCRIPT_PC:
	STA ENTITY_SCRIPT_TABLE,X
	PHX
	ASL
	ADC ENTITY_SCRIPT_TABLE,X
	TXY
	TAX
	LDA f:EVENT_SCRIPT_POINTERS+2,X
	TAY
	LDA f:EVENT_SCRIPT_POINTERS,X
	PLX
	STZ ENTITY_ANIMATION_FRAME,X
	DEC ENTITY_ANIMATION_FRAME,X
	STZ ENTITY_DELTA_X_FRACTION_TABLE,X
	STZ ENTITY_DELTA_X_TABLE,X
	STZ ENTITY_DELTA_Y_FRACTION_TABLE,X
	STZ ENTITY_DELTA_Y_TABLE,X
	STZ ENTITY_DELTA_Z_FRACTION_TABLE,X
	STZ ENTITY_DELTA_Z_TABLE,X
	BRA INIT_SCRIPT_PC_SHARED
REASSIGN_ENTITY_SCRIPT_FAR:
	PHA
	TXA
	ASL
	TAX
	PLA
	JSL REASSIGN_ENTITY_SCRIPT
	RTL
REASSIGN_ENTITY_SCRIPT:
	PHY
	PHA
	LDA ENTITY_SCRIPT_TABLE,X
	BPL @DONT_LOOP
@LOOP:
	BRA @LOOP
@DONT_LOOP:
	JSR FREE_ENTITY_SCRIPTS
	JSR ALLOCATE_ENTITY_SCRIPT_SLOT
	TYA
	STA ENTITY_SCRIPT_INDEX_TABLE,X
	LDA #$FFFF
	STA ENTITY_SCRIPT_NEXT_SCRIPTS,Y
	PLA
	PLY
INIT_SCRIPT_PC_SHARED:
	PHY
	PHA
	JSR CLEAR_SPRITE_TICK_CALLBACK
	TXY
	LDX ENTITY_SCRIPT_INDEX_TABLE,Y
	PLA
	STA ENTITY_SCRIPT_PROGRAM_COUNTERS,X
	PLA
	AND #$00FF
	STA ENTITY_SCRIPT_PROGRAM_COUNTER_BANKS,X
	STZ ENTITY_SCRIPT_SLEEP_FRAMES,X
	STZ ENTITY_SCRIPT_STACK_OFFSETS,X
	TYA
	LSR
	CLC
MOVEMENT_NOP:
	RTL
