
INITIALIZE_PARTY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA GAME_STATE+game_state::player_controlled_party_count
	STA GAME_STATE+game_state::party_count
	REP #PROC_FLAGS::ACCUM8
	LDA #0
	STA @LOCAL00
	BRA @CLEAR_LOOP_CHECK
@CLEAR_SLOT:
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ __BSS_START__+game_state::party_order,X
	STZ __BSS_START__+game_state::player_controlled_party_members,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	ASL
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	STZ a:game_state::party_entity_slots,X
.ELSE
	TAX
	STZ GAME_STATE + game_state::party_entity_slots,X
.ENDIF
	LDA @LOCAL00
	INC
	STA @LOCAL00
@CLEAR_LOOP_CHECK:
	CMP #TOTAL_PARTY_COUNT
	BCC @CLEAR_SLOT
	LDA #1
	STA UNREAD_7E5D7E
	LDX #0
	STX @LOCAL00
	BRA @ADD_LOOP_CHECK
@ADD_MEMBER:
.IF .DEFINED(JPN)
	TXA
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
.ELSE
	LDA GAME_STATE + game_state::party_members,X
.ENDIF
	AND #$00FF
	BEQ @DONE
	AND #$00FF
	JSL ADD_PARTY_MEMBER
	LDX @LOCAL00
	INX
	STX @LOCAL00
@ADD_LOOP_CHECK:
	CPX #TOTAL_PARTY_COUNT
	BCC @ADD_MEMBER
@DONE:
	STZ UNREAD_7E5D7E
	LDA GAME_STATE + game_state::character_mode
	ASL
	STA FOOTSTEP_SOUND_ID
	STZ FOOTSTEP_SOUND_ID_OVERRIDE
	END_C_FUNCTION
