
INITIALIZE_MISC_OBJECT_DATA:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	LDY #0
	BRA @LOOP_CHECK
@LOOP:
	TYA
	ASL
	TAX
	STZ ENTITY_MOVEMENT_SPEEDS,X
	LDA #ENTITY_COLLISION_NO_OBJECT
	STA ENTITY_COLLIDED_OBJECTS,X
	STA ENTITY_NPC_IDS,X
	INY
@LOOP_CHECK:
	CPY #MAX_ENTITIES
	BCC @LOOP
	END_C_FUNCTION
