
INIT_BUTTERFLY_MOVEMENT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDY CURRENT_ENTITY_SLOT
	STY @LOCAL02
	TYA
	ASL
	TAX
	STX @LOCAL01
	LDA ENTITY_ABS_X_TABLE,X
	STA ENTITY_SCRIPT_VAR6_TABLE,X
	LDA ENTITY_ABS_Y_TABLE,X
	CLC
	ADC #16
	STA ENTITY_SCRIPT_VAR7_TABLE,X
	STZ @LOCAL00 + fixed_point::fraction
	LDA ENTITY_MOVEMENT_SPEEDS,X
	LSR
	LSR
	LSR
	LSR
	STA @LOCAL00 + fixed_point::integer
	MOVE_INT_CONSTANT $64800, @VIRTUAL0A
	MOVE_INT @LOCAL00, @VIRTUAL06
	JSL DIVISION32
	LDA @VIRTUAL06
	XBA
	AND #$FF00
	STA ENTITY_SCRIPT_VAR5_TABLE,X
	JSL RAND
	AND #$0001
	BEQ @SET_DOWN
	LDX @LOCAL01
	STZ ENTITY_DIRECTIONS,X
	BRA @CHECK_Y_DIRECTION
@SET_DOWN:
	LDA #DIRECTION::DOWN
	LDX @LOCAL01
	STA ENTITY_DIRECTIONS,X
@CHECK_Y_DIRECTION:
	LDY @LOCAL02
	TYA
	ASL
	TAX
	LDA ENTITY_DIRECTIONS,X
	CMP #DIRECTION::DOWN
	BCS @MOVING_UP
	STZ ENTITY_BUTTERFLY_ORBIT_DIRECTION,X
	BRA @CLEAR_VAR4
@MOVING_UP:
	LDA #.LOWORD(-1)
	STA ENTITY_BUTTERFLY_ORBIT_DIRECTION,X
@CLEAR_VAR4:
	TYA
	ASL
	TAX
	STZ ENTITY_SCRIPT_VAR4_TABLE,X
	END_C_FUNCTION
