
INIT_DELIVERY_SEQUENCE:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	LDA #1
	STA OVERWORLD_STATUS_SUPPRESSION
	STA PENDING_INTERACTIONS
	JSL DISABLE_OTHER_ENTITY_CALLBACKS
	LDA #MUSIC::DELIVERY
	JSL CHANGE_MUSIC
	JSL DISMOUNT_BICYCLE
	END_C_FUNCTION
