
IS_BATTLE_PENDING:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA BATTLE_SWIRL_COUNTDOWN
	BNE @BATTLE_PENDING
	LDA ENEMY_HAS_BEEN_TOUCHED
	BEQ @NO_BATTLE
@BATTLE_PENDING:
	LDA #$0001
	BRA @RETURN
@NO_BATTLE:
	LDA #$0000
@RETURN:
	RTL
