
IS_ENTITY_NEAR_LEADER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA PSI_TELEPORT_SPEED + fixed_point::integer
	CMP #04
	BCC @CHECK_POSITION
	LDA #.LOWORD(-1)
	BRA @RETURN
@CHECK_POSITION:
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA GAME_STATE+game_state::leader_x_coord
	SEC
	SBC #128
	STA @VIRTUAL02
	LDA ENTITY_ABS_X_TABLE,X
	SEC
	SBC @VIRTUAL02
	STA @LOCAL00
	LDA GAME_STATE+game_state::leader_y_coord
	SEC
	SBC #112
	STA @VIRTUAL02
	LDA ENTITY_ABS_Y_TABLE,X
	SEC
	SBC @VIRTUAL02
	TAX
	LDA @LOCAL00
	CMP #.LOWORD(-64)
	BCS @CHECK_Y
	CMP #320
	BCS @OFF_SCREEN
@CHECK_Y:
	CPX #.LOWORD(-64)
	BCS @ON_SCREEN
	CPX #320
	BCS @OFF_SCREEN
@ON_SCREEN:
	LDA #.LOWORD(-1)
	BRA @RETURN
@OFF_SCREEN:
	LDA #0
@RETURN:
	END_C_FUNCTION
