
IS_ENTITY_ON_SCREEN:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	STX @LOCAL00
	LDA ENTITY_SIZES,X
	ASL
	TAY
	LDA ENTITY_SCREEN_X_TABLE,X
	TYX
	SEC
	SBC f:ENTITY_COLLISION_X_OFFSET,X
	STA @VIRTUAL04
	LDX @LOCAL00
	LDA ENTITY_SCREEN_Y_TABLE,X
	STA @LOCAL00
	TYX
	SEC
	SBC f:ENTITY_COLLISION_Y_OFFSET,X
	STA @VIRTUAL02
	LDA @LOCAL00
	CLC
	ADC #8
	PHA
	LDA @VIRTUAL04
	ORA @VIRTUAL04
	ORA @VIRTUAL02
	PLY
	STY @VIRTUAL02
	ORA @VIRTUAL02
	AND #$FF00
	BEQ @ON_SCREEN
	LDA #0
	BRA @RETURN
@ON_SCREEN:
	LDA #.LOWORD(-1)
@RETURN:
	END_C_FUNCTION
