
IS_VALID_ITEM_TRANSFORMATION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDY #0
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(loaded_timed_item_transformation)
	TAX
	LDA LOADED_TIMED_ITEM_TRANSFORMATIONS + loaded_timed_item_transformation::transformation_countdown,X
	AND #$00FF
	BNE @IS_VALID
	LDA LOADED_TIMED_ITEM_TRANSFORMATIONS + loaded_timed_item_transformation::sfx_frequency,X
	AND #$00FF
	BEQ @RETURN
@IS_VALID:
	LDY #1
@RETURN:
	TYA
	END_C_FUNCTION
