
LINK_ENTITY_TO_LIST:
	LDA #$FFFF
	STA ENTITY_NEXT_ENTITY_TABLE,X
	TXA
	LDX FIRST_ENTITY
	BPL @FIND_TAIL
	STA FIRST_ENTITY
	BRA @RESTORE_X
@FIND_TAIL:
	TXY
	LDX ENTITY_NEXT_ENTITY_TABLE,Y
	BPL @FIND_TAIL
	STA ENTITY_NEXT_ENTITY_TABLE,Y
@RESTORE_X:
	TAX
	RTS
