
LOAD_SPECIAL_SPRITE_PALETTE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 2
	LDA __BSS_START__ + BPP4PALETTE_SIZE * 2,X
	BEQ @DONE
	OPTIMIZED_MULT @VIRTUAL04, BPP4PALETTE_SIZE
	CLC
	ADC #.LOWORD(PALETTES)
	TAX
	STX @LOCAL01
	LDA #(BPP4PALETTE_SIZE * 4) / 2 ;goes by colour count, not size
	STA @LOCAL00
	BRA @LOOP_CHECK
@LOOP:
	ASL
	PHA
	LDA __BSS_START__,X
	PLX
	STA PALETTES + BPP4PALETTE_SIZE * 8,X
	LDX @LOCAL01
	INX
	INX
	STX @LOCAL01
	LDA @LOCAL00
	INC
	STA @LOCAL00
@LOOP_CHECK:
	CMP #(BPP4PALETTE_SIZE * 5) / 2
	BCC @LOOP
@DONE:
	END_C_FUNCTION
