
LOAD_MAP_PAL:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int
	END_STACK_VARS
	STA @LOCAL05
	LDY #3 * 192
	STY @LOCAL04
	LOADPTR MAP_PALETTE_PTR_TABLE, @VIRTUAL06
	LDA @LOCAL05
	ASL
	ASL
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL06
	TXA
	LDY #BPP4PALETTE_SIZE * 6
	JSL MULT168
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL02
	LDA @VIRTUAL06+2
	STA @LOCAL02+2
	LDA PHOTOGRAPH_MAP_LOADING_MODE
	BNE @PHOTOGRAPH_MODE
@LOAD_PALETTE:
	MOVE_INT @LOCAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #BPP4PALETTE_SIZE * 6
	LDY @LOCAL04
	TYA
	JSL MEMCPY16
	LDY @LOCAL04
	LDA __BSS_START__,Y
	BEQL @RETURN
	AND #$7FFF
	JSL GET_EVENT_FLAG
	STA @LOCAL03
	LDX #0
	LDY @LOCAL04
	LDA __BSS_START__,Y
	CMP #EVENT_FLAG_UNSET
	BLTEQ @FLAG_SET
	LDX #1
@FLAG_SET:
	STX @VIRTUAL02
	LDA @LOCAL03
	CMP @VIRTUAL02
	BNEL @RETURN
	MOVE_INT f:MAP_PALETTE_PTR_TABLE, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	LDA __BSS_START__ + BPP4PALETTE_SIZE * 1,Y
	STA @LOCAL02
	BRA @LOAD_PALETTE
@PHOTOGRAPH_MODE:
	LOADPTR BUFFER, @VIRTUAL06
	LOADPTR COMPRESSED_PHOTOGRAPH_PALETTES, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DECOMP
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	LDA CUR_PHOTO_DISPLAY
	LDY #.SIZEOF(photographer_config_entry)
	JSL MULT168
	CLC
	ADC #photographer_config_entry::credits_map_palettes_offset
	TAX
	LDA f:PHOTOGRAPHER_CFG_TABLE,X
	STORE_INT1632 @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #BPP4PALETTE_SIZE * 6
	LDY @LOCAL04
	TYA
	JSL MEMCPY16
@RETURN:
	END_C_FUNCTION
