
LOAD_MAP_BLOCK_EVENT_CHANGES:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL01
	LOADPTR EVENT_CONTROL_PTR_TABLE & $FF0000, @VIRTUAL06
	LDA @LOCAL01
	ASL
	TAX
	LDA f:EVENT_CONTROL_PTR_TABLE,X
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
@PROCESS_ENTRY:
	LDA [@VIRTUAL06] ;map_tile_event::event_flag
	BEQ @RETURN
	AND #$7FFF
	JSL GET_EVENT_FLAG
	STA @LOCAL00
	LDY #map_tile_event::count
	LDA [@VIRTUAL06],Y
	TAY
	STY @LOCAL01
	LDX #0
	LDA [@VIRTUAL06]
	CMP #$8000
	BCC @CHECK_FLAG_VALUE
	LDX #1
@CHECK_FLAG_VALUE:
	STX @VIRTUAL02
	LDA @LOCAL00
	CMP @VIRTUAL02
	BNE @SKIP_ENTRY
	LDA #map_tile_event::block_pairs
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	BRA @REPLACE_LOOP_CHECK
@REPLACE_BLOCK:
	LDY #map_tile_event::count
	LDA [@VIRTUAL06],Y
	TAX
	LDA [@VIRTUAL06]
	JSR REPLACE_BLOCK
	LDA #map_tile_event::block_pairs
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDY @LOCAL01
	DEY
	STY @LOCAL01
@REPLACE_LOOP_CHECK:
	CPY #0
	BNE @REPLACE_BLOCK
	BRA @PROCESS_ENTRY
@SKIP_ENTRY:
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 4
	OPTIMIZED_ADD 4
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	BRA @PROCESS_ENTRY
@RETURN:
	END_C_FUNCTION
