
;void LoadMapAtSector(int sector_x, int sector_y)
LOAD_MAP_AT_SECTOR:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int x
	STACK_RESERVE_PARAM_INT16 ;int y
	END_STACK_VARS
	STA @LOCAL04
	LDA CURRENT_TELEPORT_DESTINATION_X
	ORA CURRENT_TELEPORT_DESTINATION_Y
	BEQ @AFTER_TELEPORT
	LDA CURRENT_TELEPORT_DESTINATION_X
	LSR
	LSR
	LSR
	LSR
	LSR
	STA @LOCAL04
	LDA CURRENT_TELEPORT_DESTINATION_Y
	LSR
	LSR
	LSR
	LSR
	TAX
@AFTER_TELEPORT:
	LDA @LOCAL04
	STA @VIRTUAL02
	TXA
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL02
	TAX
	LDA f:GLOBAL_MAP_TILESETPALETTE_DATA,X
	AND #$00FF
	STA @LOCAL04
	AND #$0007
	STA @LOCAL03
	LDA @LOCAL04
	LSR
	LSR
	LSR
	STA @VIRTUAL04
	ASL
	TAX
	LDA f:TILESET_TABLE,X
	TAY
	STY @LOCAL02
	TYA
	ASL
	ASL
	STA @VIRTUAL02
	LOADPTR MAP_DATA_TILE_ARRANGEMENT_PTR_TABLE, @VIRTUAL0A
	LDA @VIRTUAL02
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LOADPTR BUFFER + $8000, @LOCAL01
	JSL DECOMP
	LDY @LOCAL02
	TYA
	JSR LOAD_TILE_COLLISION
	LDY @LOCAL02
	TYA
	JSL LOAD_MAP_BLOCK_EVENT_CHANGES
	JSL PREPARE_AVERAGE_FOR_SPRITE_PALETTES
	LOADPTR SPRITE_GROUP_PALETTES, @LOCAL00
	LDX #BPP4PALETTE_SIZE * 8
	LDA #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 8
	JSL MEMCPY16
	LDA @VIRTUAL04
	CMP LOADED_MAP_TILE_COMBO
	BEQ @WAIT_FADE_PALETTE
	LDY @LOCAL02
	STY LOADED_MAP_TILESET
	LOADPTR MAP_DATA_TILESET_PTR_TABLE, @VIRTUAL0A
	LDA @VIRTUAL02
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LOADPTR BUFFER, @LOCAL01
	JSL DECOMP
@WAIT_FADE_TILESET:
	LDA FADE_PARAMETERS + fade_parameters::step
	AND #$00FF
	BNE @WAIT_FADE_TILESET
	LDA PHOTOGRAPH_MAP_LOADING_MODE
	BNE @PHOTOGRAPH_TILESET
	COPY_TO_VRAM3 BUFFER, $0000, $7000, 0
	BRA @WAIT_FADE_PALETTE
@PHOTOGRAPH_TILESET:
	.A16
	COPY_TO_VRAM3 BUFFER, $0000, $4000, 0
@WAIT_FADE_PALETTE:
	.A16
	LDA FADE_PARAMETERS + fade_parameters::step
	AND #$00FF
	BNE @WAIT_FADE_PALETTE
	LDX @LOCAL03
	LDA @VIRTUAL04
	JSL LOAD_MAP_PAL
	JSL ADJUST_SPRITE_PALETTES_BY_AVERAGE
	JSL LOAD_SPECIAL_SPRITE_PALETTE
	LDA PHOTOGRAPH_MAP_LOADING_MODE
	BNE @AFTER_OVERLAY
	JSL LOAD_OVERLAY_SPRITES
	JSR LOAD_TILESET_ANIM
	JSR LOAD_PALETTE_ANIM
@AFTER_OVERLAY:
	LDA PHOTOGRAPH_MAP_LOADING_MODE
	BNE @BACKUP_PALETTE
	LDA DEBUG
	BEQ @NO_DEBUG
	JSL INIT_DEBUG_MODE_DISPLAY
	BRA @UPLOAD_PALETTES
@NO_DEBUG:
	JSL LOAD_CHARACTER_WINDOW_PALETTE
@UPLOAD_PALETTES:
	LDA #0
	JSL SET_PALETTE_UPLOAD_MODE
@BACKUP_PALETTE:
	.A16
	PROMOTENEARPTR PALETTES, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	LDA #64
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDX #BPP4PALETTE_SIZE * 14
	LDA #.LOWORD(MAP_PALETTE_BACKUP)
	JSL MEMCPY16
	LDA WIPE_PALETTES_ON_MAP_LOAD
	BEQ @AFTER_WIPE
	JSL COPY_FADE_BUFFER_TO_PALETTES
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FF
	STA @LOCAL00
	LDX #BPP4PALETTE_SIZE * 16
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(PALETTES)
	JSL MEMSET16
	STZ WIPE_PALETTES_ON_MAP_LOAD
@AFTER_WIPE:
	LDA PHOTOGRAPH_MAP_LOADING_MODE
	BEQ @STORE_LOADED_STATE
	JSL COPY_FADE_BUFFER_TO_PALETTES
	SEP #PROC_FLAGS::ACCUM8
	STZ_BADOPT @LOCAL00
	LDX #BPP4PALETTE_SIZE * 15
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 1
	JSL MEMSET16
@STORE_LOADED_STATE:
	LDA #24
	JSL SET_PALETTE_UPLOAD_MODE
	LDA @VIRTUAL04
	STA LOADED_MAP_TILE_COMBO
	LDA @LOCAL03
	STA LOADED_MAP_PALETTE
	END_C_FUNCTION
