
LOAD_DAD_PHONE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LDA WINDOW_HEAD
	CMP #.LOWORD(-1)
	BNE @RETURN
	LDA BATTLE_MODE_FLAG
	BNE @RETURN
	LDA BATTLE_SWIRL_COUNTDOWN
	BNE @RETURN
	LDA ENEMY_HAS_BEEN_TOUCHED
	BNE @RETURN
	LDA DAD_PHONE_QUEUED
	BNE @RETURN
	LDA #EVENT_FLAG::FLG_SYS_DIS_2H_PAPA
	JSL GET_EVENT_FLAG
	CMP #0
	BNE @RETURN
	LOADPTR MSG_SYS_PAPA_2H, @LOCAL00
	LDA #10
	JSL QUEUE_INTERACTION
	LDA #1
	STA DAD_PHONE_QUEUED
@RETURN:
	END_C_FUNCTION
