
LOAD_MAP_AT_POSITION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int x
	STACK_RESERVE_PARAM_INT16 ;int y
	END_STACK_VARS
	STX @LOCAL04
	STA @LOCAL03
	JSL CLEAR_ALL_ENEMIES
	LDA @LOCAL03
	STA SCREEN_X_PIXELS
	STA SCREEN_X_PIXELS_COPY
	LDX @LOCAL04
	STX SCREEN_Y_PIXELS
	STX SCREEN_Y_PIXELS_COPY
	LSR
	LSR
	LSR
	STA @VIRTUAL02
	TXA
	LSR
	LSR
	LSR
	TAY
	STY @LOCAL02
	TYA
	LSR
	LSR
	LSR
	LSR
	TAX
	LDA @VIRTUAL02
	LSR
	LSR
	LSR
	LSR
	LSR
	JSR LOAD_MAP_AT_SECTOR
	LDA PHOTOGRAPH_MAP_LOADING_MODE
	BNE @AFTER_VRAM_SETUP
	JSL OVERWORLD_SETUP_VRAM
@AFTER_VRAM_SETUP:
	LDA @VIRTUAL02
	SEC
	SBC #16
	STA @LOCAL01
	LDY @LOCAL02
	TYA
	SEC
	SBC #14
	STA @LOCAL03
	LDA @VIRTUAL02
	SEC
	SBC #32
	STA @VIRTUAL04
	TYA
	SEC
	SBC #32
	STA @VIRTUAL02
	STA @LOCAL00
	LDX #0
	BRA @INVALIDATE_LOADED_TILES_CHECK
@INVALIDATE_LOADED_TILES_LOOP:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FF
	STA LOADED_COLUMNS_Y,X
	STA LOADED_COLUMNS_X,X
	STA LOADED_ROWS_Y,X
	STA LOADED_ROWS_X,X
	INX
@INVALIDATE_LOADED_TILES_CHECK:
	CPX #16
	BCC @INVALIDATE_LOADED_TILES_LOOP
	LDY #0
	STY @LOCAL02
	BRA @LOAD_MAP_ROWS_CHECK
@LOAD_MAP_ROWS_LOOP:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	STA @VIRTUAL02
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	TAX
	LDA @VIRTUAL04
	JSR LOAD_MAP_ROW
	LDY @LOCAL02
	INY
	STY @LOCAL02
@LOAD_MAP_ROWS_CHECK:
	CPY #60
	BCC @LOAD_MAP_ROWS_LOOP
	LDY #0
	STY @LOCAL02
	BRA @LOAD_COLLISION_ROWS_CHECK
@LOAD_COLLISION_ROWS_LOOP:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	STA @VIRTUAL02
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	TAX
	LDA @VIRTUAL04
	JSR LOAD_COLLISION_ROW
	LDY @LOCAL02
	INY
	STY @LOCAL02
@LOAD_COLLISION_ROWS_CHECK:
	CPY #60
	BCC @LOAD_COLLISION_ROWS_LOOP
@WAIT_FOR_FADE:
	REP #PROC_FLAGS::ACCUM8
	LDA FADE_PARAMETERS + fade_parameters::step
	AND #$00FF
	BNE @WAIT_FOR_FADE
	LDA PHOTOGRAPH_MAP_LOADING_MODE
	BNE @AFTER_TM_SETUP
	SEP #PROC_FLAGS::ACCUM8
	LDA #$17
	STA TM_MIRROR
@AFTER_TM_SETUP:
	REP #PROC_FLAGS::ACCUM8
	LDA NPC_SPAWNS_ENABLED
	BEQ @AFTER_NPC_SPAWNS_CLAMP
	LDA #1
	STA NPC_SPAWNS_ENABLED
@AFTER_NPC_SPAWNS_CLAMP:
	LDA SCREEN_X_PIXELS
	SEC
	SBC #128
	STA BG2_X_POS
	STA BG1_X_POS
	LDA SCREEN_Y_PIXELS
	SEC
	SBC #112
	STA BG2_Y_POS
	STA BG1_Y_POS
	LDY #.LOWORD(-1)
	STY @LOCAL02
	BRA @UPLOAD_ROWS_AND_SPAWN_NPCS_CHECK
@UPLOAD_ROWS_AND_SPAWN_NPCS_LOOP:
	TYA
	CLC
	ADC @LOCAL03
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA @LOCAL01
	JSR LOAD_MAP_ROW_TO_VRAM
	LDX @VIRTUAL02
	LDA @LOCAL01
	JSL SPAWN_NPCS_IN_ROW
	LDY @LOCAL02
	INY
	STY @LOCAL02
@UPLOAD_ROWS_AND_SPAWN_NPCS_CHECK:
	CPY #31
	BNE @UPLOAD_ROWS_AND_SPAWN_NPCS_LOOP
	LDY #.LOWORD(-8)
	STY @LOCAL02
	BRA @SPAWN_HORIZONTAL_NPCS_CHECK
@SPAWN_HORIZONTAL_NPCS_LOOP:
	TYA
	CLC
	ADC @LOCAL03
	TAX
	LDA @LOCAL01
	SEC
	SBC #8
	JSL SPAWN_HORIZONTAL
	LDY @LOCAL02
	INY
	STY @LOCAL02
@SPAWN_HORIZONTAL_NPCS_CHECK:
	CPY #40
	BNE @SPAWN_HORIZONTAL_NPCS_LOOP
	LDA NPC_SPAWNS_ENABLED
	BEQ @AFTER_NPC_SPAWNS_RESTORE
	LDA #.LOWORD(-1)
	STA NPC_SPAWNS_ENABLED
@AFTER_NPC_SPAWNS_RESTORE:
	LDA @LOCAL01
	STA SCREEN_LEFT_X
	LDA @LOCAL03
	STA SCREEN_TOP_Y
	END_C_FUNCTION
