
NPC_COLLISION_CHECK:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @LOCAL07
	STA @VIRTUAL02
	LDA #ENTITY_COLLISION_NO_OBJECT
	STA @LOCAL06
	TYA
	ASL
	TAX
	LDA ENTITY_HITBOX_ENABLED,X
	BEQL @RETURN
	LDA PLAYER_MOVEMENT_FLAGS
	AND #$0002
	BNEL @RETURN
	LDA GAME_STATE+game_state::walking_style
	CMP #WALKING_STYLE::ESCALATOR
	BEQL @RETURN
	LDA DEMO_FRAMES_LEFT
	BNEL @RETURN
	LDA ENTITY_DIRECTIONS,X
	CMP #DIRECTION::RIGHT
	BEQ @USE_LR_HITBOX
	CMP #DIRECTION::LEFT
	BNE @USE_UD_HITBOX
@USE_LR_HITBOX:
	TYA
	ASL
	TAX
	LDA ENTITY_HITBOX_LEFT_RIGHT_WIDTHS,X
	STA @LOCAL05
	LDA ENTITY_HITBOX_LEFT_RIGHT_HEIGHTS,X
	STA @VIRTUAL04
	BRA @COMPUTE_BOUNDS
@USE_UD_HITBOX:
	LDA ENTITY_HITBOX_UP_DOWN_WIDTHS,X
	STA @LOCAL05
	LDA ENTITY_HITBOX_UP_DOWN_HEIGHTS,X
	STA @VIRTUAL04
@COMPUTE_BOUNDS:
	LDA @LOCAL05
	PHA
	LDA @VIRTUAL02
	PLY
	STY @VIRTUAL02
	SEC
	SBC @VIRTUAL02
	STA @LOCAL04
	LDA @LOCAL05
	ASL
	STA @LOCAL03
	LDA @LOCAL07
	SEC
	SBC @VIRTUAL04
	STA @LOCAL07
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL02
	JMP @LOOP_CHECK
@CHECK_ENTITY:
	LDA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_SCRIPT_TABLE,X
	CMP #$FFFF
	BEQL @NEXT_ENTITY
	LDA ENTITY_COLLIDED_OBJECTS,X
	CMP #ENTITY_COLLISION_DISABLED
	BEQL @NEXT_ENTITY
	LDA PLAYER_INTANGIBILITY_FRAMES
	BEQ @CHECK_HITBOX
	LDA ENTITY_NPC_IDS,X
	INC
	CMP #$8001
	BCC @CHECK_HITBOX
	JMP @NEXT_ENTITY
@CHECK_HITBOX:
	LDA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_HITBOX_ENABLED,X
	BEQ @NEXT_ENTITY
	LDA ENTITY_DIRECTIONS,X
	CMP #DIRECTION::RIGHT
	BEQ @NPC_LR_HITBOX
	CMP #DIRECTION::LEFT
	BNE @NPC_UD_HITBOX
@NPC_LR_HITBOX:
	LDA @VIRTUAL02
	ASL
	TAX
	LDY ENTITY_HITBOX_LEFT_RIGHT_WIDTHS,X
	LDA ENTITY_HITBOX_LEFT_RIGHT_HEIGHTS,X
	STA @LOCAL01
	BRA @AABB_TEST
@NPC_UD_HITBOX:
	LDY ENTITY_HITBOX_UP_DOWN_WIDTHS,X
	LDA ENTITY_HITBOX_UP_DOWN_HEIGHTS,X
	STA @LOCAL01
@AABB_TEST:
	LDA @VIRTUAL02
	ASL
	TAX
	LDA @LOCAL01
	STA @VIRTUAL02
	LDA ENTITY_ABS_Y_TABLE,X
	SEC
	SBC @VIRTUAL02
	STA @LOCAL00
	SEC
	SBC @VIRTUAL04
	CMP @LOCAL07
	BCS @NEXT_ENTITY
	LDA @LOCAL01
	CLC
	ADC @LOCAL00
	CMP @LOCAL07
	BLTEQ @NEXT_ENTITY
	STY @VIRTUAL02
	LDA ENTITY_ABS_X_TABLE,X
	SEC
	SBC @VIRTUAL02
	STA @LOCAL00
	TYA
	ASL
	TAX
	LDA @LOCAL00
	SEC
	SBC @LOCAL03
	CMP @LOCAL04
	BCS @NEXT_ENTITY
	STX @VIRTUAL02
	LDA @LOCAL00
	CLC
	ADC @VIRTUAL02
	CMP @LOCAL04
	BLTEQ @NEXT_ENTITY
	LDA @LOCAL02
	STA @VIRTUAL02
	STA @LOCAL06
	BRA @RETURN
@NEXT_ENTITY:
	LDA @LOCAL02
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL02
@LOOP_CHECK:
	LDA @VIRTUAL02
	CMP #23
	BNEL @CHECK_ENTITY
@RETURN:
	LDA @LOCAL06
	STA ENTITY_COLLIDED_OBJECTS+46
	LDA @LOCAL06
	END_C_FUNCTION
