
OPEN_MENU_BUTTON:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	END_STACK_VARS
	JSL DISABLE_ALL_ENTITIES
	LDA #SFX::CURSOR1
	JSL PLAY_SOUND
	CREATE_WINDOW_NEAR #WINDOW::COMMAND_MENU
	LDA #1
	STA @VIRTUAL02
	JMP @COMMAND_MENU_LOOP_CHECK
@CHECK_MENU_ITEM:
	LDA @VIRTUAL02
	CMP #3
	BNE @AFTER_PSI_CHECK
	JSR FIND_FIRST_CHARACTER_WITH_PSI
	CMP #0
	BEQL @SKIP_MENU_ITEM
@AFTER_PSI_CHECK:
	LDA @VIRTUAL02
	CMP #1
	BEQ @MENU_ITEM_DISABLED
	LDA @VIRTUAL02
	CMP #5
	BEQ @MENU_ITEM_DISABLED
	LDA @VIRTUAL02
	CMP #2
	BNE @MENU_ITEM_ENABLED
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	CMP #1
	BNE @MENU_ITEM_ENABLED
	LDX #1
	LDA GAME_STATE + game_state::party_members
	AND #$00FF
	JSL GET_CHARACTER_ITEM
	CMP #0
	BNE @MENU_ITEM_ENABLED
@MENU_ITEM_DISABLED:
	LDX #1
	BRA @ADD_COMMAND_ITEM
@MENU_ITEM_ENABLED:
	LDX #27
@ADD_COMMAND_ITEM:
	LDY @VIRTUAL02
	DEY
	LOADPTR DEBUG_MENU_ELEMENT_SPACING_DATA, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL09
	TYA
	ASL
	STA @LOCAL08
	LOADPTR CMD_WINDOW_TEXT, @VIRTUAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 10
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	MOVE_INT_CONSTANT NULL, @LOCAL01
	TXA
	SEP #PROC_FLAGS::ACCUM8
	STA @LOCAL02
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL08
	INC
	MOVE_INTX @LOCAL09, @VIRTUAL06
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	TAY
	LDA @LOCAL08
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	TAX
	LDA @VIRTUAL02
	JSR ADD_MENU_ITEM_WITH_SOUND
@SKIP_MENU_ITEM:
	INC @VIRTUAL02
@COMMAND_MENU_LOOP_CHECK:
	LDA @VIRTUAL02
	CMP #7
	BCCL @CHECK_MENU_ITEM
	JSR PRINT_MENU_ITEMS
@MAIN_PAUSE_MENU:
	REP #PROC_FLAGS::ACCUM8
	LDA #0
	JSR SET_WINDOW_FOCUS
	LDA #1
	JSR SELECTION_MENU
	STORE_INT1632 @VIRTUAL06
	LDA @VIRTUAL06
	CMP #MENU_OPTIONS::TALK_TO
	BEQ @TALK_TO
	CMP #MENU_OPTIONS::GOODS
	BEQ @GOODS
	CMP #MENU_OPTIONS::PSI
	BEQL @PSI
	CMP #MENU_OPTIONS::EQUIP
	BEQL @EQUIP
	CMP #MENU_OPTIONS::CHECK
	BEQL @CHECK
	CMP #MENU_OPTIONS::STATUS
	BEQL @STATUS
	JMP @CLEANUP_AND_CLOSE
@TALK_TO:
	JSL TALK_TO
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BNE @T012
	LOADPTR MSG_SYS_HANASU_NG, @VIRTUAL06
@T012:
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
	JMP @CLEANUP_AND_CLOSE
@GOODS:
	JSR SHOW_HPPP_AND_MONEY_WINDOWS
@GOODS_CHAR_SELECT:
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	CMP #1
	BNE @GOODS_MANY_PARTY_MEMBERS
	LDY #.LOWORD(GAME_STATE) + game_state::party_members
	STY @LOCAL07
	LDX #1
	LDA __BSS_START__,Y
	AND #$00FF
	JSL GET_CHARACTER_ITEM
	CMP #0
	BEQL @MAIN_PAUSE_MENU
	LDX #2
	LDY @LOCAL07
	LDA __BSS_START__,Y
	AND #$00FF
	JSR INVENTORY_GET_ITEM_NAME
	LDY @LOCAL07
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,Y
	STORE_INT832 @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL06
	LDA #0
	JSL SELECT_BATTLE_MENU_CHARACTER
	BRA @AFTER_GOODS_CHAR_SELECT
@GOODS_MANY_PARTY_MEMBERS:
	LDA #0
	JSR DISPLAY_MENU_HEADER_TEXT
	LOADPTR GET_WEAPON_ITEM_NAME, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDX #1
	LDA #0
	JSR CHAR_SELECT_PROMPT
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL06
@AFTER_GOODS_CHAR_SELECT:
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BNE @GOODS_VERIFY_HAS_ITEMS
	LDA #WINDOW::INVENTORY
	JSL CLOSE_WINDOW
	JSR CLOSE_MENU_HEADER_WINDOW
	JMP @MAIN_PAUSE_MENU
@GOODS_VERIFY_HAS_ITEMS:
	LDX #1
	LDA @VIRTUAL06
	JSL GET_CHARACTER_ITEM
	CMP #0
	BEQL @GOODS_CHAR_SELECT
@GOODS_SHOW_INVENTORY:
	LDA #1
	JSR DISPLAY_MENU_HEADER_TEXT
	LDA #WINDOW::INVENTORY
	JSR SET_WINDOW_FOCUS
	LDA #1
	JSR SELECTION_MENU
	STA @VIRTUAL04
	STA @LOCAL05
	JSR CLOSE_MENU_HEADER_WINDOW
	LDA @VIRTUAL04
	BNE @GOODS_ITEM_SELECTED
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	CMP #1
	BNEL @GOODS_CHAR_SELECT
	LDX #1
	LDA GAME_STATE + game_state::party_members
	AND #$00FF
	JSL GET_CHARACTER_ITEM
	CMP #0
	BEQ @CLOSE_INVENTORY_RETURN
	LDA #SFX::MENU_OPEN_CLOSE
	JSL PLAY_SOUND
	JSL CLEAR_BATTLE_MENU_CHARACTER_INDICATOR
@CLOSE_INVENTORY_RETURN:
	LDA #WINDOW::INVENTORY
	JSL CLOSE_WINDOW
	JMP @MAIN_PAUSE_MENU
@GOODS_ITEM_SELECTED:
	CREATE_WINDOW_NEAR #WINDOW::INVENTORY_MENU
	MOVE_INT @LOCAL06, @VIRTUAL06
	LDA @VIRTUAL06
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::afflictions,X
	AND #$00FF
	TAX
	BEQ @GOODS_ITEM_SELECTED_ALIVE
	STX @VIRTUAL02
	LDA #4
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @GOODS_ITEM_SELECTED_ALIVE
	LDX #1
	BRA @SETUP_ITEM_ACTION_MENU
@GOODS_ITEM_SELECTED_ALIVE:
	LDX #0
@SETUP_ITEM_ACTION_MENU:
	TXY
	STY @LOCAL04
	TYX
	LDA #0
	JSL SET_FOCUS_TEXT_CURSOR
	BRA @ITEM_MENU_OPTION_LOOP_CHECK
@ADD_ITEM_MENU_OPTION:
	TYX
	INX
	STX @LOCAL03
	LOADPTR ITEM_USE_MENU_STRINGS, @VIRTUAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 6
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	MOVE_INT_CONSTANT NULL, @LOCAL01
	TXA
	JSR ADD_MENU_ITEM_NO_POSITION
	LDX @LOCAL03
	TXY
	STY @LOCAL04
@ITEM_MENU_OPTION_LOOP_CHECK:
	LDY @LOCAL04
	CPY #4
	BCC @ADD_ITEM_MENU_OPTION
	LDY #0
	TYX
	LDA #1
	JSL LAYOUT_MENU_OPTIONS
	LDA #0
	STA @VIRTUAL02
@ITEM_ACTION_LOOP:
	LDA @VIRTUAL02
	BEQ @FOCUS_ACTION_MENU
	LDA #2
	JSR SET_WINDOW_FOCUS
	JSR PRINT_MENU_ITEMS
	BRA @DO_ITEM_ACTION_SELECT
@FOCUS_ACTION_MENU:
	LDA #3
	JSR SET_WINDOW_FOCUS
	JSR PRINT_MENU_ITEMS
@DO_ITEM_ACTION_SELECT:
	LDA #3
	JSR SET_WINDOW_FOCUS
	LDA #1
	JSR SELECTION_MENU
	STORE_INT1632 @VIRTUAL0A
	LDA @VIRTUAL0A
	BEQ @BACK_TO_ITEM_LIST
	CMP #1
	BEQ @GOODS_ITEM_USE
	CMP #4
	BEQ @GOODS_ITEM_HELP
	CMP #2
	BEQL @GOODS_GIVE
	CMP #3
	BEQL @GOODS_DROP
	JMP @CLEANUP_AND_CLOSE
@BACK_TO_ITEM_LIST:
	JSR CLOSE_FOCUS_WINDOW
	LDA #2
	JSR SET_WINDOW_FOCUS
	JMP @GOODS_SHOW_INVENTORY
@GOODS_ITEM_USE:
	LDA #1
	STA @VIRTUAL02
	LDY #0
	LDA @LOCAL05
	STA @VIRTUAL04
	LDX @VIRTUAL04
	MOVE_INT @LOCAL06, @VIRTUAL06
	LDA @VIRTUAL06
	JSR OVERWORLD_USE_ITEM
	CMP #0
	BEQ @ITEM_ACTION_LOOP
	JMP @CLEANUP_AND_CLOSE
@GOODS_ITEM_HELP:
	CREATE_WINDOW_NEAR #WINDOW::TEXT_STANDARD
	LDA @LOCAL05
	STA @VIRTUAL04
	LDX @VIRTUAL04
	MOVE_INT @LOCAL06, @VIRTUAL06
	LDA @VIRTUAL06
	JSL GET_CHARACTER_ITEM
	STA @LOCAL05
	LOADPTR ITEM_CONFIGURATION_TABLE, @VIRTUAL0A
	LDA @LOCAL05
	LDY #.SIZEOF(item)
	JSL MULT168
	CLC
	ADC #item::help_text
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
	LDA #WINDOW::TEXT_STANDARD
	JSL CLOSE_WINDOW
	LDA #WINDOW::INVENTORY_MENU
	JSL CLOSE_WINDOW
	LDA #WINDOW::INVENTORY
	JSR SET_WINDOW_FOCUS
	JMP @GOODS_SHOW_INVENTORY
@GOODS_GIVE:
	LDA #WINDOW::INVENTORY
	JSR SET_WINDOW_FOCUS
	JSR CLEAR_FOCUS_WINDOW_CONTENT
	LDA #1
	STA @VIRTUAL02
	LDA #3
	JSR DISPLAY_MENU_HEADER_TEXT
	LOADPTR GET_BODY_ITEM_NAME, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDX #1
	LDA #2
	JSR CHAR_SELECT_PROMPT
	STA @LOCAL07
	JSR CLOSE_MENU_HEADER_WINDOW
	LDA #WINDOW::OVERWORLD_CHAR_SELECT
	JSL CLOSE_WINDOW
	LDA @LOCAL07
	BEQL @ITEM_ACTION_LOOP
	MOVE_INT @LOCAL06, @VIRTUAL06
	MOVE_INT1632 @LOCAL07, @VIRTUAL0A
	CMP32 @VIRTUAL0A, @VIRTUAL06
	BEQ @GOODS_GIVE_CHECK_STATUS
	LDA @LOCAL05
	STA @VIRTUAL04
	LDX @VIRTUAL04
	LDA @VIRTUAL06
	JSL GET_CHARACTER_ITEM
	LDY #.SIZEOF(item)
	JSL MULT168
	.A16
	CLC
	ADC #item::flags
	TAX
	LDA f:ITEM_CONFIGURATION_TABLE,X
	AND #$00FF
	AND #ITEM_FLAGS::CANNOT_GIVE
	BEQ @GOODS_GIVE_CHECK_STATUS
	CREATE_WINDOW_NEAR #WINDOW::TEXT_STANDARD
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	MOVE_INT1632 @VIRTUAL04, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_ARGUMENT_MEMORY
	DISPLAY_TEXT_PTR MSG_SYS_GOODS_NOCARRY
	LDA #WINDOW::TEXT_STANDARD
	JSL CLOSE_WINDOW
	JMP @ITEM_ACTION_LOOP
@GOODS_GIVE_CHECK_STATUS:
	LDY #0
	STY @LOCAL03
	LDA @VIRTUAL06
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	.A16
	TAX
	LDA PARTY_CHARACTERS + char_struct::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	TAX
	CPX #STATUS_0::UNCONSCIOUS
	BEQ @GIVER_DEAD_STATUS
	CPX #STATUS_0::DIAMONDIZED
	BNE @AFTER_GIVER_STATUS_CHECK
@GIVER_DEAD_STATUS:
	LDY #5
	STY @LOCAL03
@AFTER_GIVER_STATUS_CHECK:
	MOVE_INT1632 @LOCAL07, @VIRTUAL0A
	CMP32 @VIRTUAL0A, @VIRTUAL06
	.A16
	BEQ @DISPLAY_GIVE_MESSAGE
	LDY @LOCAL03
	INY
	STY @LOCAL03
	LDA @LOCAL07
	JSL FIND_INVENTORY_SPACE2
	CMP #0
	BEQ @AFTER_INVENTORY_CHECK
	LDY @LOCAL03
	INY
	INY
	STY @LOCAL03
@AFTER_INVENTORY_CHECK:
	LDA @LOCAL07
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS + char_struct::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	AND #$00FF
	TAX
	CPX #STATUS_0::UNCONSCIOUS
	BEQ @TARGET_DEAD_STATUS
	CPX #STATUS_0::DIAMONDIZED
	BNE @DISPLAY_GIVE_MESSAGE
@TARGET_DEAD_STATUS:
	LDY @LOCAL03
	INY
	STY @LOCAL03
@DISPLAY_GIVE_MESSAGE:
	CREATE_WINDOW_NEAR #WINDOW::TEXT_STANDARD
	JSR GET_ACTIVE_WINDOW_ADDRESS
	STA @LOCAL08
	CLC
	ADC #window_stats::working_memory
	TAY
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	MOVE_INT1632 @LOCAL07, @VIRTUAL0A
	LDA @LOCAL08
	CLC
	ADC #window_stats::working_memory_storage
	TAY
	MOVE_INT_YPTRDEST @VIRTUAL0A, __BSS_START__
	LDA @LOCAL05
	STA @VIRTUAL04
	STORE_INT1632 @VIRTUAL0A
	LDA @LOCAL08
	CLC
	ADC #window_stats::argument_memory
	TAY
	MOVE_INT_YPTRDEST @VIRTUAL0A, __BSS_START__
	LDY @LOCAL03
	TYA
	BEQ @GOODS_GIVE_SELF_ALIVE_TEXT
	CMP #1
	BEQ @GOODS_GIVE_ALIVE_TO_ALIVE_FAIL_TEXT
	CMP #2
	BEQ @GOODS_GIVE_ALIVE_TO_DEAD_FAIL_TEXT
	CMP #3
	BEQL @GOODS_GIVE_ALIVE_TO_ALIVE_SUCC_TEXT
	CMP #4
	BEQL @GOODS_GIVE_ALIVE_TO_DEAD_SUCC_TEXT
	CMP #5
	BEQL @GOODS_GIVE_SELF_DEAD_TEXT
	CMP #6
	BEQL @GOODS_GIVE_DEAD_TO_ALIVE_FAIL_TEXT
	CMP #7
	BEQL @GOODS_GIVE_DEAD_TO_DEAD_FAIL_TEXT
	CMP #8
	BEQL @GOODS_GIVE_DEAD_TO_ALIVE_SUCC_TEXT
	CMP #9
	BEQL @GOODS_GIVE_DEAD_TO_DEAD_SUCC_TEXT
	JMP @GOODS_GIVE_INVALID_TEXT
@GOODS_GIVE_SELF_ALIVE_TEXT:
	DISPLAY_TEXT_PTR MSG_SYS_CARRY_SELF_ALIVE
	LDY @VIRTUAL04
	MOVE_INT @LOCAL06, @VIRTUAL06
	LDA @VIRTUAL06
	TAX
	LDA @LOCAL07
	JSL SWAP_ITEM_INTO_EQUIPMENT
	JMP @GOODS_GIVE_DONE
@GOODS_GIVE_ALIVE_TO_ALIVE_FAIL_TEXT:
	DISPLAY_TEXT_PTR MSG_SYS_CARRY_FAIL_OTHER_ALIVE_ALIVE
	JMP @GOODS_GIVE_DONE
@GOODS_GIVE_ALIVE_TO_DEAD_FAIL_TEXT:
	DISPLAY_TEXT_PTR MSG_SYS_CARRY_FAIL_OTHER_ALIVE_DEAD
	JMP @GOODS_GIVE_DONE
@GOODS_GIVE_ALIVE_TO_ALIVE_SUCC_TEXT:
	DISPLAY_TEXT_PTR MSG_SYS_CARRY_OTHER_ALIVE_ALIVE
	LDY @VIRTUAL04
	MOVE_INT @LOCAL06, @VIRTUAL06
	LDA @VIRTUAL06
	TAX
	LDA @LOCAL07
	JSL SWAP_ITEM_INTO_EQUIPMENT
	JMP @GOODS_GIVE_DONE
@GOODS_GIVE_ALIVE_TO_DEAD_SUCC_TEXT:
	DISPLAY_TEXT_PTR MSG_SYS_CARRY_OTHER_ALIVE_DEAD
	LDY @VIRTUAL04
	MOVE_INT @LOCAL06, @VIRTUAL06
	LDA @VIRTUAL06
	TAX
	LDA @LOCAL07
	JSL SWAP_ITEM_INTO_EQUIPMENT
	JMP @GOODS_GIVE_DONE
@GOODS_GIVE_SELF_DEAD_TEXT:
	DISPLAY_TEXT_PTR MSG_SYS_CARRY_SELF_DEAD
	LDY @VIRTUAL04
	MOVE_INT @LOCAL06, @VIRTUAL06
	LDA @VIRTUAL06
	TAX
	LDA @LOCAL07
	JSL SWAP_ITEM_INTO_EQUIPMENT
	BRA @GOODS_GIVE_DONE
@GOODS_GIVE_DEAD_TO_ALIVE_FAIL_TEXT:
	DISPLAY_TEXT_PTR MSG_SYS_CARRY_FAIL_OTHER_DEAD_ALIVE
	BRA @GOODS_GIVE_DONE
@GOODS_GIVE_DEAD_TO_DEAD_FAIL_TEXT:
	DISPLAY_TEXT_PTR MSG_SYS_CARRY_FAIL_OTHER_DEAD_DEAD
	BRA @GOODS_GIVE_DONE
@GOODS_GIVE_DEAD_TO_ALIVE_SUCC_TEXT:
	DISPLAY_TEXT_PTR MSG_SYS_CARRY_OTHER_DEAD_ALIVE
	LDY @VIRTUAL04
	MOVE_INT @LOCAL06, @VIRTUAL06
	LDA @VIRTUAL06
	TAX
	LDA @LOCAL07
	JSL SWAP_ITEM_INTO_EQUIPMENT
	BRA @GOODS_GIVE_DONE
@GOODS_GIVE_DEAD_TO_DEAD_SUCC_TEXT:
	DISPLAY_TEXT_PTR MSG_SYS_CARRY_OTHER_DEAD_DEAD
	LDY @VIRTUAL04
	MOVE_INT @LOCAL06, @VIRTUAL06
	LDA @VIRTUAL06
	TAX
	LDA @LOCAL07
	JSL SWAP_ITEM_INTO_EQUIPMENT
	BRA @GOODS_GIVE_DONE
@GOODS_GIVE_INVALID_TEXT:
	BRA @GOODS_GIVE_INVALID_TEXT
@GOODS_GIVE_DONE:
	LDA #WINDOW::TEXT_STANDARD
	JSL CLOSE_WINDOW
	LDA #WINDOW::INVENTORY_MENU
	JSL CLOSE_WINDOW
	LDA #WINDOW::INVENTORY
	JSL CLOSE_WINDOW
	JMP @MAIN_PAUSE_MENU
@GOODS_DROP:
	CREATE_WINDOW_NEAR #WINDOW::TEXT_STANDARD
	MOVE_INT @LOCAL06, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	LDA @LOCAL05
	STA @VIRTUAL04
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_ARGUMENT_MEMORY
	DISPLAY_TEXT_PTR MSG_SYS_GOODS_DROP
	LDA #WINDOW::TEXT_STANDARD
	JSL CLOSE_WINDOW
	LDA #WINDOW::INVENTORY_MENU
	JSL CLOSE_WINDOW
	LDA #WINDOW::INVENTORY
	JSL CLOSE_WINDOW
	JMP @MAIN_PAUSE_MENU
@PSI:
	JSR SHOW_HPPP_AND_MONEY_WINDOWS
	JSR FIND_FIRST_CHARACTER_WITH_PSI
	STORE_INT1632 @VIRTUAL06
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BEQ @PSI_MENU_OPEN
	LDA @VIRTUAL06
	DEC
	JSL SELECT_BATTLE_MENU_CHARACTER
@PSI_MENU_OPEN:
	JSR OVERWORLD_PSI_MENU
	CMP #0
	BNEL @CLEANUP_AND_CLOSE
	JSR COUNT_CHARACTERS_WITH_PSI
	CMP #1
	BNEL @MAIN_PAUSE_MENU
	LDA #SFX::MENU_OPEN_CLOSE
	JSL PLAY_SOUND
	JSL CLEAR_BATTLE_MENU_CHARACTER_INDICATOR
	JMP @MAIN_PAUSE_MENU
@EQUIP:
	JSR SHOW_HPPP_AND_MONEY_WINDOWS
	JSR OPEN_EQUIPMENT_MENU
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	CMP #1
	BNEL @MAIN_PAUSE_MENU
	LDA #SFX::MENU_OPEN_CLOSE
	JSL PLAY_SOUND
	JSL CLEAR_BATTLE_MENU_CHARACTER_INDICATOR
	JMP @MAIN_PAUSE_MENU
@CHECK:
	JSL CHECK
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BNE @DISPLAY_CHECK_TEXT
	LOADPTR MSG_SYS_NOPROBLEM, @VIRTUAL06
@DISPLAY_CHECK_TEXT:
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
	BRA @CLEANUP_AND_CLOSE
@STATUS:
	JSR SHOW_HPPP_AND_MONEY_WINDOWS
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA FORCE_LEFT_TEXT_ALIGNMENT
	JSR OPEN_STATUS_MENU
	SEP #PROC_FLAGS::ACCUM8
	STZ FORCE_LEFT_TEXT_ALIGNMENT
	JMP @MAIN_PAUSE_MENU
@CLEANUP_AND_CLOSE:
	JSL CLEAR_INSTANT_PRINTING
	JSR HIDE_HPPP_WINDOWS
	JSR CLOSE_ALL_WINDOWS
@WAIT_ENTITY_FADE:
	JSL WINDOW_TICK
	.A16
	LDA ENTITY_FADE_ENTITY
	CMP #.LOWORD(-1)
	BNE @WAIT_ENTITY_FADE
	JSL ENABLE_ALL_ENTITIES
	END_C_FUNCTION

OPEN_MENU_BUTTON_CHECKTALK:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	JSL DISABLE_ALL_ENTITIES
	LDA #SFX::CURSOR1
	JSL PLAY_SOUND
	JSL TALK_TO
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BNE @DISPLAY_RESULT
	JSL CHECK
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BNE @DISPLAY_RESULT
	LOADPTR MSG_SYS_NOPROBLEM, @VIRTUAL06
@DISPLAY_RESULT:
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
	JSL CLEAR_INSTANT_PRINTING
	JSR HIDE_HPPP_WINDOWS
	JSR CLOSE_ALL_WINDOWS
@WAIT_FADE:
	JSL WINDOW_TICK
	LDA ENTITY_FADE_ENTITY
	CMP #.LOWORD(-1)
	BNE @WAIT_FADE
	JSL ENABLE_ALL_ENTITIES
	END_C_FUNCTION
