
PREPARE_YOUR_SANCTUARY_LOCATION_TILESET_DATA:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL02
	LDA #0
	STA @VIRTUAL04
	BRA @BLOCK_LOOP_CHECK
@PROCESS_BLOCK:
	LDA @VIRTUAL04
	ASL
	CLC
	ADC #.LOWORD(LOADED_MAP_BLOCKS)
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	BEQ @NEXT_BLOCK
	LOADPTR BUFFER + $8000, @VIRTUAL06
	LDA @VIRTUAL04
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA NEXT_YOUR_SANCTUARY_LOCATION_TILE_INDEX
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #$6000
	AND #$7FFF
	TAY
	LDX #32
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	.A16
	LDA NEXT_YOUR_SANCTUARY_LOCATION_TILE_INDEX
	LDX @VIRTUAL02
	STA __BSS_START__,X
	INC NEXT_YOUR_SANCTUARY_LOCATION_TILE_INDEX
	INC YOUR_SANCTUARY_LOADED_TILESET_TILES
@NEXT_BLOCK:
	INC @VIRTUAL04
@BLOCK_LOOP_CHECK:
	LDA @VIRTUAL04
	CMP #1024
	BCC @PROCESS_BLOCK
	LOADPTR BUFFER, @VIRTUAL06
	LDY #$0800
	LDA @LOCAL02
	JSL MULT16
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDX #0
	STX @LOCAL01
	BRA @REMAP_LOOP_CHECK
@REMAP_TILE:
	LDA [@VIRTUAL06]
	STA @LOCAL02
	AND #$03FF
	ASL
	TAX
	LDA @LOCAL02
	AND #$FC00
	ORA LOADED_MAP_BLOCKS,X
	STA [@VIRTUAL06]
	INC @VIRTUAL06
	INC @VIRTUAL06
	LDX @LOCAL01
	INX
	STX @LOCAL01
@REMAP_LOOP_CHECK:
	CPX #960
	BCC @REMAP_TILE
	END_C_FUNCTION
