
PREPARE_NEW_ENTITY_AT_EXISTING_ENTITY_LOCATION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	BEQ @USE_CURRENT_ENTITY
	CMP #1
	BEQ @USE_PARTY_LEADER
	BRA @COPY_POSITION
@USE_CURRENT_ENTITY:
	LDX CURRENT_ENTITY_SLOT
	STX @LOCAL00
	BRA @COPY_POSITION
@USE_PARTY_LEADER:
	LDX GAME_STATE+game_state::current_party_members
	STX @LOCAL00
@COPY_POSITION:
	LDX @LOCAL00
	TXA
	ASL
	TAX
	LDA ENTITY_ABS_X_TABLE,X
	STA ENTITY_PREPARED_X_COORDINATE
	LDA ENTITY_ABS_Y_TABLE,X
	STA ENTITY_PREPARED_Y_COORDINATE
	LDA ENTITY_DIRECTIONS,X
	STA ENTITY_PREPARED_DIRECTION
	END_C_FUNCTION
