
PROCESS_OVERWORLD_TASKS:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA FRAME_COUNTER
	AND #$00FF
	BNE @CHECK_CAN_PROCESS
	LDA DAD_PHONE_TIMER
	BEQ @CHECK_CAN_PROCESS
	DEC DAD_PHONE_TIMER
@CHECK_CAN_PROCESS:
	LDA WINDOW_HEAD
	CMP #.LOWORD(-1)
	BNE @RETURN
	LDA BATTLE_MODE_FLAG
	BNE @RETURN
	LDA BATTLE_SWIRL_COUNTDOWN
	BNE @RETURN
	LDA ENEMY_HAS_BEEN_TOUCHED
	BNE @RETURN
	LDY #.LOWORD(OVERWORLD_TASKS)
	STY @LOCAL00
	LDA #0
	STA @VIRTUAL02
	BRA @LOOP_CHECK
@PROCESS_TASK:
	LDA a:overworld_task::frames_left,Y
	BEQ @NEXT_TASK
	TYX
	DEC
	STA a:overworld_task::frames_left,X
	BNE @NEXT_TASK
	INY ;overworld_task::function
	INY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	PHA
	MOVE_INT @VIRTUAL06, TEMP_FUNCTION_POINTER
	PLA
	JSL JUMP_TEMP_FUNCTION_POINTER
@NEXT_TASK:
	LDY @LOCAL00
	TYA
	CLC
	ADC #.SIZEOF(overworld_task)
	TAY
	STY @LOCAL00
	INC @VIRTUAL02
@LOOP_CHECK:
	LDA @VIRTUAL02
	CMP #4
	BCC @PROCESS_TASK
@RETURN:
	END_C_FUNCTION
