
PROCESS_ITEM_TRANSFORMATIONS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA ENEMY_HAS_BEEN_TOUCHED
	CLC
	ADC BATTLE_SWIRL_COUNTDOWN
	BNEL @RETURN
	LDA DISABLED_TRANSITIONS
	BNEL @RETURN
	LDA GAME_STATE + game_state::camera_mode
	CMP #2
	BEQL @RETURN
	SEP #PROC_FLAGS::ACCUM8
	LDA TIME_UNTIL_NEXT_ITEM_TRANSFORMATION_CHECK
	DEC
	STA TIME_UNTIL_NEXT_ITEM_TRANSFORMATION_CHECK
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNEL @RETURN
	SEP #PROC_FLAGS::ACCUM8
	LDA #60
	STA TIME_UNTIL_NEXT_ITEM_TRANSFORMATION_CHECK
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(LOADED_TIMED_ITEM_TRANSFORMATIONS)
	STA @VIRTUAL02
	LDA #1
	STA @LOCAL03
	LDA #0
	STA @VIRTUAL04
	STA @LOCAL02
	JMP @LOOP_HEAD
@PROCESS_SLOT:
	LDA @LOCAL03
	BEQ @AFTER_SFX_CHECK
	LDY @VIRTUAL02
	INY
	STY @LOCAL01
	LDA __BSS_START__,Y
	AND #$00FF
	BEQ @AFTER_SFX_CHECK
	LDX @VIRTUAL02
	INX
	INX
	STX @LOCAL00
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNE @AFTER_SFX_CHECK
	LDA #2
	JSL RAND_MOD
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	LDY @LOCAL01
	LDA __BSS_START__,Y
	CLC
	ADC @VIRTUAL00
	DEC
	LDX @LOCAL00
	STA __BSS_START__,X
	LDX @VIRTUAL02
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	AND #$00FF
	JSL PLAY_SOUND
	STZ @LOCAL03
@AFTER_SFX_CHECK:
	LDX @VIRTUAL02
	INX
	INX
	INX
	LDA __BSS_START__,X
	AND #$00FF
	BEQ @CHECK_TRANSFORMATION_COUNTDOWN
	SEP #PROC_FLAGS::ACCUM8
	DEC
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNE @CHECK_TRANSFORMATION_COUNTDOWN
	LOADPTR TIMED_ITEM_TRANSFORMATION_TABLE, @VIRTUAL06
	LDA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(timed_item_transformation)
	TAY
	STY @LOCAL00
	TYA
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	TAX
	LDA #$00FF
	JSL TAKE_ITEM_FROM_CHARACTER
	STA @LOCAL01
	LDY @LOCAL00
	TYA
	INC
	INC
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	TAX
	LDA @LOCAL01
	JSL GIVE_ITEM_TO_CHARACTER
@CHECK_TRANSFORMATION_COUNTDOWN:
	INC @VIRTUAL02
	INC @VIRTUAL02
	INC @VIRTUAL02
	INC @VIRTUAL02
	LDA @LOCAL02
	STA @VIRTUAL04
	INC @VIRTUAL04
	LDA @VIRTUAL04
	STA @LOCAL02
@LOOP_HEAD:
	LDA @VIRTUAL04
	CMP #4
	BCCL @PROCESS_SLOT
@RETURN:
	END_C_FUNCTION
