
PROCESS_QUEUED_INTERACTIONS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
.IF .DEFINED(JPN)
	STACK_RESERVE_INT32 "LOCALM2"
.ENDIF
	STACK_RESERVE_INT16 "LOCAL02"
	END_STACK_VARS
	LDA CURRENT_QUEUED_INTERACTION
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(queued_interaction)
	TAX
	LDA QUEUED_INTERACTIONS + queued_interaction::type,X
	STA @LOCAL02
	TXA
	CLC
	ADC #.LOWORD(QUEUED_INTERACTIONS) + queued_interaction::text_ptr
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
.IF .DEFINED(JPN)
	MOVE_INT @VIRTUAL06, @LOCALM2
.ENDIF
	LDA @LOCAL02
	STA CURRENT_QUEUED_INTERACTION_TYPE
	LDA CURRENT_QUEUED_INTERACTION
	INC
	AND #$0003
	STA CURRENT_QUEUED_INTERACTION
	LDA PLAYER_INTANGIBILITY_FRAMES
	AND #$FFFE
	STA PLAYER_INTANGIBILITY_FRAMES
	JSL CLEAR_PARTY_SPRITE_HIDE_FLAGS
	LDA @LOCAL02
	CMP #2
	BEQ @DOOR_INTERACTION
	CMP #10
	BEQ @SCREEN_RELOAD_INTERACTION
	CMP #0
	BEQ @TEXT_INTERACTION
	CMP #8
	BEQ @TEXT_INTERACTION
	CMP #9
	BEQ @TEXT_INTERACTION
	BRA @UPDATE_PENDING
@DOOR_INTERACTION:
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR DOOR_TRANSITION
	BRA @UPDATE_PENDING
@SCREEN_RELOAD_INTERACTION:
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT_AND_WAIT_FOR_FADE
.IF .DEFINED(JPN)
	LOADPTR MSG_SYS_PAPA_2H, @VIRTUAL06
	LDA @VIRTUAL06
	STA @VIRTUAL02
	MOVE_INT @LOCALM2, @VIRTUAL06
	LDA @VIRTUAL06
	CMP @VIRTUAL02
.ELSE
	LOADPTR MSG_SYS_PAPA_2H, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
.ENDIF
	BNE @UPDATE_PENDING
	LDA #1687
	STA DAD_PHONE_TIMER
	STZ DAD_PHONE_QUEUED
	BRA @UPDATE_PENDING
@TEXT_INTERACTION:
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT_AND_WAIT_FOR_FADE
@UPDATE_PENDING:
	LDX #0
	LDA CURRENT_QUEUED_INTERACTION
	CMP NEXT_QUEUED_INTERACTION
	BEQ @STORE_PENDING
	LDX #1
@STORE_PENDING:
	STX PENDING_INTERACTIONS
	LDA #.LOWORD(-1)
	STA CURRENT_QUEUED_INTERACTION_TYPE
	END_C_FUNCTION
