
RENDER_ENTITY_SPRITE:
	LDX $88
	LDA PLAYER_HAS_MOVED_SINCE_MAP_LOAD
	CLC
	ADC CURRENT_ENTITY_SLOT
	LSR
	LSR
	LSR
	AND #$0001
	STA $00
	LDA ENTITY_DIRECTIONS,X
	ASL
	ORA $00
	STA $02
	LDA ENTITY_WALKING_STYLES,X
	XBA
	ORA $02
	CMP ENTITY_ANIMATION_FINGERPRINTS,X
	BNE @FINGERPRINT_CHANGED
	RTL
@FINGERPRINT_CHANGED:
	STA ENTITY_ANIMATION_FINGERPRINTS,X
	LDA $00
	STA USE_SECOND_SPRITE_FRAME
	BRA RENDER_ENTITY_SPRITE_SETUP_AND_RENDER
	LDA FRAME_COUNTER
	LSR
	LSR
	LSR
	AND #$0001
	STA USE_SECOND_SPRITE_FRAME
	BRA RENDER_ENTITY_SPRITE_SETUP_AND_RENDER
RENDER_ENTITY_SPRITE_MOVEMENT_ENTRY_3:
	LDY $88
	REP #PROC_FLAGS::ACCUM8
	PHD
	PHA
	TDC
	SEC
	SBC #$0006
	TCD
	PLA
	BRA RENDER_ENTITY_SPRITE_LOAD_ANIM_FRAME
RENDER_ENTITY_SPRITE_ENTRY2:
	REP #PROC_FLAGS::ACCUM8
	PHD
	PHA
	TDC
	SEC
	SBC #$0006
	TCD
	PLA
	ASL
	TAY
RENDER_ENTITY_SPRITE_LOAD_ANIM_FRAME:
	LDA ENTITY_ANIMATION_FRAME,Y
	STA USE_SECOND_SPRITE_FRAME
	JSL RENDER_ENTITY_SPRITE_ENTRY4
	PLD
	RTL
RENDER_ENTITY_SPRITE_ENTRY3:
	STZ USE_SECOND_SPRITE_FRAME
	JSL IS_ENTITY_ON_SCREEN
	BNE RENDER_ENTITY_SPRITE_SETUP_AND_RENDER
	RTL
RENDER_ENTITY_SPRITE_MOVEMENT_ENTRY_1:
	LDA #$0001
	STA USE_SECOND_SPRITE_FRAME
	JSL IS_ENTITY_ON_SCREEN
	BNE RENDER_ENTITY_SPRITE_SETUP_AND_RENDER
	RTL
RENDER_ENTITY_SPRITE_MOVEMENT_ENTRY_2:
	STZ USE_SECOND_SPRITE_FRAME
RENDER_ENTITY_SPRITE_SETUP_AND_RENDER:
	LDY $88
RENDER_ENTITY_SPRITE_ENTRY4:
	STY $08
	LDA ENTITY_TILE_HEIGHTS,Y
	STA $00
	LDA ENTITY_BYTE_WIDTHS,Y
	STA DMA_COPY_SIZE
	LDA ENTITY_VRAM_ADDRESS,Y
	STA DMA_COPY_VRAM_DEST
	LDA ENTITY_GRAPHICS_PTR_HIGH,Y
	STA $04
	LDA ENTITY_GRAPHICS_PTR_LOW,Y
	STA $02
	LDA ENTITY_DIRECTIONS,Y
	ASL
	TAX
	LDA f:SPRITE_DIRECTION_MAPPING_4_DIRECTION,X
	BEQ @APPLY_FRAME_OFFSET
	TAX
	LDA $02
	CLC
@DIRECTION_OFFSET_LOOP:
	ADC #$0004
	DEX
	BNE @DIRECTION_OFFSET_LOOP
	STA $02
@APPLY_FRAME_OFFSET:
	LDA USE_SECOND_SPRITE_FRAME
	BEQ @LOAD_SPRITE_DATA
	INC $02
	INC $02
@LOAD_SPRITE_DATA:
	LDA [$02]
	AND #$0002
	BNE @COPY_SPRITE_ROWS
	LDA ENTITY_SURFACE_FLAGS,Y
	STA $06
	AND #$0008
	BEQ @COPY_SPRITE_ROWS
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0003
	STA DMA_COPY_MODE
	LDA #.BANKBYTE(BLANK_TILE_DATA)
	STA DMA_COPY_RAM_SRC + 2
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(BLANK_TILE_DATA)
	STA DMA_COPY_RAM_SRC
	JSL PREPARE_VRAM_COPY_ROW_SAFE
	DEC $00
	BEQ @RENDER_DONE
	LDA $06
	AND #$0004
	BEQ @COPY_SPRITE_ROWS
	JSL PREPARE_VRAM_COPY_ROW_SAFE
	DEC $00
	BEQ @RENDER_DONE
@COPY_SPRITE_ROWS:
	LDY $08
	LDA [$02]
	STA ENTITY_CURRENT_DISPLAYED_SPRITES,Y
	AND #$FFF0
	STA DMA_COPY_RAM_SRC
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	STA DMA_COPY_MODE
	LDA ENTITY_GRAPHICS_SPRITE_BANK,Y
	STA DMA_COPY_RAM_SRC + 2
	REP #PROC_FLAGS::ACCUM8
@DMA_ROW_LOOP:
	JSL PREPARE_VRAM_COPY_ROW_SAFE
	DEC $00
	BEQ @RENDER_DONE
	LDA DMA_COPY_RAM_SRC
	CLC
	ADC DMA_COPY_SIZE
	STA DMA_COPY_RAM_SRC
	BRA @DMA_ROW_LOOP
@RENDER_DONE:
	RTL
