
RESET_PARTY_STATE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #1
	STA ENTITY_SIZES+23 * 2
	LDA #.LOWORD(-1)
	STA MINI_GHOST_ENTITY_ID
	STZ GAME_STATE+game_state::unknown88
	STZ GAME_STATE+game_state::camera_mode
	STZ GAME_STATE+game_state::auto_move_frames_left
	STZ GAME_STATE+game_state::auto_move_saved_walking_style
	SEP #PROC_FLAGS::ACCUM8
	STZ GAME_STATE+game_state::party_status
	REP #PROC_FLAGS::ACCUM8
	LDA #PARTY_LEADER_ENTITY_INDEX
	STA GAME_STATE+game_state::current_party_members
	LDA #0
	STA @LOCAL00
	BRA @LOOP_CHECK
@CLEAR_PARTY_MEMBER:
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ a:game_state::party_order,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
.ELSE
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ GAME_STATE+game_state::party_order,X
	REP #PROC_FLAGS::ACCUM8
.ENDIF
	ASL
	TAX
	STZ HP_ALERT_SHOWN,X
	LDA @LOCAL00
	INC
	STA @LOCAL00
@LOOP_CHECK:
	CMP #TOTAL_PARTY_COUNT
	BCC @CLEAR_PARTY_MEMBER
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA GAME_STATE+game_state::player_controlled_party_count
	STA GAME_STATE+game_state::party_count
	JSL VELOCITY_STORE
	LDA f:NESS_PAJAMA_FLAG
	JSL GET_EVENT_FLAG
	STA PAJAMA_FLAG
	END_C_FUNCTION
