
RUN_GAS_STATION_CREDITS:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #0
	STA @VIRTUAL04
	TAX
	STX @LOCAL01
	BRA @PHASE1_CHECK
@PHASE1_LOOP:
	LDA PAD_PRESS
	BEQ @PHASE1_NO_BUTTON
	LDA #1
	JMP @RETURN
@PHASE1_NO_BUTTON:
	JSL UPDATE_BATTLE_SCREEN_EFFECTS
	JSL WAIT_UNTIL_NEXT_FRAME
	LDX @LOCAL01
	INX
	STX @LOCAL01
@PHASE1_CHECK:
	CPX #236
	BCC @PHASE1_LOOP
	LDA #0
	STA @VIRTUAL02
	BRA @PHASE2_CHECK
@PHASE2_LOOP:
	LDA PAD_PRESS
	BEQ @PHASE2_NO_BUTTON
	LDA #1
	JMP @RETURN
@PHASE2_NO_BUTTON:
	LDY #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 2
	STY @LOCAL01
	TYA
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #BPP4PALETTE_SIZE
	LDA #.LOWORD(MAP_PALETTE_BACKUP)
	JSL MEMCPY16
	JSL UPDATE_MAP_PALETTE_ANIMATION
	SEP #PROC_FLAGS::ACCUM8
	STZ PALETTE_UPLOAD_MODE
	JSL COPY_BG_PALETTE_FROM_POINTER
	.A16
	PROMOTENEARPTR MAP_PALETTE_BACKUP, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #BPP4PALETTE_SIZE
	LDY @LOCAL01
	TYA
	JSL MEMCPY16
	JSL UPDATE_BATTLE_SCREEN_EFFECTS
	SEP #PROC_FLAGS::ACCUM8
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
	JSL WAIT_UNTIL_NEXT_FRAME
	INC @VIRTUAL02
@PHASE2_CHECK:
	LDA @VIRTUAL02
	.A16
	CMP #$01E0
	BCCL @PHASE2_LOOP
	JSL FINALIZE_PALETTE_FADE
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00
	STA f:CGADSUB
	STA f:CGWSEL
	LDA #$01
	STA TM_MIRROR
	STZ TD_MIRROR
	REP #PROC_FLAGS::ACCUM8
	LDA #120
	JSR WAIT_FRAMES_OR_UNTIL_PRESSED
	CMP #0
	BEQ @PHASE4_MUSIC
	LDA #1
	BRA @RETURN
@PHASE4_MUSIC:
	LDA #MUSIC::GAS_STATION_2
	JSL CHANGE_MUSIC
	LDY #0
	TYX
	LDA #EVENT_SCRIPT::EVENT_860
	JSL INIT_ENTITY_WIPE
	STA @LOCAL01
	BRA @EVENT_CHECK
@EVENT_LOOP:
	JSL RUN_ACTIONSCRIPT_FRAME
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA PAD_PRESS
	BEQ @EVENT_CHECK
	LDA @LOCAL01
	JSL DEACTIVATE_ENTITY_FAR
	LDA #1
	BRA @RETURN
@EVENT_CHECK:
	LDA @LOCAL01
	ASL
	TAX
	LDA ENTITY_SCRIPT_TABLE,X
	CMP #.LOWORD(-1)
	BNE @EVENT_LOOP
	LDA #330
	JSR PREPARE_PALETTE_FADE_FROM_CURRENT
	LDA @VIRTUAL04
@RETURN:
	END_C_FUNCTION
