
SCHEDULE_OVERWORLD_TASK:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT32
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TAY
	MOVE_INT @PARAM01, @VIRTUAL06
	LDA #.LOWORD(OVERWORLD_TASKS)
	STA @LOCAL01
	LDX #0
	STX @LOCAL00
	BRA @LOOP_CHECK
@CHECK_SLOT:
	TAX
	LDA a:overworld_task::frames_left,X
	BEQ @FOUND_SLOT
	LDA @LOCAL01
	CLC
	ADC #.SIZEOF(overworld_task)
	STA @LOCAL01
	LDX @LOCAL00
	INX
	STX @LOCAL00
@LOOP_CHECK:
	CPX #4
	BCC @CHECK_SLOT
@FOUND_SLOT:
	LDA @LOCAL01
	TAX
	TYA
	STA a:overworld_task::frames_left,X
	LDA @LOCAL01
	TAY
	INY ;overworld_task::function
	INY
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDX @LOCAL00
	TXA
	END_C_FUNCTION
