
SCREEN_TRANSITION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT8
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_PARAM_INT16 ;int
	END_STACK_VARS
	TXY
	STY @LOCAL06
	STA @LOCAL05
	MOVE_INT_CONSTANT SCREEN_TRANSITION_CONFIG_TABLE, @VIRTUAL06
	LDA @LOCAL05
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(screen_transition_config)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL04
	LDA @VIRTUAL06+2
	STA @LOCAL04+2
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	LDA [@VIRTUAL0A] ;screen_transition_config::duration
	AND #$00FF
	STA @VIRTUAL02
	CMP #>-1
	BNE @NOT_MAX_DURATION
	LDA #900
	STA @VIRTUAL02
@NOT_MAX_DURATION:
	SEP #PROC_FLAGS::ACCUM8
	LDY #screen_transition_config::direction
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	ASL
	ASL
	TAX
	LDY #screen_transition_config::unknown5
	LDA [@VIRTUAL06],Y
	JSL INIT_TRANSITION_SCROLL_VELOCITY
	LDY @LOCAL06
	CPY #1
	BNEL @ENTER_TRANSITION
	JSL DISABLE_ALL_ENTITIES
	LDA #2
	JSL WAIT_FRAMES_WITH_UPDATES
	SEP #PROC_FLAGS::ACCUM8
	LDY #screen_transition_config::animation_id
	LDA [@VIRTUAL06],Y
	STA @LOCAL03
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQ @SKIP_SWIRL_INIT
	SEP #PROC_FLAGS::ACCUM8
	LDY #screen_transition_config::animation_flags
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
	INX
	INX
	LDA @LOCAL03
	AND #$00FF
	JSL INIT_SWIRL_EFFECT
@SKIP_SWIRL_INIT:
	PROMOTENEARPTR PALETTES, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDA #^__BSS_START__
	STA @LOCAL01+2
.IF .DEFINED(JPN)
	MOVE_INT @LOCAL01, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @LOCAL00
.ELSE
	MOVE_INT @LOCAL01, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
.ENDIF
	MOVE_INT @LOCAL04, @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDY #screen_transition_config::fade_style
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	JSL LOAD_PALETTE_TO_FADE_BUFFER
	LDX #.LOWORD(-1)
	LDA @VIRTUAL02
	JSL PREPARE_PALETTE_FADE
	LDA #0
	STA @LOCAL02
	BRA @EXIT_LOOP_CHECK
@EXIT_LOOP_BODY:
	LDA PALETTE_UPLOAD_MODE
	AND #$00FF
	BEQ @EXIT_PALETTE_DONE
	JSL WAIT_UNTIL_NEXT_FRAME
@EXIT_PALETTE_DONE:
	JSL UPDATE_MAP_PALETTE_ANIMATION
	JSL OAM_CLEAR
	JSL UPDATE_TRANSITION_SCROLL
	JSL UPDATE_ENTITY_SCREEN_POSITIONS
	JSL RUN_ACTIONSCRIPT_FRAME
	JSL UPDATE_SCREEN
	JSL UPDATE_SWIRL_EFFECT
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA @LOCAL02
	INC
	STA @LOCAL02
@EXIT_LOOP_CHECK:
	CMP @VIRTUAL02
	BCC @EXIT_LOOP_BODY
	SEP #PROC_FLAGS::ACCUM8
	LDY #screen_transition_config::fade_style
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #>-1
	STA @VIRTUAL02
	LDA #50
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @FADE_TO_WHITE
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	BRA @EXIT_DONE
@FADE_TO_WHITE:
	SEP #PROC_FLAGS::ACCUM8
	LDA #>-1
	STA @LOCAL00
	LDX #BPP4PALETTE_SIZE * 16
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(PALETTES)
	JSL MEMSET16
	LDA #24
	JSL SET_PALETTE_UPLOAD_MODE
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA #1
	STA WIPE_PALETTES_ON_MAP_LOAD
@EXIT_DONE:
	JSL ENABLE_ALL_ENTITIES
	JMP @TRANSITION_CLEANUP
@ENTER_TRANSITION:
	LDX #0
	SEP #PROC_FLAGS::ACCUM8
	LDY #screen_transition_config::fade_style
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	LDA #50
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @ENTER_FADE_MODE_SET
	LDX #1
@ENTER_FADE_MODE_SET:
	TXY
	STY @LOCAL05
	BEQ @ENTER_PALETTE_FADE
	LDX #1
	TXA
	JSL FADE_IN
	BRA @CHECK_SECONDARY_ANIMATION
@ENTER_PALETTE_FADE:
	LDX #.LOWORD(-1)
	SEP #PROC_FLAGS::ACCUM8
	LDY #screen_transition_config::secondary_duration
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	JSL PREPARE_PALETTE_FADE
@CHECK_SECONDARY_ANIMATION:
	SEP #PROC_FLAGS::ACCUM8
	LDY #screen_transition_config::secondary_animation_id
	LDA [@VIRTUAL06],Y
	STA @LOCAL03
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQ @SKIP_SECONDARY_SWIRL
	SEP #PROC_FLAGS::ACCUM8
	LDY #screen_transition_config::secondary_animation_flags
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
	LDA @LOCAL03
	AND #$00FF
	JSL INIT_SWIRL_EFFECT
@SKIP_SECONDARY_SWIRL:
	LDA #0
	STA @LOCAL02
	BRA @ENTER_LOOP_CHECK
@ENTER_LOOP_BODY:
	LDY @LOCAL05
	BNE @ENTER_LOOP_UPDATE
	LDA PALETTE_UPLOAD_MODE
	AND #$00FF
	BEQ @ENTER_PALETTE_DONE
	JSL WAIT_UNTIL_NEXT_FRAME
@ENTER_PALETTE_DONE:
	JSL UPDATE_MAP_PALETTE_ANIMATION
@ENTER_LOOP_UPDATE:
	JSL OAM_CLEAR
	JSL RUN_ACTIONSCRIPT_FRAME
	JSL UPDATE_SWIRL_EFFECT
	JSL UPDATE_SCREEN
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA @LOCAL02
	CMP #1
	BNE @ENTER_LOOP_INCREMENT
	JSL DISABLE_ALL_ENTITIES
@ENTER_LOOP_INCREMENT:
	LDA @LOCAL02
	INC
	STA @LOCAL02
@ENTER_LOOP_CHECK:
	SEP #PROC_FLAGS::ACCUM8
	LDY #screen_transition_config::secondary_duration
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @VIRTUAL02
	LDA @LOCAL02
	CMP @VIRTUAL02
	BCC @ENTER_LOOP_BODY
	LDY @LOCAL05
	BNE @TRANSITION_CLEANUP
	JSL FINALIZE_PALETTE_FADE
@TRANSITION_CLEANUP:
	LDA GIYGAS_PHASE
	CMP #GIYGAS_PHASES::START_PRAYING
	BCS @SKIP_STOP_OVAL
	JSL STOP_OVAL_WINDOW
@SKIP_STOP_OVAL:
	JSL ENABLE_ALL_ENTITIES
	STZ LADDER_STAIRS_TILE_Y
	STZ LADDER_STAIRS_TILE_X
	END_C_FUNCTION
