
SETUP_DELIVERY_PATH_REVERSE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STA @VIRTUAL04
	LDY CURRENT_ENTITY_SLOT
	STY @LOCAL02
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL LOAD_SECTOR_ATTRS
	AND #$0007
	TAX
	LDA f:DELIVERY_SECTOR_PASSABLE_TABLE,X
	AND #$00FF
	BEQL @PATHFIND_FAILED
	LDY @LOCAL02
	TYA
	ASL
	STA @LOCAL01
	CLC
	ADC #.LOWORD(ENTITY_PATHFINDING_STATES)
	TAX
	STX @LOCAL00
	LDA #.LOWORD(-1)
	STA __BSS_START__,X
	JSL PATHFIND_TO_PARTY_LEADER
	TAY
	BNE @PATHFIND_FAILED
	LDA #0
	LDX @LOCAL00
	STA __BSS_START__,X
	LDA @LOCAL01
	CLC
	ADC #.LOWORD(ENTITY_PATH_POINTS)
	TAX
	LDA __BSS_START__,X
	STA @VIRTUAL02
	LDA @VIRTUAL04
	STA @VIRTUAL04
	ASL
	ASL
	ADC @VIRTUAL04
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC #.LOWORD(DELIVERY_PATHS)
	TAY
	STA __BSS_START__,X
	LDA @LOCAL01
	TAX
	LDA ENTITY_PATH_POINT_COUNTS,X
	STA @LOCAL01
	LDX #0
	STX @LOCAL00
	BRA @COPY_CHECK
@COPY_POINT:
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	STA __BSS_START__,Y
	LDX @VIRTUAL02
	LDA __BSS_START__+2,X
	STA __BSS_START__+2,Y
	INC @VIRTUAL02
	INC @VIRTUAL02
	INC @VIRTUAL02
	INC @VIRTUAL02
	INY
	INY
	INY
	INY
	LDA @LOCAL01
	DEC
	STA @LOCAL01
	LDX @LOCAL00
	INX
	STX @LOCAL00
@COPY_CHECK:
	CMP #0
	BEQ @COPY_DONE
	CPX #20
	BCC @COPY_POINT
@COPY_DONE:
	LDA #0
	BRA @RETURN
@PATHFIND_FAILED:
	LDA #1
@RETURN:
	END_C_FUNCTION
