
SHOW_TOWN_MAP:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDX #$00CA
	LDA #$00FF
	JSL FIND_ITEM_IN_INVENTORY2
	CMP #$0000
	BEQ @NO_TOWN_MAP
	JSL DISABLE_ALL_ENTITIES
	JSL DISPLAY_TOWN_MAP
	JSL ENABLE_ALL_ENTITIES
@NO_TOWN_MAP:
	RTL
