
SPAWN_DELIVERY_ENTITIES:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
.IF .DEFINED(JPN)
	STACK_RESERVE_INT16
.ENDIF
	STACK_RESERVE_INT16 "LOCAL03"
	END_STACK_VARS
	LDA #0
	STA @VIRTUAL02
	BRA @LOOP_CHECK
@LOOP_BODY:
	LOADPTR TIMED_DELIVERY_TABLE, @VIRTUAL06
	LDA @VIRTUAL02
	OPTIMIZED_MULT @VIRTUAL04, 20
	TAX
	STX @LOCAL03
	TXA
	INC
	INC
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	JSL GET_EVENT_FLAG
	CMP #0
	BEQ @NEXT_ENTRY
	LDA @VIRTUAL02
	STA NEW_ENTITY_VAR0
	LDX @LOCAL03
	TXA
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
.IF .DEFINED(JPN)
	STA @LOCAL02
.ENDIF
	BNE @CREATE_ENTITY
	JSL RAND
	AND #$0003
	ASL
	TAX
	LDA FOR_SALE_SIGN_SPRITE_TABLE,X
.IF .DEFINED(JPN)
	STA @LOCAL02
.ENDIF
@CREATE_ENTITY:
	STZ_BADOPT @LOCAL00
	STZ_BADOPT2 @LOCAL01
	LDY #.LOWORD(-1)
	LDX #EVENT_SCRIPT::EVENT_500
.IF .DEFINED(JPN)
	LDA @LOCAL02
.ENDIF
	JSL CREATE_ENTITY
@NEXT_ENTRY:
	INC @VIRTUAL02
@LOOP_CHECK:
	LDA @VIRTUAL02
	CMP #10
	BCC @LOOP_BODY
	END_C_FUNCTION
