
; Places player in world after loading a game
SPAWN:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	LDA RESPAWN_X
	STA @VIRTUAL02
	LDX RESPAWN_Y
	STX @LOCAL03
	JSL DISABLE_ALL_ENTITIES
	JSR INITIALIZE_GAME_OVER_SCREEN
	JSR PLAY_COMEBACK_SEQUENCE
	STA @VIRTUAL04
	CMP #0
	BEQ @COMEBACK_SEQUENCE_FAILED
	LDY #0
	LDX #1
	LDA #2
	JSL FADE_OUT_WITH_MOSAIC
	JSL ENABLE_ALL_ENTITIES
	JMP @DONE
@COMEBACK_SEQUENCE_FAILED:
	LDA #32
	JSL FADE_PALETTE_TO_WHITE
	LDA #2
	JSL WRITE_APU_PORT1
	SEP #PROC_FLAGS::ACCUM8
	LDA #$17
	STA TM_MIRROR
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(-1)
	STA LOADED_MAP_TILE_COMBO
	STA CURRENT_MAP_MUSIC_TRACK
	STA CURRENT_MUSIC_TRACK
	LDA #1
	STA WIPE_PALETTES_ON_MAP_LOAD
	.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
		JSL WAIT_UNTIL_NEXT_FRAME
	.ENDIF
	LDY #6
	LDX @LOCAL03
	LDA @VIRTUAL02
	JSL INITIALIZE_MAP
	LDA GAME_STATE + game_state::party_members
	AND #$00FF
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	STA CURRENT_PARTY_MEMBER_TICK
	LDA #0
	STA @LOCAL02
	BRA @CLEAR_AFFLICTIONS_CHECK
@CLEAR_AFFLICTIONS_LOOP:
	CLC
	ADC CURRENT_PARTY_MEMBER_TICK
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ a:char_struct::afflictions,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	INC
	STA @LOCAL02
@CLEAR_AFFLICTIONS_CHECK:
	CMP #6
	BCC @CLEAR_AFFLICTIONS_LOOP
	LDX CURRENT_PARTY_MEMBER_TICK
	LDA a:char_struct::max_hp,X
	LDX CURRENT_PARTY_MEMBER_TICK
	STA a:char_struct::current_hp_target,X
	LDX CURRENT_PARTY_MEMBER_TICK
	STA a:char_struct::current_hp,X
	LDX CURRENT_PARTY_MEMBER_TICK
	STZ a:char_struct::current_pp_target,X
	LDX CURRENT_PARTY_MEMBER_TICK
	STZ a:char_struct::current_pp,X
	LDY #.LOWORD(GAME_STATE) + game_state::money_carried
	STY @LOCAL01
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	MOVE_INT_CONSTANT 1, @VIRTUAL06
	AND_INT_ASSIGN @VIRTUAL0A, @VIRTUAL06
	PHA
	LDA @VIRTUAL0A
	PHA
	MOVE_INT_CONSTANT 2, @VIRTUAL0A
	MOVE_INT @LOCAL00, @VIRTUAL06
	JSL DIVISION32
	PULL32 @VIRTUAL0A
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	LDY @LOCAL01
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
		JSL REFRESH_PARTY_ENTITIES
	.ENDIF
	LDY #1
	STY @LOCAL03
	BRA @SET_EVENT_FLAGS_CHECK
@SET_EVENT_FLAGS_LOOP:
	LDX #0
	TYA
	JSL SET_EVENT_FLAG
	LDY @LOCAL03
	INY
	STY @LOCAL03
@SET_EVENT_FLAGS_CHECK:
	TYA
	CLC
	SBC #10
	BRANCHLTEQS @SET_EVENT_FLAGS_LOOP
	LDA #0
	STA @LOCAL02
	BRA @CLEAR_COLLISIONS_CHECK
@CLEAR_COLLISIONS_LOOP:
	ASL
	TAX
	LDA #ENTITY_COLLISION_NO_OBJECT
	STA ENTITY_COLLIDED_OBJECTS,X
	LDA @LOCAL02
	INC
	STA @LOCAL02
@CLEAR_COLLISIONS_CHECK:
	CMP #MAX_ENTITIES
	BCC @CLEAR_COLLISIONS_LOOP
	JSL RESET_QUEUED_INTERACTIONS
	STZ DAD_PHONE_QUEUED
	STZ PLAYER_INTANGIBILITY_FRAMES
	JSL SPAWN_BUZZ_BUZZ
	JSL OAM_CLEAR
	JSL ENABLE_ALL_ENTITIES
	LDA #32
	JSL ANIMATE_PALETTE_FADE_WITH_RENDERING
@DONE:
	LDA @VIRTUAL04
	END_C_FUNCTION
