
SPAWN_HORIZONTAL:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @LOCAL05
	TAY
	STY @LOCAL04
	LDA #EVENT_FLAG::FLG_SYS_MONSTER_OFF
	JSL GET_EVENT_FLAG
	CMP #0
	BNEL @RETURN
	LDA #EVENT_FLAG::FLG_WIN_GIEGU
	JSL GET_EVENT_FLAG
	CMP #0
	BNEL @RETURN
	LDA ENEMY_SPAWNS_ENABLED
	BEQL @RETURN
	LDX @LOCAL05
	TXA
	AND #$0007
	BNEL @RETURN
	CPX #$FFF0
	BCC @CHECK_Y_UPPER
	LDX #0
@CHECK_Y_UPPER:
	CPX #MAP_HEIGHT_TILES8
	BCC @Y_VALID
	JMP @RETURN
@Y_VALID:
	LDY @LOCAL04
	TYA
	ASL
	PHP
	LSR
	LSR
	LSR
	LSR
	PLP
	BCC @SIGN_EXTEND_X
.IF .DEFINED(JPN)
	ORA #$E000
.ELSE
	ORA #$F000
.ENDIF
@SIGN_EXTEND_X:
	STA @LOCAL03
	TXA
	ASL
	PHP
	LSR
	LSR
	LSR
	LSR
	PLP
	BCC @SIGN_EXTEND_Y
.IF .DEFINED(JPN)
	ORA #$E000
.ELSE
	ORA #$F000
.ENDIF
@SIGN_EXTEND_Y:
	STA @LOCAL02
	LDA @LOCAL03
	STA @VIRTUAL04
	BRA @COLUMN_LOOP_CHECK
@PROCESS_COLUMN:
	LDA @VIRTUAL04
	STA @LOCAL01
	LDA #8
	STA ENEMY_SPAWN_RANGE_WIDTH
	STA ENEMY_SPAWN_RANGE_HEIGHT
	LDA #1
	STA @VIRTUAL02
@SCAN_TILE:
	LDX @LOCAL02
	LDA @VIRTUAL04
	JSL GET_MAP_ENEMY_PLACEMENT
	STA @LOCAL04
	LDY @VIRTUAL04
	INY
	STY @LOCAL00
	LDX @LOCAL02
	TYA
	JSL GET_MAP_ENEMY_PLACEMENT
	TAX
	LDA @LOCAL04
	BEQ @SPAWN_LOOP_CHECK
	CPX @LOCAL04
	BNE @SPAWN_LOOP_CHECK
	LDA ENEMY_SPAWN_RANGE_WIDTH
	CLC
	ADC #8
	STA ENEMY_SPAWN_RANGE_WIDTH
	LDY @LOCAL00
	STY @VIRTUAL04
	INC @VIRTUAL02
	LDA @VIRTUAL02
	CMP #6
	BNE @SCAN_TILE
	BRA @SPAWN_LOOP_CHECK
@ATTEMPT_SPAWN:
	LDY @LOCAL04
	LDX @LOCAL02
	LDA @LOCAL01
	JSR ATTEMPT_ENEMY_SPAWN
@SPAWN_LOOP_CHECK:
	LDX @VIRTUAL02
	LDA @VIRTUAL02
	DEC
	STA @VIRTUAL02
	CPX #0
	BNE @ATTEMPT_SPAWN
	INC @VIRTUAL04
@COLUMN_LOOP_CHECK:
	LDA @LOCAL03
	CLC
	ADC #5
	CLC
	SBC @VIRTUAL04
	BRANCHGTS @PROCESS_COLUMN
@RETURN:
	END_C_FUNCTION
