
SPAWN_VERTICAL:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TXY
	STY @LOCAL05
	TAX
	STX @LOCAL04
	LDA #EVENT_FLAG::FLG_SYS_MONSTER_OFF
	JSL GET_EVENT_FLAG
	CMP #0
	BNEL @RETURN
	LDA #EVENT_FLAG::FLG_WIN_GIEGU
	JSL GET_EVENT_FLAG
	CMP #0
	BNEL @RETURN
	LDA ENEMY_SPAWNS_ENABLED
	BEQL @RETURN
	LDX @LOCAL04
	TXA
	AND #$0007
	BNEL @RETURN
	CPX #$FFF0
	BCC @CHECK_X_UPPER
	LDX #0
@CHECK_X_UPPER:
	CPX #MAP_WIDTH_TILES8
	BCC @SIGN_EXTEND_X
	JMP @RETURN
@SIGN_EXTEND_X:
	TXA
	ASL
	PHP
	LSR
	LSR
	LSR
	LSR
	PLP
	BCC @SIGN_EXTEND_Y
.IF .DEFINED(JPN)
	ORA #$E000
.ELSE
	ORA #$F000
.ENDIF
@SIGN_EXTEND_Y:
	STA @LOCAL03
	LDY @LOCAL05
	TYA
	ASL
	PHP
	LSR
	LSR
	LSR
	LSR
	PLP
	BCC @AFTER_SIGN_EXTEND_Y
.IF .DEFINED(JPN)
	ORA #$E000
.ELSE
	ORA #$F000
.ENDIF
@AFTER_SIGN_EXTEND_Y:
	STA @LOCAL02
	STA @VIRTUAL04
	BRA @ROW_LOOP_CHECK
@PROCESS_ROW:
	LDA @VIRTUAL04
	STA @LOCAL01
	LDA #8
	STA ENEMY_SPAWN_RANGE_WIDTH
	STA ENEMY_SPAWN_RANGE_HEIGHT
	LDA #1
	STA @VIRTUAL02
@SCAN_TILE:
	LDX @VIRTUAL04
	LDA @LOCAL03
	JSL GET_MAP_ENEMY_PLACEMENT
	STA @LOCAL05
	LDY @VIRTUAL04
	INY
	STY @LOCAL00
	TYX
	LDA @LOCAL03
	JSL GET_MAP_ENEMY_PLACEMENT
	TAX
	LDA @LOCAL05
	BEQ @SPAWN_LOOP_CHECK
	CPX @LOCAL05
	BNE @SPAWN_LOOP_CHECK
	LDA ENEMY_SPAWN_RANGE_HEIGHT
	CLC
	ADC #8
	STA ENEMY_SPAWN_RANGE_HEIGHT
	LDY @LOCAL00
	STY @VIRTUAL04
	INC @VIRTUAL02
	LDA @VIRTUAL02
	CMP #6
	BNE @SCAN_TILE
	BRA @SPAWN_LOOP_CHECK
@ATTEMPT_SPAWN:
	LDY @LOCAL05
	LDX @LOCAL01
	LDA @LOCAL03
	JSR ATTEMPT_ENEMY_SPAWN
@SPAWN_LOOP_CHECK:
	LDX @VIRTUAL02
	LDA @VIRTUAL02
	DEC
	STA @VIRTUAL02
	CPX #0
	BNE @ATTEMPT_SPAWN
	INC @VIRTUAL04
@ROW_LOOP_CHECK:
	LDA @LOCAL02
	CLC
	ADC #5
	CLC
	SBC @VIRTUAL04
	BRANCHGTS @PROCESS_ROW
@RETURN:
	END_C_FUNCTION
