
TALK_TO:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_RETURN_INT32
	END_STACK_VARS
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CREATE_WINDOW_NEAR #WINDOW::TEXT_STANDARD
	JSL FIND_NEARBY_TALKABLE_TPT_ENTRY
	LDA INTERACTING_NPC_ID
	BEQL @DONE
	LDA INTERACTING_NPC_ID
	CMP #.LOWORD(-1)
	BEQL @DONE
	LDA INTERACTING_NPC_ID
	CMP #.LOWORD(-2)
	BNE @LOOKUP_NPC_CONFIG
	MOVE_INT MAP_OBJECT_TEXT, @VIRTUAL0A
	BRA @DONE
@LOOKUP_NPC_CONFIG:
	LOADPTR NPC_CONFIG_TABLE, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA INTERACTING_NPC_ID
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(npc_config)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	CMP #NPC_TYPE::PERSON
	BEQ @PERSON_TYPE
	CMP #NPC_TYPE::ITEM_BOX
	BEQ @DONE
	CMP #NPC_TYPE::OBJECT
	BEQ @DONE
	BRA @DONE
@PERSON_TYPE:
	LDA INTERACTING_NPC_ENTITY
	JSL SET_ENTITY_DIRECTION_FROM_LEADER
	LDA INTERACTING_NPC_ID
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(npc_config)
	CLC
	ADC #npc_config::text_pointer
	MOVE_INTX @LOCAL00, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL0A
@DONE:
	MOVE_INT @VIRTUAL0A, @RETURNVAL
	END_C_FUNCTION
