
TEST_YOUR_SANCTUARY_DISPLAY:
	BEGIN_C_FUNCTION_FAR
.IF .DEFINED(JPN) ;this function never returns in mother 2
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16 "LOCATION"
	END_STACK_VARS
	JSL INITIALIZE_YOUR_SANCTUARY_DISPLAY
	LDX #0
	STX @LOCATION
@LOOP:
	STZ BG1_Y_POS
	STZ BG1_X_POS
	JSL UPDATE_SCREEN
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA PAD_STATE
	AND #PAD::R_BUTTON
	BNE @LOOP
	LDX @LOCATION
	TXA
	JSL DISPLAY_YOUR_SANCTUARY_LOCATION
	JSL ENABLE_YOUR_SANCTUARY_DISPLAY
	LDX @LOCATION
	INX
	STX @LOCATION
	CPX #8
	BNE @LOOP
	LDX #0
	STX @LOCATION
	BRA @LOOP
.ELSE
	END_C_FUNCTION
.ENDIF
