
UNLINK_ENTITY_FROM_LIST:
	JSR FIND_ENTITY_PREDECESSOR
	LDA ENTITY_NEXT_ENTITY_TABLE,X
	CPY #$FFFF
	BEQ @IS_HEAD
	STA ENTITY_NEXT_ENTITY_TABLE,Y
	BRA @CHECK_ACTIVE
@IS_HEAD:
	STA FIRST_ENTITY
@CHECK_ACTIVE:
	CPX NEXT_ACTIVE_ENTITY
	BNE @DONE
	STA NEXT_ACTIVE_ENTITY
@DONE:
	RTS
