
UNLINK_ACTION_SCRIPT:
	PHX
	JSR FIND_PREVIOUS_ACTION_SCRIPT
	LDA ENTITY_SCRIPT_NEXT_SCRIPTS,Y
	CPX #$FFFF
	BEQ @IS_HEAD
	STA ENTITY_SCRIPT_NEXT_SCRIPTS,X
	PLX
	BRA @CHECK_CURRENT
@IS_HEAD:
	PLX
	STA ENTITY_SCRIPT_INDEX_TABLE,X
@CHECK_CURRENT:
	CPY ACTIONSCRIPT_CURRENT_SCRIPT
	BNE @DONE
	STA ACTIONSCRIPT_CURRENT_SCRIPT
@DONE:
	RTS
