
UPDATE_MUSHROOM_STATUS:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA GAME_STATE+game_state::player_controlled_party_members
	AND #$00FF
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::afflictions
	TAX
	LDA __BSS_START__+1,X
	AND #$00FF
	CMP #$0001
	BNE @NOT_MUSHROOMIZED
	LDA #$0001
	STA MUSHROOMIZED_WALKING_FLAG
	LDA MUSHROOMIZATION_TIMER
	BNE @CHECK_BICYCLE
	LDA #$0708
	STA MUSHROOMIZATION_TIMER
	STZ MUSHROOMIZATION_MODIFIER
@CHECK_BICYCLE:
	LDA GAME_STATE+game_state::walking_style
	CMP #WALKING_STYLE::BICYCLE
	BNE @RETURN
	JSL DISMOUNT_BICYCLE
	BRA @RETURN
@NOT_MUSHROOMIZED:
	STZ MUSHROOMIZED_WALKING_FLAG
@RETURN:
	RTL
