
UPDATE_PARTY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_ARRAY 6, 2 ;int[6]
	STACK_RESERVE_ARRAY 6, 2 ;int[6]
	STACK_RESERVE_ARRAY 6, 2 ;int[6]
	STACK_RESERVE_ARRAY 6, 2 ;int[6]
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16 "PARTY_COUNT"
	END_STACK_VARS
	LDA GAME_STATE+game_state::party_count
	AND #$00FF
	STA @PARTY_COUNT
	LDA #0
	STA @LOCAL08
	BRA @SAVE_POSITION_LOOP_CHECK
@SAVE_POSITION_INDEX:
	ASL
	PHA
	LDA @LOCAL08
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::player_controlled_party_members,X
	AND #$00FF
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::position_index,X
	PLX
	STA @LOCAL00,X
	LDA @LOCAL08
	INC
	STA @LOCAL08
@SAVE_POSITION_LOOP_CHECK:
	CMP @PARTY_COUNT
	BCC @SAVE_POSITION_INDEX
	LDX #0
	STX @LOCAL07
	JMP @BUILD_SORT_LOOP_CHECK
@BUILD_SORT_ENTRY:
	TXA
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_order,X
	AND #$00FF
	STA @LOCAL06
	CMP #5
	BCC @CHECK_AFFLICTION
	CLC
	ADC #$0300
	STA @LOCAL06
	BRA @STORE_SORT_DATA
@CHECK_AFFLICTION:
	LDX @LOCAL07
	TXA
	ASL
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_entity_slots,X
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR1_TABLE,X
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::afflictions,X
	AND #$00FF
	TAY
	CPY #1
	BEQ @HAS_STATUS_PENALTY
	CPY #2
	BNE @STORE_SORT_DATA
@HAS_STATUS_PENALTY:
	LDA @LOCAL06
	CLC
	ADC #$0100
	STA @LOCAL06
@STORE_SORT_DATA:
	LDX @LOCAL07
	TXA
	ASL
	TAY
	LDA @LOCAL06
	TYX
	STA @LOCAL01,X
	TYA
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_entity_slots,X
	TAX
	STX @LOCAL02,Y
	LDX @LOCAL07
	TXA
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::player_controlled_party_members,X
	AND #$00FF
	TAX
	STX @LOCAL03,Y
	LDX @LOCAL07
	INX
	STX @LOCAL07
@BUILD_SORT_LOOP_CHECK:
	CPX @PARTY_COUNT
	BCCL @BUILD_SORT_ENTRY
	STZ_BADOPT @VIRTUAL04
	JMP @OUTER_SORT_LOOP_CHECK
@SORT_INNER_INIT:
	LDX #0
	STX @LOCAL08
	BRA @INNER_SORT_LOOP_CHECK
@COMPARE_ADJACENT:
	TXA
	ASL
	TAY
	TYX
	LDA @LOCAL01,X
	STA @LOCAL05
	STY @VIRTUAL02
	INC @VIRTUAL02
	INC @VIRTUAL02
	LDX @VIRTUAL02
	LDA @LOCAL01,X
	STA @LOCAL04
	LDA @LOCAL05
	CMP @LOCAL04
	BLTEQ @NEXT_INNER
	LDX @LOCAL08
	TXA
	ASL
	TAX
	LDA @LOCAL04
	STA @LOCAL01,X
	LDX @LOCAL08
	TXA
	ASL
	TAX
	INX
	INX
	LDA @LOCAL05
	STA @LOCAL01,X
	TYX
	LDA @LOCAL02,X
	STA @LOCAL05
	LDX @LOCAL08
	TXA
	ASL
	PHA
	LDX @VIRTUAL02
	LDA @LOCAL02,X
	PLX
	STA @LOCAL02,X
	LDX @LOCAL08
	TXA
	ASL
	TAX
	INX
	INX
	LDA @LOCAL05
	STA @LOCAL02,X
	LDX @LOCAL03,Y
	TXY
	LDX @LOCAL08
	TXA
	ASL
	PHA
	LDX @VIRTUAL02
	LDA @LOCAL03,X
	PLX
	STA @LOCAL03,X
	LDX @LOCAL08
	TXA
	ASL
	TAX
	INX
	INX
	STY @LOCAL03,X
@NEXT_INNER:
	LDX @LOCAL08
	INX
	STX @LOCAL08
@INNER_SORT_LOOP_CHECK:
	LDA @PARTY_COUNT
	DEC
	STA @VIRTUAL02
	TXA
	CMP @VIRTUAL02
	BCC @COMPARE_ADJACENT
	INC @VIRTUAL04
@OUTER_SORT_LOOP_CHECK:
	LDA @PARTY_COUNT
	DEC
	STA @VIRTUAL02
	LDA @VIRTUAL04
	CMP @VIRTUAL02
	BCCL @SORT_INNER_INIT
	LDA #0
	STA @LOCAL06
	BRA @WRITE_SORTED_LOOP_CHECK
@WRITE_SORTED_ENTRY:
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAY
	LDA @LOCAL06
	ASL
	STA @VIRTUAL02
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01,X
	STA a:game_state::party_order,Y
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(GAME_STATE)
	CLC
	ADC #game_state::party_entity_slots
	TAX
	STX @LOCAL08
	LDX @VIRTUAL02
	LDA @LOCAL02,X
	LDX @LOCAL08
	STA __BSS_START__,X
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03,X
	STA a:game_state::player_controlled_party_members,Y
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL06
	ASL
	TAX
	LDA @LOCAL03,X
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	PHA
	LDX @VIRTUAL02
	LDA @LOCAL00,X
	PLX
	STA PARTY_CHARACTERS+char_struct::position_index,X
	LDX @LOCAL08
	LDA __BSS_START__,X
	ASL
	TAX
	LDA @VIRTUAL02
	STA ENTITY_SCRIPT_VAR5_TABLE,X
	LDA @LOCAL06
	INC
	STA @LOCAL06
@WRITE_SORTED_LOOP_CHECK:
	CMP @PARTY_COUNT
	BCC @WRITE_SORTED_ENTRY
	LDA GAME_STATE +game_state::party_entity_slots
	STA GAME_STATE+game_state::current_party_members
	JSL UPDATE_NPC_PARTY_LINEUP
	JSL UPDATE_MUSHROOM_STATUS
	JSL LOAD_CHARACTER_WINDOW_PALETTE
	END_C_FUNCTION
