
UPDATE_LEADER_MOVEMENT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX #.LOWORD(GAME_STATE) + game_state::leader_moved
	LDA __BSS_START__,X
	STA @LOCAL03
	LDA #0
	STA __BSS_START__,X
	LDA PLAYER_INTANGIBILITY_FRAMES
	BEQ @CHECK_DEBUG
	JSL CLEAR_PARTY_SPRITE_HIDE_FLAGS
	DEC PLAYER_INTANGIBILITY_FRAMES
@CHECK_DEBUG:
	LDA DEBUG
	BEQ @SYNC_POSITION_INDEX
	LDA PAD_STATE
	AND #PAD::X_BUTTON
	BEQ @SYNC_POSITION_INDEX
	LDA FRAME_COUNTER
	AND #$00FF
	AND #$000F
	BNEL @RETURN
@SYNC_POSITION_INDEX:
	LDA GAME_STATE+game_state::current_party_members
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR1_TABLE,X
	ASL
	TAX
	LDA CHOSEN_FOUR_PTRS,X
	TAX
	LDA GAME_STATE + game_state::unknown88
	STA a:char_struct::position_index,X
	LDA GAME_STATE + game_state::camera_mode
	BEQ @DISPATCH_BY_WALKING_STYLE
	JSR UPDATE_SPECIAL_CAMERA_MODE
	BRA @AFTER_MOVEMENT
@DISPATCH_BY_WALKING_STYLE:
	LDA GAME_STATE+game_state::walking_style
	CMP #WALKING_STYLE::ESCALATOR
	BEQ @DISPATCH_ESCALATOR
	CMP #WALKING_STYLE::BICYCLE
	BEQ @DISPATCH_BICYCLE
	BRA @DISPATCH_NORMAL
@DISPATCH_ESCALATOR:
	JSR UPDATE_ESCALATOR_MOVEMENT
	BRA @AFTER_MOVEMENT
@DISPATCH_BICYCLE:
	LDA @LOCAL03
	JSR UPDATE_BICYCLE_MOVEMENT
	BRA @AFTER_MOVEMENT
@DISPATCH_NORMAL:
	JSR UPDATE_OVERWORLD_PLAYER_INPUT
@AFTER_MOVEMENT:
	LDA #.LOWORD(GAME_STATE) + game_state::unknown88
	STA @LOCAL03
	LDA (@LOCAL03)
	STA @LOCAL02
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(player_position_buffer_entry)
	CLC
	ADC #.LOWORD(PLAYER_POSITION_BUFFER)
	STA @LOCAL01
	LDA #.LOWORD(GAME_STATE) + game_state::leader_x_coord
	STA @VIRTUAL04
	LDA #.LOWORD(GAME_STATE) + game_state::leader_y_coord
	STA @VIRTUAL02
	LDY GAME_STATE+game_state::current_party_members
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	TAX
	STX @LOCAL00
	LDX @VIRTUAL04
	LDA __BSS_START__,X
	LDX @LOCAL00
	JSL CHECK_PLAYER_COLLISION_AT_POSITION
	STA GAME_STATE+game_state::trodden_tile_type
	LDA GAME_STATE + game_state::leader_moved
	BEQ @LEADER_NOT_MOVED
	LDX @VIRTUAL04
	LDA __BSS_START__,X
	STA (@LOCAL01) ;player_position_buffer_entry::x_coord
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	LDY #player_position_buffer_entry::y_coord
	STA (@LOCAL01),Y
	LDA @LOCAL02
	INC
	AND #$00FF
	STA (@LOCAL03)
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	TAX
	STX @LOCAL00
	LDX @VIRTUAL04
	LDA __BSS_START__,X
	LDX @LOCAL00
	JSL CENTER_SCREEN
	LDA #1
	STA UNREAD_7E4DD4
	BRA @STORE_BUFFER_FIELDS
@LEADER_NOT_MOVED:
	STZ UNREAD_7E4DD4
@STORE_BUFFER_FIELDS:
	LDX #.LOWORD(GAME_STATE)+game_state::trodden_tile_type
	LDA __BSS_START__,X
	LDY #player_position_buffer_entry::tile_flags
	STA (@LOCAL01),Y
	LDA GAME_STATE+game_state::walking_style
	LDY #player_position_buffer_entry::walking_style
	STA (@LOCAL01),Y
	LDA GAME_STATE+game_state::leader_direction
	LDY #player_position_buffer_entry::direction
	STA (@LOCAL01),Y
	LDY #.LOWORD(FOOTSTEP_SOUND_ID_OVERRIDE)
	LDA #0
	STA __BSS_START__,Y
	LDA __BSS_START__,X
	STA @LOCAL03
	AND #$0008
	BEQ @RETURN
	LDA @LOCAL03
	AND #$0004
	BEQ @FOOTSTEP_INDOOR
	LDA #16
	STA __BSS_START__,Y
	BRA @RETURN
@FOOTSTEP_INDOOR:
	LDA #18
	STA __BSS_START__,Y
@RETURN:
	END_C_FUNCTION
