
UPDATE_PARTY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_ARRAY 6, 2 ;int[6]
	STACK_RESERVE_ARRAY 6, 2 ;int[6]
	STACK_RESERVE_ARRAY 6, 2 ;int[6]
	STACK_RESERVE_ARRAY 6, 2 ;int[6]
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16 "PARTY_COUNT"
	END_STACK_VARS
	LDA GAME_STATE+game_state::party_count
	AND #$00FF
	STA @PARTY_COUNT
	LDA #0
	STA @LOCAL0A
	BRA @SAVE_POSITION_CHECK
@SAVE_POSITION_LOOP:
	ASL
	PHA
	LDA @LOCAL0A
	TAX
	LDA GAME_STATE+game_state::player_controlled_party_members,X
	AND #$00FF
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::position_index,X
	PLX
	STA @LOCAL00,X
	LDA @LOCAL0A
	INC
	STA @LOCAL0A
@SAVE_POSITION_CHECK:
	CMP @PARTY_COUNT
	BCC @SAVE_POSITION_LOOP
	LDY #0
	STY @LOCAL09
	BRA @BUILD_ARRAYS_CHECK
@BUILD_ARRAYS_LOOP:
	LDA GAME_STATE + game_state::party_order,Y
	AND #$00FF
	STA @LOCAL08
	CMP #5
	BCC @CHECK_AFFLICTION
	CLC
	ADC #$0300
	STA @LOCAL08
	BRA @STORE_MEMBER_DATA
@CHECK_AFFLICTION:
	TYA
	ASL
	TAX
	LDA GAME_STATE + game_state::party_entity_slots,X
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR1_TABLE,X
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::afflictions,X
	AND #$00FF
	TAX
	CPX #1
	BEQ @HAS_INCAPACITATING_AFFLICTION
	CPX #2
	BNE @STORE_MEMBER_DATA
@HAS_INCAPACITATING_AFFLICTION:
	LDA @LOCAL08
	CLC
	ADC #$0100
	STA @LOCAL08
@STORE_MEMBER_DATA:
	LDY @LOCAL09
	TYA
	ASL
	TAX
	LDA @LOCAL08
	STA @LOCAL01,X
	LDA GAME_STATE + game_state::party_entity_slots,X
	STA @LOCAL02,X
	LDA GAME_STATE + game_state::player_controlled_party_members,Y
	AND #$00FF
	STA @LOCAL03,X
	INY
	STY @LOCAL09
@BUILD_ARRAYS_CHECK:
	CPY @PARTY_COUNT
	BCC @BUILD_ARRAYS_LOOP
	STZ @LOCAL07
	JMP @SORT_OUTER_CHECK
@SORT_OUTER_LOOP:
	STZ @LOCAL06
	JMP @SORT_INNER_CHECK
@SORT_INNER_LOOP:
	LDA @LOCAL06
	ASL
	STA @VIRTUAL02
	TDC
	CLC
	ADC #@LOCAL01
	CLC
	ADC @VIRTUAL02
	TAY
	LDA __BSS_START__,Y
	STA @LOCAL08
	LDA @VIRTUAL02
	STA @VIRTUAL04
	INC @VIRTUAL04
	INC @VIRTUAL04
	TDC
	CLC
	ADC #@LOCAL01
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	STA @LOCAL0A
	LDA @LOCAL08
	CMP @LOCAL0A
	BLTEQ @SKIP_SWAP
	LDA @LOCAL0A
	STA __BSS_START__,Y
	LDA @LOCAL08
	STA __BSS_START__,X
	TDC
	CLC
	ADC #@LOCAL02
	CLC
	ADC @VIRTUAL02
	TAY
	LDA __BSS_START__,Y
	STA @LOCAL05
	TDC
	CLC
	ADC #@LOCAL02
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	STA __BSS_START__,Y
	LDA @LOCAL05
	STA __BSS_START__,X
	TDC
	CLC
	ADC #@LOCAL03
	CLC
	ADC @VIRTUAL02
	TAY
	LDA __BSS_START__,Y
	STA @LOCAL0A
	TDC
	CLC
	ADC #@LOCAL03
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	STA __BSS_START__,Y
	LDA @LOCAL0A
	STA __BSS_START__,X
@SKIP_SWAP:
	INC @LOCAL06
@SORT_INNER_CHECK:
	LDA @PARTY_COUNT
	DEC
	CMP @LOCAL06
	BGTL @SORT_INNER_LOOP
	INC @LOCAL07
@SORT_OUTER_CHECK:
	LDA @PARTY_COUNT
	DEC
	CMP @LOCAL07
	BGTL @SORT_OUTER_LOOP
	LDA #0
	STA @LOCAL08
	BRA @WRITEBACK_CHECK
@WRITEBACK_LOOP:
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAY
	LDA @LOCAL08
	ASL
	STA @VIRTUAL04
	LDX @VIRTUAL04
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01,X
	STA __BSS_START__ + game_state::party_order,Y
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	CLC
	ADC #.LOWORD(GAME_STATE) + game_state::party_entity_slots
	TAX
	STX @LOCAL04
	LDX @VIRTUAL04
	LDA @LOCAL02,X
	LDX @LOCAL04
	STA __BSS_START__,X
	TDC
	CLC
	ADC #@LOCAL03
	CLC
	ADC @VIRTUAL04
	STA @VIRTUAL02
	LDX @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA __BSS_START__ + game_state::player_controlled_party_members,Y
	LDX @VIRTUAL02
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	PHA
	LDX @VIRTUAL04
	LDA @LOCAL00,X
	PLX
	STA PARTY_CHARACTERS+char_struct::position_index,X
	LDX @LOCAL04
	LDA __BSS_START__,X
	ASL
	TAX
	LDA @VIRTUAL04
	STA ENTITY_SCRIPT_VAR5_TABLE,X
	LDA @LOCAL08
	INC
	STA @LOCAL08
@WRITEBACK_CHECK:
	CMP @PARTY_COUNT
	BCC @WRITEBACK_LOOP
	LDA GAME_STATE +game_state::party_entity_slots
	STA GAME_STATE+game_state::current_party_members
	JSL UPDATE_NPC_PARTY_LINEUP
	JSL UPDATE_MUSHROOM_STATUS
	JSL LOAD_CHARACTER_WINDOW_PALETTE
	END_C_FUNCTION
