
UPDATE_OVERWORLD_FRAME:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA BATTLE_MODE
	BNEL @RETURN
	LDA POSSESSED_PLAYER_COUNT
	BEQ @MINI_GHOST_EXISTS
	LDA MINI_GHOST_ENTITY_ID
	CMP #.LOWORD(-1)
	BNE @ANIMATE_TILES
	JSL CREATE_MINI_GHOST_ENTITY
	BRA @ANIMATE_TILES
@MINI_GHOST_EXISTS:
	LDA MINI_GHOST_ENTITY_ID
	CMP #.LOWORD(-1)
	BEQ @ANIMATE_TILES
	JSL DESTROY_MINI_GHOST_ENTITY
@ANIMATE_TILES:
	LDA LOADED_ANIMATED_TILE_COUNT
	BEQ @ANIMATE_PALETTE
	JSL ANIMATE_TILESET
@ANIMATE_PALETTE:
	LDA MAP_PALETTE_ANIMATION_LOADED
	BEQ @PROCESS_TRANSFORMATIONS
	JSL ANIMATE_PALETTE
@PROCESS_TRANSFORMATIONS:
	LDA ITEM_TRANSFORMATIONS_LOADED
	BEQ @UPDATE_SECTOR_MUSIC
	JSL PROCESS_ITEM_TRANSFORMATIONS
@UPDATE_SECTOR_MUSIC:
	JSL UPDATE_LEADER_MOVEMENT
	LDA GAME_STATE+game_state::leader_x_coord
	XBA
	AND #$00FF
	STA @LOCAL00
	LDA GAME_STATE+game_state::leader_y_coord
	XBA
	AND #$00FF
	TAX
	LDA @LOCAL00
	EOR LAST_SECTOR_X
	BNE @SECTOR_CHANGED
	TXA
	EOR LAST_SECTOR_Y
	BEQ @CHECK_DAD_PHONE
@SECTOR_CHANGED:
	LDA @LOCAL00
	STA LAST_SECTOR_X
	STX LAST_SECTOR_Y
	LDA ENABLE_AUTO_SECTOR_MUSIC_CHANGES
	BEQ @CHECK_DAD_PHONE
	JSR FADE_TO_MAP_MUSIC_AT_LEADER
@CHECK_DAD_PHONE:
	LDA DAD_PHONE_TIMER
	BNE @UPDATE_PLAYER_STATE
	LDA GAME_STATE + game_state::camera_mode
	CMP #2
	BEQ @UPDATE_PLAYER_STATE
	JSL LOAD_DAD_PHONE
@UPDATE_PLAYER_STATE:
	STZ POSSESSED_PLAYER_COUNT
	LDA GAME_STATE+game_state::leader_direction
	STA CURRENT_LEADER_DIRECTION
	LDA GAME_STATE+game_state::current_party_members
	ASL
	STA CURRENT_LEADING_PARTY_MEMBER_ENTITY
	LDA GAME_STATE + game_state::leader_moved
	BEQ @RETURN
	LDA #1
	STA PLAYER_HAS_DONE_SOMETHING_THIS_FRAME
@RETURN:
	END_C_FUNCTION
