
UPDATE_FOLLOWER_STATE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA GAME_STATE + game_state::camera_mode
	CMP #3
	BEQL @RETURN
	LDA BATTLE_SWIRL_COUNTDOWN
	BNEL @RETURN
	LDA ENEMY_HAS_BEEN_TOUCHED
	BNEL @RETURN
	LDA BATTLE_MODE
	BNEL @RETURN
	LDA CURRENT_ENTITY_SLOT
	STA @VIRTUAL04
	STA @LOCAL07
	LDA @VIRTUAL04
	ASL
	TAX
	STX @LOCAL06
	LDA ENTITY_SCRIPT_VAR0_TABLE,X
	STA @LOCAL05
	LDA ENTITY_SCRIPT_VAR1_TABLE,X
	ASL
	TAX
	LDY CHOSEN_FOUR_PTRS,X
	STY CURRENT_PARTY_MEMBER_TICK
	LDA a:char_struct::position_index,Y
	STA @LOCAL04
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(player_position_buffer_entry)
	CLC
	ADC #.LOWORD(PLAYER_POSITION_BUFFER)
	STA @LOCAL03
	LDY #player_position_buffer_entry::direction
	LDA (@LOCAL03),Y
	LDX @LOCAL06
	STA ENTITY_DIRECTIONS,X
	LDY #player_position_buffer_entry::tile_flags
	LDA (@LOCAL03),Y
	STA ENTITY_SURFACE_FLAGS,X
	LDA @LOCAL03
	CLC
	ADC #player_position_buffer_entry::walking_style
	STA @VIRTUAL02
	LDY CURRENT_ENTITY_SLOT
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	TAX
	LDA @LOCAL05
	JSL UPDATE_PARTY_ENTITY_GRAPHICS
	LDA GAME_STATE + game_state::leader_moved
	BNE @POSITION_UPDATE
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	CMP #12
	BNEL @RETURN
@POSITION_UPDATE:
	LDA @LOCAL07
	STA @VIRTUAL04
	ASL
	TAX
	LDA (@LOCAL03) ;player_position_buffer_entry::x_coord
	STA ENTITY_ABS_X_TABLE,X
	LDY #player_position_buffer_entry::y_coord
	LDA (@LOCAL03),Y
	STA ENTITY_ABS_Y_TABLE,X
	LDX #0
	STX @LOCAL07
	LDA GAME_STATE + game_state::party_order
	AND #$00FF
	STA @VIRTUAL02
	LDA @LOCAL05
	INC
	CMP @VIRTUAL02
	BEQ @COMPUTE_SPACING
	LDY #player_position_buffer_entry::walking_style
	LDA (@LOCAL03),Y
	AND #$00FF
	CMP #WALKING_STYLE::LADDER
	BEQ @SPACING_LADDER_ROPE
	CMP #WALKING_STYLE::ROPE
	BEQ @SPACING_LADDER_ROPE
	CMP #WALKING_STYLE::ESCALATOR
	BEQ @SPACING_ESCALATOR
	CMP #WALKING_STYLE::STAIRS
	BEQ @SPACING_STAIRS
	BRA @SPACING_DEFAULT
@SPACING_LADDER_ROPE:
	LDA #30
	STA @LOCAL02
	BRA @COMPUTE_SPACING
@SPACING_ESCALATOR:
	LDA GAME_STATE+game_state::walking_style
	BNE @ESCALATOR_HAS_STYLE
	LDX #1
	STX @LOCAL07
	BRA @COMPUTE_SPACING
@ESCALATOR_HAS_STYLE:
	LDA #30
	STA @LOCAL02
	BRA @COMPUTE_SPACING
@SPACING_STAIRS:
	LDA #24
	STA @LOCAL02
	BRA @COMPUTE_SPACING
@SPACING_DEFAULT:
	LDA GAME_STATE + game_state::character_mode
	CMP #3
	BNE @SPACING_NORMAL
	LDA #8
	STA @LOCAL02
	BRA @COMPUTE_SPACING
@SPACING_NORMAL:
	LDA #12
	STA @LOCAL02
@COMPUTE_SPACING:
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR0_TABLE,X
	ASL
	TAX
	LDA f:CHARACTER_SIZES,X
	CLC
	ADC @LOCAL02
	STA @LOCAL01
	LDY #player_position_buffer_entry::walking_style
	LDA (@LOCAL03),Y
	LDX CURRENT_PARTY_MEMBER_TICK
	STA a:char_struct::buffer_walking_style,X
	LDA GAME_STATE + game_state::party_order
	AND #$00FF
	STA @VIRTUAL02
	LDA @LOCAL05
	INC
	CMP @VIRTUAL02
	BEQ @SIMPLE_ADVANCE
	LDX @LOCAL07
	BNE @SIMPLE_ADVANCE
	LDA #2
	STA @LOCAL00
	LDY @LOCAL04
	LDA @LOCAL01
	TAX
	LDA @LOCAL05
	JSL ADJUST_PARTY_MEMBER_VISIBILITY
.IF .DEFINED(JPN)
	STA @LOCAL01
.ELSE
	STA @LOCAL06
.ENDIF
	BRA @STORE_POSITION_INDEX
@SIMPLE_ADVANCE:
	LDA @LOCAL04
	INC
.IF .DEFINED(JPN)
	STA @LOCAL01
.ELSE
	STA @LOCAL06
.ENDIF
	LDA CURRENT_ENTITY_SLOT
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SCRIPT_VAR7_TABLE)
	TAX
	LDA __BSS_START__,X
	AND #$FFFF ^ (SPRITE_TABLE_10_FLAGS::SPACING_HIDE)
	STA __BSS_START__,X
@STORE_POSITION_INDEX:
.IF .DEFINED(JPN)
	LDA @LOCAL01
.ELSE
	LDA @LOCAL06
.ENDIF
	AND #$00FF
	LDX CURRENT_PARTY_MEMBER_TICK
	STA a:char_struct::position_index,X
@RETURN:
	END_C_FUNCTION
