
UPDATE_OVERWORLD_DAMAGE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA GAME_STATE + game_state::camera_mode
	CMP #2
	BNE @CAMERA_OK
	LDA #1
	JMP @RETURN
@CAMERA_OK:
	LDA OVERWORLD_STATUS_SUPPRESSION
	BEQ @NOT_SUPPRESSED
	LDA #1
	JMP @RETURN
@NOT_SUPPRESSED:
	STZ @LOCAL04
	STZ @LOCAL03
	LDA #0
	STA @VIRTUAL04
	STA @VIRTUAL02
	STA @LOCAL02
	JMP @PARTY_LOOP_CHECK
@PROCESS_PARTY_MEMBER:
	LDA __BSS_START__+game_state::player_controlled_party_members,X
	AND #$00FF
	ASL
	TAX
	LDA CHOSEN_FOUR_PTRS,X
	STA CURRENT_PARTY_MEMBER_TICK
	TAX
	LDA __BSS_START__+char_struct::afflictions,X
	AND #$00FF
	TAY
	STY @LOCAL01
	CPY #1
	BEQL @NEXT_PARTY_MEMBER
	CPY #2
	BEQL @NEXT_PARTY_MEMBER
	CPY #5
	BNE @CHECK_ENVIRONMENTAL_DAMAGE
	LDA @VIRTUAL02
	ASL
	CLC
	ADC #.LOWORD(OVERWORLD_DAMAGE_COUNTDOWN_FRAMES)
	TAX
	LDA __BSS_START__,X
	BEQ @RESET_POISON_TIMER
	DEC
	STA __BSS_START__,X
	BNEL @AFTER_DAMAGE
	INC @VIRTUAL04
	LDA CURRENT_PARTY_MEMBER_TICK
	CLC
	ADC #char_struct::current_hp
	TAX
	LDA __BSS_START__,X
	SEC
	SBC #10
	STA __BSS_START__,X
	LDA CURRENT_PARTY_MEMBER_TICK
	CLC
	ADC #char_struct::current_hp_target
	TAX
	LDA __BSS_START__,X
	SEC
	SBC #10
	STA __BSS_START__,X
	LDA @VIRTUAL02
	JSR CHECK_LOW_HP_ALERT
	JMP @AFTER_DAMAGE
@RESET_POISON_TIMER:
	LDA #120
	STA __BSS_START__,X
	JMP @AFTER_DAMAGE
@CHECK_ENVIRONMENTAL_DAMAGE:
	CPY #4
	BCC @CHECK_HOT_TILE
	CPY #7
	BLTEQ @APPLY_ENV_DAMAGE
@CHECK_HOT_TILE:
	LDA GAME_STATE+game_state::trodden_tile_type
	AND #$000C
	CMP #12
	BNEL @AFTER_DAMAGE
@APPLY_ENV_DAMAGE:
	LDA @VIRTUAL02
	ASL
	CLC
	ADC #.LOWORD(OVERWORLD_DAMAGE_COUNTDOWN_FRAMES)
	TAX
	LDA __BSS_START__,X
	BEQ @RESET_ENV_TIMER
	DEC
	STA __BSS_START__,X
	BNE @AFTER_DAMAGE
	INC @VIRTUAL04
	CPY #4
	BNE @REDUCE_HP_BY_2
	LDA CURRENT_PARTY_MEMBER_TICK
	CLC
	ADC #char_struct::current_hp
	TAX
	LDA __BSS_START__,X
	SEC
	SBC #10
	STA __BSS_START__,X
	LDA CURRENT_PARTY_MEMBER_TICK
	CLC
	ADC #char_struct::current_hp_target
	TAX
	LDA __BSS_START__,X
	SEC
	SBC #10
	STA __BSS_START__,X
	BRA @AFTER_HP_REDUCE
@REDUCE_HP_BY_2:
	LDA CURRENT_PARTY_MEMBER_TICK
	CLC
	ADC #char_struct::current_hp
	TAX
	LDA __BSS_START__,X
	DEC
	DEC
	STA __BSS_START__,X
	LDA CURRENT_PARTY_MEMBER_TICK
	CLC
	ADC #char_struct::current_hp_target
	TAX
	LDA __BSS_START__,X
	DEC
	DEC
	STA __BSS_START__,X
@AFTER_HP_REDUCE:
	LDA @VIRTUAL02
	JSR CHECK_LOW_HP_ALERT
	BRA @AFTER_DAMAGE
@RESET_ENV_TIMER:
	CPY #4
	BNE @SET_SLOW_TIMER
	LDA #120
	STA __BSS_START__,X
	BRA @AFTER_DAMAGE
@SET_SLOW_TIMER:
	LDA #240
	STA __BSS_START__,X
@AFTER_DAMAGE:
	LDX CURRENT_PARTY_MEMBER_TICK
	LDA __BSS_START__+char_struct::current_hp,X
	CMP #$8000
	BGT @HP_DEPLETED
	CMP #0
	BNE @HP_POSITIVE
@HP_DEPLETED:
	LDY @LOCAL01
	CPY #1
	BEQ @NEXT_PARTY_MEMBER
	LDA #0
	STA @LOCAL00
	BRA @CLEAR_AFFLICTION_CHECK
@CLEAR_AFFLICTION_LOOP:
	LDA @LOCAL00
	CLC
	ADC CURRENT_PARTY_MEMBER_TICK
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ __BSS_START__+char_struct::afflictions,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	INC
	STA @LOCAL00
@CLEAR_AFFLICTION_CHECK:
	STA @VIRTUAL02
	LDA #6
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @CLEAR_AFFLICTION_LOOP
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	LDX CURRENT_PARTY_MEMBER_TICK
	STA a:char_struct::afflictions,X
	LDX CURRENT_PARTY_MEMBER_TICK
	REP #PROC_FLAGS::ACCUM8
	STZ a:char_struct::current_hp_target,X
	LDX CURRENT_PARTY_MEMBER_TICK
	STZ a:char_struct::current_hp,X
	LDX CURRENT_PARTY_MEMBER_TICK
	LDA a:char_struct::unknown59,X
	ASL
	TAX
	LDA #16
	STA ENTITY_SCRIPT_VAR3_TABLE,X
	INC @LOCAL04
	BRA @NEXT_PARTY_MEMBER
@HP_POSITIVE:
	LDY @LOCAL01
	CPY #2
	BEQ @NEXT_PARTY_MEMBER
	CLC
	ADC @LOCAL03
	STA @LOCAL03
@NEXT_PARTY_MEMBER:
	LDA @LOCAL02
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL02
@PARTY_LOOP_CHECK:
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA __BSS_START__+game_state::party_order,X
	AND #$00FF
	BEQ @PARTY_LOOP_DONE
	AND #$00FF
	CLC
	SBC #4
	JUMPLTEQS @PROCESS_PARTY_MEMBER
@PARTY_LOOP_DONE:
	LDA @VIRTUAL04
	BEQ @CHECK_KO
	JSR START_ENEMY_TOUCH_FLASH
@CHECK_KO:
	LDA @LOCAL04
	BEQ @CHECK_TOTAL_DAMAGE
	STZ PARTY_MEMBERS_ALIVE_OVERWORLD
	JSL UPDATE_PARTY
	JSL REFRESH_PARTY_ENTITIES
	JSL ENABLE_ALL_ENTITIES
@CHECK_TOTAL_DAMAGE:
	LDA @LOCAL03
@RETURN:
	END_C_FUNCTION
