
UPDATE_BICYCLE_MOVEMENT:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL07
	LDA GAME_STATE+game_state::walking_style
	JSL MAP_INPUT_TO_DIRECTION
	TAY
	STY @LOCAL06
	STY @VIRTUAL02
	LDA BATTLE_SWIRL_COUNTDOWN
	BEQ @CHECK_R_BUTTON
	LDX BATTLE_SWIRL_COUNTDOWN
	DEX
	STX BATTLE_SWIRL_COUNTDOWN
	BEQ @TRIGGER_BATTLE
	LDY GAME_STATE+game_state::current_party_members
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL NPC_COLLISION_CHECK
	JMP @RETURN
@TRIGGER_BATTLE:
	LDA #.LOWORD(-1)
	STA BATTLE_MODE
	JMP @RETURN
@CHECK_R_BUTTON:
	LDA PAD_PRESS
	AND #PAD::R_BUTTON
	BEQ @CHECK_DIRECTION
	LDA #SFX::BICYCLE_BELL
	JSL PLAY_SOUND
@CHECK_DIRECTION:
	LDY @LOCAL06
	CPY #.LOWORD(-1)
	BNE @DIAGONAL_TURN_CHECK
	LDX @LOCAL07
	BEQ @STOPPED
	LDY GAME_STATE+game_state::leader_direction
	STY @LOCAL06
	BRA @DIAGONAL_TURN_CHECK
@STOPPED:
	LDY GAME_STATE+game_state::current_party_members
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL NPC_COLLISION_CHECK
	JMP @RETURN
@DIAGONAL_TURN_CHECK:
	TYA
	AND #$0001
	BEQ @CARDINAL_TURN
	LDA #4
	STA BICYCLE_DIAGONAL_TURN_COUNTER
	BRA @CALCULATE_POSITION
@CARDINAL_TURN:
	LDA BICYCLE_DIAGONAL_TURN_COUNTER
	BEQ @CALCULATE_POSITION
	LDX BICYCLE_DIAGONAL_TURN_COUNTER
	DEX
	STX BICYCLE_DIAGONAL_TURN_COUNTER
	BEQ @DELAY_EXPIRED
	LDY GAME_STATE+game_state::leader_direction
	STY @LOCAL06
	BRA @CALCULATE_POSITION
@DELAY_EXPIRED:
	LDA @VIRTUAL02
	CMP #.LOWORD(-1)
	BNE @CALCULATE_POSITION
	LDY GAME_STATE+game_state::leader_direction
	STY @LOCAL06
@CALCULATE_POSITION:
	STY GAME_STATE+game_state::leader_direction
	LDA #.LOWORD(GAME_STATE) + game_state::leader_x_frac
	STA @LOCAL05
	TYA
	ASL
	ASL
	STA @LOCAL04
	CLC
	ADC #.LOWORD(HORIZONTAL_MOVEMENT_SPEEDS) + .SIZEOF(movement_speeds) * 3
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL0A
	LDY @LOCAL05
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDA #.LOWORD(GAME_STATE) + game_state::leader_y_frac
	STA @LOCAL07
	LDA @LOCAL04
	CLC
	ADC #.LOWORD(VERTICAL_MOVEMENT_SPEEDS) + .SIZEOF(movement_speeds) * 3
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL0A
	LDY @LOCAL07
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, @LOCAL02
	LDA #.LOWORD(-1)
	STA LADDER_STAIRS_TILE_X
	TDC
	CLC
	ADC #18
	STA @VIRTUAL04
	TDC
	CLC
	ADC #22
	STA @VIRTUAL02
	LDY @LOCAL06
	STY @LOCAL00
	LDY #24
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	TAX
	STX @LOCAL03
	LDX @VIRTUAL04
	LDA __BSS_START__,X
	LDX @LOCAL03
	JSL CHECK_ENTITY_COLLISION
	STA @LOCAL04
	LDY GAME_STATE+game_state::current_party_members
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	TAX
	STX @LOCAL06
	LDX @VIRTUAL04
	LDA __BSS_START__,X
	LDX @LOCAL06
	JSL NPC_COLLISION_CHECK
	LDA ENTITY_COLLIDED_OBJECTS + 23 * 2
	CMP #ENTITY_COLLISION_NO_OBJECT
	BNE @RETURN
	LDX #.LOWORD(GAME_STATE) + game_state::leader_moved
	LDA __BSS_START__,X
	INC
	STA __BSS_START__,X
	INC PLAYER_HAS_MOVED_SINCE_MAP_LOAD
	LDA @LOCAL04
	AND #$00C0
	BEQ @WRITE_POSITION
	LDA #0
	STA __BSS_START__,X
	BRA @RETURN
@WRITE_POSITION:
	MOVE_INT @LOCAL01, @VIRTUAL06
	LDY @LOCAL05
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	MOVE_INT @LOCAL02, @VIRTUAL06
	LDY @LOCAL07
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
@RETURN:
	END_C_FUNCTION
