
UPDATE_OVERWORLD_PLAYER_INPUT:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	STZ GAME_STATE + game_state::leader_moved
	LDA MUSHROOMIZED_WALKING_FLAG
	BEQ @NOT_MUSHROOMIZED
	JSR MUSHROOMIZATION_MOVEMENT_SWAP
@NOT_MUSHROOMIZED:
	LDX #.LOWORD(GAME_STATE) + game_state::walking_style
	STX @LOCAL07
	LDA __BSS_START__,X
	JSL MAP_INPUT_TO_DIRECTION
	STA @VIRTUAL02
	LDA BATTLE_SWIRL_COUNTDOWN
	BEQ @NO_BATTLE_SWIRL
	LDX BATTLE_SWIRL_COUNTDOWN
	DEX
	STX BATTLE_SWIRL_COUNTDOWN
	BEQ @START_BATTLE
	LDY GAME_STATE+game_state::current_party_members
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL NPC_COLLISION_CHECK
	JMP @RETURN
@START_BATTLE:
	LDA #.LOWORD(-1)
	STA BATTLE_MODE
	JMP @RETURN
@NO_BATTLE_SWIRL:
	LDA @VIRTUAL02
	CMP #.LOWORD(-1)
	BNE @HAS_DIRECTION_INPUT
	LDY GAME_STATE+game_state::current_party_members
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL NPC_COLLISION_CHECK
	JMP @RETURN
@HAS_DIRECTION_INPUT:
	LDX @LOCAL07
	LDA __BSS_START__,X
	CMP #13
	BNE @NOT_ESCALATOR
	LDA STAIRS_DIRECTION
	CMP #$0100
	BEQ @STAIRS_UP_OR_RIGHT
	LDA STAIRS_DIRECTION
	CMP #$0200
	BNE @STAIRS_DOWN_OR_LEFT
@STAIRS_UP_OR_RIGHT:
	LDA @VIRTUAL02
	CMP #3
	BGT @STAIRS_FORCE_DOWN_LEFT
	LDA #1
	STA @VIRTUAL02
	BRA @SET_ESCALATOR_FACING
@STAIRS_FORCE_DOWN_LEFT:
	LDA #5
	STA @VIRTUAL02
	BRA @SET_ESCALATOR_FACING
@STAIRS_DOWN_OR_LEFT:
	LDA @VIRTUAL02
	DEC
	AND #$0007
	CMP #3
	BGT @STAIRS_FORCE_UP_LEFT
	LDA #3
	STA @VIRTUAL02
	BRA @SET_ESCALATOR_FACING
@STAIRS_FORCE_UP_LEFT:
	LDA #7
	STA @VIRTUAL02
@SET_ESCALATOR_FACING:
	LDA @VIRTUAL02
	CMP #4
	BCS @FACE_LEFT
	LDA #2
	STA GAME_STATE+game_state::leader_direction
	BRA @UPDATE_MOVEMENT_STATE
@FACE_LEFT:
	LDA #6
	STA GAME_STATE+game_state::leader_direction
	BRA @UPDATE_MOVEMENT_STATE
@NOT_ESCALATOR:
	LDA PLAYER_MOVEMENT_FLAGS
	AND #$0001
	BNE @UPDATE_MOVEMENT_STATE
	LDA @VIRTUAL02
	STA GAME_STATE+game_state::leader_direction
@UPDATE_MOVEMENT_STATE:
	INC PLAYER_HAS_MOVED_SINCE_MAP_LOAD
	LDX #.LOWORD(GAME_STATE) + game_state::leader_moved
	LDA __BSS_START__,X
	INC
	STA __BSS_START__,X
	LDA GAME_STATE+game_state::trodden_tile_type
	STA @LOCAL06
	LDA #.LOWORD(GAME_STATE) + game_state::leader_x_frac
	STA @LOCAL05
	LDY @LOCAL05
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL04
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDA #.LOWORD(GAME_STATE) + game_state::leader_y_frac
	STA @LOCAL03
	LDY @LOCAL03
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	MOVE_INT @LOCAL04, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX @LOCAL06
	LDA @VIRTUAL02
	JSR ADJUST_POSITION_HORIZONTAL
	MOVE_INT @VIRTUAL06, @LOCAL01
	MOVE_INT @LOCAL02, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX @LOCAL06
	LDA @VIRTUAL02
	JSR ADJUST_POSITION_VERTICAL
	MOVE_INT @VIRTUAL06, @LOCAL02
	LDA #.LOWORD(-1)
	STA LADDER_STAIRS_TILE_X
	LDA PLAYER_MOVEMENT_FLAGS
	AND #$0002
	BNE @MOVEMENT_LOCKED
	LDA @VIRTUAL02
	STA @LOCAL00
	LDY GAME_STATE+game_state::current_party_members
	LDX @LOCAL02 + fixed_point::integer
	LDA @LOCAL01 + fixed_point::integer
	JSL CHECK_DIRECTIONAL_COLLISION
	STA @VIRTUAL04
	LDA @VIRTUAL02
	CMP FINAL_MOVEMENT_DIRECTION
	BEQ @STORE_TILE_TYPE
	LDY @LOCAL05
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX @LOCAL06
	LDA FINAL_MOVEMENT_DIRECTION
	JSR ADJUST_POSITION_HORIZONTAL
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDY @LOCAL03
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX @LOCAL06
	LDA FINAL_MOVEMENT_DIRECTION
	JSR ADJUST_POSITION_VERTICAL
	MOVE_INT @VIRTUAL06, @LOCAL02
	BRA @STORE_TILE_TYPE
@MOVEMENT_LOCKED:
	LDA DEMO_FRAMES_LEFT
	BNE @DEMO_NO_COLLISION
	LDY GAME_STATE+game_state::current_party_members
	LDX @LOCAL02 + fixed_point::integer
	LDA @LOCAL01 + fixed_point::integer
	JSR GET_COLLISION_AT_PIXEL
	AND #$003F
	STA @VIRTUAL04
	BRA @STORE_TILE_TYPE
@DEMO_NO_COLLISION:
	LDA #0
	STA @VIRTUAL04
@STORE_TILE_TYPE:
	LDA @VIRTUAL04
	STA GAME_STATE+game_state::trodden_tile_type
	LDA #1
	STA @VIRTUAL02
	LDY GAME_STATE+game_state::current_party_members
	LDX @LOCAL02 + fixed_point::integer
	LDA @LOCAL01 + fixed_point::integer
	JSL NPC_COLLISION_CHECK
	LDA ENTITY_COLLIDED_OBJECTS+46
	CMP #ENTITY_COLLISION_NO_OBJECT
	BEQ @NO_NPC_COLLISION
	LDA #0
	STA @VIRTUAL02
@NO_NPC_COLLISION:
	LDA @VIRTUAL04
	AND #$00C0
	BEQ @NO_TILE_COLLISION
	LDA #0
	STA @VIRTUAL02
@NO_TILE_COLLISION:
	LDA LADDER_STAIRS_TILE_X
	CMP #.LOWORD(-1)
	BEQ @NO_LADDER_TILE
	LDX LADDER_STAIRS_TILE_Y
	LDA LADDER_STAIRS_TILE_X
	JSL PROCESS_DOOR_AT_TILE
	STA @VIRTUAL02
	BRA @CHECK_CAN_MOVE
@NO_LADDER_TILE:
	LDX GAME_STATE+game_state::walking_style
	CPX #WALKING_STYLE::LADDER
	BEQ @CLEAR_LADDER_STYLE
	CPX #WALKING_STYLE::ROPE
	BNE @CHECK_CAN_MOVE
@CLEAR_LADDER_STYLE:
	STZ GAME_STATE+game_state::walking_style
@CHECK_CAN_MOVE:
	LDA @VIRTUAL02
	BEQ @MOVEMENT_BLOCKED
	MOVE_INT @LOCAL01, @VIRTUAL06
	LDA @VIRTUAL06
	STA GAME_STATE + game_state::leader_x_frac
	LDA @VIRTUAL06 + fixed_point::integer
	STA GAME_STATE+game_state::leader_x_coord
	MOVE_INT @LOCAL02, @VIRTUAL06
	LDA @VIRTUAL06
	STA GAME_STATE + game_state::leader_y_frac
	LDA @VIRTUAL06 + fixed_point::integer
	STA GAME_STATE+game_state::leader_y_coord
	BRA @CHECK_HOTSPOT_0
@MOVEMENT_BLOCKED:
	STZ GAME_STATE + game_state::leader_moved
@CHECK_HOTSPOT_0:
	LDA FRAME_COUNTER
	AND #$00FF
	AND #$0001
	BNE @CHECK_HOTSPOT_1
	LDA ACTIVE_HOTSPOTS
	BEQ @CHECK_HOTSPOT_1
	LDA #0
	JSL CHECK_HOTSPOT_EXIT
@CHECK_HOTSPOT_1:
	LDA FRAME_COUNTER
	AND #$00FF
	AND #$0001
	BEQ @CHECK_LADDER_ALIGNMENT
	LDA ACTIVE_HOTSPOTS + .SIZEOF(active_hotspot)
	BEQ @CHECK_LADDER_ALIGNMENT
	LDA #1
	JSL CHECK_HOTSPOT_EXIT
@CHECK_LADDER_ALIGNMENT:
	LDX GAME_STATE+game_state::walking_style
	CPX #WALKING_STYLE::LADDER
	BEQ @ALIGN_TO_LADDER
	CPX #WALKING_STYLE::ROPE
	BNE @CHECK_DEBUG_SNAP
@ALIGN_TO_LADDER:
	LDA LADDER_STAIRS_TILE_X
	OPTIMIZED_MULT @VIRTUAL04, 8
	CLC
	ADC #8
	STA GAME_STATE+game_state::leader_x_coord
@CHECK_DEBUG_SNAP:
	LDA DEBUG
	BEQ @RETURN
	LDA PAD_STATE
	AND #PAD::X_BUTTON
	BEQ @RETURN
	LDX #.LOWORD(GAME_STATE) + game_state::leader_x_coord
	LDA __BSS_START__,X
	AND #$FFF8
	STA __BSS_START__,X
	LDX #.LOWORD(GAME_STATE) + game_state::leader_y_coord
	LDA __BSS_START__,X
	AND #$FFF8
	STA __BSS_START__,X
@RETURN:
	END_C_FUNCTION
