
UPDATE_JOYPAD_STATE:
	SEP #PROC_FLAGS::ACCUM8
@WAIT_UNTIL_READY:
	LDA HVBJOY
	LSR
	BCS @WAIT_UNTIL_READY
	JSR READ_JOYPAD
	JSR RECORD_DEMO_INPUT
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	LDX #$0002
@PROCESS_PAD:
	LDA <PAD_RAW,X
	AND #$FFF0
	STA <PAD_TEMP
	LDA <PAD_STATE,X
	EOR #$FFFF
	AND <PAD_TEMP + 0
	STA <PAD_PRESS,X
	LDA <PAD_TEMP + 0
	CMP <PAD_STATE,X
	STA <PAD_STATE,X
	BEQ @SAME_STATE
	LDA <PAD_PRESS,X
	STA <PAD_HELD,X
	LDA #$0014
	STA <PAD_TIMER,X
	BRA @NEXT_PAD
@SAME_STATE:
	LDY <PAD_TIMER,X
	BEQ @TIMER_EXPIRED
	DEC <PAD_TIMER,X
	STZ <PAD_HELD,X
	BRA @NEXT_PAD
@TIMER_EXPIRED:
	STA <PAD_HELD,X
	LDA #$0003
	STA <PAD_TIMER,X
@NEXT_PAD:
	DEX
	DEX
	BPL @PROCESS_PAD
	LDA f:DEBUG
	BNE @CHECK_ACTIVITY
	LDA <PAD_STATE + 2
	ORA <PAD_STATE + 0
	STA <PAD_STATE
	LDA <PAD_HELD + 2
	ORA <PAD_HELD + 0
	STA <PAD_HELD
	LDA <PAD_PRESS + 2
	ORA <PAD_PRESS + 0
	STA <PAD_PRESS
@CHECK_ACTIVITY:
	LDA <PAD_PRESS + 0
	BEQ @DONE
	INC PLAYER_HAS_DONE_SOMETHING_THIS_FRAME
@DONE:
	RTS
