
OVERWORLD_USE_ITEM:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_PARAM_INT16 ;int unused
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	STX @LOCAL0A
	STA @VIRTUAL04
	STA @LOCAL09
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL08
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL07
	LDX @LOCAL0A
	LDA @VIRTUAL04
	JSL GET_CHARACTER_ITEM
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL01
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL01
	AND #$00FF
	STA @LOCAL06
	LOADPTR ITEM_CONFIGURATION_TABLE, @VIRTUAL06
	LDA @LOCAL06
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL05
	LDA @VIRTUAL06+2
	STA @LOCAL05+2
	LDY #item::type
	LDA [@LOCAL05],Y
	AND #$00FF
	TAX
	STX @LOCAL04
	TXA
	AND #ITEM_FLAGS::TRANSFORM | ITEM_FLAGS::CANNOT_GIVE
	BEQ @TYPE_USABLE
	CMP #ITEM_FLAGS::TRANSFORM
	BEQ @TYPE_EQUIPMENT
	CMP #ITEM_FLAGS::CANNOT_GIVE
	BEQ @TYPE_CANNOT_GIVE
	CMP #ITEM_FLAGS::TRANSFORM | ITEM_FLAGS::CANNOT_GIVE
	BEQL @TYPE_KEY_ITEM
	JMP @AFTER_ITEM_TYPE_CHECK
@TYPE_USABLE:
	LDA #1
	STA @VIRTUAL02
	STA @LOCAL07
	LOADPTR BATTLE_ACTION_TABLE, @VIRTUAL0A
	LDY #item::effect
	LDA [@LOCAL05],Y
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(battle_action)
	OPTIMIZED_ADD battle_action::description_text_pointer
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL08
	JMP @AFTER_ITEM_TYPE_CHECK
@TYPE_EQUIPMENT:
	LOADPTR MSG_SYS_GOODS_EQUIP, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL08
	JMP @AFTER_ITEM_TYPE_CHECK
@TYPE_CANNOT_GIVE:
	LDA #1
	STA @VIRTUAL02
	STA @LOCAL07
	LOADPTR BATTLE_ACTION_TABLE, @VIRTUAL0A
	LDY #item::effect
	LDA [@LOCAL05],Y
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(battle_action)
	OPTIMIZED_ADD battle_action::description_text_pointer
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL08
	JMP @AFTER_ITEM_TYPE_CHECK
@TYPE_KEY_ITEM:
	LDY #item::flags
.IF .DEFINED(JPN)
	LDA @LOCAL09
	STA @VIRTUAL04
.ENDIF
	LDX @VIRTUAL04
	DEX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_USABLE_FLAGS,X
	AND [@LOCAL05],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNE @CHAR_CAN_USE_ITEM
	LOADPTR MSG_SYS_GOODS_USE_NG_USER, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL08
	JMP @AFTER_ITEM_TYPE_CHECK
@CHAR_CAN_USE_ITEM:
	LDX @LOCAL04
	TXA
	AND #$000C
	BEQ @USE_ANYWHERE
	CMP #4
	BEQ @BATTLE_ONLY
	CMP #8
	BEQ @CHECK_USE_CONTEXT
	JMP @AFTER_ITEM_TYPE_CHECK
@USE_ANYWHERE:
	LDA #1
	STA @VIRTUAL02
	STA @LOCAL07
	LOADPTR BATTLE_ACTION_TABLE, @VIRTUAL0A
	LDY #item::effect
	LDA [@LOCAL05],Y
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(battle_action)
	OPTIMIZED_ADD battle_action::description_text_pointer
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL08
	JMP @AFTER_ITEM_TYPE_CHECK
@BATTLE_ONLY:
	LOADPTR MSG_SYS_GOODS_USE_NG_HERE, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL08
	JMP @AFTER_ITEM_TYPE_CHECK
@CHECK_USE_CONTEXT:
	TXA
	AND #$0003
	BEQ @USE_DEFAULT
	CMP #1
	BEQ @USE_DEFAULT
	CMP #2
	BEQ @CHECK_SECTOR_TYPE
	CMP #3
	BEQL @CHECK_NPC_TARGET
	JMP @AFTER_ITEM_TYPE_CHECK
@USE_DEFAULT:
	LDA #1
	STA @VIRTUAL02
	STA @LOCAL07
	LOADPTR BATTLE_ACTION_TABLE, @VIRTUAL0A
	LDY #item::effect
	LDA [@LOCAL05],Y
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(battle_action)
	OPTIMIZED_ADD battle_action::description_text_pointer
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL08
	JMP @AFTER_ITEM_TYPE_CHECK
@CHECK_SECTOR_TYPE:
	JSR GET_SECTOR_ITEM_TYPE
	TAX
	LDA @LOCAL06
	STA @VIRTUAL02
	TXA
	CMP @VIRTUAL02
	BNE @SECTOR_MISMATCH
	LDA @LOCAL06
	CMP #ITEM::BICYCLE
	BNE @SECTOR_MATCH
	JSL GET_COLLISION_AT_LEADER
	CMP #0
	BEQ @SECTOR_MATCH
	LOADPTR MSG_SYS_BICYCLE_ATARI_HERE, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL08
	JMP @AFTER_ITEM_TYPE_CHECK
@SECTOR_MATCH:
	LDA #1
	STA @VIRTUAL02
	STA @LOCAL07
	LOADPTR BATTLE_ACTION_TABLE, @VIRTUAL0A
	LDY #item::effect
	LDA [@LOCAL05],Y
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(battle_action)
	OPTIMIZED_ADD battle_action::description_text_pointer
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL08
	JMP @AFTER_ITEM_TYPE_CHECK
@SECTOR_MISMATCH:
	LOADPTR MSG_SYS_GOODS_USE_NG_HERE, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL08
	JMP @AFTER_ITEM_TYPE_CHECK
@CHECK_NPC_TARGET:
	LDA #1
	STA @VIRTUAL02
	STA @LOCAL07
	JSR GET_NEARBY_NPC_CONFIG_TYPE
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	CMP #1
	BEQ @NPC_HAS_USE_TEXT
	CMP #3
	BNE @AFTER_NPC_TEXT
@NPC_HAS_USE_TEXT:
	LOADPTR NPC_CONFIG_TABLE, @VIRTUAL0A
	LDA INTERACTING_NPC_ID
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(npc_config)
	CLC
	ADC #npc_config::text_pointer2
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL08
@AFTER_NPC_TEXT:
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	MOVE_INT @LOCAL08, @VIRTUAL06
	CMP @VIRTUAL0A+2
	BNE @CHECK_NULL_LOW
	LDA @VIRTUAL06
	CMP @VIRTUAL0A
@CHECK_NULL_LOW:
	BNE @AFTER_ITEM_TYPE_CHECK
	LOADPTR BATTLE_ACTION_TABLE, @VIRTUAL0A
	LDY #item::effect
	LDA [@LOCAL05],Y
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(battle_action)
	OPTIMIZED_ADD battle_action::description_text_pointer
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL08
@AFTER_ITEM_TYPE_CHECK:
	LDA @LOCAL09
	STA @VIRTUAL04
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	STA @VIRTUAL02
	BEQ @SETUP_ACTION_WINDOW
	LDX @VIRTUAL04
	LDY #item::effect
	LDA [@LOCAL05],Y
	JSR DETERMINE_TARGETTING
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	AND #$00FF
	BNE @CHECK_CONSUME_ITEM
	LDA #0
	JMP @RETURN
@CHECK_CONSUME_ITEM:
	LDY #item::flags
	LDA [@LOCAL05],Y
	AND #$00FF
	AND #ITEM_FLAGS::CONSUMED_ON_USE
	BEQ @SETUP_ACTION_WINDOW
	LDX @LOCAL0A
	LDA @VIRTUAL04
	JSR REMOVE_ITEM_FROM_INVENTORY
@SETUP_ACTION_WINDOW:
	LDA #WINDOW::INVENTORY_MENU
	JSR CLOSE_WINDOW
	LDA #WINDOW::INVENTORY
	JSR CLOSE_WINDOW
	LDX #.SIZEOF(char_struct::name)
	LDA @VIRTUAL04
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	JSR SET_BATTLE_ATTACKER_NAME
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL01
	JSR SET_CURRENT_ITEM
	.A16
	CREATE_WINDOW_NEAR #WINDOW::TEXT_STANDARD
.IF .DEFINED(JPN)
	MOVE_INT1632 @VIRTUAL04, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @LOCAL00
.ELSE
	MOVE_INT1632 @VIRTUAL04, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
.ENDIF
	JSR SET_WORKING_MEMORY
.IF .DEFINED(JPN)
	MOVE_INT1632 @LOCAL0A, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @LOCAL00
.ELSE
	MOVE_INT1632 @LOCAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
.ENDIF
	JSR SET_ARGUMENT_MEMORY
	LDA @VIRTUAL00
	AND #$00FF
	TAY
	CPY #>-1
	BEQ @AFTER_TARGET_NAME
	LDX #.SIZEOF(char_struct::name)
	TYA
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	.A16
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	JSR SET_BATTLE_TARGET_NAME
@AFTER_TARGET_NAME:
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	MOVE_INT @LOCAL08, @VIRTUAL06
	CMP @VIRTUAL0A+2
	BNE @CHECK_DESC_NULL_LOW
	LDA @VIRTUAL06
	CMP @VIRTUAL0A
@CHECK_DESC_NULL_LOW:
	BNE @AFTER_DESC_CHECK
	LOADPTR MSG_SYS_GOODS_USE_NG, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL08
@AFTER_DESC_CHECK:
	LDA @VIRTUAL02
	BEQL @DISPLAY_TEXT_ONLY
	LOADPTR BATTLE_ACTION_TABLE, @LOCAL03
	MOVE_INT @LOCAL05, @VIRTUAL0A
	LDA #item::effect
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	STA @LOCAL02
	LDA @VIRTUAL0A+2
	STA @LOCAL02+2
	MOVE_INT @LOCAL03, @VIRTUAL06
	LDA [@VIRTUAL0A]
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(battle_action)
	CLC
	ADC #battle_action::battle_function_pointer
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL06
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BEQL @DISPLAY_TEXT_ONLY
	LDA #.LOWORD(BATTLERS_TABLE)
	STA CURRENT_ATTACKER
	TAX
	LDA @LOCAL09
	STA @VIRTUAL04
	JSL BATTLE_INIT_PLAYER_STATS
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL01
	LDX CURRENT_ATTACKER
	STA __BSS_START__ + battler::current_action_argument,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL0A
	SEP #PROC_FLAGS::ACCUM8
	LDX CURRENT_ATTACKER
	STA __BSS_START__ + battler::action_item_slot,X
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @LOCAL08, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL01
	JSR SET_CURRENT_ITEM
	.A16
	LDX #.LOWORD(BATTLERS_TABLE) + .SIZEOF(battler)
	STX CURRENT_TARGET
	LDA @VIRTUAL00
	AND #$00FF
	TAY
	CPY #>-1
	BNEL @SPECIFIC_TARGET
	LDY #0
	STY @LOCAL06
	JMP @ALL_TARGETS_CHECK
@ALL_TARGETS_LOOP:
	TYA
	CLC
.IF .DEFINED(JPN)
	ADC #.LOWORD(GAME_STATE)
	CLC
	ADC #game_state::party_members
.ELSE
	ADC #.LOWORD(GAME_STATE) + game_state::party_members
.ENDIF
	STA @VIRTUAL02
	LDX #.SIZEOF(char_struct::name)
	STX @LOCAL01
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	AND #$00FF
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	.A16
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	LDX @LOCAL01
	JSR SET_BATTLE_TARGET_NAME
	LDX CURRENT_TARGET
	STX @LOCAL01
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	AND #$00FF
	LDX @LOCAL01
	JSL BATTLE_INIT_PLAYER_STATS
	LOADPTR BATTLE_ACTION_TABLE, @VIRTUAL0A
	LDY #item::effect
	LDA [@LOCAL05],Y
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(battle_action)
	CLC
	ADC #8
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	PHA
	MOVE_INT @VIRTUAL06, TEMP_FUNCTION_POINTER
	PLA
	JSL JUMP_TEMP_FUNCTION_POINTER
	LDA #0
	STA @LOCAL0A
	BRA @COPY_AFFLICTIONS_ALL_CHECK
@COPY_AFFLICTIONS_ALL:
	LDA @LOCAL0A
	STA @VIRTUAL02
	LDY @LOCAL06
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::afflictions
	CLC
	ADC @VIRTUAL02
	PHA
	LDA @LOCAL0A
	CLC
	ADC CURRENT_TARGET
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__ + battler::afflictions,X
	PLX
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL0A
	INC
	STA @LOCAL0A
@COPY_AFFLICTIONS_ALL_CHECK:
	STA @VIRTUAL02
	LDA #7
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @COPY_AFFLICTIONS_ALL
	LDY @LOCAL06
	INY
	STY @LOCAL06
@ALL_TARGETS_CHECK:
	STY @VIRTUAL02
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	CLC
	SBC @VIRTUAL02
	JUMPGTS @ALL_TARGETS_LOOP
	JMP @AFTER_ACTION
@SPECIFIC_TARGET:
	TYA
	JSL BATTLE_INIT_PLAYER_STATS
	MOVE_INT @LOCAL02, @VIRTUAL0A
	LDA [@VIRTUAL0A]
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(battle_action)
	CLC
	ADC #battle_action::battle_function_pointer
	PHA
	MOVE_INT @LOCAL03, @VIRTUAL0A
	PLA
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	PHA
	MOVE_INT @VIRTUAL06, TEMP_FUNCTION_POINTER
	PLA
	JSL JUMP_TEMP_FUNCTION_POINTER
	LDA #0
	STA @LOCAL0A
	BRA @COPY_AFFLICTIONS_ONE_CHECK
@COPY_AFFLICTIONS_ONE:
	LDA @LOCAL0A
	STA @VIRTUAL02
	LDA @VIRTUAL00
	AND #$00FF
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::afflictions
	CLC
	ADC @VIRTUAL02
	PHA
	LDA @LOCAL0A
	CLC
	ADC CURRENT_TARGET
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__+battler::afflictions,X
	PLX
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL0A
	INC
	STA @LOCAL0A
@COPY_AFFLICTIONS_ONE_CHECK:
	STA @VIRTUAL02
	LDA #7
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @COPY_AFFLICTIONS_ONE
@AFTER_ACTION:
	JSL RENDER_AND_DISABLE_ENTITIES
	BRA @CLOSE_TEXT_WINDOW
@DISPLAY_TEXT_ONLY:
	MOVE_INT @LOCAL08, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
@CLOSE_TEXT_WINDOW:
	LDA #WINDOW::TEXT_STANDARD
	JSR CLOSE_WINDOW
	LDA #TRUE
@RETURN:
	END_C_FUNCTION
