
USE_SOUND_STONE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int
	END_STACK_VARS
	STA @LOCAL11
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	JSL STOP_MUSIC
	JSL LOAD_ENEMY_BATTLE_SPRITES
	LOADPTR BUFFER, @VIRTUAL06
	LOADPTR SOUND_STONE_GFX, @LOCAL00
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSL DECOMP
	COPY_TO_VRAM1P @VIRTUAL06, VRAM::SOUND_STONE_GFX, $2C00, 0
	.A16
	LOADPTR SOUND_STONE_PALETTE, @LOCAL00
	LDX #BPP4PALETTE_SIZE * 6
	LDA #.LOWORD(PALETTES) + BPP4PALETTE_SIZE * 8
	JSL MEMCPY16
	JSL LOAD_CHARACTER_WINDOW_PALETTE
	LDY #4
	LDX #BATTLEBG_LAYER::SOUNDSTONE2
	LDA #BATTLEBG_LAYER::SOUNDSTONE1
	JSL LOAD_BATTLE_BG
	SEP #PROC_FLAGS::ACCUM8
	STZ_BADOPT @LOCAL00
	LDX #5
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(SOUND_STONE_SPRITEMAP_1)
	JSL MEMSET16
	SEP #PROC_FLAGS::ACCUM8
	STZ_BADOPT @LOCAL00
	LDX #5
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(SOUND_STONE_SPRITEMAP_2)
	JSL MEMSET16
	SEP #PROC_FLAGS::ACCUM8
	LDA #240
	STA SOUND_STONE_SPRITEMAP_1 + spritemap::x_offset
	STA SOUND_STONE_SPRITEMAP_1 + spritemap::y_offset
	LDA #248
	STA SOUND_STONE_SPRITEMAP_2 + spritemap::x_offset
	STA SOUND_STONE_SPRITEMAP_2 + spritemap::y_offset
	LDA #$81
	STA SOUND_STONE_SPRITEMAP_1 + spritemap::special_flags
	LDA #$80
	STA SOUND_STONE_SPRITEMAP_2 + spritemap::special_flags
	REP #PROC_FLAGS::ACCUM8
	STZ @LOCAL10
	LDY #0
	STY @LOCAL0F
	BRA @MELODY_INIT_LOOP_CHECK
@INIT_MELODY:
	TYX
	LDA f:SOUND_STONE_MELODY_FLAGS,X
	AND #$00FF
	JSL GET_EVENT_FLAG
	CMP #0
	BEQ @MELODY_NOT_COLLECTED
	LDY @LOCAL0F
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(sound_stone_playback_state)
	TAX
	LDA #1
	STA SOUND_STONE_PLAYBACK_STATE + sound_stone_playback_state::state,X
	INC @LOCAL10
	BRA @INIT_PLAYBACK_STATE
@MELODY_NOT_COLLECTED:
	LDY @LOCAL0F
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(sound_stone_playback_state)
	TAX
	STZ SOUND_STONE_PLAYBACK_STATE + sound_stone_playback_state::state,X
@INIT_PLAYBACK_STATE:
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(sound_stone_playback_state)
	TAX
	LDA #1
	STA SOUND_STONE_PLAYBACK_STATE + sound_stone_playback_state::unknown2,X
	STZ SOUND_STONE_PLAYBACK_STATE + sound_stone_playback_state::orbit_sprite_frame,X
	INY
	STY @LOCAL0F
@MELODY_INIT_LOOP_CHECK:
	CPY #8
	BCC @INIT_MELODY
	JSL BLANK_SCREEN_AND_WAIT_VBLANK
	LDX #1
	TXA
	JSL FADE_IN
	LDA #15
	STA @LOCAL0E
	STZ @LOCAL0F
	LDA #60
	STA @LOCAL0D
	STZ @LOCAL0C
	STZ @LOCAL0B
	LDA #0
	STA @VIRTUAL04
	STA @LOCAL0A
	STA @VIRTUAL02
	STA @LOCAL09
@MAIN_LOOP:
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA PAD_PRESS
	STA @LOCAL08
	LDA @LOCAL0A
	STA @VIRTUAL04
	BNE @CHECK_COUNTDOWN
	DEC @LOCAL0D
	LDA @LOCAL0D
	BNE @CHECK_COUNTDOWN
	LDA #.LOWORD(-1)
	STA @VIRTUAL02
	STA @LOCAL09
	LDA @VIRTUAL02
	STA @LOCAL0B
	LDA #1
	STA @VIRTUAL04
	STA @LOCAL0A
@CHECK_COUNTDOWN:
	LDA @LOCAL0C
	BEQ @CHECK_SEQUENCE
	DEC @LOCAL0C
	LDA @LOCAL0C
	BEQL @EXIT_FADE_OUT
	JMP @RENDER_SPRITES
@CHECK_SEQUENCE:
	LDA @VIRTUAL04
	BEQL @RENDER_SPRITES
	LDA @VIRTUAL04
	DEC
	STA @VIRTUAL04
	STA @LOCAL0A
	LDA @VIRTUAL04
	BNEL @UPDATE_TIMING
	LDA @LOCAL09
	STA @VIRTUAL02
	CMP #8
	BCS @CHECK_WRAP
	LDA @VIRTUAL02
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(sound_stone_playback_state)
	CLC
	ADC #.LOWORD(SOUND_STONE_PLAYBACK_STATE)
	TAX
	LDA a:sound_stone_playback_state::state,X
	CMP #2
	BNE @CHECK_WRAP
	LDA #1
	STA a:sound_stone_playback_state::state,X
@CHECK_WRAP:
	LDA @VIRTUAL02
	CMP #8
	BNE @ADVANCE_MELODY
	LDA @LOCAL0B
	INC
	STA @LOCAL07
	BRA @FIND_NEXT_CHECK
@FIND_NEXT_MELODY:
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(sound_stone_playback_state)
	TAX
	LDA SOUND_STONE_PLAYBACK_STATE + sound_stone_playback_state::state,X
	BNE @CHECK_ALL_SKIPPED
	LDA @LOCAL07
	INC
	STA @LOCAL07
@FIND_NEXT_CHECK:
	CMP #8
	BCC @FIND_NEXT_MELODY
@CHECK_ALL_SKIPPED:
	LDA @LOCAL07
	CMP #8
	BNE @ADVANCE_MELODY
	LDA #150
	STA @LOCAL0C
@ADVANCE_MELODY:
	INC @LOCAL0B
	LDA @LOCAL0B
	CMP #8
	BCS @ALL_MELODIES_DONE
	LDA @LOCAL0B
	STA @VIRTUAL02
	STA @LOCAL09
	LDA @VIRTUAL02
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(sound_stone_playback_state)
	CLC
	ADC #.LOWORD(SOUND_STONE_PLAYBACK_STATE) + sound_stone_playback_state::state
	TAX
	LDA __BSS_START__,X
	BEQ @MELODY_NOT_ACTIVE
	LDA #2
	STA __BSS_START__,X
	BRA @PLAY_MELODY
@MELODY_NOT_ACTIVE:
	LDA #8
	STA @VIRTUAL02
	STA @LOCAL09
@PLAY_MELODY:
	LDA @VIRTUAL02
	ASL
	TAX
	LDA f:SOUND_STONE_UNKNOWN7,X
	STA @VIRTUAL04
	STA @LOCAL0A
	LDX @VIRTUAL02
	LDA f:SOUND_STONE_MUSIC,X
	AND #$00FF
	JSL CHANGE_MUSIC
	BRA @UPDATE_TIMING
@ALL_MELODIES_DONE:
	LDA #150
	STA @LOCAL0C
@UPDATE_TIMING:
	LDA @LOCAL09
	STA @VIRTUAL02
	CMP #8
	BCS @RENDER_SPRITES
	LDA @VIRTUAL02
	ASL
	TAX
	LDA f:SOUND_STONE_UNKNOWN7,X
	SEC
	SBC #9
	STA @VIRTUAL02
	LDA @LOCAL0A
	STA @VIRTUAL04
	CMP @VIRTUAL02
	BNE @RENDER_SPRITES
	LDA @LOCAL10
	CLC
	ADC #8
	JSL WRITE_APU_PORT1
@RENDER_SPRITES:
	JSL OAM_CLEAR
	LDA #^SOUND_STONE_SPRITEMAP_1
	JSL SWAP_SPRITEMAP_BANK
	STZ @LOCAL06
	JMP @SPRITE_LOOP_CHECK
@PROCESS_MELODY_SPRITE:
	LDA @LOCAL06
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(sound_stone_playback_state)
	STA @LOCAL05
	TAX
	LDA SOUND_STONE_PLAYBACK_STATE + sound_stone_playback_state::state,X
	CMP #1
	BEQ @DRAW_IDLE_SPRITE
	CMP #2
	BEQ @DRAW_ORBIT_SPRITE
	JMP @NEXT_MELODY_SPRITE
@DRAW_IDLE_SPRITE:
	LDX @LOCAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA f:SOUND_STONE_UNKNOWN3,X
	STA SOUND_STONE_SPRITEMAP_1 + spritemap::tile
	LDA #$30
	STA SOUND_STONE_SPRITEMAP_1 + spritemap::flags
	LDX @LOCAL06
	REP #PROC_FLAGS::ACCUM8
	LDA f:SOUND_STONE_UNKNOWN2,X
	AND #$00FF
	TAY
	LDX @LOCAL06
	LDA f:SOUND_STONE_UNKNOWN,X
	AND #$00FF
	TAX
	LDA #.LOWORD(SOUND_STONE_SPRITEMAP_1)
	JSL WRITE_SPRITEMAP_TO_OAM
	JMP @NEXT_MELODY_SPRITE
@DRAW_ORBIT_SPRITE:
	LDA @LOCAL05
	CLC
	ADC #.LOWORD(SOUND_STONE_PLAYBACK_STATE) + sound_stone_playback_state::orbit_sprite_position_2
	TAX
	LDA __BSS_START__,X
	CLC
	ADC #65540 / 20 ;65536/20, but rounded up
	STA __BSS_START__,X
	LDA @LOCAL05
	CLC
	ADC #.LOWORD(SOUND_STONE_PLAYBACK_STATE) + sound_stone_playback_state::unknown2
	TAX
	LDA __BSS_START__,X
	TAY
	DEY
	TYA
	STA __BSS_START__,X
	BNE @DRAW_ORBIT_PAIR
	LDA #2
	STA __BSS_START__,X
	LDA @LOCAL05
	CLC
	ADC #.LOWORD(SOUND_STONE_PLAYBACK_STATE) + sound_stone_playback_state::orbit_sprite_frame
	TAX
	STX @LOCAL07
	LDA @LOCAL05
	PHA
	LOADPTR SOUND_STONE_MELODY_PTR_TABLE, @VIRTUAL06
	LDA @LOCAL06
	ASL
	ASL
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL06
	LDA __BSS_START__,X
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	PLX
	STA SOUND_STONE_PLAYBACK_STATE + sound_stone_playback_state::orbit_sprite_position_1,X
	LDX @LOCAL07
	LDA __BSS_START__,X
	INC
	STA __BSS_START__,X
	LDA @LOCAL05
	CLC
	ADC #.LOWORD(SOUND_STONE_PLAYBACK_STATE) + sound_stone_playback_state::unknown4
	TAX
	LDA __BSS_START__,X
	STA @VIRTUAL02
	LDA #2
	SEC
	SBC @VIRTUAL02
	STA __BSS_START__,X
@DRAW_ORBIT_PAIR:
	LDA @LOCAL06
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(sound_stone_playback_state)
	STA @LOCAL07
	PHA
	LDX @LOCAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA f:SOUND_STONE_UNKNOWN5,X
	PLX
	CLC
	ADC SOUND_STONE_PLAYBACK_STATE + sound_stone_playback_state::unknown4,X
	STA SOUND_STONE_SPRITEMAP_2 + spritemap::tile
	LDX @LOCAL06
	LDA f:SOUND_STONE_UNKNOWN6,X
	ASL
	CLC
	ADC #$31
	STA SOUND_STONE_SPRITEMAP_2 + spritemap::flags
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL07
	CLC
	ADC #.LOWORD(SOUND_STONE_PLAYBACK_STATE) + sound_stone_playback_state::orbit_sprite_position_1
	STA @LOCAL04
	LDA (@LOCAL04)
	TAY
	BEQL @DRAW_MAIN_SPRITE
	LOADPTR SOUND_STONE_UNKNOWN, @VIRTUAL0A
	LDA @LOCAL06
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA @LOCAL07
	CLC
	ADC #.LOWORD(SOUND_STONE_PLAYBACK_STATE) + sound_stone_playback_state::orbit_sprite_position_2
	STA @LOCAL03
	LOADPTR SOUND_STONE_UNKNOWN2, @VIRTUAL06
	LDA @LOCAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA (@LOCAL03)
	XBA
	AND #$00FF
	TAX
	TYA
	JSL COSINE_SINE
	STA @LOCAL02
	LDA (@LOCAL03)
	XBA
	AND #$00FF
	TAX
	LDA (@LOCAL04)
	JSL COSINE
	STA @VIRTUAL02
	LDA [@VIRTUAL06]
	AND #$00FF
	CLC
	ADC @VIRTUAL02
	TAY
	LDA [@VIRTUAL0A]
	AND #$00FF
	CLC
	ADC @LOCAL02
	TAX
	LDA #.LOWORD(SOUND_STONE_SPRITEMAP_2) + spritemap::y_offset
	JSL WRITE_SPRITEMAP_TO_OAM
	LDA (@LOCAL03)
	XBA
	AND #$00FF
	CLC
	ADC #128
	AND #$00FF
	TAX
	LDA (@LOCAL04)
	JSL COSINE_SINE
	STA @LOCAL02
	LDA (@LOCAL03)
	XBA
	AND #$00FF
	CLC
	ADC #128
	AND #$00FF
	TAX
	LDA (@LOCAL04)
	JSL COSINE
	STA @VIRTUAL02
	LDA [@VIRTUAL06]
	AND #$00FF
	CLC
	ADC @VIRTUAL02
	TAY
	LDA [@VIRTUAL0A]
	AND #$00FF
	CLC
	ADC @LOCAL02
	TAX
	LDA #.LOWORD(SOUND_STONE_SPRITEMAP_2) + spritemap::y_offset
	JSL WRITE_SPRITEMAP_TO_OAM
@DRAW_MAIN_SPRITE:
	LDX @LOCAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA f:SOUND_STONE_UNKNOWN3,X
	CLC
	ADC #128
	STA SOUND_STONE_SPRITEMAP_1 + spritemap::tile
	LDX @LOCAL06
	LDA f:SOUND_STONE_UNKNOWN4,X
	ASL
	CLC
	ADC #$30
	STA SOUND_STONE_SPRITEMAP_1 + spritemap::flags
	LDX @LOCAL06
	REP #PROC_FLAGS::ACCUM8
	LDA f:SOUND_STONE_UNKNOWN2,X
	AND #$00FF
	TAY
	LDX @LOCAL06
	LDA f:SOUND_STONE_UNKNOWN,X
	AND #$00FF
	TAX
	LDA #.LOWORD(SOUND_STONE_SPRITEMAP_1)
	JSL WRITE_SPRITEMAP_TO_OAM
@NEXT_MELODY_SPRITE:
	INC @LOCAL06
@SPRITE_LOOP_CHECK:
	LDA @LOCAL06
	CMP #8
	BCCL @PROCESS_MELODY_SPRITE
	DEC @LOCAL0E
	LDA @LOCAL0E
	BNE @UPDATE_CENTER_SPRITE
	LDA #15
	STA @LOCAL0E
	LDA @LOCAL0F
	INC
	AND #$0003
	STA @LOCAL0F
@UPDATE_CENTER_SPRITE:
	LDA @LOCAL0F
	SEP #PROC_FLAGS::ACCUM8
	ASL
	CLC
	ADC #64
	STA SOUND_STONE_SPRITEMAP_2 + spritemap::tile
	LDA #$3B
	STA SOUND_STONE_SPRITEMAP_2 + spritemap::flags
	LDY #112
	LDX #128
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(SOUND_STONE_SPRITEMAP_2)
	JSL WRITE_SPRITEMAP_TO_OAM
	JSL UPDATE_SCREEN
	LDX #0
	LDA #.LOWORD(LOADED_BG_DATA_LAYER1)
	JSL GENERATE_BATTLEBG_FRAME
	LDX #1
	LDA #.LOWORD(LOADED_BG_DATA_LAYER2)
	JSL GENERATE_BATTLEBG_FRAME
	LDA @LOCAL11
	BEQL @MAIN_LOOP
	LDA @LOCAL08
	AND #$80C0
	BEQL @MAIN_LOOP
@EXIT_FADE_OUT:
	LDX #1
	TXA
	JSL FADE_OUT
	BRA @WAIT_FADE_CHECK
@WAIT_FADE_STEP:
	JSL WAIT_UNTIL_NEXT_FRAME
@WAIT_FADE_CHECK:
	LDA FADE_PARAMETERS + fade_parameters::step
	AND #$00FF
	BNE @WAIT_FADE_STEP
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	LDA #1
	JSL SET_COLOR_MATH_FROM_TABLE
	JSL RELOAD_MAP
	LDX #1
	TXA
	JSL FADE_IN
	END_C_FUNCTION
