
WAIT_FRAMES_WITH_UPDATES:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL00
	BRA @CHECK_COUNT
@FRAME_LOOP:
	JSL OAM_CLEAR
	JSL RUN_ACTIONSCRIPT_FRAME
	JSL UPDATE_SCREEN
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA @LOCAL00
	DEC
	STA @LOCAL00
@CHECK_COUNT:
	BNE @FRAME_LOOP
	END_C_FUNCTION
