
WAIT_FRAMES_OR_UNTIL_PRESSED:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STA @LOCAL00
	BRA @LOOP_CHECK
@CHECK_PRESS:
	LDA PAD_PRESS
	BEQ @NO_PRESS
	LDA #1
	BRA @RETURN
@NO_PRESS:
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA @LOCAL00
	DEC
	STA @LOCAL00
@LOOP_CHECK:
	BNE @CHECK_PRESS
	LDA #0
@RETURN:
	END_C_FUNCTION
