
ADD_ENTITY_POSITION_OFFSET:
	LDY ENTITY_SCRIPT_VAR0_TABLE,X
	LDA ENTITY_ABS_X_FRACTION_TABLE,Y
	CLC
	ADC ENTITY_ABS_X_FRACTION_TABLE,X
	LDA ENTITY_SCREEN_X_TABLE,Y
	ADC ENTITY_ABS_X_TABLE,X
	STA ENTITY_SCREEN_X_TABLE,X
	LDA ENTITY_ABS_Y_FRACTION_TABLE,Y
	CLC
	ADC ENTITY_ABS_Y_FRACTION_TABLE,X
	LDA ENTITY_SCREEN_Y_TABLE,Y
	ADC ENTITY_ABS_Y_TABLE,X
	STA ENTITY_SCREEN_Y_TABLE,X
	RTS
