
ALLOCATE_SPRITE_VRAM:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	STX @VIRTUAL04
	STA @VIRTUAL02
	STA @LOCAL02
	LDY #0
	BRA @OUTER_LOOP
@CHECK_FREE:
	LDA #0
	STA @LOCAL01
	BRA @COUNT_CHECK
@CHECK_SLOT:
	STA @VIRTUAL02
	TYA
	CLC
	ADC @VIRTUAL02
	TAX
	LDA SPRITE_VRAM_TABLE,X
	AND #$00FF
	BNE @SLOT_OCCUPIED
	LDA @LOCAL01
	INC
	STA @LOCAL01
@COUNT_CHECK:
	LDX @LOCAL02
	STX @VIRTUAL02
	CMP @VIRTUAL02
	BCC @CHECK_SLOT
	LDA #0
	STA @LOCAL00
	BRA @MARK_COUNT_CHECK
@MARK_SLOT:
	STA @VIRTUAL02
	TYA
	CLC
	ADC @VIRTUAL02
	TAX
	LDA @VIRTUAL04
	SEP #PROC_FLAGS::ACCUM8
	ORA #$0080
	STA SPRITE_VRAM_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	INC
	STA @LOCAL00
@MARK_COUNT_CHECK:
	LDX @LOCAL02
	STX @VIRTUAL02
	CMP @VIRTUAL02
	BCC @MARK_SLOT
	TYA
	BRA @RETURN
@SLOT_OCCUPIED:
	TXY
	INY
@OUTER_LOOP:
	LDA @LOCAL02
	STA @VIRTUAL02
	LDA #88
	SEC
	SBC @VIRTUAL02
	STA @VIRTUAL02
	TYA
	CMP @VIRTUAL02
	BLTEQ @CHECK_FREE
	LDA #.LOWORD(-253)
@RETURN:
	END_C_FUNCTION
