
ANIMATE_ENTITY_TILE_BLEND:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STZ @LOCAL06
	LDA #0
	STA @VIRTUAL04
	MOVE_INT ENTITY_FADE_STATES, @VIRTUAL0A
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL05
	JMP @LOOP_CHECK
@PROCESS_ENTITY:
	LDY #4
	LDA [@VIRTUAL0A],Y
	CMP #3
	BNEL @ADVANCE_ENTRY
	INC @VIRTUAL04
	LDY #18
	LDA [@VIRTUAL0A],Y
	CMP #2
	BNE @PHASE_NOT_DONE
	INC @LOCAL06
	JMP @ADVANCE_ENTRY
@PHASE_NOT_DONE:
	CMP #0
	BEQ @PHASE0
	LDY #16
	LDA [@VIRTUAL0A],Y
	STA @LOCAL04
	AND #$0001
	BNE @PHASE1_ODD_STEP
	LDA @LOCAL04
	TAX
	BRA @DO_BLEND
@PHASE1_ODD_STEP:
	LDA @LOCAL04
	STA @VIRTUAL02
	LDY #6
	LDA [@VIRTUAL0A],Y
	SEC
	SBC @VIRTUAL02
	TAX
	DEX
	BRA @DO_BLEND
@PHASE0:
	LDY #16
	LDA [@VIRTUAL0A],Y
	STA @LOCAL04
	AND #$0001
	BEQ @PHASE0_EVEN_STEP
	LDA @LOCAL04
	TAX
	BRA @DO_BLEND
@PHASE0_EVEN_STEP:
	LDA @LOCAL04
	STA @VIRTUAL02
	LDY #6
	LDA [@VIRTUAL0A],Y
	SEC
	SBC @VIRTUAL02
	TAX
	DEX
@DO_BLEND:
	LDA #12
	MOVE_INTY @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL03
	LDA @VIRTUAL06+2
	STA @LOCAL03+2
	LDA #6
	MOVE_INTY @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL02
	LDA @VIRTUAL06+2
	STA @LOCAL02+2
	LDY #8
	LDA [@VIRTUAL0A],Y
	STA @LOCAL00
	LDA [@LOCAL02]
	LSR
	LSR
	LSR
	ASL
	ASL
	ASL
	ASL
	ASL
	STA @LOCAL01
	TXY
	STY @LOCAL04
	LDY #10
	LDA [@VIRTUAL0A],Y
	TAX
	MOVE_INT @LOCAL03, @VIRTUAL06
	LDA [@VIRTUAL06]
	LDY @LOCAL04
	JSL BLEND_SPRITE_TILE_DATA
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	LDA [@VIRTUAL06]
	TAX
	MOVE_INT @LOCAL03, @VIRTUAL06
	LDA [@VIRTUAL06]
	JSL UPLOAD_ENTITY_SPRITE_TO_VRAM
	LDA #16
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL03
	LDA @VIRTUAL06+2
	STA @LOCAL03+2
	LDA [@VIRTUAL06]
	INC
	STA @LOCAL04
	STA [@VIRTUAL06]
	LDA [@LOCAL02]
	LSR
	STA @VIRTUAL02
	LDA @LOCAL04
	CMP @VIRTUAL02
	BCC @ADVANCE_ENTRY
	LDA #18
	MOVE_INTX @VIRTUAL0A, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL02
	LDA @VIRTUAL06+2
	STA @LOCAL02+2
	LDA [@LOCAL02]
	INC
	STA [@LOCAL02]
	LDA #0
	MOVE_INTX @LOCAL03, @VIRTUAL06
	STA [@VIRTUAL06]
@ADVANCE_ENTRY:
	LDA #20
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA @LOCAL05
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL05
@LOOP_CHECK:
	LDA @VIRTUAL02
	CMP ENTITY_FADE_STATES_LENGTH
	BCCL @PROCESS_ENTITY
	LDA @VIRTUAL04
	SEC
	SBC @LOCAL06
	PLD
	RTL
