
ANIMATE_ENTITY_TILE_COPY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STZ @LOCAL07
	LDA #0
	STA @VIRTUAL04
	MOVE_INT ENTITY_FADE_STATES, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL06
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL05
	JMP @ENTITY_LOOP_CHECK
@PROCESS_ENTITY:
	LDY #4
	LDA [@LOCAL06],Y
	CMP #2
	BNEL @NEXT_ENTITY
	INC @VIRTUAL04
	MOVE_INT @LOCAL06, @VIRTUAL06
	LDA #18
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL03
	LDA @VIRTUAL06+2
	STA @LOCAL04
	LDA [@LOCAL03]
	CMP #2
	BNE @ANIMATE_TILE
	INC @LOCAL07
	JMP @NEXT_ENTITY
@ANIMATE_TILE:
	MOVE_INT @LOCAL06, @VIRTUAL0A
	LDA #16
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	STA @LOCAL02
	LDY #6
	LDA [@LOCAL06],Y
	LSR
	LSR
	LSR
	TAX
	LDY #8
	LDA @LOCAL02
	JSL MODULUS16
	ASL
	STA @VIRTUAL02
	TXA
	ASL
	ASL
	ASL
	ASL
	ASL
	TAY
	LDA @LOCAL02
	LSR
	LSR
	LSR
	JSL MULT16
	CLC
	ADC @VIRTUAL02
	STA @LOCAL02
	MOVE_INT @LOCAL06, @VIRTUAL06
	LDA #12
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STX @LOCAL00
	LDA @LOCAL02
	TAY
	STY @LOCAL01
	LDY #10
	LDA [@LOCAL06],Y
	TAX
	LDA [@VIRTUAL06]
	LDY @LOCAL01
	JSL COPY_SPRITE_TILE_DATA
	LDY #0
	LDA [@LOCAL06],Y
	TAX
	LDA [@VIRTUAL06]
	JSL UPLOAD_ENTITY_SPRITE_TO_VRAM
	LDA [@VIRTUAL0A]
	INC
	INC
	STA [@VIRTUAL0A]
	LDY #8
	CMP [@LOCAL06],Y
	BCC @NEXT_ENTITY
	LDA #1
	STA [@VIRTUAL0A]
	LDA [@LOCAL03]
	INC
	STA [@LOCAL03]
@NEXT_ENTITY:
	MOVE_INT @LOCAL06, @VIRTUAL06
	LDA #20
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL06
	LDA @VIRTUAL06+2
	STA @LOCAL06+2
	LDA @LOCAL05
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL05
@ENTITY_LOOP_CHECK:
	LDA @VIRTUAL02
	CMP ENTITY_FADE_STATES_LENGTH
	BCCL @PROCESS_ENTITY
	LDA @VIRTUAL04
	SEC
	SBC @LOCAL07
	END_C_FUNCTION
