
ANIMATE_ENTITY_TILE_MERGE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	END_STACK_VARS
	MOVE_INT ENTITY_FADE_STATES, @VIRTUAL0A
	LOADPTR BUFFER + $7F00, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL06
	JSL RAND
	AND #$003F
	STA @LOCAL05
	ASL
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	BEQ @SLOT_FOUND
@FIND_UNUSED_SLOT:
	LDA @LOCAL05
	INC
	AND #$003F
	STA @LOCAL05
	ASL
	MOVE_INTX @LOCAL06, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	BNE @FIND_UNUSED_SLOT
@SLOT_FOUND:
	LDA @LOCAL05
	ASL
	MOVE_INTX @LOCAL06, @VIRTUAL06
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA #1
	STA [@VIRTUAL06]
	LDA @LOCAL05
	LSR
	LSR
	LSR
	STA @LOCAL04
	LDY #8
	LDA @LOCAL05
	JSL MODULUS16
	STA @LOCAL03
	STZ @LOCAL02
	JMP @ENTITY_LOOP_CHECK
@PROCESS_ENTITY:
	LDY #4
	LDA [@VIRTUAL0A],Y
	CMP #4
	BNEL @ADVANCE_ENTRY
	LDA #0
	STA @VIRTUAL04
	BRA @COLUMN_LOOP_CHECK
@PROCESS_COLUMN:
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL01
	BRA @ROW_LOOP_CHECK
@PROCESS_ROW:
	LDA @LOCAL01
	STA @VIRTUAL02
	ASL
	ASL
	ASL
	ASL
	ASL
	PHA
	LDA @LOCAL04
	ASL
	STA @VIRTUAL02
	LDA @VIRTUAL04
	JSL MULT16
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL02
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	STA @LOCAL05
	LDA @LOCAL03
	STA @LOCAL00
	LDA @LOCAL05
	TAY
	STY @LOCAL05
	LDY #10
	LDA [@VIRTUAL0A],Y
	TAX
	LDY #12
	LDA [@VIRTUAL0A],Y
	LDY @LOCAL05
	JSL MERGE_SPRITE_TILE_PAIR
	LDA @LOCAL01
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL01
@ROW_LOOP_CHECK:
	LDY #6
	LDA [@VIRTUAL0A],Y
	LSR
	LSR
	LSR
	TAY
	LDA @VIRTUAL02
	STY @VIRTUAL02
	CMP @VIRTUAL02
	BCC @PROCESS_ROW
	INC @VIRTUAL04
@COLUMN_LOOP_CHECK:
	LDY #8
	LDA [@VIRTUAL0A],Y
	LSR
	LSR
	LSR
	STA @VIRTUAL02
	LDA @VIRTUAL04
	CMP @VIRTUAL02
	BCCL @PROCESS_COLUMN
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	LDA [@VIRTUAL06]
	TAX
	LDY #12
	LDA [@VIRTUAL0A],Y
	JSL UPLOAD_ENTITY_SPRITE_TO_VRAM
@ADVANCE_ENTRY:
	LDA #20
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	INC @LOCAL02
@ENTITY_LOOP_CHECK:
	LDA ENTITY_FADE_STATES_LENGTH
	CMP @LOCAL02
	BGTL @PROCESS_ENTITY
	END_C_FUNCTION
