
APPLY_ENTITY_DELTA_POSITION_ENTRY2:
	LDX $88
APPLY_ENTITY_DELTA_POSITION_ENTRY3:
	LDA ENTITY_ABS_X_FRACTION_TABLE,X
	CLC
	ADC ENTITY_DELTA_X_FRACTION_TABLE,X
	STA ENTITY_ABS_X_FRACTION_TABLE,X
	LDA ENTITY_ABS_X_TABLE,X
	ADC ENTITY_DELTA_X_TABLE,X
	STA ENTITY_ABS_X_TABLE,X
	LDA ENTITY_ABS_Y_FRACTION_TABLE,X
	CLC
	ADC ENTITY_DELTA_Y_FRACTION_TABLE,X
	STA ENTITY_ABS_Y_FRACTION_TABLE,X
	LDA ENTITY_ABS_Y_TABLE,X
	ADC ENTITY_DELTA_Y_TABLE,X
	STA ENTITY_ABS_Y_TABLE,X
APPLY_ENTITY_DELTA_POSITION_ENTRY4:
	RTS
