
ASSIGN_ENTITY_SCRIPT_FROM_STREAM:
	JSR SCRIPT_READ_BYTE
	TAX
	JSR SCRIPT_READ_WORD
	PHA
	JSR SCRIPT_READ_BYTE
	STY $94
	TAY
	PLA
	JMP REASSIGN_ENTITY_SCRIPT
	LDX CURRENT_ENTITY_OFFSET
	BRA @CHECK_ON_SCREEN
	LDX $88
	BRA @CHECK_ON_SCREEN
	ASL
	TAX
@CHECK_ON_SCREEN:
	LDY #$0000
	SEP #PROC_FLAGS::ACCUM8
	LDA ENTITY_SCREEN_X_TABLE+1,X
	BNE @RETURN
	LDA ENTITY_SCREEN_Y_TABLE+1,X
	BNE @RETURN
	DEY
@RETURN:
	REP #PROC_FLAGS::ACCUM8
	TYA
	RTL
