
BUILD_ENTITY_DRAW_LIST:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA PAD_STATE + 2
	AND #PAD::SELECT_BUTTON
	BEQ @NORMAL_PATH
	JSR SORT_ENTITY_DRAW_ORDER
	JMP @DONE
@NORMAL_PATH:
	LDA #.LOWORD(-1)
	STA @LOCAL04
	LDY FIRST_ENTITY
	STY @LOCAL03
	BRA @CHECK_ENTITY_LOOP
@PROCESS_ENTITY:
	TYA
	LSR
	ASL
	TAX
	LDA ENTITY_SCREEN_Y_TABLE,X
	CMP #256
	BCC @CHECK_SCREEN_X
	CMP #.LOWORD(-64)
	BCC @NEXT_ENTITY
@CHECK_SCREEN_X:
	TYA
	LSR
	ASL
	TAX
	LDA ENTITY_SCREEN_X_TABLE,X
	CMP #320
	BCC @CHECK_PRIORITY
	CMP #.LOWORD(-64)
	BCC @NEXT_ENTITY
@CHECK_PRIORITY:
	TYA
	LSR
	STA @LOCAL02
	ASL
	TAX
	LDA ENTITY_DRAW_PRIORITY,X
	CMP #1
	BNE @DRAW_IMMEDIATELY
	LDA @LOCAL04
	STA ENTITY_DRAW_SORTING,X
	LDA @LOCAL02
	STA @LOCAL04
	BRA @NEXT_ENTITY
@DRAW_IMMEDIATELY:
	LDA @LOCAL02
	JSR CALL_ENTITY_DRAW_CALLBACK
@NEXT_ENTITY:
	LDY @LOCAL03
	TYA
	LSR
	ASL
	TAX
	LDY ENTITY_NEXT_ENTITY_TABLE,X
	STY @LOCAL03
@CHECK_ENTITY_LOOP:
	TYA
	INC
	BNE @PROCESS_ENTITY
	BRA @SORT_CHECK_EMPTY
@SORT_OUTER_LOOP:
	LDA @LOCAL04
	STA @LOCAL01
	LDA @LOCAL04
	ASL
	TAX
	LDA ENTITY_ABS_Y_TABLE,X
	STA @LOCAL00
	LDA #.LOWORD(-1)
	STA @VIRTUAL04
	LDA @LOCAL04
	STA @VIRTUAL02
	LDY ENTITY_DRAW_SORTING,X
	BRA @SORT_CHECK_END
@SORT_COMPARE:
	TYA
	ASL
	TAX
	LDA ENTITY_ABS_Y_TABLE,X
	CMP @LOCAL00
	BCC @SORT_ADVANCE
	STA @LOCAL00
	STY @LOCAL01
	LDA @VIRTUAL02
	STA @VIRTUAL04
@SORT_ADVANCE:
	STY @VIRTUAL02
	TYA
	ASL
	TAX
	LDY ENTITY_DRAW_SORTING,X
@SORT_CHECK_END:
	TYA
	INC
	BNE @SORT_COMPARE
	LDA @LOCAL01
	JSR CALL_ENTITY_DRAW_CALLBACK
	LDA @VIRTUAL04
	INC
	BEQ @SORT_REMOVE_HEAD
	LDA @VIRTUAL04
	ASL
	PHA
	LDA @LOCAL01
	ASL
	TAX
	LDA ENTITY_DRAW_SORTING,X
	PLX
	STA ENTITY_DRAW_SORTING,X
	BRA @SORT_CHECK_EMPTY
@SORT_REMOVE_HEAD:
	LDA @LOCAL01
	ASL
	TAX
	LDA ENTITY_DRAW_SORTING,X
	STA @LOCAL04
@SORT_CHECK_EMPTY:
	LDA @LOCAL04
	INC
	BNE @SORT_OUTER_LOOP
@DONE:
	END_C_FUNCTION
