
CHECK_ENTITY_CAN_PURSUE:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_PATHFINDING_STATES,X
	BEQ @CHECK_INTANGIBILITY
	LDA #$0000
	BRA @RETURN
@CHECK_INTANGIBILITY:
	LDA PLAYER_INTANGIBILITY_FRAMES
	BNE @PLAYER_INTANGIBLE
	JSL CLASSIFY_ENTITY_LEADER_DISTANCE
	BRA @RETURN
@PLAYER_INTANGIBLE:
	LDA #$FFFF
@RETURN:
	RTL
