
CHECK_ENTITY_CAN_PURSUE_SHORT:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_PATHFINDING_STATES,X
	BEQ @NOT_PATHFINDING
	LDA #$0000
	BRA @RETURN
@NOT_PATHFINDING:
	LDA PLAYER_INTANGIBILITY_FRAMES
	BNE @PLAYER_INVULNERABLE
	JSL CLASSIFY_ENTITY_LEADER_DISTANCE_SHORT
	BRA @RETURN
@PLAYER_INVULNERABLE:
	LDA #$FFFF
@RETURN:
	RTL
