
CHOOSE_ENTITY_DIRECTION_TO_PLAYER:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	JSL CHECK_ENEMY_SHOULD_FLEE
	CMP #$0000
	BEQ @NO_FLEE
	JSL GET_OPPOSITE_DIRECTION_FROM_PLAYER_TO_ENTITY
	BRA @DONE
@NO_FLEE:
	JSL GET_DIRECTION_FROM_PLAYER_TO_ENTITY
@DONE:
	RTL
