
CLASSIFY_ENTITY_LEADER_DISTANCE_SHORT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA GAME_STATE+game_state::leader_x_coord
	SEC
	SBC ENTITY_ABS_X_TABLE,X
	STA @VIRTUAL02
	LDA GAME_STATE+game_state::leader_y_coord
	SEC
	SBC ENTITY_ABS_Y_TABLE,X
	STA @LOCAL00
	STA @VIRTUAL04
	LDA #0
	CLC
	SBC @VIRTUAL04
	BRANCHLTEQS @DY_POSITIVE
	LDA @LOCAL00
	EOR #$FFFF
	INC
	STA @VIRTUAL04
	BRA @ABS_DY_DONE
@DY_POSITIVE:
	LDA @LOCAL00
	STA @VIRTUAL04
@ABS_DY_DONE:
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @DX_POSITIVE
	LDA @VIRTUAL02
	EOR #$FFFF
	INC
	BRA @ABS_DX_DONE
@DX_POSITIVE:
	LDA @VIRTUAL02
@ABS_DX_DONE:
	CLC
	ADC @VIRTUAL04
	STA @LOCAL00
	CLC
	SBC #128
	BRANCHLTEQS @CHECK_80
	LDA #3
	BRA @RETURN
@CHECK_80:
	LDA @LOCAL00
	CLC
	SBC #80
	BRANCHLTEQS @CHECK_64
	LDA #2
	BRA @RETURN
@CHECK_64:
	LDA @LOCAL00
	CLC
	SBC #64
	BRANCHLTEQS @CLOSE
	LDA #1
	BRA @RETURN
@CLOSE:
	LDA #0
@RETURN:
	END_C_FUNCTION
