
CLASSIFY_ENTITY_LEADER_DISTANCE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA GAME_STATE+game_state::leader_x_coord
	SEC
	SBC ENTITY_ABS_X_TABLE,X
	STA @VIRTUAL02
	LDA GAME_STATE+game_state::leader_y_coord
	SEC
	SBC ENTITY_ABS_Y_TABLE,X
	STA @LOCAL00
	STA @VIRTUAL04
	LDA #0
	CLC
	SBC @VIRTUAL04
	BRANCHLTEQS @Y_POSITIVE
	LDA @LOCAL00
	EOR #$FFFF
	INC
	STA @VIRTUAL04
	BRA @Y_ABS_DONE
@Y_POSITIVE:
	LDA @LOCAL00
	STA @VIRTUAL04
@Y_ABS_DONE:
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @X_POSITIVE
	LDA @VIRTUAL02
	EOR #$FFFF
	INC
	BRA @COMPUTE_MANHATTAN
@X_POSITIVE:
	LDA @VIRTUAL02
@COMPUTE_MANHATTAN:
	CLC
	ADC @VIRTUAL04
	STA @LOCAL00
	CLC
	SBC #256
	BRANCHLTEQS @DIST_FAR
	LDA #3
	BRA @RETURN
@DIST_FAR:
	LDA @LOCAL00
	CLC
	SBC #160
	BRANCHLTEQS @DIST_MEDIUM
	LDA #2
	BRA @RETURN
@DIST_MEDIUM:
	LDA @LOCAL00
	CLC
	SBC #128
	BRANCHLTEQS @DIST_CLOSE
	LDA #1
	BRA @RETURN
@DIST_CLOSE:
	LDA #0
@RETURN:
	END_C_FUNCTION
