
CLEAR_SPRITEMAP_BUFFER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	END_STACK_VARS
	LOADPTR BUFFER + $7F00, @VIRTUAL06
	LDX #0
	BRA @ENTRY_LOOP_CHECK
@CLEAR_ENTRY:
	LDA #0
	STA [@VIRTUAL06]
	INC @VIRTUAL06
	INC @VIRTUAL06
	INX
@ENTRY_LOOP_CHECK:
	CPX #64
	BCC @CLEAR_ENTRY
	END_C_FUNCTION
