
CLEAR_FADE_ENTITY_FLAGS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	END_STACK_VARS
	MOVE_INT ENTITY_FADE_STATES, @VIRTUAL06
	LDY #0
	BRA @ENTITY_LOOP_CHECK
@PROCESS_ENTITY:
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	LDA [@VIRTUAL0A]
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAX
	LDA __BSS_START__,X
	AND #$BFFF
	STA __BSS_START__,X
	LDA #20
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	INY
@ENTITY_LOOP_CHECK:
	CPY ENTITY_FADE_STATES_LENGTH
	BCC @PROCESS_ENTITY
	END_C_FUNCTION
