
CLEAR_ENTITY_DELTA_MOTION:
	ASL
	TAX
	STZ ENTITY_DELTA_X_FRACTION_TABLE,X
	STZ ENTITY_DELTA_X_TABLE,X
	STZ ENTITY_DELTA_Y_FRACTION_TABLE,X
	STZ ENTITY_DELTA_Y_TABLE,X
	STZ ENTITY_DELTA_Z_FRACTION_TABLE,X
	STZ ENTITY_DELTA_Z_TABLE,X
	RTL
