
CLEAR_OVERWORLD_SPRITEMAPS:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDX #$0000
	BRA @LOOP_CHECK
@FILL_BYTE:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FF
	STA OVERWORLD_SPRITEMAPS,X
	INX
@LOOP_CHECK:
	CPX #$0380
	BCC @FILL_BYTE
	REP #PROC_FLAGS::ACCUM8
	RTL
