
CREATE_ENTITY_FROM_STREAM:
	STZ ENTITY_ALLOCATION_MIN_SLOT
	LDA #$003C
	STA ENTITY_ALLOCATION_MAX_SLOT
@READ_PARAMS:
	LDX $88
	JSR SCRIPT_READ_WORD
	STA $96
	JSR SCRIPT_READ_WORD
	CLC
	ADC ENTITY_SCREEN_X_TABLE,X
	STA $98
	JSR SCRIPT_READ_WORD
	CLC
	ADC ENTITY_SCREEN_Y_TABLE,X
	STA $9A
	JSR SCRIPT_READ_WORD
	CLC
	ADC ENTITY_ABS_Z_TABLE,X
	STA NEW_ENTITY_POS_Z
	JSR SCRIPT_READ_WORD
	STA NEW_ENTITY_VAR0
	JSR SCRIPT_READ_WORD
	CLC
	ADC ENTITY_SCRIPT_VAR1_TABLE,X
	STA NEW_ENTITY_VAR1
	STX NEW_ENTITY_VAR2
	STZ NEW_ENTITY_VAR3
	STZ NEW_ENTITY_VAR4
	STZ NEW_ENTITY_VAR5
	STZ NEW_ENTITY_VAR6
	STZ NEW_ENTITY_VAR7
	STY $94
	LDY $9A
	LDX $98
	LDA $96
	AND #$7FFF
	JMP INIT_ENTITY
	JSR SCRIPT_READ_BYTE
	STA ENTITY_ALLOCATION_MIN_SLOT
	JSR SCRIPT_READ_BYTE
	STA ENTITY_ALLOCATION_MAX_SLOT
	BRA @READ_PARAMS
	JSR SCRIPT_READ_BYTE
	STA ENTITY_ALLOCATION_MIN_SLOT
	INC
	INC
	STA ENTITY_ALLOCATION_MAX_SLOT
	BRA @READ_PARAMS
	JSR SCRIPT_READ_BYTE
	STA ENTITY_ALLOCATION_MIN_SLOT
	TAX
	INC
	INC
	STA ENTITY_ALLOCATION_MAX_SLOT
	STY $94
	JSR DEACTIVATE_ENTITY
	LDY $94
	JMP @READ_PARAMS
	STZ ENTITY_ALLOCATION_MIN_SLOT
	LDA #$003C
	STA ENTITY_ALLOCATION_MAX_SLOT
	STZ NEW_ENTITY_VAR1
	STZ NEW_ENTITY_VAR3
	STZ NEW_ENTITY_VAR4
	STZ NEW_ENTITY_VAR5
	STZ NEW_ENTITY_VAR6
	STZ NEW_ENTITY_VAR7
	STZ NEW_ENTITY_POS_Z
	JSR SCRIPT_READ_WORD
	TAX
	JSR SCRIPT_READ_WORD
	STY $94
	STA NEW_ENTITY_VAR0
	LDA $88
	STA NEW_ENTITY_VAR2
	TXA
	AND #$7FFF
	JMP INIT_ENTITY
