
DEALLOCATE_ENTITY_SPRITE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	STA @VIRTUAL02
	ASL
	TAY
	STY @LOCAL00
	LDA ENTITY_SPRITEMAP_POINTER_LOW,Y
	JSL CLEAR_SPRITEMAP_SLOTS
	LDX #0
	LDA @VIRTUAL02
	JSL ALLOC_SPRITE_MEM
	LDY @LOCAL00
	LDA ENTITY_NPC_IDS,Y
	AND #$F000
	CMP #$8000
	BNE @NOT_ENEMY
	DEC OVERWORLD_ENEMY_COUNT
@NOT_ENEMY:
	LDA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_ENEMY_IDS,X
	CMP #ENEMY::MAGIC_BUTTERFLY
	BNE @NOT_BUTTERFLY
	STZ MAGIC_BUTTERFLY_SPAWNED
@NOT_BUTTERFLY:
	LDA @VIRTUAL02
	ASL
	TAX
	LDA #.LOWORD(-1)
	STA ENTITY_SPRITE_IDS,X
	STA ENTITY_NPC_IDS,X
	END_C_FUNCTION
