
DISABLE_ALL_ENTITY_CALLBACKS:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	LDA #$FFFF
	STA CURRENT_ENTITY_OFFSET
DISABLE_OTHER_ENTITY_CALLBACKS:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	PHA
	LDX #$0000
@BACKUP_LOOP:
	LDA ENTITY_TICK_CALLBACK_HIGH,X
	STA ENTITY_CALLBACK_FLAGS_BACKUP,X
	INX
	INX
	CPX #$003C
	BNE @BACKUP_LOOP
	PLA
	LDX FIRST_ENTITY
	BMI @DONE
@DISABLE_LOOP:
	CPX CURRENT_ENTITY_OFFSET
	BEQ @SKIP_CURRENT
	LDA ENTITY_TICK_CALLBACK_HIGH,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA ENTITY_TICK_CALLBACK_HIGH,X
@SKIP_CURRENT:
	LDA ENTITY_NEXT_ENTITY_TABLE,X
	TAX
	BPL @DISABLE_LOOP
@DONE:
	RTL
