
DISABLE_OTHER_ENTITY_UPDATES:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #0
	STA @LOCAL00
	BRA @LOOP_CHECK
@LOOP:
	CMP CURRENT_ENTITY_SLOT
	BEQ @NEXT_ENTITY
	CMP #23
	BEQ @NEXT_ENTITY
	ASL
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA __BSS_START__,X
@NEXT_ENTITY:
	LDA @LOCAL00
	INC
	STA @LOCAL00
@LOOP_CHECK:
	CMP #MAX_ENTITIES
	BCC @LOOP
	END_C_FUNCTION
