
DRAW_ENTITY:
	LDA ENTITY_SPRITEMAP_POINTER_HIGH,X
	BMI @SKIP
	BVS @SKIP
	STA $8E
	LDA ENTITY_SPRITEMAP_POINTER_LOW,X
	STA $8C
	LDA ENTITY_ANIMATION_FRAME,X
	BMI @SKIP
	JMP (.LOWORD(ENTITY_DRAW_CALLBACK),X)
@SKIP:
	RTS
