
DRAW_ENTITY_SPRITE:
	LDA ENTITY_CURRENT_DISPLAYED_SPRITES,X
	AND #$0001
	BEQ @SKIP_SECOND_FRAME
	LDA ENTITY_SPRITEMAP_SIZES,X
	CLC
	ADC $8C
	STA $8C
@SKIP_SECOND_FRAME:
	SEP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	LDA #$0030
	LDY #$0020
	STA $00
	STA $02
	LDA ENTITY_SURFACE_FLAGS,X
	LSR
	BCC @UPPER_PRIORITY_SET
	STY $02
@UPPER_PRIORITY_SET:
	LSR
	BCC @LOWER_PRIORITY_SET
	STY $00
@LOWER_PRIORITY_SET:
	LDA ENTITY_UPPER_LOWER_BODY_DIVIDES+1,X
	TAX
	LDY #$00FD
	BRA @UPPER_CHECK
@UPPER_LOOP:
	INY
	INY
	INY
	INY
	INY
	LDA [$8C],Y
	AND #$00CF
	ORA $00
	STA [$8C],Y
@UPPER_CHECK:
	DEX
	BPL @UPPER_LOOP
	LDX $88
	LDA ENTITY_UPPER_LOWER_BODY_DIVIDES,X
	TAX
	BRA @LOWER_CHECK
@LOWER_LOOP:
	INY
	INY
	INY
	INY
	INY
	LDA [$8C],Y
	AND #$00CF
	ORA $02
	STA [$8C],Y
@LOWER_CHECK:
	DEX
	BPL @LOWER_LOOP
	REP #PROC_FLAGS::INDEX8
	LDX $88
	LDA $8E
	STA SPRITEMAP_BANK
	REP #PROC_FLAGS::ACCUM8
	LDA ENTITY_DRAW_PRIORITY,X
	STA CURRENT_SPRITE_DRAWING_PRIORITY
	TAY
	AND #$8000
	BEQ @DRAW_OVERLAYS
	TYA
	AND #$003F
	ASL
	TAX
	LDA ENTITY_DRAW_PRIORITY,X
	LDX $88
	STA CURRENT_SPRITE_DRAWING_PRIORITY
	TYA
	AND #$4000
	BNE @DRAW_OVERLAYS
	LDA #$0000
	STA ENTITY_DRAW_PRIORITY,X
@DRAW_OVERLAYS:
	JSL DRAW_ENTITY_OVERLAYS
	LDX $88
	LDA $8E
	STA SPRITEMAP_BANK
	LDY ENTITY_SCREEN_Y_TABLE,X
	LDA ENTITY_SCREEN_X_TABLE,X
	TAX
	LDA $8C
	JMP DISPATCH_SPRITE_DRAW_BY_PRIORITY
