
DRAW_ENTITY_OVERLAYS:
	LDA #$00C4
	STA $04
	STA SPRITEMAP_BANK
	LDY #$0000
	LDA ENTITY_SURFACE_FLAGS,X
	AND #$0001
	BEQ @AFTER_SURFACE_CHECK
	LDY #$0005
@AFTER_SURFACE_CHECK:
	STY $00
	LDA ENTITY_SURFACE_FLAGS,X
	AND #$000C
	BEQ @AFTER_RIPPLE
	CMP #$0004
	BEQ @DRAW_SWEAT
	LDA ENTITY_BYTE_WIDTHS,X
	CMP #$0040
	BNE @BIG_RIPPLE
	LDA ENTITY_RIPPLE_OVERLAY_PTRS,X
	STA $02
	LDA ENTITY_RIPPLE_NEXT_UPDATE_FRAMES,X
	BNE @RIPPLE_TICK
	LDA #.LOWORD(ENTITY_RIPPLE_SPRITEMAPS)
	JSR EXECUTE_OVERLAY_ANIMATION_SCRIPT
	LDX $88
	STA ENTITY_RIPPLE_OVERLAY_PTRS,X
	TYA
	STA ENTITY_RIPPLE_NEXT_UPDATE_FRAMES,X
@RIPPLE_TICK:
	DEC ENTITY_RIPPLE_NEXT_UPDATE_FRAMES,X
	LDA ENTITY_SCREEN_X_TABLE,X
	STA $06
	LDY ENTITY_SCREEN_Y_TABLE,X
	LDA ENTITY_RIPPLE_SPRITEMAPS,X
	CLC
	ADC $00
	LDX $06
	JSR DISPATCH_SPRITE_DRAW_BY_PRIORITY
	BRA @AFTER_RIPPLE
@BIG_RIPPLE:
	LDA ENTITY_BIG_RIPPLE_OVERLAY_PTRS,X
	STA $02
	LDA ENTITY_BIG_RIPPLE_NEXT_UPDATE_FRAMES,X
	BNE @BIG_RIPPLE_TICK
	LDA #.LOWORD(ENTITY_BIG_RIPPLE_SPRITEMAPS)
	JSR EXECUTE_OVERLAY_ANIMATION_SCRIPT
	LDX $88
	STA ENTITY_BIG_RIPPLE_OVERLAY_PTRS,X
	TYA
	STA ENTITY_BIG_RIPPLE_NEXT_UPDATE_FRAMES,X
@BIG_RIPPLE_TICK:
	DEC ENTITY_BIG_RIPPLE_NEXT_UPDATE_FRAMES,X
	LDA ENTITY_SCREEN_X_TABLE,X
	STA $06
	LDA ENTITY_SCREEN_Y_TABLE,X
	CLC
	ADC #$0008
	TAY
	LDA ENTITY_BIG_RIPPLE_SPRITEMAPS,X
	CLC
	ADC $00
	ADC $00
	LDX $06
	JSR DISPATCH_SPRITE_DRAW_BY_PRIORITY
@AFTER_RIPPLE:
	LDX $88
	LDA ENTITY_OVERLAY_FLAGS,X
	BNE @HAS_OVERLAY
	RTL
@HAS_OVERLAY:
	BPL @AFTER_SWEAT
@DRAW_SWEAT:
	CPX #$002E
	BCC @RETURN
	LDA ENTITY_SWEATING_OVERLAY_PTRS,X
	STA $02
	LDA ENTITY_SWEATING_NEXT_UPDATE_FRAMES,X
	BNE @SWEAT_TICK
	LDA #.LOWORD(ENTITY_SWEATING_SPRITEMAPS)
	JSR EXECUTE_OVERLAY_ANIMATION_SCRIPT
	LDX $88
	STA ENTITY_SWEATING_OVERLAY_PTRS,X
	TYA
	STA ENTITY_SWEATING_NEXT_UPDATE_FRAMES,X
@SWEAT_TICK:
	DEC ENTITY_SWEATING_NEXT_UPDATE_FRAMES,X
	LDA ENTITY_SCREEN_X_TABLE,X
	STA $06
	LDY ENTITY_SCREEN_Y_TABLE,X
	LDA ENTITY_SWEATING_SPRITEMAPS,X
	BEQ @AFTER_SWEAT
	CLC
	ADC $00
	LDX $06
	JSR DISPATCH_SPRITE_DRAW_BY_PRIORITY
	LDX $88
@AFTER_SWEAT:
	LDA ENTITY_OVERLAY_FLAGS,X
	AND #$4000
	BEQ @RETURN
	CPX #$002E
	BCC @RETURN
	LDA ENTITY_MUSHROOMIZED_OVERLAY_PTRS,X
	STA $02
	LDA ENTITY_MUSHROOMIZED_NEXT_UPDATE_FRAMES,X
	BNE @MUSHROOM_TICK
	LDA #.LOWORD(ENTITY_MUSHROOMIZED_SPRITEMAPS)
	JSR EXECUTE_OVERLAY_ANIMATION_SCRIPT
	LDX $88
	STA ENTITY_MUSHROOMIZED_OVERLAY_PTRS,X
	TYA
	STA ENTITY_MUSHROOMIZED_NEXT_UPDATE_FRAMES,X
@MUSHROOM_TICK:
	DEC ENTITY_MUSHROOMIZED_NEXT_UPDATE_FRAMES,X
	LDA ENTITY_SCREEN_X_TABLE,X
	STA $06
	LDY ENTITY_SCREEN_Y_TABLE,X
	LDA ENTITY_MUSHROOMIZED_SPRITEMAPS,X
	CLC
	ADC $00
	LDX $06
	JSR DISPATCH_SPRITE_DRAW_BY_PRIORITY
@RETURN:
	RTL
