
FACE_ENTITY_TOWARD_SPRITE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	LDY CURRENT_ENTITY_SLOT
	STY @LOCAL01
	TXA
	JSL FIND_ENTITY_BY_SPRITE_ID
	STA @VIRTUAL04
	CMP #.LOWORD(-1)
	BEQ @DONE
	LDA @VIRTUAL04
	ASL
	STA @VIRTUAL02
	LDY @LOCAL01
	TYA
	ASL
	TAX
	LDA ENTITY_ABS_Y_TABLE,X
	STA @LOCAL00
	LDY ENTITY_ABS_X_TABLE,X
	LDX @VIRTUAL02
	LDA ENTITY_ABS_Y_TABLE,X
	TAX
	STX @LOCAL01
	LDX @VIRTUAL02
	LDA ENTITY_ABS_X_TABLE,X
	LDX @LOCAL01
	JSL CALCULATE_DIRECTION_FROM_POSITIONS
	LDY #$2000
	CLC
	ADC #$1000
	JSL DIVISION16S_DIVISOR_POSITIVE
	STA @LOCAL01
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(ENTITY_DIRECTIONS)
	TAX
	LDA @LOCAL01
	STA @VIRTUAL02
	LDA __BSS_START__,X
	CMP @VIRTUAL02
	BEQ @DONE
	LDA @LOCAL01
	STA __BSS_START__,X
	LDA @VIRTUAL04
	JSL RENDER_ENTITY_SPRITE_ENTRY2
@DONE:
	END_C_FUNCTION
