
FIND_ENTITY_BY_TYPE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	BEQ @BY_CHARACTER
	CMP #1
	BEQ @BY_NPC_ID
	CMP #2
	BEQ @BY_SPRITE_ID
	BRA @RETURN
@BY_CHARACTER:
	TXA
	SEP #PROC_FLAGS::ACCUM8
	JSL FIND_ENTITY_FOR_CHARACTER
	TAY
	STY @LOCAL00
	BRA @RETURN
@BY_NPC_ID:
	TXA
	JSL FIND_ENTITY_BY_NPC_ID
	TAY
	STY @LOCAL00
	BRA @RETURN
@BY_SPRITE_ID:
	TXA
	JSL FIND_ENTITY_BY_SPRITE_ID
	TAY
	STY @LOCAL00
@RETURN:
	LDY @LOCAL00
	TYA
	END_C_FUNCTION
