
FIND_ENTITY_FOR_CHARACTER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	SEP #PROC_FLAGS::ACCUM8
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	CMP #$00FF
	BNE @SEARCH_PARTY
	LDA GAME_STATE+game_state::current_party_members
	BRA @RETURN
@SEARCH_PARTY:
	LDX #0
	BRA @LOOP_CHECK
@CHECK_MEMBER:
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	CMP GAME_STATE + game_state::party_order,X
	BNE @NEXT_MEMBER
	REP #PROC_FLAGS::ACCUM8
	TXA
	ASL
	TAX
	LDA GAME_STATE + game_state::party_entity_slots,X
	BRA @RETURN
@NEXT_MEMBER:
	INX
@LOOP_CHECK:
	CPX #6
	BCC @CHECK_MEMBER
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(-1)
@RETURN:
	END_C_FUNCTION
