
FIND_ENTITY_BY_NPC_ID:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL01
	LDA #0
	STA @LOCAL00
	BRA @LOOP_CHECK
@CHECK_ENTITY:
	ASL
	PHA
	LDX @LOCAL01
	TXA
	PLX
	CMP ENTITY_NPC_IDS,X
	BNE @NEXT_ENTITY
	LDA @LOCAL00
	BRA @RETURN
@NEXT_ENTITY:
	LDA @LOCAL00
	INC
	STA @LOCAL00
@LOOP_CHECK:
	CMP #MAX_ENTITIES
	BCC @CHECK_ENTITY
	LDA #.LOWORD(-1)
@RETURN:
	END_C_FUNCTION
