
FIND_ENTITY_FOR_CHARACTER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	AND #$00FF
	CMP #$00FF
	BNE @SEARCH_PARTY
	LDA GAME_STATE+game_state::current_party_members
	BRA @RETURN
@SEARCH_PARTY:
	LDA #0
	STA @LOCAL00
	BRA @LOOP_CHECK
@LOOP_BODY:
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	CMP a:game_state::party_order,X
	BNE @NEXT_MEMBER
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	ASL
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_entity_slots,X
	BRA @RETURN
@NEXT_MEMBER:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	INC
	STA @LOCAL00
@LOOP_CHECK:
	CMP #6
	BCC @LOOP_BODY
	LDA #.LOWORD(-1)
@RETURN:
	END_C_FUNCTION
