
FLUSH_ENTITY_CREATION_QUEUE:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	BRA @CHECK_LENGTH
@POP_ENTRY:
	LDA ENTITY_CREATION_QUEUE_LENGTH
	DEC
	STA ENTITY_CREATION_QUEUE_LENGTH
	ASL
	ASL
	TAY
	LDA ENTITY_CREATION_QUEUE + queued_entity_creation::script,Y
	TAX
	LDA ENTITY_CREATION_QUEUE + queued_entity_creation::sprite,Y
	JSL CREATE_PREPARED_ENTITY_SPRITE
@CHECK_LENGTH:
	LDA ENTITY_CREATION_QUEUE_LENGTH
	BNE @POP_ENTRY
	RTL
