
GET_ENTITY_BOUNDARY_SIDE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_ABS_X_TABLE,X
	LDY ENTITY_ABS_Y_TABLE,X
	CMP ENTITY_SCRIPT_VAR0_TABLE,X
	BCS @CHECK_RIGHT_BOUND
	LDA #3
	BRA @RETURN
@CHECK_RIGHT_BOUND:
	CMP ENTITY_SCRIPT_VAR1_TABLE,X
	BLTEQ @CHECK_TOP_BOUND
	LDA #7
	BRA @RETURN
@CHECK_TOP_BOUND:
	TYA
	CMP ENTITY_SCRIPT_VAR2_TABLE,X
	BCS @CHECK_BOTTOM_BOUND
	LDA #5
	BRA @RETURN
@CHECK_BOTTOM_BOUND:
	TYA
	CMP ENTITY_SCRIPT_VAR3_TABLE,X
	BLTEQ @INSIDE
	LDA #1
	BRA @RETURN
@INSIDE:
	LDA #0
@RETURN:
	END_C_FUNCTION
