
HIDE_ENTITY_SPRITES:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL00
	JSL CLEAR_PARTY_SPRITE_HIDE_FLAGS
	STZ PLAYER_INTANGIBILITY_FRAMES
	LDA @LOCAL00
	CMP #$00FF
	BEQ @ALL_PARTY
	SEP #PROC_FLAGS::ACCUM8
	JSL FIND_ENTITY_FOR_CHARACTER
	.A16
	CMP #.LOWORD(-1)
	BEQ @DONE
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #SPRITEMAP_FLAGS::DRAW_DISABLED
	STA __BSS_START__,X
	BRA @DONE
@ALL_PARTY:
	LDA #0
	STA @LOCAL00
	BRA @LOOP_CHECK
@LOOP_BODY:
	ASL
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_entity_slots,X
.ELSE
	TAX
	LDA GAME_STATE + game_state::party_entity_slots,X
.ENDIF
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #SPRITEMAP_FLAGS::DRAW_DISABLED
	STA __BSS_START__,X
	LDA @LOCAL00
	INC
	STA @LOCAL00
@LOOP_CHECK:
	LDA GAME_STATE+game_state::party_count
	AND #$00FF
	STA @VIRTUAL02
	LDA @LOCAL00
	CMP @VIRTUAL02
	BCC @LOOP_BODY
@DONE:
	END_C_FUNCTION
