
INIT_ENTITY_FADE_STATE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @VIRTUAL02
	STX @LOCAL06
	STA @VIRTUAL04
	STA @LOCAL05
	LDA @VIRTUAL02
	BEQL @DONE
	LDA @VIRTUAL02
	CMP #1
	BEQL @DONE
	LDA @VIRTUAL02
	CMP #6
	BEQL @DONE
	LDA @VIRTUAL04
	ASL
	TAX
	LDA ENTITY_TILE_HEIGHTS,X
	BEQL @DONE
	LDA ENTITY_FADE_ENTITY
	CMP #.LOWORD(-1)
	BNE @FADE_ENTITY_EXISTS
	JSR INIT_ENTITY_FADE_STATES_BUFFER
	STZ NEW_ENTITY_VAR3
	STZ NEW_ENTITY_VAR2
	STZ NEW_ENTITY_VAR1
	STZ NEW_ENTITY_VAR0
	LDY #0
	TYX
	LDA #EVENT_SCRIPT::EVENT_859
	JSL INIT_ENTITY_WIPE
	STA ENTITY_FADE_ENTITY
@FADE_ENTITY_EXISTS:
	MOVE_INT ENTITY_FADE_STATES, @VIRTUAL06
	LDA ENTITY_FADE_STATES_LENGTH
	OPTIMIZED_MULT @VIRTUAL04, 20
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL04
	LDA @VIRTUAL06+2
	STA @LOCAL04+2
	LDA @LOCAL05
	STA @VIRTUAL04
	LDY #0
	STA [@LOCAL04],Y
	LDA @VIRTUAL04
	ASL
	TAY
	STY @LOCAL03
	TYA
	CLC
	ADC #.LOWORD(ENTITY_SPRITEMAP_POINTER_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #$4000
	STA __BSS_START__,X
	LDA @VIRTUAL02
	LDY #2
	STA [@LOCAL04],Y
	LDY @LOCAL03
	LDA ENTITY_SIZES,Y
	STA @LOCAL02
	MOVE_INT @LOCAL04, @VIRTUAL0A
	LDA #6
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA @LOCAL02
	ASL
	TAX
	LDA f:ENTITY_TILE_BYTE_WIDTH_TABLE,X
	STA [@VIRTUAL0A]
	LDA ENTITY_TILE_HEIGHTS,Y
	ASL
	ASL
	ASL
	STA @LOCAL02
	LDY #8
	STA [@LOCAL04],Y
	MOVE_INT @LOCAL04, @VIRTUAL06
	LDA #14
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL01
	LDA @VIRTUAL06+2
	STA @LOCAL01+2
	LDA @LOCAL02
	TAY
	LDA [@VIRTUAL0A]
	JSL MULT16
	LSR
	STA @LOCAL02
	STA [@VIRTUAL06]
	MOVE_INT @LOCAL04, @VIRTUAL0A
	LDA #10
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA @LOCAL02
	ASL
	JSR DOUBLE_ENTITY_FADE_STATE
	STA @LOCAL03
	STA [@VIRTUAL0A]
	LDA [@VIRTUAL06]
	ASL
	TAX
	LDA @LOCAL03
	JSR CLEAR_BUFFER_RANGE
	MOVE_INT @LOCAL04, @VIRTUAL06
	LDA #12
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	MOVE_INT @LOCAL01, @VIRTUAL06
	LDA [@VIRTUAL06]
	STA @VIRTUAL02
	LDA [@VIRTUAL0A]
	CLC
	ADC @VIRTUAL02
	STA [@LOCAL00]
	LDA #0
	LDY #18
	STA [@LOCAL04],Y
	LDY #16
	STA [@LOCAL04],Y
	LDA @LOCAL06
	STA @VIRTUAL02
	CMP #2
	BEQ @WIPE_TYPE
	LDA @VIRTUAL02
	CMP #3
	BEQ @WIPE_TYPE
	LDA @VIRTUAL02
	CMP #4
	BEQ @WIPE_TYPE
	LDA @VIRTUAL02
	CMP #5
	BNE @USE_FULL_BUFFER
@WIPE_TYPE:
	LDY #10
	LDA [@LOCAL04],Y
	STA @LOCAL02
	BRA @INITIAL_REVEAL_SET
@USE_FULL_BUFFER:
	LDA [@LOCAL00]
	STA @LOCAL02
@INITIAL_REVEAL_SET:
	LDA @VIRTUAL04
	CMP #24
	BCC @COPY_4DIR_SPRITE
	LDY #14
	LDA [@LOCAL04],Y
	TAY
	LDA @LOCAL02
	TAX
	LDA @VIRTUAL04
	JSL COPY_8DIR_ENTITY_SPRITE
	BRA @AFTER_COPY_SPRITE
@COPY_4DIR_SPRITE:
	LDY #14
	LDA [@LOCAL04],Y
	TAY
	LDA @LOCAL02
	TAX
	LDA @VIRTUAL04
	JSL COPY_4DIR_ENTITY_SPRITE
@AFTER_COPY_SPRITE:
	LDA ENTITY_FADE_ENTITY
	STA @LOCAL02
	LDA @VIRTUAL02
	CMP #2
	BEQ @SET_FADE_DIRECTION_UP
	CMP #7
	BEQ @SET_FADE_DIRECTION_UP
	CMP #3
	BEQ @SET_FADE_DIRECTION_DOWN
	CMP #8
	BEQ @SET_FADE_DIRECTION_DOWN
	CMP #4
	BEQ @SET_FADE_DIRECTION_LEFT
	CMP #9
	BEQ @SET_FADE_DIRECTION_LEFT
	CMP #5
	BEQ @SET_FADE_DIRECTION_RIGHT
	CMP #10
	BEQ @SET_FADE_DIRECTION_RIGHT
	BRA @UPDATE_TOTAL_COUNT
@SET_FADE_DIRECTION_UP:
	LDA @LOCAL02
	ASL
	TAX
	LDA #1
	STA ENTITY_SCRIPT_VAR0_TABLE,X
	LDY #4
	STA [@LOCAL04],Y
	BRA @UPDATE_TOTAL_COUNT
@SET_FADE_DIRECTION_DOWN:
	LDA @LOCAL02
	ASL
	TAX
	LDA #1
	STA ENTITY_SCRIPT_VAR1_TABLE,X
	LDA #2
	LDY #4
	STA [@LOCAL04],Y
	BRA @UPDATE_TOTAL_COUNT
@SET_FADE_DIRECTION_LEFT:
	LDA @LOCAL02
	ASL
	TAX
	LDA #1
	STA ENTITY_SCRIPT_VAR2_TABLE,X
	LDA #3
	LDY #4
	STA [@LOCAL04],Y
	BRA @UPDATE_TOTAL_COUNT
@SET_FADE_DIRECTION_RIGHT:
	LDA @LOCAL02
	ASL
	TAX
	LDA #1
	STA ENTITY_SCRIPT_VAR3_TABLE,X
	LDA #4
	TAY
	STA [@LOCAL04],Y
@UPDATE_TOTAL_COUNT:
	LDA @LOCAL02
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR0_TABLE,X
	CLC
	ADC ENTITY_SCRIPT_VAR1_TABLE,X
	CLC
	ADC ENTITY_SCRIPT_VAR2_TABLE,X
	CLC
	ADC ENTITY_SCRIPT_VAR3_TABLE,X
	STA ENTITY_SCRIPT_VAR4_TABLE,X
	INC ENTITY_FADE_STATES_LENGTH
@DONE:
	END_C_FUNCTION
