
IS_ENTITY_IN_RANGE_OF_LEADER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA PSI_TELEPORT_DESTINATION
	BEQ @CHECK_RANGE
	LDA #0
	BRA @RETURN
@CHECK_RANGE:
	LDY CURRENT_ENTITY_SLOT
	TYA
	ASL
	TAX
	LDA ENTITY_ABS_X_TABLE,X
	SEC
	SBC GAME_STATE+game_state::leader_x_coord
	STA @LOCAL01
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @X_NEGATIVE
	LDA @LOCAL01
	EOR #$FFFF
	INC
	STA @LOCAL00
	BRA @X_ABS_DONE
@X_NEGATIVE:
	LDA @LOCAL01
	STA @LOCAL00
@X_ABS_DONE:
	TYA
	ASL
	TAX
	LDA @LOCAL00
	CMP ENTITY_SCRIPT_VAR2_TABLE,X
	BCS @OUT_OF_RANGE
	LDA ENTITY_ABS_Y_TABLE,X
	SEC
	SBC GAME_STATE+game_state::leader_y_coord
	STA @LOCAL01
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @Y_NEGATIVE
	LDA @LOCAL01
	EOR #$FFFF
	INC
	STA @LOCAL01
	BRA @Y_ABS_DONE
@Y_NEGATIVE:
	LDA @LOCAL01
	STA @LOCAL01
@Y_ABS_DONE:
	TYA
	ASL
	TAX
	LDA @LOCAL01
	CMP ENTITY_SCRIPT_VAR3_TABLE,X
	BCS @OUT_OF_RANGE
	LDA #1
	BRA @RETURN
@OUT_OF_RANGE:
	LDA #0
@RETURN:
	END_C_FUNCTION
