
IS_X_LESS_THAN_ENTITY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL01
	LDX #0
	STX @LOCAL00
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA @LOCAL01
	CMP ENTITY_ABS_X_TABLE,X
	BCS @DONE
	LDX #1
	STX @LOCAL00
@DONE:
	LDX @LOCAL00
	TXA
	END_C_FUNCTION
