
LOAD_OVERWORLD_SPRITEMAPS:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	STY @LOCAL05
	STX @VIRTUAL04
	TAX
	MOVE_INT @PARAM03, @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	STA @VIRTUAL02
	STA @LOCAL04
	INC @VIRTUAL06
	INC @VIRTUAL06
	LDY #0
	STY @LOCAL03
	JMP @DIR_LOOP_CHECK
@DIR_LOOP_BODY:
	LDA #0
	STA @LOCAL02
	BRA @SPRITE_LOOP_CHECK
@SPRITE_LOOP_BODY:
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	STA OVERWORLD_SPRITEMAPS + spritemap::y_offset,X
	INX ;spritemap::tile
	STX @LOCAL01
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	STA @VIRTUAL02
	LDA @VIRTUAL04
	CLC
	ADC @VIRTUAL02
	ASL
	TAX
	LDA f:SPRITE_TILE_INDEX_TABLE,X
	STA @LOCAL00
	SEP #PROC_FLAGS::ACCUM8
	LDX @LOCAL01
	STA OVERWORLD_SPRITEMAPS,X
	INX ;spritemap::flags
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	XBA
	AND #$00FF
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL05
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL01
	LDY #spritemap::flags
	LDA [@VIRTUAL06],Y
	AND #$00FE
	ORA @VIRTUAL01
	ORA @VIRTUAL00
	STA OVERWORLD_SPRITEMAPS,X
	INX ;spritemap::x_offset
	LDY #spritemap::x_offset
	LDA [@VIRTUAL06],Y
	STA OVERWORLD_SPRITEMAPS,X
	INX ;spritemap::special_flags
	LDY #spritemap::special_flags
	LDA [@VIRTUAL06],Y
	STA OVERWORLD_SPRITEMAPS,X
	INX ;next spritemap::y_offset
	REP #PROC_FLAGS::ACCUM8
	LDA #.SIZEOF(spritemap)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA @LOCAL02
	INC
	STA @LOCAL02
@SPRITE_LOOP_CHECK:
	LDY @LOCAL04
	STY @VIRTUAL02
	CMP @VIRTUAL02
	BCC @SPRITE_LOOP_BODY
	LDY @LOCAL03
	INY
	STY @LOCAL03
@DIR_LOOP_CHECK:
	CPY #2
	BCCL @DIR_LOOP_BODY
	END_C_FUNCTION
