
MOVE_ENTITY_TOWARD_TARGET:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	TXY
	STY @LOCAL04
	STA @VIRTUAL04
	LDA CURRENT_ENTITY_SLOT
	STA @VIRTUAL02
	STA @LOCAL03
	LDA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR6_TABLE,X
	SEC
	SBC ENTITY_ABS_X_TABLE,X
	STA @LOCAL02
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @X_DIFF_NEGATIVE
	LDA @LOCAL02
	EOR #$FFFF
	INC
	STA @LOCAL02
	BRA @X_ABS_DONE
@X_DIFF_NEGATIVE:
	LDA @LOCAL02
	STA @LOCAL02
@X_ABS_DONE:
	LDA @LOCAL03
	STA @VIRTUAL02
	ASL
	TAX
	LDA @LOCAL02
	CMP ENTITY_SCRIPT_VAR5_TABLE,X
	BCS @NOT_AT_TARGET
	LDA ENTITY_SCRIPT_VAR7_TABLE,X
	SEC
	SBC ENTITY_ABS_Y_TABLE,X
	STA @LOCAL02
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @Y_DIFF_NEGATIVE
	LDA @LOCAL02
	EOR #$FFFF
	INC
	STA @LOCAL02
	BRA @Y_ABS_DONE
@Y_DIFF_NEGATIVE:
	LDA @LOCAL02
	STA @LOCAL02
@Y_ABS_DONE:
	LDA @LOCAL03
	STA @VIRTUAL02
	ASL
	TAX
	LDA @LOCAL02
	CMP ENTITY_SCRIPT_VAR5_TABLE,X
	BCS @NOT_AT_TARGET
	LDA #TRUE
	BRA @RETURN
@NOT_AT_TARGET:
	JSL CALCULATE_DIRECTION_TO_TARGET
	TAX
	STX @LOCAL02
	TXA
	JSL SET_ENTITY_VELOCITY_FROM_DIRECTION
	LDY @LOCAL04
	BNE @SKIP_SPRITE_UPDATE
	LDX @LOCAL02
	TXA
	JSL QUANTIZE_ENTITY_DIRECTION
	TAX
	STX @LOCAL01
	LDA @VIRTUAL04
	BEQ @NO_REVERSE
	TXA
	JSL REVERSE_DIRECTION_8
	TAX
	STX @LOCAL01
@NO_REVERSE:
	LDA @VIRTUAL02
	ASL
	CLC
	ADC #.LOWORD(ENTITY_DIRECTIONS)
	TAY
	LDA __BSS_START__,Y
	STA @LOCAL00
	TXA
	STA __BSS_START__,Y
	LDA @LOCAL00
	JSL MAP_DIRECTION_TO_SPRITE_GROUP
	TAY
	STY @LOCAL04
	LDX @LOCAL01
	TXA
	JSL MAP_DIRECTION_TO_SPRITE_GROUP
	STA @VIRTUAL04
	LDY @LOCAL04
	TYA
	CMP @VIRTUAL04
	BEQ @SKIP_SPRITE_UPDATE
	LDA @VIRTUAL02
	JSL RENDER_ENTITY_SPRITE_ENTRY2
@SKIP_SPRITE_UPDATE:
	LDA #FALSE
@RETURN:
	END_C_FUNCTION
