
NAVIGATE_ENTITY_TO_TARGET:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR6_TABLE,X
	SEC
	SBC ENTITY_ABS_X_TABLE,X
	STA @LOCAL02
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @X_NEGATIVE
	LDA @LOCAL02
	EOR #$FFFF
	INC
	STA @LOCAL01
	BRA @X_ABS_DONE
@X_NEGATIVE:
	LDA @LOCAL02
	STA @LOCAL01
@X_ABS_DONE:
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA @LOCAL01
	CMP ENTITY_SCRIPT_VAR5_TABLE,X
	BCS @NOT_AT_TARGET
	LDA ENTITY_SCRIPT_VAR7_TABLE,X
	SEC
	SBC ENTITY_ABS_Y_TABLE,X
	STA @LOCAL02
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @Y_NEGATIVE
	LDA @LOCAL02
	EOR #$FFFF
	INC
	STA @LOCAL00
	BRA @Y_ABS_DONE
@Y_NEGATIVE:
	LDA @LOCAL02
	STA @LOCAL00
@Y_ABS_DONE:
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA @LOCAL00
	CMP ENTITY_SCRIPT_VAR5_TABLE,X
	BCS @NOT_AT_TARGET
	LDA #TRUE
	BRA @RETURN
@NOT_AT_TARGET:
	JSL GET_DIRECTION_TO_SCRIPT_TARGET
	TAY
	STY @LOCAL01
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	TYA
	CMP ENTITY_DIRECTIONS,X
	BEQ @DIRECTION_UNCHANGED
	TYA
	JSL SET_ENTITY_DIRECTION_VELOCITY
	LDA CURRENT_ENTITY_SLOT
	ASL
	CLC
	ADC #.LOWORD(ENTITY_DIRECTIONS)
	TAX
	LDA __BSS_START__,X
	STA @LOCAL02
	LDY @LOCAL01
	TYA
	STA __BSS_START__,X
	LDA @LOCAL02
	JSL MAP_DIRECTION_TO_SPRITE_GROUP
	TAX
	STX @LOCAL00
	LDY @LOCAL01
	TYA
	JSL MAP_DIRECTION_TO_SPRITE_GROUP
	STA @VIRTUAL02
	LDX @LOCAL00
	TXA
	CMP @VIRTUAL02
	BEQ @DIRECTION_UNCHANGED
	LDA CURRENT_ENTITY_SLOT
	JSL RENDER_ENTITY_SPRITE_ENTRY2
@DIRECTION_UNCHANGED:
	LDA #FALSE
@RETURN:
	END_C_FUNCTION
