
REBUILD_ENTITY_FREE_LIST:
	LDA #$8000
	LDX LAST_ENTITY
	BRA @MARK_LOOP_CHECK
@MARK_ACTIVE:
	LDY ENTITY_NEXT_ENTITY_TABLE,X
	STA ENTITY_NEXT_ENTITY_TABLE,X
	TYX
@MARK_LOOP_CHECK:
	BPL @MARK_ACTIVE
	LDX #$003A
	LDY #$FFFF
@BUILD_FREE_LIST:
	LDA ENTITY_NEXT_ENTITY_TABLE,X
	CMP #$8000
	BNE @SKIP_SLOT
	TYA
	STA ENTITY_NEXT_ENTITY_TABLE,X
	TXY
@SKIP_SLOT:
	DEX
	DEX
	BPL @BUILD_FREE_LIST
	STY LAST_ENTITY
	RTL
