
RENDER_ALL_PRIORITY_SPRITES:
	PHP
	REP #PROC_FLAGS::ACCUM8
	LDA UNUSED_7E2402
	CMP #$0000
	BNE @AFTER_HOOK_P0
	JSR PRIORITY_SPRITE_HOOK
@AFTER_HOOK_P0:
	LDX #$0000
	BRA @CHECK_P0
@LOOP_P0:
	LDA PRIORITY_0_SPRITEMAP_BANKS,X
	STA SPRITEMAP_BANK
	PHX
	LDA PRIORITY_0_SPRITEMAPS,X
	PHA
	LDA PRIORITY_0_SPRITE_Y,X
	TAY
	LDA PRIORITY_0_SPRITE_X,X
	TAX
	PLA
	JSL WRITE_SPRITEMAP_TO_OAM
	PLX
	INX
	INX
@CHECK_P0:
	CPX PRIORITY_0_SPRITE_OFFSET
	BCC @LOOP_P0
	LDA UNUSED_7E2402
	CMP #$0001
	BNE @AFTER_HOOK_P1
	JSR PRIORITY_SPRITE_HOOK
@AFTER_HOOK_P1:
	LDX #$0000
	BRA @CHECK_P1
@LOOP_P1:
	LDA PRIORITY_1_SPRITEMAP_BANKS,X
	STA SPRITEMAP_BANK
	PHX
	LDA PRIORITY_1_SPRITEMAPS,X
	PHA
	LDA PRIORITY_1_SPRITE_Y,X
	TAY
	LDA PRIORITY_1_SPRITE_X,X
	TAX
	PLA
	JSL WRITE_SPRITEMAP_TO_OAM
	PLX
	INX
	INX
@CHECK_P1:
	CPX PRIORITY_1_SPRITE_OFFSET
	BCC @LOOP_P1
	LDA UNUSED_7E2402
	CMP #$0002
	BNE @AFTER_HOOK_P2
	JSR PRIORITY_SPRITE_HOOK
@AFTER_HOOK_P2:
	LDX #$0000
	BRA @CHECK_P2
@LOOP_P2:
	LDA PRIORITY_2_SPRITEMAP_BANKS,X
	STA SPRITEMAP_BANK
	PHX
	LDA PRIORITY_2_SPRITEMAPS,X
	PHA
	LDA PRIORITY_2_SPRITE_Y,X
	TAY
	LDA PRIORITY_2_SPRITE_X,X
	TAX
	PLA
	JSL WRITE_SPRITEMAP_TO_OAM
	PLX
	INX
	INX
@CHECK_P2:
	CPX PRIORITY_2_SPRITE_OFFSET
	BCC @LOOP_P2
	LDA UNUSED_7E2402
	CMP #$0003
	BNE @AFTER_HOOK_P3
	JSR PRIORITY_SPRITE_HOOK
@AFTER_HOOK_P3:
	LDX #$0000
	BRA @CHECK_P3
@LOOP_P3:
	LDA PRIORITY_3_SPRITEMAP_BANKS,X
	STA SPRITEMAP_BANK
	PHX
	LDA PRIORITY_3_SPRITEMAPS,X
	PHA
	LDA PRIORITY_3_SPRITE_Y,X
	TAY
	LDA PRIORITY_3_SPRITE_X,X
	TAX
	PLA
	JSL WRITE_SPRITEMAP_TO_OAM
	PLX
	INX
	INX
@CHECK_P3:
	CPX PRIORITY_3_SPRITE_OFFSET
	BCC @LOOP_P3
	PLP
	RTS
