
RENDER_ENTITY_SPRITE_8DIR:
	LDY SPRITE_UPDATE_ENTITY_OFFSET
	LDA ENTITY_TILE_HEIGHTS,Y
	STA $00
	LDA ENTITY_BYTE_WIDTHS,Y
	STA DMA_COPY_SIZE
	LDA ENTITY_VRAM_ADDRESS,Y
	STA DMA_COPY_VRAM_DEST
	LDA ENTITY_GRAPHICS_PTR_HIGH,Y
	STA $04
	LDA ENTITY_DIRECTIONS,Y
	ASL
	TAX
	LDA f:SPRITE_DIRECTION_MAPPING_8_DIRECTION,X
	ASL
	ASL
	CLC
	ADC ENTITY_GRAPHICS_PTR_LOW,Y
	ADC ENTITY_ANIMATION_FRAME,Y
	STA $02
	LDA [$02]
	AND #$0002
	BNE @COPY_SPRITE_ROWS
	LDA ENTITY_SURFACE_FLAGS,Y
	STA $06
	AND #$0008
	BEQ @COPY_SPRITE_ROWS
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0003
	STA DMA_COPY_MODE
	LDA #.BANKBYTE(BLANK_TILE_DATA)
	STA DMA_COPY_RAM_SRC + 2
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(BLANK_TILE_DATA)
	STA DMA_COPY_RAM_SRC
	JSL PREPARE_VRAM_COPY_ROW_SAFE
	DEC $00
	BEQ @RENDER_DONE
	LDA $06
	AND #$0004
	BEQ @COPY_SPRITE_ROWS
	JSL PREPARE_VRAM_COPY_ROW_SAFE
	DEC $00
	BEQ @RENDER_DONE
@COPY_SPRITE_ROWS:
	LDY SPRITE_UPDATE_ENTITY_OFFSET
	LDA [$02]
	STA ENTITY_CURRENT_DISPLAYED_SPRITES,Y
	AND #$FFFE
	STA DMA_COPY_RAM_SRC
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	STA DMA_COPY_MODE
	LDA ENTITY_GRAPHICS_SPRITE_BANK,Y
	STA DMA_COPY_RAM_SRC + 2
	REP #PROC_FLAGS::ACCUM8
@DMA_ROW_LOOP:
	JSL PREPARE_VRAM_COPY_ROW_SAFE
	DEC $00
	BEQ @RENDER_DONE
	LDA DMA_COPY_RAM_SRC
	CLC
	ADC DMA_COPY_SIZE
	STA DMA_COPY_RAM_SRC
	BRA @DMA_ROW_LOOP
@RENDER_DONE:
	RTS
