
RUN_ENTITY_SCRIPTS_AND_TICK:
	BIT ENTITY_TICK_CALLBACK_HIGH,X
	BVS @RUN_TICK_CALLBACK
	LDY ENTITY_SCRIPT_INDEX_TABLE,X
@NEXT_SCRIPT:
	STY $8A
	STY CURRENT_SCRIPT_OFFSET
	STY CURRENT_SCRIPT_SLOT
	LSR CURRENT_SCRIPT_SLOT
	LDA ENTITY_SCRIPT_NEXT_SCRIPTS,Y
	STA ACTIONSCRIPT_CURRENT_SCRIPT
	JSR EXECUTE_MOVEMENT_SCRIPT
	LDY ACTIONSCRIPT_CURRENT_SCRIPT
	BPL @NEXT_SCRIPT
	LDX $88
@RUN_TICK_CALLBACK:
	LDA ENTITY_TICK_CALLBACK_HIGH,X
	BMI @DONE
	STA CURRENT_ENTITY_TICK_CALLBACK+2
	LDA ENTITY_TICK_CALLBACK_LOW,X
	STA CURRENT_ENTITY_TICK_CALLBACK
	JSL JUMP_TO_LOADED_MOVEMENT_PTR
@DONE:
	RTS
