
SET_CAMERA_FOCUS_BY_SPRITE_ID:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	JSL FIND_ENTITY_BY_SPRITE_ID
	STA CAMERA_FOCUS_ENTITY
	LDA #2
	STA GAME_STATE + game_state::camera_mode
	END_C_FUNCTION
