
SET_ENTITY_DIRECTION_AND_FRAME:
	LDX $88
	LDA ENTITY_SCRIPT_VAR0_TABLE,X
	BNE @USE_8DIR
	JSL MOVEMENT_DATA_READ8
	STY $94
	STA ENTITY_DIRECTIONS,X
	JSL MOVEMENT_DATA_READ8
	STY $94
	STA ENTITY_ANIMATION_FRAME,X
	STA USE_SECOND_SPRITE_FRAME
	TXY
	JSL RENDER_ENTITY_SPRITE_ENTRY4
	RTL
@USE_8DIR:
	LDX $88
	JSL MOVEMENT_DATA_READ8
	STY $94
	STA ENTITY_DIRECTIONS,X
	JSL MOVEMENT_DATA_READ8
	STY $94
	ASL
	STA ENTITY_ANIMATION_FRAME,X
	STX SPRITE_UPDATE_ENTITY_OFFSET
	JSR RENDER_ENTITY_SPRITE_8DIR
	RTL
