
SET_ENTITY_DIRECTION_VELOCITY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STA @LOCAL04
	LDY CURRENT_ENTITY_SLOT
	STY @LOCAL03
	TYA
	ASL
	TAX
	LDA @LOCAL04
	STA ENTITY_MOVING_DIRECTIONS,X
	AND #$0001
	BEQ @CARDINAL_SPEED
	MOVE_INT_CONSTANT $B505, @VIRTUAL0A ;1.0 / sqrt(2.0)
	LDA ENTITY_MOVEMENT_SPEEDS,X
	STORE_INT1632 @VIRTUAL06
	JSL MULT32
	ASR8_INT @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	BRA @DIRECTION_SWITCH
@CARDINAL_SPEED:
	MOVE_INT_CONSTANT $10000, @VIRTUAL0A ;1.0
	LDA ENTITY_MOVEMENT_SPEEDS,X
	STORE_INT1632 @VIRTUAL06
	JSL MULT32
	ASR8_INT @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
@DIRECTION_SWITCH:
	LDA @LOCAL04
	BEQ @DIR_UP
	CMP #1
	BEQ @DIR_UP_RIGHT
	CMP #2
	BEQL @DIR_RIGHT
	CMP #3
	BEQL @DIR_DOWN_RIGHT
	CMP #4
	BEQL @DIR_DOWN
	CMP #5
	BEQL @DIR_DOWN_LEFT
	CMP #6
	BEQL @DIR_LEFT
	CMP #7
	BEQL @DIR_UP_LEFT
	JMP @STORE_VELOCITIES
@DIR_UP:
	MOVE_INT_CONSTANT NULL, @LOCAL01
	MOVE_INT @LOCAL00, @VIRTUAL06
	SEC
	NEGATE_INT_ASSIGN @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	JMP @STORE_VELOCITIES
@DIR_UP_RIGHT:
	MOVE_INT @LOCAL00, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	MOVE_INT @LOCAL00, @VIRTUAL06
	SEC
	NEGATE_INT_ASSIGN @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	JMP @STORE_VELOCITIES
@DIR_RIGHT:
	MOVE_INT @LOCAL00, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	MOVE_INT_CONSTANT NULL, @LOCAL02
	JMP @STORE_VELOCITIES
@DIR_DOWN_RIGHT:
	MOVE_INT @LOCAL00, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	MOVE_INT @LOCAL00, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	JMP @STORE_VELOCITIES
@DIR_DOWN:
	MOVE_INT_CONSTANT NULL, @LOCAL01
	MOVE_INT @LOCAL00, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	JMP @STORE_VELOCITIES
@DIR_DOWN_LEFT:
	MOVE_INT @LOCAL00, @VIRTUAL06
	SEC
	NEGATE_INT_ASSIGN @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	MOVE_INT @LOCAL00, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	BRA @STORE_VELOCITIES
@DIR_LEFT:
	MOVE_INT @LOCAL00, @VIRTUAL06
	SEC
	NEGATE_INT_ASSIGN @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	MOVE_INT_CONSTANT NULL, @LOCAL02
	BRA @STORE_VELOCITIES
@DIR_UP_LEFT:
	MOVE_INT @LOCAL00, @VIRTUAL06
	SEC
	NEGATE_INT_ASSIGN @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	MOVE_INT @VIRTUAL06, @LOCAL02
@STORE_VELOCITIES:
	LDY @LOCAL03
	TYA
	ASL
	TAX
	LDA @LOCAL01 + fixed_point::integer
	STA ENTITY_DELTA_X_TABLE,X
	LDA @LOCAL01 + fixed_point::fraction
	STA ENTITY_DELTA_X_FRACTION_TABLE,X
	LDA @LOCAL02 + fixed_point::integer
	STA ENTITY_DELTA_Y_TABLE,X
	LDA @LOCAL02 + fixed_point::fraction
	STA ENTITY_DELTA_Y_FRACTION_TABLE,X
	END_C_FUNCTION
