
SET_ENTITY_DIRECTION_BY_SPRITE_ID:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @VIRTUAL02
	TAX
	JSL FIND_ENTITY_BY_SPRITE_ID
	STA @LOCAL00
	CMP #.LOWORD(-1)
	BEQ @DONE
	ASL
	CLC
	ADC #.LOWORD(ENTITY_DIRECTIONS)
	TAX
	LDA __BSS_START__,X
	CMP @VIRTUAL02
	BEQ @DONE
	LDA @VIRTUAL02
	STA __BSS_START__,X
	LDA @LOCAL00
	JSL RENDER_ENTITY_SPRITE_ENTRY2
@DONE:
	END_C_FUNCTION
