
SET_ENTITY_DIRECTION_FROM_LEADER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL00
	TXA
	ASL
	PHA
	LDA GAME_STATE+game_state::leader_direction
	ASL
	TAX
	LDA f:DIRECTION_FACING_TABLE,X
	PLX
	STA ENTITY_DIRECTIONS,X
	LDX @LOCAL00
	TXA
	JSL CLEAR_ENTITY_DELTA_MOTION
	LDX @LOCAL00
	TXA
	JSL RENDER_ENTITY_SPRITE_ENTRY2
	END_C_FUNCTION
