
SET_CHARACTER_ENTITY_DIRECTION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @VIRTUAL02
	TAX
	SEP #PROC_FLAGS::ACCUM8
	JSL FIND_ENTITY_FOR_CHARACTER
	.A16
	STA @LOCAL00
	CMP #.LOWORD(-1)
	BEQ @DONE
	ASL
	CLC
	ADC #.LOWORD(ENTITY_DIRECTIONS)
	TAX
	LDA __BSS_START__,X
	CMP @VIRTUAL02
	BEQ @DONE
	LDA @VIRTUAL02
	STA __BSS_START__,X
	LDA @LOCAL00
	JSL UPDATE_ENTITY_SPRITE
@DONE:
	END_C_FUNCTION
