
SETUP_ENTITY_HDMA_WINDOW_CH4:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDY CURRENT_ENTITY_SLOT
	STY @LOCAL03
	TYA
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR0_TABLE,X
	AND #$0001
	BEQ @USE_SECOND_BUFFER
	LDA #0
	STA @LOCAL02
	BRA @BUFFER_SELECTED
@USE_SECOND_BUFFER:
	LDA #$02FE
	STA @LOCAL02
@BUFFER_SELECTED:
	LOADPTR BUFFER, @VIRTUAL06
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL01
	LDA @VIRTUAL06+2
	STA @LOCAL01+2
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR RENDER_ENTITY_HDMA_WINDOW
	LDX @LOCAL01
	LDA @LOCAL01+2
	JSL SETUP_HDMA_CHANNEL4_WH0_ALT
	LDY @LOCAL03
	TYA
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SCRIPT_VAR0_TABLE)
	TAX
	LDA __BSS_START__,X
	INC
	STA __BSS_START__,X
	END_C_FUNCTION
