
UPDATE_ENTITY_ANIMATION:
	LDX $88
	STX SPRITE_UPDATE_ENTITY_OFFSET
	LDA ENTITY_WALKING_STYLES,X
	XBA
	ORA ENTITY_DIRECTIONS,X
	CMP ENTITY_ANIMATION_FINGERPRINTS,X
	BEQ @FINGERPRINT_UNCHANGED
	STA ENTITY_ANIMATION_FINGERPRINTS,X
	JSR RENDER_ENTITY_SPRITE_8DIR
	RTL
@FINGERPRINT_UNCHANGED:
	LDA ENTITY_SCRIPT_VAR7_TABLE,X
	BPL @CHECK_FORCE_STATIC
	AND #$FFFF ^ SPRITE_TABLE_10_FLAGS::WALKING_STYLE_CHANGED
	STA ENTITY_SCRIPT_VAR7_TABLE,X
	BRA @RENDER_SPRITE
@CHECK_FORCE_STATIC:
	AND #$2000
	BEQ @TICK_ANIM_TIMER
	LDA ENTITY_ANIMATION_FRAME,X
	BEQ @CHECK_INTANGIBILITY
	STZ ENTITY_ANIMATION_FRAME,X
	BRA @RENDER_SPRITE
@TICK_ANIM_TIMER:
	LDA BATTLE_SWIRL_COUNTDOWN
	BNE @CHECK_INTANGIBILITY
	DEC ENTITY_SCRIPT_VAR2_TABLE,X
	BMI @TIMER_EXPIRED
	BNE @CHECK_INTANGIBILITY
@TIMER_EXPIRED:
	LDA ENTITY_SCRIPT_VAR3_TABLE,X
	STA ENTITY_SCRIPT_VAR2_TABLE,X
	LDA ENTITY_ANIMATION_FRAME,X
	EOR #$0002
	STA ENTITY_ANIMATION_FRAME,X
	BNE @RENDER_SPRITE
	CPX FOOTSTEP_SOUND_IGNORE_ENTITY
	BNE @RENDER_SPRITE
	LDX FOOTSTEP_SOUND_ID_OVERRIDE
	BNE @USE_FOOTSTEP_SOUND
	LDX FOOTSTEP_SOUND_ID
@USE_FOOTSTEP_SOUND:
	LDA f:FOOTSTEP_SOUND_TABLE,X
	BEQ @RENDER_SPRITE
	LDX DISABLED_TRANSITIONS
	BNE @RENDER_SPRITE
	JSL PLAY_SOUND
@RENDER_SPRITE:
	JSR RENDER_ENTITY_SPRITE_8DIR
@CHECK_INTANGIBILITY:
	LDX $88
	LDA PSI_TELEPORT_DESTINATION
	BNE @DONE
	LDA PLAYER_INTANGIBILITY_FRAMES
	BEQ @DONE
	CMP #$002D
	BCS @FAST_FLICKER
	AND #$0003
	BNE @MAKE_VISIBLE
@FAST_FLICKER:
	AND #$0001
	BNE @MAKE_VISIBLE
	LDA ENTITY_SPRITEMAP_POINTER_HIGH,X
	ORA #$8000
	BRA @STORE_VISIBILITY
@MAKE_VISIBLE:
	LDA ENTITY_SPRITEMAP_POINTER_HIGH,X
	AND #$7FFF
@STORE_VISIBILITY:
	STA ENTITY_SPRITEMAP_POINTER_HIGH,X
@DONE:
	RTL
