
UPDATE_ENTITY_DIRECTION_AND_VELOCITY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL02
	LDA CURRENT_ENTITY_SLOT
	STA @VIRTUAL02
	ASL
	TAX
	LDY ENTITY_SCRIPT_VAR0_TABLE,X
	STY @LOCAL01
	TYA
	JSL SET_ENTITY_VELOCITY_FROM_DIRECTION
	LDY @LOCAL01
	TYA
	JSL QUANTIZE_DIRECTION
	TAY
	STY @LOCAL01
	LDX @LOCAL02
	BEQ @SKIP_REVERSE
	TYA
	JSL REVERSE_DIRECTION_8
	TAY
	STY @LOCAL01
@SKIP_REVERSE:
	LDA @VIRTUAL02
	ASL
	CLC
	ADC #.LOWORD(ENTITY_DIRECTIONS)
	TAX
	LDA __BSS_START__,X
	STA @LOCAL00
	TYA
	STA __BSS_START__,X
	LDA @LOCAL00
	JSL MAP_DIRECTION_TO_SPRITE_GROUP
	TAX
	STX @LOCAL02
	LDY @LOCAL01
	TYA
	JSL MAP_DIRECTION_TO_SPRITE_GROUP
	STA @VIRTUAL04
	LDX @LOCAL02
	TXA
	CMP @VIRTUAL04
	BEQ @DONE
	LDA @VIRTUAL02
	JSL RENDER_ENTITY_SPRITE_ENTRY2
@DONE:
	END_C_FUNCTION
