
UPDATE_FADE_ENTITY_SPRITES:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	MOVE_INT ENTITY_FADE_STATES, @VIRTUAL06
	LDX #0
	STX @LOCAL00
	BRA @ENTITY_LOOP_CHECK
@PROCESS_ENTITY:
	LDY #4
	LDA [@VIRTUAL06],Y
	CMP #1
	BNE @AFTER_FRAME_RESET
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	LDA [@VIRTUAL0A]
	ASL
	TAX
	STZ ENTITY_ANIMATION_FRAME,X
@AFTER_FRAME_RESET:
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	LDA [@VIRTUAL0A]
	JSL RENDER_ENTITY_SPRITE_ENTRY2
	LDA #20
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDX @LOCAL00
	INX
	STX @LOCAL00
@ENTITY_LOOP_CHECK:
	CPX ENTITY_FADE_STATES_LENGTH
	BCC @PROCESS_ENTITY
	END_C_FUNCTION
