
UPDATE_ENTITY_SCREEN_POSITIONS:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	LDX #$0000
@ENTITY_LOOP:
	LDA ENTITY_SCRIPT_TABLE,X
	BMI @NEXT_ENTITY
	LDA ENTITY_ABS_X_TABLE,X
	SEC
	SBC BG1_X_POS
	STA ENTITY_SCREEN_X_TABLE,X
	LDA ENTITY_ABS_Y_TABLE,X
	SEC
	SBC BG1_Y_POS
	STA ENTITY_SCREEN_Y_TABLE,X
@NEXT_ENTITY:
	INX
	INX
	CPX #$003C
	BNE @ENTITY_LOOP
	RTL
