
UPLOAD_ENTITY_SPRITE_TO_VRAM:
	PHA
	TXA
	ASL
	TAX
	LDA ENTITY_TILE_HEIGHTS,X
	STA $00
	LDA #$0000
	STA DMA_COPY_MODE
	LDA ENTITY_BYTE_WIDTHS,X
	STA DMA_COPY_SIZE
	LDA #$007F
	STA DMA_COPY_RAM_SRC + 2
	PLA
	STA DMA_COPY_RAM_SRC
	LDA ENTITY_VRAM_ADDRESS,X
	STA DMA_COPY_VRAM_DEST
@ROW_LOOP:
	JSL PREPARE_VRAM_COPY_ROW_SAFE
	DEC $00
	BEQ @DONE
	LDA DMA_COPY_RAM_SRC
	CLC
	ADC DMA_COPY_SIZE
	STA DMA_COPY_RAM_SRC
	BRA @ROW_LOOP
@DONE:
	RTL
