
WRITE_SPRITEMAP_TO_OAM:
	PHP
	PHD
	PEA __BSS_START__
	PLD
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	STX <CURRENT_SPRITE_BASE_X + 0
	STY <CURRENT_SPRITE_BASE_Y + 0
	TAY
	LDX <OAM_ADDR + 0
	CPX <OAM_END_ADDR + 0
	BCC @START_LOOP
	PLD
	PLP
	RTL
@START_LOOP:
	PHB
	SEP #PROC_FLAGS::ACCUM8
	LDA <SPRITEMAP_BANK + 0
	PHA
	PLB
	BRA @READ_Y_OFFSET
@FOLLOW_LINK:
	LDA a:spritemap::tile,Y
	TAY
	BRA @READ_Y_OFFSET
@NEXT_ENTRY:
	INY
	INY
	INY
	INY
	INY
@READ_Y_OFFSET:
	REP #PROC_FLAGS::ACCUM8
	LDA a:spritemap::y_offset,Y
	AND #$00FF
	CMP #$0080
	BCC @APPLY_Y_OFFSET
	BEQ @FOLLOW_LINK
	ORA #$FF00
	CLC
@APPLY_Y_OFFSET:
	ADC <CURRENT_SPRITE_BASE_Y + 0
	DEC
	CMP #$00E0
	BCC @Y_VISIBLE
	CMP #$FFE0
	BCS @Y_VISIBLE
	SEP #PROC_FLAGS::ACCUM8
@SKIP_ENTRY:
	LDA a:spritemap::special_flags,Y
	BPL @NEXT_ENTRY
	BRA @DONE
@Y_VISIBLE:
	.A16
	STA <CURRENT_SPRITE_Y + 0
	LDA a:spritemap::tile,Y
	STA <oam_entry::starting_tile,X
	LDA a:spritemap::x_offset,Y
	AND #$00FF
	CMP #$0080
	BCC @APPLY_X_OFFSET
	ORA #$FF00
	CLC
@APPLY_X_OFFSET:
	ADC <CURRENT_SPRITE_BASE_X + 0
	SEP #PROC_FLAGS::ACCUM8
	STA <oam_entry::x_coord,X
	XBA
	BEQ @X_VALID
	CMP #$00FF
	BNE @SKIP_ENTRY
@X_VALID:
	ROL
	ROR <OAM_HIGH_TABLE_BUFFER + 0
	LDA a:spritemap::special_flags,Y
	ROR
	ROR <OAM_HIGH_TABLE_BUFFER + 0
	BCC @HIGH_TABLE_FULL
	LDA <OAM_HIGH_TABLE_BUFFER + 0
	STA [<OAM_HIGH_TABLE_ADDR + 0]
	INC <OAM_HIGH_TABLE_ADDR + 0
	LDA #$0080
	STA <OAM_HIGH_TABLE_BUFFER + 0
@HIGH_TABLE_FULL:
	LDA <CURRENT_SPRITE_Y + 0
	STA <oam_entry::y_coord,X
	INX
	INX
	INX
	INX
	LDA a:spritemap::special_flags,Y
	BMI @DONE
	REP #PROC_FLAGS::ACCUM8
	CPX <OAM_END_ADDR + 0
	BCC @NEXT_ENTRY
@DONE:
	STX <OAM_ADDR + 0
	PLB
	PLD
	PLP
	RTL
