
ADVANCE_ENTITY_TOWARD_LEADER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	STA @VIRTUAL02
	JSL CLASSIFY_ENTITY_LEADER_DISTANCE
	CMP #0
	BNE @CALCULATE_MOVEMENT
	LDA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_PATHFINDING_STATES,X
	BEQ @CALCULATE_MOVEMENT
	LDA GAME_STATE+game_state::leader_x_coord
	STA ENTITY_ABS_X_TABLE,X
	LDA GAME_STATE+game_state::leader_y_coord
	STA ENTITY_ABS_Y_TABLE,X
	LDA #.LOWORD(-1)
	BRA @RETURN
@CALCULATE_MOVEMENT:
	JSL CALCULATE_PROSPECTIVE_POSITION
	LDA #4
	STA @LOCAL00
	LDY @VIRTUAL02
	LDX ENTITY_MOVEMENT_PROSPECTIVE_Y
	LDA ENTITY_MOVEMENT_PROSPECTIVE_X
	JSL CHECK_ENTITY_COLLISION
	AND #$00C0
	BEQ @APPLY_MOVEMENT
	LDA @VIRTUAL02
	ASL
	CLC
	ADC #.LOWORD(ENTITY_MOVEMENT_SPEEDS)
	TAX
	LDA __BSS_START__,X
	SEC
	SBC #$1000
	STA __BSS_START__,X
	LDA #0
	BRA @RETURN
@APPLY_MOVEMENT:
	LDA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_MOVEMENT_PROSPECTIVE_X
	STA ENTITY_ABS_X_TABLE,X
	LDA ENTITY_MOVEMENT_PROSPECTIVE_Y
	STA ENTITY_ABS_Y_TABLE,X
	LDA #.LOWORD(-1)
@RETURN:
	END_C_FUNCTION
