
CALCULATE_PATHFINDING_TARGETS:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL04
	STX @LOCAL03
	STA @LOCAL02
	LDX @PARAM03
	STX @VIRTUAL04
	LDA #0
	STA @VIRTUAL02
	BRA @LOOP_CHECK
@PROCESS_PARTY_MEMBER:
	LDA @VIRTUAL02
	ASL
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_entity_slots,X
.ELSE
	TAX
	LDA GAME_STATE + game_state::party_entity_slots,X
.ENDIF
	ASL
	TAY
	LDA ENTITY_SIZES,Y
	STA @LOCAL01
	LDA @VIRTUAL02
	ASL
	ASL
	CLC
	ADC @LOCAL02
	TAX
	STX @LOCAL00
	LDA @LOCAL01
	ASL
	STA @LOCAL01
	TAX
	LDA ENTITY_ABS_X_TABLE,Y
	SEC
	SBC f:ENTITY_COLLISION_X_OFFSET,X
	LSR
	LSR
	LSR
	SEC
	SBC @LOCAL04
	AND #$003F
	LDX @LOCAL00
	STA a:pathfinding::targets + 2,X
	LDA @LOCAL01
	PHA
	TAX
	LDA ENTITY_ABS_Y_TABLE,Y
	SEC
	SBC f:ENTITY_COLLISION_Y_OFFSET,X
	PLX
	CLC
	ADC f:SPRITE_HITBOX_ENABLE_TABLE,X
	LSR
	LSR
	LSR
	SEC
	SBC @VIRTUAL04
	AND #$003F
	LDX @LOCAL00
	STA a:pathfinding::targets,X
	INC @VIRTUAL02
@LOOP_CHECK:
	LDA @VIRTUAL02
	CMP @LOCAL03
	BCC @PROCESS_PARTY_MEMBER
	END_C_FUNCTION
