
ENTITY_PATHFINDING_STEP:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	STA @LOCAL08
	ASL
	TAX
	LDA ENTITY_PATHFINDING_STATES,X
	CMP #.LOWORD(-1)
	BNEL @RETURN
	LDA ENTITY_SIZES,X
	STA @LOCAL07
	LDA ENTITY_PATH_POINTS,X
	STA @VIRTUAL02
	STA @LOCAL06
	LDA ENTITY_ABS_X_TABLE,X
	STA @LOCAL05
	LDA ENTITY_ABS_Y_TABLE,X
	STA @LOCAL04
	LDA @LOCAL07
	ASL
	TAX
	STX @LOCAL03
	LDX @VIRTUAL02
	LDA __BSS_START__+2,X
	ASL
	ASL
	ASL
	LDX @LOCAL03
	CLC
	ADC f:ENTITY_COLLISION_X_OFFSET,X
	STA @VIRTUAL04
	LDA PATHFINDING_TARGET_CENTRE_X
	SEC
	SBC PATHFINDING_TARGET_WIDTH
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL04
	STA @LOCAL02
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	ASL
	ASL
	ASL
	LDX @LOCAL03
	SEC
	SBC f:SPRITE_HITBOX_ENABLE_TABLE,X
	CLC
	ADC f:ENTITY_COLLISION_Y_OFFSET,X
	STA @VIRTUAL02
	LDA PATHFINDING_TARGET_CENTRE_Y
	SEC
	SBC PATHFINDING_TARGET_HEIGHT
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL04
	LDA @LOCAL05
	SEC
	SBC @LOCAL02
	STA @LOCAL01
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @X_DIFF_POSITIVE
	LDA @LOCAL01
	EOR #$FFFF
	INC
	BRA @CHECK_X_THRESHOLD
@X_DIFF_POSITIVE:
	LDA @LOCAL01
@CHECK_X_THRESHOLD:
	STA @VIRTUAL02
	LDA #3
	CLC
	SBC @VIRTUAL02
	JUMPLTEQS @UPDATE_DIRECTION
	LDA @LOCAL04
	SEC
	SBC @VIRTUAL04
	STA @LOCAL01
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @Y_DIFF_POSITIVE
	LDA @LOCAL01
	EOR #$FFFF
	INC
	BRA @CHECK_Y_THRESHOLD
@Y_DIFF_POSITIVE:
	LDA @LOCAL01
@CHECK_Y_THRESHOLD:
	STA @VIRTUAL02
	LDA #3
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @UPDATE_DIRECTION
	LDA @LOCAL08
	ASL
	STA @LOCAL01
	CLC
	ADC #.LOWORD(ENTITY_PATH_POINT_COUNTS)
	TAX
	LDA __BSS_START__,X
	TAY
	DEY
	TYA
	STA __BSS_START__,X
	BEQ @UPDATE_DIRECTION
	LDA @LOCAL06
	STA @VIRTUAL02
	LDX @VIRTUAL02
	INX
	INX
	INX
	INX
	STX @LOCAL03
	PHX
	LDA @LOCAL01
	TAX
	PLA
	STA ENTITY_PATH_POINTS,X
	LDA @LOCAL07
	ASL
	STA @LOCAL07
	PHA
	LDX @LOCAL03
	LDA __BSS_START__+2,X
	ASL
	ASL
	ASL
	PLX
	CLC
	ADC f:ENTITY_COLLISION_X_OFFSET,X
	STA @VIRTUAL02
	LDA PATHFINDING_TARGET_CENTRE_X
	SEC
	SBC PATHFINDING_TARGET_WIDTH
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL02
	STA @LOCAL02
	LDA @LOCAL07
	PHA
	PHA
	LDX @LOCAL03
	LDA __BSS_START__,X
	ASL
	ASL
	ASL
	PLX
	SEC
	SBC f:SPRITE_HITBOX_ENABLE_TABLE,X
	PLX
	CLC
	ADC f:ENTITY_COLLISION_Y_OFFSET,X
	STA @VIRTUAL02
	LDA PATHFINDING_TARGET_CENTRE_Y
	SEC
	SBC PATHFINDING_TARGET_HEIGHT
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL04
@UPDATE_DIRECTION:
	LDA @LOCAL08
	ASL
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA ENTITY_PATH_POINT_COUNTS,X
	BEQ @PATHFINDING_DONE
	LDA @VIRTUAL04
	STA @LOCAL00
	LDY @LOCAL02
	LDX @LOCAL04
	LDA @LOCAL05
	JSL CALCULATE_DIRECTION_FROM_POSITIONS
	JSL SET_ENTITY_VELOCITY_FROM_DIRECTION
	JSL QUANTIZE_ENTITY_DIRECTION
	LDX @VIRTUAL02
	STA ENTITY_DIRECTIONS,X
	BRA @RETURN
@PATHFINDING_DONE:
	LDX @VIRTUAL02
	STZ ENTITY_PATHFINDING_STATES,X
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(ENTITY_OBSTACLE_FLAGS)
	TAX
	LDA __BSS_START__,X
	ORA #$0080
	STA __BSS_START__,X
@RETURN:
	PLD
	RTL
