
INITIALIZE_PATHFINDER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT32
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @VIRTUAL04
	STX @VIRTUAL02
	STA @LOCAL12
	LDA @PARAM0B
	STA @LOCAL11
	LDY @PARAM0A
	STY @LOCAL10
	LDA @PARAM09
	STA @LOCAL0F
	LDA @PARAM08
	STA @LOCAL0E
	LDX @PARAM07
	STX @LOCAL0D
	LDA @PARAM06
	STA @LOCAL0C
	LDA @PARAM05
	STA @LOCAL0B
	LDX @PARAM04
	STX @LOCAL0A
	MOVE_INT @PARAM03, @VIRTUAL06
	STZ @LOCAL09
	LDA @VIRTUAL02
	STA PATH_HEAP_START
	LDA @VIRTUAL02
	STA PATH_HEAP_CURRENT
	LDA @VIRTUAL02
	CLC
	ADC @LOCAL12
	STA PATH_HEAP_END
	LDX @VIRTUAL04
	LDA __BSS_START__,X
	STA PATH_MATRIX_ROWS
	LDX @VIRTUAL04
	LDY __BSS_START__+2,X
	STY PATH_MATRIX_COLUMNS
	LDX @LOCAL0A
	STX PATH_MATRIX_BORDER
	JSL MULT16
	STA PATH_MATRIX_SIZE
	MOVE_INT @VIRTUAL06, PATH_MATRIX_BUFFER
	LDA @LOCAL11
	ASL
	STA @VIRTUAL02
	INC
	INC
	JSR PATH_HEAP_ALLOC
	STA @LOCAL08
	STA PATH_SEARCH_TEMP_START
	CLC
	ADC @VIRTUAL02
	STA PATH_SEARCH_TEMP_END
	LDA @LOCAL08
	STA PATH_SEARCH_TEMP_B
	STA PATH_SEARCH_TEMP_A
	LDA PATH_MATRIX_COLUMNS
	EOR #$FFFF
	INC
	STA PATH_CARDINAL_OFFSET
	LDA #1
	STA PATH_CARDINAL_OFFSET+2
	LDA PATH_MATRIX_COLUMNS
	STA PATH_CARDINAL_OFFSET+4
	LDA #.LOWORD(-1)
	STA PATH_CARDINAL_OFFSET+6
	STA PATH_CARDINAL_INDEX + .SIZEOF(pathfinder_coords) * 0 + pathfinder_coords::y_coord
	STZ PATH_CARDINAL_INDEX + .SIZEOF(pathfinder_coords) * 0 + pathfinder_coords::x_coord
	STZ PATH_CARDINAL_INDEX + .SIZEOF(pathfinder_coords) * 1 + pathfinder_coords::y_coord
	LDA #1
	STA PATH_CARDINAL_INDEX + .SIZEOF(pathfinder_coords) * 1 + pathfinder_coords::x_coord
	STA PATH_CARDINAL_INDEX + .SIZEOF(pathfinder_coords) * 2 + pathfinder_coords::y_coord
	STZ PATH_CARDINAL_INDEX + .SIZEOF(pathfinder_coords) * 2 + pathfinder_coords::x_coord
	STZ PATH_CARDINAL_INDEX + .SIZEOF(pathfinder_coords) * 3 + pathfinder_coords::y_coord
	LDA #.LOWORD(-1)
	STA PATH_CARDINAL_INDEX + .SIZEOF(pathfinder_coords) * 3 + pathfinder_coords::x_coord
	STA PATH_DIAGONAL_INDEX + .SIZEOF(pathfinder_coords) * 0 + pathfinder_coords::y_coord
	LDA #1
	STA PATH_DIAGONAL_INDEX + .SIZEOF(pathfinder_coords) * 0 + pathfinder_coords::x_coord
	STA PATH_DIAGONAL_INDEX + .SIZEOF(pathfinder_coords) * 1 + pathfinder_coords::y_coord
	STA PATH_DIAGONAL_INDEX + .SIZEOF(pathfinder_coords) * 1 + pathfinder_coords::x_coord
	STA PATH_DIAGONAL_INDEX + .SIZEOF(pathfinder_coords) * 2 + pathfinder_coords::y_coord
	LDA #.LOWORD(-1)
	STA PATH_DIAGONAL_INDEX + .SIZEOF(pathfinder_coords) * 2 + pathfinder_coords::x_coord
	STA PATH_DIAGONAL_INDEX + .SIZEOF(pathfinder_coords) * 3 + pathfinder_coords::y_coord
	STA PATH_DIAGONAL_INDEX + .SIZEOF(pathfinder_coords) * 3 + pathfinder_coords::x_coord
	LDA @LOCAL10
	CMP #251
	BCC @CLAMP_DONE
	LDA #251
	STA @LOCAL10
@CLAMP_DONE:
	LDA @LOCAL0D
	ASL
	JSR PATH_HEAP_ALLOC
	STA @LOCAL07
	LDY @LOCAL07
	LDX @LOCAL0E
	LDA @LOCAL0D
	JSR SORT_PATH_NODES
	LDA @LOCAL10
	ASL
	ASL
	JSR PATH_HEAP_ALLOC
	STA @LOCAL0E
	JSR INIT_PATH_MATRIX_BORDERS
	STZ @LOCAL06
	STZ @LOCAL05
	LDA #0
	STA @VIRTUAL04
	JMP @NODE_LOOP_CHECK
@NODE_LOOP_BODY:
	LDA @VIRTUAL04
	ASL
	TAY
	LDA (@LOCAL07),Y
	STA @VIRTUAL02
	STA @LOCAL12
	LDX @VIRTUAL02
	LDA __BSS_START__+2,X
	CMP @LOCAL06
	BNE @NEW_POSITION
	LDX @VIRTUAL02
	LDA __BSS_START__+4,X
	CMP @LOCAL05
	BEQ @TRACE_ROUTE
@NEW_POSITION:
	LDY #1
	STY @LOCAL04
	LDX @VIRTUAL02
	LDA __BSS_START__+2,X
	STA @LOCAL06
	LDX @VIRTUAL02
	LDA __BSS_START__+4,X
	STA @LOCAL05
	LDA @VIRTUAL04
	INC
	STA @LOCAL08
	BRA @GROUP_COUNT_CHECK
@GROUP_COUNT_BODY:
	ASL
	TAY
	LDA (@LOCAL07),Y
	TAX
	LDA __BSS_START__+2,X
	CMP @LOCAL06
	BNE @GROUP_COUNT_DONE
	LDA __BSS_START__+4,X
	CMP @LOCAL05
	BNE @GROUP_COUNT_DONE
	LDY @LOCAL04
	INY
	STY @LOCAL04
	LDA @LOCAL08
	INC
	STA @LOCAL08
@GROUP_COUNT_CHECK:
	CMP @LOCAL0D
	BCC @GROUP_COUNT_BODY
@GROUP_COUNT_DONE:
	LDA @VIRTUAL04
	ASL
	CLC
	ADC @LOCAL07
	TAX
	LDY @LOCAL04
	TYA
	JSR POPULATE_PATH_MATRIX
	LDY @LOCAL04
	STY @LOCAL00
	LDA @LOCAL10
	STA @LOCAL01
	LDA @LOCAL0F
	STA @LOCAL02
	LDY @VIRTUAL02
	LDX @LOCAL0C
	LDA @LOCAL0B
	JSR PATH_BFS_SEARCH
@TRACE_ROUTE:
	LDY @LOCAL0E
	LDX @LOCAL10
	LDA @VIRTUAL02
	CLC
	ADC #6
	JSR TRACE_PATH_ROUTE
	LDX @VIRTUAL02
	STA __BSS_START__+14,X
	LDX @LOCAL0E
	JSR COMPRESS_PATH_WAYPOINTS
	STA @LOCAL03
	ASL
	ASL
	JSR PATH_HEAP_ALLOC
	STA @LOCAL0A
	STZ @LOCAL08
	BRA @COPY_WAYPOINTS_CHECK
@COPY_WAYPOINTS_BODY:
	LDA @LOCAL08
	ASL
	ASL
	TAX
	STX @VIRTUAL02
	LDA @LOCAL0A
	CLC
	ADC @VIRTUAL02
	TAY
	TXA
	CLC
	ADC @LOCAL0E
	TAX
	MOVE_INT_XPTRSRC_YPTRDEST __BSS_START__, __BSS_START__
	INC @LOCAL08
@COPY_WAYPOINTS_CHECK:
	LDA @LOCAL08
	CMP @LOCAL03
	BCC @COPY_WAYPOINTS_BODY
	LDA @LOCAL03
	LDX @LOCAL12
	STX @VIRTUAL02
	STA __BSS_START__+10,X
	LDA @LOCAL0A
	LDX @VIRTUAL02
	STA __BSS_START__+12,X
	LDA @LOCAL03
	BEQ @NO_WAYPOINTS
	INC @LOCAL09
@NO_WAYPOINTS:
	INC @VIRTUAL04
@NODE_LOOP_CHECK:
	LDA @VIRTUAL04
	CMP @LOCAL0D
	BCCL @NODE_LOOP_BODY
	LDA @LOCAL09
	END_C_FUNCTION
