
PATH_BFS_SEARCH:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL0B
	STX @VIRTUAL04
	STA @VIRTUAL02
	STA @LOCAL0A
	LDY @PARAM05
	STY @LOCAL09
	LDA @PARAM04
	STA @LOCAL08
	LDX @PARAM03
	STX @LOCAL07
	LDY #2
	LDA (@LOCAL0B),Y
	STA @LOCAL06
	LDY #4
	LDA (@LOCAL0B),Y
	STA @LOCAL05
	STZ @LOCAL04
	STZ @LOCAL03
	LDX PATH_SEARCH_TEMP_START
	STX PATH_SEARCH_TEMP_B
	STX PATH_SEARCH_TEMP_A
	LDA #0
	STA @LOCAL02
	BRA @ENQUEUE_INIT_CHECK
@ENQUEUE_INIT_BODY:
	ASL
	ASL
	STA @VIRTUAL02
	LDA @VIRTUAL04
	CLC
	ADC @VIRTUAL02
	TAX
	LDY PATH_MATRIX_COLUMNS
	LDA __BSS_START__,X
	JSL MULT16
	CLC
	ADC __BSS_START__+2,X
	LDX PATH_SEARCH_TEMP_B
	STA __BSS_START__,X
	LDA PATH_SEARCH_TEMP_B
	CMP PATH_SEARCH_TEMP_END
	BNE @ENQUEUE_INIT_WRAP
	LDX PATH_SEARCH_TEMP_START
	BRA @ENQUEUE_INIT_ADVANCE
@ENQUEUE_INIT_WRAP:
	LDX PATH_SEARCH_TEMP_B
	INX
	INX
@ENQUEUE_INIT_ADVANCE:
	STX PATH_SEARCH_TEMP_B
	LDA @LOCAL02
	INC
	STA @LOCAL02
@ENQUEUE_INIT_CHECK:
	LDX @LOCAL0A
	STX @VIRTUAL02
	CMP @VIRTUAL02
	BCC @ENQUEUE_INIT_BODY
	JMP @QUEUE_NOT_EMPTY_CHECK
@DEQUEUE_NODE:
	LDX PATH_SEARCH_TEMP_A
	LDA __BSS_START__,X
	STA @VIRTUAL02
	LDA PATH_SEARCH_TEMP_A
	CMP PATH_SEARCH_TEMP_END
	BNE @DEQUEUE_WRAP
	LDX PATH_SEARCH_TEMP_START
	BRA @DEQUEUE_ADVANCE
@DEQUEUE_WRAP:
	LDX PATH_SEARCH_TEMP_A
	INX
	INX
@DEQUEUE_ADVANCE:
	STX PATH_SEARCH_TEMP_A
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	STA @VIRTUAL00
	CMP #<-2
	BCCL @QUEUE_NOT_EMPTY_CHECK
	LDY #1
	LDX @VIRTUAL02
	REP #PROC_FLAGS::ACCUM8
	LDA #0
	STA @LOCAL02
	BRA @WALL_CHECK_ROW_COND
@WALL_CHECK_ROW_BODY:
	LDA #0
	STA @VIRTUAL04
	BRA @WALL_CHECK_COL_COND
@WALL_CHECK_COL_BODY:
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	TXA
	CLC
	ADC @VIRTUAL04
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	CMP #<-3
	BNE @WALL_CHECK_COL_NEXT
	LDY #0
	BRA @WALL_CHECK_DONE
@WALL_CHECK_COL_NEXT:
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL04
@WALL_CHECK_COL_COND:
	LDA @VIRTUAL04
	CMP @LOCAL05
	BCC @WALL_CHECK_COL_BODY
	TXA
	CLC
	ADC PATH_MATRIX_COLUMNS
	TAX
	LDA @LOCAL02
	INC
	STA @LOCAL02
@WALL_CHECK_ROW_COND:
	CMP @LOCAL06
	BCC @WALL_CHECK_ROW_BODY
@WALL_CHECK_DONE:
	CPY #0
	BNE @NODE_NOT_WALLED
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA #<-4
	STA [@VIRTUAL06]
	JMP @QUEUE_NOT_EMPTY_CHECK
@NODE_NOT_WALLED:
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	CMP #<-1
	BNE @MARK_VISITED
	REP #PROC_FLAGS::ACCUM8
	INC @LOCAL04
	LDA (@LOCAL0B)
	CMP #1
	BNE @MARK_VISITED
	LDY PATH_MATRIX_COLUMNS
	LDA @VIRTUAL02
	JSL DIVISION16S_DIVISOR_POSITIVE
	LDY #6
	STA (@LOCAL0B),Y
	LDY PATH_MATRIX_COLUMNS
	LDA @VIRTUAL02
	JSL MODULUS16
	LDY #8
	STA (@LOCAL0B),Y
@MARK_VISITED:
	SEP #PROC_FLAGS::ACCUM8
	LDA #<-4
	STA @VIRTUAL00
	LDX #0
	STX @LOCAL01
	JMP @NEIGHBOR_LOOP_COND
@EXPAND_NEIGHBOR:
	REP #PROC_FLAGS::ACCUM8
	TXA
	ASL
	TAX
	LDA @VIRTUAL02
	CLC
	ADC PATH_CARDINAL_OFFSET,X
	STA @LOCAL02
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @LOCAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	STA @VIRTUAL01
	CMP #<-2
	BCC @TRACK_MIN_COST
	REP #PROC_FLAGS::ACCUM8
	LDA PATH_SEARCH_TEMP_A
	CMP PATH_SEARCH_TEMP_START
	BNE @QUEUE_FULL_CHECK_ALT
	LDY #0
	LDA PATH_SEARCH_TEMP_B
	CMP PATH_SEARCH_TEMP_END
	BNE @QUEUE_FULL_RESULT
	LDY #1
	BRA @QUEUE_FULL_RESULT
@QUEUE_FULL_CHECK_ALT:
	LDY #0
	LDA PATH_SEARCH_TEMP_B
	INC
	INC
	CMP PATH_SEARCH_TEMP_A
	BNE @QUEUE_FULL_RESULT
	LDY #1
@QUEUE_FULL_RESULT:
	CPY #0
	BNE @NEXT_NEIGHBOR
	LDA @LOCAL02
	LDX PATH_SEARCH_TEMP_B
	STA __BSS_START__,X
	LDA PATH_SEARCH_TEMP_B
	CMP PATH_SEARCH_TEMP_END
	BNE @ENQUEUE_WRAP
	LDY PATH_SEARCH_TEMP_START
	BRA @ENQUEUE_ADVANCE
@ENQUEUE_WRAP:
	LDY PATH_SEARCH_TEMP_B
	INY
	INY
@ENQUEUE_ADVANCE:
	STY PATH_SEARCH_TEMP_B
	BRA @NEXT_NEIGHBOR
@TRACK_MIN_COST:
	LDA @VIRTUAL00
	CMP @VIRTUAL01
	BLTEQ @NEXT_NEIGHBOR
	LDA @VIRTUAL01
	STA @VIRTUAL00
@NEXT_NEIGHBOR:
	LDX @LOCAL01
	INX
	STX @LOCAL01
@NEIGHBOR_LOOP_COND:
	CPX #4
	BCCL @EXPAND_NEIGHBOR
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	AND #$00FF
	CMP #<-4
	BNE @SET_NODE_COST
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA [@VIRTUAL06]
	BRA @NODE_DONE
@SET_NODE_COST:
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	INC
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	CMP @LOCAL08
	BNE @NODE_DONE
	LDA #0
	STA @LOCAL02
	BRA @BLOCK_NEIGHBORS_COND
@BLOCK_NEIGHBOR_BODY:
	ASL
	TAX
	LDA @VIRTUAL02
	CLC
	ADC PATH_CARDINAL_OFFSET,X
	TAX
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	TXA
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	CMP #<-2
	BCC @BLOCK_NEIGHBOR_SKIP
	LDA #<-4
	STA [@VIRTUAL06]
@BLOCK_NEIGHBOR_SKIP:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL02
	INC
	STA @LOCAL02
@BLOCK_NEIGHBORS_COND:
	CMP #4
	BCC @BLOCK_NEIGHBOR_BODY
@NODE_DONE:
	REP #PROC_FLAGS::ACCUM8
	INC @LOCAL03
	LDA @LOCAL09
	CMP @LOCAL03
	BLTEQ @DONE
	LDA @LOCAL04
	CMP @LOCAL07
	BEQ @DONE
@QUEUE_NOT_EMPTY_CHECK:
	REP #PROC_FLAGS::ACCUM8
	LDA PATH_SEARCH_TEMP_A
	CMP PATH_SEARCH_TEMP_B
	BNEL @DEQUEUE_NODE
@DONE:
	END_C_FUNCTION
