
PATH_BFS_SEARCH:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL0C
	STX @VIRTUAL04
	STA @VIRTUAL02
	STA @LOCAL0B
	LDY @PARAM05
	STY @LOCAL0A
	LDA @PARAM04
	STA @LOCAL09
	LDX @PARAM03
	STX @LOCAL08
	LDY #2
	LDA (@LOCAL0C),Y
	STA @LOCAL07
	LDY #4
	LDA (@LOCAL0C),Y
	STA @LOCAL06
	STZ @LOCAL05
	STZ @LOCAL04
	LDX PATH_SEARCH_TEMP_START
	STX PATH_SEARCH_TEMP_B
	STX PATH_SEARCH_TEMP_A
	LDA #0
	STA @LOCAL03
	BRA @START_ENQUEUE_CHECK
@ENQUEUE_START_NODE:
	ASL
	ASL
	STA @VIRTUAL02
	LDA @VIRTUAL04
	CLC
	ADC @VIRTUAL02
	TAX
	LDY PATH_MATRIX_COLUMNS
	LDA __BSS_START__,X
	JSL MULT16
	CLC
	ADC __BSS_START__+2,X
	LDX PATH_SEARCH_TEMP_B
	STA __BSS_START__,X
	LDA PATH_SEARCH_TEMP_B
	CMP PATH_SEARCH_TEMP_END
	BNE @ADVANCE_QUEUE_TAIL
	LDX PATH_SEARCH_TEMP_START
	BRA @AFTER_QUEUE_TAIL_UPDATE
@ADVANCE_QUEUE_TAIL:
	LDX PATH_SEARCH_TEMP_B
	INX
	INX
@AFTER_QUEUE_TAIL_UPDATE:
	STX PATH_SEARCH_TEMP_B
	LDA @LOCAL03
	INC
	STA @LOCAL03
@START_ENQUEUE_CHECK:
	LDX @LOCAL0B
	STX @VIRTUAL02
	CMP @VIRTUAL02
	BCC @ENQUEUE_START_NODE
	JMP @BFS_CONTINUE_CHECK
@DEQUEUE_NODE:
	LDX PATH_SEARCH_TEMP_A
	LDA __BSS_START__,X
	STA @VIRTUAL04
	LDA PATH_SEARCH_TEMP_A
	CMP PATH_SEARCH_TEMP_END
	BNE @ADVANCE_QUEUE_HEAD
	LDX PATH_SEARCH_TEMP_START
	BRA @AFTER_QUEUE_HEAD_UPDATE
@ADVANCE_QUEUE_HEAD:
	LDX PATH_SEARCH_TEMP_A
	INX
	INX
@AFTER_QUEUE_HEAD_UPDATE:
	STX PATH_SEARCH_TEMP_A
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @VIRTUAL04
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	STA @VIRTUAL00
	CMP #<-2
	BCCL @BFS_CONTINUE_CHECK
	REP #PROC_FLAGS::ACCUM8
	LDA #1
	STA @VIRTUAL02
	STA @LOCAL02
	LDY @VIRTUAL04
	LDX #0
	BRA @ROW_LOOP_CHECK
@CHECK_ROW:
	LDA #0
	STA @LOCAL01
	BRA @COLUMN_LOOP_CHECK
@CHECK_COLUMN:
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @LOCAL01
	STA @VIRTUAL02
	TYA
	CLC
	ADC @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	CMP #<-3
	BNE @NEXT_COLUMN
	REP #PROC_FLAGS::ACCUM8
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL02
	BRA @AFTER_OBSTACLE_CHECK
@NEXT_COLUMN:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	INC
	STA @LOCAL01
@COLUMN_LOOP_CHECK:
	CMP @LOCAL06
	BCC @CHECK_COLUMN
	TYA
	CLC
	ADC PATH_MATRIX_COLUMNS
	TAY
	INX
@ROW_LOOP_CHECK:
	CPX @LOCAL07
	BCC @CHECK_ROW
@AFTER_OBSTACLE_CHECK:
	LDA @LOCAL02
	STA @VIRTUAL02
	BNE @NO_OBSTACLE
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @VIRTUAL04
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA #<-4
	STA [@VIRTUAL06]
	JMP @BFS_CONTINUE_CHECK
@NO_OBSTACLE:
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	CMP #<-1
	BNE @AFTER_DESTINATION_CHECK
	REP #PROC_FLAGS::ACCUM8
	INC @LOCAL05
	LDA (@LOCAL0C)
	CMP #1
	BNE @AFTER_DESTINATION_CHECK
	LDY PATH_MATRIX_COLUMNS
	LDA @VIRTUAL04
	JSL DIVISION16S_DIVISOR_POSITIVE
	LDY #6
	STA (@LOCAL0C),Y
	LDY PATH_MATRIX_COLUMNS
	LDA @VIRTUAL04
	JSL MODULUS16
	LDY #8
	STA (@LOCAL0C),Y
@AFTER_DESTINATION_CHECK:
	SEP #PROC_FLAGS::ACCUM8
	LDA #<-4
	STA @VIRTUAL00
	LDX #0
	STX @LOCAL03
	BRA @DIRECTION_LOOP_CHECK
@PROCESS_NEIGHBOR:
	REP #PROC_FLAGS::ACCUM8
	TXA
	ASL
	TAX
	LDA @VIRTUAL04
	CLC
	ADC PATH_CARDINAL_OFFSET,X
	STA @LOCAL01
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @LOCAL01
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	STA @VIRTUAL01
	CMP #<-2
	BCC @CHECK_LOWER_COST
	REP #PROC_FLAGS::ACCUM8
	LDA PATH_SEARCH_TEMP_A
	CMP PATH_SEARCH_TEMP_START
	BNE @CHECK_QUEUE_FULL_ALT
	LDA PATH_SEARCH_TEMP_B
	CMP PATH_SEARCH_TEMP_END
	BEQ @NEXT_DIRECTION
	BRA @ENQUEUE_NEIGHBOR
@CHECK_QUEUE_FULL_ALT:
	LDA PATH_SEARCH_TEMP_B
	INC
	INC
	CMP PATH_SEARCH_TEMP_A
	BEQ @NEXT_DIRECTION
@ENQUEUE_NEIGHBOR:
	LDA @LOCAL01
	LDX PATH_SEARCH_TEMP_B
	STA __BSS_START__,X
	LDA PATH_SEARCH_TEMP_B
	CMP PATH_SEARCH_TEMP_END
	BNE @ADVANCE_ENQUEUE_TAIL
	LDY PATH_SEARCH_TEMP_START
	BRA @AFTER_ENQUEUE_TAIL
@ADVANCE_ENQUEUE_TAIL:
	LDY PATH_SEARCH_TEMP_B
	INY
	INY
@AFTER_ENQUEUE_TAIL:
	STY PATH_SEARCH_TEMP_B
	BRA @NEXT_DIRECTION
@CHECK_LOWER_COST:
	LDA @VIRTUAL00
	CMP @VIRTUAL01
	BLTEQ @NEXT_DIRECTION
	LDA @VIRTUAL01
	STA @VIRTUAL00
@NEXT_DIRECTION:
	LDX @LOCAL03
	INX
	STX @LOCAL03
@DIRECTION_LOOP_CHECK:
	CPX #4
	BCCL @PROCESS_NEIGHBOR
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	AND #$00FF
	CMP #<-4
	BNE @AT_MAX_DEPTH
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @VIRTUAL04
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA [@VIRTUAL06]
	BRA @AFTER_CELL_PROCESSING
@AT_MAX_DEPTH:
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	INC
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	LDA @VIRTUAL04
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	STA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	CMP @LOCAL09
	BNE @AFTER_CELL_PROCESSING
	LDA #0
	STA @LOCAL01
	BRA @MARK_NEIGHBOR_LOOP_CHECK
@MARK_BLOCKED_NEIGHBOR:
	ASL
	TAX
	LDA @VIRTUAL04
	CLC
	ADC PATH_CARDINAL_OFFSET,X
	TAX
	MOVE_INT PATH_MATRIX_BUFFER, @VIRTUAL06
	TXA
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	CMP #<-2
	BCC @AFTER_MARK_NEIGHBOR
	LDA #<-4
	STA [@VIRTUAL06]
@AFTER_MARK_NEIGHBOR:
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	INC
	STA @LOCAL01
@MARK_NEIGHBOR_LOOP_CHECK:
	CMP #4
	BCC @MARK_BLOCKED_NEIGHBOR
@AFTER_CELL_PROCESSING:
	REP #PROC_FLAGS::ACCUM8
	INC @LOCAL04
	LDA @LOCAL0A
	CMP @LOCAL04
	BLTEQ @RETURN
	LDA @LOCAL05
	CMP @LOCAL08
	BEQ @RETURN
@BFS_CONTINUE_CHECK:
	REP #PROC_FLAGS::ACCUM8
	LDA PATH_SEARCH_TEMP_A
	CMP PATH_SEARCH_TEMP_B
	BNEL @DEQUEUE_NODE
@RETURN:
	END_C_FUNCTION
