
RESET_ENTITY_PATHFINDING:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA CURRENT_ENTITY_SLOT
	ASL
	CLC
	ADC #.LOWORD(ENTITY_PATHFINDING_STATES)
	TAX
	LDA __BSS_START__,X
	BEQ @ALREADY_RESET
	LDA #$0001
	STA __BSS_START__,X
@ALREADY_RESET:
	RTL
