
STEER_ENTITY_TOWARD_DIRECTION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STA @LOCAL01
	LDA CURRENT_ENTITY_SLOT
	STA @LOCAL00
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR4_TABLE,X
	STA @VIRTUAL02
	STA @VIRTUAL04
	LDA @LOCAL01
	CMP @VIRTUAL02
	BEQ @APPLY_DIRECTION
	CMP @VIRTUAL02
	BLTEQ @TARGET_LESS_THAN_CURRENT
	SEC
	SBC @VIRTUAL02
	CMP #$8000
	BCS @TURN_COUNTER_CLOCKWISE
	LDX #0
	BRA @APPLY_TURN
@TURN_COUNTER_CLOCKWISE:
	LDX #.LOWORD(-1)
	BRA @APPLY_TURN
@TARGET_LESS_THAN_CURRENT:
	STA @VIRTUAL04
	LDA @VIRTUAL02
	SEC
	SBC @VIRTUAL04
	CMP #$8000
	BCS @TURN_CLOCKWISE
	LDX #.LOWORD(-1)
	BRA @APPLY_TURN
@TURN_CLOCKWISE:
	LDX #0
@APPLY_TURN:
	BNE @DECREMENT_DIRECTION
	LDA @VIRTUAL02
	CLC
	ADC #$0800
	STA @VIRTUAL04
	BRA @APPLY_DIRECTION
@DECREMENT_DIRECTION:
	LDA @VIRTUAL02
	SEC
	SBC #$0800
	STA @VIRTUAL04
@APPLY_DIRECTION:
	LDA @LOCAL00
	ASL
	TAX
	CLC
	ADC #.LOWORD(ENTITY_MOVEMENT_SPEEDS)
	TAY
	LDA __BSS_START__,Y
	CMP ENTITY_SCRIPT_VAR3_TABLE,X
	BCS @SPEED_REACHED
	CLC
	ADC #16
	STA __BSS_START__,Y
@SPEED_REACHED:
	LDA @VIRTUAL02
	JSL QUANTIZE_ENTITY_DIRECTION
	TAX
	STX @LOCAL01
	LDA @VIRTUAL04
	JSL QUANTIZE_ENTITY_DIRECTION
	STA @VIRTUAL02
	LDX @LOCAL01
	TXA
	CMP @VIRTUAL02
	BEQ @SKIP_SPRITE_UPDATE
	LDA @LOCAL00
	JSL RENDER_ENTITY_SPRITE_ENTRY2
@SKIP_SPRITE_UPDATE:
	LDA @VIRTUAL04
	END_C_FUNCTION
