
RESOLVE_MAP_SECTOR_MUSIC:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL01
	LDA DISABLE_MUSIC_CHANGES
	BNEL @RETURN
	LDA @LOCAL01
	XBA
	AND #$00FF
	STA @VIRTUAL02
	LDY #MAP_WIDTH_TILES
	TXA
	JSL DIVISION16S_DIVISOR_POSITIVE
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL02
	TAX
	LDA f:MAP_DATA_PER_SECTOR_MUSIC,X
	AND #$00FF
	STA @LOCAL01
	LOADPTR DOOR_DATA & $FF0000, @VIRTUAL0A
	LDA @LOCAL01
	ASL
	TAX
	LDA f:OVERWORLD_EVENT_MUSIC_PTR_TABLE,X
	AND #$7FFF
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
@WALK_ENTRIES:
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	LDA [@VIRTUAL06]
	BEQ @ENTRY_FOUND
	AND #$7FFF
	JSL GET_EVENT_FLAG
	STA @LOCAL00
	LDX #0
	LDA [@VIRTUAL06]
	CMP #$8000
	BLTEQ @CHECK_EXPECTED_STATE
	LDX #1
@CHECK_EXPECTED_STATE:
	STX @VIRTUAL02
	LDA @LOCAL00
	CMP @VIRTUAL02
	BEQ @ENTRY_FOUND
	LDA #4
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	BRA @WALK_ENTRIES
@ENTRY_FOUND:
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, LOADED_MAP_MUSIC_ENTRY
	SEP #PROC_FLAGS::ACCUM8
	LDY #2
	LDA [@VIRTUAL0A],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
	STX NEXT_MAP_MUSIC_TRACK
	LDA DO_MAP_MUSIC_FADE
	BNE @RETURN
	CPX CURRENT_MAP_MUSIC_TRACK
	BEQ @RETURN
	LDA #2
	JSL WRITE_APU_PORT1
@RETURN:
	END_C_FUNCTION
