
STOP_MUSIC:
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0000
	STA f:APUIO0
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
@WAIT_APU_READY:
	JSL READ_APU_IO0
	CMP #$0000
	BNE @WAIT_APU_READY
	LDA #$FFFF
	STA CURRENT_MUSIC_TRACK
	RTL
