
CHECK_ENTITY_OBSTACLE_FLAGS:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL01
	JSL CALCULATE_PROSPECTIVE_POSITION
	TAX
	BNE @HAS_POSITION
	LDA #$FF00
	BRA @RETURN
@HAS_POSITION:
	LDA @LOCAL01
	ASL
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA ENTITY_DIRECTIONS,X
	STA @LOCAL00
	LDA @LOCAL01
	TAY
	LDX ENTITY_MOVEMENT_PROSPECTIVE_Y
	LDA ENTITY_MOVEMENT_PROSPECTIVE_X
	JSL CHECK_ENTITY_COLLISION
	AND #$00D0
	LDX @VIRTUAL02
	STA ENTITY_OBSTACLE_FLAGS,X
@RETURN:
	END_C_FUNCTION
