
CHECK_DIRECTIONAL_COLLISION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @VIRTUAL04
	TAY
	LDX @PARAM03
	STX @LOCAL03
	STZ NOT_MOVING_IN_SAME_DIRECTION_FACED
	STZ SET_TEMP_ENTITY_SURFACE_FLAGS
	STZ TEMP_ENTITY_SURFACE_FLAGS
	LDA @LOCAL03
	STA FINAL_MOVEMENT_DIRECTION
	LDA @LOCAL03
	STA UNREAD_7E5DA2
	STY CHECKED_COLLISION_LEFT_X
	LDA @VIRTUAL04
	STA CHECKED_COLLISION_TOP_Y
	LDA @LOCAL03
	BEQ @CHECK_NORTH
	CMP #4
	BEQL @CHECK_SOUTH
	CMP #6
	BEQL @CHECK_WEST
	CMP #2
	BEQL @CHECK_EAST
	CMP #7
	BEQL @CHECK_DIAGONAL
	CMP #1
	BEQL @CHECK_DIAGONAL
	CMP #5
	BEQL @CHECK_DIAGONAL
	CMP #3
	BEQL @CHECK_DIAGONAL
	JMP @PROCESS_RESULT
@CHECK_NORTH:
	JSR TEST_COLLISION_NORTH
	STA @VIRTUAL02
	STA @LOCAL02
	LDA @VIRTUAL02
	CMP #.LOWORD(-1)
	BNEL @PROCESS_RESULT
	LDX LADDER_STAIRS_TILE_X
	STX @LOCAL01
	LDA CHECKED_COLLISION_TOP_Y
	AND #$0007
	CMP #5
	BCS @RESTORE_LADDER_NORTH
	DEC CHECKED_COLLISION_TOP_Y
	DEC CHECKED_COLLISION_TOP_Y
	DEC CHECKED_COLLISION_TOP_Y
	DEC CHECKED_COLLISION_TOP_Y
	JSR TEST_COLLISION_NORTH
	STA @LOCAL00
	AND #$FF00
	CMP #$FF00
	BEQ @RESTORE_LADDER_NORTH
	LDA @LOCAL00
	STA @VIRTUAL02
	STA @LOCAL02
@RESTORE_LADDER_NORTH:
	LDX @LOCAL01
	STX LADDER_STAIRS_TILE_X
	BRA @PROCESS_RESULT
@CHECK_SOUTH:
	JSR TEST_COLLISION_SOUTH
	STA @VIRTUAL02
	STA @LOCAL02
	LDA @VIRTUAL02
	CMP #.LOWORD(-1)
	BNE @PROCESS_RESULT
	LDX LADDER_STAIRS_TILE_X
	STX @LOCAL01
	LDA CHECKED_COLLISION_TOP_Y
	AND #$0007
	CMP #3
	BLTEQ @RESTORE_LADDER_SOUTH
	INC CHECKED_COLLISION_TOP_Y
	INC CHECKED_COLLISION_TOP_Y
	INC CHECKED_COLLISION_TOP_Y
	INC CHECKED_COLLISION_TOP_Y
	JSR TEST_COLLISION_SOUTH
	STA @LOCAL00
	AND #$FF00
	CMP #$FF00
	BEQ @RESTORE_LADDER_SOUTH
	LDA @LOCAL00
	STA @VIRTUAL02
	STA @LOCAL02
@RESTORE_LADDER_SOUTH:
	LDX @LOCAL01
	STX LADDER_STAIRS_TILE_X
	BRA @PROCESS_RESULT
@CHECK_WEST:
	JSR TEST_COLLISION_WEST
	STA @VIRTUAL02
	STA @LOCAL02
	BRA @PROCESS_RESULT
@CHECK_EAST:
	JSR TEST_COLLISION_EAST
	STA @VIRTUAL02
	STA @LOCAL02
	BRA @PROCESS_RESULT
@CHECK_DIAGONAL:
	LDA @LOCAL03
	JSR TEST_COLLISION_DIAGONAL
	STA @VIRTUAL02
	STA @LOCAL02
	LDA @VIRTUAL02
	CMP #$FF00
	BEQ @PROCESS_RESULT
	LDA @LOCAL03
	STA @VIRTUAL02
	STA @LOCAL02
@PROCESS_RESULT:
	LDA PENDING_INTERACTIONS
	BEQ @NO_PENDING_INTERACTION
	LDA #.LOWORD(-1)
	STA LADDER_STAIRS_TILE_X
@NO_PENDING_INTERACTION:
	LDA @LOCAL02
	STA @VIRTUAL02
	CMP #.LOWORD(-1)
	BEQ @NO_COLLISION
	LDA @VIRTUAL02
	CMP #$FF00
	BNE @HAS_COLLISION
@NO_COLLISION:
	LDA TEMP_ENTITY_SURFACE_FLAGS
	BRA @RETURN
@HAS_COLLISION:
	LDX #0
	LDA @VIRTUAL02
	CMP @LOCAL03
	BEQ @SAME_DIRECTION
	LDX #1
@SAME_DIRECTION:
	STX NOT_MOVING_IN_SAME_DIRECTION_FACED
	LDA @VIRTUAL02
	STA FINAL_MOVEMENT_DIRECTION
	LDA TEMP_ENTITY_SURFACE_FLAGS
	AND #$003F
@RETURN:
	END_C_FUNCTION
