
CHECK_COLLISION_TILE_PATTERN:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STA @VIRTUAL04
	LDY #0
	STY @LOCAL03
	STY @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL02
	BRA @LOOP_TEST
@LOOP_BODY:
	LDA @VIRTUAL04
	AND #$0001
	BEQ @NEXT_POINT
	TYA
	ASL
	STA @LOCAL01
	TAX
	LDA f:COLLISION_CHECK_Y_OFFSETS,X
	CLC
	ADC CHECKED_COLLISION_TOP_Y
	LSR
	LSR
	LSR
	TAX
	STX @LOCAL00
	LDA @LOCAL01
	TAX
	LDA f:COLLISION_CHECK_X_OFFSETS,X
	CLC
	ADC CHECKED_COLLISION_LEFT_X
	LSR
	LSR
	LSR
	LDX @LOCAL00
	JSR GET_COLLISION_TILE_AND_CHECK_LADDER
	STA @LOCAL00
	ORA @LOCAL02
	STA @LOCAL02
	LDA @LOCAL00
	AND #$00C0
	BEQ @NEXT_POINT
	LDA @VIRTUAL02
	ORA #$0040
	STA @VIRTUAL02
@NEXT_POINT:
	LDA @VIRTUAL02
	LSR
	STA @VIRTUAL02
	LDA @VIRTUAL04
	LSR
	STA @VIRTUAL04
	LDY @LOCAL03
	INY
	STY @LOCAL03
@LOOP_TEST:
	CPY #6
	BCC @LOOP_BODY
	LDA SET_TEMP_ENTITY_SURFACE_FLAGS
	CMP #1
	BNE @SKIP_SURFACE_STORE
	LDA @LOCAL02
	STA TEMP_ENTITY_SURFACE_FLAGS
@SKIP_SURFACE_STORE:
	LDA @VIRTUAL02
	END_C_FUNCTION
