
CHECK_ENTITY_ENEMY_COLLISION:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDA PLAYER_MOVEMENT_FLAGS
	AND #$0002
	BEQ @CHECK_LEADER_COLLISION
	LDA #$0000
	BRA @RETURN
@CHECK_LEADER_COLLISION:
	LDA ENTITY_COLLIDED_OBJECTS+46
	CMP CURRENT_ENTITY_SLOT
	BNE @CHECK_NPC_COLLISION
	LDA #$FFFF
	BRA @RETURN
@CHECK_NPC_COLLISION:
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_COLLIDED_OBJECTS,X
	CMP #$7FFF
	BGT @NO_COLLISION
	CMP #$0017
	BCS @COLLISION_DETECTED
@NO_COLLISION:
	LDA #$0000
	BRA @RETURN
@COLLISION_DETECTED:
	LDA #$FFFF
@RETURN:
	RTL
