
CHECK_ENTITY_AND_NPC_COLLISION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @LOCAL08
	TXY
	TAX
	STX @LOCAL07
	LDA #ENTITY_COLLISION_NO_OBJECT
	STA @LOCAL06
	LDA @LOCAL08
	ASL
	STA @VIRTUAL04
	LDX @VIRTUAL04
	LDA ENTITY_HITBOX_ENABLED,X
	BEQL @STORE_RESULT
	LDX @VIRTUAL04
	LDA ENTITY_DIRECTIONS,X
	CMP #DIRECTION::RIGHT
	BEQ @DIR_LEFT_RIGHT
	CMP #DIRECTION::LEFT
	BNE @DIR_UP_DOWN
@DIR_LEFT_RIGHT:
	LDA @LOCAL08
	ASL
	STA @LOCAL05
	TAX
	LDA ENTITY_HITBOX_LEFT_RIGHT_WIDTHS,X
	STA @VIRTUAL02
	LDA @LOCAL05
	TAX
	LDA ENTITY_HITBOX_LEFT_RIGHT_HEIGHTS,X
	STA @LOCAL04
	BRA @HITBOX_SELECTED
@DIR_UP_DOWN:
	LDX @VIRTUAL04
	LDA ENTITY_HITBOX_UP_DOWN_WIDTHS,X
	STA @VIRTUAL02
	LDX @VIRTUAL04
	LDA ENTITY_HITBOX_UP_DOWN_HEIGHTS,X
	STA @LOCAL04
@HITBOX_SELECTED:
	LDX @LOCAL07
	TXA
	SEC
	SBC @VIRTUAL02
	STA @VIRTUAL04
	LDA @VIRTUAL02
	ASL
	STA @LOCAL05
	TYA
	SEC
	SBC @LOCAL04
	STA @VIRTUAL02
	STA @LOCAL03
	LDA PLAYER_INTANGIBILITY_FRAMES
	BNEL @BEGIN_NPC_LOOP
	LDX #24
	JMP @PARTY_LOOP_CHECK
@CHECK_PARTY_ENTITY:
	TXA
	ASL
	TAY
	LDA ENTITY_SCRIPT_TABLE,Y
	CMP #.LOWORD(-1)
	BEQL @SKIP_PARTY_ENTITY
	LDA ENTITY_COLLIDED_OBJECTS,Y
	CMP #ENTITY_COLLISION_DISABLED
	BEQL @SKIP_PARTY_ENTITY
	LDA ENTITY_HITBOX_ENABLED,Y
	BEQL @SKIP_PARTY_ENTITY
	LDA ENTITY_DIRECTIONS,Y
	CMP #DIRECTION::RIGHT
	BEQ @PARTY_DIR_LEFT_RIGHT
	CMP #DIRECTION::LEFT
	BNE @PARTY_DIR_UP_DOWN
@PARTY_DIR_LEFT_RIGHT:
	TXA
	ASL
	TAY
	LDA ENTITY_HITBOX_LEFT_RIGHT_WIDTHS,Y
	STA @LOCAL02
	LDA ENTITY_HITBOX_LEFT_RIGHT_HEIGHTS,Y
	STA @LOCAL01
	BRA @PARTY_HITBOX_SELECTED
@PARTY_DIR_UP_DOWN:
	LDA ENTITY_HITBOX_UP_DOWN_WIDTHS,Y
	STA @LOCAL02
	LDA ENTITY_HITBOX_UP_DOWN_HEIGHTS,Y
	STA @LOCAL01
@PARTY_HITBOX_SELECTED:
	TXA
	ASL
	STA @LOCAL00
	LDY #.LOWORD(ENTITY_ABS_Y_TABLE)
	LDA (@LOCAL00),Y
	SEC
	SBC @LOCAL01
	TAY
	SEC
	SBC @LOCAL04
	PHA
	LDA @LOCAL03
	STA @VIRTUAL02
	STA TEMP_REGISTER
	PLA
	STA @VIRTUAL02
	LDA TEMP_REGISTER
	CMP @VIRTUAL02
	BLTEQ @SKIP_PARTY_ENTITY
	TYA
	CLC
	ADC @LOCAL01
	PHA
	LDA @LOCAL03
	STA @VIRTUAL02
	PLY
	STY @VIRTUAL02
	CMP @VIRTUAL02
	BCS @SKIP_PARTY_ENTITY
	LDA @LOCAL02
	STA @VIRTUAL02
	LDY #.LOWORD(ENTITY_ABS_X_TABLE)
	LDA (@LOCAL00),Y
	SEC
	SBC @VIRTUAL02
	TAY
	LDA @LOCAL02
	ASL
	STA @LOCAL02
	TYA
	SEC
	SBC @LOCAL05
	STA @VIRTUAL02
	LDA @VIRTUAL04
	CMP @VIRTUAL02
	BLTEQ @SKIP_PARTY_ENTITY
	LDA @LOCAL02
	STA @VIRTUAL02
	TYA
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL02
	LDA @VIRTUAL04
	CMP @VIRTUAL02
	BCS @SKIP_PARTY_ENTITY
	STX @LOCAL06
	JMP @STORE_RESULT
@SKIP_PARTY_ENTITY:
	INX
@PARTY_LOOP_CHECK:
	CPX #MAX_ENTITIES
	BNEL @CHECK_PARTY_ENTITY
@BEGIN_NPC_LOOP:
	LDX #0
	JMP @NPC_LOOP_CHECK
@CHECK_NPC_ENTITY:
	CPX @LOCAL08
	BEQL @SKIP_NPC_ENTITY
	TXA
	ASL
	TAY
	LDA ENTITY_SCRIPT_TABLE,Y
	CMP #.LOWORD(-1)
	BEQL @SKIP_NPC_ENTITY
	LDA ENTITY_NPC_IDS,Y
	CMP #$1000
	BCC @NPC_IS_VALID
	JMP @SKIP_NPC_ENTITY
@NPC_IS_VALID:
	LDA ENTITY_COLLIDED_OBJECTS,Y
	CMP #ENTITY_COLLISION_DISABLED
	BEQL @SKIP_NPC_ENTITY
	LDA ENTITY_HITBOX_ENABLED,Y
	BEQL @SKIP_NPC_ENTITY
	LDA ENTITY_DIRECTIONS,Y
	CMP #DIRECTION::RIGHT
	BEQ @NPC_DIR_LEFT_RIGHT
	CMP #DIRECTION::LEFT
	BNE @NPC_DIR_UP_DOWN
@NPC_DIR_LEFT_RIGHT:
	TXA
	ASL
	TAY
	LDA ENTITY_HITBOX_LEFT_RIGHT_WIDTHS,Y
	STA @LOCAL02
	LDA ENTITY_HITBOX_LEFT_RIGHT_HEIGHTS,Y
	STA @LOCAL01
	BRA @NPC_HITBOX_SELECTED
@NPC_DIR_UP_DOWN:
	LDA ENTITY_HITBOX_UP_DOWN_WIDTHS,Y
	STA @LOCAL02
	LDA ENTITY_HITBOX_UP_DOWN_HEIGHTS,Y
	STA @LOCAL01
@NPC_HITBOX_SELECTED:
	TXA
	ASL
	STA @LOCAL00
	LDY #.LOWORD(ENTITY_ABS_Y_TABLE)
	LDA (@LOCAL00),Y
	SEC
	SBC @LOCAL01
	TAY
	SEC
	SBC @LOCAL04
	PHA
	LDA @LOCAL03
	STA @VIRTUAL02
	STA TEMP_REGISTER
	PLA
	STA @VIRTUAL02
	LDA TEMP_REGISTER
	CMP @VIRTUAL02
	BLTEQ @SKIP_NPC_ENTITY
	TYA
	CLC
	ADC @LOCAL01
	DEC
	PHA
	LDA @LOCAL03
	STA @VIRTUAL02
	PLY
	STY @VIRTUAL02
	CMP @VIRTUAL02
	BCS @SKIP_NPC_ENTITY
	LDA @LOCAL02
	STA @VIRTUAL02
	LDY #.LOWORD(ENTITY_ABS_X_TABLE)
	LDA (@LOCAL00),Y
	SEC
	SBC @VIRTUAL02
	TAY
	LDA @LOCAL02
	ASL
	STA @LOCAL02
	TYA
	SEC
	SBC @LOCAL05
	STA @VIRTUAL02
	LDA @VIRTUAL04
	CMP @VIRTUAL02
	BLTEQ @SKIP_NPC_ENTITY
	LDA @LOCAL02
	STA @VIRTUAL02
	TYA
	CLC
	ADC @VIRTUAL02
	DEC
	STA @VIRTUAL02
	LDA @VIRTUAL04
	CMP @VIRTUAL02
	BCS @SKIP_NPC_ENTITY
	STX @LOCAL06
	BRA @STORE_RESULT
@SKIP_NPC_ENTITY:
	INX
@NPC_LOOP_CHECK:
	CPX #23
	BNEL @CHECK_NPC_ENTITY
@STORE_RESULT:
	LDA @LOCAL08
	ASL
	TAX
	LDA @LOCAL06
	STA ENTITY_COLLIDED_OBJECTS,X
	LDA @LOCAL06
	END_C_FUNCTION
