
CHECK_ENTITY_COLLISION_PATH:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @LOCAL07
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	LDA CURRENT_ENTITY_SLOT
	STA @LOCAL06
	ASL
	TAX
	STX @LOCAL05
	LDA ENTITY_SIZES,X
	STA @LOCAL04
	LOADPTR DIRECTION_QUANTIZE_TABLE, @VIRTUAL06
	LDA @LOCAL04
	ASL
	STA @LOCAL03
	PHA
	LDA ENTITY_ABS_X_TABLE,X
	PLX
	SEC
	SBC f:ENTITY_COLLISION_X_OFFSET,X
	LSR
	LSR
	LSR
	SEC
	SBC #4
	TAY
	LDA @LOCAL03
	PHA
	PHA
	LDX @LOCAL05
	LDA ENTITY_ABS_Y_TABLE,X
	PLX
	SEC
	SBC f:ENTITY_COLLISION_Y_OFFSET,X
	PLX
	CLC
	ADC f:SPRITE_HITBOX_ENABLE_TABLE,X
	LSR
	LSR
	LSR
	SEC
	SBC #4
	STA @VIRTUAL02
	STA @LOCAL02
	TYA
	AND #$003F
	TAX
	STX @LOCAL01
	LDA @VIRTUAL02
	AND #$003F
	STA @LOCAL05
	LDA #0
	STA @VIRTUAL04
	JMP @LOOP_CHECK
@CHECK_TILE:
	LDX @LOCAL01
	CPX #64
	BCS @ADVANCE_DIRECTION
	LDA @LOCAL05
	CMP #64
	BCS @ADVANCE_DIRECTION
	TXA
	AND #$003F
	STA @VIRTUAL02
	LDA @LOCAL05
	AND #$003F
	OPTIMIZED_MULT @VIRTUAL04, 64
	CLC
	ADC @VIRTUAL02
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	AND LOADED_COLLISION_TILES,X
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNE @COLLISION_FOUND
@ADVANCE_DIRECTION:
	LDA [@VIRTUAL06]
	AND #$00FF
	STA @LOCAL00
	INC @VIRTUAL06
	LDA @LOCAL00
	CMP #1
	BEQ @DIR_UP
	CMP #2
	BEQ @DIR_RIGHT
	CMP #3
	BEQ @DIR_DOWN
	CMP #4
	BEQ @DIR_LEFT
	BRA @STEP_DONE
@DIR_UP:
	LDA @LOCAL05
	DEC
	STA @LOCAL05
	LDA @LOCAL02
	STA @VIRTUAL02
	DEC
	STA @VIRTUAL02
	STA @LOCAL02
	BRA @STEP_DONE
@DIR_RIGHT:
	LDX @LOCAL01
	INX
	STX @LOCAL01
	INY
	BRA @STEP_DONE
@DIR_DOWN:
	LDA @LOCAL05
	INC
	STA @LOCAL05
	LDA @LOCAL02
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL02
	BRA @STEP_DONE
@DIR_LEFT:
	LDX @LOCAL01
	DEX
	STX @LOCAL01
	DEY
@STEP_DONE:
	INC @VIRTUAL04
@LOOP_CHECK:
	LDA @VIRTUAL04
	CMP @LOCAL07
	BNEL @CHECK_TILE
	LDA #0
	BRA @RETURN
@COLLISION_FOUND:
	LDA @LOCAL06
	ASL
	STA @LOCAL07
	LDA @LOCAL04
	ASL
	TAX
	STX @LOCAL03
	LDA @LOCAL07
	PHA
	TYA
	OPTIMIZED_MULT @VIRTUAL04, 8
	CLC
	ADC f:ENTITY_COLLISION_X_OFFSET,X
	PLX
	STA ENTITY_SCRIPT_VAR6_TABLE,X
	LDA @LOCAL07
	PHA
	LDX @LOCAL03
	LDA @LOCAL02
	STA @VIRTUAL02
	OPTIMIZED_MULT @VIRTUAL04, 8
	SEC
	SBC f:SPRITE_HITBOX_ENABLE_TABLE,X
	CLC
	ADC f:ENTITY_COLLISION_Y_OFFSET,X
	PLX
	STA ENTITY_SCRIPT_VAR7_TABLE,X
	LDA #.LOWORD(-1)
@RETURN:
	END_C_FUNCTION
