
CHECK_ENTITY_COLLISION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @VIRTUAL04
	STA @LOCAL02
	LDX @PARAM03
	STX @LOCAL01
	STZ TEMP_ENTITY_SURFACE_FLAGS
	TYA
	ASL
	TAX
	LDA ENTITY_SIZES,X
	STA @VIRTUAL02
	ASL
	STA @LOCAL00
	LDX @LOCAL00
	LDA @LOCAL02
	SEC
	SBC f:ENTITY_COLLISION_X_OFFSET,X
	TAY
	STY CHECKED_COLLISION_LEFT_X
	LDX @LOCAL00
	LDA @VIRTUAL04
	SEC
	SBC f:ENTITY_COLLISION_Y_OFFSET,X
	LDX @LOCAL00
	CLC
	ADC f:SPRITE_HITBOX_ENABLE_TABLE,X
	STA @LOCAL00
	STA CHECKED_COLLISION_TOP_Y
	LDX @LOCAL01
	TXA
	CMP #1
	BEQ @DIR_UP_RIGHT
	CMP #0
	BEQ @DIR_UP
	CMP #3
	BEQ @DIR_DOWN_RIGHT
	CMP #2
	BEQ @DIR_RIGHT
	CMP #5
	BEQ @DIR_DOWN_LEFT
	CMP #4
	BEQ @DIR_DOWN
	CMP #7
	BEQ @DIR_UP_LEFT
	CMP #6
	BEQ @DIR_LEFT
	BRA @RETURN
@DIR_UP_RIGHT:
	LDX @VIRTUAL02
	LDA @LOCAL00
	JSR ACCUMULATE_COLLISION_FLAGS_HORIZONTAL
@DIR_UP:
	LDX @VIRTUAL02
	LDA CHECKED_COLLISION_LEFT_X
	JSR CHECK_COLLISION_TILES_HORIZONTAL
	BRA @RETURN
@DIR_DOWN_RIGHT:
	LDX @VIRTUAL02
	TYA
	JSR CHECK_COLLISION_TILES_VERTICAL
@DIR_RIGHT:
	LDX @VIRTUAL02
	LDA CHECKED_COLLISION_TOP_Y
	JSR ACCUMULATE_COLLISION_FLAGS_HORIZONTAL
	BRA @RETURN
@DIR_DOWN_LEFT:
	LDX @VIRTUAL02
	LDA @LOCAL00
	JSR ACCUMULATE_COLLISION_FLAGS_VERTICAL
@DIR_DOWN:
	LDX @VIRTUAL02
	LDA CHECKED_COLLISION_LEFT_X
	JSR CHECK_COLLISION_TILES_VERTICAL
	BRA @RETURN
@DIR_UP_LEFT:
	LDX @VIRTUAL02
	TYA
	JSR CHECK_COLLISION_TILES_HORIZONTAL
@DIR_LEFT:
	LDX @VIRTUAL02
	LDA CHECKED_COLLISION_TOP_Y
	JSR ACCUMULATE_COLLISION_FLAGS_VERTICAL
@RETURN:
	LDA TEMP_ENTITY_SURFACE_FLAGS
	END_C_FUNCTION
