
CHECK_DIRECTIONAL_NPC_COLLISION:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL04
	ASL
	TAX
	LDA f:INTERACTION_X_OFFSETS,X
	CLC
	ADC GAME_STATE+game_state::leader_x_coord
	STA @LOCAL03
	LDA f:INTERACTION_Y_OFFSETS,X
	CLC
	ADC GAME_STATE+game_state::leader_y_coord
	STA @VIRTUAL04
	LDA PLAYER_INTANGIBILITY_FRAMES
	STA @LOCAL02
	LDA #1
	STA PLAYER_INTANGIBILITY_FRAMES
@NPC_COLLISION_LOOP:
	LDA #.LOWORD(GAME_STATE) + game_state::current_party_members
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	TAY
	LDX @VIRTUAL04
	LDA @LOCAL03
	JSL NPC_COLLISION_CHECK
	STA @LOCAL01
	CMP #$8000
	BCS @CHECK_ENTITY_COLLISION
	ASL
	TAX
	LDA ENTITY_NPC_IDS,X
	STA INTERACTING_NPC_ID
	LDA @LOCAL01
	STA INTERACTING_NPC_ENTITY
	BRA @RESTORE_INTANGIBILITY
@CHECK_ENTITY_COLLISION:
	LDA @LOCAL04
	STA @LOCAL00
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	TAY
	LDX @VIRTUAL04
	LDA @LOCAL03
	JSL CHECK_ENTITY_COLLISION
	AND #$0082
	CMP #130
	BNE @RESTORE_INTANGIBILITY
	LDA @LOCAL04
	ASL
	TAX
	LDA f:INTERACTION_X_OFFSETS,X
	BEQ @CHECK_Y_ADJUST
	AND #$8000
	BEQ @ADJUST_X_POSITIVE
	LDX #.LOWORD(-8)
	BRA @APPLY_X_ADJUST
@ADJUST_X_POSITIVE:
	LDX #8
@APPLY_X_ADJUST:
	TXA
	CLC
	ADC @LOCAL03
	STA @LOCAL03
@CHECK_Y_ADJUST:
	LDA @LOCAL04
	ASL
	TAX
	LDA f:INTERACTION_Y_OFFSETS,X
	BEQ @NPC_COLLISION_LOOP
	AND #$8000
	BEQ @ADJUST_Y_POSITIVE
	LDX #.LOWORD(-8)
	BRA @APPLY_Y_ADJUST
@ADJUST_Y_POSITIVE:
	LDX #8
@APPLY_Y_ADJUST:
	STX @VIRTUAL02
	LDA @VIRTUAL04
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL04
	JMP @NPC_COLLISION_LOOP
@RESTORE_INTANGIBILITY:
	LDA @LOCAL02
	STA PLAYER_INTANGIBILITY_FRAMES
	LDA INTERACTING_NPC_ID
	CMP #.LOWORD(-1)
	BEQ @CHECK_DOOR
	LDA INTERACTING_NPC_ID
	BNE @DONE
@CHECK_DOOR:
	LDA @LOCAL04
	JSL CHECK_DOOR_NEAR_LEADER
@DONE:
	LDA INTERACTING_NPC_ID
	END_C_FUNCTION
