
CHECK_ENEMY_MOVEMENT_OBSTACLES:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX CURRENT_ENTITY_SLOT
	STX @LOCAL01
	TXA
	JSR CHECK_ENTITY_OBSTACLE_FLAGS
	STA @LOCAL00
	CMP #$FF00
	BNE @HAS_VALID_POSITION
	LDA #0
	BRA @RETURN
@HAS_VALID_POSITION:
	CMP #0
	BEQ @NO_MAP_OBSTACLE
	LDA #0
	BRA @RETURN
@NO_MAP_OBSTACLE:
	LDX @LOCAL01
	TXA
	ASL
	TAY
	CLC
	ADC #.LOWORD(ENTITY_OBSTACLE_FLAGS)
	STA @VIRTUAL02
	LDA ENTITY_ENEMY_IDS,Y
	TAY
	LDA @LOCAL00
	JSL CAN_ENEMY_RUN_IN_DIRECTION
	STA @VIRTUAL04
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	ORA @VIRTUAL04
	LDX @VIRTUAL02
	STA __BSS_START__,X
@RETURN:
	END_C_FUNCTION
