
CHECK_NPC_PLAYER_OBSTACLES:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	STA @LOCAL01
	JSL CALCULATE_PROSPECTIVE_POSITION
	CMP #0
	BNE @NO_PROSPECTIVE
	LDA #0
	BRA @RETURN
@NO_PROSPECTIVE:
	LDY @LOCAL01
	LDX ENTITY_MOVEMENT_PROSPECTIVE_Y
	LDA ENTITY_MOVEMENT_PROSPECTIVE_X
	JSL CHECK_PLAYER_COLLISION_AT_POSITION
	AND #$00D0
	STA @VIRTUAL02
	LDA @LOCAL01
	ASL
	TAX
	STX @LOCAL00
	TXA
	CLC
	ADC #.LOWORD(ENTITY_OBSTACLE_FLAGS)
	STA @VIRTUAL04
	LDA @VIRTUAL02
	LDX @VIRTUAL04
	STA __BSS_START__,X
	LDA @VIRTUAL02
	BEQ @HAS_OBSTACLE
	LDA #0
	BRA @RETURN
@HAS_OBSTACLE:
	LDX @LOCAL00
	LDY ENTITY_ENEMY_IDS,X
	LDX @LOCAL01
	LDA @VIRTUAL02
	JSL CAN_ENEMY_RUN_IN_DIRECTION
	PHA
	LDA @VIRTUAL02
	PLY
	STY @VIRTUAL02
	ORA @VIRTUAL02
	LDX @VIRTUAL04
	STA __BSS_START__,X
@RETURN:
	END_C_FUNCTION
