
CHECK_PROSPECTIVE_ENTITY_COLLISION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX CURRENT_ENTITY_SLOT
	STX @LOCAL00
	TXA
	ASL
	TAX
	LDA ENTITY_COLLIDED_OBJECTS,X
	CMP #ENTITY_COLLISION_DISABLED
	BEQ @COLLISION_DISABLED
	LDX @LOCAL00
	TXA
	JSL CALCULATE_PROSPECTIVE_POSITION_ENTRY2
	LDX @LOCAL00
	TXY
	LDX ENTITY_MOVEMENT_PROSPECTIVE_Y
	LDA ENTITY_MOVEMENT_PROSPECTIVE_X
	JSL CHECK_ENTITY_COLLISION_AT_POSITION
@COLLISION_DISABLED:
	END_C_FUNCTION
