
ENTITY_PHYSICS_SIMPLE_COLLISION:
	LDX $88
	LDA ENTITY_PATHFINDING_STATES,X
	BMI @APPLY_DELTA
	LDA ENTITY_OBSTACLE_FLAGS,X
	AND #$00D0
	BEQ @CHECK_COLLIDED_OBJECTS
	JMP MOVEMENT_CODE_39
@CHECK_COLLIDED_OBJECTS:
	LDX $88
	LDA ENTITY_COLLIDED_OBJECTS,X
	BMI @APPLY_DELTA
	RTS
	LDX $88
@APPLY_DELTA:
	JSR APPLY_ENTITY_DELTA_POSITION_ENTRY3
	RTS
