
ENTITY_PHYSICS_WITH_COLLISION:
	LDX $88
	LDA ENTITY_PATHFINDING_STATES,X
	BMI ENTITY_PHYSICS_FORCE_MOVE_1
	LDA ENTITY_OBSTACLE_FLAGS,X
	AND #$00D0
	BEQ @HAS_OBSTACLE
	JMP MOVEMENT_CODE_39
@HAS_OBSTACLE:
	LDX $88
	LDA ENTITY_COLLIDED_OBJECTS,X
	BMI ENTITY_PHYSICS_FORCE_MOVE_1
	RTS
ENTITY_PHYSICS_FORCE_MOVE:
	LDX $88
ENTITY_PHYSICS_FORCE_MOVE_1:
	JSR APPLY_ENTITY_DELTA_POSITION_ENTRY3
	JSL UPDATE_ENTITY_SURFACE_FLAGS
	RTS
