
GET_COLLISION_AT_LEADER:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDY #$000C
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL LOOKUP_ENTITY_SURFACE_FLAGS
	AND #$00C0
	RTL
