
LOOKUP_ENTITY_SURFACE_FLAGS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @LOCAL02
	STX @LOCAL01
	STA @LOCAL00
	TYA
	ASL
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA @LOCAL00
	SEC
	SBC f:ENTITY_COLLISION_X_OFFSET,X
	STA @LOCAL00
	STA CHECKED_COLLISION_LEFT_X
	LDX @LOCAL01
	TXA
	LDX @VIRTUAL02
	SEC
	SBC f:ENTITY_COLLISION_Y_OFFSET,X
	LDX @VIRTUAL02
	CLC
	ADC f:SPRITE_HITBOX_ENABLE_TABLE,X
	STA CHECKED_COLLISION_TOP_Y
	TYX
	LDA @LOCAL00
	JSR CHECK_COLLISION_TILES_HORIZONTAL
	LDY @LOCAL02
	TYX
	LDA CHECKED_COLLISION_LEFT_X
	JSR CHECK_COLLISION_TILES_VERTICAL
	LDY @LOCAL02
	TYX
	LDA CHECKED_COLLISION_TOP_Y
	JSR ACCUMULATE_COLLISION_FLAGS_VERTICAL
	LDY @LOCAL02
	TYX
	LDA CHECKED_COLLISION_TOP_Y
	JSR ACCUMULATE_COLLISION_FLAGS_HORIZONTAL
	LDA TEMP_ENTITY_SURFACE_FLAGS
	END_C_FUNCTION
