
PREDICT_SURFACE_FLAGS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	STA @VIRTUAL02
	JSL CALCULATE_PROSPECTIVE_POSITION
	CMP #0
	BEQ @NO_MOVEMENT
	LDY @VIRTUAL02
	LDX ENTITY_MOVEMENT_PROSPECTIVE_Y
	LDA ENTITY_MOVEMENT_PROSPECTIVE_X
	JSL LOOKUP_SURFACE_FLAGS
	STA @LOCAL00
	LDA @VIRTUAL02
	ASL
	TAX
	LDA @LOCAL00
	STA ENTITY_SURFACE_FLAGS,X
@NO_MOVEMENT:
	END_C_FUNCTION
