
TEST_COLLISION_EAST:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDY #.LOWORD(-1)
	STY @LOCAL02
	LDA #0
	STA @VIRTUAL02
	TAX
	STX @LOCAL01
	STZ TEMP_ENTITY_SURFACE_FLAGS
	LDA #1
	STA SET_TEMP_ENTITY_SURFACE_FLAGS
	LDA #36
	JSR CHECK_COLLISION_TILE_PATTERN
	STA @LOCAL00
	CMP #0
	BNE @CHECK_BOTH_EDGES_BLOCKED
	INC CHECKED_COLLISION_LEFT_X
	INC CHECKED_COLLISION_LEFT_X
	INC CHECKED_COLLISION_LEFT_X
	INC CHECKED_COLLISION_LEFT_X
	LDA #36
	JSR CHECK_COLLISION_TILE_PATTERN
	STA @LOCAL00
	CMP #0
	BNE @EXTENDED_CHECK_HIT
	LDA #2
	JMP @RETURN
@EXTENDED_CHECK_HIT:
	LDA #1
	STA @VIRTUAL02
@CHECK_BOTH_EDGES_BLOCKED:
	LDA @LOCAL00
	AND #$0024
	CMP #36
	BNE @CHECK_TOP_CORNER_SURFACE
	LDA CHECKED_COLLISION_TOP_Y
	AND #$0007
	BEQ @CHECK_TOP_CORNER_SURFACE
	LDA @VIRTUAL02
	BEQ @BLOCKED_NO_NUDGE
	LDA #2
	JMP @RETURN
@BLOCKED_NO_NUDGE:
	LDA #.LOWORD(-1)
	JMP @RETURN
@CHECK_TOP_CORNER_SURFACE:
	LDA CHECKED_COLLISION_LEFT_X
	INC
	INC
	INC
	INC
	LSR
	LSR
	LSR
	AND #$003F
	STA @VIRTUAL04
	LDA CHECKED_COLLISION_TOP_Y
	DEC
	DEC
	LSR
	LSR
	LSR
	AND #$003F
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL04
	TAX
	LDA LOADED_COLLISION_TILES,X
	AND #$00FF
	AND #$00C0
	BEQ @CHECK_BOTTOM_CORNER_SURFACE
	LDX @LOCAL01
	TXA
	ORA #$0001
	TAX
	STX @LOCAL01
@CHECK_BOTTOM_CORNER_SURFACE:
	LDA CHECKED_COLLISION_LEFT_X
	INC
	INC
	INC
	INC
	LSR
	LSR
	LSR
	AND #$003F
	STA @VIRTUAL04
	LDA CHECKED_COLLISION_TOP_Y
	CLC
	ADC #9
	LSR
	LSR
	LSR
	AND #$003F
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL04
	TAX
	LDA LOADED_COLLISION_TILES,X
	AND #$00FF
	AND #$00C0
	BEQ @DISPATCH_COLLISION_PATTERN
	LDX @LOCAL01
	TXA
	ORA #$0002
	TAX
	STX @LOCAL01
@DISPATCH_COLLISION_PATTERN:
	LDA @LOCAL00
	CMP #36
	BEQ @BOTH_EDGES_BLOCKED
	CMP #4
	BEQ @TOP_EDGE_BLOCKED
	CMP #32
	BEQ @BOTTOM_EDGE_BLOCKED
	BRA @CHECK_EXTENDED_RESULT
@BOTH_EDGES_BLOCKED:
	LDX @LOCAL01
	CPX #1
	BNE @BOTH_ONLY_BOTTOM_WALL
	LDY #3
	STY @LOCAL02
	BRA @CHECK_EXTENDED_RESULT
@BOTH_ONLY_BOTTOM_WALL:
	CPX #2
	BNE @BOTH_NO_WALLS
	LDY #1
	STY @LOCAL02
	BRA @CHECK_EXTENDED_RESULT
@BOTH_NO_WALLS:
	CPX #0
	BNE @CHECK_EXTENDED_RESULT
	LDA CHECKED_COLLISION_TOP_Y
	AND #$0007
	CMP #4
	BCS @BOTH_NUDGE_DOWN
	LDY #1
	STY @LOCAL02
	BRA @CHECK_EXTENDED_RESULT
@BOTH_NUDGE_DOWN:
	LDY #3
	STY @LOCAL02
	BRA @CHECK_EXTENDED_RESULT
@TOP_EDGE_BLOCKED:
	LDX @LOCAL01
	TXA
	AND #$0002
	BNE @CHECK_EXTENDED_RESULT
	LDY #3
	STY @LOCAL02
	BRA @CHECK_EXTENDED_RESULT
@BOTTOM_EDGE_BLOCKED:
	LDX @LOCAL01
	TXA
	AND #$0001
	BNE @CHECK_EXTENDED_RESULT
	LDY #1
	STY @LOCAL02
@CHECK_EXTENDED_RESULT:
	LDA @VIRTUAL02
	BEQ @RETURN_NUDGE_DIRECTION
	LDY @LOCAL02
	CPY #.LOWORD(-1)
	BNE @RETURN_NUDGE_DIRECTION
	LDA #2
	BRA @RETURN
@RETURN_NUDGE_DIRECTION:
	LDY @LOCAL02
	TYA
@RETURN:
	END_C_FUNCTION
