
TEST_COLLISION_SOUTH:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STZ TEMP_ENTITY_SURFACE_FLAGS
	INC SET_TEMP_ENTITY_SURFACE_FLAGS
	LDA #$0038
	JSR CHECK_COLLISION_TILE_PATTERN
	STA NORTH_SOUTH_COLLISION_TEST_RESULT
	CMP #$0007
	BEQ @FULLY_BLOCKED
	CMP #$0010
	BNE @CHECK_NO_COLLISION
@FULLY_BLOCKED:
	LDA #$FF00
	BRA @RETURN
@CHECK_NO_COLLISION:
	CMP #$0000
	BNE @CHECK_LEFT_BLOCKED
	LDA #$FFFF
	BRA @RETURN
@CHECK_LEFT_BLOCKED:
	CMP #$0008
	BNE @CHECK_RIGHT_BLOCKED
	LDA #$0003
	BRA @RETURN
@CHECK_RIGHT_BLOCKED:
	CMP #$0020
	BNE @CHECK_CENTER_RIGHT
	LDA #$0005
	BRA @RETURN
@CHECK_CENTER_RIGHT:
	CMP #$0030
	BNE @DEFAULT_CLEAR
	LDA CHECKED_COLLISION_LEFT_X
	AND #$0007
	BNE @DEFAULT_CLEAR
	LDA #$0005
	BRA @RETURN
@DEFAULT_CLEAR:
	LDA #$FFFF
@RETURN:
	RTS
