
TEST_COLLISION_DIAGONAL:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL00
	STZ TEMP_ENTITY_SURFACE_FLAGS
	INC SET_TEMP_ENTITY_SURFACE_FLAGS
	TXA
	LSR
	ASL
	TAX
	LDA f:DIAGONAL_COLLISION_MASKS,X
	JSR CHECK_COLLISION_TILE_PATTERN
	CMP #0
	BEQ @CLEAR
	LDA #$FF00
	BRA @RETURN
@CLEAR:
	LDX @LOCAL00
	TXA
@RETURN:
	END_C_FUNCTION
