.SEGMENT "SRAM"
.INCLUDE "config.asm"
.INCLUDE "enums.asm"
.INCLUDE "structs.asm"
.INCLUDE "symbols/sram.inc.asm"

SRAM: ;For pointers.

.ORG $306000
SAVE_BASE:

.ORG $316000
REPLAY_SAVE_GAME_STATE:
	.RES .SIZEOF(game_state)
REPLAY_SAVE_PARTY_CHARACTERS:
	.RES .SIZEOF(char_struct) * 6
REPLAY_SAVE_EVENT_FLAGS:
	.RES (EVENT_FLAG_COUNT/8)
REPLAY_SAVE_TIMER:

.ORG $307FF0
SRAM_SIZE_1_SCRATCH:
ANTIPIRACY_SCRATCH_SPACE:

.ORG $317FF0
SRAM_SIZE_2_SCRATCH:
ANTIPIRACY_MIRROR_TEST:

.ORG $327FF0
SRAM_SIZE_3_SCRATCH:

.ORG $326000
REPLAY_DEMO_DATA:
