
ANIMATE_WINDOW_BORDER_WITH_HPPP:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #3
	JSR SET_WINDOW_PALETTE_INDEX
	LOADPTR WINDOW_BORDER_ANIM_TILES_ROW2, @VIRTUAL06
	LDY #0
	STY @LOCAL01
	BRA @TILE_CHECK_1
@TILE_LOOP_1:
	LDA [@VIRTUAL06]
	INC @VIRTUAL06
	INC @VIRTUAL06
	JSR SET_TILE_ATTRIBUTE_AND_REDRAW
	LDX #1
	STX @LOCAL00
	BRA @TICK_CHECK_1
@TICK_LOOP_1:
	JSL WINDOW_TICK
@TICK_CHECK_1:
	LDX @LOCAL00
	TXA
	DEX
	STX @LOCAL00
	CMP #0
	BNE @TICK_LOOP_1
	LDY @LOCAL01
	INY
	STY @LOCAL01
@TILE_CHECK_1:
	CPY #4
	BCC @TILE_LOOP_1
	LDX #8
	STX @LOCAL00
	BRA @HPPP_CHECK
@HPPP_TICK:
	JSL UPDATE_HPPP_METER_AND_RENDER
@HPPP_CHECK:
	LDX @LOCAL00
	TXA
	DEX
	STX @LOCAL00
	CMP #0
	BNE @HPPP_TICK
	LDY #0
	STY @LOCAL01
	BRA @TILE_CHECK_2
@TILE_LOOP_2:
	LDA [@VIRTUAL06]
	INC @VIRTUAL06
	INC @VIRTUAL06
	JSR SET_TILE_ATTRIBUTE_AND_REDRAW
	LDX #1
	STX @LOCAL00
	BRA @TICK_CHECK_2
@TICK_LOOP_2:
	JSL WINDOW_TICK
@TICK_CHECK_2:
	LDX @LOCAL00
	TXA
	DEX
	STX @LOCAL00
	CMP #0
	BNE @TICK_LOOP_2
	LDY @LOCAL01
	INY
	STY @LOCAL01
@TILE_CHECK_2:
	CPY #5
	BCC @TILE_LOOP_2
	LDA #0
	JSR SET_WINDOW_PALETTE_INDEX
	END_C_FUNCTION
