
; Drawi a single HP/PP window
DRAW_HP_PP_WINDOW:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
.IF !.DEFINED(JPN)
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16 "TILEARRPTR"
.ELSE
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16 "TILEARRPTR"
	STACK_RESERVE_INT16 "LOCAL01"
.ENDIF
	STACK_RESERVE_INT16 "LOCAL03"
	STACK_RESERVE_INT16 "LOCAL04"
	STACK_RESERVE_INT16 "LOCAL05"
	STACK_RESERVE_INT16 "LOCAL06"
	STACK_RESERVE_INT16 "LOCAL07"
	STACK_RESERVE_INT16 "LOCAL08"
	STACK_RESERVE_INT16 "CHAR_ENTRY"
	STACK_RESERVE_INT16 "CHAR_ID"
	STACK_RESERVE_PARAM_INT16 ;int id
	END_STACK_VARS
	STA @CHAR_ID
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
.ELSE
	LDY #.LOWORD(GAME_STATE) + game_state::party_members
	LDA (@CHAR_ID),Y
.ENDIF
	AND #$00FF
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	STA @CHAR_ENTRY
	CLC
	ADC #char_struct::afflictions
	STA @VIRTUAL02
	LDX #1
	LDA @VIRTUAL02
	JSL GET_EQUIP_WINDOW_TEXT
	TAY
	STY @LOCAL08
	LDX #1
	LDA @VIRTUAL02
	JSL GET_EQUIP_WINDOW_TEXT
	STA @VIRTUAL04
	LDY @LOCAL08
	TYA
	AND #$FFF0
	CLC
	ADC @VIRTUAL04
.IF .DEFINED(JPN)
	TAY
	STY @LOCAL07
.ELSE
	STA @LOCAL07
.ENDIF
	LDY #char_struct::hp_pp_window_options
	LDA (@CHAR_ENTRY),Y
	STA @VIRTUAL04
	STA @LOCAL06
	LDA @VIRTUAL04
	CMP #$0C00
	BNE @NORMAL_DISPLAY_MODE
	LDA #$0C00
	STA @VIRTUAL02
	STA @LOCAL05
	STA @LOCAL08
	LDA #$0800
	STA @LOCAL04
	BRA @AFTER_DISPLAY_MODE
@NORMAL_DISPLAY_MODE:
	LDA @VIRTUAL02
	JSL GET_EQUIP_WINDOW_TEXT_ALT
	LDY #$0400
	JSL MULT16
	STA @VIRTUAL02
	STA @LOCAL05
	LDA #$1000
	STA @LOCAL08
	STZ @LOCAL04
@AFTER_DISPLAY_MODE:
	LDA BATTLE_MENU_CURRENT_CHARACTER_ID
	CMP @CHAR_ID
	BNE @NOT_ACTIVE_CHAR
	LDA #ACTIVE_HPPP_WINDOW_Y_OFFSET
	STA @LOCAL03
	BRA @AFTER_Y_OFFSET
@NOT_ACTIVE_CHAR:
	LDA #NORMAL_HPPP_WINDOW_Y_OFFSET
	STA @LOCAL03
@AFTER_Y_OFFSET:
	LDA @CHAR_ID
	OPTIMIZED_MULT @VIRTUAL04, 7
	PHA
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, 7
	PHA
	ASL
	PLA
	ROR
	STA @VIRTUAL02
	LDA #16
	SEC
	SBC @VIRTUAL02
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	ASL
	STA @VIRTUAL02
	LDA @LOCAL03
	OPTIMIZED_MULT @VIRTUAL04, SCREEN_X_TILE_RESOLUTION * 2
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #.LOWORD(BG2_BUFFER)
	TAX
	LDA @LOCAL06
	STA @VIRTUAL04
	CLC
	ADC #$2004
	STA __BSS_START__,X
	INX
	INX
.IF .DEFINED(JPN)
	LDA #HPPP_WINDOW_WIDTH - 2
	STA @LOCAL01
.ELSE
	LDY #HPPP_WINDOW_WIDTH - 2
.ENDIF
	BRA @TOP_EDGE_LOOP_CHECK
@WRITE_TOP_EDGE_TILE:
	LDA @VIRTUAL04
	CLC
	ADC #$2005
	STA __BSS_START__,X
	INX
	INX
.IF .DEFINED(JPN)
	LDA @LOCAL01
	DEC
	STA @LOCAL01
.ELSE
	DEY
.ENDIF
@TOP_EDGE_LOOP_CHECK:
.IF .DEFINED(JPN)
	BNE @WRITE_TOP_EDGE_TILE
	LDA @VIRTUAL04
	CLC
	ADC #$6004
	STA __BSS_START__,X
	TXA
	INC
	INC
	CLC
	ADC #SCREEN_X_TILE_RESOLUTION * 2 - HPPP_WINDOW_WIDTH * 2
	TAX
	LDA @VIRTUAL04
	CLC
	ADC #$2006
	STA __BSS_START__,X
	TXA
	INC
	INC
	STA @TILEARRPTR
	LDA @CHAR_ID
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
	AND #$00FF
	DEC
	ASL
	ASL
	CLC
	ADC #$22A0
	STA @LOCAL03
	LDX #0
	BRA @NAME_ROW_LOOP_CHECK
@WRITE_NAME_TILE:
	TXY
	LDA (@CHAR_ENTRY),Y
	AND #$00FF
	BEQ @WRITE_BLANK_NAME_TILE
	LDA @LOCAL05
	STA @VIRTUAL02
	LDA @LOCAL03
	CLC
	ADC @VIRTUAL02
	STA (@TILEARRPTR)
	INC @TILEARRPTR
	INC @TILEARRPTR
	LDA @LOCAL03
	INC
	STA @LOCAL03
	BRA @AFTER_NAME_TILE
@WRITE_BLANK_NAME_TILE:
	LDA @LOCAL05
	STA @VIRTUAL02
	CLC
	ADC #$2007
	STA (@TILEARRPTR)
	INC @TILEARRPTR
	INC @TILEARRPTR
@AFTER_NAME_TILE:
	INX
@NAME_ROW_LOOP_CHECK:
	CPX #HPPP_WINDOW_WIDTH - 3
	BNE @WRITE_NAME_TILE
	LDA @LOCAL05
	STA @VIRTUAL02
	LDY @LOCAL07
	TYA
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #$2000
	STA (@TILEARRPTR)
	LDX @TILEARRPTR
	INX
	INX
	LDA @VIRTUAL04
	CLC
	ADC #$6006
	STA __BSS_START__,X
	TXA
	INC
	INC
	CLC
	ADC #SCREEN_X_TILE_RESOLUTION * 2 - HPPP_WINDOW_WIDTH * 2
	TAX
	LDA @VIRTUAL04
	CLC
	ADC #$2006
	STA __BSS_START__,X
	TXA
	INC
	INC
	STA @TILEARRPTR
	LDA @CHAR_ID
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
	AND #$00FF
	DEC
	ASL
	ASL
	CLC
	ADC #$22B0
	STA @LOCAL03
.ELSE
	BNE @WRITE_TOP_EDGE_TILE
	LDA @VIRTUAL04
	CLC
	ADC #$6004
	STA __BSS_START__,X
	TXA
	INC
	INC
	CLC
	ADC #SCREEN_X_TILE_RESOLUTION * 2 - HPPP_WINDOW_WIDTH * 2
	TAX
	LDA @VIRTUAL04
	CLC
	ADC #$2006
	STA __BSS_START__,X
	TXA
	INC
	INC
	STA @TILEARRPTR
	LDY #.LOWORD(GAME_STATE) + game_state::party_members
	LDA (@CHAR_ID),Y
	AND #$00FF
	DEC
	ASL
	ASL
	CLC
	ADC #$22A0
	TAY
	STY @LOCAL02
	LDA @CHAR_ENTRY
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL STRLEN
	OPTIMIZED_MULT @VIRTUAL04, 6
	CLC
	ADC #9
	LSR
	LSR
	LSR
	STA @LOCAL01
	LDX #0
	BRA @NAME_ROW_LOOP_CHECK
@WRITE_NAME_TILE:
	LDA @LOCAL01
	BEQ @WRITE_BLANK_NAME_TILE
	LDA @LOCAL05
	STA @VIRTUAL02
	LDY @LOCAL02
	TYA
	CLC
	ADC @VIRTUAL02
	STA (@TILEARRPTR)
	INC @TILEARRPTR
	INC @TILEARRPTR
	INY
	STY @LOCAL02
	LDA @LOCAL01
	DEC
	STA @LOCAL01
	BRA @AFTER_NAME_TILE
@WRITE_BLANK_NAME_TILE:
	LDA @LOCAL05
	STA @VIRTUAL02
	CLC
	ADC #$2007
	STA (@TILEARRPTR)
	INC @TILEARRPTR
	INC @TILEARRPTR
@AFTER_NAME_TILE:
	INX
@NAME_ROW_LOOP_CHECK:
	CPX #HPPP_WINDOW_WIDTH - 3
	BNE @WRITE_NAME_TILE
	LDA @LOCAL05
	STA @VIRTUAL02
	CLC
	ADC @LOCAL07
	CLC
	ADC #$2000
	STA (@TILEARRPTR)
	LDX @TILEARRPTR
	INX
	INX
	LDA @LOCAL06
	STA @VIRTUAL04
	CLC
	ADC #$6006
	STA __BSS_START__,X
	TXA
	INC
	INC
	CLC
	ADC #SCREEN_X_TILE_RESOLUTION * 2 - HPPP_WINDOW_WIDTH * 2
	TAX
	LDA @VIRTUAL04
	CLC
	ADC #$2006
	STA __BSS_START__,X
	TXA
	INC
	INC
	STA @TILEARRPTR
	LDY #.LOWORD(GAME_STATE) + game_state::party_members
	LDA (@CHAR_ID),Y
	AND #$00FF
	DEC
	ASL
	ASL
	CLC
	ADC #$22B0
	TAY
	STY @LOCAL02
	LDA @CHAR_ENTRY
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL STRLEN
	OPTIMIZED_MULT @VIRTUAL04, 6
	CLC
	ADC #9
	LSR
	LSR
	LSR
	STA @LOCAL01
.ENDIF
	LDX #0
	BRA @NAME_ROW2_LOOP_CHECK
@WRITE_NAME_TILE_ROW2:
.IF .DEFINED(JPN)
	TXY
	LDA (@CHAR_ENTRY),Y
	AND #$00FF
	BEQ @WRITE_BLANK_NAME_TILE_ROW2
	LDA @LOCAL03
	CLC
	ADC @VIRTUAL02
	STA (@TILEARRPTR)
	INC @TILEARRPTR
	INC @TILEARRPTR
	LDA @LOCAL03
	INC
	STA @LOCAL03
.ELSE
	LDA @LOCAL01
	BEQ @WRITE_BLANK_NAME_TILE_ROW2
	LDY @LOCAL02
	TYA
	CLC
	ADC @VIRTUAL02
	STA (@TILEARRPTR)
	INC @TILEARRPTR
	INC @TILEARRPTR
	INY
	STY @LOCAL02
	LDA @LOCAL01
	DEC
	STA @LOCAL01
.ENDIF
	BRA @AFTER_NAME_TILE_ROW2
@WRITE_BLANK_NAME_TILE_ROW2:
	LDA @VIRTUAL02
	CLC
	ADC #$2017
	STA (@TILEARRPTR)
	INC @TILEARRPTR
	INC @TILEARRPTR
@AFTER_NAME_TILE_ROW2:
	INX
@NAME_ROW2_LOOP_CHECK:
	CPX #HPPP_WINDOW_WIDTH - 3
	BNE @WRITE_NAME_TILE_ROW2
.IF .DEFINED(JPN)
	LDY @LOCAL07
	TYA
	CLC
	ADC @VIRTUAL02
.ELSE
	LDA @VIRTUAL02
	CLC
	ADC @LOCAL07
.ENDIF
	CLC
	ADC #$2010
	STA (@TILEARRPTR)
	LDX @TILEARRPTR
	INX
	INX
.IF .DEFINED(JPN)
	LDA @VIRTUAL04
.ELSE
	LDA @LOCAL06
	STA @VIRTUAL04
.ENDIF
	CLC
	ADC #$6006
	STA __BSS_START__,X
	TXA
	INC
	INC
	CLC
	ADC #SCREEN_X_TILE_RESOLUTION * 2 - HPPP_WINDOW_WIDTH * 2
	STA @VIRTUAL02
	LDY #char_struct::current_hp_fraction
	LDA (@CHAR_ENTRY),Y
	TAY
.IF .DEFINED(JPN)
	STY @LOCAL05
.ELSE
	STY @LOCAL02
.ENDIF
	LDY #char_struct::current_hp
	LDA (@CHAR_ENTRY),Y
	TAX
	LDA @CHAR_ID
.IF .DEFINED(JPN)
	LDY @LOCAL05
.ELSE
	LDY @LOCAL02
.ENDIF
	JSR FILL_CHARACTER_HP_TILE_BUFFER
	LOADPTR HPPP_WINDOW_TILE_DATA, @VIRTUAL06
	LDA @CHAR_ID
	OPTIMIZED_MULT @VIRTUAL04, 24
	CLC
	ADC #.LOWORD(HPPP_WINDOW_BUFFER)
	TAY
	LDX #2
	STX @LOCAL01
	BRA @HP_ROW_LOOP_CHECK
@HP_ROW_START:
	LDA @LOCAL06
	STA @VIRTUAL04
	CLC
	ADC #$2006
	LDX @VIRTUAL02
	STA __BSS_START__,X
	INC @VIRTUAL02
	INC @VIRTUAL02
	LDA #2
	STA @LOCAL07
	BRA @HP_HEADER_LOOP_CHECK
@WRITE_HP_HEADER_TILE:
	LDA [@VIRTUAL06]
	AND #$00FF
	CLC
	ADC @LOCAL08
	CLC
	ADC #$2000
	LDX @VIRTUAL02
	STA __BSS_START__,X
	INC @VIRTUAL06
	INC @VIRTUAL02
	INC @VIRTUAL02
	LDA @LOCAL07
	DEC
	STA @LOCAL07
@HP_HEADER_LOOP_CHECK:
	BNE @WRITE_HP_HEADER_TILE
	LDA #HPPP_WINDOW_WIDTH - 4
	STA @LOCAL07
	BRA @HP_DIGIT_LOOP_CHECK
@WRITE_HP_DIGIT_TILE:
	LDA __BSS_START__,Y
	CLC
	ADC @LOCAL04
	LDX @VIRTUAL02
	STA __BSS_START__,X
	INY
	INY
	INC @VIRTUAL02
	INC @VIRTUAL02
	LDA @LOCAL07
	DEC
	STA @LOCAL07
@HP_DIGIT_LOOP_CHECK:
	BNE @WRITE_HP_DIGIT_TILE
	LDA @VIRTUAL04
	CLC
	ADC #$6006
	LDX @VIRTUAL02
	STA __BSS_START__,X
	LDA @VIRTUAL02
	INC
	INC
	CLC
	ADC #SCREEN_X_TILE_RESOLUTION * 2 - HPPP_WINDOW_WIDTH * 2
	STA @VIRTUAL02
	LDX @LOCAL01
	DEX
	STX @LOCAL01
@HP_ROW_LOOP_CHECK:
	BNE @HP_ROW_START
	LDY #char_struct::current_pp_fraction
	LDA (@CHAR_ENTRY),Y
	STA @LOCAL00
	LDY #char_struct::current_pp
	LDA (@CHAR_ENTRY),Y
	TAY
	LDA @CHAR_ENTRY
	CLC
	ADC #char_struct::afflictions
	TAX
	LDA @CHAR_ID
	JSR FILL_CHARACTER_PP_TILE_BUFFER
	LDA @CHAR_ID
	OPTIMIZED_MULT @VIRTUAL04, 24
	CLC
	ADC #.LOWORD(HPPP_WINDOW_BUFFER) + hp_pp_window_buffer::pp1
	TAY
	LDX #2
	STX @LOCAL01
	BRA @PP_ROW_LOOP_CHECK
@PP_ROW_START:
	LDA @LOCAL06
	STA @VIRTUAL04
	CLC
	ADC #$2006
	LDX @VIRTUAL02
	STA __BSS_START__,X
	INC @VIRTUAL02
	INC @VIRTUAL02
	LDA #2
	STA @LOCAL07
	BRA @PP_HEADER_LOOP_CHECK
@WRITE_PP_HEADER_TILE:
	LDA [@VIRTUAL06]
	AND #$00FF
	CLC
	ADC @LOCAL08
	CLC
	ADC #$2000
	LDX @VIRTUAL02
	STA __BSS_START__,X
	INC @VIRTUAL06
	INC @VIRTUAL02
	INC @VIRTUAL02
	LDA @LOCAL07
	DEC
	STA @LOCAL07
@PP_HEADER_LOOP_CHECK:
	BNE @WRITE_PP_HEADER_TILE
	LDA #HPPP_WINDOW_WIDTH - 4
	STA @LOCAL07
	BRA @PP_DIGIT_LOOP_CHECK
@WRITE_PP_DIGIT_TILE:
	LDA __BSS_START__,Y
	CLC
	ADC @LOCAL04
	LDX @VIRTUAL02
	STA __BSS_START__,X
	INY
	INY
	INC @VIRTUAL02
	INC @VIRTUAL02
	LDA @LOCAL07
	DEC
	STA @LOCAL07
@PP_DIGIT_LOOP_CHECK:
	BNE @WRITE_PP_DIGIT_TILE
	LDA @VIRTUAL04
	CLC
	ADC #$6006
	LDX @VIRTUAL02
	STA __BSS_START__,X
	LDA @VIRTUAL02
	INC
	INC
	CLC
	ADC #SCREEN_X_TILE_RESOLUTION * 2 - HPPP_WINDOW_WIDTH * 2
	STA @VIRTUAL02
	LDX @LOCAL01
	DEX
	STX @LOCAL01
@PP_ROW_LOOP_CHECK:
	BNE @PP_ROW_START
	LDA @LOCAL06
	STA @VIRTUAL04
	CLC
	ADC #$A004
	LDX @VIRTUAL02
	STA __BSS_START__,X
	LDX @VIRTUAL02
	INX
	INX
	LDY #HPPP_WINDOW_WIDTH - 2
	BRA @BOTTOM_EDGE_LOOP_CHECK
@WRITE_BOTTOM_EDGE_TILE:
	LDA @VIRTUAL04
	CLC
	ADC #$A005
	STA __BSS_START__,X
	INX
	INX
	DEY
@BOTTOM_EDGE_LOOP_CHECK:
	BNE @WRITE_BOTTOM_EDGE_TILE
	LDA @VIRTUAL04
	CLC
	ADC #$E004
	STA __BSS_START__,X
	END_C_FUNCTION
