
FILL_HP_PP_TILE_BUFFER_X:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int
	END_STACK_VARS
	OPTIMIZED_MULT @VIRTUAL04, 24
	CLC
	ADC #.LOWORD(HPPP_WINDOW_BUFFER) + 12
	TAX
	LDA #0
	STA @LOCAL00
	BRA @LOOP_CHECK
@STORE_TILES:
	CLC
	ADC #$264C ;tile ids for top of X
	STA __BSS_START__,X
	LDA @LOCAL00
	CLC
	ADC #$265C ;tile ids for bottom of X
	STA __BSS_START__+6,X
	LDA @LOCAL00
	INC
	STA @LOCAL00
	INX
	INX
@LOOP_CHECK:
	CMP #3
	BCC @STORE_TILES
	END_C_FUNCTION
