
FILL_HP_PP_TILE_BUFFER:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_PARAM_INT16 ;int
	END_STACK_VARS
	STX @VIRTUAL02
	TAX
	CPY #$3000
	BCS @HAS_OVERFLOW
	LDA #0
	STA @LOCAL04
	BRA @AFTER_OVERFLOW
@HAS_OVERFLOW:
	TYA
	SEC
	SBC #$3000
	STA @LOCAL04
@AFTER_OVERFLOW:
	MOVE_INT_CONSTANT $3400, @VIRTUAL0A ;13312/65536 is close to 1/5. 13107/65536 is closer, but more expensive
	MOVE_INT1632 @LOCAL04, @VIRTUAL06
	JSL DIVISION32
	LDA @VIRTUAL06
	TAY
	LDA @VIRTUAL02
	OPTIMIZED_MULT @VIRTUAL04, 12
	STA @VIRTUAL02
	TXA
	OPTIMIZED_MULT @VIRTUAL04, 24
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #.LOWORD(HPPP_WINDOW_BUFFER) + .SIZEOF(hp_pp_window_buffer::hp1) - (1 * 2)
	TAX
	LDA HPPP_WINDOW_DIGIT_BUFFER + 2
	AND #$00FF
	STA @LOCAL03
	LDA HPPP_WINDOW_DIGIT_BUFFER + 1
	AND #$00FF
	STA @VIRTUAL04
	LDA HPPP_WINDOW_DIGIT_BUFFER
	AND #$00FF
	STA @LOCAL02
	LDA @LOCAL03
	LSR
	LSR
	ASL
	ASL
	ASL
	ASL
	STA @VIRTUAL02
	LDA @LOCAL03
	ASL
	ASL
	CLC
	ADC @VIRTUAL02
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #$2600
	STA @VIRTUAL02
	STA __BSS_START__ + hp_pp_window_buffer::hp1,X
	LDA @VIRTUAL02
	CLC
	ADC #$0010
	STA __BSS_START__ + hp_pp_window_buffer::hp2,X
	TXA
	DEC
	DEC
	STA @VIRTUAL02
	STA @LOCAL01
	LDA @VIRTUAL04
	BNE @TENS_NOT_BLANK
	LDA @LOCAL02
	BNE @TENS_NOT_BLANK
	LDX #$0248
	BRA @COMPUTE_TENS_TILE
@TENS_NOT_BLANK:
	LDX #$0200
@COMPUTE_TENS_TILE:
	LDA @LOCAL03
	CMP #9
	BNE @RESET_TENS_CARRY
	CPY #0
	BNE @STORE_TENS_TILE
@RESET_TENS_CARRY:
	LDY #0
@STORE_TENS_TILE:
	LDA @VIRTUAL04
	LSR
	LSR
	ASL
	ASL
	ASL
	ASL
	STA @VIRTUAL02
	LDA @VIRTUAL04
	ASL
	ASL
	CLC
	ADC @VIRTUAL02
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	STX @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #$2400
	LDX @LOCAL01
	STX @VIRTUAL02
	STA __BSS_START__,X
	CLC
	ADC #$0010
	LDX @VIRTUAL02
	STA __BSS_START__ + hp_pp_window_buffer::hp2,X
	LDA @VIRTUAL02
	DEC
	DEC
	STA @LOCAL00
	LDA @LOCAL02
	BNE @HUNDREDS_NOT_BLANK
	LDX #$0248
	BRA @COMPUTE_HUNDREDS_TILE
@HUNDREDS_NOT_BLANK:
	LDX #$0200
@COMPUTE_HUNDREDS_TILE:
	LDA @VIRTUAL04
	CMP #9
	BNE @RESET_HUNDREDS_CARRY
	CPY #0
	BNE @STORE_HUNDREDS_TILE
@RESET_HUNDREDS_CARRY:
	LDY #0
@STORE_HUNDREDS_TILE:
	STY @VIRTUAL04
	LDA @LOCAL02
	LSR
	LSR
	ASL
	ASL
	ASL
	ASL
	STA @VIRTUAL02
	LDA @LOCAL02
	ASL
	ASL
	CLC
	ADC @VIRTUAL02
	CLC
	ADC @VIRTUAL04
	STX @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #$2400
	TAX
	STX @LOCAL02
	PHX
	LDA @LOCAL00
	TAX
	PLA
	STA __BSS_START__ + hp_pp_window_buffer::hp1,X
	LDA @LOCAL00
	PHA
	LDX @LOCAL02
	TXA
	CLC
	ADC #$0010
	PLX
	STA __BSS_START__ + hp_pp_window_buffer::hp2,X
	END_C_FUNCTION
