
TICK_HPPP_METER_N_FRAMES:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL00
	JSR CLEAR_INSTANT_PRINTING
	JSL WINDOW_TICK
	BRA @FRAME_LOOP_CHECK
@UPDATE_FRAME:
	JSL UPDATE_HPPP_METER_AND_RENDER
@FRAME_LOOP_CHECK:
	LDX @LOCAL00
	TXA
	DEX
	STX @LOCAL00
	CMP #0
	BNE @UPDATE_FRAME
	END_C_FUNCTION
