
TOGGLE_HPPP_FLIPOUT_MODE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL04
	LDA HPPP_METER_FLIPOUT_MODE
	BNE @CHECK_RESTORE
	LDA @VIRTUAL04
	BEQ @CHECK_RESTORE
	LDA #0
	STA @VIRTUAL02
	BRA @SAVE_LOOP_CHECK
@SAVE_AND_SET:
	LDA @VIRTUAL02
	ASL
	TAY
	STY @LOCAL01
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	STA @LOCAL00
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::current_hp_target
	TAX
	LDA __BSS_START__,X
	LDY @LOCAL01
	STA HPPP_METER_FLIPOUT_MODE_HP_BACKUPS,Y
	LDA #999
	STA __BSS_START__,X
	LDA @LOCAL00
	TAX
	LDA #999
	STA PARTY_CHARACTERS+char_struct::current_hp,X
	LDA @LOCAL00
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::current_pp_target
	TAX
	LDA __BSS_START__,X
	STA HPPP_METER_FLIPOUT_MODE_PP_BACKUPS,Y
	LDA #0
	STA __BSS_START__,X
	LDA @LOCAL00
	TAX
	STZ PARTY_CHARACTERS+char_struct::current_pp,X
	INC @VIRTUAL02
@SAVE_LOOP_CHECK:
	LDA #PLAYER_CHAR_COUNT
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @SAVE_AND_SET
	BRA @UPDATE_STATE
@CHECK_RESTORE:
	LDA HPPP_METER_FLIPOUT_MODE
	BEQ @UPDATE_STATE
	LDA @VIRTUAL04
	BNE @UPDATE_STATE
	LDA #0
	STA @LOCAL01
	BRA @RESTORE_LOOP_CHECK
@RESTORE_VALUES:
	LDA @LOCAL01
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAY
	LDA @LOCAL01
	ASL
	TAX
	LDA HPPP_METER_FLIPOUT_MODE_HP_BACKUPS,X
	STA PARTY_CHARACTERS+char_struct::current_hp_target,Y
	LDA HPPP_METER_FLIPOUT_MODE_PP_BACKUPS,X
	STA PARTY_CHARACTERS+char_struct::current_pp_target,Y
	LDA @LOCAL01
	INC
	STA @LOCAL01
@RESTORE_LOOP_CHECK:
	STA @VIRTUAL02
	LDA #PLAYER_CHAR_COUNT
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @RESTORE_VALUES
@UPDATE_STATE:
	LDA @VIRTUAL04
	STA HPPP_METER_FLIPOUT_MODE
	JSL RESUME_MUSIC
	END_C_FUNCTION
