
UPDATE_HPPP_METER_AND_RENDER:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	JSL HP_PP_ROLLER
	LDA HPPP_METER_AREA_NEEDS_UPDATE
	BEQ @AFTER_VRAM_UPDATE
	JSR COPY_HPPP_WINDOW_TO_VRAM
	STZ HPPP_METER_AREA_NEEDS_UPDATE
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA UPLOAD_HPPP_METER_TILES
@AFTER_VRAM_UPDATE:
	JSL UPDATE_HPPP_METER_TILES
	JSL RENDER_FRAME_TICK
	RTL
