
GET_ITEM_SUBTYPE:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::type
	TAX
	LDA f:ITEM_CONFIGURATION_TABLE,X
	AND #$00FF
	AND #$000C
	BEQ @SUBTYPE_WEAPON
	CMP #$0004
	BEQ @SUBTYPE_BODY
	CMP #$0008
	BEQ @SUBTYPE_ARMS
	CMP #$000C
	BEQ @SUBTYPE_OTHER
	BRA @SUBTYPE_NONE
@SUBTYPE_WEAPON:
	LDA #$0001
	BRA @RETURN
@SUBTYPE_BODY:
	LDA #$0002
	BRA @RETURN
@SUBTYPE_ARMS:
	LDA #$0003
	BRA @RETURN
@SUBTYPE_OTHER:
	LDA #$0004
	BRA @RETURN
@SUBTYPE_NONE:
	LDA #$0000
@RETURN:
	PLD
	RTL
