
GET_ITEM_SUBTYPE_2:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDY #.SIZEOF(item)
	JSL MULT168
	CLC
	ADC #item::type
	TAX
	LDA f:ITEM_CONFIGURATION_TABLE,X
	AND #$00FF
	AND #$000C
	BEQ @SUBTYPE_1
	CMP #$000C
	BEQ @SUBTYPE_1
	CMP #$0004
	BEQ @SUBTYPE_2
	CMP #$0008
	BEQ @SUBTYPE_3
	BRA @SUBTYPE_0
@SUBTYPE_1:
	LDA #$0001
	BRA @RETURN
@SUBTYPE_2:
	LDA #$0002
	BRA @RETURN
@SUBTYPE_3:
	LDA #$0003
	BRA @RETURN
@SUBTYPE_0:
	LDA #$0000
@RETURN:
	RTL
