
GET_SECTOR_ITEM_TYPE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL LOAD_SECTOR_ATTRS
	TAX
	STX @LOCAL00
	LDA #EVENT_FLAG::FLG_WIN_GIEGU
	JSL GET_EVENT_FLAG
	CMP #0
	BEQ @NO_BICYCLE
	LDX @LOCAL00
	TXA
	AND #$0007
	BNE @NO_BICYCLE
	LDA #ITEM::BICYCLE
	BRA @RETURN
@NO_BICYCLE:
	LDX @LOCAL00
	TXA
	XBA
	AND #$00FF
@RETURN:
	END_C_FUNCTION
