
INIT_ALL_ITEM_TRANSFORMATIONS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDY #0
	STY @LOCAL00
	BRA @LOOP_HEAD
@PROCESS_ENTRY:
	AND #$00FF
	TAX
	LDA #$00FF
	JSL FIND_ITEM_IN_INVENTORY2
	CMP #0
	BEQ @ITEM_NOT_IN_INVENTORY
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	JSL START_ITEM_TRANSFORMATION
	BRA @NEXT_ENTRY
@ITEM_NOT_IN_INVENTORY:
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	JSL START_TIMED_ITEM_TRANSFORMATION
	.A16
@NEXT_ENTRY:
	LDY @LOCAL00
	INY
	STY @LOCAL00
@LOOP_HEAD:
	LOADPTR TIMED_ITEM_TRANSFORMATION_TABLE, @VIRTUAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(timed_item_transformation)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	BNE @PROCESS_ENTRY
	END_C_FUNCTION
