
IS_ITEM_EQUIPPED_BY_ID:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @VIRTUAL02
	TAX
	TXY
	DEY
	STY @LOCAL00
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(char_struct)
	TAX
	LDA PARTY_CHARACTERS + char_struct::equipment + EQUIPMENT_SLOT::WEAPON,X
	AND #$00FF
	BEQ @CHECK_BODY
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TXA
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @CHECK_BODY
	LDA #1
	JMP @RETURN
@CHECK_BODY:
	LDY @LOCAL00
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(char_struct)
	TAX
	LDA PARTY_CHARACTERS + char_struct::equipment + EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	BEQ @CHECK_ARMS
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TXA
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @CHECK_ARMS
	LDA #1
	BRA @RETURN
@CHECK_ARMS:
	LDY @LOCAL00
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(char_struct)
	TAX
	LDA PARTY_CHARACTERS + char_struct::equipment + EQUIPMENT_SLOT::ARMS,X
	AND #$00FF
	BEQ @CHECK_OTHER
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TXA
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @CHECK_OTHER
	LDA #1
	BRA @RETURN
@CHECK_OTHER:
	LDY @LOCAL00
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(char_struct)
	TAX
	LDA PARTY_CHARACTERS + char_struct::equipment + EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	BEQ @NOT_EQUIPPED
	AND #$00FF
	DEC
	STA @VIRTUAL04
	TXA
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS) + char_struct::items
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	CMP @VIRTUAL02
	BNE @NOT_EQUIPPED
	LDA #1
	BRA @RETURN
@NOT_EQUIPPED:
	LDA #0
@RETURN:
	END_C_FUNCTION
