
QUEUE_ITEM_FOR_CHARACTER:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @VIRTUAL04
	STA @VIRTUAL02
	LDY #0
	BRA @CHECK_SLOT_INDEX
@CHECK_SLOT:
	TYA
	CLC
	ADC #.LOWORD(GAME_STATE)
	STA @LOCAL00
	CLC
	ADC #game_state::unknownB6
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	BNE @NEXT_SLOT
	LDA @VIRTUAL04
	SEP #PROC_FLAGS::ACCUM8
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	TAX
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STA a:game_state::unknownB8,X
	BRA @DONE
@NEXT_SLOT:
	INY
@CHECK_SLOT_INDEX:
	CPY #3
	BCC @CHECK_SLOT
@DONE:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
