
REMOVE_ESCARGO_EXPRESS_ITEM:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TAX
	DEX
	SEP #PROC_FLAGS::ACCUM8
	LDA GAME_STATE+game_state::escargo_express_items,X
	STA @VIRTUAL01
	BRA @SHIFT_LOOP_TEST
@SHIFT_ITEM:
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	STA GAME_STATE+game_state::escargo_express_items,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	TAX
@SHIFT_LOOP_TEST:
	SEP #PROC_FLAGS::ACCUM8
	LDA GAME_STATE+game_state::escargo_express_items+1,X
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	AND #$00FF
	BEQ @CLEAR_LAST_SLOT
	TXA
	INC
	STA @LOCAL00
	CMP #36
	BCC @SHIFT_ITEM
@CLEAR_LAST_SLOT:
	SEP #PROC_FLAGS::ACCUM8
	STZ GAME_STATE+game_state::escargo_express_items,X
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL01
	AND #$00FF
	END_C_FUNCTION
