
START_TIMED_ITEM_TRANSFORMATION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	LDY #0
	STY @LOCAL03
	BRA @FIND_TABLE_ENTRY
@NEXT_TABLE_ENTRY:
	INY
	STY @LOCAL03
@FIND_TABLE_ENTRY:
	REP #PROC_FLAGS::ACCUM8
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(timed_item_transformation)
	TAX
	LDA f:TIMED_ITEM_TRANSFORMATION_TABLE,X
	AND #$00FF
	BEQ @ENTRY_FOUND
	SEP #PROC_FLAGS::ACCUM8
	CMP @VIRTUAL00
	BNE @NEXT_TABLE_ENTRY
@ENTRY_FOUND:
	REP #PROC_FLAGS::ACCUM8
	TYA
	JSL CANCEL_ITEM_TRANSFORMATION
	LDX #0
	STX @LOCAL02
	BRA @PARTY_LOOP_HEAD
@CHECK_PARTY_MEMBER:
.IF .DEFINED(JPN)
	TXA
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
.ELSE
	LDA GAME_STATE + game_state::party_members,X
.ENDIF
	AND #$00FF
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)
	STA @VIRTUAL04
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL01
	BRA @ITEM_LOOP_HEAD
@CHECK_ITEM:
	LDA @VIRTUAL00
	AND #$00FF
	STA @VIRTUAL02
	LDA @LOCAL00
	CMP @VIRTUAL02
	BNE @NEXT_ITEM
	LDY @LOCAL03
	TYA
	JSL INITIALIZE_ITEM_TRANSFORMATION
	BRA @RETURN
@NEXT_ITEM:
	LDA @LOCAL01
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL01
@ITEM_LOOP_HEAD:
	LDA #.SIZEOF(char_struct::items)
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @NEXT_PARTY_MEMBER
	LDA @VIRTUAL04
	CLC
	ADC @VIRTUAL02
	TAX
	LDA a:char_struct::items,X
	AND #$00FF
	STA @LOCAL00
	BNE @CHECK_ITEM
@NEXT_PARTY_MEMBER:
	LDX @LOCAL02
	INX
	STX @LOCAL02
@PARTY_LOOP_HEAD:
	LDA GAME_STATE + game_state::player_controlled_party_count
	AND #$00FF
	STA @VIRTUAL02
	TXA
	CMP @VIRTUAL02
	BCC @CHECK_PARTY_MEMBER
@RETURN:
	END_C_FUNCTION
