
START_ITEM_TRANSFORMATION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	SEP #PROC_FLAGS::ACCUM8
	STA @VIRTUAL00
	LDX #0
	STX @LOCAL00
	BRA @LOOP_HEAD
@CHECK_MATCH:
	SEP #PROC_FLAGS::ACCUM8
	CMP @VIRTUAL00
	BNE @NEXT_ENTRY
	LDX @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	TXA
	JSL IS_VALID_ITEM_TRANSFORMATION
	CMP #0
	BNE @RETURN
	LDX @LOCAL00
	TXA
	JSL INITIALIZE_ITEM_TRANSFORMATION
	BRA @RETURN
@NEXT_ENTRY:
	LDX @LOCAL00
	INX
	STX @LOCAL00
@LOOP_HEAD:
	REP #PROC_FLAGS::ACCUM8
	TXA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(timed_item_transformation)
	TAX
	LDA f:TIMED_ITEM_TRANSFORMATION_TABLE + timed_item_transformation::item,X
	AND #$00FF
	BNE @CHECK_MATCH
@RETURN:
	END_C_FUNCTION
