
FIND_BATTLE_SPRITE_FOR_ENEMY:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int enemyID
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	TAX
	STX @LOCAL01
	LDA #0
	STA @LOCAL00
	BRA @LOOP_CHECK
@LOOP_BODY:
	ASL
	PHA
	LDX @LOCAL01
	TXA
	PLX
	CMP CURRENT_BATTLE_SPRITE_ENEMY_IDS,X
	BNE @NEXT
	LDA @LOCAL00
	BRA @RETURN
@NEXT:
	LDA @LOCAL00
	INC
	STA @LOCAL00
@LOOP_CHECK:
	CMP #4
	BCC @LOOP_BODY
	LDA #0
@RETURN:
	END_C_FUNCTION
