.MACRO EVENT_END
	.BYTE $00
.ENDMACRO

.MACRO EVENT_LOOP arg
	.BYTE $01, arg
.ENDMACRO

.MACRO EVENT_LOOP_END
	.BYTE $02
.ENDMACRO

.MACRO EVENT_LONGJUMP arg
	.BYTE $03
	PTR3 arg
.ENDMACRO

.MACRO EVENT_LONGCALL arg
	.BYTE $04
	PTR3 arg
.ENDMACRO

.MACRO EVENT_LONG_RETURN
	.BYTE $05
.ENDMACRO

.MACRO EVENT_PAUSE arg
	.BYTE $06, arg
.ENDMACRO

.MACRO EVENT_START_TASK arg
	.BYTE $07
	.WORD arg
.ENDMACRO

.MACRO EVENT_SET_TICK_CALLBACK arg
	.BYTE $08
	PTR3 arg
.ENDMACRO

.MACRO EVENT_HALT
	.BYTE $09
.ENDMACRO

.MACRO EVENT_SHORTCALL_CONDITIONAL arg
	.BYTE $0A
	.WORD arg
.ENDMACRO

.MACRO EVENT_SHORTCALL_CONDITIONAL_NOT arg
	.BYTE $0B
	.WORD arg
.ENDMACRO

.MACRO EVENT_END_TASK
	.BYTE $0C
.ENDMACRO

.MACRO EVENT_SET_VAR arg1, arg2
	.BYTE $0E, arg1
	.WORD arg2
.ENDMACRO

.MACRO EVENT_CLEAR_TICK_CALLBACK
	.BYTE $0F
.ENDMACRO

.MACRO EVENT_SWITCH_JUMP_TEMPVAR arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12
	.BYTE $10
	.BYTE .PARAMCOUNT
	.IF(.PARAMCOUNT > 0)
		.WORD arg1
	.ENDIF
	.IF(.PARAMCOUNT > 1)
		.WORD arg2
	.ENDIF
	.IF(.PARAMCOUNT > 2)
		.WORD arg3
	.ENDIF
	.IF(.PARAMCOUNT > 3)
		.WORD arg4
	.ENDIF
	.IF(.PARAMCOUNT > 4)
		.WORD arg5
	.ENDIF
	.IF(.PARAMCOUNT > 5)
		.WORD arg6
	.ENDIF
	.IF(.PARAMCOUNT > 6)
		.WORD arg7
	.ENDIF
	.IF(.PARAMCOUNT > 7)
		.WORD arg8
	.ENDIF
	.IF(.PARAMCOUNT > 8)
		.WORD arg9
	.ENDIF
	.IF(.PARAMCOUNT > 9)
		.WORD arg10
	.ENDIF
	.IF(.PARAMCOUNT > 10)
		.WORD arg11
	.ENDIF
.ENDMACRO

.MACRO EVENT_SWITCH_CALL_TEMPVAR arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12
	.BYTE $11
	.BYTE .PARAMCOUNT
	.IF(.PARAMCOUNT > 0)
		.WORD arg1
	.ENDIF
	.IF(.PARAMCOUNT > 1)
		.WORD arg2
	.ENDIF
	.IF(.PARAMCOUNT > 2)
		.WORD arg3
	.ENDIF
	.IF(.PARAMCOUNT > 3)
		.WORD arg4
	.ENDIF
	.IF(.PARAMCOUNT > 4)
		.WORD arg5
	.ENDIF
	.IF(.PARAMCOUNT > 5)
		.WORD arg6
	.ENDIF
	.IF(.PARAMCOUNT > 6)
		.WORD arg7
	.ENDIF
	.IF(.PARAMCOUNT > 7)
		.WORD arg8
	.ENDIF
	.IF(.PARAMCOUNT > 8)
		.WORD arg9
	.ENDIF
	.IF(.PARAMCOUNT > 9)
		.WORD arg10
	.ENDIF
	.IF(.PARAMCOUNT > 10)
		.WORD arg11
	.ENDIF
.ENDMACRO

.MACRO EVENT_WRITE_BYTE_WRAM arg1, arg2
	.BYTE $12
	.WORD arg1
	.BYTE arg2
.ENDMACRO

.MACRO EVENT_END_LAST_TASK
	.BYTE $13
.ENDMACRO

.MACRO EVENT_BINOP arg1, arg2, arg3
	.BYTE $14, arg1, arg2
	.WORD arg3
.ENDMACRO

.MACRO EVENT_AND entry, operand
	EVENT_BINOP entry, $00, operand
.ENDMACRO

.MACRO EVENT_OR entry, operand
	EVENT_BINOP entry, $01, operand
.ENDMACRO

.MACRO EVENT_ADD entry, operand
	EVENT_BINOP entry, $02, operand
.ENDMACRO

.MACRO EVENT_XOR entry, operand
	EVENT_BINOP entry, $03, operand
.ENDMACRO

.MACRO EVENT_WRITE_WORD_WRAM arg1, arg2
	.BYTE $15
	.WORD arg1
	.WORD arg2
.ENDMACRO

.MACRO EVENT_WRITE_DWORD_WRAM arg1, arg2
	.BYTE $15
	.WORD arg1
	.WORD .LOWORD(arg2)
	.BYTE $15
	.WORD arg1 + 2
	.WORD .HIWORD(arg2)
.ENDMACRO

.MACRO EVENT_BREAK_IF_FALSE arg
	.BYTE $16
	.WORD arg
.ENDMACRO

.MACRO EVENT_BREAK_IF_TRUE arg
	.BYTE $17
	.WORD arg
.ENDMACRO

.MACRO EVENT_BINOP_WRAM arg1, arg2, arg3
	.BYTE $18
	.WORD arg1
	.BYTE arg2, arg3
.ENDMACRO

.MACRO EVENT_AND_WRAM address, operand
	EVENT_BINOP_WRAM address, $00, operand
.ENDMACRO

.MACRO EVENT_OR_WRAM address, operand
	EVENT_BINOP_WRAM address, $01, operand
.ENDMACRO

.MACRO EVENT_ADD_WRAM address, operand
	EVENT_BINOP_WRAM address, $02, operand
.ENDMACRO

.MACRO EVENT_XOR_WRAM address, operand
	EVENT_BINOP_WRAM address, $03, operand
.ENDMACRO

.MACRO EVENT_SHORTJUMP arg
	.BYTE $19
	.WORD arg
.ENDMACRO

.MACRO EVENT_SHORTCALL arg
	.BYTE $1A
	.WORD arg
.ENDMACRO

.MACRO EVENT_SHORT_RETURN
	.BYTE $1B
.ENDMACRO

.MACRO EVENT_SET_ANIMATION_POINTER arg
	.BYTE $1C
	PTR3 arg
.ENDMACRO

.MACRO EVENT_WRITE_WORD_TEMPVAR arg
	.BYTE $1D
	.WORD arg
.ENDMACRO

.MACRO EVENT_WRITE_WRAM_TEMPVAR arg
	.BYTE $1E
	.WORD arg
.ENDMACRO

.MACRO EVENT_WRITE_TEMPVAR_TO_VAR arg
	.BYTE $1F, arg
.ENDMACRO

.MACRO EVENT_WRITE_VAR_TO_TEMPVAR arg
	.BYTE $20,  arg
.ENDMACRO

.MACRO EVENT_WRITE_VAR_TO_WAIT_TIMER arg
	.BYTE $21,  arg
.ENDMACRO

.MACRO EVENT_SET_DRAW_CALLBACK arg
	.BYTE $22
	.WORD arg
.ENDMACRO

.MACRO EVENT_SET_POSITION_CHANGE_CALLBACK arg
	.BYTE $23
	.WORD  arg
.ENDMACRO

.MACRO EVENT_LOOP_TEMPVAR
	.BYTE $24
.ENDMACRO

.MACRO EVENT_SET_PHYSICS_CALLBACK arg
	.BYTE $25
	.WORD arg
.ENDMACRO

.MACRO EVENT_SET_ANIMATION_FRAME_VAR arg
	.BYTE $26,  arg
.ENDMACRO

.MACRO EVENT_BINOP_TEMPVAR arg, arg2
	.BYTE $27,  arg
	.WORD arg2
.ENDMACRO

.MACRO EVENT_AND_TEMPVAR operand
	EVENT_BINOP_TEMPVAR $00, operand
.ENDMACRO

.MACRO EVENT_OR_TEMPVAR operand
	EVENT_BINOP_TEMPVAR $01, operand
.ENDMACRO

.MACRO EVENT_ADD_TEMPVAR operand
	EVENT_BINOP_TEMPVAR $02, operand
.ENDMACRO

.MACRO EVENT_XOR_TEMPVAR operand
	EVENT_BINOP_TEMPVAR $03, operand
.ENDMACRO

.MACRO EVENT_SET_X arg
	.BYTE $28
	.WORD arg
.ENDMACRO

.MACRO EVENT_SET_Y arg
	.BYTE $29
	.WORD arg
.ENDMACRO

.MACRO EVENT_SET_Z arg
	.BYTE $2A
	.WORD arg
.ENDMACRO

.MACRO EVENT_SET_X_RELATIVE arg
	.BYTE $2B
	.WORD arg
.ENDMACRO

.MACRO EVENT_SET_Y_RELATIVE arg
	.BYTE $2C
	.WORD arg
.ENDMACRO

.MACRO EVENT_SET_Z_RELATIVE arg
	.BYTE $2D
	.WORD arg
.ENDMACRO

.MACRO EVENT_SET_X_VELOCITY_RELATIVE arg
	.BYTE $2E
	.WORD arg
.ENDMACRO

.MACRO EVENT_SET_Y_VELOCITY_RELATIVE arg
	.BYTE $2F
	.WORD arg
.ENDMACRO

.MACRO EVENT_SET_Z_VELOCITY_RELATIVE arg
	.BYTE $30
	.WORD arg
.ENDMACRO

.MACRO EVENT_SET_VELOCITIES_ZERO
	.BYTE $39
.ENDMACRO

.MACRO EVENT_SET_ANIMATION arg
	.BYTE $3B, arg
.ENDMACRO

.MACRO EVENT_NEXT_ANIMATION_FRAME
	.BYTE $3C
.ENDMACRO

.MACRO EVENT_PREV_ANIMATION_FRAME
	.BYTE $3D
.ENDMACRO

.MACRO EVENT_SKIP_N_ANIMATION_FRAMES arg
	.BYTE $3E, arg
.ENDMACRO

.MACRO EVENT_SET_X_VELOCITY arg
	.BYTE $3F
	.WORD arg
.ENDMACRO

.MACRO EVENT_SET_Y_VELOCITY arg
	.BYTE $40
	.WORD arg
.ENDMACRO

.MACRO EVENT_SET_Z_VELOCITY arg
	.BYTE $41
	.WORD arg
.ENDMACRO

.MACRO EVENT_CALLROUTINE arg, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21, arg22
	.BYTE $42
	PTR3 arg
	.IF(.PARAMCOUNT > 1)
		.BYTE arg2
	.ENDIF
	.IF(.PARAMCOUNT > 2)
		.BYTE arg3
	.ENDIF
	.IF(.PARAMCOUNT > 3)
		.BYTE arg4
	.ENDIF
	.IF(.PARAMCOUNT > 4)
		.BYTE arg5
	.ENDIF
	.IF(.PARAMCOUNT > 5)
		.BYTE arg6
	.ENDIF
	.IF(.PARAMCOUNT > 6)
		.BYTE arg7
	.ENDIF
	.IF(.PARAMCOUNT > 7)
		.BYTE arg8
	.ENDIF
	.IF(.PARAMCOUNT > 8)
		.BYTE arg9
	.ENDIF
	.IF(.PARAMCOUNT > 9)
		.BYTE arg10
	.ENDIF
	.IF(.PARAMCOUNT > 10)
		.BYTE arg11
	.ENDIF
	.IF(.PARAMCOUNT > 11)
		.BYTE arg12
	.ENDIF
	.IF(.PARAMCOUNT > 12)
		.BYTE arg13
	.ENDIF
	.IF(.PARAMCOUNT > 13)
		.BYTE arg14
	.ENDIF
	.IF(.PARAMCOUNT > 14)
		.BYTE arg15
	.ENDIF
	.IF(.PARAMCOUNT > 15)
		.BYTE arg16
	.ENDIF
	.IF(.PARAMCOUNT > 16)
		.BYTE arg17
	.ENDIF
	.IF(.PARAMCOUNT > 17)
		.BYTE arg18
	.ENDIF
	.IF(.PARAMCOUNT > 18)
		.BYTE arg19
	.ENDIF
	.IF(.PARAMCOUNT > 19)
		.BYTE arg20
	.ENDIF
	.IF(.PARAMCOUNT > 20)
		.BYTE arg21
	.ENDIF
	.IF(.PARAMCOUNT > 21)
		.BYTE arg22
	.ENDIF
.ENDMACRO

.MACRO EVENT_EX_CALLROUTINE ex, arg, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg20, arg21, arg22
	.BYTE $F0+ex
	PTR3 arg
	.IF(.PARAMCOUNT > 2)
		.BYTE arg2
	.ENDIF
	.IF(.PARAMCOUNT > 3)
		.BYTE arg3
	.ENDIF
	.IF(.PARAMCOUNT > 4)
		.BYTE arg4
	.ENDIF
	.IF(.PARAMCOUNT > 5)
		.BYTE arg5
	.ENDIF
	.IF(.PARAMCOUNT > 6)
		.BYTE arg6
	.ENDIF
	.IF(.PARAMCOUNT > 7)
		.BYTE arg7
	.ENDIF
	.IF(.PARAMCOUNT > 8)
		.BYTE arg8
	.ENDIF
	.IF(.PARAMCOUNT > 9)
		.BYTE arg9
	.ENDIF
	.IF(.PARAMCOUNT > 10)
		.BYTE arg10
	.ENDIF
	.IF(.PARAMCOUNT > 11)
		.BYTE arg11
	.ENDIF
	.IF(.PARAMCOUNT > 12)
		.BYTE arg12
	.ENDIF
	.IF(.PARAMCOUNT > 13)
		.BYTE arg13
	.ENDIF
	.IF(.PARAMCOUNT > 14)
		.BYTE arg14
	.ENDIF
	.IF(.PARAMCOUNT > 15)
		.BYTE arg15
	.ENDIF
	.IF(.PARAMCOUNT > 16)
		.BYTE arg16
	.ENDIF
	.IF(.PARAMCOUNT > 17)
		.BYTE arg17
	.ENDIF
	.IF(.PARAMCOUNT > 18)
		.BYTE arg18
	.ENDIF
	.IF(.PARAMCOUNT > 19)
		.BYTE arg19
	.ENDIF
	.IF(.PARAMCOUNT > 20)
		.BYTE arg20
	.ENDIF
	.IF(.PARAMCOUNT > 21)
		.BYTE arg21
	.ENDIF
	.IF(.PARAMCOUNT > 22)
		.BYTE arg22
	.ENDIF
.ENDMACRO

.MACRO EVENT_SET_PRIORITY arg
	.BYTE $43, arg
.ENDMACRO

.MACRO EVENT_WRITE_TEMPVAR_WAITTIMER
	.BYTE $44
.ENDMACRO

.MACRO EVENT_TEST_EVENT_FLAG arg
	EVENT_CALLROUTINE MOVEMENT_CMD_GET_EVENT_FLAG, .LOBYTE(arg), .HIBYTE(arg)
.ENDMACRO

.MACRO EVENT_QUEUE_TEXT arg
	EVENT_CALLROUTINE MOVEMENT_QUEUE_INTERACTION, .BANKBYTE(arg), 0, .LOBYTE(arg), .HIBYTE(arg)
.ENDMACRO

.MACRO EVENT_DISPLAY_TEXT_IMMEDIATELY arg
	EVENT_CALLROUTINE MOVEMENT_DISPLAY_TEXT, .BANKBYTE(arg), 0, .LOBYTE(arg), .HIBYTE(arg)
.ENDMACRO

.MACRO EVENT_LOAD_BATTLEBGS arg, arg2
	EVENT_CALLROUTINE MOVEMENT_LOAD_BATTLEBG, .LOBYTE(arg), .HIBYTE(arg), .LOBYTE(arg2), .HIBYTE(arg2)
.ENDMACRO

.MACRO EVENT_STORE_ENTITY_POSITION_TO_VARS
	EVENT_CALLROUTINE STORE_ENTITY_POSITION_TO_VARS
.ENDMACRO

.MACRO EVENT_SPAWN_ENTITY arg
	EVENT_CALLROUTINE SPAWN_ENTITY, .LOBYTE(arg), .HIBYTE(arg)
.ENDMACRO

.MACRO EVENT_RENDER_ENTITY_SPRITE_ME1
	EVENT_CALLROUTINE RENDER_ENTITY_SPRITE_MOVEMENT_ENTRY_1
.ENDMACRO

.MACRO EVENT_RENDER_ENTITY_SPRITE_ME2
	EVENT_CALLROUTINE RENDER_ENTITY_SPRITE_MOVEMENT_ENTRY_2
.ENDMACRO

.MACRO EVENT_RENDER_ENTITY_SPRITE_ME3
	EVENT_CALLROUTINE RENDER_ENTITY_SPRITE_ENTRY3
.ENDMACRO

.MACRO EVENT_SET_DIRECTION
	EVENT_CALLROUTINE SET_DIRECTION
.ENDMACRO

.MACRO EVENT_RELOAD_MAP
	EVENT_CALLROUTINE RELOAD_MAP
.ENDMACRO

.MACRO EVENT_INITIALIZE_YOUR_SANCTUARY_DISPLAY
	EVENT_CALLROUTINE INITIALIZE_YOUR_SANCTUARY_DISPLAY
.ENDMACRO

.MACRO EVENT_DECOMP_ITOI_PRODUCTION
	EVENT_CALLROUTINE DECOMP_ITOI_PRODUCTION
.ENDMACRO

.MACRO EVENT_DECOMP_NINTENDO_PRESENTATION
	EVENT_CALLROUTINE DECOMP_NINTENDO_PRESENTATION
.ENDMACRO

.MACRO EVENT_LOAD_DEBUG_CURSOR_GRAPHICS
	EVENT_CALLROUTINE LOAD_DEBUG_CURSOR_GRAPHICS
.ENDMACRO

.MACRO EVENT_SRAM_CHECK_ROUTINE_CHECKSUM
	EVENT_CALLROUTINE SRAM_CHECK_ROUTINE_CHECKSUM
.ENDMACRO

.MACRO EVENT_DISPLAY_ANTI_PIRACY_SCREEN
	EVENT_CALLROUTINE DISPLAY_ANTI_PIRACY_SCREEN
.ENDMACRO

.MACRO EVENT_INFLICT_SUNSTROKE_CHECK
	EVENT_CALLROUTINE INFLICT_SUNSTROKE_CHECK
.ENDMACRO

.MACRO EVENT_RAND
	EVENT_CALLROUTINE RAND
.ENDMACRO

.MACRO EVENT_UNDRAW_FLYOVER_TEXT
	EVENT_CALLROUTINE UNDRAW_FLYOVER_TEXT
.ENDMACRO

.MACRO EVENT_DEALLOCATE_ENTITY_SPRITE
	EVENT_CALLROUTINE DEALLOCATE_ENTITY_SPRITE
.ENDMACRO

.MACRO EVENT_INIT_PARTY_POSITION_BUFFER
	EVENT_CALLROUTINE INIT_PARTY_POSITION_BUFFER
.ENDMACRO

.MACRO EVENT_CHECK_ENEMY_MOVEMENT_OBSTACLES
	EVENT_CALLROUTINE CHECK_ENEMY_MOVEMENT_OBSTACLES
.ENDMACRO

.MACRO EVENT_CHECK_NPC_PLAYER_OBSTACLES
	EVENT_CALLROUTINE CHECK_NPC_PLAYER_OBSTACLES
.ENDMACRO

.MACRO EVENT_RESTORE_ENTITY_CALLBACK_FLAGS
	EVENT_CALLROUTINE RESTORE_ENTITY_CALLBACK_FLAGS
.ENDMACRO

.MACRO EVENT_RAND_HIGH_BYTE
	EVENT_CALLROUTINE RAND_HIGH_BYTE
.ENDMACRO

.MACRO EVENT_CHECK_PROSPECTIVE_NPC_COLLISION
	EVENT_CALLROUTINE CHECK_PROSPECTIVE_NPC_COLLISION
.ENDMACRO

.MACRO EVENT_ENTITY_COORDS_RELATIVE_TO_BG3
	EVENT_CALLROUTINE ENTITY_COORDS_RELATIVE_TO_BG3
.ENDMACRO

.MACRO EVENT_ENABLE_ALL_ENTITIES
	EVENT_CALLROUTINE ENABLE_ALL_ENTITIES
.ENDMACRO

.MACRO EVENT_DISABLE_OTHER_ENTITY_CALLBACKS
	EVENT_CALLROUTINE DISABLE_OTHER_ENTITY_CALLBACKS
.ENDMACRO

.MACRO EVENT_RENDER_ENTITY_SPRITE_MOVEMENT_ENTRY_1
	EVENT_CALLROUTINE RENDER_ENTITY_SPRITE_MOVEMENT_ENTRY_1
.ENDMACRO

.MACRO EVENT_RENDER_ENTITY_SPRITE_MOVEMENT_ENTRY_2
	EVENT_CALLROUTINE RENDER_ENTITY_SPRITE_MOVEMENT_ENTRY_2
.ENDMACRO

.MACRO EVENT_RENDER_ENTITY_SPRITE_MOVEMENT_ENTRY_3
	EVENT_CALLROUTINE RENDER_ENTITY_SPRITE_MOVEMENT_ENTRY_3
.ENDMACRO

.MACRO EVENT_RENDER_ENTITY_SPRITE_ENTRY3
	EVENT_CALLROUTINE RENDER_ENTITY_SPRITE_ENTRY3
.ENDMACRO

.MACRO EVENT_GET_ENTITY_DIRECTION
	EVENT_CALLROUTINE GET_ENTITY_DIRECTION
.ENDMACRO

.MACRO EVENT_GET_ENTITY_MOVEMENT_SPEED
	EVENT_CALLROUTINE GET_ENTITY_MOVEMENT_SPEED
.ENDMACRO

.MACRO EVENT_IS_ENTITY_COLLISION_ENABLED
	EVENT_CALLROUTINE IS_ENTITY_COLLISION_ENABLED
.ENDMACRO

.MACRO EVENT_DISABLE_CURRENT_ENTITY_COLLISION
	EVENT_CALLROUTINE DISABLE_CURRENT_ENTITY_COLLISION
.ENDMACRO

.MACRO EVENT_CLEAR_CURRENT_ENTITY_COLLISION
	EVENT_CALLROUTINE CLEAR_CURRENT_ENTITY_COLLISION
.ENDMACRO

.MACRO EVENT_DISABLE_CURRENT_ENTITY_COLLISION2
	EVENT_CALLROUTINE DISABLE_CURRENT_ENTITY_COLLISION2
.ENDMACRO

.MACRO EVENT_CLEAR_CURRENT_ENTITY_COLLISION2
	EVENT_CALLROUTINE CLEAR_CURRENT_ENTITY_COLLISION2
.ENDMACRO

.MACRO EVENT_MOVE_TOWARD_TARGET_CALLBACK
	EVENT_CALLROUTINE MOVE_TOWARD_TARGET_CALLBACK
.ENDMACRO

.MACRO EVENT_MOVE_TOWARD_TARGET_REVERSED_CALLBACK
	EVENT_CALLROUTINE MOVE_TOWARD_TARGET_REVERSED_CALLBACK
.ENDMACRO

.MACRO EVENT_MOVE_TOWARD_TARGET_NO_SPRITE_CALLBACK
	EVENT_CALLROUTINE MOVE_TOWARD_TARGET_NO_SPRITE_CALLBACK
.ENDMACRO

.MACRO EVENT_UPDATE_DIRECTION_VELOCITY_CALLBACK
	EVENT_CALLROUTINE UPDATE_DIRECTION_VELOCITY_CALLBACK
.ENDMACRO

.MACRO EVENT_PREPARE_NEW_ENTITY_AT_SELF
	EVENT_CALLROUTINE ACTIONSCRIPT_PREPARE_NEW_ENTITY_AT_SELF
.ENDMACRO

.MACRO EVENT_PREPARE_NEW_ENTITY_AT_PARTY_LEADER
	EVENT_CALLROUTINE ACTIONSCRIPT_PREPARE_NEW_ENTITY_AT_PARTY_LEADER
.ENDMACRO

.MACRO EVENT_FORCE_RENDER_ENTITY_SPRITE
	EVENT_CALLROUTINE FORCE_RENDER_ENTITY_SPRITE
.ENDMACRO

.MACRO EVENT_MOVEMENT_CMD_RETURN_2
	EVENT_CALLROUTINE MOVEMENT_CMD_RETURN_2
.ENDMACRO

.MACRO EVENT_MOVEMENT_CMD_CLEAR_LOOP_COUNTER
	EVENT_CALLROUTINE MOVEMENT_CMD_CLEAR_LOOP_COUNTER
.ENDMACRO

.MACRO EVENT_SETUP_DELIVERY_PATH_REVERSE
	EVENT_CALLROUTINE SETUP_DELIVERY_PATH_REVERSE
.ENDMACRO

.MACRO EVENT_SETUP_DELIVERY_PATH_FROM_ENTITY
	EVENT_CALLROUTINE SETUP_DELIVERY_PATH_FROM_ENTITY
.ENDMACRO

.MACRO EVENT_SET_CURRENT_NPC_DIRECTION_FROM_EVENT_FLAG
	EVENT_CALLROUTINE SET_CURRENT_NPC_DIRECTION_FROM_EVENT_FLAG
.ENDMACRO

.MACRO EVENT_GET_LEADER_MOVED_FLAG
	EVENT_CALLROUTINE GET_LEADER_MOVED_FLAG
.ENDMACRO

.MACRO EVENT_CHECK_ENTITY_CAN_PURSUE
	EVENT_CALLROUTINE CHECK_ENTITY_CAN_PURSUE
.ENDMACRO

.MACRO EVENT_CHECK_ENTITY_CAN_PURSUE_SHORT
	EVENT_CALLROUTINE CHECK_ENTITY_CAN_PURSUE_SHORT
.ENDMACRO

.MACRO EVENT_CALCULATE_DIRECTION_TO_LEADER
	EVENT_CALLROUTINE CALCULATE_DIRECTION_TO_LEADER
.ENDMACRO

.MACRO EVENT_GET_DIRECTION_ROTATED_CLOCKWISE
	EVENT_CALLROUTINE GET_DIRECTION_ROTATED_CLOCKWISE
.ENDMACRO

.MACRO EVENT_IS_ENTITY_NEAR_LEADER
	EVENT_CALLROUTINE IS_ENTITY_NEAR_LEADER
.ENDMACRO

.MACRO EVENT_UPDATE_ENTITY_SURFACE_FLAGS
	EVENT_CALLROUTINE UPDATE_ENTITY_SURFACE_FLAGS
.ENDMACRO

.MACRO EVENT_SET_ENTITY_DIRECTION_VELOCITY
	EVENT_CALLROUTINE SET_ENTITY_DIRECTION_VELOCITY
.ENDMACRO

.MACRO EVENT_CALCULATE_TRAVEL_FRAMES
	EVENT_CALLROUTINE CALCULATE_TRAVEL_FRAMES
.ENDMACRO

.MACRO EVENT_CALCULATE_TRAVEL_TIME_TO_TARGET
	EVENT_CALLROUTINE CALCULATE_TRAVEL_TIME_TO_TARGET
.ENDMACRO

.MACRO EVENT_INIT_BUTTERFLY_MOVEMENT
	EVENT_CALLROUTINE INIT_BUTTERFLY_MOVEMENT
.ENDMACRO

.MACRO EVENT_UPDATE_BUTTERFLY_MOVEMENT
	EVENT_CALLROUTINE UPDATE_BUTTERFLY_MOVEMENT
.ENDMACRO

.MACRO EVENT_STEER_ENTITY_TOWARD_DIRECTION
	EVENT_CALLROUTINE STEER_ENTITY_TOWARD_DIRECTION
.ENDMACRO

.MACRO EVENT_CHECK_ENTITY_COLLISION_AHEAD
	EVENT_CALLROUTINE CHECK_ENTITY_COLLISION_AHEAD
.ENDMACRO

.MACRO EVENT_ADVANCE_ENTITY_TOWARD_LEADER
	EVENT_CALLROUTINE ADVANCE_ENTITY_TOWARD_LEADER
.ENDMACRO

.MACRO EVENT_CHECK_ENTITY_ENEMY_COLLISION
	EVENT_CALLROUTINE CHECK_ENTITY_ENEMY_COLLISION
.ENDMACRO

.MACRO EVENT_IS_BATTLE_PENDING
	EVENT_CALLROUTINE IS_BATTLE_PENDING
.ENDMACRO

.MACRO EVENT_HANDLE_ENEMY_CONTACT
	EVENT_CALLROUTINE HANDLE_ENEMY_CONTACT
.ENDMACRO

.MACRO EVENT_DISABLE_OTHER_ENTITY_UPDATES
	EVENT_CALLROUTINE DISABLE_OTHER_ENTITY_UPDATES
.ENDMACRO

.MACRO EVENT_SAVE_ENTITY_POSITION
	EVENT_CALLROUTINE SAVE_ENTITY_POSITION
.ENDMACRO

.MACRO EVENT_RESTORE_ENTITY_ACTIONSCRIPT_POSITION
	EVENT_CALLROUTINE RESTORE_ENTITY_ACTIONSCRIPT_POSITION
.ENDMACRO

.MACRO EVENT_ADVANCE_ENTITY_PATH_POINT
	EVENT_CALLROUTINE ADVANCE_ENTITY_PATH_POINT
.ENDMACRO

.MACRO EVENT_DECOMPRESS_TITLE_DATA
	EVENT_CALLROUTINE DECOMPRESS_TITLE_DATA
.ENDMACRO

.MACRO EVENT_LOAD_TITLE_SCREEN_PALETTE
	EVENT_CALLROUTINE LOAD_TITLE_SCREEN_PALETTE
.ENDMACRO

.MACRO EVENT_LOAD_FILE_SELECT_PALETTES
	EVENT_CALLROUTINE LOAD_FILE_SELECT_PALETTES
.ENDMACRO

.MACRO EVENT_SET_ACTIONSCRIPT_STATE_PAUSED
	EVENT_CALLROUTINE SET_ACTIONSCRIPT_STATE_PAUSED
.ENDMACRO

.MACRO EVENT_CYCLE_ENTITY_PALETTE
	EVENT_CALLROUTINE CYCLE_ENTITY_PALETTE
.ENDMACRO

.MACRO EVENT_LOAD_GAS_STATION_PALETTE
	EVENT_CALLROUTINE LOAD_GAS_STATION_PALETTE
.ENDMACRO

.MACRO EVENT_LOAD_GAS_STATION_FLASH_PALETTE
	EVENT_CALLROUTINE LOAD_GAS_STATION_FLASH_PALETTE
.ENDMACRO

.MACRO EVENT_UPDATE_BATTLE_SCREEN_EFFECTS
	EVENT_CALLROUTINE UPDATE_BATTLE_SCREEN_EFFECTS
.ENDMACRO

.MACRO EVENT_INSTANT_WIN_PP_RECOVERY
	EVENT_CALLROUTINE INSTANT_WIN_PP_RECOVERY
.ENDMACRO

.MACRO EVENT_INIT_OVAL_WINDOW
	EVENT_CALLROUTINE INIT_OVAL_WINDOW
.ENDMACRO

.MACRO EVENT_CLOSE_OVAL_WINDOW
	EVENT_CALLROUTINE CLOSE_OVAL_WINDOW
.ENDMACRO

.MACRO EVENT_IS_PSI_ANIMATION_ACTIVE
	EVENT_CALLROUTINE IS_PSI_ANIMATION_ACTIVE
.ENDMACRO

.MACRO EVENT_FILL_PALETTES_WHITE
	EVENT_CALLROUTINE FILL_PALETTES_WHITE
.ENDMACRO

.MACRO EVENT_FILL_PALETTES_BLACK
	EVENT_CALLROUTINE FILL_PALETTES_BLACK
.ENDMACRO

.MACRO EVENT_SET_DEFAULT_TM
	EVENT_CALLROUTINE SET_DEFAULT_TM
.ENDMACRO

.MACRO EVENT_SHOW_CURRENT_ENTITY_SPRITE
	EVENT_CALLROUTINE SHOW_CURRENT_ENTITY_SPRITE
.ENDMACRO

.MACRO EVENT_CHECK_SECTOR_USES_MINISPRITES
	EVENT_CALLROUTINE CHECK_SECTOR_USES_MINISPRITES
.ENDMACRO

.MACRO EVENT_RESET_ENTITY_ANIMATION
	EVENT_CALLROUTINE RESET_ENTITY_ANIMATION
.ENDMACRO

.MACRO EVENT_SET_ENTITY_SLEEP_FRAMES
	EVENT_CALLROUTINE SET_ENTITY_SLEEP_FRAMES
.ENDMACRO

.MACRO EVENT_INIT_WINDOW_REGISTERS
	EVENT_CALLROUTINE INIT_WINDOW_REGISTERS
.ENDMACRO

.MACRO EVENT_SETUP_FULLSCREEN_WINDOW_CLIPPING
	EVENT_CALLROUTINE SETUP_FULLSCREEN_WINDOW_CLIPPING
.ENDMACRO

.MACRO EVENT_DISABLE_OBJ_HDMA
	EVENT_CALLROUTINE DISABLE_OBJ_HDMA
.ENDMACRO

.MACRO EVENT_SETUP_DARK_WINDOW_EFFECT
	EVENT_CALLROUTINE SETUP_DARK_WINDOW_EFFECT
.ENDMACRO

.MACRO EVENT_DISABLE_HDMA_CHANNEL4_ALT
	EVENT_CALLROUTINE DISABLE_HDMA_CHANNEL4_ALT
.ENDMACRO

.MACRO EVENT_SETUP_DUAL_DARK_WINDOW_EFFECT
	EVENT_CALLROUTINE SETUP_DUAL_DARK_WINDOW_EFFECT
.ENDMACRO

.MACRO EVENT_DISABLE_HDMA_CHANNEL4
	EVENT_CALLROUTINE DISABLE_HDMA_CHANNEL4
.ENDMACRO

.MACRO EVENT_DISABLE_HDMA_CHANNEL5
	EVENT_CALLROUTINE DISABLE_HDMA_CHANNEL5
.ENDMACRO

.MACRO EVENT_UPDATE_MAP_PALETTE_ANIMATION
	EVENT_CALLROUTINE UPDATE_MAP_PALETTE_ANIMATION
.ENDMACRO

.MACRO EVENT_DISABLE_PARTY_MOVEMENT_AND_HIDE
	EVENT_CALLROUTINE DISABLE_PARTY_MOVEMENT_AND_HIDE
.ENDMACRO

.MACRO EVENT_ENABLE_PARTY_MOVEMENT_AND_SHOW
	EVENT_CALLROUTINE ENABLE_PARTY_MOVEMENT_AND_SHOW
.ENDMACRO

.MACRO EVENT_GET_RANDOM_NPC_DELAY
	EVENT_CALLROUTINE GET_RANDOM_NPC_DELAY
.ENDMACRO

.MACRO EVENT_GET_RANDOM_SCREEN_DELAY
	EVENT_CALLROUTINE GET_RANDOM_SCREEN_DELAY
.ENDMACRO

.MACRO EVENT_ENABLE_TESSIE_LEAVES_ENTITIES
	EVENT_CALLROUTINE ENABLE_TESSIE_LEAVES_ENTITIES
.ENDMACRO

.MACRO EVENT_QUEUE_NPC_TEXT_INTERACTION
	EVENT_CALLROUTINE QUEUE_NPC_TEXT_INTERACTION
.ENDMACRO

.MACRO EVENT_GET_PAD_PRESS
	EVENT_CALLROUTINE GET_PAD_PRESS
.ENDMACRO

.MACRO EVENT_GET_PAD_STATE
	EVENT_CALLROUTINE GET_PAD_STATE
.ENDMACRO

.MACRO EVENT_IS_X_LESS_THAN_ENTITY
	EVENT_CALLROUTINE IS_X_LESS_THAN_ENTITY
.ENDMACRO

.MACRO EVENT_IS_Y_LESS_THAN_ENTITY
	EVENT_CALLROUTINE IS_Y_LESS_THAN_ENTITY
.ENDMACRO

.MACRO EVENT_IS_BELOW_LEADER_Y
	EVENT_CALLROUTINE IS_BELOW_LEADER_Y
.ENDMACRO

.MACRO EVENT_GET_NPC_DEFAULT_DIRECTION
	EVENT_CALLROUTINE GET_NPC_DEFAULT_DIRECTION
.ENDMACRO

.MACRO EVENT_SET_ENTITY_DIRECTION
	EVENT_CALLROUTINE SET_ENTITY_DIRECTION
.ENDMACRO

.MACRO EVENT_GET_LEADER_DIRECTION_OFFSET
	EVENT_CALLROUTINE GET_LEADER_DIRECTION_OFFSET
.ENDMACRO

.MACRO EVENT_GET_CARDINAL_DIRECTION
	EVENT_CALLROUTINE GET_CARDINAL_DIRECTION
.ENDMACRO

.MACRO EVENT_CALCULATE_DIRECTION_TO_TARGET
	EVENT_CALLROUTINE CALCULATE_DIRECTION_TO_TARGET
.ENDMACRO

.MACRO EVENT_QUANTIZE_ENTITY_DIRECTION
	EVENT_CALLROUTINE QUANTIZE_ENTITY_DIRECTION
.ENDMACRO

.MACRO EVENT_SCALE_DIRECTION_DISTANCE
	EVENT_CALLROUTINE SCALE_DIRECTION_DISTANCE
.ENDMACRO

.MACRO EVENT_REVERSE_DIRECTION_8
	EVENT_CALLROUTINE REVERSE_DIRECTION_8
.ENDMACRO

.MACRO EVENT_QUANTIZE_DIRECTION
	EVENT_CALLROUTINE QUANTIZE_DIRECTION
.ENDMACRO

.MACRO EVENT_STORE_LEADER_POS_TO_ENTITY_VARS
	EVENT_CALLROUTINE STORE_LEADER_POS_TO_ENTITY_VARS
.ENDMACRO

.MACRO EVENT_RESTORE_ENTITY_POSITION_FROM_VARS
	EVENT_CALLROUTINE RESTORE_ENTITY_POSITION_FROM_VARS
.ENDMACRO

.MACRO EVENT_SET_ENTITY_RANDOM_SCREEN_X
	EVENT_CALLROUTINE SET_ENTITY_RANDOM_SCREEN_X
.ENDMACRO

.MACRO EVENT_SET_PHOTOGRAPHER_POSITION
	EVENT_CALLROUTINE SET_PHOTOGRAPHER_POSITION
.ENDMACRO

.MACRO EVENT_TEST_PLAYER_IN_AREA
	EVENT_CALLROUTINE TEST_PLAYER_IN_AREA
.ENDMACRO

.MACRO EVENT_IS_ENTITY_IN_RANGE_OF_LEADER
	EVENT_CALLROUTINE IS_ENTITY_IN_RANGE_OF_LEADER
.ENDMACRO

.MACRO EVENT_SET_ENTITY_VELOCITY_FROM_DIRECTION
	EVENT_CALLROUTINE SET_ENTITY_VELOCITY_FROM_DIRECTION
.ENDMACRO

.MACRO EVENT_GET_ENTITY_BOUNDARY_SIDE
	EVENT_CALLROUTINE GET_ENTITY_BOUNDARY_SIDE
.ENDMACRO

.MACRO EVENT_HALVE_ENTITY_DELTA_Y
	EVENT_CALLROUTINE HALVE_ENTITY_DELTA_Y
.ENDMACRO

.MACRO EVENT_GET_PARTY_COUNT
	EVENT_CALLROUTINE GET_PARTY_COUNT
.ENDMACRO

.MACRO EVENT_LOAD_CURRENT_MAP_BLOCK_EVENTS
	EVENT_CALLROUTINE LOAD_CURRENT_MAP_BLOCK_EVENTS
.ENDMACRO

.MACRO EVENT_LOAD_MAP_ROW_AT_SCROLL_POS
	EVENT_CALLROUTINE LOAD_MAP_ROW_AT_SCROLL_POS
.ENDMACRO

.MACRO EVENT_LOAD_INITIAL_MAP_DATA_FAR
	EVENT_CALLROUTINE LOAD_INITIAL_MAP_DATA_FAR
.ENDMACRO

.MACRO EVENT_APPLY_ENTITY_PALETTE_BRIGHTNESS
	EVENT_CALLROUTINE APPLY_ENTITY_PALETTE_BRIGHTNESS
.ENDMACRO

.MACRO EVENT_SETUP_ENTITY_COLOR_MATH
	EVENT_CALLROUTINE SETUP_ENTITY_COLOR_MATH
.ENDMACRO

.MACRO EVENT_REFLECT_ENTITY_Y_AT_TARGET
	EVENT_CALLROUTINE REFLECT_ENTITY_Y_AT_TARGET
.ENDMACRO

.MACRO EVENT_LOAD_ANIMATION_SEQUENCE_FRAME
	EVENT_CALLROUTINE LOAD_ANIMATION_SEQUENCE_FRAME
.ENDMACRO

.MACRO EVENT_DISPLAY_ANIMATION_SEQUENCE_FRAME
	EVENT_CALLROUTINE DISPLAY_ANIMATION_SEQUENCE_FRAME
.ENDMACRO

.MACRO EVENT_LOAD_CHARACTER_PORTRAIT_SCREEN
	EVENT_CALLROUTINE LOAD_CHARACTER_PORTRAIT_SCREEN
.ENDMACRO

.MACRO EVENT_ADVANCE_TILEMAP_ANIMATION_FRAME
	EVENT_CALLROUTINE ADVANCE_TILEMAP_ANIMATION_FRAME
.ENDMACRO

.MACRO EVENT_SETUP_PSI_TELEPORT_DEPARTURE
	EVENT_CALLROUTINE SETUP_PSI_TELEPORT_DEPARTURE
.ENDMACRO

.MACRO EVENT_MAKE_PARTY_LOOK_AT_ACTIVE_ENTITY
	EVENT_CALLROUTINE MAKE_PARTY_LOOK_AT_ACTIVE_ENTITY
.ENDMACRO

.MACRO EVENT_FINALIZE_PALETTE_FADE
	EVENT_CALLROUTINE FINALIZE_PALETTE_FADE
.ENDMACRO

.MACRO EVENT_RESTORE_MAP_PALETTE
	EVENT_CALLROUTINE RESTORE_MAP_PALETTE
.ENDMACRO

.MACRO EVENT_LOAD_TEXT_LAYER_TILEMAP
	EVENT_CALLROUTINE LOAD_TEXT_LAYER_TILEMAP
.ENDMACRO

.MACRO EVENT_INIT_OVAL_WINDOW_FAR
	EVENT_CALLROUTINE INIT_OVAL_WINDOW_FAR
.ENDMACRO

.MACRO EVENT_PLAY_FLYOVER_SCRIPT
	EVENT_CALLROUTINE PLAY_FLYOVER_SCRIPT
.ENDMACRO

.MACRO EVENT_UPDATE_SWIRL_EFFECT
	EVENT_CALLROUTINE UPDATE_SWIRL_EFFECT
.ENDMACRO

.MACRO EVENT_CLEAR_FADE_ENTITY_FLAGS
	EVENT_CALLROUTINE CLEAR_FADE_ENTITY_FLAGS
.ENDMACRO

.MACRO EVENT_UPDATE_FADE_ENTITY_SPRITES
	EVENT_CALLROUTINE UPDATE_FADE_ENTITY_SPRITES
.ENDMACRO

.MACRO EVENT_HIDE_FADE_ENTITY_FRAMES
	EVENT_CALLROUTINE HIDE_FADE_ENTITY_FRAMES
.ENDMACRO

.MACRO EVENT_NULL_CALLROUTINE
	EVENT_CALLROUTINE NULL_CALLROUTINE
.ENDMACRO

.MACRO EVENT_ANIMATE_ENTITY_TILE_COPY
	EVENT_CALLROUTINE ANIMATE_ENTITY_TILE_COPY
.ENDMACRO

.MACRO EVENT_ANIMATE_ENTITY_TILE_BLEND
	EVENT_CALLROUTINE ANIMATE_ENTITY_TILE_BLEND
.ENDMACRO

.MACRO EVENT_CLEAR_SPRITEMAP_BUFFER
	EVENT_CALLROUTINE CLEAR_SPRITEMAP_BUFFER
.ENDMACRO

.MACRO EVENT_ANIMATE_ENTITY_TILE_MERGE
	EVENT_CALLROUTINE ANIMATE_ENTITY_TILE_MERGE
.ENDMACRO

.MACRO EVENT_ENABLE_YOUR_SANCTUARY_DISPLAY
	EVENT_CALLROUTINE ENABLE_YOUR_SANCTUARY_DISPLAY
.ENDMACRO

.MACRO EVENT_DISPLAY_YOUR_SANCTUARY_LOCATION
	EVENT_CALLROUTINE DISPLAY_YOUR_SANCTUARY_LOCATION
.ENDMACRO

.MACRO EVENT_SET_CAST_SCROLL_THRESHOLD
	EVENT_CALLROUTINE SET_CAST_SCROLL_THRESHOLD
.ENDMACRO

.MACRO EVENT_CHECK_CAST_SCROLL_THRESHOLD
	EVENT_CALLROUTINE CHECK_CAST_SCROLL_THRESHOLD
.ENDMACRO

.MACRO EVENT_UPLOAD_SPECIAL_CAST_PALETTE
	EVENT_CALLROUTINE UPLOAD_SPECIAL_CAST_PALETTE
.ENDMACRO

.MACRO EVENT_IS_ENTITY_STILL_ON_CAST_SCREEN
	EVENT_CALLROUTINE IS_ENTITY_STILL_ON_CAST_SCREEN
.ENDMACRO

.MACRO EVENT_INIT_BUBBLE_MONKEY
	EVENT_CALLROUTINE INIT_BUBBLE_MONKEY
.ENDMACRO

.MACRO EVENT_CHECK_DELIVERY_ATTEMPT_LIMIT
	EVENT_CALLROUTINE CHECK_DELIVERY_ATTEMPT_LIMIT
.ENDMACRO

.MACRO EVENT_GET_DELIVERY_ATTEMPTS
	EVENT_CALLROUTINE GET_DELIVERY_ATTEMPTS
.ENDMACRO

.MACRO EVENT_RESET_DELIVERY_ATTEMPTS
	EVENT_CALLROUTINE RESET_DELIVERY_ATTEMPTS
.ENDMACRO

.MACRO EVENT_GET_TIMED_DELIVERY_TIME
	EVENT_CALLROUTINE GET_TIMED_DELIVERY_TIME
.ENDMACRO

.MACRO EVENT_SET_DELIVERY_TIMER
	EVENT_CALLROUTINE SET_DELIVERY_TIMER
.ENDMACRO

.MACRO EVENT_DECREMENT_DELIVERY_TIMER
	EVENT_CALLROUTINE DECREMENT_DELIVERY_TIMER
.ENDMACRO

.MACRO EVENT_QUEUE_DELIVERY_SUCCESS_INTERACTION
	EVENT_CALLROUTINE QUEUE_DELIVERY_SUCCESS_INTERACTION
.ENDMACRO

.MACRO EVENT_QUEUE_DELIVERY_FAILURE_INTERACTION
	EVENT_CALLROUTINE QUEUE_DELIVERY_FAILURE_INTERACTION
.ENDMACRO

.MACRO EVENT_GET_TIMED_DELIVERY_ENTER_SPEED
	EVENT_CALLROUTINE GET_TIMED_DELIVERY_ENTER_SPEED
.ENDMACRO

.MACRO EVENT_GET_TIMED_DELIVERY_EXIT_SPEED
	EVENT_CALLROUTINE GET_TIMED_DELIVERY_EXIT_SPEED
.ENDMACRO

.MACRO EVENT_IS_PLAYER_BUSY
	EVENT_CALLROUTINE IS_PLAYER_BUSY
.ENDMACRO

.MACRO EVENT_INIT_DELIVERY_SEQUENCE
	EVENT_CALLROUTINE INIT_DELIVERY_SEQUENCE
.ENDMACRO

.MACRO EVENT_RESTORE_OVERWORLD_STATE
	EVENT_CALLROUTINE RESTORE_OVERWORLD_STATE
.ENDMACRO

.MACRO EVENT_INITIALIZE_PARTY_MEMBER_ENTITY
	EVENT_CALLROUTINE INITIALIZE_PARTY_MEMBER_ENTITY
.ENDMACRO

.MACRO EVENT_UPDATE_FOLLOWER_VISUALS
	EVENT_CALLROUTINE UPDATE_FOLLOWER_VISUALS
.ENDMACRO

.MACRO EVENT_GET_DIRECTION_FROM_PLAYER_TO_ENTITY
	EVENT_CALLROUTINE GET_DIRECTION_FROM_PLAYER_TO_ENTITY
.ENDMACRO

.MACRO EVENT_YIELD_TO_TEXT
	EVENT_CALLROUTINE SET_ACTIONSCRIPT_STATE_RUNNING
.ENDMACRO

.MACRO EVENT_SET_ENTITY_MOVEMENT_SPEED arg, arg2
	EVENT_CALLROUTINE SET_ENTITY_MOVEMENT_SPEED, arg, arg2
.ENDMACRO

.MACRO EVENT_SET_ENTITY_MOVEMENT_SPEED_ME2
	EVENT_CALLROUTINE SET_ENTITY_MOVEMENT_SPEED_ENTRY2
.ENDMACRO

.MACRO EVENT_UPDATE_ENTITY_ANIMATION
	EVENT_CALLROUTINE UPDATE_ENTITY_ANIMATION
.ENDMACRO

.MACRO EVENT_SET_ENTITY_DIRECTION_AND_FRAME arg, arg2
	EVENT_CALLROUTINE SET_ENTITY_DIRECTION_AND_FRAME, arg, arg2
.ENDMACRO

.MACRO EVENT_PLAY_SOUND arg
	EVENT_CALLROUTINE MOVEMENT_CMD_PLAY_SOUND, .LOBYTE(arg), .HIBYTE(arg)
.ENDMACRO

.MACRO EVENT_SET_DIRECTION8 arg
	EVENT_CALLROUTINE SET_DIRECTION8, .LOBYTE(arg)
.ENDMACRO

.MACRO EVENT_SET_SURFACE_FLAGS arg
	EVENT_CALLROUTINE SET_SURFACE_FLAGS, .LOBYTE(arg)
.ENDMACRO

.MACRO EVENT_MOVEMENT_CMD_COPY_LEADER_POS arg
	EVENT_CALLROUTINE MOVEMENT_CMD_COPY_LEADER_POS, .LOBYTE(arg)
.ENDMACRO

.MACRO EVENT_PREPARE_NEW_ENTITY_AT_TELEPORT_DESTINATION arg
	EVENT_CALLROUTINE ACTIONSCRIPT_PREPARE_NEW_ENTITY_AT_TELEPORT_DESTINATION, .LOBYTE(arg)
.ENDMACRO

;x,y coords go in vars 6 and 7
.MACRO EVENT_GET_POSITION_OF_PARTY_MEMBER arg
	EVENT_CALLROUTINE ACTIONSCRIPT_GET_POSITION_OF_PARTY_MEMBER, .LOBYTE(arg)
.ENDMACRO

.MACRO EVENT_MOVEMENT_CMD_SET_EVENT_FLAG arg
	EVENT_CALLROUTINE MOVEMENT_CMD_SET_EVENT_FLAG, .LOBYTE(arg), .HIBYTE(arg)
.ENDMACRO

.MACRO EVENT_MOVEMENT_CMD_COPY_SPRITE_POS arg
	EVENT_CALLROUTINE MOVEMENT_CMD_COPY_SPRITE_POS, .LOBYTE(arg), .HIBYTE(arg)
.ENDMACRO

.MACRO EVENT_MOVEMENT_CMD_STORE_NPC_POSITION arg
	EVENT_CALLROUTINE MOVEMENT_CMD_STORE_NPC_POSITION, .LOBYTE(arg), .HIBYTE(arg)
.ENDMACRO

.MACRO EVENT_MOVEMENT_CMD_STORE_SPRITE_POSITION arg
	EVENT_CALLROUTINE MOVEMENT_CMD_STORE_SPRITE_POSITION, .LOBYTE(arg), .HIBYTE(arg)
.ENDMACRO

.MACRO EVENT_MOVEMENT_CMD_FACE_TOWARD_NPC arg
	EVENT_CALLROUTINE MOVEMENT_CMD_FACE_TOWARD_NPC, .LOBYTE(arg), .HIBYTE(arg)
.ENDMACRO

.MACRO EVENT_MOVEMENT_CMD_FACE_TOWARD_SPRITE arg
	EVENT_CALLROUTINE MOVEMENT_CMD_FACE_TOWARD_SPRITE, .LOBYTE(arg), .HIBYTE(arg)
.ENDMACRO

.MACRO EVENT_MOVEMENT_SET_BOUNDING_BOX arg, arg2
	EVENT_CALLROUTINE MOVEMENT_SET_BOUNDING_BOX, .LOBYTE(arg), .HIBYTE(arg), .LOBYTE(arg2), .HIBYTE(arg2)
.ENDMACRO

.MACRO EVENT_SPAWN_ENTITY_RELATIVE arg, arg2
	EVENT_CALLROUTINE MOVEMENT_CMD_CREATE_ENTITY_BG3, .LOBYTE(arg), .HIBYTE(arg), .LOBYTE(arg2), .HIBYTE(arg2)
.ENDMACRO

.MACRO EVENT_SPAWN_ENTITY_AT_SELF arg, arg2
	EVENT_CALLROUTINE MOVEMENT_CMD_CREATE_ENTITY, .LOBYTE(arg), .HIBYTE(arg), .LOBYTE(arg2), .HIBYTE(arg2)
.ENDMACRO

.MACRO EVENT_MOVEMENT_SET_POSITION_FROM_SCREEN arg, arg2
	EVENT_CALLROUTINE MOVEMENT_SET_POSITION_FROM_SCREEN, .LOBYTE(arg), .HIBYTE(arg), .LOBYTE(arg2), .HIBYTE(arg2)
.ENDMACRO

.MACRO EVENT_MOVEMENT_CMD_LOOP arg, arg2
	EVENT_CALLROUTINE MOVEMENT_CMD_LOOP, .LOBYTE(arg), .LOBYTE(arg2), .HIBYTE(arg2)
.ENDMACRO

.MACRO EVENT_MOVEMENT_STORE_OFFSET_POSITION arg, arg2
	EVENT_CALLROUTINE MOVEMENT_STORE_OFFSET_POSITION, .LOBYTE(arg), .HIBYTE(arg), .LOBYTE(arg2), .HIBYTE(arg2)
.ENDMACRO

.MACRO EVENT_MOVEMENT_CMD_SET_NPC_ID arg
	EVENT_CALLROUTINE MOVEMENT_CMD_SET_NPC_ID, .LOBYTE(arg), .HIBYTE(arg)
.ENDMACRO

.MACRO EVENT_MOVEMENT_CMD_CALCULATE_TRAVEL_FRAMES arg
	EVENT_CALLROUTINE MOVEMENT_CMD_CALCULATE_TRAVEL_FRAMES, .LOBYTE(arg), .HIBYTE(arg)
.ENDMACRO

.MACRO EVENT_FADE_OUT arg1, arg2
	EVENT_CALLROUTINE ACTIONSCRIPT_FADE_OUT, arg1, arg2
.ENDMACRO

.MACRO EVENT_FADE_IN arg1, arg2
	EVENT_CALLROUTINE ACTIONSCRIPT_FADE_IN, arg1, arg2
.ENDMACRO

.MACRO EVENT_CHECK_CURRENT_ENTITY_OBSTACLES arg1, arg2
	EVENT_CALLROUTINE CHECK_CURRENT_ENTITY_OBSTACLES, arg1, .LOBYTE(arg2), .HIBYTE(arg2), .BANKBYTE(arg2)
.ENDMACRO

.MACRO EVENT_MOVE_ENTITY_DISTANCE arg
	EVENT_CALLROUTINE MOVE_ENTITY_DISTANCE, .LOBYTE(arg), .HIBYTE(arg)
.ENDMACRO

.MACRO EVENT_MOVEMENT_CMD_PRINT_CAST_NAME arg, arg2, arg3
	EVENT_CALLROUTINE MOVEMENT_CMD_PRINT_CAST_NAME, .LOBYTE(arg), .HIBYTE(arg), .LOBYTE(arg2), .HIBYTE(arg2), .LOBYTE(arg3), .HIBYTE(arg3)
.ENDMACRO

.MACRO EVENT_PREPARE_NEW_ENTITY arg, arg2, arg3
	EVENT_CALLROUTINE ACTIONSCRIPT_PREPARE_NEW_ENTITY, .LOBYTE(arg), .HIBYTE(arg), .LOBYTE(arg2), .HIBYTE(arg2), .LOBYTE(arg3)
.ENDMACRO

.MACRO EVENT_MOVEMENT_CMD_PRINT_CAST_NAME_VAR0 arg, arg2, arg3
	EVENT_CALLROUTINE MOVEMENT_CMD_PRINT_CAST_NAME_VAR0, .LOBYTE(arg), .HIBYTE(arg), .LOBYTE(arg2), .HIBYTE(arg2), .LOBYTE(arg3), .HIBYTE(arg3)
.ENDMACRO

.MACRO EVENT_FADE_OUT_WITH_MOSAIC arg, arg2, arg3
	EVENT_CALLROUTINE ACTIONSCRIPT_FADE_OUT_WITH_MOSAIC, .LOBYTE(arg), .HIBYTE(arg), .LOBYTE(arg2), .HIBYTE(arg2), .LOBYTE(arg3), .HIBYTE(arg3)
.ENDMACRO

.MACRO EVENT_MOVEMENT_CMD_SETUP_SPOTLIGHT arg, arg2, arg3
	EVENT_CALLROUTINE MOVEMENT_CMD_SETUP_SPOTLIGHT, .LOBYTE(arg), .HIBYTE(arg), .LOBYTE(arg2), .HIBYTE(arg2), .LOBYTE(arg3), .HIBYTE(arg3)
.ENDMACRO

.MACRO EVENT_MOVEMENT_CMD_ANIMATE_PALETTE_FADE arg, arg2, arg3
	EVENT_CALLROUTINE MOVEMENT_CMD_ANIMATE_PALETTE_FADE, .LOBYTE(arg), .HIBYTE(arg), .LOBYTE(arg2), .LOBYTE(arg3)
.ENDMACRO

.MACRO EVENT_MOVEMENT_CMD_APPLY_COLOR_MATH_FIXED arg, arg2, arg3
	EVENT_CALLROUTINE MOVEMENT_CMD_APPLY_COLOR_MATH_FIXED, .LOBYTE(arg), .LOBYTE(arg2),.LOBYTE(arg3)
.ENDMACRO

.MACRO EVENT_MOVEMENT_CMD_PRINT_CAST_NAME_PARTY arg, arg2, arg3
	EVENT_CALLROUTINE MOVEMENT_CMD_PRINT_CAST_NAME_PARTY, .LOBYTE(arg), .HIBYTE(arg), .LOBYTE(arg2), .HIBYTE(arg2), .LOBYTE(arg3), .HIBYTE(arg3)
.ENDMACRO

.MACRO EVENT_CHOOSE_RANDOM arg, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10
	.IF(.PARAMCOUNT = 1)
		EVENT_CALLROUTINE CHOOSE_RANDOM, .PARAMCOUNT, .LOBYTE(arg), .HIBYTE(arg)
	.ENDIF
	.IF(.PARAMCOUNT = 2)
		EVENT_CALLROUTINE CHOOSE_RANDOM, .PARAMCOUNT, .LOBYTE(arg), .HIBYTE(arg), .LOBYTE(arg2), .HIBYTE(arg2)
	.ENDIF
	.IF(.PARAMCOUNT = 3)
		EVENT_CALLROUTINE CHOOSE_RANDOM, .PARAMCOUNT, .LOBYTE(arg), .HIBYTE(arg), .LOBYTE(arg2), .HIBYTE(arg2), .LOBYTE(arg3), .HIBYTE(arg3)
	.ENDIF
	.IF(.PARAMCOUNT = 4)
		EVENT_CALLROUTINE CHOOSE_RANDOM, .PARAMCOUNT, .LOBYTE(arg), .HIBYTE(arg), .LOBYTE(arg2), .HIBYTE(arg2), .LOBYTE(arg3), .HIBYTE(arg3), .LOBYTE(arg4), .HIBYTE(arg4)
	.ENDIF
	.IF(.PARAMCOUNT = 5)
		EVENT_CALLROUTINE CHOOSE_RANDOM, .PARAMCOUNT, .LOBYTE(arg), .HIBYTE(arg), .LOBYTE(arg2), .HIBYTE(arg2), .LOBYTE(arg3), .HIBYTE(arg3), .LOBYTE(arg4), .HIBYTE(arg4), .LOBYTE(arg5), .HIBYTE(arg5)
	.ENDIF
	.IF(.PARAMCOUNT = 6)
		EVENT_CALLROUTINE CHOOSE_RANDOM, .PARAMCOUNT, .LOBYTE(arg), .HIBYTE(arg), .LOBYTE(arg2), .HIBYTE(arg2), .LOBYTE(arg3), .HIBYTE(arg3), .LOBYTE(arg4), .HIBYTE(arg4), .LOBYTE(arg5), .HIBYTE(arg5), .LOBYTE(arg6), .HIBYTE(arg6)
	.ENDIF
	.IF(.PARAMCOUNT = 7)
		EVENT_CALLROUTINE CHOOSE_RANDOM, .PARAMCOUNT, .LOBYTE(arg), .HIBYTE(arg), .LOBYTE(arg2), .HIBYTE(arg2), .LOBYTE(arg3), .HIBYTE(arg3), .LOBYTE(arg4), .HIBYTE(arg4), .LOBYTE(arg5), .HIBYTE(arg5), .LOBYTE(arg6), .HIBYTE(arg6), .LOBYTE(arg7), .HIBYTE(arg7)
	.ENDIF
	.IF(.PARAMCOUNT = 8)
		EVENT_CALLROUTINE CHOOSE_RANDOM, .PARAMCOUNT, .LOBYTE(arg), .HIBYTE(arg), .LOBYTE(arg2), .HIBYTE(arg2), .LOBYTE(arg3), .HIBYTE(arg3), .LOBYTE(arg4), .HIBYTE(arg4), .LOBYTE(arg5), .HIBYTE(arg5), .LOBYTE(arg6), .HIBYTE(arg6), .LOBYTE(arg7), .HIBYTE(arg7), .LOBYTE(arg8), .HIBYTE(arg8)
	.ENDIF
	.IF(.PARAMCOUNT = 9)
		EVENT_CALLROUTINE CHOOSE_RANDOM, .PARAMCOUNT, .LOBYTE(arg), .HIBYTE(arg), .LOBYTE(arg2), .HIBYTE(arg2), .LOBYTE(arg3), .HIBYTE(arg3), .LOBYTE(arg4), .HIBYTE(arg4), .LOBYTE(arg5), .HIBYTE(arg5), .LOBYTE(arg6), .HIBYTE(arg6), .LOBYTE(arg7), .HIBYTE(arg7), .LOBYTE(arg8), .HIBYTE(arg8), .LOBYTE(arg9), .HIBYTE(arg9)
	.ENDIF
	.IF(.PARAMCOUNT = 10)
		EVENT_CALLROUTINE CHOOSE_RANDOM, .PARAMCOUNT, .LOBYTE(arg), .HIBYTE(arg), .LOBYTE(arg2), .HIBYTE(arg2), .LOBYTE(arg3), .HIBYTE(arg3), .LOBYTE(arg4), .HIBYTE(arg4), .LOBYTE(arg5), .HIBYTE(arg5), .LOBYTE(arg6), .HIBYTE(arg6), .LOBYTE(arg7), .HIBYTE(arg7), .LOBYTE(arg8), .HIBYTE(arg8), .LOBYTE(arg9), .HIBYTE(arg9), .LOBYTE(arg10), .HIBYTE(arg10)
	.ENDIF
.ENDMACRO
