
MOVEMENT_CODE_0C:
	STY $94
	LDY $8A
MOVEMENT_CODE_0C_UNK1:
	LDX $88
	JSR FREE_ACTION_SCRIPT
	LDA #$FFFF
	STA ENTITY_SCRIPT_SLEEP_FRAMES,Y
	LDA ENTITY_SCRIPT_INDEX_TABLE,X
	BPL @HAS_MORE_SCRIPTS
	JMP MOVEMENT_CODE_00
@HAS_MORE_SCRIPTS:
	LDY $94
	RTS
