
GET_DIRECTION_TURNED_RANDOMLY_LEFT_OR_RIGHT:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	JSL RAND
	AND #$0001
	BEQ @TURN_LEFT
	LDA #$0001
	BRA @APPLY_ROTATION
@TURN_LEFT:
	LDA #$FFFF
@APPLY_ROTATION:
	JSL GET_DIRECTION_ROTATED_CLOCKWISE
	RTL
