
MAKE_PARTY_LOOK_AT_ACTIVE_ENTITY:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	STA @LOCAL04
	LDA FRAME_COUNTER
	AND #$00FF
	AND #$0001
	BNEL @RETURN
	STZ @LOCAL03
	BRA @MEMBER_LOOP_CHECK
@PROCESS_MEMBER:
.IF .DEFINED(JPN)
	LDA @LOCAL03
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_order,X
.ELSE
	LDY #.LOWORD(GAME_STATE) + game_state::party_order
	LDA (@LOCAL03),Y
.ENDIF
	AND #$00FF
	STA @VIRTUAL02
	LDA #16
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @NEXT_MEMBER
	LDA @LOCAL03
	ASL
.IF .DEFINED(JPN)
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_entity_slots,X
.ELSE
	TAX
	LDA GAME_STATE + game_state::party_entity_slots,X
.ENDIF
	STA @VIRTUAL04
	ASL
	STA @VIRTUAL02
	LDA @LOCAL04
	ASL
	TAX
	LDA ENTITY_ABS_Y_TABLE,X
	STA @LOCAL00
	LDY ENTITY_ABS_X_TABLE,X
	LDX @VIRTUAL02
	LDA ENTITY_ABS_Y_TABLE,X
	TAX
	STX @LOCAL02
	LDX @VIRTUAL02
	LDA ENTITY_ABS_X_TABLE,X
	LDX @LOCAL02
	JSL CALCULATE_DIRECTION_FROM_POSITIONS
	LDY #$2000
	CLC
	ADC #$1000
	JSL DIVISION16S_DIVISOR_POSITIVE
	STA @LOCAL01
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(ENTITY_DIRECTIONS)
	TAX
	LDA @LOCAL01
	STA @VIRTUAL02
	LDA __BSS_START__,X
	CMP @VIRTUAL02
	BEQ @NEXT_MEMBER
	LDA @LOCAL01
	STA __BSS_START__,X
	LDA @VIRTUAL04
	JSL UPDATE_ENTITY_SPRITE
@NEXT_MEMBER:
	INC @LOCAL03
@MEMBER_LOOP_CHECK:
	LDA GAME_STATE+game_state::party_count
	AND #$00FF
	CMP @LOCAL03
	BGTL @PROCESS_MEMBER
@RETURN:
	END_C_FUNCTION
