
RUN_ACTIONSCRIPT_FRAME:
	LDA DISABLE_ACTIONSCRIPT
	BEQ @ENABLED
	RTL
@ENABLED:
	JMP $800000 | .LOWORD(@FAR_ENTRY)
@FAR_ENTRY:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8
	REP #PROC_FLAGS::ACCUM8
	PHD
	PHA
	TDC
	SEC
	SBC #$00A0
	AND #$FF00
	TCD
	PLA
	INC DISABLE_ACTIONSCRIPT
	LDX FIRST_ENTITY
	BMI @RETURN
	STZ $80
	STZ $86
@SCRIPT_LOOP:
	STX $88
	STX CURRENT_ENTITY_OFFSET
	STX CURRENT_ENTITY_SLOT
	LSR CURRENT_ENTITY_SLOT
	LDA ENTITY_NEXT_ENTITY_TABLE,X
	STA NEXT_ACTIVE_ENTITY
	JSR RUN_ENTITY_SCRIPTS_AND_TICK
	LDX NEXT_ACTIVE_ENTITY
	BPL @SCRIPT_LOOP
	LDX FIRST_ENTITY
	BMI @RETURN
@MOVE_LOOP:
	STX CURRENT_ENTITY_SLOT
	LSR CURRENT_ENTITY_SLOT
	STX $88
	BIT ENTITY_TICK_CALLBACK_HIGH,X
	BVS @AFTER_MOVE
	JSR (.LOWORD(ENTITY_MOVE_CALLBACK),X)
@AFTER_MOVE:
	JSR (.LOWORD(ENTITY_SCREEN_POSITION_CALLBACK),X)
	LDX $88
	LDA ENTITY_NEXT_ENTITY_TABLE,X
	TAX
	BPL @MOVE_LOOP
	LDX #$0000
	JSR (.LOWORD(CURRENT_ENTITY_DRAW_CALLBACK),X)
@RETURN:
	PLD
	STZ DISABLE_ACTIONSCRIPT
	RTL
