
TEST_PLAYER_IN_AREA:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16 ;bool
	END_STACK_VARS
	LDA PSI_TELEPORT_DESTINATION
	BEQ @CHECK_X
	LDA #FALSE
	BRA @RETURN
@CHECK_X:
	LDY CURRENT_ENTITY_SLOT
	TYA
	ASL
	TAX
	LDA ENTITY_SCRIPT_VAR0_TABLE,X
	SEC
	SBC GAME_STATE+game_state::leader_x_coord
	STA @LOCAL01
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @X_DELTA_POSITIVE
	LDA @LOCAL01
	EOR #$FFFF
	INC
	STA @LOCAL00
	BRA @CHECK_X_RANGE
@X_DELTA_POSITIVE:
	LDA @LOCAL01
	STA @LOCAL00
@CHECK_X_RANGE:
	TYA
	ASL
	TAX
	LDA @LOCAL00
	CMP ENTITY_SCRIPT_VAR2_TABLE,X
	BCS @OUT_OF_AREA
	LDA ENTITY_SCRIPT_VAR1_TABLE,X
	SEC
	SBC GAME_STATE+game_state::leader_y_coord
	STA @LOCAL01
	STA @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @Y_DELTA_POSITIVE
	LDA @LOCAL01
	EOR #$FFFF
	INC
	STA @LOCAL01
	BRA @CHECK_Y_RANGE
@Y_DELTA_POSITIVE:
	LDA @LOCAL01
	STA @LOCAL01
@CHECK_Y_RANGE:
	TYA
	ASL
	TAX
	LDA @LOCAL01
	CMP ENTITY_SCRIPT_VAR3_TABLE,X
	BCS @OUT_OF_AREA
	LDA #TRUE
	BRA @RETURN
@OUT_OF_AREA:
	LDA #FALSE
@RETURN:
	END_C_FUNCTION
