
DISABLE_NPC_MOVEMENT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	JSL FIND_ENTITY_BY_NPC_ID
	CMP #.LOWORD(-1)
	BEQ @DONE
	ASL
	CLC
	ADC #.LOWORD(ENTITY_TICK_CALLBACK_HIGH)
	TAX
	LDA __BSS_START__,X
	ORA #OBJECT_TICK_DISABLED | OBJECT_MOVE_DISABLED
	STA __BSS_START__,X
@DONE:
	END_C_FUNCTION
