
FIND_ADJACENT_NPC_INTERACTION:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA GAME_STATE+game_state::leader_direction
	AND #$FFFE
	TAY
	STY @LOCAL01
	TYX
	STX @LOCAL00
	TXA
	JSR CHECK_DIRECTIONAL_NPC_COLLISION
	CMP #.LOWORD(-1)
	BEQ @TRY_CW90
	CMP #0
	BEQ @TRY_CW90
	LDX @LOCAL00
	TXA
	BRA @DONE
@TRY_CW90:
	LDX @LOCAL00
	TXA
	INC
	INC
	AND #$0007
	TAX
	STX @LOCAL00
	STX GAME_STATE+game_state::leader_direction
	TXA
	JSR CHECK_DIRECTIONAL_NPC_COLLISION
	CMP #.LOWORD(-1)
	BEQ @TRY_CCW90
	CMP #0
	BEQ @TRY_CCW90
	LDX @LOCAL00
	TXA
	BRA @DONE
@TRY_CCW90:
	LDX @LOCAL00
	TXA
	INC
	INC
	INC
	INC
	AND #$0007
	TAX
	STX @LOCAL00
	STX GAME_STATE+game_state::leader_direction
	TXA
	JSR CHECK_DIRECTIONAL_NPC_COLLISION
	CMP #.LOWORD(-1)
	BEQ @TRY_OPPOSITE
	CMP #0
	BEQ @TRY_OPPOSITE
	LDX @LOCAL00
	TXA
	BRA @DONE
@TRY_OPPOSITE:
	LDX @LOCAL00
	TXA
	DEC
	DEC
	AND #$0007
	TAX
	STX @LOCAL00
	STX GAME_STATE+game_state::leader_direction
	TXA
	JSR CHECK_DIRECTIONAL_NPC_COLLISION
	CMP #.LOWORD(-1)
	BEQ @NOT_FOUND
	CMP #0
	BEQ @NOT_FOUND
	LDX @LOCAL00
	TXA
	BRA @DONE
@NOT_FOUND:
	LDY @LOCAL01
	STY GAME_STATE+game_state::leader_direction
	LDA #.LOWORD(-1)
@DONE:
	END_C_FUNCTION
