
GET_DIRECTION_BETWEEN_NPC_ENTITIES:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @VIRTUAL02
	TXY
	TAX
	LDA @VIRTUAL02
	STA @LOCAL00
	LDA #1
	JSL GET_DIRECTION_BETWEEN_ENTITIES
	END_C_FUNCTION
