
GET_NPC_DEFAULT_DIRECTION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_NPC_IDS,X
	STA @LOCAL00
	CMP #.LOWORD(-1)
	BNE @HAS_NPC
	LDA #4
	BRA @RETURN
@HAS_NPC:
	LOADPTR NPC_CONFIG_TABLE, @VIRTUAL06
	LDA @LOCAL00
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(npc_config)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDY #npc_config::direction
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
@RETURN:
	END_C_FUNCTION
