
SPAWN_NPCS_AT_SECTOR:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @LOCAL0C
	STA @VIRTUAL04
	STA @LOCAL0B
	LDA @VIRTUAL04
	CMP #32
	BCC @CHECK_Y_RANGE
	JMP @RETURN
@CHECK_Y_RANGE:
	LDA @LOCAL0C
	CMP #40
	BCC @LOOKUP_PLACEMENT
	JMP @RETURN
@LOOKUP_PLACEMENT:
	LDA @VIRTUAL04
	ASL
	STA @VIRTUAL02
	LDA @LOCAL0C
	OPTIMIZED_MULT @VIRTUAL04, 64
	CLC
	ADC @VIRTUAL02
	TAX
	LDA f:SPRITE_PLACEMENT_PTR_TABLE,X
	BEQL @RETURN
	STORE_INT1632 @VIRTUAL06
	CLC
	VAR_ADD_CONST_INT_ASSIGN SPRITE_PLACEMENT_TABLE & $FF0000, @VIRTUAL06
	LDA [@VIRTUAL06]
	STA @LOCAL0A
	INC @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	STZ @LOCAL09
	JMP @NPC_LOOP_CHECK
@PROCESS_NPC:
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	LDA [@VIRTUAL06] ;sprite_placement::id
	STA @LOCAL08
	SEP #PROC_FLAGS::ACCUM8
	LDY #sprite_placement::y_coord
	LDA [@VIRTUAL0A],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAY
	STY @LOCAL07
	SEP #PROC_FLAGS::ACCUM8
	LDY #sprite_placement::x_coord
	LDA [@VIRTUAL0A],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
	STX @LOCAL06
	LDA #.SIZEOF(sprite_placement)
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDY @LOCAL07
	TYA
	LSR
	LSR
	LSR
	STA @VIRTUAL02
	LDA @LOCAL0B
	STA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, 32
	CLC
	ADC @VIRTUAL02
	STA @LOCAL05
	TXA
	LSR
	LSR
	LSR
	STA @VIRTUAL02
	LDA @LOCAL0C
	OPTIMIZED_MULT @VIRTUAL04, 32
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL02
	LDA @LOCAL05
	LSR
	LSR
	LSR
	LSR
	LSR
	PHA
	LDA @VIRTUAL02
	LSR
	LSR
	LSR
	LSR
	OPTIMIZED_MULT @VIRTUAL04, 32
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	TAX
	LDA f:GLOBAL_MAP_TILESETPALETTE_DATA,X
	AND #$00FF
	LSR
	LSR
	LSR
	CMP LOADED_MAP_TILE_COMBO
	BNEL @NEXT_NPC
	LDA @LOCAL08
	JSL FIND_ENTITY_BY_NPC_ID_LINKED
	CMP #0
	BNEL @NEXT_NPC
	LDY @LOCAL07
	STY @VIRTUAL02
	LDA @VIRTUAL04
	XBA
	AND #$FF00
	CLC
	ADC @VIRTUAL02
	TAY
	STY @LOCAL04
	LDX @LOCAL06
	STX @VIRTUAL02
	LDA @LOCAL0C
	XBA
	AND #$FF00
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL02
	STA @LOCAL03
	TYA
	SEC
	SBC BG1_X_POS
	STA @LOCAL06
	LDA @VIRTUAL02
	SEC
	SBC BG1_Y_POS
	TAX
	LDA DEBUG
	BEQ @NORMAL_SPAWN_CHECK
	LDA PAD_STATE
	AND #PAD::L_BUTTON | PAD::R_BUTTON
	BNE @DEBUG_FORCE_SPAWN
	LDA NPC_SPAWNS_ENABLED
	DEC
	BEQ @CHECK_BOUNDS
@DEBUG_FORCE_SPAWN:
	LDA @LOCAL06
	CMP #256
	BCS @CHECK_BOUNDS
	CPX #224
	BCCL @NEXT_NPC
	BRA @CHECK_BOUNDS
@NORMAL_SPAWN_CHECK:
	LDA NPC_SPAWNS_ENABLED
	DEC
	BEQ @CHECK_BOUNDS
	LDA @LOCAL06
	CMP #256
	BCS @CHECK_BOUNDS
	CPX #224
	BCCL @NEXT_NPC
@CHECK_BOUNDS:
	LDA @LOCAL06
	STA @VIRTUAL02
	LDA #.LOWORD(-64)
	CLC
	SBC @VIRTUAL02
	JUMPGTS @NEXT_NPC
	LDA @LOCAL06
	STA @VIRTUAL02
	LDA #320
	CLC
	SBC @VIRTUAL02
	JUMPLTEQS @NEXT_NPC
	STX @VIRTUAL02
	LDA #.LOWORD(-64)
	CLC
	SBC @VIRTUAL02
	JUMPGTS @NEXT_NPC
	STX @VIRTUAL02
	LDA #320
	CLC
	SBC @VIRTUAL02
	JUMPLTEQS @NEXT_NPC
	LOADPTR NPC_CONFIG_TABLE, @VIRTUAL06
	LDA @LOCAL08
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(npc_config)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL02
	LDA @VIRTUAL06+2
	STA @LOCAL02+2
	LDX #.LOWORD(-1)
	STX @LOCAL05
	LDA PHOTOGRAPH_MAP_LOADING_MODE
	BNEL @PHOTOGRAPH_MODE
	LDA DEBUG
	BEQ @CHECK_EVENT_FLAG
	SEP #PROC_FLAGS::ACCUM8
	LDY #npc_config::appearance_style
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @LOCAL07
	BEQ @AFTER_EVENT_FLAG
	JSL CHECK_DEBUG_MODE_1
	CMP #0
	BEQ @AFTER_EVENT_FLAG
	LDY #npc_config::event_flag
	LDA [@VIRTUAL06],Y
	JSL GET_EVENT_FLAG
	STA @VIRTUAL02
	LDA @LOCAL07
	DEC
	DEC
	EOR @VIRTUAL02
	AND #$0001
	BEQL @NEXT_NPC
	BRA @AFTER_EVENT_FLAG
@CHECK_EVENT_FLAG:
	SEP #PROC_FLAGS::ACCUM8
	LDY #npc_config::appearance_style
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @LOCAL06
	BEQ @AFTER_EVENT_FLAG
	LDY #npc_config::event_flag
	LDA [@VIRTUAL06],Y
	JSL GET_EVENT_FLAG
	STA @VIRTUAL02
	LDA @LOCAL06
	DEC
	DEC
	EOR @VIRTUAL02
	AND #$0001
	BEQL @NEXT_NPC
@AFTER_EVENT_FLAG:
	LDA DEBUG
	BEQ @NORMAL_CHECK_NPC_FLAG
	LDA SHOW_NPC_FLAG
	BEQ @DEBUG_CREATE_ENTITY
	LDA [@VIRTUAL06]
	AND #$00FF
	CMP #3
	BNEL @SET_ENTITY_ATTRIBUTES
@DEBUG_CREATE_ENTITY:
	MOVE_INT @LOCAL02, @VIRTUAL06
	LDY #npc_config::event_script
	LDA [@VIRTUAL06],Y
	JSL CLAMP_TO_DEBUG_MAX
	STA @LOCAL07
	LDY @LOCAL04
	STY @LOCAL00
	LDA @LOCAL03
	STA @VIRTUAL02
	STA @LOCAL01
	LDY #.LOWORD(-1)
	STY @LOCAL06
	LDA @LOCAL07
	TAX
	LDY #npc_config::sprite
	LDA [@VIRTUAL06],Y
	LDY @LOCAL06
	JSL CREATE_ENTITY
	TAX
	STX @LOCAL05
	BRA @SET_ENTITY_ATTRIBUTES
@NORMAL_CHECK_NPC_FLAG:
	LDA SHOW_NPC_FLAG
	BEQ @NORMAL_CREATE_ENTITY
	LDA [@VIRTUAL06]
	AND #$00FF
	CMP #3
	BNE @SET_ENTITY_ATTRIBUTES
@NORMAL_CREATE_ENTITY:
	LDY @LOCAL04
	STY @LOCAL00
	LDA @LOCAL03
	STA @VIRTUAL02
	STA @LOCAL01
	LDY #.LOWORD(-1)
	STY @LOCAL07
	MOVE_INT @LOCAL02, @VIRTUAL06
	LDY #npc_config::event_script
	LDA [@VIRTUAL06],Y
	TAX
	LDY #npc_config::sprite
	LDA [@VIRTUAL06],Y
	LDY @LOCAL07
	JSL CREATE_ENTITY
	TAX
	STX @LOCAL05
	BRA @SET_ENTITY_ATTRIBUTES
@PHOTOGRAPH_MODE:
	SEP #PROC_FLAGS::ACCUM8
	LDY #npc_config::appearance_style
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNE @SET_ENTITY_ATTRIBUTES
	LDY @LOCAL04
	STY @LOCAL00
	LDA @LOCAL03
	STA @VIRTUAL02
	STA @LOCAL01
	LDY #.LOWORD(-1)
	STY @LOCAL06
	LDX #EVENT_SCRIPT::EVENT_799
	LDY #npc_config::sprite
	LDA [@VIRTUAL06],Y
	LDY @LOCAL06
	JSL CREATE_ENTITY
	TAX
	STX @LOCAL05
@SET_ENTITY_ATTRIBUTES:
	LDX @LOCAL05
	CPX #.LOWORD(-1)
	BEQ @NEXT_NPC
	TXA
	ASL
	TAX
	MOVE_INT @LOCAL02, @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDY #npc_config::direction
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA ENTITY_DIRECTIONS,X
	LDA @LOCAL08
	STA ENTITY_NPC_IDS,X
@NEXT_NPC:
	INC @LOCAL09
@NPC_LOOP_CHECK:
	LDA @LOCAL09
	CMP @LOCAL0A
	BNEL @PROCESS_NPC
@RETURN:
	END_C_FUNCTION
