
SPAWN_NPCS_AT_SECTOR:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @LOCAL0C
	STA @VIRTUAL04
	STA @LOCAL0B
	LDA @VIRTUAL04
	CMP #32
	BCC @CHECK_SECTOR_X
	JMP @RETURN
@CHECK_SECTOR_X:
	LDA @LOCAL0C
	CMP #40
	BCC @LOOKUP_PLACEMENT_TABLE
	JMP @RETURN
@LOOKUP_PLACEMENT_TABLE:
	LDA @VIRTUAL04
	ASL
	STA @VIRTUAL02
	LDA @LOCAL0C
	OPTIMIZED_MULT @VIRTUAL04, 64
	CLC
	ADC @VIRTUAL02
	TAX
	LDA f:SPRITE_PLACEMENT_PTR_TABLE,X
	BEQL @RETURN
	STORE_INT1632 @VIRTUAL06
	CLC
	VAR_ADD_CONST_INT_ASSIGN SPRITE_PLACEMENT_TABLE & $FF0000, @VIRTUAL06
	LDA [@VIRTUAL06]
	STA @LOCAL0A
	INC @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	STZ @LOCAL09
	JMP @CHECK_NPC_INDEX
@PROCESS_NPC:
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	LDA [@VIRTUAL06] ;sprite_placement::id
	STA @LOCAL08
	SEP #PROC_FLAGS::ACCUM8
	LDY #sprite_placement::y_coord
	LDA [@VIRTUAL0A],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
	STX @LOCAL07
	SEP #PROC_FLAGS::ACCUM8
	LDY #sprite_placement::x_coord
	LDA [@VIRTUAL0A],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAY
	STY @LOCAL06
	LDA #.SIZEOF(sprite_placement)
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	TXA
	LSR
	LSR
	LSR
	STA @VIRTUAL02
	LDA @LOCAL0B
	STA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, 32
	CLC
	ADC @VIRTUAL02
	STA @LOCAL05
	TYA
	LSR
	LSR
	LSR
	STA @VIRTUAL02
	LDA @LOCAL0C
	OPTIMIZED_MULT @VIRTUAL04, 32
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL02
	LDA @LOCAL05
	LSR
	LSR
	LSR
	LSR
	LSR
	PHA
	LDA @VIRTUAL02
	LSR
	LSR
	LSR
	LSR
	OPTIMIZED_MULT @VIRTUAL04, 32
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	TAX
	LDA f:GLOBAL_MAP_TILESETPALETTE_DATA,X
	AND #$00FF
	LSR
	LSR
	LSR
	CMP LOADED_MAP_TILE_COMBO
	BNEL @SKIP_NPC
	LDA @LOCAL08
	JSL FIND_ENTITY_BY_NPC_ID_LINKED
	CMP #0
	BNEL @SKIP_NPC
	LDX @LOCAL07
	STX @VIRTUAL02
	LDA @VIRTUAL04
	XBA
	AND #$FF00
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL02
	STA @LOCAL04
	LDY @LOCAL06
	STY @VIRTUAL02
	LDA @LOCAL0C
	XBA
	AND #$FF00
	CLC
	ADC @VIRTUAL02
	TAY
	STY @LOCAL03
	LDA @LOCAL04
	STA @VIRTUAL02
	SEC
	SBC BG1_X_POS
	STA @LOCAL05
	TYA
	SEC
	SBC BG1_Y_POS
	TAX
	LDA DEBUG
	BEQ @CHECK_SPAWN_ENABLED_NORMAL
	LDA PAD_STATE
	AND #PAD::L_BUTTON | PAD::R_BUTTON
	BNE @DEBUG_FORCE_SPAWN
	LDA NPC_SPAWNS_ENABLED
	DEC
	BEQ @CHECK_OFFSCREEN_RANGE
@DEBUG_FORCE_SPAWN:
	LDA @LOCAL05
	CMP #256
	BCS @CHECK_OFFSCREEN_RANGE
	CPX #224
	BCCL @SKIP_NPC
	BRA @CHECK_OFFSCREEN_RANGE
@CHECK_SPAWN_ENABLED_NORMAL:
	LDA NPC_SPAWNS_ENABLED
	DEC
	BEQ @CHECK_OFFSCREEN_RANGE
	LDA @LOCAL05
	CMP #256
	BCS @CHECK_OFFSCREEN_RANGE
	CPX #224
	BCCL @SKIP_NPC
@CHECK_OFFSCREEN_RANGE:
	LDA @LOCAL05
	STA @VIRTUAL02
	LDA #.LOWORD(-64)
	CLC
	SBC @VIRTUAL02
	JUMPGTS @SKIP_NPC
	LDA @LOCAL05
	STA @VIRTUAL02
	LDA #320
	CLC
	SBC @VIRTUAL02
	JUMPLTEQS @SKIP_NPC
	STX @VIRTUAL02
	LDA #.LOWORD(-64)
	CLC
	SBC @VIRTUAL02
	JUMPGTS @SKIP_NPC
	STX @VIRTUAL02
	LDA #320
	CLC
	SBC @VIRTUAL02
	JUMPLTEQS @SKIP_NPC
	LOADPTR NPC_CONFIG_TABLE, @VIRTUAL06
	LDA @LOCAL08
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(npc_config)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL02
	LDA @VIRTUAL06+2
	STA @LOCAL02+2
	LDX #.LOWORD(-1)
	STX @LOCAL05
	LDA PHOTOGRAPH_MAP_LOADING_MODE
	BNEL @PHOTOGRAPH_MODE_SPAWN
	LDA DEBUG
	BEQ @CHECK_APPEARANCE_NORMAL
	SEP #PROC_FLAGS::ACCUM8
	LDY #npc_config::appearance_style
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @LOCAL06
	BEQ @APPEARANCE_OK
	JSL CHECK_DEBUG_MODE_1
	CMP #0
	BEQ @APPEARANCE_OK
	LDY #npc_config::event_flag
	LDA [@VIRTUAL06],Y
	JSL GET_EVENT_FLAG
	STA @VIRTUAL02
	LDA @LOCAL06
	DEC
	DEC
	EOR @VIRTUAL02
	AND #$0001
	BEQL @SKIP_NPC
	BRA @APPEARANCE_OK
@CHECK_APPEARANCE_NORMAL:
	SEP #PROC_FLAGS::ACCUM8
	LDY #npc_config::appearance_style
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA @LOCAL07
	BEQ @APPEARANCE_OK
	LDY #npc_config::event_flag
	LDA [@VIRTUAL06],Y
	JSL GET_EVENT_FLAG
	STA @VIRTUAL02
	LDA @LOCAL07
	DEC
	DEC
	EOR @VIRTUAL02
	AND #$0001
	BEQL @SKIP_NPC
@APPEARANCE_OK:
	LDA DEBUG
	BEQ @CHECK_SHOW_NPC_NORMAL
	LDA SHOW_NPC_FLAG
	BEQ @CREATE_ENTITY_DEBUG
	LDA [@VIRTUAL06]
	AND #$00FF
	CMP #3
	BNEL @ENTITY_CREATED
@CREATE_ENTITY_DEBUG:
	MOVE_INT @LOCAL02, @VIRTUAL06
	LDY #npc_config::event_script
	LDA [@VIRTUAL06],Y
	JSL CLAMP_TO_DEBUG_MAX
	STA @LOCAL07
	LDA @LOCAL04
	STA @VIRTUAL02
	STA @LOCAL00
	LDY @LOCAL03
	STY @LOCAL01
	LDY #.LOWORD(-1)
	STY @LOCAL05
	LDA @LOCAL07
	TAX
	LDY #npc_config::sprite
	LDA [@VIRTUAL06],Y
	LDY @LOCAL05
	JSL CREATE_ENTITY
	TAX
	STX @LOCAL05
	BRA @ENTITY_CREATED
@CHECK_SHOW_NPC_NORMAL:
	LDA SHOW_NPC_FLAG
	BEQ @CREATE_ENTITY_NORMAL
	LDA [@VIRTUAL06]
	AND #$00FF
	CMP #3
	BNE @ENTITY_CREATED
@CREATE_ENTITY_NORMAL:
	LDA @LOCAL04
	STA @VIRTUAL02
	STA @LOCAL00
	LDY @LOCAL03
	STY @LOCAL01
	LDY #.LOWORD(-1)
	STY @LOCAL06
	MOVE_INT @LOCAL02, @VIRTUAL06
	LDY #npc_config::event_script
	LDA [@VIRTUAL06],Y
	TAX
	LDY #npc_config::sprite
	LDA [@VIRTUAL06],Y
	LDY @LOCAL06
	JSL CREATE_ENTITY
	TAX
	STX @LOCAL05
	BRA @ENTITY_CREATED
@PHOTOGRAPH_MODE_SPAWN:
	SEP #PROC_FLAGS::ACCUM8
	LDY #npc_config::appearance_style
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNE @ENTITY_CREATED
	LDA @LOCAL04
	STA @VIRTUAL02
	STA @LOCAL00
	LDY @LOCAL03
	STY @LOCAL01
	LDY #.LOWORD(-1)
	STY @LOCAL05
	LDX #EVENT_SCRIPT::EVENT_799
	LDY #npc_config::sprite
	LDA [@VIRTUAL06],Y
	LDY @LOCAL05
	JSL CREATE_ENTITY
	TAX
	STX @LOCAL05
@ENTITY_CREATED:
	LDX @LOCAL05
	CPX #.LOWORD(-1)
	BEQ @SKIP_NPC
	TXA
	ASL
	TAX
	MOVE_INT @LOCAL02, @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDY #npc_config::direction
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	STA ENTITY_DIRECTIONS,X
	LDA @LOCAL08
	STA ENTITY_NPC_IDS,X
@SKIP_NPC:
	INC @LOCAL09
@CHECK_NPC_INDEX:
	LDA @LOCAL09
	CMP @LOCAL0A
	BNEL @PROCESS_NPC
@RETURN:
	END_C_FUNCTION
