
CHECK_DOOR_IN_DIRECTION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL01
	ASL
	TAX
	LDA GAME_STATE+game_state::leader_x_coord
	LSR
	LSR
	LSR
	CLC
	ADC f:DIRECTION_X_OFFSET_TABLE,X
	TAY
	STY @LOCAL00
	LDA GAME_STATE+game_state::leader_y_coord
	LSR
	LSR
	LSR
	CLC
	ADC f:DIRECTION_Y_OFFSET_TABLE,X
	STA @VIRTUAL02
	LDA @LOCAL01
	CMP #6
	BNE @AFTER_LEFT_ADJUST
	DEY
	STY @LOCAL00
@AFTER_LEFT_ADJUST:
	LDX @VIRTUAL02
	TYA
	JSL FIND_DOOR_AT_POSITION
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
	CPX #$00FF
	BNE @CHECK_RESULT
	LDX @VIRTUAL02
	LDY @LOCAL00
	TYA
	INC
	JSL FIND_DOOR_AT_POSITION
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	TAX
@CHECK_RESULT:
	CPX #$00FF
	BEQ @RETURN
	CPX #6
	BNE @RETURN
	LOADPTR DOOR_DATA & $FF0000, @VIRTUAL06
	LDA DOOR_FOUND
	AND #$7FFF
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA DOOR_FOUND_TYPE
	STA UNREAD_7E5DDC
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, MAP_OBJECT_TEXT
	LDA #.LOWORD(-2)
	STA INTERACTING_NPC_ID
@RETURN:
	END_C_FUNCTION
