
FIND_DOOR_AT_POSITION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TXY
	STY @LOCAL01
	STA @LOCAL00
	LOADPTR DOOR_POINTER_TABLE, @VIRTUAL0A
	LDA @LOCAL00
	LSR
	LSR
	LSR
	LSR
	LSR
	STA @VIRTUAL02
	TYA
	AND #$FFE0
	CLC
	ADC @VIRTUAL02
	ASL
	ASL
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	LDA [@VIRTUAL06]
	TAX
	BNE @HAS_DOORS
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FF
	BRA @RETURN
@HAS_DOORS:
	.A16
	INC @VIRTUAL06
	INC @VIRTUAL06
	LDA @LOCAL00
	AND #$001F
	STA @VIRTUAL02
	LDY @LOCAL01
	TYA
	AND #$001F
	STA @LOCAL00
	BRA @LOOP_CHECK
@CHECK_DOOR:
	SEP #PROC_FLAGS::ACCUM8
	LDY #1
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	CMP @VIRTUAL02
	BNE @NEXT_DOOR
	LDA @LOCAL00
	STA @VIRTUAL04
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	CMP @VIRTUAL04
	BNE @NEXT_DOOR
	LDY #3
	LDA [@VIRTUAL06],Y
	STA DOOR_FOUND
	INC @VIRTUAL06
	INC @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	STA DOOR_FOUND_TYPE
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	BRA @RETURN
@NEXT_DOOR:
	.A16
	LDA #5
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEX
@LOOP_CHECK:
	CPX #0
	BNE @CHECK_DOOR
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FF
@RETURN:
	END_C_FUNCTION
