
GET_STAIRS_MOVEMENT_DIRECTION:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDY #$0001
	LDX GAME_STATE+game_state::leader_direction
	CMP #$0100
	BEQ @STAIRS_RIGHT_A
	CMP #$0000
	BEQ @STAIRS_LEFT_A
	CMP #$0300
	BEQ @STAIRS_RIGHT_B
	CMP #$0200
	BEQ @STAIRS_LEFT_B
	BRA @RETURN
@STAIRS_RIGHT_A:
	CPX #$0000
	BEQ @RIGHT_A_BLOCK
	TXA
	AND #$0003
	BEQ @RIGHT_A_SET_DIR
@RIGHT_A_BLOCK:
	LDY #$0000
@RIGHT_A_SET_DIR:
	LDA #$0002
	STA AUTO_MOVEMENT_DIRECTION
	BRA @RETURN
@STAIRS_LEFT_A:
	CPX #$0000
	BEQ @LEFT_A_BLOCK
	TXA
	AND #$0003
	BEQ @LEFT_A_SET_DIR
@LEFT_A_BLOCK:
	LDY #$0000
@LEFT_A_SET_DIR:
	LDA #$0006
	STA AUTO_MOVEMENT_DIRECTION
	BRA @RETURN
@STAIRS_RIGHT_B:
	TXA
	AND #$0007
	BEQ @RIGHT_B_SET_DIR
	LDY #$0000
@RIGHT_B_SET_DIR:
	LDA #$0002
	STA AUTO_MOVEMENT_DIRECTION
	BRA @RETURN
@STAIRS_LEFT_B:
	TXA
	AND #$0007
	BEQ @LEFT_B_SET_DIR
	LDY #$0000
@LEFT_B_SET_DIR:
	LDA #$0006
	STA AUTO_MOVEMENT_DIRECTION
@RETURN:
	TYA
	RTS
