
HANDLE_STAIRS_LEAVE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #0
	STA @LOCAL01
	LDA STAIRS_DIRECTION
	BEQ @CHECK_Y_ASCENDING
	LDA STAIRS_DIRECTION
	CMP #256
	BNE @CHECK_Y_DESCENDING
@CHECK_Y_ASCENDING:
	LDA GAME_STATE + game_state::leader_y_coord
	CMP STAIRS_NEW_Y
	BCS @CHECK_REACHED
	LDA #1
	STA @LOCAL01
	BRA @CHECK_REACHED
@CHECK_Y_DESCENDING:
	LDA GAME_STATE + game_state::leader_y_coord
	CMP STAIRS_NEW_Y
	BLTEQ @CHECK_REACHED
	LDA #1
	STA @LOCAL01
@CHECK_REACHED:
	LDA @LOCAL01
	BEQ @NOT_REACHED
	LDA #.LOWORD(-1)
	STA STAIRS_DIRECTION
	STZ GAME_STATE + game_state::walking_style
	STZ PLAYER_MOVEMENT_FLAGS
	LDA STAIRS_NEW_X
	STA GAME_STATE + game_state::leader_x_coord
	LDA STAIRS_NEW_Y
	STA GAME_STATE + game_state::leader_y_coord
	STZ GAME_STATE + game_state::leader_y_frac
	STZ GAME_STATE + game_state::leader_x_frac
	STZ UNREAD_7E5DBA
	BRA @DONE
@NOT_REACHED:
	LOADPTR HANDLE_STAIRS_LEAVE, @LOCAL00
	LDA #1
	JSL SCHEDULE_OVERWORLD_TASK
@DONE:
	END_C_FUNCTION
