
HANDLE_STAIRS_ENTER:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #0
	STA @LOCAL01
	LDA STAIRS_DIRECTION
	BEQ @VERTICAL_STAIRS
	LDA STAIRS_DIRECTION
	CMP #256
	BNE @HORIZONTAL_STAIRS
@VERTICAL_STAIRS:
	LDA STAIRS_NEW_Y
	DEC
	CMP GAME_STATE+game_state::leader_y_coord
	BLTEQ @CHECK_ENTERED
	LDA #1
	STA @LOCAL01
	BRA @CHECK_ENTERED
@HORIZONTAL_STAIRS:
	LDA STAIRS_NEW_Y
	INC
	CMP GAME_STATE+game_state::leader_y_coord
	BCS @CHECK_ENTERED
	LDA #1
	STA @LOCAL01
@CHECK_ENTERED:
	LDA @LOCAL01
	BEQ @RESCHEDULE
	LDA #WALKING_STYLE::STAIRS
	STA GAME_STATE+game_state::walking_style
	LDA STAIRS_NEW_X
	STA GAME_STATE+game_state::leader_x_coord
	LDA STAIRS_NEW_Y
	STA GAME_STATE+game_state::leader_y_coord
	STZ GAME_STATE + game_state::leader_y_frac
	STZ GAME_STATE + game_state::leader_x_frac
	BRA @DONE
@RESCHEDULE:
	LOADPTR HANDLE_STAIRS_ENTER, @LOCAL00
	LDA #1
	JSL SCHEDULE_OVERWORLD_TASK
@DONE:
	END_C_FUNCTION
