
HANDLE_ESCALATOR_MOVEMENT:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL06
	STX @LOCAL05
	STA @LOCAL04
	LDA DEMO_FRAMES_LEFT
	BNEL @RETURN
	JSL CLEAR_AUTO_MOVEMENT_BUFFER
	LDX @LOCAL05
	TXA
	ASL
	ASL
	ASL
	TAX
	STX @LOCAL03
	LDY @LOCAL06
	TYA
	ASL
	ASL
	ASL
	STA @LOCAL02
	LDA @LOCAL04
	AND #$8000
	BEQ @ENTER_ESCALATOR
	LDY #.LOWORD(GAME_STATE) + game_state::walking_style
	LDA __BSS_START__,Y
	CMP #12
	BNEL @RETURN
	LDA #0
	STA __BSS_START__,Y
	LDA #3
	STA PLAYER_MOVEMENT_FLAGS
	LDA ESCALATOR_ENTRANCE_DIRECTION
	XBA
	AND #$00FF
	ASL
	STA @VIRTUAL02
	TXA
	LDX @VIRTUAL02
	CLC
	ADC f:ESCALATOR_OFFSET_TABLE+8,X
	STA @VIRTUAL04
	LDA @LOCAL02
	STA @LOCAL00
	LDY @VIRTUAL04
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL CALCULATE_MOVEMENT_PATH_STEPS
	TAY
	STY @LOCAL01
	LDX #16
	STX @LOCAL05
	LDX @VIRTUAL02
	LDA f:ESCALATOR_OFFSET_TABLE+16,X
	LDX @LOCAL05
	JSL RECORD_REPEATED_AUTO_MOVEMENT
	LOADPTR FINISH_ESCALATOR_MOVEMENT, @LOCAL00
	LDY @LOCAL01
	TYA
	INC
	JSL SCHEDULE_OVERWORLD_TASK
	JSL QUEUE_AUTO_MOVEMENT_STEP
	STZ ESCALATOR_ENTRANCE_DIRECTION
	LDA #1
	STA UNREAD_7E5DBA
	BRA @STORE_ESCALATOR_STATE
@ENTER_ESCALATOR:
	LDA GAME_STATE+game_state::walking_style
	CMP #WALKING_STYLE::ESCALATOR
	BEQ @RETURN
	LDA #1
	STA UNREAD_7E5DBA
	LDA @LOCAL04
	STA ESCALATOR_ENTRANCE_DIRECTION
	XBA
	AND #$00FF
	ASL
	STA @LOCAL06
	TAX
	LDA f:ESCALATOR_OFFSET_TABLE+16,X
	STA GAME_STATE+game_state::leader_direction
	LDA #3
	STA PLAYER_MOVEMENT_FLAGS
	LDA @LOCAL06
	PHA
	LDX @LOCAL03
	TXA
	PLX
	CLC
	ADC f:ESCALATOR_OFFSET_TABLE,X
	STA @VIRTUAL04
	LDA @LOCAL02
	STA @LOCAL00
	LDY @VIRTUAL04
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL CALCULATE_MOVEMENT_PATH_STEPS
	TAX
	LOADPTR START_ESCALATOR_MOVEMENT, @LOCAL00
	TXA
	INC
	JSL SCHEDULE_OVERWORLD_TASK
	JSL QUEUE_AUTO_MOVEMENT_STEP
@STORE_ESCALATOR_STATE:
	LDA @VIRTUAL04
	STA ESCALATOR_NEW_X
	LDA @LOCAL02
	STA ESCALATOR_NEW_Y
	LDA #.LOWORD(-1)
	STA STAIRS_DIRECTION
@RETURN:
	END_C_FUNCTION
