
HANDLE_STAIRS_MOVEMENT:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
.IF .DEFINED(USA)
	STACK_RESERVE_INT16
.ELSE
	@LOCAL01 := @LOCAL04
.ENDIF
	STACK_RESERVE_INT16 "LOCAL02"
	STACK_RESERVE_INT16 "LOCAL03"
	STACK_RESERVE_INT16 "LOCAL04"
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @VIRTUAL02
	TXY
	STY @LOCAL04
	STA @LOCAL03
	LDA DEMO_FRAMES_LEFT
	BNEL @DONE
	JSL CLEAR_AUTO_MOVEMENT_BUFFER
	LDA @LOCAL03
	TAX
	XBA
	AND #$00FF
	STA @VIRTUAL04
	LDY @LOCAL04
	TYA
	ASL
	ASL
	ASL
	TAY
	STY @LOCAL04
	LDA @VIRTUAL02
	ASL
	ASL
	ASL
	STA @VIRTUAL02
	LDA GAME_STATE+game_state::walking_style
	BNEL @LEAVING_STAIRS
	TXA
	JSR GET_STAIRS_MOVEMENT_DIRECTION
	CMP #0
	BNEL @DONE
	LDA AUTO_MOVEMENT_DIRECTION
	STA GAME_STATE+game_state::leader_direction
	STZ NOT_MOVING_IN_SAME_DIRECTION_FACED
	LDA #3
	STA PLAYER_MOVEMENT_FLAGS
	LDA #1
	STA UNREAD_7E5DBA
	LDA @VIRTUAL04
	XBA
	AND #$FF00
	STA STAIRS_DIRECTION
	LDA @VIRTUAL04
	ASL
	TAX
	LDY @LOCAL04
	TYA
	CLC
	ADC f:STAIRS_ENTER_Y_OFFSET_TABLE,X
	STA @LOCAL03
	LDA @VIRTUAL02
	CLC
	ADC f:STAIRS_ENTER_X_OFFSET_TABLE,X
	STA @VIRTUAL02
	STA @LOCAL00
	LDY @LOCAL03
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL CALCULATE_MOVEMENT_PATH_STEPS
	TAY
	STY @LOCAL02
	BNE @STEPS_NONZERO
	INY
	STY @LOCAL02
@STEPS_NONZERO:
	LDX #6
	STX @LOCAL01
	LDA @VIRTUAL04
	ASL
	TAX
	LDA f:STAIRS_DIRECTION_TABLE,X
	LDX @LOCAL01
	JSL RECORD_REPEATED_AUTO_MOVEMENT
	LOADPTR HANDLE_STAIRS_ENTER, @LOCAL00
	LDY @LOCAL02
	TYA
	JSL SCHEDULE_OVERWORLD_TASK
	BRA @STORE_NEW_COORDS
@LEAVING_STAIRS:
	LDA @VIRTUAL04
	ASL
	TAX
	TYA
	CLC
	ADC f:STAIRS_EXIT_Y_OFFSET_TABLE,X
	STA @LOCAL03
	LDA @VIRTUAL02
	CLC
	ADC f:STAIRS_EXIT_X_OFFSET_TABLE,X
	STA @VIRTUAL02
	STA @LOCAL00
	LDY @LOCAL03
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL CALCULATE_MOVEMENT_PATH_STEPS
	TAY
	STY @LOCAL02
	BNE @LEAVE_STEPS_NONZERO
	INY
	STY @LOCAL02
@LEAVE_STEPS_NONZERO:
	LDX #12
	STX @LOCAL04
	LDA @VIRTUAL04
	ASL
	TAX
	LDA f:STAIRS_FACING_DIRECTION_TABLE,X
	LDX @LOCAL04
	JSL RECORD_REPEATED_AUTO_MOVEMENT
	LOADPTR HANDLE_STAIRS_LEAVE, @LOCAL00
	LDY @LOCAL02
	TYA
	JSL SCHEDULE_OVERWORLD_TASK
@STORE_NEW_COORDS:
	LDA @LOCAL03
	STA STAIRS_NEW_X
	LDA @VIRTUAL02
	STA STAIRS_NEW_Y
	JSL QUEUE_AUTO_MOVEMENT_STEP
@DONE:
	END_C_FUNCTION
