
PROCESS_DOOR_AT_TILE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TXY
	STY @LOCAL01
	STA @VIRTUAL02
	TYX
	LDA @VIRTUAL02
	JSL FIND_DOOR_AT_POSITION
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQ @HANDLE_TYPE0
	CMP #DOOR_TYPE::TYPE1
	BEQ @HANDLE_TYPE1
	CMP #DOOR_TYPE::TYPE2
	BEQ @HANDLE_TYPE2
	CMP #DOOR_TYPE::TYPE3
	BEQ @HANDLE_TYPE3
	CMP #DOOR_TYPE::TYPE4
	BEQ @HANDLE_TYPE4
	CMP #DOOR_TYPE::TYPE5
	BEQ @HANDLE_TYPE5_7
	CMP #DOOR_TYPE::TYPE7
	BEQ @HANDLE_TYPE5_7
	CMP #DOOR_TYPE::TYPE6
	BEQ @HANDLE_TYPE6
	BRA @DONE
@HANDLE_TYPE0:
	LDA DOOR_FOUND
	JSR CHECK_DOOR_EVENT_FLAG
	LDA #0
	STA @VIRTUAL04
	STA @LOCAL00
	BRA @DONE
@HANDLE_TYPE1:
	LDA DOOR_FOUND
	JSR SET_WALKING_STYLE_STAIRS
	LDA #1
	STA @VIRTUAL04
	STA @LOCAL00
	BRA @DONE
@HANDLE_TYPE2:
	LDA DOOR_FOUND
	JSR TRY_ACTIVATE_DOOR
	LDA #0
	STA @VIRTUAL04
	STA @LOCAL00
	BRA @DONE
@HANDLE_TYPE3:
	LDY @LOCAL01
	LDX @VIRTUAL02
	LDA DOOR_FOUND
	JSR HANDLE_ESCALATOR_MOVEMENT
	LDA #0
	STA @VIRTUAL04
	STA @LOCAL00
	BRA @DONE
@HANDLE_TYPE4:
	LDY @LOCAL01
	LDX @VIRTUAL02
	LDA DOOR_FOUND
	JSR HANDLE_STAIRS_MOVEMENT
	LDA #1
	STA @VIRTUAL04
	STA @LOCAL00
	BRA @DONE
@HANDLE_TYPE5_7:
	LDA DOOR_FOUND
	JSR DOOR_HANDLER_NOP
	LDA #0
	STA @VIRTUAL04
	STA @LOCAL00
	BRA @DONE
@HANDLE_TYPE6:
	LDA DOOR_FOUND
	JSR DOOR_HANDLER_TYPE6
	LDA #0
	STA @VIRTUAL04
	STA @LOCAL00
@DONE:
	LDA @LOCAL00
	STA @VIRTUAL04
	END_C_FUNCTION
