
PROCESS_DOOR_INTERACTIONS:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDX #0
	STX @LOCAL02
	TXY
	STY @LOCAL01
	BRA @CHECK_LOOP
@PROCESS_INTERACTION:
	JSL GET_CURRENT_INTERACTION_TYPE
	CMP #10
	BNE @NEXT_INTERACTION
	JSL GET_QUEUED_INTERACTION_TEXT
	LDY @LOCAL01
	TYA
	ASL
	ASL
	CLC
	ADC #.LOWORD(DOOR_INTERACTIONS)
	TAY
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDY @LOCAL01
	INY
	STY @LOCAL01
@NEXT_INTERACTION:
	LDA CURRENT_QUEUED_INTERACTION
	INC
	AND #$0003
	STA CURRENT_QUEUED_INTERACTION
	LDX @LOCAL02
	INX
	STX @LOCAL02
@CHECK_LOOP:
	STX @VIRTUAL02
	LDA #4
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @WRITE_TERMINATOR
	LDA CURRENT_QUEUED_INTERACTION
	CMP NEXT_QUEUED_INTERACTION
	BNE @PROCESS_INTERACTION
@WRITE_TERMINATOR:
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
	LDY @LOCAL01
	TYA
	ASL
	ASL
	CLC
	ADC #.LOWORD(DOOR_INTERACTIONS)
	TAY
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDX #0
	STX @LOCAL02
	BRA @CHECK_REQUEUE
@REQUEUE_INTERACTION:
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #10
	JSL QUEUE_INTERACTION
	LDX @LOCAL02
	INX
	STX @LOCAL02
@CHECK_REQUEUE:
	TXA
	ASL
	ASL
	CLC
	ADC #.LOWORD(DOOR_INTERACTIONS)
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BNE @REQUEUE_INTERACTION
	END_C_FUNCTION
