
SET_WALKING_STYLE_STAIRS:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	TAY
	LDX #.LOWORD(GAME_STATE) + game_state::walking_style
	LDA __BSS_START__,X
	CMP #$0007
	BEQ @ALREADY_ON_STAIRS
	CMP #$0008
	BEQ @ALREADY_ON_STAIRS
	CPY #$0000
	BNE @SET_DOWNSTAIRS
	LDA #$0007
	STA __BSS_START__,X
	BRA @UPDATE_DIRECTION
@SET_DOWNSTAIRS:
	LDA #$0008
	STA __BSS_START__,X
@UPDATE_DIRECTION:
	LDX #.LOWORD(GAME_STATE) + game_state::leader_direction
	LDA __BSS_START__,X
	AND #$FFFE
	STA __BSS_START__,X
	LDA #$FFFF
	STA STAIRS_DIRECTION
@ALREADY_ON_STAIRS:
	RTS
