
TRY_ACTIVATE_DOOR:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL01
	LDA PLAYER_HAS_DONE_SOMETHING_THIS_FRAME
	BEQ @RETURN
	LDA GAME_STATE + game_state::camera_mode
	CMP #2
	BEQ @RETURN
	LDA PENDING_INTERACTIONS
	BNE @RETURN
	LDA ENEMY_HAS_BEEN_TOUCHED
	ORA BATTLE_SWIRL_COUNTDOWN
	BNE @RETURN
	LDA @LOCAL01
	AND #$7FFF
	STA @LOCAL01
	LDA #1
	STA USING_DOOR
	LOADPTR DOOR_DATA & $FF0000, @VIRTUAL06
	LDA @LOCAL01
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA #2
	JSL QUEUE_INTERACTION
	JSL CLEAR_PARTY_SPRITE_HIDE_FLAGS
@RETURN:
	PLD
	RTS
