
UPDATE_ESCALATOR_MOVEMENT:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA ENEMY_HAS_BEEN_TOUCHED
	BNEL @RETURN
	LDA BATTLE_SWIRL_COUNTDOWN
	BEQ @MAP_DIRECTION
	DEC BATTLE_SWIRL_COUNTDOWN
	JMP @RETURN
@MAP_DIRECTION:
	LDA ESCALATOR_ENTRANCE_DIRECTION
	AND #$0300
	BEQ @DIR_UP_LEFT
	CMP #2 << 8
	BEQ @DIR_DOWN_LEFT
	CMP #1 << 8
	BEQ @DIR_UP_RIGHT
	CMP #3 << 8
	BEQ @DIR_DOWN_RIGHT
	BRA @CHECK_COLLISION
@DIR_UP_LEFT:
	LDA #7
	STA @VIRTUAL02
	STA @LOCAL03
	BRA @CHECK_COLLISION
@DIR_DOWN_LEFT:
	LDA #5
	STA @VIRTUAL02
	STA @LOCAL03
	BRA @CHECK_COLLISION
@DIR_UP_RIGHT:
	LDA #1
	STA @VIRTUAL02
	STA @LOCAL03
	BRA @CHECK_COLLISION
@DIR_DOWN_RIGHT:
	LDA #3
	STA @VIRTUAL02
	STA @LOCAL03
@CHECK_COLLISION:
	LDA #.LOWORD(-1)
	STA LADDER_STAIRS_TILE_X
	LDA @LOCAL03
	STA @VIRTUAL02
	STA @LOCAL00
	LDY GAME_STATE+game_state::current_party_members
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL CHECK_DIRECTIONAL_COLLISION
	LDA LADDER_STAIRS_TILE_X
	CMP #.LOWORD(-1)
	BEQ @APPLY_MOVEMENT
	LDX LADDER_STAIRS_TILE_Y
	LDA LADDER_STAIRS_TILE_X
	JSL PROCESS_DOOR_AT_TILE
@APPLY_MOVEMENT:
	LDX #1
.IF .DEFINED(JPN)
	BEQL @SET_LEADER_MOVED
.ELSE
	BEQ @SET_LEADER_MOVED
.ENDIF
	LDY #.LOWORD(GAME_STATE) + game_state::leader_x_frac
	STY @LOCAL02
	LDA @VIRTUAL02
	ASL
	ASL
	STA @LOCAL01
	CLC
.IF .DEFINED(JPN)
	ADC #.LOWORD(HORIZONTAL_MOVEMENT_SPEEDS)
	CLC
	ADC #.SIZEOF(movement_speeds) * 12
.ELSE
	ADC #.LOWORD(HORIZONTAL_MOVEMENT_SPEEDS) + .SIZEOF(movement_speeds) * 12
.ENDIF
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL0A
	LDY @LOCAL02
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDY #.LOWORD(GAME_STATE) + game_state::leader_y_frac
	STY @LOCAL03
	LDA @LOCAL01
	CLC
.IF .DEFINED(JPN)
	ADC #.LOWORD(VERTICAL_MOVEMENT_SPEEDS)
	CLC
	ADC #.SIZEOF(movement_speeds) * 12
.ELSE
	ADC #.LOWORD(VERTICAL_MOVEMENT_SPEEDS) + .SIZEOF(movement_speeds) * 12
.ENDIF
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL0A
	LDY @LOCAL03
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
@SET_LEADER_MOVED:
	LDA #1
	STA GAME_STATE + game_state::leader_moved
@RETURN:
	END_C_FUNCTION
