
SETUP_RECT_WINDOW_HDMA:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STY @LOCAL05
	TXY
	STA @VIRTUAL04
	LDX @PARAM03
	STX @VIRTUAL02
	LDA RECTANGLE_WINDOW_BUFFER_INDEX
	AND #$0001
	BEQ @USE_SECOND_BUFFER
	LDA #0
	STA @LOCAL04
	BRA @BUFFER_SELECTED
@USE_SECOND_BUFFER:
	LDA #766
	STA @LOCAL04
@BUFFER_SELECTED:
	LOADPTR BUFFER, @VIRTUAL06
	LDA @LOCAL04
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL01
	LDA @VIRTUAL06+2
	STA @LOCAL01+2
	LDX #224
	TYA
	JSR CLAMP_VALUE_TO_RANGE
	STA @LOCAL03
	LDX #224
	LDA @VIRTUAL02
	JSR CLAMP_VALUE_TO_RANGE
	STA @LOCAL02
	LDX #256
	LDA @VIRTUAL04
	JSR CLAMP_VALUE_TO_RANGE
	STA @VIRTUAL04
	LDX #256
	LDA @LOCAL05
	JSR CLAMP_VALUE_TO_RANGE
	STA @VIRTUAL02
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDY #127
	LDX #128
	LDA @LOCAL03
	JSR WRITE_WINDOW_HDMA_ENTRY
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDY @VIRTUAL02
	LDX @VIRTUAL04
	LDA @LOCAL02
	SEC
	SBC @LOCAL03
	JSR WRITE_WINDOW_HDMA_ENTRY
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDY #127
	LDX #128
	LDA #224
	SEC
	SBC @LOCAL02
	DEC
	JSR WRITE_WINDOW_HDMA_ENTRY
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA [@VIRTUAL06]
	LDX @LOCAL01
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01+2
	JSL ENABLE_OBJ_HDMA
	INC RECTANGLE_WINDOW_BUFFER_INDEX
	END_C_FUNCTION
