
CHAR_SELECT_PROMPT:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_PARAM_INT32 ;void (*)(int)
	STACK_RESERVE_PARAM_INT32 ;int (*checkValid)(int)
	STACK_RESERVE_RETURN_INT16 ;int
	END_STACK_VARS
	STX @LOCAL0D
	STA @LOCAL0C
	MOVE_INT @PARAM03, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL0B
	MOVE_INT @PARAM02, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @LOCAL0A
	JSR GET_ACTIVE_WINDOW_ADDRESS
	STA @LOCAL09
	CLC
	ADC #window_stats::argument_memory
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL08
	LDA @LOCAL0C
	CMP #1
	BNEL @BATTLE_STYLE_SELECT
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
	JSL SAVE_WINDOW_TEXT_ATTRIBUTES
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	CMP #1
	BNE @MULTI_PARTY_WINDOW
	LDX #WINDOW::SINGLE_CHARACTER_SELECT
	BRA @AFTER_WINDOW_ID
@MULTI_PARTY_WINDOW:
	CLC
	ADC #WINDOW::TARGETING_PROMPT
	TAX
	DEX
@AFTER_WINDOW_ID:
	STX @LOCAL07
	CREATE_WINDOW_NEAR @LOCAL07
	LDA #0
	STA @VIRTUAL02
	BRA @CHARACTER_LOOP_CHECK
@ADD_CHARACTER_ITEM:
	LDA @VIRTUAL02
	CLC
.IF .DEFINED(JPN)
	ADC #.LOWORD(GAME_STATE)
	CLC
	ADC #game_state::party_members
.ELSE
	ADC #.LOWORD(GAME_STATE) + game_state::party_members
.ENDIF
	STA @VIRTUAL04
	STA @LOCAL06
	LDX @VIRTUAL04
	LDA __BSS_START__,X
	AND #$00FF
	JSL GET_PARTY_CHARACTER_NAME
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #6
	LDA #.LOWORD(TEMPORARY_TEXT_BUFFER)
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	STZ TEMPORARY_TEXT_BUFFER + .SIZEOF(char_struct::name)
	REP #PROC_FLAGS::ACCUM8
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDY #0
	LDA @VIRTUAL02
	STA @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	ASL
	TAX
	STX @LOCAL05
	LDA @LOCAL06
	STA @VIRTUAL04
	LDX @VIRTUAL04
	LDA __BSS_START__,X
	AND #$00FF
	LDX @LOCAL05
	JSR ADD_MENU_ITEM
	INC @VIRTUAL02
@CHARACTER_LOOP_CHECK:
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	CLC
	SBC @VIRTUAL02
	JUMPGTS @ADD_CHARACTER_ITEM
	JSR PRINT_MENU_ITEMS
.IF .DEFINED(JPN)
	MOVE_INT @VIRTUAL0A, @LOCAL00
.ELSE
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
.ENDIF
	JSR SET_CURSOR_MOVE_CALLBACK
	LDA @LOCAL0D
	JSR SELECTION_MENU
	TAX
	STX @LOCAL06
	JSR CLEAR_CURSOR_MOVE_CALLBACK
	LDA @LOCAL07
	JSR CLOSE_WINDOW
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
	JSL RESTORE_WINDOW_TEXT_ATTRIBUTES
	JMP @CLEANUP_AND_RETURN
@BATTLE_STYLE_SELECT:
	LDA BATTLE_MENU_CURRENT_CHARACTER_ID
	CMP #.LOWORD(-1)
	BEQ @NO_CURRENT_CHAR
	LDA @LOCAL0C
	CMP #2
	BNE @USE_CURRENT_CHAR
@NO_CURRENT_CHAR:
	LDX #0
	BRA @AFTER_INITIAL_CHAR
@USE_CURRENT_CHAR:
	LDX BATTLE_MENU_CURRENT_CHARACTER_ID
@AFTER_INITIAL_CHAR:
	STX @VIRTUAL04
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
	CMP32 @VIRTUAL0A, @VIRTUAL06
	BEQ @AFTER_CURSOR_CALLBACK
.IF .DEFINED(JPN)
	LDA @VIRTUAL04
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
.ELSE
	LDX @VIRTUAL04
	LDA GAME_STATE + game_state::party_members,X
.ENDIF
	AND #$00FF
	PHA
	MOVE_INT @VIRTUAL0A, TEMP_FUNCTION_POINTER
	PLA
	JSL JUMP_TEMP_FUNCTION_POINTER
@AFTER_CURSOR_CALLBACK:
	STZ PAGINATION_ANIMATION_FRAME
	LDA #10
	STA @VIRTUAL02
	STA @LOCAL07
@SELECTION_LOOP:
	LDA @LOCAL0C
	BNE @AFTER_INDICATOR_SELECT
	LDA @VIRTUAL04
	JSR SELECT_BATTLE_MENU_CHARACTER
@AFTER_INDICATOR_SELECT:
	JSR CLEAR_INSTANT_PRINTING
	JSL WINDOW_TICK
	LDA @VIRTUAL04
	STA @LOCAL04
	LDA PAGINATION_WINDOW
	CMP #.LOWORD(-1)
	BEQ @RENDER_PAGINATION
	LDA PAGINATION_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	CMP #.LOWORD(-1)
	BEQ @RENDER_PAGINATION
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	STA @LOCAL03
@RENDER_PAGINATION:
	LDA PAGINATION_WINDOW
	CMP #.LOWORD(-1)
	BEQ @AFTER_PAGINATION
	LDA PAGINATION_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	CMP #.LOWORD(-1)
	BEQ @AFTER_PAGINATION
	LOADPTR PAGINATION_ANIM_TILES_PTR_TABLE, @VIRTUAL06
	LDA PAGINATION_ANIMATION_FRAME
	ASL
	ASL
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDY #window_stats::window_y
	LDA (@LOCAL03),Y
	OPTIMIZED_MULT @VIRTUAL04, 32
	STA @VIRTUAL02
	LDY #window_stats::window_x
	LDA (@LOCAL03),Y
	LDY #window_stats::width
	CLC
	ADC (@LOCAL03),Y
	DEC
	DEC
	DEC
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #VRAM::TEXT_LAYER_TILEMAP
	TAY
	LDX #8
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	.A16
@AFTER_PAGINATION:
	LDA #0
	STA @LOCAL06
	JMP @FRAME_WAIT_CHECK
@INPUT_TICK:
	JSL UPDATE_HPPP_METER_AND_RENDER
	LDA PAD_PRESS
	AND #PAD::LEFT
	BEQ @CHECK_RIGHT
	LDX @LOCAL04
	DEX
	STX @LOCAL04
	LDA @LOCAL0C
	BEQ @LEFT_CLOSE_SOUND
	LDY #SFX::CURSOR2
	BRA @AFTER_LEFT_SOUND
@LEFT_CLOSE_SOUND:
	LDY #SFX::MENU_OPEN_CLOSE
@AFTER_LEFT_SOUND:
	STY @LOCAL02
	LDA #2
	STA PAGINATION_ANIMATION_FRAME
	JMP @HANDLE_DIRECTION_CHANGE
@CHECK_RIGHT:
	LDA PAD_PRESS
	AND #PAD::RIGHT
	BEQ @CHECK_CONFIRM
	LDX @LOCAL04
	INX
	STX @LOCAL04
	LDA @LOCAL0C
	BEQ @RIGHT_CLOSE_SOUND
	LDY #SFX::CURSOR2
	BRA @AFTER_RIGHT_SOUND
@RIGHT_CLOSE_SOUND:
	LDY #SFX::MENU_OPEN_CLOSE
@AFTER_RIGHT_SOUND:
	STY @LOCAL02
	LDA #3
	STA PAGINATION_ANIMATION_FRAME
	BRA @HANDLE_DIRECTION_CHANGE
@CHECK_CONFIRM:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON | PAD::L_BUTTON
	BEQ @CHECK_CANCEL
	LDX @VIRTUAL04
	LDA GAME_STATE + game_state::party_members,X
	AND #$00FF
	TAX
	STX @LOCAL06
	LDA #SFX::CURSOR1
	JSL PLAY_SOUND
	JMP @CLEANUP_AND_RETURN
@CHECK_CANCEL:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON
	BEQ @NO_INPUT
	LDA @LOCAL0D
	CMP #1
	BNE @NO_INPUT
	LDX #0
	STX @LOCAL06
	LDA @LOCAL0C
	BEQ @CANCEL_CLOSE_SOUND
	LDY #SFX::CURSOR2
	BRA @AFTER_CANCEL_SOUND
@CANCEL_CLOSE_SOUND:
	LDY #SFX::MENU_OPEN_CLOSE
@AFTER_CANCEL_SOUND:
	TYA
	JSL PLAY_SOUND
	JSL CLEAR_BATTLE_MENU_CHARACTER_INDICATOR
	JMP @CLEANUP_AND_RETURN
@NO_INPUT:
	LDA @LOCAL06
	INC
	STA @LOCAL06
@FRAME_WAIT_CHECK:
	LDX @LOCAL07
	STX @VIRTUAL02
	CMP @VIRTUAL02
	BCCL @INPUT_TICK
	LDA PAGINATION_ANIMATION_FRAME
	BNE @PAGINATION_OFF
	LDX #1
	BRA @AFTER_PAGINATION_TOGGLE
@PAGINATION_OFF:
	LDX #0
@AFTER_PAGINATION_TOGGLE:
	STX PAGINATION_ANIMATION_FRAME
	LDA #10
	STA @VIRTUAL02
	STA @LOCAL07
	JMP @RENDER_PAGINATION
@HANDLE_DIRECTION_CHANGE:
	TXA
	SEC
	SBC @VIRTUAL04
	STA @VIRTUAL02
	STA @LOCAL07
@VALIDATE_SELECTION:
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	STA @LOCAL06
	STX @VIRTUAL02
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @CHECK_UNDERFLOW
	LDX #0
	STX @LOCAL04
	BRA @AFTER_CLAMP
@CHECK_UNDERFLOW:
	STX @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @AFTER_CLAMP
	LDA @LOCAL06
	TAX
	DEX
	STX @LOCAL04
@AFTER_CLAMP:
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	MOVE_INT @LOCAL0B, @VIRTUAL06
	CMP @VIRTUAL0A+2
	BNE @CHECK_CALLBACK_LOW
	LDA @VIRTUAL06
	CMP @VIRTUAL0A
@CHECK_CALLBACK_LOW:
	BEQ @AFTER_VALIDITY_CHECK
	LDA GAME_STATE + game_state::party_members,X
	AND #$00FF
	PHA
	MOVE_INT @VIRTUAL06, TEMP_FUNCTION_POINTER
	PLA
	JSL JUMP_TEMP_FUNCTION_POINTER
	CMP #0
	BNE @AFTER_VALIDITY_CHECK
	LDA @LOCAL07
	STA @VIRTUAL02
	LDX @LOCAL04
	TXA
	CLC
	ADC @VIRTUAL02
	TAX
	STX @LOCAL04
	JMP @VALIDATE_SELECTION
@AFTER_VALIDITY_CHECK:
	LDX @LOCAL04
	TXA
	CMP @VIRTUAL04
	BEQ @AFTER_ONCHANGE
	LDY @LOCAL02
	TYA
	JSL PLAY_SOUND
	LDX @LOCAL04
	STX @VIRTUAL04
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
	MOVE_INT @LOCAL0A, @VIRTUAL0A
	CMP @VIRTUAL06+2
	BNE @CHECK_ONCHANGE_LOW
	LDA @VIRTUAL0A
	CMP @VIRTUAL06
@CHECK_ONCHANGE_LOW:
	BEQ @AFTER_ONCHANGE
	LDX @VIRTUAL04
	LDA GAME_STATE + game_state::party_members,X
	AND #$00FF
	PHA
	MOVE_INT @VIRTUAL0A, TEMP_FUNCTION_POINTER
	PLA
	JSL JUMP_TEMP_FUNCTION_POINTER
@AFTER_ONCHANGE:
	LDA #4
	STA @VIRTUAL02
	STA @LOCAL07
	JMP @SELECTION_LOOP
@CLEANUP_AND_RETURN:
	LDA #.LOWORD(-1)
	STA PAGINATION_ANIMATION_FRAME
	MOVE_INT @LOCAL08, @VIRTUAL06
	LDA @LOCAL09
	CLC
	ADC #window_stats::argument_memory
	TAY
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDX @LOCAL06
	TXA
	END_C_FUNCTION
