
CHECK_TEXT_WORD_WRAP:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	TAY
	MOVE_INT @PARAM01, @VIRTUAL0A
	LDX #0
	STX @LOCAL04
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL03
	LDA CURRENT_FOCUS_WINDOW
	CMP #.LOWORD(-1)
	BEQL @DONE
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	TAY
	STY @LOCAL02
@READ_NEXT_CHAR:
	LDA [@VIRTUAL0A]
	AND #$00FF
	BEQ @RELOAD_SOURCE_PTR
	AND #$00FF
	INC @VIRTUAL0A
	BRA @CHECK_DICT_CODE
@RELOAD_SOURCE_PTR:
	MOVE_INT @LOCAL03, @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	INC @VIRTUAL06
	MOVE_INTX @VIRTUAL06, @LOCAL03
@CHECK_DICT_CODE:
	CMP #$15
	BEQ @DICT1
	CMP #$16
	BEQ @DICT2
	CMP #$17
	BEQL @DICT3
	JMP @MEASURE_CHAR
@DICT1:
	MOVE_INT @LOCAL03, @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	ASL
	ASL
	PHA
	LOADPTR COMPRESSED_TEXT_PTRS, @VIRTUAL06
	PLA
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @LOCAL03, @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL03
	LDA [@VIRTUAL0A]
	AND #$00FF
	INC @VIRTUAL0A
	JMP @MEASURE_CHAR
@DICT2:
	MOVE_INT @LOCAL03, @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	ASL
	ASL
	PHA
	LOADPTR COMPRESSED_TEXT_PTRS+1024, @VIRTUAL06
	PLA
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @LOCAL03, @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL03
	LDA [@VIRTUAL0A]
	AND #$00FF
	INC @VIRTUAL0A
	BRA @MEASURE_CHAR
@DICT3:
	MOVE_INT @LOCAL03, @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	ASL
	ASL
	PHA
	LOADPTR COMPRESSED_TEXT_PTRS+2048, @VIRTUAL06
	PLA
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @LOCAL03, @VIRTUAL06
	INC @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL03
	LDA [@VIRTUAL0A]
	AND #$00FF
	INC @VIRTUAL0A
@MEASURE_CHAR:
	CMP #$50
	BEQ @WORD_ENDED
	CMP #$20
	BCC @WORD_ENDED
	INC UPCOMING_WORD_LENGTH
	CMP #$2F
	BNE @LOOKUP_GLYPH_WIDTH
	LDA #8
	BRA @ADD_CHAR_WIDTH
@LOOKUP_GLYPH_WIDTH:
	SEC
	SBC #$50
	AND #$007F
	STA @VIRTUAL02
	LDY @LOCAL02
	LDA a:window_stats::font,Y
	STA @LOCAL01
	LOADPTR FONT_PTR_TABLE, @VIRTUAL06
	LDA @LOCAL01
	OPTIMIZED_MULT @VIRTUAL04, 12
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL06
	LDA @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	STA @LOCAL01
	LDA CHARACTER_PADDING
	AND #$00FF
	STA @VIRTUAL02
	LDA @LOCAL01
	CLC
	ADC @VIRTUAL02
@ADD_CHAR_WIDTH:
	STA @VIRTUAL02
	LDX @LOCAL04
	TXA
	CLC
	ADC @VIRTUAL02
	TAX
	STX @LOCAL04
	JMP @READ_NEXT_CHAR
@WORD_ENDED:
	LDY @LOCAL02
	LDA a:window_stats::text_x,Y
	STA @LOCAL00
	BEQ @AT_LINE_START
	LDA VWF_X
	AND #$0007
	STA @VIRTUAL04
	LDA @LOCAL00
	DEC
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL04
	STA @VIRTUAL02
	LDX @LOCAL04
	TXA
	CLC
	ADC @VIRTUAL02
	BRA @CHECK_FITS
@AT_LINE_START:
	LDA VWF_X
	AND #$0007
	STA @VIRTUAL02
	LDX @LOCAL04
	TXA
	CLC
	ADC @VIRTUAL02
@CHECK_FITS:
	STA @VIRTUAL02
	LDA a:window_stats::width,Y
	ASL
	ASL
	ASL
	CMP @VIRTUAL02
	BCS @DONE
	JSL REDIRECT_PRINT_NEWLINE
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA VWF_INDENT_NEW_LINE
@DONE:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
