
CHECK_PSI_CATEGORY_AVAILABLE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @VIRTUAL02
	CMP #1
	BEQ @CHECK_OFFENSIVE
	CMP #2
	BEQ @CHECK_RECOVERY
	CMP #3
	BEQ @CHECK_ASSIST
	BRA @RETURN
@CHECK_OFFENSIVE:
	LDY #1
	LDX #2
	LDA @VIRTUAL02
	JSR CHECK_CHARACTER_HAS_PSI_ABILITY
	TAY
	STY @LOCAL00
	BRA @RETURN
@CHECK_RECOVERY:
	LDY #2
	TYX
	LDA @VIRTUAL02
	JSR CHECK_CHARACTER_HAS_PSI_ABILITY
	TAY
	STY @LOCAL00
	BRA @RETURN
@CHECK_ASSIST:
	LDY #4
	LDX #2
	LDA @VIRTUAL02
	JSR CHECK_CHARACTER_HAS_PSI_ABILITY
	TAY
	STY @LOCAL00
@RETURN:
	LDY @LOCAL00
	TYA
	END_C_FUNCTION
