
CHECK_LAST_MEMBER_STATUS_CHANGE:
	BEGIN_C_FUNCTION
	END_STACK_VARS
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
.IF .DEFINED(JPN)
	DEC
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::player_controlled_party_members,X
.ELSE
	TAX
	DEX
	LDA GAME_STATE+game_state::player_controlled_party_members,X
.ENDIF
	AND #$00FF
	ASL
	TAX
	LDA CHOSEN_FOUR_PTRS,X
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA a:char_struct::afflictions + STATUS_GROUP::PERSISTENT_EASYHEAL,X
	LDX #0
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	CMP #STATUS_0::UNCONSCIOUS
	BEQ @STATUS_INCAPACITATED
	CMP #STATUS_0::DIAMONDIZED
	BNE @AFTER_STATUS_CHECK
@STATUS_INCAPACITATED:
	LDX #1
@AFTER_STATUS_CHECK:
	LDA #0
	CPX LAST_PARTY_MEMBER_STATUS_LAST_CHECK
	BEQ @RETURN
	LDA #1
@RETURN:
	STX LAST_PARTY_MEMBER_STATUS_LAST_CHECK
	END_C_FUNCTION
