
CHECK_CHARACTER_PSI_AVAILABILITY:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @LOCAL01
	STX @LOCAL00
	STA @VIRTUAL02
	LDA #0
	STA @VIRTUAL04
	LDA @VIRTUAL02
	CMP #3
	BEQ @NOT_AVAILABLE
	LDA @VIRTUAL02
	JSR CHECK_PSI_AFFLICTION_BLOCK
	CMP #0
	BEQ @NOT_AVAILABLE
	LDY @LOCAL01
	LDX @LOCAL00
	LDA @VIRTUAL02
	JSR CHECK_CHARACTER_HAS_PSI_ABILITY
	CMP #0
	BEQ @NOT_AVAILABLE
	LDA #1
	STA @VIRTUAL04
@NOT_AVAILABLE:
	LDA @VIRTUAL04
	END_C_FUNCTION
