
CHECK_CHARACTER_HAS_PSI_ABILITY:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT8
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @VIRTUAL04
	PHA
	LDA @VIRTUAL04
	STA @LOCAL04
	PLA
	STX @VIRTUAL02
	TAX
	CPX #PARTY_MEMBER::JEFF
	BNE @NOT_JEFF
	LDA #0
	JMP @RETURN
@NOT_JEFF:
	TXY
	DEY
	STY @LOCAL03
	LDX #1
	STX @LOCAL02
	JMP @ABILITY_LOOP_CHECK
@CHECK_ABILITY:
	LDY @LOCAL03
	TYA
	BEQ @CHAR_NESS
	CMP #PARTY_MEMBER::PAULA - 1
	BEQ @CHAR_PAULA
	CMP #PARTY_MEMBER::POO - 1
	BEQ @CHAR_POO
	BRA @CHECK_LEVEL
@CHAR_NESS:
	LDA @LOCAL00
	CLC
	ADC #psi_ability::ness_level
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	STA @VIRTUAL00
	STA @LOCAL01
	BRA @CHECK_LEVEL
@CHAR_PAULA:
	.A16
	LDA @LOCAL00
	CLC
	ADC #psi_ability::paula_level
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	STA @VIRTUAL00
	STA @LOCAL01
	BRA @CHECK_LEVEL
@CHAR_POO:
	.A16
	LDA @LOCAL00
	CLC
	ADC #psi_ability::poo_level
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	STA @VIRTUAL00
	STA @LOCAL01
@CHECK_LEVEL:
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	AND #$00FF
	BEQ @NEXT_ABILITY
	LOADPTR PSI_ABILITY_TABLE, @VIRTUAL06
	TXA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(psi_ability)
	STA @LOCAL00
	OPTIMIZED_ADD psi_ability::usability
	MOVE_INTX @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	AND @VIRTUAL02
	BEQ @NEXT_ABILITY
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	CMP PARTY_CHARACTERS + char_struct::level,X
	BGT @NEXT_ABILITY
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL04
	STA @VIRTUAL04
	LDA @LOCAL00
	OPTIMIZED_ADD psi_ability::category
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	AND @VIRTUAL04
	BEQ @NEXT_ABILITY
	LDA #1
	JMP @RETURN
@NEXT_ABILITY:
	LDX @LOCAL02
	INX
	STX @LOCAL02
@ABILITY_LOOP_CHECK:
	REP #PROC_FLAGS::ACCUM8
	LOADPTR PSI_ABILITY_TABLE, @VIRTUAL06
	TXA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(psi_ability)
	STA @LOCAL00
	OPTIMIZED_ADD psi_ability::name
	MOVE_INTY @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	BNEL @CHECK_ABILITY
	LDY @LOCAL03
	BNE @CHECK_POO_SPECIAL
	LDA @VIRTUAL02
	AND #$0001
	BEQ @CHECK_POO_SPECIAL
	LDA GAME_STATE + game_state::party_psi
	AND #$00FF
	AND #$0001
	BEQ @CHECK_POO_SPECIAL
	LDA @LOCAL04
	STA @VIRTUAL04
	AND #$0008
	BEQ @CHECK_POO_SPECIAL
	LDA #1
	BRA @RETURN
@CHECK_POO_SPECIAL:
	CPY #3
	BNE @NO_ABILITY
	LDA @VIRTUAL02
	AND #$0002
	BEQ @NO_ABILITY
	LDA GAME_STATE + game_state::party_psi
	AND #$00FF
	AND #$0006
	BEQ @NO_ABILITY
	LDA @LOCAL04
	STA @VIRTUAL04
	AND #$0001
	BEQ @NO_ABILITY
	LDA #1
	BRA @RETURN
@NO_ABILITY:
	LDA #0
@RETURN:
	END_C_FUNCTION
