
CLEAR_WINDOW_TILEMAP:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	TAX
	LDY a:window_stats::tilemap_address,X
	STY @LOCAL01
	LDY a:window_stats::height,X
	LDA a:window_stats::width,X
	JSL MULT16
	TAX
	STX @LOCAL00
	BRA @LOOP_CHECK
@LOOP_BODY:
	LDY @LOCAL01
	LDA __BSS_START__,Y
	BEQ @SKIP_FREE
	JSL FREE_TILE_SAFE
@SKIP_FREE:
	LDA #64
	LDY @LOCAL01
	STA __BSS_START__,Y
	INY
	INY
	STY @LOCAL01
	LDX @LOCAL00
	DEX
	STX @LOCAL00
@LOOP_CHECK:
	BNE @LOOP_BODY
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA REDRAW_ALL_WINDOWS
	JSL CLEAR_PARTY_SPRITE_HIDE_FLAGS
	END_C_FUNCTION
