
CLOSE_WINDOW:
.IF .DEFINED(JPN)
	BEGIN_C_FUNCTION
.ELSE
	BEGIN_C_FUNCTION_FAR
.ENDIF
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL04
	CMP #.LOWORD(-1)
	BEQL @EXIT
	LDA @LOCAL04
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	STA @VIRTUAL04
	CMP #.LOWORD(-1)
	BEQL @EXIT
	LDA CURRENT_FOCUS_WINDOW
	CMP @LOCAL04
	BNE @CLEAR_MENU_OPTIONS
	LDA #.LOWORD(-1)
	STA CURRENT_FOCUS_WINDOW
@CLEAR_MENU_OPTIONS:
	LDA @LOCAL04
	JSR CLEAR_WINDOW_MENU_OPTIONS
	LDA @VIRTUAL04
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDY WINDOW_STATS + window_stats::next,X
	STY @LOCAL03
	LDA WINDOW_STATS + window_stats::prev,X
	STA @LOCAL02
	CPY #.LOWORD(-1)
	BNE @UPDATE_NEXT_PREV
	STA WINDOW_TAIL
	BRA @CHECK_PREV_NULL
@UPDATE_NEXT_PREV:
	TYA
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA @LOCAL02
	STA WINDOW_STATS + window_stats::prev,X
@CHECK_PREV_NULL:
	CMP #.LOWORD(-1)
	BNE @UPDATE_PREV_NEXT
	LDY @LOCAL03
	STY WINDOW_HEAD
	BRA @FREE_WINDOW_SLOT
@UPDATE_PREV_NEXT:
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDY @LOCAL03
	TYA
	STA WINDOW_STATS + window_stats::next,X
@FREE_WINDOW_SLOT:
	LDA @VIRTUAL04
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	STX @LOCAL01
	LDA #.LOWORD(-1)
	STA WINDOW_STATS + window_stats::id,X
	LDA @LOCAL04
	ASL
	TAX
	LDA #.LOWORD(-1)
	STA OPEN_WINDOW_TABLE,X
	LDX @LOCAL01
	LDA WINDOW_STATS + window_stats::window_x,X
	ASL
	STA @VIRTUAL02
	LDA WINDOW_STATS + window_stats::window_y,X
	OPTIMIZED_MULT @VIRTUAL04, 64
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #.LOWORD(BG2_BUFFER)
.IF .DEFINED(JPN)
	TAY
	STY @LOCAL00
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL01
.ELSE
	STA @VIRTUAL02
	STA @LOCAL00
	LDY WINDOW_STATS + window_stats::tilemap_address,X
	STY @LOCAL03
	LDX #0
	STX @LOCAL01
	BRA @CHECK_TILE_COUNT
@FREE_TILE_LOOP:
	LDY @LOCAL03
	LDA __BSS_START__,Y
	CMP #64
	BNE @DO_FREE_TILE
	CMP #0
	BEQ @WRITE_BLANK_TILE
@DO_FREE_TILE:
	LDA __BSS_START__,Y
	JSL FREE_TILE
@WRITE_BLANK_TILE:
	LDA #64
	LDY @LOCAL03
	STA __BSS_START__,Y
	INY
	INY
	STY @LOCAL03
	LDX @LOCAL01
	INX
	STX @LOCAL01
@CHECK_TILE_COUNT:
	LDA @VIRTUAL04
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDY WINDOW_STATS + window_stats::width,X
	TAX
	LDA WINDOW_STATS + window_stats::height,X
	JSL MULT16
	STA @VIRTUAL02
	LDX @LOCAL01
	TXA
	CMP @VIRTUAL02
	BCC @FREE_TILE_LOOP
	LDY #0
	STY @LOCAL01
.ENDIF
	BRA @CHECK_ROW
@START_ROW:
.IF .DEFINED(JPN)
	LDX #0
	STX @LOCAL03
.ELSE
	LDA #0
	STA @LOCAL02
.ENDIF
	BRA @CHECK_COL
@CLEAR_CELL:
.IF .DEFINED(JPN)
	LDA #0
	LDY @LOCAL00
	STA __BSS_START__,Y
	INY
	INY
	STY @LOCAL00
	INX
	STX @LOCAL03
.ELSE
	LDA #0
	LDX @LOCAL00
	STX @VIRTUAL02
	STA __BSS_START__,X
	INC @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL00
	LDA @LOCAL02
	INC
	STA @LOCAL02
.ENDIF
@CHECK_COL:
	LDA @VIRTUAL04
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA WINDOW_STATS + window_stats::width,X
.IF .DEFINED(JPN)
	STA @LOCAL02
	STA @VIRTUAL02
.ELSE
	TAX
	STX @VIRTUAL02
.ENDIF
	INC @VIRTUAL02
	INC @VIRTUAL02
.IF .DEFINED(JPN)
	LDX @LOCAL03
	TXA
	CMP @VIRTUAL02
.ELSE
	LDA @LOCAL02
	CMP @VIRTUAL02
.ENDIF
	BNE @CLEAR_CELL
.IF .DEFINED(JPN)
	LDA @LOCAL02
	STA @VIRTUAL02
.ELSE
	STX @VIRTUAL02
.ENDIF
	LDA #32
	SEC
	SBC @VIRTUAL02
	DEC
	DEC
	ASL
.IF .DEFINED(JPN)
	STA @VIRTUAL02
	LDY @LOCAL00
	TYA
.ELSE
	PHA
	LDA @LOCAL00
	STA @VIRTUAL02
	PLY
	STY @VIRTUAL02
.ENDIF
	CLC
	ADC @VIRTUAL02
.IF .DEFINED(JPN)
	TAY
	STY @LOCAL00
	LDA @LOCAL01
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL01
.ELSE
	STA @VIRTUAL02
	STA @LOCAL00
	LDY @LOCAL01
	INY
	STY @LOCAL01
.ENDIF
@CHECK_ROW:
	LDA @VIRTUAL04
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
.IF .DEFINED(JPN)
	LDA @VIRTUAL02
	PHA
.ELSE
	STX @LOCAL02
.ENDIF
	LDA WINDOW_STATS + window_stats::height,X
	STA @VIRTUAL02
	INC @VIRTUAL02
	INC @VIRTUAL02
.IF .DEFINED(JPN)
	PLA
.ELSE
	LDY @LOCAL01
	TYA
.ENDIF
	CMP @VIRTUAL02
	BNE @START_ROW
.IF .DEFINED(USA)
	JSL RESET_VWF_TEXT_STATE
	LDX @LOCAL02
.ENDIF
	LDA WINDOW_STATS + window_stats::unknown59,X
	AND #$00FF
	BEQ @CLEAR_WINDOW_FLAGS
	AND #$00FF
	DEC
	ASL
	TAX
	LDA #.LOWORD(-1)
	STA TITLED_WINDOWS,X
@CLEAR_WINDOW_FLAGS:
	LDA @VIRTUAL04
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	SEP #PROC_FLAGS::ACCUM8
	STZ WINDOW_STATS + window_stats::unknown59,X
	LDA #1
	STA REDRAW_ALL_WINDOWS
	REP #PROC_FLAGS::ACCUM8
	LDA PAGINATION_WINDOW
	CMP @LOCAL04
	BNE @CHECK_EXTRA_TICK
	LDA #.LOWORD(-1)
	STA PAGINATION_WINDOW
@CHECK_EXTRA_TICK:
.IF .DEFINED(USA)
	LDA EXTRA_TICK_ON_WINDOW_CLOSE
	AND #$00FF
	BNE @CLEAR_VWF_INDENT
	JSL WINDOW_TICK_WITHOUT_INSTANT_PRINTING
	JSL CLEAR_INSTANT_PRINTING
@CLEAR_VWF_INDENT:
.IF !.DEFINED(PROTOTYPE19950327)
	SEP #PROC_FLAGS::ACCUM8
	STZ VWF_INDENT_NEW_LINE
.ENDIF
.ENDIF
@EXIT:
.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
	REP #PROC_FLAGS::ACCUM8
.ENDIF
	END_C_FUNCTION
