
COFFEETEA_SCENE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL02
	LDY #0
	LDX #1
	TXA
	JSL FADE_OUT_WITH_MOSAIC
	JSL INIT_FLYOVER_TEXT_SCREEN
	JSL OAM_CLEAR
	LDA @VIRTUAL02
	BNE @SELECT_COFFEE_BG1
	LDX #BATTLEBG_LAYER::COFFEE2
	BRA @SKIP_COFFEE_BG1
@SELECT_COFFEE_BG1:
	LDX #BATTLEBG_LAYER::TEA2
@SKIP_COFFEE_BG1:
	LDA @VIRTUAL02
	BNE @SELECT_COFFEE_BG2
	LDY #BATTLEBG_LAYER::COFFEE1
	BRA @SKIP_COFFEE_BG2
@SELECT_COFFEE_BG2:
	LDY #BATTLEBG_LAYER::TEA1
@SKIP_COFFEE_BG2:
	TYA
	JSL LOAD_BACKGROUND_ANIMATION
	LDX #1
	TXA
	JSL FADE_IN
	LDA #28
	STA FLYOVER_SCREEN_OFFSET
	LDA #0
	STA @VIRTUAL04
	LDA @VIRTUAL02
	BNE @SELECT_COFFEE_TEXT
	LOADPTR COFFEE_SEQUENCE_TEXT, @VIRTUAL06
	BRA @SKIP_COFFEE_TEXT
@SELECT_COFFEE_TEXT:
	LOADPTR TEA_SEQUENCE_TEXT, @VIRTUAL06
@SKIP_COFFEE_TEXT:
@SCRIPT_PARSE_BEGIN:
	LDA [@VIRTUAL06]
	AND #$00FF
	STA @LOCAL01
	INC @VIRTUAL06
	CMP #$00
	BEQL @END_OF_SCRIPT
	CMP #$09
	BEQ @PARSE_09
	CMP #$01
	BEQ @PARSE_01
	CMP #$08
	BEQ @PARSE_08
	BRA @PRINT_TEXT
@PARSE_09:
	LDA @VIRTUAL04
	JSL ADVANCE_TEXT_LINE_POSITION
	TAX
	STX @LOCAL00
	LDA #18
	JSL UPLOAD_VWF_BUFFER_TO_VRAM
	JSL UPDATE_BATTLE_SCREEN_EFFECTS
	BRA @SCROLL_LOOP_CHECK
@SCROLL_WAIT_FRAME:
	TXA
	JSL ADVANCE_TEXT_LINE_POSITION
	TAX
	STX @LOCAL00
	JSR WAIT_AND_UPDATE_BATTLE_EFFECTS
@SCROLL_LOOP_CHECK:
	LDX @LOCAL00
	CPX #4608
	BCC @SCROLL_WAIT_FRAME
	TXA
	SEC
	SBC #4608
	STA @VIRTUAL04
	LDA #18
	JSL SCROLL_FLYOVER_TEXT
	BRA @SCRIPT_PARSE_BEGIN
@PARSE_01:
	SEP #PROC_FLAGS::ACCUM8
	LDA [@VIRTUAL06]
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
	JSL ADVANCE_FLYOVER_PIXEL_OFFSET
	BRA @SCRIPT_PARSE_BEGIN
@PARSE_08:
	LDA [@VIRTUAL06]
	AND #$00FF
	TAY
	INC @VIRTUAL06
	LDX #12
	TYA
	JSL RENDER_PARTY_MEMBER_NAME
	JMP @SCRIPT_PARSE_BEGIN
@PRINT_TEXT:
	LDA [@VIRTUAL06]
	AND #$00FF
	TAX
	INC @VIRTUAL06
	LDY #12
	LDA @LOCAL01
	JSL RENDER_FLYOVER_TEXT_CHARACTER
	JMP @SCRIPT_PARSE_BEGIN
@END_OF_SCRIPT:
	LDX #1
	TXA
	JSL FADE_OUT
	BRA @FADE_OUT_LOOP_CHECK
@WAIT_FADE_OUT:
	JSR WAIT_AND_UPDATE_BATTLE_EFFECTS
@FADE_OUT_LOOP_CHECK:
	LDA FADE_PARAMETERS + fade_parameters::step
	AND #$00FF
	BNE @WAIT_FADE_OUT
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	JSL RELOAD_MAP
	LDY #.LOWORD(BG2_BUFFER)
	LDX #896
	BRA @CLEAR_BG2_LOOP_CHECK
@CLEAR_BG2_ENTRY:
	LDA #0
	STA __BSS_START__,Y
	INY
	INY
	DEX
@CLEAR_BG2_LOOP_CHECK:
	BNE @CLEAR_BG2_ENTRY
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	JSL UNDRAW_FLYOVER_TEXT
	JSL BLANK_SCREEN_AND_WAIT_VBLANK
	LDX #1
	TXA
	JSL FADE_IN
	END_C_FUNCTION
