
COMPARE_STRINGS:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXY
	TAX
	BRA @CHAR_LOOP_CHECK
@COMPARE_CHAR:
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,Y
	STA @VIRTUAL00
	LDA @LOCAL00
	CMP @VIRTUAL00
	BNE @RETURN_DIFF
	INX
	INY
@CHAR_LOOP_CHECK:
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BNE @COMPARE_CHAR
@RETURN_DIFF:
	REP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	AND #$00FF
	STA @VIRTUAL02
	LDA __BSS_START__,Y
	AND #$00FF
	SEC
	SBC @VIRTUAL02
	END_C_FUNCTION
