
COPY_ENEMY_NAME:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_PARAM_INT32 ;const char* src
	STACK_RESERVE_PARAM_INT16 ;NEAR char* dest
	STACK_RESERVE_PARAM_INT16 ;int length
	STACK_RESERVE_RETURN_INT16 ;NEAR char*
	END_STACK_VARS
	STX @VIRTUAL02
	TAY
	MOVE_INT @PARAM00, @VIRTUAL06
	BRA @LOOP_CHECK
@READ_CHAR:
	LDA [@VIRTUAL06]
	AND #$00FF
	TAX
	BEQ @TERMINATE
	CPX #CHAR::NESS_PLACEHOLDER
	BNE @STORE_CHAR
	LDX #0
	BRA @NESS_NAME_CHECK
@COPY_NESS_CHAR:
	SEP #PROC_FLAGS::ACCUM8
	LDA PARTY_CHARACTERS+char_struct::name,X
	STA @LOCAL00
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQ @ADVANCE_SRC
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	STA __BSS_START__,Y
	INY
	INX
@NESS_NAME_CHECK:
	CPX #.SIZEOF(char_struct::name)
	BCC @COPY_NESS_CHAR
	BRA @ADVANCE_SRC
@STORE_CHAR:
	SEP #PROC_FLAGS::ACCUM8
	STA __BSS_START__,Y
	INY
@ADVANCE_SRC:
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL06
@LOOP_CHECK:
	LDX @VIRTUAL02
	LDA @VIRTUAL02
	DEC
	STA @VIRTUAL02
	CPX #0
	BNE @READ_CHAR
@TERMINATE:
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA __BSS_START__,Y
	REP #PROC_FLAGS::ACCUM8
	TYA
	END_C_FUNCTION
