
DISPLAY_TEXT_AND_WAIT_FOR_FADE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	MOVE_INT @PARAM00, @VIRTUAL06
	JSL DISABLE_ALL_ENTITIES
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
@WAIT_FADE:
	JSL WINDOW_TICK
	LDA ENTITY_FADE_ENTITY
	CMP #.LOWORD(-1)
	BNE @WAIT_FADE
	JSL ENABLE_ALL_ENTITIES
	END_C_FUNCTION
