
DISPLAY_TEXT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT32 ;const char* script
	STACK_RESERVE_RETURN_INT32 ;const char*
	END_STACK_VARS
	MOVE_INT @PARAM00, @VIRTUAL06
	LDY #0
	STY @LOCAL03
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BNE @INIT_TEXT
	MOVE_INT @VIRTUAL06, @RETURNVAL
	JMP @RETURN
@INIT_TEXT:
	JSR PUSH_TEXT_STACK_FRAME
	STA @LOCAL02
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @LOCAL02
	JSR INIT_TEXT_STATE
	STA @VIRTUAL02
	STA @LOCAL02
	LDA @VIRTUAL02
	BNE @MAIN_LOOP
	MOVE_INT @VIRTUAL0A, @RETURNVAL
	JMP @RETURN
@MAIN_LOOP:
	LDA @LOCAL02
	STA @VIRTUAL02
	LDX @VIRTUAL02
	TXY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDA [@VIRTUAL06]
	AND #$00FF
	STA @LOCAL01
	INC @VIRTUAL06
	TXY
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
@AFTER_READ:
	LDY @LOCAL03
	BEQ @CHECK_CONTROL_CODE
	LDA @LOCAL01
	TAX
	LDA @VIRTUAL02
	STY @VIRTUAL02
	STA TEMP_REGISTER
	PEA .LOWORD(@UNK)
	LDA @VIRTUAL02
	DEC
	PHA
	LDA TEMP_REGISTER
@UNK:
	RTS
	TAY
	STY @LOCAL03
	BRA @MAIN_LOOP
@CHECK_CONTROL_CODE:
	LDA @LOCAL01
	CMP #$20
	BCC @CC_DISPATCH
	JMP @PRINT_CHAR
@CC_DISPATCH:
	STZ CC_ARGUMENT_GATHERING_LOOP_COUNTER
	CMP #$00
	BEQL @CC_00
	CMP #$01
	BEQL @CC_01
	CMP #$02
	BEQL @CC_02
	CMP #$03
	BEQL @CC_03
	CMP #$04
	BEQL @CC_04
	CMP #$05
	BEQL @CC_05
	CMP #$06
	BEQL @CC_06
	CMP #$07
	BEQL @CC_07
	CMP #$08
	BEQL @CC_08
	CMP #$09
	BEQL @CC_09
	CMP #$0A
	BEQL @CC_0A
	CMP #$0B
	BEQL @CC_0B
	CMP #$0C
	BEQL @CC_0C
	CMP #$0D
	BEQL @CC_0D
	CMP #$0E
	BEQL @CC_0E
	CMP #$0F
	BEQL @CC_0F
	CMP #$10
	BEQL @CC_10
	CMP #$11
	BEQL @CC_11
	CMP #$12
	BEQL @CC_12
	CMP #$13
	BEQL @CC_13
	CMP #$14
	BEQL @CC_14
	CMP #$18
	BEQL @CC_18
	CMP #$19
	BEQL @CC_19
	CMP #$1A
	BEQL @CC_1A
	CMP #$1B
	BEQL @CC_1B
	CMP #$1C
	BEQL @CC_1C
	CMP #$1D
	BEQL @CC_1D
	CMP #$1E
	BEQL @CC_1E
	CMP #$1F
	BEQL @CC_1F
	JMP @MAIN_LOOP
@CC_00:
	JSR PRINT_NEWLINE
	JMP @MAIN_LOOP
@CC_01:
	JSR GET_TEXT_X
	CMP #0
	BEQL @MAIN_LOOP
	JSR PRINT_NEWLINE
	JMP @MAIN_LOOP
@CC_03:
	LDX #0
	LDA #1
	JSR CC_13_14
	JMP @MAIN_LOOP
@CC_04:
	LDY #.LOWORD(CC_04)
	STY @LOCAL03
	JMP @MAIN_LOOP
@CC_05:
	LDY #.LOWORD(CC_05)
	STY @LOCAL03
	JMP @MAIN_LOOP
@CC_06:
	LDY #.LOWORD(CC_06)
	STY @LOCAL03
	JMP @MAIN_LOOP
@CC_07:
	LDY #.LOWORD(CC_07)
	STY @LOCAL03
	JMP @MAIN_LOOP
@CC_08:
	LDY #.LOWORD(CC_08)
	STY @LOCAL03
	JMP @MAIN_LOOP
@CC_09:
	LDY #.LOWORD(CC_09)
	STY @LOCAL03
	JMP @MAIN_LOOP
@CC_0A:
	LDY #.LOWORD(CC_0A)
	STY @LOCAL03
	JMP @MAIN_LOOP
@CC_0B:
	LDY #.LOWORD(CC_0B)
	STY @LOCAL03
	JMP @MAIN_LOOP
@CC_0C:
	LDY #.LOWORD(CC_0C)
	STY @LOCAL03
	JMP @MAIN_LOOP
@CC_0D:
	LDY #.LOWORD(CC_0D)
	STY @LOCAL03
	JMP @MAIN_LOOP
@CC_0E:
	LDY #.LOWORD(CC_0E)
	STY @LOCAL03
	JMP @MAIN_LOOP
@CC_0F:
	JSR INCREMENT_SECONDARY_MEMORY
	JMP @MAIN_LOOP
@CC_10:
	LDY #.LOWORD(CC_10)
	STY @LOCAL03
	JMP @MAIN_LOOP
@CC_11:
	LDA #1
	JSR SELECTION_MENU
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	JSR CLEAR_FOCUS_WINDOW_MENU_OPTIONS
	JMP @MAIN_LOOP
@CC_12:
	JSR CC_12
	JMP @MAIN_LOOP
@CC_13:
	LDX #0
	TXA
	JSR CC_13_14
	JMP @MAIN_LOOP
@CC_14:
	LDX #1
	TXA
	JSR CC_13_14
	JMP @MAIN_LOOP
@CC_18:
	LDY #.LOWORD(CC_18_TREE)
	STY @LOCAL03
	JMP @MAIN_LOOP
@CC_19:
	LDY #.LOWORD(CC_19_TREE)
	STY @LOCAL03
	JMP @MAIN_LOOP
@CC_1A:
	LDY #.LOWORD(CC_1A_TREE)
	STY @LOCAL03
	JMP @MAIN_LOOP
@CC_1B:
	LDY #.LOWORD(CC_1B_TREE)
	STY @LOCAL03
	JMP @MAIN_LOOP
@CC_1C:
	LDY #.LOWORD(CC_1C_TREE)
	STY @LOCAL03
	JMP @MAIN_LOOP
@CC_1D:
	LDY #.LOWORD(CC_1D_TREE)
	STY @LOCAL03
	JMP @MAIN_LOOP
@CC_1E:
	LDY #.LOWORD(CC_1E_TREE)
	STY @LOCAL03
	JMP @MAIN_LOOP
@CC_1F:
	LDY #.LOWORD(CC_1F_TREE)
	STY @LOCAL03
	JMP @MAIN_LOOP
@PRINT_CHAR:
	JSR PRINT_LETTER
	JMP @MAIN_LOOP
@CC_02:
	LDY @VIRTUAL02
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDA @VIRTUAL02
	JSR RESTORE_TEXT_STATE_ATTRIBUTES
	JSR POP_TEXT_STACK_FRAME
	MOVE_INT @VIRTUAL06, @RETURNVAL
@RETURN:
	END_C_FUNCTION
