
DISPLAY_TEXT_WAIT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT32
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	MOVE_INT @PARAM01, @VIRTUAL06
	MOVE_INT @PARAM00, @VIRTUAL0A
	LDX #.LOWORD(GAME_STATE) + game_state::auto_fight_enable
	LDA __BSS_START__,X
	AND #$00FF
	BEQ @AFTER_AUTO_FIGHT_CHECK
	LDA PAD_STATE
	AND #PAD::B_BUTTON
	BEQ @AFTER_AUTO_FIGHT_CHECK
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA __BSS_START__,X
	JSL CLEAR_HPPP_WINDOW_HEADER
@AFTER_AUTO_FIGHT_CHECK:
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_CNUM
	.A16
	LDA BATTLE_MODE_FLAG
	BEQ @NO_PROMPT
	LDA #2
	JSR ENABLE_BLINKING_TRIANGLE
@NO_PROMPT:
.IF .DEFINED(JPN)
	MOVE_INT @VIRTUAL0A, @LOCAL00
.ELSE
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
.ENDIF
	JSL DISPLAY_TEXT
	JSR CLEAR_BLINKING_PROMPT
	END_C_FUNCTION
