
ENTER_YOUR_NAME_PLEASE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL02
	STZ ENABLE_WORD_WRAP
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA ALLOW_TEXT_OVERFLOW
	JSL SET_INSTANT_PRINTING
	.A16
	CREATE_WINDOW_NEAR #WINDOW::NAMING_PROMPT
	LDX @LOCAL02
	BEQL @INPUT_EB_NAME
	LDX #0
	TXA
	JSL SET_FOCUS_TEXT_CURSOR
	.A16
	PROMOTENEARPTR GAME_STATE + game_state::earthbound_playername, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #24
	JSR PRINT_STRING
	LDX #1
	LDA #0
	JSL SET_FOCUS_TEXT_CURSOR
	LDA #12
	JSL INITIALIZE_KEYBOARD_INPUT_VWF
	LDA GAME_STATE
	AND #$00FF
	BEQ @INPUT_M2_NAME
	PROMOTENEARPTR GAME_STATE + game_state::mother2_playername, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #12
	JSR PRINT_STRING
@INPUT_M2_NAME:
	LDX #1
	LDA #0
	JSL SET_FOCUS_TEXT_CURSOR
	STZ @LOCAL00
	LDA #.LOWORD(-1)
	STA @LOCAL00+2
	LDY #.LOWORD(GAME_STATE) + game_state::mother2_playername
	LDX #12
	LDA #WINDOW::NAMING_PROMPT
	JSR TEXT_INPUT_DIALOG
	TAY
	STY @LOCAL01
	JMP @DONE
@INPUT_EB_NAME:
	LDX #0
	TXA
	JSL SET_FOCUS_TEXT_CURSOR
	LOADPTR NAME_REGISTRY_REQUEST_STRING, @LOCAL00
	LDA #26
	JSR PRINT_STRING
	JSL WAIT_DMA_FINISHED
	LDX #1
	LDA #0
	JSL SET_FOCUS_TEXT_CURSOR
	LDA #24
	JSL INITIALIZE_KEYBOARD_INPUT_VWF
	LDX #1
	LDA #0
	JSL SET_FOCUS_TEXT_CURSOR
	LDY #.LOWORD(GAME_STATE) + game_state::earthbound_playername
	LDA __BSS_START__,Y
	AND #$00FF
	BEQ @BEGIN_EB_INPUT
	LDX #24
	TYA
	JSL INITIALIZE_EXISTING_NAME_VWF
@BEGIN_EB_INPUT:
	LDX #1
	LDA #0
	JSL SET_FOCUS_TEXT_CURSOR
	LDA #.LOWORD(GAME_STATE) + game_state::earthbound_playername
	STA @VIRTUAL02
	STZ @LOCAL00
	LDA #.LOWORD(-1)
	STA @LOCAL00+2
	LDY @VIRTUAL02
	LDX #24
	LDA #WINDOW::NAMING_PROMPT
	JSR TEXT_INPUT_DIALOG
	TAY
	STY @LOCAL01
	LDX @VIRTUAL02
	LDA #.LOWORD(TEMPORARY_TEXT_BUFFER)
	JSL PROCESS_NAME_INPUT_STRING
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #.SIZEOF(game_state::mother2_playername)
	LDA #.LOWORD(GAME_STATE) + game_state::mother2_playername
	JSL MEMCPY16
@DONE:
	LDA #WINDOW::FILE_SELECT_NAMING_KEYBOARD
	JSL CLOSE_WINDOW
	LDA #WINDOW::NAMING_PROMPT
	JSL CLOSE_WINDOW
	LDA #$00FF
	STA ENABLE_WORD_WRAP
	SEP #PROC_FLAGS::ACCUM8
	STZ ALLOW_TEXT_OVERFLOW
	LDY @LOCAL01
	REP #PROC_FLAGS::ACCUM8
	TYA
	END_C_FUNCTION
