
ENTER_YOUR_NAME_PLEASE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL02
	JSR SET_INSTANT_PRINTING
	.A16
	CREATE_WINDOW_NEAR #WINDOW::NAMING_PROMPT
	LDX @LOCAL02
	BEQL @INPUT_EB_NAME
	.A16
	PROMOTENEARPTR GAME_STATE + game_state::earthbound_playername, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #24
	JSR PRINT_STRING
	LDX #1
	LDA #0
	JSR SET_FOCUS_TEXT_CURSOR
	LDX #0
	STX @LOCAL02
	BRA @PLACEHOLDER_LOOP_CHECK
@PRINT_PLACEHOLDER:
	LDA #CHAR::PLACEHOLDER
	JSR PRINT_LETTER
	LDX @LOCAL02
	INX
	STX @LOCAL02
@PLACEHOLDER_LOOP_CHECK:
	CPX #12
	BCC @PRINT_PLACEHOLDER
	LDX #1
	LDA #0
	JSR SET_FOCUS_TEXT_CURSOR
	LDA GAME_STATE
	AND #$00FF
	BEQ @INPUT_M2_NAME
	PROMOTENEARPTR GAME_STATE + game_state::mother2_playername, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #12
	JSR PRINT_STRING
	LDA #.LOWORD(WINDOW_STATS) + window_stats::text_x
	STA @VIRTUAL02
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(window_stats)
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	CMP #12
	BCS @OPEN_M2_INPUT
	LDA #CHAR::BULLET
	JSR PRINT_LETTER
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(window_stats)
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
	BRA @OPEN_M2_INPUT
@INPUT_M2_NAME:
	LDA #CHAR::BULLET
	JSR PRINT_LETTER
	LDX #1
	LDA #0
	JSR SET_FOCUS_TEXT_CURSOR
@OPEN_M2_INPUT:
	LDA #0
	STA @LOCAL00
	LDA #.LOWORD(-1)
	STA @LOCAL00+2
	LDY #.LOWORD(GAME_STATE) + game_state::mother2_playername
	LDX #12
	LDA #WINDOW::NAMING_PROMPT
	JSR TEXT_INPUT_DIALOG
	TAY
	STY @LOCAL01
	JMP @DONE
@INPUT_EB_NAME:
	LOADPTR NAME_REGISTRY_REQUEST_STRING, @LOCAL00
	LDA #11
	JSR PRINT_STRING
	LDX #1
	LDA #0
	JSR SET_FOCUS_TEXT_CURSOR
	LDX #0
	STX @LOCAL02
	BRA @EB_PLACEHOLDER_LOOP_CHECK
@PRINT_EB_PLACEHOLDER:
	LDA #CHAR::PLACEHOLDER
	JSR PRINT_LETTER
	LDX @LOCAL02
	INX
	STX @LOCAL02
@EB_PLACEHOLDER_LOOP_CHECK:
	CPX #24
	BCC @PRINT_EB_PLACEHOLDER
	LDX #1
	LDA #0
	JSR SET_FOCUS_TEXT_CURSOR
	LDX #.LOWORD(GAME_STATE) + game_state::earthbound_playername
	LDA __BSS_START__,X
	AND #$00FF
	BEQ @BEGIN_EB_INPUT
	TXA
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #24
	JSR PRINT_STRING
	LDA #.LOWORD(WINDOW_STATS) + window_stats::text_x
	STA @VIRTUAL02
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(window_stats)
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	CMP #24
	BCS @OPEN_EB_INPUT
	LDA #CHAR::BULLET
	JSR PRINT_LETTER
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(window_stats)
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
	BRA @OPEN_EB_INPUT
@BEGIN_EB_INPUT:
	LDA #CHAR::BULLET
	JSR PRINT_LETTER
	LDX #1
	LDA #0
	JSR SET_FOCUS_TEXT_CURSOR
@OPEN_EB_INPUT:
	LDA #.LOWORD(GAME_STATE) + game_state::earthbound_playername
	STA @VIRTUAL02
	LDA #2
	STA @LOCAL00
	LDA #.LOWORD(-1)
	STA @LOCAL00+2
	LDY @VIRTUAL02
	LDX #24
	LDA #WINDOW::NAMING_PROMPT
	JSR TEXT_INPUT_DIALOG
	TAY
	STY @LOCAL01
	LDX @VIRTUAL02
	LDA #.LOWORD(TEMPORARY_TEXT_BUFFER)
	JSL PROCESS_NAME_INPUT_STRING
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #.SIZEOF(game_state::mother2_playername)
	LDA #.LOWORD(GAME_STATE) + game_state::mother2_playername
	JSL MEMCPY16
@DONE:
	LDA #WINDOW::FILE_SELECT_NAMING_KEYBOARD
	JSR CLOSE_WINDOW
	LDA #WINDOW::NAMING_PROMPT
	JSR CLOSE_WINDOW
	LDY @LOCAL01
	TYA
	END_C_FUNCTION
