
FIND_FREE_WINDOW_SLOT:
.IF .DEFINED(JPN)
	BEGIN_C_FUNCTION
.ELSE
	BEGIN_C_FUNCTION_FAR
.ENDIF
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA #0
	STA @LOCAL00
	BRA @LOOP_CHECK
@LOOP_BODY:
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA WINDOW_STATS + window_stats::id,X
	CMP #.LOWORD(-1)
	BNE @NEXT_SLOT
	LDA @LOCAL00
	BRA @RETURN
@NEXT_SLOT:
	LDA @LOCAL00
	INC
	STA @LOCAL00
@LOOP_CHECK:
	CMP #8
	BNE @LOOP_BODY
	LDA #.LOWORD(-1)
@RETURN:
	END_C_FUNCTION
