
FIND_FIRST_CHARACTER_WITH_PSI:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA #0
	STA @VIRTUAL02
	BRA @MEMBER_LOOP_CHECK
@CHECK_MEMBER:
	LDY #15
	LDX #1
	STX @LOCAL00
.IF .DEFINED(JPN)
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_members,X
.ELSE
	LDX @VIRTUAL02
	LDA GAME_STATE + game_state::party_members,X
.ENDIF
	AND #$00FF
	LDX @LOCAL00
	JSR CHECK_CHARACTER_PSI_AVAILABILITY
	CMP #0
	BEQ @NEXT_MEMBER
	LDA @VIRTUAL02
	INC
	BRA @RETURN
@NEXT_MEMBER:
	INC @VIRTUAL02
@MEMBER_LOOP_CHECK:
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	STA @VIRTUAL04
	LDA @VIRTUAL02
	CMP @VIRTUAL04
	BCC @CHECK_MEMBER
	LDA #0
@RETURN:
	END_C_FUNCTION
