
GET_CHARACTER_BY_PARTY_POSITION:
	BEGIN_C_FUNCTION
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
.IF .DEFINED(JPN)
	DEC
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_order,X
.ELSE
	TAX
	DEX
	LDA GAME_STATE + game_state::party_order,X
.ENDIF
	AND #$00FF
	END_C_FUNCTION
