
GET_ACTIVE_WINDOW_ADDRESS:
	BEGIN_C_FUNCTION
	LDA WINDOW_HEAD
	CMP #$FFFF
	BNE @CALC_WINDOW_ADDRESS
	LDA #.LOWORD(DUMMY_WINDOW)
	BRA @RETURN
@CALC_WINDOW_ADDRESS:
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
@RETURN:
	END_C_FUNCTION
