
GET_TEXT_PIXEL_WIDTH:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	STX @VIRTUAL04
	STX @LOCAL03
	STA @VIRTUAL02
	STA @LOCAL02
	MOVE_INT @PARAM02, @VIRTUAL06
	LDY #0
	STY @LOCAL01
	TYX
	BRA @CHAR_LOOP_CHECK
@CHAR_LOOP_BODY:
	LDA [@VIRTUAL06]
	AND #$00FF
	INC @VIRTUAL06
	SEC
	SBC #$50
	AND #$007F
	STA @LOCAL00
	LDA CHARACTER_PADDING
	AND #$00FF
	STA @VIRTUAL02
	LOADPTR FONT_PTR_TABLE, @VIRTUAL0A
	LDA @LOCAL03
	STA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(font_table_entry)
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL0A
	LDA @LOCAL00
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL02
	LDY @LOCAL01
	TYA
	CLC
	ADC @VIRTUAL02
	TAY
	STY @LOCAL01
	INX
@CHAR_LOOP_CHECK:
	LDA @LOCAL02
	STA @VIRTUAL02
	TXA
	CMP @VIRTUAL02
	BCC @CHAR_LOOP_BODY
	TYA
	END_C_FUNCTION
