
GET_NEARBY_NPC_CONFIG_TYPE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	END_STACK_VARS
	JSL FIND_NEARBY_CHECKABLE_TPT_ENTRY
	LDA INTERACTING_NPC_ID
	BEQ @NO_NPC
	LDA INTERACTING_NPC_ID
	CMP #.LOWORD(-1)
	BEQ @NO_NPC
	LDA INTERACTING_NPC_ID
	CMP #.LOWORD(-2)
	BNE @HAS_NPC
@NO_NPC:
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	BRA @RETURN
@HAS_NPC:
	LDA INTERACTING_NPC_ID
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(npc_config)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:NPC_CONFIG_TABLE,X
@RETURN:
	END_C_FUNCTION
