
GET_TEXT_X:
	BEGIN_C_FUNCTION
	END_STACK_VARS
.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
	LDA CURRENT_FOCUS_WINDOW
	CMP #.LOWORD(-1)
	BNE @HAS_FOCUS_WINDOW
	LDA #0
	BRA @RETURN
.ENDIF
@HAS_FOCUS_WINDOW:
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA WINDOW_STATS+window_stats::text_x,X
@RETURN:
	END_C_FUNCTION
