
GET_STRING_PIXEL_WIDTH:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT32
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TAY
	STY @LOCAL03
	MOVE_INT @PARAM01, @VIRTUAL06
	LDX #0
	STX @LOCAL02
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	STA @VIRTUAL02
	STA @LOCAL01
.IF .DEFINED(PROTOTYPE19950327)
	BRA @LOOP_CHECK
.ELSE
	JMP @LOOP_CHECK
.ENDIF
@CHAR_LOOP_BODY:
	DEY
	STY @LOCAL03
	AND #$00FF
	SEC
	SBC #$50
	AND #$007F
	STA @LOCAL00
	INC @VIRTUAL06
.IF !.DEFINED(PROTOTYPE19950327)
	LDA FORCE_NORMAL_FONT_FOR_LENGTH_CALCULATIONS
	AND #$00FF
	BEQ @USE_WINDOW_FONT
	MOVE_INT FONT_PTR_TABLE, @VIRTUAL0A
	LDA @LOCAL00
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	BRA @ADD_WIDTH
.ENDIF
@USE_WINDOW_FONT:
	LOADPTR FONT_PTR_TABLE, @VIRTUAL0A
	LDA @LOCAL01
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA a:window_stats::font,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(font_table_entry)
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL0A
	LDA @LOCAL00
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
@ADD_WIDTH:
	STA @VIRTUAL02
	LDA CHARACTER_PADDING
	AND #$00FF
	CLC
	ADC @VIRTUAL02
	STA @VIRTUAL04
	LDX @LOCAL02
	TXA
	CLC
	ADC @VIRTUAL04
	TAX
	STX @LOCAL02
@LOOP_CHECK:
	LDA [@VIRTUAL06]
	AND #$00FF
	BEQ @DONE
	LDY @LOCAL03
.IF .DEFINED(PROTOTYPE19950327)
	BNE @CHAR_LOOP_BODY
.ELSE
	BNEL @CHAR_LOOP_BODY
.ENDIF
@DONE:
	LDX @LOCAL02
	TXA
	END_C_FUNCTION
