
INIT_FLYOVER_TEXT_SCREEN:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LOADPTR BUFFER, @VIRTUAL06
	JSL FORCE_BLANK_AND_WAIT_VBLANK
	LDY #VRAM::TEXT_LAYER_TILES
	LDX #VRAM::TEXT_LAYER_TILEMAP
	LDA #BG_TILEMAP_SIZE::NORMAL
	JSL SET_BG3_VRAM_LOCATION
	LDA #0
	STA [@VIRTUAL06]
	COPY_TO_VRAM1P @VIRTUAL06, VRAM::TEXT_LAYER_TILES, $3800, 3
	.A16
	LOADPTR MOVEMENT_TEXT_STRING_PALETTE, @LOCAL00
	LDX #8
	LDA #.LOWORD(PALETTES)
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	LDA #PALETTE_UPLOAD::FULL
	STA PALETTE_UPLOAD_MODE
	LDA #<-1
	STA @LOCAL00
	LDX #32 * 52
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(VWF_BUFFER)
	JSL MEMSET16
	LDY #16
	LDX #0
	STX @LOCAL02
	BRA @ROW_LOOP_CHECK
@PROCESS_ROW:
	TXA
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	TAX
	STZ BG2_BUFFER,X
	TAX
	STZ BG2_BUFFER + 2,X
	TAX
	STZ BG2_BUFFER + 4,X
	LDA #3
	STA @LOCAL01
	BRA @ROW_TILE_LOOP_CHECK
@FILL_ROW_TILE:
	ASL
	STA @VIRTUAL02
	LDX @LOCAL02
	TXA
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	CLC
	ADC @VIRTUAL02
	TAX
	TYA
	CLC
	ADC #$2000
	STA BG2_BUFFER,X
	INY
	LDA @LOCAL01
	INC
	STA @LOCAL01
@ROW_TILE_LOOP_CHECK:
	CMP #29
	BCC @FILL_ROW_TILE
	LDX @LOCAL02
	TXA
	ASL
	ASL
	ASL
	ASL
	ASL
	ASL
	TAX
	STZ BG2_BUFFER + 58,X
	TAX
	STZ BG2_BUFFER + 60,X
	TAX
	STZ BG2_BUFFER + 62,X
	LDX @LOCAL02
	INX
	STX @LOCAL02
@ROW_LOOP_CHECK:
	CPX #32
	BCC @PROCESS_ROW
	PROMOTENEARPTR BG2_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	COPY_TO_VRAM1P @VIRTUAL06, VRAM::TEXT_LAYER_TILEMAP, $800, 0
	.A16
	LDA #26
	STA FLYOVER_TILES_PER_ROW
	STZ FLYOVER_TILE_OFFSET
	LDA #.LOWORD(-1)
	STA FLYOVER_DIRTY_MIN
	STZ FLYOVER_DIRTY_MAX
	STZ FLYOVER_VWF_X
	STZ FLYOVER_VWF_Y
	STZ FLYOVER_PIXEL_OFFSET
	STZ FLYOVER_BYTE_OFFSET
	JSL BLANK_SCREEN_AND_WAIT_VBLANK
	END_C_FUNCTION
