
IS_ESCARGO_EXPRESS_FULL:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDX #36
	STX @LOCAL01
	LDA #0
	STA @LOCAL00
	BRA @SAVE_SLOT_LOOP_CHECK
@CHECK_SAVE_SLOT:
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::unknownB6,X
	AND #$00FF
	BEQ @SLOT_NOT_EMPTY
	LDX @LOCAL01
	DEX
	STX @LOCAL01
@SLOT_NOT_EMPTY:
	LDA @LOCAL00
	INC
	STA @LOCAL00
@SAVE_SLOT_LOOP_CHECK:
	CMP #3
	BCC @CHECK_SAVE_SLOT
	LDA #0
	STA @LOCAL00
	BRA @ITEM_LOOP_CHECK
@CHECK_ITEM:
	LDA @LOCAL00
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::escargo_express_items,X
	AND #$00FF
	BNE @ITEM_NOT_EMPTY
	LDA #0
	BRA @RETURN
@ITEM_NOT_EMPTY:
	LDA @LOCAL00
	INC
	STA @LOCAL00
@ITEM_LOOP_CHECK:
	STA @VIRTUAL02
	LDX @LOCAL01
	TXA
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @CHECK_ITEM
	LDA #1
@RETURN:
	END_C_FUNCTION
