
IS_ESCARGO_EXPRESS_FULL:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA #36
	STA @LOCAL00
	LDX #0
	BRA @RESERVED_LOOP_TEST
@CHECK_RESERVED_SLOT:
	LDA GAME_STATE + game_state::unknownB6,X
	AND #$00FF
	BEQ @NEXT_RESERVED
	LDA @LOCAL00
	DEC
	STA @LOCAL00
@NEXT_RESERVED:
	INX
@RESERVED_LOOP_TEST:
	CPX #3
	BCC @CHECK_RESERVED_SLOT
	LDX #0
	BRA @ITEM_LOOP_TEST
@CHECK_ITEM_SLOT:
	LDA GAME_STATE+game_state::escargo_express_items,X
	AND #$00FF
	BNE @NEXT_ITEM
	LDA #0
	BRA @RETURN
@NEXT_ITEM:
	INX
@ITEM_LOOP_TEST:
	STX @VIRTUAL02
	LDA @LOCAL00
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @CHECK_ITEM_SLOT
	LDA #1
@RETURN:
	END_C_FUNCTION
