

NUM_SELECT_PROMPT:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT32
	END_STACK_VARS
	.IF .DEFINED(JPN)
		@PRINT_LETTER_FUNC = PRINT_LETTER
	.ELSE
		@PRINT_LETTER_FUNC = PRINT_CHAR_WITH_SOUND
	.ENDIF
	STA @LOCAL08
	LDA CURRENT_FOCUS_WINDOW
	CMP #.LOWORD(-1)
	BNE @NO_FOCUS_WINDOW
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @RETURNVAL
	JMP @RETURN
@NO_FOCUS_WINDOW:
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	TAX
	LDA a:window_stats::text_x,X
	STA @LOCAL07
	LDA a:window_stats::text_y,X
	STA @LOCAL06
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL05
	LDA #1
	STA @LOCAL04
	MOVE_INT_CONSTANT 1, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @LOCAL03
@RENDER_NUMBER:
	JSR SET_INSTANT_PRINTING
	LDX @LOCAL06
	LDA @LOCAL07
	JSR SET_FOCUS_TEXT_CURSOR
	MOVE_INT @LOCAL05, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR NUMBER_TO_TEXT_BUFFER
	STA @VIRTUAL02
	LDA #7
	SEC
	SBC @VIRTUAL02
	CLC
	ADC #.LOWORD(NUMBER_TEXT_BUFFER)
	STA @VIRTUAL04
	LDY @LOCAL08
	STY @LOCAL02
	BRA @LEADING_LOOP_CHECK
@PRINT_LEADING:
	CPY @LOCAL04
	BNE @USE_EMPTY_PREFIX
	LDX #16
	BRA @AFTER_PREFIX
@USE_EMPTY_PREFIX:
	LDX #48
@AFTER_PREFIX:
	TXA
	JSR @PRINT_LETTER_FUNC
	LDY @LOCAL02
	DEY
	STY @LOCAL02
@LEADING_LOOP_CHECK:
	TYA
	CMP @VIRTUAL02
	BGT @PRINT_LEADING
	BRA @DIGIT_LOOP_CHECK
@PRINT_DIGIT:
	CPY @LOCAL04
	BNE @USE_EMPTY_DIGIT_PREFIX
	LDX #16
	BRA @AFTER_DIGIT_PREFIX
@USE_EMPTY_DIGIT_PREFIX:
	LDX #48
@AFTER_DIGIT_PREFIX:
	STX @VIRTUAL02
	LDX @VIRTUAL04
	LDA __BSS_START__,X
	AND #$00FF
	CLC
	ADC @VIRTUAL02
	INC @VIRTUAL04
	JSR @PRINT_LETTER_FUNC
	LDY @LOCAL02
	DEY
	STY @LOCAL02
@DIGIT_LOOP_CHECK:
	CPY #0
	BNE @PRINT_DIGIT
	JSR CLEAR_INSTANT_PRINTING
	JSL WINDOW_TICK
@INPUT_LOOP:
	JSL UPDATE_HPPP_METER_AND_RENDER
	LDA PAD_PRESS
	AND #PAD::LEFT
	BEQ @CHECK_RIGHT
	LDA @LOCAL04
	CMP @LOCAL08
	BCS @CHECK_RIGHT
	LDA #SFX::CURSOR2
	JSL PLAY_SOUND
	INC @LOCAL04
	MOVE_INT @LOCAL03, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT_CONSTANT 10, @VIRTUAL0A
	JSL MULT32
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @LOCAL03
	JMP @RENDER_NUMBER
@CHECK_RIGHT:
	LDA PAD_PRESS
	AND #PAD::RIGHT
	BEQ @CHECK_UP
	LDA @LOCAL04
	CMP #1
	BLTEQ @CHECK_UP
	LDA #SFX::CURSOR2
	JSL PLAY_SOUND
	DEC @LOCAL04
	MOVE_INT @LOCAL03, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT_CONSTANT 10, @VIRTUAL0A
	JSL DIVISION32S_DIVISOR_POSITIVE
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @LOCAL03
	JMP @RENDER_NUMBER
@CHECK_UP:
	LDA PAD_HELD
	AND #PAD::UP
	BEQL @CHECK_DOWN
	LDA #SFX::CURSOR3
	JSL PLAY_SOUND
	MOVE_INT_CONSTANT 9, @LOCAL01
	MOVE_INT @LOCAL03, @VIRTUAL0A
	JSL DIVISION32S_DIVISOR_POSITIVE
	MOVE_INT_CONSTANT 10, @VIRTUAL0A
	JSL MODULUS32
	MOVE_INT @LOCAL01, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BEQ @WRAP_UP
	MOVE_INT @LOCAL03, @VIRTUAL0A
	MOVE_INT @LOCAL05, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, @LOCAL05
	JMP @RENDER_NUMBER
@WRAP_UP:
	MOVE_INT @LOCAL03, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @LOCAL01, @VIRTUAL0A
	JSL MULT32
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @LOCAL05, @VIRTUAL06
	SEC
	SUB_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, @LOCAL05
	JMP @RENDER_NUMBER
@CHECK_DOWN:
	LDA PAD_HELD
	AND #PAD::DOWN
	BEQL @CHECK_CONFIRM
	LDA #SFX::CURSOR3
	JSL PLAY_SOUND
	MOVE_INT @LOCAL03, @VIRTUAL0A
	JSL DIVISION32S_DIVISOR_POSITIVE
	MOVE_INT_CONSTANT 10, @VIRTUAL0A
	JSL MODULUS32
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BEQ @WRAP_DOWN
	MOVE_INT @LOCAL03, @VIRTUAL0A
	MOVE_INT @LOCAL05, @VIRTUAL06
	SEC
	SUB_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, @LOCAL05
	JMP @RENDER_NUMBER
@WRAP_DOWN:
	MOVE_INT @LOCAL03, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT_CONSTANT 9, @VIRTUAL0A
	JSL MULT32
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @LOCAL05, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, @LOCAL05
	JMP @RENDER_NUMBER
@CHECK_CONFIRM:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON | PAD::L_BUTTON
	BEQ @CHECK_CANCEL
	LDA #SFX::CURSOR1
	JSL PLAY_SOUND
	MOVE_INT @VIRTUAL06, @RETURNVAL
	BRA @RETURN
@CHECK_CANCEL:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON
	BEQL @INPUT_LOOP
	LDA #SFX::CURSOR2
	JSL PLAY_SOUND
	MOVE_INT_CONSTANT -1, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @RETURNVAL
@RETURN:
	END_C_FUNCTION
