
NUMBER_TO_ASCII_BUFFER:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAY
	STY @LOCAL01
	LDX #.LOWORD(NUMBER_TEXT_BUFFER)
	LDA #10000
	STA @LOCAL00
	BRA @DIGIT_LOOP_CHECK
@PROCESS_DIGIT:
	PHA
	LDY @LOCAL01
	TYA
	PLY
	JSL DIVISION16S_DIVISOR_POSITIVE
	SEP #PROC_FLAGS::ACCUM8
	CLC
	ADC #48
	STA __BSS_START__,X
	INX
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	PHA
	LDY @LOCAL01
	TYA
	PLY
	JSL MODULUS16
	TAY
	STY @LOCAL01
	LDY #10
	LDA @LOCAL00
	JSL DIVISION16S_DIVISOR_POSITIVE
	STA @LOCAL00
@DIGIT_LOOP_CHECK:
	CMP #0
	BNE @PROCESS_DIGIT
	END_C_FUNCTION
