
OPEN_HPPP_DISPLAY:
	BEGIN_C_FUNCTION_FAR
	END_STACK_VARS
	JSL DISABLE_ALL_ENTITIES
	LDA #SFX::CURSOR1
	JSL PLAY_SOUND
	JSR SHOW_HPPP_AND_MONEY_WINDOWS
@INPUT_LOOP:
	JSL WINDOW_TICK
	LDA PAD_PRESS
	AND #PAD::A_BUTTON | PAD::L_BUTTON
	BEQ @CHECK_DISMISS
	JSL OPEN_MENU_BUTTON
	BRA @DONE
@CHECK_DISMISS:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON
	BEQ @INPUT_LOOP
	LDA #SFX::CURSOR2
	JSL PLAY_SOUND
	JSR CLEAR_INSTANT_PRINTING
	JSR HIDE_HPPP_WINDOWS
	JSR CLOSE_ALL_WINDOWS
	JSL WINDOW_TICK
	JSL ENABLE_ALL_ENTITIES
@DONE:
	END_C_FUNCTION
