
PARTY_CHARACTER_SELECTOR:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @LOCAL0A
	STX @LOCAL09
	STA @LOCAL08
	JSR GET_ACTIVE_WINDOW_ADDRESS
	STA @LOCAL07
	CLC
	ADC #window_stats::argument_memory
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL0A
	MOVE_INT @VIRTUAL0A, @LOCAL06
	LDA @LOCAL09
	CMP #1
	BNEL @BATTLE_MODE_PATH
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
	JSL SAVE_WINDOW_TEXT_ATTRIBUTES
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	CMP #1
	BNE @MULTI_PARTY_WINDOW
	LDX #WINDOW::SINGLE_CHARACTER_SELECT
	BRA @STORE_WINDOW_ID
@MULTI_PARTY_WINDOW:
	CLC
	ADC #WINDOW::TARGETING_PROMPT
	TAX
	DEX
@STORE_WINDOW_ID:
	STX @VIRTUAL04
	LDA @VIRTUAL04
	STA @LOCAL05
	CREATE_WINDOW_NEAR @VIRTUAL04
	STZ @LOCAL04
	JMP @CHAR_LOOP_CHECK
@BUILD_CHAR_MENU:
	LDA @LOCAL04
	CLC
	ADC #.LOWORD(GAME_STATE) + game_state::party_members
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	AND #$00FF
	JSL GET_PARTY_CHARACTER_NAME
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #6
	LDA #.LOWORD(TEMPORARY_TEXT_BUFFER)
	JSL MEMCPY16
	SEP #PROC_FLAGS::ACCUM8
	STZ TEMPORARY_TEXT_BUFFER+5
	REP #PROC_FLAGS::ACCUM8
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @LOCAL04
	ASL
	ASL
	CLC
	ADC @LOCAL08
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL01
	LDY #0
	LDA @LOCAL04
	STA @VIRTUAL04
	ASL
	ADC @VIRTUAL04
	ASL
	TAX
	STX @LOCAL03
	LDX @VIRTUAL02
	LDA __BSS_START__,X
	AND #$00FF
	LDX @LOCAL03
	JSR ADD_MENU_ITEM
	INC @LOCAL04
@CHAR_LOOP_CHECK:
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	CLC
	SBC @LOCAL04
	JUMPGTS @BUILD_CHAR_MENU
	JSR PRINT_MENU_ITEMS
	LDA @LOCAL0A
	JSR SELECTION_MENU
	TAX
	STX @LOCAL02
	LDA @LOCAL05
	STA @VIRTUAL04
	JSL CLOSE_WINDOW
	LDA #.LOWORD(WINDOW_TEXT_ATTRIBUTES_BACKUP)
	JSL RESTORE_WINDOW_TEXT_ATTRIBUTES
	JMP @CHAR_LOOP_CHECK2
@BATTLE_MODE_PATH:
	LDX #0
	BRA @SCRIPT_COPY_CHECK
@COPY_SCRIPT:
	TXA
	ASL
	ASL
	STA @LOCAL05
	CLC
	ADC @LOCAL08
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDA @LOCAL05
	CLC
	ADC #.LOWORD(PARTY_MEMBER_SELECTION_SCRIPTS)
	TAY
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	INX
@SCRIPT_COPY_CHECK:
	CPX #4
	BNE @COPY_SCRIPT
	LDA BATTLE_MENU_CURRENT_CHARACTER_ID
	CMP #.LOWORD(-1)
	BNE @MULTI_PARTY_WINDOW0
	LDX #0
	BRA @MULTI_PARTY_WINDOW1
@MULTI_PARTY_WINDOW0:
	LDX BATTLE_MENU_CURRENT_CHARACTER_ID
@MULTI_PARTY_WINDOW1:
	STX @VIRTUAL04
	LDA GAME_STATE + game_state::party_members,X
	AND #$00FF
	DEC
	ASL
	ASL
	CLC
	ADC #.LOWORD(PARTY_MEMBER_SELECTION_SCRIPTS)
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BEQ @MULTI_PARTY_WINDOW3
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
@MULTI_PARTY_WINDOW3:
	STZ PAGINATION_ANIMATION_FRAME
	LDA #10
	STA @VIRTUAL02
	STA @LOCAL05
@MULTI_PARTY_WINDOW4:
	LDA @LOCAL09
	BNE @MULTI_PARTY_WINDOW5
	LDA @VIRTUAL04
	JSL SELECT_BATTLE_MENU_CHARACTER
@MULTI_PARTY_WINDOW5:
	JSL CLEAR_INSTANT_PRINTING
	JSL WINDOW_TICK
	LDA @VIRTUAL04
	STA @LOCAL08
	LDA PAGINATION_WINDOW
	CMP #.LOWORD(-1)
	BEQ @MULTI_PARTY_WINDOW6
	LDA PAGINATION_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	CMP #.LOWORD(-1)
	BEQ @MULTI_PARTY_WINDOW6
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	STA @LOCAL04
@MULTI_PARTY_WINDOW6:
	LDA PAGINATION_WINDOW
	CMP #.LOWORD(-1)
	BEQ @MULTI_PARTY_WINDOW7
	LDA PAGINATION_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	CMP #.LOWORD(-1)
	BEQ @MULTI_PARTY_WINDOW7
	LOADPTR PAGINATION_ANIM_TILES_PTR_TABLE, @VIRTUAL06
	LDA PAGINATION_ANIMATION_FRAME
	ASL
	ASL
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	DEREFERENCE_PTR_TO @VIRTUAL06, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDY #window_stats::window_y
	LDA (@LOCAL04),Y
	ASL
	ASL
	ASL
	ASL
	ASL
	STA @VIRTUAL02
	LDY #window_stats::window_x
	LDA (@LOCAL04),Y
	LDY #window_stats::width
	CLC
	ADC (@LOCAL04),Y
	DEC
	DEC
	DEC
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #VRAM::TEXT_LAYER_TILEMAP
	TAY
	LDX #8
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	.A16
@MULTI_PARTY_WINDOW7:
	LDA #0
	STA @LOCAL02
	JMP @STORE_WINDOW_ID9
@MULTI_PARTY_WINDOW8:
	JSL UPDATE_HPPP_METER_AND_RENDER
	LDA PAD_PRESS
	AND #PAD::LEFT
	BEQ @STORE_WINDOW_ID1
	LDX @LOCAL08
	DEX
	STX @LOCAL02
	LDA @LOCAL09
	BEQ @MULTI_PARTY_WINDOW9
	LDY #2
	BRA @STORE_WINDOW_ID0
@MULTI_PARTY_WINDOW9:
	LDY #27
@STORE_WINDOW_ID0:
	LDA #2
	STA PAGINATION_ANIMATION_FRAME
	JMP @BUILD_CHAR_MENU3
@STORE_WINDOW_ID1:
	LDA PAD_PRESS
	AND #PAD::RIGHT
	BEQ @STORE_WINDOW_ID4
	LDX @LOCAL08
	INX
	STX @LOCAL02
	LDA @LOCAL09
	BEQ @STORE_WINDOW_ID2
	LDY #SFX::CURSOR2
	BRA @STORE_WINDOW_ID3
@STORE_WINDOW_ID2:
	LDY #SFX::MENU_OPEN_CLOSE
@STORE_WINDOW_ID3:
	LDA #3
	STA PAGINATION_ANIMATION_FRAME
	BRA @BUILD_CHAR_MENU3
@STORE_WINDOW_ID4:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON | PAD::L_BUTTON
	BEQ @STORE_WINDOW_ID5
	LDX @VIRTUAL04
	LDA GAME_STATE + game_state::party_members,X
	AND #$00FF
	TAX
	STX @LOCAL02
	LDA #SFX::CURSOR1
	JSL PLAY_SOUND
	JMP @CHAR_LOOP_CHECK2
@STORE_WINDOW_ID5:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON
	BEQ @STORE_WINDOW_ID8
	LDA @LOCAL0A
	CMP #1
	BNE @STORE_WINDOW_ID8
	LDX #0
	STX @LOCAL02
	LDA @LOCAL09
	BEQ @STORE_WINDOW_ID6
	LDY #SFX::CURSOR2
	BRA @STORE_WINDOW_ID7
@STORE_WINDOW_ID6:
	LDY #SFX::MENU_OPEN_CLOSE
@STORE_WINDOW_ID7:
	TYA
	JSL PLAY_SOUND
	JSL CLEAR_BATTLE_MENU_CHARACTER_INDICATOR
	JMP @CHAR_LOOP_CHECK2
@STORE_WINDOW_ID8:
	LDA @LOCAL02
	INC
	STA @LOCAL02
@STORE_WINDOW_ID9:
	LDX @LOCAL05
	STX @VIRTUAL02
	CMP @VIRTUAL02
	BCCL @MULTI_PARTY_WINDOW8
	LDA PAGINATION_ANIMATION_FRAME
	BNE @BUILD_CHAR_MENU1
	LDX #1
	BRA @BUILD_CHAR_MENU2
@BUILD_CHAR_MENU1:
	LDX #0
@BUILD_CHAR_MENU2:
	STX PAGINATION_ANIMATION_FRAME
	LDA #10
	STA @VIRTUAL02
	STA @LOCAL05
	JMP @MULTI_PARTY_WINDOW6
@BUILD_CHAR_MENU3:
	LDA GAME_STATE+game_state::player_controlled_party_count
	AND #$00FF
	STA @LOCAL08
	STX @VIRTUAL02
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @BUILD_CHAR_MENU6
	LDX #0
	STX @LOCAL02
	BRA @BUILD_CHAR_MENU9
@BUILD_CHAR_MENU6:
	STX @VIRTUAL02
	LDA #0
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @BUILD_CHAR_MENU9
	LDA @LOCAL08
	TAX
	DEX
	STX @LOCAL02
@BUILD_CHAR_MENU9:
	TXA
	CMP @VIRTUAL04
	BEQ @CHAR_LOOP_CHECK1
	TYA
	JSL PLAY_SOUND
	LDX @LOCAL02
	STX @VIRTUAL04
	LDA GAME_STATE + game_state::party_members,X
	AND #$00FF
	DEC
	ASL
	ASL
	CLC
	ADC #.LOWORD(PARTY_MEMBER_SELECTION_SCRIPTS)
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BEQ @CHAR_LOOP_CHECK1
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
@CHAR_LOOP_CHECK1:
	LDA #4
	STA @VIRTUAL02
	STA @LOCAL05
	JMP @MULTI_PARTY_WINDOW4
@CHAR_LOOP_CHECK2:
	LDA #.LOWORD(-1)
	STA PAGINATION_ANIMATION_FRAME
	MOVE_INT @LOCAL06, @VIRTUAL0A
	LDA @LOCAL07
	CLC
	ADC #window_stats::argument_memory
	TAY
	MOVE_INT_YPTRDEST @VIRTUAL0A, __BSS_START__
	LDX @LOCAL02
	TXA
	END_C_FUNCTION
