
POP_TEXT_STACK_FRAME:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	END_STACK_VARS
	LDX NEXT_TEXT_STACK_FRAME
	DEX
	STX NEXT_TEXT_STACK_FRAME
	STX @VIRTUAL02
	LDA #$000A
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @AFTER_UNDERFLOW_CHECK
	LDA #$0009
	STA NEXT_TEXT_STACK_FRAME
@AFTER_UNDERFLOW_CHECK:
	PLD
	RTS
