
PRINT_NUMBER:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	MOVE_INT @PARAM00, @VIRTUAL0A
	LDA CURRENT_FOCUS_WINDOW
	CMP #.LOWORD(-1)
	BEQL @DONE
.IF CLEAN_ROM
	MOVE_INT_CONSTANT $FFFF967F, @VIRTUAL06 ; fun with C enums?
.ELSE
	MOVE_INT_CONSTANT 9999999, @VIRTUAL06
.ENDIF
	LDA @VIRTUAL06
	CMP @VIRTUAL0A
	LDA @VIRTUAL06+2
	SBC @VIRTUAL0A+2
	BCS @CLAMP_DONE
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
@CLAMP_DONE:
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	STA @LOCAL03
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR NUMBER_TO_TEXT_BUFFER
	TAX
	STX @LOCAL02
	STX @VIRTUAL02
	LDA #7
	SEC
	SBC @VIRTUAL02
	CLC
	ADC #.LOWORD(NUMBER_TEXT_BUFFER)
	TAY
	STY @LOCAL01
	LDA @LOCAL03
	TAX
	LDA a:window_stats::number_padding,X
	AND #$00FF
	STA @LOCAL03
	AND #$0080
	BNE @PRINT_DIGIT_LOOP
	LDA @LOCAL03
	AND #$000F
	INC
	LDX @LOCAL02
	STX @VIRTUAL02
	CMP @VIRTUAL02
	BCS @CALC_PADDING
	TXA
@CALC_PADDING:
	STX @VIRTUAL02
	SEC
	SBC @VIRTUAL02
	OPTIMIZED_MULT @VIRTUAL04, 6
	JSL ADVANCE_TEXT_CURSOR_PIXELS
	BRA @PRINT_DIGIT_LOOP
@PRINT_DIGIT:
	LDY @LOCAL01
	LDA __BSS_START__,Y
	AND #$00FF
	CLC
	ADC #CHAR::ZERO
	INY
	STY @LOCAL01
	JSR PRINT_LETTER
	LDX @LOCAL02
	DEX
	STX @LOCAL02
@PRINT_DIGIT_LOOP:
	LDX @LOCAL02
	BNE @PRINT_DIGIT
@DONE:
	END_C_FUNCTION
