
PRINT_LETTER:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 "CHAR" ;int
	END_STACK_VARS
	TAY
	STY @LOCAL01
	LDA CURRENT_FOCUS_WINDOW
	CMP #.LOWORD(-1)
	BEQL @RETURN
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA WINDOW_STATS+window_stats::font,X
	LDY @LOCAL01
	TYX
	JSL RENDER_VWF_CHARACTER
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	CMP WINDOW_TAIL
	BEQ @AFTER_REDRAW
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA REDRAW_ALL_WINDOWS
@AFTER_REDRAW:
	REP #PROC_FLAGS::ACCUM8
	LDA TEXT_SOUND_MODE
	CMP #2
	BNE @CHECK_MODE_3
	LDX #1
	BRA @CHECK_PLAY_SOUND
@CHECK_MODE_3:
	LDA TEXT_SOUND_MODE
	CMP #3
	BNE @DEFAULT_MODE
	LDX #0
	BRA @CHECK_PLAY_SOUND
@DEFAULT_MODE:
	LDX #0
	LDA BLINKING_TRIANGLE_FLAG
	BNE @CHECK_PLAY_SOUND
	LDX #1
@CHECK_PLAY_SOUND:
	CPX #0
	BEQ @AFTER_SOUND
	LDA INSTANT_PRINTING
	AND #$00FF
	BNE @AFTER_SOUND
	LDY @LOCAL01
	CPY #32
	BEQ @AFTER_SOUND
.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
	CPY #CHAR::SPACE
	BEQ @AFTER_SOUND
.ENDIF
	LDA #SFX::TEXT_PRINT
	JSL PLAY_SOUND
@AFTER_SOUND:
	LDA INSTANT_PRINTING
	AND #$00FF
	BNE @RETURN
	LDX SELECTED_TEXT_SPEED
	INX
	STX @LOCAL00
	BRA @DELAY_LOOP_CHECK
@TICK_DELAY:
	JSL WINDOW_TICK
	LDX @LOCAL00
	DEX
	STX @LOCAL00
@DELAY_LOOP_CHECK:
	BNE @TICK_DELAY
@RETURN:
	END_C_FUNCTION
