
PRINT_NEWLINE:
.IF .DEFINED(JPN)
	BEGIN_C_FUNCTION
.ELSE
	BEGIN_C_FUNCTION_FAR
.ENDIF
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
	LDA CURRENT_FOCUS_WINDOW
	CMP #.LOWORD(-1)
	BEQ @DONE
.ENDIF
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	TAY
	STY @LOCAL01
.IF .DEFINED(USA)
	JSL RESET_VWF_TEXT_STATE
	LDY @LOCAL01
.ENDIF
	LDA a:window_stats::font,Y
	BEQ @CHECK_TEXT_Y
	JSL RESET_VWF_TEXT_STATE
@CHECK_TEXT_Y:
	LDY @LOCAL01
	TYA
	CLC
	ADC #window_stats::text_y
	TAX
	LDA __BSS_START__,X
	STA @LOCAL00
	LDA a:window_stats::height,Y
	LSR
	DEC
	STA @VIRTUAL02
	LDA @LOCAL00
	CMP @VIRTUAL02
	BEQ @SCROLL_WINDOW
	INC
	STA __BSS_START__,X
	BRA @RESET_TEXT_X
@SCROLL_WINDOW:
	LDA CURRENT_FOCUS_WINDOW
.IF .DEFINED(JPN)
	JSR SCROLL_WINDOW_UP
.ELSE
	JSL SCROLL_WINDOW_UP
.ENDIF
@RESET_TEXT_X:
	LDY @LOCAL01
	TYX
	STZ a:window_stats::text_x,X
@DONE:
	END_C_FUNCTION
