
PRINT_STRING:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT32
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	STX @LOCAL01
	MOVE_INT @PARAM00, @VIRTUAL06
	LDA FORCE_CENTRE_TEXT_ALIGNMENT
	AND #$00FF
	BEQ @LOOP_CHECK
	MOVE_INT @VIRTUAL06, @LOCAL00
	TXA
	JSL CENTER_TEXT_IN_WINDOW
	BRA @LOOP_CHECK
@PRINT_CHAR:
	DEX
	STX @LOCAL01
	AND #$00FF
	INC @VIRTUAL06
	JSR PRINT_LETTER
@LOOP_CHECK:
	LDA [@VIRTUAL06]
	AND #$00FF
	BEQ @DONE
	LDX @LOCAL01
	BNE @PRINT_CHAR
@DONE:
	END_C_FUNCTION
