
PRINT_CURRENCY_VALUE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT32
	END_STACK_VARS
	MOVE_INT @PARAM00, @VIRTUAL06
	LDA CURRENT_FOCUS_WINDOW
	CMP #.LOWORD(-1)
	BEQ @DONE
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	TAY
	STY @LOCAL03
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR NUMBER_TO_TEXT_BUFFER
	STA @VIRTUAL02
	LDA #7
	SEC
	SBC @VIRTUAL02
	CLC
	ADC #.LOWORD(NUMBER_TEXT_BUFFER)
	STA @VIRTUAL04
	LDY @LOCAL03
	LDA a:window_stats::text_x,Y
	STA @LOCAL02
	LDA a:window_stats::text_y,Y
	STA @LOCAL01
	LDX @LOCAL01
	LDA a:window_stats::width,Y
	DEC
	DEC
	SEC
	SBC @VIRTUAL02
	JSR SET_FOCUS_TEXT_CURSOR
	LDA #$23
	JSR PRINT_LETTER
	BRA @CHECK_DIGITS_LEFT
@PRINT_DIGIT_LOOP:
	LDX @VIRTUAL04
	LDA __BSS_START__,X
	AND #$00FF
	CLC
	ADC #CHAR::ZERO
	INC @VIRTUAL04
	JSR PRINT_LETTER
	LDA @VIRTUAL02
	DEC
	STA @VIRTUAL02
@CHECK_DIGITS_LEFT:
	LDA @VIRTUAL02
	BNE @PRINT_DIGIT_LOOP
	LDA #$24
	JSR PRINT_LETTER
	LDX @LOCAL01
	LDA @LOCAL02
	JSR SET_FOCUS_TEXT_CURSOR
@DONE:
	END_C_FUNCTION
