
PRINT_TEXT_WITH_WORD_SPLITTING:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	LDY #0
	LDA #.LOWORD(USED_BG2_TILE_MAP) + 64
	STA WORD_SPLIT_CURSOR
	LDA USED_BG2_TILE_MAP + 112,X
	AND #$00FF
	DEC
	CLC
	ADC #.LOWORD(USED_BG2_TILE_MAP) + 64
	STA MENU_BACKUP_SELECTED_TEXT_Y
	LDA #.LOWORD(USED_BG2_TILE_MAP) + 64
	STA @LOCAL00
	BRA @ACCUMULATE_CHECK
@ACCUMULATE_LOOP:
	LDX WORD_SPLIT_CURSOR
	LDA __BSS_START__,X
	AND #$00FF
	STA @VIRTUAL02
	TYA
	CLC
	ADC @VIRTUAL02
	TAY
	INC WORD_SPLIT_CURSOR
	LDA @LOCAL00
	INC
	STA @LOCAL00
@ACCUMULATE_CHECK:
	LDA MENU_BACKUP_SELECTED_TEXT_Y
	STA @VIRTUAL02
	INC @VIRTUAL02
	LDA @LOCAL00
	CMP @VIRTUAL02
	BNE @ACCUMULATE_LOOP
	LDA #.LOWORD(USED_BG2_TILE_MAP) + 64
	STA WORD_SPLIT_CURSOR
	SEP #PROC_FLAGS::ACCUM8
	STZ UNREAD_7E9651
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
