
PRINT_ITEM_TYPE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL01
	LOADPTR ITEM_CONFIGURATION_TABLE, @VIRTUAL06
	LDA @LOCAL01
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA #item::type
.IF .DEFINED(JPN)
	JSR PRINT_STRING
.ELSEIF .DEFINED(PROTOTYPE19950327)
	JSL PRINT_STRING_WITH_WORDWRAP
.ELSE
	JSL PRINT_TEXT_WITH_WORD_SPLITTING
.ENDIF
	END_C_FUNCTION
