
PRINT_CHAR_WITH_SOUND:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL02
.IF !.DEFINED(PROTOTYPE19950327)
	LDA CURRENT_FOCUS_WINDOW
	CMP #.LOWORD(-1)
	BEQL @DONE
.ENDIF
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	TAX
	CLC
	ADC #window_stats::width
	TAY
	STY @LOCAL01
	LDA a:window_stats::text_x,X
	ASL
	STA @VIRTUAL04
	LDA __BSS_START__,Y
	TAY
	LDA a:window_stats::text_y,X
	JSL MULT16
	ASL
	ASL
	CLC
	ADC a:window_stats::tilemap_address,X
	CLC
	ADC @VIRTUAL04
	TAX
	STX @LOCAL00
	LDA __BSS_START__,X
	JSL FREE_TILE_SAFE
	LDY @LOCAL01
	LDA __BSS_START__,Y
	ASL
	STA @VIRTUAL04
	LDX @LOCAL00
	TXA
	CLC
	ADC @VIRTUAL04
	TAX
	LDA __BSS_START__,X
	JSL FREE_TILE_SAFE
	LDA @VIRTUAL02
	CMP #47
	BNE @NOT_SPACE
	SEP #PROC_FLAGS::ACCUM8
	STZ VWF_INDENT_NEW_LINE
@NOT_SPACE:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL02
	JSL SET_WINDOW_TILE_ATTRIBUTE_FAR
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	CMP WINDOW_TAIL
	BEQ @CHECK_SOUND_MODE
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA REDRAW_ALL_WINDOWS
@CHECK_SOUND_MODE:
	REP #PROC_FLAGS::ACCUM8
	LDA TEXT_SOUND_MODE
	CMP #2
	BNE @CHECK_MODE_3
	LDX #1
	BRA @SOUND_FLAG_SET
@CHECK_MODE_3:
	LDA TEXT_SOUND_MODE
	CMP #3
	BNE @DEFAULT_SOUND
	LDX #0
	BRA @SOUND_FLAG_SET
@DEFAULT_SOUND:
	LDX #0
	LDA BLINKING_TRIANGLE_FLAG
	BNE @SOUND_FLAG_SET
	LDX #1
@SOUND_FLAG_SET:
	CPX #0
	BEQ @SKIP_SOUND
	LDA INSTANT_PRINTING
	AND #$00FF
	BNE @SKIP_SOUND
	LDA @VIRTUAL02
	CMP #32
	BEQ @SKIP_SOUND
	LDA #SFX::TEXT_PRINT
	JSL PLAY_SOUND
@SKIP_SOUND:
	LDA INSTANT_PRINTING
	AND #$00FF
	BNE @DONE
	LDX SELECTED_TEXT_SPEED
	INX
	STX @LOCAL01
	BRA @DELAY_LOOP_CHECK
@DELAY_LOOP_BODY:
	JSL WINDOW_TICK
	LDX @LOCAL01
	DEX
	STX @LOCAL01
@DELAY_LOOP_CHECK:
	BNE @DELAY_LOOP_BODY
@DONE:
	END_C_FUNCTION
