
PRINT_MENU_ITEMS:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT8
	END_STACK_VARS
	LDA CURRENT_FOCUS_WINDOW
	CMP #.LOWORD(-1)
	BEQL @RETURN
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	STA @VIRTUAL04
	LDX @VIRTUAL04
	LDA a:window_stats::current_option,X
	CMP #.LOWORD(-1)
	BNE @HAS_OPTIONS
	SEP #PROC_FLAGS::ACCUM8
	LDA #$00FF
	STA EARLY_TICK_EXIT
	JMP @RETURN
@HAS_OPTIONS:
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	.A16
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	STA @VIRTUAL02
	JSR SET_INSTANT_PRINTING
@PROCESS_OPTION:
	LDX @VIRTUAL02
	LDA a:menu_option::page,X
	LDX @VIRTUAL04
	CMP a:window_stats::menu_page_number,X
	BEQ @ON_CURRENT_PAGE
	CMP #0
	BNEL @NEXT_OPTION
@ON_CURRENT_PAGE:
	LDA @VIRTUAL02
	JSL CLEAR_MENU_OPTION_TEXT
	LDX @VIRTUAL02
	LDA a:menu_option::page,X
	BNEL @PRINT_OPTION_LABEL
	LDA #0
	JSR SET_WINDOW_PALETTE_INDEX
	LDA #$014F
	JSL PRINT_CHAR_WITH_SOUND
	JSL ADVANCE_VWF_TILE
	LDA #0
	JSR SET_WINDOW_PALETTE_INDEX
	LDA @VIRTUAL04
	CLC
	ADC #window_stats::title
	TAY
	LDA __BSS_START__,Y
	AND #$00FF
	BEQL @PRINT_OPTION_LABEL
	LDX #.LOWORD(TEMPORARY_TEXT_BUFFER)
	BRA @TITLE_CHAR_LOOP
@COPY_TITLE_CHAR:
	SEP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	STA __BSS_START__,X
	INY
	INX
@TITLE_CHAR_LOOP:
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,Y
	STA @LOCAL03
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	BEQ @AFTER_TITLE_COPY
	AND #$00FF
	CMP #88
	BNE @COPY_TITLE_CHAR
@AFTER_TITLE_COPY:
	SEP #PROC_FLAGS::ACCUM8
	LDA #88
	STA __BSS_START__,X
	INX
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL04
	CLC
	ADC #window_stats::menu_page_number
	TAY
	STY @LOCAL02
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,Y
	CLC
	ADC #CHAR::ZERO
	STA __BSS_START__,X
	INX
	LDA #89
	STA __BSS_START__,X
	INX
	LDA #0
	STA __BSS_START__,X
	JSL ADVANCE_VWF_TILE
	.A16
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #.LOWORD(-1)
	LDA CURRENT_FOCUS_WINDOW
	JSL SET_WINDOW_TITLE
	JSL ADVANCE_VWF_TILE
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL STRLEN
	STA @LOCAL01
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @LOCAL01
	DEC
	DEC
	JSR PRINT_STRING
	LDY @LOCAL02
	LDA __BSS_START__,Y
	STA @LOCAL02
	LDX @VIRTUAL04
	LDA a:window_stats::option_count,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	TAX
	LDA MENU_OPTIONS + menu_option::previous,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	TAX
	LDA @LOCAL02
	CMP MENU_OPTIONS + menu_option::page,X
	BNE @NOT_LAST_PAGE
	LDA #CHAR::ONE
	BRA @PRINT_PAGE_TOTAL
@NOT_LAST_PAGE:
	CLC
	ADC #CHAR::ONE
@PRINT_PAGE_TOTAL:
	JSR PRINT_LETTER
	LDA #89
	JSR PRINT_LETTER
	BRA @NEXT_OPTION
@PRINT_OPTION_LABEL:
	LDA @VIRTUAL02
	CLC
	ADC #menu_option::label
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #.LOWORD(-1)
	JSR PRINT_STRING
@NEXT_OPTION:
	LDX @VIRTUAL02
	LDA a:menu_option::next,X
	CMP #.LOWORD(-1)
	BEQ @RETURN
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	STA @VIRTUAL02
	JMP @PROCESS_OPTION
@RETURN:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
