
PRINT_LETTER:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 "CHAR" ;int
	END_STACK_VARS
	TAX
	STX @LOCAL01
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	TAX
	LDA WINDOW_STATS + window_stats::font,X
	BEQ @USE_NORMAL_FONT
	LDX @LOCAL01
	TXA
	JSR PRINT_MRSATURN_LETTER
	LDX @LOCAL01
	CPX #$0060
	BCC @AFTER_FONT_RENDER
	TXA
	AND #$000F
	CMP #3
	BEQ @PRINT_DAKUTEN
	CMP #5
	BEQ @PRINT_DAKUTEN
	CMP #7
	BEQ @PRINT_DAKUTEN
	CMP #10
	BEQ @PRINT_DAKUTEN
	CMP #11
	BEQ @PRINT_HANDAKUTEN
	BRA @AFTER_FONT_RENDER
@PRINT_DAKUTEN:
	LDA #26
	JSR PRINT_MRSATURN_LETTER
	BRA @AFTER_FONT_RENDER
@PRINT_HANDAKUTEN:
	LDA #27
	JSR PRINT_MRSATURN_LETTER
	BRA @AFTER_FONT_RENDER
@USE_NORMAL_FONT:
	LDX @LOCAL01
	TXA
	JSR SET_WINDOW_TILE_ATTRIBUTE
@AFTER_FONT_RENDER:
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE + window_stats::prev,X
	CMP WINDOW_TAIL
	BEQ @AFTER_REDRAW
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA REDRAW_ALL_WINDOWS
@AFTER_REDRAW:
	REP #PROC_FLAGS::ACCUM8
	LDA TEXT_SOUND_MODE
	CMP #2
	BEQ @PLAY_SOUND
	LDA TEXT_SOUND_MODE
	CMP #3
	BEQ @AFTER_SOUND
	LDA BLINKING_TRIANGLE_FLAG
	BNE @AFTER_SOUND
@PLAY_SOUND:
	LDA INSTANT_PRINTING
	AND #$00FF
	BNE @AFTER_SOUND
	LDX @LOCAL01
	CPX #32
	BEQ @AFTER_SOUND
	LDA #SFX::TEXT_PRINT
	JSL PLAY_SOUND
@AFTER_SOUND:
	LDA INSTANT_PRINTING
	AND #$00FF
	BNE @RETURN
	LDA SELECTED_TEXT_SPEED
	INC
	STA @LOCAL00
	BRA @DELAY_LOOP_CHECK
@TICK_DELAY:
	JSL WINDOW_TICK
	LDA @LOCAL00
	DEC
	STA @LOCAL00
@DELAY_LOOP_CHECK:
	BNE @TICK_DELAY
@RETURN:
	END_C_FUNCTION
