
PRINT_CC_TABLE_VALUE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL01
	LOADPTR CC_1C_01_TABLE, @VIRTUAL06
	LDA @LOCAL01
	OPTIMIZED_MULT @VIRTUAL04, 3
	TAX
	MOVE_INTY @VIRTUAL06, @VIRTUAL0A
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	LDA [@VIRTUAL0A]
	AND #$00FF
	STA @LOCAL01
	AND #$0080
	BEQ @PRINT_STRING
	LDA @LOCAL01
	AND #$007F
	CMP #1
	BEQ @PRINT_INT8
	CMP #2
	BEQ @PRINT_INT16
	BRA @PRINT_INT32
@PRINT_INT8:
	TXA
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STORE_INT832 @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR PRINT_NUMBER
	BRA @RETURN
@PRINT_INT16:
	TXA
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	TAX
	LDA __BSS_START__,X
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR PRINT_NUMBER
	BRA @RETURN
@PRINT_INT32:
	TXA
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR PRINT_NUMBER
	BRA @RETURN
@PRINT_STRING:
	TXA
	INC
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA [@VIRTUAL06]
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA @LOCAL01
.IF .DEFINED(JPN)
	JSR PRINT_STRING
.ELSE
	JSL PRINT_STRING_WITH_WORDWRAP
.ENDIF
@RETURN:
	END_C_FUNCTION
