PROCESS_NAME_INPUT_STRING:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16 ;NEAR char*
	STACK_RESERVE_INT16 ;NEAR char*
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STX @VIRTUAL04
	STA @LOCAL01
	LDX #0
	STX @LOCAL00
	JMP @LOOP_NEXT
@PROCESS_CHAR:
	LDA @VIRTUAL00
	AND #$00FF
	STA @VIRTUAL02
	INC @VIRTUAL04
	LDX @LOCAL00
	BEQL @NO_PENDING
	TXA
	CMP @VIRTUAL02
	BNE @PENDING_CHECK_VOWEL
	LDA @LOCAL01
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #$7E
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	INC
	STA @LOCAL01
	JMP @LOOP_NEXT
@PENDING_CHECK_VOWEL:
	LDA @VIRTUAL02
	CMP #$41
	BEQ @PENDING_VOWEL_A
	CMP #$49
	BEQ @PENDING_VOWEL_I
	CMP #$55
	BEQ @PENDING_VOWEL_U
	CMP #$45
	BEQ @PENDING_VOWEL_E
	CMP #$4F
	BEQ @PENDING_VOWEL_O
	BRA @PENDING_NOT_VOWEL
@PENDING_VOWEL_A:
	LDY #0
	LDA @LOCAL01
	JSR TRANSLITERATE_CONSONANT_VOWEL
	STA @LOCAL01
	JMP @CLEAR_PENDING
@PENDING_VOWEL_I:
	LDY #1
	LDA @LOCAL01
	JSR TRANSLITERATE_CONSONANT_VOWEL
	STA @LOCAL01
	JMP @CLEAR_PENDING
@PENDING_VOWEL_U:
	LDY #2
	LDA @LOCAL01
	JSR TRANSLITERATE_CONSONANT_VOWEL
	STA @LOCAL01
	JMP @CLEAR_PENDING
@PENDING_VOWEL_E:
	LDY #3
	LDA @LOCAL01
	JSR TRANSLITERATE_CONSONANT_VOWEL
	STA @LOCAL01
	JMP @CLEAR_PENDING
@PENDING_VOWEL_O:
	LDY #4
	LDA @LOCAL01
	JSR TRANSLITERATE_CONSONANT_VOWEL
	STA @LOCAL01
	BRA @CLEAR_PENDING
@PENDING_NOT_VOWEL:
	LDA #$41
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @PENDING_NON_LETTER
	LDA @VIRTUAL02
	CLC
	SBC #$5A
	BRANCHGTS @PENDING_NON_LETTER
	CPX #$4E
	BNE @FLUSH_NON_N_CONSONANT
	LDA @LOCAL01
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #$9D
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	INC
	STA @LOCAL01
	BRA @STORE_NEW_PENDING
@FLUSH_NON_N_CONSONANT:
	LDY #1
	LDA @LOCAL01
	JSR TRANSLITERATE_CONSONANT_VOWEL
	STA @LOCAL01
@STORE_NEW_PENDING:
	LDX @VIRTUAL02
	STX @LOCAL00
	JMP @LOOP_NEXT
@PENDING_NON_LETTER:
	CPX #$4E
	BNE @FLUSH_PENDING_THEN_WRITE
	LDA @LOCAL01
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #$9D
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	TAX
	INX
	BRA @WRITE_CURRENT_CHAR
@FLUSH_PENDING_THEN_WRITE:
	LDY #1
	LDA @LOCAL01
	JSR TRANSLITERATE_CONSONANT_VOWEL
	TAX
@WRITE_CURRENT_CHAR:
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	TXA
	INC
	STA @LOCAL01
@CLEAR_PENDING:
	LDX #0
	STX @LOCAL00
	JMP @LOOP_NEXT
@NO_PENDING:
	LDA @VIRTUAL02
	CMP #$41
	BEQ @STANDALONE_VOWEL_A
	CMP #$49
	BEQ @STANDALONE_VOWEL_I
	CMP #$55
	BEQ @STANDALONE_VOWEL_U
	CMP #$45
	BEQ @STANDALONE_VOWEL_E
	CMP #$4F
	BEQ @STANDALONE_VOWEL_O
	BRA @STANDALONE_NOT_VOWEL
@STANDALONE_VOWEL_A:
	LDA @LOCAL01
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #$60
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	INC
	STA @LOCAL01
	JMP @LOOP_NEXT
@STANDALONE_VOWEL_I:
	LDA @LOCAL01
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #$70
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	INC
	STA @LOCAL01
	BRA @LOOP_NEXT
@STANDALONE_VOWEL_U:
	LDA @LOCAL01
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #$80
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	INC
	STA @LOCAL01
	BRA @LOOP_NEXT
@STANDALONE_VOWEL_E:
	LDA @LOCAL01
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #$90
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	INC
	STA @LOCAL01
	BRA @LOOP_NEXT
@STANDALONE_VOWEL_O:
	LDA @LOCAL01
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #$A0
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	INC
	STA @LOCAL01
	BRA @LOOP_NEXT
@STANDALONE_NOT_VOWEL:
	LDA #$41
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @WRITE_LITERAL
	LDA @VIRTUAL02
	CLC
	SBC #$5A
	BRANCHGTS @WRITE_LITERAL
	LDX @VIRTUAL02
	STX @LOCAL00
	BRA @LOOP_NEXT
@WRITE_LITERAL:
	LDA @LOCAL01
	TAX
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	INC
	STA @LOCAL01
@LOOP_NEXT:
	LDX @VIRTUAL04
	SEP #PROC_FLAGS::ACCUM8
	LDA __BSS_START__,X
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	AND #$00FF
	BNEL @PROCESS_CHAR
	LDX @LOCAL00
	BEQ @WRITE_TERMINATOR
	CPX #$4E
	BNE @FLUSH_FINAL_CONSONANT
	LDA @LOCAL01
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #$9D
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	INC
	STA @LOCAL01
	BRA @WRITE_TERMINATOR
@FLUSH_FINAL_CONSONANT:
	LDY #1
	LDA @LOCAL01
	JSR TRANSLITERATE_CONSONANT_VOWEL
	STA @LOCAL01
@WRITE_TERMINATOR:
	LDA @LOCAL01
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA __BSS_START__,X
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
