
PUSH_TEXT_STACK_FRAME:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	END_STACK_VARS
	LDX NEXT_TEXT_STACK_FRAME
	INX
	STX NEXT_TEXT_STACK_FRAME
	STX @VIRTUAL02
	LDA #$000A
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @AFTER_OVERFLOW_CHECK
	STZ NEXT_TEXT_STACK_FRAME
@AFTER_OVERFLOW_CHECK:
	LDA NEXT_TEXT_STACK_FRAME
	OPTIMIZED_MULT @VIRTUAL04, 27
	CLC
	ADC #.LOWORD(DISPLAY_TEXT_STATES)
	PLD
	RTS
