
QUEUE_NPC_TEXT_INTERACTION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA CURRENT_ENTITY_SLOT
	ASL
	TAX
	LDA ENTITY_NPC_IDS,X
	STA @LOCAL01
	CMP #.LOWORD(-1)
	BEQ @DONE
	LOADPTR NPC_CONFIG_TABLE, @VIRTUAL0A
	LDA @LOCAL01
	OPTIMIZED_MULT $04, .SIZEOF(npc_config)
	CLC
	ADC #npc_config::text_pointer
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BEQ @DONE
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #8
	JSL QUEUE_INTERACTION
@DONE:
	END_C_FUNCTION
