
RENDER_DONT_CARE_NAME:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @VIRTUAL02
	STX @LOCAL04
	STA @LOCAL03
	JSL SET_INSTANT_PRINTING
	CREATE_WINDOW_NEAR @LOCAL03
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	TAY
	STY @LOCAL02
	LDA #4
	CLC
	SBC @LOCAL04
	BRANCHLTEQS @MAX_LEN_6
	LDX #5
	BRA @SET_MAX_LEN
@MAX_LEN_6:
	LDX #6
@SET_MAX_LEN:
	STX @LOCAL01
	LDA @LOCAL01
	JSL INITIALIZE_KEYBOARD_INPUT_VWF
	LDY @LOCAL02
	LDA a:window_stats::text_y,Y
	TAX
	LDA #0
	JSL SET_FOCUS_TEXT_CURSOR
	LDA @VIRTUAL02
	CMP #6
	BNE @INCREMENT_ROW
	LDX #0
	BRA @STORE_ROW
@INCREMENT_ROW:
	LDX @VIRTUAL02
	INX
@STORE_ROW:
	STX @VIRTUAL04
	LDA @VIRTUAL04
	STA @LOCAL02
	LDA #0
	STA @VIRTUAL02
	STA @LOCAL00
	BRA @CHECK_NEXT_CHAR
@RENDER_CHAR:
	TXY
	LDX @LOCAL01
	LDA @LOCAL03
	JSL RENDER_KEYBOARD_INPUT_CHARACTER
	INC @VIRTUAL02
	LDA @VIRTUAL02
	STA @LOCAL00
@CHECK_NEXT_CHAR:
	LDA @LOCAL02
	STA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, 6
	STA @VIRTUAL02
	LDA @LOCAL04
	OPTIMIZED_MULT @VIRTUAL04, 42
	CLC
	ADC @VIRTUAL02
	LDX @LOCAL00
	STX @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	TAX
	LDA f:DONT_CARE_NAMES,X
	AND #$00FF
	TAX
	BNE @RENDER_CHAR
	LDA #WINDOW::FILE_SELECT_NAMING_KEYBOARD
	JSR SET_WINDOW_FOCUS
	LDA @LOCAL02
	STA @VIRTUAL04
	END_C_FUNCTION
