
RENDER_NAMING_CHARACTER:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @LOCAL03
	STX @VIRTUAL04
	TAX
	STX @LOCAL02
	JSR SET_INSTANT_PRINTING
	LDX @LOCAL02
	TXA
	JSR SET_WINDOW_FOCUS
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(window_stats)
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	STA @VIRTUAL02
	LDY @LOCAL03
	TYA
	CMP #.LOWORD(-1)
	BEQ @HANDLE_BACKSPACE
	CMP #WINDOW::FILE_SELECT_NAMING_NAME_BOX
	BEQ @HANDLE_NAME_BOX
	CMP #WINDOW::FILE_SELECT_NAMING_MESSAGE
	BEQL @HANDLE_MESSAGE_WINDOW
	JMP @HANDLE_OTHER_WINDOW
@HANDLE_BACKSPACE:
	LDA @VIRTUAL02
	CLC
	ADC #window_stats::text_x
	TAX
	STX @LOCAL03
	LDA __BSS_START__,X
	BNE @CHECK_CURSOR_POS
	LDX #1
	STX @LOCAL01
	JMP @SET_FOCUS_AND_RETURN
@CHECK_CURSOR_POS:
	CMP @VIRTUAL04
	BCS @PRINT_BULLET
	LDA #CHAR::PLACEHOLDER
	JSR PRINT_LETTER
	LDX @LOCAL03
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
@PRINT_BULLET:
	LDA @VIRTUAL02
	CLC
	ADC #window_stats::text_x
	TAX
	STX @LOCAL00
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
	LDA #CHAR::BULLET
	JSR PRINT_LETTER
	LDX @LOCAL00
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
	JMP @DONE
@HANDLE_NAME_BOX:
	LDX @VIRTUAL02
	LDA a:window_stats::text_x,X
	STA @LOCAL00
	BEQL @DONE
	LDX @VIRTUAL02
	LDA a:window_stats::text_y,X
	TAX
	LDA @LOCAL00
	DEC
	JSL GET_MENU_TILE_AT_POSITION
	STA @LOCAL00
	CMP #96
	BCS @CHECK_DAKUTEN
	JMP @DONE
@CHECK_DAKUTEN:
	AND #$000F
	TAX
	CPX #2
	BEQ @PRINT_DAKUTEN
	CPX #4
	BEQ @PRINT_DAKUTEN
	CPX #6
	BEQ @PRINT_DAKUTEN
	CPX #9
	BEQ @PRINT_DAKUTEN
	JMP @DONE
@PRINT_DAKUTEN:
	LDA @VIRTUAL02
	CLC
	ADC #window_stats::text_x
	TAX
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
	LDA @LOCAL00
	INC
	JSR PRINT_LETTER
	BRA @DONE
@HANDLE_MESSAGE_WINDOW:
	LDA @VIRTUAL02
	CLC
	ADC #window_stats::text_x
	TAY
	STY @LOCAL03
	LDA __BSS_START__,Y
	STA @LOCAL01
	BEQ @DONE
	LDX @VIRTUAL02
	LDA a:window_stats::text_y,X
	TAX
	LDA @LOCAL01
	DEC
	JSL GET_MENU_TILE_AT_POSITION
	STA @LOCAL02
	CMP #96
	BLTEQ @DONE
	AND #$000F
	CMP #9
	BNE @DONE
	LDY @LOCAL03
	LDA __BSS_START__,Y
	DEC
	STA __BSS_START__,Y
	LDA @LOCAL02
	INC
	INC
	JSR PRINT_LETTER
	BRA @DONE
@HANDLE_OTHER_WINDOW:
	LDA @VIRTUAL02
	CLC
	ADC #window_stats::text_x
	TAX
	STX @LOCAL02
	LDA __BSS_START__,X
	CMP @VIRTUAL04
	BCS @DONE
	TYA
	JSR PRINT_LETTER
	LDX @LOCAL02
	LDA __BSS_START__,X
	CMP @VIRTUAL04
	BCS @DONE
	LDA #CHAR::BULLET
	JSR PRINT_LETTER
	LDX @LOCAL02
	LDA __BSS_START__,X
	DEC
	STA __BSS_START__,X
@DONE:
	LDX #0
	STX @LOCAL01
@SET_FOCUS_AND_RETURN:
	LDA #WINDOW::FILE_SELECT_NAMING_KEYBOARD
	JSR SET_WINDOW_FOCUS
	LDX @LOCAL01
	TXA
	PLD
	RTS
