
SCROLL_FLYOVER_TEXT:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
.IF .DEFINED(JPN)
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
.ELSE
	STACK_RESERVE_INT8
.ENDIF
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	CLC
	ADC FLYOVER_VWF_Y
	STA FLYOVER_VWF_Y
	STZ FLYOVER_VWF_X
	LSR
	LSR
	LSR
.IF !.DEFINED(JPN)
	INC
.ENDIF
	CLC
	ADC FLYOVER_SCREEN_OFFSET
	STA FLYOVER_SCREEN_OFFSET
	CMP #32
	BCC @AFTER_WRAP
	SEC
	SBC #32
	STA FLYOVER_SCREEN_OFFSET
@AFTER_WRAP:
.IF .DEFINED(JPN)
	LDA FLYOVER_VWF_Y
	LSR
	LSR
	LSR
	STA @LOCAL01
	LDY #32 * 13
	JSL MULT16
	CLC
	ADC #.LOWORD(VWF_BUFFER)
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDY #32 * 13
	LDA @LOCAL01
	STA @VIRTUAL02
	LDA #4
	SEC
	SBC @VIRTUAL02
	JSL MULT16
	TAX
	LDA #.LOWORD(VWF_BUFFER)
	JSL MEMCPY16
	LDA FLYOVER_VWF_Y
	LSR
	LSR
	LSR
	STA @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA @LOCAL00
	LDY #32 * 13
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL01
	JSL MULT16
	TAX
	LDY #32 * 13
	LDA @LOCAL01
	STA @VIRTUAL02
	LDA #4
	SEC
	SBC @VIRTUAL02
	JSL MULT16
	CLC
	ADC #.LOWORD(VWF_BUFFER)
	JSL MEMSET16
.ELSE
	JSL WAIT_DMA_FINISHED
	SEP #PROC_FLAGS::ACCUM8
	LDA #<-1
	STA @LOCAL00
	LDX #32 * 52
	REP #PROC_FLAGS::ACCUM8
	LDA #.LOWORD(VWF_BUFFER)
	JSL MEMSET16
.ENDIF
	LDA FLYOVER_VWF_Y
	AND #$0007
	STA FLYOVER_VWF_Y
.IF !.DEFINED(JPN)
	STZ FLYOVER_PIXEL_OFFSET
	STZ FLYOVER_BYTE_OFFSET
.ENDIF
	END_C_FUNCTION
