
SELECTION_MENU:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL0C
	LDA CURRENT_FOCUS_WINDOW
	STA @LOCAL0B
	CMP #.LOWORD(-1)
	BNE @INIT_WINDOW
	LDA #0
	JMP @RETURN
@INIT_WINDOW:
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	STA @LOCAL0A
.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
	LDA RESTORE_MENU_BACKUP
	AND #$00FF
	BEQ @AFTER_RESTORE_BACKUP
	LDA MENU_BACKUP_CURRENT_OPTION
	LDY #window_stats::current_option
	STA (@LOCAL0A),Y
	LDA MENU_BACKUP_SELECTED_OPTION
	LDY #window_stats::selected_option
	STA (@LOCAL0A),Y
.ENDIF
@AFTER_RESTORE_BACKUP:
	LDY #window_stats::selected_option
	LDA (@LOCAL0A),Y
	CMP #.LOWORD(-1)
	BEQ @NO_SELECTED_OPTION
	TAX
	STX @LOCAL09
	STA @LOCAL08
	LDY #window_stats::current_option
	LDA (@LOCAL0A),Y
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	STA @VIRTUAL04
	BRA @TRAVERSE_SELECTED_CHECK
@TRAVERSE_SELECTED:
	DEX
	STX @LOCAL09
	LDX @VIRTUAL04
	LDA __BSS_START__+2,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	STA @VIRTUAL04
@TRAVERSE_SELECTED_CHECK:
	LDX @LOCAL09
	BNE @TRAVERSE_SELECTED
	JSR SET_INSTANT_PRINTING
	LDX @VIRTUAL04
	LDY a:menu_option::text_y,X
	LDX @VIRTUAL04
	LDA a:menu_option::text_x,X
	TAX
	INX
	LDA @VIRTUAL04
	JSL SETUP_MENU_OPTION_VWF
	LDA @VIRTUAL04
	CLC
	ADC #menu_option::label
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #0
	LDA #.LOWORD(-1)
	JSL SET_FILE_SELECT_TEXT_HIGHLIGHT
	BRA @SETUP_CURRENT_OPTION
@NO_SELECTED_OPTION:
	STZ @LOCAL08
	LDY #window_stats::current_option
	LDA (@LOCAL0A),Y
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	STA @VIRTUAL04
@SETUP_CURRENT_OPTION:
	STZ @LOCAL09
	LDA @VIRTUAL04
	CLC
	ADC #menu_option::script
	TAY
	STY @LOCAL07
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	CMP @VIRTUAL0A+2
	BNE @CHECK_SCRIPT_LOW
	LDA @VIRTUAL06
	CMP @VIRTUAL0A
@CHECK_SCRIPT_LOW:
	BEQ @AFTER_SCRIPT
	JSR SET_INSTANT_PRINTING
	LDY @LOCAL07
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
@AFTER_SCRIPT:
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	LDA @LOCAL0A
	CLC
	ADC #window_stats::cursor_move_callback
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	CMP @VIRTUAL0A+2
	BNE @CHECK_CALLBACK_LOW
	LDA @VIRTUAL06
	CMP @VIRTUAL0A
@CHECK_CALLBACK_LOW:
	BEQ @AFTER_CURSOR_CALLBACK
	LDX @VIRTUAL04
	LDA a:menu_option::unknown0,X
	CMP #1
	BNE @CALLBACK_USE_USERDATA
	LDA @LOCAL08
	INC
	BRA @CALL_CURSOR_CALLBACK
@CALLBACK_USE_USERDATA:
	LDX @VIRTUAL04
	LDA a:menu_option::userdata,X
@CALL_CURSOR_CALLBACK:
	STA @LOCAL06
	LDA @LOCAL0A
	CLC
	ADC #window_stats::cursor_move_callback
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDA @LOCAL06
	PHA
	MOVE_INT @VIRTUAL06, TEMP_FUNCTION_POINTER
	PLA
	JSL JUMP_TEMP_FUNCTION_POINTER
	LDA @LOCAL0B
	JSR SET_WINDOW_FOCUS
@AFTER_CURSOR_CALLBACK:
	JSR CLEAR_INSTANT_PRINTING
.IF .DEFINED(USA) && (!.DEFINED(PROTOTYPE19950327))
	LDA RESTORE_MENU_BACKUP
	AND #$00FF
	BEQ @AFTER_BACKUP_TEXT_POS
	LDA MENU_BACKUP_SELECTED_TEXT_X
	LDX @VIRTUAL04
	STA a:menu_option::text_x,X
	LDA MENU_BACKUP_SELECTED_TEXT_Y
	LDX @VIRTUAL04
	STA a:menu_option::text_y,X
.ENDIF
@AFTER_BACKUP_TEXT_POS:
	LDX @VIRTUAL04
	LDY a:menu_option::text_y,X
	LDX @VIRTUAL04
	LDA a:menu_option::text_x,X
	TAX
	LDA @VIRTUAL04
	JSL SETUP_MENU_OPTION_VWF
	LDA #1
	JSR SET_WINDOW_PALETTE_INDEX
	LDA #33
	JSR SET_TILE_ATTRIBUTE_AND_REDRAW
	LDA #0
	JSR SET_WINDOW_PALETTE_INDEX
	JSL WINDOW_TICK
	LDA #1
	STA @VIRTUAL02
@CURSOR_BLINK_LOOP:
	LDA @VIRTUAL02
	EOR #$0001
	STA @VIRTUAL02
	STA @LOCAL05
	LDY #window_stats::text_y
	LDA (@LOCAL0A),Y
	ASL
	LDY #window_stats::window_y
	CLC
	ADC (@LOCAL0A),Y
	ASL
	ASL
	ASL
	ASL
	ASL
	STA @VIRTUAL02
	LDY #window_stats::window_x
	LDA (@LOCAL0A),Y
	LDY #window_stats::text_x
	CLC
	ADC (@LOCAL0A),Y
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #VRAM::TEXT_LAYER_TILEMAP + TILEMAP_COORDS 0, 1
	STA @LOCAL07
	LDA @LOCAL05
	STA @VIRTUAL02
	ASL
	STA @LOCAL04
	LOADPTR HPPP_WINDOW_TILE_DATA+14, @VIRTUAL06
	LDA @LOCAL04
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDY @LOCAL07
	LDX #2
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	.A16
	LOADPTR HPPP_WINDOW_TILE_DATA+18, @VIRTUAL06
	LDA @LOCAL04
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA @LOCAL07
	CLC
	ADC #32
	TAY
	LDX #2
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	.A16
	LDX #0
	STX @LOCAL07
	JMP @FRAME_WAIT_CHECK
@INPUT_TICK:
	JSL UPDATE_HPPP_METER_AND_RENDER
	LDA PAD_PRESS
	AND #PAD::UP
	BEQ @CHECK_LEFT_PRESS
	LDX @VIRTUAL04
	LDA a:menu_option::text_x,X
	STA @LOCAL07
	STZ @LOCAL00
	LDA #SFX::CURSOR3
	STA @LOCAL00+2
	LDA @LOCAL07
	STA @LOCAL01
	LDY #window_stats::height
	LDA (@LOCAL0A),Y
	LSR
	STA @LOCAL02
	LDY #.LOWORD(-1)
	LDX @VIRTUAL04
	LDA a:menu_option::text_y,X
	TAX
	LDA @LOCAL07
	JSL MOVE_CURSOR
	STA @LOCAL06
	JMP @PROCESS_CURSOR_MOVE
@CHECK_LEFT_PRESS:
	LDA PAD_PRESS
	AND #PAD::LEFT
	BEQ @CHECK_DOWN_PRESS
	LDX @VIRTUAL04
	LDA a:menu_option::text_y,X
	STA @LOCAL09
	LDA #.LOWORD(-1)
	STA @LOCAL00
	LDA #SFX::CURSOR2
	STA @LOCAL00+2
	LDY #window_stats::width
	LDA (@LOCAL0A),Y
	STA @LOCAL01
	LDA @LOCAL09
	STA @LOCAL02
	LDY #0
	TAX
	STX @LOCAL03
	LDX @VIRTUAL04
	LDA a:menu_option::text_x,X
	LDX @LOCAL03
	JSL MOVE_CURSOR
	STA @LOCAL06
	JMP @PROCESS_CURSOR_MOVE
@CHECK_DOWN_PRESS:
	LDA PAD_PRESS
	AND #PAD::DOWN
	BEQ @CHECK_RIGHT_PRESS
	LDX @VIRTUAL04
	LDA a:menu_option::text_x,X
	STA @LOCAL07
	STZ @LOCAL00
	LDA #SFX::CURSOR3
	STA @LOCAL00+2
	LDA @LOCAL07
	STA @LOCAL01
	LDA #.LOWORD(-1)
	STA @LOCAL02
	LDY #1
	LDX @VIRTUAL04
	LDA a:menu_option::text_y,X
	TAX
	LDA @LOCAL07
	JSL MOVE_CURSOR
	STA @LOCAL06
	JMP @PROCESS_CURSOR_MOVE
@CHECK_RIGHT_PRESS:
	LDA PAD_PRESS
	AND #PAD::RIGHT
	BEQ @CHECK_UP_HELD
	LDX @VIRTUAL04
	LDA a:menu_option::text_y,X
	STA @LOCAL09
	LDA #1
	STA @LOCAL00
	LDA #SFX::CURSOR2
	STA @LOCAL00+2
	LDA #.LOWORD(-1)
	STA @LOCAL01
	LDA @LOCAL09
	STA @LOCAL02
	LDY #0
	TAX
	STX @LOCAL06
	LDX @VIRTUAL04
	LDA a:menu_option::text_x,X
	LDX @LOCAL06
	JSL MOVE_CURSOR
	STA @LOCAL06
	JMP @PROCESS_CURSOR_MOVE
@CHECK_UP_HELD:
	LDA PAD_HELD
	AND #PAD::UP
	BEQ @CHECK_LEFT_HELD
	STZ @LOCAL00
	LDA #SFX::CURSOR3
	STA @LOCAL00+2
	LDY #.LOWORD(-1)
	LDX @VIRTUAL04
	LDA a:menu_option::text_y,X
	TAX
	STX @LOCAL05
	LDX @VIRTUAL04
	LDA a:menu_option::text_x,X
	LDX @LOCAL05
	JSL FIND_NEXT_MENU_OPTION
	STA @LOCAL06
	JMP @PROCESS_CURSOR_MOVE
@CHECK_LEFT_HELD:
	LDA PAD_HELD
	AND #PAD::LEFT
	BEQ @CHECK_DOWN_HELD
	LDA #.LOWORD(-1)
	STA @LOCAL00
	LDA #SFX::CURSOR2
	STA @LOCAL00+2
	LDY #0
	LDX @VIRTUAL04
	LDA a:menu_option::text_y,X
	TAX
	STX @LOCAL05
	LDX @VIRTUAL04
	LDA a:menu_option::text_x,X
	LDX @LOCAL05
	JSL FIND_NEXT_MENU_OPTION
	STA @LOCAL06
	JMP @PROCESS_CURSOR_MOVE
@CHECK_DOWN_HELD:
	LDA PAD_HELD
	AND #PAD::DOWN
	BEQ @CHECK_RIGHT_HELD
	STZ @LOCAL00
	LDA #SFX::CURSOR3
	STA @LOCAL00+2
	LDY #1
	LDX @VIRTUAL04
	LDA a:menu_option::text_y,X
	TAX
	STX @LOCAL03
	LDX @VIRTUAL04
	LDA a:menu_option::text_x,X
	LDX @LOCAL03
	JSL FIND_NEXT_MENU_OPTION
	STA @LOCAL06
	JMP @PROCESS_CURSOR_MOVE
@CHECK_RIGHT_HELD:
	LDA PAD_HELD
	AND #PAD::RIGHT
	BEQ @CHECK_CONFIRM
	LDA #1
	STA @LOCAL00
	LDA #SFX::CURSOR2
	STA @LOCAL00+2
	LDY #0
	LDX @VIRTUAL04
	LDA a:menu_option::text_y,X
	TAX
	STX @LOCAL06
	LDX @VIRTUAL04
	LDA a:menu_option::text_x,X
	LDX @LOCAL06
	JSL FIND_NEXT_MENU_OPTION
	STA @LOCAL06
	JMP @PROCESS_CURSOR_MOVE
@CHECK_CONFIRM:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON | PAD::L_BUTTON
	BEQL @CHECK_CANCEL
	JSR SET_INSTANT_PRINTING
	LDX @VIRTUAL04
	LDA a:menu_option::page,X
	BEQL @HANDLE_PAGINATION
	LDX @VIRTUAL04
	LDA a:menu_option::sound_effect,X
	AND #$00FF
	JSL PLAY_SOUND
	LDX @VIRTUAL04
	LDY a:menu_option::text_y,X
	LDX @VIRTUAL04
	LDA a:menu_option::text_x,X
	TAX
	LDA @VIRTUAL04
	JSL SETUP_MENU_OPTION_VWF
	LDA #47
	JSR SET_TILE_ATTRIBUTE_AND_REDRAW
	LDA #6
	JSR SET_WINDOW_PALETTE_INDEX
	LDA ENABLE_WORD_WRAP
	BEQ @NO_WORD_WRAP
	LDA f:ALLOW_TEXT_OVERFLOW
	AND #$00FF
	CMP #1
	BNE @HIGHLIGHT_DEFAULT
	LDA CURRENT_FOCUS_WINDOW
	CMP #WINDOW::FILE_SELECT_MAIN
	BNE @HIGHLIGHT_FILE_SELECT
	JSL APPLY_WINDOW_TEXT_ATTRIBUTES
	BRA @AFTER_HIGHLIGHT
@HIGHLIGHT_FILE_SELECT:
	LDA @VIRTUAL04
	CLC
	ADC #menu_option::label
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #1
	LDA #4
	JSL SET_FILE_SELECT_TEXT_HIGHLIGHT
	BRA @AFTER_HIGHLIGHT
@HIGHLIGHT_DEFAULT:
	LDA @VIRTUAL04
	CLC
	ADC #menu_option::label
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX #1
	LDA #.LOWORD(-1)
	JSL SET_FILE_SELECT_TEXT_HIGHLIGHT
	BRA @AFTER_HIGHLIGHT
@NO_WORD_WRAP:
	JSL APPLY_WINDOW_TEXT_ATTRIBUTES
@AFTER_HIGHLIGHT:
	LDA #0
	JSR SET_WINDOW_PALETTE_INDEX
	JSR CLEAR_INSTANT_PRINTING
	LDA @LOCAL08
	LDY #window_stats::selected_option
	STA (@LOCAL0A),Y
	LDX @VIRTUAL04
	LDA a:menu_option::unknown0,X
	CMP #1
	BNE @RETURN_USERDATA
	LDA @LOCAL08
	INC
	JMP @RETURN
@RETURN_USERDATA:
	LDX @VIRTUAL04
	LDA a:menu_option::userdata,X
	JMP @RETURN
@HANDLE_PAGINATION:
	LDA #SFX::CURSOR2
	JSL PLAY_SOUND
	JSR CLEAR_FOCUS_WINDOW_CONTENT
	LDA @LOCAL0A
	CLC
	ADC #window_stats::menu_page_number
	TAX
	STX @LOCAL09
	LDA __BSS_START__,X
	STA @LOCAL07
	LDX @VIRTUAL04
	LDA a:menu_option::previous,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	TAX
	LDA @LOCAL07
	CMP MENU_OPTIONS + menu_option::page,X
	BNE @PAGE_INCREMENT
	LDA #1
	LDX @LOCAL09
	STA __BSS_START__,X
	BRA @AFTER_PAGE_UPDATE
@PAGE_INCREMENT:
	INC
	LDX @LOCAL09
	STA __BSS_START__,X
@AFTER_PAGE_UPDATE:
	JSR CLEAR_INSTANT_PRINTING
	LDA @LOCAL0B
.IF .DEFINED(PROTOTYPE19950327)
	JSL CLEANUP_WINDOW_TILES
.ELSE
	JSL CLEAR_WINDOW_TILEMAP
.ENDIF
	JSL WINDOW_TICK
	JSR PRINT_MENU_ITEMS
	JSR SET_INSTANT_PRINTING
	JMP @SETUP_CURRENT_OPTION
@CHECK_CANCEL:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON
	BEQ @NO_CANCEL
	LDA @LOCAL0C
	CMP #1
	BNE @NO_CANCEL
	LDA #SFX::CURSOR2
	JSL PLAY_SOUND
	LDA #0
	JMP @RETURN
@NO_CANCEL:
	INC @LOCAL09
	LDA OPEN_WINDOW_TABLE
	CMP WINDOW_TAIL
	BNE @INCREMENT_FRAME
	LDA @LOCAL09
	CMP #60
	BLTEQ @INCREMENT_FRAME
	LDA OPEN_WINDOW_TABLE + WINDOW::CARRIED_MONEY * 2
	CMP #.LOWORD(-1)
	BNE @AFTER_SHOW_MONEY
	JSR SHOW_HPPP_AND_MONEY_WINDOWS
@AFTER_SHOW_MONEY:
	LDA #0
	JSR SET_WINDOW_FOCUS
	JMP @SETUP_CURRENT_OPTION
@INCREMENT_FRAME:
	LDX @LOCAL07
	INX
	STX @LOCAL07
@FRAME_WAIT_CHECK:
	CPX #10
	BCCL @INPUT_TICK
	JMP @CURSOR_BLINK_LOOP
@PROCESS_CURSOR_MOVE:
	CMP #.LOWORD(-1)
	BEQL @SETUP_CURRENT_OPTION
	LDA #0
	STA @VIRTUAL02
	LDY #window_stats::current_option
	LDA (@LOCAL0A),Y
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	STA @LOCAL09
	LDA @LOCAL06
	AND #$00FF
	TAX
	LDA @LOCAL06
	AND #$FF00
	XBA
	AND #$00FF
	STA @LOCAL06
	BRA @FIND_OPTION_CHECK
@FIND_OPTION_NEXT:
	INC @VIRTUAL02
	LDY #menu_option::next
	LDA (@LOCAL09),Y
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	STA @LOCAL09
@FIND_OPTION_CHECK:
	LDY #menu_option::text_x
	TXA
	CMP (@LOCAL09),Y
	BNE @FIND_OPTION_NEXT
	LDY #menu_option::text_y
	LDA @LOCAL06
	CMP (@LOCAL09),Y
	BNE @FIND_OPTION_NEXT
	LDY #menu_option::page
	LDA (@LOCAL09),Y
	TAY
	STY @LOCAL08
	TYA
	LDY #window_stats::menu_page_number
	CMP (@LOCAL0A),Y
	BEQ @OPTION_FOUND
	LDY @LOCAL08
	BNE @FIND_OPTION_NEXT
@OPTION_FOUND:
	LDX @VIRTUAL04
	LDY a:menu_option::text_y,X
	LDX @VIRTUAL04
	LDA a:menu_option::text_x,X
	TAX
	LDA @VIRTUAL04
	JSL SETUP_MENU_OPTION_VWF
	LDA #47
	JSR SET_TILE_ATTRIBUTE_AND_REDRAW
	LDA @VIRTUAL02
	STA @LOCAL08
	LDA @LOCAL09
	STA @VIRTUAL04
	JMP @SETUP_CURRENT_OPTION
@RETURN:
	END_C_FUNCTION
