
SELECTION_MENU:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL0C
	LDA CURRENT_FOCUS_WINDOW
	STA @LOCAL0B
	CMP #.LOWORD(-1)
	BNE @INIT_WINDOW
	LDA #0
	JMP @RETURN
@INIT_WINDOW:
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	STA @LOCAL0A
	LDY #window_stats::selected_option
	LDA (@LOCAL0A),Y
	CMP #.LOWORD(-1)
	BEQ @NO_SELECTED_OPTION
	TAX
	STX @LOCAL09
	STA @LOCAL08
	LDY #window_stats::current_option
	LDA (@LOCAL0A),Y
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	STA @VIRTUAL02
	BRA @TRAVERSE_SELECTED_CHECK
@TRAVERSE_SELECTED:
	DEX
	STX @LOCAL09
	LDX @VIRTUAL02
	LDA __BSS_START__+2,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	STA @VIRTUAL02
@TRAVERSE_SELECTED_CHECK:
	LDX @LOCAL09
	BNE @TRAVERSE_SELECTED
	JSR SET_INSTANT_PRINTING
	LDX @VIRTUAL02
	LDA a:menu_option::text_y,X
	TAX
	STX @LOCAL07
	LDX @VIRTUAL02
	LDA a:menu_option::text_x,X
	INC
	LDX @LOCAL07
	JSR SET_FOCUS_TEXT_CURSOR
	LDA @VIRTUAL02
	CLC
	ADC #menu_option::label
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #.LOWORD(-1)
	JSR PRINT_STRING
	BRA @SETUP_CURRENT_OPTION
@NO_SELECTED_OPTION:
	STZ @LOCAL08
	LDY #window_stats::current_option
	LDA (@LOCAL0A),Y
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	STA @VIRTUAL02
@SETUP_CURRENT_OPTION:
	STZ @LOCAL09
	LDA @VIRTUAL02
	CLC
	ADC #menu_option::script
	TAY
	STY @LOCAL06
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	CMP @VIRTUAL0A+2
	BNE @CHECK_SCRIPT_LOW
	LDA @VIRTUAL06
	CMP @VIRTUAL0A
@CHECK_SCRIPT_LOW:
	BEQ @AFTER_SCRIPT
	JSR SET_INSTANT_PRINTING
	LDY @LOCAL06
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
@AFTER_SCRIPT:
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	LDA @LOCAL0A
	CLC
	ADC #window_stats::cursor_move_callback
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	CMP @VIRTUAL0A+2
	BNE @CHECK_CALLBACK_LOW
	LDA @VIRTUAL06
	CMP @VIRTUAL0A
@CHECK_CALLBACK_LOW:
	BEQ @AFTER_CURSOR_CALLBACK
	LDX @VIRTUAL02
	LDA a:menu_option::unknown0,X
	CMP #1
	BNE @CALLBACK_USE_USERDATA
	LDA @LOCAL08
	INC
	BRA @CALL_CURSOR_CALLBACK
@CALLBACK_USE_USERDATA:
	LDX @VIRTUAL02
	LDA a:menu_option::userdata,X
@CALL_CURSOR_CALLBACK:
	STA @LOCAL07
	LDA @LOCAL0A
	CLC
	ADC #window_stats::cursor_move_callback
	TAY
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDA @LOCAL07
	PHA
	MOVE_INT @VIRTUAL06, TEMP_FUNCTION_POINTER
	PLA
	JSL JUMP_TEMP_FUNCTION_POINTER
	LDA @LOCAL0B
	JSR SET_WINDOW_FOCUS
@AFTER_CURSOR_CALLBACK:
	JSR CLEAR_INSTANT_PRINTING
	LDX @VIRTUAL02
	LDA a:menu_option::text_y,X
	TAX
	STX @LOCAL07
	LDX @VIRTUAL02
	LDA a:menu_option::text_x,X
	LDX @LOCAL07
	JSR SET_FOCUS_TEXT_CURSOR
	LDA #1
	JSR SET_WINDOW_PALETTE_INDEX
	LDA #33
	JSR SET_TILE_ATTRIBUTE_AND_REDRAW
	LDA #0
	JSR SET_WINDOW_PALETTE_INDEX
	JSL WINDOW_TICK
	LDA #1
	STA @LOCAL06
@CURSOR_BLINK_LOOP:
	LDA @LOCAL06
	EOR #$0001
	STA @LOCAL06
	LDY #window_stats::text_y
	LDA (@LOCAL0A),Y
	ASL
	LDY #window_stats::window_y
	CLC
	ADC (@LOCAL0A),Y
	ASL
	ASL
	ASL
	ASL
	ASL
	STA @VIRTUAL04
	LDY #window_stats::window_x
	LDA (@LOCAL0A),Y
	LDY #window_stats::text_x
	CLC
	ADC (@LOCAL0A),Y
	CLC
	ADC @VIRTUAL04
	CLC
	ADC #VRAM::TEXT_LAYER_TILEMAP + TILEMAP_COORDS 0, 1
	STA @LOCAL05
	LDA @LOCAL06
	ASL
	STA @VIRTUAL04
	LOADPTR HPPP_WINDOW_TILE_DATA+14, @VIRTUAL06
	LDA @VIRTUAL04
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDY @LOCAL05
	LDX #2
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	.A16
	LOADPTR HPPP_WINDOW_TILE_DATA+18, @VIRTUAL06
	LDA @VIRTUAL04
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA @LOCAL05
	CLC
	ADC #32
	TAY
	LDX #2
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	.A16
	LDX #0
	STX @LOCAL04
	JMP @FRAME_WAIT_CHECK
@INPUT_TICK:
	JSL UPDATE_HPPP_METER_AND_RENDER
	LDA PAD_PRESS
	AND #PAD::UP
	BEQ @CHECK_LEFT_PRESS
	LDX @VIRTUAL02
	LDA a:menu_option::text_x,X
	STA @LOCAL03
	LDA #0
	STA @LOCAL00
	LDA #SFX::CURSOR3
	STA @LOCAL00+2
	LDA @LOCAL03
	STA @LOCAL01
	LDY #window_stats::height
	LDA (@LOCAL0A),Y
	LSR
	STA @LOCAL02
	LDY #.LOWORD(-1)
	LDX @VIRTUAL02
	LDA a:menu_option::text_y,X
	TAX
	LDA @LOCAL03
	JSL MOVE_CURSOR
	STA @LOCAL07
	JMP @PROCESS_CURSOR_MOVE
@CHECK_LEFT_PRESS:
	LDA PAD_PRESS
	AND #PAD::LEFT
	BEQ @CHECK_DOWN_PRESS
	LDX @VIRTUAL02
	LDA a:menu_option::text_y,X
	STA @LOCAL07
	LDA #.LOWORD(-1)
	STA @LOCAL00
	LDA #SFX::CURSOR2
	STA @LOCAL00+2
	LDY #window_stats::width
	LDA (@LOCAL0A),Y
	STA @LOCAL01
	LDA @LOCAL07
	STA @LOCAL02
	LDY #0
	TAX
	STX @LOCAL07
	LDX @VIRTUAL02
	LDA a:menu_option::text_x,X
	LDX @LOCAL07
	JSL MOVE_CURSOR
	STA @LOCAL07
	JMP @PROCESS_CURSOR_MOVE
@CHECK_DOWN_PRESS:
	LDA PAD_PRESS
	AND #PAD::DOWN
	BEQ @CHECK_RIGHT_PRESS
	LDX @VIRTUAL02
	LDA a:menu_option::text_x,X
	STA @LOCAL03
	LDA #0
	STA @LOCAL00
	LDA #SFX::CURSOR3
	STA @LOCAL00+2
	LDA @LOCAL03
	STA @LOCAL01
	LDA #.LOWORD(-1)
	STA @LOCAL02
	LDY #1
	LDX @VIRTUAL02
	LDA a:menu_option::text_y,X
	TAX
	LDA @LOCAL03
	JSL MOVE_CURSOR
	STA @LOCAL07
	JMP @PROCESS_CURSOR_MOVE
@CHECK_RIGHT_PRESS:
	LDA PAD_PRESS
	AND #PAD::RIGHT
	BEQ @CHECK_UP_HELD
	LDX @VIRTUAL02
	LDA a:menu_option::text_y,X
	STA @LOCAL04
	LDA #1
	STA @LOCAL00
	LDA #SFX::CURSOR2
	STA @LOCAL00+2
	LDA #.LOWORD(-1)
	STA @LOCAL01
	LDA @LOCAL04
	STA @LOCAL02
	LDY #0
	TAX
	STX @LOCAL03
	LDX @VIRTUAL02
	LDA a:menu_option::text_x,X
	LDX @LOCAL03
	JSL MOVE_CURSOR
	STA @LOCAL07
	JMP @PROCESS_CURSOR_MOVE
@CHECK_UP_HELD:
	LDA PAD_HELD
	AND #PAD::UP
	BEQ @CHECK_LEFT_HELD
	LDA #0
	STA @LOCAL00
	LDA #SFX::CURSOR3
	STA @LOCAL00+2
	LDY #.LOWORD(-1)
	LDX @VIRTUAL02
	LDA a:menu_option::text_y,X
	TAX
	STX @LOCAL07
	LDX @VIRTUAL02
	LDA a:menu_option::text_x,X
	LDX @LOCAL07
	JSL FIND_NEXT_MENU_OPTION
	STA @LOCAL07
	JMP @PROCESS_CURSOR_MOVE
@CHECK_LEFT_HELD:
	LDA PAD_HELD
	AND #PAD::LEFT
	BEQ @CHECK_DOWN_HELD
	LDA #.LOWORD(-1)
	STA @LOCAL00
	LDA #SFX::CURSOR2
	STA @LOCAL00+2
	LDY #0
	LDX @VIRTUAL02
	LDA a:menu_option::text_y,X
	TAX
	STX @LOCAL07
	LDX @VIRTUAL02
	LDA a:menu_option::text_x,X
	LDX @LOCAL07
	JSL FIND_NEXT_MENU_OPTION
	STA @LOCAL07
	JMP @PROCESS_CURSOR_MOVE
@CHECK_DOWN_HELD:
	LDA PAD_HELD
	AND #PAD::DOWN
	BEQ @CHECK_RIGHT_HELD
	LDA #0
	STA @LOCAL00
	LDA #SFX::CURSOR3
	STA @LOCAL00+2
	LDY #1
	LDX @VIRTUAL02
	LDA a:menu_option::text_y,X
	TAX
	STX @LOCAL07
	LDX @VIRTUAL02
	LDA a:menu_option::text_x,X
	LDX @LOCAL07
	JSL FIND_NEXT_MENU_OPTION
	STA @LOCAL07
	JMP @PROCESS_CURSOR_MOVE
@CHECK_RIGHT_HELD:
	LDA PAD_HELD
	AND #PAD::RIGHT
	BEQ @CHECK_CONFIRM
	LDA #1
	STA @LOCAL00
	LDA #SFX::CURSOR2
	STA @LOCAL00+2
	LDY #0
	LDX @VIRTUAL02
	LDA a:menu_option::text_y,X
	TAX
	STX @LOCAL03
	LDX @VIRTUAL02
	LDA a:menu_option::text_x,X
	LDX @LOCAL03
	JSL FIND_NEXT_MENU_OPTION
	STA @LOCAL07
	JMP @PROCESS_CURSOR_MOVE
@CHECK_CONFIRM:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON | PAD::L_BUTTON
	BEQL @CHECK_CANCEL
	JSR SET_INSTANT_PRINTING
	LDX @VIRTUAL02
	LDA a:menu_option::page,X
	BEQ @HANDLE_PAGINATION
	LDX @VIRTUAL02
	LDA a:menu_option::sound_effect,X
	AND #$00FF
	JSL PLAY_SOUND
	LDX @VIRTUAL02
	LDA a:menu_option::text_y,X
	TAX
	STX @LOCAL07
	LDX @VIRTUAL02
	LDA a:menu_option::text_x,X
	LDX @LOCAL07
	JSR SET_FOCUS_TEXT_CURSOR
	LDA #47
	JSR SET_TILE_ATTRIBUTE_AND_REDRAW
	LDA #6
	JSR SET_WINDOW_PALETTE_INDEX
	LDA @VIRTUAL02
	CLC
	ADC #menu_option::label
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #.LOWORD(-1)
	JSR PRINT_STRING
	LDA #0
	JSR SET_WINDOW_PALETTE_INDEX
	JSR CLEAR_INSTANT_PRINTING
	LDA @LOCAL08
	LDY #window_stats::selected_option
	STA (@LOCAL0A),Y
	LDX @VIRTUAL02
	LDA a:menu_option::unknown0,X
	CMP #1
	BNE @RETURN_USERDATA
	LDA @LOCAL08
	INC
	JMP @RETURN
@RETURN_USERDATA:
	LDX @VIRTUAL02
	LDA a:menu_option::userdata,X
	JMP @RETURN
@HANDLE_PAGINATION:
	LDA #SFX::CURSOR2
	JSL PLAY_SOUND
	JSR CLEAR_FOCUS_WINDOW_CONTENT
	LDA @LOCAL0A
	CLC
	ADC #window_stats::menu_page_number
	TAX
	STX @LOCAL05
	LDA __BSS_START__,X
	STA @LOCAL09
	LDX @VIRTUAL02
	LDA a:menu_option::previous,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	TAX
	LDA @LOCAL09
	CMP MENU_OPTIONS + menu_option::page,X
	BNE @PAGE_INCREMENT
	LDA #1
	LDX @LOCAL05
	STA __BSS_START__,X
	BRA @AFTER_PAGE_UPDATE
@PAGE_INCREMENT:
	INC
	LDX @LOCAL05
	STA __BSS_START__,X
@AFTER_PAGE_UPDATE:
	JSR PRINT_MENU_ITEMS
	JMP @SETUP_CURRENT_OPTION
@CHECK_CANCEL:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON
	BEQ @NO_CANCEL
	LDA @LOCAL0C
	CMP #1
	BNE @NO_CANCEL
	LDA #SFX::CURSOR2
	JSL PLAY_SOUND
	LDA #0
	JMP @RETURN
@NO_CANCEL:
	INC @LOCAL09
	LDA OPEN_WINDOW_TABLE
	CMP WINDOW_TAIL
	BNE @INCREMENT_FRAME
	LDA @LOCAL09
	CMP #60
	BLTEQ @INCREMENT_FRAME
	JSR SHOW_HPPP_AND_MONEY_WINDOWS
@AFTER_SHOW_MONEY:
	LDA #0
	JSR SET_WINDOW_FOCUS
	JMP @SETUP_CURRENT_OPTION
@INCREMENT_FRAME:
	LDX @LOCAL04
	INX
	STX @LOCAL04
@FRAME_WAIT_CHECK:
	CPX #10
	BCCL @INPUT_TICK
	JMP @CURSOR_BLINK_LOOP
@PROCESS_CURSOR_MOVE:
	CMP #.LOWORD(-1)
	BEQL @SETUP_CURRENT_OPTION
	LDY #0
	STY @LOCAL04
	LDY #window_stats::current_option
	LDA (@LOCAL0A),Y
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	STA @LOCAL09
	LDA @LOCAL07
	AND #$00FF
	TAX
	LDA @LOCAL07
	AND #$FF00
	XBA
	AND #$00FF
	STA @LOCAL07
	BRA @FIND_OPTION_CHECK
@FIND_OPTION_NEXT:
	LDY @LOCAL04
	INY
	STY @LOCAL04
	LDY #menu_option::next
	LDA (@LOCAL09),Y
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(menu_option)
	CLC
	ADC #.LOWORD(MENU_OPTIONS)
	STA @LOCAL09
@FIND_OPTION_CHECK:
	LDY #menu_option::text_x
	TXA
	CMP (@LOCAL09),Y
	BNE @FIND_OPTION_NEXT
	LDY #menu_option::text_y
	LDA @LOCAL07
	CMP (@LOCAL09),Y
	BNE @FIND_OPTION_NEXT
	LDY #menu_option::page
	LDA (@LOCAL09),Y
	STA @VIRTUAL04
	LDY #window_stats::menu_page_number
	LDA @VIRTUAL04
	CMP (@LOCAL0A),Y
	BEQ @OPTION_FOUND
	LDA @VIRTUAL04
	BNE @FIND_OPTION_NEXT
@OPTION_FOUND:
	LDX @VIRTUAL02
	LDA a:menu_option::text_y,X
	TAX
	STX @LOCAL07
	LDX @VIRTUAL02
	LDA a:menu_option::text_x,X
	LDX @LOCAL07
	JSR SET_FOCUS_TEXT_CURSOR
	LDA #47
	JSR SET_TILE_ATTRIBUTE_AND_REDRAW
	LDY @LOCAL04
	STY @LOCAL08
	LDA @LOCAL09
	STA @VIRTUAL02
	JMP @SETUP_CURRENT_OPTION
@RETURN:
	END_C_FUNCTION
