
SET_TEXT_PIXEL_POSITION:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL00
	SEP #PROC_FLAGS::ACCUM8
	AND #$0007
	STA NEW_TEXT_PIXEL_OFFSET
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL00
	LSR
	LSR
	LSR
	JSL SET_TEXT_CURSOR_WITH_PIXEL_OFFSET
	END_C_FUNCTION
