
SET_HPPP_WINDOW_MODE_ITEM:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
.IF .DEFINED(JPN)
	STACK_RESERVE_INT16
.ENDIF
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL04
.IF .DEFINED(JPN)
	STA @LOCAL03
.ENDIF
	LDY #$0000
	STY @LOCAL02
	JMP @CHARACTER_LOOP_CHECK
@PROCESS_CHARACTER:
.IF .DEFINED(JPN)
	LDA @LOCAL03
	STA @VIRTUAL04
.ENDIF
	LDX @VIRTUAL04
	TYA
	INC
	JSL CHECK_ITEM_USABLE_BY
	CMP #$0000
	BNE @ITEM_USABLE
	LDA #$0C00
	STA @LOCAL01
	JMP @STORE_WINDOW_MODE
@ITEM_USABLE:
	LDA @VIRTUAL04
	JSR GET_ITEM_TYPE
	CMP #$0002
	BEQ @ITEM_EQUIPPABLE
	LDA #$0400
	STA @LOCAL01
	JMP @STORE_WINDOW_MODE
@ITEM_EQUIPPABLE:
	LDA @VIRTUAL04
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::type
	TAX
	LDA f:ITEM_CONFIGURATION_TABLE,X
	AND #$00FF
	AND #$000C
	BEQ @SLOT_WEAPON
	CMP #$0004
	BEQ @SLOT_BODY
	CMP #$0008
	BEQ @SLOT_ARMS
	CMP #$000C
	BEQ @SLOT_OTHER
	BRA @COMPARE_STATS
@SLOT_WEAPON:
	LDY @LOCAL02
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::WEAPON,X
	AND #$00FF
	STA @VIRTUAL02
	STA @LOCAL00
	BRA @COMPARE_STATS
@SLOT_BODY:
	LDY @LOCAL02
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::BODY,X
	AND #$00FF
	STA @VIRTUAL02
	STA @LOCAL00
	BRA @COMPARE_STATS
@SLOT_ARMS:
	LDY @LOCAL02
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::ARMS,X
	AND #$00FF
	STA @VIRTUAL02
	STA @LOCAL00
	BRA @COMPARE_STATS
@SLOT_OTHER:
	LDY @LOCAL02
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA PARTY_CHARACTERS+char_struct::equipment+EQUIPMENT_SLOT::OTHER,X
	AND #$00FF
	STA @VIRTUAL02
	STA @LOCAL00
@COMPARE_STATS:
	LDA @LOCAL00
	STA @VIRTUAL02
	BEQ @NO_EQUIPMENT
	LDX #$0000
	STX @LOCAL01
	LDY @LOCAL02
	CPY #$0003
	BNE @NOT_POO
	LDX #$0001
	STX @LOCAL01
@NOT_POO:
	LDA @VIRTUAL02
	DEC
.IF .DEFINED(JPN)
	STA @VIRTUAL04
.ELSE
	STA @VIRTUAL02
.ENDIF
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	CLC
.IF .DEFINED(JPN)
	ADC @VIRTUAL04
.ELSE
	ADC @VIRTUAL02
.ENDIF
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	LDX @LOCAL01
	STX @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	BRA @COMPARE_NEW_ITEM
@NO_EQUIPMENT:
	LDA #$0000
@COMPARE_NEW_ITEM:
	LDX #$0000
	LDY @LOCAL02
	CPY #$0003
	BNE @NOT_POO_NEW
	LDX #$0001
@NOT_POO_NEW:
	PHA
	STX @VIRTUAL02
.IF .DEFINED(JPN)
	LDA @LOCAL03
	STA @VIRTUAL04
.ELSE
	LDA @VIRTUAL04
.ENDIF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #item::params + item_parameters::strength
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA f:ITEM_CONFIGURATION_TABLE,X
	REP #PROC_FLAGS::ACCUM8
	SEC
	AND #$00FF
	SBC #$0080
	EOR #$FF80
	PLY
	STY @VIRTUAL02
	CLC
	SBC @VIRTUAL02
	BRANCHLTEQS @STAT_NOT_BETTER
	LDX #$1400
	BRA @SET_WINDOW_MODE
@STAT_NOT_BETTER:
	LDX #$0400
@SET_WINDOW_MODE:
	TXA
	STA @LOCAL01
@STORE_WINDOW_MODE:
	LDY @LOCAL02
	TYA
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA @LOCAL01
	STA PARTY_CHARACTERS+char_struct::hp_pp_window_options,X
	LDY @LOCAL02
	INY
	STY @LOCAL02
@CHARACTER_LOOP_CHECK:
	CPY #PLAYER_CHAR_COUNT
	BCCL @PROCESS_CHARACTER
	LDA #$0001
	STA REDRAW_ALL_WINDOWS
	END_C_FUNCTION
