
SET_FOCUS_TEXT_CURSOR:
.IF .DEFINED(JPN)
	BEGIN_C_FUNCTION
.ELSE
	BEGIN_C_FUNCTION_FAR
.ENDIF
	END_STACK_VARS
	TXY
	TAX
	LDA CURRENT_FOCUS_WINDOW
.IF .DEFINED(JPN)
	JSR SET_WINDOW_TEXT_POSITION
.ELSE
	JSL SET_WINDOW_TEXT_POSITION
.ENDIF
	END_C_FUNCTION
