
SET_TILE_ATTRIBUTE_AND_REDRAW:
	BEGIN_C_FUNCTION
	END_STACK_VARS
	JSR SET_WINDOW_TILE_ATTRIBUTE
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	CMP WINDOW_TAIL
	BEQ @SKIP_REDRAW
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA REDRAW_ALL_WINDOWS
@SKIP_REDRAW:
	REP #PROC_FLAGS::ACCUM8
	END_C_FUNCTION
