
SHOW_FILE_COPY_DIALOG:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDX #0
	TXY
	BRA @SLOT_COUNT_LOOP_CHECK
@COUNT_EMPTY_SLOT:
	LDA SAVE_FILES_PRESENT,X
	AND #$00FF
	BNE @NEXT_SLOT
	INY
@NEXT_SLOT:
	INX
@SLOT_COUNT_LOOP_CHECK:
	STX @VIRTUAL02
	LDA #3
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @COUNT_EMPTY_SLOT
	CPY #1
	BNEL @TWO_FILES_CASE
	CREATE_WINDOW_NEAR #WINDOW::FILE_SELECT_COPY_MENU_ONE_FILE
	JSL SET_INSTANT_PRINTING
	LOADPTR FILE_SELECT_TEXT_COPY_TO_WHERE, @LOCAL00
	LDA #14
	JSR PRINT_STRING
	LDA #0
	STA @VIRTUAL02
	BRA @ONE_FILE_LOOP_CHECK
@ADD_ONE_FILE_SLOT:
	LDX @VIRTUAL02
	LDA SAVE_FILES_PRESENT,X
	AND #$00FF
	BNE @NEXT_ONE_FILE_SLOT
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	CLC
	ADC #CHAR::ONE
	STA TEMPORARY_TEXT_BUFFER
	LDA #CHAR::COLON
	STA TEMPORARY_TEXT_BUFFER+1
	STZ TEMPORARY_TEXT_BUFFER+2
	REP #PROC_FLAGS::ACCUM8
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	LDY #1
	LDX #0
	LDA @VIRTUAL02
	INC
	JSR ADD_MENU_ITEM
@NEXT_ONE_FILE_SLOT:
	INC @VIRTUAL02
@ONE_FILE_LOOP_CHECK:
	LDA #3
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @ADD_ONE_FILE_SLOT
	JMP @SHOW_MENU
@TWO_FILES_CASE:
	CREATE_WINDOW_NEAR #WINDOW::FILE_SELECT_COPY_MENU_TWO_FILES
	JSL SET_INSTANT_PRINTING
	LOADPTR FILE_SELECT_TEXT_COPY_TO_WHERE, @LOCAL00
	LDA #14
	JSR PRINT_STRING
	LDA #0
	STA @VIRTUAL02
	LDA #1
	STA @VIRTUAL04
	BRA @TWO_FILE_LOOP_CHECK
@ADD_TWO_FILE_SLOT:
	LDX @VIRTUAL02
	LDA SAVE_FILES_PRESENT,X
	AND #$00FF
	BNE @NEXT_TWO_FILE_SLOT
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	CLC
	ADC #CHAR::ONE
	STA TEMPORARY_TEXT_BUFFER
	LDA #CHAR::COLON
	STA TEMPORARY_TEXT_BUFFER+1
	STZ TEMPORARY_TEXT_BUFFER+2
	LDX @VIRTUAL04
	REP #PROC_FLAGS::ACCUM8
	INC @VIRTUAL04
	PROMOTENEARPTR TEMPORARY_TEXT_BUFFER, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	MOVE_INT_CONSTANT NULL, @LOCAL01
	TXY
	LDX #0
	LDA @VIRTUAL02
	INC
	JSR ADD_MENU_ITEM
@NEXT_TWO_FILE_SLOT:
	INC @VIRTUAL02
@TWO_FILE_LOOP_CHECK:
	LDA #3
	CLC
	SBC @VIRTUAL02
	BRANCHGTS @ADD_TWO_FILE_SLOT
@SHOW_MENU:
	JSR PRINT_MENU_ITEMS
	LDA #1
	JSR SELECTION_MENU
	TAY
	STY @LOCAL02
	BEQ @AFTER_COPY
	LDA CURRENT_SAVE_SLOT
	AND #$00FF
	TAX
	DEX
	TYA
	DEC
	JSL COPY_SAVE
@AFTER_COPY:
	STZ ENABLE_WORD_WRAP
	JSR CLOSE_FOCUS_WINDOW
	LDY @LOCAL02
	TYA
	END_C_FUNCTION
