
SKIPPABLE_PAUSE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STA @LOCAL00
	BRA @CHECK_COUNTER
@LOOP_BODY:
	LDA PAD_PRESS
	BEQ @NO_BUTTON_PRESSED
	LDA #.LOWORD(-1)
	BRA @RETURN
@NO_BUTTON_PRESSED:
	JSL WAIT_UNTIL_NEXT_FRAME
	LDA @LOCAL00
	DEC
	STA @LOCAL00
@CHECK_COUNTER:
	BNE @LOOP_BODY
	LDA #0
@RETURN:
	END_C_FUNCTION
