
SPAWN_FLOATING_SPRITE:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16 ;int
	STACK_RESERVE_PARAM_INT16 ;int
	END_STACK_VARS
	TXY
	STA @VIRTUAL02
	CMP #.LOWORD(-1)
	BEQL @RETURN
	LDA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_SCRIPT_TABLE,X
	CMP #.LOWORD(-1)
	BEQL @RETURN
	LDA ENTITY_SIZES,X
	STA @LOCAL03
	LOADPTR FLOATING_SPRITE_TABLE, @VIRTUAL06
	TYA
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(floating_sprite)
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	LDA ENTITY_ABS_X_TABLE,X
	STA ACTIVE_MANPU_X
	LDA ENTITY_ABS_Y_TABLE,X
	STA ACTIVE_MANPU_Y
	LDA @LOCAL03
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDY #floating_sprite::position_mode
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	JSR UPDATE_FLOATING_SPRITE_OFFSET
	SEP #PROC_FLAGS::ACCUM8
	LDY #floating_sprite::x_offset
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	AND #$0080
	BEQ @SIGN_EXTEND_X_POSITIVE
	LDX #$FF00
	BRA @APPLY_X_OFFSET
@SIGN_EXTEND_X_POSITIVE:
	LDX #0
@APPLY_X_OFFSET:
	STX @VIRTUAL04
	SEP #PROC_FLAGS::ACCUM8
	LDY #floating_sprite::x_offset
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	ORA @VIRTUAL04
	CLC
	ADC ACTIVE_MANPU_X
	STA ACTIVE_MANPU_X
	SEP #PROC_FLAGS::ACCUM8
	LDY #floating_sprite::y_offset
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	AND #$0080
	BEQ @SIGN_EXTEND_Y_POSITIVE
	LDX #$FF00
	BRA @APPLY_Y_OFFSET
@SIGN_EXTEND_Y_POSITIVE:
	LDX #0
@APPLY_Y_OFFSET:
	STX @VIRTUAL04
	SEP #PROC_FLAGS::ACCUM8
	LDY #floating_sprite::y_offset
	LDA [@VIRTUAL06],Y
	REP #PROC_FLAGS::ACCUM8
	AND #$00FF
	ORA @VIRTUAL04
	CLC
	ADC ACTIVE_MANPU_Y
	STA @LOCAL02
	STA ACTIVE_MANPU_Y
	LDA ACTIVE_MANPU_X
	STA @LOCAL00
	LDA @LOCAL02
	STA @LOCAL01
	LDY #.LOWORD(-1)
	LDX #EVENT_SCRIPT::EVENT_785
	LDA [@VIRTUAL06] ;floating_sprite::sprite
	JSL CREATE_ENTITY
	ASL
	TAX
	STX @LOCAL02
	LDA @VIRTUAL02
	ORA #$C000
	STA ENTITY_DRAW_PRIORITY,X
	LDA @VIRTUAL02
	ASL
	TAX
	LDA ENTITY_SURFACE_FLAGS,X
	LDX @LOCAL02
	STA ENTITY_SURFACE_FLAGS,X
@RETURN:
	END_C_FUNCTION
