
TEXT_INPUT_DIALOG:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @LOCAL0F
	STX @LOCAL0E
	STA @LOCAL0D
	LDY @PARAM04
	STY @LOCAL0C
	LDX @PARAM03
	STX @LOCAL0B
	LDA #.LOWORD(-1)
	STA @LOCAL0A
	STZ @LOCAL09
	LDA @LOCAL09
	STA @LOCAL08
	LDA @LOCAL0B
	STA @LOCAL07
	JSL SET_INSTANT_PRINTING
	CREATE_WINDOW_NEAR #WINDOW::FILE_SELECT_NAMING_KEYBOARD
	LDA @LOCAL0C
	CMP #.LOWORD(-1)
	BNE @LAYOUT_WITH_DONTCARE
	MOVE_INT f:NAME_INPUT_WINDOW_SELECTION_LAYOUT_POINTERS+20, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
	BRA @LAYOUT_DONE
@LAYOUT_WITH_DONTCARE:
	MOVE_INT f:NAME_INPUT_WINDOW_SELECTION_LAYOUT_POINTERS+16, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
@LAYOUT_DONE:
	SEP #PROC_FLAGS::ACCUM8
	STZ CHARACTER_PADDING
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL0C
	CMP #.LOWORD(-1)
	BNE @LAYOUT_WITHOUT_DONTCARE
	LOADPTR NAME_INPUT_WINDOW_SELECTION_LAYOUT_POINTERS, @VIRTUAL0A
	LDA @LOCAL0B
	ASL
	ASL
	CLC
	ADC #8
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
	BRA @INIT_CHAR_PADDING
@LAYOUT_WITHOUT_DONTCARE:
	LOADPTR NAME_INPUT_WINDOW_SELECTION_LAYOUT_POINTERS, @VIRTUAL0A
	LDA @LOCAL0B
	ASL
	ASL
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
@INIT_CHAR_PADDING:
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA CHARACTER_PADDING
@REDRAW_KEYBOARD:
	JSL SET_INSTANT_PRINTING
	LDA @LOCAL07
	CMP @LOCAL0B
	BEQL @GET_WINDOW_STATS
	.A16
	CREATE_WINDOW_NEAR #WINDOW::FILE_SELECT_NAMING_KEYBOARD
	JSL WINDOW_TICK_WITHOUT_INSTANT_PRINTING
	.A16
	LDA @LOCAL0C
	CMP #.LOWORD(-1)
	BNE @REDRAW_LAYOUT_WITH_DONTCARE
	MOVE_INT f:NAME_INPUT_WINDOW_SELECTION_LAYOUT_POINTERS+20, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
	BRA @REDRAW_LAYOUT_DONE
@REDRAW_LAYOUT_WITH_DONTCARE:
	MOVE_INT f:NAME_INPUT_WINDOW_SELECTION_LAYOUT_POINTERS+16, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
@REDRAW_LAYOUT_DONE:
	LDA @LOCAL0B
	STA @LOCAL07
	SEP #PROC_FLAGS::ACCUM8
	STZ CHARACTER_PADDING
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL0C
	CMP #.LOWORD(-1)
	BNE @REDRAW_LAYOUT_WITHOUT_DONTCARE
	LOADPTR NAME_INPUT_WINDOW_SELECTION_LAYOUT_POINTERS, @VIRTUAL0A
	LDA @LOCAL0B
	OPTIMIZED_MULT @VIRTUAL04, 4
	CLC
	ADC #8
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
	BRA @REDRAW_SET_PADDING
@REDRAW_LAYOUT_WITHOUT_DONTCARE:
	LOADPTR NAME_INPUT_WINDOW_SELECTION_LAYOUT_POINTERS, @VIRTUAL0A
	LDA @LOCAL0B
	OPTIMIZED_MULT @VIRTUAL04, 4
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
@REDRAW_SET_PADDING:
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA CHARACTER_PADDING
@GET_WINDOW_STATS:
	REP #PROC_FLAGS::ACCUM8
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	STA @LOCAL06
@RENDER_CURSOR:
	JSL CLEAR_INSTANT_PRINTING
	LDX @LOCAL09
	LDA @LOCAL08
	JSL SET_FOCUS_TEXT_CURSOR
	LDA #1
	JSR SET_WINDOW_PALETTE_INDEX
	LDA #33
	JSR SET_TILE_ATTRIBUTE_AND_REDRAW
	LDA #0
	JSR SET_WINDOW_PALETTE_INDEX
	JSL WINDOW_TICK
	LDA #1
	STA @VIRTUAL04
@CURSOR_BLINK:
	LDA @VIRTUAL04
	EOR #$0001
	STA @VIRTUAL04
	LDY #window_stats::text_y
	LDA (@LOCAL06),Y
	ASL
	LDY #window_stats::window_y
	CLC
	ADC (@LOCAL06),Y
	OPTIMIZED_MULT @VIRTUAL04, 32
	STA @VIRTUAL02
	LDY #window_stats::window_x
	LDA (@LOCAL06),Y
	LDY #window_stats::text_x
	CLC
	ADC (@LOCAL06),Y
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #VRAM::TEXT_LAYER_TILEMAP + TILEMAP_COORDS 0, 1
	STA @LOCAL05
	LDA @VIRTUAL04
	ASL
	STA @VIRTUAL02
	LOADPTR CURSOR_BLINK_UPPER_TILES, @VIRTUAL06
	LDA @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDY @LOCAL05
	LDX #2
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	.A16
	LOADPTR CURSOR_BLINK_LOWER_TILES, @VIRTUAL06
	LDA @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA @LOCAL05
	CLC
	ADC #32
	TAY
	LDX #2
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	.A16
	LDX #0
	STX @LOCAL04
	JMP @CHECK_FRAME_COUNTER
@PROCESS_INPUT:
	JSL RENDER_FRAME_TICK
	LDA PAD_PRESS
	AND #PAD::UP
	BEQ @CHECK_PAD_LEFT
	STZ @LOCAL00
	LDA #SFX::NAMING_CURSOR_VERTICAL
	STA @LOCAL00+2
	LDA @LOCAL08
	STA @LOCAL01
	LDY #window_stats::height
	LDA (@LOCAL06),Y
	LSR
	STA @LOCAL02
	LDY #.LOWORD(-1)
	LDX @LOCAL09
	LDA @LOCAL08
	JSL MOVE_CURSOR
	TAY
	STY @LOCAL03
	JMP @UPDATE_CURSOR_POSITION
@CHECK_PAD_LEFT:
	LDA PAD_PRESS
	AND #PAD::LEFT
	BEQ @CHECK_PAD_DOWN
	LDA #.LOWORD(-1)
	STA @LOCAL00
	LDA #$007B
	STA @LOCAL00+2
	LDY #window_stats::width
	LDA (@LOCAL06),Y
	STA @LOCAL01
	LDA @LOCAL09
	STA @LOCAL02
	LDY #0
	LDX @LOCAL09
	LDA @LOCAL08
	JSL MOVE_CURSOR
	TAY
	STY @LOCAL03
	JMP @UPDATE_CURSOR_POSITION
@CHECK_PAD_DOWN:
	LDA PAD_PRESS
	AND #PAD::DOWN
	BEQ @CHECK_PAD_RIGHT
	STZ @LOCAL00
	LDA #SFX::NAMING_CURSOR_VERTICAL
	STA @LOCAL00+2
	LDA @LOCAL08
	STA @LOCAL01
	LDA #.LOWORD(-1)
	STA @LOCAL02
	LDY #1
	LDX @LOCAL09
	LDA @LOCAL08
	JSL MOVE_CURSOR
	TAY
	STY @LOCAL03
	JMP @UPDATE_CURSOR_POSITION
@CHECK_PAD_RIGHT:
	LDA PAD_PRESS
	AND #PAD::RIGHT
	BEQ @CHECK_HELD_UP
	LDA #1
	STA @LOCAL00
	LDA #$007B
	STA @LOCAL00+2
	LDA #.LOWORD(-1)
	STA @LOCAL01
	LDA @LOCAL09
	STA @LOCAL02
	LDY #0
	LDX @LOCAL09
	LDA @LOCAL08
	JSL MOVE_CURSOR
	TAY
	STY @LOCAL03
	JMP @UPDATE_CURSOR_POSITION
@CHECK_HELD_UP:
	LDA PAD_HELD
	AND #PAD::UP
	BEQ @CHECK_HELD_DOWN
	STZ @LOCAL00
	LDA #SFX::NAMING_CURSOR_VERTICAL
	STA @LOCAL00+2
	LDY #.LOWORD(-1)
	LDX @LOCAL09
	LDA @LOCAL08
	JSL FIND_NEXT_MENU_OPTION
	TAY
	STY @LOCAL03
	JMP @UPDATE_CURSOR_POSITION
@CHECK_HELD_DOWN:
	LDA PAD_HELD
	AND #PAD::DOWN
	BEQ @CHECK_HELD_LEFT
	STZ @LOCAL00
	LDA #SFX::NAMING_CURSOR_VERTICAL
	STA @LOCAL00+2
	LDY #1
	LDX @LOCAL09
	LDA @LOCAL08
	JSL FIND_NEXT_MENU_OPTION
	TAY
	STY @LOCAL03
	JMP @UPDATE_CURSOR_POSITION
@CHECK_HELD_LEFT:
	LDA PAD_HELD
	AND #PAD::LEFT
	BEQ @CHECK_HELD_RIGHT
	LDA #.LOWORD(-1)
	STA @LOCAL00
	LDA #$007B
	STA @LOCAL00+2
	LDY #0
	LDX @LOCAL09
	LDA @LOCAL08
	JSL FIND_NEXT_MENU_OPTION
	TAY
	STY @LOCAL03
	JMP @UPDATE_CURSOR_POSITION
@CHECK_HELD_RIGHT:
	LDA PAD_HELD
	AND #PAD::RIGHT
	BEQ @CHECK_A_L_BUTTON
	LDA #1
	STA @LOCAL00
	LDA #$007B
	STA @LOCAL00+2
	LDY #0
	LDX @LOCAL09
	LDA @LOCAL08
	JSL FIND_NEXT_MENU_OPTION
	TAY
	STY @LOCAL03
	JMP @UPDATE_CURSOR_POSITION
@CHECK_A_L_BUTTON:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON | PAD::L_BUTTON
	BEQL @CHECK_B_SELECT
	LDA @LOCAL09
	CMP #6
	BNE @SELECTION_NOT_IN_LINE_6
	LDA @LOCAL08
	BEQ @DONTCARE_SELECTED
	CMP #17
	BEQ @BACKSPACE_SELECTED
	CMP #25
	BEQ @OK_SELECTED
	JMP @ADVANCE_FRAME_COUNTER
@DONTCARE_SELECTED:
	LDA #SFX::TEXT_INPUT
	JSL PLAY_SOUND
	LDY @LOCAL0A
	LDX @LOCAL0C
	LDA @LOCAL0D
	JSR RENDER_DONT_CARE_NAME
	STA @LOCAL0A
	JMP @RENDER_CURSOR
@BACKSPACE_SELECTED:
	LDA #SFX::TEXT_INPUT
	JSL PLAY_SOUND
	LDY #.LOWORD(-1)
	LDX @LOCAL0E
	LDA @LOCAL0D
	JSR RENDER_NAMING_CHARACTER
	CMP #0
	BEQL @RENDER_CURSOR
	LDA @LOCAL0C
	CMP #.LOWORD(-1)
	BEQL @RENDER_CURSOR
	LDA #1
	JMP @RETURN
@OK_SELECTED:
	LDA #SFX::NAMING_CONFIRM
	JSL PLAY_SOUND
	JMP @CONFIRM_NAME
@SELECTION_NOT_IN_LINE_6:
	LDA #SFX::TEXT_INPUT
	JSL PLAY_SOUND
	LDA @LOCAL09
	CMP #4
	BNE @SELECT_GRID_CHAR
	LDA @LOCAL08
	BEQ @SELECT_CAPITAL
	CMP #7
	BEQ @SELECT_SMALL
	BRA @SELECT_GRID_CHAR
@SELECT_CAPITAL:
	STZ @LOCAL0B
	JMP @REDRAW_KEYBOARD
@SELECT_SMALL:
	LDA #1
	STA @LOCAL0B
	JMP @REDRAW_KEYBOARD
@SELECT_GRID_CHAR:
	LDY @LOCAL0B
	LDX @LOCAL09
	LDA @LOCAL08
	LSR
	JSL GET_CHARACTER_AT_CURSOR_POSITION
	TAY
	LDX @LOCAL0E
	LDA @LOCAL0D
	JSR RENDER_NAMING_CHARACTER
	JMP @RENDER_CURSOR
@CHECK_B_SELECT:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON
	BEQ @CHECK_START
	LDA #SFX::NAMING_BACKSPACE
	JSL PLAY_SOUND
	LDY #.LOWORD(-1)
	LDX @LOCAL0E
	LDA @LOCAL0D
	JSR RENDER_NAMING_CHARACTER
	CMP #0
	BEQL @RENDER_CURSOR
	LDA @LOCAL0C
	CMP #.LOWORD(-1)
	BEQL @RENDER_CURSOR
	LDA #1
	JMP @RETURN
@CHECK_START:
	LDA PAD_PRESS
	AND #PAD::START_BUTTON
	BEQ @ADVANCE_FRAME_COUNTER
	LDA #SFX::NAMING_CONFIRM_ALT
	JSL PLAY_SOUND
	BRA @CONFIRM_NAME
@ADVANCE_FRAME_COUNTER:
	LDX @LOCAL04
	INX
	STX @LOCAL04
@CHECK_FRAME_COUNTER:
	STX @VIRTUAL02
	LDA #10
	CLC
	SBC @VIRTUAL02
	JUMPGTS @PROCESS_INPUT
	JMP @CURSOR_BLINK
@UPDATE_CURSOR_POSITION:
	LDX @LOCAL09
	LDA @LOCAL08
	JSL SET_FOCUS_TEXT_CURSOR
	LDA #47
	JSR SET_TILE_ATTRIBUTE_AND_REDRAW
	LDY @LOCAL03
	CPY #.LOWORD(-1)
	BEQL @RENDER_CURSOR
	TYA
	AND #$00FF
	STA @LOCAL08
	TYA
	AND #$FF00
	XBA
	AND #$00FF
	STA @LOCAL09
	JMP @RENDER_CURSOR
@CONFIRM_NAME:
	PROMOTENEARPTR $1B86, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL STRLEN
	CMP #0
	BEQL @RENDER_CURSOR
	LDA @LOCAL0D
	JSR SET_WINDOW_FOCUS
	LDX #0
	BRA @COPY_LOOP
@COPY_CHAR:
	SEP #PROC_FLAGS::ACCUM8
	STA (@LOCAL0F)
	REP #PROC_FLAGS::ACCUM8
	INC @LOCAL0F
	INX
@COPY_LOOP:
	LDA KEYBOARD_INPUT_CHARACTERS,X
	AND #$00FF
	BEQ @PAD_LOOP
	CPX @LOCAL0E
	BCC @COPY_CHAR
	BRA @PAD_LOOP
@PAD_NULL:
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA (@LOCAL0F)
	REP #PROC_FLAGS::ACCUM8
	INC @LOCAL0F
	INX
@PAD_LOOP:
	CPX @LOCAL0E
	BCC @PAD_NULL
	LDA #0
@RETURN:
	END_C_FUNCTION
