
TEXT_SPEED_DELAY:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	TAX
	LDA DEBUG
	BEQ @CHECK_PROMPT
	LDA BATTLE_MODE
	BNE @CHECK_PROMPT
	BRA @DEBUG_SKIP_CHECK
@DEBUG_SKIP_LOOP:
	JSL UPDATE_HPPP_METER_AND_RENDER
@DEBUG_SKIP_CHECK:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON | PAD::A_BUTTON | PAD::L_BUTTON
	BEQ @DEBUG_SKIP_LOOP
	BRA @DONE
@CHECK_DEBUG_COMBO:
	LDA DEBUG
	BEQ @CHECK_PROMPT
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::R_BUTTON
	CMP #PAD::B_BUTTON | PAD::R_BUTTON
	BNE @CHECK_PROMPT
	STZ TEXT_PROMPT_WAITING_FOR_INPUT
	BRA @GET_DELAY
@CHECK_PROMPT:
	LDA TEXT_PROMPT_WAITING_FOR_INPUT
	BNE @CHECK_DEBUG_COMBO
@GET_DELAY:
	CPX #0
	BEQ @USE_DEFAULT_SPEED
	TXA
	BRA @SET_COUNTER
@USE_DEFAULT_SPEED:
	LDA TEXT_SPEED_BASED_WAIT
@SET_COUNTER:
	TAX
	STX @LOCAL00
	BRA @DELAY_CHECK
@DELAY_LOOP:
	JSL UPDATE_HPPP_METER_AND_RENDER
@DELAY_CHECK:
	LDX @LOCAL00
	TXA
	DEX
	STX @LOCAL00
	CMP #0
	BEQ @DONE
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON | PAD::A_BUTTON | PAD::L_BUTTON
	BEQ @DELAY_LOOP
@DONE:
	END_C_FUNCTION
