
TEXT_INPUT_DIALOG:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STY @LOCAL0D
	STX @LOCAL0C
	STA @LOCAL0B
	LDX @PARAM04
	STX @LOCAL0A
	LDY @PARAM03
	TYX
	STX @LOCAL09
	LDA #.LOWORD(-1)
	STA @LOCAL08
	LDA #0
	STA @VIRTUAL04
	STA @LOCAL07
@OPEN_KEYBOARD:
	JSR SET_INSTANT_PRINTING
	CREATE_WINDOW_NEAR #WINDOW::FILE_SELECT_NAMING_KEYBOARD
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(window_stats)
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	STA @LOCAL06
	LDA @LOCAL0A
	CMP #.LOWORD(-1)
	BNE @HAS_DONT_CARE
	LOADPTR NAME_INPUT_WINDOW_SELECTION_LAYOUT_POINTERS, @VIRTUAL0A
	LDX @LOCAL09
	TXA
	OPTIMIZED_MULT @VIRTUAL04, 4
	CLC
	ADC #4 * 3
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
	BRA @RENDER_SWITCH_ARROWS
@HAS_DONT_CARE:
	LOADPTR NAME_INPUT_WINDOW_SELECTION_LAYOUT_POINTERS, @VIRTUAL0A
	LDX @LOCAL09
	TXA
	OPTIMIZED_MULT @VIRTUAL04, 4
	CLC
	ADC @VIRTUAL0A
	STA @VIRTUAL0A
	DEREFERENCE_PTR_TO @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSL DISPLAY_TEXT
@RENDER_SWITCH_ARROWS:
	LDX #3
	LDA #25
	JSR SET_FOCUS_TEXT_CURSOR
	LDA #$001A
	JSR PRINT_LETTER
	LDX #4
	LDA #25
	JSR SET_FOCUS_TEXT_CURSOR
	LDA #$001B
	JSR PRINT_LETTER
@CURSOR_SETUP:
	JSR CLEAR_INSTANT_PRINTING
	LDX @VIRTUAL04
	LDA @LOCAL07
	JSR SET_FOCUS_TEXT_CURSOR
	LDA #1
	JSR SET_WINDOW_PALETTE_INDEX
	LDA #33
	JSR SET_TILE_ATTRIBUTE_AND_REDRAW
	LDA #0
	JSR SET_WINDOW_PALETTE_INDEX
	JSL WINDOW_TICK
	LDA #1
	STA @LOCAL05
@CURSOR_BLINK_LOOP:
	LDA @LOCAL05
	EOR #$0001
	STA @LOCAL05
	LDY #window_stats::text_y
	LDA (@LOCAL06),Y
	ASL
	LDY #window_stats::window_y
	CLC
	ADC (@LOCAL06),Y
	OPTIMIZED_MULT @VIRTUAL04, 32
	STA @VIRTUAL02
	LDY #window_stats::window_x
	LDA (@LOCAL06),Y
	LDY #window_stats::text_x
	CLC
	ADC (@LOCAL06),Y
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #VRAM::TEXT_LAYER_TILEMAP + TILEMAP_COORDS 0, 1
	STA @LOCAL09
	LDA @LOCAL05
	ASL
	STA @VIRTUAL02
	LOADPTR CURSOR_BLINK_UPPER_TILES, @VIRTUAL06
	LDA @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDY @LOCAL09
	LDX #2
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	.A16
	LOADPTR CURSOR_BLINK_LOWER_TILES, @VIRTUAL06
	LDA @VIRTUAL02
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA @LOCAL00
	LDA @VIRTUAL06+2
	STA @LOCAL00+2
	LDA @LOCAL09
	CLC
	ADC #32
	TAY
	LDX #2
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	.A16
	LDX #0
	STX @LOCAL04
	JMP @FRAME_WAIT_CHECK
@INPUT_TICK:
	JSL RENDER_FRAME_TICK
	LDA PAD_PRESS
	AND #PAD::UP
	BEQ @CHECK_LEFT_PRESS
	LDA #0
	STA @LOCAL00
	LDA #$007C
	STA @LOCAL00+2
	LDA @LOCAL07
	STA @LOCAL01
	LDY #window_stats::height
	LDA (@LOCAL06),Y
	LSR
	STA @LOCAL02
	LDY #.LOWORD(-1)
	LDX @VIRTUAL04
	LDA @LOCAL07
	JSL MOVE_CURSOR
	TAY
	STY @LOCAL03
	JMP @PROCESS_CURSOR_MOVE
@CHECK_LEFT_PRESS:
	LDA PAD_PRESS
	AND #PAD::LEFT
	BEQ @CHECK_DOWN_PRESS
	LDA #.LOWORD(-1)
	STA @LOCAL00
	LDA #$007B
	STA @LOCAL00+2
	LDY #window_stats::width
	LDA (@LOCAL06),Y
	STA @LOCAL01
	LDA @VIRTUAL04
	STA @LOCAL02
	LDY #0
	LDX @VIRTUAL04
	LDA @LOCAL07
	JSL MOVE_CURSOR
	TAY
	STY @LOCAL03
	JMP @PROCESS_CURSOR_MOVE
@CHECK_DOWN_PRESS:
	LDA PAD_PRESS
	AND #PAD::DOWN
	BEQ @CHECK_RIGHT_PRESS
	LDA #0
	STA @LOCAL00
	LDA #$007C
	STA @LOCAL00+2
	LDA @LOCAL07
	STA @LOCAL01
	LDA #.LOWORD(-1)
	STA @LOCAL02
	LDY #1
	LDX @VIRTUAL04
	LDA @LOCAL07
	JSL MOVE_CURSOR
	TAY
	STY @LOCAL03
	JMP @PROCESS_CURSOR_MOVE
@CHECK_RIGHT_PRESS:
	LDA PAD_PRESS
	AND #PAD::RIGHT
	BEQ @CHECK_UP_HELD
	LDA #1
	STA @LOCAL00
	LDA #$007B
	STA @LOCAL00+2
	LDA #.LOWORD(-1)
	STA @LOCAL01
	LDA @VIRTUAL04
	STA @LOCAL02
	LDY #0
	LDX @VIRTUAL04
	LDA @LOCAL07
	JSL MOVE_CURSOR
	TAY
	STY @LOCAL03
	JMP @PROCESS_CURSOR_MOVE
@CHECK_UP_HELD:
	LDA PAD_HELD
	AND #PAD::UP
	BEQ @CHECK_DOWN_HELD
	LDA #0
	STA @LOCAL00
	LDA #$007C
	STA @LOCAL00+2
	LDY #.LOWORD(-1)
	LDX @VIRTUAL04
	LDA @LOCAL07
	JSL FIND_NEXT_MENU_OPTION
	TAY
	STY @LOCAL03
	JMP @PROCESS_CURSOR_MOVE
@CHECK_DOWN_HELD:
	LDA PAD_HELD
	AND #PAD::DOWN
	BEQ @CHECK_LEFT_HELD
	LDA #0
	STA @LOCAL00
	LDA #$007C
	STA @LOCAL00+2
	LDY #1
	LDX @VIRTUAL04
	LDA @LOCAL07
	JSL FIND_NEXT_MENU_OPTION
	TAY
	STY @LOCAL03
	JMP @PROCESS_CURSOR_MOVE
@CHECK_LEFT_HELD:
	LDA PAD_HELD
	AND #PAD::LEFT
	BEQ @CHECK_RIGHT_HELD
	LDA #.LOWORD(-1)
	STA @LOCAL00
	LDA #$007B
	STA @LOCAL00+2
	LDY #0
	LDX @VIRTUAL04
	LDA @LOCAL07
	JSL FIND_NEXT_MENU_OPTION
	TAY
	STY @LOCAL03
	JMP @PROCESS_CURSOR_MOVE
@CHECK_RIGHT_HELD:
	LDA PAD_HELD
	AND #PAD::RIGHT
	BEQ @CHECK_CONFIRM
	LDA #1
	STA @LOCAL00
	LDA #$007B
	STA @LOCAL00+2
	LDY #0
	LDX @VIRTUAL04
	LDA @LOCAL07
	JSL FIND_NEXT_MENU_OPTION
	TAY
	STY @LOCAL03
	JMP @PROCESS_CURSOR_MOVE
@CHECK_CONFIRM:
	LDA PAD_PRESS
	AND #PAD::A_BUTTON | PAD::L_BUTTON
	BEQL @CHECK_CANCEL
	LDA @VIRTUAL04
	CMP #8
	BNE @CHECK_SPECIAL_ROW
	LDA @LOCAL07
	BEQ @DONT_CARE_BUTTON
	CMP #19
	BEQ @BACKSPACE_BUTTON
	CMP #24
	BEQ @END_BUTTON
	JMP @INCREMENT_FRAME
@DONT_CARE_BUTTON:
	LDA #SFX::TEXT_INPUT
	JSL PLAY_SOUND
	LDY @LOCAL08
	LDX @LOCAL0A
	LDA @LOCAL0B
	JSR RENDER_DONT_CARE_NAME
	STA @LOCAL08
	JMP @CURSOR_SETUP
@BACKSPACE_BUTTON:
	LDA #SFX::TEXT_INPUT
	JSL PLAY_SOUND
	LDY #.LOWORD(-1)
	LDX @LOCAL0C
	LDA @LOCAL0B
	JSR RENDER_NAMING_CHARACTER
	CMP #0
	BEQL @CURSOR_SETUP
	LDA @LOCAL0A
	CMP #.LOWORD(-1)
	BEQL @CURSOR_SETUP
	LDA #1
	JMP @RETURN
@END_BUTTON:
	LDA #SFX::NAMING_CONFIRM
	JSL PLAY_SOUND
	JMP @FINISH_ENTRY
@CHECK_SPECIAL_ROW:
	LDA #SFX::TEXT_INPUT
	JSL PLAY_SOUND
	LDA @VIRTUAL04
	CMP #6
	BNE @INPUT_CHARACTER
	LDA @LOCAL07
	CMP #8
	BEQ @SWITCH_HIRAGANA
	CMP #14
	BEQ @SWITCH_KATAKANA
	CMP #20
	BEQ @SWITCH_ROMAJI
	BRA @INCREMENT_FRAME
@SWITCH_HIRAGANA:
	LDX #0
	STX @LOCAL09
	JMP @OPEN_KEYBOARD
@SWITCH_KATAKANA:
	LDX #1
	STX @LOCAL09
	JMP @OPEN_KEYBOARD
@SWITCH_ROMAJI:
	LDX #2
	STX @LOCAL09
	JMP @OPEN_KEYBOARD
@INPUT_CHARACTER:
	LDX @VIRTUAL04
	LDA @LOCAL07
	INC
	JSL GET_MENU_TILE_AT_POSITION
	TAY
	LDX @LOCAL0C
	LDA @LOCAL0B
	JSR RENDER_NAMING_CHARACTER
	JMP @CURSOR_SETUP
@CHECK_CANCEL:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON
	BEQ @CHECK_START
	LDA #SFX::NAMING_BACKSPACE
	JSL PLAY_SOUND
	LDY #.LOWORD(-1)
	LDX @LOCAL0C
	LDA @LOCAL0B
	JSR RENDER_NAMING_CHARACTER
	CMP #0
	BEQL @CURSOR_SETUP
	LDA @LOCAL0A
	CMP #.LOWORD(-1)
	BEQL @CURSOR_SETUP
	LDA #1
	JMP @RETURN
@CHECK_START:
	LDA PAD_PRESS
	AND #PAD::START_BUTTON
	BEQ @INCREMENT_FRAME
	LDA #SFX::NAMING_CONFIRM_ALT
	JSL PLAY_SOUND
	BRA @FINISH_ENTRY
@INCREMENT_FRAME:
	LDX @LOCAL04
	INX
	STX @LOCAL04
@FRAME_WAIT_CHECK:
	STX @VIRTUAL02
	LDA #10
	CLC
	SBC @VIRTUAL02
	JUMPGTS @INPUT_TICK
	JMP @CURSOR_BLINK_LOOP
@PROCESS_CURSOR_MOVE:
	LDX @VIRTUAL04
	LDA @LOCAL07
	JSR SET_FOCUS_TEXT_CURSOR
	LDA #47
	JSR SET_TILE_ATTRIBUTE_AND_REDRAW
	LDY @LOCAL03
	CPY #.LOWORD(-1)
	BEQL @CURSOR_SETUP
	TYA
	AND #$00FF
	STA @LOCAL07
	TYA
	AND #$FF00
	XBA
	AND #$00FF
	STA @VIRTUAL04
	JMP @CURSOR_SETUP
@FINISH_ENTRY:
	LDA @LOCAL0B
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(window_stats)
	TAX
	LDA WINDOW_STATS + window_stats::text_x,X
	BEQL @CURSOR_SETUP
	LDA @LOCAL0B
	JSR SET_WINDOW_FOCUS
	LDY #0
	STY @LOCAL09
	BRA @COPY_NAME_CHECK
@COPY_NAME_LOOP:
	LDA WINDOW_STATS + window_stats::text_y,X
	TAX
	TYA
	JSL GET_MENU_TILE_AT_POSITION
	SEP #PROC_FLAGS::ACCUM8
	STA (@LOCAL0D)
	REP #PROC_FLAGS::ACCUM8
	INC @LOCAL0D
	LDY @LOCAL09
	INY
	STY @LOCAL09
@COPY_NAME_CHECK:
	LDA @LOCAL0B
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(window_stats)
	TAX
	LDY @LOCAL09
	TYA
	CMP WINDOW_STATS + window_stats::text_x,X
	BCC @COPY_NAME_LOOP
	BRA @PAD_ZEROS_CHECK
@PAD_ZEROS_LOOP:
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	STA (@LOCAL0D)
	REP #PROC_FLAGS::ACCUM8
	INC @LOCAL0D
	INY
@PAD_ZEROS_CHECK:
	CPY @LOCAL0C
	BCC @PAD_ZEROS_LOOP
	LDA #0
@RETURN:
	PLD
	RTS
