
WAIT_FOR_ACTIONSCRIPT:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STZ ACTIONSCRIPT_STATE
	JSR CLEAR_INSTANT_PRINTING
	JSL WINDOW_TICK
	BRA @CHECK_STATE
@LOOP:
	LDA DEBUG
	BEQ @RENDER
	LDA PAD_STATE
	AND #PAD::START_BUTTON
	BEQ @RENDER
	LDA PAD_STATE
	AND #PAD::SELECT_BUTTON
	BNE @DONE
@RENDER:
	JSL RENDER_FRAME_TICK
@CHECK_STATE:
	LDA ACTIONSCRIPT_STATE
	BEQ @LOOP
	STZ ACTIONSCRIPT_STATE
@DONE:
	RTS
