
WINDOW_TICK:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	JSL RAND
	.A16
	LDA INSTANT_PRINTING
	AND #$00FF
	BNE @RETURN
	LDA REDRAW_ALL_WINDOWS
	AND #$00FF
	BNE @REDRAW_ALL
	LDA WINDOW_HEAD
	CMP #$FFFF
	BEQ @AFTER_RENDER
	LDA WINDOW_TAIL
	JSL RENDER_WINDOW_FRAME
	BRA @AFTER_RENDER
@REDRAW_ALL:
	JSL RENDER_ALL_WINDOWS
	SEP #PROC_FLAGS::ACCUM8
	STZ REDRAW_ALL_WINDOWS
@AFTER_RENDER:
	JSL HP_PP_ROLLER
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA UPLOAD_HPPP_METER_TILES
	JSL UPDATE_HPPP_METER_TILES
	LDA DISABLED_TRANSITIONS
	BNE @AFTER_PALETTE_CHECK
	JSR CHECK_LAST_MEMBER_STATUS_CHANGE
	CMP #$0000
	BRK
	BEQ @AFTER_PALETTE_CHECK
	JSL LOAD_CHARACTER_WINDOW_PALETTE
@AFTER_PALETTE_CHECK:
	STZ HPPP_METER_AREA_NEEDS_UPDATE
	JSL UPLOAD_BATTLE_SCREEN_TO_VRAM
	JSL RENDER_FRAME_TICK
@RETURN:
	RTL
