
WINDOW_TICK:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	JSL RAND
	LDA EARLY_TICK_EXIT
	AND #$00FF
	BEQ @NORMAL_TICK
	SEP #PROC_FLAGS::ACCUM8
	STZ EARLY_TICK_EXIT
	BRA @EXIT
@NORMAL_TICK:
	.A16
	LDA INSTANT_PRINTING
	AND #$00FF
	BNE @EXIT
	LDA REDRAW_ALL_WINDOWS
	AND #$00FF
	BNE @REDRAW_ALL
	LDA WINDOW_HEAD
	CMP #$FFFF
	BEQ @UPDATE_HPPP
	LDA WINDOW_TAIL
	JSL RENDER_WINDOW_FRAME
	BRA @UPDATE_HPPP
@REDRAW_ALL:
	JSL RENDER_ALL_WINDOWS
	SEP #PROC_FLAGS::ACCUM8
	STZ REDRAW_ALL_WINDOWS
@UPDATE_HPPP:
	JSL HP_PP_ROLLER
	SEP #PROC_FLAGS::ACCUM8
	LDA #$0001
	STA UPLOAD_HPPP_METER_TILES
	JSL UPDATE_HPPP_METER_TILES
	LDA DISABLED_TRANSITIONS
	BNE @UPLOAD_VRAM
	JSR CHECK_LAST_MEMBER_STATUS_CHANGE
	CMP #$0000
	BRK
	BEQ @UPLOAD_VRAM
	JSL LOAD_CHARACTER_WINDOW_PALETTE
@UPLOAD_VRAM:
	STZ HPPP_METER_AREA_NEEDS_UPDATE
	JSL UPLOAD_BATTLE_SCREEN_TO_VRAM
	JSL RENDER_FRAME_TICK
@EXIT:
	REP #PROC_FLAGS::ACCUM8
	RTL
