
CC_1D_0C:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXY
	STY @LOCAL02
	LDA #1
	CLC
	SBC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BRANCHLTEQS @ARGS_GATHERED
	TYA
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_1D_0C)
	JMP @RETURN
@ARGS_GATHERED:
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	TAX
	BEQ @CHARACTER_FROM_WORKING_MEM
	TXA
	BRA @HAVE_CHARACTER
@CHARACTER_FROM_WORKING_MEM:
	JSR GET_WORKING_MEMORY
	LDA @VIRTUAL06
@HAVE_CHARACTER:
	STA @VIRTUAL02
	LDY @LOCAL02
	BEQ @ITEM_SLOT_FROM_ARG_MEM
	TYA
	BRA @HAVE_ITEM_SLOT
@ITEM_SLOT_FROM_ARG_MEM:
	JSR GET_ARGUMENT_MEMORY
	LDA @VIRTUAL06
@HAVE_ITEM_SLOT:
	TAY
	STY @LOCAL01
	JSR IS_ESCARGO_EXPRESS_FULL
	CMP #0
	BEQ @EXPRESS_NOT_FULL
	LDX #2
	STX @LOCAL02
	BRA @CHECK_ITEM_FLAG
@EXPRESS_NOT_FULL:
	LDX #0
	STX @LOCAL02
@CHECK_ITEM_FLAG:
	LDY @LOCAL01
	TYA
	DEC
	PHA
	LDA @VIRTUAL02
	DEC
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	CLC
	ADC #.LOWORD(PARTY_CHARACTERS)+char_struct::items
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	TAX
	LDA __BSS_START__,X
	AND #$00FF
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::flags
	TAX
	LDA f:ITEM_CONFIGURATION_TABLE,X
	AND #$00FF
	AND #ITEM_FLAGS::CANNOT_STORE
	BEQ @FLAG_NOT_SET
	LDA #1
	BRA @COMBINE_RESULT
@FLAG_NOT_SET:
	LDA #0
@COMBINE_RESULT:
	LDX @LOCAL02
	STX @VIRTUAL02
	ORA @VIRTUAL02
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	LDA #NULL
@RETURN:
	END_C_FUNCTION
