
CC_0D:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	CPX #0
	BEQ @FROM_WORKING_MEMORY
	JSR GET_SECONDARY_MEMORY
	STORE_INT1632 @VIRTUAL06
	BRA @HAVE_VALUE
@FROM_WORKING_MEMORY:
	JSR GET_WORKING_MEMORY
@HAVE_VALUE:
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_ARGUMENT_MEMORY
	LDA #NULL
	END_C_FUNCTION
