
CC_1F_1A:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @LOCAL00
	LDA #2
	CLC
	SBC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BRANCHLTEQS @ARGS_GATHERED
	TXA
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_1F_1A)
	BRA @RETURN
@ARGS_GATHERED:
	SEP #PROC_FLAGS::ACCUM8
	LDA #8
	SEP #PROC_FLAGS::INDEX8
	TAY
	REP #PROC_FLAGS::ACCUM8
	LDA CC_ARGUMENT_STORAGE+1
	AND #$00FF
	JSL ASL16_ENTRY2
	STA @VIRTUAL02
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	ORA @VIRTUAL02
	REP #PROC_FLAGS::INDEX8
	LDX @LOCAL00
	JSL SPAWN_FLOATING_SPRITE_FOR_NPC
	LDA #NULL
@RETURN:
	END_C_FUNCTION
