
CC_1F_67:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXA
	BEQ @ARG_IS_ZERO
	STORE_INT1632 @VIRTUAL06
	BRA @HAVE_VALUE
@ARG_IS_ZERO:
	JSR GET_ARGUMENT_MEMORY
@HAVE_VALUE:
	LDA @VIRTUAL06
	JSL DISABLE_HOTSPOT
	LDA #NULL
	PLD
	RTS
