
CC_1C_13:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @LOCAL01
	LDA #1
	CLC
	SBC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BRANCHLTEQS @ARGS_GATHERED
	TXA
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_1C_13)
	BRA @RETURN
@ARGS_GATHERED:
	JSR GET_BLINKING_PROMPT
	CMP #0
	BEQ @NO_PROMPT
	LDX @LOCAL01
	DEX
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	DEC
	JSL CHECK_BATTLE_TARGET_TYPE
	SIGN_EXTENDA1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
@NO_PROMPT:
	LDA #NULL
@RETURN:
	END_C_FUNCTION
