
CC_18_0D:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXY
	STY @LOCAL00
	LDA #1
	CLC
	SBC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BRANCHLTEQS @ARGS_GATHERED
	TYA
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_18_0D)
	BRA @RETURN
@ARGS_GATHERED:
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	TAX
	BEQ @ARG_IS_ZERO
	TXA
	BRA @ARG_IS_NONZERO
@ARG_IS_ZERO:
	JSR GET_WORKING_MEMORY
	LDA @VIRTUAL06
@ARG_IS_NONZERO:
	TAX
	LDY @LOCAL00
	TYA
	CMP #1
	BEQ @CASE_STATUS_WINDOW
	CMP #2
	BEQ @CASE_NULL_C3EF23
	BRA @DONE
@CASE_STATUS_WINDOW:
	TXA
	JSL DISPLAY_STATUS_WINDOW
	BRA @DONE
@CASE_NULL_C3EF23:
	TXA
	JSL NULL_C3EF23
@DONE:
	LDA #NULL
@RETURN:
	END_C_FUNCTION
