
CC_1F_83:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXY
	STY @LOCAL01
	LDA #1
	CLC
	SBC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BRANCHLTEQS @ARGS_READY
	TYA
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_1F_83)
	BRA @RETURN
@ARGS_READY:
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	TAX
	BEQ @ITEM_FROM_MEMORY
	TXA
	BRA @HAVE_ITEM
@ITEM_FROM_MEMORY:
	JSR GET_WORKING_MEMORY
	LDA @VIRTUAL06
@HAVE_ITEM:
	STA @VIRTUAL02
	LDY @LOCAL01
	BEQ @CHARACTER_FROM_MEMORY
	TYA
	BRA @HAVE_CHARACTER
@CHARACTER_FROM_MEMORY:
	JSR GET_ARGUMENT_MEMORY
	LDA @VIRTUAL06
@HAVE_CHARACTER:
	TAX
	LDA @VIRTUAL02
	JSR EQUIP_ITEM
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_ARGUMENT_MEMORY
	LDA #NULL
@RETURN:
	END_C_FUNCTION
