
CC_1D_12:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXY
	STY @LOCAL00
	LDA #1
	CLC
	SBC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BRANCHLTEQS @ARGS_GATHERED
	TYA
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_1D_12)
	BRA @RETURN
@ARGS_GATHERED:
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	TAX
	BEQ @CHARACTER_FROM_WORKING_MEM
	TXA
	BRA @HAVE_CHARACTER
@CHARACTER_FROM_WORKING_MEM:
	JSR GET_WORKING_MEMORY
	LDA @VIRTUAL06
@HAVE_CHARACTER:
	STA @VIRTUAL02
	LDY @LOCAL00
	BEQ @ITEM_SLOT_FROM_ARG_MEM
	TYA
	BRA @HAVE_ITEM_SLOT
@ITEM_SLOT_FROM_ARG_MEM:
	JSR GET_ARGUMENT_MEMORY
	LDA @VIRTUAL06
@HAVE_ITEM_SLOT:
	TAX
	LDA @VIRTUAL02
	JSR ESCARGO_EXPRESS_MOVE
	LDA #NULL
@RETURN:
	END_C_FUNCTION
