
CC_18_05:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA #1
	CLC
	SBC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BRANCHLTEQS @ARGS_GATHERED
	TXA
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_18_05)
	BRA @RETURN_HANDLER
@ARGS_GATHERED:
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	STA @LOCAL00
	LDA FORCE_LEFT_TEXT_ALIGNMENT
	AND #$00FF
	BEQ @DEFAULT_ALIGNMENT
	LDA @LOCAL00
	JSL SET_TEXT_PIXEL_POSITION
	BRA @ALIGNMENT_SET
@DEFAULT_ALIGNMENT:
	LDA @LOCAL00
	JSL SET_FOCUS_TEXT_CURSOR
@ALIGNMENT_SET:
	LDA #NULL
@RETURN_HANDLER:
	END_C_FUNCTION
