
CC_1D_23:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXA
	BEQ @ARG_FROM_MEMORY
	STORE_INT1632 @VIRTUAL06
	BRA @HAVE_ITEM_ID
@ARG_FROM_MEMORY:
	JSR GET_ARGUMENT_MEMORY
@HAVE_ITEM_ID:
	LDA @VIRTUAL06
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::type
	TAX
	LDA f:ITEM_CONFIGURATION_TABLE,X
	AND #$00FF
	AND #$000C
	BEQ @TYPE_NONE
	CMP #$04
	BEQ @TYPE_HAS_BITS
	CMP #$08
	BEQ @TYPE_HAS_BITS
	CMP #$0C
	BEQ @TYPE_HAS_BITS
	BRA @TYPE_OTHER
@TYPE_NONE:
	LDA #1
	BRA @STORE_RESULT
@TYPE_HAS_BITS:
	LDA #2
	BRA @STORE_RESULT
@TYPE_OTHER:
	LDA #0
@STORE_RESULT:
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	LDA #NULL
	END_C_FUNCTION
