
CC_1D_0A:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	CPX #0
	BEQ @FROM_ARG_MEMORY
	TXA
	BRA @HAVE_VALUE
@FROM_ARG_MEMORY:
	JSR GET_ARGUMENT_MEMORY
	LDA @VIRTUAL06
@HAVE_VALUE:
	OPTIMIZED_MULT @VIRTUAL04, .SIZEOF(item)
	CLC
	ADC #item::cost
	TAX
	LDA f:ITEM_CONFIGURATION_TABLE,X
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	LDA #NULL
	END_C_FUNCTION
