
CC_1D_0E:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	LDA #1
	CLC
	SBC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BRANCHLTEQS @ARGS_GATHERED
	TXA
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_1D_0E)
	BRA @RETURN
@ARGS_GATHERED:
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	STA @LOCAL03
	CPX #0
	BEQ @CHARACTER_FROM_ARG_MEMORY
	STX @LOCAL02
	BRA @HAVE_CHARACTER
@CHARACTER_FROM_ARG_MEMORY:
	JSR GET_ARGUMENT_MEMORY
	LDA @VIRTUAL06
	TAX
	STX @LOCAL02
@HAVE_CHARACTER:
	LDA @LOCAL03
	BNE @HAVE_ITEM
	JSR GET_WORKING_MEMORY
	LDA @VIRTUAL06
@HAVE_ITEM:
	LDX @LOCAL02
	JSL GIVE_ITEM_TO_CHARACTER
	TAX
	STX @LOCAL01
	TXA
	JSL FIND_EMPTY_INVENTORY_SLOT
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_ARGUMENT_MEMORY
	LDX @LOCAL01
	TXA
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	LDA #NULL
@RETURN:
	END_C_FUNCTION
