
CC_13_14:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @LOCAL02
	TAY
	STY @LOCAL01
	BRA @CHECK_WAITING
@DEBUG_SKIP_CHECK:
	LDA DEBUG
	BEQ @CHECK_WAITING
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::R_BUTTON
	CMP #PAD::B_BUTTON | PAD::R_BUTTON
	BNE @CHECK_WAITING
	STZ TEXT_PROMPT_WAITING_FOR_INPUT
	BRA @DONE_WAITING
@CHECK_WAITING:
	LDA TEXT_PROMPT_WAITING_FOR_INPUT
	BNE @DEBUG_SKIP_CHECK
@DONE_WAITING:
	JSR CLEAR_INSTANT_PRINTING
	JSL WINDOW_TICK
	LDX @LOCAL02
	BNE @CHECK_TRIANGLE
	LDA BLINKING_TRIANGLE_FLAG
	BEQ @CHECK_TRIANGLE
	LDA TEXT_SPEED_BASED_WAIT
	BEQ @CHECK_TRIANGLE
	LDA #0
	JSR TEXT_SPEED_DELAY
	JMP @RETURN
@CHECK_TRIANGLE:
	LDA BLINKING_TRIANGLE_FLAG
	BEQ @CALC_WINDOW_POS
	JSL PAUSE_MUSIC
@CALC_WINDOW_POS:
	LDA CURRENT_FOCUS_WINDOW
	ASL
	TAX
	LDA OPEN_WINDOW_TABLE,X
	LDY #.SIZEOF(window_stats)
	JSL MULT168
	CLC
	ADC #.LOWORD(WINDOW_STATS)
	STA @VIRTUAL02
	LDY @LOCAL01
	BNE @DRAW_TRIANGLE_FRAME0
	BRA @WAIT_NO_TRIANGLE_CHECK
@WAIT_NO_TRIANGLE_TICK:
	JSL UPDATE_HPPP_METER_AND_RENDER
@WAIT_NO_TRIANGLE_CHECK:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON | PAD::A_BUTTON | PAD::L_BUTTON
	BEQ @WAIT_NO_TRIANGLE_TICK
	JMP @RESUME_MUSIC
@DRAW_TRIANGLE_FRAME0:
	LOADPTR BLINKING_TRIANGLE_TILES + 0 * 2, @LOCAL00
	LDX @VIRTUAL02
	LDA a:window_stats::window_y,X
	LDX @VIRTUAL02
	CLC
	ADC a:window_stats::height,X
	OPTIMIZED_MULT @VIRTUAL04, 32
	STA @VIRTUAL04
	LDX @VIRTUAL02
	LDA a:window_stats::window_x,X
	LDX @VIRTUAL02
	CLC
	ADC a:window_stats::width,X
	CLC
	ADC @VIRTUAL04
	CLC
	ADC #VRAM::TEXT_LAYER_TILEMAP + TILEMAP_COORDS 0, 1
	TAY
	LDX #2
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	.A16
	LDX #15
	STX @LOCAL01
	BRA @FRAME0_WAIT_CHECK
@FRAME0_WAIT_TICK:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON | PAD::A_BUTTON | PAD::L_BUTTON
	BNE @BUTTON_PRESSED_FRAME0
	JSL UPDATE_HPPP_METER_AND_RENDER
	LDX @LOCAL01
	DEX
	STX @LOCAL01
@FRAME0_WAIT_CHECK:
	BNE @FRAME0_WAIT_TICK
	LOADPTR BLINKING_TRIANGLE_TILES + 1 * 2, @LOCAL00
	LDX @VIRTUAL02
	LDA a:window_stats::window_y,X
	LDX @VIRTUAL02
	CLC
	ADC a:window_stats::height,X
	OPTIMIZED_MULT @VIRTUAL04, 32
	STA @VIRTUAL04
	LDX @VIRTUAL02
	LDA a:window_stats::window_x,X
	LDX @VIRTUAL02
	CLC
	ADC a:window_stats::width,X
	CLC
	ADC @VIRTUAL04
	CLC
	ADC #VRAM::TEXT_LAYER_TILEMAP + TILEMAP_COORDS 0, 1
	TAY
	LDX #2
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
	.A16
	LDX #10
	STX @LOCAL01
	BRA @FRAME1_WAIT_CHECK
@FRAME1_WAIT_TICK:
	LDA PAD_PRESS
	AND #PAD::B_BUTTON | PAD::SELECT_BUTTON | PAD::A_BUTTON | PAD::L_BUTTON
	BNE @RESUME_MUSIC
	JSL UPDATE_HPPP_METER_AND_RENDER
	LDX @LOCAL01
	DEX
	STX @LOCAL01
@FRAME1_WAIT_CHECK:
	BNE @FRAME1_WAIT_TICK
	JMP @DRAW_TRIANGLE_FRAME0
@BUTTON_PRESSED_FRAME0:
	LOADPTR BLINKING_TRIANGLE_TILES + 2 * 2, @LOCAL00
	LDX @VIRTUAL02
	LDA a:window_stats::window_y,X
	LDX @VIRTUAL02
	CLC
	ADC a:window_stats::height,X
	OPTIMIZED_MULT @VIRTUAL04, 32
	PHA
	LDX @VIRTUAL02
	LDA a:window_stats::window_x,X
	LDX @VIRTUAL02
	CLC
	ADC a:window_stats::width,X
	PLY
	STY @VIRTUAL02
	CLC
	ADC @VIRTUAL02
	CLC
	ADC #VRAM::TEXT_LAYER_TILEMAP + TILEMAP_COORDS 0, 1
	TAY
	LDX #2
	SEP #PROC_FLAGS::ACCUM8
	LDA #0
	JSL PREPARE_VRAM_COPY
@RESUME_MUSIC:
	JSL RESUME_MUSIC
@RETURN:
	END_C_FUNCTION
