
CC_19_05:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @VIRTUAL02
	LDA #2
	CLC
	SBC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BRANCHLTEQS @ARGS_READY
	LDA @VIRTUAL02
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_19_05)
	BRA @RETURN
@ARGS_READY:
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	TAY
	STY @LOCAL02
	LDA CC_ARGUMENT_STORAGE+1
	AND #$00FF
	TAX
	BEQ @CHARACTER_FROM_MEMORY
	STX @LOCAL01
	BRA @HAVE_CHARACTER
@CHARACTER_FROM_MEMORY:
	JSR GET_ARGUMENT_MEMORY
	LDA @VIRTUAL06
	TAX
	STX @LOCAL01
@HAVE_CHARACTER:
	LDY @LOCAL02
	BEQ @STATUS_FROM_MEMORY
	TYA
	BRA @HAVE_STATUS
@STATUS_FROM_MEMORY:
	JSR GET_WORKING_MEMORY
	LDA @VIRTUAL06
@HAVE_STATUS:
	LDY @VIRTUAL02
	LDX @LOCAL01
	JSL INFLICT_STATUS_NONBATTLE
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	LDA #NULL
@RETURN:
	END_C_FUNCTION
