
CC_06:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TAY
	STY @LOCAL00
	LDA CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BNE @HAVE_ALL_ARGS
	TXA
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_06)
	BRA @RETURN
@HAVE_ALL_ARGS:
	TXA
	SEP #PROC_FLAGS::INDEX8
	LDY #8
	JSL ASL16_ENTRY2
	STA @VIRTUAL02
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	ORA @VIRTUAL02
	JSL GET_EVENT_FLAG
	CMP #0
	BEQ @FLAG_NOT_SET
	STZ CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_0A)
	BRA @RETURN
@FLAG_NOT_SET:
	LDY @LOCAL00
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDA #4
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA __BSS_START__,Y
	LDA @VIRTUAL06+2
	STA __BSS_START__+2,Y
	LDA #NULL
@RETURN:
	END_C_FUNCTION
