
CC_1F_02:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXA
	BEQ @FROM_ARG_MEMORY
	STORE_INT1632 $06
	BRA @HAVE_VALUE
@FROM_ARG_MEMORY:
	JSR GET_ARGUMENT_MEMORY
@HAVE_VALUE:
	LDA @VIRTUAL06
	JSL PLAY_SOUND_AND_UPDATE_METERS
	LDA #NULL
	PLD
	RTS
