
CC_1F_00:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXA
	STA @LOCAL00
	LDA #1
	CLC
	SBC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BRANCHLTEQS @ARGS_GATHERED
	LDA @LOCAL00
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_1F_00)
	BRA @RETURN
@ARGS_GATHERED:
	LDA @LOCAL00
	BEQ @FROM_ARG_MEMORY
	STORE_INT1632 @VIRTUAL06
	BRA @HAVE_MUSIC_ID
@FROM_ARG_MEMORY:
	JSR GET_ARGUMENT_MEMORY
@HAVE_MUSIC_ID:
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	TAX
	LDA @VIRTUAL06
	JSL SET_MAP_MUSIC
	LDA #NULL
@RETURN:
	END_C_FUNCTION
