
CC_1C_05:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	CPX #$0000
	BEQ @FROM_ARG_MEMORY
	TXA
	BRA @HAVE_VALUE
@FROM_ARG_MEMORY:
	JSR GET_ARGUMENT_MEMORY
	LDA @VIRTUAL06
@HAVE_VALUE:
	JSR PRINT_ITEM_TYPE
	LDA #NULL
	PLD
	RTS
