
CC_1E_06:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @LOCAL00
	LDA #1
	CLC
	SBC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BRANCHLTEQS @ARGS_GATHERED
	TXA
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_1E_06)
	BRA @RETURN
@ARGS_GATHERED:
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	BEQ @FROM_ARG_MEMORY
	AND #$00FF
	BRA @HAVE_CHAR_ID
@FROM_ARG_MEMORY:
	JSR GET_ARGUMENT_MEMORY
	LDA @VIRTUAL06
@HAVE_CHAR_ID:
	LDY #1
	LDX @LOCAL00
	JSR RECOVER_PP_AMTPERCENT
	LDA #NULL
@RETURN:
	END_C_FUNCTION
