
CC_0E:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	CPX #$0000
	BNE @HAVE_VALUE
	JSR GET_ARGUMENT_MEMORY
	LDA @VIRTUAL06
	AND #$00FF
	TAX
@HAVE_VALUE:
	TXA
	JSR SET_SECONDARY_MEMORY
	LDA #NULL
	PLD
	RTS
