
CC_1D_0F:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @LOCAL01
	LDA #1
	CLC
	SBC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BRANCHLTEQS @ARGS_GATHERED
	TXA
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_1D_0F)
	BRA @RETURN
@ARGS_GATHERED:
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	TAY
	BEQ @SLOT_FROM_WORKING_MEMORY
	TYA
	BRA @HAVE_SLOT
@SLOT_FROM_WORKING_MEMORY:
	JSR GET_WORKING_MEMORY
	LDA @VIRTUAL06
@HAVE_SLOT:
	STA @VIRTUAL02
	LDX @LOCAL01
	BEQ @CHARACTER_FROM_ARG_MEMORY
	TXA
	BRA @HAVE_CHARACTER
@CHARACTER_FROM_ARG_MEMORY:
	JSR GET_ARGUMENT_MEMORY
	LDA @VIRTUAL06
@HAVE_CHARACTER:
	TAY
	STY @LOCAL01
	TYX
	LDA @VIRTUAL02
	JSL GET_CHARACTER_ITEM
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_ARGUMENT_MEMORY
	LDY @LOCAL01
	TYX
	LDA @VIRTUAL02
	JSR REMOVE_ITEM_FROM_INVENTORY
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	LDA #NULL
@RETURN:
	END_C_FUNCTION
