
CC_1F_EE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXA
	STA @LOCAL00
	LDA CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BNE @HAVE_ALL_ARGS
	LDA @LOCAL00
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_1F_EE)
	BRA @RETURN
@HAVE_ALL_ARGS:
	SEP #PROC_FLAGS::INDEX8
	LDY #8
	LDA @LOCAL00
	JSL ASL16_ENTRY2
	STA @VIRTUAL02
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	ORA @VIRTUAL02
	JSL SET_CAMERA_FOCUS_BY_NPC_ID
	LDA #NULL
@RETURN:
	END_C_FUNCTION
