
CC_1D_02:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @VIRTUAL02
	LDX #0
	STX @LOCAL01
	JSR GET_ARGUMENT_MEMORY
	LDA @VIRTUAL06
	JSR GET_ITEM_TYPE
	CMP @VIRTUAL02
	BNE @STORE_RESULT
	LDX #1
	STX @LOCAL01
@STORE_RESULT:
	LDX @LOCAL01
	TXA
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	LDA #NULL
	END_C_FUNCTION
