
CC_19_1C:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	STX @LOCAL01
	LDA #1
	CLC
	SBC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BRANCHLTEQS @ARGS_GATHERED
	TXA
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_19_1C)
	BRA @RETURN_HANDLER
@ARGS_GATHERED:
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	BEQ @ARG_1_IS_ZERO
	SEP #PROC_FLAGS::ACCUM8
	MOVE_INT832 CC_ARGUMENT_STORAGE, @VIRTUAL06
	BRA @ARG_1_IS_NONZERO
@ARG_1_IS_ZERO:
	JSR GET_WORKING_MEMORY
@ARG_1_IS_NONZERO:
	REP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL06
	STA @VIRTUAL04
	LDX @LOCAL01
	BEQ @ARG_2_IS_ZERO
	TXA
	BRA @ARG_2_IS_NONZERO
@ARG_2_IS_ZERO:
	JSR GET_ARGUMENT_MEMORY
	LDA @VIRTUAL06
@ARG_2_IS_NONZERO:
	TAY
	STY @LOCAL00
	LDA @VIRTUAL04
	CMP #$00FF
	BNE @CHARACTER_INVENTORY
	TYA
	JSR REMOVE_ESCARGO_EXPRESS_ITEM
	STA @VIRTUAL02
	BRA @QUEUE_ITEM
@CHARACTER_INVENTORY:
	TYX
	LDA @VIRTUAL04
	JSL GET_CHARACTER_ITEM
	STA @VIRTUAL02
	LDY @LOCAL00
	TYX
	LDA @VIRTUAL04
	JSR REMOVE_ITEM_FROM_INVENTORY
@QUEUE_ITEM:
	LDX @VIRTUAL02
	LDA @VIRTUAL04
	JSR QUEUE_ITEM_FOR_CHARACTER
	LDA #NULL
@RETURN_HANDLER:
	END_C_FUNCTION
