
CC_1D_TREE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXA
	BEQL @GIVE_ITEM_TO_CHARACTER
	CMP #$01
	BEQL @TAKE_ITEM_FROM_CHARACTER
	CMP #$02
	BEQL @GET_PLAYER_HAS_INVENTORY_FULL
	CMP #$03
	BEQL @GET_PLAYER_HAS_INVENTORY_ROOM
	CMP #$04
	BEQL @CHECK_ITEM_NOT_EQUIPPED
	CMP #$05
	BEQL @CHECK_ITEM_IN_INVENTORY
	CMP #$06
	BEQL @ADD_TO_ATM
	CMP #$07
	BEQL @TAKE_FROM_ATM
	CMP #$08
	BEQL @ADD_TO_WALLET
	CMP #$09
	BEQL @TAKE_FROM_WALLET
	CMP #$0A
	BEQL @GET_BUY_PRICE_OF_ITEM
	CMP #$0B
	BEQL @GET_SELL_PRICE_OF_ITEM
	CMP #$0C
	BEQL @ESCARGO_EXPRESS_ITEM_STATUS
	CMP #$0D
	BEQL @CHARACTER_HAS_AILMENT
	CMP #$0E
	BEQL @GIVE_ITEM_TO_CHARACTER_B
	CMP #$0F
	BEQL @TAKE_ITEM_FROM_CHARACTER_2
	CMP #$10
	BEQL @CHECK_ITEM_EQUIPPED
	CMP #$11
	BEQL @CHECK_ITEM_USABLE_BY
	CMP #$12
	BEQL @ESCARGO_EXPRESS_MOVE
	CMP #$13
	BEQL @DELIVER_ESCARGO_EXPRESS_ITEM
	CMP #$14
	BEQL @HAVE_ENOUGH_MONEY
	CMP #$15
	BEQL @PUT_VAL_IN_ARGMEM
	CMP #$17
	BEQL @HAVE_ENOUGH_MONEY_IN_ATM
	CMP #$18
	BEQL @ESCARGO_EXPRESS_STORE
	CMP #$19
	BEQL @HAVE_X_PARTY_MEMBERS
	CMP #$20
	BEQL @TEST_SELF_TARGET
	CMP #$21
	BEQL @GENERATE_RANDOM_NUMBER
	CMP #$22
	BEQL @TEST_EXIT_MOUSE_USABLE
	CMP #$23
	BEQL @GET_ITEM_CATEGORY
	CMP #$24
	BEQL @GET_GAME_STATE_C4
	JMP @RETURN_NULL
@GIVE_ITEM_TO_CHARACTER:
	LDA #.LOWORD(CC_1D_00)
	JMP @RETURN_HANDLER
@TAKE_ITEM_FROM_CHARACTER:
	LDA #.LOWORD(CC_1D_01)
	JMP @RETURN_HANDLER
@GET_PLAYER_HAS_INVENTORY_FULL:
	LDA #.LOWORD(CC_1D_02)
	JMP @RETURN_HANDLER
@GET_PLAYER_HAS_INVENTORY_ROOM:
	LDA #.LOWORD(CC_1D_03)
	JMP @RETURN_HANDLER
@CHECK_ITEM_NOT_EQUIPPED:
	LDA #.LOWORD(CC_1D_04)
	JMP @RETURN_HANDLER
@CHECK_ITEM_IN_INVENTORY:
	LDA #.LOWORD(CC_1D_05)
	JMP @RETURN_HANDLER
@ADD_TO_ATM:
	LDA #.LOWORD(CC_1D_06)
	JMP @RETURN_HANDLER
@TAKE_FROM_ATM:
	LDA #.LOWORD(CC_1D_07)
	JMP @RETURN_HANDLER
@ADD_TO_WALLET:
	LDA #.LOWORD(CC_1D_08)
	JMP @RETURN_HANDLER
@TAKE_FROM_WALLET:
	LDA #.LOWORD(CC_1D_09)
	JMP @RETURN_HANDLER
@GET_BUY_PRICE_OF_ITEM:
	LDA #.LOWORD(CC_1D_0A)
	JMP @RETURN_HANDLER
@GET_SELL_PRICE_OF_ITEM:
	LDA #.LOWORD(CC_1D_0B)
	JMP @RETURN_HANDLER
@ESCARGO_EXPRESS_ITEM_STATUS:
	LDA #.LOWORD(CC_1D_0C)
	JMP @RETURN_HANDLER
@CHARACTER_HAS_AILMENT:
	LDA #.LOWORD(CC_1D_0D)
	JMP @RETURN_HANDLER
@GIVE_ITEM_TO_CHARACTER_B:
	LDA #.LOWORD(CC_1D_0E)
	JMP @RETURN_HANDLER
@TAKE_ITEM_FROM_CHARACTER_2:
	LDA #.LOWORD(CC_1D_0F)
	JMP @RETURN_HANDLER
@CHECK_ITEM_EQUIPPED:
	LDA #.LOWORD(CC_1D_10)
	JMP @RETURN_HANDLER
@CHECK_ITEM_USABLE_BY:
	LDA #.LOWORD(CC_1D_11)
	JMP @RETURN_HANDLER
@ESCARGO_EXPRESS_MOVE:
	LDA #.LOWORD(CC_1D_12)
	JMP @RETURN_HANDLER
@DELIVER_ESCARGO_EXPRESS_ITEM:
	LDA #.LOWORD(CC_1D_13)
	JMP @RETURN_HANDLER
@HAVE_ENOUGH_MONEY:
	LDA #.LOWORD(CC_1D_14)
	JMP @RETURN_HANDLER
@PUT_VAL_IN_ARGMEM:
	LDA #.LOWORD(CC_1D_15)
	JMP @RETURN_HANDLER
@HAVE_ENOUGH_MONEY_IN_ATM:
	LDA #.LOWORD(CC_1D_17)
	JMP @RETURN_HANDLER
@ESCARGO_EXPRESS_STORE:
	LDA #.LOWORD(CC_1D_18)
	JMP @RETURN_HANDLER
@HAVE_X_PARTY_MEMBERS:
	LDA #.LOWORD(CC_1D_19)
	JMP @RETURN_HANDLER
@TEST_SELF_TARGET:
	LDY #0
	STY @LOCAL02
	JSR RETURN_BATTLE_TARGET_ADDRESS
	STA @LOCAL01
	JSR RETURN_BATTLE_ATTACKER_ADDRESS
	TAX
	LDA @LOCAL01
	JSR COMPARE_STRINGS
	CMP #0
	BNE @SELF_TARGET_MATCH
	LDY #1
	STY @LOCAL02
@SELF_TARGET_MATCH:
	LDY @LOCAL02
	TYA
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	BRA @RETURN_NULL
@GENERATE_RANDOM_NUMBER:
	LDA #.LOWORD(CC_1D_21)
	BRA @RETURN_HANDLER
@TEST_EXIT_MOUSE_USABLE:
	LDY #0
	STY @LOCAL02
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL LOAD_SECTOR_ATTRS
	AND #$0007
	CMP #2
	BNE @NOT_EXIT_MOUSE_AREA
	LDY #1
	STY @LOCAL02
@NOT_EXIT_MOUSE_AREA:
	LDY @LOCAL02
	TYA
	STORE_INT1632S @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	BRA @RETURN_NULL
@GET_ITEM_CATEGORY:
	LDA #.LOWORD(CC_1D_23)
	BRA @RETURN_HANDLER
@GET_GAME_STATE_C4:
	LDA #.LOWORD(CC_1D_24)
	BRA @RETURN_HANDLER
@RETURN_NULL:
	LDA #NULL
@RETURN_HANDLER:
	END_C_FUNCTION
