
CC_1A_TREE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXA
	BEQ @PARTY_SELECTION_UNCANCELLABLE
	CMP #$01
	BEQ @PARTY_SELECTION_CANCELLABLE
	CMP #$04
	BEQ @SELECTION_MENU_NO_CANCEL
	CMP #$05
	BEQ @SHOW_CHARACTER_INVENTORY
	CMP #$06
	BEQ @DISPLAY_SHOP_MENU
	CMP #$07
	BEQ @SELECT_ESCARGO_EXPRESS_ITEM
	CMP #$08
	BEQ @SELECTION_MENU_NO_CANCEL_2
	CMP #$09
	BEQ @SELECTION_MENU_ALLOW_CANCEL
	CMP #$0A
	BEQL @DISPLAY_TELEPHONE_CONTACT
	CMP #$0B
	BEQL @OPEN_TELEPORT_MENU
	JMP @RETURN_NULL
@PARTY_SELECTION_UNCANCELLABLE:
	LDA #.LOWORD(CC_1A_00)
	JMP @RETURN_HANDLER
@PARTY_SELECTION_CANCELLABLE:
	LDA #.LOWORD(CC_1A_01)
	JMP @RETURN_HANDLER
@SELECTION_MENU_NO_CANCEL:
	LDA #0
	JSR SELECTION_MENU
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	JSR CLEAR_FOCUS_WINDOW_MENU_OPTIONS
	BRA @RETURN_NULL
@SHOW_CHARACTER_INVENTORY:
	LDA #.LOWORD(CC_1A_05)
	BRA @RETURN_HANDLER
@DISPLAY_SHOP_MENU:
	LDA #.LOWORD(CC_1A_06)
	BRA @RETURN_HANDLER
@SELECT_ESCARGO_EXPRESS_ITEM:
	JSR SELECT_ESCARGO_EXPRESS_ITEM
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	BRA @RETURN_NULL
@SELECTION_MENU_NO_CANCEL_2:
	LDA #0
	JSR SELECTION_MENU
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	BRA @RETURN_NULL
@SELECTION_MENU_ALLOW_CANCEL:
	LDA #1
	JSR SELECTION_MENU
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	BRA @RETURN_NULL
@DISPLAY_TELEPHONE_CONTACT:
	JSR DISPLAY_TELEPHONE_CONTACT_TEXT
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	BRA @RETURN_NULL
@OPEN_TELEPORT_MENU:
	JSR OPEN_TELEPORT_DESTINATION_MENU
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
@RETURN_NULL:
	LDA #NULL
@RETURN_HANDLER:
	END_C_FUNCTION
