
CC_1F_TREE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXA
	BEQL @PLAY_MUSIC
	CMP #$01
	BEQL @STOP_MUSIC
	CMP #$02
	BEQL @PLAY_SOUND
	CMP #$03
	BEQL @RESTORE_DEFAULT_MUSIC
	CMP #$04
	BEQL @SET_TEXT_PRINTING_SOUND
	CMP #$05
	BEQL @DISABLE_SECTOR_MUSIC
	CMP #$06
	BEQL @ENABLE_SECTOR_MUSIC
	CMP #$07
	BEQL @APPLY_MUSIC_EFFECT
	CMP #$11
	BEQL @ADD_PARTY_MEMBER
	CMP #$12
	BEQL @REMOVE_PARTY_MEMBER
	CMP #$13
	BEQL @CHANGE_CHARACTER_DIRECTION
	CMP #$14
	BEQL @CHANGE_PARTY_DIRECTION
	CMP #$15
	BEQL @GENERATE_ACTIVE_SPRITE
	CMP #$16
	BEQL @CHANGE_TPT_DIRECTION
	CMP #$17
	BEQL @CREATE_ENTITY
	CMP #$18
	BEQL @DUMMY_18
	CMP #$19
	BEQL @DUMMY_19
	CMP #$1A
	BEQL @CREATE_FLOATING_NEAR_TPT
	CMP #$1B
	BEQL @DELETE_FLOATING_NEAR_TPT
	CMP #$1C
	BEQL @CREATE_FLOATING_NEAR_CHAR
	CMP #$1D
	BEQL @DELETE_FLOATING_NEAR_CHAR
	CMP #$1E
	BEQL @DELETE_TPT_INSTANCE
	CMP #$1F
	BEQL @DELETE_GENERATED_SPRITE
	CMP #$20
	BEQL @TRIGGER_PSI_TELEPORT
	CMP #$21
	BEQL @TELEPORT_TO
	CMP #$23
	BEQL @TRIGGER_BATTLE
	CMP #$30
	BEQL @CHANGE_FONT
	CMP #$31
	BEQL @CHANGE_FONT
	CMP #$40
	BEQL @CC_40
	CMP #$41
	BEQL @TRIGGER_SPECIAL_EVENT
	CMP #$50
	BEQL @LOCK_INPUT
	CMP #$51
	BEQL @UNLOCK_INPUT
	CMP #$52
	BEQL @CREATE_NUMBER_SELECTOR
	CMP #$60
	BEQL @TEXT_SPEED_DELAY
	CMP #$61
	BEQL @WAIT_FOR_ACTIONSCRIPT
	CMP #$62
	BEQL @ENABLE_BLINKING_TRIANGLE
	CMP #$63
	BEQL @SCREEN_RELOAD_PTR
	CMP #$64
	BEQL @SAVE_PARTY_NPC_STATE
	CMP #$65
	BEQL @RESTORE_PARTY_NPC_STATE
	CMP #$66
	BEQL @ACTIVATE_HOTSPOT
	CMP #$67
	BEQL @DEACTIVATE_HOTSPOT
	CMP #$68
	BEQL @STORE_COORDS_TO_MEMORY
	CMP #$69
	BEQL @TELEPORT_TO_STORED_COORDS
	CMP #$71
	BEQL @REALIZE_PSI
	CMP #$81
	BEQL @TEST_CHARACTER_CAN_EQUIP
	CMP #$83
	BEQL @EQUIP_ITEM
	CMP #$90
	BEQL @OPEN_TELEPHONE_MENU
	CMP #$A0
	BEQL @SET_INTERACTING_FLAG_ON
	CMP #$A1
	BEQL @SET_INTERACTING_FLAG_OFF
	CMP #$A2
	BEQL @GET_INTERACTING_FLAG
	CMP #$B0
	BEQL @SAVE_GAME
	CMP #$C0
	BEQL @JUMP_MULTI2
	CMP #$D0
	BEQL @TRY_FIX_ITEM
	CMP #$D1
	BEQL @GET_MAGIC_TRUFFLE_DISTANCE
	CMP #$D2
	BEQL @SUMMON_PHOTOGRAPHER
	CMP #$D3
	BEQL @TRIGGER_TIMED_EVENT
	CMP #$E1
	BEQL @CHANGE_MAP_PALETTE
	CMP #$E4
	BEQL @CHANGE_SPRITE_DIRECTION
	CMP #$E5
	BEQL @SET_PLAYER_LOCK
	CMP #$E6
	BEQL @DISABLE_NPC_MOVEMENT
	CMP #$E7
	BEQL @DISABLE_SPRITE_MOVEMENT
	CMP #$E8
	BEQL @RESTRICT_PLAYER_MOVEMENT
	CMP #$E9
	BEQL @ENABLE_NPC_MOVEMENT
	CMP #$EA
	BEQL @ENABLE_SPRITE_MOVEMENT
	CMP #$EB
	BEQL @MAKE_INVISIBLE
	CMP #$EC
	BEQL @MAKE_VISIBLE
	CMP #$ED
	BEQL @RESTORE_MOVEMENT
	CMP #$EE
	BEQL @SET_CAMERA_FOCUS_NPC
	CMP #$EF
	BEQL @SET_CAMERA_FOCUS_SPRITE
	CMP #$F0
	BEQL @RIDE_BICYCLE
	CMP #$F1
	BEQL @SET_TPT_MOVEMENT
	CMP #$F2
	BEQL @SET_SPRITE_MOVEMENT
	CMP #$F3
	BEQL @CREATE_FLOATING_NEAR_ENTITY
	CMP #$F4
	BEQL @DELETE_FLOATING_NEAR_ENTITY
	JMP @RETURN_NULL
@PLAY_MUSIC:
	LDA #.LOWORD(CC_1F_00)
	JMP @RETURN_HANDLER
@STOP_MUSIC:
	LDA #.LOWORD(CC_1F_01)
	JMP @RETURN_HANDLER
@PLAY_SOUND:
	LDA #.LOWORD(CC_1F_02)
	JMP @RETURN_HANDLER
@RESTORE_DEFAULT_MUSIC:
	JSL GET_MAP_MUSIC_AT_LEADER
	LDX #0
	JSL SET_MAP_MUSIC
	JMP @RETURN_NULL
@SET_TEXT_PRINTING_SOUND:
	LDA #.LOWORD(CC_1F_04)
	JMP @RETURN_HANDLER
@DISABLE_SECTOR_MUSIC:
	LDA #0
	JSL SET_AUTO_SECTOR_MUSIC_CHANGES
	JMP @RETURN_NULL
@ENABLE_SECTOR_MUSIC:
	LDA #1
	JSL SET_AUTO_SECTOR_MUSIC_CHANGES
	JMP @RETURN_NULL
@APPLY_MUSIC_EFFECT:
	LDA #.LOWORD(CC_1F_07)
	JMP @RETURN_HANDLER
@ADD_PARTY_MEMBER:
	LDA #.LOWORD(CC_1F_11)
	JMP @RETURN_HANDLER
@REMOVE_PARTY_MEMBER:
	LDA #.LOWORD(CC_1F_12)
	JMP @RETURN_HANDLER
@CHANGE_CHARACTER_DIRECTION:
	LDA #.LOWORD(CC_1F_13)
	JMP @RETURN_HANDLER
@CHANGE_PARTY_DIRECTION:
	LDA #.LOWORD(CC_1F_14)
	JMP @RETURN_HANDLER
@GENERATE_ACTIVE_SPRITE:
	LDA #.LOWORD(CC_1F_15)
	JMP @RETURN_HANDLER
@CHANGE_TPT_DIRECTION:
	LDA #.LOWORD(CC_1F_16)
	JMP @RETURN_HANDLER
@CREATE_ENTITY:
	LDA #.LOWORD(CC_1F_17)
	JMP @RETURN_HANDLER
@DUMMY_18:
	LDA #.LOWORD(CC_1F_18)
	JMP @RETURN_HANDLER
@DUMMY_19:
	LDA #.LOWORD(CC_1F_19)
	JMP @RETURN_HANDLER
@CREATE_FLOATING_NEAR_TPT:
	LDA #.LOWORD(CC_1F_1A)
	JMP @RETURN_HANDLER
@DELETE_FLOATING_NEAR_TPT:
	LDA #.LOWORD(CC_1F_1B)
	JMP @RETURN_HANDLER
@CREATE_FLOATING_NEAR_CHAR:
	LDA #.LOWORD(CC_1F_1C)
	JMP @RETURN_HANDLER
@DELETE_FLOATING_NEAR_CHAR:
	LDA #.LOWORD(CC_1F_1D)
	JMP @RETURN_HANDLER
@DELETE_TPT_INSTANCE:
	LDA #.LOWORD(CC_1F_1E)
	JMP @RETURN_HANDLER
@DELETE_GENERATED_SPRITE:
	LDA #.LOWORD(CC_1F_1F)
	JMP @RETURN_HANDLER
@TRIGGER_PSI_TELEPORT:
	LDA #.LOWORD(CC_1F_20)
	JMP @RETURN_HANDLER
@TELEPORT_TO:
	LDA #.LOWORD(CC_1F_21)
	JMP @RETURN_HANDLER
@TRIGGER_BATTLE:
	LDA #.LOWORD(CC_1F_23)
	JMP @RETURN_HANDLER
@CHANGE_FONT:
	JSR CHANGE_CURRENT_WINDOW_FONT
	JMP @RETURN_NULL
@CC_40:
	LDA #.LOWORD(CC_1F_40)
	JMP @RETURN_HANDLER
@TRIGGER_SPECIAL_EVENT:
	LDA #.LOWORD(CC_1F_41)
	JMP @RETURN_HANDLER
@LOCK_INPUT:
	JSR LOCK_INPUT
	JMP @RETURN_NULL
@UNLOCK_INPUT:
	JSR UNLOCK_INPUT
	JMP @RETURN_NULL
@CREATE_NUMBER_SELECTOR:
	LDA #.LOWORD(CC_1F_52)
	JMP @RETURN_HANDLER
@TEXT_SPEED_DELAY:
	LDA #.LOWORD(CC_1F_60)
	JMP @RETURN_HANDLER
@WAIT_FOR_ACTIONSCRIPT:
	JSR WAIT_FOR_ACTIONSCRIPT
	JMP @RETURN_NULL
@ENABLE_BLINKING_TRIANGLE:
	LDA #.LOWORD(CC_1F_62)
	JMP @RETURN_HANDLER
@SCREEN_RELOAD_PTR:
	LDA #.LOWORD(CC_1F_63)
	JMP @RETURN_HANDLER
@SAVE_PARTY_NPC_STATE:
	JSL SAVE_PARTY_NPC_STATE
	JMP @RETURN_NULL
@RESTORE_PARTY_NPC_STATE:
	JSL RESTORE_PARTY_NPC_STATE
	JMP @RETURN_NULL
@ACTIVATE_HOTSPOT:
	LDA #.LOWORD(CC_1F_66)
	JMP @RETURN_HANDLER
@DEACTIVATE_HOTSPOT:
	LDA #.LOWORD(CC_1F_67)
	JMP @RETURN_HANDLER
@STORE_COORDS_TO_MEMORY:
	LDA GAME_STATE+game_state::leader_x_coord
	STA GAME_STATE+game_state::exit_mouse_x_coord
	LDA GAME_STATE+game_state::leader_y_coord
	STA GAME_STATE+game_state::exit_mouse_y_coord
	JMP @RETURN_NULL
@TELEPORT_TO_STORED_COORDS:
	LDY #1
	STY @LOCAL01
	BRA @TELEPORT_LOOP_CHECK
@TELEPORT_SET_FLAGS:
	LDX #0
	TYA
	JSL SET_EVENT_FLAG
	LDY @LOCAL01
	INY
	STY @LOCAL01
@TELEPORT_LOOP_CHECK:
	CPY #10
	BLTEQ @TELEPORT_SET_FLAGS
	LDX #1
	TXA
	JSL FADE_OUT
	LDA #SFX::EQUIPPED_ITEM
	JSL PLAY_SOUND
	LDA GAME_STATE+game_state::exit_mouse_x_coord
	STA @VIRTUAL04
	LDA GAME_STATE+game_state::exit_mouse_y_coord
	STA @VIRTUAL02
	LDX @VIRTUAL02
	LDA @VIRTUAL04
	JSL LOAD_MAP_AT_POSITION
	STZ PLAYER_HAS_MOVED_SINCE_MAP_LOAD
	LDY #4
	LDX @VIRTUAL02
	LDA @VIRTUAL04
	JSL SET_LEADER_POSITION_AND_LOAD_PARTY
	LDX #1
	TXA
	JSL FADE_IN
	LDA #.LOWORD(-1)
	STA STAIRS_DIRECTION
	JMP @RETURN_NULL
@REALIZE_PSI:
	LDA #.LOWORD(CC_1F_71)
	JMP @RETURN_HANDLER
@TEST_CHARACTER_CAN_EQUIP:
	LDA #.LOWORD(CC_1F_81)
	JMP @RETURN_HANDLER
@EQUIP_ITEM:
	LDA #.LOWORD(CC_1F_83)
	JMP @RETURN_HANDLER
@OPEN_TELEPHONE_MENU:
	JSR OPEN_TELEPHONE_MENU
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	JMP @RETURN_NULL
@SET_INTERACTING_FLAG_ON:
	LDA #1
	JSL SET_CURRENT_INTERACTING_EVENT_FLAG
	JMP @RETURN_NULL
@SET_INTERACTING_FLAG_OFF:
	LDA #0
	JSL SET_CURRENT_INTERACTING_EVENT_FLAG
	JMP @RETURN_NULL
@GET_INTERACTING_FLAG:
	JSL GET_CURRENT_INTERACTING_EVENT_FLAG
	SIGN_EXTENDA1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	JMP @RETURN_NULL
@SAVE_GAME:
	JSL SAVE_CURRENT_GAME
	JMP @RETURN_NULL
@JUMP_MULTI2:
	LDA #.LOWORD(CC_1F_C0)
	JMP @RETURN_HANDLER
@TRY_FIX_ITEM:
	LDA #.LOWORD(CC_1F_D0)
	JMP @RETURN_HANDLER
@GET_MAGIC_TRUFFLE_DISTANCE:
	JSL GET_DISTANCE_TO_MAGIC_TRUFFLE
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	BRA @RETURN_NULL
@SUMMON_PHOTOGRAPHER:
	LDA #.LOWORD(CC_1F_D2)
	BRA @RETURN_HANDLER
@TRIGGER_TIMED_EVENT:
	LDA #.LOWORD(CC_1F_D3)
	BRA @RETURN_HANDLER
@CHANGE_MAP_PALETTE:
	LDA #.LOWORD(CC_1F_E1)
	BRA @RETURN_HANDLER
@CHANGE_SPRITE_DIRECTION:
	LDA #.LOWORD(CC_1F_E4)
	BRA @RETURN_HANDLER
@SET_PLAYER_LOCK:
	LDA #.LOWORD(CC_1F_E5)
	BRA @RETURN_HANDLER
@DISABLE_NPC_MOVEMENT:
	LDA #.LOWORD(CC_1F_E6)
	BRA @RETURN_HANDLER
@DISABLE_SPRITE_MOVEMENT:
	LDA #.LOWORD(CC_1F_E7)
	BRA @RETURN_HANDLER
@RESTRICT_PLAYER_MOVEMENT:
	LDA #.LOWORD(CC_1F_E8)
	BRA @RETURN_HANDLER
@ENABLE_NPC_MOVEMENT:
	LDA #.LOWORD(CC_1F_E9)
	BRA @RETURN_HANDLER
@ENABLE_SPRITE_MOVEMENT:
	LDA #.LOWORD(CC_1F_EA)
	BRA @RETURN_HANDLER
@MAKE_INVISIBLE:
	LDA #.LOWORD(CC_1F_EB)
	BRA @RETURN_HANDLER
@MAKE_VISIBLE:
	LDA #.LOWORD(CC_1F_EC)
	BRA @RETURN_HANDLER
@RESTORE_MOVEMENT:
	JSL RESET_CAMERA_MODE
	BRA @RETURN_NULL
@SET_CAMERA_FOCUS_NPC:
	LDA #.LOWORD(CC_1F_EE)
	BRA @RETURN_HANDLER
@SET_CAMERA_FOCUS_SPRITE:
	LDA #.LOWORD(CC_1F_EF)
	BRA @RETURN_HANDLER
@RIDE_BICYCLE:
	JSL GET_ON_BICYCLE
	BRA @RETURN_NULL
@SET_TPT_MOVEMENT:
	LDA #.LOWORD(CC_1F_F1)
	BRA @RETURN_HANDLER
@SET_SPRITE_MOVEMENT:
	LDA #.LOWORD(CC_1F_F2)
	BRA @RETURN_HANDLER
@CREATE_FLOATING_NEAR_ENTITY:
	LDA #.LOWORD(CC_1F_F3)
	BRA @RETURN_HANDLER
@DELETE_FLOATING_NEAR_ENTITY:
	LDA #.LOWORD(CC_1F_F4)
	BRA @RETURN_HANDLER
@RETURN_NULL:
	LDA #NULL
@RETURN_HANDLER:
	END_C_FUNCTION
