
CC_1C_TREE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXA
	BEQL @SET_PALETTE
	CMP #$01
	BEQL @PRINT_STAT
	CMP #$02
	BEQL @PRINT_CHARACTER_NAME
	CMP #$03
	BEQL @PRINT_CHARACTER
	CMP #$04
	BEQL @SHOW_HPPP_WINDOWS
	CMP #$05
	BEQL @PRINT_ITEM_NAME
	CMP #@VIRTUAL06
	BEQL @PRINT_TELEPORT_DEST_NAME
	CMP #$07
	BEQL @PRINT_HORIZONTAL_STRINGS
	CMP #$08
	BEQL @PRINT_SPECIAL_GRAPHICS
	CMP #$09
	BEQL @SET_NUMBER_PADDING
	CMP #$0A
	BEQL @PRINT_NUMBER
	CMP #$0B
	BEQL @PRINT_MONEY_AMOUNT
	CMP #$0C
	BEQL @PRINT_VERTICAL_STRINGS
.IF .DEFINED(USA)
	CMP #$14
	BEQL @GET_ATTACKER_GENDER
	CMP #$15
	BEQL @GET_TARGET_GENDER
.ENDIF
	CMP #$0D
	BEQL @PRINT_ENEMY_ATTACKER_NAME
	CMP #$0E
	BEQL @PRINT_ENEMY_TARGET_NAME
	CMP #$0F
	BEQL @PRINT_ATTACK_NUMBER
	CMP #$11
	BEQL @PRINT_PARTY_OR_HINT_NEWLINE
	CMP #$12
	BEQL @PRINT_PSI_NAME
	CMP #$13
	BEQL @DISPLAY_BATTLE_ANIMATION
	JMP @RETURN_NULL
@SET_PALETTE:
	LDA #.LOWORD(CC_1C_00)
	JMP @RETURN_HANDLER
@PRINT_STAT:
	LDA #.LOWORD(CC_1C_01)
	JMP @RETURN_HANDLER
@PRINT_CHARACTER_NAME:
	LDA #.LOWORD(CC_1C_02)
	JMP @RETURN_HANDLER
@PRINT_CHARACTER:
	LDA #.LOWORD(CC_1C_03)
	JMP @RETURN_HANDLER
@SHOW_HPPP_WINDOWS:
	JSR SHOW_HPPP_WINDOWS
	JMP @RETURN_NULL
@PRINT_ITEM_NAME:
	LDA #.LOWORD(CC_1C_05)
	JMP @RETURN_HANDLER
@PRINT_TELEPORT_DEST_NAME:
	LDA #.LOWORD(CC_1C_06)
	JMP @RETURN_HANDLER
@PRINT_HORIZONTAL_STRINGS:
	LDA #.LOWORD(CC_1C_07)
	JMP @RETURN_HANDLER
@PRINT_SPECIAL_GRAPHICS:
	LDA #.LOWORD(CC_1C_08)
	JMP @RETURN_HANDLER
@SET_NUMBER_PADDING:
	LDA #.LOWORD(CC_1C_09)
	JMP @RETURN_HANDLER
@PRINT_NUMBER:
	LDA #.LOWORD(CC_1C_0A)
	JMP @RETURN_HANDLER
@PRINT_MONEY_AMOUNT:
	LDA #.LOWORD(CC_1C_0B)
	JMP @RETURN_HANDLER
@PRINT_VERTICAL_STRINGS:
	LDA #.LOWORD(CC_1C_0C)
	JMP @RETURN_HANDLER
@GET_ATTACKER_GENDER:
.IF .DEFINED(USA)
	LDA #.LOWORD(CC_1C_14)
	.IF .DEFINED(PROTOTYPE19950327)
		JMP @RETURN_HANDLER
	.ELSE
		BRA @RETURN_HANDLER
	.ENDIF
@GET_TARGET_GENDER:
	LDA #.LOWORD(CC_1C_15)
	.IF .DEFINED(PROTOTYPE19950327)
		JMP @RETURN_HANDLER
	.ELSE
		BRA @RETURN_HANDLER
	.ENDIF
.ENDIF
@PRINT_ENEMY_ATTACKER_NAME:
.IF .DEFINED(USA)
	LDA #0
	JSL PRINT_ENEMY_ARTICLE
.ENDIF
	JSR RETURN_BATTLE_ATTACKER_ADDRESS
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #80
.IF .DEFINED(JPN)
	JSR PRINT_STRING
.ELSE
	JSL PRINT_STRING_WITH_WORDWRAP
.ENDIF
	BRA @RETURN_NULL
@PRINT_ENEMY_TARGET_NAME:
.IF .DEFINED(USA)
	LDA #1
	JSL PRINT_ENEMY_ARTICLE
.ENDIF
	JSR RETURN_BATTLE_TARGET_ADDRESS
	PROMOTENEARPTRA @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDA #80
.IF .DEFINED(JPN)
	JSR PRINT_STRING
.ELSE
	JSL PRINT_STRING_WITH_WORDWRAP
.ENDIF
	BRA @RETURN_NULL
@PRINT_ATTACK_NUMBER:
	JSR GET_CNUM
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR PRINT_NUMBER
	BRA @RETURN_NULL
@PRINT_PARTY_OR_HINT_NEWLINE:
.IF .DEFINED(PROTOTYPE19950327) || .DEFINED(JPN)
	JSL UPDATE_PARTY
	JSL FIND_FIRST_ALIVE_PARTY_MEMBER
	JSR PRINT_CHARACTER_NAME
	JSL COUNT_ALIVE_PARTY_MEMBERS
.IF .DEFINED(JPN)
	CMP #1
	BLTEQ @RETURN_NULL
	LDA #$0066
	JSR PRINT_LETTER
	LDA #$0076
	JSR PRINT_LETTER
.ENDIF
	BRA @RETURN_NULL
.ELSE
	LDA #.LOWORD(CC_1C_11)
	BRA @RETURN_HANDLER
.ENDIF
@PRINT_PSI_NAME:
	LDA #.LOWORD(CC_1C_12)
	BRA @RETURN_HANDLER
@DISPLAY_BATTLE_ANIMATION:
	LDA #.LOWORD(CC_1C_13)
	BRA @RETURN_HANDLER
@RETURN_NULL:
	LDA #NULL
@RETURN_HANDLER:
	END_C_FUNCTION
