
CC_18_TREE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TAY
	STY @LOCAL00
	TXA
	BEQ @CLOSE_WINDOW
	CMP #$01
	BEQ @OPEN_WINDOW
	CMP #$02
	BEQ @SAVE_TEXT_ATTRIBUTES
	CMP #$03
	BEQ @SWITCH_TO_WINDOW
	CMP #$04
	BEQ @CLOSE_ALL
	CMP #$05
	BEQ @FORCE_TEXT_ALIGNMENT
	CMP #$06
	BEQ @CLEAR_WINDOW
	CMP #$07
	BEQ @CHECK_INEQUALITY
	CMP #$08
	BEQ @SELECTION_MENU_ALLOW_CANCEL
	CMP #$09
	BEQ @SELECTION_MENU_NO_CANCEL
	CMP #$0A
	BEQ @DISPLAY_MONEY
	CMP #$0D
	BEQ @DISPLAY_STATUS
	BRA @RETURN_NULL
@CLOSE_WINDOW:
	JSR CLOSE_FOCUS_WINDOW
	BRA @RETURN_NULL
@OPEN_WINDOW:
	LDA #.LOWORD(CC_18_01)
	BRA @RETURN_HANDLER
@SAVE_TEXT_ATTRIBUTES:
	TYA
	CLC
	ADC #6
	JSL SAVE_WINDOW_TEXT_ATTRIBUTES
	LDA #1
	LDY @LOCAL00
	STA __BSS_START__+4,Y
	BRA @RETURN_NULL
@SWITCH_TO_WINDOW:
	LDA #.LOWORD(CC_18_03)
	BRA @RETURN_HANDLER
@CLOSE_ALL:
	JSR CLOSE_ALL_WINDOWS
	JSR HIDE_HPPP_WINDOWS
	JSL WINDOW_TICK
	BRA @RETURN_NULL
@FORCE_TEXT_ALIGNMENT:
	LDA #.LOWORD(CC_18_05)
	BRA @RETURN_HANDLER
@CLEAR_WINDOW:
	JSR CLEAR_FOCUS_WINDOW_CONTENT
	BRA @RETURN_NULL
@CHECK_INEQUALITY:
	LDA #.LOWORD(CC_18_07)
	BRA @RETURN_HANDLER
@SELECTION_MENU_ALLOW_CANCEL:
	LDA #.LOWORD(CC_18_08)
	BRA @RETURN_HANDLER
@SELECTION_MENU_NO_CANCEL:
	LDA #.LOWORD(CC_18_09)
	BRA @RETURN_HANDLER
@DISPLAY_MONEY:
	JSR DISPLAY_MONEY_WINDOW
	BRA @RETURN_NULL
@DISPLAY_STATUS:
	LDA #.LOWORD(CC_18_0D)
	BRA @RETURN_HANDLER
@RETURN_NULL:
	LDA #0
@RETURN_HANDLER:
	END_C_FUNCTION
