
CC_1E_TREE:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	TXA
	BEQ @RECOVER_HP_PERCENT
	CMP #$0001
	BEQ @DEPLETE_HP_PERCENT
	CMP #$0002
	BEQ @RECOVER_HP_AMOUNT
	CMP #$0003
	BEQ @DEPLETE_HP_AMOUNT
	CMP #$0004
	BEQ @RECOVER_PP_PERCENT
	CMP #$0005
	BEQ @DEPLETE_PP_PERCENT
	CMP #$0006
	BEQ @RECOVER_PP_AMOUNT
	CMP #$0007
	BEQ @DEPLETE_PP_AMOUNT
	CMP #$0008
	BEQ @SET_CHARACTER_LEVEL
	CMP #$0009
	BEQ @GIVE_EXPERIENCE
	CMP #$000A
	BEQ @BOOST_IQ
	CMP #$000B
	BEQ @BOOST_GUTS
	CMP #$000C
	BEQ @BOOST_SPEED
	CMP #$000D
	BEQ @BOOST_VITALITY
	CMP #$000E
	BEQ @BOOST_LUCK
	BRA @RETURN_NULL
@RECOVER_HP_PERCENT:
	LDA #.LOWORD(CC_1E_00)
	BRA @RETURN_HANDLER
@DEPLETE_HP_PERCENT:
	LDA #.LOWORD(CC_1E_01)
	BRA @RETURN_HANDLER
@RECOVER_HP_AMOUNT:
	LDA #.LOWORD(CC_1E_02)
	BRA @RETURN_HANDLER
@DEPLETE_HP_AMOUNT:
	LDA #.LOWORD(CC_1E_03)
	BRA @RETURN_HANDLER
@RECOVER_PP_PERCENT:
	LDA #.LOWORD(CC_1E_04)
	BRA @RETURN_HANDLER
@DEPLETE_PP_PERCENT:
	LDA #.LOWORD(CC_1E_05)
	BRA @RETURN_HANDLER
@RECOVER_PP_AMOUNT:
	LDA #.LOWORD(CC_1E_06)
	BRA @RETURN_HANDLER
@DEPLETE_PP_AMOUNT:
	LDA #.LOWORD(CC_1E_07)
	BRA @RETURN_HANDLER
@SET_CHARACTER_LEVEL:
	LDA #.LOWORD(CC_1E_08)
	BRA @RETURN_HANDLER
@GIVE_EXPERIENCE:
	LDA #.LOWORD(CC_1E_09)
	BRA @RETURN_HANDLER
@BOOST_IQ:
	LDA #.LOWORD(CC_1E_0A)
	BRA @RETURN_HANDLER
@BOOST_GUTS:
	LDA #.LOWORD(CC_1E_0B)
	BRA @RETURN_HANDLER
@BOOST_SPEED:
	LDA #.LOWORD(CC_1E_0C)
	BRA @RETURN_HANDLER
@BOOST_VITALITY:
	LDA #.LOWORD(CC_1E_0D)
	BRA @RETURN_HANDLER
@BOOST_LUCK:
	LDA #.LOWORD(CC_1E_0E)
	BRA @RETURN_HANDLER
@RETURN_NULL:
	LDA #$0000
@RETURN_HANDLER:
	RTS
