
CC_19_TREE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXA
	CMP #$02
	BEQL @LOAD_STRING_TO_MEMORY
	CMP #$04
	BEQL @CLEAR_MENU_OPTIONS
	CMP #$05
	BEQL @INFLICT_STATUS
	CMP #$10
	BEQL @GET_CHARACTER_NUMBER
	CMP #$11
	BEQL @GET_CHARACTER_NAME_LETTER
	CMP #$14
	BEQL @GET_ESCARGO_EXPRESS_ITEM
	CMP #$16
	BEQL @GET_CHARACTER_STATUS
	CMP #$18
	BEQL @CC_19_18
	CMP #$19
	BEQL @ADD_ITEM_TO_WORK_MEMORY
	CMP #$1A
	BEQL @CC_19_1A
	CMP #$1B
	BEQL @CC_19_1B
	CMP #$1C
	BEQL @GIVE_ITEM_TO_CHARACTER
	CMP #$1D
	BEQL @CC_19_1D
	CMP #$1E
	BEQL @GET_CNUM
	CMP #$1F
	BEQL @GET_CURRENT_ITEM
	CMP #$20
	BEQL @GET_PLAYER_CONTROLLED_PARTY_COUNT
	CMP #$21
	BEQL @IS_ITEM_DRINK
	CMP #$22
	BEQL @GET_DIR_FROM_CHAR_TO_ENTITY
	CMP #$23
	BEQL @GET_DIR_FROM_NPC_TO_ENTITY
	CMP #$24
	BEQL @GET_DIR_FROM_SPRITE_TO_ENTITY
	CMP #$25
	BEQL @IS_ITEM_CONDIMENT
	CMP #$26
	BEQL @CC_19_26
	CMP #$27
	BEQL @CC_19_27
	CMP #$28
	BEQL @CC_19_28
	JMP @RETURN_NULL
@LOAD_STRING_TO_MEMORY:
	LDA #.LOWORD(CC_19_02)
	JMP @RETURN_HANDLER
@CLEAR_MENU_OPTIONS:
	JSR CLEAR_FOCUS_WINDOW_MENU_OPTIONS
	JMP @RETURN_NULL
@INFLICT_STATUS:
	LDA #.LOWORD(CC_19_05)
	JMP @RETURN_HANDLER
@GET_CHARACTER_NUMBER:
	LDA #.LOWORD(CC_19_10)
	JMP @RETURN_HANDLER
@GET_CHARACTER_NAME_LETTER:
	LDA #.LOWORD(CC_19_11)
	JMP @RETURN_HANDLER
@GET_ESCARGO_EXPRESS_ITEM:
	JSR GET_SECONDARY_MEMORY
.IF .DEFINED(JPN)
	DEC
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	SEP #PROC_FLAGS::ACCUM8
	LDA a:game_state::escargo_express_items,X
.ELSE
	TAX
	DEX
	SEP #PROC_FLAGS::ACCUM8
	LDA GAME_STATE+game_state::escargo_express_items,X
.ENDIF
	STORE_INT832 @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	JSR INCREMENT_SECONDARY_MEMORY
	JMP @RETURN_NULL
@GET_CHARACTER_STATUS:
	LDA #.LOWORD(CC_19_16)
	JMP @RETURN_HANDLER
@CC_19_18:
	LDA #.LOWORD(CC_19_18)
	JMP @RETURN_HANDLER
@ADD_ITEM_TO_WORK_MEMORY:
	LDA #.LOWORD(CC_19_19)
	JMP @RETURN_HANDLER
@CC_19_1A:
	LDA #.LOWORD(CC_19_1A)
	JMP @RETURN_HANDLER
@CC_19_1B:
	LDA #.LOWORD(CC_19_1B)
	JMP @RETURN_HANDLER
@GIVE_ITEM_TO_CHARACTER:
	LDA #.LOWORD(CC_19_1C)
	BRA @RETURN_HANDLER
@CC_19_1D:
	LDA #.LOWORD(CC_19_1D)
	BRA @RETURN_HANDLER
@GET_CNUM:
	JSR GET_CNUM
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	BRA @RETURN_NULL
@GET_CURRENT_ITEM:
	JSR GET_CURRENT_ITEM
	STORE_INT832 @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	BRA @RETURN_NULL
@GET_PLAYER_CONTROLLED_PARTY_COUNT:
	SEP #PROC_FLAGS::ACCUM8
	MOVE_INT832 GAME_STATE+game_state::player_controlled_party_count, @VIRTUAL06
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	BRA @RETURN_NULL
@IS_ITEM_DRINK:
	LDA #.LOWORD(CC_19_21)
	BRA @RETURN_HANDLER
@GET_DIR_FROM_CHAR_TO_ENTITY:
	LDA #.LOWORD(CC_19_22)
	BRA @RETURN_HANDLER
@GET_DIR_FROM_NPC_TO_ENTITY:
	LDA #.LOWORD(CC_19_23)
	BRA @RETURN_HANDLER
@GET_DIR_FROM_SPRITE_TO_ENTITY:
	LDA #.LOWORD(CC_19_24)
	BRA @RETURN_HANDLER
@IS_ITEM_CONDIMENT:
	LDA #.LOWORD(CC_19_25)
	BRA @RETURN_HANDLER
@CC_19_26:
	LDA #.LOWORD(CC_19_26)
	BRA @RETURN_HANDLER
@CC_19_27:
	LDA #.LOWORD(CC_19_27)
	BRA @RETURN_HANDLER
@CC_19_28:
	LDA #.LOWORD(CC_19_28)
	BRA @RETURN_HANDLER
@RETURN_NULL:
	LDA #0
@RETURN_HANDLER:
	END_C_FUNCTION
