
CC_1B_TREE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TAY
	STY @LOCAL02
	TXA
	BEQ @COPY_ACTIVE_TO_STORAGE
	CMP #$01
	BEQ @COPY_STORAGE_TO_ACTIVE
	CMP #$02
	BEQ @JUMP_IF_FALSE
	CMP #$03
	BEQ @JUMP_IF_TRUE
	CMP #$04
	BEQL @SWAP_WORKING_AND_ARG
	CMP #$05
	BEQL @COPY_ACTIVE_TO_GLOBAL_BACKUP
	CMP #$06
	BEQL @COPY_GLOBAL_BACKUP_TO_ACTIVE
	JMP @RETURN_NULL
@COPY_ACTIVE_TO_STORAGE:
	JSR TRANSFER_ACTIVE_MEM_STORAGE
	JMP @RETURN_NULL
@COPY_STORAGE_TO_ACTIVE:
	JSR TRANSFER_STORAGE_MEM_ACTIVE
	JMP @RETURN_NULL
@JUMP_IF_FALSE:
	JSR GET_WORKING_MEMORY
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BNE @JUMP_IF_FALSE_SKIP
	LDA #.LOWORD(CC_0A)
	JMP @RETURN_HANDLER
@JUMP_IF_FALSE_SKIP:
	LDY @LOCAL02
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDA #4
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA __BSS_START__,Y
	LDA @VIRTUAL06+2
	STA __BSS_START__+2,Y
	JMP @RETURN_NULL
@JUMP_IF_TRUE:
	JSR GET_WORKING_MEMORY
	MOVE_INT_CONSTANT NULL, @VIRTUAL0A
	CMP32 @VIRTUAL06, @VIRTUAL0A
	BEQ @JUMP_IF_TRUE_SKIP
	LDA #.LOWORD(CC_0A)
	JMP @RETURN_HANDLER
@JUMP_IF_TRUE_SKIP:
	LDY @LOCAL02
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	LDA #4
	CLC
	ADC @VIRTUAL06
	STA @VIRTUAL06
	STA __BSS_START__,Y
	LDA @VIRTUAL06+2
	STA __BSS_START__+2,Y
	JMP @RETURN_NULL
@SWAP_WORKING_AND_ARG:
	JSR GET_WORKING_MEMORY
	MOVE_INT @VIRTUAL06, @LOCAL01
	JSR GET_ARGUMENT_MEMORY
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
.IF .DEFINED(JPN)
	MOVE_INT @VIRTUAL0A, @LOCAL00
.ELSE
	MOVE_INT @VIRTUAL0A, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
.ENDIF
	JSR SET_WORKING_MEMORY
	MOVE_INT @LOCAL01, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_ARGUMENT_MEMORY
	BRA @RETURN_NULL
@COPY_ACTIVE_TO_GLOBAL_BACKUP:
	JSR GET_WORKING_MEMORY
	MOVE_INT @VIRTUAL06, TEXT_MAIN_REGISTER_BACKUP
	JSR GET_ARGUMENT_MEMORY
	MOVE_INT @VIRTUAL06, TEXT_SUB_REGISTER_BACKUP
	JSR GET_SECONDARY_MEMORY
	SEP #PROC_FLAGS::ACCUM8
	STA TEXT_LOOP_REGISTER_BACKUP
	BRA @RETURN_NULL
@COPY_GLOBAL_BACKUP_TO_ACTIVE:
	.A16
	MOVE_INT TEXT_MAIN_REGISTER_BACKUP, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	MOVE_INT TEXT_SUB_REGISTER_BACKUP, @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_ARGUMENT_MEMORY
	LDA TEXT_LOOP_REGISTER_BACKUP
	AND #$00FF
	JSR SET_SECONDARY_MEMORY
@RETURN_NULL:
	REP #PROC_FLAGS::ACCUM8
	LDA #NULL
@RETURN_HANDLER:
	END_C_FUNCTION
