
CC_1F_20:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT8
	STACK_RESERVE_INT8
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXA
	STA @LOCAL03
	LDA #1
	CLC
	SBC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BRANCHLTEQS @ARGS_GATHERED
	LDA @LOCAL03
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_1F_20)
	BRA @RETURN
@ARGS_GATHERED:
	SEP #PROC_FLAGS::ACCUM8
	LDA CC_ARGUMENT_STORAGE
	STA @VIRTUAL00
	REP #PROC_FLAGS::ACCUM8
	LDA @LOCAL03
	BEQ @DEST_FROM_MEMORY
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL02
	BRA @HAVE_DEST
@DEST_FROM_MEMORY:
	JSR GET_ARGUMENT_MEMORY
	MOVE_INT @VIRTUAL06, @LOCAL02
@HAVE_DEST:
	LDA @VIRTUAL00
	AND #$00FF
	BEQ @STYLE_FROM_MEMORY
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL00
	STA @LOCAL01
	BRA @HAVE_STYLE
@STYLE_FROM_MEMORY:
	JSR GET_WORKING_MEMORY
	MOVE_INT @VIRTUAL06, @VIRTUAL0A
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL0A
	STA @LOCAL01
@HAVE_STYLE:
	REP #PROC_FLAGS::ACCUM8
	MOVE_INT @LOCAL02, @VIRTUAL06
	SEP #PROC_FLAGS::ACCUM8
	LDA @VIRTUAL06
	STA @LOCAL00
	LDA @LOCAL01
	JSL SET_TELEPORT_STATE
	.A16
	LDA #NULL
@RETURN:
	END_C_FUNCTION
