
CC_1F_D2:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXA
	BEQ @FROM_ARG_MEMORY
	STORE_INT1632 @VIRTUAL06
	BRA @HAVE_ARG
@FROM_ARG_MEMORY:
	JSR GET_ARGUMENT_MEMORY
@HAVE_ARG:
	LDA @VIRTUAL06
	JSL ENCOUNTER_TRAVELLING_PHOTOGRAPHER
	LDA #NULL
	PLD
	RTS
