
CC_1F_23:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	TXA
	STA @LOCAL01
	LDA CC_ARGUMENT_GATHERING_LOOP_COUNTER
	BNE @ARGS_GATHERED
	LDA @LOCAL01
	SEP #PROC_FLAGS::ACCUM8
	LDX CC_ARGUMENT_GATHERING_LOOP_COUNTER
	STA CC_ARGUMENT_STORAGE,X
	REP #PROC_FLAGS::ACCUM8
	INC CC_ARGUMENT_GATHERING_LOOP_COUNTER
	LDA #.LOWORD(CC_1F_23)
	BRA @RETURN
@ARGS_GATHERED:
	SEP #PROC_FLAGS::INDEX8
	LDY #8
	LDA @LOCAL01
	JSL ASL16_ENTRY2
	STA @VIRTUAL02
	LDA CC_ARGUMENT_STORAGE
	AND #$00FF
	ORA @VIRTUAL02
	BEQ @ARG_FROM_MEMORY
	STORE_INT1632 @VIRTUAL06
	BRA @HAVE_BATTLE_ID
@ARG_FROM_MEMORY:
	JSR GET_ARGUMENT_MEMORY
@HAVE_BATTLE_ID:
	LDA @VIRTUAL06
	JSL INIT_BATTLE_SCRIPTED
	SIGN_EXTENDA1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	LDA #NULL
@RETURN:
	END_C_FUNCTION
