
CC_1F_D0:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_PARAM_INT16
	STACK_RESERVE_RETURN_INT16
	END_STACK_VARS
	CPX #0
	BEQ @ARG_IS_ZERO
	TXA
	BRA @ARG_IS_NONZERO
@ARG_IS_ZERO:
	JSR GET_ARGUMENT_MEMORY
	LDA @VIRTUAL06
@ARG_IS_NONZERO:
	JSL TRY_FIX_BROKEN_ITEM
	TAX
	STX @LOCAL01
	BEQ @FIX_FAILED
	TXA
	JSR GET_ITEM_EP
	STORE_INT1632 @VIRTUAL06
	BRA @STORE_RESULT
@FIX_FAILED:
	MOVE_INT_CONSTANT NULL, @VIRTUAL06
@STORE_RESULT:
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_WORKING_MEMORY
	LDX @LOCAL01
	TXA
	STORE_INT1632 @VIRTUAL06
	MOVE_INT @VIRTUAL06, @LOCAL00
	JSR SET_ARGUMENT_MEMORY
	LDA #NULL
	END_C_FUNCTION
