/*
 * battle_text_data.h — Compatibility shim.
 *
 * All text label constants are now in text_refs.h, auto-generated by
 * ebtools pack-all from the dialogue YAML files in src/assets/dialogue/.
 *
 * This header exists only to avoid breaking existing #include directives.
 * New code should #include "data/text_refs.h" directly.
 */
#ifndef DATA_BATTLE_TEXT_DATA_H
#define DATA_BATTLE_TEXT_DATA_H

#include "data/text_refs.h"

#endif /* DATA_BATTLE_TEXT_DATA_H */
