
INIT_PSI_TELEPORT_BETA:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	JSR SETUP_TELEPORT_ENTITY_FLAGS
	JSL RAND
	XBA
	AND #$FF00
	STA PSI_TELEPORT_BETA_ANGLE
	LDA PSI_TELEPORT_STYLE
	CMP #TELEPORT_STYLE::PSI_BETA
	BNE @NOT_PSI_BETA
	LDA #$0004
	STA PSI_TELEPORT_BETA_PROGRESS
	BRA @STORE_COORDS
@NOT_PSI_BETA:
	LDA #$0008
	STA PSI_TELEPORT_BETA_PROGRESS
	STZ PSI_TELEPORT_BETTER_PROGRESS
@STORE_COORDS:
	LDA GAME_STATE+game_state::leader_x_coord
	STA PSI_TELEPORT_BETA_X_ADJUSTMENT
	LDA GAME_STATE+game_state::leader_y_coord
	STA PSI_TELEPORT_BETA_Y_ADJUSTMENT
	RTS
