
INIT_TELEPORT_ARRIVAL:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA PSI_TELEPORT_STYLE
	CMP #TELEPORT_STYLE::INSTANT
	BEQ @INSTANT_SKIP
	LDA #24
	STA @LOCAL03
	BRA @LOOP_CHECK
@DISABLE_COLLISION:
	ASL
	TAX
	LDA #ENTITY_COLLISION_DISABLED
	STA ENTITY_COLLIDED_OBJECTS,X
	LDA @LOCAL03
	INC
	STA @LOCAL03
@LOOP_CHECK:
	CMP #MAX_ENTITIES
	BCC @DISABLE_COLLISION
	LDY #.LOWORD(PSI_TELEPORT_SPEED_Y) + fixed_point::integer
	STY @LOCAL02
	LDA #00
	STA __BSS_START__,Y
	LDX #.LOWORD(PSI_TELEPORT_SPEED_X) + fixed_point::integer
	STX @LOCAL03
	STA __BSS_START__,X
	LOADPTR PSI_TELEPORT_SUCCESS_TICK, @LOCAL00
	LOADPTR UPDATE_PARTY_ENTITY_FROM_BUFFER, @LOCAL01
	LDA #23
	JSL SET_PARTY_TICK_CALLBACKS
	LDX @LOCAL03
	LDA __BSS_START__,X
	STA PSI_TELEPORT_SUCCESS_SCREEN_SPEED_X
	LDA GAME_STATE+game_state::leader_x_coord
	STA PSI_TELEPORT_SUCCESS_SCREEN_X
	LDY @LOCAL02
	LDA __BSS_START__,Y
	STA PSI_TELEPORT_SUCCESS_SCREEN_SPEED_Y
	LDA GAME_STATE+game_state::leader_y_coord
	STA PSI_TELEPORT_SUCCESS_SCREEN_Y
	LDX #4
	LDA #1
	JSL FADE_OUT
	JSR RUN_FRAMES_UNTIL_FADE_DONE
@INSTANT_SKIP:
	END_C_FUNCTION
