
INIT_TELEPORT_DEPARTURE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA PSI_TELEPORT_STYLE
	CMP #TELEPORT_STYLE::INSTANT
	BNE @NOT_INSTANT
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL CENTER_SCREEN
	LDX #1
	TXA
	JSL FADE_IN
	JSR RUN_FRAMES_UNTIL_FADE_DONE
	JMP @DONE
@NOT_INSTANT:
	LDA #0
	STA @VIRTUAL02
	BRA @MEMBER_LOOP_CHECK
@UPDATE_MEMBER:
	LDA @VIRTUAL02
	LDY #.SIZEOF(char_struct)
	JSL MULT168
	TAX
	LDA #.LOWORD(-1)
	STA PARTY_CHARACTERS + char_struct::previous_walking_style,X
	LDA @VIRTUAL02
	CLC
	ADC #24
	TAY
	LDX #0
	STX @LOCAL03
.IF .DEFINED(JPN)
	LDA @VIRTUAL02
	CLC
	ADC #.LOWORD(GAME_STATE)
	TAX
	LDA a:game_state::party_order,X
.ELSE
	LDX @VIRTUAL02
	LDA GAME_STATE + game_state::party_order,X
.ENDIF
	AND #$00FF
	DEC
	LDX @LOCAL03
	JSL UPDATE_PARTY_ENTITY_GRAPHICS
	INC @VIRTUAL02
@MEMBER_LOOP_CHECK:
	LDA @VIRTUAL02
	CMP #6
	BCC @UPDATE_MEMBER
	MOVE_INT_CONSTANT $00080000, PSI_TELEPORT_SPEED
	LDA #6
	STA GAME_STATE+game_state::leader_direction
	LDA #3
	STA PSI_TELEPORT_STATE
	LOADPTR PSI_TELEPORT_DECELERATE_TICK, @LOCAL00
	LOADPTR UPDATE_PARTY_ENTITY_FROM_BUFFER, @LOCAL01
	LDA #23
	JSL SET_PARTY_TICK_CALLBACKS
	JSR SETUP_TELEPORT_ENTITY_FLAGS
	LDA #MUSIC::TELEPORT_IN
	JSL CHANGE_MUSIC
	LDX #0
	STX @LOCAL02
	BRA @WAIT_LOOP_CHECK
@WAIT_FRAME:
	JSL WAIT_UNTIL_NEXT_FRAME
	LDX @LOCAL02
	INX
	STX @LOCAL02
@WAIT_LOOP_CHECK:
	CPX #30
	BCC @WAIT_FRAME
	LDX #4
	LDA #1
	JSL FADE_IN
	BRA @ANIMATE_CHECK
@ANIMATE_FRAME:
	JSL OAM_CLEAR
	JSL RUN_ACTIONSCRIPT_FRAME
	JSL UPDATE_SCREEN
	JSL WAIT_UNTIL_NEXT_FRAME
@ANIMATE_CHECK:
	LDA PSI_TELEPORT_SPEED + fixed_point::integer
	BNE @ANIMATE_FRAME
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL CENTER_SCREEN
@DONE:
	END_C_FUNCTION
