
PSI_TELEPORT_ALPHA_TICK:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #1
	STA GAME_STATE + game_state::leader_moved
	LDA #0
	JSL MAP_INPUT_TO_DIRECTION
	STA @VIRTUAL02
	LDA GAME_STATE+game_state::leader_direction
	STA @LOCAL04
	LDA @VIRTUAL02
	EOR #$0004
	STA @VIRTUAL04
	LDA @LOCAL04
	CMP @VIRTUAL04
	BNE @DIRECTION_NOT_REVERSED
	STA @VIRTUAL02
@DIRECTION_NOT_REVERSED:
	LDA @VIRTUAL02
	CMP #.LOWORD(-1)
	BNE @HAS_INPUT
	LDA GAME_STATE+game_state::leader_direction
	STA @VIRTUAL02
@HAS_INPUT:
	LDA @VIRTUAL02
	STA GAME_STATE+game_state::leader_direction
	LDA BATTLE_SWIRL_COUNTDOWN
	BEQ @NO_BATTLE_SWIRL
	LDA #2
	STA PSI_TELEPORT_STATE
	LDA #1
	STA BATTLE_MODE
@NO_BATTLE_SWIRL:
	LDA @VIRTUAL02
	JSR UPDATE_PSI_TELEPORT_SPEED
	LDA GAME_STATE + game_state::leader_x_frac
	STA @VIRTUAL0A
	LDA GAME_STATE+game_state::leader_x_coord
	STA @VIRTUAL0A+2
	MOVE_INT PSI_TELEPORT_SPEED_X, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, PSI_TELEPORT_NEXT_X
	LDA GAME_STATE + game_state::leader_y_frac
	STA @VIRTUAL0A
	LDA GAME_STATE+game_state::leader_y_coord
	STA @VIRTUAL0A+2
	MOVE_INT PSI_TELEPORT_SPEED_Y, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT @VIRTUAL06, PSI_TELEPORT_NEXT_Y
	LDY GAME_STATE+game_state::current_party_members
	LDX PSI_TELEPORT_NEXT_Y + fixed_point::integer
	LDA PSI_TELEPORT_NEXT_X + fixed_point::integer
	JSL NPC_COLLISION_CHECK
	CMP #.LOWORD(-1)
	BEQ @NO_NPC_COLLISION
	LDA #2
	STA PSI_TELEPORT_STATE
@NO_NPC_COLLISION:
	LDA PSI_TELEPORT_NEXT_Y + fixed_point::integer
	STA @LOCAL00
	LDA @VIRTUAL02
	STA @LOCAL01
	LDY PSI_TELEPORT_NEXT_X + fixed_point::integer
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSR GET_COMBINED_SURFACE_FLAGS
	AND #$00C0
	BEQ @NO_SURFACE_COLLISION
	LDA #2
	STA PSI_TELEPORT_STATE
@NO_SURFACE_COLLISION:
	LDA PSI_TELEPORT_STATE
	CMP #2
	BEQ @UPDATE_CAMERA
	MOVE_INT PSI_TELEPORT_NEXT_X, @VIRTUAL06
	LDA @VIRTUAL06
	STA GAME_STATE + game_state::leader_x_frac
	LDA @VIRTUAL06+2
	STA GAME_STATE+game_state::leader_x_coord
	MOVE_INT PSI_TELEPORT_NEXT_Y, @VIRTUAL06
	LDA @VIRTUAL06
	STA GAME_STATE + game_state::leader_y_frac
	LDA @VIRTUAL06+2
	STA GAME_STATE+game_state::leader_y_coord
@UPDATE_CAMERA:
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL CENTER_SCREEN
	JSR RECORD_PLAYER_POSITION
	JSR SET_TELEPORT_ENTITY_SPEED_VARS
	LDA PSI_TELEPORT_SPEED + fixed_point::integer
	CMP #9
	BLTEQ @RETURN
	LDA #1
	STA PSI_TELEPORT_STATE
@RETURN:
	END_C_FUNCTION
