
PSI_TELEPORT_SUCCESS_TICK:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	STACK_RESERVE_VARS
	END_STACK_VARS
	LDA GAME_STATE+game_state::leader_direction
	JSR UPDATE_PSI_TELEPORT_SPEED
	LDY #.LOWORD(GAME_STATE) + game_state::leader_x_frac
	MOVE_INT PSI_TELEPORT_SPEED_X, @VIRTUAL0A
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDY #.LOWORD(GAME_STATE) + game_state::leader_y_frac
	MOVE_INT PSI_TELEPORT_SPEED_Y, @VIRTUAL0A
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDA PSI_TELEPORT_SUCCESS_SCREEN_X
	CLC
	ADC PSI_TELEPORT_SUCCESS_SCREEN_SPEED_X
	TAY
	STY PSI_TELEPORT_SUCCESS_SCREEN_X
	LDA PSI_TELEPORT_SUCCESS_SCREEN_Y
	CLC
	ADC PSI_TELEPORT_SUCCESS_SCREEN_SPEED_Y
	STA PSI_TELEPORT_SUCCESS_SCREEN_Y
	TAX
	TYA
	JSL CENTER_SCREEN
	JSR RECORD_PLAYER_POSITION
	PLD
	RTL
