
PSI_TELEPORT_DECELERATE_TICK:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	END_STACK_VARS
	LDA GAME_STATE+game_state::leader_direction
	JSR UPDATE_PSI_TELEPORT_SPEED
	LDY #.LOWORD(GAME_STATE) + game_state::leader_x_frac
	MOVE_INT PSI_TELEPORT_SPEED_X, @VIRTUAL0A
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDY #.LOWORD(GAME_STATE) + game_state::leader_y_frac
	MOVE_INT PSI_TELEPORT_SPEED_Y, @VIRTUAL0A
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	CLC
	ADD_INT_ASSIGN @VIRTUAL06, @VIRTUAL0A
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	MOVE_INT_CONSTANT 2, @VIRTUAL0A
	MOVE_INT PSI_TELEPORT_SPEED, @VIRTUAL06
	JSL MULT32
	MOVE_INT @VIRTUAL06, @LOCAL00
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	SEC
	SBC @LOCAL00 + fixed_point::integer
	JSL CENTER_SCREEN
	JSR RECORD_PLAYER_POSITION
	JSR SET_TELEPORT_ENTITY_SPEED_VARS
	END_C_FUNCTION
