
PSI_TELEPORT_BETA_TICK:
	BEGIN_C_FUNCTION_FAR
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #1
	STA GAME_STATE + game_state::leader_moved
	JSR UPDATE_TELEPORT_BETA_INPUT
	LDX PSI_TELEPORT_BETA_PROGRESS
	LDA PSI_TELEPORT_BETA_ANGLE
	JSL CALCULATE_VELOCITY_COMPONENTS
	MOVE_INT @VIRTUAL06, @LOCAL02
	AND #$FF00
	XBA
	BPL @X_SIGN_EXTENDED
	ORA #$FF00
@X_SIGN_EXTENDED:
	CLC
	ADC PSI_TELEPORT_BETA_X_ADJUSTMENT
	TAX
	STX PSI_TELEPORT_NEXT_X + fixed_point::integer
	LDA @LOCAL02
	AND #$FF00
	XBA
	BPL @Y_SIGN_EXTENDED
	ORA #$FF00
@Y_SIGN_EXTENDED:
	CLC
	ADC PSI_TELEPORT_BETA_Y_ADJUSTMENT
	STA @LOCAL03
	STA PSI_TELEPORT_NEXT_Y + fixed_point::integer
	LDA PSI_TELEPORT_STYLE
	CMP #TELEPORT_STYLE::PSI_BETTER
	BEQ @CHECK_STATE
	LDA @LOCAL03
	STA @LOCAL00
	LDA GAME_STATE+game_state::leader_direction
	STA @LOCAL01
	TXY
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSR GET_COMBINED_SURFACE_FLAGS
	AND #$00C0
	BEQ @NO_SURFACE_COLLISION
	LDA #2
	STA PSI_TELEPORT_STATE
@NO_SURFACE_COLLISION:
	LDA BATTLE_SWIRL_COUNTDOWN
	BEQ @NO_BATTLE_SWIRL
	LDA #2
	STA PSI_TELEPORT_STATE
	LDA #1
	STA BATTLE_MODE
@NO_BATTLE_SWIRL:
	LDY GAME_STATE+game_state::current_party_members
	LDX PSI_TELEPORT_NEXT_Y + fixed_point::integer
	LDA PSI_TELEPORT_NEXT_X + fixed_point::integer
	JSL NPC_COLLISION_CHECK
	CMP #.LOWORD(-1)
	BEQ @CHECK_STATE
	LDA #2
	STA PSI_TELEPORT_STATE
@CHECK_STATE:
	LDA PSI_TELEPORT_STATE
	CMP #2
	BEQ @SKIP_POSITION_UPDATE
	LDA PSI_TELEPORT_NEXT_X + fixed_point::integer
	STA GAME_STATE+game_state::leader_x_coord
	LDA PSI_TELEPORT_NEXT_Y + fixed_point::integer
	STA GAME_STATE+game_state::leader_y_coord
@SKIP_POSITION_UPDATE:
	SEP #PROC_FLAGS::INDEX8
	LDY #13
	LDA PSI_TELEPORT_BETA_ANGLE
	JSL ASR8_POSITIVE
	INC
	INC
	AND #$0007
	STA GAME_STATE+game_state::leader_direction
	REP #PROC_FLAGS::INDEX8
	LDY #.LOWORD(PSI_TELEPORT_SPEED)
	MOVE_INT_YPTRSRC __BSS_START__, @VIRTUAL06
	CLC
	LDA @VIRTUAL06 + fixed_point::fraction
	ADC #$1851 ;approx +0.95
	STA @VIRTUAL06 + fixed_point::fraction
	BCC @NO_SPEED_CARRY
	INC @VIRTUAL06 + fixed_point::integer
@NO_SPEED_CARRY:
	MOVE_INT_YPTRDEST @VIRTUAL06, __BSS_START__
	LDA PSI_TELEPORT_STYLE
	CMP #TELEPORT_STYLE::PSI_BETA
	BNE @STYLE_BETTER
	LDA PSI_TELEPORT_BETA_ANGLE
	CLC
	ADC #$0A00
	STA PSI_TELEPORT_BETA_ANGLE
	LDA PSI_TELEPORT_BETA_PROGRESS
	CLC
	ADC #12
	STA PSI_TELEPORT_BETA_PROGRESS
	BRA @UPDATE_CAMERA
@STYLE_BETTER:
	LDA PSI_TELEPORT_BETTER_PROGRESS
	CLC
	ADC #32
	STA PSI_TELEPORT_BETTER_PROGRESS
	CLC
	ADC PSI_TELEPORT_BETA_ANGLE
	STA PSI_TELEPORT_BETA_ANGLE
	LDA PSI_TELEPORT_BETA_PROGRESS
	CLC
	ADC #16
	STA PSI_TELEPORT_BETA_PROGRESS
@UPDATE_CAMERA:
	LDX GAME_STATE+game_state::leader_y_coord
	LDA GAME_STATE+game_state::leader_x_coord
	JSL CENTER_SCREEN
	JSR RECORD_PLAYER_POSITION
	JSR SET_TELEPORT_ENTITY_SPEED_VARS
	LDA PSI_TELEPORT_STYLE
	CMP #TELEPORT_STYLE::PSI_BETA
	BNE @CHECK_BETTER_DONE
	LDA PSI_TELEPORT_BETA_PROGRESS
	CMP #$1000
	BLTEQ @DONE
	LDA #1
	STA PSI_TELEPORT_STATE
	JSR SET_TELEPORT_VELOCITY_BY_DIRECTION
	BRA @DONE
@CHECK_BETTER_DONE:
	LDA PSI_TELEPORT_BETTER_PROGRESS
	CMP #$1800
	BLTEQ @DONE
	LDA #1
	STA PSI_TELEPORT_STATE
	JSR SET_TELEPORT_VELOCITY_BY_DIRECTION
@DONE:
	END_C_FUNCTION
