
RESET_ENTITIES_AFTER_TELEPORT:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #.LOWORD(PARTY_CHARACTERS)
	STA CURRENT_PARTY_MEMBER_TICK
	LDY #24
	BRA @LOOP_CHECK
@LOOP_BODY:
	TYA
	ASL
	STA @LOCAL00
	TAX
	LDA #8
	STA ENTITY_SCRIPT_VAR3_TABLE,X
	LDA @LOCAL00
	CLC
	ADC #.LOWORD(ENTITY_SCRIPT_VAR7_TABLE)
	TAX
	LDA __BSS_START__,X
	AND #$FFFF ^ SPRITE_TABLE_10_FLAGS::TELEPORTING
	STA __BSS_START__,X
	LDA @LOCAL00
	CLC
	ADC #.LOWORD(ENTITY_COLLIDED_OBJECTS)
	TAX
	LDA __BSS_START__,X
	AND #$7FFF
	STA __BSS_START__,X
	LDA #.LOWORD(-1)
	LDX CURRENT_PARTY_MEMBER_TICK
	STA a:char_struct::previous_walking_style,X
	LDA CURRENT_PARTY_MEMBER_TICK
	CLC
	ADC #.SIZEOF(char_struct)
	STA CURRENT_PARTY_MEMBER_TICK
	INY
@LOOP_CHECK:
	CPY #MAX_ENTITIES
	BCC @LOOP_BODY
	JSL CHANGE_MUSIC_5DD6
	END_C_FUNCTION
