
RUN_TELEPORT_FAILURE_SEQUENCE:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA #1
	STA DISABLED_TRANSITIONS
	LDA #MUSIC::TELEPORT_FAIL
	JSL CHANGE_MUSIC
	LDA #PARTY_LEADER_ENTITY_INDEX
	STA @LOCAL02
	BRA @FLAG_ENTITY_CHECK
@FLAG_ENTITY_LOOP:
	ASL
	CLC
	ADC #.LOWORD(ENTITY_SCRIPT_VAR7_TABLE)
	TAX
	LDA __BSS_START__,X
	ORA #SPRITE_TABLE_10_FLAGS::WALKING_STYLE_CHANGED
	STA __BSS_START__,X
	LDA @LOCAL02
	INC
	STA @LOCAL02
@FLAG_ENTITY_CHECK:
	CMP #MAX_ENTITIES
	BCC @FLAG_ENTITY_LOOP
	LOADPTR TICK_CALLBACK_NOP, @LOCAL00
	LOADPTR UPDATE_ENTITY_SURFACE_AND_GRAPHICS, @LOCAL01
	LDA #23
	JSL SET_PARTY_TICK_CALLBACKS
	SEP #PROC_FLAGS::ACCUM8
	LDA #1
	STA GAME_STATE + game_state::party_status
	LDX #0
	STX @LOCAL02
	BRA @WAIT_LOOP_CHECK
@WAIT_LOOP:
	JSL OAM_CLEAR
	JSL RUN_ACTIONSCRIPT_FRAME
	JSL UPDATE_SCREEN
	JSL WAIT_UNTIL_NEXT_FRAME
	LDX @LOCAL02
	INX
	STX @LOCAL02
@WAIT_LOOP_CHECK:
	CPX #180
	BCC @WAIT_LOOP
	SEP #PROC_FLAGS::ACCUM8
	STZ GAME_STATE + game_state::party_status
	REP #PROC_FLAGS::ACCUM8
	STZ DISABLED_TRANSITIONS
	END_C_FUNCTION
