
SET_TELEPORT_VELOCITY_BY_DIRECTION:
	REP #PROC_FLAGS::ACCUM8 | PROC_FLAGS::INDEX8 | PROC_FLAGS::CARRY
	LDX #.LOWORD(PSI_TELEPORT_SPEED_Y) + fixed_point::integer
	LDA #$0000
	STA __BSS_START__,X
	LDY #.LOWORD(PSI_TELEPORT_SPEED_X) + fixed_point::integer
	STA __BSS_START__,Y
	LDA GAME_STATE+game_state::leader_direction
	BEQ @DIR_UP
	CMP #$0001
	BEQ @DIR_UP_RIGHT
	CMP #$0002
	BEQ @DIR_RIGHT
	CMP #$0003
	BEQ @DIR_DOWN_RIGHT
	CMP #$0004
	BEQ @DIR_DOWN
	CMP #$0005
	BEQ @DIR_DOWN_LEFT
	CMP #$0006
	BEQ @DIR_LEFT
	CMP #$0007
	BEQ @DIR_UP_LEFT
	BRA @DONE
@DIR_UP:
	LDA #$FFFB
	STA __BSS_START__,X
	BRA @DONE
@DIR_UP_RIGHT:
	LDA #$FFFB
	STA __BSS_START__,X
	LDA #$0005
	STA __BSS_START__,Y
	BRA @DONE
@DIR_RIGHT:
	LDA #$0005
	STA __BSS_START__,Y
	BRA @DONE
@DIR_DOWN_RIGHT:
	LDA #$0005
	STA __BSS_START__,X
	STA __BSS_START__,Y
	BRA @DONE
@DIR_DOWN:
	LDA #$0005
	STA __BSS_START__,X
	BRA @DONE
@DIR_DOWN_LEFT:
	LDA #$0005
	STA __BSS_START__,X
	LDA #$FFFB
	STA __BSS_START__,Y
	BRA @DONE
@DIR_LEFT:
	LDA #$FFFB
	STA __BSS_START__,Y
	BRA @DONE
@DIR_UP_LEFT:
	LDA #$FFFB
	STA __BSS_START__,Y
	STA __BSS_START__,X
@DONE:
	RTS
