
SETUP_TELEPORT_ENTITY_FLAGS:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDY #24
	BRA @LOOP_CHECK
@LOOP_BODY:
	TYA
	ASL
	STA @LOCAL00
	TAX
	LDA #8
	STA ENTITY_SCRIPT_VAR3_TABLE,X
	LDA @LOCAL00
	CLC
	ADC #.LOWORD(ENTITY_SCRIPT_VAR7_TABLE)
	TAX
	LDA __BSS_START__,X
	ORA #SPRITE_TABLE_10_FLAGS::TELEPORTING
	STA __BSS_START__,X
	INY
@LOOP_CHECK:
	CPY #MAX_ENTITIES
	BCC @LOOP_BODY
	END_C_FUNCTION
