
UPDATE_TELEPORT_PARTY_VISIBILITY:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @VIRTUAL02
	TXY
	TXA
	INC
	AND #$00FF
	STA @LOCAL01
	LDA @VIRTUAL02
	STA @VIRTUAL04
	INC @VIRTUAL04
	LDA GAME_STATE + game_state::party_order
	AND #$00FF
	CMP @VIRTUAL04
	BNE @CHECK_SPEED
	LDA @LOCAL01
	BRA @DONE
@CHECK_SPEED:
	LDA PSI_TELEPORT_SPEED + fixed_point::integer
	BNE @ADJUST_VISIBILITY
	TYA
	BRA @DONE
@ADJUST_VISIBILITY:
	LDA #2
	STA @LOCAL00
	LDX #6
	LDA @VIRTUAL02
	JSL ADJUST_PARTY_MEMBER_VISIBILITY
@DONE:
	END_C_FUNCTION
