
UPDATE_TELEPORT_BETA_INPUT:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT16
	END_STACK_VARS
	LDA PSI_TELEPORT_STYLE
	CMP #TELEPORT_STYLE::PSI_BETTER
	BEQ @DONE
	LDA PAD_STATE
	STA @LOCAL00
	AND #PAD::UP
	BEQ @CHECK_DOWN
	DEC PSI_TELEPORT_BETA_Y_ADJUSTMENT
@CHECK_DOWN:
	LDA @LOCAL00
	AND #PAD::DOWN
	BEQ @CHECK_LEFT
	INC PSI_TELEPORT_BETA_Y_ADJUSTMENT
@CHECK_LEFT:
	LDA @LOCAL00
	AND #PAD::LEFT
	BEQ @CHECK_RIGHT
	DEC PSI_TELEPORT_BETA_X_ADJUSTMENT
@CHECK_RIGHT:
	LDA @LOCAL00
	AND #PAD::RIGHT
	BEQ @DONE
	INC PSI_TELEPORT_BETA_X_ADJUSTMENT
@DONE:
	END_C_FUNCTION
