
UPDATE_PSI_TELEPORT_SPEED:
	BEGIN_C_FUNCTION
	STACK_RESERVE_VARS
	STACK_RESERVE_INT32
	STACK_RESERVE_INT16
	STACK_RESERVE_PARAM_INT16
	END_STACK_VARS
	STA @LOCAL01
	LDA PSI_TELEPORT_STATE
	CMP #1
	BEQ @STATE_ACCELERATING
	CMP #3
	BEQ @STATE_DECELERATING
	JMP @STATE_SPINNING
@STATE_ACCELERATING:
	LDA GAME_STATE + game_state::character_mode
	CMP #3
	BNE @NORMAL_ACCEL
	MOVE_INT PSI_TELEPORT_SPEED, @VIRTUAL06
	CLC
	LDA @VIRTUAL06
	ADC #$051E
	STA @VIRTUAL06
	BCC @SMALL_ACCEL_NO_CARRY
	INC @VIRTUAL06+2
@SMALL_ACCEL_NO_CARRY:
	MOVE_INT @VIRTUAL06, @LOCAL00
	JMP @APPLY_SPEED
@NORMAL_ACCEL:
	MOVE_INT PSI_TELEPORT_SPEED, @VIRTUAL06
	CLC
	LDA @VIRTUAL06
	ADC #$3333
	STA @VIRTUAL06
	BCC @NORMAL_ACCEL_NO_CARRY
	INC @VIRTUAL06+2
@NORMAL_ACCEL_NO_CARRY:
	MOVE_INT @VIRTUAL06, @LOCAL00
	JMP @APPLY_SPEED
@STATE_DECELERATING:
	LDA GAME_STATE + game_state::character_mode
	CMP #3
	BNE @NORMAL_DECEL
	MOVE_INT PSI_TELEPORT_SPEED, @VIRTUAL06
	SEC
	LDA @VIRTUAL06
	SBC #$1999
	STA @VIRTUAL06
	BCS @SMALL_DECEL_NO_BORROW
	DEC @VIRTUAL06+2
@SMALL_DECEL_NO_BORROW:
	MOVE_INT @VIRTUAL06, @LOCAL00
	BRA @APPLY_SPEED
@NORMAL_DECEL:
	MOVE_INT PSI_TELEPORT_SPEED, @VIRTUAL06
	SEC
	LDA @VIRTUAL06
	SBC #$1999
	STA @VIRTUAL06
	BCS @NORMAL_DECEL_NO_BORROW
	DEC @VIRTUAL06+2
@NORMAL_DECEL_NO_BORROW:
	MOVE_INT @VIRTUAL06, @LOCAL00
	BRA @APPLY_SPEED
@STATE_SPINNING:
	LDA GAME_STATE + game_state::character_mode
	CMP #3
	BNE @NORMAL_SPIN
	MOVE_INT PSI_TELEPORT_SPEED, @VIRTUAL06
	CLC
	LDA @VIRTUAL06
	ADC #$29FB
	STA @VIRTUAL06
	BCC @SMALL_SPIN_NO_CARRY
	INC @VIRTUAL06+2
@SMALL_SPIN_NO_CARRY:
	MOVE_INT @VIRTUAL06, @LOCAL00
	BRA @APPLY_SPEED
@NORMAL_SPIN:
	MOVE_INT PSI_TELEPORT_SPEED, @VIRTUAL06
	CLC
	LDA @VIRTUAL06
	ADC #$1851
	STA @VIRTUAL06
	BCC @NORMAL_SPIN_NO_CARRY
	INC @VIRTUAL06+2
@NORMAL_SPIN_NO_CARRY:
	MOVE_INT @VIRTUAL06, @LOCAL00
@APPLY_SPEED:
	MOVE_INT @LOCAL00, @VIRTUAL06
	MOVE_INT @VIRTUAL06, PSI_TELEPORT_SPEED
	LDA @LOCAL01
	AND #$0001
	BEQ @CARDINAL_DIRECTION
	MOVE_INT @LOCAL00, @VIRTUAL06
	ASR8_INT @VIRTUAL06
	MOVE_INT_CONSTANT $B505, @VIRTUAL0A
	JSL MULT32
	ASR8_INT @VIRTUAL06
	MOVE_INT @VIRTUAL06, PSI_TELEPORT_SPEED_X
	MOVE_INT @VIRTUAL06, PSI_TELEPORT_SPEED_Y
	BRA @APPLY_DIRECTION
@CARDINAL_DIRECTION:
	MOVE_INT @LOCAL00, @VIRTUAL06
	MOVE_INT @VIRTUAL06, PSI_TELEPORT_SPEED_Y
	MOVE_INT @VIRTUAL06, PSI_TELEPORT_SPEED_X
@APPLY_DIRECTION:
	LDA @LOCAL01
	BEQ @DIR_UP
	CMP #4
	BEQ @DIR_DOWN
	CMP #6
	BEQ @DIR_LEFT
	CMP #2
	BEQ @DIR_RIGHT
	CMP #1
	BEQ @DIR_UP_RIGHT
	CMP #7
	BEQL @DIR_UP_LEFT
	CMP #5
	BEQL @DIR_DOWN_LEFT
	JMP @DONE
@DIR_UP:
	MOVE_INT PSI_TELEPORT_SPEED_Y, @VIRTUAL06
	SEC
	NEGATE_INT_ASSIGN @VIRTUAL06
	MOVE_INT @VIRTUAL06, PSI_TELEPORT_SPEED_Y
@DIR_DOWN:
	MOVE_INT_CONSTANT NULL, PSI_TELEPORT_SPEED_X
	JMP @DONE
@DIR_LEFT:
	MOVE_INT PSI_TELEPORT_SPEED_X, @VIRTUAL06
	SEC
	NEGATE_INT_ASSIGN @VIRTUAL06
	MOVE_INT @VIRTUAL06, PSI_TELEPORT_SPEED_X
@DIR_RIGHT:
	MOVE_INT_CONSTANT NULL, PSI_TELEPORT_SPEED_Y
	BRA @DONE
@DIR_UP_RIGHT:
	MOVE_INT PSI_TELEPORT_SPEED_Y, @VIRTUAL06
	SEC
	NEGATE_INT_ASSIGN @VIRTUAL06
	MOVE_INT @VIRTUAL06, PSI_TELEPORT_SPEED_Y
	BRA @DONE
@DIR_UP_LEFT:
	MOVE_INT PSI_TELEPORT_SPEED_Y, @VIRTUAL06
	SEC
	NEGATE_INT_ASSIGN @VIRTUAL06
	MOVE_INT @VIRTUAL06, PSI_TELEPORT_SPEED_Y
@DIR_DOWN_LEFT:
	MOVE_INT PSI_TELEPORT_SPEED_X, @VIRTUAL06
	SEC
	NEGATE_INT_ASSIGN @VIRTUAL06
	MOVE_INT @VIRTUAL06, PSI_TELEPORT_SPEED_X
@DONE:
	END_C_FUNCTION
